### PR TITLE
Add Google Sheets

### LINKED ISSUE #2207: Add Google sheets icon
**Name:** Google Sheets
**Website:** https://www.google.com/sheets/about/
**Official resources for icon and color:** Similar to google Colab ? https://colab.research.google.com/assets/colab-badge.svg

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
image

**Issue:** Closes #2207

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by runxel** [comment]
Why not this logo?

sheets

**Comment by PeterShaggyNoble** [comment]
@runxel, see my comments on the boxed version in #2207 - to me, the square version are the icons and the page versions are the logos and, as we're an icon library, I went for the former, which have the added advantage of already being monochrome.

**Comment by ericcornelissen** [comment]
> Why not this logo?
>
> sheets

I would also expect that logo 🤔 


> as we're an icon library

We may be an icon logo, but I would say what we provide is logos.

**Comment by PeterShaggyNoble** [comment]
@runxel & @ericcornelissen, does this treatment look OK to you?

Google Sheets

**Comment by ericcornelissen** [comment]
> does this treatment look OK to you?

Looks good to me, it is a bit of an artistic impression but I definitely prefer it over the original version you included.

**Comment by PeterShaggyNoble** [comment]
PR updated.
> it is a bit of an artistic impression

Which is why I was truing to avoid using it! 😆

For consistency, we'll need to ensure that any future Google Drive/Docs icons use the same cutout in the corner.

**Comment by runxel** [comment]
Took the liberty to run svgo on it.
I'm happy with your result, Peter! :)

**Pull request merged**
