### PR TITLE
Add Airbyte icon

### PR DESCRIPTION
**Pull request by nialloriordan**
**Issue:** closes https://github.com/simple-icons/simple-icons/issues/7537

**Similarweb rank:** [205,005](https://www.similarweb.com/website/airbyte.com/#overview)

  
[7.1k Github stars](https://github.com/airbytehq/airbyte/stargazers)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Got hex value from original svg fill value

#### Preview
airbyte

### CODE REVIEW

**Comment by nialloriordan** [comment]
Can someone help resize the logo I keep getting the following error when linting:

> icon-centered <path> must be centered at (12, 12); the center is currently (11.947, 12)

**Comment by nialloriordan** [comment]
> Can someone help resize the logo I keep getting the following error when linting:
> 
> > icon-centered  must be centered at (12, 12); the center is currently (11.947, 12)

Fixed the issue using boxy-svg

**Review by sachinraja — CHANGES_REQUESTED** [review]
Some differences:
image
white is original, red is yours

**Comment by nialloriordan** [comment]
> Some differences: image white is original, red is yours

@sachinraja Do you have any advice on how to reproduce the above diagram so I can compare any changes I make? I have tried the following steps, but I keep getting the same results
- Copy element from https://airbyte.com/
- Import element directly to Boxy SVG via "New from Clipboard"
- Extract icon using Boxy SVG:
    - Change the icon's viewbox/canvas/page size to 24x24.
    - Scale the icon to fit the viewbox, while preserving the icon's original proportions. This means the icon should be touching at least two sides of the viewbox.
    - Center the icon horizontally and vertically.
    - Remove all colors. The icon should be monochromatic.
    - Export the icon as an SVG.
- Optimise the icon via `npm run svgo -- icons/airbyte.svg`
- Annotate and name the icon

**Review by sachinraja — APPROVED** [review]
Thanks for fixing it!

**Pull request merged**
