### PR TITLE
Add cPanel

### LINKED ISSUE #2152: cPanel (web application control panel)
**Name:** cPanel
**Website:** https://cpanel.net/
**Official resources for icon and color:**  https://cpanel.net/company/cpanel-brand-guide/ (arguably, the wordmark is more recognizable)
  

Alexa ranking: [~5.8k](https://www.alexa.com/siteinfo/cpanel.net)

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
cPanel

**Issue:** Closes #2152

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Should we include the `TM`?

Rejected alternative treatment:
cPanel

### CODE REVIEW

**Comment by birjolaxew** [comment]
Agree with @foo-dogsquared. Although it would make more sense to use the "cP" logomark, they explicitly say not to. Everything else looks good.

**Comment by PeterShaggyNoble** [comment]
Thanks, @foo-dogsquared & @birjolaxew; I'll get this updated in a while.

**Comment by PeterShaggyNoble** [comment]
Updated to use the full wordmark.

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @PeterShaggyNoble 👍

**Pull request merged**
