### PR TITLE
Add RethinkDB

### PR DESCRIPTION
**Pull request by mhf-ir**
**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Alexa rank is about [220K](https://www.alexa.com/siteinfo/rethinkdb.com)

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
@mhf-ir, what's the relationship between the repo you provided as the source URL and RethinkDB? I don't see that icon used anywhere on their website, nor can it be [found in their own GH org](https://github.com/search?l=SVG&p=7&q=org%3Arethinkdb+svg&type=Code) and Wikimedia [returns no files when searching for `RethinkDB`](https://commons.wikimedia.org/w/index.php?search="RethinkDB").

**Comment by mhf-ir** [comment]
You mean that Ghost? It's official rethink db symbolic icon.
Amazon use it:
https://aws.amazon.com/marketplace/pp/RethinkDB-RethinkDB/B013R60Q8Y
And rethinkdb blog:
https://rethinkdb.com/blog

That repo i mention it for CNCF.
Most important organization that hold for best cloud native applications and stuff.
https://landscape.cncf.io/

Screenshot from 2020-01-21 19-42-55

**Comment by runxel** [comment]
But where did you actually got your vector version from?
I also can't see how the cncf thing relates to rethinkdb.... 🤔

**Comment by mhf-ir** [comment]
CNCF is show techs supporter by this community and rethinkdb is one of them.
ICON came from : https://github.com/cncf/landscape/blob/master/hosted_logos/rethinkdb.svg
It's official CNCF and use all logo from official ones to repository that represent mark of technology.

**Comment by PeterShaggyNoble** [comment]
@mhf-ir, see the ongoing discussion in #2363.

From everything I can see (website, Twitter, GitHub, etc.) of these guys, I would expect their icon to be just the `R` from their logo.

**Comment by PeterShaggyNoble** [comment]
Closing as abandoned due to [this comment](https://github.com/simple-icons/simple-icons/pull/2402#issuecomment-579852495). If anyone else would like to take this on, please feel free to open a new PR or issue.

**Pull request closed without merging**
