### PR TITLE
Update C#

### PR DESCRIPTION
**Pull request by adamalston**
csharp

**Issue:** #3314 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I used the C# hex that was already on file as I could not find another definitive color. If someone could specify a hex, i could easily change it.

### CODE REVIEW

**Comment by adamalston** [comment]
I do not know why the build is failing. This PR is the first time I have ever run into issues with the build. 

My first instinct is the renaming of the icon `C Sharp icon` to `C# icon` (as was laid out in the issue above). Other than that, some insight from others would be welcome.

**Comment by adamalston** [comment]
Is there anyway you could help me with this icon @NovaGL. You seem really good at these things.

In my commit above I pushed 
```html
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>C# icon</title><path d="M23.71 6a2.28 2.28 0 00-.87-.75L13.25.33a2.63 2.63 0 00-2.55 0c-1.27.68-7.64 3.94-9.57 4.92A2 2 0 000 7.08V17a2.09 2.09 0 00.28 1 2.2 2.2 0 00.88.77c1.9 1 8.27 4.23 9.54 4.9a2.58 2.58 0 002.55 0l9.59-4.92a2.2 2.2 0 00.88-.75 2 2 0 00.28-1V7.08A2.11 2.11 0 0023.71 6zM12 19.13C7.59 19.13 4 16 4 12s3.57-7.11 8-7.11a8.19 8.19 0 016.89 3.59l-3.47 1.77A4.24 4.24 0 0010 9a3.48 3.48 0 00-2 3 3.78 3.78 0 004 3.57 4.08 4.08 0 003.46-1.8l3.46 1.78A8.17 8.17 0 0112 19.13zm9.37-7.51h-.65v.84h.65v.71h-.65v.57h-.79v-.57H19v.57h-.78v-.57h-.63v-.71h.63v-.84h-.63v-.72h.63v-.57H19v.57h1v-.57h.79v.57h.61z M19.05 11.61h.85v.85h-.85z"/></svg>
```

The build error that I am getting is
```
x icon-centered <path> must be centered at (12, 12); the center is currently (12, 12.01)
```

Setting my viewbox to 0, 0, 24, 24 in theory should have set the center of the element to 12, 12 so I dont know why I am getting this error. Do you have any suggestions?

**Comment by NovaGL** [comment]
Hi @adamalston 

When I open this in Inkscape it shows the height as 24.007, this would cause the centering to be off.

Try opening it in Inkscape before SVGOMG to make sure that the dimensions are less than the 24 viewbox. If you are sure its correct try increasing the precision in SVGOMG

**Comment by adamalston** [comment]
Noted, I opened this PR in response to #3314 as it seemed that others were trying to reach parity between the C++ and C# icons. 

If this icon does not in fact need updating, I would be fine with someone closing this PR.

**Comment by NovaGL** [comment]
It's failing because you named your file csharp but the json says c# you need to be consistent.

It's also failing due to the fact the HEX is in lower case. It's expected to be uppercase.

I'll let the @simple-icons/maintainers chime in if this is the right approach for the logos. 

Unfortunately there is no official logo so we need to have a consensus on what the right approach is.

**Comment by NovaGL** [comment]
The logo can't have a hash in the name as mentioned in the guidelines so it should be chash.svg (I believe)

If you are replacing the csharp.svg that logo should be removed.

**Pull request closed without merging**
