### PR TITLE
Updated Stitcher icon

### PR DESCRIPTION
**Pull request by NovaGL**
stitcher

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json` (N\A)
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
Logo is very simple so created it manually, if you prefer we can use the word with the name in it but the apps don't have it that way.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one on, @NovaGL.

You icon, however, isn't quite centred on the canvas. Also, using the [app](https://play.google.com/store/apps/details?id=com.stitcher.app) icon as the source ans tracing over it myself, I notice a couple of minor differences to your version (in red below). Although, as both my manual vertorisation and raster/vector comparison skills suck, I'd like a second opinion from one of the other @simple-icons/maintainers before asking you to take any changes.

If you based your icon on the app icon, then we should probably update the source URL, too. If you used a different icon, though, let us know.

**Comment by NovaGL** [comment]
@PeterShaggyNoble Happy to take any action required.

However I have redone the logo based on the official source. I removed the word stitcher and filled in the blank space. Let me know if that is any better.

I think we use use the SVG as source material as using raster is prone to problems.

Let me know if you want me to change the source to the following:
https://partners.stitcher.com/img/onboarding/StitcherLogoWhite.svg

**Comment by PeterShaggyNoble** [comment]
> However I have redone the logo based on the official source. I removed the word stitcher and filled in the blank space.

Ah, good thinking :+1: I'm happy to run with that option. There are, however, a couple of hairline differences between yours and the original (see screenshot below of top-left corner of second bar) plus quite a significant difference at the bottom of the second bar (second screenshot below).

If it's any help, here's a step-by-step of how I'd recreate the icon in Inkscape, after removing the wordmark.
1. Convert all the rectangles to paths,
2. Select all the paths and drag the bottom nodes of the top ones down to touch the node opposite them in the bottom ones (third screenshot below) - Inkscape, by default, will "snap" them together when they get close but you may need to enable this option in your sortware, or,
3. Alternatively, select the top and bottom rectangle for each bar, take note of the total height, increase the height of the top path to that and delete the bottom path.
4. Combine all paths together. If you followed step 2 above, make sure to merge them, rather than compound them, to avoid the lines running across each bar. If you're using Inkscape, they call the merge command "Union".

> Let me know if you want me to change the source

I'd suggest going with the page you found that version of the logo on. Unless it's "hidden" begind the login at https://partners.stitcher.com/, in which case I think the direct URL to the SVG is fine.

**Comment by ericcornelissen** [comment]
From a quick comparison with [the original SVG](https://partners.stitcher.com/img/onboarding/StitcherLogoWhite.svg) (just removing "stitcher") it still seems there are some small differences. In particular on the right sides of the first, third, and fifth rectangle. This could very well be the result of optimizing...

**FULL**:
image

**FIRST RECTANGLE**:
image

**Comment by PeterShaggyNoble** [comment]
Don't forget about this one, @NovaGL 😉

**Comment by NovaGL** [comment]
Hi @PeterShaggyNoble 

Hopefully this should be ok, increased precision to 4. I think that's the part that always stuffs things up.

**Comment by PeterShaggyNoble** [comment]
Still seeing a couple of hairline differences around the edges, unfortunately, @NovaGL.

Here's what I came up with after trying it myself, if it helps:
```
M19.59 8.516H24v6.928h-4.41zM0 8.854h4.41v7.803H0zm4.914-1.328h4.388v8.572H4.914zm4.892.725h4.388v8.81H9.806zm4.892-1.312h4.388v9.158h-4.388Z
```

**Review by mondeja — CHANGES_REQUESTED** [review]
Although the difference is minimal, I think that @PeterShaggyNoble has offered a bit better version in this case. Just to make sure that this update it is not forgotten, I think the correct thing in this case is to use the path provided by @PeterShaggyNoble and coauthor the pull together. I can create the commit and do the merge myself, defining both as coauthors. What do you think @NovaGL?

**Comment by NovaGL** [comment]
I'm happy with whatever you suggest. Just a bit busy atm so go ahead and modify any of my PRs so that they are appropriate.

**Review by mondeja — APPROVED** [review]
Thank you for the permission @NovaGL :100:

**Pull request merged**
