### PR TITLE
Add HTTPie icon

### PR DESCRIPTION
**Pull request by zrfisaac**
httpie

**Issue:** #7329

**Similarweb rank:** [429,201](https://www.similarweb.com/website/httpie.io/#overview)

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
As easy as /aitch-tee-tee-pie/ 🥧 Modern, user-friendly command-line HTTP client for the API era. JSON support, colors, sessions, downloads, plugins & more.

### CODE REVIEW

**Comment by sisp** [comment]
A couple of remarks:

- The official HTTPie logo consists of an _icon_ and a _wordmark_. For Simple Icons, we should use only the _icon_.
- The Similarweb rank is not 72, that's github.com's rank. The Similiarweb rank for httpie.io is [429,201](https://www.similarweb.com/website/httpie.io/#overview). However, for HTTPie the number of GitHub stars is the more relevant popularity metric. Today, HTTPie has 15.9k stars. Note that HTTPie had 54k GitHub stars until recently, [lost many of them by accident](https://github.com/httpie/httpie#we-lost-54k-github-stars), and is currently recovering.
- The source URL should be a permanent link (see [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/master/CONTRIBUTING.md#source-guidelines)):

  > In any case, the commit hash should be part of the URL. On GitHub, you can get the correct URL by pressing `y` on the GitHub page you want to link to.

  With the latest commit hash at the time of this writing, it is https://github.com/httpie/httpie/blob/d262181bede5241a6b692c3245a77e2eb02bc262/docs/httpie-logo.svg.

- Although the official SVG logo uses the fill color `#4B78E6`, the website seems to use `#73DC8C` as the primary/brand color (also according to CSS class names). In my opinion, the hex value should be this shade of green. But since there's inconsistency, a second opinion would be great.

**Review by sisp — CHANGES_REQUESTED** [review]
A couple of remarks:

- The official HTTPie logo consists of an _icon_ and a _wordmark_. For Simple Icons, we should use only the _icon_.
- The Similarweb rank is not 72, that's github.com's rank. The Similiarweb rank for httpie.io is [429,201](https://www.similarweb.com/website/httpie.io/#overview). However, for HTTPie the number of GitHub stars is the more relevant popularity metric. At the time of this writing, HTTPie has 17.7k stars. Note that HTTPie had 54k GitHub stars until recently, [lost many of them by accident](https://github.com/httpie/httpie#we-lost-54k-github-stars), and is currently recovering.
- The source URL should be a permanent link (see [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/master/CONTRIBUTING.md#source-guidelines)):

  > In any case, the commit hash should be part of the URL. On GitHub, you can get the correct URL by pressing `y` on the GitHub page you want to link to.

  With the latest commit hash at the time of this writing, it is https://github.com/httpie/httpie/blob/d262181bede5241a6b692c3245a77e2eb02bc262/docs/httpie-logo.svg.

- Although the official SVG logo uses the fill color `#4B78E6`, the website seems to use `#73DC8C` as the primary/brand color (also according to CSS class names). In my opinion, the hex value should be this shade of green. But since there's inconsistency, a second opinion would be great.

**Comment by sachinraja** [comment]
I agree with everything @sisp noted

**Comment by zrfisaac** [comment]
Ok! Thanks for the advice, I will correct and post my changes soon. 🙌

**Comment by zrfisaac** [comment]
@sisp Thanks for the advice, I've made everything that you have said.

**Review by sisp — APPROVED** [review]
Thanks for making the changes!

httpie-diff

LGTM! :tada: This PR can be merged now IMO, @sachinraja.

**Comment by sachinraja** [comment]
Thanks for reviewing @sisp!

**Pull request merged**
