### PR TITLE
Add Sky Bet Logo

### LINKED ISSUE #10479: Request: Sky Bet
### Brand Name

Sky Bet

### Website

https://m.skybet.com/

### Popularity Metric

The similarweb rank is: 3,039. See https://www.similarweb.com/website/skybet.com

### Official Resources for Icon and Color

Skybet https://bet.sbgcdn.com/static/mbet/img/content/logos/skybet-rebrand.png

### Additional Comments

The favicon is also used occasionally: https://bet.sbgcdn.com/static/mbet/img/favicon.png

### PR DESCRIPTION
**Pull request by performant23**
**Issue:** closes #10479

**Similarweb rank:** 3039

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Used Inkscape to work on the logo taken from Wikipedia (https://en.wikipedia.org/wiki/File:Sky_Bet.svg).

### CODE REVIEW

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
Thanks for the contribution, @performant23. However, that's an old logo of theirs you've used for your icon. There's a link to an SVG of their current logo in my comment on the linked issue; could you update to use that instead, please?

**Comment by performant23** [comment]
Hey, @PeterShaggyNoble , thanks for the feedback. I'll make the changes accordingly!

**Comment by performant23** [comment]
@PeterShaggyNoble , So the problem I'm facing is that the viewbox isn't getting synchronized due to the aspect ratio of the image. So it is around 0 0 406 120 (scalable)

**Comment by AlexeiBlue** [comment]
Hey sorry I didn't get back to you, I'll have a read through the contributor guide at some point and see if I can figure something out.  Never used any of the tools mentioned there before but will give it a go

**Pull request closed without merging**
