### PR TITLE
Add BeReal icon

### PR DESCRIPTION
**Pull request by RostiMelk**
### Preview
bereal

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The logo was fetched from the official website, more specifically: https://bereal.com/bereal-logo.svg, note that the SVG is white in this url.

### CODE REVIEW

**Comment by adamrusted** [comment]
There is an SVG available on [their website](https://bereal.com/en) which we should probably use, given it's an official resource.

**Comment by adamrusted** [comment]
@simple-icons/icon-review - I've updated this one to match the favicon on the website.

**Comment by PratyushJayachandran** [comment]
> @simple-icons/icon-review - I've updated this one to match the favicon on the website.

I cannot find the SVG you contributed on their website. It says `BeReal.` in full instead of `B.`

**Comment by RostiMelk** [comment]
Updated to use the logo from the official website, and now the full wordmark, spelled "BeReal."

**Comment by PratyushJayachandran** [comment]
> Updated to use the logo from the official website, and now the full wordmark, spelled "BeReal."

Icon is failing linter as it is not centered properly. Can you try again to make the icon center at 12,12px.

**Comment by RostiMelk** [comment]
@PratyushJayachandran Good to go 👍

**Review by PratyushJayachandran — APPROVED** [review]
Looks good @RostiMelk and thank you for updating the PR previously @adamrusted 🎉

**Pull request merged**
