### PR TITLE
Add Scalar icon

### LINKED ISSUE #12311: Request: Scalar
### Brand Name

Scalar

### Website

https://scalar.com/

### Popularity Metric

The Similarweb rank is 601,058. See https://www.similarweb.com/website/scalar.com

### Official Resources for Icon and Color

- SVG: https://scalar.com/favicon.svg
- Color: #E7E7E7

### Additional Comments

This tool is one of the best alternatives for the Swashbuckle library for .NET, announced for discontinuation in .NET 9.
Source: https://github.com/dotnet/aspnetcore/issues/54599

### PR DESCRIPTION
**Pull request by antlio**
image

Closes #12311 

**Popularity metric:**

- [GitHub stars](https://github.com/scalar/scalar): 7.8k
- [Star history](https://star-history.com/#scalar/scalar&Date): Upward

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by antlio** [comment]
fixed the svg file + rebased. tysm for that project!

**Comment by adamrusted** [comment]
Hey @antlio - think the linter is complaining about the space between `"` and `/>` in the path. If you remove that, it should pass.

**Comment by antlio** [comment]
> Hey @antlio - think the linter is complaining about the space between `"` and `/>` in the path. If you remove that, it should pass.

thank you @adamrusted, my bad i should have run the lint again! got that whitespace out 👍

**Review by adamrusted — APPROVED** [review]
Perfect match, thanks @antlio!

**Pull request merged**
