### PR TITLE
Added Chai

### LINKED ISSUE #4983: Chaijs Icon
**Brand Name:** Chai (or Chaijs, not sure which is more "official" for branding)
**Website:** https://www.chaijs.com/  (also https://github.com/chaijs/chai)
**Alexa rank:** 192,110 (GitHub stars > 7k)
  

**Official resources for icon and color:**  I'm not clear on which of these is the more official branding image. The first is taken from the website, the second from the GitHub ReadMe:

  Small Chai

  Chai

### PR DESCRIPTION
**Pull request by adamrusted**
chai

**Issue:** Fixes #4983
**Alexa rank:** [164,653](https://www.alexa.com/siteinfo/chaijs.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Inverted icon to preserve clarity as much as possible. Alternative treatment below is truer to the _darker segments_ of the original, though lacks clarity at smaller sizes.

### Alternative Treatment
chai (1)

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I think the alternative treatment is the way to go here.

**Comment by adamrusted** [comment]
Done! Reduced the points down in the `C` wherever possible, so there may be a couple hairline differences.

**Comment by PeterShaggyNoble** [comment]
Looking good, @adamrusted 👍🏻 Just a couple of tiny differences ([1](https://user-images.githubusercontent.com/15157491/111345369-1f56a600-8675-11eb-9e2c-48e15a1e7b92.png) & [2](https://user-images.githubusercontent.com/15157491/111345435-339aa300-8675-11eb-9cef-2f9add7199d2.png), with yours in red) and [at the very bottom](https://user-images.githubusercontent.com/15157491/111345537-4a40fa00-8675-11eb-83f5-c1064be1c3ba.png). But if @keithamus is OK with them, we can run with them.

Keith, as well, is there any licensing info or usage guidelines you'd like us to include with your icon?

**Comment by keithamus** [comment]
The yellow on grey for the light buttons doesn't seem like a satisfactory contrast ratio, perhaps they should be altered? The typeface is Apache 2 Licensed, the logos are MIT licensed, so minimal licensing restrictions (just a case of including notices).

**Comment by PeterShaggyNoble** [comment]
Thanks for the feedback, @keithamus 🙂

Those buttons are examples of how the various [Shields.io](https://shields.io/) styles will look, as they use our package. We could use the red, instead, if you prefer but that would also then be the colour we'd be serving up to all our users.

**Comment by keithamus** [comment]
Is it possible to specify two colours? One against light backgrounds and one against dark?

**Comment by adamrusted** [comment]
> Is it possible to specify two colours? One against light backgrounds and one against dark?

Not with the project in it's current format, no. The hex we provide only serves as a 'guide' to end-users anyway, as the SVG is served without colour (defaulting to the path being black), with the hex being available via the JSON. In most cases, there's a clear "primary colour" for the brand, that something like shields.io will pull for their badges - though I get the worry about the cream on white being rubbish for readability.

**Comment by adamrusted** [comment]
Hey @keithamus - given we're only able to specify the one colour, would the red hex be preferred? We can look at getting this merged in if that's the case!

**Comment by keithamus** [comment]
Sure. Let's use the red.

**Comment by adamrusted** [comment]
Amazing, thank you! I'll put this back up for review, and hopefully we'll see it added soon!

**Review by PeterShaggyNoble — APPROVED** [review]
Looks perfect now, @adamrusted, nice work 👍🏻

Thanks for your feedback & contributions on this one, @keithamus, much appreciated 🙂

**Pull request merged**
