### PR TITLE
Part 1 of the letter T review

### PR DESCRIPTION
**Pull request by service-paradis**
Part of #9072

### CODE REVIEW

**Comment by adamrusted** [comment]
As discussed in #9375 - I think anything where we're altering the source / guidelines should be included in the release note. If you wanted to split out the removal of trailing slashes into another PR that we could skip the release note on, that's chill.

**Comment by service-paradis** [comment]
Totally missed that! Make sense to me though!
I will split the PRs!

**Comment by adamrusted** [comment]
Trailforks also appears to just be slash slashing @service-paradis  - could you bin that one from this PR, and then we can merge!

**Comment by service-paradis** [comment]
Too many slashes to slash... I'm seeing slashes everywhere!

**Comment by adamrusted** [comment]
> I'm seeing slashes everywhere!

SLASH 'EM!

**Pull request merged**
