### PR TITLE
Peerlist SVG Assets

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
Brand Name: Peerlist
Website: https://Peerlist.io

image

**Issue:**

**Alexa rank:**

- World Rank: [859,982](https://www.alexa.com/siteinfo/peerlist.io)
- Country Rank ( India ): [79,667](https://www.alexa.com/siteinfo/peerlist.io)

  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Hex Color: #27AE60;
picked this because of their Background Color.

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
@service-paradis Please Review & Merge!

**Comment by sachinraja** [comment]
Please don't randomly mention people. We review PRs on our own time. Also, we require a minimum Alexa rank of 500,000, so this does not meet our requirements for inclusion. Is there another popularity metric we can use?

**Comment by Siddhant-K-code** [comment]
You Can Consider this: https://www.crunchbase.com/organization/peerlist

**Comment by LitoMore** [comment]
Could you explain why the artwork of the SVG you provided is so different from the logo on the official website?

**Comment by sachinraja** [comment]
As @LitoMore said, the icon doesn't seem to match the one on the website. Also I don't think we can accept crunchbase rankings as an alternative to the alexa rank. That being said, we are open to adding this in the future when the alexa rank reaches 500,000.

**Pull request closed without merging**
