### PR TITLE
Update Fur Affinity icon

### PR DESCRIPTION
**Pull request by KovuTheHusky**
furaffinity

**Alexa rank:** 6,873

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Vectorized using Inkscape. Logo, color, and source updated in accordance with [official announcement](https://www.furaffinity.net/journal/9761295).

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome back, @KovuTheHusky 🙂 And thanks for the update on this one.

However, I'm seeing quite a few differences between your version and the source PNG, mostly in the details of the "splat". Before we go through all the hassles of trying to clean it up again, as we did last time they updated their icon, could you reach out to Fur Affinity or the designer of the new logo to see if they can provide you with a vector version?

**Comment by adamrusted** [comment]
Hey @KovuTheHusky, have you had any joy with getting hold of a designer? If not, as @PeterShaggyNoble mentioned above - this may need some tidying to match the source PNG closer.

**Comment by PeterShaggyNoble** [comment]
@adamrusted, did you ever hear back from the designer on Twitter?

**Comment by adamrusted** [comment]
Nope. I did send them a DM, as opposed to tweeting at them - so potentially they've just not checked them

**Comment by KovuTheHusky** [comment]
I also sent a DM on February 10th and have not received a reply.

**Comment by ericcornelissen** [comment]
Given the lack of response from their side, I think we should move ahead and continue with this Pull Request based on the raster version. @KovuTheHusky, do you think you're able to improve upon the current version of the SVG based on [Peter's feedback](https://github.com/simple-icons/simple-icons/pull/4961#issuecomment-776632656)?

**Comment by adamrusted** [comment]
It's now been 2 months since the last message to @KovuTheHusky.
In the interest of closing some stale/abandoned PRs I'll give another 14 days and look to close this one off as inactive.

**Comment by adamrusted** [comment]
Closing due to inactivity. @KovuTheHusky please feel free to reopen and continue working on this at a later date.

**Pull request closed without merging**
