### PR TITLE
Update Adobe InDesign

### PR DESCRIPTION
**Pull request by MetLee**
image

**Issue:** #3369 
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
The letters have shifted in this one, @MetLee. Comparison below is [the original version](https://www.adobe.com/content/dam/cc/icons/indesign.svg) with yours overlaid in red.

**Comment by MetLee** [comment]
@PeterShaggyNoble Thanks! You are so careful! I will check it again.

**Comment by MetLee** [comment]
The size of origin svg is 22.5*21.9, not 24*24. Therefore, I resize it to 24*24. Meanwhile, it not in the center. 
Maybe the staff of Adobe made a mistake lol.

**Comment by PeterShaggyNoble** [comment]
> The size of origin svg is 22.5 * 21.9

Ah-ha! I think we may be using different source files, so. I'm using https://www.adobe.com/content/dam/cc/icons/indesign.svg, which is coming in at `240*234`, same as the others.

**Comment by fbernhart** [comment]
@MetLee Are you still working on this one? If so, could you use the following SVG as source and rebuild the icon from that source?

https://www.adobe.com/content/dam/cc/us/en/creativecloud/max2020/mnemonics/indesign.svg

**Pull request closed without merging**
