### PR TITLE
Updated Google Pay

### PR DESCRIPTION
**Pull request by adamrusted**
googlepay

**Issue:** #4205
**Alexa rank:** N/A

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> Not Necessary
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Slight change to logo (Added 0.35px lines where colours change in the 'G').
Generated in Adobe Illustrator.
Ran through SVGO CLI & SVGlint.

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
Good work with these gaps @adamrusted :+1:

I'm seeing some differences against the source in the letter "G". Can you check them?

image

**Comment by mondeja** [comment]
Before continuing with the review, although Google doesn't prohibit it, I want to know what other @simple-icons/maintainers think about that gaps. We should allow them or not? Note that the previous version did not include them and they could be a subjective distortion of the symbol :thinking:

**Comment by adamrusted** [comment]
> Before continuing with the review, although Google doesn't prohibit it, I want to know what other @simple-icons/maintainers think about that gaps. We should allow them or not? Note that the previous version did not include them and they could be a subjective distortion of the symbol 🤔

Totally agree, I added the gaps purely to distinguish where colours would change, as I've seen discussed on other icons. If you want to stick with the current icon, the path itself is absolutely fine.

**Comment by ericcornelissen** [comment]
Our [current version of just the Google logo](https://github.com/simple-icons/simple-icons/blob/6379ae7022b7bf8bca9e46c74dc53874265f66d8/icons/google.svg) also doesn't have it. I'd say the logo is recognizable without the separations and in my opinion looks better. Since there are no explicit guidelines on how to do the logo monochrome I would say we leave out the gaps. Moreover, I think there are examples of Google using the "G" monochrome, e.g. on [the back of Pixel phones](https://images.app.goo.gl/7bLJaXU1kxiFmRwaA).


> If you want to stick with the current icon, the path itself is absolutely fine.

To clarify, you mean [the existing path](https://github.com/simple-icons/simple-icons/blob/6379ae7022b7bf8bca9e46c74dc53874265f66d8/icons/googlepay.svg) is fine and doesn't need to be updated?

**Comment by adamrusted** [comment]
> To clarify, you mean [the existing path](https://github.com/simple-icons/simple-icons/blob/6379ae7022b7bf8bca9e46c74dc53874265f66d8/icons/googlepay.svg) is fine and doesn't need to be updated?

Yep. Only difference between the two is the addition of the gaps.

**Pull request closed without merging**
