### PR TITLE
Update Basecamp Icon

### LINKED ISSUE #2978: Basecamp
Name: Basecamp
Official resources for icon and color: 
https://basecamp.com/about/press

The Basecamp brand seems to have gone under a rebranding. I'd like to help out, where are the instructions and/or resources to update icons for pull requests?

### PR DESCRIPTION
**Pull request by Z33**
basecamp

Issue: Closes #2978
https://basecamp.com/about/press

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with ~~SVGO~~ or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Original
basecamp(1)

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution and bringing this to our attention, @Z33.

A couple of things to correct before we can merge this in:
1. The path needs to be centred vertically.
2. It doesn't quite fill the horizontal width of the canvas; it's coming in at `23.999` wide.
3. There are a number of differences in a few places (see comparison with your version in red below).

There could be a couple of things that would account for that last issue:
1. The SVG you use may not be the same I'm using for my comparison. I'm using [this one](https://basecamp.com/assets/about/press/standard-basecamp-logo-99cc6f352739d6b51eaa905e6022cb45215b7a9151ca53fc5218109485149971.svg) which appears in the logo section of the press page. Which file did you base your version on?
2. Some software (e.g., Inkscape) doesn't maintain the original shape when converting some `stroke`s to `path`s.

**Comment by Z33** [comment]
I always forget Sketch tends to cause issues with illustration vectors. I've exported from Affinity Design this round.

**Comment by PeterShaggyNoble** [comment]
Thanks for updating, @Z33. However, it's still coming in at `23.999` wide with a few differences between your version and the source, which, as mentioned, could either be accounted for by us using different source files - can you let us know which file you're using - or by your software struggling to convert the stroke to a path (assuming that's what you're doing).

**Comment by Z33** [comment]
Not sure how it’s coming out any different. I’m using the eps from their resources I linked above. There was no need for conversion as they’ve already converted the strokes to paths. 

The only thing I could imagine is that OMSVG is adjusting the paths? As far as the width, I have no clue what’s going on there.

**Comment by PeterShaggyNoble** [comment]
Yep, spotted that your version was closer to the EPS versions (see edit in previous comment). As for the issue with the size that's usually down to the chosen precision when optimising the path; it can usualy be fixed by increasing the precision by 1 until it's sorted.

**Comment by Z33** [comment]
I’ll try that once more. Any tips on how I can replicate your comparison to the original?

**Comment by ericcornelissen** [comment]
> I’ll try that once more. Any tips on how I can replicate your comparison to the original?

@Z33 you can do that by simply importing your final SVG and the original SVG into the same workspace and trying to align them (with contrasting colors).

However, the width issue is, as @PeterShaggyNoble suggested, probably fixable by increasing the precision of SVGOMG.

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @Z33?

**Comment by Z33** [comment]
Yeah, I plan to be back on it early this week. Thanks for checking in.

**Comment by ericcornelissen** [comment]
@Z33, checking in again. Any chance you will be able to finalize this contribution in the near future or would you like some help?

**Comment by PeterShaggyNoble** [comment]
Closing this out due to inactivity; I'll get a fresh PR together for it shortly.

**Pull request closed without merging**
