### PR TITLE
Add Peugeot

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
#2059

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Color was taken from wordmark in official SVG.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Nice work @runxel 👍

**Comment by PeterShaggyNoble** [comment]
Should the eye not be knocked out of this? And I wonder would an outline be a better treatment? 🤔

**Comment by runxel** [comment]
> Should the eye not be knocked out of this? And I wonder would an outline be a better treatment? 

No and no.
Brief explanation:
- The eye isn't even knocked out in the original version, it's just a small black dot.
- Also at small sizes nobody can actually see it.
- An outline would look weird here, because the icon is not uniform enough (think of the tail...!).

**Comment by ericcornelissen** [comment]
> The eye isn't even knocked out in the original version, it's just a small black dot.
> Also at small sizes nobody can actually see it.

That, to me, doesn't sound like we shouldn't cut it out. Though it is an artistic interpretation, I do think it would make the logo more recognizable 🤔 


> An outline would look weird here, because the icon is not uniform enough (think of the tail...!).

Although I agree a filled version is more accurate, I don't think a outlined version would look weird. (in fact, an older version of the logo is an outline!)

**Comment by runxel** [comment]
The outline works, if it's the same size as the tail, otherwise the tail would either look to big or to small.
Anyway, if I have time I will make a version with eyes for you in the next days 👀

**Pull request merged**
