### PR TITLE
Bower!

### PR DESCRIPTION
**Pull request by whoisjorge**
As Webpack, I am not sure about the brand's primary color of Bower. According to the branding guideliness there are... [a lot](https://bower.io/docs/about/#colors) of options?

| Color              | Hex Code       |
| ------------- |:-------------:| 
| Dark Brown      | `#543729` | 
| Red      | `#EF5734`      | 
| Gold     | `#FFCC2F` | 
| Green      | `#2BAF2B`      | 
| Blue      | `#00ACEE` | 

PD: Relevant for #625

### CODE REVIEW

**Comment by birjolaxew** [comment]
I'd probably go with the red color. I feel like that is the most dominant color in their logo, and the one I connect with the brand the most.

**Comment by whoisjorge** [comment]
Yes, I think the same @birjolaxew. The gold color is he second option, but I feel like is not as recognizable as red.

**Comment by birjolaxew** [comment]
Nice! Could you run it through SVGO with 3-4 precision to reduce the filesize a bit? Looks good other than that.

**Comment by birjolaxew** [comment]
:+1: Thanks for the pr! Merged and published

**Comment by whoisjorge** [comment]
Thanks @birjolaxew !

**Pull request merged**
