### PR TITLE
Added Vectorworks Icon

### PR DESCRIPTION
**Pull request by sjstark**
vectorworks

**Issue:** #1984
**Alexa rank:** 137,530
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with **SVGO** or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Chose the hex value based on company's main brand color. Vectorworks updates actual application icon yearly with release of new software.
Grabbed the svg from company website's SVG.

### CODE REVIEW

**Review by runxel — CHANGES_REQUESTED** [review]
I was actually working on that one, too.

The problem I detected early, was the high probability this icon was potraced, and not done by hand.
We now could say: It doesn't matter, they themself seem to use it... etc.

However one of our rules is not to accept protraced icons _at all_, since they are so often malformed. (See attached screenshot)
vw

We already had a handful of similar cases where instead we redraw the icons with the intention the icon _has_ to look like in the first place. That's why I will flag this as "request changes".

If you are not able/willing to fix the issues of the icon I can take it over, so no pressure here it all. Thanks for understanding! ❤️

**Comment by sjstark** [comment]
@runxel I actually noticed that with another corner and thought it was kind of surprising (especially since Vectorworks is a vector editing company...)

I'll take a swing at it later today since I'd love to get involved more with knocking some of these requests out.

**Comment by runxel** [comment]
Cool! Thanks for not resigning 😃 Take all the time you need.
And yeah, it's always quite surprising how sub-par a lot of those companies handle their brands...

**Comment by adamrusted** [comment]
Hi @sjstark, are you still interested in contributing this icon? No worries if not! 🙂

**Comment by sjstark** [comment]
I have 2 or 3 I need to hop back on 😅 Apologies, life came in hard in the last 4 months. I'll do it this week!

**Comment by adamrusted** [comment]
> I have 2 or 3 I need to hop back on 😅 Apologies, life came in hard in the last 4 months. I'll do it this week!

No worries! Just wanted to check in before I worked on this myself - will leave it to you 👌

**Comment by PeterShaggyNoble** [comment]
> Vectorworks updates actual application icon yearly with release of new software.

Is the icon in this PR for the company or the software? If the latter then I think it might fall into the "yearly releases" category which, per [our guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) we don't allow.

**Comment by runxel** [comment]
> 
> 
> > Vectorworks updates actual application icon yearly with release of new software.
> 
> Is the icon in this PR for the company or the software? 

Both, actually.
Vectorworks does release new software yearly, as most vendors in the CAD/BIM world do. 
Chrome and Firefox are releasing every some weeks – So, that is not the metric, @PeterShaggyNoble.
Instead this always refered to logos, which e.g. have the current year in their logo or other elements, that are prone to frequent changes (at least this is how I perceived it when establishing this rule).
The Vectorworks logo doesn't change that often. The last rebrand was just 2 or 3 years ago.

**Comment by PeterShaggyNoble** [comment]
Thanks, @runxel. Guess I misinterpreted @sjstark's comment; I thought they were saying that Vectorworks change their logo/icon every year, with each release.

**Comment by sjstark** [comment]
I have time set aside this Wednesday to fix these issues!
But on the note of the logo updates, they go through an application update yearly, and with the update they change the app's color on the desktop, however logo svg remains constant for the past couple of years (until their design team gets bored and revamps it). That said, I made the logo color black because their website currently has black as the main theme of the site and the favicon is black.
Luckily though, the color of the logo can be updated fairly easily with the application color updates if that's the route desired.

**Comment by sjstark** [comment]
Hey all, I reopened this in a new pull #4764. Only because I went through my github at some point and purged some misc repos and it looks like I lost the original branch this was on.

**Pull request closed without merging**
