### PR TITLE
add Dgraph

### LINKED ISSUE #4924: Dgraph
**Brand Name:** Dgraph
**Website:** [https://dgraph.io/](https://dgraph.io/)
**Alexa rank:** [147,042](https://www.alexa.com/siteinfo/dgraph.io)

**Official resources for icon and color:**
I found no official entry, but submitted a [request](https://discuss.dgraph.io/t/brand-simple-icons-submission/12248) in their forum.
The logo can be found in [wikipedia](https://en.wikipedia.org/wiki/File:Dgraph-logo.svg) also.

### PR DESCRIPTION
**Pull request by jlnrrg**
dgraph
**Issue:** Closes #4924
**Alexa rank:**  [147,042](https://www.alexa.com/siteinfo/dgraph.io)
### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by fbernhart** [comment]
@jlnrrg The preview images can be generated here: https://petershaggynoble.github.io/MDI-Sandbox/simpleicons/preview/

**Comment by jlnrrg** [comment]
@jlnrrg use this more aligned version [wetransfer](https://we.tl/t-dHL1O0l3RK)

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one on, @jlnrrg. Can you update the PR with the centred version, please?

**Comment by jlnrrg** [comment]
@PeterShaggyNoble sorry for the delay. I had some rl stuff to do that interrupted the process.
Now it should work find

**Comment by PeterShaggyNoble** [comment]
Thanks for updating, @jlnrrg. However it looks like the precision is a little low, resulting in [some differences](https://user-images.githubusercontent.com/15157491/108229701-f4da0180-7137-11eb-8a9d-05684d02a861.png) between the source (in black) and your version (in red) - could you have another look at that, please?

Also, where did you source the colour you used? While I agree that pink is probably the best choice for the colour here, the shade used in the gradients both in the SVG and on their website is `#e50695`.

Finally, could you update the source to just https://dgraph.io/?

> sorry for the delay. I had some rl stuff to do

Never apologise; real life comes first 🙂

**Review by adamrusted — APPROVED** [review]
Looks good to me! Thanks @jlnrrg for your work on this one! 🚀

**Comment by jlnrrg** [comment]
@adamrusted that made happier than it should have :smile:

**Pull request merged**
