### PR TITLE
Refactor add-icon-data script

### PR DESCRIPTION
**Pull request by uncenter**
### Description

Applies improvements from #10573 to the latest version of the add-icon-data script.

### CODE REVIEW

**Comment by mondeja** [comment]
You're doing great contributions to simple-icons! Do you want to become a maintainer? It just means that we will give you access as a member or administrator to some parts of the project, without any commitment to the activity since we all do this for pleasure in our free time.

I'll review this PR later, but looks very good as usual.

**Comment by uncenter** [comment]
> You're doing great contributions to simple-icons! Do you want to become a maintainer? It just means that we will give you access as a member or administrator to some parts of the project, without any commitment to the activity since we all do this for pleasure in our free time.

Thank you for the offer! I would love to become a maintainer. Very happy to be part of this project, I've used it for a long time on my own projects and it feels good to contribute!

**Comment by adamrusted** [comment]
Invite sent to you @uncenter!
If you're on the Discord too - feel free to tag me and I'll give you maintainer perms there too :)

**Comment by uncenter** [comment]
> If you're on the [Discord](https://discord.gg/vUXFa7t5xJ) too - feel free to tag me and I'll give you maintainer perms there too :)

I am now! My username is `@uncenter` :)

**Review by mondeja — APPROVED** [review]
Awesome! Thank you @uncenter 👏🏼

**Pull request merged**
