### PR TITLE
Add Mantine icon

### LINKED ISSUE #7670: Request: Mantine
### Brand Name

Mantine

### Website

https://mantine.dev/

### Popularity Metric

85,722

### Official Resources for Icon and Color

svg: https://github.com/mantinedev/mantine/blob/master/src/mantine-ds/src/MantineLogo/MantineLogoRounded.tsx
color: https://mantine.dev/pages/about/

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by teaguestockwell**
mantine

**Issue:** closes #7670 

**Similarweb rank:** 85,722

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- manual combined paths using boxy-svg then used vectr to resize viewport to 24 24
@rtivital

### CODE REVIEW

**Comment by dirien** [comment]
Hi @teaguestockwell,

Is there an issue linked to this PR? And can you link the source of the icon so we can review your PR, thanks

**Comment by teaguestockwell** [comment]
@dirien I created an issue: #7670, the source of the icon is here: https://mantine.dev/pages/about/

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @teaguestockwell,

I see some differences ( I used the icon SVG on the website as reference=

image

Maybe try to up the precision?

**Comment by teaguestockwell** [comment]
@dirien Thanks for this feedback. Here is how I made the most recent change:
1. using a new [source](https://omatsuri.app/svg-compressor) that had a pre compressed icon
1. using inkscape to resize the viewport to 24 x 24
1. running `npx svgo -i path2.svg -o mantine.svg -p 2` to compress the resized svg

Are you apposed to a loss of fidelity given when resizing to a 24 x 24 viewport then optimizing with svgo? My understanding is that the reduction in noise is expected and would be acceptable as long as it does not cause the icon to distort.

**Comment by dirien** [comment]
Sometimes, playing with the precision helps to be close to the original icon without any extra effort! If it's still not help, I would opt to merge it as it's very close!

**Comment by teaguestockwell** [comment]
If its close thats probably ok then. I think there will still be some noise in the visual diff because of compression with svgo.

**Comment by dirien** [comment]
ask the fellow @simple-icons/maintainers for an additional opinion.

**Comment by sachinraja** [comment]
Up to you @dirien. I'm ok if you merge.

**Comment by service-paradis** [comment]
Every icons of the repository are compressed using svgo. This logo is not a particularly complex one, I'm pretty sure this could be done without this kind of difference. The precision used is only 2, so maybe we should try with a precision of 3 or 4 to see if it reduce the differences!

**Comment by dirien** [comment]
hi @teaguestockwell,

can you have a look what @service-paradis wrote and try to up the precision?

**Comment by teaguestockwell** [comment]
Thanks for the feedback @service-paradis. I was starting to work through this using -p 4 to see if I could remove this difference, and I noticed that the source of the icons [here in the header](https://mantine.dev/)

Screen Shot 2022-08-27 at 12 04 36  

as well as [here in the download link](https://mantine.dev/pages/about/) 
Screen Shot 2022-08-27 at 12 11 14

are not perfect spheres. I think that correcting for this is why there is a visual difference. If this is expected, are you opposed to using the -p 2 icon?

**Comment by LitoMore** [comment]
@teaguestockwell As I mentioned here: https://github.com/mantinedev/mantine/issues/2255#issuecomment-1229400145. Let's use this one https://github.com/mantinedev/mantine/blob/f2da0287bfcda19dcf7866f4d03a05d1ee7b49f7/docs/src/images/logo.svg instead.

**Comment by PratyushJayachandran** [comment]
Every single source SVG I am checking with is missing one shape or the other. The complete ones are very off from the contribution. The one in JSON only shows the small white circle after downloading.
@adamrusted please tell me which source you used

**Comment by adamrusted** [comment]
I think the other path in the source one is under the circle, or has no fill. I seem to remember having this issue when working on it.

**Comment by PratyushJayachandran** [comment]
> I think the other path in the source one is under the circle, or has no fill. I seem to remember having this issue when working on it.

Okay now I see it. Strange.
But I see [some differences](https://github.com/simple-icons/simple-icons/assets/35000807/bd4513dc-67dc-468f-8c28-eab23a91e8e6)

**Review by PratyushJayachandran — APPROVED** [review]
[Perfect match](https://github.com/simple-icons/simple-icons/assets/35000807/f33a89bf-4d84-440d-ab1b-f926466df550) 
Thank you @teaguestockwell for starting and @adamrusted for tirelessly making the corrections
🎉

**Pull request merged**
