### PR TITLE
Add V (#2055)

### LINKED ISSUE #2055: V Lang
**Name:** V Lang
**Website:** https://vlang.io/
**Official resources for icon and color:** ... only a png in header

[Github](https://github.com/vlang/v) repo has ~14k stars.

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
Closes #2055

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
If you look at https://vlang.io/ the name is just "V".
Icon taken from header and vectorized. Color `#5D87BF` taken from the light of the stylized V.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Found an SVG at https://github.com/vlang/v-logo/blob/master/dist/v-logo.svg

**Comment by runxel** [comment]
Wow, nice catch! Thank you @PeterShaggyNoble 
Would never guessed they have their own repo just for the logo.
(The vector of mine is already pretty much on point.)

**Comment by PeterShaggyNoble** [comment]
Found it in the readme of their main repo, which led me to the logo's repo.

**Comment by runxel** [comment]
Maybe I also hadn't enough coffee at that part 😃

**Comment by phatbhoy67** [comment]
Hey @runxel thanks for your work on this one. 👍 

Can you check the dimensions on your .svg, the width is not quite 24px and the icon is not quite centered vertically.

**Comment by runxel** [comment]
Updated the icon.

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @runxel 👍

**Pull request merged**
