### PR TITLE
Add Elk icon

### LINKED ISSUE #10699: Request: Elk
### Brand Name

Elk

### Website

https://elk.zone

### Popularity Metric

The Similarweb rank is 219,110. See https://www.similarweb.com/website/elk.zone/#overview.

### Official Resources for Icon and Color

SVG: https://github.com/elk-zone/elk/blob/main/public/logo.svg.

Color: `#ea9e44` (primary color from logo above).

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by uncenter**
elk

**Issue:** closes #10699.

**Popularity metric:** The Similarweb rank is 219,110. See https://www.similarweb.com/website/elk.zone/#overview.

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
I'm spotting some differences when comparing, granted my software didn't want to play nicely with the mask initially...

image

Can another @simple-icons/pr-reviewers verify the differences seen above?

**Comment by uncenter** [comment]
It's not just you! I'm seeing that now as well. Curiously I've gone and redone the icon and I'm still seeing this differences... ugh masks are the worst!

**Comment by uncenter** [comment]
I'm going to unfortunately close this PR. Issue is still open if anyone wants to contribute!

**Comment by anhthang** [comment]
I've been encountering the same issue with the mask after resizing it to fit the 24x24 view box.

If the resized doesn't work within acceptance criteria, we might need to use a temporary workaround with `.svglint-ignored.json` file.

**Comment by uncenter** [comment]
The linter wasn't complaining though? What would we ignore...

**Comment by anhthang** [comment]
Like this
```json
{
  "icon-centered": {
    "M22.915 8.321c-.642-.997-1.542-1.879-2.672-2.624-2.185-1.436-5.056-2.227-8.084-2.227-1.012 0-2.009.088-2.976.262a9.84 9.84 0 0 0-2.046-1.509C4.378.848 1.947 1.361.719 1.802a.59.59 0 0 0-.229.964c.866.894 2.299 2.66 1.946 4.267C1.067 8.431.324 10.117.324 11.872c0 1.789.742 3.475 2.112 4.873.352 1.607-1.081 3.374-1.947 4.268a.589.589 0 0 0 .229.963c1.228.442 3.659.955 6.418-.421a9.892 9.892 0 0 0 2.046-1.509c.968.174 1.964.262 2.976.262 3.029 0 5.9-.79 8.084-2.226 1.131-.744 2.031-1.626 2.672-2.624.715-1.11 1.077-2.306 1.077-3.552.001-1.279-.361-2.473-1.076-3.585zm-10.881 9.916c-1.309 0-2.558-.169-3.696-.474l-.832.8A7.609 7.609 0 0 1 5.972 19.7a6.033 6.033 0 0 1-2.17.613c.041-.073.078-.147.117-.221.833-1.531 1.059-2.907.674-4.128-1.363-1.071-2.181-2.442-2.181-3.935 0-3.427 4.308-6.206 9.621-6.206 5.313 0 9.622 2.779 9.622 6.206.001 3.429-4.307 6.208-9.621 6.208zM8.85 12.01c0 .777-.635 1.407-1.418 1.407-.783 0-1.418-.63-1.418-1.407s.635-1.407 1.418-1.407c.783 0 1.418.63 1.418 1.407zm4.563 0c0 .777-.635 1.407-1.418 1.407-.783 0-1.418-.63-1.418-1.407s.635-1.407 1.418-1.407c.783 0 1.418.63 1.418 1.407zm4.565 0c0 .777-.635 1.407-1.418 1.407-.783 0-1.418-.63-1.418-1.407s.635-1.407 1.418-1.407c.783 0 1.418.63 1.418 1.407z": "Rocket.Chat"
  },
  "icon-size": {
    "M22.915 8.321c-.642-.997-1.542-1.879-2.672-2.624-2.185-1.436-5.056-2.227-8.084-2.227-1.012 0-2.009.088-2.976.262a9.84 9.84 0 0 0-2.046-1.509C4.378.848 1.947 1.361.719 1.802a.59.59 0 0 0-.229.964c.866.894 2.299 2.66 1.946 4.267C1.067 8.431.324 10.117.324 11.872c0 1.789.742 3.475 2.112 4.873.352 1.607-1.081 3.374-1.947 4.268a.589.589 0 0 0 .229.963c1.228.442 3.659.955 6.418-.421a9.892 9.892 0 0 0 2.046-1.509c.968.174 1.964.262 2.976.262 3.029 0 5.9-.79 8.084-2.226 1.131-.744 2.031-1.626 2.672-2.624.715-1.11 1.077-2.306 1.077-3.552.001-1.279-.361-2.473-1.076-3.585zm-10.881 9.916c-1.309 0-2.558-.169-3.696-.474l-.832.8A7.609 7.609 0 0 1 5.972 19.7a6.033 6.033 0 0 1-2.17.613c.041-.073.078-.147.117-.221.833-1.531 1.059-2.907.674-4.128-1.363-1.071-2.181-2.442-2.181-3.935 0-3.427 4.308-6.206 9.621-6.206 5.313 0 9.622 2.779 9.622 6.206.001 3.429-4.307 6.208-9.621 6.208zM8.85 12.01c0 .777-.635 1.407-1.418 1.407-.783 0-1.418-.63-1.418-1.407s.635-1.407 1.418-1.407c.783 0 1.418.63 1.418 1.407zm4.563 0c0 .777-.635 1.407-1.418 1.407-.783 0-1.418-.63-1.418-1.407s.635-1.407 1.418-1.407c.783 0 1.418.63 1.418 1.407zm4.565 0c0 .777-.635 1.407-1.418 1.407-.783 0-1.418-.63-1.418-1.407s.635-1.407 1.418-1.407c.783 0 1.418.63 1.418 1.407z": "Rocket.Chat"
  }
}
```

**Comment by uncenter** [comment]
Yes, I can see the file too! I don't understand what you mean we should ignore? My version of the Elk icon had no linter issues. And we can't ignore the mask entirely, we need to remove it no matter what.

**Comment by anhthang** [comment]
After releasing the mask, there will be a noticeable difference in the logo's alignment. While this version avoids linter errors, it compromises the logo's visual consistency with the original.

image

image


To maintain the original logo alignment, we would need to skip resizing it to 24x24. However, this approach would trigger linter warnings. In that case, we'd have to use `.svglint-ignored.json` to suppress those specific warnings.

**Pull request closed without merging**
