### PR TITLE
Add Wikimedia Commons

### LINKED ISSUE #2615: Wikimedia Commons
**Name:** Wikimedia Commons
**Website:** https://commons.wikimedia.org/
**Alexa Rank:** n/a (Wikimedia subdomain)
**Colour:** `#006699`?
**Official resources for icon and color:** Icon from [this file](https://commons.m.wikimedia.org/static/images/mobile/copyright/commons-wordmark-en.svg), colour from [this one](https://upload.wikimedia.org/wikipedia/en/4/4a/Commons-logo.svg)

[Wikimedia Commons](https://github.com/simple-icons/simple-icons/files/4219299/wikimediacommons.zip)

### PR DESCRIPTION
**Pull request by ericcornelissen**
Wikimedia Commons

**Issue:** Closes #2615

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Adds Wikimedia Commons logo, as discussed in #2615. I left the imperfection in the logo, as it is an official source, but I suppose that is up for debate.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Nice one, Eric. SVG & colour look good to me but, because of the imperfections and the manual fiddling to sort that curve out, we'll need one of the other @simple-icons/maintainers to review it too.

The only change I'd suggest is changing the source URL to https://commons.wikimedia.org/wiki/File:Commons-logo.svg as the homepage doesn't include a vector version of the logo anywhere, that I can see.

I took the liberty of editing a preview in for you, by the way; hope you don't mind.

**Comment by ericcornelissen** [comment]
> The only change I'd suggest is changing the source URL to https://commons.wikimedia.org/wiki/File:Commons-logo.svg as the homepage doesn't include a vector version of the logo anywhere, that I can see.

The logo in the top left is an SVG, at least for me... But I do think your source URL is better (especially given our freshly updated guidelines in #2567!). Will update it 👌 


> I took the liberty of editing a preview in for you, by the way; hope you don't mind.

Dang, forgot to do it myself 😅 Thank you!

**Comment by PeterShaggyNoble** [comment]
> The logo in the top left is an SVG, at least for me...

Weird, I have [this PNG](https://commons.wikimedia.org/static/images/project-logos/commonswiki.png) 🤷‍♂

**Comment by ericcornelissen** [comment]
> Weird, I have [this PNG](https://commons.wikimedia.org/static/images/project-logos/commonswiki.png) 🤷‍♂

Just double checked, apparently I didn't look careful enough 🙃

**Pull request merged**
