### PR TITLE
Add RustDocs icon

### PR DESCRIPTION
**Pull request by wandercn**
**Issue:**
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by wandercn** [comment]
I just shrink the svg picture to 24*24, how the picture data and format check, the picture is able to display normally, why?

**Comment by wandercn** [comment]
Can you help to fix the formatting problem, I'm not a professional picture maker

**Comment by elliotwutingfeng** [comment]
Would this svg be acceptable?

rustdocs

Similarweb ranking: 57,851, see https://www.similarweb.com/website/docs.rs/

**Comment by sachinraja** [comment]
Yes, that one is a perfect match @elliotwutingfeng. Is it okay if we switch to that @wandercn?

**Comment by sachinraja** [comment]
@elliotwutingfeng could you open another PR for your version?

**Comment by sachinraja** [comment]
superseded by #7290

**Pull request closed without merging**
