### PR TITLE
Updated DTube

### PR DESCRIPTION
**Pull request by fbernhart**
dtube

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by service-paradis** [comment]
Looks like they also updated their logo:
https://about.d.tube/mediakit.html

What do you think?

**Comment by fbernhart** [comment]
dtube

@service-paradis  Updated.
**Source:** https://about.d.tube/mediakit.html
**Color:** #223154 (main color of the official logo)

**Comment by service-paradis** [comment]
Thanks, the logo looks perfect to me!
I'm questioning about the color. According to https://about.d.tube/mediakit.html, here are the colors (in order):
- `#F01A30`
- `#223154`
- `#E6E6E6`

Personally, I think I would choose the first color mentioned as the brand color (it looks to be the main accent color on the website). Maybe we can ask for other @simple-icons/maintainers what they think?

**Comment by mondeja** [comment]
I would also opt for `#F01A30`.

**Comment by fbernhart** [comment]
dtube

So shall it be. 👍🏼

**Pull request merged**
