### PR TITLE
Add China Eastern Airlines

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
China Eastern Airlines

**Issue:** #2587
**Alexa rank:** [~59k](https://www.alexa.com/siteinfo/ceair.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon & colour from logo on first page of [this PDF](http://en.ceair.com/upload/2017/5/51132788.pdf). Note that I'd created the icon _before_ I stumbled across the page used for the source URL and, even though the PDF used isn't linked from that page, I went with it for better future proofing.

Some possible alternative colour: `#dd0716`

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
There's potentially some extra point we don't need here - are you able to see if there's any reductions that can be made @PeterShaggyNoble?

image

**Comment by PeterShaggyNoble** [comment]
If you mean the 2 at the top of the point where the 2 curves meet, @adamrusted, I did try cleaning them up but everything I did affected one or other of the curves.

**Comment by adamrusted** [comment]
> If you mean the 2 at the top of the point where the 2 curves meet, @adamrusted, I did try cleaning them up but everything I did affected one or other of the curves.

Yeah, sorry I should've put arrows on the screenshot before uploading. There's those, and where the two shapes join. Happy to merge if you've already looked into that though.

**Comment by PeterShaggyNoble** [comment]
Tried again and no joy 🙁 If you can figure it out, feel free to push an update 🙂

**Comment by adamrusted** [comment]
I'm also unable to effectively reduce those points. I'm happy to go with the PR version for now, and hopefully someone's able to optimize further down the line. Will see if any other @simple-icons/maintainers want to have a go before merging tomorrow 😅

**Comment by adamrusted** [comment]
14 tomorrow's later - assuming we're good to go, being as none of the other @simple-icons/maintainers have said anything. Will look to merge this at end of day.

**Review by adamrusted — APPROVED** [review]
Merging due to no objections from @simple-icons/maintainers. Can submit another PR if improvements can be made.

**Pull request merged**
