### PR TITLE
Add Vaultwarden Icon

### LINKED ISSUE #8848: Icon Request: Vaultwarden
### Brand Name

Vaultwarden

### Website

None

### Popularity Metric

25.7k stars on [GitHub](https://github.com/dani-garcia/vaultwarden)

### Official Resources for Icon and Color

svg: https://github.com/dani-garcia/vaultwarden/blob/44e9e1a58ed37bf4b352bb499fd3e97adcd3b26b/resources/vaultwarden-icon.svg

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by RiteshK-611**
**Issue:** closes #8848

**Popularity Metric:**
25.7k stars on [GitHub](https://github.com/dani-garcia/vaultwarden)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This commit resolves issue #8848 by adding Vaultwarden logo in vaultwarden.svg and by updating simple-icons.json file with icon's data

### Preview
vaultwarden

### CODE REVIEW

**Comment by LitoMore** [comment]
@RiteshK-611 I can't find `#084AF4` on there GitHub project. Could you please clarify where to find this?

**Comment by RiteshK-611** [comment]
> @RiteshK-611 I can't find `#084AF4` on there GitHub project. Could you please clarify where to find this?

I got that color from their website vaultwarden.us

**Comment by LitoMore** [comment]
@RiteshK-611 I see. But the brand icon the website is not the one you're submitting. Could you give more information on this?

**Comment by RiteshK-611** [comment]
> @RiteshK-611 I see. But the brand icon on the website is not the one you're submitting. Could you give more information on this?

Brand icon is as per the issue raised for vaultwarden and their github repo. And as there was no color available in their repo I searched for vaultwarden's website and took from there

**Comment by LitoMore** [comment]
Hi @dani-garcia, could you help to review this PR? Does the icon meet your expectations?

**Comment by dani-garcia** [comment]
Hey, the icon looks good, but we only ever use it in black (or white when against a dark background). That website (vaultwarden.us) is not managed by us, they just seem to be deploying their own instance of vaultwarden.

**Comment by RiteshK-611** [comment]
Thanks @dani-garcia for confirming!

I'll change hex value to black `#000000`

**Comment by LitoMore** [comment]
image

The icon size looks not correct.

**Comment by RiteshK-611** [comment]
> image
> The icon size looks not correct.

`npm run lint` is showing that file is valid, but I'll adjust it through Inkscape 👍🏼

**Comment by GiorgioReale** [comment]
Hi,
any update on this PR?

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @RiteshK-611 🎉

**Pull request merged**
