### PR TITLE
Update Power BI

### PR DESCRIPTION
**Pull request by adamrusted**
powerbi

**Issue:** #5562
**Alexa rank:** N/A (Microsoft Power Platform)

### Checklist
  - [x] ~I updated the JSON data in `_data/simple-icons.json`~
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Used a 0.5pt cut-out on each shape to create single path.

### CODE REVIEW

**Comment by fbernhart** [comment]
What happened to the [bottom right](https://user-images.githubusercontent.com/70264417/118542760-bca48800-b753-11eb-98e6-115ac0897013.png) of the icon? 😄 Did you use a different source than I did?

**Comment by adamrusted** [comment]
> What happened to the [bottom right](https://user-images.githubusercontent.com/70264417/118542760-bca48800-b753-11eb-98e6-115ac0897013.png) of the icon? 😄 Did you use a different source than I did?

Yeah, because the mask didn't want to play in Illustrator I had to manually round the corners, looks like I messed that one up. Found a way to use the mask path in the other Power Platform PRs I submitted, so will rebuild this one.

**Comment by adamrusted** [comment]
@fbernhart give that a try. Rebuilt using my new method, so should hopefully match up!

**Comment by fbernhart** [comment]
It's a perfect match. 👍🏼

**Pull request merged**
