### PR TITLE
Ohdear

### PR DESCRIPTION
**Pull request by CrazyMarvin**
ohdear

**Issue: #6519**
**Alexa rank: 418,749**
  

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

I picked the hex value from https://ohdear.app/logos.
I am not sure how to design the icon though. Please have a look at the issue regarding this.

### CODE REVIEW

**Review by dirien — APPROVED** [review]
Hi @CrazyMarvin,

thanks for your coooooooooooooooooooooooooooooooontribution 😄 with very long icon.

image
Its a perfect fit for me.

**Comment by dirien** [comment]
hi @CrazyMarvin, can you rebase your branch please?

**Comment by CrazyMarvin** [comment]
> hi @CrazyMarvin, can you rebase your branch please?

Done, thanks 😁

**Review by dirien — APPROVED** [review]

**Comment by dirien** [comment]
hmm @CrazyMarvin, cant merge button is greyed out for me... 

image

asking @ericcornelissen for help on this.

**Comment by ericcornelissen** [comment]
None of us can update the branch because @CrazyMarvin has disabled [the option for maintainers to update the branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork). @CrazyMarvin you either need to keep your branch up-to-date all the time and hope a maintainer comes online to merge this in time before `develop` is updated **or** allow maintainers to edit your Pull Request so a maintainer can update and then merge.

**Comment by CrazyMarvin** [comment]
Where may I enable that option?

**Comment by dirien** [comment]
@CrazyMarvin -> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by CrazyMarvin** [comment]
I do not see that option in this PR. I will open a new one, @dirien & @ericcornelissen.
no

**Comment by dirien** [comment]
PR is now in -> #6836

**Pull request closed without merging**
