### PR TITLE
adding Google Marketing Platform, updating Google Keep, Google Meet a…

### PR DESCRIPTION
**Pull request by jorgeamadosoria**
googlekeep

googlemeet (1)

googlemessages

googlemarketingplatform (1)

**Issue:** #4205

### CODE REVIEW

**Comment by service-paradis** [comment]
@jorgeamadosoria No need to request review on PRs. There are more than 200 to review and they all need to be reviewed.

**Comment by jorgeamadosoria** [comment]
> @jorgeamadosoria No need to request review on PRs. There are more than 200 to review and they all need to be reviewed.

this is a pinned icon, and apparently time sensitive (since it seems to be something that is done regularly / has been done more than once). I would think this one is priority 0, thus I requested reviews.

**Comment by adamrusted** [comment]
The pinned issues are just there so we can monitor much larger projects than one or two updates. Doesn't make them priority 0, which I've always used for "non-icon updates that need attention". This PR contains both priority 1 and priority 3 icons, and but I guess would be placed in priority 1 because of the update - but should be reviewed (roughly) in order along with the other PRs in that priority band.

**Comment by service-paradis** [comment]
> Hard disagree, but, as you wish.

There are rules right now for priorisation: https://github.com/orgs/simple-icons/teams/maintainers/discussions/9

If you disagree with those rules, you can open an issue to discuss about this, but this PR is not the place to do so.

**Review by sachinraja — APPROVED** [review]
All changes look good, great job!

**Pull request merged**
