### PR TITLE
Add PubMed

### LINKED ISSUE #3302: Request: PubMed
**Name:** PubMed
**Website:** https://pubmed.ncbi.nlm.nih.gov/
**Alexa rank:** 126 (nih.gov)
  

**Official resources for icon and color:**
  

https://cdn.ncbi.nlm.nih.gov/pubmed/01ddcb93-2e80-4446-b2b2-d89a220d4f38/core/images/pubmed-logo-blue.svg?cf01ef562bf0

The icon is also included in [academicons](http://jpswalsh.github.io/academicons/).

### PR DESCRIPTION
**Pull request by thomasfedb**
pubmed

Closes #3302
**Name:** PubMed
**Website:** https://pubmed.ncbi.nlm.nih.gov/
**Alexa rank:** 126 (nih.gov)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Following on from #3302. No guidelines available, extracted icon from logo in same manner as Academicons.

### CODE REVIEW

**Comment by thomasfedb** [comment]
@PeterShaggyNoble icon was sized full height and vertically centred in AI before SVGOMG. Any tips on adjusting height/centre in the SVG directly?

**Comment by adamrusted** [comment]
> Any tips on adjusting height/centre in the SVG directly?

Hi @thomasfedb! Just taking a look at the linter feedback, it looks like SVGO(MG) has exported this at one decimal of precision. We recommend somewhere between 3 and 5 decimals, with the former being preferred if at all possible. Any chance you could take another look with it at 3 decimals, and see if it passes the linter? You can run it locally by doing executing `npm install` and `npm run svglint` in your local fork. You could also try running `npm run svgo -- icons/pubmed.svg` to run the command-line version of SVGO with _most of_ our recommended settings.

**Comment by adamrusted** [comment]
Hi @thomasfedb, are you still interested in looking at this one?

**Comment by thomasfedb** [comment]
Hey @adamrusted, I will get back to this but it might take me a few more days

**Comment by thomasfedb** [comment]
> You could also try running `npm run svgo -- icons/pubmed.svg` to run the command-line version of SVGO with _most of_ our recommended settings.

Tried this and ended up with an identical result to what I had previously using SVGOMG. I also played around with the precision slider in SVGOMG and received identical results for any value of precision 1 or greater.

So I've now tried keeping the original `<path>` from the Illustrator export, and manually removing the other cruft.

**Comment by thomasfedb** [comment]
Okay, so looks like the error if from before optimisation... Will double-check my Illustrator file

**Comment by thomasfedb** [comment]
@adamrusted the issues turned out be to exporting from Illustrator at low precision. High precision export was run through SVGO and now passes.

**Review by adamrusted — APPROVED** [review]
Looks good to me! Thanks @thomasfedb 🎉

**Pull request merged**
