### PR TITLE
Add Pelican Icon

### PR DESCRIPTION
**Pull request by iEFdev**
## Pelican Icon

Preview image of your submission using: https://petershaggynoble.github.io/MDI-Sandbox/simpleicons/preview/

pelican_preview

- - -

**Issue:** n/a
**Alexa rank:** 461k [»»](https://www.alexa.com/siteinfo/getpelican.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

This commit add the icon for Pelican (Static Site Generator):

- The icon is made out of the colored one ([»»](https://blog.getpelican.com/pages/gratitude.html)),
- Optimized using the online tool: svgomg,
- and it's been OK'd by the Pelican maintainer.

### CODE REVIEW

**Comment by iEFdev** [comment]
```
x icons/pelican.svg
  x icon-centered <path> must be centered at (12, 12); the center is currently 
                  (12.005, 12)
```

I'm not sure how to get it centered… Seems like the optimization brakes it. When opening the optimized image in inkscape it's showing something else, but the one I save (before running svgomg) looks ok.

<details>
<summary>...</summary>

  ```xml
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Pelican icon</title><path d="m 0.94175003,1.6e-6 c 0.34199197,1.054765 1.87641397,2.185673 2.90622697,2.62384 1.313315,0.558291 2.598224,0.684827 3.749971,0.812141 0.894933,0.09632 1.701777,0.201384 2.343732,0.499779 0.162206,0.07268 0.328753,0.147976 0.468746,0.24989 0.458653,0.336412 0.946439,0.987675 1.28124,1.436864 0.718663,0.958282 0.585863,1.745099 1.437489,2.21777 0.08901,0.0492 0.168262,0.0831 0.281248,0.124945 0.271036,0.101914 0.666994,0.227355 0.843743,-0.156181 0.02557,-0.05464 0.04588,-0.107548 0.0625,-0.187418 -0.07127,-0.229067 -0.321083,-0.432775 -0.468747,-0.531015 -0.261768,-0.170922 -0.37344,-0.273979 -0.562495,-0.468543 -0.349344,-0.358296 -0.347959,-0.950761 -0.593746,-1.374392 0.309232,-0.130987 1.93908,-0.359645 2.281232,-0.312362 0.731289,0.03259 1.309871,0.07815 1.749987,0.531015 0.172593,0.136418 0.249633,0.256627 0.406247,0.374835 0.01103,0.0091 0.02023,0.02405 0.03125,0.03124 0.693254,0.50366 1.338752,0.670538 1.906235,0.843377 0.149582,0.04537 0.298782,0.105378 0.437497,0.156181 0.212866,0.07636 0.406449,0.159403 0.593745,0.281125 0.222136,0.147281 0.608855,0.541875 0.624996,0.874614 -0.558694,-0.17827 -0.207105,0.03234 -1.031242,-0.03124 -0.401921,-0.04553 -0.805793,-0.06463 -1.218741,-0.09371 -0.642115,-0.04537 -1.272982,-0.104279 -1.874985,-0.218654 -0.100201,-0.01837 -0.214535,-0.03883 -0.312498,-0.06247 -0.07655,-0.01629 -0.146035,-0.01112 -0.218748,-0.03124 -0.0018,0.03083 0,0.03531 0,0.06247 -0.01662,0.629217 0.421365,0.958684 -0.593746,2.155298 -0.0091,0.01278 -0.02039,0.0167 -0.03125,0.03124 C 15.172198,10.154087 13.784662,10.755659 13.347903,10.870194 11.488679,11.243027 10.056107,10.042292 7.816696,10.65154 7.028995,10.944344 6.460088,12.227065 6.09796,13.181672 5.615974,14.44937 5.222229,15.977291 4.78547,17.492266 4.585388,18.19049 4.367661,18.893807 4.129225,19.553855 3.55423,21.137837 2.818009,22.496701 1.722994,23.270961 c -0.163805,0.125556 -0.78708397,0.410033 -0.81249397,0.624724 0.40399897,0.203676 4.18473097,0.05607 4.81246297,0 2.503256,-0.218364 3.646654,-1.773271 4.468715,-3.904524 0.565885,-1.461942 1.065025,-3.986385 2.031234,-5.310152 0.01278,-0.01821 0.0183,-0.0151 0.03125,-0.03124 0.145586,-0.19664 0.327082,-0.369112 0.499996,-0.499779 0.04539,-0.03467 0.07754,-0.06479 0.124999,-0.09371 0.03436,-0.02188 0.15661,-0.05921 0.343747,-0.09371 1.735691,-0.30734 9.348743,-1.347348 9.843673,-6.8719616 0.05098,-0.558132 0.01572,-1.158841 -0.09375,-1.811699 -0.05433,-0.336407 -0.11503,-0.665303 -0.218747,-1.030788 -0.245627,-0.869147 -0.798032,-1.613952 -1.531238,-2.21777 -0.192571,-0.159899 -0.404937,-0.32845 -0.624996,-0.468543 C 19.751975,1.0217274 18.720619,0.6407284 17.62912,0.4060694 16.895913,0.2479274 16.141748,0.1670424 15.379137,0.1561804 9.839819,0.0325414 6.397488,0.2073504 0.94175003,-6.0000001e-7 z M 2.566737,4.2168876 c 0.02349,0.03818 0.03885,0.05745 0.0625,0.09371 1.599055,2.527568 3.609397,2.502857 5.437458,2.717548 0.665927,0.07812 1.316858,0.184844 1.906235,0.468543 0.261928,0.123479 0.511558,0.264874 0.749994,0.468543 -0.02925,-0.130988 -0.0761,-0.256467 -0.124999,-0.374835 -0.44411,-1.076329 -1.648717,-1.66613 -2.687479,-1.96788 -1.393698,-0.498388 -2.403692,-0.01813 -5.343708,-1.405628 z m 1.406239,3.186091 c 0.01071,0.05272 0.0094,0.09452 0.03125,0.156181 0.219898,0.634648 1.040269,1.650375 2.093734,1.874172 0.456735,0.163573 0.314989,0.117354 1.093741,0.09371 1.140561,-0.05814 1.691984,-0.07934 2.499981,0.249889 -0.02014,-0.0492 -0.04236,-0.109062 -0.0625,-0.156181 C 9.007044,8.1749406 8.258935,8.4209536 5.879211,8.2463576 4.860426,7.9390176 4.620524,7.9048846 3.972976,7.4029806 z"/></svg>
  ```
  
</details>

**Comment by justinmayer** [comment]
Pelican maintainer here. I just wanted to give my full endorsement as well as sincere thanks to @iEFdev for helping with this endeavor. 👍 💯

**Comment by ericcornelissen** [comment]
> I'm not sure how to get it centered… Seems like the optimization brakes it. When opening the optimized image in inkscape it's showing something else, but the one I save (before running svgomg) looks ok.

That is possible, you can try optimizing with a higher precision. If you have NodeJS installed you can check if that works locally by running `npm run svglint`, otherwise it is fine to push a couple of version and wait for the results from Travis CI.


> Pelican maintainer here. I just wanted to give my full endorsement as well as sincere thanks to @iEFdev for helping with this endeavor. 👍 💯 

That's great to hear, thanks for the feedback!

**Comment by iEFdev** [comment]
> Pelican maintainer here. I just wanted to give my full endorsement as well as sincere thanks to @iEFdev for helping with this endeavor. +1 100

Thanks Justin! :+1:

> That is possible, you can try optimizing with a higher precision. If you have NodeJS installed you can check if that works locally by running `npm run svglint`, otherwise it is fine to push a couple of version and wait for the results from Travis CI.

Thanks! Yes, I'll try that. Did som thinking before I got up this morning… Perhaps it's the “odd” number on the width that needs to be adjusted. If calculating the sides when centered, it'll be: `(24-22.179)/2 = 0.9105`. And when centering the image, that rounds to `0.911` (in Inkscape) – which *could* explain the `12.005` offset in the lint. I'll try using `22.180`. which should end up with `0.910`.

**Comment by iEFdev** [comment]
@ericcornelissen, Fixed it. After a couple of sloppy errors from my side, the build test passed now. 🤞

**Comment by iEFdev** [comment]
@ericcornelissen, Thanks for the quick handling of this. :+1: Looking forward to see on the site later.

_Kiitos!_

**Pull request merged**
