### PR TITLE
Updated Stackbit

### PR DESCRIPTION
**Pull request by fbernhart**
stackbit

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by service-paradis** [comment]
According to https://www.stackbit.com/branding-guidelines/ (which we could use as source), I think they updated their primary color to `#207BEA`
Also, the logo looks a little bit different from the official one. Do you want to take a look or do you prefer we merge this fix and we open a new issue to update the color?
image

**Comment by fbernhart** [comment]
@service-paradis I'll change it. :) Thanks for pointing out.

**Comment by fbernhart** [comment]
stackbit

@service-paradis  Updated. Can this be merged now?

**Comment by service-paradis** [comment]
> @service-paradis Updated. Can this be merged now?

Sure it is! Thank you 😃

**Pull request merged**
