### PR TITLE
Add CommonMark

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
CommonMark

**Issue:** #1102 & #1087

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

**Alexa rank:** [~268k](https://www.alexa.com/siteinfo/commonmark.org)

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Hmm, [Markdown is already in the collection](https://simpleicons.org/?q=markdown), any specific reason why you want to add CommonMark separately?

**Comment by PeterShaggyNoble** [comment]
Just picking up an [old, abandoned PR](https://github.com/simple-icons/simple-icons/pull/1102). Plus it's an excuse for us to add the outlined version of the Markdown icon for those that may prefer it.

**Comment by PeterShaggyNoble** [comment]
[Stack Exchange recently switched to CommonMark](https://meta.stackexchange.com/questions/348746/), which may be a case in favour of adding this one to help differentiate between the two "flavours".

**Comment by mondeja** [comment]
Alexa rank of https://commonmark.org is [126,941](https://www.alexa.com/siteinfo/commonmark.org). I agree whit this inclusion, any thoughs against this?

**Comment by ericcornelissen** [comment]
I had forgotten about this PR, thanks for bringing it back to my attention @mondeja. Though I'm personally not in fan, so far it seems to be 2 against 1 :sweat_smile: I can see why this _could_ be added in addition to the MarkDown icon itself. So, if you reviewed the icon, @mondeja, feel free to merge this in :+1:

**Comment by mondeja** [comment]
I have thought more time about this inclusion and I don't think I agree to include it either. I'm closing this, if someone else really wants this inclusion, please reopen or comment here.

**Pull request closed without merging**
