### PR TITLE
Add Spine

### LINKED ISSUE #10220: Request: EsotericSoftware
### Brand Name

EsotericSoftware

### Website

https://esotericsoftware.com/

### Popularity Metric

Stars: https://github.com/EsotericSoftware/spine-runtimes/

### Official Resources for Icon and Color

Badges & color: https://esotericsoftware.com/branding

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by RampantDespair**
image

**Issue:** #10220

**Similarweb rank:** [271936](https://www.similarweb.com/es/website/esotericsoftware.com)

### Checklist
- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
Branding: https://esotericsoftware.com/branding
Added both icons respecting the guidelines and using the colors provided by the brand link above.

### CODE REVIEW

**Comment by RampantDespair** [comment]
Both svg icons now comply with the Lint checks.

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
Thanks for the contributions, @RampantDespair 👍🏻 The Spine icon as it is is perfect but I'm seeing [some differences](https://github.com/simple-icons/simple-icons/assets/15157491/3fb7924b-bd4b-4a4b-a0bb-e070168081d2) in your version (in red) of the Esoteric icon. It looks like it might have become vertically stretched; the source isn't a perfect square.

_However_, I think we should be including the background squares in both icons as they're included in the official SVGs.

Also, the source URL in both cases should be https://esotericsoftware.com/branding and a `guidelines` entry should also be added using the same URL.

**Comment by RampantDespair** [comment]
@PeterShaggyNoble 
> Thanks for the contributions, @RampantDespair 👍🏻 The Spine icon as it is is perfect but I'm seeing [some diffences](https://github.com/simple-icons/simple-icons/assets/15157491/3fb7924b-bd4b-4a4b-a0bb-e070168081d2) in your version (in red) of the Esoteric icon. It looks like it might have become vertically stretched; the source isn't a perfect square.
> 
> _However_, I think we should be including the background squares in both icons as they're included in the official SVGs.
> 
> Also, the source URL in both cases should be [esotericsoftware.com/branding](https://esotericsoftware.com/branding) and a `guidelines` entry should also be added using the same URL.

Yes I had a couple of issues when attempting to scale the Esoteric Software logo, I shall revisit it to attempt to fix the scaling issue once more.
As for the backgrounds, how do you want me to go about it? Do you want me to force a specific color, because I noticed there is only one color parameter for logos... So if both inherit the fill color, it'll always end up being a square.
And I will update the url entries following your requested changes.

**Comment by RampantDespair** [comment]
I'm unable to scale the EsotericSoftware logo while preserving the ratio, because for some reason my editor always adds .001 to the width...
That being said I scaled it manually to:
`24 x 23.8060046189`
Hopefully this works, otherwise I am out of ideas.

**Comment by PeterShaggyNoble** [comment]
> As for the backgrounds, how do you want me to go about it? Do you want me to force a specific color, because I noticed there is only one color parameter for logos

Our icons consist of a single path only, so you would need to cut the icon path out of the background path, giving a result like this:

**Comment by RampantDespair** [comment]
@PeterShaggyNoble 
Hey there, 
I went ahead and asked the brand manager over @[esotericsoftware](https://esotericsoftware.com/) for his opinion on whether or not the background should be included. 
He thinks that the badges look much better *without* the background (hence why their website's favicon is displayed without the background I assume).
See thread [here](https://esotericsoftware.com/forum/d/25405-sheildsio-branding).
He also went ahead and provided a proper 24x24 logo which I uploaded in my last commit.
Let me know if there is anything else I can do.

**Comment by PeterShaggyNoble** [comment]
Great work, @RampantDespair, thanks for reaching out to them.

Will review properly when I'm back at my computer in the morn'. In the meantime, though, could you update the `source` for Esoteric Software to use the thread you linked above? For the benefit of future reviewers.

**Comment by RampantDespair** [comment]
I updated both sources, because the thread pertains to why neither of the logos have a background.
If you only want EsotericSoftware, I can revert the Spine source.
Up to you.

**Comment by PeterShaggyNoble** [comment]
@RampantDespair, our linter appears to be having some issues with the Esoteric Software icon. Could you open a new PR for it, please, and remove it from this one while we investigate, so that it's not blocking Spine from being merged?

**Comment by PeterShaggyNoble** [comment]
So, it turns out the issue is with my software and _not_ the linter 🤦🏻‍♂️ @simple-icons/maintainers, I've reviewed the Esoteric Software icon that was included in this PR and it lines up perfectly with the one we were provided with so that can be merged straight in when @RampantDespair opens a PR for it.

Sorry for the all the messing.

**Comment by RampantDespair** [comment]
@PeterShaggyNoble 
Alright that's great news, I'll revert the title then :)
Also do you have an idea when the icons will be available in production (on your site)?

**Comment by PeterShaggyNoble** [comment]
@RampantDespair, as this PR has been merged, you'll need to create a new one for Esoteric Software.

We release a new version every Sunday, so Spine will be available then and, if you can get the PR submitted before that, so will Esoteric Software. Otherwise, it will be next Sunday.

**Comment by RampantDespair** [comment]
@PeterShaggyNoble 
Ahhhh okay, I misunderstood what you meant.
I'll create a new PR this instant.

**Pull request merged**
