### PR TITLE
Add Google Cast

### LINKED ISSUE #2335: Google Cast
**Name:** Google Cast
**Website:** https://developers.google.com/cast
**Alexa Rank:** n/a (Google subdomain)
**Colour:** Not too sure. Maybe `#000000`? Or Google blue `#4285f4`?
**Official resources for icon and color:** https://developers.google.com/cast/docs/developers (Download at end of page) or https://material.io/resources/icons/?search=cast&icon=cast&style=baseline (Used as their website logo)

[Google Cast](https://github.com/simple-icons/simple-icons/files/4046226/googlecast.zip)

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Google Cast

**Issue:** Closes #2335 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Possible alternative name: Chromecast

~There seems to be a fair few possibilities for the colour. I've gone with the blue in [this logo](https://www.google.com/chromecast/built-in/static/images/chromecast-built-in-logo.svg) found on [this page](https://www.google.com/intl/en_ie/chromecast/built-in/) but it doesn't sit well with me.~ Colour confirmed [here](https://partnermarketinghub.withgoogle.com/#/brands/1OHAdVP-LxljDJEgIshtaCkSVvQHXeLLs/15jSHM75dlnhCrmqsBJ6DHk3zBW5hu8jruzd1qgd_3Ms).

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Updated the name to "Google Cast"; I think "Cast" would be too generic.

**Comment by PeterShaggyNoble** [comment]
@ericcornelissen, there's a `.zip` file available for download at the end of the page I provided as the source URL, which is what I based the version in this PR on. Although, the cast icons or one area that Google seem to be very consistent in.

I've been trying to avoid the marketing hub URLs as sources 'cause they're hideous! 😆 But, you're probably right: as *both* the icon *and* the colour are available there, we should probably use it in this case. Will update shortly.

**Comment by PeterShaggyNoble** [comment]
I think `https://partnermarketinghub.withgoogle.com/#/brands` is a good compromise for when we need to use that site as a source, @ericcornelissen. URL updated.

**Comment by ericcornelissen** [comment]
Thanks @PeterShaggyNoble and thank you once again for the contributions! 🎉 

PS. I will look into why the [labeling action is failing](https://github.com/simple-icons/simple-icons/pull/2352/checks?check_run_id=402757307) 😕

**Pull request merged**
