### PR TITLE
Add Roon

### LINKED ISSUE #9786: RoonLabs
### Brand Name

Roon

### Website

https://roonlabs.com

### Popularity Metric

The Similarweb rank is 86,068.
It is well known brand for Hi-Fi audio manias.
https://www.similarweb.com/website/roonlabs.com

### Official Resources for Icon and Color

None

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Roon

**Issue:** Closes #9786 (cc: https://github.com/Templarian/MaterialDesign/issues/7077)
(Well, ain't that fecking typical, I pick one rejected brand icon request from MDI from over 2 years' worth of a personal backlog, double check it hasn't already been requested here, submit a PR, and _hours_ later discover a request for it here under old branding! 🙄)

**Similarweb rank:** [168948](https://www.similarweb.com/website/roon.app)

### Checklist
- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon from [SVG](https://roonlabs.com/wp-content/uploads/roon_logo.svg) in [source](https://help.roonlabs.com/portal/en/home) footer. Colour from [website](https://roon.app) stylesheet.

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
@PeterShaggyNoble - there's a stroke on the source icon, which can be expanded, merged, and then included in our path. Comparing source in red against your PR in black - I'm seeing the below differences:

image

**Comment by PeterShaggyNoble** [comment]
You're right! I missed that.

But, confusingly, the version in the footer _doesn't_ have the `stroke` 🤔 If we choose to run with the version in the header then we're going to need someone with something other than Inkscape, 'cause [it _really_ doesn't like that `stroke` at all](https://github.com/simple-icons/simple-icons/assets/15157491/235f6bc6-ff4a-4ae3-be09-b1a03c7daf80)! 😮

**Comment by adamrusted** [comment]
> it _really_ doesn't like that `stroke` at all

**Comment by service-paradis** [comment]
They use a bolder icon almost everywhere but for their homepage (ex. social media, https://help.roonlabs.com/portal/en/home, https://blog.roonlabs.com/).

I think it would look better here. https://roonlabs.com/wp-content/uploads/roon_logo.svg that can be found in the footer at https://help.roonlabs.com/portal/en/home might be workable.

**Comment by PeterShaggyNoble** [comment]
Thanks, @service-paradis, I've updated based on that. I can't do better than a precision of 5, though, without the left side of the "n" shifting down 🙁

**Review by service-paradis — CHANGES_REQUESTED** [review]
I'm seeing some differences at the end of the letters `r` and `n`:
image
Can you take another look?

**Review by service-paradis — APPROVED** [review]

**Pull request merged**
