### PR TITLE
Add Wappalyzer icon

### LINKED ISSUE #4993: Add Wappalyzer icon
**Brand Name:** Wappalyzer
**Website:** https://www.wappalyzer.com/
**Alexa rank:** 9,985
  

**Official resources for icon and color:**
Color: `#32067c`
SVG:
```html
<svg width="389px" height="100%" viewBox="0 0 389 97" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" alt="Wappalyzer" class="logo d-block"><title>Logo-White</title><desc>Created with Sketch.</desc><defs></defs><g id="Styleguide" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g id="wappalyzer_rebrand" transform="translate(-317.000000, -1149.000000)" fill="#FFFFFF"><g id="Logo-White" transform="translate(317.000000, 1149.000000)"><g id="Logo-Mark-White"><polygon id="Fill-1" opacity="0.6" points="57.0285 74.6616 6.5385 48.4526 0.0015 53.1396 -0.0005 56.0066 57.0285 96.9046 114.0545 56.0086 114.0585 53.1426 107.5185 48.4526"></polygon><path d="M57.0285,0.0003 L0.0025,40.8963 L-0.0005,43.7633 L57.0285,84.6623 L114.0545,43.7653 L114.0575,40.8983 L57.0285,0.0003 Z M64.4895,40.3623 L57.5365,30.7743 L63.4645,26.4363 L75.8235,44.7273 L70.8465,48.3703 L57.5555,42.8723 L57.4985,42.9133 L65.0675,52.5983 L60.0905,56.2403 L35.0915,47.1963 L41.0385,42.8443 L54.1065,47.9333 L54.1805,47.8783 L46.9285,38.5343 L51.6075,35.1113 L64.4145,40.4173 L64.4895,40.3623 Z" id="Fill-2"></path></g><g id="Wappalyzer" transform="translate(133.000000, 23.905100)"><path d="M57.8766,28.762 C60.5366,28.762 62.6966,26.647 62.6966,23.394 C62.6966,20.257 60.6276,17.983 57.8996,17.983 C55.1256,17.983 53.0106,20.143 53.0106,23.394 C53.0106,26.6 55.0346,28.76 57.8766,28.76 L57.8766,28.762 L57.8766,28.762 Z M69.6996,11.958 L69.6996,34.74 L62.7876,34.74 L62.7876,32.284 L62.6966,32.284 C61.2416,34.194 59.1046,35.172 56.3756,35.172 C50.1006,35.172 45.6446,30.42 45.6446,23.372 C45.6446,16.414 50.1456,11.526 56.0346,11.526 C58.4906,11.526 60.6956,12.481 62.3106,14.368 L62.4016,14.368 L62.4016,11.958 L69.6996,11.958 L69.6996,11.958 Z" id="Fill-4"></path><path d="M91.2316,23.3943 C91.2316,20.1433 89.1166,17.9833 86.3436,17.9833 C83.4326,17.9833 81.3406,20.2563 81.3406,23.3943 C81.3406,26.6453 83.5006,28.7603 86.3656,28.7603 C89.2076,28.7603 91.2316,26.6003 91.2316,23.3943 M98.5986,23.3713 C98.5986,30.4203 94.1196,35.1723 87.8666,35.1723 C85.2516,35.1723 83.2056,34.2173 81.7276,32.5113 L81.6136,32.5113 L81.6136,43.9483 L74.3386,43.9483 L74.3386,11.9573 L81.6366,11.9573 L81.6366,14.4133 L81.7276,14.4133 C83.3646,12.5033 85.6386,11.5253 88.2076,11.5253 C94.0966,11.5253 98.5986,16.4143 98.5986,23.3713" id="Fill-6"></path><path d="M119.1525,23.3943 C119.1525,20.1433 117.0375,17.9833 114.2645,17.9833 C111.3535,17.9833 109.2615,20.2563 109.2615,23.3943 C109.2615,26.6453 111.4215,28.7603 114.2865,28.7603 C117.1285,28.7603 119.1525,26.6003 119.1525,23.3943 M126.5195,23.3713 C126.5195,30.4203 122.0405,35.1723 115.7875,35.1723 C113.1725,35.1723 111.1265,34.2173 109.6485,32.5113 L109.5345,32.5113 L109.5345,43.9483 L102.2595,43.9483 L102.2595,11.9573 L109.5575,11.9573 L109.5575,14.4133 L109.6485,14.4133 C111.2855,12.5033 113.5595,11.5253 116.1285,11.5253 C122.0175,11.5253 126.5195,16.4143 126.5195,23.3713" id="Fill-8"></path><path d="M141.2527,28.762 C143.9127,28.762 146.0727,26.647 146.0727,23.394 C146.0727,20.257 144.0037,17.983 141.2757,17.983 C138.5017,17.983 136.3867,20.143 136.3867,23.394 C136.3867,26.6 138.4107,28.76 141.2527,28.76 L141.2527,28.762 Z M153.0757,11.958 L153.0757,34.74 L146.1637,34.74 L146.1637,32.284 L146.0727,32.284 C144.6177,34.194 142.4807,35.172 139.7517,35.172 C133.4767,35.172 129.0207,30.42 129.0207,23.372 C129.0207,16.414 133.5217,11.526 139.4107,11.526 C141.8667,11.526 144.0717,12.481 145.6867,14.368 L145.7777,14.368 L145.7777,11.958 L153.0757,11.958 Z" id="Fill-10"></path><polygon id="Fill-12" points="157.964 34.74 165.217 34.74 165.217 0.453 157.964 0.453"></polygon><polygon id="Fill-14" points="192.1151 11.9577 180.1551 43.9487 172.9481 43.9487 176.8811 33.1937 167.9911 11.9577 175.5401 11.9577 180.1781 24.3037 180.2921 24.3037 184.6571 11.9577"></polygon><polygon id="Fill-15" points="203.2561 28.783 203.2561 28.874 212.9421 28.874 212.9421 34.74 193.7291 34.74 193.7291 29.874 203.5741 17.892 203.5741 17.801 194.5931 17.801 194.5931 11.958 213.3281 11.958 213.3281 16.778"></polygon><path d="M222.2624,20.9615 L230.7884,20.9165 C230.3114,18.7105 228.8334,17.3465 226.6504,17.3465 C224.4674,17.3465 222.7394,18.6195 222.2624,20.9615 L222.2624,20.9615 Z M237.9284,23.1445 C237.9284,23.7805 237.8144,24.8045 237.7464,25.3045 L222.2394,25.3045 C222.7624,27.8735 225.0134,29.2375 227.6284,29.2375 C229.7424,29.2375 231.5844,28.3055 233.1554,26.4865 L237.0184,30.8295 C235.0874,33.2625 231.5864,35.1725 226.8574,35.1725 C220.1044,35.1725 215.0114,30.3975 215.0114,23.3485 C215.0114,16.4365 219.8994,11.5255 226.5844,11.5255 C233.2234,11.5255 237.9294,16.3685 237.9294,23.1445 L237.9284,23.1445 Z" id="Fill-16"></path><path d="M255.7556,11.5484 L255.7556,19.3924 C255.0966,19.3474 254.4146,19.3474 254.0506,19.3474 C250.5946,19.3474 248.8206,21.5294 248.8206,24.5084 L248.8206,34.7404 L241.5446,34.7404 L241.5446,11.9574 L248.8206,11.9574 L248.8206,15.0044 L248.9116,15.0044 C250.6396,12.7304 253.0046,11.5254 255.5056,11.5254 C255.5736,11.5254 255.6876,11.5254 255.7556,11.5484" id="Fill-17"></path><polygon id="Fill-3" points="47.1903 1.6579 36.8453 34.7399 29.7283 34.7399 24.1803 12.9809 24.1123 12.9809 18.3603 34.7399 11.2433 34.7399 0.8983 1.6579 9.1973 1.6579 14.7903 21.9619 14.8583 21.9619 19.9743 1.6579 28.1823 1.6579 33.2303 21.9619 33.2983 21.9619 38.8913 1.6579"></polygon></g></g></g></g></svg>
```

### PR DESCRIPTION
**Pull request by endermctv**
**Issue:** Fixes #4993 
**Alexa rank:** [10,263](https://www.alexa.com/siteinfo/wappalyzer.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Used the "svg-grabber" Chrome's extension for it's SVG. It prefer to go with `#32067C` color.

### CODE REVIEW

**Comment by endermctv** [comment]
Sorry for the 2 `path` attributes, if I can't put into the icon, it's totally black :(

**Comment by adamrusted** [comment]
Hey @endermctv, thanks for the contribution! 💪
Just having a quick look at this, it looks like as well as there being two paths, the icon itself isn't entirely centered. We also don't allow opacity on the icons in the collection.

Thankfully, it's a relatively easy fix! If you could let me know which vector editing software you're using, I can provide a walkthrough on how to fix it. I agree on the hex - so once we're able to fix the SVG we can look to merge this one in.

**Comment by endermctv** [comment]
Hi @adamrusted!

My vector editing software is Inkscape. But is the image you put in your message resolve my issue? (I think no)

**Comment by adamrusted** [comment]
No, the image itself won't resolve the issue - it was just to show you what the icon should look like for inclusion in Simple Icons. Some of these steps you'll have already done - but I've included them just in case you decide to start from scratch with the icon.

## Inkscape Walkthrough

1. Pull the icon out from the logo - removing any styles to it, so you're left with something like [this](https://user-images.githubusercontent.com/1830867/109395990-44ce7a80-7927-11eb-8f7a-90f9042244bd.png).
2. Group both shapes together and keeping the aspect ratio, resize the largest length (in this case, the width) to [24px](https://user-images.githubusercontent.com/1830867/109396026-7a736380-7927-11eb-9c35-2467a841f8b0.png).
3. Select just the top shape using the `Edit path by nodes` tool, and open the Fill and Stroke panel using `Ctrl+Shift+F`. Here, set the stroke paint to solid, and the stroke style to a width of 1px. In [this example](https://user-images.githubusercontent.com/1830867/109396185-464c7280-7928-11eb-8e1d-8b5330b41b0d.png) I've used red just to show what it should look like.
4. With just the top shape still selected, hit `Ctrl+Alt+C` or `Path -> Stroke to Path` to separate the stroke from the path. You should now have three objects, the 'shadow', the top shape, and the stroke.
5. Deselect everything, and then using the `Edit path by nodes` tool select both the stroke, and the shadow. You can then use `Path -> Difference` or `Ctrl+-` to remove the stroke from the bottom path. It'll turn [fully black](https://user-images.githubusercontent.com/1830867/109396286-af33ea80-7928-11eb-99d9-6d5c336755de.png) at this point, but that's fine.
6. Now you've only got the two shapes remaining, select them both and use `Path -> Combine` or `Ctrl+K` to combine them into a single `<path>` entry. Then, all you need to do is re-size the document/artboard with `File -> Document Properties` to 24px*24px - and make sure your final shape is [centered](https://user-images.githubusercontent.com/1830867/109396379-1a7dbc80-7929-11eb-9a49-d8802c17bc71.png).
7. Save the file, and use [SVGOMG](https://jakearchibald.github.io/svgomg/) with all the default settings to optimize the path with a precision of 4. Make sure the optimized SVG matches the guidelines from [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#4-annotate-the-icon) - and it should be good to go!

If you have any issues, feel free to ask me here 👌

**Comment by endermctv** [comment]
@adamrusted I have a question the 6th point. How do resize the document? I'm not sure of myself (besides Inkscape is in French)

**Comment by adamrusted** [comment]
> @adamrusted I have a question the 6th point. How do resize the document? I'm not sure of myself (besides Inkscape is in French)

Under the File menu in Document properties - there should be a Custom Dimensions option, you can enter it in there.

**Comment by endermctv** [comment]
> and make sure your final shape is centered

@adamrusted How do I can verify that?

**Comment by adamrusted** [comment]
> @adamrusted How do I can verify that?

On the right hand side of my program there is an "Align" panel, which may be hidden under "View" or "Window" if it's not already on the side for you. Make sure it's set to align to document, and not selection - and hit centre vertically and horizontally.

**Comment by endermctv** [comment]
@adamrusted

When I execute the command `npm run svgo -- icons/wappalyzer.svg`, I have `<g>` tags in the SVG file, but why? In the contributing guidelines, it says:

> [5. Check the Icon](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#5-check-the-icon)
>
> ...
>
> - Not contain extraneous elements.
>   - This includes: ..., `g`, etc.

**Comment by adamrusted** [comment]
> @adamrusted
> 
> When I execute the command `npm run svgo -- icons/wappalyzer.svg`, I have `<g>` tags in the SVG file, but why? In the contributing guidelines, it says:
> 
> > [5. Check the Icon](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#5-check-the-icon)
> >
> > ...
> >
> > - Not contain extraneous elements.
> >   - This includes: ..., `g`, etc.

Weird - not sure if it's after you've ran the optimizer - though if there's only one path element, you can safely remove the `<g>` tag on either end.

**Comment by endermctv** [comment]
@adamrusted So I removed the `<g>` tags. I going to execute the test command. If I don't have any errors, I can make a commit (with this pull request)?

**Comment by endermctv** [comment]
Lol there are 2 `<path>` elements: https://pastebin.com/urqnLQW8

**Comment by adamrusted** [comment]
If you update the Pull Request with where you're at, I can take another look at it. It may be the paths didn't merge when you did Ctrl-K, make sure you've got both selected when you do that step 👌

**Comment by endermctv** [comment]
With one or two `<path>` tags it's **totally** the same! So I think my problem is resolved

**Comment by endermctv** [comment]
ok let's gooo

**Comment by adamrusted** [comment]
Hey @endermctv - unfortunately it looks like you've stretched the logo in both directions [in both directions](https://user-images.githubusercontent.com/1830867/109401034-29be3380-7944-11eb-9415-62e4b1a38a3e.png), see yours in red over the source SVG in black - if you could look at this again, and keep the aspect ratio of the icon so it matches the original?

**Comment by endermctv** [comment]
@adamrusted After 1 hour of struggle, I finally succeeded with the Wappalyzer icon! (I think)

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for taking another look at this @endermctv - though unfortunately it looks like the icon is still stretched to fit the box (see your PR in red, with the source file in black) [here](https://user-images.githubusercontent.com/1830867/109427300-9dfee280-79e9-11eb-94d0-38b4406c5731.png).

Here's the path I've got, which is passing the linter and matches the aspect ratio of the original icon - feel free to use it if you like, though I'll need to get another maintainer to review it before it can be merged.

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Wappalyzer icon</title><path d="M24 11.014v-.604L12 1.805 0 10.41v.603l12 8.606 12-8.605zM8.634 10.82l2.75 1.07.016-.01-1.526-1.967.984-.72 2.695 1.116.016-.011-1.463-2.018 1.247-.913 2.6 3.85-1.046.766-2.797-1.157-.012.008 1.593 2.038-1.048.767-5.26-1.903 1.251-.916zm14.418 1.488l.947.679v.603l-12 8.605L0 13.59v-.603l.947-.678 10.761 7.717.292.21.291-.21 10.762-7.717z"/></svg>
```

**Comment by endermctv** [comment]
@adamrusted I make an another commit with your SVG code. You help me a lot!!

**Review by endermctv — COMMENTED** [review]
perfect

**Comment by endermctv** [comment]
@adamrusted I have to wait for a maintainer to come and review my PR?

**Comment by adamrusted** [comment]
> @adamrusted I have to wait for a maintainer to come and review my PR?

Yep - I'll ping the @simple-icons/maintainers group - though it may take a while for it to get reviewed. We're not in any major hurry though, as it wouldn't get released now until next Sunday at the earliest. Hopefully another member of the team can take a look before then.

Thanks again for your work on this one - SVGs can be _really_ awkward to work with until you've got the hang of it! 💪

**Comment by endermctv** [comment]
> Thanks again for your work on this one - SVGs can be really awkward to work with until you've got the hang of it! :muscle:

You're welcome! I like helping communities and repos :)

**Review by PeterShaggyNoble — APPROVED** [review]
This looks perfect to me 👍🏻

Thanks for your continued efforts on it, @endermctv and for your invaluable assistance, @adamrusted.

**Pull request merged**
