### PR TITLE
Add Botble CMS icon

### PR DESCRIPTION
**Pull request by vigstudio**
image

**Similarweb rank:** 370,616
image

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Botble is a CMS based on Laravel Framework that allows you to build websites for any purpose. It has powerful tools for developers to build any kind of website.

### CODE REVIEW

**Comment by LitoMore** [comment]
Hi @vigstudio, where can I find the original SVG file of the logo?

**Comment by LitoMore** [comment]
@vigstudio please share the vector file. Thanks.

**Comment by vigstudio** [comment]
> @vigstudio please share the vector file. Thanks.

should i post it in this comment or do i have to git it in this PR ?
I will send you 2 vector files that I made here

https://www.dropbox.com/s/rxon3z41lwu1r69/Favicon%20Botble.ai?dl=0
https://www.dropbox.com/s/c4m7jqf8le4q2tr/botble.svg?dl=0

**Comment by LitoMore** [comment]
CleanShot 2023-04-28 at 19 17 09@2x

@vigstudio I found some differences between the `.svg` and `.ai` files. Please ensure you don't lose too much precision when converting `.ai` to `.svg`.

**Comment by vigstudio** [comment]
> 
I edited everything. You can check the raw file I uploaded at the link below
https://www.dropbox.com/s/apk9tvmtqc0lbbr/botblecms-raw.zip?dl=0

**Comment by vigstudio** [comment]
image
I tried to convert and optimize the svg so I could lose the minimum precision

**Comment by LitoMore** [comment]
Hi @sangnguyenplus, could you help to review this? Do you think this looks good for your team?

This icon is manually vectorized, so we would appreciate your approval before we merge.

**Comment by sangnguyenplus** [comment]
@LitoMore Yes, it looks good. Please merge this PR.

Thank you @vigstudio @LitoMore

**Review by LitoMore — APPROVED** [review]

**Pull request merged**
