### PR TITLE
feat: add TableCheck logo

### LINKED ISSUE #7695: Request: TableCheck
### Brand Name

TableCheck

### Website

https://www.tablecheck.com

### Popularity Metric

The Similarweb rank is 16,183: https://www.similarweb.com/website/tablecheck.com/#overview

### Official Resources for Icon and Color

svg: https://a.storyblok.com/f/125576/20x20/7541a79b41/logo-img-white.svg
color: #7935D2

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by DragonStuff**
image

**Issue:** closes #7695

**Similarweb rank:** 16,183: https://www.similarweb.com/website/tablecheck.com/#overview
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by yusancky** [comment]
@DragonStuff I could help you deal with the problem. I met it with #7682 , too.

**Comment by DragonStuff** [comment]
@yusancky Please provide any advice you may have! It's definitely appreciated.

**Comment by yusancky** [comment]
I solved some of the questions. :bulb:
But it was still worked badly. :unamused:
It was because it's 19.923 x 19.93 instead of 24 x 24. You can change its size with some applications. :smiley:
_I am so sorry that I cannot help you with this problem._ :sob:

**Comment by DragonStuff** [comment]
All issues resolved! Ready for review.

**Comment by DragonStuff** [comment]
All issues resolved! Ready for review.

CC: @dirien

**Review by dirien — APPROVED** [review]
Hi @DragonStuff,

Thanks for your contribution to simple-icons!

It's a perfect fit:
image

**Pull request merged**
