### PR TITLE
Add NextDNS

### LINKED ISSUE #9009: Icon Request: NextDNS
### Brand Name

NextDNS

### Website

https://nextdns.io

### Popularity Metric

The Similarweb ranking is 29,615. See https://www.similarweb.com/website/nextdns.io/#overview

### Official Resources for Icon and Color

None

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by CodeWithShipraJain**
**Issue:** closes #9009 

**Similarweb rank:** [29,615](https://www.similarweb.com/website/nextdns.io/#overview)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- The hex value is taken as the middle of the gradient as the logo and all the other text are displayed with gradient color.

### CODE REVIEW

**Comment by adamrusted** [comment]
Where did you pull the icon from, @CodeWithShipraJain? Looks like the header image is only a PNG.

**Comment by CodeWithShipraJain** [comment]
> Where did you pull the icon from, @CodeWithShipraJain? Looks like the header image is only a PNG.

It is created keeping PNG as a reference.

**Review by adamrusted — CHANGES_REQUESTED** [review]
I think there's too much of a difference between your PR (black) and the source icon (blue) on this one, I'm afraid @CodeWithShipraJain. Any chance you can have another look?
image

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @CodeWithShipraJain?

**Comment by PeterShaggyNoble** [comment]
Going to ping @rs from the @nextdns team here to see if they have a vector version of the icon that they could provide us with.

**Comment by rs** [comment]
Here it is: nextdns-logo

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to reply, @rs, and for providing us with that file 👍🏻 Much appreciated.

@CodeWithShipraJain, could you give this another go, please, using the SVG above as a starting point?

**Review by PeterShaggyNoble — APPROVED** [review]

**Pull request merged**
