### PR TITLE
Update SVGO Icon

### PR DESCRIPTION
**Pull request by adamrusted**
svgo

**Issue:** N/A
**Alexa rank:** N/A

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Following resolution of discussion at https://github.com/svg/svgo/issues/1336, I've drafted an update to the SVGO icon in our collection. Hex is the [calculated midpoint](https://meyerweb.com/eric/tools/color-blend/#45AFE4:364F9E:1:hex) of the gradient used. Happy for this to sit unmerged until SVGO officially launch the new logo _(it's currently sat in a branch on the main repo)_.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Can you take another look at this one, @adamrusted? They [added the new logo](https://github.com/svg/svgo/pull/1389) shortly after you opened this PR and I'm noticing some small differences between your version and the 3 originals I compared against.

**Comment by adamrusted** [comment]
@PeterShaggyNoble that's the logo I was working off 😅

I'm using https://github.com/svg/svgo/blob/master/logo/isotype.svg as my reference.

**Comment by PeterShaggyNoble** [comment]
Most all the differences I'm seeing are in the circles ([example](https://user-images.githubusercontent.com/15157491/109531090-60648d00-7aaf-11eb-834f-0b92ba44883d.png) so it might just be a precision issue.

**Comment by adamrusted** [comment]
@PeterShaggyNoble give that a go - rebuilt from the colour isotype variation with some simplification of the inner path - output at 4 decimals.

**Comment by PeterShaggyNoble** [comment]
Still seeing [some minor differences](https://user-images.githubusercontent.com/15157491/109677949-12fd2400-7b72-11eb-87f0-0acfeffd078b.png) in the inner part of the cog, @adamrusted.

Also, don't forget to update the source to https://github.com/svg/svgo/blob/93a5db197ca32990131bf41becf2e002bb0841bf/logo/isotype.svg and undo the changes in `svgo.config.js`.

**Comment by adamrusted** [comment]
Give that a try @PeterShaggyNoble - helps if I push to this branch and not the Trino one!

**Review by PeterShaggyNoble — APPROVED** [review]
Looks perfect to me now, @adamrusted :+1: Nice one.

I was also, sadly, unable to get the precision down to 3.

**Pull request merged**
