### PR TITLE
Update Sublime Text

### PR DESCRIPTION
**Pull request by fbernhart**
sublimetext

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
LGTM!

Could you get this down to 3 decimals? 🙏🏻

**Comment by fbernhart** [comment]
@adamrusted Done 👍🏼

**Review by adamrusted — CHANGES_REQUESTED** [review]
There's some slight differences between PR (red) and source (black) - might be down to the optimization, so 4 decimals may be needed after all!

image

**Comment by fbernhart** [comment]
@adamrusted Should be fine now. I've rebuilt it from source now instead of using the version of SImple Icons. 😊

**Review by adamrusted — APPROVED** [review]
LGTM!

**Pull request merged**
