### PR TITLE
Add CodersRank icon

### LINKED ISSUE #2863: CodersRank
**Name:** CodersRank
**Website:** https://codersrank.io/
**Official resources for icon and color:** [Official website, already in SVG format](https://111201-1031849-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2019/11/cr-logo-horizontal-1.svg)

### PR DESCRIPTION
**Pull request by greenled**
codersrank

**Issue:** Closes #2863

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

It renders fine in Firefox and Chrome, but in Gnome Desktop renders distorted. It happens to several other icons in the repo so I guess it is not too important.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one on, @greenled :+1:

Could you try it with a higher precision, though? There are some hairline differences between your version and the original. For example, with your version in red:


The problem you're experiencing is known issue with SVGO(MG) (see #2061 for more details) which we (@runxel!) can fix for you before merging.

**Comment by greenled** [comment]
You're welcome @PeterShaggyNoble. I did it again, this time with the Inkscape plugin mentioned by @ericcornelissen in https://github.com/simple-icons/simple-icons/issues/2061#issuecomment-566209296

**Comment by greenled** [comment]
Good news are using the plugin the icon displays correctly everywhere.

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @greenled.

Unfortunately, though, it looks like this is one of those tricky icons that requires even higher precision as it's coming in at `24.003` in width now.

**Comment by greenled** [comment]
> **Edit:** Gave it a stab myself and managed to get the precision down to `3`. Path data is below if you want to use it:
> 
> ```
> M23.134 8.64l-5.973-3.62a.286.286 0 0 0-.412.125l-1.4 3.286 2.842 1.696a.53.53 0 0 1 0 .921l-5.335 3.14-2.267 5.274a.127.127 0 0 0 .052.203.122.122 0 0 0 .134-.035l3.914-2.365 1.545 2.219a.373.373 0 0 0 .309.167h3.708a.367.367 0 0 0 .327-.2.382.382 0 0 0-.018-.386l-2.513-3.852 5.088-3.077c.577-.349.865-.74.865-1.172V9.813c0-.433-.288-.823-.866-1.172zM13.082 4.35L.845 12.052c-.577.348-.858.739-.845 1.171v1.173c.014.432.303.816.866 1.15l6.056 3.496a.286.286 0 0 0 .412-.146l1.36-3.286-2.884-1.633a.518.518 0 0 1-.275-.384.529.529 0 0 1 .254-.537l5.295-3.245 2.183-5.316a.128.128 0 0 0-.04-.142.122.122 0 0 0-.146-.005z
> ```

Thanks, that's very helpful. Here is an update with your path data and a 24px width.

**Comment by PeterShaggyNoble** [comment]
As you're using my path, we'll need one of the other @simple-icons/maintainers to throw an eye over it before merging and to check that the optimised path isn't causing issues in Illustrator, etc. as the original was.

**Comment by greenled** [comment]
> As you're using my path, we'll need one of the other @simple-icons/maintainers to throw an eye over it before merging and to check that the optimised path isn't causing issues in Illustrator, etc. as the original was.

I can confirm it looks good in Inkscape.

**Comment by greenled** [comment]
By the way @PeterShaggyNoble, how did you optimize the icon? I tried online SVGO with a precision of 3 and 4 and it sometimes looked distorted as commented above.

**Comment by PeterShaggyNoble** [comment]
I'm using [this plugin](https://github.com/konsumer/inkscape-svgo) for Inkscape, @greenled.

**Comment by greenled** [comment]
You're welcome @runxel !

**Pull request merged**
