### PR TITLE
add NumPy icon

### PR DESCRIPTION
**Pull request by rajrohanyadav**
**Issue:**#3529
**Alexa rank:**14,027
  

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

I chose Website accent color as the hex value. SVG logo was taken from the official website.

### CODE REVIEW

**Review by ericcornelissen — CHANGES_REQUESTED** [review]
Thanks for taking the time to contribute @rajrohanyadav, and nice job on figuring out why the build failed 👍 

I have a question w.r.t. the SVG. [The SVG you linked in the original issue](https://numpy.org/images/logos/numpy.svg) **is not** square, but the SVG you contributed **is** square (see the comparison below, red is the original). Could you correct this so that the original dimensions of the logo are maintained (within a 24x24 canvas)?

Also, where on the website exactly can I find the color you specified (`#013243`)? Also, @NovaGL, why did you suggest `#4d77cf` or `#4dabcf` as brand colors?

comparison

**Comment by NovaGL** [comment]
Hi @ericcornelissen 
When suggesting colors I just provide the colors used in the SVG and nothing else, if the contributor feels there are more suitable colors its up to their discretion.

I agree that `#013243` is a better choice in this case as it seems to be the main color used on the website. For example its the background color used for the footer.

**Comment by ericcornelissen** [comment]
@rajrohanyadav I see you updated the contribution. However, now it looks like the icon is not scaled to fit the viewbox, as stated in [the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#2-extract-the-icon-from-the-logo):

> Scale the icon to fit the viewbox, while preserving the icon's original proportions. This means the icon should be touching at least two sides of the viewbox.

**Comment by rajrohanyadav** [comment]
Hey @ericcornelissen Original ratio of the icon was 18.59 * 19.87. If I scale it, it does not fit the box exactly. Also, centering is also failing. I'm using figma. I'd really like to do it, can you tell if figma is ok, or I should use something else.
Also, you said while touching atleast two sides, if I try to accomplish that should it be at the cost of centering.
Thankyou.

**Comment by rajrohanyadav** [comment]
hey @ericcornelissen Thankyou for your help, I fixed the dimension and scaling.
The only issue is:
For maintaining the logo ratio, I resized it to 22.46 * 24
Now I don't find a way to center it perfectly unless I resize it to 22 * 24.
Can you please help. Thankyou

**Comment by rajrohanyadav** [comment]
Hey @ericcornelissen I'm getting center at (11.998, 12), which is causing fail. I am using Figma which has only 2 decimal places accuracy. Should I use some other program?
Thankyou

**Comment by ericcornelissen** [comment]
@rajrohanyadav you could try changing the location entirely and manually setting it so that the center is at 12x12, or you could maybe try [Inkscape](https://inkscape.org/) (with which I don't have experience) instead. Do also note that the SVGO(MG) optimization may be causing the SVG to be off-center. You can see if this is the case by increasing the precision that SVGO uses. Hope that helps :slightly_smiling_face:

**Comment by rajrohanyadav** [comment]
Hey @ericcornelissen and @NovaGL many thanks for your help. I think I've done it right this time. 
Maybe next time I won't need to ask so many questions.
I chose `#013243` because the brand name, the primary action button as well as the footer are of this color. It seems to be the accent color of the brand.

**Review by ericcornelissen — APPROVED** [review]
> many thanks for your help. I think I've done it right this time.
> Maybe next time I won't need to ask so many questions.

Yes, awesome :tada: It's not a problem that you ask questions :smile: Many thanks for the contribution!

> I chose `#013243` because the brand name, the primary action button as well as the footer are of this color. It seems to be the accent color of the brand.

Okay, thanks for the clarification. Given that @NovaGL agrees as well I complete fine merging this as is :+1:

**Pull request merged**
