### PR TITLE
Add Puppet icon

### LINKED ISSUE #2693: Puppet
**Name:** Puppet
**Website:** https://puppet.com
**Official resources for icon and color:** https://puppet.com/company/press-room/

### PR DESCRIPTION
**Pull request by DavidS**
Closes #2693

**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The logo is manually converted in inkscape from the `Puppet-Logo-Mark-Black.eps` file in the media kit on the puppet homepage. The color code is the corporate amber.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @DavidS and thanks for the contribution.

The SVG looks good to me, other than the fact that it needs to be centred horizontally.

Can I ask, though, where you sourced the colour? I get `#ffae1a` from the website's stylesheet & [SVG](https://d33wubrfki0l68.cloudfront.net/e46ed8979bef8e39f838fd07006ad4daa22a4fde/d3f2d/images/logos/puppet-logo-white.svg) in the footer and `#f9a512` from the amber logomark in their media kit (although CMYK -> HEX is often not exact).

**Comment by DavidS** [comment]
Thanks for cross-checking that colour. I'll fix that and the centring.

**Comment by DavidS** [comment]
According to the media kit at https://puppet.com/company/press-room/, `#ffae1a` is the correct colour:

2020-03-09_15MS+0000_429x210

**Comment by PeterShaggyNoble** [comment]
This looks good to me now, @DavidS - thanks for your work on it :+1:

**Pull request merged**
