### PR TITLE
Add VOX

### PR DESCRIPTION
**Pull request by vigonotion**
**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Color was extracted from primary color of their website (https://www.vox.de/)

### CODE REVIEW

**Comment by foo-dogsquared** [comment]
Alexa ranking: [~61k](https://www.alexa.com/siteinfo/vox.de) 

Take note there is a similar site called [Vox](https://www.vox.com/) that tackles on news/opinions and it seems to be unrelated with each other based on my quick search here. 
Can you confirm this, @vigonotion ?

**Comment by vigonotion** [comment]
Yes, they are completely unrelated. They are written differently though (VOX and Vox).

Shall I add some kind of suffix? But there is no official suffix (like TV or DE).

**Comment by foo-dogsquared** [comment]
Personally, I would go with the suffix 'TV' (making it 'VOX TV'). 
Though, my input is not enough. 

I'll wait for the other @simple-icons/maintainers to see their take on this.

**Comment by PeterShaggyNoble** [comment]
I think we should go ahead and add this one as just "VOX". We're a fair few icons deep on this project without (as far as I can see) having had any clashes in brand names.

If and when the time comes that such a clash does arise, we can address it then.

Of course, Sod's Law dictates that, now that I've said that, someone's going to immediately request a vox.com icon!

**Comment by ericcornelissen** [comment]
I don't think it is unlikely the vox.com icon will be requested and ideally we deal with name clashes before that happens, as it will likely result in backwards compatibility issues 😞 That said, I'm really not sure how we would do that. I opened #2260 to discuss this further. In the meanwhile I will mark this with "Awaiting replay" and I don't think we should merge this in until we found a suitable solution.

**Comment by PeterShaggyNoble** [comment]
Coming back to this one again, I don't think that #2260 should block us merging it as I think whatever we do do avoid name clashes should be done on a "first come, first served" basis, as best we can. For example, should the other Vox ever be added, we could quite easily solve the problem in this case by calling that one "Vox.com". Thoughts, @simple-icons/maintainers?

**Comment by PeterShaggyNoble** [comment]
As there have been no objections, I'm going to invoke the "first-come, first-served" rule here and _finally_ get around to reviewing this one! 😆

Taking the source SVG as-is, there are quite a few differences between your version (in green below) and it, @vigonotion - could you look into those, please?

Also, since this PR was opened, we have changed our requirements for source URLs from Wikpedia & Wikimedia; they should now link to the _file's_ page rather than the brands so could you update the URL in your JSON to https://commons.wikimedia.org/wiki/File:VOX_Logo_2013.svg?

**Comment by vigonotion** [comment]
I used the 1993 logo, because it was already (almost) monochrome. But if desired, I redo the icon based on the current logo

**Comment by PeterShaggyNoble** [comment]
Yeas, we should go with the latest version. Warning, though: That SVG is a mess of multiple paths and there is an `<image>` tag sitting on top of the `<path>` tags of the circle that is slightly larger than the paths underneath.

Before you go to the effort, though, you could try doing a visual comparison between your version and [the logo from their website](https://www.vox.de/css/images/vox_logo.png) as, just by eyeballing it, the circle doe appear to be _slightly_ smaller there than in the latest version on Wikimedia.

Alternatively, this version can be found in the HTML of their site: https://www.vox.de/safari-pinned-tab.svg It's very poorly Potraced but it might be easier to clean it up than to work with the Wikimedia file.

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @vigonotion?

**Comment by vigonotion** [comment]
Didn't have the time yet, gonna look at this again this weekend as this is probably not a big change

**Comment by vigonotion** [comment]
Sorry it took me so long, but here it is. I used the 2013 logo svg and drew a circle above that red ball (which was an image in the original svg). I eyeballed it, as the circle wasn't even a round circle, but I think this really is good enough.

**Review by ericcornelissen — APPROVED** [review]

**Comment by ericcornelissen** [comment]
The SVG looks good now, unfortunately [the size of the logo is just slightly off](https://travis-ci.com/github/simple-icons/simple-icons/jobs/386610479#L233) (possibly due to optimization). Could you look into this and fix that?

**Comment by adamrusted** [comment]
> The SVG looks good now, unfortunately [the size of the logo is just slightly off](https://travis-ci.com/github/simple-icons/simple-icons/jobs/386610479#L233) (possibly due to optimization). Could you look into this and fix that?

vox

Just chipping in with a path that is passing the linter.

```svg
M24 15.802h-4.129l-1.42-1.754-1.564 1.754H14.12l.103-.05a4.242 4.242 0 0 0 .262-.145c.054-.033.107-.068.161-.103.034-.022.067-.043.1-.066.033-.023.064-.048.096-.072a6.536 6.536 0 0 0 .264-.214 6.058 6.058 0 0 0 .355-.351 3.76 3.76 0 0 0 .223-.269 6.266 6.266 0 0 0 .154-.217 3.108 3.108 0 0 0 .155-.252 4.921 4.921 0 0 0 .221-.447l.055-.135a4.016 4.016 0 0 0 .103-.303 3.019 3.019 0 0 0 .07-.267 3.815 3.815 0 0 0 .058-.309c.008-.05.014-.1.02-.149.006-.047.01-.094.014-.141a4.695 4.695 0 0 0 .016-.267c.001-.053-.002-.106-.002-.16-.001-.053 0-.106-.002-.16l-.006-.081a82.085 82.085 0 0 0-.022-.238l-.012-.089-.014-.093a4.162 4.162 0 0 0-.074-.353l-.024-.091-.036-.122a2.957 2.957 0 0 0-.089-.255 9.635 9.635 0 0 0-.061-.152c-.012-.028-.023-.057-.036-.085-.017-.038-.037-.076-.056-.113-.03-.06-.059-.119-.091-.178a3.958 3.958 0 0 0-.329-.508 4.357 4.357 0 0 0-.174-.216c-.039-.046-.08-.09-.121-.135a1.682 1.682 0 0 0-.148-.15c-.046-.043-.091-.086-.138-.128a5.26 5.26 0 0 0-.355-.282c-.031-.022-.063-.042-.095-.063-.032-.021-.063-.043-.095-.063l-.089-.053c-.036-.022-.072-.044-.109-.064l-.026-.014h3.185l.931 1.248.952-1.248h4.173l-3.088 3.572L24 15.802zM10.205 8.198H7.112l-1.678 3.216-1.705-3.216H0l4.182 7.603h2.442l1.527-2.732-.025-.084c-.013-.047-.023-.095-.033-.142a5.524 5.524 0 0 1-.049-.272c-.008-.052-.014-.105-.02-.158l-.015-.156c-.002-.026-.005-.052-.006-.079-.003-.054-.002-.11-.002-.166-.001-.056-.004-.112-.003-.168l.005-.095c.003-.055.006-.11.011-.166a2.52 2.52 0 0 1 .012-.125l.016-.127.026-.162a4.078 4.078 0 0 1 .062-.285l.04-.147.05-.16.044-.127.036-.095.048-.115c.014-.033.028-.066.044-.099.02-.043.041-.085.063-.127l.058-.111.023-.042.029-.053.035-.059.049-.079.067-.103.073-.105.066-.09a6.9 6.9 0 0 1 .069-.089l.071-.087.079-.091c.036-.041.073-.08.11-.12l.064-.067c.029-.029.06-.056.09-.084a6.042 6.042 0 0 1 .265-.232 3.47 3.47 0 0 1 .119-.093c.041-.031.082-.06.124-.09.039-.028.079-.054.119-.081l.108-.068c.028-.017.056-.036.086-.051.015-.008.046-.02.046-.021zm2.075 1.59a2.132 2.132 0 1 0 0 4.264 2.132 2.132 0 0 0 0-4.264z
```

If another @simple-icons/maintainers can okay this path, then feel free to use it 😁

**Comment by PeterShaggyNoble** [comment]
Man, I can't believe this one's still going, over a year later 😆

@adamrusted, in the interests of getting this off our plate (and finally giving @vigonotion some peace!), I don't think anyone would object to you pushing your version directly to the branch and we'll take it from there.

**Comment by adamrusted** [comment]
@PeterShaggyNoble sorted - if another @simple-icons/maintainers could take a look at this, we may be able to *finally* get it merged!

**Comment by vigonotion** [comment]
Thaaaank you @adamrusted, that thing was a journey 😄

**Comment by fbernhart** [comment]
@adamrusted I can see a slight difference between your version (red) and the source (black). Probably due to optimizing it and the circle only having two points.
image

On the other hand, the V and X have A LOT of points, that probably aren't really needed. Would be worth it simplifying it a bit in my opinion.

image


I've created a simplified path (with a precision of 3) that should still match perfectly the source, while it only has 1/4 of file size.

```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>VOX icon</title><path d="M0 8.198l4.182 7.604h2.442L8.15 13.07a4.276 4.276 0 0 1 2.054-4.872H7.112l-1.677 3.216-1.706-3.216zm14.342 0a4.24 4.24 0 0 1 1.923 2.206c.784 2.081-.098 4.415-2.145 5.398h2.767l1.564-1.754 1.42 1.754H24l-3.505-4.032 3.088-3.572H19.41l-.952 1.249-.931-1.249zm-2.09 1.596c-.949 0-1.913.69-2.074 1.775a2.132 2.132 0 0 0 2.064 2.483c1.268.01 2.192-1.126 2.156-2.18-.013-1.015-.877-2.08-2.146-2.078z"/></svg>
```

Could you review it and if it matches the source push it and merge it? 😊

**Review by adamrusted — APPROVED** [review]
Spot on @fbernhart!
Thanks @vigonotion for the work on the original PR, hopefully now you can rest easy at night! 😆 

**EDIT:** would help if I pushed the new SVG before trying to merge it, wouldn't it?

**Pull request merged**
