### PR TITLE
GIPHY

### PR DESCRIPTION
**Pull request by suvozit**
**Issue:** GIPHY #3414
**Alexa rank:** 392 (Global, October 2019)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Where did you pick the hex value?
https://support.giphy.com/hc/en-us/articles/360022283772-GIPHY-Brand-Guidelines

### CODE REVIEW

**Comment by runxel** [comment]
Hi @suvozit! Thank you and congratulations for your first PR here! 🥳 
However there some small issues with the svg: As you can see the build is currently failing. That's because we don't allow our svg to have extraneous attributes, like the `fill-rule` present in your svg.
Also the title says "Photoshop" 😉 This needs to be fixed as well.

Thanks again for your work and time on it!

**Comment by suvozit** [comment]
Hi @runxel I have submitted the changes 🙇🏻‍♂️

**Comment by runxel** [comment]
Hey again! I've looked at it, and on the Brand Guidelines as well.
Two things: Take the link to the guideline as source. (I'm sorry I didn't catched that earlier)
And then I don't quite understand why you took the Wikipedia one to begin with? The icon provided in their dropbox
looks substantilly different, as you can see here:

Zeichenfläche 1@4x

**Comment by suvozit** [comment]
@runxel But when monochrome it'll look the same. I took the icon from the [Brand Guidelines](https://support.giphy.com/hc/en-us/articles/360022283772-GIPHY-Brand-Guidelines) as mentioned.

GIPHY icon Square

**Comment by runxel** [comment]
If you click on "Download icons" on the brand guideline page it takes you to a Dropbox folder. 
Did you take the logo from there? Because – again – their version and your's doesn't match up. 🙈

**Comment by suvozit** [comment]
@runxel the icon is now according to the brand guidelines

**Comment by runxel** [comment]
Yes, great work! 💯 
Thanks for your patience and doing the job! I will gladly merge this in.

<small>Please note: I've changed the link from Wikipedia back to the brand guidelines.</small>

**Pull request merged**
