### PR TITLE
Kakaotalk icon

### PR DESCRIPTION
**Pull request by jlnrrg**
107856704-e3d07e00-6e21-11eb-84fa-f9c08fb11a79
**Issue:** #4923 
**Alexa rank:** [13,761](https://www.alexa.com/siteinfo/kakaocorp.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

Credits go towards @adamrusted (#4979)

### CODE REVIEW

**Comment by adamrusted** [comment]
That was a fast re-submission @jlnrrg 😅🚀

Could another @simple-icons/maintainers take a look at this one, being as I worked on the path?

**Comment by PeterShaggyNoble** [comment]
I think we'll need too go with the boxed version here; I haven't seen the speech bubble in use on its own anywhere.

**Comment by adamrusted** [comment]
@jlnrrg for reference, I've been able to generate the below 3 decimal path with the box - as requested by @PeterShaggyNoble. You're welcome to use it.

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>KakaoTalk icon</title><path d="M22.125 0H1.875C.839 0 0 .84 0 1.875v20.25C0 23.161.84 24 1.875 24h20.25C23.161 24 24 23.16 24 22.125V1.875C24 .839 23.16 0 22.125 0zM12 18.75c-.591 0-1.17-.041-1.732-.12-.562.396-3.813 2.679-4.12 2.722 0 0-.125.049-.232-.014s-.088-.229-.088-.229c.032-.22.843-3.018.992-3.533-2.745-1.36-4.57-3.769-4.57-6.513 0-4.246 4.365-7.688 9.75-7.688s9.75 3.442 9.75 7.688c0 4.245-4.365 7.687-9.75 7.687zm-1.313-9.428c-.095-.27-.383-.548-.75-.556-.366.008-.654.286-.749.555l-1.345 3.541c-.171.53-.022.728.133.8a.857.857 0 0 0 .357.077c.235 0 .414-.095.468-.248l.279-.73h1.715l.279.73c.054.153.233.248.468.248a.86.86 0 0 0 .357-.078c.155-.071.304-.268.133-.8l-1.345-3.54zm-1.311 2.443l.562-1.596.561 1.596H9.376zM8.05 9.867h-.878v3.342c0 .296-.252.537-.563.537s-.562-.24-.562-.537V9.867h-.878a.552.552 0 0 1 0-1.101h2.88a.552.552 0 0 1 0 1.101zm7.231 3.281a.528.528 0 0 1-.539.516h-1.805a.528.528 0 0 1-.539-.516v-3.82c0-.31.258-.562.575-.562s.574.252.574.562v3.305h1.195c.297 0 .54.231.54.515zm3.757-.324a.559.559 0 0 1-.449.901.558.558 0 0 1-.45-.224l-1.319-1.747-.195.195v1.227a.563.563 0 0 1-1.125 0V9.328a.563.563 0 0 1 1.125 0v1.21l1.57-1.57a.437.437 0 0 1 .311-.126c.14 0 .282.061.388.167a.555.555 0 0 1 .165.356.438.438 0 0 1-.124.343l-1.282 1.281 1.385 1.835z"/></svg>
```

kakaotalk

**Comment by PeterShaggyNoble** [comment]
The colour should probably be [Kakao](https://github.com/simple-icons/simple-icons/pull/3192)'s yellow `#ffcd00`, which they actually first used for Kakao Talk.

**Comment by jlnrrg** [comment]
@adamrusted @PeterShaggyNoble thank you for spending the effort in my stead

**Comment by adamrusted** [comment]
@PeterShaggyNoble - could you review this one, given the path is one I helped with?

**Comment by PeterShaggyNoble** [comment]
I'm seeing a couple of differences in the letters, most noticeably in the "T"'s horizontal and the "K"'s vertical:

(PR version in red)

**Comment by adamrusted** [comment]
This should fix it @PeterShaggyNoble - had to go to 4 decimals of precision to get the round edges working properly. 3 would result in the same issue as above.

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>KakaoTalk icon</title><path d="M22.125 0H1.875C.8394 0 0 .8394 0 1.875v20.25C0 23.1606.8394 24 1.875 24h20.25C23.1606 24 24 23.1606 24 22.125V1.875C24 .8394 23.1606 0 22.125 0zM12 18.75c-.591 0-1.1697-.0413-1.7317-.1209-.5626.3965-3.813 2.6797-4.1198 2.7225 0 0-.1258.0489-.2328-.0141s-.0876-.2282-.0876-.2282c.0322-.2198.8426-3.0183.992-3.5333-2.7452-1.36-4.5701-3.7686-4.5701-6.5135C2.25 6.8168 6.6152 3.375 12 3.375s9.75 3.4418 9.75 7.6875c0 4.2457-4.3652 7.6875-9.75 7.6875zM8.0496 9.8672h-.8777v3.3417c0 .2963-.2523.5372-.5625.5372s-.5625-.2409-.5625-.5372V9.8672h-.8777c-.3044 0-.552-.2471-.552-.5508s.2477-.5508.552-.5508h2.8804c.3044 0 .552.2471.552.5508s-.2477.5508-.552.5508zm10.9879 2.9566a.558.558 0 0 1 .108.4167.5588.5588 0 0 1-.2183.371.5572.5572 0 0 1-.3383.1135.558.558 0 0 1-.4493-.2236l-1.3192-1.7479-.1952.1952v1.2273a.5635.5635 0 0 1-.5627.5628.563.563 0 0 1-.5625-.5625V9.3281c0-.3102.2523-.5625.5625-.5625s.5625.2523.5625.5625v1.209l1.5694-1.5694c.0807-.0807.1916-.1252.312-.1252.1404 0 .2814.0606.3871.1661.0985.0984.1573.2251.1654.3566.0082.1327-.036.2542-.1241.3425l-1.2818 1.2817 1.3845 1.8344zm-8.3502-3.5023c-.095-.2699-.3829-.5475-.7503-.5557-.3663.0083-.6542.2858-.749.5551l-1.3455 3.5415c-.1708.5305-.0217.7272.1333.7988a.8568.8568 0 0 0 .3576.0776c.2346 0 .4139-.0952.4678-.2481l.2787-.7297 1.7152.0001.2785.7292c.0541.1532.2335.2484.4681.2484a.8601.8601 0 0 0 .3576-.0775c.1551-.0713.3041-.2681.1329-.7999l-1.3449-3.5398zm-1.3116 2.4433l.5618-1.5961.5618 1.5961H9.3757zm5.9056 1.3836c0 .2843-.2418.5156-.5391.5156h-1.8047c-.2973 0-.5391-.2314-.5391-.5156V9.3281c0-.3102.2576-.5625.5742-.5625s.5742.2523.5742.5625v3.3047h1.1953c.2974 0 .5392.2314.5392.5156z"/></svg>
```

**Review by PeterShaggyNoble — APPROVED** [review]
Looks perfect to me now. Gonna push an update for the colour and then this is good to go.

Thanks for your work on this one, @jlnrrg and for your assistance, @adamrusted 👍🏻

**Pull request merged**
