### PR TITLE
Update Buy Me A Coffee icon

### LINKED ISSUE #3782: Buy Me A Coffee Logo Update
**Name:** Buy Me A Coffee
**Official resources for icon and color:**
[Brand Assets.zip](https://github.com/simple-icons/simple-icons/files/5464372/Brand.Assets.zip)

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** Closes #3782
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- I took the SVG from the brand assets file given in #3782.
- I used Inkscape to merge path, fix size and center
- I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
@service-paradis they are now using yellow not orange...

**Comment by service-paradis** [comment]
> @service-paradis they are now using yellow not orange...

image

**Review by mondeja — CHANGES_REQUESTED** [review]
Good job cleaning the path @service-paradis :+1: However, I'm still seeing some points which render nothing and should also be removed:

bmc-opt-2

**Comment by service-paradis** [comment]
> Good job cleaning the path @service-paradis 👍 However, I'm still seeing some points which render nothing and should also be removed:

Thanks for the feedback! Some of those was difficult to remove without messing the path while optimizing, but I will give another shot to clean it a little bit more. Will try to make a new PR soon!

**Comment by service-paradis** [comment]
image
I removed some unnecessary paths. Do you think we should clean it a little more?

**Review by mondeja — APPROVED** [review]

**Comment by mondeja** [comment]
Now it looks very good! Thank you for the quick fix @service-paradis :clap:

**Comment by WarenGonzaga** [comment]
Yey! thanks guys!

**Pull request merged**
