### PR TITLE
Add Aldi

### LINKED ISSUE #10330: Request: Aldi
### Brand Name
Aldi

### Website
https://aldi.de
https://aldi.com
https://aldi.ie
https://aldi.us

### Similarweb Ranks
- aldi.de [197855](https://similarweb.com/website/aldi.de)
- aldi.com [213062](https://www.similarweb.com/website/aldi.com)
- aldi.ie: [51776](https://www.similarweb.com/website/aldi.ie)
- aldi.us: [3771](https://www.similarweb.com/website/aldi.us)

### Official Resources for Icon and Color
SVG in header of [American website](https://www.aldi.us)

### Additional Comments
Outside of Germany Aldi is pretty much just Aldi, no North or South, so neither of our existing icons are suitable for use to people in those countries. The icon we come up with could also be used as the basis for [Hofer](https://github.com/simple-icons/simple-icons/issues/10081).

### PR DESCRIPTION
**Pull request by Garbg**
aldi

**Issue:** closes #10330

**Similarweb rank (for US website):**
Global: 3,681
Country (US): 681
Category: 5

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

This company has several websites for different countries, but I used the stats from www.aldi.us

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Nice find with the trademark guidelines, @Garbg 👍🏻 Unfortunately, though, the line below means we're going to have to seek their permission to add it. Would you like to see if you can make contact with them?

> The trademarks, service marks, copyrighted material, patents and other intellectual property owned or used by ALDI Inc. may not be used by you without the express written consent of ALDI Inc.

**Comment by Garbg** [comment]
I don't want to request permission because I don't know who to ask, and I know nothing about the law.

**Comment by adamrusted** [comment]
>  I don't know who to ask

Looking at their website, [this](https://www.aldi.us/contact/) is probably the best starting point we have.
Could you drop them a message, @Garbg? We can't look to add this icon until we've got permission (previous Aldi icons were added by a former employee of the Schwarz Group).

**Comment by dirien** [comment]
@adamrusted: I don't see anything written for the usage of Aldi (Nord or Süd).

**Comment by PratyushJayachandran** [comment]
> > I don't know who to ask
> 
> Looking at their website, [this](https://www.aldi.us/contact/) is probably the best starting point we have. Could you drop them a message, @Garbg? We can't look to add this icon until we've got permission (previous Aldi icons were added by a former employee of the Schwarz Group).

Looking at [Aldi corporate website where the logo is hosted](https://corporate.aldi.us/newsroom/multimedia-library/aldi-logo/), the terms of use says that:

> Except with the express written consent of ALDI Inc., the materials in this site may be used only for personal, non-commercial purposes.

Refer: https://corporate.aldi.us/newsroom/multimedia-library/terms-of-use/

So, aren't we good to add this @adamrusted?

**Comment by adamrusted** [comment]
> So, aren't we good to add this @adamrusted?

Nope, we can't guarantee our users will use only for personal / non-commercial purposes, and the fact still stands that we'd need written permission from them for any other use case.

**Comment by Garbg** [comment]
I'll close this for now

**Pull request closed without merging**
