### PR TITLE
Add Ingress

### PR DESCRIPTION
**Pull request by MetLee**
image

**Issue:**
**Alexa rank:** [~52.9k](https://www.alexa.com/siteinfo/ingress.com)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the PR, @MetLee. Probably my lack of caffeine but I didn't spot a vector version of this logo at the source URL provided, did you redraw this yourself from a raster file? There _is_ a vector version buried in a font file at https://ingress.com/ that we could use.

**Comment by MetLee** [comment]
> Thanks for the PR, @MetLee. Probably my lack of caffeine but I didn't spot a vector version of this logo at the source URL provided, did you redraw this yourself from a raster file? There _is_ a vector version buried in a font file at https://ingress.com/ that we could use.

https://nianticlabs.com/img/index/logo-ingress-new.png
The last term on https://nianticlabs.com/en/products/ .

**Comment by PeterShaggyNoble** [comment]
Thanks for the info, @MetLee; that's what I'd assumed you'd done 🙂 It _looks_ to me like there are a few differences between that version and your but I am pretty terrible at comparing vector to raster, especially at the level of detail we require so we'll need someone else to double check it.

I did do a comparison with the vector version I mentioned above and there are some differences there too (see screenshot below, with your version in red). The original path data I extracted from the font files is:
```
M13 131h6h1v-1v-54v-1l-1 -1l-6 1l-1 1v54l1 1v0zM91 75h-2l-22 39q-1 1 -1 0v-38q0 -1 -1 -1h-6q-1 0 -1 1v54q0 1 1 1h7h1l23 -39q1 -1 1 0v38q0 1 1 1h6q1 0 1 -1v-54l-1 -1v0h-7zM177 84q-1 -1 -1 -2l-7 -7h-2h-22h-2l-6 7q-1 1 -1 2v38q0 1 1 2l6 7h2h22h2l7 -7v-2
v-7q0 -1 -1 -1h-6l-1 5v2l-2 2h-1h-17h-2l-1 -1q-1 -1 -1 -2v-33q0 -1 1 -2l2 -2h2h15h2l2 2v2v8q0 1 -1 1h-7h-1v1v7l1 1h16q1 -1 1 -2v-19zM247 75q-1 0 -1 1v17q0 1 -1 2l-1 1q-1 1 -2 1h-19l-1 -1v0v-20l-1 -1v-1l-7 1v1v54v1h31h2l7 -7v-2v-16v-2l-3 -3q-1 0 0 -1l2 -3
q1 0 1 -2v-20v0l-1 -1zM246 120q0 1 -1 1l-1 2h-2h-19h-1v-17q0 -1 1 -1h19q1 0 2 1l1 1q1 1 1 2v11zM293 75h-1l-1 1v54q0 1 2 1h39v-1v-6l-31 -1q-1 0 -1 -1v-14q0 -1 1 -1h24v-1v-7h-24q-1 0 -1 -1v-14q0 -1 1 -1l31 -1v0v-7l-1 -1zM410 84q0 -1 -1 -2l-6 -7h-2h-22h-2
l-7 7q-1 1 -1 2v6q0 1 1 1h6q1 0 1 -1v-3q0 -2 1 -2l1 -2h2h17h2l1 1q1 1 1 2v9q0 1 -1 2l-1 1q-1 1 -2 1h-19q-1 0 -2 1l-7 6q-1 1 -1 2v14q0 1 1 2l7 7h2h22h2l6 -7q1 -1 1 -2v-6l-1 -1l-7 1v3q0 2 -1 2l-1 2h-2h-17h-2l-1 -1q0 -1 -1 -2v-9q1 -1 1 -2l1 -1q1 -1 2 -1h20
q1 0 2 -1l6 -6q1 -1 1 -2v-14zM488 84q0 -1 -1 -2l-6 -7h-2h-23h-2l-6 7q-1 1 -1 2v7h1h7v-4q0 -2 1 -2l1 -2h2h17h2l1 1q1 1 1 2v9q0 1 -1 2l-1 1q-1 1 -2 1h-20q-1 0 -2 1l-6 6q-1 1 -1 2v14q0 1 1 2l6 7h2h23h1l7 -7q1 -1 1 -2v-6q0 -1 -1 -1h-6q-1 0 -1 1v3q0 2 -1 2
l-1 2h-2h-17h-2l-1 -1q-1 -1 -1 -2v-9q0 -1 1 -2l1 -1q1 -1 2 -1h20q1 0 1 -1l7 -6q1 -1 1 -2v-14zM125 30q0 2 -2 4l-2 2l-3 1h-25v-32h8v10h18h2q2 1 3 4t1 7v4zM117 25v-3h-2h-14v8h15l1 -1v-2v-2zM198 18v1l1 1q1 1 2 3v4q1 4 -1.5 6.5t-4.5 2.5l-5 1h-21v-32h8v10h12
q1 0 3 -1l1 -1v-8h8v7q0 2 -1 3.5t-2 2.5zM193 26q0 -3 -0.5 -3.5t-3.5 -0.5h-12v8h13q2 0 2.5 -0.5t0.5 -3.5zM246 37h8v-32h-8v32zM338 34q0 3 -3 3h-6q-2 0 -3 -2l-7 -20l-7 20q-1 2 -3 2h-5q-4 0 -4 -3l-2 -29h8l1 21l8 -19q1 -2 4 -2h1q3 0 4 2l7 19l2 -21h8zM392 11v7
h18v6h-18v6h21v7h-29v-33h29v7h-21zM382 421l-125 72q-7 4 -14 0l-125 -72q-7 -4 -7 -12v-144q0 -8 7 -13l125 -71q7 -4 14 0l125 71q7 5 7 13v144q0 8 -7 12zM251 192h-1l-118 69l51 29l-7 12l-51 -30v138l118 68v-60h14v60l118 -68l1 -1v-137l-52 30l-7 -12l52 -29z
M152 393l97 -169h1h1l97 169v1v0h-195h-1v-1zM243 263v0l-60 105l55 -32q6 -3 6 -9zM245 348l-55 32v1h120l1 -1l-56 -32q-5 -3 -11 0h1zM257 263v0v0v64q0 6 5 9l55 32l1 -1z
```

**Comment by PeterShaggyNoble** [comment]
**UPDATE:** I also found this path in the same file, which is just the icon, differs from the full logo above and lines up a bit better with your version.
```
M450 378l-189 109q-11 6 -22 0l-189 -109q-11 -6 -11 -19v-218q0 -13 11 -19l189 -109q11 -6 22 0l189 109q11 6 11 19v218q0 13 -11 19zM251 31h-2l-179 103l78 45l-10 18l-78 -45v207v1l180 104v-90h20v90l179 -104l1 -1v-207l-78 45l-10 -18l78 -45zM101 335l148 -256
q0 -1 1 -1t1 1l148 256v1.5t-1 0.5h-296q-1 0 -1 -0.5v-1.5zM240 139q0 -1 -1 -1l-92 158v1h1l83 -48q9 -5 9 -14v-96zM242 267l-83 48l-1 1h1h183v0l-84 -49q-8 -5 -16 0zM262 138h-1h-1v96q0 10 9 15l83 48h1v-1z
```

**Comment by MetLee** [comment]
Thanks for your check! I used a online tool (https://www.pngtosvg.com/) which lacks professionalism, so there are some difference.

**Comment by mondeja** [comment]
I've vectorized this icon using Inkscape and I can see some differences with your version (red) and mine (black). Please, can you double check this pull @MetLee?

ingress-diff

**Comment by adamrusted** [comment]
@MetLee - I've been able to extract the path from the font file ([found here](https://ingress.com/assets/fonts/ingress_icons.woff)) - ran this path through SVGO and SVGlint, so if you want to use it feel free - either that or I can push this icon to the PR?

```svg
M22.55 6.55v10.9c0 .434-.184.749-.55.95l-9.45 5.45c-.367.2-.733.2-1.1 0L2 18.4c-.366-.201-.55-.516-.55-.95V6.55c0-.434.184-.749.55-.95L11.45.15c.367-.2.733-.2 1.1 0L22 5.6c.366.201.55.516.55.95zM21 17.8l-3.9-2.25.5-.9 3.9 2.249V6.549l-.05-.048-8.95-5.2v4.5h-1v-4.5l-9 5.2v10.398l3.9-2.248.5.899L3 17.8l8.95 5.15h.1L21 17.8zM4.55 7.675c0-.016.016-.025.05-.025h14.8c.033 0 .05.009.05.025v.075l-7.4 12.799c0 .034-.017.05-.05.05-.034 0-.05-.016-.05-.05L4.55 7.75v-.075zm6.95 5.076c0-.301-.15-.533-.45-.7L6.9 9.65h-.05v.05l4.6 7.9c.033 0 .05-.019.05-.051v-4.8zm.9-1.601l4.2-2.45H7.4l.05.051 4.15 2.399a.701.701 0 00.8 0zM17.15 9.7v-.05h-.05l-4.15 2.4c-.3.167-.45.417-.45.749v4.8h.1l4.55-7.899z
```

**Comment by adamrusted** [comment]
@simple-icons/maintainers I've pushed the extracted path onto this PR, so it's ready for another review.

**Comment by fbernhart** [comment]
@adamrusted The path looks perfect! 👍🏼  I've now updated the `source` to point to your mentioned font file.

### Color:

I'm not quite happy with black (`#000000`). Looking at their social media presence they are using a white logo on a violet gradient ([Facebook](https://www.facebook.com/Ingress), [Twitter](https://twitter.com/ingress), [Instagram](https://www.instagram.com/ingress)).

On their website they are using `#783CBD` for CTA elements. So I would either go with this one or just with white (`#FFFFFF`). What do you think?


Here's a preview with  `#783CBD`:

ingress

**Comment by adamrusted** [comment]
@fbernhart I agree on the purple colour. Would you mind pushing that, and if the icon matches up feel free to merge 👍🏻

**Comment by fbernhart** [comment]
@adamrusted Done. 👍🏼 

Thanks to you and as well to @MetLee for the initial work! 🏅

**Pull request merged**
