### PR TITLE
Add Tutanota

### LINKED ISSUE #3186: Tutanota Icon
**Name:** Tutanota
**Website:** https://tutanota.com/
**Official resources for icon and color:** https://raw.githubusercontent.com/tutao/tutanota/master/resources/images/logo-solo-red.svg
**Alexa rank**: [~25,8k](https://www.alexa.com/siteinfo/tutanota.com)

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Tutanota

**Issue:** Closes #3186
**Alexa rank:** [~19.6k](https://www.alexa.com/siteinfo/tutanota.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Fixed a couple of imperfections in this; namely the bottom-left corner being crooked and the line of the right edge not being straight.

### CODE REVIEW

**Review by runxel — COMMENTED** [review]
I wonder if this is really the best treatment, or if rather there should be a small outline in the bottom part so the icon stays in its rounded rectangle.

**Comment by mondeja** [comment]
+1 to @runxel's suggestion

**Comment by mondeja** [comment]
> I think they "kind of" want this effect, no?

Yes, you're right, sorry I've only see the Github icon. So seems that this icon could be added as is. What do you think about @service-paradis has pointed @runxel?

**Comment by runxel** [comment]
Yeah I agree. Seems like they really want it that way.  ¯\_(ツ)_/¯
Feel free to merge!

**Review by mondeja — APPROVED** [review]
Looks right. Thank you @PeterShaggyNoble! :tada:

**Pull request merged**
