### PR TITLE
Nexusmods

### LINKED ISSUE #10311: Request: Nexus Mods
### Brand Name

Nexus Mods

### Website

https://www.nexusmods.com/

### Popularity Metric

Rank: 317

https://www.similarweb.com/website/nexusmods.com/

### Official Resources for Icon and Color

They don't seem to have official brand guidelines.

~~Their logo is present in both header and footer as an inline SVG (so I can't link it here).~~
Their logo is available ins SVG format here: [https://wiki.nexusmods.com/skins/Metrolook/images/nexuslogo.svg](https://wiki.nexusmods.com/skins/Metrolook/images/nexuslogo.svg)
The logo also has what I think is their main brand color, a light orange.

### Additional Comments

It is one of the most popular and important websites about videogame modding.

### PR DESCRIPTION
**Pull request by stefanobartoletti**
**Issue:** closes #10311 

**Similarweb rank:**

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

nexusmods

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one one, @stefanobartoletti.

And, wow, it's much trickier than it first looked! I didn't even notice the black background shape, which complicates things further. Had it been a basic shape, I would have said we could omit it but, as it follows the outline of the icon, I think you're right that we'll need to include it.

I wonder could we simplify it a little bit by doing something like the following? What do you think?

**Comment by stefanobartoletti** [comment]
Thanks for the suggestions, it should be better now, it is way more detailed and recognizable even in small sizes.

nexusmods

**Comment by PeterShaggyNoble** [comment]
Yep, that works much better, @stefanobartoletti - nicely done 👍🏻 I'm not entirely sure about the double border on the inner circle but as that's an entirely subjective opinion, I'll ask the other @simple-icons/maintainers what they think as well.

If we do proceed with the current treatment as-is then I am seeing a few small differences, mostly around the outer edge and the insides of the arrows. Some of those could be account for by the fact that the source icon isn't a perfect square, though, while yours is.

**Comment by LitoMore** [comment]
The icon looks not good on the badge. How about remove the white white background part?

**Comment by PeterShaggyNoble** [comment]
While that _would_ work much better for us, @LitoMore, unfortunately, if you look at the logo in the footer, their favicon and the logos on their social media sites, it definitely looks like the background shape is part of the icon and that we should therefore include it.

**Comment by BlackDahlia313** [comment]
how funny I come across this as soon as i need it. lookin good

**Comment by stefanobartoletti** [comment]
Thanks for your insights! :)

@LitoMore the original icon has that border, as you can see also from their website favicon.

@PeterShaggyNoble about small differences, maybe it can be accounted for having to clean the source svg, which really had a lot of unnecessary vertices, and to adapt a design that was intended to be displayed with multiple colors (so no need of borders) into a monochromatic icon.

Most of the shapes had to be refined both before and after merging them into a single path, maybe this explains the small differences, together with optimization by SVGO (the linter complained and I had to test various precisions).

Because of this, creating this icon was less easy than I thought, and at the moment I am unable to invest more time and effort into it. Especially because in its current state, it is both faithful enough to the source to be recognizable and identifiable at first glance and readable enough to be able to do these things also on small sizes (that is what matters the most). Unfortunately at the moment, I can't work on fixing pixel decimals for something that in the end won't even be noticeable.

This does not mean that you should accept it if it is not up to your standards, just that I cannot personally do any more improvement. Feel free to use it as a base to further enhance it if this is what you need :)

**Comment by adamrusted** [comment]
Gang, how about the below treatment?
I've used two different 'gaps' between colours to give more of a gap between the central circle and the back of the arrows - but otherwise should have everything we're expecting. It will _definitely_ need some cleaning up - that logo isn't a fun one to work with in terms of excess points - but should (I think) give us a good starting point?

image

```
M6.548,23.986C6.46,23.986 6.356,23.986 6.268,23.971C6.047,23.942 5.84,23.898 5.604,23.824C5.191,23.691 4.837,23.499 4.586,23.352C4.025,23.027 3.45,22.629 2.845,22.127C2.58,21.906 2.314,21.67 2.063,21.434L1.857,21.228C1.709,21.095 1.577,20.947 1.473,20.785C1.282,20.49 1.119,20.106 1.105,19.605C1.09,19.442 1.075,19.28 1.075,19.103C1.075,18.749 1.09,18.366 1.149,17.997C1.252,17.23 1.503,16.551 1.695,16.035L1.739,15.902C1.68,15.769 1.636,15.622 1.577,15.474C1.311,14.707 1.134,13.851 1.046,12.996C0.957,12.096 0.986,11.181 1.119,10.281C1.149,10.09 1.178,9.898 1.223,9.721C0.868,9.204 0.426,8.467 0.146,7.611L0.146,7.596C0.087,7.419 -0.061,6.977 0.028,6.416C0.057,6.21 0.101,6.003 0.175,5.782C0.308,5.369 0.5,5.03 0.647,4.779C0.972,4.218 1.37,3.658 1.857,3.053C2.078,2.787 2.299,2.522 2.535,2.286L2.742,2.079C2.845,1.961 2.963,1.858 3.096,1.769C3.391,1.548 3.804,1.356 4.365,1.342C4.542,1.327 4.734,1.312 4.925,1.312L4.94,1.312C5.309,1.312 5.707,1.342 6.091,1.401C6.681,1.489 7.212,1.651 7.684,1.828C7.994,1.696 8.318,1.578 8.658,1.46C9.454,1.194 10.31,1.017 11.166,0.958C12.065,0.884 12.98,0.928 13.85,1.076C14.057,1.105 14.263,1.15 14.47,1.194C15.163,0.722 15.798,0.383 16.462,0.176L16.476,0.176C16.624,0.117 16.948,0.014 17.376,0.014C17.465,0.014 17.568,0.014 17.656,0.029C17.878,0.058 18.084,0.102 18.32,0.176C18.733,0.309 19.087,0.501 19.338,0.648C19.899,0.973 20.474,1.371 21.079,1.873C21.345,2.094 21.61,2.33 21.861,2.566L22.067,2.772C22.171,2.861 22.274,2.964 22.348,3.082C22.613,3.422 22.82,3.908 22.835,4.587C22.849,4.823 22.849,5.074 22.835,5.325C22.805,5.87 22.731,6.387 22.598,6.859C22.495,7.213 22.377,7.567 22.244,7.921C22.51,8.585 22.702,9.263 22.835,9.957C23.1,11.417 23.071,12.922 22.746,14.368C22.938,14.648 23.115,14.914 23.262,15.179C23.513,15.622 23.72,16.079 23.867,16.551C23.926,16.728 24.059,17.171 23.97,17.761C23.941,17.967 23.882,18.159 23.808,18.38C23.543,19.133 23.13,19.752 22.761,20.269C22.362,20.829 21.905,21.375 21.433,21.877L21.256,22.054C21.153,22.172 21.035,22.275 20.902,22.378C20.607,22.599 20.194,22.776 19.633,22.806C19.456,22.821 19.264,22.835 19.073,22.835L19.058,22.835C18.66,22.835 18.261,22.806 17.848,22.732C17.184,22.629 16.594,22.422 16.063,22.216C15.783,22.334 15.488,22.437 15.208,22.526C14.381,22.776 13.511,22.939 12.641,22.983C11.741,23.042 10.826,22.968 9.941,22.806C9.838,22.791 9.72,22.762 9.617,22.747C8.849,23.293 8.171,23.647 7.463,23.883L7.448,23.883C7.3,23.868 6.976,23.986 6.548,23.986ZM3.171,19.149L3.298,19.171C3.769,19.251 4.288,19.105 4.83,18.787C4.346,18.28 3.915,17.722 3.545,17.122C3.453,17.384 3.372,17.646 3.303,17.908L3.303,17.923C3.206,18.344 3.164,18.756 3.171,19.149ZM5.642,5.679C5.816,5.896 6.013,6.115 6.23,6.335L6.234,6.339C6.669,6.802 7.188,7.237 7.754,7.632L7.758,7.635C8.002,7.814 8.247,7.973 8.53,8.127L9.438,6.397L11.52,11.86L5.703,13.422C5.703,13.422 6.536,11.846 6.536,11.846C4.924,11.094 3.955,10.399 3.336,9.809C3.17,10.49 3.081,11.202 3.081,11.934C3.081,14.372 4.061,16.584 5.649,18.195C5.808,18.06 5.968,17.912 6.127,17.755L6.132,17.75C6.595,17.316 7.029,16.796 7.425,16.231L7.428,16.227C7.608,15.98 7.768,15.734 7.922,15.447L6.224,14.523L11.638,12.465L13.2,18.281C13.2,18.281 11.623,17.448 11.623,17.448C10.91,18.978 10.248,19.93 9.677,20.551C10.42,20.752 11.201,20.859 12.006,20.859C14.442,20.859 16.65,19.881 18.261,18.298C18.108,18.112 17.938,17.926 17.754,17.739L17.749,17.734C17.315,17.271 16.795,16.837 16.23,16.441L16.226,16.438C15.981,16.26 15.737,16.1 15.453,15.947L14.564,17.637L12.459,12.23L18.28,10.666C18.28,10.666 17.447,12.243 17.447,12.243C19.04,12.986 20.006,13.673 20.625,14.259C20.825,13.517 20.931,12.738 20.931,11.934C20.931,9.511 19.964,7.313 18.396,5.705C18.197,5.867 17.997,6.048 17.797,6.245L17.792,6.25C17.329,6.684 16.895,7.204 16.499,7.769L16.496,7.773C16.317,8.019 16.157,8.265 16.003,8.55L17.724,9.475L12.286,11.535L10.724,5.719C10.724,5.719 12.301,6.552 12.301,6.552C13.061,4.922 13.763,3.949 14.357,3.332L14.364,3.324C14.325,3.313 14.286,3.303 14.247,3.293L14.133,3.264C13.451,3.097 12.739,3.009 12.006,3.009C9.516,3.009 7.262,4.031 5.642,5.679ZM18.609,17.937C18.841,18.216 19.039,18.495 19.199,18.77C19.585,19.43 19.756,20.068 19.666,20.635C19.665,20.64 19.664,20.646 19.663,20.652L19.947,20.356C19.965,20.337 19.984,20.317 20.002,20.298C20.059,20.238 20.116,20.176 20.174,20.111C20.958,19.238 21.891,17.893 21.905,17.289L21.89,17.215C21.743,16.713 21.507,16.212 21.168,15.725L21.168,15.71C21.011,15.46 20.802,15.153 20.46,14.801C19.833,14.156 18.761,13.358 16.757,12.479L17.302,11.447L13.128,12.568L14.632,16.433L15.237,15.282C15.753,15.518 16.134,15.758 16.521,16.035C17.106,16.454 17.651,16.911 18.114,17.392C18.29,17.575 18.458,17.755 18.609,17.937ZM19.148,20.695L19.17,20.569C19.245,20.125 19.12,19.638 18.839,19.129C18.352,19.592 17.818,20.006 17.245,20.363C17.466,20.438 17.686,20.505 17.907,20.564L17.922,20.564C18.343,20.661 18.755,20.703 19.148,20.695ZM4.835,3.379L4.813,3.505C4.744,3.915 4.845,4.361 5.081,4.826C5.532,4.388 6.023,3.991 6.55,3.644C6.397,3.595 6.244,3.551 6.091,3.51L6.076,3.51C5.65,3.412 5.232,3.37 4.835,3.379ZM3.51,19.948C3.53,19.966 3.549,19.985 3.568,20.003C3.628,20.06 3.69,20.117 3.755,20.175C4.628,20.959 5.974,21.892 6.578,21.906L6.651,21.891C7.153,21.744 7.654,21.508 8.141,21.168L8.156,21.168C8.423,21.001 8.756,20.773 9.139,20.387C9.771,19.751 10.542,18.686 11.387,16.758L12.419,17.303L11.298,13.129L7.418,14.604L8.584,15.238C8.348,15.754 8.108,16.135 7.832,16.522C7.412,17.107 6.955,17.651 6.474,18.115C6.318,18.265 6.165,18.41 6.01,18.542C5.735,18.777 5.461,18.978 5.189,19.145C4.496,19.57 3.825,19.761 3.232,19.667C3.226,19.666 3.22,19.665 3.214,19.664L3.51,19.948ZM18.036,5.356C18.318,5.125 18.599,4.93 18.875,4.772C19.26,4.553 19.637,4.407 19.996,4.345C19.997,4.346 20.008,4.343 20.029,4.339C20.265,4.301 20.493,4.299 20.71,4.336L20.356,3.997C19.501,3.186 17.996,2.109 17.347,2.094L17.273,2.109C16.771,2.256 16.27,2.492 15.783,2.832L15.768,2.832C15.53,2.98 15.24,3.178 14.909,3.492C14.254,4.112 13.438,5.186 12.537,7.242L11.505,6.697L12.626,10.871L16.521,9.396L15.34,8.762C15.576,8.246 15.816,7.865 16.093,7.478C16.512,6.893 16.969,6.349 17.45,5.885C17.647,5.695 17.841,5.516 18.036,5.356ZM20.752,4.819C20.731,4.835 20.718,4.844 20.719,4.845L20.674,4.837C20.651,4.836 20.619,4.833 20.581,4.822C20.163,4.765 19.708,4.881 19.234,5.134C19.686,5.614 20.09,6.139 20.44,6.701C20.507,6.498 20.568,6.295 20.622,6.092L20.622,6.077C20.721,5.645 20.763,5.222 20.752,4.819ZM3.491,9.254C4.113,9.905 5.187,10.716 7.227,11.609L6.681,12.642L10.856,11.521L9.366,7.611L8.746,8.791C8.23,8.555 7.849,8.315 7.463,8.039C6.877,7.62 6.333,7.163 5.869,6.682C5.664,6.468 5.471,6.258 5.3,6.046C5.07,5.76 4.876,5.475 4.722,5.195C4.384,4.58 4.236,3.988 4.315,3.457C4.317,3.445 4.319,3.433 4.32,3.422L3.981,3.79C3.17,4.646 2.093,6.151 2.078,6.8L2.093,6.874C2.24,7.375 2.476,7.877 2.816,8.364L2.816,8.378C2.967,8.62 3.168,8.916 3.491,9.254Z
```

**Comment by PeterShaggyNoble** [comment]
@adamrusted, yeah, that's where we started from in this PR. It looked a little busy at 24*24, though, which was what led to me suggesting a more simplified treatment.

**Review by adamrusted — APPROVED** [review]

**Comment by PeterShaggyNoble** [comment]
@adamrusted, did you mean to merge this one? It doesn't look like any changes were made since [I mentioned](https://github.com/simple-icons/simple-icons/pull/10313#issuecomment-1898621245) that there were some differences that needed fixing.

**Pull request merged**
