### PR TITLE
Add XState

### LINKED ISSUE #4965: Icon request for XState
**Brand Name:** XState
**Website:** https://xstate.js.org/
**Alexa rank:** [328,744](https://www.alexa.com/siteinfo/xstate.js.org)
  

**Official resources for icon and color:** [Image kit on GitHub](https://github.com/davidkpiano/xstate/tree/master/docs/.vuepress/public)

### PR DESCRIPTION
**Pull request by Neo42**
XState

**Issue:** Closes #4965
**Alexa rank:** 328744
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Hex value was grabbed from XState's official stylesheet by @PeterShaggyNoble.
The logo was cropped with Inkscape and scaled with [SVG Path Editor](https://aydos.com/svgedit/) which is pretty easy to use. Highly recommended tools. (Just to keep a record for my own)

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one on, @Neo42. The linting is failing because you need to combine the 2 `path`s into 1, optimise that path and remove all newlines & tabs from the SVG.

Can you also please complete the PR template and update the source to https://github.com/davidkpiano/xstate/blob/544df7f00e2ef49603b5e5ff2f0d183ff6bd5e7c/docs/.vuepress/public/logo.svg?

**Comment by Neo42** [comment]
Cool. Thanks for the hint, @PeterShaggyNoble. First time doing svg editing. Harder than I thought.

**Comment by Neo42** [comment]
Sorry, I should've run the lint locally. I'll fix it.

**Comment by PeterShaggyNoble** [comment]
> First time doing svg editing. Harder than I thought.

Don't worry, we're here to help 🙂

Thanks for the update. However, your version (in red below) is slightly misaligned but that's most likely down to the precision being too low, could you have another look at that please?

For the colour, I'm getting `#000000` from [the website's logo](https://xstate.js.org/docs/logo.svg) but I do still think we should go with the `#2c3e50` from the website's stylesheet.

Finally, you might want to double check the `source` entry in the JSON file 😉

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @Neo42?

**Comment by Neo42** [comment]
Sorry @PeterShaggyNoble, I couldn't make time for this. Just give me this week and hopefully I can get it fixed.

**Comment by Neo42** [comment]
@PeterShaggyNoble, seems like you gotta help me with the source entry.😅

**Comment by Neo42** [comment]
Should be fine now @PeterShaggyNoble.

**Comment by Neo42** [comment]
Thanks to you, too. Will submit again at some time. Shouldn't be so tricky next time.

**Pull request merged**
