### PR TITLE
Updated Runkeeper

### PR DESCRIPTION
**Pull request by fbernhart**
runkeeper

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Runkeeper have updated their icon, and have a proper [press kit](https://runkeeper.com/cms/press-kit/) section on their website. Could you rebuild this one, and point source to this page?

**Comment by fbernhart** [comment]
@adamrusted Done 🏃🏼  For reference: I've used the `ASICS Runkeeper logo - Intl - blue and white.svg` file.

runkeeper

**Comment by adamrusted** [comment]
Here's a fun one @simple-icons/maintainers - just having a quick glance at the [Brand Guidelines](https://runkeeper.com/cms/wp-content/uploads/sites/3/2020/06/Brand_Guidelines.pdf) for Runkeeper, and it's saying that ® should only be used in the USA, otherwise `TM` should be used. It's also unclear as to whether the icon can be used without the wordmark from the documentation there. I imagine given that an icon option isn't presented, we ***should*** use the full wordmark and icon?

**Comment by fbernhart** [comment]
Hmm ... as Simple Icons is clearly an international project, we can use the international version of the Runkeeper logo (and as they don't requite the trademark symbol, remove the (TM) sign 😝).

Probably we should go for "logo + wordmark". Because actually the logo itself is the logo of ASICS, the sports company that bought Runkeeper some time ago. So that we differenciate between ASICS and Runkeeper.

**Comment by fbernhart** [comment]
runkeeper

**Review by adamrusted — APPROVED** [review]
Perfect! 🏃🏻‍♂️

**Comment by PeterShaggyNoble** [comment]
Generally, adding the wordmark simply to differentiate it from another brand, wouldn't be the correct call. If the brand colours are the same then adding the parent brand instead of the sub-brand would usually be the way to go. Although, there are, of course, plenty of exceptions which get addressed on a case-by-case basis. If the brand colours are different then we'd need to address #3270 first.

That said, though, given the following line from their brand guidelines, I think it's clear that we _had_ to include the wordmark in this case:

> The ASICS Runkeeper® master logo should be used at all times.

However, on the trademark symbol, the brand guidelines do state that it _must_ be included as well so I think we, unfortunately, will need to add it in:

> Don't remove the (R) or (TM) from the logo

**Pull request merged**
