### PR TITLE
Add XML icon

### LINKED ISSUE #11836: Request: XML
### Brand Name

XML

### Website

https://www.w3.org/XML/

### Popularity Metric

comm'on, XML needs no introduction lol :laughing: 
SVG, HTML, the office suites documents, and tonnes of other things are better written in XML.

also, i ain't gonna create an account on that ranking site [Similarweb rank](https://www.similarweb.com/)  just for this.

### Official Resources for Icon and Color

* This icon from https://devicon.dev
* wikipedia is also using this: https://en.wikipedia.org/wiki/XML
* oh yeah, found it officially linked: https://www.w3.org/Icons/XML/xml.svg

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by DerBraky**
Untitled

**Issue:** closes #11836

**Popularity metric:**
Similarweb Global Rank: [20,193](https://www.similarweb.com/website/w3.org) (same as for #11376)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Someone has already tried to add this in 2023: #8783

### CODE REVIEW

**Review by uncenter — APPROVED** [review]

**Comment by goyalyashpal** [comment]
hi!  a kinda partially unrelated question.  why was the `'develop' branch merged into xml`?  my git experience is limited to the (github workflow i guess it's called?), 

and i have heard that any pr should not contain a merge commit.

so i am curious to know and learn 😃

**Comment by uncenter** [comment]
> hi! a kinda partially unrelated question. why was the `'develop' branch merged into xml`? my git experience is limited to the (github workflow i guess it's called?),

One of our requirements for merging a pull request is that the branch is fully up to date:
CleanShot 2024-09-27 at 15 25 37
You can see in this picture that though the tests are passing, the merge button isn't green because the branch isn't u to date with `develop`.

I believe it is that we want to make sure that any changes, say to the tests or to the SVG linter, exist in the PR branch so that the latest tests and lints are run and not anything outdated.

> and i have heard that any pr should not contain a merge commit.

Hmm where from? I haven't heard that myself.

> 
> so i am curious to know and learn why it was done here 😃

Happy to answer questions :)

**Comment by goyalyashpal** [comment]
> One of our requirements for merging a pull request is that the branch is fully up to date:

yep.  i understand that.  sorry i missed being specific: why "merge" instead of rebase to sync with the upstream branch.

> > and i have heard that any pr should not contain a merge commit.
> 
> Hmm where from? I haven't heard that myself.

i dont remember exactly.  but it was smth like the everything becomes tangled and messy: the history., the pr commits, the pr changes etc...  

it has happened at least 3-4 times with me too, & have seen it happening one other place... where after doing the merge in pr branch, all of the new/missed commits from upstream branch end up at pr branch.  and what was a 1 commit merge, now becomes say, 130 commit merge.

**Comment by goyalyashpal** [comment]
> it doesn't really matter which merge method we use due to squash merging [where] the diff of the pull request is turned into a single commit

ohwkayh.  well yeah, it would indeed solve all the issues.  'cz it has just been synced with upstream, & will be immediatly merged back in, thus no involvement of any of the intermediate cruft comits. 

nice to know.  thanks for the share.

for my personal projects though, i do like keeping individual commit history - with conventional commits and such - carefully trying to create such a path from start to end that would make most sense for a human to follow the diffs (given a sufficiently capable diff engine like vscodium v1.93 for e.g.)

**Pull request merged**
