### PR TITLE
Updated Google Play

### PR DESCRIPTION
**Pull request by adamrusted**
googleplay

**Issue:** Contributes to #4205
**Alexa rank:** N/A

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Updated source to ~Google Press Corner~ Partner Marketing Hub.
Rebuilt from source, with gaps ~of 0.35px~ between colours to try and match monochrome treatment found at source.
Ran through SVGO CLI.

#### Original Treatment
googleplay

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
@adamrusted, could you share the source SVG you used for this one, for review purposes? Or did you redraw it from scratch? Note that an official monochrome treatment can be found [here](https://thepartnermarketinghub.withgoogle.com/brands/google-play/visual-identity/primary-logos/#horizontal-lockup).

**Comment by adamrusted** [comment]
> @adamrusted, could you share the source SVG you used for this one, for review purposes? Or did you redraw it from scratch? Note that an official monochrome treatment can be found [here](https://thepartnermarketinghub.withgoogle.com/brands/google-play/visual-identity/primary-logos/#horizontal-lockup).

I used the monochrome treatment on that page (PNG) and tried to match the line thickness to that.

**Comment by PeterShaggyNoble** [comment]
Can one of the @simple-icons/maintainers that's better at comparing vector to raster than I throw an eye over this one, please?

**Comment by service-paradis** [comment]
Look a little bit different to me comparing to the monochrome raster version
image

**Comment by adamrusted** [comment]
@service-paradis yeah - I couldn't get it to perfectly match up when building it manually. By any chance, does our existing icon match up to that PNG perfectly? 😅

**Comment by service-paradis** [comment]
That is a tough one 😄 
The original does not quite fit:
image

**Comment by adamrusted** [comment]
Just tried rebuilding this at 3 decimals precision. Hoping this should be okay.

**Review by service-paradis — APPROVED** [review]
LGTM 💯 🎮 Merging this one, would be hard to make this better without a better source for the monochrome version!
Good job @adamrusted!

**Pull request merged**
