### PR TITLE
added colours to some files

### PR DESCRIPTION
**Pull request by vivian-dai**
most SVGs now have colours

### CODE REVIEW

**Comment by vivian-dai** [comment]
wait, sorry to whoever is reviewing this but `script.py` is irrelevant

**Comment by fbernhart** [comment]
@vivian-dai Thanks for your PR.

However, this is a huge change you're proposing. May I ask you why you're proposing that? How are you using the icons? Maybe there are other ways to achieve a colored version than adding the color to the SVGs. For example through CSS.

About colored icons: There already has been some discussion about this going on in https://github.com/simple-icons/simple-icons/issues/1060, and although the issue is still open, I think common ground is that adding the colors straight to the SVGs themselves is not something we're aiming for at the moment.

So unless the other @simple-icons/maintainers have a different opinion, we'll probably have to close this PR and label it as `won't add`.

If you just need a way to download the icons in their brand color, you might be interested in this proposed feature:

https://github.com/simple-icons/simple-icons-website/issues/32

**Comment by vivian-dai** [comment]
I've been downloading the SVGs then manually adding in a fill for it so I thought it would be nice to just download with the fill. I'll take a look into the website proposal and see if I can add a download with colours option.

**Comment by ericcornelissen** [comment]
I'm closing this as a precaution as this is definitely something we can just merge, this would likely break in many unexpected ways and even with V5 coming up I wouldn't want to risk this change.

For some additional context, we intentionally provide the SVGs without any styling so that users are free to style the SVGs as they see fit. Though there may be some/many users like yourself that want the icons coloured in the brand color we provide, many others use the icons in a different way and setting a fill on the SVG tag itself makes the latter more difficult.

That said, you're not the first to bring this issue to our attention and we would be glad to find an easy solution for users like you. Given that you use the website to get the SVGs the issue linked to by @fbernhart is probably your best bet, if you're really interested in this please leave some feedback on that issue so that we know what we can prioritize.

**Pull request closed without merging**
