### PR TITLE
Update Travis CI icon

### LINKED ISSUE #1178: Update: Travis CI
**Name:** Travis CI
**Official resources for icon and color:** https://travis-ci.com/logo
  

Travis CI was originally added ~3 years back in 28f9fef without any clear details on the source, at least now they have a better source for the logo. Specifically, I think we should remove the circle around the head from the logo we have now :arrow_down: . However, making just the head monochrome might proof difficult of the outline itself isn't clear.

current preview

Also the current colour, `#39A85B`, is not in line with the page linked above, if we want to stick with green we should use `#39AA56` instead.

### PR DESCRIPTION
**Pull request by ericcornelissen**
**Issue:** closes #1178

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Updated the Travis CI icon, what elements to exclude from the logo is somewhat arbitrary as [the guidelines](https://travis-ci.com/logo) do not specify anything in this regard. I have some more alternatives in [this zip file](https://github.com/simple-icons/simple-icons/files/2851502/Downloads.zip).

One thing worth considering is changing the brand color from green (`#39AA56`) to blue (`#3EAAAF`)

preview

### CODE REVIEW

**Comment by davidklebanoff** [comment]
This is a big improvement!

My vote is to use the oxide blue color (`#3EAAAF`) as the brand's primary color. While not explicitly stated, that seems to me to be the correct option based on their website and brand guidelines page.

I would also fill in the `T` on the hat. I think it's more consistent with the official icon seen here:
https://travis-ci.com/images/logos/TravisCI-Mascot-grey.png

**Comment by ericcornelissen** [comment]
Good suggestions @davidklebanoff, I agree with you on the color. Updated both the color and the SVG 👍

**Comment by davidklebanoff** [comment]
That looks good! Maybe update the source to `https://travis-ci.com/logo`? Then I think it's good to merge!

**Comment by ericcornelissen** [comment]
Of course, my bad 😅 Changed it @davidklebanoff

**Comment by davidklebanoff** [comment]
Thanks @ericcornelissen!

**Pull request merged**
