### PR TITLE
Sencha

### PR DESCRIPTION
**Pull request by runxel**
**Issue:** _none_

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo and color <del>`#95C93D`</del><ins>`#86BC40` (Pantone 368 C)</ins> comes from the [website's](https://www.sencha.com/) header <ins>and their design [guidelines](http://design.sencha.com/marketingcolor.html)</ins>.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Would anything found at http://design.sencha.com/ be of use here?

**Comment by runxel** [comment]
Thanks alot for pointing that one out @PeterShaggyNoble! 👍 
I've updated the color and the source.
As per `Product Styles` section it's okay if the leaf stands on it's own.

**Comment by PeterShaggyNoble** [comment]
The shape of the monotone icon seems to differ from the full colour one. Here's what I pulled from http://design.sencha.com/images/white-blue.svg with your version overlaid in red.

Sencha

**Comment by runxel** [comment]
@PeterShaggyNoble 
Thanks for your tireless support! Updated the logo :)

**Comment by PeterShaggyNoble** [comment]
Looks good, @runxel, thanks.

**Pull request merged**
