### PR TITLE
Add Daimler icon

### LINKED ISSUE #2852: Daimler AG
**Name:** Daimler
**Website:** [Daimler AG](https://daimler.com)
**Alexa Rank:** [~11.6k](https://www.alexa.com/siteinfo/daimler.com)
**Official resources for icon and color:** [JPG/PNG/WMF](https://designnavigator.daimler.com/Daimler_Corporate_Logotype_Black_Office) [Design Guide](https://designnavigator.daimler.com/Daimler_Corporate_Logotype?lang=en#color-background)
**Color**: `#000000`

### PR DESCRIPTION
**Pull request by LuckyF**
daimler

**Issue:** Closes #2852

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this on, @LuckyF :+1:

A few things before we can merge this in, though:

1. You'll need to remove the Loom SVG and JSON entry.
2. The path needs to be centred vertically on the canvas.
3. Your path is just a sahde over `24` units wide at `24.015`.
3. Using [this EPS](https://designnavigator.daimler.com/Daimler_Corporate_Logotype_Black_DTP) for comparison, I'm noticing a few differences to your version (see the `R` below, for example, with yours in red). Did you use a different source file maybe?
4. As there was some discussion over the colour, we'll need one of the other @simple-icons/maintainers to double check the choice.
5. Purely out of my own personal preference, so not essential, I'd suggest removing the `lang` querystring parameter from the source URL.

**Comment by ericcornelissen** [comment]
> As there was some discussion over the colour

This colour seems like a good choice to me. Also, choosing the full wordmark over just the "D" seems better :+1: 

> Purely out of my own personal preference, so not essential, I'd suggest removing the lang querystring parameter from the source URL.

It's not a strict rule, but I'd agree :smile:

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @LuckyF?

**Comment by LuckyF** [comment]
Unfortunately I have messed up my git repo and had to create a new pull request (#2950).

**Pull request closed without merging**
