### PR TITLE
Ohdear2

### PR DESCRIPTION
**Pull request by CrazyMarvin**
ohdear

**Issue: #6519**
**Alexa rank: 418,749**
  

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

I picked the hex value from https://ohdear.app/logos.
I am not sure how to design the icon though. Please have a look at the issue regarding this.

### CODE REVIEW

**Review by dirien — APPROVED** [review]
Hi @CrazyMarvin,

thanks for your coooooooooooooooooooooooooooooooontribution 😄 with very long icon.

image
Its a perfect fit for me.

**Comment by dirien** [comment]
hi @CrazyMarvin, try to update your fork (develop branch) and rebase again. :/

**Comment by CrazyMarvin** [comment]
Done, @dirien

**Comment by dirien** [comment]
@CrazyMarvin, puh finally 😅 

thanks for the contribution by the way! It really toooooooooooooooooooook long!

**Comment by CrazyMarvin** [comment]
Thanks for your help! 😘
😂

**Pull request merged**
