### PR TITLE
Add osu!

### LINKED ISSUE #5082: Request : Osu! Icon
**Brand Name: Osu!**
**Website: osu.ppy.sh**

### PR DESCRIPTION
**Pull request by creepertron95**
osu

**Issue:** Fixes #5082
**Alexa rank:** 
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I picked the hex value from the guidelines under the `Single colour` section. The logo came from the SVG found in the header.

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
There are a [few](https://user-images.githubusercontent.com/1830867/112608973-e2c44080-8e12-11eb-912f-50d1acca71fc.png) [small](https://user-images.githubusercontent.com/1830867/112609050-fb345b00-8e12-11eb-989b-e6661a3b2697.png) [differences](https://user-images.githubusercontent.com/1830867/112609113-0b4c3a80-8e13-11eb-9c92-c435cb328eb6.png) in the lettering, which could just be down to optimization, but you may be able to drag those points to match the original better. Otherwise, this is pretty spot on, thanks @creepertron95 🚀
If you're able to update the guidelines and look at matching the icon to the source, we can get this merged straight in!

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @creepertron95?

**Comment by adamrusted** [comment]
@PeterShaggyNoble I've just pushed the change I suggested regarding the source link. Any chance you could review this? Icon looks good to me against the `osu! Logo - 1C Black.ai` file.

**Comment by PeterShaggyNoble** [comment]
I'm seeing a few differences in the lettering, most notably [in the "s"](https://user-images.githubusercontent.com/15157491/117954848-5660d500-b30f-11eb-9b35-07ff0f2cae06.png).

**Comment by adamrusted** [comment]
@PeterShaggyNoble - give that a go. I've rebuilt from source using a precision of 4.

**Comment by fbernhart** [comment]
LGTM 👍🏼 Thanks @adamrusted

**Pull request merged**
