### PR TITLE
Remove extraneous spaces from icon markup

### LINKED ISSUE #3247: Keeping our markup consistent
Following on from my side note in [this comment](https://github.com/simple-icons/simple-icons/issues/3223#issuecomment-646657173), I've run a few different RegExes with various degrees of strictness in order to identify inconsistencies in the markup of all our existing icons. The first thing to decide is which of the issues we want to fix in those and then which ones we want to lint for in the future. Ideally, where possible, as most of these are merely minor niggles, we would try to fix these automatically. This list does not include the fix from #3239.

1. **Space before the `>` in the opening svg tag**
The 3 files affected are: `ardour.svg`, `centos.svg` & `cloudsmith.svg`
2. ~**Attributes on opening SVG tag out of order**
There are 365 files affected by this~ To be addressed in #2380
3. **Space before or after the `=` in one or more of the opening svg tag's attributes**
`jetbrains.svg` is the only file affected by this, with a space after `role`.
4. ~**No closing `Z` or `z` in the path's data**
There are 88 files affected by this one~
5. **Space before the closing `/` in the path tag**
The four files affected by this are: `celery.svg`, `deepin.svg` `ktm.svg` & `ublockorigin.svg`.

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
**Issue:** Fixes #3247
**Alexa rank:** n/a

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Removes spaces
- before the `>` in the opening svg tag in `ardour.svg`, `centos.svg` & `cloudsmith.svg`,
- between the `role` attribute and its `=` in the opening svg tag in `jetbrains.svg`, and,
- before the closing `/` in the path tag in `celery.svg`, `deepin.svg` `ktm.svg` & `ublockorigin.svg`.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Depends how far out we are from implementing #2380 - SVGO will strip away any excess whitespace for us.

**Comment by ericcornelissen** [comment]
> Depends how far out we are from implementing #2380 - SVGO will strip away any excess whitespace for us.

Since we need to create a [Probot](https://probot.github.io/) for that, not for as I don't think anyone started doing that yet.

**Comment by PeterShaggyNoble** [comment]
OK, I've updated the RegEx you added in #3239 with the one I suggested in #3247 and reworded the related error message accordingly.

**Comment by runxel** [comment]
Consistency is always good :)
And the PR looks good to me so I will gladly merge this in. Thank you for the work @PeterShaggyNoble, and of course for detecting this in the first place. 👍

**Pull request merged**
