### PR TITLE
Specify recommended continuous monochromatic geometries treatment

### LINKED ISSUE #4530: Specify impossible continuous monochromatic geometries treatment
Following the discussion in #3829, we continually come across continuous geometries that can't be easily converted to a monochromatic path. See #4480, #4485 and #3829. I can remember two cases:

- Geometry jumps due to positioning on different positions of Z axis (3D-like logos, eg. [Netflix](https://brand.netflix.com/en/assets/brand-symbol/)).
- Continuous geometries with different colors (eg. [Kotlin](https://kotlinlang.org/)).

The treatment that we are giving to these geometries converting to monochromatic is to create gaps between colors or jumps, introducing a discontinuation. I think, like @runxel [has pointed](https://github.com/simple-icons/simple-icons/issues/3829#issuecomment-749561677) in #3829 that this should be added to our contribution guidelines after or inside the "Extract the Icon from the Logo" section to make it easier for new contributors to deal with such cases.

My position about what should be the wide of the gaps is: these should be relative to surrounding geometries trying to make it look good at small sizes of icons, whenever possible.

- Do you think that this is a nice addition to contribution guidelines?
- Any case that you remember that I'm not taking into account? 
- What is your position about the treatment of the geometries in these cases?

### PR DESCRIPTION
**Pull request by mondeja**
Closes #4530

### CODE REVIEW

**Comment by adamrusted** [comment]
Hope you don't mind @mondeja - I've made a couple of small tweaks to the wording. Feel free to revert if necessary.

**Comment by mondeja** [comment]
Thank you @adamrusted, it's great to have active native English speakers maintainers again :tada:

**Review by adamrusted — APPROVED** [review]
This looks good to me now. Could another @simple-icons/maintainers give this a once-over before merging?

**Comment by fbernhart** [comment]
LGTM! 👍🏼

**Pull request merged**
