### PR TITLE
Add Cesium (#2659)

### LINKED ISSUE #2659: Cesium
**Name:**
**Website:** https://cesium.com
**Official resources for icon and color:**
https://cesium.com/press/

[Alexa rank ](https://www.alexa.com/siteinfo/cesium.com)~211k

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
closes #2659

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Color `#6CADDF` and svg from their press kit.

cesium

### CODE REVIEW

**Comment by runxel** [comment]
Bumped dat precision.

**Comment by PeterShaggyNoble** [comment]
Don't know why, but I was expecting the inverse of the treatment you gave this 🤔

Comparison looks good to me, though, but I'll hold off on merging for a bit in case one of the other @simple-icons/maintainers agrees with me.

image

**Comment by runxel** [comment]
> Don't know why, but I was expecting the inverse of the treatment you gave this 🤔

I did so too, until I saw their strict policy on the website regarding their icon. If you look in the press kit there luckily _is_ a monochrome version provided (only as png, tho). Still looks the same like mine :)

**Comment by PeterShaggyNoble** [comment]
Ah-ha! I hadn't looked at the PNGs. In that case, I think this is good to go. Thanks for the work on it, @runxel.

**Pull request merged**
