### PR TITLE
Webpack!

### PR DESCRIPTION
**Pull request by whoisjorge**
I am not sure about the brand's primary color, according to the branding guideliness there are two possible options. I have chosen Malibu  🍹 🌴 🌅

| Color              | Hex Code       | RG code |
| ------------- |:-------------:| :----------|
| Malibu      | `#8dd6f9` | `rgb(141, 214, 249)`
| Denim      | `#1d78c1`      | `rgb(29, 120, 193)`

### CODE REVIEW

**Comment by birjolaxew** [comment]
Looking good! Could you run this through [SVGO(MG)](https://jakearchibald.github.io/svgomg/) with a precision of 3-4 to reduce the file size a bit? It also looks like you have a small typo in the ID of your `<title>`. Other than that this looks ready to go.

**Comment by ericcornelissen** [comment]
Relevant for #625

**Comment by birjolaxew** [comment]
:+1: Thanks for the work! Merged and published.

**Comment by whoisjorge** [comment]
Thanks @birjolaxew! I love doing it, and always welcomed 🥇

**Pull request merged**
