### PR TITLE
Updated Azure Functions

### PR DESCRIPTION
**Pull request by fbernhart**
azurefunctions

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
I rebuilt using the SVG shape found [here](https://azurecomcdn.azureedge.net/cvt-e1f3e817b5f78c61296bf5c8cc8a9fcba21d0246debd6828ce14d7cf359c6777/images/page/services/functions/value-prop-2.svg) and seems to be quite a few differences.

image

**Comment by fbernhart** [comment]
@adamrusted Done. I've now used [this SVG](https://azurecomcdn.azureedge.net/cvt-e1f3e817b5f78c61296bf5c8cc8a9fcba21d0246debd6828ce14d7cf359c6777/images/page/services/functions/value-prop-4.svg) as source.

**Review by adamrusted — APPROVED** [review]
Perfect 🎉

**Comment by fbernhart** [comment]
@adamrusted Done 🛠️

**Pull request merged**
