### PR TITLE
Updated AirPlay Audio

### PR DESCRIPTION
**Pull request by fbernhart**
airplayaudio

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by adamrusted — APPROVED** [review]
Perfect 💯

**Comment by mondeja** [comment]
Conflict solved :hammer_and_wrench: 
Thank you both! :+1:

**Comment by adamrusted** [comment]
> Conflict solved 🛠️
> Thank you both! 👍

I was just trying to do this 😅 got caught up pushing it to my own branch...

**Comment by mondeja** [comment]
Ups sorry :sweat_smile:

**Comment by adamrusted** [comment]
> Ups sorry 😅

No worries - I just don't know what git commands to use 🤣

**Pull request merged**
