### PR TITLE
Add Bastyon icon

### LINKED ISSUE #5395: Request: Bastyon Icon
**Brand Name: Pocketnet**
**Website: https://pocketnet.app**
**Github: https://github.com/pocketnetteam**
**Alexa rank: 216,136**
  

**Official resources for icon and color:**
~~https://github.com/pocketnetteam/pocketnet.gui/blob/master/img/logo20.svg~~
https://github.com/pocketnetteam/pocketnet.gui/blob/978201dca0d63bc87c4c66513a67f085f2f51d83/img/logo.svg

### PR DESCRIPTION
**Pull request by andyoknen**
bastyon

Bastyon is a decentralized social network based on the blockchain.

**Issue:** closes #5395
**Website:**: https://bastyon.com
**Similarweb rank:** 49,533
**Contributing:** Yes

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Difference preview
Screenshot_2

### CODE REVIEW

**Comment by LitoMore** [comment]
CleanShot 2022-09-07 at 02 27 44@2x

@andyoknen There is some difference. You could try with `--precision 4` when you compressing the source file. Our default precision is 3.

```sh
npm run svgo -- -p 4 icons/bastyon.svg
```

**Comment by andyoknen** [comment]
> @andyoknen There is some difference. You could try with `--precision 4` when you compressing the source file. Our default precision is 3.
> 
> ```shell
> npm run svgo -- -p 4 icons/bastyon.svg
> ```

This gives no results. I checked different levels up to 7 - the result is the same as level 3

**Comment by LitoMore** [comment]
@andyoknen Not re-svgo your compressed file. You need to redo your steps, and compress the source file with precision 4.

**Comment by andyoknen** [comment]
> @andyoknen Not re-svgo your compressed file. You need to redo your steps, and compress the source file with precision 4.

Yes, I figured it out - maybe I'm missing something - I've tried npm and online service

original

**Comment by LitoMore** [comment]
@andyoknen Those black parts are differences. We should make the compressed file is perfect fit the source one.

For example this PR https://github.com/simple-icons/simple-icons/pull/7732. You can see a perfect fit picture there.

**Comment by andyoknen** [comment]
@LitoMore I still don't understand how to get this difference - a file in this pool and a source file in the repository are the same file..

**Comment by LitoMore** [comment]
@andyoknen Here is how I check differences:

1. Download the processed SVG file from the pull request
2. Open the file with Inkscape (or other SVG editor)
3. Drag the original file ([the source one](https://github.com/pocketnetteam/pocketnet.gui/blob/master/img/logo20.svg?rgh-link-date=2021-04-01T12%3A54%3A29Z)) to Inkscape
4. Resize the original file to 24, and center it, bring it to top
5. Change the fill color of the source one to white
6. Then you will see the difference

**Comment by andyoknen** [comment]
I understood - I specified logo20.svg in the issue as an official file, but that was before I got into the requirements for adding an icon. This file is not the best option. I will deal with this issue and bring logo20.svg to the correct form

**Comment by andyoknen** [comment]
@LitoMore Hi! I fixed the icons in the repository and the original issue. Based on them, I made a file in this pull request

**Comment by LitoMore** [comment]
CleanShot 2022-09-08 at 01 13 09@2x

@andyoknen Perfect fit! Thank you for your contributions!

**Review by LitoMore — APPROVED** [review]

**Pull request merged**
