### PR TITLE
Added Trino

### LINKED ISSUE #5120: Request : Trino Icon
**Brand Name:** Trino
**Website:** https://trino.io/
**Alexa rank:** https://www.alexa.com/siteinfo/trino.io  (used to be: prestosql.io )
  

**Official resources for icon and color:**
https://github.com/trinodb/trino.io/blob/master/favicon.ico
https://trino.io/assets/images/trino-logo/trino-ko_tiny-alt.svg

Note: Trino is the new name of previous [PrestoSQL](https://github.com/trinodb/trino) project.
There is already an icon for Presto in simple-icons. Due to legal reasons they had to rename the project and disconnect all attachments to Presto trademark : https://trino.io/blog/2020/12/27/announcing-trino.html

This is a new name, many people are still searching PrestoSQL when looking to find Trino. it will take time till the new name is acknowledged.

### PR DESCRIPTION
**Pull request by adamrusted**
trino

**Issue:** Fixes #5120
**Alexa rank:** [255,770](https://www.alexa.com/siteinfo/trino.io)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Hex from website stylesheet - SVG found by @PeterShaggyNoble in docs repo. Needed 4 decimals for it to display correctly, also had a fair few 'issues' with the circles, so may be _slightly_ different to source in order to tidy them up.

### CODE REVIEW

**Comment by HaloKo4** [comment]
waiting for this :)

**Comment by PeterShaggyNoble** [comment]
Thanks for this one, @adamrusted. The only small differences I see are in [the left eye](https://user-images.githubusercontent.com/15157491/109682939-c36d2700-7b76-11eb-9667-280612482d42.png) (the one in the right is obviously as a result of you fixing an imperfection in the original) and in [the left of the inner curve of the neck](https://user-images.githubusercontent.com/15157491/109683252-121ac100-7b77-11eb-82d9-2928c3fb3a52.png). There's also a [small imperfection in the left side of the nose](https://user-images.githubusercontent.com/15157491/109683491-4e4e2180-7b77-11eb-863d-70601f6bb500.png) in the original if you want to try fixing that.

**Comment by adamrusted** [comment]
@PeterShaggyNoble give that a try - still a few differences, but they're _all_ down to fixing errors.

**Comment by PeterShaggyNoble** [comment]
Still seeing a [small difference](https://user-images.githubusercontent.com/15157491/109967297-254d9e00-7ce9-11eb-8d5b-dc20e6c05cf4.png) in the left eye, @adamrusted. Might just be a precision issue.

**Comment by adamrusted** [comment]
Give that a go @PeterShaggyNoble - matches up on my end against the source, even after optimization.

**Review by PeterShaggyNoble — APPROVED** [review]
Looks good to me now, @adamrusted 👍🏻 Nice work.

**Pull request merged**
