### PR TITLE
Update: Tor

### PR DESCRIPTION
**Pull request by adamalston**
tor

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Updated name to `Tor Project`
- Updated icon to the 'invert' option as suggested
- Updated color
- Updated source to official documentation
- Updated preview above

### CODE REVIEW

**Comment by runxel** [comment]
Hi @adamalston, thanks for this PR!
However this update seems to be misplaced. Until now, the "Tor" icon we have is the logo of the _Tor project_ – which is still the onion.
You've taken the icon from the _Tor Browser_, which, indeed, is different and rather stylized.
I see that there is now an "invert" option for the Tor Project.
So maybe you can update the _Tor Project_ in this PR, and if you like, you can make another PR to incorporate the icon of the Tor Browser (the one currently in this PR).

**Comment by adamalston** [comment]
Done, thanks @runxel

**Comment by runxel** [comment]
Thank you for the fast change, @adamalston!
However, if we are renaming this to "Tor Project", we will have to wait for v4 to merge this. Right, @PeterShaggyNoble?

**Comment by ericcornelissen** [comment]
> However, if we are renaming this to "Tor Project", we will have to wait for v4 to merge this.

A little late, but I'll answer this now: Yes. I just added it to the [v4 milestone](https://github.com/simple-icons/simple-icons/milestone/3) which is planned for this weekend.

@runxel, did you do a full review of the new SVG?

**Pull request merged**
