### PR TITLE
Add AMG icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
image

**Issue:** #6334 
**Alexa rank:** 154,374
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Everything from https://www.mercedes-amg.com/content/global/en/home.html and https://www.mercedes-amg.com/etc/clientlibs/amg/amg.base/assets/images/svg/amg-logo.svg

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
image

@dirien notice the slightly darker edges in the A and M. Perhaps try it with precision 4?

**Comment by jorgeamadosoria** [comment]
> @jorgeamadosoria do i need to "rebuild" the SVG from the original or just save it with precision 4?

i would start by saving it with precision 4 and see if that's enough.

**Comment by dirien** [comment]
@jorgeamadosoria rework with precison 4

**Comment by jorgeamadosoria** [comment]
excellent 100%. LGTM

**Review by jorgeamadosoria — APPROVED** [review]
LGTM

**Pull request merged**
