### PR TITLE
Add Proteus

### LINKED ISSUE #8082: add proteus icon
### Brand Name

Proteus

### Website

https://www.labcenter.com/

### Popularity Metric

The Proteus rank is 284,598. See https://www.similarweb.com/zh/website/labcenter.com/#overview

### Official Resources for Icon and Color

None

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
proteus

**Issue:** closes #8082 

**Similarweb rank:** 256,396. See https://www.similarweb.com/website/labcenter.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Hex Value picked from website header: `#1C79B3`
Logo picked from on of the [brochures ](https://www.labcenter.com/downloads/proteusPcb.pdf )and redrawn to match the original high fidelity icon.

### CODE REVIEW

**Comment by PratyushJayachandran** [comment]
image

Created vector overlaid over original logo(auto vectorized).

I am still working on this.

**Comment by adamrusted** [comment]
@PratyushJayachandran - if you could share the source file (including raster) I'd be happy to throw some ideas around our interpretation of it your way?

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran - if you could share the source file (including raster) I'd be happy to throw some ideas around our interpretation of it your way?

I would appreciate that. I took the image from here https://www.labcenter.com/downloads/proteusPcb.pdf

I tried a few things. If I make the gaps as big as 1px it doesn't look good.

**Comment by adamrusted** [comment]
@PratyushJayachandran - what do we think to this? Passes our linter, if you wanted to go with it?
proteus

```html
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Proteus</title><path d="M18.308 4.912a1.19 1.19 0 1 1 1.537 1.01 3.699 3.699 0 0 1-.23.783c-.224.561-.596 1.24-1.093 1.997 1.71.323 3.114.77 4.061 1.291.859.474 1.349 1.027 1.417 1.596v.276c-.005.04-.012.08-.021.12-.119.526-.598 1.035-1.396 1.475-1.229.678-3.228 1.226-5.666 1.546.794 1.12 1.371 2.113 1.672 2.883l.052.138a1.19 1.19 0 1 1-1.139 1.715 4.38 4.38 0 0 1-.614-.218c-1.142-.5-2.768-1.647-4.547-3.226l.31-.28c1.723 1.527 3.294 2.64 4.404 3.124.114.05.222.092.325.128l-.001-.055c0-.534.352-.986.837-1.136l-.015-.039c-.308-.789-.914-1.816-1.749-2.97l.005-.007a36.43 36.43 0 0 1-1.921.17l-1.727.071-.809.008-2.178-.058-1.426-.103a34.956 34.956 0 0 1-.852-.088l.021.026c-.832 1.137-1.436 2.146-1.748 2.926l-.015.038c.484.151.835.602.835 1.135l-.001.06c.101-.034.207-.076.319-.123 1.185-.507 2.899-1.72 4.766-3.388l.01-.009h.621l-.323.291c-1.923 1.72-3.692 2.968-4.91 3.49a4.167 4.167 0 0 1-.606.21 1.19 1.19 0 1 1-1.136-1.718c.016-.046.034-.093.053-.14.305-.764.885-1.747 1.681-2.852-2.45-.318-4.461-.868-5.694-1.549-.798-.44-1.277-.949-1.396-1.475a1.256 1.256 0 0 1-.021-.12v-.276c.068-.569.558-1.122 1.417-1.596.969-.535 2.418-.989 4.183-1.313-.507-.782-.885-1.48-1.109-2.055a4.062 4.062 0 0 1-.203-.667A1.19 1.19 0 1 1 5.79 4.81v.025c.127.042.261.093.402.155.78.341 1.785.983 2.909 1.86a5.228 5.228 0 0 0-.365.24c-1.045-.805-1.978-1.398-2.711-1.718a4.332 4.332 0 0 0-.317-.126 1.19 1.19 0 0 1-.986.747c.037.147.09.308.157.48.231.592.629 1.316 1.165 2.13.444-.075.905-.14 1.382-.198a5.483 5.483 0 0 0-.292.454c-.284.037-.563.077-.835.12.251.364.527.744.826 1.134.316.412.657.837 1.02 1.271l1.059 1.213.937 1.004.854.865a40.154 40.154 0 0 1-.61-.019l-1.187-1.24-.839-.934-.732-.863-.598-.744a29.438 29.438 0 0 1-1.18-1.61c-1.789.315-3.257.765-4.23 1.302-.396.218-.707.45-.918.694-.187.217-.293.441-.293.675 0 .087.015.173.043.258.048.142.133.281.25.417.211.244.522.475.918.694 1.321.73 3.555 1.298 6.266 1.588.435.046.882.085 1.34.117l1.595.077.611.013c.188.003.378.004.569.004l2.048-.05.132-.007a36.405 36.405 0 0 0 1.937-.155c2.71-.29 4.943-.858 6.264-1.587.396-.219.707-.45.918-.694.117-.136.202-.275.25-.417a.821.821 0 0 0 .043-.258c0-.234-.106-.458-.293-.675-.211-.245-.522-.476-.918-.694-.951-.525-2.375-.967-4.109-1.282a28.993 28.993 0 0 1-1.278 1.716l-.763.925-.789.9-1.188 1.267-.555.56-.615.02 1.197-1.21 1.152-1.252.772-.899c.247-.297.483-.588.706-.874.332-.425.636-.837.911-1.23a27.31 27.31 0 0 0-.955-.14 5.644 5.644 0 0 0-.291-.454c.52.062 1.022.135 1.502.218.527-.789.919-1.494 1.15-2.072.085-.212.147-.406.185-.579a1.19 1.19 0 0 1-.989-.66 4.838 4.838 0 0 0-.333.128c-.739.316-1.683.907-2.742 1.711a5.32 5.32 0 0 0-.36-.247c1.138-.872 2.152-1.51 2.938-1.847.133-.057.26-.105.381-.145zM12.256 16.76l-.255.006-.186-.003.364-.319zM8.752 15.6c.76.062 1.549.103 2.36.12-.295.258-.586.503-.87.735a5.094 5.094 0 0 1-1.49-.855zm6.497 0a5.095 5.095 0 0 1-1.462.845c-.277-.23-.56-.472-.847-.726a39.103 39.103 0 0 0 2.309-.119zM7.296 9.653a5.115 5.115 0 0 1 4.705-3.11A5.117 5.117 0 0 1 16.75 9.76a41.095 41.095 0 0 1-3.137 3.587c-.274.28-.547.554-.82.82l-.313.304-.483.008c-.134 0-.267 0-.399-.003l-.311-.306a45.888 45.888 0 0 1-.845-.857 40.888 40.888 0 0 1-3.146-3.66Zm-.386 1.533a43.478 43.478 0 0 0 2.63 2.993l.232.24a35.525 35.525 0 0 1-2.185-.187 5.08 5.08 0 0 1-.677-3.046zm10.192.134a5.08 5.08 0 0 1-.688 2.912 36.33 36.33 0 0 1-2.098.181l.192-.193a43.578 43.578 0 0 0 2.594-2.9z"/></svg>
```

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran - what do we think to this? Passes our linter, if you wanted to go with it? proteus

I was thinking this plus some gap on the small orbs also. Will that look good? Like make it look as if the rings go through the orbs.

**Comment by adamrusted** [comment]
> I was thinking this plus some gap on the small orbs also. Will that look good? Like make it look as if the rings go through the orbs.

Totally - feel free to have a go at that, this was about as adventurous as I want to go 😅

**Comment by PratyushJayachandran** [comment]
> > I was thinking this plus some gap on the small orbs also. Will that look good? Like make it look as if the rings go through the orbs.
> 
> Totally - feel free to have a go at that, this was about as adventurous as I want to go 😅

I appreciate the input. This one is particularly complex even though it may look simple. Thanks for putting in time 🥺

**Comment by PratyushJayachandran** [comment]
> Totally - feel free to have a go at that, this was about as adventurous as I want to go 😅

proteus

I used your suggestion and corrected a few things.

Maybe something like this can be tried:
proteus

**Comment by PratyushJayachandran** [comment]
@adamrusted hey, can we finalize this one? Or should I try something different?

**Comment by PeterShaggyNoble** [comment]
I like the idea of adding a shine to the globe but think it should follow one of the defined shapes in the original. Perhaps the light blue blob on the left-hand side? If that's not doable then I think we're better to go without it.

And should we add cut-outs around the "moons" as well?

**Comment by PratyushJayachandran** [comment]
> I like the idea of adding a shine to the globe but think it should follow one of the defined shapes in the original. Perhaps the light blue blob on the left-hand side? If that's not doable then I think we're better to go without it.
> 
> And should we add cut-outs around the "moons" as well?

Lets go without it. Cut-outs on the moons(or electrons) didn't look good so I didn't include it. Since the circles are really small, it loses resemblance.

**Comment by adamrusted** [comment]
@PratyushJayachandran - are you still updating this one?

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran - are you still updating this one?

Yes yes. I think we were just discussing different approaches. I put my opinion above which matches the present contribution. So I didn't make any changes.

**Review by adamrusted — APPROVED** [review]
image

Returning to this then, I'm happy with this treatment as-is.

**Review by PeterShaggyNoble — APPROVED** [review]

**Pull request merged**
