### PR TITLE
Request: Suckless Icon and dwm Icon

### LINKED ISSUE #4883: Add Icon for Suckless (and possibly dwm)
**Brand Name:** Suckless
**Website:** https://suckless.org
**Alexa rank:** 412,962

## Official resources for icon and color:
* Icon: https://suckless.org/logo.svg and/or https://dwm.suckless.org/dwm.svg
* Colors:
  * [](https://suckless.org/pub/style.css)
  * [](https://git.suckless.org/dwm/file/config.def.h.html#l10)
  * [](https://git.suckless.org/dwm/file/config.def.h.html#l11)
  * [#bbbbbb](https://git.suckless.org/dwm/file/config.def.h.html#l12)
  * [#eeeeee](https://git.suckless.org/dwm/file/config.def.h.html#l13)
  * [](https://git.suckless.org/dwm/file/config.def.h.html#l14)

### PR DESCRIPTION
**Pull request by yuri-norwood**
## Details
**Issue:** Closes #4883 - Add Icon for Suckless (and possibly dwm)
**Alexa rank:** [412,962](https://www.alexa.com/siteinfo/suckless.org)

**Why did you pick the hex value?**
The suckless tools all have a very consistent aesthetic, based on the 6 colours listed in my issue, however, the website and it's logo used `#069` (nice) and since most people customize the colours of the tools, this seems to be the best fitting. Both in terms of recognizability, and brand consistency.

**Did you manually vectorize the logo?**
Yes, I manually wrote the `path="..."` for both icons to get them to fit 24x24.

### Suckless
suckless

#### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### dwm
dwm

#### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by yuri-norwood** [comment]
Resolves #4886

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @yuri-norwood and thanks for the contributions. For ease of reviewing and so we can assess its popularity without blocking suckless could you separate dwm into another PR please?

**Comment by yuri-norwood** [comment]
Sure thing, I'll pop through two new PRs now 👍

**Comment by yuri-norwood** [comment]
Hi @PeterShaggyNoble, please see #4890 and #4890

**Pull request closed without merging**
