### PR TITLE
Add Floatplane (#2139)

### LINKED ISSUE #2139: Floatplane
**Name:** Floatplane
**Website:** https://www.floatplane.com/
**Official resources for icon and color:** website header
  
[Alexa rank](https://www.alexa.com/siteinfo/floatplane.com) at ~ 36k

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
Closes #2139

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo is from website header (already svg). Color `#08314B` is the calculated midpoint of the gradient they use in the website header's background.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
They use a lighter blue - `#00aeef` - in [their favicons](https://pbs.floatplanecdn.com/icons/apple-touch-icon-152x152.png) and another variant of that - `#00a1ea` - on their site.

**Comment by phatbhoy67** [comment]
Hey @runxel the .svg is great. 

I agree with @PeterShaggyNoble that blue might be the better choice here.

I think the `#00aeef` colour found in the favicons would be best.

**Comment by runxel** [comment]
Thank you for the comments! I've changed the color :)

**Comment by PeterShaggyNoble** [comment]
Nice work, @runxel. Merging this in.

**Pull request merged**
