### PR TITLE
Update Bun

### PR DESCRIPTION
**Pull request by colinhacks**
I'm a team member at Bun. This original version of this icon looked a little anemic at small sizes so this replaces it with a solid version.

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by LitoMore** [comment]
Hi @colinhacks. This looks very different from the original icon. Can you share where the modified new one appears in your products? Or any discussions about this change at https://github.com/oven-sh/bun?

BTW, Jarred selected the current one at this thread: https://discord.com/channels/876711213126520882/1014601416846872688/1014601416846872688.

**Comment by colinhacks** [comment]
@LitoMore We hadn't designed a version of our icon that's designed to work at very small sizes. The detail around the eyes and mouth doesn't translate to something icon-sized. We're attempting to use the current version of the icon in our documentation (as I mentioned, I'm an employee of Bun) but it didn't work aesthetically. 

I've added a presskit page to the `bun.sh` website: https://bun.sh/press-kit. If you download the ZIP file you'll see it contains `icon.svg` file that matches the one in this PR 👍

**Comment by LitoMore** [comment]
TBH, I prefer the current one with bright eyes. And it's consistent with the original design.



Let's ask for the project owner's opinion.

Hi @Jarred-Sumner, could you help to review this change?

**Comment by Jarred-Sumner** [comment]
@LitoMoore we want the fill version (this PR). It's better at small sizes and usually people will use a small icon, not a huge icon

**Review by Jarred-Sumner — APPROVED** [review]

**Comment by adamrusted** [comment]
Thanks @colinhacks and @Jarred-Sumner!
I'm seeing a _slight_ difference between the source icon (red) and the PR version (black)
image

Might just be down to SVGO precision, so perhaps worth regenerating with a precision of 4 decimals?

**Comment by adamrusted** [comment]
> Hey @adamrusted, where is that comparison from? The diff I'm seeing is more dramatic, and an inevitable side effect of the the switch to the fill icon. We exaggerated some of the features so it looks better at 24px. 

It's compared to the icon in the media kit on the site. The slight differences between that and the PR could be just down to optimization, given I'm assuming they're one and the same 😅

**Comment by colinhacks** [comment]
Gotcha! Yeah looks like the presskit contained an unoptimized version. I just updated the presskit to contain the same file in this PR.

**Comment by adamrusted** [comment]
One last time, with feeling.
The path was somehow aligned to the left-hand side of the canvas, and was 23.9px wide.
Path below is 24px wide exactly, and passes all our linters. If you could update the PR with the below, it'll be spot on - and bonus, you won't need to update the press kit as it matches perfectly when we scale it up ever so slightly!

```html
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Bun</title><path d="M12 22.596c6.628 0 12-4.338 12-9.688 0-3.318-2.057-6.248-5.219-7.986-1.286-.715-2.297-1.357-3.139-1.89C14.058 2.025 13.08 1.404 12 1.404c-1.097 0-2.334.785-3.966 1.821a49.92 49.92 0 0 1-2.816 1.697C2.057 6.66 0 9.59 0 12.908c0 5.35 5.372 9.687 12 9.687v.001ZM10.599 4.715c.334-.759.503-1.58.498-2.409 0-.145.202-.187.23-.029.658 2.783-.902 4.162-2.057 4.624-.124.048-.199-.121-.103-.209a5.763 5.763 0 0 0 1.432-1.977Zm2.058-.102a5.82 5.82 0 0 0-.782-2.306v-.016c-.069-.123.086-.263.185-.172 1.962 2.111 1.307 4.067.556 5.051-.082.103-.23-.003-.189-.126a5.85 5.85 0 0 0 .23-2.431Zm1.776-.561a5.727 5.727 0 0 0-1.612-1.806v-.014c-.112-.085-.024-.274.114-.218 2.595 1.087 2.774 3.18 2.459 4.407a.116.116 0 0 1-.049.071.11.11 0 0 1-.153-.026.122.122 0 0 1-.022-.083 5.891 5.891 0 0 0-.737-2.331Zm-5.087.561c-.617.546-1.282.76-2.063 1-.117 0-.195-.078-.156-.181 1.752-.909 2.376-1.649 2.999-2.778 0 0 .155-.118.188.085 0 .304-.349 1.329-.968 1.874Zm4.945 11.237a2.957 2.957 0 0 1-.937 1.553c-.346.346-.8.565-1.286.62a2.178 2.178 0 0 1-1.327-.62 2.955 2.955 0 0 1-.925-1.553.244.244 0 0 1 .064-.198.234.234 0 0 1 .193-.069h3.965a.226.226 0 0 1 .19.07c.05.053.073.125.063.197Zm-5.458-2.176a1.862 1.862 0 0 1-2.384-.245 1.98 1.98 0 0 1-.233-2.447c.207-.319.503-.566.848-.713a1.84 1.84 0 0 1 1.092-.11c.366.075.703.261.967.531a1.98 1.98 0 0 1 .408 2.114 1.931 1.931 0 0 1-.698.869v.001Zm8.495.005a1.86 1.86 0 0 1-2.381-.253 1.964 1.964 0 0 1-.547-1.366c0-.384.11-.76.32-1.079.207-.319.503-.567.849-.713a1.844 1.844 0 0 1 1.093-.108c.367.076.704.262.968.534a1.98 1.98 0 0 1 .4 2.117 1.932 1.932 0 0 1-.702.868Z"/></svg>
```

**Comment by colinhacks** [comment]
Looks like you beat me too it 👍

**Review by LitoMore — APPROVED** [review]

**Pull request merged**
