### PR TITLE
Remove Autotask

### PR DESCRIPTION
**Pull request by adamrusted**
Contributes to #5251.

Autotask now redirects to [Datto](https://www.datto.com/), and while it seems to still be a product of theirs - no obvious logos are shown.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
It looks like they've rebranded everything Autotask with Datto's branding. The only places I found the Autotask icon and logo in use were in PDFs that pre-dated the 2017 merger and in [this GH org](https://github.com/AutotaskDevelopment) with repos that have been updated since the merger. However, I don't think that alone is sufficient reason for us to add it.

As we added the icon _after_ the merger, though, I'm going to ping @moldypenguins, who originally requested it, and @atomicjeep, who contributed it, to see if they can shed any light on whether or not they still use the Autotask branding somewhere, assuming one of them is familiar with the product.

**Comment by moldypenguins** [comment]
<path xmlns="http://www.w3.org/2000/svg" d="M25.9958675,14.3271821 C25.8352069,20.4676553 21.0873056,25.4070746 15.1176191,25.9580238 L15.1176191,19.601837 C17.8128909,19.1313023 19.8623646,16.7818797 19.8623646,13.9521695 C19.8623646,11.4218382 18.2233403,9.27579448 15.9495156,8.51314769 L17.0612291,2.41761477 C22.3985059,3.82367309 26.141992,8.73345087 25.9958675,14.3271821 Z M14.1244884,8.21510731 C12.3935624,8.21510731 10.8429969,8.98243937 9.79105299,10.1942025 L4.73732284,6.3855582 C7.39730664,3.1109483 11.287013,1.56048813 15.4815918,2.10801422 L14.3667224,8.22122684 C14.2862965,8.21788023 14.2057749,8.21510731 14.1244884,8.21510731 Z M8.91449675,11.5488185 L3.80023202,7.69466016 C0.488511547,13.0269726 1.84931584,20.0858538 7.03218645,23.7819561 C9.03900867,25.2129706 11.0648615,25.9063902 13.5081449,26 L13.5081449,19.6557654 C10.6290698,19.3483545 8.38661213,16.9123979 8.38661213,13.9521695 C8.38661213,13.0937137 8.57644021,12.2801027 8.91449675,11.5488185" id="PSAIcon-White" fill-rule="nonzero" transform="translate(14.000000, 14.000000) scale(1, -1) translate(-14.000000, -14.000000) "/>

**Comment by moldypenguins** [comment]
looks like maybe a fade from #00457C to #518BC9
see datto logo as example: https://help.aem.autotask.net/en/Content/Resources/Images/2SETUPImages/Branding/Branding2_thumb_0_64.png

**Comment by adamrusted** [comment]
Amazing, thanks @moldypenguins!
I'll look to open an Issue for Datto, so we can continue with the removal of Autotask in v5.0.0.
Are you aware if this was just a name change, or a buy-out? We're looking to introduce 'alias' entries if a brand has been renamed.

**Review by PeterShaggyNoble — APPROVED** [review]
Seeing as the Autotask brand & branding looks to have been dropped by Datto altogether, I think it's safe to remove this one.

**Pull request merged**
