### PR TITLE
Added Ark Ecosystem logo

### LINKED ISSUE #4697: Add Ark Ecosystem Icon
**Brand Name: Ark Ecosystem**
**Website: https://www.ark.io**
**Alexa rank: [90,395](https://www.alexa.com/siteinfo/ark.io)**

**Official resources for icon and color: https://ark.io/images/logo.svg**

### PR DESCRIPTION
**Pull request by Moustikitos**
**Issue:** Fixes #4697
**Alexa rank:** [90,395](https://www.alexa.com/siteinfo/ark.io)

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by fbernhart** [comment]
@Moustikitos Thanks for you PR. It already looks very promising!

The icon looks great. 👍🏼 But looking at their website, they write themselves as "ARK Ecosystem", with the letters "ARK" capitalised. Could you change that?

And please as well point the `source` attribute to their press kit instead, which is https://ark.io/press-kit.

**Comment by Moustikitos** [comment]
Hi, Just done.
Any idea of the delay for availability of ARK Ecosystem logo ?
Thanks.

**Comment by fbernhart** [comment]
@Moustikitos Thanks. One last change:

I just saw that you were using a precision of 5. Whenever possible, we're trying to reduce the precision to 3 to decrease the file size. Could you optimize it with a precision of 3 instead?

> Any idea of the delay for availability of ARK Ecosystem logo ?

We're releasing new icons every Sunday at 0:00.

**Comment by fbernhart** [comment]
@Moustikitos Perfect! Thanks a lot for your work! 🏆

**Comment by Moustikitos** [comment]
@fbernhart Thanks 👍 
Nice project !

**Pull request merged**
