### PR TITLE
Add Android Auto

### LINKED ISSUE #2526: Android Auto
**Name:** Android Auto
**Website:** https://www.android.com/auto/
**Alexa Rank:** n/a (Android subdirectory)
**Colour:** `#3ddc84`
**Official resources for icon and color:** https://partnermarketinghub.withgoogle.com/#/brands/1fSUpZEKQJQHg77aw5ppyKX5lpFR4bOeX

Unsure of the best approach here, the icon is only available in full colour (PNG at the end of [this page](https://partnermarketinghub.withgoogle.com/#/brands/1fSUpZEKQJQHg77aw5ppyKX5lpFR4bOeX/1TIgcW9AH3Z7z15s9bXBHxIotiTQdFasbT29g0m7-tsQ)) with no explicit mention that it _can't_ be used in monochrome. They do have some specific limits on where it can be used, though, so we probably _would_ have to go with [the vertical wordmark](https://partnermarketinghub.withgoogle.com/viewasset/1mYxSQQ-lumagLTFRFbizDfuYoglirBXb-android-auto-marks_stacked_black_rgb-svg.svg/download).

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Android Auto

**Issue:** Closes #2526

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I can see the reasoning for Google Blue and would be OK to run with it if we get a consensus to do so.

**Comment by ericcornelissen** [comment]
> I can see the reasoning for Google Blue and would be OK to run with it if we get a consensus to do so.

Didn't realize that is Google Blue 😅 @simple-icons/maintainers or others, any opinions?

**Comment by PeterShaggyNoble** [comment]
Thanks, @runxel. Before I update, though, just want to double check that you & @ericcornelissen saw [this page](https://partnermarketinghub.withgoogle.com/#/brands/1fSUpZEKQJQHg77aw5ppyKX5lpFR4bOeX/1uE8LvGANEiG2dzrqwgGLw3ddl2FxFzrdLRxdkOnEnDo), where the primary brand colour is given as Android green?

**Comment by runxel** [comment]
Yes! We both did, I think.
Maybe they are transitioning the brand, but since the icon itself is not green I personally think it's weird to have it green. 😅 
Also the last time I had this app open there was no single green color to be seen for me. 🤷‍♂

**Comment by PeterShaggyNoble** [comment]
Just making sure 😉

Colour updated.

**Comment by PeterShaggyNoble** [comment]
> Also I just thought we might need to establish a rule where we state a how big a gap should be.

I've been going with 1dp.

**Comment by runxel** [comment]
> I've been going with 1dp.

Are you sure? 🤔 
I was measuring it and I remember the gap only to be 0.5 dp...

**Comment by ericcornelissen** [comment]
> Thanks, runxel. Before I update, though, just want to double check that you & ericcornelissen saw [this page](https://partnermarketinghub.withgoogle.com/#/brands/1fSUpZEKQJQHg77aw5ppyKX5lpFR4bOeX/1uE8LvGANEiG2dzrqwgGLw3ddl2FxFzrdLRxdkOnEnDo), where the primary brand colour is given as Android green?


I did as well and share @runxel's opinion.

**Comment by PeterShaggyNoble** [comment]
Seems everyone is in agreement so hope nobody minds me merging this 8n myself.

**Pull request merged**
