### PR TITLE
Add Houdini (#2493)

### LINKED ISSUE #2493: Houdini
**Name:** Houdini
**Website:** https://www.sidefx.com/products/houdini/
**Official resources for icon and color:** logo as svg is on site

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
Closes  #2493

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG taken from websites header. Color `#FF4713` from the svg, too.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Looks like this is just a hair taller than 24px, @runxel. Note that the original isn't quite square and that there are some "bumps" on the inner part of the spiral. It might be better to go with [this version](https://d2wvmrjymyrujw.cloudfront.net/media/uploads/products/overview/houdini_white.svg) which *is* square and doesn't include those "bumps" - although the spiral is slightly different in it.

**Comment by runxel** [comment]
Done! Thanks for the better version! 😘

**Comment by PeterShaggyNoble** [comment]
This looks good to go - just need to fix the missing `>` on the opening `svg` tag and it can be merged in.

**Comment by runxel** [comment]
🤦‍♂️ Always check twice before copy&pasting, kids!

**Pull request merged**
