### PR TITLE
Added Miscrosoft Azure icon

### PR DESCRIPTION
**Pull request by hylickipiotr**
**Issue:** #1377 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
@prologh
I've picked color from official Microsoft Azure logo.
Btw I found `svg` logo at the Wikimedia: https://upload.wikimedia.org/wikipedia/commons/a/a8/Microsoft_Azure_Logo.svg

### CODE REVIEW

**Comment by birjolaxew** [comment]
Are we confident that this is the right logo? It seems like they've discontinued its use on the public-facing website at least. Comparing [an old website](https://buildazure.com/2017/09/25/microsoft-azure-gets-a-new-logo-and-a-manifesto/) to now:

<p align="center">Old version (2017)</p>
<p align="center">New (2019)</p>

Everywhere I can find (including [their Twitter](https://twitter.com/Azure)) they now use the generic flat Microsoft logo.

**Comment by ericcornelissen** [comment]
Good point @birjolaxew, I had the same feeling when reviewing this PR. But since I'm not very familiar Azure I didn't mention it...

**Comment by hylickipiotr** [comment]
I only changed the URL because I do not have the final opinion about changing this logo to generic flat Microsoft logo

**Comment by birjolaxew** [comment]
To hopefully stop this from going stale, I'll be merging this in 2 days unless anyone objects. This decision is mostly based on the argument expressed earlier:

> It would probably still make sense to add this logo since it's unique to the product and generally accepted by the community as the Azure logo - but it's still worth noting that they seem to have officially moved away from it.

**Comment by birjolaxew** [comment]
:+1: Thanks for your work @hylickipiotr, it is much appreciated!

**Pull request merged**
