### PR TITLE
Konami icon

### PR DESCRIPTION
**Pull request by deepmalamittal**
konami

**Issue:https://github.com/simple-icons/simple-icons/issues/6660**
**Alexa rank:16,933**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by dirien** [comment]
Used `https://upload.wikimedia.org/wikipedia/commons/a/ab/Konami_4th_logo_1.svg` as reference

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @deepmalamittal,

I see some differences 
image

I used the wikipedia 4th Logo

**Comment by deepmalamittal** [comment]
@dirien Changes have been implemented. Please verify whenever you get a chance.
Let me know if some issue still prevails.

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @deepmalamittal,

i see still some differences
image


Maybe try a precission of 4? 

What do you think @jorgeamadosoria?

**Comment by jorgeamadosoria** [comment]
The logo was shifted slighly in the Y axis. I added a source for commons wiki and shifted the logo back up a bit, and it is a perfect match.
Please check @dirien

**Review by dirien — APPROVED** [review]
@jorgeamadosoria and @deepmalamittal,

looks perfect now!
image

**Pull request merged**
