### PR TITLE
Add Musixmatch

### LINKED ISSUE #7435: Request: Musixmatch
### Brand Name

Musixmatch

### Website

https://www.musixmatch.com/

### Popularity Metric

**[Similarweb rank](https://www.similarweb.com/website/musixmatch.com/#overview)**: 6,901

### Official Resources for Icon and Color

svg: `https://s.mxmcdn.net/site/images/logo.svg`
color: `#ff5145`

### Additional Comments

No

### Contributing

Yes

### PR DESCRIPTION
**Pull request by SebiTalent04**
musixmatch

**Issue:** closes #7435

**Similarweb rank:** 8,193
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I'm having some trouble with this: it should have a stroke to look more like the original icon, but the guidelines don't allow it.

Help will be appreciated!

Edit: should work I think

The link from the original .svg is [here](https://drive.google.com/drive/folders/14-RKGvjp8-ul3_Doctyv9aWZzAX-rGPK).
The color has been eyedropped from their header.

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for your work on this @SebiTalent04!
I can see the dilema you're having with this one! My typical suggestion would be to add a 0.5-1px line where each colour change is, and remove those from the path. That way, you're showing there would be a differentiation, but without having multiple colours or paths included. I'd suggest giving that a go for this one, and trying it with our [preview generator](https://petershaggynoble.github.io/SI-Sandbox/preview/) to see how it'd look. I'm concerned it may not display well with the lines at a smaller size.

**Comment by SebiTalent04** [comment]
I did something, might work if the linter would work too...

**Comment by adamrusted** [comment]
This PR currently contains no changes. I'm assuming this isn't intended, @SebiTalent04? 😅

**Comment by SebiTalent04** [comment]
Oops, I messed up, the other icons submitted by me should be at their places though.

**Comment by adamrusted** [comment]
No stress - just wanted to highlight in case you weren't aware :)

**Comment by adamrusted** [comment]
@SebiTalent04 - I'm going to close this one off as there are no changes showing in the branch. If you'd like to open another PR with the changes applied, that'd be much appreciated!

**Pull request closed without merging**
