### PR TITLE
Update Klook

### PR DESCRIPTION
**Pull request by adamrusted**
klook

### Description
Updated to use icon suggested by @PeterShaggyNoble in #3290 - was actually able to extract icon this time!

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
@adamrusted, what's the new id on the `symbol` containing this icon?

**Comment by adamrusted** [comment]
> what's the new id on the `symbol` containing this icon?

@PeterShaggyNoble it's referred to as `common-klook-app` within the first of 3 SVG definitions in the header.

```svg
<svg id="common-klook-app" viewBox="0 0 40 40"><defs><linearGradient id="common-klook-app__a" x1="50%" x2="50%" y1="0%" y2="100%"><stop offset="0%" stop-color="#FF5722"></stop><stop offset="100%" stop-color="#D84315"></stop></linearGradient></defs><g fill="none" fill-rule="evenodd"><rect width="40" height="40" fill="url(#common-klook-app__a)" rx="8"></rect><path fill="#FFF" d="M25.9 21.476a3.066 3.066 0 010 4.392l-8.415-8.263L25.9 9.34a3.066 3.066 0 010 4.392l-3.943 3.872 3.943 3.871zm-9.134 1.304c0 1.705-1.394 3.088-3.113 3.088V9.581c1.72 0 3.113 1.383 3.113 3.089v10.11zM20 5.749c-7.262 0-13.054 3.348-13.054 10.285 0 4.887 6.433 13.025 10.272 16.939 1.696 1.728 3.915 1.68 5.564 0 3.84-3.915 10.272-12.052 10.272-16.939C33.054 8.924 27.07 5.75 20 5.75z"></path></g></svg>
```

**Comment by PeterShaggyNoble** [comment]
Thinking back to my initial research on this, I seem to remember them being pretty consistent in using the boxed version of the icon, as seen in their favicon.



Could've sworn I posted this yesterday; must be going nuts!

**Comment by adamrusted** [comment]
> Thinking back to my initial research on this, I seem to remember them being pretty consistent in using the boxed version of the icon, as seen in their favicon.
> Could've sworn I posted this yesterday; must be going nuts!

Is this embedded in those SVGs too? If not (and you've still got the path to hand) feel free to merge it into here.

**Comment by PeterShaggyNoble** [comment]
There's a `rect` element in the source SVG you posted above but here's my unoptimised path, too, if you want it:

```
M 2.4,0 C 1.0704,0 0,1.0704 0,2.4 V 21.6 C 0,22.9296 1.0704,24 2.4,24 H 21.6 C 22.9296,24 24,22.9296 24,21.6 V 2.4 C 24,1.0704 22.9296,0 21.6,0 Z M 12,3.4488281 V 3.45 C 16.242,3.45 19.832813,5.3539219 19.832813,9.6199218 19.832813,12.552122 15.97275,17.434594 13.66875,19.783594 12.67935,20.791594 11.34885,20.820394 10.33125,19.783594 8.02785,17.435194 4.1671875,12.552122 4.1671875,9.6199218 4.1671875,5.4577219 7.6428,3.4488281 12,3.4488281 Z M 15.540235,5.6039063 10.490625,10.563281 15.540235,15.520313 A 1.8396,1.8396 0 0 0 15.540235,12.885937 V 12.884765 L 13.174219,10.56211 15.540235,8.2394532 A 1.8396,1.8396 0 0 0 15.540235,5.6039063 Z M 8.1914064,5.7480469 V 15.520313 C 9.2228064,15.520312 10.059375,14.690578 10.059375,13.667578 V 7.6019532 C 10.059375,6.5783532 9.2234064,5.7480469 8.1914064,5.7480469 Z
```

**Comment by adamrusted** [comment]
@PeterShaggyNoble Just went back to source and fixed it. Must've cut the original `rect` out when I made mine 😅

**Review by PeterShaggyNoble — APPROVED** [review]
Looks perfect to me, @adamrusted 👍🏻 And, as there have been no objections to using the boxed version, I'm going to merge this in. We can always change it in the future if anyone wants to make a case for the unboxed version.

**Pull request merged**
