### PR TITLE
add Fraunhofer-Gesellschaft

### LINKED ISSUE #5021: Fraunhofer-Gesellschaft
**Brand Name:** Fraunhofer-Gesellschaft
**Website:** [fraunhofer.de](https://fraunhofer.de) 
**Alexa rank:** [#59,300](https://www.alexa.com/siteinfo/fraunhofer.de) 
  

**Official resources for icon and color:**
https://commons.wikimedia.org/wiki/Category:Logos_of_Fraunhofer_Society

### PR DESCRIPTION
**Pull request by cyper85**
fraunhofer-gesellschaft

**Issue:** Closes #5021
**Alexa rank:** [#59,300](https://www.alexa.com/siteinfo/fraunhofer.de) 
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
German research organization with 74 institutes.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @cyper85 and thanks for the contribution.

Could you have another look at it, though, please? Assuming you used [this SVG](https://www.fraunhofer.de/content/dam/zv/fhg.svg) from the website's header as the source then note that the icon in it isn't quite a perfect square.

**Comment by PeterShaggyNoble** [comment]
Are you still working on these ones, @cyper85?

**Comment by fbernhart** [comment]
@cyper85 The icon looks perfect 👍🏼 

However, could you change the source to https://www.fraunhofer.de instead? As the [SVG](https://www.fraunhofer.de/content/dam/zv/fhg.svg) can be found in the header of their website.


The mentioned SVG as well has `#179C7D` as color. As I wasn't able to find any official brand guidelines, we should just stick with this color in my opinion.

Once you've changed that, your pull request an be merged. 😊

**Comment by adamrusted** [comment]
@fbernhart have made those changes, so we can get this PR closed. Would you mind just checking it over and merging?

**Comment by fbernhart** [comment]
Thanks @cyper85  for your work on this one. 👍🏼 And thanks @adamrusted for the slight changes.

**Pull request merged**
