### PR TITLE
Added B&R Automation

### LINKED ISSUE #3321: Icon request for B&R Automation
**Name:B&R**
**Website: https://www.br-automation.com/**
**Alexa rank:*194,230*
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by adamrusted**
b-and-rautomation

**Issue:** Closes #3321
**Alexa rank:** [179,013](https://www.alexa.com/siteinfo/br-automation.com)
### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG in header of site. Orange pulled from SVG.

### CODE REVIEW

**Comment by fbernhart** [comment]
@adamrusted Did you use [this SVG from the header](https://www.br-automation.com/typo3conf/ext/br_sitesetup/Resources/Public/Images/logo.svg) as source? Because I can see quite some differences (your version in green). The frame matches perfectly, but not the "B&R". Can you have another look at it?

image

**Comment by adamrusted** [comment]
@fbernhart - I've just rebuilt from source, and compared against the source SVG. Should be good to go now!

**Comment by fbernhart** [comment]
@adamrusted Strange ... I'm still seeing the same differences. 🤔   Are you sure you've pushed the correct file? 😅 The SVG in your new commit _almost_ looks the same as the one in your old commit.

**Comment by adamrusted** [comment]
@fbernhart yep - this is what I'm seeing on my end 😅 original icon below my path in pinkish-purple.

image

**Comment by fbernhart** [comment]
Are we using the same source? 😄 I'm using the SVG found in the header, which is:

https://www.br-automation.com/typo3conf/ext/br_sitesetup/Resources/Public/Images/logo.svg

It isn't actually a full SVG. The letters B&R are image data, therefore it looks pixelated. While yours doesn't. 🤔  Which source are you using?

**Comment by adamrusted** [comment]
@fbernhart I'm using exactly that. There's a weird texture mesh on it - which may just be an Illustrator thing. That may be causing the issue?

**Comment by fbernhart** [comment]
@adamrusted Oh, now I saw it. You're right! I only saw the image texture first. But there is as well a clipping path laying underneath. 👍🏼 

In Inkscape it's only displaying the texture by default, that's why it looked different on my side (see image) 😅  Thanks for the help! Let's merge it.

image

**Pull request merged**
