### PR TITLE
Add European Union icon

### LINKED ISSUE #11094: Request: European Union
### Brand Name

European Union

### Website

https://www.europa.eu

### Popularity Metric

The European Union (EU) is a supranational political and economic union of 27 member states that are located primarily in Europe.

Since international organizations are allowed, I think we need to put this here.

Its SimilarWeb rank is 826. https://www.similarweb.com/website/europa.eu/#overview

### Official Resources for Icon and Color

svg: https://commons.wikimedia.org/wiki/File:European_stars.svg
color: `#003399`

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by uncenter**
image

**Issue:** closes #11094.

**Popularity metric:** Its SimilarWeb rank is 826. [similarweb.com/website/europa.eu/#overview](https://www.similarweb.com/website/europa.eu/#overview).

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

The issue with this logo is the stars are so small it really doesn't look great at small sizes. Not sure if there is any way around it though.

### CODE REVIEW

**Comment by adamrusted** [comment]
@uncenter - can we get away with just the stars? Seems a bit of a waste of space to include the entire flag...

**Comment by uncenter** [comment]
image

How does this look?

**Comment by adamrusted** [comment]
Wow, that still looks _rubbish_ at smaller sizes...
Let me review the PR - and other @simple-icons/maintainers feel free to chip in if you can think of a better way of handling this icon

**Comment by mondeja** [comment]
I think that the second one with only starts, without the flag, looks good. Not all brands fit appropiatelly for small sizes.

**Comment by LitoMore** [comment]
This one is out of our scope.

**Comment by uncenter** [comment]
> This one is out of our scope.

As per our guidelines it is in scope:
> Allowed: International organizations and NGOs with supranational interests

**Comment by LitoMore** [comment]
European Union:

- ❌ International organizations
- ❌ NGOs with supranational interests

**Comment by uncenter** [comment]
It isn't an NGO but it is an international organization, and it literally is supranational lol.

**Comment by LitoMore** [comment]
It is an international organization but not supranational interests.

**Comment by uncenter** [comment]
This seems pretty clear to me.

> Beyond the borders or scope of any one nation. 

The EU is a union of nations. By definition it deals with issues and is itself beyond the borders or scope of any *one* nation. It is also literally a "supranational union":

> The [European Union](https://en.wikipedia.org/wiki/European_Union) (EU) has been described as a paradigmatic case of a supranational organization,[[2]](https://en.wikipedia.org/wiki/Supranational_union#cite_note-Kiljunen-2004a-2) as it has deep political, economic and social integration, which includes a [common market](https://en.wikipedia.org/wiki/Single_market), [joint border control](https://en.wikipedia.org/wiki/Schengen_Area), a [supreme court](https://en.wikipedia.org/wiki/European_Court_of_Justice), and regular [popular elections](https://en.wikipedia.org/wiki/Elections_to_the_European_Parliament).

**Comment by LitoMore** [comment]
This still does not meet NGOs. I don't want anyone to use this as an excuse to add NATO or other [country groupings](https://en.wikipedia.org/wiki/List_of_country_groupings) in the future.

**Comment by uncenter** [comment]
> This still does not meet NGOs.

This is not a requirement? I don't want to debate English semantics and grammar all day. If you don't want this added, go change the wording. As of now, this is allowed.

> International organizations and NGOs with supranational interests

The above sentence means either "international organizations" or "NGOs with supranational interests". If you wanted to stretch it you could say it means either "international organizations" or "NGOs", with "supranational interests". Under both interpretations, this is allowed.

**Comment by LitoMore** [comment]
> I don't want to debate English semantics and grammar all day. If you don't want this added, go change the wording. As of now, this is allowed.

I feel disrespect from your tone. In my understanding, these two conditions must exist. We can always seek advice from other maintainers. This is not up to me alone. My native language is not English, so please forgive me if I misunderstand your words.

**Comment by uncenter** [comment]
> I feel disrespected from your tone.

I'm sorry I came off that way, I'm frustrated that we are still debating these semantics.

> In my understanding, these two conditions must exist. We can always seek advice from other maintainers. This is not up to me alone. My native language is not English, so please forgive me if I misunderstand your words.

Sure, we can wait for some other maintainers to chime in. Just to reiterate though; I am a native English speaker, and I'm pretty confident that this is the intended interpretation. I think adding this is fine, but if you disagree I would suggest changing the wording in the guidelines to that effect, or adding an additional clause forbidding some category of these such as NATO like you mentioned.

**Comment by LitoMore** [comment]
Let's see what other maintainers think, I just don't want anyone to use our logo to promote their political stance.

On the other hand, the EU is also responsible for formulating many manufacturing-related standards, and I think it is acceptable to understand it this way. For example, the GDPR sign contains EU stars.

**Comment by adamrusted** [comment]
I agree with the reading of the rules as follows:

---

Either:
- An international organisation
- An NGO with supranational interests

---

The EU is categorically in the first camp here, it's a political organisation (though mostly safety legislation etc) based internationally.

I don't think there is necessarily the strong feeling toward 'the EU' that there may be toward particular political parties in different territories (which I'm against us adding, by the way).

I also think we will skirt around adding NATO (as was the example given) based on the fact it's primary focus is military, which we've made a point of not adding in the past, and I'd like us to continue moving forward.

**Review by LitoMore — APPROVED** [review]

**Comment by LitoMore** [comment]
Approving on this icon but the shape still needs to be discussed.

**Comment by adamrusted** [comment]
I've messaged @uncenter separately, based on the consensus above being to stick with just the stars. Hoping to have an update to the PR end of the week, and if not I guess it's fair game for one of us to push an update.

**Review by adamrusted — APPROVED** [review]
Perfect match, thank you @uncenter!

**Pull request merged**
