### PR TITLE
Updated Google News

### PR DESCRIPTION
**Pull request by adamrusted**
googlenews

**Issues:** Contributes to #3169 and #4205
**Alexa rank:** N/A

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Source updated.
Rebuilt from SVG as mentioned [here](https://github.com/simple-icons/simple-icons/issues/4205#issuecomment-748528744) using 0.~3~5px lines between items.
Ran through SVGO CLI.

#### Previous Treatment
googlenews

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
@adamrusted, there is an official monochrome SVG available [here](https://partnermarketinghub.withgoogle.com/#/brands/1C87X7OO4X-zyFTcp2QWMu7mXFdQHqD64/1yylUu1myx0pvtD7-Iq34px6pebB_0AgnAFgU84dBtBU). Also, keep an eye on their new branding site at https://thepartnermarketinghub.withgoogle.com/brands/google-news/visual-identity/visual-identity/lockups-visual-identity/ - all links are currently broken but may be updated soon.

**Comment by adamrusted** [comment]
@PeterShaggyNoble I've just updated the gaps on this one to 0.5px given I'm still unable to download the monochrome treatment on the website.

**Comment by PeterShaggyNoble** [comment]
Found a copy of the monochrome version in my WIP directory, if it helps: [googlenews.zip](https://github.com/simple-icons/simple-icons/files/5841767/googlenews.zip)

**Comment by adamrusted** [comment]
Amazing @PeterShaggyNoble - just pushed version with the SVG you provided.

**Comment by PeterShaggyNoble** [comment]
There's a slight difference in the inner curve of the `G` between the source and your version (in red below), @adamrusted. Also, I think the https://thepartnermarketinghub.withgoogle.com/brands/google-news/ will suffice for the source here.

**Comment by adamrusted** [comment]
Should be good to go @PeterShaggyNoble - rebuilt from source and compared against the SVG you provided. Unfortunately I needed to keep it at 4 decimals optimization for it to work though.

**Comment by PeterShaggyNoble** [comment]
Looks perfect now, @adamrusted. Although it also looks identical to my original version and, being as the file size or yours is larger, I wonder do we _need_ to update?

**Comment by adamrusted** [comment]
Happy to just make sure the source is up to date if the icons are identical.

**Comment by PeterShaggyNoble** [comment]
Strange that fixing them would increase rather than decrease the file size 🤷🏻‍♂️ But let's run with it.

**Pull request merged**
