### PR TITLE
Add Google Docs icon

### LINKED ISSUE #5155: Request: Google docs, forms, & slides
**Brand Name:** Google slides, Google Docs, Google Forms
**Website:** https://docs.google.com/
**Alexa rank:** 1! (Only because they're subdomains of Google 🙃)

**Official resources for icon and color:**
https://ssl.gstatic.com/docs/common/material_common_sprite259.svg
https://logos.fandom.com/wiki/Google_Drive  

Note: Google Sheets is [already added](https://github.com/simple-icons/simple-icons/blob/c690da95aeb1a2473fc1f69ec4f05ad0a33480a2/icons/googlesheets.svg) along with [lots of other Google products](https://simpleicons.org/?q=google)

- [x] Google Docs #8981
- [x] Google Forms #9080
- [x] Google Slides #9317

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
googledocs

**Issue:** closes #5155 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from website header https://www.google.com/docs/about
Color: `#4285F4` Taken from logo

### Material UI
Screenshot_20230709-223211
Unable to find the source for material UI icon for Google Docs but this is how it looks

### CODE REVIEW

**Comment by PratyushJayachandran** [comment]
If this looks fine I can do Forms and Slides icon in similar style

**Comment by adamrusted** [comment]
Looking at this, we have Google Keep and Google Sheets in a different style to this. Much though I like this interpretation, the icon gets lost on the small `shields.io` previews at the bottom there... What do we think @simple-icons/maintainers?

**Comment by service-paradis** [comment]
> Looking at this, we have Google Keep and Google Sheets in a different style to this. Much though I like this interpretation, the icon gets lost on the small `shields.io` previews at the bottom there... What do we think @simple-icons/maintainers?

I agree with you. I think it would be better to be consistent. I cannot find any official use on Google Docs Website using the outline icon.

**Comment by PratyushJayachandran** [comment]
> > Looking at this, we have Google Keep and Google Sheets in a different style to this. Much though I like this interpretation, the icon gets lost on the small `shields.io` previews at the bottom there... What do we think @simple-icons/maintainers?
> 
> I agree with you. I think it would be better to be consistent. I cannot find any official use on Google Docs Website using the outline icon.

I'll try that

**Comment by PratyushJayachandran** [comment]
> Looking at this, we have Google Keep and Google Sheets in a different style to this. Much though I like this interpretation, the icon gets lost on the small `shields.io` previews at the bottom there... What do we think @simple-icons/maintainers?

googledocs
Updated the icon based on review comments

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @PratyushJayachandran 🎉

**Pull request merged**
