### PR TITLE
Added Cloudron icon 

### LINKED ISSUE #8069: Request: Cloudron
### Brand Name

Cloudron

### Website

https://www.cloudron.io/

### Popularity Metric

Similarweb rank is 462,387 https://www.similarweb.com/website/cloudron.io/#overview

### Official Resources for Icon and Color

Color might be #05a9f4 from their icon. It's present when hovering over links, but also in tooltips.

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by simrahnb**
Added Cloudron icon ('cloudron.svg' to the icons folder and updated simple-icons.json)

**Issue:** closes #8069

**Similarweb rank:** 462,387

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I couldn't merge the two paths together on Inkscape without the icon overlapping.

### CODE REVIEW

**Review by adamrusted — COMMENTED** [review]
Thanks for this contribution @simrahnb!
It looks like you've still got multiple layers in your SVG, which should be merged down in whatever program you're using. Once you've taken a quick look at this, I'd be more than happy to review in full!

**Comment by PeterShaggyNoble** [comment]
This now [falls outside our scope](https://www.similarweb.com/website/cloudron.io/), with a rank of 592667. Will leave this PR open for now for further monitoring in case it improves.

**Comment by adamrusted** [comment]
As per @PeterShaggyNoble's comment above, closing for now as out of scope. Feel free to re-open if/when the brand comes back into scope @simrahnb.

**Comment by PeterShaggyNoble** [comment]
We've reopened this one for further monitoring, as it's now back _in_ scope. As its rank is so volatile, we'll be waiting for Similarweb's next monthly update to see what happens.

**Comment by PeterShaggyNoble** [comment]
I think we can now say this is within our scope. @simrahnb, would you like to continue working on it?

**Review by adamrusted — APPROVED** [review]
For some reason my editor is removing the rounded corners on the inner squares, but this looks to be a perfect match. Thanks @simrahnb for the initial work, and @PeterShaggyNoble for finishing this off!

**Pull request merged**
