### PR TITLE
Remove Microsoft brands

### LINKED ISSUE #11236: Removal: All Microsoft Icons
### Brand Name

Microsoft Brands & Products

### Reason for Removal

We have received notification from Microsoft's legal team that the only brands / products of theirs we can include are available at the below sources, without any edits being made:

- [Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/icons)
- [Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/get-started/icons)
- [Microsoft 365](https://learn.microsoft.com/en-us/microsoft-365/solutions/architecture-icons-templates?view=o365-worldwide)
- [Azure](https://learn.microsoft.com/en-us/azure/architecture/icons/)

Looking at our Microsoft collection, almost every icon either required significant edits - or are not from one of the above sources. As such, we are required to remove them as soon as we can. I've pulled v13.0.0 forward to 29th June to ensure we comply.

### Related PR

- https://github.com/simple-icons/simple-icons/pull/10019

### PR DESCRIPTION
**Pull request by adamrusted**
Closes #11236

[Microsoft Trademark Terms](https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks) prohibit us using the icons without explicit permission. This PR serves to remove them as of ~~04/01/2024~~  24/11/2024 - and we'll work to seek permission to re-add once completed.

## [Explicit Microsoft Products](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWArzw)

- Azure Artifacts
- Azure Data Explorer
- Azure DevOps
- Azure Functions
- Azure Pipelines
- C# - Unapproved Microsoft source.
- ~~C++~~ - Trademark is for `Visual C++` which is the term used when compiling C++ code within Visual Studio.
- Dataverse
- Dynamics 365
- ~~F#~~ - Trademark is for `Visual F#` which is the term used when compiling F# code within Visual Studio.
- Internet Explorer
- Microsoft
- Microsoft Academic
- Microsoft Access
- Microsoft Azure
- Microsoft Bing
- Microsoft Edge
- Microsoft Excel
- Microsoft Exchange
- Microsoft OneDrive
- Microsoft OneNote
- Microsoft Outlook
- Microsoft PowerPoint
- Microsoft SharePoint
- Microsoft SQL Server
- Microsoft Store
- Microsoft Teams
- Microsoft Translator
- Microsoft Visio
- Microsoft Word
- Minecraft
- Mojang Studios
- Playwright - Microsoft repo source.
- Power Apps
- Power Automate
- Power BI
- Power Fx
- Power Pages
- PowerShell
- Power Virtual Agents
- Skype
- Skype for Business
- Visual Basic
- Visual Studio
- Visual Studio App Center
- Visual Studio Code
- Windows
- Windows 10
- Windows 11
- Windows 95
- Windows Terminal
- Windows XP
- Xamarin
- XAML - Microsoft repo source.
- Xbox
- Yammer

### CODE REVIEW

**Comment by LitoMore** [comment]
I don't think Microsoft will take down our icons.

**Comment by Lordfirespeed** [comment]
> Their terms specifically say you need permission to include them. Regardless of whether or not we think they'll send a take-down, we _should_ obtain permission before continuing to have them in our collection.

Here's hoping the Microsoft (and/or Adobe) icons make a return in a future release!

**Comment by adamrusted** [comment]
> This PR is ruining our collection.

It's a heavy blow, for sure - however we should've historically identified the need to ask for consent. The fact we did not at the time means the least we can do is retroactively remove the offending icons, and seek permission to add them again. 

Given how long the icons have been in the collection without issue thus far, you're probably right in that they don't care too much - but that doesn't mean we should ignore their trademark terms.

**Comment by PratyushJayachandran** [comment]
> The use of the F# Software Foundation Logo for F# is welcome and encouraged when used in a way that is supportive of the mission statement of the F# Software Foundation. Individuals and companies are encouraged to incorporate the F# Software Foundation logo for F# on their website, brochures, and other media for activities that support the mission of the foundation.

Refer: https://foundation.fsharp.org/logo

**Comment by PratyushJayachandran** [comment]
C++ is not owned by Microsoft.

https://isocpp.org/home/terms-of-use

We should probably update this logo though and ask for permission.

**Comment by PratyushJayachandran** [comment]
C is not owned by Microsoft either.

The current logo in simple icons is from the cover page of the book "The C Programming Language" published by [Prentice Hall](https://en.m.wikipedia.org/wiki/Prentice_Hall), now defunct company.

We can probably keep using the icon.

**Comment by adamrusted** [comment]
I think we need to refer to [the threshold of originality](https://commons.wikimedia.org/wiki/Commons:Threshold_of_originality) where possible, and potentially adapt something similar (officially) ourselves. I would argue, given we're not restricted to one territory - we should adhere to the strictest possible rules on copyright, that being that if guidance is place, or the shape is complex enough to not be classed as a 'basic shape' (uses a custom font or illustration, essentially) then we have to adhere to copyright rules.

In that respect, both the C++ and C# icons we include would fall under 'too simple to copyright' - based on my understanding of the above link.

**Comment by service-paradis** [comment]
We might need to add Internet Explorer to this list. Anyway, it is kind of deprecated now...

**Comment by adamrusted** [comment]
Internet Explorer is already on the list ;)

**Comment by service-paradis** [comment]
> Internet Explorer is already on the list ;)

Yesterday felt like a difficult day. You confirmed it was 😅

**Comment by adamrusted** [comment]
@service-paradis

**Comment by LitoMore** [comment]
You will get the attention of a lot of GitHub users.

**Comment by adamrusted** [comment]
Oh I know it will, but in the absence of us having permission, we will need to remove them.

**Comment by LitoMore** [comment]
Guess what? Even Mircosoft is using them. Like this one:

https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/includes/get-status-badge.md

**Comment by adamrusted** [comment]
Unless I'm missing something, that's a statically generated badge which, being the rightsholders to that icon, they're totally able to do. Point being I don't think _we_ as a project should make their icons available without their permission, given the size of the org and the confusing nature of their ToS.

If we can get written permission from Microsoft to continue hosting these icons, then we're good.

**Comment by LitoMore** [comment]
Would you mind sending them an email? The email address of their open-source team can be found at https://github.com/microsoft.

**Comment by adamrusted** [comment]
See Discord :)

**Comment by adamrusted** [comment]
Microsoft were contacted 22nd April 2024, meaning by [our guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission) they have until 22nd June 2024 to respond, before we should re-visit this removal.

My gut tells me at that point we should look to remove all Microsoft icons, and only retain/add where explicit permission is given moving forward. Probably one to line up for v13.

**Comment by bsdayo** [comment]
I'm not contempting for the trademark law, but I'm curious that do ALL of the icons in this repository got explict permissions? If not, why do you only removing Microsoft-related icons?

Removing these **widely-used** icons will only break many things, such as many project badges (ones related to Microsoft technologies). As Microsoft didn't contacted the maintainers for taking down, I highly recommend you to think again before finally removing these. Thanks.

**Comment by adamrusted** [comment]
You're correct - a lot of other companies will not have given explicit permission. The difference here is that Microsoft (and Adobe, for that matter) are incredibly obscure with their Terms. Some documents say zero permission is granted, whereas others grant full access for specific use cases. We have reached out to Microsoft for guidance, but have yet to hear back.

**Comment by adamrusted** [comment]
An update on this, we've heard back from Microsoft saying the below sources are the officially available icons, providing users accept the terms laid out on those pages. Given our icons _have_ been altered to suit our monochrome requirements, I've asked for further clarification as to whether they are okay - or whether we need to continue removing them. By the looks of things none of the suggested sources contain truly monochrome icons - so pending the outcome of this communication, we may need to remove most of them still @simple-icons/maintainers

**Comment by adamrusted** [comment]
Response from Microsoft's lawyers is that we can only include icons from the architecture icon packs, and only if we do not alter them in any way (colour, path, etc). This therefore means all of the above icons (have removed a few) need to be removed. No timeline given, so I will keep it scheduled for v13.0.0.

**Comment by adamrusted** [comment]
@simple-icons/maintainers - can we please get an approval on this prior to the weekend?

**Review by PratyushJayachandran — APPROVED** [review]

**Comment by ClaytonTDM** [comment]
man, rip

**Comment by d-kleine** [comment]
> Response from Microsoft's lawyers is that we can only include icons from the architecture icon packs, and only if we do not alter them in any way (colour, path, etc). This therefore means all of the above icons (have removed a few) need to be removed. 

@adamrusted Given that, why did you need to remove these specific icons? I don't not fully understand the reasoning behind it, could you please elaborate on that?

**Comment by uncenter** [comment]
We need to optimize and merge the paths of the icons and they are presumably not like that from the source.

**Comment by uncenter** [comment]
We've informed them about our project and how we use their icons, described in the above comments. Another response won't change anything.

**Comment by LIGMATV** [comment]
LOL. Microsoft even not care about the users who paid for they're services, what's more this. They just want money, the whole rules is just an decoration. No one cares.

**Comment by vshymanskyy** [comment]
Ok I'm just replacing the Windows Icon with a :hankey:

**Comment by LIGMATV** [comment]
Are it's... just get merged? I was hope that the microsoft icons was puted like in archive branch...
Ah yes, they're still exist in [12.4.0](https://github.com/simple-icons/simple-icons/blob/12.4.0/icons/microsoft.svg) and older branch :)

**Pull request merged**
