### PR TITLE
Add PaddlePaddle icon

### LINKED ISSUE #8460: Request: PaddlePaddle
### Brand Name

PaddlePaddle

### Website

https://www.paddlepaddle.org.cn/en

### Popularity Metric

The PaddlePaddle rank is 124,703. See [https://www.similarweb.com/website/paddlepaddle.org.cn](https://www.similarweb.com/website/paddlepaddle.org.cn)

### Official Resources for Icon and Color

png: [https://paddlepaddle-org-cn.cdn.bcebos.com/paddle-international-site-web/static/media/logo.42424ce5.png](https://paddlepaddle-org-cn.cdn.bcebos.com/paddle-international-site-web/static/media/logo.42424ce5.png)
color: `#3334E3`, from the website header

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by geoyee**
paddlepaddle

**Issue:** closes #8460 

**Similarweb rank:**
  
Global Rank is [124,703](https://www.similarweb.com/website/paddlepaddle.org.cn/#overview) and Github star is [19.9k](https://github.com/PaddlePaddle/Paddle)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I have vectorized the official PNG using Illustrator

### CODE REVIEW

**Comment by LitoMore** [comment]
@geoyee Could you please ask their team to provide an original vector version of the logo?

**Comment by geoyee** [comment]
ok, i will try to do that tmrw



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/02/2023 16:22 |
| To | ***@***.***> |
| Cc | Yizhou ***@***.***>***@***.***> |
| Subject | Re: [simple-icons/simple-icons] Add PaddlePaddle icon (PR #8461) |

@geoyee Could you please ask their team to provide an original vector version of the logo?

**Comment by geoyee** [comment]
@LitoMore This is original vector logo from their team

image

I changed `Circle` to `Path` and modified it as required by `sample-icons`

paddlepaddle

**Comment by LitoMore** [comment]
Thank you, @geoyee! Would you mind pasting the original SVG here in case we can review this?

**Comment by geoyee** [comment]
> Thank you, @geoyee! Would you mind pasting the original SVG here in case we can review this?

it is a `.ai` file, do you means export SVG by illustrator?

**Comment by LitoMore** [comment]
@geoyee OK, then please share the `.ai` file directly. You could pack it to `.zip` and then upload it.

**Comment by geoyee** [comment]
> @geoyee OK, then please share the `.ai` file directly. You could pack it to `.zip` and then upload it to your comment.

of course [PaddlePaddle-CMYK.zip](https://github.com/simple-icons/simple-icons/files/11136205/PaddlePaddle-CMYK.zip)

**Comment by LitoMore** [comment]
CleanShot 2023-04-03 at 16 32 24@2x

@geoyee I found some differences.

The expected size should be:

CleanShot 2023-04-03 at 16 34 43@2x

But yours:

CleanShot 2023-04-03 at 16 35 26@2x

Could you recheck this?

**Comment by geoyee** [comment]
> CleanShot 2023-04-03 at 16 32 24@2x
> 
> @geoyee I found some differences.
> 
> The expected size should be:
> 
> CleanShot 2023-04-03 at 16 34 43@2x
> 
> But yours:
> 
> CleanShot 2023-04-03 at 16 35 26@2x
> 
> Could you recheck this?

ok, you are so careful 😃

**Comment by geoyee** [comment]
this is the error between the two images after update

error

**Comment by geoyee** [comment]
> this is the error between the two images after update
> 
> error

i am certain that i can not achieve a better result. i have tried multiple times 😭

**Comment by LitoMore** [comment]
@geoyee Because it loses precision when you convert `.ai` to `.svg`.

Could you try [Inkscape](http://inkscape.org)? The Inkscape allows selecting the precision when importing the `.ai` file to the canvas. The precision `2.0` is enough to use.

CleanShot 2023-04-03 at 18 31 25@2x

**Comment by geoyee** [comment]
sure, thank you for your advice, i never use it. i will try after dinner.



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/03/2023 18:34 |
| To | ***@***.***> |
| Cc | Yizhou ***@***.***>***@***.***> |
| Subject | Re: [simple-icons/simple-icons] Add PaddlePaddle icon (PR #8461) |

@geoyee Because it loses precision when you convert .ai to .svg.

Could you try Inkscape? The Inkscape allows selecting the precision when importing the .ai file to the canvas. The precision 2.0 is enough to use.

**Review by LitoMore — APPROVED** [review]
CleanShot 2023-04-03 at 22 58 41@2x

@geoyee Perfect fit now! Thank you for your contribution!

**Pull request merged**
