### PR TITLE
feat(clickhouse): add clickhouse icon

### PR DESCRIPTION
**Pull request by tiagomichaelsousa**
clickhouse

**Issue: n/a**
**Alexa rank: ~86.5k**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon from SVG in website through [svg-grabber](https://chrome.google.com/webstore/detail/svg-grabber-get-all-the-s/ndakggdliegnegeclmfgodmgemdokdmg), colour is the background colour of the logo itself `#FFCC01` 
Used [inkscape](https://inkscape.org/) to vectorize the icon as it was suggested in the [CONTRIBUTING.md](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) file

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome (again!) to Simple Icons, @tiagomichaelsousa and thanks for the contribution 🙂

When [comparing your SVG](https://user-images.githubusercontent.com/15157491/119971817-5e747200-bfa9-11eb-90aa-dd53121137a4.png) (in red) to [the one in the website's header](https://clickhouse.tech/images/clickhouse-black.svg), I'm seeing some small differences so could you have another quick look at it, please? Or did you base your your version off another file? If so, let us know and we'll compare against that first.

**Comment by tiagomichaelsousa** [comment]
> Welcome (again!) to Simple Icons, @tiagomichaelsousa and thanks for the contribution 🙂
> 
> When [comparing your SVG](https://user-images.githubusercontent.com/15157491/119971817-5e747200-bfa9-11eb-90aa-dd53121137a4.png) (in red) to [the one in the website's header](https://clickhouse.tech/images/clickhouse-black.svg), I'm seeing some small differences so could you have another quick look at it, please? Or did you base your your version off another file? If so, let us know and we'll compare against that first.

Hey again @PeterShaggyNoble 🤗

Regarding this icon I had some doubts when generating the svg. I used the svg-grabber (as mention in the PR description) to get [the original svg](https://clickhouse.tech/images/logo.svg). Regarding the differences of the icons, are we talking about the favicon vs the logo with text or the black borders around this [red icon](https://user-images.githubusercontent.com/15157491/119971817-5e747200-bfa9-11eb-90aa-dd53121137a4.png)?
I have to admit that I never edited svg icons and was quite complicated for me to match all the criteria that simple-icons requires with inkscape. What do you normally use to create the SVG ? If you guys have content regarding how it's the best way to generate the icon with inkscape would be nice.

Also, if you need anything feel free to reach me out through [twitter](https://twitter.com/tmichaelsousa) 🙂

**Comment by PeterShaggyNoble** [comment]
Sorry, I linked to the wrong source SVG above 🤦🏻‍♂️

My comparison was between the one you "grabbed" and linked above, in black, and your version, in red pointing out some minor differences where they don't exactly line up.

If it's any help, here's a step-by-step tutorial for Inkscape starting from scratch.
1. Select everything and unify it (`Path > Union` or <kbd>Ctrl + +</kbd>)
2. Open the document's properties (`File > Document Properties...` or <kbd>Ctrl + Shift + D</kbd>)
3. Set the value of "Scale x" to `1` and then change both the width & height to `24`.
4. Select your unified path with the select and transform tool (<kbd>S</kbd>)
5. Click the lock icon between the "W" & "H" fields in the toolbar and then set the value of "W" to 24.
6. Open the alignment tools (`Object > Align and Distribute...` or <kbd>Ctrl + Shift +</kbd>)
7. Ensure "Page" is selected in the "Relative to" field and then click "Center on vertical axis" & "Center on horizontal axis"

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @tiagomichaelsousa?

**Comment by tiagomichaelsousa** [comment]
> Are you still working on this one, @tiagomichaelsousa?

Hey @PeterShaggyNoble,

Sorry, busy weeks around here 😅
I'll try to update this ASAP and I will let you once I update the icon.

Sorry once more for any inconvenience

**Comment by tiagomichaelsousa** [comment]
@PeterShaggyNoble already updated the svg 🙂  hope everything is okay now

**Comment by ericcornelissen** [comment]
I'm a bit surprised the SVG is 24px high as [this SVG](https://clickhouse.tech/images/logo.svg) is wider than it is tall 🤔 But, reading [Peter's comment](https://github.com/simple-icons/simple-icons/pull/5753#issuecomment-853937982) I'm not sure if that was the intention or not, could you confirm this @PeterShaggyNoble?

Apologies for the inconvenience @tiagomichaelsousa 😅 If you want to work on this now, I will give this an approval if you redo this without vertically stretching the icon (and, since v5 has been released, removing "icon" from the `<title>`), as other than that the SVG looks perfect. However, if you want to be sure, you may want to wait for Peter's response for a couple days (say 4) first.

**Comment by dirien** [comment]
@service-paradis and @ericcornelissen, i create a new PR under https://github.com/simple-icons/simple-icons/pull/6854 to finish this.

We can close this one

**Pull request closed without merging**
