### PR TITLE
Add Virgin Atlantic

### LINKED ISSUE #7100: VIRGIN ATLANTIC
### Brand Name

Virgin Atlantic

### Website

https://www.virginatlantic.com/

### Popularity Metric

Virgin Atlantic is a UK airline

### Official Resources for Icon and Color

https://commons.wikimedia.org/wiki/File:Virgin_Atlantic_logo.svg

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Virgin Atlantic

**Issue:** closes #7100

**Similarweb rank:** [15152](https://www.similarweb.com/website/virginatlantic.com)

### Checklist
- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

### Description
Icon & colour from [SVG](https://content.virginatlantic.com/content/vaa/www/gb/en.damAssetRender.20230301T0629203960500.html/content/dam/virgin-applications/images/idp-shopping/VA_ST_lockup_RGB_POS_v4.svg) in [source](https://www.virginatlantic.com) header.

### CODE REVIEW

**Comment by service-paradis** [comment]
Did not reviewed yet, but since brand guidelines are available at https://brand.virginatlantic.com/assetbank-virginatlantic/action/viewLogin (linked from https://flywith.virginatlantic.com/eu/en/partner-hub/brand-library.html), we might create an account to view guidelines and assets available.

**Comment by PeterShaggyNoble** [comment]
Its worth a try, @service-paradis, but, from past experience, companies tend to be selective about who they give access to. I've registered myself, anyway; let's see how it goes.

**Comment by PeterShaggyNoble** [comment]
No reply as yet, @service-paradis, nor do I expect one. So I'd suggest we proceed with this as-is and if they ever _do_ reply to me then we can address any changes that might be needed in a new PR.

**Review by service-paradis — APPROVED** [review]
LGTM 🎉

**Pull request merged**
