### PR TITLE
Add Shotcut

### LINKED ISSUE #3593: Shotcut video editor
**Name:** Shotcut
**Website:** http://shotcut.org/
**Alexa rank:** 16.9 k
  

**Official resources for icon and color:**
  
[Shotcut logo](https://www.shotcut.org/assets/img/media/shotcut-logo-512x512.png)
Brand color: #115C77

### PR DESCRIPTION
**Pull request by adamalston**
shotcut

Closes #3593

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one on, @adamalston :+1:

However, I think the outlined version would be more faithful to the original. What do the other @simple-icons/maintainers think?

(Side note: Could you leave a comment on issues you're working on or planning to work on? That way we can assign the issue to you and avoid the potential of anyone else working on it simultaneously.)

**Comment by adamalston** [comment]
Sure, in general I just look at issues that have been inactive for > 2 weeks.

**Comment by adamrusted** [comment]
Oh that original logo isn't nice at all!
I think I agree with @PeterShaggyNoble in that we need to try and keep the line in-tact. Would something like the below work better?

simpleicons

```svg
M0 0h6.667v24H0v-.889h5.778V.889H0V0zm7.556 0v24H24v-.889H8.444V.889H24V0H7.556zm1.388 22.611H24V1.389H8.944v21.222zM5.278 1.389H0v21.222h5.278V1.389z
```

**Comment by adamrusted** [comment]
Thanks for the update @adamalston - I'll wait for another @simple-icons/maintainers to review this before merging though 👌🏻

**Comment by ericcornelissen** [comment]
I would say all versions in this thread "work" in that they are quite faithful to the original and can represent what I think the original tries to represent - moving frames (or am I the only one? :thinking:). I think both the original version and the version by @adamrusted are good options, both are legible at small sizes. I feel like the version by @adamrusted is the hardest to confuse with a different symbol (e.g. I can't help but see [the I-beam pointer](https://en.wikipedia.org/wiki/Cursor_(user_interface)#/media/File:I-beam_pointer.png) in @PeterShaggyNoble's version) and I would therefore choose it.

**Comment by adamrusted** [comment]
Fab, thanks for the input @ericcornelissen - could a @simple-icons/maintainers look to review this one, being as the path used is one I contributed toward?

**Review by PeterShaggyNoble — APPROVED** [review]
Looks good to me; nice work @adamalston & @adamrusted 👍🏻 Both the path and the colour line up with [this SVG](https://github.com/mltframework/shotcut_web/blob/master/assets/img/media/shotcut%20logo%203.svg) I just found.

**Pull request merged**
