### PR TITLE
Update Uber and Telegram

### LINKED ISSUE #574: Update: Telegram
The Telegram icon is incorrect. See the Favicon on the official site for an example of a monochrome icon: https://telegram.org/.

The press page does not offer a monochrome version.

### LINKED ISSUE #575: Update: Uber
I think we should be using the Uber icon instead of the full logo.

Design Guidelines:
https://d1a3f4spazzrp4.cloudfront.net/uberex/Uber_API_Design_Guidelines_20160329.pdf

Official SVG taken from their brand assets .zip found [here](https://developer.uber.com/docs/riders/guides/design-guidelines):
```svg
<svg id="Content" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 34 34"><defs><style>.cls-1{fill:#fff;}</style></defs><title>svg</title><rect x="0.5" y="0.5" width="33" height="33" rx="2.5" ry="2.5"/><path class="cls-1" d="M32,2a2,2,0,0,1,2,2V32a2,2,0,0,1-2,2H4a2,2,0,0,1-2-2V4A2,2,0,0,1,4,2H32m0-1H4A3,3,0,0,0,1,4V32a3,3,0,0,0,3,3H32a3,3,0,0,0,3-3V4a3,3,0,0,0-3-3h0Z" transform="translate(-1 -1)"/><path class="cls-1" d="M18,8a10,10,0,0,0-9.95,9H15V15.5a0.5,0.5,0,0,1,.5-0.5h5a0.5,0.5,0,0,1,.5.5v5a0.5,0.5,0,0,1-.5.5h-5a0.5,0.5,0,0,1-.5-0.5V19H8.05A10,10,0,1,0,18,8Z" transform="translate(-1 -1)"/></svg>
```

### PR DESCRIPTION
**Pull request by xdesro**
Fixes #575, fixes #574

### CODE REVIEW

**Comment by davidklebanoff** [comment]
The icon appears to have padding around the edges. Can you scale it so the icon fills the viewbox?

**Comment by xdesro** [comment]
Hey David, I'm happy to talk about that. A little hesitant because the icons I've been pushing up till now have all had the one pixel trim zone indicated in Material Design guidelines, which is referenced in the contributing guidelines. Can @birjolaxew weigh in on the official standard for this? I may have many icons to update 😉

image

**Comment by davidklebanoff** [comment]
Ah, excellent points @xdesro. I had no idea. I opened a separate issue to allow a more formal discussion and not dirty up this pull-request. Find it here #582.

Seeing as the padding of the current Simple Icons is not super consistent, I would go ahead and merge this in regardless of the padding discussions. :)

They look good by the way, thanks for the updates.

**Comment by birjolaxew** [comment]
:+1: Merged so far. Updating padding will be a massive bit of work anyway, one or two icons won't make a huge difference ;)

**Pull request merged**
