### PR TITLE
Steemit

### PR DESCRIPTION
**Pull request by atomicjeep**
Not sure about original colour for the data file.  I have used the hex colour #06D6A9 (green) referenced in the css.  #345

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Actually #345 is about [Steem.io](https://steem.io/). Regardless [Steemit]() seems to be a pretty popular website ([ranked at ~3000](https://www.alexa.com/siteinfo/steemit.com)). The icon and details look good, but there are some issues with your SVG though, from the Travis CI logs:

```
x icons/steemit.svg
  x attr-1 0:0 Expected attribute 'role', didn't find it
                 At node <svg> (0:0)
  x custom-1 'aria-labelledby' and 'id' should match, were 'simpleicons-steemit
             -icon' and 'undefined'
```

**Comment by atomicjeep** [comment]
should have referenced #799 I'll have a look at the SVG

**Comment by atomicjeep** [comment]
sorted, no idea what it was, I just replaced the attributes & title(missing from my first commit, oops)

**Comment by birjolaxew** [comment]
That's exactly what it was ;) Looking good now! :+1: Thanks for your work on this.

**Pull request merged**
