### PR TITLE
Added Ticketmaster

### LINKED ISSUE #1516: Ticketmaster Icon
**Name:** Ticketmaster
**Website:** https://www.ticketmaster.com/
**Official resources for icon and color:** http://design.ticketmaster.com/brand/overview/

### PR DESCRIPTION
**Pull request by adamrusted**
ticketmaster

**Issue:** Closes #1516
**Alexa rank:** [3,868](https://www.alexa.com/siteinfo/ticketmaster.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Picked up stale issue.
SVG available at source, as well as full colour guidance.

### CODE REVIEW

**Comment by fbernhart** [comment]
@adamrusted Do you remember with SVG you took as source?

Neither the one with the trademark in the footer of the site nor the one with the trademark in the "®Registered Trademark Usage" section matches.

**Comment by adamrusted** [comment]
@fbernhart I believe it was in the ZIP file available from [this page](https://design.ticketmaster.com/brand/logos/), but I'll check again when I get a moment.

**Comment by adamrusted** [comment]
@fbernhart it would've been `RGB/SVG/Azure.svg` that I used from [this page](https://lne.app.box.com/s/995l7oust2nd2lqiym2ps5kxa7zczkob)

**Comment by fbernhart** [comment]
@adamrusted I would assume that the file you've used (which is back from 2018) might be slightly outdated. I guess the SVG in the footer of https://design.ticketmaster.com/brand/logos should be more up to date.

These are the differences:
image

If you agree, would you mind rebuilding from the footer?

**Comment by adamrusted** [comment]
@fbernhart sorted, though I needed to use a precision of 4 on it.

**Comment by fbernhart** [comment]
@adamrusted Thanks! Looks great now 💯

**Pull request merged**
