### PR TITLE
Add X.Org icon (#1937)

### PR DESCRIPTION
**Pull request by phatbhoy67**
**Issue: #1937**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Source is [wikimedia .svg](https://upload.wikimedia.org/wikipedia/commons/9/90/X.Org_Logo.svg).

Hex value `#F28834` is calculated [midpoint](https://meyerweb.com/eric/tools/color-blend/#FEC350:E54C18:1:hex) of orange gradient (stops: `#FEC350`, `#E54C18`) used in logo.

Built on GitPod, working as expected.

### CODE REVIEW

**Comment by runxel** [comment]
Hey @phatbhoy67, thanks for the work on this one!
The color is a smart choice (I also already wondered what the color should be). I support that one.

However: This svg also suffers from the overzealous whitespace consumption of SVGOMG (see #2061 for a technical explanation). Since this currently a problem I would suggest you minimize the SVG just with the commandline tool (for which I also updated the [.svgo.yml](https://github.com/simple-icons/simple-icons/blob/develop/.svgo.yml), which prevents the problems of #2061 otherwise also present at the default cmdline tool config).

**Comment by phatbhoy67** [comment]
Hey @runxel do you mean you can't see it in your fancy premium software? 🙀 🎣 🤣

**Comment by phatbhoy67** [comment]
This is the icon optimised with SVGO:

```xml
<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>X.Org icon</title><path d="M19.94 1.9l-9.092 11.874 4.598 6.392a14.29 14.29 0 0 1-2.56.228c-2.387 0-4.582-.577-6.316-1.542l6.556-8.627-6.031-8.311L2.23 1.91 9.8 12.48l-4.332 5.66c-1.692-1.266-2.729-2.965-2.729-4.832 0-2.13 1.348-4.042 3.48-5.342l-.655-.999C2.22 8.386 0 10.876 0 13.71c0 2.432 1.635 4.61 4.212 6.075l-1.765 2.307h1.661l1.299-1.709c1.892.83 4.158 1.314 6.592 1.314a17.43 17.43 0 0 0 4.188-.501l.65.903h4.865l-1.729-2.422C22.443 18.214 24 16.082 24 13.71c0-2.94-2.39-5.512-5.948-6.9l-.217.311c3.099 1.214 5.195 3.531 5.195 6.188 0 2.202-1.44 4.17-3.698 5.47l-5.153-7.22 7.382-9.658zM12 5.755c-.586 0-1.212.046-1.775.1 1.004 1.309 1.836 2.417 2.795 3.676-.538-1.157-1.644-2.268-1.261-2.839.378-.565 1.075-.47 1.128-.47 1.118 0 2.194.127 3.2.36l.235-.324C14.98 5.91 13.523 5.754 12 5.754z"/></svg>
```

**Comment by runxel** [comment]
Thank you so much! My fancy premium software is useful again! 😃

**Pull request merged**
