### PR TITLE
Request: PyScaffold Icon

### PR DESCRIPTION
**Pull request by FlorianWilhelm**
**Issue:** Hi there, I'd like to request the addition of the [PyScaffold](https://pyscaffold.org/) icon.
**Alexa rank:** 4,001,917
**Github stars:** 1,096 stars (I know that's below 5k but I think PyScaffold is still worth being added as it has more than [200k downloads per months](https://pepy.tech/project/pyscaffold))

**Disclaimer**: @abravalheri and I are the maintainers of PyScaffold and we have been working on this project for more than 7 years.

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- the icon and the color are used from the original logo of PyScaffold.

pyscaffold

### CODE REVIEW

**Comment by FlorianWilhelm** [comment]
I fixed the linter problems and locally everything looks fine. Could someone please trigger the Github Workflows? Thank you.

**Comment by PeterShaggyNoble** [comment]
Welcome Simple Icons, @FlorianWilhelm, and thanks for the contribution 🙂 Thanks also for mentioning your affiliation with PyScaffold; it makes the review process easier knowing that as we can allow ourselves to be guided by you.

Before we get to reviewing, though, we will need to determine if it's popular enough for inclusion. Obviously, as you say, it wouldn't be based on our primary metrics of Alexa rank & GitHub stars. For me, though, >11m total downloads would definitely be significant enough - we've included Android apps in the pas that have had ~5m downloads. What do the other @simple-icons/maintainers think?

**Comment by FlorianWilhelm** [comment]
Thanks, @PeterShaggyNoble for considering and supporting this contribution, it's much appreciated :-) 

I just merged the `develop` branch again and resolved a merge conflict.

**Comment by ericcornelissen** [comment]
> Before we get to reviewing, though, we will need to determine if it's popular enough for inclusion. Obviously, as you say, it wouldn't be based on our primary metrics of Alexa rank & GitHub stars. For me, though, >11m total downloads would definitely be significant enough - we've included Android apps in the pas that have had ~5m downloads. 

Comparing it to existing Python packages we already have included, PyScaffold outperforms at least PyTorch - which has [an Alexa rank of ~18K](https://www.alexa.com/siteinfo/pytorch.org), but [fewer downloads](https://pepy.tech/project/pytorch) all around. Based on that I'd be fine with including this :+1:

**Comment by PeterShaggyNoble** [comment]
Thanks, @ericcornelissen, that sounds reasonable to me 👍🏻

@FlorianWilhelm, the version in the PR (in red below) is taller than the one in the source you provided. However, as you are an official representative of the brand then if you say we're OK to run with that, we will 🙂 Separately to that, though, there are a number of duplicate and excess points throughout the SVG that could be removed - would you mind having a look at that?

**Comment by FlorianWilhelm** [comment]
@PeterShaggyNoble Thanks, I fixed several duplicate and excess points using Inkscape. I am not sure I understand what you mean by:
> the version in the PR (in red below) is taller than the one in the source you provided

The version in the PR is 2.6kb (24x24) while the original icon from the PyScaffold repo as stated under `source` is 15kb (512x512).

**Comment by PeterShaggyNoble** [comment]
Sorry, @FlorianWilhelm; it probably would have helped if I'd actually included the comparison I mentioned in my last comment! 🤦🏻‍♂️

PR version in red, original in black.

**Comment by FlorianWilhelm** [comment]
@PeterShaggyNoble Thanks for pointing this out! That was my bad when I was scaling down the original logo. I fixed this in the latest commit. 

Here is the updated preview:
pyscaffold

**Comment by PeterShaggyNoble** [comment]
Thanks, @FlorianWilhelm. However, it still doesn't quite line up with the original (see below) but, again, if you're OK fo us to run with then we will.

**Comment by FlorianWilhelm** [comment]
Hi @PeterShaggyNoble, thanks again :-) Let's simply chalk up the remaining differences to artistic freedom ;-) So I'm happy with it and thus am looking forward to seeing this PR merged 🎉  Thank you.

**Comment by PeterShaggyNoble** [comment]
Works for me, @FlorianWilhelm 🙂

Found a few more excess points, mainly in the perforation running across the middle, that I was able to remove, if you want to give the path below a try:

```
M2.402 2.06C.357 2.06 0 5.626 0 5.626l5.36.996s-3.65.862-4.227 1.054c.167.456 1.701.623 1.701.623h5.434c.886 0 1.342-.815 1.342-.815h9.056c.193 0 1.366 0 1.366 1.582 0 1.583-1.366 1.777-1.366 1.777H7.787c-.175 0-1.577.258-2.765 1.361h.077v.11h-.184a5.18 5.18 0 00-1.352 2.327h4.57c.154-.072.27-.11.27-.11h10.208c1.819.003 3.51-.837 4.466-2.218h-.282v-.11h.331c.523-.907.865-2.176.874-3.068 0-3.73-2.84-5.527-4.72-5.527h-9.25c-.61-1.192-2.101-1.55-2.101-1.55h-.896l.316 1.096h-.283v4.02h.283c-.107.367-.212.736-.318 1.105l-.318-1.106h.261V3.155h-.26l.315-1.096zm.788 1.419a.557.557 0 01.566.56.553.553 0 01-.561.56c-.747.003-.752-1.117-.005-1.12zm2.019 8.726h.33v.108h-.33zm.44 0h.33v.108h-.33zm.439 0h.332v.108h-.331l-.001-.108zm.44 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.768 0v.108h-.327v-.11c.101.005.22.001.327.002zm.109 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.329v.108h-.33l.001-.108zm.439 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.329v.108h-.33l.001-.108zm.439 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.329v.108h-.33l.001-.108zm.439 0h.33v.108h-.33v-.11zm.44 0h.33v.108h-.33v-.11zm.44 0h.33v.108h-.33v-.11zm.439 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.329v.108h-.33l.001-.108zm.439 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.439 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.329v.108h-.33l.001-.108zm.439 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.33v.108h-.33zm.44 0h.329v.108h-.33l.001-.108zm.439 0h.33v.108h-.33zm.44 0h.33v.108h-.33v-.108zM3.52 14.812c-.015.061-.022.13-.036.193l.277-.192-.241-.001zm.543 0l-.622.43a7.27 7.27 0 00-.097.765l1.726-1.194zm1.306 0l-2.038 1.412c-.005.11-.019.208-.019.321 0 .184.017.351.03.524l3.262-2.256-1.235-.001zm1.532 0L3.354 17.27c.022.217.057.418.099.615 1.38-.925 2.753-1.89 4.123-2.838.09-.093.182-.17.273-.233-.314.001-.64-.001-.948-.002zm.404.627l-3.532 2.445h.992l2.337-1.62c.005-.284.073-.565.2-.825zm-.203 1.037l-2.039 1.408h1.003l1.149-.795a2.066 2.066 0 01-.113-.614zm.173.778l-.908.63h.843l.336-.233a1.539 1.539 0 01-.27-.398zm.397.517l-.163.113h.348c-.064-.041-.119-.055-.185-.113zm-4.186.283c.835 3.483 4.47 3.888 4.47 3.888h7.856c2.412 0 4.141-3.805 4.141-3.805-3.864.002-7.729-.007-11.593-.012 0 0-.092-.018-.224-.071H3.485zm9.045.099l.26 1h-.231v1.786h.23l-.259.98-.275-.98h.211v-1.787h-.21Z
```

**Comment by FlorianWilhelm** [comment]
Wow, thanks again @PeterShaggyNoble, that's really noble of you helping me out like this :-) 

It seems this reduced the space again by about 4% while looking the same, cool! What kind of tools do you use for this? Also Inkscape? You surely noticed but I have only rudimentary skills in design and tools, thus your help is really appreciated.

**Comment by PeterShaggyNoble** [comment]
No problem, @FlorianWilhelm, we're here to help 🙂 This looks good to me now so I'll be merging once the checks passed.

I'm using Inkscape, too, but years of working on icons, especially reviewing them here, has taught me to spot things like duplicate points just by eyeballing them. My own "skills" suck pretty badly when it comes to creating stuff from scratch but I can hide that fact here as we, mainly, deal with existing artwork! 😆

**Pull request merged**
