### PR TITLE
Update freeCodeCamp (design style guide)

### LINKED ISSUE #3305: Update freeCodeCamp
**Name:** freeCodeCamp
**Official resources for icon and color:** [freeCodeCamp - Style Guide](https://design-style-guide.freecodecamp.org/)

***

Since #830, the color associated with freeCodeCamp icon is set to `#006400`. But, if you check the  [freeCodeCamp - Style Guide](https://design-style-guide.freecodecamp.org/), this color no longer appears anywhere.

This document states in [Logo Colors](https://design-style-guide.freecodecamp.org/#logo-colors) section:

> The freeCodeCamp logo is designed for use primarily on dark backgrounds. For instances in which the full color logo is not practical, the following color combinations are approved alternatives. 

The [Layout colors](https://design-style-guide.freecodecamp.org/#layout-colors) section gives various values, but `#0a0a23` (called _gray 90_) seems to be used for displaying the [main logo](https://design-style-guide.freecodecamp.org/#logo).

In addition, the main glyph no longer seems to have a horizontal line under the flame representation.

PS: While the (former) _green logo_ seems to have disappeared from the [main site](https://www.freecodecamp.org/), it is paradoxically still used... for the favicon of the [Style Guide page](https://design-style-guide.freecodecamp.org/) (which seems strange by the way: cf. https://github.com/freeCodeCamp/design-style-guide/issues/40).

### PR DESCRIPTION
**Pull request by gizmecano**
freecodecamp

**Issue:** close #3305 
**Alexa rank:** cira 1'600

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The [Layout colors](https://design-style-guide.freecodecamp.org/#layout-colors) section gives various values, but `#0a0a23` (called _gray 90_) seems to be used for displaying the [main logo](https://design-style-guide.freecodecamp.org/#logo).

In addition, the [main glyph](https://design-style-guide.freecodecamp.org/downloads/fcc_primary_small.svg) no longer get a horizontal line under the flame representation.

### CODE REVIEW

**Comment by gizmecano** [comment]
I do not understand these two validation errors: from my side, the initial image gets the right dimensions (24x24px) whether it is before or after going through the SVGO optimization...

🤔

**Comment by ericcornelissen** [comment]
What software are you using to edit the SVG @gizmecano?

**Comment by gizmecano** [comment]
> What software are you using to edit the SVG @gizmecano?

Inkscape, [version 1.0 (4035a4fb49, 2020-05-01)](https://inkscape.org/fr/release/inkscape-1.0/)

**Comment by NovaGL** [comment]
@gizmecano Can you check again as when I open the file the width is 24.001

**Comment by gizmecano** [comment]
I have checked all the steps:

- I made a simple `svg` sized `24.000x24.000`px
- after using SVGO, the downloaded file is now sized `24.001` in the horizontal axis (with a horizontal positionning set at `-0,001px`) and _24.000_ vertically
- Travis job states that size of the file is `24.001x16.188`px

Does anybody experienced such an issue during a process using Inkscape > SVGO > Travis before?

🤔

**Comment by PeterShaggyNoble** [comment]
@gizmecano, that can usually be fixed by increasing the precision level by 1 when running your file through SVGO(MG).

**Comment by gizmecano** [comment]
Setting SVGMO precision level to 1 seems to resolve the positioning issue, but in the other hand, this simplification significantly degrades the main drawn (see the image below, with a much less precise rounding for example)...

rounding detail


I tested with a precision level set to 2, but the positioning issue remains unchanged.

**Comment by gizmecano** [comment]
> `<path>` must be centered at (12, 12); the center is currently (12, 12.023)

Failed again. I do not understand nothing about what is wrong with this image. I wonder if it is not better to restart from scratch...

**Comment by PeterShaggyNoble** [comment]
> I tested with a precision level set to 2

It can be trial and error sometimes to get it exactly right; just keep upping the precision by 1 until it's resolved. If it helps, I usually do an initial pass at optimising through [SVGOMG](https://jakearchibald.github.io/svgomg/) so I can see if there's any visual shift in the icon as I reduce the precision.

**Comment by gizmecano** [comment]
So, by changing the initial working file to be defined with a horizontal offset of `0.001`px before optimization in SVGMO (cf. 3eee46b96a0531078c8ba3c0f3ed2a9dc44c023a), it seems that the output file is now considered as correct by Travis checker.

It's a bit strange: I will let maintainers take a look to this to let me know their thoughs about this.

**Comment by PeterShaggyNoble** [comment]
This looks spot-on to me now, @gizmecano, thanks for your continued efforts on it :+1:

**Comment by gizmecano** [comment]
Thank you very much for this encouragement @PeterShaggyNoble ! 🎉

**Pull request merged**
