### PR TITLE
Add Cordova icon

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
From the previously abandoned #1339.

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
At https://cordova.apache.org/artwork/ are PSDs. There are paths in there which can be exported to Illustrator.
Color `#32383D` is taken from their monochrome, non-white icon.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @runxel thanks for your work on this. 👍 

There is an [official .svg](https://cordova.apache.org/static/img/cordova-logo-newbrand.svg) in the header of their [website](https://cordova.apache.org/).

The colour you chose is also used as the text colour in this version of the [logo](https://cordova.apache.org/static/img/artwork/cordova_logo_dark_gray_small.png).

The website has a lot of black and shades of grey eg `#333333`, blues and highlighting is with some colours like `#3992ab`, `#4CC2E4`, `#2c7185` (vaguely familiar as Apache colours) and since the logo used on their actual website is the white text version I think we should seek the considered view of the @simple-icons/maintainers for hex value representative of the project.

**Comment by birjolaxew** [comment]
Coming in with a third opinion here :P I personally think that the primary color of their logo is the white, either `#ffffff` or `#e8e8e8` (top and front of cube respectively, according to their PSD), although both of those have a transparent->black gradient overlayed on them.

Alternative colors are `#00f0ff` from the eyes, or `#2d3b48` from the visor.

I personally prefer `#E8E8E8`, but can easily be convinced otherwise. Thoughts @simple-icons/maintainers?

**Comment by PeterShaggyNoble** [comment]
Found [this SVG](https://github.com/apache/cordova-docs/blob/master/www/static/img/cordova-logo-newbrand.svg), which uses `#a5b0b8` for the grey.

**Comment by runxel** [comment]
Aw man, so many options 😅 
I could see it being white, or having one of the blues.
But again I also don't think the color I chose is necessarily wrong. At least that's the color they picked _themself_ for a monochrome version...

**Comment by ericcornelissen** [comment]
I would vote for `#00f0ff` and otherwise for `#e8e8e8` or `#32383D`. I favour `#00f0ff` because it is a more unique colour, and therefore feels more like a brand colour, and they use the (or at least similar) colour throughout their site. But arguing for `#e8e8e8` or `#32383D` (or more generally, some form of light or dark grey from the logo/website) is equally valid.

**Comment by phatbhoy67** [comment]
Hey @runxel looking at the comments, can you update the hex value to `#e8e8e8` and I'll merge this one in.

**Comment by runxel** [comment]
Here we go 😎

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @runxel 👍

**Pull request merged**
