### PR TITLE
Add Babylon.js icon

### LINKED ISSUE #7148: Request: babylon.js
### Brand Name

babylon.js

### Website

https://www.babylonjs.com/

### Popularity Metric

https://www.alexa.com/siteinfo/babylonjs.com

https://github.com/BabylonJS/Babylon.js/stargazers

### Official Resources for Icon and Color

svg: https://d33wubrfki0l68.cloudfront.net/b39661bbf642a09168d424b5c1f48076d23c8fa3/44cb5/assets/img/babylonidentity.svg
color:  #2a2342

### Additional Comments

_No response_

### Contributing

No

### LINKED ISSUE #8736: Request: Babylon.js
### Brand Name

Babylon.js

### Website

https://www.babylonjs.com/

### Popularity Metric

The Similarweb rank is 140,065. See https://www.similarweb.com/website/babylonjs.com/#overview
The Github repo has 20.8k stars.

### Official Resources for Icon and Color

svg: https://github.com/BabylonJS/Brand-Toolkit/blob/master/babylon_logo/fullColor/babylon_logo_color.svg
color: #BB464B
brand-toolkit: https://github.com/BabylonJS/Brand-Toolkit

### Additional Comments

There are multiple monochrome variants of the logo:
- monochrome dark: https://github.com/BabylonJS/Brand-Toolkit/blob/master/babylon_logo/monochrome/babylon_logo_monochrome_dark.svg
- monochrome light: https://github.com/BabylonJS/Brand-Toolkit/blob/master/babylon_logo/monochrome/babylon_logo_monochrome_light.svg

### Contributing

Yes

### PR DESCRIPTION
**Pull request by timondev**
**Issue:** closes #8736 close #7148

**Similarweb rank:**
  

The Similarweb rank is 140,065. See https://www.similarweb.com/website/babylonjs.com/#overview
The Github repo has 20.8k stars.

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by LitoMore — APPROVED** [review]
image

@timondev Perfect fit. Thank you for contributing!

**Comment by adamrusted** [comment]
@LitoMore - as per their licensing, we should not have accepted a single-color variant of the logo that wasn't officially supplied on their repo. I've mentioned it on #6317 - but we may need to look at removal, or requesting that they add our SVG as an appropriate option.

**Comment by LitoMore** [comment]
@adamrusted Thanks. I will send a request to https://github.com/BabylonJS/Brand-Toolkit.

**Comment by PeterShaggyNoble** [comment]
@LitoMore, did you ever hear back from them? If not then we should queue this up for removal in v11 until we do.

**Pull request merged**
