### PR TITLE
Add ExpressVPN icon

### LINKED ISSUE #6000: ExpressVPN
**Brand Name:** ExpressVPN
**Website:** https://www.expressvpn.com/
**Alexa rank:** 2,356
  

**Official resources for icon and color:** SVG is available in the header of the website. Primary color used from the logo is `#DA393F`.

### PR DESCRIPTION
**Pull request by wwwescape**
expressvpn

**Issue:** Closes #6000
**Alexa rank:** 2,356
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

 - I used the SVG from the header of the website
 - I used Inkscape to remove the text, scale and adjust
 - I used https://jakearchibald.github.io/svgomg/ to optimize

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @wwwescape 👍🏻

The SVG looks perfect to me. Just a couple of small changes and this will be ready to merge:
1. They have logos available to download in [their press section](https://www.expressvpn.com/press) so I think we should run with that for the source,
2. As that page also includes some information about the usage of the logo, we should add a `guidelines` entry to JSON using the same URL, and,
3. According to that press page, the colour should be `#DA3940`.

**Comment by wwwescape** [comment]
Sure @PeterShaggyNoble. I'll take another look at it over the weekend.

**Comment by wwwescape** [comment]
@PeterShaggyNoble Done.

**Comment by PeterShaggyNoble** [comment]
Excellent, thanks, @wwwescape 🙂

**Pull request merged**
