### PR TITLE
Add Staticman icon

### PR DESCRIPTION
**Pull request by iriiiina**
https://staticman.net

### CODE REVIEW

**Comment by davidklebanoff** [comment]
Hi @iriiiina, thanks for the contribution!

It looks like the icon has not been vertically centered. Can you fix that and verify it meets all the other [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon).

**Comment by iriiiina** [comment]
Hi, I've centered the icon vertically.

**Comment by birjolaxew** [comment]
It looks like there are a couple of small differences between this SVG and the Staticman logo: namely the SVG lacks a butterfly, and has sun glasses where the logo has glasses and eyes.

Other than that this looks good.

**Comment by davidklebanoff** [comment]
@birjolaxew, ah yes, it does seem to be missing some key components.

@iriiiina, I would recommend taking the icon on the [homepage](https://staticman.net/), and simply make the white components transparent (to make the logo monochrome), and go from there to fit the contribution guidelines. 

If you don't have the proper tools or know how, I can do this myself sometime later this week.

**Comment by iriiiina** [comment]
@davidklebanoff, the only SVG editing tool that I know (Vectr) somehow cuts thes parts off. So I'd say that I know how to do it:)

**Comment by davidklebanoff** [comment]
I created #667 with the discussed changes. Closing this pull request in favor of the other one.

**Pull request closed without merging**
