### PR TITLE
Added Apache Flink icon

### PR DESCRIPTION
**Pull request by JoaoPedroMoraes**
**Issue:** #1330 

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
From the official SVG I was able to create a monocolor version. https://flink.apache.org/

the svg logo was removed from https://flink.apache.org/material.html#scalable-vector-graphics-svg

### CODE REVIEW

**Comment by davidklebanoff** [comment]
I went ahead and updated the source to the logo page.

As for the logo itself, I was thinking the "Black Outline" version of the logo would be the most appropriate, but I realise the one you have included here might be equally as good. Perhaps it's just a matter of opinion. I'd like some additional opinions. Thoughts @ericcornelissen @birjolaxew?

See all versions here: https://flink.apache.org/material.html

**Comment by ericcornelissen** [comment]
I personally think the black outline version is a better option since it's a little easier on the eyes. Can you elaborate why you picked this version @JoaoPedroMoraes?

**Comment by JoaoPedroMoraes** [comment]
> Eu pessoalmente acho que a versão de contorno preto é uma opção melhor, pois é um pouco mais fácil para os olhos. Você pode explicar por que escolheu esta versão @JoaoPedroMoraes ?

I thought that when the icon was small it would be better to visualize. But you who deny what is best

**Comment by ericcornelissen** [comment]
Hmm that's an interesting hypothesis. Care to create a comparison between the two (maybe on a few different scales)? If not, I'll try to do it myself later.

**Comment by ericcornelissen** [comment]
Here is a quick comparison between the two options ⬇️ I'm not convinced either way, neither version is very legible at a small scale. Personally I still prefer the outlined version, which I think looks better at larger scales, but in my opinion both are fine.

### Small

| Outline | Filled |
| --- | --- |
| image | image |

### Large

| Outline | Filled |
| --- | --- |
| image | image |

**Comment by JoaoPedroMoraes** [comment]
> Here is a quick comparison between the two options  I'm not convinced either way, neither version is very legible at a small scale. Personally I still prefer the outlined version, which I think looks better at larger scales, but in my opinion both are fine.
> 
> ### Small
> Outline	Filled
> image	image
> ### Large
> Outline	Filled
> image	image

All in all, the outline version looks more beautiful

**Comment by JoaoPedroMoraes** [comment]
and, what version will it be?

**Comment by ericcornelissen** [comment]
Let's let others way in before we make a final decision :)

**Comment by davidklebanoff** [comment]
I prefer the black outlined version.

**Pull request merged**
