### PR TITLE
Updated Apple

### PR DESCRIPTION
**Pull request by fbernhart**
apple

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
I don't know what source you've used @fbernhart. Seems to be different that the original (and better). However, I think that we must use an apple official logo like [this](https://www.apple.com/ac/globalnav/6/en_US/images/be15095f-5a20-57d0-ad14-cf4c638e223a/globalnav_apple_image__cxwwnrj0urau_large.svg) or [this](https://developer.apple.com/assets/elements/icons/brandmark/apple-developer-brandmark.svg). Could you rebuilt using an official Apple source and update the source?

**Comment by fbernhart** [comment]
@mondeja I've used the SVG that was already part of Simple Icons.

Let me rebuild it. 👍🏼

**Comment by fbernhart** [comment]
apple


@mondeja Done. I've now as well changed the color to black `#000000` (like as well used for Apple TV, Apple Pay and Apple Music) as there doesn't seem to be any official resource, that is stating that Apple is using `#999999`.

I've used this source: https://www.apple.com/ac/globalnav/6/en_US/images/be15095f-5a20-57d0-ad14-cf4c638e223a/globalnav_apple_image__cxwwnrj0urau_large.svg

**Review by mondeja — APPROVED** [review]
In their [brand guidelines](https://www.apple.com/legal/sales-support/certification/docs/logo_guidelines.pdf) they point that black and white are the colors for the Apple logo, so good catch @fbernhart! :+1:
The geometry it's perfect and the source correctly updated, thank you! :trophy:

**Pull request merged**
