### PR TITLE
Added Bitcoin SV

### LINKED ISSUE #3536: Request: Bitcoin SV icon
image

**Name:** Bitcoin SV
**Website:** No official website since it is a decentralized network
**Alexa rank:** N/A but network is valued at $3B+, see: http://coinmarketcap.com/
**Official resources for icon and color:**
https://bitcoinassociation.net/media-assets/

There are multiple options, I vote to use the most minimal one, the simple B.

### PR DESCRIPTION
**Pull request by adamrusted**
bitcoinsv

**Issue:** Closes #3536
**Alexa rank:** [523,423 (BitcoinSV.com)](https://www.alexa.com/siteinfo/bitcoinsv.com) / [474,633 (BitcoinSV.io)](https://www.alexa.com/siteinfo/bitcoinsv.io)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo found on homepage of BitcoinSV.com - hex extracted from logo.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Do we need to include the wordmark here, @adamrusted?

**Comment by adamrusted** [comment]
> Do we need to include the wordmark here, @adamrusted?

Not 100% sure - it seems a little generic to just have the `Bitcoin` symbol inside a circle - as I imagine a lot of these sites will use **very** similar logos. Happy to change it if you think it'd be better though :+1:

**Comment by PeterShaggyNoble** [comment]
Yep, we should always endeavour to avoid wordmarks.

If there are multiple sub-brands using the same icon then we'll cross that bridge when we come to it.

Sidenote: I don't understand why we need so many variations of the one brand - would our existing Bitcoin icon not cove all cases? Having said that, I know feck all of "crypto currencies" and have no interest in learning of them! 😆

**Comment by adamrusted** [comment]
> Yep, we should always endeavour to avoid wordmarks.
> Having said that, I know feck all of "crypto currencies" and have no interest in learning of them! 😆

Me either! I'll update to just the icon ready for a review.

**Comment by adamrusted** [comment]
Icon updated, though as @PeterShaggyNoble points out - it's basically the same as our existing [Bitcoin icon](https://github.com/simple-icons/simple-icons/blob/develop/icons/bitcoin.svg), but without the angle. How do other @simple-icons/maintainers feel about including this one too?

**Comment by PeterShaggyNoble** [comment]
Looks like there's a couple of overlapping points in the bottom inner curve of the "B" that could be joined into one, @adamrusted.

**Comment by adamrusted** [comment]
@PeterShaggyNoble should be updated.

**Comment by remjx** [comment]
> it's basically the same as our existing [Bitcoin icon](https://github.com/simple-icons/simple-icons/blob/develop/icons/bitcoin.svg), but without the angle. How do other @simple-icons/maintainers feel about including this one too?

I'm not a maintainer but I created the original request. I believe having separate logos is valid because they are totally separate blockchains that are incompatible with each other. On one of my projects, I am giving users the option to pay in whichever version of Bitcoin they prefer, and showing the different logos helps users distinguish between them.

Thank you!!

**Comment by PeterShaggyNoble** [comment]
I'm seeing [an imperfection](https://user-images.githubusercontent.com/15157491/108494652-b7908380-729f-11eb-91aa-de000c5fe828.png) in the upper part of the curves of both inner parts of the "B" now, @adamrusted. I think the same thing happened to me when I deleted one of the excess points but it worked fine when I joined them instead. Or maybe it was the other way 'round?! 🤔

Also, you might be able to save a point or 2 on the circle by redrawing it; the one in [the source](https://bitcoinsv.com/bitcoinsv-logo.svg) isn't quite perfect.

**Comment by adamrusted** [comment]
@PeterShaggyNoble give that a try. I've cut down the points as best I can in Illustrator.

**Comment by PeterShaggyNoble** [comment]
Looks like one of the extra points, in the bottom inner curve, managed to sneak back in, @adamrusted 🙈

**Comment by adamrusted** [comment]
Try that out @PeterShaggyNoble - that's what I get for rebuilding the icon from scratch, eh?

**Comment by PeterShaggyNoble** [comment]
I'm almost afraid to post this at this stage! 🙈 In the interests of getting this off your plate, let's run with [this version](https://github.com/simple-icons/simple-icons/pull/4576/commits/e96ef0cd5cf3e975baa9ec0df29ec3b44f0d57a0) if you're happy with it.

(Your version in red)

**Comment by PeterShaggyNoble** [comment]
Thanks, @adamrusted 👍🏻 Let's run with that for now.

**Pull request merged**
