### PR TITLE
Added PS3, PS4, and Gamecube icons.

### PR DESCRIPTION
**Pull request by davidklebanoff**
I updated the playstation color as well, as it was slightly off.

The reference was old brand reference was dead, but I was able to confirm the new color using the official website corroborated with some an official style guide hosted on another domain.

Issue #560 and #565.

### CODE REVIEW

**Comment by birjolaxew** [comment]
Where on https://www.playstation.com and https://www.nintendo.com did you find the logos? I could only find the Playstation brand as an SVG.

**Comment by davidklebanoff** [comment]
The PS3 logo had come from a filter from the German retailer Saturn, now broken link:
http://www.saturn.at/flyer/10/A_SA_V_2808HTE1_01.pdf

The PS4 logo had come from a Japanese Sony Interactive Entertainment press release, now broken link:
http://www.sie.com/corporate/release/pdf/130221a_e.pdf

The gamecube logo is an SVG version of the logo seen here, the console is older, so I could not locate an official SVG version:
https://www.nintendo.com/consumer/systems/nintendogamecube/index.jsp

**Comment by birjolaxew** [comment]
The `source` URL should refer to where the logos were taken from (or where the image that was traced was taken from, if no SVG is available) - that way it's easier to check for updates, and verify how correct the SVG is.

The PS4 logo source should be changed to e.g. [Wikimedia](https://commons.wikimedia.org/wiki/File:PlayStation_4_logo_and_wordmark.svg) (in lack of better/more official source - Wikimedia is preferred to most other third party sources since it includes a source of its own), while a more official/well-sourced source for the PS3 logo should be found.

Otherwise this is looking good :+1:

**Comment by davidklebanoff** [comment]
@birjolaxew I updated the sources to your guidance. The logos used were the most well-sourced logos that I could find avaliable.

**Comment by birjolaxew** [comment]
@davidklebanoff Thanks for the updates! Merged and published!

**Pull request merged**
