### PR TITLE
Add Trimble icon

### PR DESCRIPTION
**Pull request by lukasbestle**
**Popularity metric:** [Global rank 9648](https://www.similarweb.com/website/trimble.com/)

trimble

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Extracted the icon and hex color value from the main logo SVG on their homepage
- No trademark symbol as their brand guidelines allow to leave it out in small sizes and "where production constraints prevent it" (pages 16 and 17 of their [Brand Identity Book](https://brandfolder.com/s/7jmk9cq999fxz4gsgn4mnsb) as linked from brand.trimble.com)

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
I'm seeing a difference in size, your icon seems to be wider than the source. Could you give another try?

image

**Comment by lukasbestle** [comment]
Indeed, wonder how that happened. I only scaled the icon, keeping the aspect ratio. But now did that again and replaced the path.

**Review by mondeja — APPROVED** [review]
Now looks good. Thank you!

**Comment by lukasbestle** [comment]
Thank you for your review! :)

**Review by Thompson1985 — APPROVED** [review]

**Pull request merged**
