### PR TITLE
Add WebGPU icon

### LINKED ISSUE #11168: Request: WebGPU
### Brand Name

WebGPU

### Website

https://www.w3.org/TR/webgpu/

### Popularity Metric

The SimilarWeb rank is 16,346. See <https://www.similarweb.com/website/w3.org/>.

### Official Resources for Icon and Color

- SVG: https://www.w3.org/2023/02/webgpu-logos.html
- Color: `#005a9c`, from the logo

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by sebastien46**
webgpu-preview

**Issue:** closes #11168

**Popularity metric:** 
- W3C SimilarWeb (although indirectly): [**16,346**](https://www.similarweb.com/website/w3.org)
- GitHub: 4.7k Stars

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

- The Hex value is the primary path's color i.e. `#005A9C`
- The vector was provided by the W3C
- The Source for the vector is https://www.w3.org/2023/02/webgpu-logos.html
- The licence of the logo is the [CC-BY-4.0](https://spdx.org/licenses/CC-BY-4.0)

### CODE REVIEW

**Comment by uncenter** [comment]
To be on the safe side I think it is worth reaching out to `site-policy@w3.org` to confirm that we can use this logo (see https://github.com/simple-icons/simple-icons/pull/9885). @sebastien46 would you be willing to (see https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission)? I don't think the rules are as strict as they were for the W3C logo itself though so hopefully we can get this one through.

**Comment by tidoust** [comment]
> To be on the safe side I think it is worth reaching out to `site-policy@w3.org` to confirm that we can use this logo (see #9885).

With my W3C team hat on, I confirm that you may integrate the WebGPU logo. The pull request links to the usage page and notes the CC-BY 4.0 license already. That all looks good!

**Comment by uncenter** [comment]
No need to update the branch for now. It pings everyone involved and isn't necessary - maintainers will update the branch before merging to make sure (updated?) tests are passing.

**Review by uncenter — APPROVED** [review]
Looks perfect! Thanks @sebastien46! 🚀

**Comment by uncenter** [comment]
Before merging just going to make sure this fits our popularity metrics...

**Pull request merged**
