### PR TITLE
Add edX icon

### LINKED ISSUE #3340: Request: edX
**Name:** edX
**Website:** https://edX.org 
**Alexa rank:** [568](https://www.alexa.com/siteinfo/edx.org)

  

**Official resources for icon and color:**
Logo Guide: https://www.edx.org/sites/default/files/mediakit/file/edx_visual_identity_guidelines.pdf
SVG Logo: https://en.wikipedia.org/wiki/File:EdX.svg 
  
  

I am not affiliated with edX.

---

I plan to make a pull request for this icon, using the blue color indicated in the brand guide. That one seems to be the most prominently used on their website of the three (red / gray /blue) indicated in the brand guide.

### PR DESCRIPTION
**Pull request by LowlyDBA**
**Issue:** Closes #3340 
**Alexa rank:**  [568](https://www.alexa.com/siteinfo/edx.org)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Hex value taken from the three options given in [edX Visual Identity Guidelines](https://www.edx.org/sites/default/files/mediakit/file/edx_visual_identity_guidelines.pdf). Blue chosen since it is the most heavily used color in the website.

**Big** shout-out to @roch-torr for helping me with some of the difficult path problems on this! 🙏

### CODE REVIEW

**Comment by NovaGL** [comment]
Hi @LowlyDBA 

This failed as the hex is expected to be in uppercase. Can you please look into this?

Also can you provide an official monochrome source so we can compare? I feel that monochrome of this logo might break their branding guidelines.

**Comment by ericcornelissen** [comment]
@NovaGL as I pointed out in [the issue](https://github.com/simple-icons/simple-icons/issues/3340) there is a monochrome/grayscale version of the logo on [page 6 of this PDF](https://www.edx.org/sites/default/files/mediakit/file/edx_visual_identity_guidelines.pdf).

**Comment by NovaGL** [comment]
> 
> 
> @NovaGL as I pointed out in [the issue](https://github.com/simple-icons/simple-icons/issues/3340) there is a monochrome/grayscale version of the logo on [page 6 of this PDF](https://www.edx.org/sites/default/files/mediakit/file/edx_visual_identity_guidelines.pdf).

Am I going crazy? There is only 4 pages when I downloaded it and didn't see the monochrome version that's why I commented.

**Comment by ericcornelissen** [comment]
You are right... They changed the PDF on us! :anguished: :unamused:

Well, I still think it should be possible to add the logo of edX in a monochrome fashion :thinking: But ideally we would find some (new) official source as reference.

**Comment by LowlyDBA** [comment]
Sorry for the confusion! I updated the linked source as that one explicitly stated the proper hex color codes. Old link was https://www.edx.org/sites/default/files/edx-trademark-guidelines-jan2018.pdf 

I may not have time to re-work this anytime soon so feel free to close the PR.

**Comment by NovaGL** [comment]
Thanks for the updated document.  I can see for that logo that it's still using transparency so the logo you have made might be the best we are going to get.

I will leave it up to others to decide. I've updated the HEX for you so hopefully it shouldn't fail again.

**Comment by ericcornelissen** [comment]
I think it's fine if we add this version of the logo. However, when comparing to [the source material](https://en.wikipedia.org/wiki/File:EdX.svg) I'm seeing some minor differences, see my comparison below (in Adobe Illustrator). This could be due to the optimization being to aggressive. But, the logo is also just quite messy, did you attempt to clean it up a bit @LowlyDBA?

image

_Foreground/Red is the Wikimedia SVG, background/black is the SVG in this Pull Request_

**Comment by LowlyDBA** [comment]
Yeah, some cleanup was done on my part to correct some inconsistent areas I
saw when I looked at it more closely.

**Comment by PeterShaggyNoble** [comment]
Hmm ... 🤔 ... based on the (somewhat) monochrome version on page 7 of [this PDF](https://assets.ctfassets.net/ii9ehdcj88bc/3MczQtEcVQOvuLyBSgWSFB/7cba6fb2480781342aec2b0a373595d2/edX_Media_Kit_-_JULY_2020.pdf), which I found on [this page](https://www.edx.org/media-kit) and is dated July 2020, I wonder if we shouldn't have some cut-outs on this?

**Comment by LowlyDBA** [comment]
Hi all, as stated before I won't have time to update this in the near future so if the current version isn't up to snuff feel free to close the PR.

**Comment by adamrusted** [comment]
Looks like [edX](https://www.edx.org/media-kit) have changed their logo, so I'm going to go ahead and close this Pull Request, and open a new one with the updated logo and media kit. Thanks for your work on this @LowlyDBA!

**Pull request closed without merging**
