### PR TITLE
Add Google Optimize

### PR DESCRIPTION
**Pull request by RichardRNStudio**
104816664-8c37f600-5814-11eb-8307-d21766c45c93

**Issue:** #4588 
**Alexa rank:** > 10,601 based on @adamrusted's comment: (https://github.com/simple-icons/simple-icons/issues/4588#issuecomment-759736862)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by adamrusted** [comment]
Hi @RichardRNStudio, thanks for working on this! 🎉

Looks like you've been able to fix the linting errors etc, though the circle doesn't quite match up and seems to disappear when viewed at smaller sizes. I've had a quick go below using a gap of 0.5px around the outside of the circle shape - it's optimized and passes the linter so feel free to use if you'd like.

googleoptimize
```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Google Optimize icon</title><path d="M23.661 11.997a3.242 3.242 0 1 1-6.479 0V6.55H11.51a3.293 3.293 0 0 1 0-6.55h8.854a3.291 3.291 0 0 1 3.291 3.259l.006 8.738zm-16.775-.011a3.275 3.275 0 1 0-6.55 0 3.275 3.275 0 0 0 6.55 0zm5.42-3.28H5.442c1.153.647 1.944 1.867 1.944 3.28a3.766 3.766 0 0 1-1.802 3.204h3.672v5.453A3.181 3.181 0 0 0 12.372 24a3.323 3.323 0 0 0 3.291-3.357v-8.695a3.318 3.318 0 0 0-3.357-3.242z"/></svg>
```

**Comment by RichardRNStudio** [comment]
Hi @adamrusted,
You're right, it is so much better now, thank you for your help! 
The icon has been updated.

**Comment by adamrusted** [comment]
Amazing, thanks @RichardRNStudio! 💪
I'll let another of the @simple-icons/maintainers review this, and hopefully it can get added ahead of the next release 🤞

**Review by mondeja — APPROVED** [review]
Looks perfect to me :100: 

Thank you @adamrusted and @RichardRNStudio for your work on this icon!

**Pull request merged**
