### PR TITLE
Correct Netflix Icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** #3169
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- I took the already used SVG.
- I used Inkscape to fix size and center
- I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by mondeja** [comment]
Hello @service-paradis. I can see that you've updated the icon to fit with latest Netflix icon version, maybe manually (I'm not sure). I can see next difference between previous Netflix icon in simple-icons and your one (your version in red and my version correcting size from previous Netflix icon in simple-icons in black) at the bottom-right corner of the left rectangle of the "N" symbol:

netflix-diff

Checking [Netflix brand guidelines](https://brand.netflix.com/en/assets/brand-symbol/) I can see that the symbol icon has been updated in brand guidelines after this icon was updated in #561, 3 years ago. So my question is: what file are you using as source in this update? If you are using the symbol shared by Netflix brand guidelines, you should update the source in `_data/simple-icons.json`, otherwise I think that we should go ahead with official brand symbol in this update.

**Comment by service-paradis** [comment]
Hum... from memory I took the simple-icon original for this one. Looks like something went wrong, sorry!
When I compared my logo with the previous version, I though it looks pretty similar
image
I will give it another try starting from the original again!

Maybe another issue could be open to update the icon using the new guideline. 
Unfortunately, it looks like it will be difficult to respect this new guideline!

**Comment by service-paradis** [comment]
@mondeja 
I gave it another try! Is it better? :)
image

**Review by mondeja — APPROVED** [review]
Now seems correct to me :+1: Thanks for the quick reply and the fix @service-paradis. I will open an issue for update the Netflix icon using current brand guidelines.

**Pull request merged**
