### PR TITLE
Add DatoCMS icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** N/A
**Alexa rank:** [~100k](https://www.alexa.com/siteinfo/datocms.com)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I took the black icon found in their brand kit available at https://www.datocms.com/company/brand-assets
- I used Inkscape to scale
- I optimized it
- I took the main brand color listed at https://www.datocms.com/company/brand-assets

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
I'm seeing a minor difference of width between your version (23,848 px) and the source (23,647px), that could be due the optimization process. Would you min to check that @service-paradis?

**Comment by service-paradis** [comment]
> I'm seeing a minor difference of width between your version (23,848 px) and the source (23,647px), that could be due the optimization process. Would you min to check that @service-paradis?

Which file are you comparing to? I used `Only icon/Black/black_d_icon.svg` to create it. I'm not able to see the difference in width using this one in Inkscape:
image

**Review by mondeja — APPROVED** [review]
Sorry, I was using another source to compare against.
It is perfect :100: Thank you @service-paradis :pray:

**Comment by service-paradis** [comment]
No problem, thank you 😃

**Pull request merged**
