### PR TITLE
add web3.js icon

### LINKED ISSUE #5672: Icon request: Web3.js
**Brand Name: web3.js**
**Website: https://web3js.readthedocs.io/en/v1.3.4**
**Alexa rank: 61,791**
**Github Stars: 10.3k**

**Official resources for icon and color: https://github.com/ChainSafe/web3.js/tree/1.x/assets/logo**

### PR DESCRIPTION
**Pull request by Yasser-dev**
web3-dot-js

**Issue:** Closes #5672
**Alexa rank: 61,791**
### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The svg logo was already there on web3.js github repo (https://github.com/ChainSafe/web3.js/tree/1.x/assets/logo), I chose the orange hex color because it looked like a great identifier for the logo and it looked primary compared to other colors in the logo, the other colors were two shades of grey.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @Yasser-dev, and thanks for the contribution 🙂

However, I'm seeing quite a few differences between your version (in red below) and the source file. Could you have another go at this to see if you can fix them up? And could you also update the source URL to https://github.com/ChainSafe/web3.js/blob/fdbda4958cbdbaebe8ed5ea59183582b07fac254/assets/logo/web3js.svg

In the absence of anything else to go on, I'd agree with your choice of colour.

**Comment by Yasser-dev** [comment]
Thanks for the detailed feedback, kindly check my changes.

**Review by adamrusted — COMMENTED** [review]
Thanks @Yasser-dev for the contribution, and welcome to Simple Icons!

**Comment by Yasser-dev** [comment]
Hi, this is my last attempt, if it is not correct then idk what is the problem, in such case if someone else can do it I'd appreciate it.

**Comment by PeterShaggyNoble** [comment]
Thanks for your continued work on this one, @Yasser-dev. I'm still seeing a few minor differences in places, though. I gave it a try myself and it's slightly trickier than it first looked due to some imperfections in the source so, if you like, you can use my path below, which I managed to get down to a precision of 3.

And if you let us know which software you're using, one of us might be able to write you up a step-by-step tutorial to help you out with future contributions.

```
M.889.775S0 1.29 0 2.315V7.44s0 3.079 2.666 4.618c.817.472 1.384.508 1.777.334.394.628.96 1.246 1.778 1.718 2.666 1.54 2.668-1.539 2.668-1.539V7.447c0-1.027.888-1.539.888-1.539l3.557-2.054s.89-.514 1.777 0c.89.513 0 1.027 0 1.027L11.56 6.934l1.775 1.025 3.559-2.055c.052-.03.912-.495 1.773.002.89.514 0 1.026 0 1.026l-3.555 2.054s-.888.514-.888 1.54v5.124s0 1.028-.889.514c-.89-.513-.89-1.539-.89-1.539l-1.778-1.027s.001 3.08 2.668 4.619c2.667 1.539 2.666-1.54 2.666-1.54v-5.126c0-1.026.889-1.537.889-1.537l4.445-2.569s1.776-1.025-.889-2.564c-.819-.474-1.552-.704-2.177-.797-.164-.357-.565-.776-1.377-1.24-2.667-1.523-5.332-.016-5.332-.016L8.004 4.881s-.89.514-.89 1.539v5.125s0 1.027-.89.514c-.889-.514-.89-1.54-.89-1.54V5.396c0-.064.003-.127.01-.188.097-.902.879-1.353.879-1.353L4.445 2.828l-.004.002c-.052.03-.884.544-.884 1.537v5.125s-.002 1.027-.891.514c-.89-.514-.889-1.54-.889-1.54V3.343c0-1.026.889-1.54.889-1.54L.889.776zm9.78 8.735v2.053l1.778 1.025v-2.053L10.67 9.51zm8.442 2.183c-.666.005-1.332.389-1.332 1.909 0 3.039 2.666 4.619 2.666 4.619l.889.513s.89.514.89 1.54-.89.513-.89.513l-3.555-2.053v2.053l3.555 2.053S24 24.379 24 21.3c0-3.077-1.777-4.105-1.777-4.105l-1.778-1.025s-.888-.514-.888-1.54c0-1.028.888-.515.888-.515L24 16.168v-2.053l-3.555-2.05s-.667-.376-1.334-.372Z
```

**Comment by Yasser-dev** [comment]
Thanks for the help, I am using illustrator.

**Comment by PeterShaggyNoble** [comment]
As you're using my path now, we'll need one of the other @simple-icons/maintainers to throw an eye over this before merging.

And, @adamrusted, could you help out with a quick tutorial in Illustrator, if you've time?

**Comment by adamrusted** [comment]
> As you're using my path now, we'll need one of the other @simple-icons/maintainers to throw an eye over this before merging.

I'll review this shortly.

> And, @adamrusted, could you help out with a quick tutorial in Illustrator, if you've time?

Sure thing. My process is pretty simple tbh.
1. Open the source SVG in Illustrator
2. Group any needed paths (forget backgrounds, etc) and _while maintaining the aspect ratio_ change either the width or height to 24px and center the icon.
3. Now use the Artboard tool, change the size of your artboard to exactly 24*24. Make sure the icon is still centered.
4. Identify any sections of the path that may require a cut-out, and use the `Pathfinder` tools (Minus Front or Unite, in most cases) to combine / cut out shapes. An easy way to add cut-outs where a 3d-effect is used in the original is to select the front-most path, and use 'Offset Path' with a 0.5px offset. Then using the newly created shape and the one you're wanting to overlay, use the 'Minus Front' option.
5. Once you're happy with the look of your icon, select any remaining paths, group them and then use Ctrl+8 to combine them into a 'compound path'. You can then Save as an SVG directly from Illustrator's 'Save As' menu. In the options window that pops up, click 'More Options' and tweak the 'Decimal Places' to 3 or 4 (depending on the complexity of the icon). Higher means a more precise SVG.
6. Before you close out of the file, copy the path to your clipboard. This'll be handy to compare once you've optimized the path.
7. Optimize using SVGO CLI (or SVGOMG), using the settings mentioned in our contribution guidelines, and re-open the optimized file in Illustrator.
8. Paste the original path into the optimized SVG, and move it to the back layer. Change the colour of the optimized one, and if they match up - great! You've done the SVG optimization.
9. Follow the rest of the steps in the contribution guidelines (correct properties to the SVG, etc).

Hope that helps - let me know if you're having any issues.

**Review by adamrusted — APPROVED** [review]
Looks spot on to me, just needed a couple tweaks (I've made them) in order to work with the v5 release due tomorrow. Thanks for your work @Yasser-dev and @PeterShaggyNoble 🚀

**Pull request merged**
