### PR TITLE
Add Blackmagic Design

### LINKED ISSUE #5234: Request : Blackmagic Design
**Brand Name:Blackmagic Design**
**Website:https://www.blackmagicdesign.com**
**Alexa rank:4,032**
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Blackmagic Design

**Issue:** Closes #5234
**Similarweb rank:** [18,171](https://www.similarweb.com/website/blackmagicdesign.com/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon and colour from [SVG](https://images.blackmagicdesign.com/images/common/logos/gn-logo.svg) in [source](https://www.blackmagicdesign.com/) header. I wonder if, when reducing this down to just the outlines of the squares, we shouldn't include the background square as seen in [their favicon](https://www.blackmagicdesign.com/favicon.ico)?

### CODE REVIEW

**Comment by service-paradis** [comment]
They do not use any squared backgrund on their social media. They use a shortened version of their name with the squares:
image

Maybe, this version would be more representative of the brand?

They also have some vector files available by choosing "Blackmagic Design Logos" in [this page](https://www.blackmagicdesign.com/media/images).

**Comment by PeterShaggyNoble** [comment]
I'm OK with either version, @service-paradis, but my vote would go with just the squares. What do the other @simple-icons/maintainers think? If we go with the "BMD" version, we'll need to recreate it manually, preferably by figuring out which font they're using.

**Comment by adamrusted** [comment]
I think if we're matching the favicon then the current treatment is great. Given the lack of logo guidance, looking at their products they all seem to contain the full wordmark next to the squares (even their smallest products!). Does that suggest we _should_ include the wordmark on our version too?

**Comment by ericcornelissen** [comment]
I'd agree with @PeterShaggyNoble on this one. I think a version without any text looks best, but being completely unfamiliar with the brand I'd say [the version linked by @service-paradis](https://github.com/simple-icons/simple-icons/pull/5488#issuecomment-823251564) seems like a better solution. Without explicit guidelines I'd shy away from using a version with a full wordmark _if_ there is official usage of a version without it.

**Comment by adamrusted** [comment]
@LitoMore, @dirien - thoughts on this one? I can't find an SVG source of the `BMD` variant, so IMHO it's either the version currently in the PR or the full wordmark (as displayed on all their products)

**Review by PratyushJayachandran — CHANGES_REQUESTED** [review]

**Review by PratyushJayachandran — APPROVED** [review]

**Comment by PratyushJayachandran** [comment]
@simple-icons/icon-review can we merge this one. The icon matches exactly with SVG in header of the website. Asking for opinion since there was in discussion label added.

**Review by adamrusted — APPROVED** [review]

**Pull request merged**
