### PR TITLE
add Commerzbank

### PR DESCRIPTION
**Pull request by cyper85**
commerzbank

**Issue:**  #5027
**Alexa rank:** [#2698](https://www.alexa.com/siteinfo/commerzbank.de)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
International Bank, located in Germany.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @cyper85 :+1:

However, there are official vector versions of their logo available in the PDFs on [this page](https://www.commerzbank.com/en/hauptnavigation/aktionaere/publikationen_und_veranstaltungen/unternehmensberichterstattung_1/index.html) which is what we should base our icon off. I also think we may need to add cut-outs in an effort to maintain the illusion of the overlaps in the ribbon.

**Comment by adamrusted** [comment]
Regarding the cutouts - do we want something like this? If so, there's a 3-decimal path up for grabs below.

commerzbank

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Commerzbank icon</title><path d="M1.232 13.815l-.684-.19c-.004-.018-.556-.94-.548-.96C1.14 10.7 5.175 3.672 6.393 1.604h9.404c-1.03.022-1.538.058-2.416.602-1.264.817-2.15 2.252-2.553 2.948-2.836 4.914-2.698 4.679-5.535 9.593a12.59 12.59 0 0 0-.691 1.38c-.671-.114-1.258-.288-1.739-.534-.842-.428-1.136-.948-1.63-1.777zm17.846 2.868c-.619.077-1.175.09-1.542.09H6.465c-.803 0-2.49-.048-3.83-.736-.911-.49-1.194-.907-1.73-1.793l.47.811 4.235 7.338a.019.019 0 0 0 .012.006h12.756c.007 0 .01-.003.013-.007l.462-.8-.069-.863c.46-.866.748-1.322.7-2.274-.027-.541-.169-1.136-.406-1.772zM17.622 1.611c-.009-.023-1.311 0-1.325-.008v.486c-1.023.037-1.8-.035-2.644.537-.453.292-.897.713-1.33 1.236.377.498.666.972.849 1.291 2.837 4.913 2.7 4.678 5.535 9.593.402.694 1.201 2.179 1.277 3.684.032 1.037-.191 1.49-.69 2.4L24 12.676c.017-.006-6.381-11.058-6.378-11.065z"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
Don't know that a consistent cut-out along the whole edge works here, @adamrusted; it might look better if it was tapered towards the outer edge.

**Comment by fbernhart** [comment]
I've as well given it a try. :) Any opinions? The path is provided below.

commerzbank


```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"<title>Commerzbank icon</title><path d="M6.277 1.538a.018.018 0 0 0-.012.007l-4.74 8.21-1.398 2.418c.446.774.794 1.353 1.22 2.09.671 1.164 1.548 1.597 3.13 1.889a12.9 12.9 0 0 1 .697-1.392l2.783-4.824 2.786-4.826c.404-.702 1.296-2.143 2.57-2.965-.04.025-.07.059-.109.085.07-.047.137-.094.209-.136.46-.278.98-.467 1.413-.515.339-.038 1.465-.041 2.74-.041zm11.59.505c-1.048-.008-1.462.007-2.545.008-1.39 0-2.381.887-3.083 1.773.372.493.68.971.863 1.288a13357.605 13357.605 0 0 0 5.571 9.648c.404.7 1.209 2.196 1.284 3.71.029.574-.079 1.165-.265 1.592-.131.3-.652 1.207-1.256 2.253L24 12.678v-.008a.013.013 0 0 0-.002-.005zM.001 8.163l.095 4.946L0 8.163zm.093 4.946 1.132 1.964 4.264 7.384a.015.015 0 0 0 .012.005h12.265c.446-.779.664-1.147 1.311-2.282.709-1.242.278-2.681-.037-3.472-.618.076-1.18.093-1.547.093H6.35c-.809 0-2.505-.05-3.853-.741-.513-.263-.972-.65-1.248-1.027-.176-.238-.625-1.003-1.156-1.924z"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
That works for me, @fbernhart 👍🏻 What do you think, @adamrusted?

**Comment by adamrusted** [comment]
> What do you think, @adamrusted?

Looks good to me!

**Comment by fbernhart** [comment]
Ok, so feel free to review and push/merge it, if the path is ok.

**Review by adamrusted — APPROVED** [review]
Looks good to me! Thanks @cyper85 and @fbernhart for your work on this one! 🎉

**Pull request merged**
