### PR TITLE
Apache Solr

### PR DESCRIPTION
**Pull request by runxel**
**Issue:** _none_

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description
The colored svg was taken from the website header.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
SVG looks good to me, @runxel.

While I think either of their 2 colours is fine here, I wonder _should_ we go with the orange as that's what they use in their favicon?

**Comment by runxel** [comment]
Yeah, something has gone horribly wrong, and I can't figure out why (or how to fix).
I always make new branches from the `develop` branch.

After I saw something's wrong I tried to merge, but it says it's up-to-date – even it is clearly not....

**Comment by ericcornelissen** [comment]
Looks like you merged and accidentally removed the changed from `develop` without realizing. You could have undone the commit, merge `develop` again, and force push. But a new PR also works :smile:

**Comment by runxel** [comment]
Nah, it was _even worse_.
I found out I somehow managed to make the `solr` branch a parent of `develop`. How? I have no fucking clue.
This was the reason I couldn't merge develop back into solr...

**Comment by ericcornelissen** [comment]
Ow :confused:

**Pull request closed without merging**
