### PR TITLE
Add Hack club icon

### LINKED ISSUE #3450: Hack Club icon
**Name:** Hack Club
**Website:** https://hackclub.com/
**Alexa rank:** #219,404
  

**Official resources for icon and color:** https://hackclub.com/brand/

### PR DESCRIPTION
**Pull request by NovaGL**
image

**Issue:** closes #3450 
**Alexa rank:** `#219,404`
  

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by sarthaktexas** [comment]
WOOOOOO YESSSSS

**Comment by Matt-Gleich** [comment]
Thank you for this @NovaGL! You get a hack yeah from us kids over at hack club :)

**Comment by PeterShaggyNoble** [comment]
@NovaGL, was this reviewed by any of the @simple-icons/maintainers before being merged?

**Comment by fbernhart** [comment]
@PeterShaggyNoble I just reviewed it now. There seem to be some differences - I guess they have slightly updated their logo, as the "h" now has rounded edges.

I would submit a new PR to update it, but checking their Alexa rank, it seems like it has dropped quite a bit in the last half of a year. Currently it's at [683,075](https://www.alexa.com/siteinfo/hackclub.com) and with only 2k stars in their [Github repo](https://github.com/hackclub/hackclub), this would actually be `out of scope`. What do you think?

image

**Comment by PeterShaggyNoble** [comment]
It only dropped below 500k very recently, @fbernhart and, given the severity & timing of the drop, I'm guessing it might be a seasonal think. It is showing an ever so slight upswing again, up to Sunday so let's keep an eye on it for now to see if it recovers and hold off on updating our icon until we see what happens.

**Comment by fbernhart** [comment]
👍🏼 

Just a general idea:
I would be in favour of adding a different threshold for removing an icon. Something like:
- Alexa rank of 500k and below in order to be added to Simple Icons.
- If the icon is already part of Simple Icons and if it ever drops beyond an Alexa rank of 1 million, we'll remove it.

This would give us a bit of "free space". And would avoid situations where we'll add a brand that has an Alexa rank of (let's say) 450k and then the rank drops to (let's say) 700k some weeks/few months later and we _would_ actually have to remove it.

If you like, I can open an issue about this to discuss it further with everybody else.

**Comment by PeterShaggyNoble** [comment]
Yep, fire away on that issue, @fbernhart. Was giving this some thought myself over the weekend and have some ideas on it, not too dissimilar to yours.

**Pull request merged**
