### PR TITLE
Update Roundcube

### PR DESCRIPTION
**Pull request by adamrusted**
roundcube

**Issue:** Contributes to #3169
**Alexa rank:** [956,837](https://www.alexa.com/siteinfo/roundcube.com)

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> Not Necessary
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Rebuilt icon from source, 0.35px gaps between elements, kept block color on sphere for clarity.
Ran through SVGO CLI.

### CODE REVIEW

**Comment by fbernhart** [comment]
Seems like it's actually out of scope for Simple Icons? Alexa rank of 956k and "just" 3.7k Github stars.

How about removing it instead of updating it?

**Comment by adamrusted** [comment]
> Seems like it's actually out of scope for Simple Icons? Alexa rank of 956k and "just" 3.7k Github stars.
> 
> How about removing it instead of updating it?

Happy to remove it if other @simple-icons/maintainers agree? I'm used to seeing RoundCube around when using cPanel 😅

**Comment by mondeja** [comment]
I agree to remove it :recycle:

**Comment by PeterShaggyNoble** [comment]
The Alexa rank for this is [~71.2k](https://www.alexa.com/siteinfo/roundcube.net) so we should definitely keep it.

**Comment by fbernhart** [comment]
@PeterShaggyNoble Thanks for pointing out! Seems like we've all just looked at http://roundcube.com and nobody has checked http://roundcube.net. 😅

**Comment by PeterShaggyNoble** [comment]
Should the gaps in this be 0.5dp?

**Comment by adamrusted** [comment]
@PeterShaggyNoble done - I've also reworked the icon to better reflect the colour differences. Happy to revert to more like the original above if it's preferred.

roundcube

**Comment by PeterShaggyNoble** [comment]
Of the 2 options presented here, I think the first (our current treatment) with the additional gaps works better to retain the illusion of a cube when it'd converted to monochrome. See #1619 for the original discussion with a couple more options. Note as well that the current PR version (in red below) doesn't quite line up with the original, which is a perfect square.

I also think we should take the opportunity to update the source to be just https://roundcube.net/

image

**Comment by adamrusted** [comment]
That should in theory fix it @PeterShaggyNoble - The outline is on the 'outside' of the circle, so that may be distorting things somewhat. The bottom two cube segments should be the least edited, for lining up the comparison.

**Comment by PeterShaggyNoble** [comment]
Hmm ... it's still not quite lining up for me 🤔 Gave it a quick stab myself and came up with the following, which will need to be cleaned up & optimised if we go with it. Vertically aligning it to the top of the canvas will give you a better comparison with the original.

```
M 12.001953,0.07227002 C 7.722122,0.07185002 4.143247,3.32429 3.736328,7.58398 L 0.4980469,9.45312 5.179688,12.1582 C 4.536776,11.00016 4.199354,9.69753 4.199219,8.37305 4.199281,4.08064 7.667757,0.59470002 11.960938,0.57227002 11.97461,0.57223002 11.988281,0.57223002 12.001953,0.57227002 16.311161,0.57214002 19.804566,4.06467 19.804688,8.37305 19.804488,9.69603 19.467763,10.99723 18.826172,12.1543 L 23.501953,9.45312 20.265625,7.58398 C 19.858777,3.32503 16.281036,0.07285002 12.001953,0.07227002 Z M 0,9.74219 V 9.74414 17.14062 L 11.75,23.92773 V 16.5293 C 7.833927,14.26691 3.916526,12.00469 0,9.74219 Z M 24,9.74219 18.222656,13.08008 12.974609,16.11133 H 12.972656 L 12.865234,16.17383 12.25,16.5293 V 23.92773 L 24,17.14062 V 9.74414 Z
```

**Comment by adamrusted** [comment]
@PeterShaggyNoble optimized and submitted your path. May be worth another @simple-icons/maintainers looking over this one?

**Review by ericcornelissen — APPROVED** [review]
Thanks everyone for working on this and looking at this, this looks good to me 👍

**Pull request merged**
