### PR TITLE
Add Immer

### LINKED ISSUE #5387: Immer
**Brand Name:** Immer
**Website:** https://immerjs.github.io/immer/
**Alexa rank:** 503,987
**GitHub stars:** 19.7k
  

**Official resources for icon and color:** [site favicon svg](https://github.com/immerjs/immer/blob/master/website/static/img/immer-logo.svg)

### PR DESCRIPTION
**Pull request by Neo42**
immer

**Issue:** Closes #5387
**Alexa rank:** 503,987
**GitHub stars:** 19.7k
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Color is picked from image on the site. Only manually merged SVG paths into one and nothing more. Basically repeated what I did in #4971.

### CODE REVIEW

**Comment by Neo42** [comment]
@PeterShaggyNoble @adamrusted Thank you guys!

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @Neo42 🙂

There are a number of duplicate points coming from the source file in the curves of the cut-outs in the main shape as well as 4 unnecessary points in the middle. Could you see if you could tidy those up?

Also, could you update the source URL to the GitHub commit URL: https://github.com/immerjs/immer/blob/7a5382899bc8b0bf5e21972a1c7db63f53e1d697/website/static/img/immer-logo.svg

**Comment by Neo42** [comment]
@PeterShaggyNoble I don't know if I've done it right but I just trimmed it down with SVGOMG again. Seems a little tidier and still passes the linting. I've looked up for some articles on svg optimization but few really helps with this. Maybe it's because, to be honest, I don't even know what to look for for this one 😂. Could you please show me where the duplicates are in my first commit?

**Comment by PeterShaggyNoble** [comment]
Oo, wow, this one's a lot trickier to work with than it first looks! 👀

The usual way of avoiding those points in the middle of the main shape leads to a lot of distortion; the only other solution is to manually move them to the 4 corners and then fix the curves but that's far too fiddly so I think keeping them where they are is the lesser of 2 evils. As for the excess points in the curves of the cut-outs, there are 2 of them that can't be removed without introducing some minor distortion. Here's what I ended up with if you want to use it (note that the duplicate points in the circles are a result of the optimisation process):
```
M24 12.061a2.27 2.271 0 0 1-2.27 2.272 2.27 2.271 0 0 1-2.271-2.272 2.27 2.271 0 0 1 2.27-2.271A2.27 2.271 0 0 1 24 12.06zM1.245 9.074c.889-2.543 2.966-3.83 5.043-3.83 2.747 0 4.556 2.785 6.602 5.555 1.54 2.086 3.268 4.855 4.951 4.855 1.02 0 1.325-.21 2.067-1.047a3.12 3.12 0 0 0 1.822.584c.365 0 .717-.062 1.044-.177a.328.328 0 0 0 .074-.008c-.925 2.417-3.198 3.75-5.223 3.75-2.747 0-4.593-2.745-6.527-5.482-2.008-2.84-3.51-4.981-5.193-5.038-.762-.025-1.461.437-2.007 1.21a3.112 3.112 0 0 0-1.718-.514c-.326 0-.64.05-.935.142zm2.347 5.781c.616 1.13 1.633 1.574 2.69 1.574 1.695 0 3.772-2.851 5.102-5.159 1.722-2.99 3.635-6.025 6.403-6.025 2.116 0 4.233 1.314 5.113 3.913a3.106 3.106 0 0 0-1.17-.226 3.114 3.114 0 0 0-1.33.296c-.6-1.274-1.67-1.767-2.786-1.767-1.696 0-3.275 2.074-5.066 5.065-1.923 3.209-3.67 6.12-6.44 6.12-2.04 0-4.081-1.223-5.013-3.64a.298.298 0 0 0 .045.008 3.115 3.115 0 0 0 1.04.177c.508 0 .988-.12 1.412-.336zm.95-2.794a2.27 2.271 0 0 1-2.271 2.272A2.27 2.271 0 0 1 0 12.06a2.27 2.271 0 0 1 2.27-2.27 2.27 2.271 0 0 1 2.271 2.271Z
```

**Comment by Neo42** [comment]
Thanks for your fix @PeterShaggyNoble. I Shamelessly took it. But where can I learn about this? Could you please point me to some resources about it, if you will, so that next time I can do the fix on my own? Thanks!

**Comment by PeterShaggyNoble** [comment]
> I Shamelessly took it

No problem at all 🙂 But we will need one of the other @simple-icons/maintainers to review it now.

> I have no idea how you did it

Half the time, I've no idea what I'm doing either! 😆 I've been wondering recently if a series of step-by-step tutorials for specific icons in [our discussions](https://github.com/simple-icons/simple-icons/discussions) might be useful to our community and contributors?

**Comment by Neo42** [comment]
> I've been wondering recently if a series of step-by-step tutorials for specific icons in our discussions might be useful to our community and contributors?

Woo~ That'll be great! Definitely useful, at least for me. I'd love to do more contributions to this project, but I don't want to bother you guys too much with my problems. So it'd be great if I can do all the fixes on my own and save you some trouble.

**Comment by PeterShaggyNoble** [comment]
> I don't want to bother you guys too much with my problems

It's no bother, it's what we're here for 🙂 I have two axioms in life that are relevant here: "You learn more from getting it wrong than from getting it right" and "You learn nothing if you don't ask what you don't know".

We _all_ struggled when we first started with SVGs - hell I could barely draw a fecking circle! - and we all learned through the help & examples of others; it's one of the beautiful things about open source.

I'll bring the tutorials idea to the team now and we'll see if we can get them up & running in the next few days.

**Comment by Neo42** [comment]
You the man!

> "You learn more from getting it wrong than from getting it right" and "You learn nothing if you don't ask what you don't know"

These are good points. Kobe Bryant once said "I always play to my weaknesses.", which is similar to your two axioms here.

Looking forward to the series!

**Comment by adamrusted** [comment]
I'm seeing a few small differences in the path [compared to the original](https://user-images.githubusercontent.com/1830867/114911456-ef86f380-9e16-11eb-82ba-ce3aa8426943.png) and it looks like we can save a few points by merging the two overlapping paths (there's still excess points showing in the center, somehow?). To save @Neo42 and @PeterShaggyNoble worrying about the icon, I'll update this comment shortly with a path I've generated which _should_ fix those issues.

**Comment by Neo42** [comment]
Thanks for your improvement @adamrusted. I'll use yours for now and let's wait for a further review 😅

**Comment by PeterShaggyNoble** [comment]
> I'm seeing a few small differences in the path

Weird; dunno how that happened - I thought I'd been very careful, given how fiddly this one was 🤷🏻‍♂️

**Review by service-paradis — APPROVED** [review]
Looks pretty good to me now!
Is there any reason why there is a change to `imou.svg` included?

**Comment by Neo42** [comment]
@service-paradis Thanks for the approval!

> Is there any reason why there is a change to imou.svg included?

It was an accident… I tried to revert the commit, but the file change still remain in the pr 😂

**Comment by Neo42** [comment]
Solved with a dirty workaround.

**Pull request merged**
