### PR TITLE
Add Forestry

### LINKED ISSUE #5453: Icon Request: Forestry
**Brand Name:** Forestry
**Website:** [https://forestry.io](https://forestry.io)
**Alexa rank:** 94,282
  

**Official resources for icon and color:** [https://forestry.io/img/forestry-pos-symbol.svg](https://forestry.io/img/forestry-pos-symbol.svg)

### PR DESCRIPTION
**Pull request by AMatisse**
forestry

**Issue:** Closes #5453 
**Alexa rank:** 94,282
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I used the Photopea tool to put the logo in the right conditions, from this [file](https://forestry.io/img/forestry-pos-symbol.svg).
The color is not clearly indicated on the website, so I used the color in which it is displayed on the [website](https://forestry.io/). (#343a40)

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @AMatisse, and thanks for the contribution 👍🏻

Could you have another look at this, though, please? It should be sized relative to its largest dimension (width in this case) rather than both dimensions being `24`. After fixing the width, it will then need to be vertically centred on the canvas. It also looks like the precision may be too low when optimising as, after resizing and centring it, I'm seeing some small differences when comparing to the original.

(@mondeja, could you have a look at this one when you have a minute? The height is actually `24.02` but it's passing the linter)

**Comment by AMatisse** [comment]
Hey @PeterShaggyNoble 👋
It should be better.

**Comment by PeterShaggyNoble** [comment]
Thanks, @AMatisse. I'm noticing some hairline thin differences (e.g., [bottom right branch of the left tree](https://user-images.githubusercontent.com/15157491/114851289-95b40880-9dd9-11eb-91fa-6c85c6913300.png), with your version in red) throughout, though. This is most likely down to the precision being set too low during optimisation rather than anything you did wrong. Could you try again with a precision of 3?

**Comment by AMatisse** [comment]
I thought I had done the optimization with a precision of 3. To be sure I went back to SVGOMG, and the optimized file is identical to this one. (A higher precision does not change the svg either)
So the problem comes from the modified file?
I didn't do much modification to get the desired format. I assembled the layers, put the logo in a `24x24` format keeping the proportions, and centered it.

**Comment by PeterShaggyNoble** [comment]
You'll need to run SVGOMG on your original SVG, pre-optimisation rather than the version included in the PR. If you're still having trouble with it, you're more than welcome to use my version below:

```html
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Forestry icon</title><path d="M5.564.332v2.82L0 8.736l1.305 1.284 4.26-4.26v2.568L0 13.912l1.305 1.283 4.26-4.26v12.733h1.831V10.932l4.284 4.263 1.304-1.283-5.588-5.588V5.756l3.989 3.969 5.195 5.214v8.729h1.832v-8.725L24 9.355l-1.305-1.283-4.283 4.264V9.768L24 4.18l-1.305-1.284-4.283 4.264V.332H16.58v6.824l-4.26-4.26-1.304 1.284 5.564 5.584v2.568l-3.596-3.596-5.588-5.588V.332H5.564Z"/></svg>
```

**Comment by AMatisse** [comment]
This time I hope it's the right one 🤞

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @AMatisse.

As you're using my path now, though, we'll need one of the other @simple-icons/maintainers to review this before merging.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @AMatisse and @PeterShaggyNoble 💪🚀

**Pull request merged**
