### PR TITLE
Updated Apache OpenOffice

### PR DESCRIPTION
**Pull request by fbernhart**
apacheopenoffice

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I've rebuilt the icon from https://apache.org/logos/
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by fbernhart** [comment]
As the existing icon didn't pass the linter (even at a precision of 5), I've rebuilt it using the new source https://apache.org/logos/, as suggested in #2887.

If this get's merged, we can remove it from the list in #2887.

**Review by mondeja — CHANGES_REQUESTED** [review]
I'm seeing a lot of more coordinates than necessary. See the next comparison between your version (red) and mine (blue):

aoo-diff

**Comment by fbernhart** [comment]
@mondeja No, I used "Version 3", which is the logo alone.

Seems like they used different SVGs to build the different versions.

**Comment by mondeja** [comment]
I think that the source I've used it's more optimized, because I don't see differences in the geometries. Would you try again using that version?

**Comment by fbernhart** [comment]
@mondeja I've found the reason. The SVGs are actually the same.

I've made a mistake in Inkscape. The "birds" are actually already cut out of the blue circle in the original SVG. But they still exist as extra path. So when I created the difference between the circle (with the birds already cut out) and the birds themselves, some more points were created.

I've solved it now by just deleting the extra birds path. 😄

**Review by mondeja — APPROVED** [review]
It's perfect now :sparkles: Thank you @fbernhart!

**Pull request merged**
