### PR TITLE
Add JOUAV icon

### LINKED ISSUE #10468: Request: JOUAV
### Brand Name

JOUAV

### Website

https://www.jouav.com

### Popularity Metric

The JOUAV rank is 368,217. See [https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=jouav.com](https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=jouav.com)

### Official Resources for Icon and Color

svg: https://www.jouav.com/wp-content/themes/jouav-theme-dist/assets/img/theme/logo.svg
color: `#E1B133`, from the website header

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by geoyee**
jouav

**Issue:** closes #10468 

**Similarweb rank:**
  
Global Rank is [368,217](https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=jouav.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
@geoyee, I think we should be OK using just the "O" here; I can't find any brand guidelines that would explicitly prohibit it and they do use it as a branding element throughout their website's homepage. What do you think?

**Comment by geoyee** [comment]
> @geoyee, I think we should be OK using just the "O" here; I can't find any brand guidelines that would explicitly prohibit it and they do use it as a branding element throughout their website's homepage. What do you think?

I think it's better to use the full English name (JOUAV), as I've never seen a separate "O" in brand promotion.

In [YouTube](https://www.youtube.com/jouav)

image

or In [Twitter](https://twitter.com/Jouav_inc)

image

**Review by adamrusted — APPROVED** [review]

**Comment by PeterShaggyNoble** [comment]
I still think we'd be OK to use just the "O" here; what I was referring to above is that they use it in all the headings on, at least their homepage, such as the example below. This, to me, makes it a recognisable branding element on its own and, obviously, for our purposes, works better as an icon. I'm also starting to lean away from following what brand's are using on social media as, in the vast majority of cases, the space provided is big enough to use a full logo. What do the other @simple-icons/maintainers think?

**Comment by service-paradis** [comment]
The `O` would certainly look better as an icon and I agree that using it on their website suggests it is ok to use standalone. On the other side, @geoyee is right about the brand using only the full wordmark for everything else (social media and products for example).

I'm really mixed for this one. I'm ok to keep it that way, but I tend to be a little more on @PeterShaggyNoble side. The letter `O` is really distinct, they use it standalone on their website in a few occasions and it would certainly look better as an icon than a full wordmark logo.

**Comment by PeterShaggyNoble** [comment]
@geoyee, given the comments above, would you like to submit a new PR to update the SVG to use just the `O`?

**Pull request merged**
