### PR TITLE
Add PlayStation 5

### LINKED ISSUE #3528: Playstation 5
**Name:** PlayStation 5
**Website:** https://www.playstation.com/en-us/ps5/
**Alexa rank:** 485
**Official resources for icon and color:** They don't seem to be public which might be an issue

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
PlayStation 5

**Issue:** Closes #3528 (ref: #3845)
**Alexa rank:** [393](https://www.alexa.com/siteinfo/playstation.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon taken from the "ps-icon_ps5-logo-plain" `symbol` in [this SVG](https://www.playstation.com/etc.clientlibs/global_pdc/clientlibs/auto-clientlibs/pdc.designkit/resources/ps-icons-map.svg) found in HTML source. Went with the same blue as all our other PS icons but entirely unsure if that's correct.

**Edit:** Had to go up to precision 5 to prevent SVGO from resizing it 🙄 If anyone can do better, feel free to commit directly to my branch.

### CODE REVIEW

**Comment by adamrusted** [comment]
Able to get it through the linter at 4 decimals with only a small difference on the `P`. See below for path:

```svg
<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>PlayStation 5 icon</title><path d="M10.4499 14.569c.7637 0 1.3829-.6191 1.3829-1.3829v-2.3784c0-.4601.373-.8331.8331-.8331h2.685a.0373.0373 0 00.0363-.0373v-.4761a.0363.0363 0 00-.0363-.0363h-3.2337c-.7637-.0006-1.3833.6181-1.3839 1.3819V13.1882a.8342.8342 0 01-.8331.8342H7.2535a.0363.0363 0 00-.0363.0363v.4761c0 .0201.0163.0363.0363.0363l3.1964-.0021zm6.0449-3.2115V9.4612a.0363.0363 0 01.0363-.0363h7.3077a.0373.0373 0 01.0373.0363v.4761a.0382.0382 0 01-.0373.0373h-6.2093a.0363.0363 0 00-.0363.0363v1.2356a.3954.3954 0 00.3934.3974h4.6257c.8077.0424 1.4281.7316 1.3857 1.5394-.0393.7484-.6373 1.3464-1.3857 1.3857h-6.0812a.0363.0363 0 01-.0363-.0363v-.4741a.0363.0363 0 01.0363-.0363h5.5305a.9158.9158 0 00.9421-.8888.9158.9158 0 00-.9492-.9419h-4.7266a.8331.8331 0 01-.8331-.8331v-.001m-10.8461.2864a.8347.8347 0 100-1.6693H.0365a.0373.0373 0 01-.0363-.0373v-.4761a.0363.0363 0 01.0363-.0363h6.1528c.764.0206 1.3666.6567 1.346 1.4207-.0198.735-.611 1.3262-1.346 1.346H1.9328a.8331.8331 0 00-.8331.8331V14.5387a.0363.0363 0 01-.0363.0363H.0365A.0361.0361 0 010 14.539l.0002-.0043v-1.513c.0028-.7622.6217-1.3784 1.3839-1.3778h4.2646z"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
Thanks, @adamrusted, but that's a bigger difference than we generally allow.

**Comment by adamrusted** [comment]
@fbernhart - any chance you can work your ✨ Inkscape Magic ✨ on this one, or are we going to have to go for 5 decimals?

**Comment by fbernhart** [comment]
@adamrusted I wasn't able to do it better than you guys. So let's merge it with a precision of 5.

**Pull request merged**
