### PR TITLE
Add Plausible Analytics

### LINKED ISSUE #4878: Add Plausible Analytics
**Brand Name:** Plausible Analytics
**Website:** https://plausible.io
**Alexa rank:** 64,891 
  
**Official resources for icon and color:**
https://github.com/plausible/docs/blob/master/static/img/logo.svg

I'm the co-founder of Plausible Analytics. Thanks!

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Plausible Analytics

**Issue:** Closes #4878
**Alexa rank:** [~51.9k](https://www.alexa.com/siteinfo/plausible.io)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon treatment approved by co-founder @metmarkosaric in original issue.

Not as easy an icon to work on as it first appeared so may be improvable. Colour from [website](https://plausible.io/) styleseheet.

### CODE REVIEW

**Comment by metmarkosaric** [comment]
thanks @PeterShaggyNoble!

**Review by mondeja — DISMISSED** [review]
I'm seeing some minor differences in the cutout between your version and the original that maybe are caused by the optimization process. Could you check that @PeterShaggyNoble?

image

**Comment by PeterShaggyNoble** [comment]
@mondeja, you need to remove the `rect` in the source SVG before resizing it; the icon is slightly smaller than it so you'll see that difference when comparing without removing the `rect`.

**Comment by mondeja** [comment]
Yep, that's true, thank you for the correction :man_facepalming: 

I'm fine with the geometry, but could you explain why the top part of the cut [is so smooth (your version red, source blue)](https://user-images.githubusercontent.com/23049315/110349437-00cc2b80-8033-11eb-80e3-a3293db17a43.png). Wouldn't it not be better to [stick closer to the original path](https://user-images.githubusercontent.com/23049315/110349773-5274b600-8033-11eb-9c1e-70c108f64dfb.png)?

**Comment by PeterShaggyNoble** [comment]
> could you explain why the top part of the cut is so smooth

I assumed the fact that the circle overlaps the "P" shape in a number of places was a mistake in the original.

**Review by ericcornelissen — APPROVED** [review]
> 
> 
> > could you explain why the top part of the cut is so smooth
> 
> I assumed the fact that the circle overlaps the "P" shape in a number of places was a mistake in the original.

I'm inclined to agree with Peter here. In the interest of getting this off the backlog I will merge this now (provided the CI doesn't fail). We can always revisit the curvature on this one later.

**Pull request merged**
