### PR TITLE
Added LaTeX

### PR DESCRIPTION
**Pull request by phatbhoy67**
**Issue: #1391 **

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Simplified official logo hummingbird logo. (https://github.com/latex3/branding)

Hex value is from full logo and confirmed in colour pallette here: (https://github.com/latex3/branding/blob/master/latex-project_color-palette/color-palette.png?raw=true).
Built on GitPod, working as expected.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Thanks @ericcornelissen I also have the wordmark only version ready. Should I do a separate PR for that just in case @birjolaxew or @davidklebanoff go that route? Let me know.

I also looked at simplified version of the official logo, below:
 LaTeX Logo

**Comment by ericcornelissen** [comment]
> Should I do a separate PR for that just in case @birjolaxew or @davidklebanoff go that route?

No preferably not, if we decide we want the other icon I would prefer it to be in this Pull Request anyway :slightly_smiling_face:

If you don't want to lose the SVG file of the wordmark you can add it to a `.zip` file and include it in a comment here.


> I also looked at simplified version of the official logo, below:

Having a combination of wordmark and logomark is never a good idea for the intended purpose of the SVGs we provide, at the scale we expect our users to use the logos (i.e. pretty small) having both makes the icon more difficult to read while not adding any value.

**Comment by phatbhoy67** [comment]
[latexwordmarksvg.zip](https://github.com/simple-icons/simple-icons/files/3708393/latexwordmarksvg.zip)

Thanks @ericcornelissen I will wait and update this PR if required. Also attaching wordmark version as ```.zip``` as suggested 😃

**Comment by birjolaxew** [comment]
Although I personally see the LaTeX wordmark as their primary logo, I do agree with @ericcornelissen that "If the brand guidelines bad (in this case the actual logo is not recognizable) that is the problem of the brand and not ours" - with that in mind, I think that the choice of logo in this PR is the right one.

Thanks for your work on this @phatbhoy67! It is much appreciated.

**Pull request merged**
