### PR TITLE
Clickup icon

### LINKED ISSUE #3127: ClickUp Icon
**Name:** ClickUp 
**Website:** [clickup.com](https://clickup.com/)
**Official resources for icon and color:** [Official Brand Assets](https://clickup.com/brand)

### PR DESCRIPTION
**Pull request by dstrants**
ClickUp

**Issue:** Closes #3127 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Adds the [ClickUp](https://clickup.com) logo

### CODE REVIEW

**Comment by dstrants** [comment]
Yeah, I noticed that also, but I can't figure out what is causing this weird issue. In fact, as soon as I clone either the main repo or my fork, `icons/razer.svg` gets registered in unstaged changes without even opening the project in the code editor. I tried to ignore changes but it seems to keep coming back again and again. I'll have a second look though. Any ideas are more than welcome 😃

**Comment by PeterShaggyNoble** [comment]
Curious 🤔 Are you branching from `master` or `develop`?

**Comment by dstrants** [comment]
It defaults to `develop` so I branched from there? Would that be the issue?

**Comment by PeterShaggyNoble** [comment]
No, that's correct. I'm at a loss here, too 🤷‍♂️ Any of the other @simple-icons/maintainers have an idea as to what the problem might be?

**Comment by dstrants** [comment]
It seems that the issue is related with `LF` and `CRLF` as [described here](https://stackoverflow.com/questions/5834014/lf-will-be-replaced-by-crlf-in-git-what-is-that-and-is-it-important). 
I tried to `git stash`, `git reset --hard`, `git checkout`. Git acts as expected but then it keeps the file in the unstaged changes.

I even tried the configuration that is suggested in SO but still no luck.

**Comment by ericcornelissen** [comment]
Definitely looks like a `LF`/`CRLF` issue, I'm actually experiencing the same at my end (on Ubuntu). But, curiously, when I commit a fix for it on `develop` at my end it still tells me there is a difference between this branch and `develop`...

Trying to investigate what's going on here and how best to solve it.

**Comment by ericcornelissen** [comment]
Thanks for adding the Clickup icon @dstrants, your contribution is much appreciated :tada:

**Comment by dstrants** [comment]
My pleasure @ericcornelissen! Thank you and  @PeterShaggyNoble for the support on the issue with `razer.svg` 😃

**Pull request merged**
