### PR TITLE
Add AlmaLinux

### PR DESCRIPTION
**Pull request by vndroid**
**Issue:** closes #

**Similarweb rank:**

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by vndroid** [comment]
OMG, Easier said than done.

**Comment by vndroid** [comment]
@adamrusted

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for this, @vndroid!
Looks like there are [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/25cfba4d-748d-4e91-a6fd-3e823db68321) between your PR in black and the source image in green. Could you please try again while maintaining the aspect ratio of the source image?

**Comment by vndroid** [comment]
> Thanks for this, @vndroid! Looks like there are [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/25cfba4d-748d-4e91-a6fd-3e823db68321) between your PR in black and the source image in green. Could you please try again while maintaining the aspect ratio of the source image?

The original ratio would not pass the automated test. Do you have a good idea?

**Comment by adamrusted** [comment]
Providing one dimension is exactly 24px, the linter will pass. You can lock the aspect ratio of the path and the other will automatically set.

**Comment by vndroid** [comment]
> Providing one dimension is exactly 24px, the linter will pass. You can lock the aspect ratio of the path and the other will automatically set.

Yes, I try it `Providing one dimension is exactly 24px`. But `lint` report:

```
x icons/almalinux.svg
  x icon-centered <path> must be centered at (12, 12); the center is currently
                  (12, 11.745)
```

Any idea?

**Comment by PratyushJayachandran** [comment]
> Any idea?

Run the original through SVGO on precision 7 and then rework to match the contribution guidelines. The run through SVGO on precision 3.

**Comment by vndroid** [comment]
> > Any idea?
> 
> Run the original through SVGO on precision 7 and then rework to match the contribution guidelines. Then run the contribution through SVGO on precision 3.

Sorry, I don’t follow. I am a layman in this, Can you tell me what tool software I should use to do this? Inkscape?

By the way, [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/25cfba4d-748d-4e91-a6fd-3e823db68321). I just changed the center point of the icon, why can't it go through?

**Comment by PratyushJayachandran** [comment]
> Sorry, I don’t follow. I am a layman in this, Can you tell me what tool software I should use to do this? Inkscape?

Any software would work. Inkscape is good. 
Ignore what I said before. That trick is needed at times with some SVGs. Basically instead of working on the source as is, run it through the [SVG optimizer](https://jakearchibald.github.io/svgomg/) once with highest precision and then work on the icon to scale it down and fit in 24px by 24px viewbox.

> By the way, [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/25cfba4d-748d-4e91-a6fd-3e823db68321). I just changed the center point of the icon, why can't it go through?

I was able to follow the usual steps of just taking the original, scaling it down and optimizing it.
[almalinux-fixed](https://github.com/simple-icons/simple-icons/assets/35000807/bc30d731-b2d3-4ecc-8c8a-e039cbe38f4c)

**Comment by vndroid** [comment]
> > Sorry, I don’t follow. I am a layman in this, Can you tell me what tool software I should use to do this? Inkscape?
> 
> Any software would work. Inkscape is good. Ignore what I said before. That trick is needed at times with some SVGs. Basically instead of working on the source as is, run it through the [SVG optimizer](https://jakearchibald.github.io/svgomg/) once with highest precision and then work on the icon to scale it down and fit in 24px by 24px viewbox.
> 
> > By the way, [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/25cfba4d-748d-4e91-a6fd-3e823db68321). I just changed the center point of the icon, why can't it go through?
> 
> I was able to follow the usual steps of just taking the original, scaling it down and optimizing it. It is producing the expected result. [almalinux-fixed](https://github.com/simple-icons/simple-icons/assets/35000807/bc30d731-b2d3-4ecc-8c8a-e039cbe38f4c)

Thank you very much. I have updated it.

**Review by PratyushJayachandran — APPROVED** [review]
Perfect match @vndroid 🎉

**Pull request merged**
