### PR TITLE
Taco Bell icon

### PR DESCRIPTION
**Pull request by adsingh14**
**Issue:** #6944
**Alexa rank:** 19,384
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

tacobell

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @adsingh14,

thanks for the contrib. There is some slight difference. Maybe worth to up the precission?

image

**Review by dirien — COMMENTED** [review]
Still see some differences:

image


would ask a another maintainers opinion

**Comment by LitoMore** [comment]
I guess the different is from the source file. The source file have a white background but not fit.

@dirien Have you removed the background and re-centered the source image?

image

**Review by dirien — COMMENTED** [review]
hi @LitoMore,

I am using the one from the homepage of tacobell. Its already in black and whithout padding.

image

Still see a remarkable difference in the curve.

**Comment by adsingh14** [comment]
> hi @LitoMore,
> 
> I am using the one from the homepage of tacobell. Its already in black and whithout padding.
> 
> image
> 
> Still see a remarkable difference in the curve. 

Hi there! 

Today, I used  svg-grabber extension for extracting svg logos and got 2 TB logos where one logo name starts from 'Cart' and another title is the same as I mentioned in the issue. IMO, the logo I used is accurate.

**Comment by adsingh14** [comment]
> hi @LitoMore,
> 
> I am using the one from the homepage of tacobell. Its already in black and whithout padding.
> 
> image
> 
> Still see a remarkable difference in the curve. 

@dirien Hi there! 

Today, I got two logos on using 'svg-grabber' extension where first logo title starts from 'Cart' and another is same as I linked in the issue. IMO, the logo I used is accurate to the home page. Let me know if you want to increase its precision to 5?

**Comment by dirien** [comment]
Hi @adsingh14,

can you post the svg u used as file in this PR?

**Comment by adsingh14** [comment]
> Hi @adsingh14,
> 
> can you post the svg u used as file in this PR? 

Hi there! 

The recent commit has the same logo I posted in issue with having  **precision of 5**. Shall I re-upload it with precision 4, again?

**Comment by adsingh14** [comment]
Hi @dirien!

The recent commit has the same logo I linked in the issue with having precision of 5. Shall I re-upload it with `precision:4`, again?

**Comment by dirien** [comment]
So @adsingh14, it's the logo from wikipedia?

When I look on the homepage, I see also two logos there.

**Comment by adsingh14** [comment]
> So @adsingh14, it's the logo from wikipedia?
> 
> When I look on the homepage, I see also two logos there.

Ref: https://github.com/simple-icons/simple-icons/pull/6945#issuecomment-1181377111

Both website and Wikipedia svg logos are the same. Even the logo name is the same on both websites if you use svg extractor extension.

**Review by dirien — APPROVED** [review]
Hi @adsingh14,

sorry for the back and forth but now its a perfect fit!

image

**Pull request merged**
