### PR TITLE
Add Eleventy icon

### PR DESCRIPTION
**Pull request by svillegascreative**
**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- I converted manually from PNG in Inkbox
- Hex code is #000000 to match how the logo is used throughout the Eleventy site

My first PR! Please let me know if I missed anything, and apologies for any mistakes!

### CODE REVIEW

**Comment by svillegascreative** [comment]
Sorry, I have to fix the "viewBox" property...

**Comment by birjolaxew** [comment]
The vectorization looks good! I do have to ask though: is there a reason for the background to be a rectangle, as opposed to e.g. a square, or simply having the "11ty" letters without a background? I see that [their logo PNG](https://www.11ty.io/img/logo.png) is of the same format as this PR, but I think that's because the background isn't visible [when it's used](https://www.11ty.io/).

Opinions @ericcornelissen @svillegascreative?

**Comment by ericcornelissen** [comment]
When you look at [the docs](https://www.11ty.io/docs/) and [the GitHub organisation](https://github.com/11ty) you see that the logo is used as a rectangle. That said, there are also cases where it is ambiguous (e.g. [their twitter](https://twitter.com/eleven_ty)) or a square (e.g. the favicon or [this tweet](https://twitter.com/zachleat/status/1180195959730573313)).

For that reason, I'm fine either way but I think the rectangle is preferred by them in general. We could ping the maintainer of Eleventy with an @-mention?

**Comment by birjolaxew** [comment]
@ericcornelissen I clearly didn't check deep enough. My bad! With those examples I definitely agree that the rectangle is perfectly fine.

:+1: Thanks for your work on this @svillegascreative! Your contribution is much appreciated.

**Comment by svillegascreative** [comment]
Yay! Thank you!

**Pull request merged**
