### PR TITLE
Add Homepage icon

### LINKED ISSUE #10450: Request: Homepage
### Brand Name

Homepage

### Website

https://github.com/gethomepage/homepage

### Popularity Metric

https://github.com/gethomepage/homepage
> 13.7 

### Official Resources for Icon and Color

https://github.com/gethomepage/homepage/blob/main/docs/assets/favicon.ico

here is the favicon
image

the main color seems to be #009bd5

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by 21st-centuryman**
**Issue:** closes #10450

https://github.com/gethomepage/homepage
> 13.7 

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
homepage

### CODE REVIEW

**Comment by 21st-centuryman** [comment]
Honestly would prefer if there was a line in the top right, but the svg that they provided is the official one. So it has to stay this way.

**Comment by PeterShaggyNoble** [comment]
@21st-centuryman, the source icon was created with Potrace which is a tool for converting raster images to vectors. It often produces very poor results and a lot of people don't seem to bother reviewing them, so we only ever use them as a starting point at the very most. If you feel it needs to be tweaked to make it more faithful to the _actual_ icon or that it would benefit from a cut-out then feel free to do so 👍🏻

**Comment by 21st-centuryman** [comment]
@PeterShaggyNoble i think it's best I don't mess with it. After all I'm not associated with the project, I'm just a fan. 

Once they have a better svg I'll update it then on simple-icons.

**Comment by PeterShaggyNoble** [comment]
Did you hear anything back from them yet, @21st-centuryman?

**Comment by shamoon** [comment]
The actual version we have is raster, it was from one of our users. And yes, the svg we created with just the silhouette is from the png

homepage_raster

homepage_mono

**Comment by 21st-centuryman** [comment]
@PeterShaggyNoble I guess we should just use the one mentioned by @shamoon.

thank you @shamoon, hope you have a great rest of the week.

**Review by PeterShaggyNoble — DISMISSED** [review]
Thanks for taking the time to respond, @shamoon 👍🏻 

Given that feedback, we're good to run with this treatment, @21st-centuryman - the SVG lines up perfectly with the source but it does contain a good few excess points. Could you see if you could remove them before we merge this?

**Comment by 21st-centuryman** [comment]
@PeterShaggyNoble I am not sure what you mean by excess points? Do you want me to do something different with svgo?

**Comment by PeterShaggyNoble** [comment]
See [here](https://github.com/simple-icons/simple-icons/assets/15157491/6ce50760-3d48-4dc5-9771-52c985b0b0e7), @21st-centuryman; you should be able to delete all points along the straight lines as well as one of the overlapping points in the top-left. As the source SVG is generated by Potrace, I wouldn't be too concerned if any minor differences are introduced as a result.

**Comment by 21st-centuryman** [comment]
@PeterShaggyNoble Does this look good?

**Review by adamrusted — CHANGES_REQUESTED** [review]
Looks like work on the bottom of this icon has introduced some weirdness - see the source in red and your PR in black....
image

Would you mind having another look @21st-centuryman? Might just need to be a higher precision on your PR version :)

**Comment by 21st-centuryman** [comment]
@adamrusted  I believe these are caused by the excess points I was told to remove earlier, do you want me to revert to commit [d47f958](https://github.com/simple-icons/simple-icons/pull/10452/commits/d47f958a700093d480780d604d5cdbc6aa25ae7e) or should I still remove these points but to a satisfying level? 

I am fine with both.

**Comment by adamrusted** [comment]
Hey @21st-centuryman - I think there's a happy medium somewhere between what's currently in this PR and the source icon. If you keep a local copy of the source icon and compare as you remove points, remove just enough that it's 'minimized' the amount of excess points without affecting the shape (if that's possible!)

**Comment by 21st-centuryman** [comment]
I did my best attempt at this. there will be some small changes I don't think I can avoid that. If you guys are super against any changes I would recommend just using commit [d47f958](https://github.com/simple-icons/simple-icons/pull/10452/commits/d47f958a700093d480780d604d5cdbc6aa25ae7e)

**Comment by PeterShaggyNoble** [comment]
Ah, the joys of Potrace - none of the straight lines are actually straight! 🙄 The unoptimised path below is the best I could manage, if you want to run with it. Although, perhaps @adamrusted could throw an eye over it first before you go any further.
```
M1.9917359,0.03401732C1.2174189,0.16581596 0.60235859,0.84128399 0.41564385,1.7693661 0.3881858,1.9011647 0.36072775,21.857675 0.3881858,23.895063c0,0.181223 0,0.181223 0.9225905,-0.593094 0.4971291,-0.416075 1.3286269,-1.12829 1.8012481,-1.515684 0.3404798,-0.280073 0.6260435,-0.54367 0.6370267,-0.57662 0.010983,-0.03844 0.021966,-1.147746 0.016475,-2.465732l-0.00549,-2.394342h1.5156844c0.8292331,0 1.521176,0.02197 1.5376508,0.04393 0.016475,0.02197 0.027458,0.538177 0.021966,1.142254 0,0.609569 0.010983,1.103814 0.021967,1.103814 0.016475,0 0.6425183,-0.521703 0.7248925,-0.604077 0.016475,-0.01647 0.4008875,-0.334988 0.8511996,-0.713909 0.9225904,-0.768826 0.9170988,-0.763334 1.3729024,-1.147747 0.2800722,-0.236139 0.3404802,-0.263597 0.4118712,-0.203189 0.07139,0.0659 2.877603,2.4218 3.591513,3.020385 1.313579,1.098365 2.622935,2.202113 3.931992,3.305949 0.0034,0.0031 2.020159,1.739513 2.075829,1.702399 0.02197,-0.01098 0.03844,-3.333407 0.03844,-7.380723 -0.0055,-6.573458 0.0055,-7.3642495 0.08237,-7.3807243 0.04393,-0.010983 0.895133,-0.016475 1.883623,-0.016475h1.801248L23.601221,5.459728C23.59573,3.389391 23.568272,1.6430591 23.551797,1.5826513 23.409015,1.0884064 23.041077,0.56121188 22.667648,0.30310621 22.195369,-0.01540717 22.832396,0.00106766 12.10179,0.00106766 6.6596044,-0.00442395 2.1125513,0.01205088 1.9917359,0.03401732Z
```

**Comment by 21st-centuryman** [comment]
@PeterShaggyNoble Thank you for your help, i committed the changes.

**Comment by adamrusted** [comment]
Thanks for the assist @PeterShaggyNoble!
@21st-centuryman - as you can see from the checks, they're failing because the precision of Peter's unoptimized path is way too high. Could you please run it through SVGOMG or similar to get the precision points as low as possible without altering the shape?

**Comment by adamrusted** [comment]
@21st-centuryman We usually aim for a path with a precision between 3 and 5,  so the linter is likely to fail again on the precision of 2 :sweat_smile:

If a precision of 3 isn't showing any differences compared to Peter's original path, then let's go with that.

**Comment by 21st-centuryman** [comment]
ok i did some other changes. check now
@adamrusted

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks for your work on this both!

**Pull request merged**
