### PR TITLE
add iconjar file

### PR DESCRIPTION
**Pull request by abenjamin765**
- Add `.iconjar` file
More info here: https://geticonjar.com/

Note: Automation is available here: https://github.com/IconJar/iconjar-exporters - Would require an installation of the PHP library

### CODE REVIEW

**Comment by birjolaxew** [comment]
The icon addition has a couple issues:
- IconJar is missing from `simple-icons.json`
- [IconJar has a >500k Alexa rank](https://www.alexa.com/siteinfo/geticonjar.com), which [usually makes it too unpopular to be included in Simple Icons](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon). Since it is a downloadable program and not just a website this might be a bit misleading though - we could consider merging it in if anyone has a source that indicates that it's used by a wide audience.

More importantly though, the PR has some issues:
- It includes the commits from #973 - branching should happen from `develop` so we don't end up with commits in two PRs :) This can be fixed by creating a new branch off of `develop` and then cherry-picking c4f7d64 onto it.
- The commit that adds IconJar (c4f7d64) includes some apparent restructuring (?) - all icons have been moved to `assets/simple-icons.iconjar/icons/`. This definitely shouldn't happen.

**Comment by abenjamin765** [comment]
I wasn't super clear in my commit. Apologies :). I'm looking to add an `.iconjar` file that contains all of the simple-icons and their metadata so that designers who use IconJar can use simple-icons in their projects. You can read more about IconJar in the link.

**Comment by abenjamin765** [comment]
image

**Comment by ericcornelissen** [comment]
> I wasn't super clear in my commit. Apologies :). I'm looking to add an .iconjar file that contains all of the simple-icons and their metadata so that designers who use IconJar can use simple-icons in their projects. You can read more about IconJar in the link. My recommendation would be to host the .iconjar file and made it available to users for download.

I'm definitely in making SimpleIcons available for as many people as possible, however I don't think the correct approach for this is to include all the data for IconJar in this repository. For one, all the now appear twice in this repository. This also means that updating or adding new files becomes more of a hassle. 

There is an ongoing discussion on the structure of the project in #770. Personally I think it would be best to create a separate repository for the IconJar files and have it somehow be updated automatically (similar to [simple-icons-pdf](https://github.com/simple-icons/simple-icons-pdf). However, I'm not familiar with IconJar so this might not be the best approach.

For now I will close this PR, but we can discuss further here or in a separate issue :slightly_smiling_face:

**Comment by abenjamin765** [comment]
Sounds good. I linked a PHP library above (https://github.com/IconJar/iconjar-exporters) that would automate the duplication process to the jar directory with the correct metadata. It would be ideal to only have a single source, and that may be possible with further investigation. IconJar is one of the most widely used Icon managers for designers, so having an `.iconjar` file available would be valuable.

**Pull request closed without merging**
