### PR TITLE
Updated Jinja

### PR DESCRIPTION
**Pull request by fbernhart**
jinja

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
The geometry is perfect :japanese_castle:
Could you check the precision @fbernhart?
And maybe the source must be updated to use the commit-blob URL.

**Comment by fbernhart** [comment]
@mondeja Done. 😊  Precision is now 3 and the source is pointing to: https://github.com/pallets/jinja/blob/1c240154865a7b6034033027e3c2ca8a2fa53fc2/artwork/jinjalogo.svg

**Review by mondeja — APPROVED** [review]
Perfect :japan:

**Comment by d-kleine** [comment]
I love the icon, it looks fantastic! But is there a reason the icon is vertically mirrored, or has the logo been updated meanwhile? The roof goes up on the left side in the official logo — see here: https://jinja.palletsprojects.com/en/stable/

**Comment by adamrusted** [comment]
So looking at the differences between the two, it would appear Jinja have rebranded since we updated this in 2020. Would you mind opening a new issue, @d-kleine?

**Pull request merged**
