### PR TITLE
Add Cloudflare icon

### PR DESCRIPTION
**Pull request by EvasivePangolin**
Cropped down then recolored. Original source available [here](https://Cloudflare.com/logo).

### CODE REVIEW

**Comment by birjolaxew** [comment]
Nice work! It looks like you have a couple of extra attributes in your SVG - namely `width` and `height` on your `<svg>`, and `class` and `fill` on your `<path>`. Remove those and it should be ready for merging!

**Comment by ericcornelissen** [comment]
Also, can you specify why you picked `#F69259`? I can only seem to find that somewhere in the rules-list for the button at the top of the website but for me it uses `#F48120` by default. While in their logo they use `#F38020` and `#FAAE40` (from the SVG).

**Comment by EvasivePangolin** [comment]
Fixed issues

**Comment by birjolaxew** [comment]
:+1: Thanks for the contribution! It is very much appreciated.

**Comment by EvasivePangolin** [comment]
No problem :)

**Pull request merged**
