### PR TITLE
Update Conekta

### PR DESCRIPTION
**Pull request by adamrusted**
conekta

**Issue:** Contributes to #5251.
**Alexa rank:** [15,002](https://www.alexa.com/siteinfo/conekta.com)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
New icon available at [conekta.com](https://www.conekta.com/). Used hex from website stylesheet. Precision of 4 was needed for round edges and linter.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
SVG looks good to me, @adamrusted :+1: Nice work.

Not 100% on the colour, though. My first instinct would have been the purple as it's in the wordmark and used for the background of the footer and is closest to the existing. But, as the suggestion of the pink was already in my head from the preview and how vibrant it is on the site, I'm torn 🤔 What do the other @simple-icons/maintainers think?

**Comment by service-paradis** [comment]
Not an easy one! I think I would opt for the dark purple (`#0A1837`).
- Used in the logo, in the footer. 
- Used as background at https://github.com/conekta/conekta-ios
- Used in their app
image

I would have no problem keeping the pink value as they use it everywhere in their website and docs.

**Comment by adamrusted** [comment]
> Not an easy one! I think I would opt for the dark purple (`#0A1837`).

Happy to swap it out, being as it's used pretty consistently. Will sort out when I'm back in front of my PC later.

**Comment by adamrusted** [comment]
@service-paradis good to go for a review 👌

**Pull request merged**
