### PR TITLE
Add Frontend Masters icon

### PR DESCRIPTION
**Pull request by LitoMore**
frontendmasters

**Popularity metric:** Similarweb global rank 74,899

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by LitoMore** [comment]
Hi @1Marc, we would like to apply to you for the right to use the icon. Is that possible?

**Review by uncenter — APPROVED** [review]
Everything looks perfect, just waiting on that permission.

**Comment by LitoMore** [comment]
@brentmn Sorry for pinging you suddenly. Can you help us get in touch with your team? Thanks!

**Comment by uncenter** [comment]
Closing as we have not been able to obtain written permission. Can reopen this if a response indicating permission granted is received.

**Pull request closed without merging**
