### PR TITLE
Added Devfolio icon

### LINKED ISSUE #6354: New Icon Request: Devfolio
**Brand Name:** Devfolio
**Website:** https://devfolio.co/home/
**Alexa rank:** 80,182
  

**Official resources for icon and color:**
  
https://devfolio.co/favicons/favicon-128.png

### LINKED ISSUE #7698: Devfolio
### Brand Name

Devfolio

### Website

https://www.similarweb.com/website/devfolio.co/#overview

### Popularity Metric

Global Rank: 316,012

### Official Resources for Icon and Color

svg: https://devfolio.co/hackathons
color: `#3770FF`, from website branding

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
Devfolio

**Issue:** closes #6354

**Similarweb rank:**
Global Rank: 316,012 &nbsp; `https://www.similarweb.com/website/devfolio.co/#overview`

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG logo is retrieved from: `https://devfolio.co/hackathons`
The hex value is extracted from the header & logo color

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @Anmol-Baranwal ,

Thanks for your contribution to simple-icons!

Can you check the output of the linting?

```bash
  x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 21.868 x 24.204
  x icon-centered <path> must be centered at (12, 12); the center is currently (11.934, 12.102)
```

Should be a quick fix

**Comment by Anmol-Baranwal** [comment]
Since I tried adobe illustrator, adobe xd, and two online SVG editors & manual trial and error using illustrator. I have set the correct coordination in Inkspace but while optimization using cmd or SVGO-
`x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 22 x 24.182`
`x icon-centered <path> must be centered at (12, 12); the center is currently (12, 12.091)`
There is always this gap, can you please tell me how to resolve this? It would be a great help.

**Comment by LitoMore** [comment]
@Anmol-Baranwal You could use [Inkscape](https://inkscape.org).

1. Create a new document
2. Change your document `width` and `height` to `24px` in `File - Document Properties...`.
3. Drag your the source icon to Inkscape
4. Delete unused layers and paths
5. Cleanup unnecessary colors
6. Resize your icon to `24px`
7. Export the icon
8. Compress with `npm run svgo -- path-to-your-file.svg`
9. Validate your file, open the SVG in text mode, it should have only one `path`
10. Fix other linting errors

Good luck~

**Comment by Anmol-Baranwal** [comment]
Sincere apologies and thanks for your help LitoMore but unfortunately the problem persisted. I will again pull the request when I would be able to do it thoroughly.

**Pull request closed without merging**
