### PR TITLE
Add Miraheze icon

### PR DESCRIPTION
**Pull request by pisceskaze**
miraheze

**Issue:** None

**Similarweb rank:**
https://www.similarweb.com/website/miraheze.org - `#9,669`

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
* SVG I got from https://upload.wikimedia.org/wikipedia/commons/b/b7/Miraheze-Logo.svg
* Popular non-profit MediaWiki farm hosting service, no issue was made since there are no require to made one before pulling.

### CODE REVIEW

**Comment by pisceskaze** [comment]
Linter glitched I guess?

**Comment by pisceskaze** [comment]
JESUS CHRIST, FINALLY...

**Comment by pisceskaze** [comment]
And uh wait, if the third one is successfully build the package, then the error in the second test can be ignored, I guess...

**Review by PratyushJayachandran — CHANGES_REQUESTED** [review]
Please remove addition of Media Wiki from this PR

**Comment by pisceskaze** [comment]
> Please remove addition of Media Wiki from this PR

Thank you for letting me know. It's just, how can I?

**Comment by pisceskaze** [comment]
I will make another pull. Thank you.

**Comment by PratyushJayachandran** [comment]
> > Please remove addition of Media Wiki from this PR
> 
> Thank you for letting me know. It's just, how can I?

Since MediaWiki is not added yet to develop, you can simply delete that SVG from YOUR BRANCH and also delete the content from the JSON file in a single commit (say: Remove MediaWiki).

For MediaWiki you can create a new PR with link to issue #9041

**Comment by pisceskaze** [comment]
> > > Please remove addition of Media Wiki from this PR
> > 
> > 
> > Thank you for letting me know. It's just, how can I?
> 
> Since MediaWiki has not been added yet to develop, you can simply delete that SVG from YOUR BRANCH and also delete the content from the JSON file in a single commit (say: Remove MediaWiki).
> 
> For MediaWiki you can create a new PR with a link to issue #9041

Oh, thanks for letting me know! But I will make another clean branch this time, as a lesson for me..

**Comment by PratyushJayachandran** [comment]
> Oh, thanks for letting me know! But I will make another clean branch this time, as a lesson for me..

You can run `npm run lint` on your system before making the commit so that you can find errors if any.

**Pull request closed without merging**
