### PR TITLE
Add YouTube Kids

### LINKED ISSUE #6178: Add YouTube Kids Icon
Brand Name: Youtube Kids
Website: https://www.youtubekids.com/
Alexa rank: 3,934

Official resources for icon and color:

https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/YouTube_Kids_LogoVector.svg/1267px-YouTube_Kids_LogoVector.svg.png

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
youtubekids

**Issue:** closes #6178 

**Similarweb rank:** 806. See https://www.similarweb.com/website/youtubekids.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from header at https://www.youtube.com/intl/ALL_us/kids/
Colr: Taken from logo `#FF0000`

### CODE REVIEW

**Comment by adamrusted** [comment]
This is going to be a controvertial opinion....
I think we should combine the outer black outline and the red main body to make this icon a lot clearer at small resolutions.

**Comment by PratyushJayachandran** [comment]
> This is going to be a controvertial opinion.... I think we should combine the outer black outline and the red main body to make this icon a lot clearer at small resolutions.

I agree actually. I tried this one first just to see.

**Comment by PratyushJayachandran** [comment]
> This is going to be a controvertial opinion.... I think we should combine the outer black outline and the red main body to make this icon a lot clearer at small resolutions.

Please review
youtubekids

**Comment by PratyushJayachandran** [comment]
> That looks spot on to me, @PratyushJayachandran 👍🏻
> 
> Could you see, though, if you could remove some of the excess nodes in the cutout with effecting the shape of the icon? If it's not possible then this should be OK to merge straight in.

There is an ever so slight curve between each of those points, presumably to give that hand drawn look I suppose. I am of the opinion that we should leave it as is and not simplify it.

**Review by PeterShaggyNoble — APPROVED** [review]
If they can't be removed without distorting the icon in anyway then this is good to go.

**Pull request merged**
