### PR TITLE
Add Amazon Music

### LINKED ISSUE #3163: Amazon Music
So Amazon Music is very confusing branding wise, just read this site and try and workout what the name of the service is.

[Amazon Music sub-brands](https://www.amazon.com/gp/help/customer/display.html?nodeId=GW3PHAUCZM8L7W9L)

I'm happy with the below image but I don't know what branding link to use.

amazonmusic

**Name:** Amazon Music
**Website:** https://music.amazon.com/
**Official resources for icon and color:** https://press.aboutamazon.com/images-videos

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
amazonmusic

**Issue:** closes #3163 . Continuing from #9312 

**Similarweb rank:** 7,352. See https://www.similarweb.com/website/music.amazon.com

### Checklist
- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from website header https://music.amazon.com
Color: `#46C3D0` [Taken from brand resources page](https://static.amazonmusic.com/dims4/default/1704934/2147483647/strip/true/crop/1080x608+0+236/resize/1000x563!/format/webp/quality/90/?url=https%3A%2F%2Famazon-k1-prod-music2.s3.us-west-2.amazonaws.com%2Fbrightspot%2Fa1%2F97%2F725eb2cc4d77a8163ebe10d5661e%2Fen-101223-website2-0-am4a-brand-guidelinesp1-1080x1080-stacked-cyan.png)

> [!TIP]
> There is no SVG for the stacked version but I rearranged the horizontal SVG based on the [stacked raster image](https://static.amazonmusic.com/dims4/default/1704934/2147483647/strip/true/crop/1080x608+0+236/resize/1000x563!/format/webp/quality/90/?url=https%3A%2F%2Famazon-k1-prod-music2.s3.us-west-2.amazonaws.com%2Fbrightspot%2Fa1%2F97%2F725eb2cc4d77a8163ebe10d5661e%2Fen-101223-website2-0-am4a-brand-guidelinesp1-1080x1080-stacked-cyan.png) in the [brand resources page](https://artists.amazonmusic.com/brand-guidelines).
The m in music is not aligned to a in amazon in the stacked versions and for some reason their proportions are slightly off in the raster but I didn't alter the SVG to match it.

### CODE REVIEW

**Comment by adamrusted** [comment]
@PratyushJayachandran - there is in fact [this](https://d5fx445wy2wpk.cloudfront.net/static/logo_stacked.svg) stacked icon used on mobile viewports. Can you use that please?

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran - there is in fact [this](https://d5fx445wy2wpk.cloudfront.net/static/logo_stacked.svg) stacked icon used on mobile viewports. Can you use that please?

Wow! Thanks for finding it.
I updated the SVG but how do we link the source now? Can we still keep using main website?

**Comment by adamrusted** [comment]
Yeah, it's in the source code of that webpage - and people looking to review can always come back to this PR to see where we pulled the icon from!

**Review by adamrusted — APPROVED** [review]

**Comment by PeterShaggyNoble** [comment]
_**Finally**_!!! 🎉 🤣 (cc: @NovaGL)

**Pull request merged**
