### PR TITLE
Add Jinja

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Jinja
**Issue:** #1590

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Not sure about the colour choice here; I lifted the `#b41717` from [original SVG](https://github.com/pallets/jinja/blob/fb7e12cce67b9849899f934e697f7e2a91d604c2/artwork/jinjalogo.svg) but there are a couple of other reds in use on [their website](https://jinja.palletsprojects.com/en/2.10.x/) and a case can probably be made for one of the greys, too.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble I'm getting a few small differences in the path, not sure if it is an optimisation issue, below is what I get from (https://github.com/pallets/jinja/blob/fb7e12cce67b9849899f934e697f7e2a91d604c2/artwork/jinjalogo.svg) optimised precision 3 on SVGOMG:

```xml
<svg xmlns="http://www.w3.org/2000/svg" height="24" width="24"><path d="M23.72.668l-.08.038s-4.564 2.176-8.245 2.653c-1.854.24-4.554.481-6.964.62a65.554 65.554 0 01-3.255.117c-.917.005-1.628-.033-1.948-.11-1.399-.339-2.4-.733-2.4-.733l-.253-.099.346 1.172L0 5.134l.248.438.439.033 1.053.131.162.513.635.058.32 1.077.09.007s1.34.114 1.763.114c.365 0 .928-.04 1.071-.05l.024.397.287.055v.313l-.799.71.157.028c-.141.01-.227.018-.5.03-.428.017-.935.022-1.204-.017-.586-.085-.709-.087-.709-.087H2.98l-.122.131-.046.445h.153l.053 1.111 2.934-.112-.205 3.68-.019.35-2.242-.128-.02-.763h.537l.057-.42.464-.104.224-.313-2.112-.509-1.706.505.466.389h.165l.026.333.495.028v.764l-.613.156.191.405.104.067v.826h.345v3.296l-.567.087.098 1.246.333.056-.053 2.342 1.802.033-.32-2.302 1.981-.049-.138 1.086-.25 1.033 2.609.032.026-2.28 1.322-.117-.07 1.292-.064.99h1.633l-.054-2.3.176.027.066-1.393h-.24l-.06-.34-.13-1.29.047-1.364h.296v-1.182l-.364.028.04-.806.432-.043.02-.352.172-.026.511-.388-1.826-.376-1.71.38.286.468.238-.02.054-.002.035.44.408-.02.005.674-1.525-.035.052-.877.059-.926v-1.212l.048-1.152 3.484-.179 4.156-.24.034.674-.153 1.95-.062 1.693-1.32-.024-.005-1.017.574-.021.027-.374.27-.04-.011-.058.152-.008.29-.39-2.011-.47-1.986.426.258.45.14-.01v.09h.245v.402l.524.007-.005.856h-.527l-.015.505.187.021-.02.979.393.021-.044 3.614-.523.107.014.424h.176v.986h.29l-.07 1.204-.112 1.314 2.17.057-.069-1.171-.138-.849-.023-.594 1.326-.023-.041 1.003-.009 1.33 1.035.081 1.252-.05.532-.157-.25-.758-.052-1.002-.08-.583 1.232-.045-.056.742-.007 1.515.74.068.63-.014.416-.131-.187-1.424-.05-.861.25-.028.007-.895.08-.017-.028-.43h-.303l-.048-.526-.025-2.693.224-.007v-.902l.094.015v-.46l-.332-.03.006-.834.569-.05-.032-.362.259-.023-.023-.116.58-.29-2.057-.414-1.88.381.232.431.223-.018.012.076h.203l.013.426.547-.007.034.774-1.672-.013-.21-1.457-.179-.826-.143-1.468.074-.747 3.847-.292.013-1.317.2-.05-.023-.378-.239-.14h-.035l-.358.052-.793.114c-.607.087-1.3.182-1.625.217l-.191.02-.015-.177-.785-.412.005-.275.272-.008.02-.671c.09-.006.353-.023.772-.062.484-.044 1.04-.105 1.36-.18.596-.14 1.452-.282 1.452-.282l.075-.012.41-1.107.804-.235.065-.183 1.78-.493.307-.252-.715-1.563.046-.237.343-.179.296-.906zM14.824 6.73l-.01.525.408.017-.016.321-.79.517-.085.26-1.858.09.008-.185.112-.18.01-.153.002-.229.065-.156.032-.16v-.093l.08-.32zm-5.18.46l-.044.265.2.235-.012.387.174.27-.047.328.025.035-1.847.073.019-.151-.652-.355-.022-.346.293-.014.026-.598zm4.016 8.501l1.256.081-.05 1.939.183 1.541-1.34-.046zm-10.226.084l2.158.112-.192 1.283v1.218l.136.524-2.09.098zm15.377.01v3.256l-1.293.095-.05-1.723-.159-1.593zm-11.494.076l1.536.006.018 2.996-1.431.025-.076-.927-.006-1.046z" /></svg>
```

**Comment by PeterShaggyNoble** [comment]
That's some eyesight you have, @phatbhoy67! Even at 1000% zoom on the larger preview below (mine in grey, yours overlaid in red), which is already scaled up 10x, I could only see some very minor discrepancies between the 2. I'll take another pass at this later on today.

Jinja

**Comment by PeterShaggyNoble** [comment]
Updated

**Comment by phatbhoy67** [comment]
Thanks for updating @PeterShaggyNoble it is spot on 👍 

I agree with the red chosen so merging this in 🎉

**Pull request merged**
