### PR TITLE
Updated Riseup

### PR DESCRIPTION
**Pull request by fbernhart**
riseup

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
riseup.net seem to have [changed their icon](https://riseup.net/en/about-us/images#logo). Might it be worth rebuilding using the star icon?

The crow used in this icon is available in their `badges` section - but looks like it isn't the 'primary' brand image.

**Comment by fbernhart** [comment]
@adamrusted Done ⭐ I've used [this SVG](https://riseup.net/about-us/images/riseup.net-inline.svg) as source. I've as well changed the color to red `#FF0000` now, like it's used in the star.

riseup

**Review by adamrusted — APPROVED** [review]
LGTM! ⭐
Can another @simple-icons/maintainers approve this too, as I'm not 100% sure the star is representative enough of the brand.

**Comment by mondeja** [comment]
Seeing their images page, it seems to me that their main logo is the :star:

**Comment by adamrusted** [comment]
> Seeing their images page, it seems to me that their main logo is the ⭐

Fab. I'll merge this one then. 🎉

**Pull request merged**
