### PR TITLE
Add Appgallery icon

### PR DESCRIPTION
**Pull request by TeerthTejani26**
**Issue:** closes #

**Popularity metric:**

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by LitoMore — CHANGES_REQUESTED** [review]
@TeerthTejani26 Your code didn't pass the verify process. This needs to be fixed.

**Comment by uncenter** [comment]
@TeerthTejani26 are you still interested in continuing this pull request?

**Comment by TeerthTejani26** [comment]
No, I am not interested in continuing this pull request.

I do apologize for not mentioning it earlier.
________________________________

**Comment by uncenter** [comment]
No worries, thanks for your quick reply!

**Pull request closed without merging**
