### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by ericcornelissen**
**Issue:** #1427

### Description

Add `composer.json` so that Simple Icons can be made available as a package for PHP on 
[Composer](https://getcomposer.org/)/[Packagist](https://packagist.org/).

Also pinging @joshuabaker for feedback/approval.

### CODE REVIEW

**Comment by birjolaxew** [comment]
How does the PHP usage look like, once the package is installed using Composer/Packagist?

**Comment by ericcornelissen** [comment]
> How does the PHP usage look like, once the package is installed using Composer?

Good question, @joshuabaker care to give a brief description?

**Comment by joshuabaker** [comment]
A call to [`file_get_contents`](https://www.php.net/manual/en/function.file-get-contents.php).

```php
echo file_get_contents('path/to/package/icons/github.svg);
```

**Comment by ericcornelissen** [comment]
> How does the PHP usage look like, once the package is installed using Composer?

More generally, I believe you will be able to do the following in your Composer configuration file.

```json5
//  ./composer.json
{
    "require": {
        "simple-icons/simple-icons": "^1.15.0"
    }
}
```

And then a simple PHP demo would be

```php
<!-- ./index.php -->
<html>
  <head>
    <title>SimpleIcons Test</title>
  </head>
  <body>
    <h1>Simple icons</h1>

    <?php echo file_get_contents('vendor/simple-icons/simple-icons/icons/github.svg'); ?>
  </body>
</html>
```

Then if you run the following command and visit `localhost:8000` you will see [the GitHub SVG](https://github.com/simple-icons/simple-icons/blob/develop/icons/github.svg):

```bash
$ php -S localhost:8000
```

The thing that is not so nice about this, at least compared to Node, is that if you're in a child directory you need to change the file path. I'm sure there is ways to solve this on our side (maybe [autoloading](https://getcomposer.org/doc/01-basic-usage.md#autoloading?)), or maybe even just a better way to use it.

Another thing is that we have [metadata](https://github.com/simple-icons/simple-icons/blob/develop/_data/simple-icons.json) that developers can use (mainly the color), and I'm not sure how that can be used in PHP.

Do you have any suggestions for us in these regard @joshuabaker?

* * *

@birjolaxew and @davidklebanoff what are your opinions? I will look into updating documentations etc.

**Comment by joshuabaker** [comment]
> The thing that is not so nice about this, at least compared to Node, is that if you're in a child directory you need to change the file path.

Yes, you would, however, that’s a pretty standard paradigm for PHP development. To interact or output the SVG you’d have to load it from disk regardless. I don’t see this as a cause for concern.

A fair number of frameworks create a global constant for such use cases. For example, [craftcms/cms](https://github.com/craftcms/cms/) sets [`CRAFT_VENDOR_PATH`](https://docs.craftcms.com/v3/config/php-constants.html#craft-vendor-path).

> Another thing is that we have [metadata](https://github.com/simple-icons/simple-icons/blob/develop/_data/simple-icons.json) that developers can use (mainly the color), and I'm not sure how that can be used in PHP.

I’m not sure how the metadata feature works here. Looks like magic via a Node script. Is that right? 

In PHP you’d probably just load the JSON from the file, I think. Anything beyond this is likely out of scope for this issue (i.e. importing via composer).

**Comment by ericcornelissen** [comment]
> Yes, you would, however, that’s a pretty standard paradigm for PHP development. To interact or output the SVG you’d have to load it from disk regardless. I don’t see this as a cause for concern.
>
> A fair number of frameworks create a global constant for such use cases. For example, craftcms/cms sets CRAFT_VENDOR_PATH.

Thanks for the insight, I think that is out of scope for now and we can add something like that if we get an issue for it.


> In PHP you’d probably just load the JSON from the file, I think. Anything beyond this is likely out of scope for this issue (i.e. importing via composer).

That makes sense, then I don't think we should worry about it for now :+1: 

Again, I will wait for the other maintainers to have a look at this before we move onwards.

**Pull request merged**
