### PR TITLE
Letter K review

### PR DESCRIPTION
**Pull request by service-paradis**
**Issue:** #5251

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`

### Question

- According to https://www.kaggle.com/brand-guidelines, should we use the full wordmark?
- According to https://more.ko-fi.com/brand-assets, can we keep this icon?

### Description

- Update Kaggle data
  - Update source
  - Add guidelines
- Update Kahoot! data
    - Add guidelines
- Update Kali Linux data
  - Update source
  - Add guidelines
- Update KDE data
  - Update source
- Update Khan Academy data
  - Add guidelines
- Update Khronos Group data
  - Add guidelines
- Update Kik data
  - Update source
- Update KnowledgeBase data
  - Add guidelines
- Update Ko-fi data
  - Update color
  - Update source
  - Add guidelines
- Update Kofax data
  - Update source
Update Komoot data
  - Add guidelines

### CODE REVIEW

**Comment by adamrusted** [comment]
> * According to [kaggle.com/brand-guidelines](https://www.kaggle.com/brand-guidelines), should we use the full wordmark?

I would say yes, we would need to use the full wordmark, unless we ask for permission to just use the `K`.

> * According to [more.ko-fi.com/brand-assets](https://more.ko-fi.com/brand-assets), can we keep this icon?

They're pretty explicit about not changing the colours. Again, unless you fancy reaching out to them I'd say we have to look at removing it (which is a shame, given it'll be used by a lot of developers!)

**Comment by service-paradis** [comment]
Thank you @adamrusted! It confirms what I though. Like you said, it is really unfortunate to remove `ko-fi`, I'm pretty sure this one is used quite often...
I will open new issues for those 2 brands where it could be discussed if needed.

**Comment by adamrusted** [comment]
> I'm pretty sure this one is used quite often...

I had a quick look at shields.io and they don't actually offer an out-of-the-box Ko-fi button, so that's a silver-lining I guess. As you say, can discuss other issues in your respective PRs. Will merge this in for now once I've confirmed JSON changes.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @service-paradis 🚀

**Pull request merged**
