### PR TITLE
Add AntV icon

### LINKED ISSUE #12274: Request: AntV
### Brand Name

AntV

### Website

https://antv.antgroup.com

### Popularity Metric

[130k weekly downloads on npm](https://www.npmjs.com/package/@antv/g2)

### Official Resources for Icon and Color

- JPEG: https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*A-lcQbVTpjwAAAAAAAAAAAAADmJ7AQ/original
- Color: `#6500FF`

from the website header: https://antv.antgroup.com/

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by Aarebecca**
antv

**Issue:** closes #12274

**Popularity metric:**

[130k weekly downloads on npm](https://www.npmjs.com/package/@antv/g2)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Icon and color are provided by AntV designers

### CODE REVIEW

**Review by LitoMore — CHANGES_REQUESTED** [review]
Hi @Aarebecca, your code didn't pass [the linter](https://github.com/simple-icons/simple-icons/actions/runs/12193694395/job/34018134885?pr=12275). This needs to be fixed.

Also, could you provide the original SVG image so we can review it?

**Comment by Aarebecca** [comment]
@LitoMore I will solve the lint problem as soon as possible. 

The following attachment is the original SVG image of the AntV Logo:

antv

**Review by LitoMore — CHANGES_REQUESTED** [review]
I can see some differences here:

image

Can you check it? Here is [How do I review differences](https://github.com/simple-icons/simple-icons/discussions/9351).

**Comment by Aarebecca** [comment]
@LitoMore I re-uploaded the newly made logo image. Now compare it with the original logo image in Inkscape. The two have exactly the same outline.

image

**Comment by LitoMore** [comment]
Thank you for solving those differences. This should be the last problem that needs to be solved:



You can double click the switch the mode from the panel to see those control points:

**Comment by Aarebecca** [comment]
Hi @LitoMore Thank you very much for your careful inspection. I have contacted our designer to optimize the Logo. The following image is our optimized Logo. At the same time, the newly simple logo has also been committed.

<image width=300 src="https://github.com/user-attachments/assets/7473db16-dc16-4d06-9f4c-1844174689ad" />

The following image is a comparison of the outlines of the original logo and the simple logo:

image

The following image shows the control points of the new simple logo:

image

**Review by LitoMore — APPROVED** [review]
Congrats on your first contribution to Simple Icons!

整挺好，多谢！

**Pull request merged**
