### PR TITLE
Add microsoft365

### LINKED ISSUE #8887: Microsoft 365 Icon Request
### Brand Name

Microsoft 365

### Website

https://www.office.com/

### Popularity Metric

Rank 23 at https://www.similarweb.com/website/office.com/#overview

### Official Resources for Icon and Color

https://res-1.cdn.office.net/files/fabric-cdn-prod_20221209.001/assets/brand-icons/product/svg/m365_48x1.svg

### Additional Comments

I can't find a black n white version but I'm sure you can. Microsoft switched to using the M365 logo for everything office related.

### Contributing

Yes

### PR DESCRIPTION
**Pull request by Gautam25Raj**
microsoft365 (1)

**Issue:** closes #8887 

**Similarweb rank:**
The similarweb rank is 23. See https://www.similarweb.com/website/office.com/#overview

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
**SVG**: Taken from website header which was provided as SVG https://www.office.com
**Color**: `#3b4a7a` Taken from averaging logo colors.

### CODE REVIEW

**Comment by adamrusted** [comment]
Thanks for the contribution @Gautam25Raj!
Unfortunately I'm not happy with this representation of the logo. In my mind, the 3 sections are meant to overlap in 3d, much like the [Power Apps](https://simpleicons.org/?q=power%20apps) icons. Could you try adding a gap between each section? Our historical guidance has been 0.5px outside the 'upper' shape of each section. Happy to give a bit of guidance if you're not sure - though I know from a cursory glance, this isn't an easy one to get looking tidy!

**Comment by Gautam25Raj** [comment]
> Thanks for the contribution @Gautam25Raj! Unfortunately I'm not happy with this representation of the logo. In my mind, the 3 sections are meant to overlap in 3d, much like the [Power Apps](https://simpleicons.org/?q=power%20apps) icons. Could you try adding a gap between each section? Our historical guidance has been 0.5px outside the 'upper' shape of each section. Happy to give a bit of guidance if you're not sure - though I know from a cursory glance, this isn't an easy one to get looking tidy!

Yes, I could try to do.

**Comment by PratyushJayachandran** [comment]
> Yes, I could try to do.

Hello @Gautam25Raj, just checking if you are still working on this one.

**Comment by Gautam25Raj** [comment]
> > Yes, I could try to do.
> 
> Hello @Gautam25Raj, just checking if you are still working on this one.
No @PratyushJayachandran, if you want you could try it.

**Comment by PeterShaggyNoble** [comment]
Closing due to #9896

Thanks for your efforts nonetheless, @Gautam25Raj

**Pull request closed without merging**
