### PR TITLE
Add Anycubic

### PR DESCRIPTION
**Pull request by adamrusted**
image

**Issue:** contributes toward #10464

**Similarweb rank:** [55,128](https://www.similarweb.com/website/anycubic.com/)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

SVG taken from page 2 of [this PDF](https://drive.google.com/file/d/1NRMp12tRvmWXrfAqgpwHvoSWEnU5_mZG/view) found at source.

### CODE REVIEW

**Comment by Mvlprem** [comment]
@adamrusted I think we should just use the cube as logo, that's what they are using on their social media platforms to represent their brand so we should be fine with just the cube. You can grab it from ` Anycubic Kobra 2 Neo ` manual.

**Review by Mvlprem — CHANGES_REQUESTED** [review]
@adamrusted I think we should just use the cube as logo, that's what they are using on their social media platforms to represent their brand so we should be fine with just the cube. You can grab it from ` Anycubic Kobra 2 Neo ` manual.

**Comment by Mvlprem** [comment]
@adamrusted I don't think we need to make any gaps at all. There are already some gaps in place, take a look at this [image](https://store.anycubic.com/cdn/shop/files/20190528162950_fc5f0cec-1646-4c39-9973-4529682d6112_x120@2x.png?v=1658114233) from their website footer.

I've made one from the source pdf feel free to use and let me know what you think.

```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Testing</title><path d="m6.761.533 10.706 10.301 6.494.63-8.471-7.449L6.761.533ZM6.591.6 0 12.465l7.354 10.978 9.939-12.509L6.591.6Zm10.892 10.397L7.525 23.468l8.649-3.14L24 11.579l-6.517-.582Z"/></svg>
```

**Comment by adamrusted** [comment]
> @adamrusted I don't think we need to make any gaps at all. There are already some gaps in place, take a look at this [image](https://store.anycubic.com/cdn/shop/files/20190528162950_fc5f0cec-1646-4c39-9973-4529682d6112_x120@2x.png?v=1658114233) from their website footer.

Yeah, I've made the gaps more pronounced because our primary use-case for icons is with shields.io, and the current gaps _do not_ display well there!

**Comment by adamrusted** [comment]
> @adamrusted I don't think we need to make any gaps at all. There are already some gaps in place, take a look at this [image](https://store.anycubic.com/cdn/shop/files/20190528162950_fc5f0cec-1646-4c39-9973-4529682d6112_x120@2x.png?v=1658114233) from their website footer.

Yeah, I've made the gaps more pronounced because our primary use-case for icons is with shields.io, and the current gaps _do not_ display well there! @Mvlprem

**Comment by Mvlprem** [comment]
@adamrusted Well in that case I'll request a review from someone else cause i don't know how to compare it with source I've never worked with these type of icons

**Comment by PeterShaggyNoble** [comment]
Has the source PDF been updated or have I been staring at icons so long today that I've gone blind? The only icon I can see on the referenced page, or in the whole PDF, is in the QR code, which is a PNG.

**Comment by Mvlprem** [comment]
> Has the source PDF been updated or have I been staring at icons so long today that I've gone blind? The only icon I can see on the referenced page, or in the whole PDF, is in the QR code, which is a PNG.

I guess you are going through the pdf mentioned in description, but that's not the source. I've asked rusty to use this  [pdf](https://drive.google.com/file/d/17Zqo5dXoWKUIKdZZPq3TvAJLDVpLVxuT/view) you can find the logo in page 1.

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
I'd agree with @Mvlprem here: if the source icon already includes gaps then we should run with those rather than increasing them.

**Comment by adamrusted** [comment]
_Do not_ like how this looks at our smaller sizes, but changes made @Mvlprem and @PeterShaggyNoble.

**Review by PeterShaggyNoble — APPROVED** [review]

**Pull request merged**
