### PR TITLE
Update guidelines for source URLs

### PR DESCRIPTION
**Pull request by ericcornelissen**
**Issue:** Following https://github.com/simple-icons/simple-icons/pull/2499#issuecomment-580798030

### Description

Updated the guidelines for the `source` URL,: slightly changing what we use them for, and providing more detailed guidelines for common sources.

This is more like draft, would appreciate feedback on the wording etc. 🙂

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
There are some files that aren't available on Wikimedia, only on WIkipedia ([this one](https://upload.wikimedia.org/wikipedia/en/8/83/Universal_Contactless_Card_Symbol.svg) I used for #2527, for exmaple) so I'd suggest including either the brand's or logo's Wikipedia page as an alternative source in those cases.

We should also list GitHub repos as a potential source in [this section](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#1-identify-official-logos-and-colors).

**Comment by ericcornelissen** [comment]
> There are some files that aren't available on Wikimedia, only on WIkipedia ([this one](https://upload.wikimedia.org/wikipedia/en/8/83/Universal_Contactless_Card_Symbol.svg) I used for #2527, for exmaple) so I'd suggest including either the brand's or logo's Wikipedia page as an alternative source in those cases.

Interesting 🤔 I updated the description for Wikipedia/Wikimedia, let me know what you think @PeterShaggyNoble 


> We should also list GitHub repos as a potential source in [this section](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#1-identify-official-logos-and-colors).

Good point, I will update that list as well 👍

**Comment by ericcornelissen** [comment]
> Just a minor tweak;
> 
> > For an SVG from Wikipedia/Wikimedia the source URL should link to the ~~page containing file information~~ **logo's page on the relevant site, and not the brand's Wikipedia page**

I changed it slightly to say "[...] logo **file's** page [...]" :+1:

**Comment by PeterShaggyNoble** [comment]
Even better 😀 This looks good to me now, Eric but, again, as it relates to our documentation, I'll leave it to someone else to throw another eye over it before merging.

**Comment by runxel** [comment]
One question (because I'm not sure if I got that right):

> In either case the commit hash should be part of the URL.

Can one just append the commit hash to the base url of a repo?
Does this then point to the repo being at this point of time of the repo?

**Comment by ericcornelissen** [comment]
> Does this then point to the repo being at this point of time of the repo?

That is correct and exactly why I want it. This prevents issues when e.g. the file is removed from the project later on.


> Can one just append the commit hash to the base url of a repo?

Not really, for GitHub it should be somewhere in the middle of the URL (replacing the branch name, to be exact). Unfortunately, as far as a I know, GitHub doesn't have an easy way of getting this kind of _permalink_ :confused:

Do you think it would be a good idea to add a step-by-step tutorial on how to get the URL we want @runxel?

**Comment by runxel** [comment]
> > Can one just append the commit hash to the base url of a repo?
> 
> Not really, for GitHub it should be somewhere in the middle of the URL (replacing the branch name, to be exact). Unfortunately, as far as a I know, GitHub doesn't have an easy way of getting this kind of _permalink_ 😕

Ach, that's what I thought!
(I was just confused for a moment thinking there might be something I've always missed until now on Github 😆)

> Do you think it would be a good idea to add a step-by-step tutorial on how to get the URL we want @runxel?

Yeah, that would be much appreciated, I'd say, @ericcornelissen!  👍

**Comment by ericcornelissen** [comment]
Updated the guidelines @runxel, turns out there is an "easy" way to get the commit hash in the URL, but it is hidden behind a keybinding... Pressing <kbd>y</kbd> on any(?) GitHub page will include the commit hash (as per [the docs](https://help.github.com/en/github/managing-files-in-a-repository/getting-permanent-links-to-files)) :upside_down_face: Glad I looked that up

**Comment by runxel** [comment]
Woah, that's interesting!
Cool you've found that!

I think this PR is good to go 😎

**Comment by PeterShaggyNoble** [comment]
😮 *Great* find, Eric - that's gonna save a bit of time in the future!

Looks like this is good to go now,

**Pull request merged**
