### PR TITLE
Add SonarLint icon (#1453)

### PR DESCRIPTION
**Pull request by phatbhoy67**
**Issue: #1453**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Manual vector of [official source .png](https://github.com/SonarSource/sonarlint-website/blob/gh-pages/resources/images/ico-sonarlint-400.png).

Hex value `#cc2026` is from the logo.

Built on GitPod, working as expected.

### CODE REVIEW

**Comment by birjolaxew** [comment]
Looks like they stylize their name as "SonarLint", while this PR uses "sonarlint".

Since this is a manual vectorization, I'll let another @simple-icons/maintainers merge this in. Regardless, it looks good to me other than the name.

**Comment by birjolaxew** [comment]
Pinging other @simple-icons/maintainers again for merging.

**Comment by phatbhoy67** [comment]
> Any reason the source URL was not updated?

Hey @ericcornelissen @birjolaxew, I completely missed that part sorry. 😿 

The repo (https://github.com/SonarSource/sonarlint-website/) has been archived (might have missed that before 😮) and as the favicon is available in the source of the website itself (https://www.sonarlint.org/favicon-152.png), should I leave it as it is or update it? 🤔

**Comment by birjolaxew** [comment]
I think that they might've archived it because they do not want issues and pull requests on it. I'd suspect that, should they ever update their brand, they might unarchive and update it. Since it also links to the website, I'd personally prefer the repo. Thoughts @simple-icons/maintainers?

**Comment by birjolaxew** [comment]
:+1: Thanks for updating it @phatbhoy67! No obvious good solution here, but what can you do ¯\\\_(ツ)_/¯

**Pull request merged**
