### PR TITLE
Add icon count to website & README

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
We could do with touting the fact that, come the next release, we'll have over 1000 icons in our library ([Wear OS was the 1000th](https://github.com/simple-icons/simple-icons/pull/2305#issuecomment-573322864)).

Do we want the count on the website to be live or not (assuming it's possible)? Personally, I always prefer the "over `X`" phrasing to the exact figure - dunno why that is!

### CODE REVIEW

**Comment by ericcornelissen** [comment]
I'm personally not a fan of saying "over a 1000 icons" rather than just "free icons", but that is just personal preference.

That said, if we decide to go ahead with this we might as well make it so the website programmatically uses the exact number of icons.

**Comment by PeterShaggyNoble** [comment]
> That said, if we decide to go ahead with this we might as well make it so the website programmatically uses the exact number of icons.

Can that be done in the templating, @ericcornelissen? If so, I'll leave that to you. If not then I'll knock together a quick, wee bit of JS to do it.

**Comment by ericcornelissen** [comment]
> Can that be done in the templating, @ericcornelissen? If so, I'll leave that to you. If not then I'll knock together a quick, wee bit of JS to do it.

That can be done with templating, yes, and we would ideally do so as then it would have to happen only once when GitHub puts together the page for GitHub pages (rather than with every page load).

I'll wait for further input before working on this 👍

**Comment by runxel** [comment]
Well I think that would be great!
I actually wondered how many icons we got now just yesterday. So yeah, would be neat! 🤷‍♂ 
:)

**Comment by PeterShaggyNoble** [comment]
@runxel, Tip: Github truncates lists of files to 1000 items so, now that we're over 1000 icons, you can see how many we have at https://github.com/simple-icons/simple-icons/tree/develop/icons - 1027 as of this comment.

**Comment by PeterShaggyNoble** [comment]
Abandoning this in favour of Eric's proposed implementation.

**Pull request closed without merging**
