### PR TITLE
Add Railway Icon

### PR DESCRIPTION
**Pull request by uiuxarghya**
railway

**Issue:** #5817
**Alexa rank:** 432,460
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Website: https://railway.app/
Hex Value: `#FFFFFF`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @uiuxarghya 👍🏻

The SVG looks spot-on to me. However, for the colour I think we should go with one of the purples. Not sure which, though, maybe the `#100f13` they use for the overall page background? What do you think?

**Comment by uiuxarghya** [comment]
> Thanks for the contribution, @uiuxarghya 👍🏻
> 
> The SVG looks spot-on to me. However, for the colour I think we should go with one of the purples. Not sure which, though, maybe the `#100f13` they use for the overall page background? What do you think?

The logo on their homepage and discord community are actually in `#ffffff` and now after checking their docs page and I found out that the logo and overall black elements on their docs page are in `#0b0d0e`.

**Review by adamrusted — APPROVED** [review]
This looks spot on to me, @uiuxarghya. While the website itself uses black and purple quite heavily, wherever I see the logo (apart from the favicon) the train itself is in white, so I'm happy to go with this. If another @simple-icons/maintainers would prefer the hex to be black - we can always update it at a later date. Great work! 💪

**Comment by ericcornelissen** [comment]
Given the docs page, which allows you to toggle between light mode and dark mode, I'd say going by the color of the logo is not reliable as changing the color mode just inverts the logo. On top of that, the preferred use of the color value is for the brand color, not the logo color.

I'd agree that either black or purple is the way to go for this one, and while I usually prefer going non-blacks, I think in this case black, specifically `#0b0d0e` from [the docs](https://docs.railway.app/), seems like the best option. What does everyone think about that?

Also, @uiuxarghya, there's really no need to keep merging `develop` into your branch unless there are conflicts. Once this is ready to merge one of the maintainers can merge `develop` in for you and than merge this into develop.

**Comment by uiuxarghya** [comment]
> Given the docs page, which allows you to toggle between light mode and dark mode, I'd say going by the color of the logo is not reliable as changing the color mode just inverts the logo. On top of that, the preferred use of the color value is for the brand color, not the logo color.
> 
> I'd agree that either black or purple is the way to go for this one, and while I usually prefer going non-blacks, I think in this case black, specifically `#0b0d0e` from [the docs](https://docs.railway.app/), seems like the best option. What does everyone think about that?
> 
> Also, @uiuxarghya, there's really no need to keep merging `develop` into your branch unless there are conflicts. Once this is ready to merge one of the maintainers can merge `develop` in for you and than merge this into develop.

Let us go with this color `#0b0d0e` as it is present mostly everywhere.

**Comment by adamrusted** [comment]
> Let us go with this color `#0b0d0e` as it is present mostly everywhere.

If you could update the hex @uiuxarghya, this can be merged straight in!

**Comment by uiuxarghya** [comment]
railway (1)

I have updated the hex to `#0b0d0e`.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @uiuxarghya 💪

**Comment by ericcornelissen** [comment]
Thanks for the contribution @uiuxarghya 🎉 

One small tip for other/feature contributions: there's no need to keep your Pull Request up-to-date with `develop` at all times, it's pretty uncommon something changes on `develop` that would render you contribution invalid, and it creates unnecessary notifications for the maintainers (and anyone else subscribed to the Pull Request). Once your Pull Request is approved a maintainer can simply merge `develop` into the Pull Request for you and merge once the build succeeds.

**Comment by uiuxarghya** [comment]
Okay I got it 😀

**Pull request merged**
