### PR TITLE
Added USPS

### LINKED ISSUE #3226: Request: USPS Icon
Name: USPS
Website: https://www.usps.com/
Official resources for icon and color:
Only information I could find was https://about.usps.com/doing-business/rights-permissions/logo-trademark-usage.htm.

### PR DESCRIPTION
**Pull request by adamrusted**
usps

**Issue:** Closes #3226
**Alexa rank:** [185](https://www.alexa.com/siteinfo/usps.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Built from SVG embedded in header of site.

### CODE REVIEW

**Comment by adamrusted** [comment]
Note - if we need to include the `r` mark, it'll look like this, using [this image](https://about.usps.com/root/global/images/usps_about_logo.png) as reference for spacing.
usps

**Comment by fbernhart** [comment]
I would say that probably we should include the (R) sign. Alone on https://www.usps.com they use it 8 times for different products. 😅  As well on all of their social media presence ([Facebook](https://www.facebook.com/USPS?rf=108501355848630), [Twitter](https://twitter.com/usps), [Pinterest](https://www.pinterest.de/uspsstamps/), [YouTube](https://www.youtube.com/user/uspstv/custom)) they use the logo together with the (R).

If you need another reference for spacing concerning the (R), probably their [Facebook profile picture](https://scontent-muc2-1.xx.fbcdn.net/v/t1.0-9/90011902_10158231700619810_8599436210709987328_n.png?_nc_cat=109&ccb=2&_nc_sid=85a577&_nc_ohc=o_JZJywind0AX_Uohjg&_nc_ht=scontent-muc2-1.xx&oh=d67c05b5faf6756a07e70a881373d938&oe=601C8B37) is the best way to go as it's pretty high resolution.

**Comment by adamrusted** [comment]
usps

@fbernhart rebuilt to include the ® in as close a fashion as their Facebook profile picture.
Inverted my path to include the outer box, as they seem to include that everywhere too.

**Comment by fbernhart** [comment]
Perfect! 📫 ✉️

**Pull request merged**
