### PR TITLE
Add Libraries.io icon

### LINKED ISSUE #4123: libraries.io
Name: libraries.io
Website: https://libraries.io/
Alexa rank: 46307
Official resources for icon and color:
  SVG: https://libraries.io/assets/logo-9a0c71ef3e238cad3e4ee8196e4b11f0d83c43435bb81602f6932bed992812ed.svg
  COLOR: #FFFFFF

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** Close #4123
**Alexa rank:** [~53k](https://www.alexa.com/siteinfo/libraries.io)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I took the logo from the header of https://libraries.io/
- I used Inskscape to scale (path is kinda funny, but looks intentional)
- I used https://jakearchibald.github.io/svgomg/ to optimize
- I took the `btn-primary` color found in their stylesheet, but I'm not sure it is the perfect fit!

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
The source SVG is a bit of a mess so I think we should redraw this one ourselves based on one of their [raster files](https://libraries.io/assets/mstile-310x310-3547800cb3aa250b9dcfa0d95ffa675c73580ece85c09edaca209657ad281a34.png). Alternatively, despite being Potraced, [this SVG](https://raw.githubusercontent.com/librariesio/libraries.io/main/public/safari-pinned-tab.svg) may give a better starting point.

**Comment by service-paradis** [comment]
Thanks @PeterShaggyNoble, I though it was intentional 😅 
Will take another loot at it soon!

**Comment by service-paradis** [comment]
Ouch, I tried to recreate it using https://raw.githubusercontent.com/librariesio/libraries.io/main/app/assets/images/logo.png
Unfortunately, I'm not the most talented one for this kind of thing 😅

**Comment by PeterShaggyNoble** [comment]
There are [some differences](https://user-images.githubusercontent.com/15157491/108503498-6470fd80-72ac-11eb-976c-4da32ac3c8ae.png), mainly in the rightmost book, between your new version (in red) and [this SVG](https://raw.githubusercontent.com/librariesio/libraries.io/main/public/safari-pinned-tab.svg), which, upon further review looks to be good enough for us to use; at most we'd just need to remove a couple of unnecessary points.

**Comment by service-paradis** [comment]
Gave it another try!
Really hard to do a good comparison since every image they have (header svg, pinned tab svg, raster) are all different 😅

**Comment by PeterShaggyNoble** [comment]
Given how bad _all_ versions of their logo are, @service-paradis, I think this is one occasion where we can allow some deviation from the source in our efforts to fix it up so I'm happy to run with this as it is now but we'll need approval from one of the other @simple-icons/maintainers too.

**Review by adamrusted — COMMENTED** [review]
Happy to go with this, as it almost perfectly matches the SVG linked by @PeterShaggyNoble. @service-paradis, before I merge this - would it be worth updating to that GitHub source for now? I'm hoping if they ever update their logo, we'll find a decent SVG in that folder!

**Comment by PeterShaggyNoble** [comment]
Updated the source; will merge once the checks pass. Thanks for you work on this one, @service-paradis.

**Pull request merged**
