### PR TITLE
Add XDA-Developers icon

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
XDA-Developers

**Issue:** #1931

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
They use the `xda` for their favicon as well as their app icons. Colour was taken from [website logo](https://forum.xda-cdn.com/images/2015/xda-logo_newcolors.svg).

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble thanks for taking this one on, the .svg is great. 👍 

I can't see anywhere the dash is used i.e. "XDA-Developers" other than in the site url, so I think it should just be "XDA Developers".

Can you update the title in the .svg file, the filename and the .json entry please.

**Comment by PeterShaggyNoble** [comment]
I was going by the `<title>` tag on the website but I see now that the hyphen isn't used anywhere else. Will update shortly.

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble thanks for the quick reply. 

Can you also update .svg file with `<title>XDA Developers</title>` (removing the "dash").

This will remove the linting error causing the check to fail. 🎉

**Comment by PeterShaggyNoble** [comment]
Ah-ha! That's what I was missing!

Updated. Thanks, @phatbhoy67.

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @PeterShaggyNoble appreciated 👍

**Pull request merged**
