### PR TITLE
Remove Livestream

### PR DESCRIPTION
**Pull request by fbernhart**
**Issue:** Contributes to #4590 
**Alexa rank:** [9,442](https://www.alexa.com/siteinfo/livestream.com)

### ~Checklist~
~- [x] I updated the JSON data in `_data/simple-icons.json`~
~- [x] I optimized the icon with SVGO or SVGOMG~
~- [x] The SVG `viewbox` is `0 0 24 24`~

### ~Description~
~- Seems like Livestream has been bought by vimeo back in 2017. See [their blog](https://livestream.com/blog/livestream-vimeo-acquisition) and [Wikipedia](https://en.wikipedia.org/wiki/Vimeo_Livestream#History)~
~- The new logo is a combination of the vimeo and livestream wordmark.~
~- SVG pulled from the header of https://livestream.com~
~- Changed source to https://livestream.com, as https://livestream.com/press doesn't exist anymore.~
~- Changed color to `#000000`. The SVG at source doesn't have a color, so black is probably the best choice.~

### Edit
This PR removes Livestream as the brand doesn't exist anymore. It's now called "Vimeo Livestream" and has a different logo. "Vimeo Livestream" is added in a different PR.

### CODE REVIEW

**Comment by fbernhart** [comment]
@simple-icons/maintainers I've been wondering if we should as well rename this one (which would be a breaking change). I have the impression that `Vimeo Livestream` would be a better fit than just `Livestream`.

Any opinions?

**Comment by ericcornelissen** [comment]
I agree @fbernhart, either

> Another option would be to actually just fix the collinear linter error of the old icon, creating a new icon called Vimeo Livestream and then removing Livestream with the next major release.

Or we update the icon under the current name and rename with the next release 👍

**Comment by PeterShaggyNoble** [comment]
I don't think this is the right way to go on either front. In the absence of a colour in the source icon (or brand guidelines where available), we should go with our best guess from the website. In this case I'd say it should be either the purple `#0a0a20` that features throughout the site and in their favicon on the homepage.

However, and more pressingly, I don't think we need to use the full wordmark here as they themselves use the Vimeo "V" in a few places, including in the favicon and in the website's header when you scale down to smaller sizes. Given that and, as we've yet to fully resolve #3270 & #3219, I'd hold off on doing anything for now as the solution may end up being to remove this completely.

> Or we update the icon under the current name and rename with the next release

If it's decided that we're going to allow brands that share an icon with another one then this would also be my preferred approach, too, to avoid duplication.

**Comment by ericcornelissen** [comment]
> If it's decided that we're going to allow brands that share an icon with another one then this would also be my preferred approach, too, to avoid duplication.

To me, the discussion here is a separate from #3270. There we consider icons that will be part of the collection "**permanently**" using the same icon. Here, we consider the option of providing the icon of a renamed brand in two ways in one version so as to make upgrading to the next major version potentially easier. That does not mean I think we should necessarily provide both icons, I just want to point out that these are two different scenarios.

Now, from a user's perspective, I would say it is ideal to have both "Livestream" and "Vimeo Livestream" available in v4, and remove "Livestream" when v5 comes around. This is because 1) it gives users of "Livestream" a larger window of time to update and 2) it allows users looking for "Vimeo Livestream" to find it already in v4. (This is arguably not as big a deal for "Vimeo Livestream" as it still contains the old name, but e.g. the rename from [Postwoman to Hopscotch](https://github.com/simple-icons/simple-icons/pull/4122) would be more relevant to this argument.)

---

<sup>I won't respond to the rest of the discussion, at least for now</sup>

**Comment by PeterShaggyNoble** [comment]
To clarify: my reference to #3270 was in direct relation to my suggestion that their icon is now just the Vimeo "V".

**Comment by adamrusted** [comment]
> I would say it is ideal to have both "Livestream" and "Vimeo Livestream" available in v4, and remove "Livestream" when v5 comes around. This is because 1) it gives users of "Livestream" a larger window of time to update and 2) it allows users looking for "Vimeo Livestream" to find it already in v4.

I agree with @ericcornelissen's comments above. I'd prefer to have ***both*** Livestream and Vimeo Livestream available in v4 *(even if it's a duplication of this newer icon)* to update the brand, and give any users of `livestream.svg` time to swap over to the newer icon, before the deletion of `livestream.svg` in v5.0.0.

**Comment by fbernhart** [comment]
Ok 👍🏼  Let me make this one the "Remove Livestream" PR, that will remove `livestream.svg` with the next major release.

I'll as well create a new PR with "Add Vimeo Livestream".

**Review by PeterShaggyNoble — APPROVED** [review]
Looks good to me 👍🏻 Once the conflicts are resolved then this can be merged straight in.

**Pull request merged**
