### PR TITLE
Update 'C' icons.

### PR DESCRIPTION
**Pull request by adamrusted**
This PR is for the brands beginning with C in #5251.

### Additions
- Updated Celery source to GitHub repo version of icon.
- Added License info to Celery.
- Added License info to CocoaPods.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
As Celery's license file mentions only the software without explicit mention of the logo or artwork, I don't think we should add it. Better not to include the license than the wrong one.

The `url` for the CocoaPods license can be removed; it only needs to be included when the `type`  is "custom".

**Review by PeterShaggyNoble — APPROVED** [review]

**Comment by PeterShaggyNoble** [comment]
_Just_ before merging, spotted that the CocoaPods license ID, should actually be [CC-BY-NC-4.0](https://spdx.org/licenses/CC-BY-NC-4.0.html). Sorry for missing it earlier.

**Comment by adamrusted** [comment]
Linter is failing because CC-BY-NC-4.0 isn't on our jsonschema.
Only BY-NC options are:
```
"CC-BY-NC-ND-1.0",
"CC-BY-NC-ND-2.0",
"CC-BY-NC-ND-2.5",
"CC-BY-NC-ND-3.0",
"CC-BY-NC-ND-4.0",
"CC-BY-NC-SA-1.0",
"CC-BY-NC-SA-2.0",
"CC-BY-NC-SA-2.5",
"CC-BY-NC-SA-3.0",
"CC-BY-NC-SA-4.0",
```

The info page they link to in their README says: 

> You are free to:
Share — copy and redistribute the material in any medium or format
Adapt — remix, transform, and build upon the material

So I took that as the SA-4.0 variant.

**Comment by PeterShaggyNoble** [comment]
I think `LICENSE.md` should supersede anything mentioned in their README in cases like this so let's add those "CC-BY-NC-x.0" types to our linter while we're at it.

**Comment by adamrusted** [comment]
Cool, should all be added to the linter.

**Review by PeterShaggyNoble — APPROVED** [review]

**Pull request merged**
