### PR TITLE
Add cohost icon

### LINKED ISSUE #8010: Cohost
### Brand Name

Cohost

### Website

https://cohost.org/

### Popularity Metric

Similarweb rank is 200,691: https://www.similarweb.com/website/cohost.org/

This is one of the websites Twitter users are fleeing towards, so its popularity might grow very quickly.

### Official Resources for Icon and Color

Account picture for the staff account: https://cohost.org/staff

https://staging.cohostcdn.org/avatar/3-3e0584c7-957a-4950-81ba-fb5a25d05e59-profile.png

Brand color is `#83254f`

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
cohost

**Issue:** closes #8010
**Popularity metric:** Similarweb rank [27703](https://www.similarweb.com/website/cohost.org)

### Checklist
- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon & colour from [source](https://cohost.org) header. Frustratingly few points could be removed from the source.

### CODE REVIEW

**Comment by service-paradis** [comment]
According to [dddd](https://cohost.org/rc/content/tos), I'm wondering if we can add this one without permission:

> Trademarks. ASSC's registered and unregistered trademarks and trade dress, including names, logos, taglines, trade dress, and other trademarks, may not be copied, imitated, or used, whether in whole, partial or modified form, without the prior written permission of ASSC. You may not use any meta tags or any other hidden text utilizing an ASSC name, trademark, or product name without ASSC's prior written permission. Third-party trademarks and service marks used on the Services are the property of their respective owners, and we use them with their consent. ASSC and the other licensors of the marks on the Site reserve all rights with respect to all Contents and all intellectual property.

**Comment by service-paradis** [comment]
Maybe we can open a support ticket at https://help.antisoftware.club/support/home ?

**Comment by adamrusted** [comment]
Could you try reaching out to them, @PeterShaggyNoble?

**Comment by adamrusted** [comment]
Closing, as we require permission to include this. If you reach out to the brand @PeterShaggyNoble - ping here and we can re-open the PR.

**Comment by RenegadeScooter** [comment]
I decided to open a ticket myself. Good news: **you got the green light**!
https://help.antisoftware.club/support/tickets/20372 (warning: ticket page requires login to view)
image

**Comment by adamrusted** [comment]
Will re-open this PR then, if another maintainer wishes to pick up where Peter left off!
Thanks @RenegadeScooter for reaching out!

**Review by mondeja — APPROVED** [review]
Looks perfect to me. Thanks all for the great work with this one! 🥇

**Pull request merged**
