### PR TITLE
Add Celery icon (#1332)

### PR DESCRIPTION
**Pull request by phatbhoy67**
**Issue: #1332**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO ~or SVGOMG~
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

~Manual vector interpretation of icon from [official project banner .png](https://raw.githubusercontent.com/celery/celery/master/docs/images/celery-banner.png) available from [GitHub repo](https://github.com/celery/celery).~

~Hex value `#ddf4a3` is picked from the "C" in [official .png](https://raw.githubusercontent.com/celery/celery/master/docs/images/celery-banner.png) the lighter of the three greens used in the logo and the closest to the colour of celery IRL.~

~Built on GitPod, working as expected.~

Manual vector of [official .png logo](http://www.celeryproject.org/static/img/splash.jpg).

Hex value `#37814a` used on [website](http://www.celeryproject.org/)

Possible alternatives: Logo is green gradient, picked light and dark points `#c4e490` `#618f3a`, `#93BA65` is [calculated midpoint](https://meyerweb.com/eric/tools/color-blend/#C4E490:618F3A:1:hex).

Hex value chosen `#37814a`.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I missed the original conversation from #1332 but, as it's what they use in their website, I think we should use the boxed `C`. Should we reach out to @celery for clarification & confirmation?

**Comment by birjolaxew** [comment]
I agree, the boxed C seems like the most relevant logo in this case.

**Comment by phatbhoy67** [comment]
I think we tried reaching out to @celery previously. The GitHub repo for the project and the project itself use the newer updated logo version.  One of the most active maintainers over there is @auvipy maybe he can swing by and give us his opinion and have a look at #1332 ? 😃

**Comment by auvipy** [comment]
I woulddvote for the green one

**Comment by runxel** [comment]
> I woulddvote for the green one

Hey @auvipy! Thanks for dropping in.
Could you elaborate? "The green one" is kidna under-descriptive (since both are green...)

To be specific: Would you rather like the stylized celery from the github repo or the boxed `C` from the website as a logo?
Thanks again! ✨

**Comment by auvipy** [comment]
this one https://www.facebook.com/celeryproject/photos/a.1261662700512051/1261675943844060/?type=1&theater

**Comment by runxel** [comment]
Since there are no complaints I gladly merge this one in.
Thanks to everybody for contributing! 🌮

**Pull request merged**
