### PR TITLE
Add Major League Hacking

### LINKED ISSUE #4259: Request: Major League Hacking(MLH) Icon
**Name:** Major League Hacking
**Website:** https://mlh.io/
**Alexa rank:** 81,400
  

**Official resources for icon and color:** https://mlh.io/

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Major League Hacking

**Issue:** Closes #4259
**Alexa rank:** [~91k](https://www.alexa.com/siteinfo/mlh.io)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon from [this SVG](https://static.mlh.io/brand-assets/logo/official/mlh-logo-black.svg), colour from page 15 of [this PDF](https://s3.amazonaws.com/static.mlh.io/docs/mlh-style-guide-v2.pdf) - I just went for the first one as they don't specify which is the primary colour, open to suggestion for an alternative pick.

The main question that we need to answer is whether or not we should include the wordmark. Although they don't explicitly state in their guidelines that it can't be removed and even provide a few examples without it, those examples seem to have specific use cases and they seem to be pretty consistent in its inclusion out side of them.

### CODE REVIEW

**Comment by hasthamalp** [comment]
color is not matching

**Comment by PeterShaggyNoble** [comment]
Which of the colours from the PDF would you suggest, @hasthamalp?

**Comment by hasthamalp** [comment]
> color is not matching
> 

follow this color

**Comment by adityaoberai** [comment]
Here are the official brand guidelines: mlh.io/brand-guidelines

**Comment by adamrusted** [comment]
@PeterShaggyNoble we may be better to use the `soft red` listed in the Style Guide `#C53C02`, as that features _more_ within the logo than the dark red above.

**Comment by PeterShaggyNoble** [comment]
Done, on both counts, @adamrusted. Although, looking at their website again, I wonder if one of the blues might not be the better choice? Although they seem to use all 6 colours quite extensively, the blues stand out most to me

**Comment by adamrusted** [comment]
@PeterShaggyNoble I think any of the 3 lighter colours would suit, given their mixed use [throughout graphics](https://news.mlh.io/wp-content/uploads/2020/12/2020-LHD-build-for-social_ohq-1-1024x539.png) as well as the logo. I only went for red, as that's the first colour in the logo - and most frequently used in the image I linked above. I think any of the 3 would be appropriate, so I'm happy for someone with a bit more knowledge on MLH to say otherwise!

**Comment by adityaoberai** [comment]
The red in the image was for a specific event that the organization ran in January @adamrusted 

What I will recommend is that apart from the grayscale versions of the logo, if implementing the multicolour logo is not possible, then the blue colour is a good option to go with too.

**Comment by adamrusted** [comment]
> What I will recommend is that apart from the grayscale versions of the logo, if implementing the multicolour logo is not possible, then the blue colour is a good option to go with too.

Looking at this again, I agree with @adityaoberai - looks like branding for events is mostly blue (see t-shirts and roller banners in event photos). Guess the best colour would be the lighter blue, which is `#265A8f`.

**Comment by PeterShaggyNoble** [comment]
Thanks, all. Colour updated.

**Review by adamrusted — APPROVED** [review]
Looks good to me - thanks @PeterShaggyNoble for your work on this, and @adityaoberai for your insight regarding which colour to use!

**Comment by varghesejose2020** [comment]
Thank you

**Comment by varghesejose2020** [comment]
Great work @PeterShaggyNoble @adityaoberai @adamrusted

**Pull request merged**
