### PR TITLE
Add Axios icon

### PR DESCRIPTION
**Pull request by SimonGolms**
axios (1)

**Issue:** #3821 
**Alexa rank:** 315,678 https://www.alexa.com/siteinfo/axios-http.com
**Github stars:** 85.2k https://github.com/axios/axios

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- I used Sketch to extracted the arrows from this [raw](https://github.com/axios/axios-docs/blob/ba35d67160f94419c1b0292831cd1a4b378adb42/assets/logo.svg) svg file, as this logo is also used as favicon and GitHub profiles.
- I picked the color `#5A29E4` directly from the mentioned file.
- I used SVGOMG with precision of 3 for further optimization

Sorry for maybe taking over the issue ticket.... I am just checking the tech stack of some of my projects and adding missing logos to be able to use them later in the shields.io badges 🙃

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one on, @SimonGolms 👍🏻

Would you mind having another look at it though, as I am seeing some differences throughout - such as [this one in the top left](https://user-images.githubusercontent.com/15157491/123287345-95856700-d506-11eb-8da2-14c3ec2396ea.png) - between the PR version (in red) and the source?

**Comment by SimonGolms** [comment]
axios

You maintainers are just really great at quality control! I picked a precision of 5 on SVGOMG now, which should fix the deviation.

**Comment by dirien** [comment]
@sachinrajam, how should we proceed with this PR?

**Comment by sachinraja** [comment]
We can merge it @dirien

**Comment by dirien** [comment]
Hi @SimonGolms, we just need to get the Lint issue sorted! Then we are ready to merge! 😄

**Comment by SimonGolms** [comment]
Thanks for pinging! The linter should be happy now 😊

**Pull request merged**
