### PR TITLE
Remove Cocos

### PR DESCRIPTION
**Pull request by adamrusted**
See #2127, #4340 
Remove Cocos logo following discussion with Marketing Director.
Designer does not want logo altered in any way, including removing / changing colors - therefore we're unable to use the monochrome version generated.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Just to clarify: from Luke's comments it seems to me that a monochrome treatment is allowed but _only_ in white - both our existing and new websites would violate that as both display it in black.

**Comment by adamrusted** [comment]
@PeterShaggyNoble yep - and because they don't have documented brand guidelines online, we're unable to advise when #2846 is resolved.

**Comment by PeterShaggyNoble** [comment]
If that's our only concern then we could, instead, link directly to Luke's comment regarding white being the only acceptable colour.

**Comment by adamrusted** [comment]
> If that's our only concern then we could, instead, link directly to Luke's comment regarding white being the only acceptable colour.

Could do, though that'd require the 'brand guidelines' Issue / PR to be resolved first.

**Comment by PeterShaggyNoble** [comment]
Let's ping, @CocosLuke for final say on this one before removing it. [Our new website](https://simple-icons.github.io/simple-icons-website/?q=cocos)'s dark theme would display your icon in white although it would be black in the light theme. But, if we were to link to [your comment](https://github.com/simple-icons/simple-icons/pull/4340#issuecomment-752365377) stating that the icon can only be used in white, would you be happy for us to keep it. Obviously, even with that link in place, it would be impossible for us to actually _enforce_ what colour our users display your icon in.

If either of those things are an issue for you then we will, of course, respect your wishes and this PR can be merged straight in once the conflicts are resolved.

**Comment by PeterShaggyNoble** [comment]
Closing this out due to us now [having full approval](https://github.com/simple-icons/simple-icons/pull/4340#issuecomment-847505387).

**Pull request closed without merging**
