### PR TITLE
Add MIT License Icon #3541

### PR DESCRIPTION
**Pull request by jack-mil**
**Issue:** Addresses #3541

Adds the MIT (License and University) Icon

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Wikipedia lists the icon as public domain, so I have omitted the "license" field in `simple-icons.json`.
Aliases are listed:
- MIT License
- Massachusetts Institute of Technology

canvas

### CODE REVIEW

**Review by sisp — COMMENTED** [review]
Thanks for your contribution, @jack-mil! :pray:

Unfortunately, we don't support university icons according to the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/9b046563d4e73eca90e457d8cfed51a5620bfdea/CONTRIBUTING.md#requesting-an-icon):

> * Doesn't fall into one of the following categories:
>   ...
>   * Universities or other educational institutions

That said, I believe the MIT _license_ icon is not the same as the MIT _university_ icon. The way I see it, [Wikipedia article on the MIT license](https://en.wikipedia.org/wiki/MIT_License) is a bit misleading as I believe the logo refers to the _publisher_ of the MIT license which is the university.

@simple-icons/icon-review What do you think?

**Comment by sisp** [comment]
The only alternative I see is to use the [favicon of mit-license.org](https://github.com/remy/mit-license/blob/633af97b132ec0602f0410a9f449854f12473348/favicon.ico), although I'm not sure whether that's an _official_ icon. And it's not available in SVG format.

**Comment by sachinraja** [comment]
Yeah I don't think we can use that because it's unofficial.

**Comment by sisp** [comment]
I'm closing this PR because the MIT license does not seem to have an official icon other than the MIT university icon which we can't use according to our guidelines.

**Comment by platform-kit** [comment]
The MIT License is something that is usually represented with scales. (See: the license section on this very repo: https://github.com/simple-icons/simple-icons)

It does not need to be officially affiliated with MIT or any university or organiztion. We just need a way to indicate the idea of a license. Here is the (MIT Licensed) SVG code for the legal scales from [Tailwind's Hero Icons](https://heroicons.com/) library - wouldn't this suffice?

<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"> <path stroke-linecap="round" stroke-linejoin="round" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" /> </svg>

Consider this a pull request.

**Comment by LitoMore** [comment]
@platform-kit I don't think the icon you provided is a specific one for MIT License.

I found a similar icon on GitHub for all licenses.

**Comment by platform-kit** [comment]
@LitoMore that is correct, that's what I was trying to say. The MIT license and other code licenses are not depicted with the MIT school logo but with a generic legal scales icon, even here on Github.

**Pull request closed without merging**
