### PR TITLE
Add Google AdSense

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Google AdSense

**Issue:** [MDI#4614](https://github.com/Templarian/MaterialDesign/issues/4614)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Had to take some artistic license with the cutout again.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble what did you base your interpretation on, I can't see that icon on the source referenced?

Did find a version here (https://upload.wikimedia.org/wikipedia/commons/c/cd/AdSense_Logo.svg)

**Comment by PeterShaggyNoble** [comment]
Ah, yes, the logo is only visible in the header when signed in to AdSense, otherwise it's just the wordmark. It _is_ also displayed while the page loads if you click "Sign In" or "Get Started" but that isn't immediately obvious. Will update the source URL to file on Commons momentarily.

**Comment by ericcornelissen** [comment]
Hmm, seems [GitHub has some problems rendering the SVG](https://github.com/simple-icons/simple-icons/diffs/1?base_sha=7f54b1dae91598e7c420c8225293130c49b8009b&commentable=true&head_user=PeterShaggyNoble&pull_number=2597&sha1=7f54b1dae91598e7c420c8225293130c49b8009b&sha2=d728f8b5e405fedc109d4989679b3d0eb116f058&short_path=5097e75) :confused: However, if I copy the SVG source into a file and load it in the browser everything works just fine. I don't have time to investigate this right now :sweat_smile:  Any idea what might be the problem @PeterShaggyNoble? Do you experience the same? If not, I'm fine with merging this as is :+1:

**Comment by PeterShaggyNoble** [comment]
Definitely something up there, @ericcornelissen - even going direct to [the file in my branch](https://github.com/PeterShaggyNoble/simple-icons/blob/googleadsense/icons/googleadsense.svg). The inability to retrieve the contributors is a new one on me, too.

Going to recreate it from source in a few minutes, see if that helps.

**Comment by PeterShaggyNoble** [comment]
Nope, [that solved nothing](https://github.com/PeterShaggyNoble/simple-icons/blob/1674c4cfca9b1107d5508ee9d3459c98445b391c/icons/googleadsense.svg). No clue what's happening here 🤷‍♂ Any of the other @simple-icons/maintainers have any ideas?

**Comment by ericcornelissen** [comment]
I did some further testing (push the same file in a different folder with a different name, same folder different name, other folder same name, see [here](https://github.com/ericcornelissen/simple-icons/tree/bug-demo)) and my conclusion: GitHub doesn't like the filename :rofl:

In fact, [this branch named `google-adsense-demo`](https://github.com/ericcornelissen/simple-icons/tree/google-adsense-demo) has problems on the repo level :confused: 

I will merge this as is. Thanks for the work @PeterShaggyNoble :+1:

**Comment by PeterShaggyNoble** [comment]
A-ha! It's not GitHub that doesn't like the filename, it's ad-blockers - I disabled mine and it loaded fine. Same problem with [Google Ads](https://github.com/simple-icons/simple-icons/blob/develop/icons/googleads.svg).

**Comment by ericcornelissen** [comment]
> A-ha! It's not GitHub that doesn't like the filename, it's ad-blockers - I disabled mine and it loaded fine. Same problem with Google Ads.

Ow, that makes much more sense! :rofl:

**Pull request merged**
