### PR TITLE
Request: dwm Icon

### LINKED ISSUE #4883: Add Icon for Suckless (and possibly dwm)
**Brand Name:** Suckless
**Website:** https://suckless.org
**Alexa rank:** 412,962

## Official resources for icon and color:
* Icon: https://suckless.org/logo.svg and/or https://dwm.suckless.org/dwm.svg
* Colors:
  * [](https://suckless.org/pub/style.css)
  * [](https://git.suckless.org/dwm/file/config.def.h.html#l10)
  * [](https://git.suckless.org/dwm/file/config.def.h.html#l11)
  * [#bbbbbb](https://git.suckless.org/dwm/file/config.def.h.html#l12)
  * [#eeeeee](https://git.suckless.org/dwm/file/config.def.h.html#l13)
  * [](https://git.suckless.org/dwm/file/config.def.h.html#l14)

### PR DESCRIPTION
**Pull request by yuri-norwood**
## Details
preview

**Issue:** Closes #4883 - Add Icon for Suckless (and possibly dwm)
**Alexa rank:** [412,962](https://www.alexa.com/siteinfo/dwm.suckless.org)

**Why did you pick the hex value?**
The suckless tools all have a very consistent aesthetic, based on the 6 colours listed in my issue, however, the website and it's logo used `#069` (nice) and since most people customize the colours of the tools, this seems to be the best fitting. Both in terms of recognizability, and brand consistency.

**Did you manually vectorize the logo?**
Yes, I manually wrote the `path="..."` to get it to fit 24x24.

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

**Edit:** Updated colour in preview.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @yuri-norwood.

However, before we can get to reviewing it, we'll first need to assess whether dwm is popular enough for inclusion; we can't go by Alexa rank as that's for suckless and it doesn't look like they have a GitHub repo for us to check the stars so do you have another suggestion for a metric we can use to determine its popularity?

**Comment by yuri-norwood** [comment]
The Alexa rating link *is* for `dwm`, Alex just lumps them in together.

The source code is stored and developed in a private repo on the [`dwm`](https://git.suckless.org/dwm/) site, but the popularity can be seen from the wide spread use of `dwm` configs on [GitHub](https://github.com/search?q=dwm).

Also, as I've mentioned in my issue, AwesomeWM is already included in Simple Icons, and since AwesomeWM is a [fork](https://web.archive.org/web/20090406012657/http://article.gmane.org/gmane.comp.window-managers.dwm/3285/match=awesome) of `dwm`, it would make sense to include the original.

**Comment by yuri-norwood** [comment]
Just a note on the Awesome WM comparison, [slant.co](https://www.slant.co/versus/1288/1289/~awesome_vs_dwm) (a website and provides comparative rankings of equivalent services) ranks `dwm` third best window manager while Awesome is ranked at fifth, so this isn't a case of an old project being replaced by it's fork. `dwm` is still very actively maintained and has a loyal (and elitist) user base.

Note: Alex ranks slant.co at [8,095](https://www.alexa.com/siteinfo/slant.co)

**Comment by yuri-norwood** [comment]
Hi @PeterShaggyNoble,

I've done some digging into alternatives to the Alexa rating, please see my findings below.

The problem with the Alexa ranking, is that the `dwm` site is a subdomain of the main suckless site, so https://www.alexa.com/siteinfo/dwm.suckless.org redirects to https://www.alexa.com/siteinfo/suckless.org.

I have been able to get some long term data on `dwm` via Google Trends as an alternative to gauge the popularity. Below are some screenshots of the past ~16 year popularity of the `dwm` search term on Google.
image
image

This shows that the search terms are indeed for `dwm` as a window manager and not for some unrelated DWM acronym, as well as the international spread of the interest, (which would make sense, as many of the `dwm` developers are German).

For further comparison, I've used the Google Trends comparison feature to compare `dwm` popularity to the aforementioned [awesomeWM](https://github.com/simple-icons/simple-icons/blob/develop/icons/awesomewm.svg), [i3](https://i3wm.org/), and the general Tiling Window Manager topic. This quite clearly shows that `dwm` (in blue) holds a clear lead over the other window managers, (except for a brief period when `i3` over took it a few years ago), and much more popular that the search topic for Tiling Window Managers in general.
image

In the interests of transparency, I've included the global spread of each of the search terms and the specific phrases to again show that the terms are indeed referring to Tiling Window Managers on Linux/UNIX operating systems.
image
image
image
image
image

### NOTE
* `i3` is another popular titling window manager that has both influenced and been influenced by `dwm`.
* Tiling Window Managers are the type of application that both `dwm` and `awesomeWM` belong to, they are a subcategory of Window Managers, i.e. the UI programs used by an Operating System.

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
Many thanks for the detailed info, @yuri-norwood 👍🏻 Based on it performance vs. AwesomWM in particular, I'm happy enough that this is popular enough for inclusion.

Couple of changes before we can merge it in though:
1. Your SVG (in red below) appears to have become vertically stretched compared to the original.
2. Could you update the source to just https://dwm.suckless.org/?

**Comment by yuri-norwood** [comment]
* [ ] Change source to `dwm` home page
* [ ] Shave two units vertically off stroke of `d`
* [ ] Re-centre logo up by two units

**Review by PeterShaggyNoble — APPROVED** [review]
Looks perfect to me now, @yuri-norwood, thanks for the contribution.

**Comment by yuri-norwood** [comment]
Thanks again, glad to contribute :)

**Pull request merged**
