### PR TITLE
Add Recoil icon

### LINKED ISSUE #5498: Recoil
**Brand Name:** Recoil
**Website:** https://recoiljs.org/
**Alexa rank:** 190,141
**GitHub stars:** 12.6k
  

**Official resources for icon and color:** [official svg logo](https://github.com/facebookexperimental/Recoil/blob/c1a899e3e7fa8fc0304f9237f64a208480086bc2/logo/SVG/logo.svg) &  #007af4 
  

I'm on it.

### PR DESCRIPTION
**Pull request by wwwescape**
recoil

**Issue:** Closes #5498
**Alexa rank:** 190,141
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I used the SVG from the header of [recoiljs.org](https://recoiljs.org/)
- I used Inkscape to remove the text, scale and adjust
- I used https://jakearchibald.github.io/svgomg/ to optimize

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @wwwescape 👍🏻

I am, however, seeing [a very slight difference](https://user-images.githubusercontent.com/15157491/123408567-0b401000-d5a5-11eb-8960-0bb31db67995.png) down the right edge of the top circle between your version (in red) and [the logo](https://recoiljs.org/img/logo.svg) in the website's header. This may simply, but not necessarily, be down to needing to set the precision a little higher when optimising. Could you have another look at that, please?

Also, assuming you grabbed the colour from the background of the header, I'm getting `#3578e5` from the website stylesheet.

**Comment by wwwescape** [comment]
Sure @PeterShaggyNoble. I'll take another look at it over the weekend.

**Comment by wwwescape** [comment]
@PeterShaggyNoble Done.

**Comment by saseungmin** [comment]
When will this PR merge?

**Review by adamrusted — APPROVED** [review]
This LGTM! Thanks @wwwescape! 🎉

**Pull request merged**
