### PR TITLE
Correct Craft CMS icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** #3169
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- I took the original logo from https://craftcms.com/brand-resources since the current icon looks wrong.
- I used Inkscape to fix size and center
- I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by fbernhart — CHANGES_REQUESTED** [review]
I can see some slight differences between your version (black) and the source (red). Can you double check @service-paradis?

image


I've used `logo-craft-cms.svg` from the "Download logo files" button on [their website](https://craftcms.com/brand-resources) to compare it.

**Comment by service-paradis** [comment]
Thank you @fbernhart for the review. Looks like a precision of 3 is not enough to make it works. I think it looks better now :)

**Comment by fbernhart** [comment]
@service-paradis Hmmm ... I guess we're using different sources? 🤔 

Because I'm still seeing the same differences:
image

Which file did you use as source? The SVG in the header?

I've used https://craftcms.com/brand-resources --> "Download logo files" button and then the `logo-craft-cms.svg` file.

And after resizing/centering/optimizing (precision = 3) I'm getting this path, which still perfectly matches with the source and passes the linter.

```
M21.474 0H2.526A2.516 2.516 0 0 0 0 2.526v18.948A2.516 2.516 0 0 0 2.526 24h18.948A2.534 2.534 0 0 0 24 21.474V2.526A2.516 2.516 0 0 0 21.474 0m-9.516 14.625c.786 0 1.628-.31 2.442-1.039l1.123 1.291c-1.18.955-2.527 1.488-3.874 1.488-2.667 0-4.35-1.769-3.958-4.267.393-2.498 2.667-4.266 5.334-4.266 1.29 0 2.498.505 3.34 1.431l-1.572 1.291c-.45-.59-1.207-.982-2.05-.982-1.6 0-2.834 1.039-3.087 2.526-.224 1.488.674 2.527 2.302 2.527
```

**Comment by service-paradis** [comment]
Well, took this one for my last try... Dont know what was going on 😅 
I took your path, thank you for your help 😄

**Comment by adamrusted** [comment]
> Well, took this one for my last try... Dont know what was going on 😅
> I took your path, thank you for your help 😄

Just built from source myself, matches new path perfectly 🎉

**Comment by adamrusted** [comment]
> Well, took this one for my last try... Dont know what was going on 😅
> I took your path, thank you for your help 😄

Just built from source myself, matches new path perfectly 🎉

**Review by adamrusted — APPROVED** [review]
> Well, took this one for my last try... Dont know what was going on 😅
> I took your path, thank you for your help 😄

Just built from source myself, matches new path perfectly 🎉

**Pull request merged**
