### PR TITLE
Add Mercury Icon

### LINKED ISSUE #11242: Request: Mercury
### Brand Name

Mercury

### Website

https://mercury.com/

### Popularity Metric

The Similarweb ranking is 19,541: https://www.similarweb.com/website/mercury.com/

### Official Resources for Icon and Color

SVG: Right click on logo on main page, can download brand guidelines and logo as an svg
Color: `#272735`

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by jrhaberland**
mercury

**Issue:** closes #11242

**Popularity metric:**
The similarweb ranking is 19,541: https://www.similarweb.com/website/mercury.com/

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
Chose color of `#272735` because it is the color of the logo on the main site.

### CODE REVIEW

**Comment by uncenter** [comment]
From https://mercury.com/legal/terms:

> The Services and all materials therein or transferred thereby, including, without limitation, software, images, text, graphics, illustrations, logos, patents, trademarks, service marks, copyrights, photographs, audio, videos, music, and User Content belonging to other Users (the "Mercury IP"), and all Intellectual Property Rights related thereto, are the exclusive property of Mercury and its licensors. Except as explicitly provided herein, nothing in this Agreement shall be deemed to create a license in or under any such Intellectual Property Rights, and you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works from any Mercury IP. Use of the Mercury IP for any purpose not expressly permitted by this Agreement is strictly prohibited.

From what I can tell this means we cannot add this icon without explicit permission from Mercury. @jrhaberland would you be willing to [reach out and request permission](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission)?

**Comment by jrhaberland** [comment]
Just sent them an email

**Comment by jrhaberland** [comment]
Update: They forwarded my email to the proper team, so I should heard back from them pretty soon

image

**Comment by uncenter** [comment]
Would you be able to follow up on that response email and see if we can get a new response from the right department?

**Comment by jrhaberland** [comment]
I sent a follow up email

**Comment by uncenter** [comment]
Closing this as we have not been able to get permission for inclusion from them. Feel free to comment on this if there is a response indicating permission and we can reopen.

**Pull request closed without merging**
