### PR TITLE
Add PM2

### LINKED ISSUE #4975: Request: PM2
**Brand Name:** PM2
**Website:** https://pm2.keymetrics.io
**Alexa rank:** 38,783
**GitHub ⭐:**  [34,2k](https://github.com/Unitech/pm2)

**Official resources for icon and color:**

**Color:** `#6901DF`

### PR DESCRIPTION
**Pull request by AlexZeDim**
pm2

**Issue:** Closes #4975
**Alexa rank:** 38,783

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
 
 - I have manually vectorized the logo, according to the guideline and picked color values from the site's background, which is relevant to the pm2 logo from GitHub.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @AlexZeDim and thanks for taking this one on 👍🏻

Bit confused as to the branding here, though, as the only place I see the version in the PR in use is in their website header - everywhere else, including the screenshot on [their website](https://pm2.io/), it's a hamburger style icon and a light blue colour. Would I be correct in saying that they are in the process of rebranding?

**Comment by AlexZeDim** [comment]
As far as I know and I understand it, there is an actual difference between the classic PM2 module logo, which you are seeing right now, in this PR, the website (but not favicon), [npmjs](https://www.npmjs.com/package/pm2), and [in the Github repo, since the 2.0 version](https://github.com/Unitech/pm2/tree/2.x). This logo is quite old and has a long time history.

And the PM2+ (plus) and pm2.io service have (another) icon, which as you mentioned, a hamburger menu style. (PM2+ isn't the updated version of PM2, it's extended metrics and the website app, not the process manager itself). This logo you may find in the favicon of the site, [on the login page for PM2+](https://id.keymetrics.io/api/oauth/login), in the [npmjs ](https://www.npmjs.com/package/@pm2/io) of pm2io, and on those screenshots of the web-app interface, you might see in the documentation. 

Also, there is a separate [keymetrics logo](https://pm2.io/legals/terms_conditions.pdf). So in the end:

> *Would I be correct in saying that they are in the process of rebranding?*

I'll be honest, I do not know, I am not among the maintainer's list of pm2. Maybe one day in the future, keymetrics decide to change/update their classic PM2 logo, from classic to hamburger-like. The only option I have here is to write to their email and wait for an answer to this question. If this is an option and you might think that the logo which I provide is incorrect or requires a confirmation from pm2, I am capable to remake the PR with another version of logo.

**Comment by AlexZeDim** [comment]
@PeterShaggyNoble I just asked the maintainer of the PM2 and Keymetrics founder directly, and [here is his comment](https://github.com/Unitech/pm2/issues/4994#issuecomment-782848577).
TL:DR, the current logo from the GitHub documentation is approved to represent PM2.

**Comment by PeterShaggyNoble** [comment]
Thanks for clarifying that for us, @AlexZeDim. The SVG looks good to me; just some minor differences that we could put down to the anti-aliasing of the source file or to me not being great at comparing raster to vector. As it _is_ a manual vectorisation, though, we will need approval from one of the other @simple-icons/maintainers before we can merge it.

On the colour, would `#2b037a` be a better choice, I wonder? It's used as the background colour for the `body` element. Another possibility would be `#3c0395`, which is the [calculated midpoint](https://meyerweb.com/eric/tools/color-blend/#0E044B:6901DF:1:hex) of the gradient they use in a few places.

**Comment by adamrusted** [comment]
Icon looks spot on to me - thanks for contributing it @AlexZeDim 👌
Are you able to reduce the precision to perhaps 4? 5 may be a little too overkill.
I'd be happy with either of the hex codes suggested by @PeterShaggyNoble, and given they're _BIG_ fans of using gradients, I think the midpoint would be the best one for us to go for. If you could take a quick look over this again @AlexZeDim, that'd be amazing! ✌

**Comment by AlexZeDim** [comment]
@PeterShaggyNoble thank you for clarifying about midpoints.  
@adamrusted yes, I am capable to lower precision down to 4. Should I make all these changes in the current branch/PR or make a new one?

**Comment by PeterShaggyNoble** [comment]
You can use the same branch and PR, @AlexZeDim.

**Comment by AlexZeDim** [comment]
Sorry for such a long delay. I haven't thought that * a couple of days* could transform into a whole week. So I have been fixed both the logo, to precision 3 and the hex color to: `#2b037a`

**Review by PeterShaggyNoble — APPROVED** [review]
Looking good to me, @AlexZeDim 👍🏻 Nice work.

As it's a manual vectorisation, though, we'll need approval from one of the other @simple-icons/maintainers before merging.

**Review by adamrusted — APPROVED** [review]
Looks good to me! Thanks @AlexZeDim for your contribution! 🚀💪

**Pull request merged**
