### PR TITLE
add RenovateBot

### LINKED ISSUE #3485: Request Icon: Renovate Bot
**Name:** renovatebot
**Website:** https://renovate.whitesourcesoftware.com/
**Alexa rank:** 109,435
**Official resources for icon and color:** https://github.com/renovatebot

### PR DESCRIPTION
**Pull request by matfax**
**Issue:** resolves #3485
**Alexa rank:** 109,435

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I used the official website and got the color from the CSS.
The logo is the latest (v4) from their GitHub account.
Their website seems to use another logo for the brand "WhiteSource" but all RenovateBot references (i.e. GitHub, documentation, Twitter) use the "window cleaner" symbol.

### Preview

renovatebot (2)

### CODE REVIEW

**Comment by matfax** [comment]
It turned out that it is the rescaling that destroys the curves somehow. I tried multiple tools. I didn't expect Adobe Illustrator to be flawed when it comes to SVG downscaling. May I ask how you usually scale the SVGs?

**Comment by NovaGL** [comment]
Yeh Illustraotr can be a bit of a pain, same thing happened to me.

What I do is don't resize in Illustrator, save it the full size there and open Inkscape and resize it there. For some reason Inkscape does a much better job at resizing.

Once done can you update the preview in the first post?

**Comment by matfax** [comment]
Thanks for the advice. Inkscape did the trick.

**Review by runxel — COMMENTED** [review]
Thanks for your work, @matfax! 💯

**Pull request merged**
