### PR TITLE
Add Bugsnag

### LINKED ISSUE #2539: Add icon for Bugsnag
No similar issue exists yet

**Name:** Bugsnag
**Website:** https://www.bugsnag.com/
**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Bugsnag

**Issue:** Closes #2539

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Colour from website stylesheet and _seems_ to be their primary colour. An alternative is `#000d47` from the 2 "full" SVGs available at https://www.bugsnag.com/newsroom and used in the footer of their website.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @PeterShaggyNoble 👍

**Comment by amomchilov** [comment]
@PeterShaggyNoble Thanks for your work on this! I'll try add my own icon in the future :D


@phatbhoy67 How does deployment work? When will this be released?

**Comment by ericcornelissen** [comment]
> How does deployment work? When will this be released?

We usually release a new version every two weeks. The next release is planned for this weekend :+1:

**Comment by PeterShaggyNoble** [comment]
You're welcome, @amomchilov. Looking forward to your future contributions :+1:

**Pull request merged**
