### PR TITLE
Add soundcore Icon

### PR DESCRIPTION
**Pull request by jrhaberland**
soundcore

**Issue:** None

**Popularity metric:**
The Similarweb rank is 24,290. See https://www.similarweb.com/website/soundcore.com

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
Color of `#17BBEF` came from svg in footer

### CODE REVIEW

**Comment by uncenter** [comment]
As per the following terms I believe we do not have permission to include this or #11271, and #10465 will have to be reverted.

From https://us.soundcore.com/policies/terms-of-service:

> 12.1 Trademarks
> Anker, Soundcore, Eufy, Nebula, AnkerWork, AnkerMake and the related logos (collectively, the "Marks") are trademarks or registered trademarks of Anker Companies, and used by us with permission. Other trademarks, Service marks, graphics, logos, and domain names appearing anywhere on, through, or in connection with Anker’s Services may be the trademarks of third parties. Neither your use of Anker’s Services nor this Agreement grant you any right, title, or interest in, or any license to reproduce or otherwise use, the Marks or any third-party trademarks, Service marks, graphics, logos, or domain names. You agree that any goodwill in the Marks generated as a result of your use of Anker’s Services will inure to the benefit of Anker Companies, and you agree to assign, and do assign, all such goodwill to Anker Companies. You shall not at any time, nor shall you assist others to, challenge Anker Companies’ right, title, or interest in, or the validity of, the Marks.

> 12.2 Copyrights
> 12.2.1 All content and other materials available through Anker’s Services, including without limitation  logos, design, text, graphics, and other files, and their selection, arrangement, and organization, are either owned by Anker Companies or are the property of our licensors and suppliers. Except as explicitly provided, neither your use of Anker’s Services nor this Agreement grant you any right, title, or interest in any such materials.

**Comment by jrhaberland** [comment]
I'm more than happy to email and ask them for permission

**Comment by uncenter** [comment]
> I'm more than happy to email and ask them for permission

Feel free! That would be great. Let me know once you've sent an email and I can set our 2 month timer 🫡

**Comment by jrhaberland** [comment]
> > I'm more than happy to email and ask them for permission
> 
> Feel free! That would be great. Let me know once you've sent an email and I can set our 2 month timer 🫡

I sent an email wish us luck 🫡

**Pull request closed without merging**
