### PR TITLE
Add Google Maps

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
**Issue:** #1515
Google Maps

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I'm not 100% on the colour so I'm open to suggestions on that, as well as a better source URL.

### CODE REVIEW

**Comment by birjolaxew** [comment]
Thanks for the PR!

Unfortunately this looks like it isn't the same as the [official Google Maps logo](https://www.google.com/permissions/trademark/logos-list/)<sup>1</sup> - we always want to use the official logo, and an official vectorization if available.

In this case the official logo might be a bit of a challenge to monochromize.

<sup>1. Unfortunately Google only provide it as PNG. The most reputable site I could find with a vectorization is [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:GoogleMaps_logo.svg)</sup>

**Comment by PeterShaggyNoble** [comment]
@birjolaxew, note that the source link is to an icon font maintained by Google themselves so the icon in this PR can be considered somewhat official.

The previous version they had was a *bit* closer to the logo but missing the `G` and with a modified pin:
Google Maps

**Comment by birjolaxew** [comment]
Hmm, I still do think that we want to use the [normal Google Maps icon](https://www.google.com/permissions/trademark/logos-list/). Pinging @ericcornelissen.

**Comment by ericcornelissen** [comment]
I think I agree with @birjolaxew, even though the SVG currently in the PR is more recent(?), Google seems to be primarily using the version @birjolaxew linked to... That said I'm not necessarily against adding the legacy icon since it matches the one Google uses pretty well and it is from an official source.

Your call @birjolaxew on whether we add the [legacy icon](https://github.com/simple-icons/simple-icons/pull/1750#issuecomment-540684958) or the "normal Google Maps logo".

**Comment by PeterShaggyNoble** [comment]
Let me double check that the legacy MDI icon came from an official source.

**Comment by PeterShaggyNoble** [comment]
The old one was used by Google for app notifications (and has since been replaced by the new one) but was manually recreated and tweaked for MDI. Original issue is [here](https://github.com/Templarian/MaterialDesign/issues/1006).

**Comment by birjolaxew** [comment]
@PeterShaggyNoble In that case we would definitely prefer having a vectorization of their current logo in Simple Icons instead. I haven't been able to find an official resource, but [Wikimedia has a vector available](https://commons.wikimedia.org/wiki/File:GoogleMaps_logo.svg).

**Comment by PeterShaggyNoble** [comment]
Sorry for the delay. If that's the one ye would prefer to go with, it's going to take someone with a bit more skill than I to recreate!

**Pull request closed without merging**
