### PR TITLE
Added Testing Library

### LINKED ISSUE #3097: Add React Testing Library Icon
**Name:** React Testing Library
**Website:** https://testing-library.com/
**Official resources for icon and color:**
  
Do not have the official ones, but this is the founder of the library. https://kentcdodds.com/

### PR DESCRIPTION
**Pull request by adamrusted**
testinglibrary

**Issue:** Closes #3097
**Alexa rank:** [113,918](https://www.alexa.com/siteinfo/testing-library.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Built from sticker SVG.
Color picked in #3097, as well as discussion on how the icon should look.

### CODE REVIEW

**Comment by fbernhart** [comment]
@adamrusted Beautiful! 🐙

**Comment by kentcdodds** [comment]
Woo! Thanks 👏

**Comment by adamrusted** [comment]
> Woo! Thanks 👏

No worries! Btw, I *love* all those logos you supplied in the issue 😅

**Comment by kentcdodds** [comment]
Feel free to add any of them that you like 😁

**Pull request merged**
