### PR TITLE
Openzfs icon

### PR DESCRIPTION
**Pull request by deepmalamittal**
openzfs

**Issue:https://github.com/simple-icons/simple-icons/issues/6575**
**Alexa rank:420953**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
I would change the source to https://openzfs.org/OpenZFS%20Guidelines.pdf, which is the official source

**Comment by jorgeamadosoria** [comment]
image

There are some very minor differences in the holes. Perhaps optimizing with precision 4 can help here.

Or maybe extracting the icon from the pdf linked above, that could also help solve the issue.

**Comment by deepmalamittal** [comment]
@jorgeamadosoria Changes have been implemented. Please review whenever you get a chance. 
Let me know if some issue still prevails.

**Comment by jorgeamadosoria** [comment]
@deepmalamittal It's good enough now, thanks!
LGTM.

**Pull request merged**
