### PR TITLE
Add Kdenlive

### LINKED ISSUE #5057: Kdenlive (video editor)
**Brand Name:** Kdenlive
**Website:** https://kdenlive.org/en/
**Alexa rank:** 115,080 (as of 2021-02-18)
  

**Official resources for icon and color:**
- https://kdenlive.org/en/logo/
- `#527eb2` could be the color here. :/

### PR DESCRIPTION
**Pull request by foo-dogsquared**
simpleicons

**Issue:** Closes #5057
**Alexa rank:** 112,742 (as of 2021-03-07)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by fbernhart** [comment]
@foo-dogsquared Thanks for your pull request.

It looks like you've somehow scaled the height of the icon a little bit. Overlaying your version (red) with the source (black), you can see it:

image

Could you give it another try, trying to keep the aspects ration of the original icon?

**Comment by foo-dogsquared** [comment]
Strange, I made sure I only scale the icon down but then again I'm working with a wonky touchpad at the time. Hopefully, this fixes it.

**Comment by PeterShaggyNoble** [comment]
Could you take another look at this one, @foo-dogsquared? From the linting, it seems the dimensions and centring have gone askew somehow.

**Comment by foo-dogsquared** [comment]
Hello! (Apologies for the delay.) I've rebuild the icon (for the third time). I used the SVGO in the project root instead of the usual SVGOMG this time for good measure. Could you take another look, @PeterShaggyNoble?

**Comment by PeterShaggyNoble** [comment]
SVG looks perfect to me now, @foo-dogsquared. However, from the source file there are 2 duplicate points in the top most bar; one in the top left corner and one on the right edge which creates an imperfection in the icon. Would you mind seeing if you could clean those up?

**Comment by foo-dogsquared** [comment]
Alright, I was able the imperfection on the side of the top bar (2 points) and the redundant point on the top corner (1 point) of it. The following image comparison shows it ("original" in green, my version in black). "Original" in quotes because I modified the original but the only change there is the removal of the imperfection around that part.

image

**Review by PeterShaggyNoble — APPROVED** [review]
Looks spot-on to me now, @foo-dogsquared, nice work 👍🏻 And welcome back to the fold 🙂

Maintainers, I left the `guidelines`  entry in this one as, while it doesn't include anything by way of brand identity or requirements, it does include mention that the full logo should be used in situations greater than 50px.

**Pull request merged**
