### PR TITLE
Add Apple Arcade icon

### LINKED ISSUE #3703: Request: Apple Arcade icon
**Name:** Apple Arcade
**Website:** https://www.apple.com/arcade
**Alexa rank:** 50
  

**Official resources for icon and color:**
  
Icon: https://www.apple.com/v/apple-arcade/i/images/overview/arcade_icon__d77taf8r7mi6_large.svg
Color: #000

### PR DESCRIPTION
**Pull request by LitoMore**
image

**Issue:** #3703
**Alexa rank:** 50
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Resolve #3703

### CODE REVIEW

**Comment by adamrusted** [comment]
Thanks for the submission @LitoMore!
Just looking at it now, there's a difference between your PR version (black) and the source file (white) - could you look at regenerating this for us?

image

**Comment by LitoMore** [comment]
@adamalston Sure. Let me check.

**Comment by adamrusted** [comment]
Hey @LitoMore, are you still interested in looking at this one? No worries if not, I can push an update to the path.

**Comment by LitoMore** [comment]
@adamalston Please help. I'm on vacation these days. Thank you so much!

**Comment by adamalston** [comment]
Enjoy your vacation!

**Comment by adamrusted** [comment]
Could another @simple-icons/maintainers review this one? I've updated it with a new path.

**Comment by PeterShaggyNoble** [comment]
@adamrusted, could you see if you can clean up the duplicate point in the bottom left of the button?

**Comment by adamrusted** [comment]
@PeterShaggyNoble give that a go. Should fix it.

**Review by PeterShaggyNoble — APPROVED** [review]
That looks perfect now.

Thanks for your work on this one, @LitoMore and for your assistance, @adamrusted 👍🏻

**Pull request merged**
