### PR TITLE
Remove Sketch

### PR DESCRIPTION
**Pull request by adamrusted**
sketch

**Alexa rank:** [5,670](https://www.alexa.com/siteinfo/sketch.com)

See https://github.com/simple-icons/simple-icons/pull/4480#issuecomment-752518958 for reason behind removal.

### CODE REVIEW

**Comment by mondeja** [comment]
I like more this version than the previous one, but these gaps are not visible in small sizes. Have you considered using wider gaps?

**Comment by adamrusted** [comment]
> I like more this version than the previous one, but these gaps are not visible in small sizes. Have you considered using wider gaps?

I can use wider gaps - set 0.35px following previous discussions I've seen. Will try with 0.5px when I'm in front of my PC next.

**Comment by mondeja** [comment]
It's something that we should discuss to clarify these cases. See [this comment](https://github.com/simple-icons/simple-icons/issues/3829#issuecomment-749561677).

**Comment by ericcornelissen** [comment]
Regarding this icons, the discussion in #1141 says that the current version was, at the time, found in the Sketch brand guidelines as is So in that regard I think we should stick with it. However, the new brand guidelines at https://www.sketch.com/about-us/#press seem to specify that a monochrome version like this is not allowed...

**Comment by adamrusted** [comment]
> However, the new brand guidelines at [sketch.com/about-us/#press](https://www.sketch.com/about-us/#press) seem to specify that a monochrome version like this is not allowed...

Well spotted! 👀
Should I look at marking this for removal in v5.0.0 then?

**Comment by PeterShaggyNoble** [comment]
They're getting as bad as Medium for constantly changing their branding!

**Comment by PeterShaggyNoble** [comment]
Looks like we might actually be able to keep this one as they now include monochrome versions in [the logos & guidelines file](https://cdn.sketchapp.com/assets/pages/about-us/logos.zip).

**Comment by adamrusted** [comment]
If other @simple-icons/maintainers are happy to keep it, maybe if we properly link to the guidelines, then this can be closed - as our version matches up perfectly to the logo they provide.

**Comment by ericcornelissen** [comment]
The presence of a monochrome version in the logos & guidelines file is definitely enough for keeping a monochrome version here, I would say :+1: Good catch @PeterShaggyNoble, glad we can keep this one :smile: 

With three votes in favor of keeping the Sketch SVG I will close this for now - should be easy enough to reopen/replicate this PR later anyway.

**Pull request closed without merging**
