### PR TITLE
Add Rakuten Icon

### LINKED ISSUE #3294: Rakuten
**Name:** Rakuten
**Website:** rakuten.co.jp
**Alexa rank:** 93
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by davidkryzaniak**
rakuten

**Issue:** Closes #3294 
**Alexa rank:** 93

  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by davidkryzaniak** [comment]
That's odd. Yes, I did use the referenced image. I just attempted to recreate the logo again and got the same output. Maybe I'm doing something wrong? (too aggressive on the optimization?)

**Comment by ericcornelissen** [comment]
> 
> 
> That's odd. Yes, I did use the referenced image. I just attempted to recreate the logo again and got the same output. Maybe I'm doing something wrong? (too aggressive on the optimization?)

Yes, it could very well be the optimization. Could you try with less aggressive optimization (i.e. increasing the `precision` value)? Alternatively you can share the SVG produced by your editing software here and we can work together from that.

**Comment by PeterShaggyNoble** [comment]
I can confirm that when running this through SVGOMG with a precision of 3, there is a very definite visual shift. However, in my version it was only apparent in the inner curve of the "R". Unfortuntately, to completely resolve it, I had to up the precision to 6! 😮 SVGO may fare better than that, though.

**Comment by ericcornelissen** [comment]
SVGOMG just runs SVGO for you but with a UI so it shouldn't make a difference (other than the fact that there are more options available)

**Comment by PeterShaggyNoble** [comment]
> it shouldn't make a difference

It shouldn't, no, but on _very_ rare occasions in the past both @runxel and I have noticed differences in the output between the two 🤷‍♂️

**Comment by adamrusted** [comment]
Found a new SVG version of the underlined 'R' [here](https://global.rakuten.com/corp/assets/img/site-icons/rakuten-black.svg) - and rebuilt from source. Seems to be working with a precision of 3, but could another @simple-icons/maintainers look at this?

rakuten

**Review by mondeja — APPROVED** [review]
Perfect @adamrusted, great work! :100:
Thank you for rescuing this addition and @davidkryzaniak for the previous effort :pray:

**Pull request merged**
