### PR TITLE
Add remark icon

### LINKED ISSUE #8933: Add Remark Icon
### Brand Name

remark

### Website

https://remark.js.org

### Popularity Metric

https://github.com/remarkjs/remark - 6.5k stars

### Official Resources for Icon and Color

svg: https://github.com/remarkjs/remark/blob/main/logo.svg
github profile: https://avatars.githubusercontent.com/u/16309564?s=200&v=4
color (from svg): `#0d1117`, `#d80303`

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by developomp**
preview

**Issue:** closes #8933

**GitHub:** https://github.com/remarkjs/remark - 6.5k stars

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- svg taken from https://github.com/remarkjs/remark/blob/26dc58a675ac7267c105f0fdb76a82db77f8402a/logo.svg

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
I'm spotting [some difference](https://github.com/simple-icons/simple-icons/assets/1830867/a6c7c27a-b9eb-4cf8-ba26-7edf2a7e28dd) between your PR in black, and the source icon in red. Could you give this one another go please @developomp 🙏

**Comment by developomp** [comment]
> I'm spotting [some difference](https://github.com/simple-icons/simple-icons/assets/1830867/a6c7c27a-b9eb-4cf8-ba26-7edf2a7e28dd) between your PR in black, and the source icon in red. Could you give this one another go please @developomp pray

@adamrusted fixed!

**Review by adamrusted — CHANGES_REQUESTED** [review]
I'm still seeing [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/a99d00ca-4bd2-4032-9250-d4a6b0b6ea7a) when comparing PR in black to the source file in red. Might need either 4 decimals of precision in SVGO, or a re-work of the icon.

**Comment by developomp** [comment]
Well this is annoying. How can I check for differences myself?

**Comment by adamrusted** [comment]
So I keep two copies of the source icon while I'm working on them - one I label as `remark.src.svg` for example, and the one I'm working on to just `remark.svg`. I then do all the optimisation so that the latter passes the linters, and then pull in the path from the `.src.svg` file to compare.

**Comment by developomp** [comment]
Found the problem. Resizing svgs in figma does that. I'll try to do it in inkscape.

**Comment by developomp** [comment]
@adamrusted Sorry for all the trouble. I believe it is fixed now.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @developomp 🎉

**Pull request merged**
