### PR TITLE
Add Drooble icon

### LINKED ISSUE #3229: Drooble
https://drooble.com/
https://blog.drooble.com/press/
https://drive.google.com/drive/folders/1HdaHwUNewKEB-ozAztnyDp_nN9pehWOQ

#27b7d1

PNG:

https://user-images.githubusercontent.com/746834/85090114-d8b24900-b1d3-11ea-846a-153fd772b2b4.png

SVG:

`<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M14,0.2v7.2c-0.2-0.1-0.5-0.2-0.7-0.2c-2.7-0.8-5.6,1-6.2,3.8c-0.6,2.8,1.4,5.5,4.2,5.9c2.7,0.4,5.3-1.5,5.7-4.2c0-0.3,0.1-0.5,0.1-0.8V4.4c0.4,0.1,0.8,0.1,1.2,0.2C21.6,5.5,24,8.5,24,12c0,5.8-4.2,10.9-10,11.8c-3.9,0.6-7.4-0.4-10.3-3.1c-2.3-2.2-3.6-4.9-3.7-8.1C-0.3,6.5,4,1.2,10,0.2C11.3-0.1,12.7-0.1,14,0.2L14,0.2z"/><path d="M14,12c0,1.1-0.9,2-2,2c-1.1,0-2-0.9-2-2c0-1.1,0.9-2,2-2C13.1,10,14,10.9,14,12C14,12,14,12,14,12z"/></svg>`

### PR DESCRIPTION
**Pull request by NovaGL**
droobble

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

@bhadaway manually converted the raster logo to vector from their [Google Drive ](https://drive.google.com/drive/folders/1HdaHwUNewKEB-ozAztnyDp_nN9pehWOQ)

Closes #3229

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
OK, I'm a bit confused by their branding here 🤔 Going by their social media alone, I'd agree that you and @bhadaway made the correct choice of logo but I'm getting hung up on why the logo on their website is _completely_ different, which would normally be our primary source for the choices we make.

I wonder, maybe, have we caught them in the middle of rebranding? But, if that were the case and it was a phased rollout, I'd expect their social media logos to be the more up-to-date ones as they're easiest to change - [their Facebook](https://www.facebook.com/DroobleOfficial/photos/a.159523070923413/1121698458039198/) logo was last updated in September of last year, though.

The other possibility is that they have separate logos for the company and the product but I can't find anything that would explicitly confirm that. If that does turn out to be the case then I think it's the product icon we should be adding. If we could figure out what the "FC" in [`Drooble_Logo_FC_Horizontal_Positive_RGB.png`](https://drive.google.com/drive/folders/1HdaHwUNewKEB-ozAztnyDp_nN9pehWOQ) that may help.

Another avenue that could have helped would have been their app icons but it appears that they've been removed from both Google Play & iTunes.

**Comment by NovaGL** [comment]
Yeh, I noticed that too. It seems this company is a bit slack in updating their branding.

I was sure I had the right logo but now not so sure. @bhadaway can you shed any light on this?

**Comment by bhadaway** [comment]
I'll just shoot them an email and ask.

**Comment by bhadaway** [comment]
Okay, they are indeed in the middle of rebranding.

Their new logo is the one in which I derived the icon from, so we're good to go.

**Comment by PeterShaggyNoble** [comment]
Thanks for reaching out to them, @bhadaway; that's a big help :+1:

Normally, I would suggest holding off on a newly rebranded logo until such a time as the rebranding is complete but as the only place they haven't rolled it out yet is on their website, I think we can proceed with this one.

**Comment by PeterShaggyNoble** [comment]
D'oh! Forgot to actually review this! 🙄

I am noticing some inconsistencies but, as proven in the past, I'm pretty bad at comparing raster to vector so I've requested reviews from a couple of the other @simple-icons/maintainers.

**Comment by bhadaway** [comment]
There have been a couple changes along the way, so let's make sure we're all looking at the newest versions:

Raster: https://user-images.githubusercontent.com/746834/85090114-d8b24900-b1d3-11ea-846a-153fd772b2b4.png

Vector: https://calmestghost.com/drooble.svg

**Comment by ericcornelissen** [comment]
When comparing I'm seeing some very minor differences:

image

image

Except for the imperfect rounding at the bottom due to an extra point I think this is _good enough_:

image

Arguably the left-side arc can also be improved by removing some extra points.

**Comment by bhadaway** [comment]
I went ahead and just requested a vector copy of the logo from the company. Then, there won't be any guesswork; it'll just be a perfect 1:1 copy.

**Comment by bhadaway** [comment]
Done.

Official AI: https://calmestghost.com/drooble.ai

Updated SVG: https://calmestghost.com/drooble.svg

Correct Brand Color: `#19c4be`

**Comment by PeterShaggyNoble** [comment]
Many thanks for reaching out, @bhadaway :+1:

**Comment by bhadaway** [comment]
You're welcome.

**Comment by ericcornelissen** [comment]
Thanks for the new source material @bhadaway, this looks good to me now. I took the liberty of updating the PR using your SVG as a basis. Since I did that I'll leave it to another @simple-icons/maintainers to have a look at this and merge it in 😃

**Comment by PeterShaggyNoble** [comment]
The new SVG is slightly off vertical centre; Inkscape shows it sitting at `0.002` on the Y axis, rather than `0`. After fixing that, though, I'm seeing a couple of hairline differences (see examples in screenshots below, with @bhadaway's version in red). Both issues are probably just a result of the precision being too low, though.

**Comment by ericcornelissen** [comment]
Good thing I left it open for review, didn't check carefully enough after optimization 🙃

Before I push an update, how is the version below (precision 4 instead of 3):

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Drooble icon</title><path d="M12.001 9.998c1.104 0 2 .896 2 2s-.896 2-2 2-2-.896-2-2 .895-2 2-2zm11.998 2C24 8.036 20.951 4.742 17 4.439v7.559c.002 2.762-2.235 5-4.997 5.001-2.76.002-5-2.234-5.001-4.995-.001-2.762 2.235-5.001 4.997-5.002.688 0 1.37.142 2.002.417V.17C7.467-.935 1.275 3.467.171 10c-1.104 6.534 3.297 12.726 9.83 13.83 6.534 1.105 12.726-3.296 13.83-9.83.111-.661.168-1.331.168-2.002z"/></svg>
```

**Comment by bhadaway** [comment]
Just wanted to jump in one last time to make sure you're using the latest version (because @ericcornelissen's reply has the wrong code). You want:

`<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Drooble icon</title><path d="m12 10a2 2 0 1 1 -2 2 2 2 0 0 1 2-2zm12 2a7.58 7.58 0 0 0 -7-7.56v7.56a5 5 0 1 1 -3-4.58v-7.25a12 12 0 1 0 10 11.83z"/></svg>`

I'm sure it's still not perfect though; is that even possible; do all the other icons in the set perfectly match their official logo? It seems like you would have to take some liberties to bend them to the will of the icon set, no?

Anyway, I'll leave it to the official contributors now, thanks for taking my suggestion, and it's an interesting process. At a later time, I may decide to properly clone the repo and get involved in a more meaningful way.

https://simpleicons.org/ has been a very vital tool in my arsenal for a while now. I jumped from one icon font to another, to premium SVG sets, blah blah blah, until finally finding something that stuck, with Simple Icons.

Thanks

**Comment by ericcornelissen** [comment]
@bhadaway I used the `.ai` file as a basis. I recal that I had to move it a bit, and I also optimized it (again?) using the SVGO CLI. Thanks for sharing your version as well, though. (I currently am not able to compare it)


> I'm sure it's still not perfect though; is that even possible; do all the other icons in the set perfectly match their official logo? It seems like you would have to take some liberties to bend them to the will of the icon set, no?

In general, if there is an official vector source then that should be possible. And @PeterShaggyNoble [compared](https://github.com/simple-icons/simple-icons/pull/3231#issuecomment-653602523) my SVG to your SVG, which should match.

**Comment by NovaGL** [comment]
There are very tiny differences between the two SVGs, I believe it's good enough to be merged.

**Comment by PeterShaggyNoble** [comment]
With [our new linting step](https://github.com/simple-icons/simple-icons/pull/3250), the build was failing on the previous version of the SVG. Upping the precision to 3 seems to solve all the issues so I've pushed an updated path using that (hope you don't mind, @NovaGL).

**Comment by NovaGL** [comment]
no problem. Sorry for being awol

**Comment by PeterShaggyNoble** [comment]
Yay, teamwork! 🎉 Thanks, everyone, for your collaborative efforts on this one.

**Pull request merged**
