### PR TITLE
Add Google Play Music

### LINKED ISSUE #3124: Google Play Music
I just wanted to know if it's approriate to add Google Play Music. I know Youtube Music is set to replace it, but I still think it could be useful.

I might need some help to fix the bottom of the icon though

simpleicons(1)

### PR DESCRIPTION
**Pull request by NovaGL**
simpleicons(2)

**Issue:** Closes #3124

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

I had to manually modify the icon as it's not available in monochrome. 

SVG Source: https://commons.wikimedia.org/wiki/File:Google_Play_Music_icon_(2016).svg

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @NovaGL :+1:

If they're only discontinuing the music _service_ and not the _app_ then I think we're OK to add this. If however, they're discontinuing _both_ I don't see much point in adding it just to remove it again in a few weeks/months, unless they have a pretty lengthy roadmap to discontinuation.

Don't have time right now to do a full review of the SVG but that treatment looks great to me, nice work. There is, however, an official vector version available [here](https://play.google.com/intl/en_us/badges-music/) that we can compare to.

**Comment by NovaGL** [comment]
My understanding is they are changing the service side of things (online).

Meaning Google Play Music will still be used as the app for your local music but anything related to online will be moved to YouTube Music.

It would be odd to call an offline music player YouTube Music.

**Comment by ericcornelissen** [comment]
I would be surprised if they get rid Google Play Music entirely, especially in a few weeks or months :thinking: I think we can include it for now, unless there is a definitive source indicating that Google Play Music will be discontinued in the near future.

**Comment by NovaGL** [comment]
Hi @PeterShaggyNoble 

I've done those changes as requested. Sorry for all the commits, I'm just using the web browser for commits so don't know how to stage and then push them all at once.

For some reason the bottom looks worse on this version however it looks perfect in Illustrator.
I had to start again and use your source as a reference.

simpleicons(1)

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @NovaGL 

However, the SVG is coming in at `29.939` high now and the path isn't quite centred on the canvas. When resized and centred, there are a few new minor differences in your version (again, in black below) when compared to the original.

**Comment by NovaGL** [comment]
Thanks Peter. Weird about the height. It seems this logo is not as easy as I first thought. Looks like it might take me a few more attempts. I'll let you know.

**Comment by PeterShaggyNoble** [comment]
I took a quick stab at it myself, if it's any help to you. I went with a slightly thicker cut-out as it looks better at smaller sizes. But not as good at bigger sizes.

```
M 2.5078125,0 C 2.1838196,0.0068209 1.9048074,0.11959163 1.6933594,0.32421875 1.3932396,0.61069672 1.2304687,1.0755419 1.2304688,1.6757812 V 22.314453 C 1.2304688,22.914693 1.4068814,23.379538 1.6933594,23.666016 2.1298972,24.088912 2.8122605,24.129867 3.5898438,23.679688 L 9.3105469,20.427734 C 9.3139359,20.428645 9.3169218,20.430734 9.3203125,20.431641 L 9.328125,20.427734 C 5.6048066,19.430193 2.8535156,16.036774 2.8535156,12.001953 2.8535155,7.9651534 5.6078822,4.5718416 9.3339844,3.5761719 L 3.5898438,0.31054688 C 3.201052,0.09227795 2.8318054,-0.0068209 2.5078125,0 Z M 11.583984,4.2714844 C 7.3083489,4.2714842 3.8535155,7.7263173 3.8535156,12.001953 3.8535156,15.962851 6.820522,19.213904 10.65625,19.671875 L 18.648438,15.134766 C 19.072966,14.176859 19.314453,13.118823 19.314453,12.001953 19.314453,7.7263175 15.85962,4.2714843 11.583984,4.2714844 Z M 11.583984,6.5449219 C 14.59789,6.5447513 17.041186,8.9880472 17.041016,12.001953 17.041186,15.015859 14.59789,17.459155 11.583984,17.458984 8.5700786,17.459154 6.1267831,15.015858 6.1269531,12.001953 6.126783,8.9880476 8.5700786,6.5447519 11.583984,6.5449219 Z M 11.583984,9.1367188 V 12.492188 C 11.392999,12.383053 11.17527,12.316406 10.943359,12.316406 10.233985,12.316406 9.6738281,12.888252 9.6738281,13.583984 9.6738281,14.293358 10.247627,14.853516 10.943359,14.853516 11.652733,14.853516 12.265625,14.279716 12.265625,13.583984 V 10.501953 H 13.494141 V 9.1367188 Z M 19.976562,9.6210938 C 20.19183,10.379141 20.314453,11.175594 20.314453,12.001953 20.314453,12.827652 20.191498,13.623351 19.976562,14.380859 L 19.986328,14.375 C 19.987809,14.369909 19.988763,14.364471 19.990234,14.359375 L 21.787109,13.337891 C 23.096723,12.601233 23.096723,11.400691 21.787109,10.650391 Z
```

Google Play Music

**Comment by NovaGL** [comment]
Looks good to me. I'm happy to go with that.
I'm not a designer so these things are a bit hard for me.

**Comment by PeterShaggyNoble** [comment]
> I'm not a designer

Me, either, and ...
> these things are a bit hard for me

Me too! I gets a bit easier with practice, though. I'm still not entirely happy with the cut-out on mine; I think we lose too much of the filled circle.

**Comment by NovaGL** [comment]
I think you might be being a bit hard on yourself. This logo is not really meant for monochrome so it's gonna be hard for anyone

**Comment by PeterShaggyNoble** [comment]
> I think you might be being a bit hard on yourself.
The bane of being a perfectionist! 😆

Gave it another try with different sized cut-outs; the one above was 1px, the first one below is .5px and the second one is .75px. Trying to strike a balance between the cut-out being visible and not losing too much of the circle so I _think_ .75 might be the way to go. What do the other @simple-icons/maintainers think?

Google Play Music
Google Play Music

**Comment by ericcornelissen** [comment]
I'd say both `1` and `0.75` work well, `0.5` is definitely too little.

**Comment by NovaGL** [comment]
I personally like `0.75` the best as it looks good at all sizes. (I also think this matches most closely my initial suggestion for the icon)
`1` looks good at small sizes but looks to different to the original at large sizes.

**Comment by PeterShaggyNoble** [comment]
Here's the unoptimised path data for that one, if you want to use it as a starting point, @NovaGL 

```
M 2.5078125 0 C 2.1838196 0.0068209 1.9048074 0.11959163 1.6933594 0.32421875 C 1.3932396 0.61069672 1.2304687 1.0755419 1.2304688 1.6757812 L 1.2304688 22.314453 C 1.2304688 22.914693 1.4068814 23.379538 1.6933594 23.666016 C 2.1298972 24.088912 2.8122605 24.129867 3.5898438 23.679688 L 9.3066406 20.429688 A 8.7309999 8.7309999 0 0 1 2.8535156 12.001953 A 8.7309999 8.7309999 0 0 1 9.3222656 3.5683594 L 3.5898438 0.31054688 C 3.201052 0.092277945 2.8318054 -0.0068209 2.5078125 0 z M 13.695312 3.53125 A 8.7309999 8.7309999 0 0 1 13.796875 3.5566406 C 13.763135 3.5477777 13.72921 3.5397163 13.695312 3.53125 z M 11.583984 3.6464844 A 8.3559999 8.3559999 0 0 0 3.2285156 12.001953 A 8.3559999 8.3559999 0 0 0 9.7929688 20.164062 L 19.509766 14.644531 A 8.3559999 8.3559999 0 0 0 19.939453 12.001953 A 8.3559999 8.3559999 0 0 0 11.583984 3.6464844 z M 14.392578 3.7363281 A 8.7309999 8.7309999 0 0 1 14.460938 3.7597656 C 14.438214 3.7517967 14.415387 3.7441133 14.392578 3.7363281 z M 11.583984 6.5449219 A 5.4567232 5.4567232 0 0 1 17.041016 12.001953 A 5.4567232 5.4567232 0 0 1 11.583984 17.458984 A 5.4567232 5.4567232 0 0 1 6.1269531 12.001953 A 5.4567232 5.4567232 0 0 1 11.583984 6.5449219 z M 11.583984 9.1367188 L 11.583984 12.492188 C 11.392999 12.383053 11.17527 12.316406 10.943359 12.316406 C 10.233985 12.316406 9.6738281 12.888252 9.6738281 13.583984 C 9.6738281 14.293358 10.247627 14.853516 10.943359 14.853516 C 11.652733 14.853516 12.265625 14.279716 12.265625 13.583984 L 12.265625 10.501953 L 13.494141 10.501953 L 13.494141 9.1367188 L 11.583984 9.1367188 z M 19.984375 9.625 A 8.7309999 8.7309999 0 0 1 20.314453 12.001953 A 8.7309999 8.7309999 0 0 1 19.990234 14.359375 L 21.787109 13.337891 C 23.096723 12.601233 23.096723 11.400691 21.787109 10.650391 L 19.984375 9.625 z M 19.990234 14.359375 A 8.7309999 8.7309999 0 0 1 19.984375 14.376953 L 19.986328 14.375 C 19.987809 14.369909 19.988763 14.364471 19.990234 14.359375 z 
```

And, to help you with your future contributions or if you'd like to try to recreate what I did, here's a quick step-by-step:
1. Delete all the unncessary paths so you're just left with four, one for each shape
2. Group them all together
3. Resize your canvas to `24*24`
4. Resize the grouped paths to `24` high, centre them on the canvas and ungroup them again
5. Take a note of the coordinates & width of the larger circle<br>(Inkscape gives me: `x=2.853`, `y=3.271` & `w=17.462`)
6. Merge the large circle with the triangle
7. Knock the the smaller circle out of the resulting path
8. Merge that path with the note
9. Draw a circle using the coordinates & dimensions from step 5, using `w` for the height so it's a perfect circle
10. Draw another circle but set the width & height to `17.462-.75=16.712`, the `x` coordinate to `2.853+.375=3.228` and the `y` coordinate to `3.271+.375=3.646`
11. Knock that circle out of the one from step 9
12. Knock the resulting path out of the path from step 8

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @NovaGL, looks good to me now (but I would say that! 😆)

A couple of minor things to fix:
1. The optimised path is coming in at `24.001` high
2. There are a couple of unnecessary points above the circle which should be removed - I didn't spot that they had crept into my version.

**Comment by NovaGL** [comment]
Hopefully this is good now. If not I might need you to look into it @PeterShaggyNoble 

It seems to not like my PC and I couldn't even see those small dots unless I reloaded your path.

**Pull request closed without merging**
