### PR TITLE
Updated NEC

### PR DESCRIPTION
**Pull request by fbernhart**
nec

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by mondeja** [comment]
The same here, asking for the precision and conflict resolution :hammer_and_pick:

**Comment by fbernhart** [comment]
@mondeja Fixed

**Review by mondeja — CHANGES_REQUESTED** [review]
Thank you @fbernhart. However, I'm seeing a difference of height between the icon of original source (dark blue, 6,399px) and your version (yellow, 6,325px). Maybe is the optimization process. Can you check that?

By the way, forget conflict resolutions, I've found that if I remove the "co-authored by" part of the pull request merge I can do a clean merge even if I resolve the conflict myself :sweat_smile: 

nec-diff

**Comment by fbernhart** [comment]
@mondeja Fixed. Thanks for checking! 😊

**Review by mondeja — APPROVED** [review]
It's perfect now. Thank you @fbernhart! :muscle:

**Pull request merged**
