### PR TITLE
Use ASCII instead of Unicode characters

### PR DESCRIPTION
**Pull request by sisp**
I've replaced Unicode apostrophes in the icon titles (in `_data/simple-icons.json`) and the SVG icon titles by ASCII apostrophes. I think ASCII characters should be preferred over Unicode characters unless Unicode characters are characteristic of the brand.

### CODE REVIEW

**Review by sachinraja — APPROVED** [review]
Nice, good catch! Since you are active in this repo: let me know if you'd like to help out more, there's a lot of things that need to be done.

**Comment by sisp** [comment]
I'd be glad to help with a limited time budget, this is a great project. :slightly_smiling_face: I'm still learning about high-quality SVGs though.

**Comment by sachinraja** [comment]
All your PRs have been very high quality though! If you'd like to help we could use more people reviewing icons (no pressure or expectations though).

**Comment by sisp** [comment]
Thank you very much for the praise. :blush: Yes, I'd love to help.

**Comment by sisp** [comment]
What are the next steps? Would you make me a member of the project?

**Comment by sachinraja** [comment]
I prefer having potential new members review icons first, so adding you as a member could come after that.

**Comment by sisp** [comment]
Sure, that's fair.

**Pull request merged**
