### PR TITLE
Add karma runner

### LINKED ISSUE #6069: Karma Test Runner Icon
**Brand Name:**
Karma

**Website:**
https://karma-runner.github.io/latest/index.html

**Alexa rank:**
290,398

**Official resources for icon and color:**
GitHub repo - https://github.com/karma-runner/karma/
png - https://github.com/karma-runner/karma/blob/master/logo/logo.png

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
karmarunner

**Issue:** closes #6069 

**GitHub Stars:** 11.9K. See https://github.com/karma-runner/karma

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: https://github.com/karma-runner/karma/blob/450fdfdac5b999967daec1020f1ac69cf9b854ab/logo/logo.svg
Color: Taken from logo `#56c5a8`

### CODE REVIEW

**Comment by adamrusted** [comment]
I'm going to say we shouldn't be adding this one - given the tool [has been deprecated](https://github.com/karma-runner/karma#karma-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes) relatively recently. What do other @simple-icons/icon-review folk think?

**Comment by PratyushJayachandran** [comment]
> I'm going to say we shouldn't be adding this one - given the tool [has been deprecated](https://github.com/karma-runner/karma#karma-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes) relatively recently. What do other @simple-icons/icon-review folk think?

Oops moment. I didn't notice the Readme. Maybe we should not add this.

**Comment by adamrusted** [comment]
Closing, see https://github.com/simple-icons/simple-icons/issues/6069#issuecomment-1680256172.

**Comment by davidlj95** [comment]
Despite deprecated, I think it could be useful to be included. See #7437 

Indeed, the project meets [inclusion criteria](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) as has 11k stars on GitHub

Furthermore, it is still used around. For instance, it's [still the default test runner when creating new Angular apps using latest version of Angular CLI (v17.3.2 when writing this)](https://github.com/angular/angular-cli/blob/17.3.2/packages/schematics/angular/workspace/files/package.json.template#L30-L34)

So one could want to indicate they're using Karma for their project for instance. wdyt?

**Pull request closed without merging**
