### PR TITLE
Update Bing

### LINKED ISSUE #4745: Update Bing
**Brand Name:** Bing
**Official resources for icon and color:** https://www.bing.com/sa/simg/favicon-2x.ico

Bing was [rebranded as Microsoft Bing](https://github.com/simple-icons/simple-icons/pull/4744) late last year. As part of that rebranded the adopted the MS logo as their logo but continue to use the `b` in places as their icon (e.g., for [their favicon](https://www.bing.com/sa/simg/favicon-2x.ico)). The icon has a new look so we should update ours to match but I haven't been able to dig up an official SVG as yet.

### PR DESCRIPTION
**Pull request by adamrusted**
bing

**Issue:** Fixes #4745
**Alexa rank:** [35](https://www.alexa.com/siteinfo/bing.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Updated source. Gaps of 0.5px between segments. Hex picked as estimated mid-point of gradient.

### CODE REVIEW

**Comment by fbernhart** [comment]
I like the monochrome treatment, but it seems like you've created some imperfections at the bottom of the right gap.
image
image

As well it seems like at the top of the right gap you've cut off a bit too much.
image


There are as well some points pretty close to each other that maybe could be simplified?

**Comment by adamrusted** [comment]
@fbernhart try that - first version was done in Inkscape as an experiment, second done in Illustrator.

**Comment by fbernhart** [comment]
The SVG looks amazing now! 👍🏼 

Concerning the color: That's really difficult. The middle part of the logo has a linear gradient from `#39D2FF` to `#104CF5`. The [mid-point](https://meyerweb.com/eric/tools/color-blend/#39D2FF:104CF5:1:hex) would be `#258FFA`.

But that's just as valid or not valid as your approach. 😅

**Comment by adamrusted** [comment]
> The middle part of the logo has a linear gradient from `#39D2FF` to `#104CF5`. The [mid-point](https://meyerweb.com/eric/tools/color-blend/#39D2FF:104CF5:1:hex) would be `#258FFA`.

Let's go with your hex @fbernhart, as it's been generated by an algorithm as opposed to me eyeballing it. Will update that, and it's ready for review.

**Comment by fbernhart** [comment]
Great! 👍🏼  LGTM

**Pull request merged**
