### PR TITLE
Updated Android Auto Source

### PR DESCRIPTION
**Pull request by adamrusted**
**Issue:** #4205
**Alexa rank:** N/A

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] ~I optimized the icon with SVGO or SVGOMG~
  - [x] ~The SVG `viewbox` is `0 0 24 24`~

### Description
Updated source of icon to match new marketing hub. Reverted changes made in original PR, as app icon preferred to wordmark.

~Revised icon to match suggested use and pulled new hex from website homepage.
SVG download on Google page broken. Used SVG from Wikipedia and PNG from Google to match spacing.
Converted in Adobe Illustrator.
Ran through SVGO CLI & SVGlint.~

[Preview of original PR treatment](https://user-images.githubusercontent.com/1830867/102641693-6a374f00-4154-11eb-99ad-41fb162f4529.png)

### CODE REVIEW

**Comment by mondeja** [comment]
> and PNG from Google to match spacing

I'm not able to fit your version completely with a Google PNG. What's is the exact PNG that you have used to match the spacing @adamrusted?

**Comment by adamrusted** [comment]
> I'm not able to fit your version completely with a Google PNG. What's is the exact PNG that you have used to match the spacing @adamrusted?

I think I used the preview PNG found [here]() as the download links weren't working. Just found out they're fixed, so regenerated from SVG source.

**Comment by mondeja** [comment]
Broken again :man_facepalming:

**Comment by adamrusted** [comment]
> Links broken again 🤦‍♂️

I put the markdown in for a link, but forgot to put it in 😅
Updating now...

**Comment by PeterShaggyNoble** [comment]
New source URL for this one: https://thepartnermarketinghub.withgoogle.com/brands/android-auto/visual-identity/visual-identity/

Unfortunately all the links to the vector files are broken. 🙁

**Comment by adamrusted** [comment]
> Unfortunately all the links to the vector files are broken. 🙁

Yeah, the download links are *very* temperamental, there have been odd occasions where I've been able to get SVGs / EPSs, but currently seem to be down. Now comparing Wikipedia SVGs against the PNG/JPG images here, and linking to this as source in the hopes that links get fixed in future.

**Comment by PeterShaggyNoble** [comment]
Linking #2526 here for further discussion on using the launcher icon rather than the wordmark. I'd still be in favour of keeping the icon.

**Comment by PeterShaggyNoble** [comment]
Any of the other @simple-icons/maintainers have any thoughts on whether we stick with the icon or go with the wordmark?

**Comment by ericcornelissen** [comment]
Not sure what the context is for switching to the wordmark, I would also still expect "the launcher icons" 🤔

**Comment by adamrusted** [comment]
The only reason I swapped was because in terms of 'brand logos' they only list the wordmark, with the app launcher icon being explicitly used for just that - the app launcher. Happy to stick with that for now though.

**Comment by ericcornelissen** [comment]
In that case I suppose this is a continuation of #2526, in which case I'm happy to switch to the wordmark but would still expect the app launcher as per my comment there.

**Comment by PeterShaggyNoble** [comment]
That's 2 votes for the icon and 1 for the wordmark; anyone else?

**Comment by mondeja** [comment]
I also vote for the icon.

**Comment by adamrusted** [comment]
Updated to restore the 'app icon' version. I've just tried rebuilding myself, and there's only minor stylistic differences - so happy to stick with existing icon. Could another @simple-icons/maintainers look over this and merge?

**Comment by PeterShaggyNoble** [comment]
So, it's just the `hex` & `source` we're updating then?

The source should probably be https://partnermarketinghub.withgoogle.com/brands/android-auto/ and, although I agree with the choice of Android Green and advocated for it initially, a good case was made for Google Blue at the time so let's see what the others think first.

**Comment by adamrusted** [comment]
Should be good to go. After all that, it's just the source we're updating in this PR 😅

**Comment by PeterShaggyNoble** [comment]
After all that! 😆 Given the debate around the colour last time, let's hear from the other @simple-icons/maintainers before merging. I'm still in favour of Android Green as the _brand_ colour, rather than Google Blue, which is the primary colour of the icon.

**Comment by service-paradis** [comment]
I would choose the Android Green `#3DDC84` also for this one. It is the primary color mentioned at https://partnermarketinghub.withgoogle.com/brands/android-auto/visual-identity/color-palette/

**Review by ericcornelissen — APPROVED** [review]
With that, I'll just merge this. Thanks for your work @adamrusted :smile:

**Pull request merged**
