### PR TITLE
Added Star Trek

### LINKED ISSUE #4417: Startrek Icons
**Name:** = Startrek!
**Website:** = https://intl.startrek.com/
**Alexa rank:** = 80,346

**Official resources for icon and color:** I dont know what this is

### PR DESCRIPTION
**Pull request by adamrusted**
startrek

**Issue:** Closes #4417
**Alexa rank:** [81.860](https://www.alexa.com/siteinfo/startrek.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Official SVG embedded in navbar of website.
Colour taken from hover state of icon.

### CODE REVIEW

**Review by mondeja — APPROVED** [review]
Easy peasy :rocket:

**Comment by GotNoMana** [comment]
yay!

**Comment by fbernhart** [comment]
@GotNoMana No. We're merging the `develop` branch into the `master` branch every Sunday. So it should be available on the website by next Sunday.

**Comment by GotNoMana** [comment]
to lovely, thankyou.

**Pull request merged**
