### PR TITLE
Updated Cirrus CI

### PR DESCRIPTION
**Pull request by fbernhart**
cirrusci

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
I've rebuilt from source and is passing the linter with 3 decimals of precision. Feel free to use the path @fbernhart:

```svg
M19.422.453a1.113 1.113 0 0 0-1.113 1.115 1.113 1.113 0 0 0 1.112 1.114c1.31 0 2.35 1.042 2.35 2.363 0 1.32-1.04 2.363-2.35 2.363H1.112A1.113 1.113 0 0 0 0 8.52a1.113 1.113 0 0 0 1.113 1.117h18.31c1.308 0 2.35 1.042 2.35 2.363 0 1.32-1.042 2.363-2.35 2.363H1.112A1.113 1.113 0 0 0 0 15.48a1.113 1.113 0 0 0 1.113 1.112h18.31c1.308 0 2.35 1.042 2.35 2.363 0 1.32-1.042 2.363-2.35 2.363H1.112A1.113 1.113 0 0 0 0 22.432a1.113 1.113 0 0 0 1.113 1.115h18.31a1.113 1.113 0 0 0 .206-.022c2.42-.112 4.37-2.12 4.37-4.57 0-1.393-.642-2.634-1.63-3.478C23.356 14.632 24 13.393 24 12c0-1.393-.643-2.632-1.63-3.477C23.357 7.68 24 6.438 24 5.045c0-2.52-2.06-4.592-4.578-4.592z
```

Also, should we use the `--md-primary-fg-color` CSS variable of their website as the brand color?

image

**Comment by fbernhart** [comment]
@mondeja Thanks a lot! I've now used your path and it looks perfect! 🚀

**Comment by mondeja** [comment]
What about the color change, do you think that is right?

**Comment by fbernhart** [comment]
@mondeja Sorry, forgot about the color.

Yes, I agree! 👍🏼

**Review by mondeja — APPROVED** [review]
Perfect, let's go ahead with this :tada:

**Pull request merged**
