### PR TITLE
Adobe Stock

### PR DESCRIPTION
**Pull request by fanatiicx**
simpleicons

**Issue:** [#5088](https://github.com/simple-icons/simple-icons/issues/5088)
**Alexa rank:** 40

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Used the hex value from [original comment](https://github.com/simple-icons/simple-icons/issues/5088#issuecomment-782899580)

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one on, @fanatiicx 👍🏻

Note though that [the original (in black under your version in red) isn't quite a perfect square](https://user-images.githubusercontent.com/15157491/123417097-434c5080-d5af-11eb-8320-09e64a45036e.png).

Also, could you update the source URL to just [the website](https://stock.adobe.com/), please?

**Comment by fanatiicx** [comment]
simpleicons (1)

@PeterShaggyNoble Oops, I didn't realise that it wasn't a perfect square!

I've made that change with an updated preview image, and updated the source URL to just the website.

Please let me know if any more changes are needed.

**Comment by PeterShaggyNoble** [comment]
Oh, I remember this one now; it's a nasty one with a tonne of excess points in the lettering. Tried to clean it up myself a while ago with little success so I think we'll have to run with it. We should, at least, though, be able to clean up the points in the corners of the square either by redrawing it or borrowing it from one of the other Adobe icons. Also, I'm seeing [some imperfections in the lettering](https://user-images.githubusercontent.com/15157491/123435172-2f134e00-d5c5-11eb-87f4-2bf390e66499.png) (your version in red), could you have a look at that, please?

**Comment by fanatiicx** [comment]
@PeterShaggyNoble Oh, those imperfections might have resulted from selecting the "join nodes" button. I skipped that step this time.

Please let me know if the alignment looks better now. Otherwise, I will borrow the square from one of the other Adobe icons and try to line them up as closely as possible. 

simpleicons (2)

**Comment by service-paradis** [comment]
@simple-icons/icon-review I was curious if the latest changes was reviewed and if there was something else needed in order to merge this PR.

**Comment by adamrusted** [comment]
Hey @fanatiicx and @service-paradis - just had a quick look at this one.

image

There appears to be some differences between your icon (black) and the website header (red) which should be easily fixed by upping the precision on SVGO when you edit the file down. Would you mind taking another look, and if not - we can look to take over this PR.

**Review by adamrusted — CHANGES_REQUESTED** [review]
Hey @fanatiicx and @service-paradis - just had a quick look at this one.

image

There appears to be some differences between your icon (black) and the website header (red) which should be easily fixed by upping the precision on SVGO when you edit the file down. Would you mind taking another look, and if not - we can look to take over this PR.

**Comment by LitoMore** [comment]
BTW, there is another PR for Adobe Stock.

- #8854

**Comment by adamrusted** [comment]
> BTW, there is another PR for Adobe Stock.

Let me go and review that one then...

**Comment by adamrusted** [comment]
Closing this, given there's a newer PR for Adobe Stock. Doesn't seem fair for @fanatiicx to drag this back up just to make changes!

**Pull request closed without merging**
