### PR TITLE
Added Ram Trucks

### PR DESCRIPTION
**Pull request by adamrusted**
ram

**Issue:** Contributes to #4578
**Alexa rank:** [19,995](https://www.alexa.com/siteinfo/ramtrucks.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Added as part of the Stellantis review, given the Alexa rank is high enough for inclusion.
~Alternative name is just `RAM`, though Stellantis and Ram trucks seem to go by the full name in most places.~

#### Previous Treatment
ramtrucks

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Looks like we may need to include the wordmark here, too: http://www.fcaci.com/x/v10_images/ram/Ram_Brand_Mark_Guidelines.pdf

For the name, I think we can just go with "Ram" as they only use the full name in a few places on their site and usually as a noun rather than part of their name. [Wikipedia](https://en.wikipedia.org/wiki/Ram_Trucks) claims it should be stylised as "RAM" but I'm not seeing that treatment anywhere on Ram's own site, nor Stellantis'.

**Comment by adamrusted** [comment]
@PeterShaggyNoble - should be updated.

**Comment by PeterShaggyNoble** [comment]
SVG looks spot on to me when compared to [this EPS](http://www.fcaci.com/x/v10_images/ram/RAM_Blk_Vert.zip). However, could you see if you could clean up any of the excess & duplicated points before we merge it?

**Comment by adamrusted** [comment]
@PeterShaggyNoble - that should be a bit better. Reduced down as many points as possible without ruining the quality of the image.

**Comment by PeterShaggyNoble** [comment]
🤔 Sorry, @adamrusted, I think we may need to bring back some of the points in the shield as removing them has introduced some minor discrepancies in [the bottom](https://user-images.githubusercontent.com/15157491/109041321-cbd0e800-76c6-11eb-9e86-d0cdb1d6c478.png) (yours in red) and on the inside of the vertical lines of the outer shape.

**Comment by adamrusted** [comment]
@PeterShaggyNoble that should be a bit better. Not been _quite_ as ruthless with the excess points this time round 😅

**Review by PeterShaggyNoble — APPROVED** [review]
Looks perfect to me now, @adamrusted; nice work 👍🏻

**Pull request merged**
