### PR TITLE
Add Construct 3 Icon

### LINKED ISSUE #5506: Request: Construct 3 Icon
**Brand Name:** Construct 3
**Website:** https://www.construct.net/
**Alexa rank:** 33595

Construct 3 is a popular game engine by Scirra comparable to Godot or Unity

**Official resources for icon and color:**

### Media kit

Media kit and guidelines: https://www.construct.net/en/downloads/press-kit.zip

Full color and Monochrome variations (vector files included in media kit):

<div>

image image

</div>

### Colors

Logo primary color: `#00ffda`

Logo secondary color: `#a5bac8`

Logo highlight color: `#dae8f7`

Preferred dark background: `#32373c`

### PR DESCRIPTION
**Pull request by DenverCoder1**
construct3-preview

**Issue:** Resolves #5506 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Note: Construct 3 has two monochrome variations, one for light background and one for dark background. 

**The dark background one was selected** since the guidelines seem to have a preference for dark background.

image

Press kit direct link: https://www.construct.net/en/downloads/press-kit.zip

**File url used within press kit:** `/print vector (CMYK)/C3logo-monochrome-darkBG-CMYK.ai`

As suggested by @PeterShaggyNoble, the color is now the main logo color `#00ffda`.

<details>
<summary><b>Preview with dark gray instead of main color so that background is dark</b></summary>

construct3-preview

</details>

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @DenverCoder1 and thanks for the contribution 🙂

Just so we can compare like with like in case there are subtle differences between all the files, which one exactly did you base your icon on?

For the colour, I think the main one is the correct choice for our package, regardless of how we may use it ourselves.

Also, for the 2 links, could you update to use just https://www.construct.net/ instead, which includes a link to the press kit in the footer, in case they ever change the direct URL to it?

**Comment by DenverCoder1** [comment]
@PeterShaggyNoble I have made the changes :+1:

The file I made the SVG from was `/print vector (CMYK)/C3logo-monochrome-darkBG-CMYK.ai`

**Comment by PeterShaggyNoble** [comment]
Thanks, @DenverCoder1. I'm noticing some small differences between your version and that source - [example](https://user-images.githubusercontent.com/15157491/115743712-d091df80-a389-11eb-9081-80a5c25ff2c3.png), with ours in red. A number of excess points also seem to have been introduced in some of the curves and corners of your version, too. Would you mind having another look to see if you can fix those things up?

Also, there are some changes to `package-lock.json` included in this PR that will need to be reverted.

**Comment by DenverCoder1** [comment]
@PeterShaggyNoble Sorry about the package-lock.json file. It's restored now. I attempted to convert the logo again using Inkscape instead of Photopea and I think it should be good this time.

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @DenverCoder1.

Could you have a another quick look at it, though, your new version has been stretched horizontally to fill the canvas; your first version with the width scaled relative to the height.

**Comment by DenverCoder1** [comment]
Of course, I will correct that

**Comment by DenverCoder1** [comment]
@PeterShaggyNoble I have made the adjustment, it should be right this time!

**Comment by PeterShaggyNoble** [comment]
Thanks, @DenverCoder1. I'm seeing [a _hairline_ thin difference](https://user-images.githubusercontent.com/15157491/116419941-6c619680-a835-11eb-9664-047bfee38331.png) between your version (in red) and the source, though. This may simply, but not necessarily, be down to the precision being too low when it was optimised. Would you mind have another quick look at it?

**Comment by DenverCoder1** [comment]
@PeterShaggyNoble I'm not sure how to fix it since I don't think I did anything unusual when creating the last version. I'd be fine with allowing this issue to be taken over by someone else so it can be finished.

**Comment by DenverCoder1** [comment]
@PeterShaggyNoble I have done one more attempt. Hopefully it is done correctly this time. If it still requires changes, I'll let someone else take over for this icon.

**Review by PeterShaggyNoble — APPROVED** [review]
All looks good to me now, @DenverCoder1, nice work 👍🏻 Thanks for your continued efforts on this one.

**Comment by PeterShaggyNoble** [comment]
Oop! Should have checked the end of the page before leaving that review 🤦🏻‍♂️ Can you rebase your branch with our `develop` branch and then remove the " icon" from the SVG's `title` tag, please? Once that's done then this can be merged straight in.

**Comment by DenverCoder1** [comment]
@PeterShaggyNoble I have made the change :+1:

**Comment by PeterShaggyNoble** [comment]
Thanks again, @DenverCoder1 👍🏻

**Pull request merged**
