### PR TITLE
Add MDX icon

### PR DESCRIPTION
**Pull request by sisp**
MDX icon preview

**Issue:** n/a
**GitHub Stars:** [12.8k](https://github.com/mdx-js/mdx)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The icon is based on the official [MDX logo](https://github.com/mdx-js/mdx/blob/b8a76c95deb14f7297bafdac1aa3eddd2b0fbb8f/docs/_static/icon.svg). The text was drawn using path strokes which I converted to filled paths with some manual post-processing to remove redundant path points. The hex value is the color code used for the rectangle in the original SVG. I think it's not entirely clear what MDX' brand color is. My other guess would have been this shade of yellow used on their [website](https://mdxjs.com/), but since the original SVG has a color, I think it's better to just use that one.

### CODE REVIEW

**Review by sachinraja — CHANGES_REQUESTED** [review]
Edit: this is incorrect, it's due to the CSS styles of the source
---
When you converted the text using stroke to path, it got enlarged:
image

**Review by sachinraja — APPROVED** [review]

**Comment by sisp** [comment]
@sachinraja I'm not sure I understand your comment above. The icon I committed is visually identical to the original one. I don't see any issues with the stroke-to-path conversion. Despite your comment, you've merged this PR :thinking:. I'm a bit confused now :confused:.

**Comment by sachinraja** [comment]
Ignore that comment, I meant that my review was incorrect.

**Comment by sisp** [comment]
Ah, I see. Thanks for the clarification. And for merging the PR. 🙂

**Pull request merged**
