### PR TITLE
Add Apache Spark icon (#1329)

### PR DESCRIPTION
**Pull request by phatbhoy67**
**Issue: #1329 **

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Extracted broken "star" from from official [wordmark logo](https://commons.wikimedia.org/wiki/File:Apache_Spark_logo.svg). The wikipedia version is converted from the [official .eps](https://spark.apache.org/images/) version.

Manually edited to complete "star" by following the "V" made from the "k" in "Spark" to match the [favicon](https://spark.apache.org/favicon.ico).

Predominant brand colour used on [Apache Spark website](https://spark.apache.org/) is blue, chosen hex value `#2FA4E7` as it appears to be the colour most used (changed my mind 😆).

Built on GitPod, working as expected.

### CODE REVIEW

**Comment by birjolaxew** [comment]
I think that we would prefer using the orange from the logo as their color. Their website is predominantly blue, but I think the brand itself is mostly connected to the orange of the star in their wordmark. Thoughts @ericcornelissen?

**Comment by ericcornelissen** [comment]
Its a tough choice but I personally associate orange with Spark more than blue. It's an easy change later on so I think it is fine if we go with orange for now :+1:

**Comment by phatbhoy67** [comment]
Hey @ericcornelissen @birjolaxew I've updated the hex value to `#E25A1C` which is extracted from the official [.eps version](https://spark.apache.org/images/spark-logo.eps) of the logo.

**Comment by birjolaxew** [comment]
:+1: Looks good! Thanks a lot for your work on the vector and this PR!

**Pull request merged**
