### PR TITLE
Add ComicFury

### LINKED ISSUE #9998: Request: ComicFury
### Brand Name

ComicFury

### Website

https://comicfury.com

### Popularity Metric

ComicFury has a ranking of 78,429 on https://www.similarweb.com/website/comicfury.com/#overview

### Official Resources for Icon and Color

https://comicfury.com/images/gator-icon-black.png
https://comicfury.com/images/cf-diamond.png

### Additional Comments

There are two versions of the new logo. They both feature the website's mascot, the gator. The website itself seems to host different artist contributed interpretations of the mascot but the black and white geometric design appears to be the official logo.

### PR DESCRIPTION
**Pull request by tonyb650**
**Issue:** closes #9998 

**Similarweb rank:** 78,429

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Used requester's description regarding color and source of artwork.

### CODE REVIEW

**Comment by tonyb650** [comment]
Sure thing.

**Review by PeterShaggyNoble — APPROVED** [review]
SVG looks good to me, @tonyb650, nice work 👍🏻

For the colour, though, I don't know that black is the right choice 🤔 From their website, I'd expect either the green from the text of [their full logo](https://comicfury.com/images/mascots/killersteakgator.png), or maybe one of the (blue-)greys from the site itself. What do you think?

**Comment by tonyb650** [comment]
@PeterShaggyNoble, I updated to the green color used on the favicon: #79BD42

This seems like the most official(?) https://comicfury.com/images/favicon.png

The cartooney "logo" graphics that they rotate through seem to all use a green gradient, so it's hard to know exactly which shade is best.

**Review by PeterShaggyNoble — APPROVED** [review]
In the absence of anything concrete to go on, I'd say that's definitely as good a choice as any. If anyone has a better suggestion then they can sumbit it in a new PR.

**Pull request merged**
