### PR TITLE
Updated Gmail

### PR DESCRIPTION
**Pull request by adamrusted**
gmail

**Issue:** Contributes to #4205
**Alexa rank:** N/A

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Updated source to [2020 variant](https://fonts.gstatic.com/s/i/productlogos/gmail_2020q4/v8/192px.svg).
Rebuilt icon from source.
Main colour of `#EA4335` pulled from logo (also used on Gmail client).

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
@adamrusted, can you update the source to the page you found the SVG on, please?

**Comment by adamrusted** [comment]
> @adamrusted, can you update the source to the page you found the SVG on, please?

Believe I actually came across this one *by accident*. The URL used actually links to a load of the "core" projects if you replace `gmail` with other products.

**Review by PeterShaggyNoble — APPROVED** [review]
SVG looks spot-on to me, @adamrusted and I agree with the colour choice as it is Google's primary red. Will leave this for one of the other @simple-icons/maintainers to merge, though, just in case a better source can be found.

**Comment by PeterShaggyNoble** [comment]
In the absence of a better source, I'm going to merge this in as-is, we can always update the source at a later date.

**Pull request merged**
