### PR TITLE
Add ImprovMX Icon

### LINKED ISSUE #9003: [Icon Request] ImprovMX
### Brand Name

ImprovMX

### Website

https://improvmx.com/

### Popularity Metric

Similarweb rank: 506,280

A (fairly popular) email forwarding service that is featured by Vercel in a guide about sending emails with a purchased domain. Vercel also has set up DNS presents for ImproMX, suggesting its popularity among similar offerings.

https://vercel.com/guides/using-email-with-your-vercel-domain

### Official Resources for Icon and Color

Taken from the website's header.
Branding color: `#2FBEFF`

```svg
<svg width="28" height="29" xmlns="http://www.w3.org/2000/svg">
  <g fill="#2FBEFF" fill-rule="evenodd">
    <path d="M17.6 25.07a5.43 5.43 0 0 1-7.73 0 6.9 6.9 0 0 0-3.93-1.94v1.51c1.04.2 2.05.7 2.86 1.5a6.93 6.93 0 0 0 4.93 2.05c1.86 0 3.61-.73 4.93-2.05a5.42 5.42 0 0 1 2.7-1.46v-1.53c-1.38.23-2.7.86-3.77 1.92"></path><path d="M17.6 21.25a5.43 5.43 0 0 1-7.73 0 6.99 6.99 0 0 0-9.87 0l1.07 1.07a5.47 5.47 0 0 1 7.73 0 6.93 6.93 0 0 0 4.93 2.05c1.86 0 3.61-.73 4.93-2.05a5.47 5.47 0 0 1 7.73 0l1.07-1.07a6.99 6.99 0 0 0-9.87 0"></path><path d="M13.78 8.46l-5.54 3-.02-5.88h1.95l7.2-.03h1.95l.01 5.87-5.55-2.96zm2.02-6.9L15.81 4l-4.09.01V1.57h4.08zm5.1 10.7l-.03-8.27h-3.5L17.36 0l-7.2.02v4h-3.5l.02 8.27-3.25 1.76 1.08 3.9a6.8 6.8 0 0 1 1.63.08l-.88-3.2L13 10.65l.02 10.04h1.56l-.03-10.04 7.77 4.14-.84 3.12a6.8 6.8 0 0 1 1.58.1L24.16 14l-3.27-1.74z"></path>
  </g>
</svg>
```

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by RiteshK-611**
**Issue:** closes #9003

**Similarweb rank:**
 Similarweb rank [506,280](https://www.similarweb.com/website/improvmx.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This change resolves issue #9003  by adding ImprovMX logo in improvmx.svg file and by updating simple-icons.json file with icon's data

### Preview
improvmx

### CODE REVIEW

**Comment by adamrusted** [comment]
@RiteshK-611 - the SimilarWeb rank is just outside contribution criteria for this one, so we can't accept it on that. Is there another popularity metric (GitHub stars, etc) that we can use?

**Comment by mwskwong** [comment]
> @RiteshK-611 - the SimilarWeb rank is just outside contribution criteria for this one, so we can't accept it on that. Is there another popularity metric (GitHub stars, etc) that we can use?

Does this help? (taken from my original issue)

> A (fairly popular) email forwarding service that is featured by Vercel in a guide about sending emails with a purchased domain. Vercel also has set up DNS presents for ImproMX, suggesting its popularity among similar offerings.

**Comment by adamrusted** [comment]
Looks like it just took some time for the Vercel post to hit the SimilarWeb ranking. Its now in scope.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @RiteshK-611 🎉

**Pull request merged**
