### PR TITLE
Update Brave icon

### PR DESCRIPTION
**Pull request by rawrmaan**
**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json` **not necessary, no metadata change**
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

New icon respects the wishes of the Brave team to not use the "alternative" inverted icon, which is the one included in this package: https://twitter.com/BraveSampson/status/1216555294408552448

This commit updates to the non-inverted Brave logo, while retaining the same official color. SVG source also remains the same: https://brave.com/brave-branding-assets/

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @rawrmaan.

Can I ask which file you based your version off? Using `Brave-Logo-Color/Brave-logo-color-rgb.svg` from [this zip](https://brave.com/wp-content/uploads/2019/11/Brave-Logo-Package.zip), I see some differences between the 2 - original in grey below, yours overlaid in red.

image

**Comment by rawrmaan** [comment]
Ah. I chose `brave_lion.svg` from the same zip, then used Sketch to resize it to 24x24 to replace the gradient with a solid fill.

**Comment by rawrmaan** [comment]
Wait no, it was [this zip](https://brave.com/wp-content/uploads/2019/11/Brave-Logo-Package.zip).

**Comment by PeterShaggyNoble** [comment]
That's the same zip I linked to above, which doesn't contain a `brave_lion.svg` file. There *is*, however, a `barve_lion.svg` file in [this zip](https://brave.com/wp-content/uploads/2018/10/PublisherMediaAssets.zip), linked from their [media assets page](https://brave.com/media-assets/). As the files on [branding assets page](https://brave.com/brave-branding-assets/) postdate those on that page, we should probably use them - could you update your SVG when you get a chance?

**Comment by rawrmaan** [comment]
Wow, this is really confusing. So I actually meant to link [this zip](https://brave.com/wp-content/uploads/2019/01/BrandBrave.zip), which is _also_ from https://brave.com/brave-branding-assets/ -- it's the one that downloads if you click on the big Brave logo. The `brave_lion.svg` in there is the one that I used. Although it's from Jan 2019, it is the one that was linked to me by a Brave team member in [this tweet](https://twitter.com/BraveSampson/status/1216543371336077315). What do you think?

**Comment by PeterShaggyNoble** [comment]
Wow, that *is* confusing! 😆 I don't see a direct link to any of the zips in that Twitter conversation so I'd still err on the side of the latest, Nov. 2019 zip. But, given the confusion with 3 different zip files, I'd suggest reaching out to Sampson, or one of the other @brave team members, again for final clarification.

**Comment by jonathansampson** [comment]
@PeterShaggyNoble @rawrmaan I tend to link to [2019/01/BrandBrave.zip](https://brave.com/wp-content/uploads/2019/01/BrandBrave.zip) since it contains lion-only imagery. While [2019/11/Brave-Logo-Package.zip](https://brave.com/wp-content/uploads/2019/11/Brave-Logo-Package.zip) is newer, it contains only logo+name imagery (which will require editing).

Hope this helps!

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to clarify, @jonathansampson.

With feedback from an official source, I think we're OK to go with `brave_lion.svg` from the Jan. 2019 zip. However, the version in the PR is slightly off horizontal centre (expected result in grey below). If you can fix that, @rawrmaan; this should be good to go.

Brave

**Comment by jonathansampson** [comment]
Thank you for catching the imbalance in the position of the logo, @PeterShaggyNoble. I'll pass this input along to our design team and see if we cant have those ZIPs refreshed a.s.a.p.

**Comment by rawrmaan** [comment]
@PeterShaggyNoble Alright, horizontal centering fixed!

**Comment by PeterShaggyNoble** [comment]
Thanks for your work on this one, @rawrmaan; looks good now 👍

**Pull request merged**
