### PR TITLE
Add Robot Framework

### PR DESCRIPTION
**Pull request by JNuutinen**
robotframework

**Issue:** Closes [#5010](https://github.com/simple-icons/simple-icons/issues/5010)
**Alexa rank:** [164,278](https://www.alexa.com/siteinfo/robotframework.org)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I picked the hex value `#000000` according to Robot Framework's [brand guidelines](https://github.com/robotframework/visual-identity/blob/fadf8cda9f79ea31987a214f0047cca9626327b7/robot-framework-brand-guidelines.pdf), which dictate that either black or white should be used for the icon.

I used the [source svg](https://github.com/robotframework/visual-identity/blob/fadf8cda9f79ea31987a214f0047cca9626327b7/logo/robot-framework.svg) and then removed whitespace, minified and added the required attributes.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @JNuutinen and thanks for taking this one on 👍🏻

Could you have another look at it, though, as I'm noticing a small difference in the left eye between your version (in red) and the source.

For the source, as the repo contains all the brand info, including the colour, I think we should go with https://github.com/robotframework/visual-identity instead.

Also, for guidelines, I think we should go with the commit URL to ensure we're always linking to the latest version so could you update that link to https://github.com/robotframework/visual-identity/blob/master/robot-framework-brand-guidelines.pdf?

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @JNuutinen?

**Comment by JNuutinen** [comment]
Sorry about not responding! Yes, I'll fix this 👍

**Comment by JNuutinen** [comment]
@PeterShaggyNoble This should now be fixed, I verified the icon by overlaying it with the original like in your comment and didn't see any differences (hoping I did it right..).

I also updated the metadata to be more sensible, as you suggested.
If this is good to go, do you want me to squash to a single commit?

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @JNuutinen. However I'm still seeing the same difference as above when overlaying the original (black) on top of yours (red).

**Comment by JNuutinen** [comment]
@PeterShaggyNoble Ah you are right, sorry about that.
I did some testing, and seems that SVGO's minification made that change! Upping the precision from 3 to 5 seems to fix the problem. I did the comparison before minification, SVG noob mistake.

**Comment by PeterShaggyNoble** [comment]
Thanks for the quick update, @JNuutinen.

Looks like a precision of 4 should suffice here, though:
```
M4.9565 10.2246c0-1.8766 1.5257-3.4023 3.4-3.4023 1.8766 0 3.4024 1.5257 3.4024 3.4023 0 .6838-.5526 1.2364-1.2341 1.2364-.6818 0-1.2344-.5526-1.2344-1.2364 0-.513-.4185-.9296-.9338-.9296-.5129 0-.9317.4165-.9317.9296 0 .6838-.5523 1.2364-1.234 1.2364-.6818 0-1.2344-.5526-1.2344-1.2364m14.0868 5.717c0 .6842-.5524 1.2363-1.2341 1.2363H6.3575c-.6818 0-1.2344-.552-1.2344-1.2363 0-.6837.5526-1.2363 1.2344-1.2363h11.4517c.6817 0 1.234.5526 1.234 1.2363m-5.351-5.0244c-.3814-.5657-.2323-1.3328.3334-1.7143l2.8628-1.9334c.5613-.3902 1.3329-.2324 1.7144.3289.3815.5654.2323 1.3329-.3334 1.7144l-2.8628 1.9333a1.2143 1.2143 0 0 1-.6884.2149c-.3968 0-.787-.1929-1.026-.5438m7.8393 7.6018a.8815.8815 0 0 1-.258.6227l-2.1277 2.1277a.8819.8819 0 0 1-.623.258H5.4772a.8819.8819 0 0 1-.623-.258l-2.1277-2.1277a.8815.8815 0 0 1-.258-.6227V5.4818a.8798.8798 0 0 1 .258-.6228l2.1277-2.1282a.8816.8816 0 0 1 .623-.2578h13.0456a.8816.8816 0 0 1 .623.2578l2.1277 2.1282a.8798.8798 0 0 1 .258.6228zm1.811-15.0835L20.5644.6577A2.245 2.245 0 0 0 18.9775 0H5.0207A2.2448 2.2448 0 0 0 3.433.658L.657 3.4359A2.2446 2.2446 0 0 0 0 5.0228v13.9547c0 .5953.2366 1.1667.6575 1.5872l2.778 2.7779c.421.421.9918.6573 1.5871.6573h13.9548a2.245 2.245 0 0 0 1.5872-.6573l2.7779-2.7779A2.2438 2.2438 0 0 0 24 18.9775V5.023a2.2448 2.2448 0 0 0-.6575-1.5875Z
```

**Comment by JNuutinen** [comment]
Thanks, the path you provided does indeed suffice without overlap.
I wonder how that is so, because I tried first with a precision of 4 and I still had some overlap (albeit less than with 3), so that's why I ended up with 5. Might be I messed something up.

Anyway, I updated the icon with the path you provided.

**Comment by PeterShaggyNoble** [comment]
> I wonder how that is so

On rare occasions it can happen that different versions or implementations of SVGO can produce different results. I've noticed it a few times between SVGOMG and the Inkscape plugin I use.

> Anyway, I updated the icon with the path you provided

As you're using my path now, we'll need one of the other @simple-icons/maintainers to review this before merging.

**Review by adamrusted — APPROVED** [review]
There is a [_single_ point](https://user-images.githubusercontent.com/1830867/110108334-f3e5d880-7da3-11eb-90c7-be6123633f23.png) that can be removed, but otherwise this is spot on. If you're not able to remove that point though, I'm happy to approve as-is. Will await feedback from either of you before I merge this though. Thanks to both @JNuutinen and @PeterShaggyNoble for your work on this! 💪

**Comment by JNuutinen** [comment]
I see what you mean, the lower part of the right eye is a bit asymmetrical and it contains that one extra node.
I tried to remove it, but then the curve's center node needs adjusting but I'm not really sure how to do that precisely instead of just eyeballing it... Would you be able to do it, @PeterShaggyNoble?

**Comment by adamrusted** [comment]
Let me take a look @JNuutinen - in Illustrator, you're able to just select those three points and 'simplify' the path - though I'm not sure how you'd go about that process in Inkscape or Affinity.

**Comment by adamrusted** [comment]
@JNuutinen - played around with this in Illustrator and got the path below. I'm happy to push it to this PR if that's easier for you?

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Robot Framework icon</title><path d="M4.9565 10.2246c0-1.8766 1.5257-3.4023 3.4-3.4023 1.8766 0 3.4024 1.5257 3.4024 3.4023 0 .6838-.5526 1.2364-1.2341 1.2364-.6818 0-1.2344-.5526-1.2344-1.2364 0-.513-.4185-.9296-.9338-.9296-.5129 0-.9317.4165-.9317.9296 0 .6838-.5523 1.2364-1.234 1.2364-.6818 0-1.2344-.5526-1.2344-1.2364m14.0868 5.717c0 .6842-.5524 1.2363-1.2341 1.2363H6.3575c-.6818 0-1.2344-.552-1.2344-1.2363 0-.6837.5526-1.2363 1.2344-1.2363h11.4517c.6817 0 1.234.5526 1.234 1.2363m-5.351-5.0244c-.3814-.5657-.2323-1.3328.3334-1.7143l2.8628-1.9334c.5613-.3902 1.3329-.2324 1.7144.3289.3815.5654.2323 1.3329-.3334 1.7144l-2.8628 1.9333c-.5442.3831-1.3348.2379-1.7144-.3289zm7.8393 7.6018a.8815.8815 0 0 1-.258.6227l-2.1277 2.1277a.8822.8822 0 0 1-.623.258H5.4772a.8822.8822 0 0 1-.623-.258l-2.1277-2.1277a.8815.8815 0 0 1-.258-.6227V5.4818a.8797.8797 0 0 1 .258-.6228l2.1277-2.1282a.8816.8816 0 0 1 .623-.2578h13.0456a.8816.8816 0 0 1 .623.2578l2.1277 2.1282a.8797.8797 0 0 1 .258.6228V18.519zm1.811-15.0835L20.5644.6577A2.2454 2.2454 0 0 0 18.9775 0H5.0207A2.2445 2.2445 0 0 0 3.433.658L.657 3.4359A2.2449 2.2449 0 0 0 0 5.0228v13.9547c0 .5953.2366 1.1667.6575 1.5872l2.778 2.7779c.421.421.9918.6573 1.5871.6573h13.9548a2.2448 2.2448 0 0 0 1.5872-.6573l2.7779-2.7779A2.2436 2.2436 0 0 0 24 18.9775V5.023a2.2451 2.2451 0 0 0-.6575-1.5875z"/></svg>
```

**Comment by JNuutinen** [comment]
Thanks! Sounds good, go ahead 👍

**Comment by adamrusted** [comment]
Fab - that's good to go then. Will await feedback from another @simple-icons/maintainers, as I can't review this now it's my version of the path 😅

**Comment by fbernhart** [comment]
LGTM 👍🏼  Thanks @JNuutinen for your work! As well thanks to @PeterShaggyNoble and @adamrusted for helping out. 🥇

**Pull request merged**
