### PR TITLE
Add bookmeter.com icon

### LINKED ISSUE #4824: Request: bookmeter.com (in Japanese: 読書メーター)
**Brand Name:** bookmeter (読書メーター)
**Website:** https://bookmeter.com/
**Alexa rank:** [23,152](https://www.alexa.com/siteinfo/bookmeter.com)
  

**Official resources for icon and color:**
  
  

There is [an SVG file](https://bookmeter.com/assets/common/logo-2bd6d48f3447beaa56041246b812bc2eb6e11706e1fea2ab027ac1d3420ba78d.svg) that is provided in the banner of the official website. This image includes the brand logo at the left side, but personally I don't like to use it because it seems to be too abstract (there could be many organizations that have similar logos, right?).  
Instead I'd like to convert [this PNG asset](https://bookmeter.com/images/common/profile_image.png) into SVG. It is a user's default icon who do not set their own profile icon. It's cute and quite familiar for everyone who use this website.

### PR DESCRIPTION
**Pull request by HelloRusk**
bookmeter (1)

**Issue:** Closes #4824
**Alexa rank:** [22,706](https://www.alexa.com/siteinfo/bookmeter.com)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Icon is from [this SVG](https://trista.jp/img/service/logo_bookmeter.svg) in the [corporation site](https://trista.jp/service/)

### CODE REVIEW

**Comment by adamrusted** [comment]
Hi @HelloRusk, thanks for your work on this! 🎉

Given that there is an SVG icon in the header of the [main website](https://bookmeter.com/), could you please update the source to their homepage and look to rebuild the SVG from there, as it appears that your icon (black) is larger than the actual logo (green).
image

**Review by adamrusted — CHANGES_REQUESTED** [review]
Hi @HelloRusk, thanks for your work on this! 🎉

Given that there is an SVG icon in the header of the [main website](https://bookmeter.com/), could you please update the source to their homepage and look to rebuild the SVG from there, as it appears that your icon (black) is larger than the actual logo (green).
image

**Comment by HelloRusk** [comment]
Updated version:

bookmeter (3)

I hope this one works well...

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for the quick response @HelloRusk!

There's still a _slight_ difference in your SVG, see the below image with yours in black and the source being in green.

image


I've been able to get a matching path on my end, which passes the linter - so feel free to use it.
```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Bookmeter icon</title><path d="M.678 14.262h6.089V24H.678v-9.738zm8.215 9.717h6.089V7.11H8.893v16.869zM17.234 0v24h6.089V0h-6.089z"/></svg>
```

**Comment by HelloRusk** [comment]
Oh... Sorry for bothering you. I'd like to just copy the codes you've written 😭

**Comment by adamrusted** [comment]
> Oh... Sorry for bothering you. I'd like to just copy the codes you've written 😭

No worries! Working on SVGs can be quite fiddly, a fair few of mine still need some work on them!
Thanks for working on this one, and hope you're able to work on some more in the future! 😜

Can another @simple-icons/maintainers review this, being as it's my path?

**Review by service-paradis — APPROVED** [review]
LGTM 💯 Thank you @adamrusted!
And thank you @HelloRusk for your initial contribution and your effort!

**Pull request merged**
