### PR TITLE
Add Veritas

### LINKED ISSUE #1654: Veritas Icon
**Name: Veritas Inc
**Website: www.veritas.com
**Official resources for icon and color: www.veritas.com

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Veritas

**Issue:** Closes #1654

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Colour from website stylesheet. Possible alternative: `#b30410`, obtained by converting the CMYK colour provided in their [brand guidelines](https://my.veritas.com/cs/groups/partner/documents/styleguide/mdaw/mdq5/~edisp/tus3cpeapp3855186572.pdf).

Although their guidelines don't explicitly forbid the use of the `V` on its own, as seen in their favicon, they don't explicitly *allow* it either so we may or may not be able to get away with this, instead:

[Veritas](https://github.com/simple-icons/simple-icons/files/4041015/veritas.zip)

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble thanks for your work on this one 👍 

"VeriRed" is specified on page 44 of the linked [brand guide](https://my.veritas.com/cs/groups/partner/documents/styleguide/mdaw/mdq5/~edisp/tus3cpeapp3855186572.pdf) as

```
Pantone 7621 C
cmyk: 0/98/91/30
rgb: 177/24/30
hex: b1181e
```
Can you update the hex value to `B1181E` please.

Also, the logo SVG is embedded in the same document on page one. 

The PR version is an exact match 👍 

I think it would be better to link brand guide as source rather than wikipedia.

**Comment by PeterShaggyNoble** [comment]
😮 How did I possibly miss all that?! Thanks, @phatbhoy67, updating now

**Comment by phatbhoy67** [comment]
It's good to merge @PeterShaggyNoble but I'm unsure about the failing check, are we safe to ignore that? 🤔 

I was just getting round to asking! 😆

**Comment by PeterShaggyNoble** [comment]
Yep, safe to ignore that one, @phatbhoy67. See #2420.

**Pull request merged**
