### PR TITLE
Photoprism

### LINKED ISSUE #7820: request adding photoprism icon, OSS project
### Brand Name

PhotoPrism

### Website

https://photoprism.app/

### Popularity Metric

22.5K stars on GitHub

https://github.com/photoprism/photoprism

### Official Resources for Icon and Color

logo:

https://photoprism.app/static/icons/logo.svg

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by M1scer**
canvas

**Issue:** closes #7820 

**Similarweb rank:**
27.9K stars on GitHub

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
- [Trademark](https://www.photoprism.app/trademark)
- [Logo Source](https://dl.photoprism.app/img/logo/logo.svg)
- Hex Color is not available from any source. I picked the dominant color `#531DB2` from [Trademark](https://www.photoprism.app/trademark) page. But the header color is changing while navigating the website. Maybe someonelse has an idea to get the best / correct color?

### CODE REVIEW

**Comment by LitoMore** [comment]
This looks not good to me. The corner should be the same as the original.

And we need to consider optimizing its control points after converting their strokes to outlines.

**Comment by M1scer** [comment]
Updated the corners. Should match the orignal now.

My skills editing .svg files are very limited. So i am not sure how to ptimizing the control points.

**Review by adamrusted — COMMENTED** [review]
Based on the Logo Usage section [here](https://www.photoprism.app/trademark) I would be inclined to drop them a message before we include this one, just to make sure they're happy with it's inclusion in this form. What do other @simple-icons/icon-review think?

**Comment by adamrusted** [comment]
image
In order to provide the icon for our repository, we need to alter the source file they provide. I'll close this one out for now - and if someone can get their permission - we can re-visit.

**Pull request closed without merging**
