### PR TITLE
Updated Unilever

### PR DESCRIPTION
**Pull request by adamrusted**
unilever

**Issue:** #3169
**Alexa rank:** [21,643](https://www.alexa.com/siteinfo/unilever.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Changed source to international homepage for Unilever.
Logo seems to be thinner than variation previously used on Simple Icons - have replaced with thinner variation and updated svglint-ignored.

### CODE REVIEW

**Comment by mondeja** [comment]
What source have you used @adamrusted?

**Comment by adamrusted** [comment]
@mondeja - logo used can be found as an embeded SVG [here](https://www.unilever.co.uk/about/who-we-are/our-logo/). On the page there are interactive elements, though there is a core SVG. I can update source to give specific URL if necessary?

**Comment by mondeja** [comment]
> I can update source to give specific URL if necessary?

Yes :+1: Please, update the source in `_data/simple-icons.json` with that URL :pray:

**Comment by mondeja** [comment]
I'm seeing some differences in different parts of the path between the source (blue) and your version (black). I don't know why, maybe it's the optimization process? :thinking: Could you compare them also to make sure?

image
image

**Comment by adamrusted** [comment]
@mondeja rebuilt from source with a precision of 4. At 3 some of the circles distort.

**Review by mondeja — APPROVED** [review]
> At 3 some of the circles distort.

You're right! Now it fits perfect. Thank you for this update @adamrusted :tada:

**Pull request merged**
