### PR TITLE
Add KnowledgeBase icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** N/A
**Website:** https://www.knowledgebase.ai/
**Guidelines:** https://www.knowledgebase.ai/design
**Alexa rank:** [~400k](https://www.alexa.com/siteinfo/knowledgebase.ai)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I took the first brand color mentioned in https://www.knowledgebase.ai/design
- I took the mark icon found at https://www.knowledgebase.ai/design
- I used Inkscape to scale
- I used https://jakearchibald.github.io/svgomg/ to optimize

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I'm seeing a [hairline thin difference](https://user-images.githubusercontent.com/15157491/108539256-a6fbff80-72d7-11eb-8a26-27ef5c7b197d.png) in the bottom right corner between your version (in red) and the `Mark_RGB_Black.svg` file in the zip, @service-paradis which is probably just a precision issue. There's also [a minor imperfection](https://user-images.githubusercontent.com/15157491/108539556-0fe37780-72d8-11eb-8264-752bf8199f23.png) in the centre of the dip of the "v" shape in the source file if you want to try fixing it.

**Comment by service-paradis** [comment]
Thanks for the feedback!
I fixed the upper `v`. Now a little bit different than the original, but is now symmetrical. Is this better?

**Comment by PeterShaggyNoble** [comment]
That looks OK to me, @service-paradis but, as we're deviating from the original slightly, I'll let one of the other @simple-icons/maintainers double check it before merging.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @service-paradis 💯🎉

**Pull request merged**
