### PR TITLE
Updated Baidu

### PR DESCRIPTION
**Pull request by fbernhart**
baidu

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by adamrusted — APPROVED** [review]
This is spot on - do you mind resolving the conflicts before merging?

**Comment by mondeja** [comment]
Wait a minute, have you considered using 3 decimals as precision @fbernhart? What happened @adamrusted is that @fbernhart uploaded a lot of pull requests using 4 decimal places as precision, and we try to use 3 as much whenever we can. So ask he if he can use 3 if you see 4 decimals used in the path.

**Comment by adamrusted** [comment]
> What happened, @adamrusted, is that @fbernhart uploaded a lot of pull requests using 4 decimal places as precision, and we try to use 3 as much whenever we can. So ask he if he can use 3 if you see 4 decimals used in the path.

My bad! For reference, my 3 decimal precision path below.
```
M4.32,12.647c2.609-0.56,2.252-3.681,2.176-4.363C6.367,7.232,5.131,5.396,3.453,5.543 c-2.112,0.188-2.42,3.239-2.42,3.239C0.747,10.194,1.716,13.209,4.32,12.647 M9.164,7.416c1.44,0,2.604-1.659,2.604-3.709 C11.768,1.657,10.604,0,9.164,0C7.723,0,6.556,1.657,6.556,3.707C6.556,5.757,7.723,7.416,9.164,7.416 M15.372,7.66 c1.928,0.252,3.163-1.804,3.41-3.362c0.252-1.556-0.993-3.366-2.354-3.676c-1.368-0.314-3.075,1.875-3.229,3.303 C13.011,5.671,13.446,7.413,15.372,7.66 M23.005,10.278c0-0.745-0.617-2.992-2.914-2.992c-2.302,0-2.606,2.12-2.606,3.618 c0,1.429,0.119,3.423,2.978,3.361C23.318,14.202,23.005,11.028,23.005,10.278 M20.091,16.819c0,0-2.98-2.305-4.719-4.797 C13.01,8.348,9.66,9.844,8.54,11.71c-1.117,1.871-2.853,3.052-3.101,3.366c-0.251,0.307-3.599,2.116-2.856,5.42 c0.745,3.301,3.355,3.238,3.355,3.238s1.924,0.188,4.156-0.311c2.236-0.498,4.16,0.122,4.16,0.122s5.216,1.749,6.642-1.617 C22.323,18.566,20.091,16.819,20.091,16.819
```

**Comment by fbernhart** [comment]
Yeah, sorry for the precision mess 😅  @adamrusted At some point I started using a precision of 4 instead of 3 (although it wasn't necessary). So we're trying to correct that now in most of my PRs.


Anyway: I've found an [official SVG](https://www.baidu.com/img/baidu_85beaf5496f291521eb75ba38eacbd87.svg) of their logo, which is a better source in my opinion than Wikipedia. It's the favicon of [their website](https://www.baidu.com/).

The website as well contains [this PNG](https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png) where I've than extracted the color `#2932E1` from.

So I've now rebuilt the icon with the new SVG (and optimized it with a precision of 3 🙃:
baidu

**Review by adamrusted — APPROVED** [review]
Looks perfect to me! 🚀

**Pull request merged**
