### PR TITLE
Add Semrush Icon

### PR DESCRIPTION
**Pull request by uiuxarghya**
semrush

**Issue:** #5822 
**Alexa rank:** 1,099

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Website: https://www.semrush.com/
Brand Resources: https://brand.semrush.com/
Hex Value: `#FF642D`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @uiuxarghya :+1:

However, I'm noticing a number of differences throughout ([example](https://user-images.githubusercontent.com/15157491/120682076-f2f04000-c493-11eb-917e-ef267f2fb886.png), with your version in red). That's most likely down to the precision having been set to 1 during optimisation. Could you give that another try with a higher precision, please?

**Comment by uiuxarghya** [comment]
> Thanks for the contribution, @uiuxarghya 👍
> 
> However, I'm noticing a number of differences throughout ([example](https://user-images.githubusercontent.com/15157491/120682076-f2f04000-c493-11eb-917e-ef267f2fb886.png), with your version in red) when compared to `Semrush Logo Pack & Brand Basics\Semrush Logo Pack\1 Horizontal \RGB\Sign\semrush sign rgb.svg`. That's most likely down to the precision having been set to 1 during optimisation. Could you give that another try with a higher precision, please?

Sure I am updating the SVG with one higher precision

**Comment by uiuxarghya** [comment]
@PeterShaggyNoble 
I have tried updating the SVG but the SVG code is not changing with the increase in precision 4 or 5. 
Can you check it once?

**Review by adamrusted — CHANGES_REQUESTED** [review]
Looks like this path has been over-simplified when optimizing (see [here](https://user-images.githubusercontent.com/1830867/122023668-ad027880-cdbf-11eb-8d87-f31b5bd27f0e.png)), which again appears to be because this is optimized to 1 decimal. If you could rebuild this from source using a precision of 3 - it should (hopefully) match up a lot better.

**Comment by uiuxarghya** [comment]
I have rebuild from the source `Semrush Logo Pack\1 Horizontal\RGB\Sign\semrush sign rgb.ai`
and I have updated the Semrush Icon SVG code.

**Pull request closed without merging**
