### PR TITLE
Aircall

### PR DESCRIPTION
**Pull request by runxel**
**Issue:** –

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Svg with color taken from website header.
[Alexa rank ~28k](https://www.alexa.com/siteinfo/aircall.io)

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
@runxel, it looks like the path in this one is slightly wider than 24px.

**Comment by runxel** [comment]
Once again! Glad to have you here!
It was even worse than expected: The dimensions are not the same on each side...
But now it's fixed with correct height and centered on the viewbox.

**Comment by PeterShaggyNoble** [comment]
I'm seeing some differences in the "feet" of the `A` now, @runxel (yours in red, original in green) - is that as a result of your fixes?

**LEFT**
image

**RIGHT**
image

**Comment by runxel** [comment]
Not sure what happened there. Rebuilt the entire thing. Should be good now!

Thanks for spotting! 👍

**Comment by PeterShaggyNoble** [comment]
Looks good now, @runxel. Nice one 👍

**Pull request merged**
