### PR TITLE
Update Simple Icons icon

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Simple Icons

**Issue:** n/a

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
There was a _very_ small gap in the middle of the "S" in our icon which I've fixed. I did, unfortunately, have to up the precision to `4` as SVGO was changing the shape of the circle at `3` - if anyone can remedy that, please do so.

~**EDIT:** The gap is also present in `images/logo.svg`, `images/favicon.png` & `images/apple-touch-icon.png` and the latter 2 are both cropped. I'll try to get those fixed tomorrow and add them to this PR.~
**Done**

### CODE REVIEW

**Comment by ericcornelissen** [comment]
I've go two small questions regarding the changes: 

1. Any reason you added the `<xml>` tag to _images/logo.svg_?
2. Did you intentionally change what the favicons (both _.ico_ and _.png_) and apple-touch-icon look like? Below is a comparison. I'm not necessarily against it (though I kind off like the original), just wondering if you're aware.

| Yours | Original |
| --- | --- |
| image | image |

**Comment by PeterShaggyNoble** [comment]
> Any reason you added the `<xml>` tag to _images/logo.svg_?

To make it a complete, well-formed XML file and avoid any potential issues where a client expects an SVG to be such, not that I can think of any off the top of my head. It's more of a "Better to have it and not need it then need it and not have it" approach.

> Did you intentionally change what the favicons and apple-touch-icon look like?

Yeah, I assumed that was a mistake originally stemming from a single source file.

**Comment by ericcornelissen** [comment]
> To make it a complete, well-formed XML file and avoid any potential issues where a client expects an SVG to be such, not that I can think of any off the top of my head. It's more of a "Better to have it and not need it then need it and not have it" approach.

:+1: 


> Yeah, I assumed that was a mistake originally stemming from a single source file.

Interesting, it seemed intentional to me. That said I'm happy with either version, but kinda prefer the old version. I'll leave it to another @simple-icons/maintainers to make a final decision.

**Comment by runxel** [comment]
Ah, thanks for correcting this one :D 
Btw I've always wondered, why the logo is that badly cropped in the first place 😅 Soooo I'm kinda more inclined to Peter's favicon.
Still wondering what the other maintainers have to say on that :)

**Comment by PeterShaggyNoble** [comment]
Looks like everyone's happy with these changes so someone can go ahead and merge them in so we can get this fixed for v3.

**Pull request merged**
