### PR TITLE
Added Capacitor

### LINKED ISSUE #3335: Capacitor
**Name:** Capacitor
**Website:** https://capacitorjs.com
**Alexa rank:** https://www.alexa.com/siteinfo/capacitorjs.com
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by Berkmann18**
**Issue:** Closes #3335 
**Alexa rank:** https://www.alexa.com/siteinfo/capacitorjs.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by NovaGL** [comment]
Hi @Berkmann18, 

I'm a bit confused. The SVG you have don't follow the correct formatting as per the guidelines. Can you please look into and fix it?
Eg there is a closing <g> and you have it as base64

Also can you convert the HEX to uppercase in the json file.

**Comment by PeterShaggyNoble** [comment]
Oop, ignore my comment in the original issue, I see now that the version included in Iconify is actually the Ionicons one.

Given that, I would suggest updating the source URL to https://ionicons.com/, as it is an official source.

**Comment by Berkmann18** [comment]
> I'm a bit confused. The SVG you have don't follow the correct formatting as per the guidelines. Can you please look into and fix it?
Eg there is a closing and you have it as base64

@NovaGL That's the SVG image **you** suggested by the way which was much less compliant than what I have on this PR so far but @PeterShaggyNoble found a _way_ icon than any of the ones I had (including your suggestion) so I'll be using that once I get enough time to work on this PR in the upcoming weeks.

**Comment by Berkmann18** [comment]
@PeterShaggyNoble Are you okay with the source or shall I use https://github.com/ionic-team/ionicons-site/blob/master/docs/ionicons/svg/logo-capacitor.svg instead?

**Comment by adamrusted** [comment]
Hi @Berkmann18! Just had a quick look at this, and it appears there's an SVG embedded [in the header of the site](https://capacitorjs.com/). Would you mind updating the source to the homepage, and rebuilding from there if your submission is any different? 🙏🏻

**Comment by Berkmann18** [comment]
@adamalston I tried using that SVG in the past and it wasn't usable and I'm unsure if mentioning a different source to the one where I got the SVG (which is maintained by Ionic who owns Capacitor) would be a good idea (especially since the SVG itself containers the name)

**Comment by adamrusted** [comment]
> @adamalston I tried using that SVG in the past and it wasn't usable and I'm unsure if mentioning a different source to the one where I got the SVG (which is maintained by Ionic who owns Capacitor) would be a good idea (especially since the SVG itself containers the name)

Odd, the SVG should be usable, should just require some tweaking - though I've not looked at it in too much detail. 🤔

I would personally use the website (or a brand guideline page on that website) as an official source, resorting to their GitHub when an icon wasn't available there. Happy for another @simple-icons/maintainers to tell me I'm wrong though 😅

**Comment by adamrusted** [comment]
My bad @Berkmann18, just compared the two logos and they're exactly the same. In that case yes feel free to use the GitHub source, though I'd use [this link](https://github.com/ionic-team/ionicons-site/blob/b0c97018d737b763301154231b34e1b882c0c84d/docs/ionicons/svg/logo-capacitor.svg) as the source, so you're linking to the specific version.

**Review by adamrusted — APPROVED** [review]
Looks good to me! Thanks @Berkmann18 🎉

**Comment by adamalston** [comment]
Someone tagged me, I assume by mistake.

**Pull request merged**
