### PR TITLE
Add Datadog

### PR DESCRIPTION
**Pull request by jiboong**
### Checklist
  - [ ⚐ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ⚐ ] I optimized the icon with SVGO or SVGOMG
  - [ ⚐ ] The SVG `viewbox` is `0 0 24 24`

### Description
https://www.datadoghq.com/about/press/resources/

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for your work on this one, @jiboong.

Could you update the SVG to be centred on the canvas, though? I also think the box behind the dog should probably be included, as per their favicon.

**Comment by jiboong** [comment]
@PeterShaggyNoble we updated the icon as advised. let us know if you have additional feedback!

**Comment by PeterShaggyNoble** [comment]
Thanks for the speedy update, @jiboong. As there is a choice of icons here, and because I can't do a thorough review on my phone, we'll need one of the other @simple-icons/maintainers to throw an eye over this too before we can merge it in.

**Comment by runxel** [comment]
I think it looks good! 👍 
Thanks for your work on this one, @jiboong

**Comment by jiboong** [comment]
@runxel thanks!

**Pull request merged**
