### PR TITLE
Add Tunein

### LINKED ISSUE #2974: TuneIn
**Name:** TuneIn
**Website:** https://tunein.com/
**Official resources for icon and color:** SVG embedded in the HTML throughout their site

### PR DESCRIPTION
**Pull request by NovaGL**
simpleicons

**Issue:** Closes #2974

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

Manually changed logo from wide version.

Hex values can be found using this website or the media kit PDF mentioned
[TuneIn Press](https://cms.tunein.com/press/)

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the PR, @NovaGL :+1: Note that you've mixed up your Tumblr & TuneIn source URLs in the JSON :wink: I'd also suggest updating the source URL to https://cms.tunein.com/press/ - should their icon ever be updated, that's going to be the best starting point for future contributors.

For those with the eye for comparing raster with vector, there's a PNG version of this logo at https://cdn-web.tunein.com/assets/img/default-item-v2.png

As a matter of _personal_ preference and without any guidance to say otherwise, I'd have gone with the darker blue but I can see why you went with the lighter.

**Comment by NovaGL** [comment]
Thanks @PeterShaggyNoble. I've updated the source.

The color along all of there press sites is the lighter one, although the background is the darker one.
Let me know if other changes are required.

**Comment by PeterShaggyNoble** [comment]
I took the liberty of fixing the issue that was causing the build to fail for you - there was some trailing whitespace after the source URL.

Given that they don't state a preference, I'm happy to go with either colour, the darker one is just my own preference.

I'll leave the review of the SVG to those that are better than I at comparing raster to vector.

**Comment by NovaGL** [comment]
Thanks Peter, I updated the size of the image as I think it was 23 wide instead of 24.

**Comment by PeterShaggyNoble** [comment]
That's still coming in a bit under `24` wide, @NovaGL, at `23.925`.

**Comment by NovaGL** [comment]
Intresting. How do I make sure it's correct as Illustrator likes to play games.

**Comment by PeterShaggyNoble** [comment]
Most software will allow you to manually enter the dimensions somewhere, @NovaGL, with an option to constrain the proportions relative to each other so you only need change one dimension. I'm not familiar with Illustrator but in Inkscape, for example, it looks like this.

**Comment by NovaGL** [comment]
Alright, I redid it in Inkscape no matter how many times I did it in Illustrator it was never 24 width. I used a different method to resize to 24 this time as it was loosing some quality and edges were looking weird. It still uses SVGO as the last step.

Hopefully this is good now.

**Pull request merged**
