### PR TITLE
Add Nickelodeon icon

### LINKED ISSUE #8449: Request: Nickelodeon
### Brand Name

Nickelodeon

### Website

https://nick.com

### Popularity Metric

The Similarweb rank is 37,212. See https://www.similarweb.com/website/nick.com

### Official Resources for Icon and Color

svg: https://upload.wikimedia.org/wikipedia/commons/7/7a/Nickelodeon_2009_logo.svg
color: `#FF6700`  taken from the site header

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by uncenter**
nickelodeon

**Issue:** closes #8449.

**Popularity metric:** The Similarweb rank is 37,212. See https://www.similarweb.com/website/nick.com.

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by adamrusted** [comment]
See section two of [this page](https://www.nick.co.uk/legal/373cyf/terms-of-use) - where they explictly say:

> You agree not to copy, reproduce, modify, create derivative works from, display, perform, publish, distribute, disseminate, broadcast, transmit, sell, rent, lease, lend, sub-licence or circulate any Material and/or part of or all of the Site to any third party (including, without limitation, the display and distribution of the Material via a third party website) without the express prior written consent of Nick UK.

That seems a pretty cut-and-dry denial of permission to reproduce their logo unless we seek permission.

**Comment by uncenter** [comment]
> Would you be willing to reach out to Nickelodeon, @uncenter?

Definitely, but like the Capital One PR I can't find a contact email address.

**Comment by adamrusted** [comment]
Were you able to find any details to reach out to them @uncenter?

**Comment by uncenter** [comment]
From some Reddit posts online it seems like Nickelodeon is notoriously difficult to contact. I found one privacy-related contact email, which I'll give a try since it seems like the only one.

**Comment by uncenter** [comment]
Closing as no feedback from brand.

**Pull request closed without merging**
