### PR TITLE
Added Bitcoin Cash

### LINKED ISSUE #3537: Request: Bitcoin Cash icon
image

**Name:** Bitcoin Cash
**Website:** No official website since it is a decentralized network
**Alexa rank:** N/A but network is valued at $4B+, see: http://coinmarketcap.com/
**Official resources for icon and color:**
https://www.bitcoincash.org/graphics.html

### PR DESCRIPTION
**Pull request by adamrusted**
bitcoincash

**Issue:** Closes #3537
**Alexa rank:** [115,009](https://www.alexa.com/siteinfo/bitcoincash.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Color pulled from SVG.

### CODE REVIEW

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
Thanks for this one, @adamrusted. SVG looks perfect to me. However, their is a visual identity section on the source page that states that the colour should be `#f59332` - if you can update that then this should be good to go.

**Comment by adamrusted** [comment]
@PeterShaggyNoble should be good to go.

**Comment by PeterShaggyNoble** [comment]
Oop, sorry, @adamrusted; just zoomed in a step further and spotted a couple of imperfections in the bottom curve of the "B" - could you take a look at those, please?

(Your version in red)

**Comment by adamrusted** [comment]
> @PeterShaggyNoble: All the curves on the "B" are an absolute mess of points!

Yep! Just pushing a version now with the shapes 'simplified' as much as I can given the source icon.

**Comment by PeterShaggyNoble** [comment]
Labelling this one as pending as there website has been [offline for over a week](https://www.isitdownrightnow.com/bitcoincash.org.html). I suggest we give it another week to see if it comes back online and then make a decision on how to proceed if it hasn't.

**Comment by adamrusted** [comment]
@PeterShaggyNoble website is back up and running - removing pending label so it's ready for review.

**Review by PeterShaggyNoble — APPROVED** [review]
Looks perfect to me now, @adamrusted 👍🏻 Nice work.

**Pull request merged**
