### PR TITLE
Adding CodeSignal icon

### LINKED ISSUE #6598: Request: CodeSignal
### Brand Name

CodeSignal

### Website

https://codesignal.com/

### Popularity Metric

The Alexa Rank is 27,761 (https://www.alexa.com/siteinfo/codesignal.com)

### Official Resources for Icon and Color

SVG: https://codesignal.com/wp-content/uploads/2020/10/Group-28393.svg
Color: `#33485f` (from site's header)

### Contributing

Yes

### PR DESCRIPTION
**Pull request by blakmagjick**
codesignal

**Issue:** closes #6598

**Similarweb rank:** 104,641
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Used the hex value in the previously opened, but closed before merging PR (#7101). 
- Confirmed that .svg was optimized to precision 3 in SVGOMG online tool. 

Updated
- Used the updated hex value received from engineer directly from their branding team.
- Updated icon to new version of logo, as per new SVG given.

### CODE REVIEW

**Comment by LitoMore** [comment]
They have a GitHub Organization https://github.com/CodeSignal.

Would you mind reaching out to them for approval?

[shields.io](https://shields.io) is our consumer, so the benefit is they can use their icon with shields.io badges.

**Comment by blakmagjick** [comment]
Hi @menewman, may I ask for your approval on this PR? Thanks 😸

**Comment by menewman** [comment]
Hm, thanks for pinging us!

At a glance, this appears to be the older version of our logo & color (we updated our branding last fall; you can see the new version on our website).

As an engineer at CodeSignal, I can't really approve this PR for you, because that would imply that we're officially endorsing this usage of our logo & branding (and it's out of my realm of ownership to do that). But I can share this thread with our our marketing & branding team to ask what they think.

**Comment by menewman** [comment]
Good news! Our excellent branding team appreciated the inquiry, and they were happy to help provide an SVG featuring our updated logo. :)

CodeSignal_Symbol_RGB

Our updated brand color is `#1062FB`.

**Comment by blakmagjick** [comment]
> Good news! Our excellent branding team appreciated the inquiry, and they were happy to help provide an SVG featuring our updated logo. :)
> 

This is awesome! Thanks so much, I'll get this updated today. 😸

**Comment by blakmagjick** [comment]
Hi @menewman, can you look over the updated work (or show branding again?) and approve? Thanks for the help!

**Review by menewman — APPROVED** [review]
Thank you for updating it!

**Pull request merged**
