### PR TITLE
Add PhpStorm

### PR DESCRIPTION
**Pull request by MetLee**
image

**Issue:** #625 
**Alexa rank:** 1,862
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the PR, @MetLee :+1: Note, though, that the Alexa rank you've quoted is for jetbrains.com and doesn't give an accurate reflection of the popularity of PhpStorm so the first thing we'll need to do is determine the popularity of both this and GoLand. After Alexa ranks, the next thing we usually look at is GitHub stars (our cut-off is 5k) but, unfortunately, neither has it's own dedicated repo. Could you suggest another metric we could use to assess the suitability of these brands?

**Comment by MetLee** [comment]
image
I found this table on https://www.alexa.com/siteinfo/jetbrains.com

**Comment by PeterShaggyNoble** [comment]
Interesting idea, @MetLee :+1: But comparing them with their parent company probably isn't going to give us the most accurate data. If we could find some sort of comparison between each brand and a direct competitor that we can definitively say would be in-scope for us, that might give us a better idea.

**Comment by MetLee** [comment]
> Interesting idea, @MetLee 👍 But comparing them with their parent company probably isn't going to give us the most accurate data. If we could find some sort of comparison between each brand and a direct competitor that we can definitively say would be in-scope for us, that might give us a better idea.

I am not good at finding the rank of a specific brand; may you give me some advice?

**Comment by cevin** [comment]
@PeterShaggyNoble 

Another product of the same company has been included. It is also a very popular commercial IDE tool. There is no reason why PhpStorm cannot be included.

**Comment by PeterShaggyNoble** [comment]
> Another product of the same company has been included

Thanks for the feedback, @cevin. However, another product from the same company already being available isn't reason alone for us to add a brand, no matter how big that company is. For example, we regularly discuss the suitability of various Google products for inclusion and have just recently [rejected a product from Adobe](https://github.com/simple-icons/simple-icons/pull/2792).

> There is no reason why PhpStorm cannot be included

What we're trying to do here is come up with some way to assess the popularity of _all_ JetBrains products that fall within their own domain so we can use that for any future requests to add more of their products (such as [GoLand](https://github.com/simple-icons/simple-icons/pull/3373)).

**Comment by MetLee** [comment]
> > Another product of the same company has been included
> 
> Thanks for the feedback, @cevin. However, another product from the same company already being available isn't reason alone for us to add a brand, no matter how big that company is. For example, we regularly discuss the suitability of various Google products for inclusion and have just recently [rejected a product from Adobe](https://github.com/simple-icons/simple-icons/pull/2792).
> 
> > There is no reason why PhpStorm cannot be included
> 
> What we're trying to do here is come up with some way to assess the popularity of _all_ JetBrains products that fall within their own domain so we can use that for any future requests to add more of their products (such as [GoLand](https://github.com/simple-icons/simple-icons/pull/3373)).

Agree. So we need to find a method to show its popularity.

**Comment by cevin** [comment]
how about Google Trends
https://trends.google.com/trends/explore?q=phpstorm

**Comment by MetLee** [comment]
https://trends.google.com/trends/explore?q=phpstorm,jetbrains
It shows that PhpStorm is of the same popularity as JB.
@PeterShaggyNoble

**Comment by cevin** [comment]
> https://trends.google.com/trends/explore?q=phpstorm,jetbrains
> It shows that PhpStorm is of the same popularity as JB.
> @PeterShaggyNoble

https://trends.google.com/trends/explore?q=phpstorm,jetbrains,webstorm
Even higher than the already included WebStorm

**Comment by mondeja** [comment]
> https://trends.google.com/trends/explore?q=phpstorm,jetbrains,webstorm
> Even higher than the already included WebStorm

Definitively this comparison reflects that WebStorm can be within the scope of simple-icons. I agree with the inclusion of PhpStorm. @PeterShaggyNoble are you against this?

**Comment by service-paradis** [comment]
I also agree with the inclusion. We already have some other JetBrains products (JetBrains, PyCharm, IntelliJ IDEA and potentially TeamCity). I think the popularity of PHPStorm is comparable to those and within the scope.

**Review by mondeja — APPROVED** [review]
Looks good to me, so I'm merging this. Thank you for adding this one @MetLee :sparkles:

**Pull request merged**
