### PR TITLE
Add GNU Bash

### LINKED ISSUE #2183: Bash (shell)
**Name:** Bash 
**Website:** https://www.gnu.org/software/bash/
**Official resources for icon and color:** 

* https://github.com/odb/official-bash-logo 
* [Here is a quicklink to the logo in SVG.](https://github.com/odb/official-bash-logo/tree/master/assets/Logos/Icons/SVG)
* To clarify that this is the official logo, check out [this article](https://opensource.com/article/16/12/bash-logo-community). 
* Be sure to read and double-check with the [given style guide](https://github.com/odb/official-bash-logo/blob/master/assets/bash-style-guide.pdf) just to be safe. 
  

Since the official website is not in its own domain, there's no official Alexa ranking to this. 
I think all will agree that this is popular enough. 
It is the default shell in most Linux distros, after all.

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
Closes #2183

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The logo is from their github repo.
The color `#4EAA25` is from the [style guide](https://github.com/odb/official-bash-logo/blob/master/assets/bash-style-guide.pdf). But I would also be okay with `#293137`.

### CODE REVIEW

**Comment by foo-dogsquared** [comment]
Just for clarification, what file from the repo did you use to make the PR (e.g., the EPS, SVG)? 

Apparently, some of the SVGs from the official repo are a bit malformed. 

Here's the `48x48.svg` from the repo. (Take note of the bottom edge.)


Here's the `512x512.svg` from the repo. 


Here's the `24x24.svg` file overlaid with your PR. (No need to compare.)

**Comment by runxel** [comment]
I took [24x24_white](https://github.com/odb/official-bash-logo/blob/master/assets/Logos/Icons/SVG/24x24_white.svg)

**Comment by PeterShaggyNoble** [comment]
There's a monochrome SVG [here](https://github.com/odb/official-bash-logo/blob/master/assets/Logos/Icons/SVG/BASH_logo-transparent-bg-bw-02.svg), if it's any help. But if the are discrepancies/doubts, I'd say go back to the [source files](https://github.com/odb/official-bash-logo/blob/master/assets/Logos/Icons/Source/).

**Comment by foo-dogsquared** [comment]
`24x24_white.svg` also has the same (if not similar) malformation with its colored counterpart. 

But compared to the `512x512` versions of the SVG, it's not too bad. 
The only (very) minor problem is the pictured part.

**Comment by runxel** [comment]
Thanks to the comment of @PeterShaggyNoble now the updated version!
It's taken from the ground truth, their Illustrator file, which also is in the the github repo.

Thanks again for everyone who commented and made this PR better! 🌮

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @runxel 👍

**Pull request merged**
