### PR TITLE
Added dev.to logo icon

### PR DESCRIPTION
**Pull request by belhassen07**
[dev.to](https://dev.to/) logo .

### CODE REVIEW

**Comment by birjolaxew** [comment]
Based on [their about page](https://dev.to/about), it looks like they prefer "dev.to" over "Dev.to". Could you update the JSON to use the lowercase variant, and also add "https://" in front of the source URL?

**Comment by birjolaxew** [comment]
Here's the SVG with a black box around it. Note that dev.to aren't consistent with the size of the black box, so I simply used the dimensions from the top-left logo on their [main site](https://dev.to).

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-40 -29.5 204 120">
  <rect x="-40" y="-29.5" width="204" height="120" />
  <path fill="#fff"
    d="M0 33v32h11.3c12.5 0 17.7-1.6 21.5-6.5 3.8-4.8 4.4-9
    4-28-.3-16.8-.5-18.2-2.7-21.8C30.3 2.5 26.1 1 12 1H0v32zm23.1-19.1c2.3
    1.9 2.4 2.3 2.4 18.5 0 15.7-.1 16.7-2.2 18.8-1.7 1.6-3.5 2.2-7
    2.2l-4.8.1-.3-20.8L11 12h4.9c3.3 0 5.6.6 7.2 1.9zM46.1 3.6c-2 2.6-2.1
    3.9-2.1 29.6v26.9l2.5 2.4c2.3 2.4 2.9 2.5 16
    2.5H76V54.1l-10.2-.3-10.3-.3v-15l6.3-.3 6.2-.3V27H55V12h21V1H62.1c-13.9
    0-14 0-16 2.6zM87 15.2c2.1 7.9 5.5 20.8 7.6 28.8 3.2 12.3 4.3 15 7 17.7
    1.9 2 4.2 3.3 5.7 3.3 3.1 0 7.1-3.1 8.5-6.7 1-2.6 15.2-55.6 15.2-56.8
    0-.3-2.8-.5-6.2-.3l-6.3.3-5.6 21.5c-3.5 13.6-5.8 20.8-6.2 19.5C105.9 40
    96 1.9 96 1.4c0-.2-2.9-.4-6.4-.4h-6.4L87 15.2z">
  </path>
</svg>
```

Before it can be used it needs to:

- Turn the `<rect>` and `<path>` into a single '<path>` by applying a subtract boolean operation on them (so the white text gets knocked out of the black box)
- Scale the SVG to 24x24
- Apply all the annotations, etc., as documented in our contribution guide

Unfortunately I don't have any vector software on my current PC so I can't be of much more help :)

**Comment by belhassen07** [comment]
all other icons are registered in the json file starting with an uppercase. this link already contains 'https'.
the svg I've put is already a 24 * 24 svg document.
please review my edit not the original dev.to logo, it took me a lot of time to make it apply to all simple-icons rules.

**Comment by birjolaxew** [comment]
> this link already contains 'https'

You're right, my mistake sorry.

> all other icons are registered in the json file starting with an uppercase

Not exactly. For instance, "freeCodeCamp" starts with lowercase because that is how their brand is written. Since Simple Icons is a collection of brands, we try to stay faithful to how the brands want to be presented. In this case, dev.to write their brand as "dev.to", not "Dev.to".

> svg I've put is already a 24 * 24 svg document

But the path inside is not resized to fit the 24 * 24 SVG document. From [our contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#5-check-the-icon):

> The final icon should:
> - [...]
> - Be scaled to fit the viewbox, while preserving the icon's original proportions.
>     - This means the icon should be touching at least two sides of the viewbox.

<p align="center"></p>

> please review my edit not the original dev.to logo

Simple Icons is a collection of brands. We cannot accept logos that don't represent the brand they are submitted as. In this case your submission is lacking the black box that dev.to use.

**Comment by birjolaxew** [comment]
Here's a fixed SVG that correctly represents the dev.to logo. Feel free to use it:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-labelledby="simpleicons-devto-icon" role="img"><title id="simpleicons-devto-icon">dev.to icon</title><path d="M7.42 10.05c-.18-.16-.46-.23-.84-.23H6l.02 2.44.04 2.45.56-.02c.41 0 .63-.07.83-.26.24-.24.26-.36.26-2.2 0-1.91-.02-1.96-.29-2.18z"/><path d="M0 4.94v14.12h24V4.94H0zM8.56 15.3c-.44.58-1.06.77-2.53.77H4.71V8.53h1.4c1.67 0 2.16.18 2.6.9.27.43.29.6.32 2.57.05 2.23-.02 2.73-.47 3.3zm5.09-5.47h-2.47v1.77h1.52v1.28l-.72.04-.75.03v1.77l1.22.03 1.2.04v1.28h-1.6c-1.53 0-1.6-.01-1.87-.3l-.3-.28v-3.16c0-3.02.01-3.18.25-3.48.23-.31.25-.31 1.88-.31h1.64v1.3zm4.68 5.45c-.17.43-.64.79-1 .79-.18 0-.45-.15-.67-.39-.32-.32-.45-.63-.82-2.08l-.9-3.39-.45-1.67h.76c.4 0 .75.02.75.05 0 .06 1.16 4.54 1.26 4.83.04.15.32-.7.73-2.3l.66-2.52.74-.04c.4-.02.73 0 .73.04 0 .14-1.67 6.38-1.8 6.68z"/></svg>
```

**Comment by birjolaxew** [comment]
@ericcornelissen Could you review & merge?

**Pull request merged**
