### PR TITLE
Add Modrinth icon

### LINKED ISSUE #7488: Icon Request: Modrinth
### Brand Name

Modrinth

### Website

https://modrinth.com

### Popularity Metric

image

**Global Rank:** 82,584

### Official Resources for Icon and Color

svg: https://github.com/modrinth/knossos/blob/master/assets/images/logo.svg
color: (Found in https://github.com/modrinth/knossos/blob/master/assets/styles/global.scss)
 - dark-mode: [`#1bd96a` <sup>source</sup>](https://github.com/modrinth/knossos/blob/43b8941f7a0f5718384d1c31547703b97e39ab72/assets/styles/global.scss#L106)
 - light-mode: [`#30b27b` <sup>source</sup>](https://github.com/modrinth/knossos/blob/43b8941f7a0f5718384d1c31547703b97e39ab72/assets/styles/global.scss#L22)

### Additional Comments

 - **Are there multiple options for the logo and/or color?**
   
   Yes, as far as I know, there are two. One for both the dark theme and the light theme.
   
 - **Is the icon released under a license?**
   
   All Rights Reserved - https://github.com/modrinth/knossos/blob/master/COPYING.md#logo-licenses
   
 - **If you think the brand might not be accepted, why do you think it should be considered?**
   
   Modrinth is new compared to another Minecraft modding platform Curseforge. I don't want to compare the two more than is necessary, but their website and how things are arranged (in my opinion) is nice (It also have dark theme). 
  
   Scrolling down in their website https://modrinth.com, will feature more what Modrinth has to offer.

---

> [Modrinth - Official Feed The Beast Wiki](https://ftb.fandom.com/wiki/Modrinth)
> Modrinth is a free and open-source modding platform currently in beta.

<sub>Various pages shown with dark mode theme, in 33% zoom. The homepage (left), sodium mod page (upper-right), and fabulously optimized mod pack page (bottom-right).</sub>
image

### Contributing

No

### PR DESCRIPTION
**Pull request by magicus**
modrinth-preview

**Issue:** closes #7488

**Similarweb rank:** [#48410](https://www.similarweb.com/website/modrinth.com/#overview)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
According to the two previously closed PRs (#7579 and #7688) trying to incorporate the Modrinth logo, the full logo was deemed too complex, and the simpler "favicon" (still svg based) should be used instead. Unfortunately this used design-wise complex objects and clipping, which made it tricky to convert into a single path as required by simple-icons. 

I solved it by following a hint about using Inkscape's fill bucket.

The color is the official light mode branding color.

### CODE REVIEW

**Comment by magicus** [comment]
I apologize. I'm not that used to working with svg files. I had apparently not succeeded in getting the icon maximized in the viewbox. I thought Inkscape had done that for me when I asked it to resize it, but it was apparently a bit off. I need to read up a bit on how to fix this.

**Comment by magicus** [comment]
@triphora Done. Also updated the preview.

**Comment by magicus** [comment]
What is the process for getting this merged?

**Comment by magicus** [comment]
Also, @triphora, I see you are associated with Modrinth. Can we consider your approval an official acknowledgement? According to the simple-icons documentation, having such an approval might speed up the process.

**Comment by triphora** [comment]
Yes, you may. It's been on my personal to-do list to PR this, but I wasn't able to figure out how to merge the paths without breaking it.

**Review by AshtakaOOf — APPROVED** [review]
This need to be merged asap

**Comment by magicus** [comment]
> I wasn't able to figure out how to merge the paths without breaking it.

Yeah, that was tricky. I'm not an SVG guru myself either, but I found a hint about using the fill bucket tool in Inkscape, and that did the trick. It created a new shape based on what is visible "to the human eye", which was just what was needed here.

**Comment by magicus** [comment]
@dirien Sorry for the ping, but I don't know else how to get this PR to the attention of someone with merge permissions. I believe this PR is ready for merge. We have an official review from the Modrinth team (https://github.com/simple-icons/simple-icons/pull/8101#issuecomment-1346374962). The automatic tests pass. All official requirements are checked off.

**Comment by dirien** [comment]
Hi @magicus, 

I will tomorrow (CET time) first thing into it! 

Thanks for the contribution!

**Review by dirien — APPROVED** [review]
Ho @magicus,

i see some differences to the reference icon (favicon.svg) I will approve this PR as the Modrinth team gave green light for your icon!

Thanks for contributing. 

image

**Pull request merged**
