### PR TITLE
Updated HappyCow

### PR DESCRIPTION
**Pull request by fbernhart**
happycow

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by mondeja — COMMENTED** [review]
Seems that the logo it's outdated in the source (your path is the red in comparison). You want to update it in this pull or I will review as is and we open another for the update?

image

**Comment by fbernhart** [comment]
happycow


@mondeja I've rebuilt it now from the source, using the new logo. And gave it a kind of different approach. 😁 

Most of the icon is filled now. And I've separated the color changes with gaps (width 0,35px). What do you think?

**Comment by mondeja** [comment]
> I've rebuilt it now from the source, using the new logo. And gave it a kind of different approach.

Surely, but seems that you forgot to push... or I'm going crazy? :smile:

**Comment by fbernhart** [comment]
@mondeja  haha, I'm sorry. I've pushed now ;)

**Comment by mondeja** [comment]
I think that, although your treatment about what geometries must be filled is good, we must respect as far as we can the original source. Because of that, maybe choose a gap width based on our fancy could not be the best choice if the original icon for the brand has stroke geometries, which is the case, and we could incur a deformation of the brand symbol.

respect-width-happycow

Have you checked if the original stroke width looks fine in small sizes?

**Comment by fbernhart** [comment]
@mondeja Thanks for your feedback I'll try it again with the original width and see how it looks like. 👍🏼

**Comment by fbernhart** [comment]
happycow

@mondeja How about this version? I've now used the original strokes to create the gaps. Unfortunatelly a precision of 3 didn't make it through the linter.

**Review by mondeja — APPROVED** [review]
It looks perfect now :1st_place_medal:
Nice work @fbernhart!

**Pull request merged**
