### PR TITLE
Add Aeroflot

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Aeroflot

**Issue:** #2587
**Alexa rank:** [~7.8k](https://www.alexa.com/siteinfo/aeroflot.ru)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon from logo on first page of [this PDF](http://webfiles.aeroflot.ru/Aeroflot_January_2021.pdf), colour from [website](https://www.aeroflot.ru/ru-en) stylesheet - although I'm not _entirely_ certain which blue is the correct one.

Possible alternative treatment below (maybe boxed?) as seen in the [PDF icon](https://www.aeroflot.ru/frontend/static/img/icon--doc-pdf.svg) at the source URL and [their favicons](https://www.aeroflot.ru/media/aflfiles/fav/favicon-192x192.png). The smaller version would definitely suit us better but I'm not sure if we can use it as I haven't seen it in use anywhere other than their own website. **UPDATE:** The cropping looks to be inconsistent between different sources (such as the 2 linked above) so I think we can definitely rule this treatment out.

### CODE REVIEW

**Review by adamrusted — COMMENTED** [review]
I'm spotting a few random points, like the ones shown below.
image

Given they're present in the original, I'd be happy to let them through - though want to run by another @simple-icons/maintainers first, to see whether we _should_ try and tidy it up. Other than that, this is good to go - so if there are no objections I'll look to merge tomorrow evening ahead of the Sunday release.

**Comment by PeterShaggyNoble** [comment]
Does this (as-yet unoptimised) version work better, @adamrusted? Wasn't sure what the correct fix for the obviously wrong "kink" in the curve towards the bottom-right in your screenshot was so I've left it as-is for now.

```
M 9.06616,12.724562 C 9.0097,12.590482 8.96913,12.452872 8.92326,12.318792 L 2.24757,12.724562 3.59718,13.417882 Z M 9.97471,13.971842 C 9.91826,13.929502 9.86004,13.871282 9.80535,13.821882 9.69068,13.717792 9.59188,13.613712 9.51779,13.504332 L 6.18524,14.174722 7.60365,14.682802 Z M 12.6157,13.686042 C 12.77448,13.661342 13.01441,13.564312 13.20318,13.417882 L 12.23464,11.385542 13.24022,10.875692 12.39165,10.094152 C 11.790106,10.386007 11.186372,10.673327 10.58336,10.962132 L 11.01382,11.987132 11.70714,11.657222 Z M 15.04675,11.145612 H 14.43634 C 14.39047,10.948022 14.33755,10.755722 14.26522,10.575782 13.85416,9.4325816 13.01441,8.6192916 12.0494,7.9418516 11.92238,7.8642216 11.8077,7.7777816 11.67892,7.7036816 11.8077,7.7477816 11.92238,7.7901316 12.0494,7.8395216 12.92973,8.2117716 13.71126,8.7251416 14.26522,9.4449316 14.63393,9.9106816 14.90385,10.485802 15.04675,11.145612 Z M 14.45046,15.961842 C 14.224622,16.075387 13.995368,16.181913 13.76772,16.291742 L 13.20318,15.099152 C 12.84505,15.234992 12.44634,15.314382 12.0494,15.324972 11.62246,15.346142 11.18318,15.280862 10.80035,15.148552 L 10.31697,16.291742 C 10.15995,16.305862 9.94296,16.291742 9.80535,16.185892 9.73302,16.140022 9.66069,16.064162 9.63599,15.961842 9.8395128,15.605359 10.024579,15.238842 10.21464,14.875102 10.08762,14.786892 9.97471,14.723382 9.86004,14.605182 L 10.20406,14.167662 C 10.78624,14.548732 11.42311,14.753372 12.0494,14.753372 12.67568,14.774542 13.29844,14.561072 13.88062,14.125322 L 14.42223,14.305272 C 14.36401,14.351142 14.32167,14.391712 14.26522,14.441112 14.15054,14.561072 14.05175,14.682802 13.86651,14.786892 14.054892,15.181685 14.254364,15.57091 14.45046,15.961842 Z M 22.23581,12.530502 24,11.343202 H 14.45046 C 14.45046,11.764842 14.39047,12.126502 14.26522,12.442292 13.8965,13.447872 12.97383,13.929502 12.0494,13.911852 11.14084,13.885392 10.21464,13.387892 9.80535,12.470512 9.66069,12.135322 9.57601,11.780722 9.57601,11.343202 H 0 L 1.75007,12.530502 9.06616,12.126502 C 9.20376,12.680452 9.4631,13.163842 9.80535,13.521972 10.3893,14.167662 11.22552,14.531082 12.0494,14.531082 12.86092,14.548732 13.68127,14.231172 14.26522,13.539612 14.57748,13.177952 14.81917,12.713972 14.95854,12.154722 Z M 21.75419,12.724562 20.40282,13.387892 15.00088,12.724562 C 15.04675,12.590482 15.09086,12.452872 15.12967,12.318792 Z M 17.84828,14.187072 16.36813,14.707502 14.26522,14.033582 14.08174,13.971842 C 14.234696,13.824677 14.369215,13.667666 14.50691,13.521972 Z M 18.55925,14.097092 19.73596,13.521972 14.87562,12.908032 C 14.83328,13.072102 14.7045,13.206182 14.61982,13.340262 Z M 5.44252,14.097092 4.26404,13.555492 9.14907,12.920382 C 9.23905,13.072102 9.3202,13.206182 9.41899,13.340262Z
```

**Comment by adamrusted** [comment]
Yep - overlaying your new unoptimized path looks a lot cleaner - though there is still one extra point that you _might_ be able to remove on the right hand side of the icon - see image below. There is a _slight_ difference between those versions, but given the minuscule resolution the original was being displayed at, I think we can get away with some liberties when tidying it up.

[Right-hand Side of Image](https://user-images.githubusercontent.com/1830867/108739333-73fe7980-752c-11eb-9a57-e7e1f93ba84a.png)
[Additional Point on Left](https://user-images.githubusercontent.com/1830867/108739600-b58f2480-752c-11eb-89c2-9bfbc832957f.png)

**Comment by PeterShaggyNoble** [comment]
How's this look, @adamrusted?

```
M 9.06616,12.724562 C 9.0097,12.590482 8.96913,12.452872 8.92326,12.318792 L 2.24757,12.724562 3.59718,13.417882 Z M 9.97471,13.971842 C 9.7472407,13.773449 9.6583611,13.698942 9.51779,13.504332 L 6.18524,14.174722 7.60365,14.682802 Z M 12.6157,13.686042 C 12.77448,13.661342 13.01441,13.564312 13.20318,13.417882 L 12.23464,11.385542 13.24022,10.875692 12.39165,10.094152 C 11.790106,10.386007 11.186372,10.673327 10.58336,10.962132 L 11.01382,11.987132 11.70714,11.657222 Z M 15.04675,11.145612 H 14.43634 C 14.39047,10.948022 14.33755,10.755722 14.26522,10.575782 13.85416,9.4325816 13.01441,8.6192916 12.0494,7.9418516 11.92238,7.8642216 11.8077,7.7777816 11.67892,7.7036816 11.8077,7.7477816 11.92238,7.7901316 12.0494,7.8395216 12.92973,8.2117716 13.71126,8.7251416 14.26522,9.4449316 14.63393,9.9106816 14.90385,10.485802 15.04675,11.145612 Z M 14.45046,15.961842 C 14.224622,16.075387 13.995368,16.181913 13.76772,16.291742 L 13.20318,15.099152 C 12.84505,15.234992 12.44634,15.314382 12.0494,15.324972 11.62246,15.346142 11.18318,15.280862 10.80035,15.148552 L 10.31697,16.291742 C 10.15995,16.305862 9.94296,16.291742 9.80535,16.185892 9.73302,16.140022 9.66069,16.064162 9.63599,15.961842 9.8395128,15.605359 10.024579,15.238842 10.21464,14.875102 10.08762,14.786892 9.97471,14.723382 9.86004,14.605182 L 10.20406,14.167662 C 10.78624,14.548732 11.42311,14.753372 12.0494,14.753372 12.67568,14.774542 13.29844,14.561072 13.88062,14.125322 L 14.42223,14.305272 C 14.205298,14.490062 14.053209,14.702628 13.86651,14.786892 14.054892,15.181685 14.254364,15.57091 14.45046,15.961842 Z M 22.23581,12.530502 24,11.343202 H 14.45046 C 14.45046,11.764842 14.39047,12.126502 14.26522,12.442292 13.8965,13.447872 12.97383,13.929502 12.0494,13.911852 11.14084,13.885392 10.21464,13.387892 9.80535,12.470512 9.66069,12.135322 9.57601,11.780722 9.57601,11.343202 H 0 L 1.75007,12.530502 9.06616,12.126502 C 9.20376,12.680452 9.4631,13.163842 9.80535,13.521972 10.3893,14.167662 11.22552,14.531082 12.0494,14.531082 12.86092,14.548732 13.68127,14.231172 14.26522,13.539612 14.57748,13.177952 14.81917,12.713972 14.95854,12.154722 Z M 21.75419,12.724562 20.40282,13.387892 15.00088,12.724562 C 15.04675,12.590482 15.09086,12.452872 15.12967,12.318792 Z M 17.84828,14.187072 16.36813,14.707502 14.26522,14.033582 14.08174,13.971842 C 14.234696,13.824677 14.369215,13.667666 14.50691,13.521972 Z M 18.55925,14.097092 19.73596,13.521972 14.87562,12.908032 C 14.83328,13.072102 14.7045,13.206182 14.61982,13.340262 Z M 5.44252,14.097092 4.26404,13.555492 9.14907,12.920382 C 9.23905,13.072102 9.3202,13.206182 9.41899,13.340262Z
```

**Comment by adamrusted** [comment]
Just about to look at that new path @PeterShaggyNoble. Just a note, the source URL seems to be updated monthly, January_2021 is no longer available - but February_2021 is.

**Comment by adamrusted** [comment]
@PeterShaggyNoble SVG lines up perfectly again. There is still _one_ excess point that you may be able to trim, see [here](https://user-images.githubusercontent.com/1830867/109282940-1a40cc80-7816-11eb-9ddc-a7e74348fc8a.png).

I'd also suggest the hex is updated to `#02458D` - as that appears to be used as the `body` colour on the website.

**Comment by PeterShaggyNoble** [comment]
Give that a try, @adamrusted; managed to remove a few more points. Also updated the colour; they have a number of different blues but the one you picked seems closest to the blue in the Russian flag which features in their logo so, in the absence of any brand guidelines, I think it's a good choice.

**Review by adamrusted — APPROVED** [review]
Looks good to me! Thanks @PeterShaggyNoble!

**Pull request merged**
