### PR TITLE
Update Strapi

### LINKED ISSUE #4937: Update Strapi icon
image

**Brand Name:** [Strapi](https://strapi.io/)
**Official resources for icon and color:**
  
- https://strapi.io/newsroom
- https://www.notion.so/Media-Kit-2e389f6d82624cf29fee9c5223defab9
- Color : 
  - `#2f2e8b` (name in logo and font color) 
  - Other shade of purple found in the logo and in the website: `#8c4bff`, `#8e75ff`

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** Closes #4937
**Alexa rank:** [~13,8k](https://www.alexa.com/siteinfo/strapi.io)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I took the icon from https://strapi.io/newsroom
- I used Inkscape to scale, adjust and add gaps (0.5px)
- I used https://jakearchibald.github.io/svgomg/ to optimize
- The chosen color can be discussed
  - It is the color of the word Strap in the full logo
  - It is also the color of every title on the website (as seen in the stylesheet)

P.S. It was my first time adding gaps 😅, let me know if it is wrong!

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Looking good, @service-paradis 👍🏻

When comparing it to `SVG.monogram.purple.svg`, though, I am noticing one small difference (below, with yours in green). Did you base your version on the same file? Because I did notice that there are differences between each on in that zip so maybe I'm not comparing to the same source.

They do use a lot of different purples! But as the one you've chosen is used in the wordmark of their logo and they don't seem to specify a brand colour, I think that's the best choice for us to use.

**Comment by service-paradis** [comment]
Oh, I should have mentioned the version I used. It was `SVG.monogram.white.svg`. I was able to see a difference anyway, the optimizing process were messing a little bit with the path.

I gave it another try, and I think it is better now! What do you think?
image

**Comment by adamrusted** [comment]
Looks to match up to me against the white monogram - though will wait for @PeterShaggyNoble to review it 👌

**Review by PeterShaggyNoble — APPROVED** [review]
Looks perfect to me now too 👍🏻 Thanks, @service-paradis.

**Pull request merged**
