### PR TITLE
LBRY icon + data entry.

### LINKED ISSUE #2800: LBRY.tv
**Name:** library icon 
**Website:** https://lbry.tv/
**Official resources for icon and color:** depends on the background. white on dark bg, black on light bg.

### PR DESCRIPTION
**Pull request by santimirandarp**
LBRY

**Issue:** fixes #2800

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Hex value from site `#111111`.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for your continued work on this one, @santimirandarp.

Your path, however, is now coming in at `23.921` in width. Even when scaled up to `24` and recentred, though, I'm still seeing differences between your path and the SVG found in the header of the source URL. Are you, perhaps, basing your icon on a different SVG than that and, if so, could you let us know which one?

**Comment by santimirandarp** [comment]
I'm taking the icon from lbry.tv in the top left corner.

**Comment by PeterShaggyNoble** [comment]
Ah-ha, I've figured out the issue - my bad for not spotting it before: There's a `stroke` on the original which increases both the overall line thickness and width of the icon that's not being included when you export just the `path`.

The solution is as follows:
1. After merging the 2 paths and removing the extra points in the arrowhead, create a duplicate of the new path and line it up with the first exactly.
2. Remove the `stroke` from one of the paths.
3. Convert the `stroke` on the second one to a `path`.
4. Merge the 2 resulting paths together.

**Comment by PeterShaggyNoble** [comment]
Alternatively, [this version](https://lbry.com/img/logo.svg) of the logo from [lbry.com](https://lbry.com) includes neither the additional points in the arrowhead, nor the `stroke`.

**Comment by PeterShaggyNoble** [comment]
Closing this out due to inactivity and @mondeja picking it up in #3235

**Pull request closed without merging**
