### PR TITLE
Add icon for Openverse

### LINKED ISSUE #7510: Request: Openverse
### Brand Name

Openverse

### Website

https://wordpress.org/openverse

### Popularity Metric

- This is an official WordPress.org (icon present; **site rank 3,742**) core project.
- Is sponsored by Automattic (icon present; **site rank 112,371**).
- Was first developed at Creative Commons (icon present) as CC Search.
- Indexes over 600M openly licensed creative works.

### Official Resources for Icon and Color

[Branding assets in GitHub repo](https://github.com/WordPress/openverse/tree/main/brand)

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by dhruvkb**
**Issue:** closes #7510 

openverse

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by sachinraja — CHANGES_REQUESTED** [review]
Seeing a difference:
image

red is original, white is yours
may want to try increasing the precision

**Comment by dhruvkb** [comment]
@sachinraja I've updated the icon with increased precision, could you take another look?

**Comment by sachinraja** [comment]
Not sure what happened, seeing a bigger difference now:
image
white is original, black is yours

**Comment by dhruvkb** [comment]
@sachinraja I've tried this again on a fresh canvas using the SVG from Figma. Hopefully there will not be any discrepancies this time.

**Comment by sachinraja** [comment]
I still see a difference with that. Here's my version which matches up with the original:
```xml
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Openverse</title><path d="M4.882 1.018C2.182 1.018 0 3.214 0 5.932c0 2.704 2.182 4.915 4.882 4.915Zm7.118 0c-2.686 0-4.882 2.196-4.882 4.914 0 2.704 2.182 4.915 4.882 4.915zm7.118 0c-2.696 0-4.881 2.2-4.881 4.914 0 2.714 2.185 4.915 4.88 4.915 2.697 0 4.883-2.2 4.883-4.915 0-2.714-2.186-4.914-4.882-4.914zm0 12.093c-2.696 0-4.881 2.2-4.881 4.915 0 2.714 2.185 4.914 4.88 4.914 2.697 0 4.883-2.2 4.883-4.914 0-2.714-2.186-4.915-4.882-4.915ZM12 13.126c-2.686 0-4.882 2.196-4.882 4.9S9.3 22.94 12 22.94zm-7.118.04c-2.7 0-4.882 2.197-4.882 4.9 0 2.719 2.182 4.916 4.882 4.916Z" /></svg>
```

Not sure how good Figma is for editing SVGs, I use [Inkscape](https://inkscape.org/) so you might want to try that. Feel free to use the SVG I derived in this PR though.

**Review by sachinraja — APPROVED** [review]

**Pull request merged**
