### PR TITLE
Add OpenAI & OpenAI Gym

### LINKED ISSUE #2981: OpenAI
**Name:**
OpenAI
**Website:**
https://openai.com/
**Official resources for icon and color:**
Raw SVG on the website navigation bar

**Name:**
OpenAI Gym
**Website:**
https://gym.openai.com/
**Official resources for icon and color:**
https://gym.openai.com/assets/dist/home/header/home-icon-54c30e2345.svg

### PR DESCRIPTION
**Pull request by HeshamMeneisi**
**Issue:** Closes #2981

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`
  - [x] I ran `npm test` and fixed errors

### Description
The OpenAI hex is based on their choice in some images on their website (and other partners) like this one: https://openai.com/content/images/2020/02/openai-pytorch.png

The Gym hex is based on the logo color on the product page https://gym.openai.com/
The hexagonal shape was omitted since the logo appears often without it (including the same page) so it's not really part of their brand.

### Preview

openai

openaigym

### CODE REVIEW

**Comment by birjolaxew** [comment]
Thanks for the contribution! I have a couple questions before merging:

When comparing the OpenAI Gym SVG to the [official SVG](http://gym.openai.com/assets/dist/home/footer/home-cta-d0fb5e0574.svg), it seems to have been stretched slightly vertically (in this comparison red is the official version):

<p align="center"></p>

Other than that the SVGs look good to me. Could you update it to match the official version?

Other than that, my only question is where the colors are taken from. Seems to be that OpenAI usually use `#000` or `#FFF` for their logo, and OpenAI Gym seems to use a variety of similar colors, including `#0081A5` (official SVG linked above), `#1A8E99` (official logo with hexagon) or `#000` (logo in their documentation header).

**Comment by HeshamMeneisi** [comment]
For Gym code I used the one in the official icon without a hexagon but I used a drop picker then and I see there's a red-shift in the hex for some reason `#3181A5` instead of `#0081A5`, weird but I will fix that. OpenAI use b/w on their website depending on the background but they use that hex here: https://openai.com/content/images/2020/02/openai-pytorch.png (`#412991`)
And also on other resources like this article: https://www.ciol.com/microsoft-invest-1-billion-openai-develop-agi/ (`#47328C`)
And on this logo database: https://dwglogo.com/openai-logo/ (`#52295A`)
All close shades of purple so I picked the one on their official site. Since these are images the code is an approximation of a few pixels.

As for the slight stretch, I think this happened when the icon was resized to 24x24 as it should be 25x24 to keep the ratio. Any ideas on how to resolve this issue?

**Comment by birjolaxew** [comment]
Seems fair enough. I'll let another @simple-icons/maintainers have the final say on colors, but I'm fine with the purple.

As for the resizing, it depends a bit on which program you use. In Illustrator for instance, you have the transform window (Window > Transform if you don't have it in your topbar), which lets you specify the size and position of the path. Setting it to `X: 12pt, Y: 12pt` centers the path, while setting `W: 24pt` (if the path is wider than it is tall) resizes it to fit the 24x24 viewport.  
Make sure the <sub><sub><sub><sub><sub><sub><sub></sub></sub></sub></sub></sub></sub></sub> button is enabled to maintain the aspect ratio of the path.

image

**Comment by ericcornelissen** [comment]
For as far as I am familiar with OpenAI, I think purple is the right choice as a brand colour :+1:

**Comment by PeterShaggyNoble** [comment]
Are you still working on these, @HeshamMeneisi?

**Comment by HeshamMeneisi** [comment]
This got lost through the cracks but I can finalize it over the weekend.

**Comment by PeterShaggyNoble** [comment]
Closing this out due to inactivity, I'll get a fresh PR in for them shortly.

**Pull request closed without merging**
