### PR TITLE
Add Sefaria

### LINKED ISSUE #4534: Sefaria Icon
**Name:** Sefaria
**Website:** https://www.sefaria.org
**Alexa rank:** 30858
  

**Official resources for icon and color:**
  
https://github.com/Sefaria/Sefaria-Project/blob/master/static/img/logo/samekh.svg
Preference here is to only use the large 'icon' - without the text, if possible.  (The above link is the 'icon' part of https://github.com/Sefaria/Sefaria-Project/blob/master/static/img/logo/logo.svg which also contains the text)

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Sefaria

**Issue:** Closes #4534
**Alexa rank:** [~29.2k](https://www.alexa.com/siteinfo/sefaria.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
From the `icon.*` files available in [this directory](https://github.com/Sefaria/Sefaria-Project/tree/master/static/img/logo) it _looks_ like the colour should be a dark purple so I've used the one from [their website](https://www.sefaria.org/).

### CODE REVIEW

**Comment by adamrusted** [comment]
`icon.svg` uses `#18345D` as it's background colour. Comparing yours against that file shows a few inconsistencies in the source file, which I think we're fine to correct. Just going to check it against the `samekh.svg` file you've linked as source.

**Comment by fbernhart** [comment]
There is as well a SVG in the header of their website - just to add more confusion. 😉 

https://www.sefaria.org/static/img/logo.svg

I assume the website is more up-to-date than the SVG in the GitHub repo (which is 3 years old). So I would be in favour of keeping `#212E50`.

**Comment by adamrusted** [comment]
Fine by me. Does the SVG in the header match the PR icon? If so, this can be merged.

**Comment by fbernhart** [comment]
@adamrusted It does.

**Pull request merged**
