### PR TITLE
Updated Figma icon

### PR DESCRIPTION
**Pull request by adamrusted**
figma

**Issue:** Contributes to #3169
**Alexa rank:** [1,074](https://www.alexa.com/siteinfo/figma.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Swapped out for monochrome icon as per @service-paradis' [comment](https://github.com/simple-icons/simple-icons/issues/3169#issuecomment-731811968), and updated color to match branding guidelines.
Converted in Adobe Illustrator.
Ran through SVGO CLI and SVGLint.

### CODE REVIEW

**Comment by service-paradis** [comment]
Thank you @adamrusted for your contributions, really appreciated!
The logo looks perfect to me 💯 

Looks really difficult to pick a single color... They have 2 palettes 😅. One with logo colors and a second more intense (https://brand.figma.com/color.html)

I would like to know why the color `#FF2020` were chosen (intense palette middle color)?

This is the file found in the brand assets:
Figma-Logo-Colors

**Comment by adamrusted** [comment]
Hi @service-paradis, so I went with `#FF2020` from the grid in the image. Happy to change to one of the other suggested ones if it's preferred.

**Comment by service-paradis** [comment]
> Hi @service-paradis, so I went with `#FF2020` from the grid in the image. Happy to change to one of the other suggested ones if it's preferred.

Just wanted to know if there was any reason to choose the middle one 😄 
Maybe we can have another @simple-icons/maintainers opinion on it before merging?
https://brand.figma.com/color.html

**Comment by fbernhart** [comment]
How about using `#F24E1E`? It's mentioned in both color specs.

**Comment by service-paradis** [comment]
> How about using `#F24E1E`? It's mentioned in both color specs.

That is a really good point 😃! The first color of the logo also used in the intense palette. Sounds good to me? What do you think @adamrusted?

**Comment by adamrusted** [comment]
Fine by me - will update when I'm back in front of my computer. 👌

**Comment by adamrusted** [comment]
figma (1)

Fixed!

**Review by service-paradis — APPROVED** [review]
Thank you!

**Pull request merged**
