### PR TITLE
Add google bigtable

### LINKED ISSUE #5133: Google cloud services
Google Cloud has many services.
This is a total different realm than https://github.com/simple-icons/simple-icons/issues/4205
Note that Google Cloud has icon but also any one of it's services has it's own icon.

These services are highly popular.

Listing the most common (important ones):

- [x] BigQuery #9437
- [x] BigTable #9439
- [x] DataFlow #9450
- [x] DataProc #9451
- [x] Cloud Composer #9452
- [x] Pub/Sub #9466
- [x] Google Storage #9467
- [x] Cloud Spanner #9472
- [x] DataStudio #9473

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
googlebigtable

**Issue:** closes #5133 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from https://cloud.google.com/icons
Color: Taken from logo `#669df6`

> **Note**
> The source itself has misaligned objects in the icon

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @PratyushJayachandran,

thanks for your contribution to Simple Icons.

Can you check on the "spikes" of the icon? See picture below for what I mean. There are some small differences to the original.

image

**Comment by PratyushJayachandran** [comment]
> Hi @PratyushJayachandran,
> 
> thanks for your contribution to Simple Icons.
> 
> Can you check on the "spikes" of the icon? See picture below for what I mean. There are some small differences to the original.

I'll increase the precision. The spikes are there in original too

**Comment by PratyushJayachandran** [comment]
> Hi @PratyushJayachandran,
> 
> thanks for your contribution to Simple Icons.
> 
> Can you check on the "spikes" of the icon? See picture below for what I mean. There are some small differences to the original.
> 
> image

I have fixed it by increasing the precision to 4. Can you check it again.

**Comment by PeterShaggyNoble** [comment]
Jebus, that source icon is horrendous! 😮 Even just combing all the paths into one starts introducing some minor differences.

Given how riddled with imperfections the original is, I'd be OK in this instance with running with our best effort even if it's not a perfect match. What do you think, @dirien? Or we take some artistic license and clean it up completely.

**Comment by PratyushJayachandran** [comment]
> Jebus, that source icon is horrendous! 😮 Even just combing all the paths into one starts introducing some minor differences.
> 
> Given how riddled with imperfections the original is, I'd be OK in this instance with running with our best effort even if it's not a perfect match. What do you think, @dirien? Or we take some artistic license and clean it up completely.

So I spent some time to clean up the source. Attaching it here:
bigtable-cleaned-up

I redid with this as source. Please review again 😢

**Review by PeterShaggyNoble — APPROVED** [review]
Your cleaned up version looks good to me, @PratyushJayachandran, I'm happy to run with it as-is given the state of the original. As we _are_ taking a little artistic license, though, we'll need approval from one other member of the team before merging.

For consistency with other icons from this collection, though, should we not either go with Google blue or `#AECBFA` for the colour?

**Comment by PratyushJayachandran** [comment]
> Your cleaned up version looks good to me, @PratyushJayachandran, I'm happy to run with it as-is given the state of the original. As we _are_ taking a little artistic license, though, we'll need approval from one other member of the team before merging.
> 
> For consistency with other icons from this collection, though, should we not either go with Google blue or `#AECBFA` for the colour?

I'm fine with either. 

> Your cleaned up version looks good to me, @PratyushJayachandran, I'm happy to run with it as-is given the state of the original. As we _are_ taking a little artistic license, though, we'll need approval from one other member of the team before merging.
> 
> For consistency with other icons from this collection, though, should we not either go with Google blue or `#AECBFA` for the colour?

I'm fine if the color needs to be changed. I always picked color from the dominant color on the logo.

**Review by adamrusted — APPROVED** [review]
I'm happy with the hex as is. Also happy with the treatment given by @PratyushJayachandran to the icon. Unfortunately I can't download the source from your comment, it's giving me a 404. Given @PeterShaggyNoble has already approved the path though, I'm good to just run with it.

**Pull request merged**
