### PR TITLE
Add Altmetric

### PR DESCRIPTION
**Pull request by TomKellyGenetics**
Name: Altmetric
Website: https://www.altmetric.com/
Alexa Rank: 48,260
Colour: ##525252 (grey background to logo with white text)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

Source: https://www.altmetric.com/about-us/logos/

Altmetric_rgb

Popular in Academic publishing industry and research.

Preview of image:
g12

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @TomKellyGenetics  and thanks for the contribution.

The build is currently failing as the SVG should contain only the `title` and a single `path` - see our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) for more information. That said, in the absence of an official monochrome version, we'd need to take some liberties to make it monochrome (see, for example, @el1f's approaches to the new Google Maps icon in #2543) assuming it *can* be monochromised.

I'd also expect the colour to be either one of the colours from the button links in their website's stylesheet or one of the greys used in the footer.

**Comment by TomKellyGenetics** [comment]
Thanks, I've update the colour to the background for their logo with white text. I think this is similar to their website style.

I'm not sure how to get it to work in monochrome (I converted to greyscale in Inkscape). Here is a copy of the full colour SVG (source EPS).

[altmetric_full_colour.svg.txt](https://github.com/simple-icons/simple-icons/files/4315750/altmetric_full_colour.svg.txt)

**Comment by PeterShaggyNoble** [comment]
One possible treatment of it could be the below. But I fear that it may be diverging too far from the original. Do you want to try reaching out to them, see if they have a (preferred) monochrome version or even if they allow it to be monochromised at all?

Altmetric

**Comment by TomKellyGenetics** [comment]
It’s a much better job in monochrome than I could come up with. They have variations in different colours to display which metrics are scored. For example here’s one generated by them.

B8F93501-42F8-481F-9483-31BAC8401384

**Comment by TomKellyGenetics** [comment]
Here are some examples of the metric they generate. They allow different colours so I think this would be okay.

DDBB1ECB-DB8D-48B2-8D83-93940C99C454
6E871064-6F9F-46BF-97C7-DAC98028C12D

**Comment by el1f** [comment]
Keep in mind that they state that the donut and logo are separate entities

**Comment by TomKellyGenetics** [comment]
Fair point, it might be worth reaching out to them and checking.

**Comment by PeterShaggyNoble** [comment]
Do you want to contact them yourself, @TomKellyGenetics or would you prefer for one of us to do so?

**Comment by TomKellyGenetics** [comment]
@PeterShaggyNoble I've reached out to their social media account and they're going to get back to me. https://twitter.com/altmetric/status/1238530014548803585?s=20

**Comment by TomKellyGenetics** [comment]
Altmetric got back to me and they're happy to be added to the repo with minor changes to the monochrome logo. I've converted it to SVG (although I'm having trouble combining the paths). 

http://ow.ly/d/8nxd
https://twitter.com/altmetric/status/1239962479196811265/photo/1

ETU7Tc0WoAE39Ka
altmetric
[altmetric.svg.txt](https://github.com/simple-icons/simple-icons/files/4346479/altmetric.svg.txt)

**Comment by PeterShaggyNoble** [comment]
Thanks, @TomKellyGenetics. I'm a bit confused, though; the image they posted on Twitter has the segments of the donut filled but the PDF they linked you to has them outlined 🤔

Unfortunately, Inkspace isn't playing nice when attempting to convert the strokes in both the PDF & your SVG to paths so I can't recreate either version for you - we'll need someone with better software (or better SVG skills!) to give it a try.

**Comment by el1f** [comment]
Will try and give it a try with Affinity Designer later on!

**Comment by el1f** [comment]
Should be ready to copypaste!
image


```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Altmetric icon</title><path d="M19.258 12.233a7.241 7.241 0 01-1.75 4.496 8.503 8.503 0 01-.945 2.702v.001a8.551 8.551 0 01-6.707 4.377c.696.125 1.413.192 2.144.192a11.957 11.957 0 005.35-1.256 8.137 8.137 0 002.728-8.622v-.002a8.14 8.14 0 00-.82-1.888zm-2.65 6.15c.144-.351.265-.714.36-1.089a7.242 7.242 0 01-4.417 1.945l-.183.126a8.553 8.553 0 01-10.23-.527 12.038 12.038 0 006.047 4.543 8.135 8.135 0 008.015-4.148l.002-.001.026-.047.018-.035.017-.032.018-.033.026-.05.016-.032.018-.033.017-.035.008-.018.015-.03.017-.034.025-.053.015-.03.016-.035.025-.052.014-.03.015-.036.016-.033.008-.02.013-.03.015-.034.012-.03.012-.025.012-.03.012-.031zm2.563-10.618a8.122 8.122 0 00-1.876-.731 7.241 7.241 0 011.944 4.416c.551.777.97 1.64 1.235 2.556h.001a8.552 8.552 0 01-1.638 7.858 12.042 12.042 0 004.544-6.048c.031-.28.048-.559.05-.837v-.197l-.001-.039-.001-.038-.002-.04v-.053l-.003-.036v-.037l-.003-.037-.002-.036-.002-.037-.002-.036a8.139 8.139 0 00-4.184-6.594l-.031-.017-.03-.017zM.19 9.857A12.09 12.09 0 00-.001 12c0 1.923.453 3.74 1.257 5.351a8.132 8.132 0 008.607 2.731 8.1 8.1 0 001.904-.824 7.236 7.236 0 01-4.496-1.75 8.523 8.523 0 01-2.662-.923l-.038-.022-.001.001A8.554 8.554 0 01.19 9.857zM5.159 2.14A12.04 12.04 0 00.62 8.186c-.05.446-.062.889-.04 1.327l.003.043.003.039.002.04.004.055.003.035.002.037.003.035A8.14 8.14 0 004.77 16.2l.04.022a8.085 8.085 0 001.895.743A7.245 7.245 0 014.76 12.55a8.468 8.468 0 01-.563-.908l-.009-.016-.022-.042-.021-.042-.022-.043-.022-.041-.02-.042-.006-.01a7.433 7.433 0 01-.13-.276l-.006-.012-.02-.044-.019-.043-.018-.043-.019-.043-.017-.044-.019-.043-.005-.012c-1.171-2.864-.73-6.23 1.336-8.706zm18.65 12.002c.127-.706.192-1.423.192-2.142a11.957 11.957 0 00-1.256-5.35 8.134 8.134 0 00-10.511-1.907 7.235 7.235 0 014.494 1.749c.948.16 1.861.48 2.701.945h.002a8.551 8.551 0 014.378 6.705zM14.068.177A11.926 11.926 0 0012 .001c-1.924 0-3.742.45-5.352 1.255a8.115 8.115 0 00-2.936 7.701l.006.041.008.04.007.04.007.04.008.04c.176.907.508 1.791.994 2.61a7.237 7.237 0 011.75-4.498l.025-.145.004-.012.003-.014.003-.013.005-.027.027-.138v-.006a8.62 8.62 0 01.765-2.145C8.496 2.486 10.654.793 13.245.286h.004c.272-.049.545-.085.819-.109zm-2.437 4.46a8.553 8.553 0 0110.234.527A12.038 12.038 0 0015.794.61l-.059-.018a8.996 8.996 0 00-1.887.022l-.037.004-.037.004-.035.005a8.024 8.024 0 00-.415.064c-2.466.482-4.516 2.092-5.632 4.265l-.016.03-.014.028-.016.03a8.299 8.299 0 00-.614 1.66A7.25 7.25 0 0111.45 4.76c.047-.034.097-.068.146-.101l.034-.023z"/></svg>
```

**Comment by TomKellyGenetics** [comment]
simpleicons (3)

Thanks @el1f that works great. I'll update the PR. Both images are provided Altmetric social media account so they should approve of this. I tried extracting an SVG from the PDF with bitmap trace.

**Comment by PeterShaggyNoble** [comment]
Thanks for helping out on this one, @el1f :+1:

Could you double check it, though, as it's not lining up with either version provided by Altmetric (your version in red)?

**Comment by el1f** [comment]
image

I actually used the PDF version but later expanded the fills so that they would touch the border. Should I try and trace the PNG as I think that the outlined version wouldn't scale all that well on smaller sizes?

P.S.
I've tried overlaying my version over the png they shared on twitter and I get this:
image

Now I'm genuinely confused.

**Comment by PeterShaggyNoble** [comment]
> Now I'm genuinely confused.

Me, too 🤔 Strange that we're both getting different results. If someone else can confirm that they're getting the same result as you then I think this is good to go :+1:

> I tried extracting an SVG from the PDF with bitmap trace.

@TomKellyGenetics, Inkscape and I'm sure many other programmes, can open PDFs directly making it easier to get at any vector images they may contain.

**Comment by TomKellyGenetics** [comment]
@PeterShaggyNoble Yes I opened the PDF provided by Altmetric but it had a pixelated image embedded in it, hence the bitmap trace.

Can we hold off on merging? Altmetric has contacted me with this request:
> Thanks so much for doing this. Before you proceed, could you give us some time to review the licencing/permissions for images on Simple Icons?

**Comment by TomKellyGenetics** [comment]
I've contacted Altmetric and their legal team has advised against this due to License concerns. What does @simple-icons typically do here? I'm okay to close this PR if this is problem. Thanks for your time.

**Comment by PeterShaggyNoble** [comment]
That's a shame, especially after all the work that went into this but, ultimately, we need to respect the wishes of the company with regard to the use of and protection of their brand so, at this point, we won't be able to add it.

Thanks for your efforts, @TomKellyGenetics and for your help on it, @el1f :+1:

**Pull request closed without merging**
