### PR TITLE
Add Prime

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Prime

**Issue:** #2989

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon is from the "Prime blue" logo on page 11 of the [style guide](https://images-na.ssl-images-amazon.com/images/G/01//gift-certificates/corporate/3PStyleGuideQ12019rev7040819002._CB1559605351_.pdf) available at the source URL, colour can be found on page 10. Possible alternative name: Prime

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Given the statement on page 13 of the PDF linked above, should we add _both_ Prime (i.e., rename this one) _and_ Amazon Prime?

**Comment by ericcornelissen** [comment]
Hmm it would seem so

**Comment by PeterShaggyNoble** [comment]
OK, I've renamed this as "Prime" and added Amazon Prime to my to-do list.

**Comment by ericcornelissen** [comment]
Thanks @PeterShaggyNoble, it is much appreciated 👍

**Pull request merged**
