### PR TITLE
Add EDEKA icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** #
**Alexa rank:** 22,274
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
image

@dirien Notice the slight discrepancy on the D. I used the svg file from wikipedia, I assume you used that one as well. Can you give it another pass?

**Comment by dirien** [comment]
@jorgeamadosoria, redone the icon and exported with precision 4 otherwhise the belly of D would slim down...

**Comment by jorgeamadosoria** [comment]
Looks good enough to me.

**Review by jorgeamadosoria — COMMENTED** [review]
good enough

**Pull request merged**
