### PR TITLE
Add Zomato

### LINKED ISSUE #3952: Request:  Zomato Icon
**Name:** Zomato
**Website:** https://www.zomato.com/
**Alexa rank:** 1,411
  

**Official resources for icon and color:** https://www.zomato.com/

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Zomato

**Issue:** Closes #3952
**Alexa rank:** [~1.3k](https://www.alexa.com/siteinfo/zomato.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon & colour from [SVG](https://b.zmtcdn.com/images/logo/zomato_flat_bg_logo.svg) in [website](https://developers.zomato.com/) footer. Colour confirmed in [this PDF](https://www.zomato.com/blog/wp-content/uploads/2019/04/Zomato-Brand-Book.pdf), which also, unfortunately, confirms that we can't just use the "Z". ~What I'm _not_ 100% on, though, is if we definitely need to include the box. That PDF states that "This unit serves as Zomato’s app and website icon.", which I imagine covers the use case of the majority of our users.~ **EDIT:** The wordmark won out.

### CODE REVIEW

**Comment by fbernhart** [comment]
I would say that we could remove the square. Their brand guidelines say about the version without the square:
> "This unit is the primary brand logo and must be used across all brand assets including print, digital, and other offline media."

"primary brand logo" is the key word in my opinion here. But I'm happy to merge either version. 😊

**Comment by PeterShaggyNoble** [comment]
Although our interpretations differ, @fbernhart, I too would prefer if we could just add the wordmark. What do the other @simple-icons/maintainers think?

**Comment by hasthamalp** [comment]
Brand name in the logo  preview is anydesk

**Comment by PeterShaggyNoble** [comment]
I was hoping nobody would notice that, @hasthamalp! 🙈

**Comment by adamrusted** [comment]
Noticed what? @PeterShaggyNoble 👀

On another note, I'd also be fine with just the wordmark.

**Comment by PeterShaggyNoble** [comment]
3 votes for the wordmark is consensus enough for me 🙂 Will update momentarily ...

**Comment by PeterShaggyNoble** [comment]
Done, @fbernhart & @adamrusted.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @PeterShaggyNoble 🥳

**Comment by hasthamalp** [comment]
> I was hoping nobody would notice that, @hasthamalp!

@PeterShaggyNoble :smile:

**Pull request merged**
