### PR TITLE
Add Istio icon

### PR DESCRIPTION
**Pull request by swarup4741**
istio

Issue: #6090 
Alexa rank: 88,863

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`
  - [x] tests performed
  - [x] linting performed  

### Description
added the [istio](https://github.com/istio/istio/raw/master/logo/istio-bluelogo-whitebackground-unframed.svg) icon and added the metadata to `_data/simple-icons.json` with hex value `466AB1` as provided in issue #6090 and also fixed some linting issues as well.

### CODE REVIEW

**Review by ericcornelissen — CHANGES_REQUESTED** [review]
The SVG looks spot on (_even_ with this low precision), nice work @swarup4741!

Before we can merge this in though, I have two requests:

- Can you revert the change the `package-lock.json`?
- If you used the SVG linked in the issue as source material, could you update the `"source"` to `"https://github.com/istio/istio/blob/5a047251817eb2523af297607b7614120812e47a/logo/istio-bluelogo-whitebackground-unframed.svg"`? Else, could you elaborate on where exactly on the website you found the SVG and why you chose it over this one?

**Comment by swarup4741** [comment]
> The SVG looks spot on (_even_ with this low precision), nice work @swarup4741!
> 
> Before we can merge this in though, I have two requests:
> 
> * Can you revert the change the `package-lock.json`?
> * If you used the SVG linked in the issue as source material, could you update the `"source"` to `"https://github.com/istio/istio/blob/5a047251817eb2523af297607b7614120812e47a/logo/istio-bluelogo-whitebackground-unframed.svg"`? Else, could you elaborate on where exactly on the website you found the SVG and why you chose it over this one?

can u tell me how can i revert `package-lock.json`

**Comment by ericcornelissen** [comment]
Thank you for updating the source @swarup4741. However, it looks like the changes to `package-lock.json` are still there, it might be easiest to just copy the content from the `package-lock.json` on the `develop` branch and pasting it to the file on your branch (the changes are due to you using npm v7, and this project still using a lockfile generated by npm <7).

Also, I didn't catch this the first time around, but where exactly did you get the color hex value from? The SVG in the source has `#466BB0`, not `#466AB1` 🤔

**Comment by swarup4741** [comment]
> Thank you for updating the source @swarup4741. However, it looks like the changes to `package-lock.json` are still there, it might be easiest to just copy the content from the `package-lock.json` on the `develop` branch and pasting it to the file on your branch (the changes are due to you using npm v7, and this project still using a lockfile generated by npm <7).
> 
> Also, I didn't catch this the first time around, but where exactly did you get the color hex value from? The SVG in the source has `#466BB0`, not `#466AB1` 🤔

I got the hex the value by using a color picker tool... shall I update the hex value ?

**Comment by ericcornelissen** [comment]
> I got the hex the value by using a color picker tool... shall I update the hex value ?

Using the color picker tool on the source SVG? Or on something else? From the source SVG I'm getting `#466BB0` with the color picker as well. If you got the brand color from somewhere else that could be valid as well. I'm not at all familiar with the brand, but it seems _blue_ is the brand color and I'm not seeing any specific color they prefer so running the value in the SVG seems as good as any. If you're familiar with the brand though, feel free to argue for any color you think makes sense 🙂

**Comment by swarup4741** [comment]
> > I got the hex the value by using a color picker tool... shall I update the hex value ?
> 
> Using the color picker tool on the source SVG? Or on something else? From the source SVG I'm getting `#466BB0` with the color picker as well. If you got the brand color from somewhere else that could be valid as well. I'm not at all familiar with the brand, but it seems _blue_ is the brand color and I'm not seeing any specific color they prefer so running the value in the SVG seems as good as any. If you're familiar with the brand though, feel free to argue for any color you think makes sense 🙂

No more worries.. i updated the hex to `#466BB0`

**Comment by ericcornelissen** [comment]
In that case the hex value seems fine (it's always possible to change this later if someone disagrees) - the only thing left to do is revert the changes of the `package-lock.json` file. If you need help with that, I can do it for you before and merge it in immediately after that.

As an aside, there's no need to merge `develop` in whenever the option appears on your Pull Request. Generally, not much changes on the `develop` that will affect your work. The reason we require the branch to be up-to-date with `develop` at this point in time is because there are still some old Pull Requests that we know of that may require some changes in order to be merged. In any case, we will take care of merging `develop` into your branch when it's ready to merge for you 🙂

**Comment by swarup4741** [comment]
> In that case the hex value seems fine (it's always possible to change this later if someone disagrees) - the only thing left to do is revert the changes of the `package-lock.json` file. If you need help with that, I can do it for you before and merge it in immediately after that.
> 
> As an aside, there's no need to merge `develop` in whenever the option appears on your Pull Request. Generally, not much changes on the `develop` that will affect your work. The reason we require the branch to be up-to-date with `develop` at this point in time is because there are still some old Pull Requests that we know of that may require some changes in order to be merged. In any case, we will take care of merging `develop` into your branch when it's ready to merge for you 🙂

I have changed the `package-lock.json` file as per you said.. just copied the whole from `develop` and pasted it in my `package-lock.json` file in my branch and pushed it

**Comment by ericcornelissen** [comment]
> I have changed the package-lock.json file as per you said.. just copied the whole from develop and pasted it in my package-lock.json file in my branch and pushed it

My apologies, the GitHub interface says there's 3 changed files so I assumed you didn't change anything yet 😅 Though you did revert most of the changes, you did end up changing (somehow) some of the whitespace in that file. Could you revert those changes as well? (Just to keep our commit history clean.)

**Review by swarup4741 — COMMENTED** [review]
removed the white-spaces....

**Comment by ericcornelissen** [comment]
> 
> 
> removed the white-spaces....

As you can see [in the GitHub UI](https://github.com/simple-icons/simple-icons/pull/6093/files) there are still changes between `package-lock.json` in your branch and on `develop`...

If you want I can take care of this and merge this in for you 🙂 If you want to give it another try, make sure you are copying the content of `package-lock.json` from the most recent commit on develop, e.g. [this one](https://raw.githubusercontent.com/simple-icons/simple-icons/develop/package-lock.json).

**Comment by swarup4741** [comment]
> > removed the white-spaces....
> 
> As you can see [in the GitHub UI](https://github.com/simple-icons/simple-icons/pull/6093/files) there are still changes between `package-lock.json` in your branch and on `develop`...
> 
> If you want I can take care of this and merge this in for you 🙂 If you want to give it another try, make sure you are copying the content of `package-lock.json` from the most recent commit on develop, e.g. [this one](https://raw.githubusercontent.com/simple-icons/simple-icons/develop/package-lock.json).

I’ll give it another try … if this time if i’m unable to fix it (somehow) then you please kindly take over and make it happen … I’ll make the changes tomorrow.. (thank you for guiding so much … I’m learning a lot)

**Review by ericcornelissen — APPROVED** [review]
> I’ll give it another try … if this time if i’m unable to fix it (somehow) then you please kindly take over and make it happen … I’ll make the changes tomorrow.. (thank you for guiding so much … I’m learning a lot)

Almost did it, just one final newline missing in `package-lock.json` - fixed that one for you :slightly_smiling_face: 

Thanks for working on this one @swarup4741 :tada:

**Pull request merged**
