### PR TITLE
Add New Japan Pro-Wrestling

### LINKED ISSUE #2784: NJPW
**Name:** NJPW (New Japan Pro-Wrestling)
**Website:** https://www.njpw.co.jp/ - https://www.njpw1972.com/ - https://njpwworld.com/
**Alexa Rank:** [~106k](https://www.alexa.com/siteinfo/njpw.co.jp) - [~154k](https://www.alexa.com/siteinfo/njpw1972.com) - [~51k](https://www.alexa.com/siteinfo/njpwworld.com)
**Colour:** `#ff160b` or `#ffd810` - I'd lean towards the red.
**Official resources for icon and color:** https://en.wikipedia.org/wiki/File:New_Japan_Pro_Wrestling_Logo_2.svg

[NJPW
NJPW](https://github.com/simple-icons/simple-icons/files/4330648/njpw.zip)

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
New Japan Pro-Wrestling

**Issue:** Closes #2784

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
~Possible alternative names: `New Japan Pro-Wrestling`, `NJPW World`
Possible alternative colour: `#ffd810`~

### CODE REVIEW

**Comment by runxel** [comment]
So we're doing the sports thing, yes?

**Comment by mondeja** [comment]
Seems that this is an organization/company related with sports, so I think after #4274 that it's within the scope of the project.

**Comment by adamrusted** [comment]
@simple-icons/maintainers are we okay to merge this icon now?

**Comment by fbernhart** [comment]
@adamrusted If it matches the source, it can be merged. 😊👍🏼

**Comment by adamrusted** [comment]
Just rebuilt this from source to test it, I tried to maintain the outer ring.
Did we want to look at the PR icon (right) or the rebuild-from-source version (left)?

image
image

If we want to go with the right-hand path, we can merge it straight away.

**Comment by PeterShaggyNoble** [comment]
Pro-wrestling would fall into the entertainment category moreso than the sports category but, in the context of sports, it would be a sporting organisation rather than a team, yes - second biggest company in the world.

Another option would be instead to add this as their [NJPW World](https://njpwworld.com/) streaming service, using the gold colour. But, for consistency, we'd then need to rename our WWE icon as WWE Network, which I _believe_, would also require the addition of the "Network" wordmark below the icon, which I'd personally be opposed to.

@adamrusted, I followed the monochrome treatment seen, in among other places, in the logo in the header of NJPW World.

**Comment by adamrusted** [comment]
> @adamrusted, I followed the monochrome treatment seen, in among other places, in the logo in the header of NJPW World.

Not to worry then - I hadn't looked *too* extensively into the other sites.

> Pro-wrestling would fall into the entertainment category moreso than the sports category but, in the context of sports, it would be a sporting organisation rather than a team, yes - second biggest company in the world.

I'm happy to merge this then, since @fbernhart approved it in https://github.com/simple-icons/simple-icons/pull/2791#issuecomment-753961063 - will leave it until later today if any other @simple-icons/maintainers have any objections.

**Review by adamrusted — APPROVED** [review]
Given no objections raised after https://github.com/simple-icons/simple-icons/pull/2791#issuecomment-758544309 - merging this one!

**Review by adamrusted — CHANGES_REQUESTED** [review]
Or not. @PeterShaggyNoble this is now showing Collinear segments in the updated Linter. Any chance you could take a look?

**Comment by PeterShaggyNoble** [comment]
Oof, identifying them all is going to be a fun process given the sheer volume of points and the curvature of some of the letters.

In the meantime, I've changed the name to New Japan Pro-Wrestling as that's how they refer to themselves officially.

**Comment by PeterShaggyNoble** [comment]
Wait, hang on, the linter reports:

> collinear-segments Collinear segment "l-0.14 0.172" in path (should be removed)

Does that mean there's actually only 1 point that needs removing? Let's see ...

**Comment by PeterShaggyNoble** [comment]
Had a little trouble finding it in the SVG markup (easier than trying to find it in Inkscape!) but t looks like that's resolved now.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @PeterShaggyNoble 🎉

**Pull request merged**
