### PR TITLE
Add commitlint icon

### PR DESCRIPTION
**Pull request by SimonGolms**
commitlint

**Issue:** #6739 
**Alexa rank:** [2 053 680](https://www.alexa.com/siteinfo/commitlint.js.org)
**GitHub:** [9.4k](https://github.com/conventional-changelog/commitlint)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- The [icon.svg](https://github.com/conventional-changelog/commitlint/blob/0b177635472214faac5a5800ced970bf4d2e6012/docs/assets/icon.svg) icon uses a text element, therefore I used the [icon.png](https://github.com/conventional-changelog/commitlint/blob/0b177635472214faac5a5800ced970bf4d2e6012/docs/assets/icon.png) file as a reference and identified Menlo as the used font.
- I picket the color `#000000`, as it was the most prominent in the svg icon.
- I used Sketch to outline the text, isolate the symbol, flatten it and scale it to the appropriate viewbox.
- With the SVGO command line tool I optimized the icon with a precision of 3.

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @SimonGolms,

the elemnts do not fit 100% to the icon.png you linked in the PR.

image

asking @jorgeamadosoria or @sachinraja to help me.

**Comment by sachinraja** [comment]
The icon matches perfectly with `icon.svg` though

**Comment by jorgeamadosoria** [comment]
I've updated the branch with a new version of the icon, please check again

**Review by dirien — COMMENTED** [review]
@jorgeamadosoria 
Maybe I checking it wrong but when trying to align the png over the icon i still get this:

image

**Comment by sachinraja** [comment]
As a sidenote I think we should avoid pushing directly to someone else's branch. This is still @SimonGolms's PR

**Comment by jorgeamadosoria** [comment]
@dirien 
are you comparing with a PNG or aSVG? the image in the comparison seems pixelated

**Comment by SimonGolms** [comment]
Sorry for the long absence. I am fine with the changes and completion of the PR of @jorgeamadosoria 😉

**Pull request merged**
