### PR TITLE
Add NordVPN

### PR DESCRIPTION
**Pull request by huuphongnguyen**
nordvpn

**Issue:**
**Alexa rank:** [2174](https://www.alexa.com/siteinfo/nordvpn.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- I got SVG code from View Code of [NordVPN.com](https://nordvpn.com)
- I used Sketchapp to adjust and export
- I used https://jakearchibald.github.io/svgomg/ to optimize
- I used Inscape to compare with source icons to make sure it fit.

### CODE REVIEW

**Comment by service-paradis** [comment]
Thank you @huuphongnguyen for your contribution!

There is a page including their logos available at https://nordvpn.com/press-area/
It would be better to use this for the source. You can also add a `guidelines` entry with this page since we can find some guidelines in this page.

I'm also wondering if we should include the wordmark since it is present in every file found in their press assets. I will ask the opinion of another @simple-icons/maintainers about this!

**Comment by ericcornelissen** [comment]
> I'm also wondering if we should include the wordmark since it is present in every file found in their press assets. I will ask the opinion of another **simple-icons/maintainers** about this!

It's used without wordmark in various places (favicon, LinkedIn, app icons) and I'd say it's pretty recognizable so unless it's explicitly stated somewhere that the wordmark should be included I think we can and should leave it out

**Comment by service-paradis** [comment]
The only "_explicit_" mention is « Use our brand resources provided below. » which is not a strong affirmation. Thank you @ericcornelissen for your feedback, we're probably ok with the icon only.

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @huuphongnguyen 👍🏻

The SVG looks spot on to me. However, from both the logo on the website and those available to download, it looks like the colour should be `#4687ff`. Once that change is made, along with the changes to the JSON @service-paradis mentioned above then this can be merged straight in.

**Comment by PeterShaggyNoble** [comment]
Hope you don't mind, @huuphongnguyen but, in the interests of getting this merged and clearing out some of our backlog, I went ahead and made those changes for you.

**Pull request merged**
