### PR TITLE
Add Wikivoyage.

### PR DESCRIPTION
**Pull request by klu17**
**Issue:** #4364
**Alexa rank:** 37,056

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
**HEX:** `#006699` is used for Wikimedia. The two are strongly related. Footer and buttons are this color on [site](https://www.wikivoyage.org/).

### Preview
image

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks again @klu17!
There appears to be some differences between your PR (red) and source (black) - could you take another look at this one please?

image

**Comment by klu17** [comment]
@adamrusted Updated.

**Review by adamrusted — APPROVED** [review]
LGTM! 🚢

**Comment by hasthamalp** [comment]
thank you for the effort

**Comment by hasthamalp** [comment]
but the icon is not found in the simple icon site

**Comment by fbernhart** [comment]
@hasthamalp It will be by next Sunday. We're updating our website every Sunday.

**Pull request merged**
