### PR TITLE
Add WeTransfer icon

### PR DESCRIPTION
**Pull request by emma-sg**
**Issue:** #3634 
**Alexa rank:** 132
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Vector was sourced from the header on https://wetransfer.com, color was sourced from the color of buttons and other UI elements on the same page. Their corporate page uses a slightly different color for the header (https://wetransfer.pr.co/, `#2AA9FB`), but it seems to me that was picked for better contrast with white text.

wetransfer

### CODE REVIEW

**Review by service-paradis — CHANGES_REQUESTED** [review]
Thanks for you PR 💯 
There are some slight differences with the original logo (probably cause by the optimization process, you ca try a precision of 4 maybe):
image
image
image

**Comment by edensg** [comment]
I see, can you re-check with this commit?

**Comment by service-paradis** [comment]
> I see, can you re-check with this commit?

Thanks again for your work. It is still looking different than the original:
image

You can try to optimize with a precision of 4 in SVGO

**Comment by edensg** [comment]
Oh weird, it came out even worse than before. I'll give it another go again later today — you're comparing against the svg in the header of [wetransfer.com](https://wetransfer.com/)?

**Comment by service-paradis** [comment]
> Oh weird, it came out even worse than before. I'll give it another go again later today — you're comparing against the svg in the header of [wetransfer.com](https://wetransfer.com/)?

I'm comparing with the header logo found at https://about.wetransfer.com/
```svg
<svg id="logo" viewBox="0 0 43 19.8" class="wetransfer-logo" data-tracking-label="clickLogo">
  <title>Welcome (back) to WeTransfer</title>
  <path d="M34.9,19.8c3.2,0,5.6-1,6.8-2.3c0.7-0.7,1.5-1.9,0.9-2.8c-0.5-0.8-1.3-0.9-2.3-0.4c-1,0.5-2.1,0.7-3.3,0.7 c-1.2,0-2.5-0.4-3.2-1.1c-0.8-0.8-1.3-1.9-1.3-3.1c0-0.3,0.2-0.3,0.5-0.1c0.9,0.7,2.1,1,3.9,1c3.2,0,6-2.1,6-5.4 c0-3.5-3.3-6.1-8.3-6.1c-5.6,0-9.9,3.6-9.9,9.7C24.8,15.5,28.6,19.8,34.9,19.8z">
  </path>
  <path d="M11.8,13.9c0.6,0,0.9,0.3,1.4,1l1.8,2.8c0.7,1.1,1.2,1.8,2.6,1.8c1.3,0,1.9-0.5,2.6-2 c0.8-1.8,1.6-4,2.4-6.9c0.8-3.3,1.2-5.3,1.2-6.9c0-1.7-0.5-2.6-2.3-3C18.8,0.3,15.5,0,11.8,0c-3.7,0-7,0.3-9.5,0.7 C0.5,1.1,0,2,0,3.7s0.4,3.7,1.2,6.9c0.8,2.9,1.6,5.1,2.4,6.9c0.6,1.5,1.2,2,2.6,2c1.3,0,1.9-0.7,2.6-1.8l1.8-2.8 C10.9,14.2,11.2,13.9,11.8,13.9z">
  </path>
</svg>
```

You can try different level of precision with SVGO (between 3 and 5). Sometimes, it tends to oversimplifies round path.

**Review by adamrusted — APPROVED** [review]
PR icon (red) matches up perfectly with the one on WeTransfer homepage (black), which seems to be the neater path when compared to the [about page](https://about.wetransfer.com/) icon. 

image


The 'corporate' logo for WeTransfer ([found here](https://wetransfer.pr.co/media_kits/217754/)) varies wildly from this one, so I think we're safe to use the `we` icon used on the homepage. Thanks for your work @emma-sg!

**Pull request merged**
