### PR TITLE
Remove Staticman

### PR DESCRIPTION
**Pull request by fbernhart**
**Issue:** #3169 
**Alexa rank:** -

### ~Checklist~
  ~- [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)~
  ~- [x] I optimized the icon with SVGO or SVGOMG~
  ~- [x] The SVG `viewbox` is `0 0 24 24`~

### ~Description~
~I took the already used SVG.~
~I used Inkscape to fix size and center~
~I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG~

### Edit
This PR removes the Staticman icon from Simple Icons as the brand is "out of scope". See the discussion below for details.

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
image

Tiny differences between PR (red) and source (black) - could you take a quick look at this?

**Comment by fbernhart** [comment]
@simple-icons/maintainers How about removing this one?

Alexa rank: [3,209,566](https://www.alexa.com/siteinfo/staticman.net)
Github stars: [1,900](https://github.com/eduardoboucas/staticman)

The statistics clearly say: `Out of scope`

**Comment by ericcornelissen** [comment]
> @simple-icons/maintainers How about removing this one (instead of updating it)?
> 
> Alexa rank: [3,209,566](https://www.alexa.com/siteinfo/staticman.net)
> Github stars: [1,900](https://github.com/eduardoboucas/staticman)
> 
> The statistics clearly say: `Out of scope`

Seems to be a very old addition -  see #655, #667, and #669 - when the guidelines weren't quite as "strict" yet. I'm okay with removing it :+1:

**Comment by PeterShaggyNoble** [comment]
@fbernhart, could you update the original post to clarify that this PR will remove this icon, please?

**Review by PeterShaggyNoble — APPROVED** [review]
Looks good to me 👍🏻 Still way beyond our scope so once the conflicts have been resolved, this can be merged straight in.

**Pull request merged**
