### PR TITLE
Correct Ruby on Rails icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** #3169
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- I took the already used SVG.
- I used Inkscape to fix size and center
- I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Looks good @service-paradis, one question: am I correct that you used an SVGOMG precision of 4? Why? I tried a precision of 3 locally and it seemed to be fine as well 🤔

**Comment by service-paradis** [comment]
Thanks for the feedback :)
I tried a few times with a precision of 3 and it something went wrong every time. Width became 0.001 too large or the logo was offset by 0.001.
I will give it another shot, so you can wait before approving it!

**Review by ericcornelissen — APPROVED** [review]
Looking good now, if you can resolve the merge conflicts this can be merged 👍

**Comment by service-paradis** [comment]
@ericcornelissen Done :)

**Comment by ericcornelissen** [comment]
> Done :)

Thanks. And thanks once agian for the improvement! 🎊

**Pull request merged**
