### PR TITLE
Update TypeScript

### PR DESCRIPTION
**Pull request by adamalston**
## Update TypeScript

typescript

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I have updated the TypeScript `hex` and `source` to reflect brand changes that have taken affect. Those changes are highlighted in the [TypeScript Website Roadmap](https://github.com/microsoft/TypeScript-Website/issues/94). 

The [old source](https://github.com/remojansen/logo.ts) pointed to a GitHub repository with an unofficial logo. The [new source](https://www.staging-typescript.org/branding/) is the official TypeScript brand website. On this website, the official logo and colors are displayed.

### CODE REVIEW

**Comment by runxel** [comment]
Thanks for this PR, @adamalston!
However it seems they indeed _also_ changed logo. Not by much, but it's still outdated. (Easily identified by the "S")

Would you also take care of updating the svg? :)

**Comment by adamalston** [comment]
Done @runxel
Do you have a link to the site that will generate a preview of the icon? I cant seem to locate it.

**Comment by runxel** [comment]
Hey @adamalston, thank you so much!
Looking good, but I have one request:
It seems you based your version on the "512" variant of TS. Given that we assume our users use the logos at very small sizes (after all we save the icons on a 24×24 square) I'd rather expect to have the icon based on the "128" version.
Those three version of logo sizes differ quite heavily (which I didn't figured out earlier)!
Before you do unnecessary work, I will ring for another @simple-icons/maintainers.

**Comment by adamalston** [comment]
Updated logo to 128x with new preview above @runxel.

**Review by runxel — CHANGES_REQUESTED** [review]
Thanks @adamalston!
But what happened to the `S`?
The OG is smooth and round, but yours is all wrinkled up...
Maybe check that again :)

**Comment by fbernhart** [comment]
Just to no forget about this PR:

Are you still working on this one @adamalston?

**Comment by adamalston** [comment]
If someone else wants to take it on and submit an update, feel free! 

I haven't had the time to properly take a look at it. @runxel

**Comment by fbernhart** [comment]
Closing this as I've opened a new PR (#4370) to update the icon.

**Pull request closed without merging**
