### PR TITLE
Add PostCSS icon (#2758)

### LINKED ISSUE #2758: PostCSS
**Name:** PostCSS
**Website:**: https://postcss.org/
**Official resources for icon and color:** https://postcss.org/_/web_modules/Hero/postcss.svg

### PR DESCRIPTION
**Pull request by phatbhoy67**
postcss

**Issue:** **Close #2758**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO ~or SVGOMG~
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Source is [official svg](https://postcss.org/_/web_modules/Hero/postcss.svg) found in the front page of the [PostCSS website](https://postcss.org/).

Hex value `#DD3A0A` is from the svg.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
This is coming in a `24.001` wide, @phatbhoy67, and it's also missing some of the detail from the 3rd path in the original (the white bits in the `12x` comparison below).

PostCSS

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble, think I have fixed both issues now.

**Comment by PeterShaggyNoble** [comment]
I think you might need to up the precision on it as well, @phatbhoy67 - I'm seeing some small differences in some of the finer detail. For example, from the bottom of the triangle's left edge (original in black):

image

There's also a very thin line running through the bottom right quarter, which is also present in the original, that we might want to fix:

image

**Comment by phatbhoy67** [comment]
Line removed @PeterShaggyNoble and precision 4.
postcss (1)

**Comment by PeterShaggyNoble** [comment]
SVG looks spot on to me now, @phatbhoy67 - nice work :+1:

Although, when I open it, it's not on the canvas. Could be Inkscape playing silly-buggers on me but I'll let one of the other @simple-icons/maintainers throw an eye over it just in case.

**Comment by PeterShaggyNoble** [comment]
Restarted Inkscape and all is fine now so gonna go ahead and merge this in.

**Pull request merged**
