### PR TITLE
Apache ECharts

### LINKED ISSUE #2444: Apache Echarts
**Name:** Apache Echarts
**Website:** https://github.com/apache/incubator-echarts
**Official resources for icon and color:** There is sadly no vector image available :(

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
Closes #2444

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Manually vectorized since no single vector version was found. :(

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @runxel your manual vector of the logo looks great 👍 

Why did you choose the colour `#A2344A`?

I can find a similar colour `#a9334c` on their website.

**Comment by runxel** [comment]
Mh 🤔 
They have different versions, as it seems.
The logo in the Github repo has even another color `#aa314d`. 😅 
Any favorites?

**Comment by PeterShaggyNoble** [comment]
I'd go with the one they use on their site.

**Comment by runxel** [comment]
Okay great, updated the color!

**Comment by PeterShaggyNoble** [comment]
Looks good to go to me now, @runxel :+1:

**Pull request merged**
