### PR TITLE
JFrog icon

### PR DESCRIPTION
**Pull request by onimur**
jfrog

**Issue:** ref: #3254
**Alexa rank:** [~38k](https://www.alexa.com/siteinfo/jfrog.com)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I get the logo [here](https://media.jfrog.com/wp-content/uploads/2017/12/20133032/Jfrog-Logo.svg) and the hex value I got from this logo too.

### CODE REVIEW

**Comment by onimur** [comment]
Sorry for errors in CI

**Comment by PeterShaggyNoble** [comment]
Don't apologise! As I said to someone the other day; A failed build is nothing more than an opportunity to learn 😉

**Comment by onimur** [comment]
Done. thank you for your guidance, @PeterShaggyNoble

**Comment by ericcornelissen** [comment]
Thanks a bunch for the contribution @onimur, it's much appreciated :tada:

**Comment by PeterShaggyNoble** [comment]
For anyone coming across this in the future, wondering why we didn't go with the "splash", without the wordmark: the brand guidelines linked above explicitly state:
> **Do not:**
> Use the logo without the letters ‘JFrog’

**Pull request merged**
