### PR TITLE
Updated Google Sheets

### PR DESCRIPTION
**Pull request by adamrusted**
googlesheets

**Issue:** Contributes to #4205
**Alexa rank:** N/A (Google Subdomain)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Updated source to Google Press site.
Used [Wikipedia SVG](https://upload.wikimedia.org/wikipedia/commons/a/ae/Google_Sheets_2020_Logo.svg) as matches official PNG - also updated hex to main icon colour.
Gap of 0.5px where the 'page flip' effect is.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
The version on [Logopedia](https://logos.fandom.com/wiki/Google_Drive), where the version on Wikipedia was sourced from has since been updated. An official SVG can also be found in the top right of [this sprite](https://ssl.gstatic.com/docs/common/h_sprite53_grey_medium.svg).

**Comment by adamrusted** [comment]
@PeterShaggyNoble give that a go - should be sorted.

**Comment by PeterShaggyNoble** [comment]
Just so I'm comparing like with like, which source are you using now, @adamrusted?

**Comment by adamrusted** [comment]
Using the top right of the spritesheet you mentioned 👌

**Comment by PeterShaggyNoble** [comment]
SVG looks perfect, so 👍🏻 Just need to revert the source to sheets.google.com, which is where I found that sprite, and update the colour to the `#34a853` used in it and this should be good to go.

**Comment by adamrusted** [comment]
Should be sorted @PeterShaggyNoble 🤞🏻

**Comment by PeterShaggyNoble** [comment]
Nice work, @adamrusted :+1:

**Pull request merged**
