### PR TITLE
Added Allocine icon

### PR DESCRIPTION
**Pull request by hylickipiotr**
**Issue:** #1392 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Color was picked from official Allocine logo.

### CODE REVIEW

**Comment by davidklebanoff** [comment]
Can you elaborate on where the color came from? I'm getting a different color for the header of their website. Not to say that's correct, but I'm trying to identify which is "official".

**Comment by hylickipiotr** [comment]
@davidklebanoff 
I've manually piced the color from the `.ico`, which was in issue #1392.
> Official resources for icon and color: http://www.allocine.fr/favicon.ico

If you don't accept this color, I will change from `#FFCD00` to color of the website header `#FECC00`

**Comment by ericcornelissen** [comment]
> 
> 
> @davidklebanoff
> I've manually piced the color from the `.ico`, which was in issue #1392.
> 
> > Official resources for icon and color: http://www.allocine.fr/favicon.ico
> 
> If you don't accept this color, I will change from `#FFCD00` to color of the website header `#FECC00`.

Since it is very close and `.ico` files may distort the colour (afaik) I think it would be better to go with the color of the website header 🤔

**Comment by hylickipiotr** [comment]
@ericcornelissen I changed the icon color to color of the website header `#FECC00`. 
I think, everything is okay 😃

**Comment by ericcornelissen** [comment]
Hmm, @hylickipiotr I just noticed the title should actually be "AlloCinè" rather than "AlloCine" to be consistent with the official name (based on [the website](http://www.allocine.fr/)). Could you update as well?

**Comment by hylickipiotr** [comment]
@ericcornelissen Title was updated, but the Travis has problem with special character in the title. I think the change is not good for this project 🤔. What do you think?

**Comment by ericcornelissen** [comment]
I was actually expecting that 😄

Although a bit annoying, I think it is better to stick with the official name. All we have to do to fix the build is update [this script](https://github.com/simple-icons/simple-icons/blob/develop/scripts/utils.js). I will try to do that and test it as soon as possible, in the meanwhile you don't have to worry about this PR 😉

**Comment by ericcornelissen** [comment]
Any reason you closed this @hylickipiotr? I did kinda forgot about the script, so sorry for that. Other than that the PR was good.

**Comment by hylickipiotr** [comment]
I had accidentally deleted my branches. I restored the branches and the reopened the PR. Sorry for this, and I think everything is okey.

**Comment by ericcornelissen** [comment]
Thanks for working on this one @hylickipiotr, glad it is finally merged 🎉 Also thanks @davidklebanoff for helping out updating the build process.

**Pull request merged**
