### PR TITLE
Add Internet Archive (#1967)

### LINKED ISSUE #1967: Internet Archive (digital library)
A digital library where it hosts free and open access content from various fields. 

**Name:** Internet Archive 
**Website:** https://archive.org/
**Official resources for icon and color:**
- https://openlibrary.org/static/images/ia-logo.svg
- A glyph of the icon from their [icon set](https://archive.org/includes/fonts/Iconochive-Regular.woff?-ccsheb) that is used from the header and the image in the hero banner. 
- Suggested brand color is `#000000`. 
  

Alexa ranking is at [~170](https://www.alexa.com/siteinfo/archive.org). 
No questions there.

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
Closes  #1967

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
See Issue.

### CODE REVIEW

**Comment by foo-dogsquared** [comment]
The resulting SVG looks pretty off - specifically on the columns of the logo - as seen in the attached image. 



For context, it's just two vectors (yours and the vector from the suggested source) with different colors (pink and green, respectively) overlaid on top on each other. 

IDK how it became different so I advice to double-check if you are indeed using the source to create the SVG.

**Comment by runxel** [comment]
> The resulting SVG looks pretty off - specifically on the columns of the logo - as seen in the attached image.
> IDK how it became different so I advice to double-check if you are indeed using the source to create the SVG.

Huh, that is indeed really odd. I just took it from the source linked in the issue and did not modify it at all. I would blame it on SVGOMG for the moment – I have no other explanation.
Thanks for noticing, I will have a look :)

**Comment by runxel** [comment]
So it turns out I ran into an Illustrator bug/edge case.
I had to redraw the columns in the logo with less points (no problem here, the original had already way to many), otherwise the SVG output would be dented.

**Comment by foo-dogsquared** [comment]
Nicely done, @runxel ! 
The improvements looking good to me. 

Many thanks for your contributions as well! :)

**Pull request merged**
