### PR TITLE
Add Dogecoin

### LINKED ISSUE #2993: Icon for Dogecoin
**Name:** Dogecoin
**Website:** https://dogecoin.com/
**Official resources for icon and color:**

http://christinemix.com/
http://christinemix.com/images/dogecoin-silent.jpg
(official logos, but `.jpg`)

<https://www.reddit.com/r/dogecoin/comments/7niv76/>
http://svgshare.com/i/4k0.svg
(`.svg` by community)

<https://cryptologos.cc/dogecoin>
https://cryptologos.cc/logos/dogecoin-doge-logo.svg
(coin `.svg` by community)

https://icons8.com/icons/set/doge
(doge `.svg` by Icons8)

### PR DESCRIPTION
**Pull request by adamrusted**
dogecoin

**Issue:** Fixes #2993
**Alexa rank:** [62,821](https://www.alexa.com/siteinfo/dogecoin.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG found at [cryptologos.cc](https://cryptologos.cc/dogecoin), hex pulled from SVG.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Is there a connection between Crypto Logos & Dogecoin, @adamrusted? Can we consider it an official source?

**Comment by adamrusted** [comment]
> Is there a connection between Crypto Logos & Dogecoin

By the looks of things, no. I'll have a look through the https://github.com/coinwink/cryptocurrency-logos repo and see if there are any obvious sources there.

**Comment by giekaton** [comment]
Maybe the official source can be considered Dogecoin's Twitter account: https://twitter.com/dogecoin

The simple D letter logo is also quite official, as it's being used on CoinMarketCap: https://coinmarketcap.com/currencies/dogecoin/

**Comment by adamrusted** [comment]
Thanks for your input @giekaton!

@PeterShaggyNoble I've also found the `D in circle` icon used a [Coinbase](https://www.coinbase.com/price/dogecoin), so given it seems a fair few crypto sites are using that as their icon of choice - I think we're ok to accept [cryptologos.cc](http://cryptologos.cc) as source on this one. Might it be worth us comparing some of the other cryptocurrencies we have icons for against the SVGs on cryptologos to validate that their SVGs match up to official sources?

**Comment by adamrusted** [comment]
Labelling as `in discussion`, as I think we need input from other @simple-icons/maintainers regarding this one - and whether we can consider [cryptologos.cc](http://cryptologos.cc/) an official source.

**Comment by PeterShaggyNoble** [comment]
I think, in this case, given the _complete_ absence of an official version of this one, even a raster one, that we make an exception on the source given that they, like us, [seem to be respectful of branding](https://cryptologos.cc/about). If we ever do find an official source then we can update if needs be.

I think, then, we need to have a broader discussion on the possibility of allowing more sources and which ones to allow. We did have an initial discussion on it internally some months back but nothing was ever formalised.

**Comment by PeterShaggyNoble** [comment]
Given no further objections to the alternative source, the SVG looks spot on to me so I'm going to merge this in. Nice work, @adamrusted 👍🏻

Note for others: We are not setting a precedent here of using Crypto Logos as an alternative source; we'll need to have a broader conversation on whether we want to allow that or not. But, in the meantime, as we did here, we will assess each icon sourced from there on a case-by-case basis.

**Pull request merged**
