### PR TITLE
Add Vue.js License

### PR DESCRIPTION
**Pull request by adamrusted**
Added License Info to Vue.js icon entry - as per their README.md at source.

### CODE REVIEW

**Comment by fbernhart** [comment]
I think it would be better to use the URL of the specific commit here, Could you update that?

And wouldn't https://github.com/vuejs/art/blob/a1c78b74569b70a25300925b4eacfefcc143b8f6/README.md as well fit for the `guidelines` attribute?

**Comment by adamrusted** [comment]
> I think it would be better to use the URL of the specific commit here, Could you update that?
> 
> And wouldn't https://github.com/vuejs/art/blob/a1c78b74569b70a25300925b4eacfefcc143b8f6/README.md as well fit for the `guidelines` attribute?

Sorted, thanks @fbernhart!

**Comment by PeterShaggyNoble** [comment]
As discussed elsewhere, I think we should use the default branch rather than the commit URL so that we're always linking to the most up-to-date version and, if the file is ever removed, we're not linking to outdated information. Would you mind submitting a new PR to update the license URL to https://github.com/vuejs/art/blob/master/README.md again? Also, should the `type` be "custom"? 🤔

**Comment by fbernhart** [comment]
@PeterShaggyNoble I haven't thought about that. Thanks, I'm agreeing 👍🏼

**Pull request merged**
