### PR TITLE
Add RSpec icon

### LINKED ISSUE #7991: RSpec
### Brand Name

RSpec

### Website

https://rspec.info/

### Popularity Metric

https://www.similarweb.com/website/rspec.info/#overview

### Official Resources for Icon and Color

https://rspec.info/images/logo.png

### Additional Comments

Used for testing Ruby Rails applications. More popular than minitest

### Contributing

Yes

### PR DESCRIPTION
**Pull request by cheehwatang**
rspec

**Issue:** closes #7991 

**Similarweb rank:** [1,786,018](https://www.similarweb.com/website/rspec.info/#overview)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- as no brand guideline is provided, the center red ruby color, with the dominant color #EF4561 is picked as the primary brand color
- the multicolor svg logo from [https://github.com/rspec/rspec.github.io/blob/source/logo.svg](https://github.com/rspec/rspec.github.io/blob/source/logo.svg) is converted to a path using Inkscape, and optimized using SVGOMG.

### CODE REVIEW

**Comment by LitoMore** [comment]
Hi @JonRowe, could you help to review this? Do you think this looks good for your team?

This icon is manually vectorized, so we would appreciate your approval before we merge.

**Comment by LitoMore** [comment]
It would be better to get vector source files in SVG or other formats from their official team.

**Comment by cheehwatang** [comment]
I will email the RSpec team to check if they can provide the official logo in SVG format.
Thanks.

**Comment by LitoMore** [comment]
@cheehwatang It's OK. Let me help you out.

**Comment by cheehwatang** [comment]
> @cheehwatang It's OK. Let me help you out.

Thank you @LitoMore, I was puzzled by the regex used.🙃

**Comment by LitoMore** [comment]
The source image has lots of unused "shining" shapes. I just removed them and reprocessed the image.

2023-05-29 at 02 03 13@2x

Here is its outline preview:

2023-05-29 at 02 05 10@2x

**Review by LitoMore — APPROVED** [review]

**Comment by LitoMore** [comment]
@simple-icons/icon-review get help.

**Comment by cheehwatang** [comment]
Thanks @LitoMore, I used union to join all the shapes into a single path.

**Comment by JonRowe** [comment]
:wave: We're fine for you to include our logo in a project distributing icons but we ask you keep it as is in terms of colours and shapes. The facets on the Ruby are part of the original logo as are the colours. Cheers.

**Comment by JonRowe** [comment]
@LitoMore then please don't use our logo, we ask you produce it as is or not at all.

**Comment by LitoMore** [comment]
Closing due to https://github.com/simple-icons/simple-icons/pull/8685#issuecomment-1569819885.

**Comment by nirname** [comment]
That's a pity this icon had not been added, because this framework seems to be a separate thing to master, thus it would be very useful to use such an icon to represent a skill

**Pull request closed without merging**
