### PR TITLE
Add Daimler icon

### LINKED ISSUE #2852: Daimler AG
**Name:** Daimler
**Website:** [Daimler AG](https://daimler.com)
**Alexa Rank:** [~11.6k](https://www.alexa.com/siteinfo/daimler.com)
**Official resources for icon and color:** [JPG/PNG/WMF](https://designnavigator.daimler.com/Daimler_Corporate_Logotype_Black_Office) [Design Guide](https://designnavigator.daimler.com/Daimler_Corporate_Logotype?lang=en#color-background)
**Color**: `#000000`

### PR DESCRIPTION
**Pull request by LuckyF**
daimler

**Issue:** Closes #2852

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Unfortunately I have messed up my git repo and had to create a new pull request.
I'll close the old one (#2875).

Requested changes:
  - [x] Removed Loom in JSON file
  - [x] Center icon vertically
  - [x] Increased path precision
  - [x] Using different EPS
  - [x] Color #E6E6E6
  - [x] Removed query parameter from URL

The changes in _line 1944-1946_ of _simple_icons.json_ are just for allignment.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @LuckyF.

To help us compare like with like, which EPS did you use for this PR? I'm seeing some differences in the shapes of the letters when comparing with [the same EPS](https://designnavigator.daimler.com/Daimler_Corporate_Logotype_Black_DTP) I used in #2875; there's a _lot_ more rounding in the one you used. Note, also, that you path is now coming in at `23.995` wide - the joys of optimisation!

**Comment by LuckyF** [comment]
You're welcome.
I'll used the [EPS ](https://designnavigator.daimler.com/Daimler_Corporate_Logotype_Black_DTP) you're mentioned.

You're right. There is much less rounding on the original (grey).
Could this be related with the optimizing process?
I'll have another try this evening 😃.

**Comment by PeterShaggyNoble** [comment]
> Could this be related with the optimizing process?

While optimising can sometimes have _some_ effect on rounding, it's usually _very_ slight - I've never seen a difference this notable.

Thanks for your patience and continued efforts on these :+1:

**Comment by PeterShaggyNoble** [comment]
Closing this out as abandoned due to inactivity. I'll put a new PR together for it shortly.

**Pull request closed without merging**
