### PR TITLE
Add Bosch (#2648)

### LINKED ISSUE #2648: Bosch
**Name:** Bosch
**Website:** https://www.bosch.de/
**Official resources for icon and color:** SVG is in header

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
closes #2648

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG with color `#EA0016` was taken from website header.

bosch

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @runxel thanks for your work on this one 👍 

Any reason you didn't include the outer circle part of the logo? I expected it to match the favicon 👇 

favicon

**Comment by runxel** [comment]
> Any reason you didn't include the outer circle part of the logo?

Noo, hahaha, I don't know at which point this guy escaped. 🤣
Total fail! Will update soon.

**Comment by PeterShaggyNoble** [comment]
I think you might need to up the precision on this one, @runxel, I'm seeing some minor differences in a couple of places on the curves, particularly the innermost ones (original in grey).

image

**Comment by runxel** [comment]
Updated the icon :)

**Pull request merged**
