### PR TITLE
Add Pi-hole

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
From previously abandonded #1339

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo comes from their github. Color `#FF0000` is the lighter red from the logo.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I'd suggest using the repo or website itself as the source URL, should they ever (re)move that SVG file.

**Comment by runxel** [comment]
Updated the source :)

**Comment by phatbhoy67** [comment]
[Alexa Rank: 42,015](https://www.alexa.com/siteinfo/pi-hole.net)

[official .svg](https://github.com/pi-hole/web/blob/master/src/img/logo.svg)

[Brand Guidelines](https://pi-hole.net/trademark-rules-and-brand-guidelines/)

Hey @runxel the .svg is great, thanks for your work on this one. 👍 

Hex value chosen is red (`#ff0000`), which is the colour you would get if you picked it from any of the images on their website (including the one on the brand guide page 👇 😕)
logo

or indeed the .svg, however the brand guide states that "red" is actually supposed to be `#F60D1A` not `#ff0000`🤔 . 

Even though the image next to where this is stated appears to be `#f6241a` red 👀 

I think the brand guide has to win this one even though the visual difference is minimal and there is inconsistency in its application.

Can you update the hex value and I will merge this one in 👍

**Comment by runxel** [comment]
Haha, good catch! Thanks! 👍

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @runxel 👍

**Pull request merged**
