### PR TITLE
Update Flask icon

### PR DESCRIPTION
**Pull request by robertgodfrey**
Icon Preview

**Issue:** No open issue for this update

**Popularity:** 63k stars on GitHub
  
### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Flask recently changed their logo. The new logo can be seen on the official Flask [website](https://flask.palletsprojects.com/) and in the [GitHub repo](https://github.com/pallets/flask/blob/d0bf462866289ad8bfe29b6e4e1e0f531003ab34/docs/_static/shortcut-icon.png).  

I manually vectorized the new logo in Adobe Illustrator. The hex value was chosen based on the color of the shortcut icon in the GitHub repo (previous link).

### CODE REVIEW

**Comment by LitoMore** [comment]
It would be better to get vector source files in SVG or other formats from their official team.

**Comment by robertgodfrey** [comment]
Agreed, will look a little harder for the official version.

**Comment by adamrusted** [comment]
@robertgodfrey - any joy finding an SVG version of the icon? Any contacts on the Flask team we could ask?

**Comment by robertgodfrey** [comment]
No luck, I tried asking a few times on their Discord but never received a response. Not sure where else to look/ask

**Review by adamrusted — APPROVED** [review]
There are some [slight differences](https://github.com/simple-icons/simple-icons/assets/1830867/30f68758-223d-4ab3-92d3-4ff65d195344) between this and the source SVG, but I'm fine with that given it's a manual vectorization. Before we accept, I'll ask another @simple-icons/icon-review member to have a look over it, just to be sure we're in agreement!

Thanks for your work on this @robertgodfrey!

**Comment by LitoMore** [comment]
My previous solution is to submit the vectorized image to the source project to replace their existing binary image. See https://github.com/simple-icons/simple-icons/pull/7702#issuecomment-1228473858.

For Flask, since its source image is used for favicon, we should care about compatibility. See https://caniuse.com/link-icon-svg.

In short, we can always provide our vectorized image as a proposal in future similar cases.

In this case, the vectorized Flask icon looks good to me.

**Review by LitoMore — APPROVED** [review]

**Comment by adamrusted** [comment]
@robertgodfrey - would you want to propose the SVG you've created to their repo, so another alternative for them? That way, if that gets merged in - we've got an official source. Feel free to use @LitoMore's message to .ENV as an example! I won't merged this until we hear one way or the other from Flask team - as that may change our source file.

**Comment by adamrusted** [comment]
Any update on this @robertgodfrey?

**Comment by robertgodfrey** [comment]
No, sorry. We can just close this and wait for the Flask team to provide an official image.

**Pull request closed without merging**
