### PR TITLE
Added Nuget icon

### PR DESCRIPTION
**Pull request by gavazquez**

### CODE REVIEW

**Comment by gavazquez** [comment]
Cound't fix the `viewBox` attribute, I saw that all your icons have a value of `viewBox="0 0 24 24"` but when I use it the image is way too big so I left it as `viewBox="0 0 550 550"`

**Comment by birjolaxew** [comment]
Thanks for the contribution! There are a couple things that need fixing as mentioned in [our contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#4-annotate-the-icon):

1. `role="img"` is missing on the `<svg>` (but thanks for including `aria-labelledby`!)
2. The `<title>` attribute that `aria-labelledby` refers to is missing.
3. As you mentioned, the `viewBox` is too large.
4. The SVG has some empty space to the right/below the icon - the icon should fit the viewBox as much as possible (and be centered on the axis where it doesn't fully fill the SVG)

Since fixing the cropping and viewBox is a bit of a task and requires installing Inkscape or similar, I've gone ahead and resized and centered it so you don't have to:

<p align="center"></p>

```svg
<svg xmlns="http://www.w3.org/2000/svg" aria-labelledby="simpleicons-nuget-icon" viewBox="0 0 24 24"><path d="M17.67 21.633a3.995 3.995 0 1 1 0-7.99 3.995 3.995 0 0 1 0 7.99m-7.969-9.157a2.497 2.497 0 1 1 0-4.994 2.497 2.497 0 0 1 0 4.994m8.145-7.795h-6.667a6.156 6.156 0 0 0-6.154 6.155v6.667a6.154 6.154 0 0 0 6.154 6.154h6.667A6.154 6.154 0 0 0 24 17.503v-6.667a6.155 6.155 0 0 0-6.154-6.155M3.995 2.339a1.998 1.998 0 1 1-3.996 0 1.998 1.998 0 0 1 3.996 0"/></svg>
```

If you could add the missing stuff (namely 1. and 2.) to that then we can get this merged in :smile:

**Comment by gavazquez** [comment]
Fixed, hopefully now is ok :)

**Comment by birjolaxew** [comment]
:+1: Great! Thanks for the contribution! It is much appreciated.

**Pull request merged**
