### PR TITLE
Add Pterodactyl icon 

### LINKED ISSUE #8833: Pterodactyl
### Brand Name

pterodactyl

### Website

https://pterodactyl.io/

### Popularity Metric

Global rank is 293,732. https://www.similarweb.com/website/pterodactyl.io/

This is a very popular self hosted game server management platform, probably the best currently available.
Used by commercal clients as well as individual users.

It is open source and the main repository has +5k stars
https://github.com/pterodactyl/panel

### Official Resources for Icon and Color

The logo on the website is extremely detailed and colored, and would not be a good fit for `simple-icons` style imo. 
The favicon used for the panel website is more approiate, and could be derived from this image.
https://github.com/pterodactyl/panel/blob/eaf46429f2a001469fb5f18f7891ce8e5be7f049/public/favicons/favicon-96x96.png

The primary color is #10529f

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by blakmagjick**
pterodactyl

**Issue:** closes #8833

**Similarweb rank:** 293,732
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Hex value picked from .png icon linked in original ticket using Digital Color Meter, and then converted RBG to hex.
- Vectorized the .png file for free online using Adobe.

### CODE REVIEW

**Comment by jack-mil** [comment]
This looks great! thank you for working on this faster than I could get to it!

**Comment by LitoMore** [comment]
Their project is active on GitHub. Can you reach out to their team to get approval? You could mention their maintainer in this PR like I did before: 

- https://github.com/simple-icons/simple-icons/pull/8856#issuecomment-1602964135
- https://github.com/simple-icons/simple-icons/pull/8311#issuecomment-1597058619
- https://github.com/simple-icons/simple-icons/pull/8388#issuecomment-1605590770

Another solution is to propose you the icon you made for their project. Here is my example:

- https://github.com/simple-icons/simple-icons/pull/8688#issuecomment-1627373919

**Comment by blakmagjick** [comment]
Hi @matthewpi, may I ask for your approval on this PR? Thanks 😸

**Comment by matthewpi** [comment]
> Hi @matthewpi, may I ask for your approval on this PR? Thanks smile_cat

For sure.

I agree that the other icons have too much detail to be represented in such a small size, the icon provided here seems to work well and is similar enough to the style of the existing favicon assets.

You have my approval and consent to merge this PR and use the icon.

**Review by matthewpi — APPROVED** [review]

**Review by LitoMore — APPROVED** [review]

**Pull request merged**
