### PR TITLE
Add GNOME

### LINKED ISSUE #2160: GNOME
**Name:** GNOME
**Website:** https://www.gnome.org/
**Alexa Rank:** [~19k](https://www.alexa.com/siteinfo/gnome.org)
**Colour:** `#4a86cf`
**Official resources for icon and color:** https://wiki.gnome.org/Engagement/BrandGuidelines - logo found in [trademark guidelines](https://www.gnome.org/logo-and-trademarks/) and colour found in [style guide](https://raw.githubusercontent.com/gnome-design-team/gnome-marketing/master/brand/style-guide.png).

Two possibilities here and, while I prefer the first, I fear we may have to go with the second.

[GNOMEGNOME](https://github.com/simple-icons/simple-icons/files/3978331/gnome.zip)

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
GNOME

**Issue:** Closes #2160

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Rejected alternative:
GNOME

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Actually, @runxel, having thought some more on it, I think a case can be made for *either* colour. We have precedent for using a brand's colour, despite it not being used in their logo or icons (Slack immediately springs to mind, for example). The difference here, of course, is that, as you pointed out, GNOME explicitly state that their logo should only appear in black or white.

What do the other @simple-icons/maintainers think?

**Comment by birjolaxew** [comment]
We generally consider the color in our data to be the brand guideline; this doesn't necessarily equal the logo color, so I'm in favor of the blue currently in this PR.

That being said, I think that including the "GNOME" letters would be right here, simply because they seem super consistent with doing so whenever they use the logo to refer to their brand. Even their favicon is logo + wordmark (although confusingly not the vertical version ¯\\\_(ツ)_/¯)

**Comment by PeterShaggyNoble** [comment]
Updated to the alternative version of the icon.

**Comment by birjolaxew** [comment]
:+1: Looks good! Thanks for updating @PeterShaggyNoble.

**Pull request merged**
