### PR TITLE
Update Firefox

### PR DESCRIPTION
**Pull request by mondeja**
image

**Issue:** #4590
**Alexa rank:** N/A

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Rebuilt from scratch fixing some inconsistencies and optimizing the path.
- Added `guidelines` entry to metadata.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Just so we can compare like with like, @mondeja, which file did you base your version on?

**Comment by mondeja** [comment]
`Standard/Horizontal/Black/SVG/Firefox Horizontal Black.svg`

**Comment by fbernhart** [comment]
LGTM 👍🏼  Thanks @mondeja

**Comment by goyalyashpal** [comment]
* wow, i didn't know they had separate "Firefox product company" and "Firefox browser". 
* but it makes sense to have it.  awesome.

links:
* https://simpleicons.org/?q=firefox
* https://mozilla.design/firefox/#logos-usage

**Pull request merged**
