### PR TITLE
Add Jasmine

### LINKED ISSUE #2948: Jasmine
**Name:** Jasmine
**Website:** https://jasmine.github.io
**Official resources for icon and color:** Vector logo from [repository](https://github.com/jasmine/jasmine/blob/master/images/jasmine-horizontal.svg) and colour `#8A4182` from [website](https://jasmine.github.io/) stylesheet.
**Alexa Rank:** [~241k](https://www.alexa.com/siteinfo/jasmine.github.io)

### PR DESCRIPTION
**Pull request by mondeja**
jasmine-preview

**Issue:** Closes #2948

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Vector logo from [repository](https://github.com/jasmine/jasmine/blob/master/images/jasmine-horizontal.svg) and colour `#8A4182` from [website](https://jasmine.github.io/) stylesheet.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one on, @mondeja.

However, you've somehow managed to vertically flip your version (in red below). Note, as well, that the icon in the source isn't _quite_ a perfect circle; it's a shade wider than it is high. The only other, minor thing is to include the commit has in the source URL: https://github.com/jasmine/jasmine/blob/8991b1bba39b5b7e89fc5eeb07ae271a684cb1a4/images/jasmine-horizontal.svg

**Comment by mondeja** [comment]
Thanks @PeterShaggyNoble. It's fixed now:

jasmine-preview

However, keep in mind that [SVGO configuration of 3 decimal digits](https://github.com/simple-icons/simple-icons/blob/develop/.svgo.yml#L6) can force the path to be a perfect circle. I've tested with [SVGOMG](https://jakearchibald.github.io/svgomg/) and this problem appears, so I've setted the precision to 5 decimals optimizing the vector this time.

**Comment by PeterShaggyNoble** [comment]
SVG looks perfect now, @mondeja, nice work :+1:

Although, personally, I don't think maintaining a difference of `0.002` in the width is worth the sacrifice and increased file size of increasing the precision to 5. If you'll allow me, I'm going to see if I can improve on the precision at all while, hopefully, maintaining the dimensions.

**Comment by PeterShaggyNoble** [comment]
Actually, looking at the path in detail, it doesn't looks like we're sacrificing all that much in file size with a precision of 5.

However, using [this SVGO plugin](https://github.com/konsumer/inkscape-svgo) for Inkscape I managed to get the precision down to 3 while maintaining the dimensions, _but_ now the path is `0.001` off horizontal centre:

```
M11.59 19.648h.772v-3.785h-.771zM4.718 14.62l-.238-.733 3.6-1.17.238.734-3.6 1.17m4.645-5.763L7.137 5.795l.624-.454 2.225 3.063-.624.453m5.315.028l-.624-.453 2.225-3.063.624.453-2.225 3.063m4.591 5.78l-3.6-1.17.238-.733 3.6 1.17-.238.733M12.001 0C5.384 0 0 5.382 0 11.998 0 18.616 5.384 24 12 24s11.998-5.384 11.998-12.002C24 5.382 18.617 0 12.001 0zm0 2.43c5.283 0 9.569 4.283 9.569 9.568 0 5.287-4.286 9.572-9.57 9.572-5.285 0-9.57-4.285-9.57-9.572 0-5.285 4.285-9.569 9.57-9.569m1.553 7.961l.575 1.768.747.243 4.736-1.539-.86-2.646-4.736 1.54-.462.634m.337 2.502l-1.504 1.092v.786l2.927 4.029 2.25-1.635-2.927-4.03-.746-.242m-2.275 1.093l-1.504-1.093-.747.243-2.927 4.029 2.25 1.635 2.928-4.03v-.784m-1.743-1.826l.575-1.768-.462-.636-4.736-1.539-.86 2.646 4.737 1.54.746-.243m1.199-2.222h1.858l.462-.635v-4.98H10.61v4.98l.462.635
```

Any of the other @simple-icons/maintainers want to weigh in here as to what our best option is?

**Comment by runxel** [comment]
We have done some optimizing in the past, mostly in cases where we think the source file itself can't be trusted/doesn't look as intended.
With a circle just being a shade not a circle I personally would always assume that this must be an error. I'd be okay with the circle being perfectly round :D

**Comment by mondeja** [comment]
I've finally used the path that @PeterShaggyNoble shared. Thanks for the plugin, it's very useful.

**Comment by PeterShaggyNoble** [comment]
Sorry, @mondeja, looks like this one fell between the cracks. Upon reflection, I agree with @runxel's comment that:

> With a circle just being a shade not a circle I personally would always assume that this must be an error.

Could you revert back to your precision 3, `24*24` version, please? Sorry for the hassle.

**Comment by mondeja** [comment]
I've removed this branch by mistake, so it's updated on #3152

**Pull request closed without merging**
