### PR TITLE
Add SVG.js icon

### LINKED ISSUE #4934: SVG.js
image

**Brand Name:** SVG.js
**Website:** https://svgjs.com/ and https://github.com/svgdotjs/svg.js
**Similarweb rank:** [2,270,762](https://www.similarweb.com/website/svgjs.dev/#overview)
**Github stars:** [10.4k](https://github.com/svgdotjs/svg.js)

**Official resources for icon and color:**

It is called SVG.js. It is to play with SVGs. I did not find any SVG logo...

- PNG Logos: https://github.com/svgdotjs/svgdotjs.github.io/tree/source-3.0/assets/images
- Color: `#FF0066`

### PR DESCRIPTION
**Pull request by adamrusted**
svgdotjs

**Issue:** closes #4934 - picks up from #6215

**Similarweb rank:** [2,270,762](https://www.similarweb.com/website/svgjs.dev/)

**GitHub stars:** [10.4k](https://github.com/svgdotjs/svg.js

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon and hex pulled from source.

### CODE REVIEW

**Comment by LitoMore** [comment]
Haha, this one should be our milestone. I will review this in a short time!

**Review by dirien — APPROVED** [review]
Hey @adamrusted,

image

The left top and bottom right looks a little bit off but not that much. So for my it's an approve but decide on your own.

**Comment by adamrusted** [comment]
You're absolutely right @dirien - hadn't spotted that! Pushing a version with 4 decimals now...

**Review by dirien — APPROVED** [review]
image

@adamrusted much better! Good to merge!

**Pull request merged**
