### PR TITLE
Add Meilisearch

### LINKED ISSUE #9064: Request: Meilisearch Icon
### Brand Name

Meilisearch

### Website

https://meilisearch.com

### Popularity Metric

- Similarweb Global Ranking: 446,034. https://www.similarweb.com/website/meilisearch.com/
- GitHub Stars: 37.7K. https://github.com/meilisearch/meilisearch

### Official Resources for Icon and Color

- https://github.com/meilisearch/devrel/tree/main/assets/logos

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by konhi**
meilisearch

Close #9064

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
  - Meilisearch is a GitHub project with [over 27k stars](https://github.com/meilisearch/meilisearch)
  - I picked the color from https://www.meilisearch.com/ - it's the most often used color for CTA, although gradient is generally used.
  - I grabbed vector from the website and removed the gradient.

### CODE REVIEW

**Comment by dirien** [comment]
Hi @konhi,

Can you take a look into your submission! I think thats a quick fix to center the icon, than I can review it.

**Comment by konhi** [comment]
@dirien Thank you! Everything fixed. Shame their own logo isn't properly centered 😄

**Comment by dirien** [comment]
Hi @konhi,

I see a difference 

image

Red is the OG from the website

**Review by PratyushJayachandran — APPROVED** [review]
Thank you for contribution @konhi 
Perfect correction @adamrusted
:tada:

**Pull request merged**
