### PR TITLE
Add Simplenote icon

### PR DESCRIPTION
**Pull request by Rcoleman956**
simplenote

**Issue:** #7136
**Similarweb rank:** 6,470

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Hex value: `#3361CC`
- Icon created with this [SVG](https://en.wikipedia.org/wiki/File:Simplenote_logo.svg)

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @Rcoleman956 

I found this svg with their logo in their codebase

`https://github.com/Automattic/simplenote-android/blob/ca4c775cf62dd0f3178e50564d8d4a17d17408ef/metadata/ic_launcher.svg`

what do you think?

**Comment by Rcoleman956** [comment]
Hey, @dirien! 

simplenote


Is this what you were picturing for it?

**Comment by dirien** [comment]
Asking @joaopedromoraez and @sachinraja for feedback

**Comment by sachinraja** [comment]
I think the one currently implemented in this PR is the correct version, with the inner parts filled as that is the one on the website.

**Comment by LitoMore** [comment]
FYI: https://apps.apple.com/app/simplenote/id289429962

**Review by LitoMore — APPROVED** [review]
Looks good.

CleanShot 2022-02-27 at 21 27 58@2x

**Pull request merged**
