### PR TITLE
Add Shadow Pc icon

### PR DESCRIPTION
**Pull request by fralps**
logo-shadow

**Issue:**
**Alexa rank:** [Shadow Pc - 7.5k](https://www.alexa.com/siteinfo/shadow.tech)
  

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

- I took the logo in the header of their website ℹ️
- I used Inkscape to scale 🎨
- I optimized it with SVGO 🗜️
- I made a PR 🚀

### CODE REVIEW

**Comment by adamrusted** [comment]
Hi @fralps - thanks for your contribution! 💪
Just looking at this one now, it appears you had the 'precision' set too high when using SVGO. We aim for 3 decimals - but allow anything up to 5 if absolutely necessary. Could you try optimizing it again, and hopefully getting it to 3 or 4 decimals?

**Comment by fralps** [comment]
Yeah you're right, I'm on it 😉
Sorry for that

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @fralps?

**Comment by fralps** [comment]
Yes, I fixed the decimals issue but I don't manage to center the svg.. 🤔

**Comment by PeterShaggyNoble** [comment]
What software are you using?

**Comment by fralps** [comment]
This one [IcoMoon](https://icomoon.io/)

**Comment by PeterShaggyNoble** [comment]
Sorry, I meant what software you were using to create your Shadow PC icon? e.g., Inkscape or Illustrator or something else?

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @fralps?

**Comment by PeterShaggyNoble** [comment]
In the interests of clearing out some of our backlog, I'm going to close this PR out and will submit a fresh one shortly.

**Pull request closed without merging**
