### PR TITLE
Update Fnac icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** #6437 
**Alexa rank:** 3,058
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
The svg has slight discrepancies with the source, due to the svgo optimization.
I tried with `precision:5` and the match is 100%.

**Comment by dirien** [comment]
@jorgeamadosoria: how to i set the precision in inkscape?

**Comment by jorgeamadosoria** [comment]
> @jorgeamadosoria: how to i set the precision in Inkscape?

what I do is look in the `svgo.config.js` file for the main repository, and set the precision parameter there. If you optimize the SVG from inkscape, it will show a dialog window asking for the precision you want to set (this is available in `Save As... -> Optimized SVG` file type).
I think there is also a command line parameter if you want to execute SVGO outside Inkscape or simple-icons, but I haven't used it.

If you are going to change the precision parameter in `svgo.config.js`, please remember to revert it back to 3 before committing. 

As I understand it precision 3 is the desired value for all the icons, but in the cases in which you can't make it work with that, precision 4 or 5 may be accepted. @service-paradis, can you please confirm or correct this interpretation, please?

**Comment by service-paradis** [comment]
> As I understand it precision 3 is the desired value for all the icons, but in the cases in which you can't make it work with that, precision 4 or 5 may be accepted. @service-paradis, can you please confirm or correct this interpretation, please?

Yes, we really try to keep precision at 3. For some icons, it does not work. In those cases, a precision of 4 can be accepted. If it still does not work, we accept a precision of 5 (it is rarely necessary to increase to 5).

**Comment by jorgeamadosoria** [comment]
> > As I understand it precision 3 is the desired value for all the icons, but in the cases in which you can't make it work with that, precision 4 or 5 may be accepted. @service-paradis, can you please confirm or correct this interpretation, please?
> 
> Yes, we really try to keep precision at 3. For some icons, it does not work. In those cases, a precision of 4 can be accepted. If it still does not work, we accept a precision of 5 (it is rarely necessary to increase to 5).

For some reason I'm running into these cases quite often :(

**Comment by jorgeamadosoria** [comment]
> hi @service-paradis and @jorgeamadosoria,
> 
> changed the percision to 5. Looking for your feedback 😄

I changed it to precision 3 and it worked.
@dirien, plz check on your side. if  you get a match, LGTM

**Pull request merged**
