### PR TITLE
Add QT icon

### LINKED ISSUE #2947: Add Qt Icon
**Name:** Qt
**Website:** [The Qt Company](https://www.qt.io)
**Official resources for icon and color:**
[I think this is good?](https://qt-brandbook.webflow.io/design#logos)

### PR DESCRIPTION
**Pull request by LuckyF**
qt

**Issue:** Closes #2947

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

**Name:** QT
**Website:** [QT.io](https://www.qt.io/)
**Alexa Rank:** [~17.1k](https://www.alexa.com/siteinfo/qt.io)
**Official resources for icon and color:** [Logo](https://qt-brandbook.webflow.io/design#logos)
**Color**: `#41CD52`

The changes in line 1944-1946 of simple_icons.json are just for alignment.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks once again for the PR, @LuckyF.

You seem to be picking up a few of the trickier ones lately 🙈 I'm using the `Print/Qt Logo/qt_logo_green_PANTONE_802.ai` for comparison and seeing some hairline differences around the inside of the letters but, again, that could be down to a difference in sources - which file did you base your SVG on?

Also, two other minor things:
1. Firstly, and purely from the point of view of my own personal preference, I'd drop the `#logos` from the source URL, and,
2. Secondly, and more importantly, the name should be stylised as "Qt", rather than "QT". Although, to avoid any potential future clashes in names, we could use the full name of "The QT Company".

**Comment by ericcornelissen** [comment]
Just chiming in here to say that I agree with both minor comments by @PeterShaggyNoble

**Comment by HatEmU** [comment]
Any progress on this one yet?

**Comment by ericcornelissen** [comment]
@LuckyF are you planning to continue working on this in the near future?

@HatEmU, if @LuckyF cannot continue their contribution, would you be interested in opening a Pull Request for QT?

**Comment by HatEmU** [comment]
@ericcornelissen I would love to contribute, but I have no experience in this field.

**Comment by ericcornelissen** [comment]
@HatEmU you can have a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) for more information, and you are free to use this Pull Request as a starting point.

If you do decide to work on this, let everyone know in this thread :slightly_smiling_face:

**Comment by PeterShaggyNoble** [comment]
@HatEmU, would you still like to give this one a try?

**Comment by PeterShaggyNoble** [comment]
I'll take this one; need something quick & easy to warm my brain up on this morning.

**Pull request closed without merging**
