### PR TITLE
Added a script for turning Simple-Icons into an icon font.

### PR DESCRIPTION
**Pull request by metaa**
# Simple Icons: The _icon font_
This PR adds a script that creates an icon font from all the icons included in `simple-icons`.
This font might then be distributed on its own or just reside in `simple-icons` to be used in it or alongside it (it could even replace the embedded SVGs on the overview page).

I recently worked on improvements to an NPM package [over here](https://github.com/fabiospampinato/icon-font-buildr/pull/1) which allows dropping in a simple configuration that then creates an icon font based on custom ligature settings and such.

Using this allows creating an icon font pretty easily.

The script included iterates through all available icons and then dynamically creates a configuration for the underlying package (`icon-font-buildr`) which then outputs an icon font in `WOFF` and `WOFF2` format (both together are supported by all current browsers, see [[1]](https://caniuse.com/#feat=woff) & [[2]](https://caniuse.com/#feat=woff2)).

There is also a (very minimalistic) test page located under `/font/test.html` that displays the icon font in use.

The following gif presents this test page with manual toggling of the font to see the actual text:

---

## Warnings

* This depends on #1306 being merged. Those two icons messed up the icon font and made the glyphs either invisible or incredibly tiny with a huge line height.
* This also depends on [#3](https://github.com/fabiospampinato/icon-font-buildr/pull/3) in the repository of the `icon-font-buildr` package, as there currently is an issue that prevents this font from being generated due to a race condition effecting the generation's success when there is a lot of icons.

## Dependencies
- [ ] Merge status d896de5 
- [x] [PR status](https://github.com/fabiospampinato/icon-font-buildr/pull/3)

### CODE REVIEW

**Comment by birjolaxew** [comment]
I feel like this would be better placed in a separate repository under the Simple Icons org, similar to [our PDF repo](https://github.com/simple-icons/simple-icons-pdf).

It is definitely something we would be interested in though.

**Comment by metaa** [comment]
I could do that and put it into a separate package if you'd like me to.

**Comment by ericcornelissen** [comment]
> I feel like this would be better placed in a separate repository under the Simple Icons org, similar to [our PDF repo](https://github.com/simple-icons/simple-icons-pdf).
> 
> It is definitely something we would be interested in though.

Completely agree. If you can set this up as a separate repo and package that would be awesome @metaa :100:

**Comment by metaa** [comment]
Sure thing, give me a moment

**Comment by metaa** [comment]
I made a thing [over here](https://github.com/metaa/simple-icons-font). Feel free to clone that into the simple-icons org.

Please read the docs and see if you would be happy with what I put up there.

**Comment by ericcornelissen** [comment]
I closed this Pull Request and invited you to the organization @metaa, that way you can just transfer the repository 😉 

The setup of the repo is fine by me. I would move the "Development" section to the contributing guidelines, and keep the README to just "Usage". I think, like with [simple-icons-pdf](https://github.com/simple-icons/simple-icons-pdf), we want to keep development in that repo to a minimum anyway.

It would be great if we can automatically publish a release of the font package with the regular package though 🤔 That might be doable if when [we get access to Github Actions](https://github.com/simple-icons/simple-icons/issues/982#issuecomment-475364447).

One problem I'm having is that the test page does not show icons, but text instead... Any idea why?

**Comment by metaa** [comment]
> One problem I'm having is that the test page does not show icons, but text instead... Any idea why?

> **NOTE:** this still depends on [d896de5](https://github.com/simple-icons/simple-icons/commit/d896de599d3ac05254f7715bfd2498388aee1a79) being merged to master [...] and will not work without manual adjustments just yet.

If you replace the svgs of those two icons with something else, it will work.

**Comment by metaa** [comment]
There we go, I moved it and adapted stuff 🙂
I leave the publishing of the NPM package and the Travis setup (never used Travis) to you guys.

**Comment by ericcornelissen** [comment]
> If you replace the svgs of those two icons with something else, it will work.

Of course 🤦‍♂️ 


> That's why I wanted to merge it in instead of having it separate 😛

Haha of course, the problem is that at some point a monorepo for things like this because cumbersome (consider [simple-icons-pdf](https://github.com/simple-icons/simple-icons-pdf), now [simple-icons-font](https://github.com/simple-icons/simple-icons-font), soon [vue-simpleicons](https://github.com/sh7dm/vue-simpleicons) and possibly at some point simple-icons-png considering the discussion in  #980?). 


> There we go, I moved it and adapted stuff 🙂
I leave the publishing of the NPM package and the Travis setup (never used Travis) to you guys.

I will try to look into that as soon as possible. Although we have not yet set it up, it should be possible to publish multiple package updates at once from a merge in a single repository.

**Pull request closed without merging**
