### PR TITLE
Add Motorola

### LINKED ISSUE #3413: Motorola
**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by sharmavins23**
**Issue:** Closes #3413 
**Alexa rank:** 13,966

motorola

  

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

The original issue has no information on sources, alexa rank, etc. So I ended up taking straight from the main page. The icon as well as the color is taken from there.

### CODE REVIEW

**Comment by NovaGL** [comment]
Can you please advise why you chose that color? What brand guidelines did you use?

I also feel your source link is incorrect as it doesn't refer to the logo.

Even though its a different company, a potential source could be
https://www.motorolasolutions.com/en_us/brand/advancing-the-lifeline/visual-toolkit.html

**Comment by fbernhart** [comment]
@sharmavins23 Are you still working on this one?

**Comment by adamrusted** [comment]
So I've just looked at [this file here](http://motorola.press/Files/_Marketing/_Motorola_BrandMaterials/Lenovo_MotorolaStyleGuide_FINAL.pdf), specifically page 8. They do seem to be using the larger icon SVG there. Given @sharmavins23 hasn't committed to this PR since August 5th, I'm going to assume they're no longer working on it and submit the icon to this PR.

**Comment by adamrusted** [comment]
motorola

Rebuilt from Lenovo takeover rebrand source, including new hex.

**Comment by fbernhart** [comment]
I was searching a bit for a different source. There is https://www.motorola.de with a SVG in the header, but of pretty bad quality.
And then I've found https://motorola-global-portal-de.custhelp.com, their German support page, with a SVG of good quality in the footer.

In my opinion this might be a better source than extracting a SVG from a PDF file, which was created back in 2017. What do you think @adamrusted? Should we change it or keep it this way?

There would be some slight differences between your PR and the SVG at https://motorola-global-portal-de.custhelp.com:

image

**Comment by adamrusted** [comment]
@fbernhart sorted :)

**Comment by fbernhart** [comment]
Thanks to @adamrusted and @sharmavins23 for your work! 💯

**Pull request merged**
