### PR TITLE
Add AFDIAN icon

### PR DESCRIPTION
**Pull request by Zuoqiu-Yingyi**
afdian

**Popularity metric:**
- **Similarweb rank:** [Global Rank - 23796 (2024-12-10)](https://www.similarweb.com/website/afdian.com/)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Logo and its brand guidelines come from [AFDIAN Brand and Logo Materials丨AFDIAN](https://afdian.com/album/248b4bb2c9b111e9a9bb52540025c377/c3d32ae4b5f311eab4a952540025c377)

### CODE REVIEW

**Review by LitoMore — CHANGES_REQUESTED** [review]
I can see some differences on its eye. Which file are you using as the source? I'm using the `afd logo-白底.svg` as the source reference.

image

**Comment by Zuoqiu-Yingyi** [comment]
> I can see some differences on its eye. Which file are you using as the source? I'm using the `afd logo-白底.svg` as the source reference.
> 
> image

This may be caused by the loss of accuracy when performing coordinate transformations.
Should I take 4 decimal places to solve this?

**Comment by LitoMore** [comment]
@simple-icons/pr-reviewers Waiting for other reviews to check if I did anything wrong.

**Comment by Zuoqiu-Yingyi** [comment]
> Here is the path what I generated with `npx svgo`.
> 
> ```
> M9 14.234a.567.567 0 0 0-.568.568.568.568 0 1 0 1.136 0A.567.567 0 0 0 9 14.234m5.351 1.705a.567.567 0 0 0-.567.569.568.568 0 1 0 1.135 0 .567.567 0 0 0-.568-.569m8.401 1.436c-.19.095-.461.1-.713.013-.17-.06-.352-.116-.534-.172-.339-.104-.904-.276-1.011-.407a.53.53 0 0 0-.748-.105.534.534 0 0 0-.105.748c.06.08.14.146.22.21-.816 1.13-4.398 3.381-9.464 2.272-2.283-.5-3.819-1.413-4.444-2.639-.45-.885-.348-1.798-.133-2.293.62-1.29 5.097-4.261 7.955-5.943a.536.536 0 0 0 .188-.733c-.15-.254-.49-.356-.73-.19-.23.136-1.015.602-2.015 1.237-.338-.227-.923-.508-1.86-.6-1.486-.148-4.92-.805-6.029-1.275C2.535 7.162.731 6.27 1.131 5.267c.092-.234.527-.613 1.47-.974a8.4 8.4 0 0 1 1.995-.492l-.212.103c-.642.312-1.342.662-1.813 1.075-.034-.022-.07-.044-.094-.069a.527.527 0 0 0-.754-.017.534.534 0 0 0-.017.756c.19.2.471.35.83.465l.038.014c1.245.383 3.458.336 6.578.211 1.345-.052 2.615-.102 3.674-.082 3.512.07 6.152 1.47 8.07 4.278 1.178 1.726.753 3.426.079 4.904a1.4 1.4 0 0 1-.231-.222.54.54 0 0 0-.75-.085.536.536 0 0 0-.086.751c.109.137.665.778 1.355.724l.037-.002c.021-.003.042 0 .064-.003.472-.086.768-.063 1.045.11.367.233.547.37.511.486-.021.073-.076.125-.168.177M8.19 11.418l-.315.232a1.6 1.6 0 0 1-.243-.321c.124-.038.33.007.558.089m14.733 4.356a1.86 1.86 0 0 0-.81-.27c.632-1.544 1.034-3.565-.336-5.573-2.096-3.071-5.101-4.667-8.93-4.743-1.09-.022-2.377.029-3.737.083-1.58.063-3.683.145-5.112.026a21 21 0 0 1 .851-.43c1.006-.49 1.797-.872 1.535-1.548-.137-.396-.547-.603-1.22-.618C3.75 2.669.69 3.489.139 4.87c-.31.78-.361 2.283 2.775 3.611 1.29.548 4.934 1.216 6.34 1.355.398.039.702.12.932.205a63 63 0 0 0-.986.664c-.577-.33-1.521-.718-2.226-.237a.94.94 0 0 0-.435.768c-.01.385.224.763.486 1.066-1.038.83-1.877 1.633-2.175 2.253-.332.762-.467 2.008.153 3.224.786 1.544 2.524 2.62 5.166 3.199 3.454.755 6.437.075 8.411-.966 1.099-.579 1.878-1.27 2.257-1.887l.356.113c.169.051.338.103.496.159.522.181 1.1.157 1.545-.068q.012-.005.025-.013c.336-.177.577-.46.683-.803.285-.922-.528-1.432-1.018-1.74
> ```
> 
> This one looks perfect compared with the source file.
> 
> You can apply my path or process according to [this guide](https://github.com/simple-icons/simple-icons/discussions/9351).

I have applied your path.

**Comment by Zuoqiu-Yingyi** [comment]
The latest adjustment uses a strict coordinate transformation (instead of a vector graphics editor) base on `afd logo-白底.svg`.

image

**Review by adamrusted — CHANGES_REQUESTED** [review]
Now seeing a slight difference in the fin on the right-hand side. Thank you for your patience with this process @Zuoqiu-Yingyi 🙏

image

**Review by LitoMore — APPROVED** [review]
@Zuoqiu-Yingyi It looks perfect now! Great work!

**Comment by LitoMore** [comment]
Let's wait for one more review in case I missed something.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @Zuoqiu-Yingyi for your work on this, and patience while we reviewed. 🙏

**Pull request merged**
