### PR TITLE
Add Mailgun icon

### PR DESCRIPTION
**Pull request by sisp**
Mailgun icon preview

**Similarweb rank:** [48,925](https://www.similarweb.com/website/mailgun.com/#overview)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The icon is based on the [official SVG logo on the website](https://www.mailgun.com/) in the navbar. The hex value is `#F06B66` which is the color used in the official logo.

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @sisp,

I see a difference with the source you pointed to (website header)

image

**Comment by sisp** [comment]
Thanks for the thorough review, @dirien! I'm not sure what happened the first time, but you're right about the difference. I've derived the icon again and verified it's similarity with the original icon. Could you please check again?

**Comment by dirien** [comment]
Hi @sisp, will do!

**Review by dirien — APPROVED** [review]
Hi @sisp,

looks very good!
image

**Pull request merged**
