### PR TITLE
Add Icinga

### LINKED ISSUE #5132: Request: Icinga Icon
**Brand Name:** Icinga
**Website:** https://icinga.com/
**Alexa rank:** [262,337](https://www.alexa.com/siteinfo/icinga.com)

**Official resources for icon and color:** https://commons.wikimedia.org/wiki/File:Icinga_logo.svg

### PR DESCRIPTION
**Pull request by rafi0101**
icinga

**Issue:** Resolves #5132 
**Alexa rank:** [262,337](https://www.alexa.com/siteinfo/icinga.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I used [this SVG](https://github.com/Icinga/icingaweb2/blob/293021b2000e9d459387153ca5690f97e0184aaa/public/img/icinga-logo-compact.svg) from IcingaWeb2.

### CODE REVIEW

**Comment by rafi0101** [comment]
Well, I think I will fix the icon size from 23.998 x 24.002 to exactly 24 x 24 :smile:

**Comment by fbernhart** [comment]
@rafi0101 Note: The icon should only be exactly 24x24px if the original icon is a perfect square.

Otherwise (in most cases) the icon has to be scaled so that either the width OR the height is 24px - whichever is bigger.

**Comment by rafi0101** [comment]
@fbernhart Now you can have a look at it. I think the icon is ready.

**Comment by PeterShaggyNoble** [comment]
The dimensions of this still seem to be off when compared to the original, @rafi0101; would you mind having another look? The width should be about `23.216` and the height `24`.

**Comment by PeterShaggyNoble** [comment]
Oh, and for the colour, I'd suggest `#06062c` from their website's stylesheet.

**Comment by rafi0101** [comment]
Yes, I'll have a look at it. 
> Oh, and for the colour, I'd suggest `#06062c` from their website's stylesheet.  

Maybe @PeterShaggyNoble can you provide me your source, because I can't find anything to this topic.

**Comment by PeterShaggyNoble** [comment]
It's the colour used for the overall page background on their website.

**Comment by rafi0101** [comment]
@PeterShaggyNoble now I think this svg is ready. I opened the original svg in inkscape and changed the hight to 24 in locked mode, so the proportions should fit.

**Review by adamrusted — CHANGES_REQUESTED** [review]
SVG matches the source perfectly, though it looks like the stroke lines remain in your PR (see [here](https://user-images.githubusercontent.com/1830867/112756233-26b67180-8fdc-11eb-836d-74bc4454b983.png)). If you can remove those lines, this'll be good to go. Thanks for your work @rafi0101 💪

**Comment by rafi0101** [comment]
A few changes later, I think it is ready :hugs:

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks @rafi0101 - though there are now [a fair few differences](https://user-images.githubusercontent.com/1830867/113473397-26492b00-9461-11eb-8803-2e90d16fb266.png) on the circles. This can be down to SVGO, so you may need to up the precision to 4. Would you mind rebuilding this one and trying a precision of 4?

**Review by adamrusted — CHANGES_REQUESTED** [review]
There's still a [couple of small differences](https://user-images.githubusercontent.com/1830867/113474466-00735480-9468-11eb-9f64-6abf12c0d1e9.png), which you may be able to tweak just by moving the points around in your editor - but otherwise the 4 decimals seem to have fixed it 💪

**Comment by rafi0101** [comment]
@adamrusted how do you compare my svg to the original? Also is there a tool I can use that I can check it myself?

**Comment by adamrusted** [comment]
I'm just pulling your PR and the original source icon (scaled, but not optimized on my end) into the same Illustrator / Affinity file, overlaying yours in a bright colour with some opacity.

**Comment by rafi0101** [comment]
Thanks for this info. But I can not fix these small differences. After SVGO these differences are always there, even with precision 7

**Comment by adamrusted** [comment]
> I can not fix these small differences.

No worries, I'll try and fix them on my end, but will need another maintainer to sign off on the PR in that case.

**Review by adamrusted — APPROVED** [review]
How strange! Pulling this existing path into Illustrator removes the issue completely. Will merge this one, and it'll be released next Sunday. Thanks for your work @rafi0101 🚀

**Comment by rafi0101** [comment]
Strange. I used Inkscape to edit the svg. Maybe it was the program or just me. However, thanks for the effort @adamrusted  💪.

**Pull request merged**
