### PR TITLE
Add Mizuno logo

### LINKED ISSUE #11280: Request: Mizuno
### Brand Name

Mizuno

### Website

https://www.mizuno.com

### Popularity Metric

The SimilarWeb rank is 21,833.
https://www.similarweb.com/website/mizuno.com

### Official Resources for Icon and Color

SVG: https://commons.wikimedia.org/wiki/File:MIZUNO_logo.svg
Color: `#001489`

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by camilomontenegro**
**Issue:** closes #11280

**Popularity metric:**

The SimilarWeb rank is 21,833.
[similarweb.com/website/mizuno.com](https://www.similarweb.com/website/mizuno.com)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by uncenter — CHANGES_REQUESTED** [review]
Please fill out the pull request template. It exists for a reason.

**Comment by uncenter** [comment]
From https://mizunousa.com/legal:

> 5. Trademark Information. The trademarks, logos, and service marks displayed on the Sites are registered and common law trademarks of Mizuno USA, Mizuno Corporation and others (collectively the "Trademarks"). Nothing contained on the Sites should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any Trademarks without the written permission of Mizuno USA or such third party that may own the Trademarks. Your use of the Trademarks, or any other content on the Sites, except as provided in these Terms and Conditions, is strictly prohibited. You are also advised that Mizuno USA will aggressively enforce its intellectual property rights to the fullest extent of the law.

We will need to request permission to include this logo. Would you be willing to [reach out](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission) to them @camilomontenegro?

**Comment by adamrusted** [comment]
Did you reach out to them @camilomontenegro? If not, we'll have to close this PR for now.

**Comment by adamrusted** [comment]
Closing as not reached out to brand. If you do reach out to them @camilomontenegro - we can re-open this when we get a response.

**Pull request closed without merging**
