### PR TITLE
Updated Statamic

### PR DESCRIPTION
**Pull request by fbernhart**
statamic

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Looks like they've changed their icon quite a bit recently. The `/press` page is no longer available, and the colors may need updating. I suggest `#FF269E` as it's used in the favicon, sticky header, and links on homepage.

**Comment by fbernhart** [comment]
@adamrusted https://statamic.com/branding provides now all the needed information: SVGs and colors 😊 

Let me update it accordingly.

**Comment by fbernhart** [comment]
I've now used [this SVG file](https://statamic.com/assets/branding/Statamic-Logo-Blackish.svg) as source, which is listed on their branding page. Color: `#FF269E`

statamic

**Review by adamrusted — APPROVED** [review]
LGTM!

**Pull request merged**
