### PR TITLE
Add LXQT

### PR DESCRIPTION
**Pull request by mhf-ir**
**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Same as other desktop environment, i think it's good to add.

### CODE REVIEW

**Comment by runxel** [comment]
Hey @mhf-ir! 👋 
Welcome to simple-icons and thank you very much for the PR! 👍 

I took the liberty and deleted the extra icon. Otherwise the PR is looking pretty good!
One small thing: Just use the basic Wikipedia link, and do not link directly to the svg.
I guess, @PeterShaggyNoble would be afraid of link rot otherwise ;)
(/note to Peter: We should state that in the CONTRIBUTING.md)

**Comment by PeterShaggyNoble** [comment]
Thanks for updating that. From that link, though, it looks like the `T` in the name should be lowercase.

**Comment by PeterShaggyNoble** [comment]
**Alexa Rank:** [~1.25m](https://www.alexa.com/siteinfo/lxqt.org)

Anything else we could use to determine the popularity of this one, @mhf-ir?

**Comment by PeterShaggyNoble** [comment]
Closing as abandoned due to [this comment](https://github.com/simple-icons/simple-icons/pull/2402#issuecomment-579852495), as well as out of scope. If anyone else would like to take this on and can make a case for its popularity beyond its Alexa rank, please feel free to open a new PR or issue.

**Pull request closed without merging**
