### PR TITLE
Added Betfair icon

### PR DESCRIPTION
**Pull request by iugabogdan**
betfair (4)

**Issue:** https://github.com/simple-icons/simple-icons/issues/5714
**Alexa rank:** 10,460
  

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

I picked the #FFB80B color from the logo itself using colour picker. I think it represents the betfair brand well, the logo looks really well on that color.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @iugabogdan and thanks for the contribution 🙂

Could you have another look at it, though, please? It appears that you have vertically stretched the original to make both dimension `24` when only the width should be `24` with the height being relative to that.

**Comment by iugabogdan** [comment]
Hey @PeterShaggyNoble sorry about that, tried to follow the contribution guide as I am completely new to svg-s. Can you look over it again ? Hope I got it right this time. This time I tried to use inkscape, last time I used some online tool for it and maybe it went a bit wrong.  
I can look over it again if it's still not ok..

**Comment by PeterShaggyNoble** [comment]
Thanks, @iugabogdan, but I'm still seeing the same vertical stretching, I'm afraid.

**Comment by iugabogdan** [comment]
Ok on it again.

**Comment by iugabogdan** [comment]
@PeterShaggyNoble ok this time I got it right, time to go grab a 🍺 . In the meantime do you guys mind if I open another pull request with the PaddyPower logo ? Should I open an Issue and then PR ? or it's ok if I just go straight into PR ?

**Comment by PeterShaggyNoble** [comment]
> @PeterShaggyNoble ok this time I got it right

Nearly there 🙂 As you can see from our automated checks, the icon isn't quite vertically centred on the canvas. There's a tool in Inkscape that can do that for you, go to `Object > Align and distribute ...` in the menu (or hit <kbd>Crtl + Shift + A</kbd>), ensure "Page" is selected in the dropdown under "Align" and then hit "Center on vertical axis". Also, when optimising, you should be able to reduce the precision to 3 without any issues. And, finally, can you revert the change to the source, please?

> In the meantime do you guys mind if I open another pull request with the PaddyPower logo ?

Not only do we not mind, we actively encourage it 🙂

> Should I open an Issue and then PR ? or it's ok if I just go straight into PR ?

You can go straight to PR without first opening an issue, if you like. There's no _harm_ in opening an issue first, though, if you need to discuss sourcing a file or if you'd simply like to stake your claim while you work on the icon.

**Comment by iugabogdan** [comment]
@PeterShaggyNoble Ok done. So I ran `npm run svgo -- icons/betfair.svg -p 3` and pushed the result, ran the linters, should be good now.

**Review by PeterShaggyNoble — APPROVED** [review]
That looks perfect now, @iugabogdan 👍🏻

Just need to revert the change to the `source` in the JSON and this is ready to merge.

**Comment by iugabogdan** [comment]
Nice, thanks @PeterShaggyNoble, and sry for all this mess, like I've said before, I'm completely new to svg-s, tbh I didn't know they can be that complex.

Not sure what you mean with this:

`Just need to revert the change to the source in the JSON and this is ready to merge.`

The source is correct, it has this `ș` char in the link which translates to  `%C8%99`

image

That's where I got the image from.

**Comment by PeterShaggyNoble** [comment]
"Y'see, Peter, if you'd read the full source URL you'd have spotted that it's actually a copy of the Betfair logo!" 🤦🏻‍♂️

Sorry about that, @iugabogdan. However, we prefer to run with official sources wherever possible and the one on Wikipedia is sourced from Betfair themselves and lines up perfectly with the one on https://partnerships.betfair.com/ which is what I was using for my comparisons. So could you update the source to https://partnerships.betfair.com/?

**Comment by iugabogdan** [comment]
Sure thing! done.

**Comment by PeterShaggyNoble** [comment]
Thanks, @iugabogdan. And thanks again for the contribution 👍🏻 Looking forward to future PRs from you 🙂

**Pull request merged**
