### PR TITLE
New Icon: Davinci Resolve

### LINKED ISSUE #8287: Davinci Resolve
### Brand Name

Davinci Resolve

### Website

https://www.blackmagicdesign.com/products/davinciresolve

### Popularity Metric

Global rank  in similarweb is 18,374. Proof: https://www.similarweb.com/website/blackmagicdesign.com/#overview

### Official Resources for Icon and Color

https://www.blackmagicdesign.com/media/images/davinci-resolve-logo
https://www.blackmagicdesign.com/media/images/davinci-resolve-logo

### Additional Comments

There are two variants of this icon…

### Contributing

Yes

### PR DESCRIPTION
**Pull request by ripzerotwo**
**Issue:** closes #8287 

**Similarweb rank:** 18,374 (https://www.similarweb.com/website/blackmagicdesign.com/#overview)

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
Monochrome Logo. 
Took raster image and image trace.
Hex code is a guess from wikimedia lookup color using google extension colorpicker eyedropper
Preview...
davinciresolve

### CODE REVIEW

**Review by dirien — COMMENTED** [review]
HI @ripzerotwo,

thanks for the contribution. I am not sure on this one, as some parts are a little bit off

image

**Comment by ripzerotwo** [comment]
Gotcha ill go over it again having a little trouble with getting the finer details since im just using illustrator to generate paths from the raster.

**Comment by service-paradis** [comment]
@ripzerotwo Do you still plan to work on this one?

**Comment by service-paradis** [comment]
Closing this one for inactivity.

**Pull request closed without merging**
