### PR TITLE
Updated Audiomack

### PR DESCRIPTION
**Pull request by fbernhart**
audiomack

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by service-paradis** [comment]
Once again, thank you @fbernhart!
And I'm asking again about the precision 😉

**Comment by fbernhart** [comment]
@service-paradis Unfortunately it failed with a precision of 3 (optimized with SVGOMG). Should I revert the commit and we merge it with a precision of 4? Or would you like to try it yourself? Maybe you can make it work with a precision of 3.

**Comment by service-paradis** [comment]
NP @fbernhart, a precision of 4 is ok if it does not work with 3 as expected.
Out of curiosity, did you try using the official source (https://styleguide.audiomack.com/)?

**Comment by fbernhart** [comment]
@service-paradis I've now rebuilt it from source and tested it locally. A precision of 3 is unfortunatelly still failing. So I guess we have to use a precision of 4 instead.

**Comment by service-paradis** [comment]
> @service-paradis I've now rebuilt it from source and tested it locally. A precision of 3 is unfortunatelly still failing. So I guess we have to use a precision of 4 instead.

Am I going crazy or the icon is vertically reversed? 😉

**Comment by fbernhart** [comment]
@service-paradis Omg ... that's just embarrassing. 😂😅

Let's pretend like you've never seen this.

**Review by service-paradis — APPROVED** [review]
¡Wꓕꓨꓶ 💯

**Pull request merged**
