### PR TITLE
Add Momenteo icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** NA
**Alexa rank:** [~325k](https://www.alexa.com/siteinfo/momenteo.com)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- I took the SVG from https://www.momenteo.com/media
- I used Inkscape to scale and adjust
- I used https://jakearchibald.github.io/svgomg/ to optimize (was not able to make it work with a precision of 3)
- I used the primary color mentioned in https://www.momenteo.com/media

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Hmm ... I wonder if we could get away with just the "m" here, which they use in their favicon and on YouTube & Instagram?

**Comment by adamrusted** [comment]
> Hmm ... I wonder if we could get away with just the "m" here, which they use in their favicon and on YouTube & Instagram?

It also appears they just use the `m` [on their dashboard](https://www.momenteo.com/Content/download/dashboard.png),  so I'd say yes.

**Comment by service-paradis** [comment]
> Hmm ... I wonder if we could get away with just the "m" here, which they use in their favicon and on YouTube & Instagram?

Sure!

On their website, they use a `m` logo having gaps. I made 2 versions, which one do you prefer?
image
```svg
<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Momenteo icon</title><path d="M17.925 6.615c-.6.01-1.154.323-1.472.831-.348.41-3.163 3.98-4.142 5.22l.765.968c1.036-1.306 4.096-5.169 4.243-5.348a.765.765 0 011.265 0c.344.42 1.624 2.047 2.703 3.408.482.591.926 1.213 1.328 1.862.626 1.043-.395 2.02-.792 2.457l-3.254-4.098a.811.811 0 00-1.25-.016L14.2 15.836 7.548 7.447a1.774 1.774 0 00-3.02.024c-.059.067-1.706 2.156-2.989 3.776-.528.701-.956 1.33-1.178 1.7-1.048 1.75.441 3.462 1.239 4.165.174.16.399.257.636.272a.727.727 0 00.677-.368l3.145-3.97s2.882 3.644 3.227 4.07a.64.64 0 001.033-.005c.198-.253.76-.962 1.373-1.733l-.765-.964c-.548.69-1.021 1.286-1.127 1.426l-3.118-3.938a.811.811 0 00-1.25.016l-3.254 4.099c-.397-.438-1.416-1.415-.792-2.458a17.57 17.57 0 011.329-1.861c1.078-1.362 2.358-2.989 2.703-3.408a.765.765 0 011.264 0l7 8.823a.64.64 0 001.034.005c.345-.426 3.227-4.07 3.227-4.07l3.146 3.968a.727.727 0 00.675.367c.238-.015.463-.11.638-.272.797-.702 2.286-2.414 1.238-4.165-.222-.37-.65-1-1.179-1.7-1.282-1.621-2.929-3.71-2.989-3.777a1.774 1.774 0 00-1.546-.854z"/></svg>
```

image
```svg
<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Momenteo icon</title><path d="M6.025 6.605c-.558.01-1.111.3-1.497.855-.06.067-1.707 2.161-2.99 3.786A21.914 21.914 0 00.36 12.95c-1.046 1.754.441 3.467 1.238 4.171.169.149.414.275.636.274.178 0 .367.012.677-.37l3.147-3.978s2.88 3.654 3.225 4.08c.297.364.767.332 1.036-.006.633-.806 1.111-1.41 1.68-2.126l.034.042c.7.883 1.416 1.784 1.65 2.084.27.338.737.37 1.033.006.345-.426 3.228-4.077 3.228-4.077l3.144 3.978c.31.382.5.366.678.367.221.001.467-.125.635-.274.797-.704 2.286-2.416 1.238-4.17a21.944 21.944 0 00-1.178-1.705c-1.281-1.624-2.93-3.719-2.99-3.786-.398-.572-.975-.863-1.551-.855-.54.008-1.082.278-1.47.831-1.497 1.866-2.973 3.75-4.453 5.629-.323-.406-4.047-5.151-4.451-5.629-.4-.571-.963-.84-1.521-.83zm-.015 1.34c.226-.013.463.085.668.335.169.205 4.065 5.13 4.55 5.742v.003h.004v.003c-.489.616-1.01 1.278-1.434 1.816L6.678 11.9a.808.808 0 00-1.25.015l-3.252 4.108c-.396-.44-1.416-1.419-.792-2.463.232-.388.66-1.028 1.328-1.865C3.79 10.33 5.072 8.7 5.417 8.28a.83.83 0 01.593-.335zm11.98 0c.226.013.438.138.593.335.344.42 1.626 2.05 2.704 3.414.668.838 1.096 1.48 1.328 1.868.624 1.044-.396 2.02-.792 2.46l-3.256-4.108a.808.808 0 00-1.25-.015l-3.12 3.945c-.125-.163-.765-.972-1.433-1.813 1.52-1.917 3.034-3.836 4.554-5.751.205-.25.445-.348.671-.335z"/></svg>

```

**Comment by adamrusted** [comment]
> On their website, they use a `m` logo having gaps. I made 2 versions, which one do you prefer?

I prefer the first one here - the header uses the gaps, and the footer seems to avoid the gaps in favour of a drop shadow, which we would re-interpret to gaps upon conversion anyway.

**Comment by service-paradis** [comment]
> > On their website, they use a `m` logo having gaps. I made 2 versions, which one do you prefer?
> 
> I prefer the first one here - the header uses the gaps, and the footer seems to avoid the gaps in favour of a drop shadow, which we would re-interpret to gaps upon conversion anyway.

Great! I just pushed this version! Thank you both for the feedback :)

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @service-paradis 🎉

**Pull request merged**
