### PR TITLE
Add F-Droid (#2037)

### LINKED ISSUE #2037: Add F-Droid
**Name:** F-Droid
**Website:** https://f-droid.org/
**Official resources for icon and color:** There is a svg in the website's header.

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
Closes #2037 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The logo comes from the svg in their website header. The blue color `#1976D2` is from the droid's body (and also mainly used on the website, that's why I chose it over the green tone).
The stenciling of the copyleft symbol was done to stay compatible to other monochrome versions, like at [Fork Awesome](https://github.com/ForkAwesome/Fork-Awesome/issues/135). (Endorsed by the maintainers of F-Droid)

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @runxel thanks for your work on this 👍 

> The stenciling of the copyleft symbol was done to stay compatible to other monochrome versions, like at [Fork Awesome](https://github.com/ForkAwesome/Fork-Awesome/issues/135). (Endorsed by the maintainers of F-Droid)

Looking at the [official .svg](https://f-droid.org/assets/fdroid-logo-text.svg) the PR version is quite different. See image below. "Exp" = "Expected"
f-droid-comp

I see you have really looked into this issue which is great.👍 

However, reading the reference you included (https://github.com/ForkAwesome/Fork-Awesome/issues/135) you conclude "endorsed", whereas I read that as an acknowledgment this action would simply be compliant with the license terms? 🤔 

Even so, I'm not convinced an interpretation of the design is appropriate when there is an official source .svg? What do the @simple-icons/maintainers think?

simplified .svg code below ⬇️  for "Exp" in above .png ⬆️ 

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M.68.153a.662.662 0 00-.067.002.662.662 0 00-.469 1.072l2.239 2.9c-.274.453-.44.98-.44 1.55v.88c0 1.663 1.338 3 3 3h14.114c1.662 0 3-1.337 3-3v-.88c0-.57-.165-1.097-.439-1.55l2.238-2.9a.662.662 0 00-.554-1.072.662.662 0 00-.493.263L20.69 3.163a2.988 2.988 0 00-1.633-.487H4.943c-.603 0-1.161.18-1.63.485L1.19.418A.662.662 0 00.68.153zM6.905 4.66a1.786 1.786 0 011.786 1.785 1.786 1.786 0 01-1.786 1.787A1.786 1.786 0 015.12 6.446a1.786 1.786 0 011.787-1.785zm10.321 0a1.786 1.786 0 011.787 1.785 1.786 1.786 0 01-1.787 1.787 1.786 1.786 0 01-1.785-1.787 1.786 1.786 0 011.785-1.785zM4.943 10.087c-1.662 0-3 1.338-3 3v7.76c0 1.662 1.338 3 3 3h14.114c1.662 0 3-1.338 3-3v-7.76c0-1.662-1.338-3-3-3zM12 11.409a5.566 5.566 0 015.56 5.557A5.567 5.567 0 0112 22.525a5.566 5.566 0 01-5.557-5.559A5.564 5.564 0 0112 11.41zm0 1.006a4.544 4.544 0 00-4.553 4.551A4.546 4.546 0 0012 21.52a4.546 4.546 0 004.553-4.553A4.544 4.544 0 0012 12.416zm0 1.244a3.32 3.32 0 013.31 3.307A3.321 3.321 0 0112 20.275a3.322 3.322 0 01-3.22-2.567h1.67c.274.581.858.979 1.55.979.96 0 1.721-.761 1.721-1.72 0-.96-.761-1.72-1.72-1.72a1.7 1.7 0 00-1.493.873H8.807A3.321 3.321 0 0112 13.66z"/></svg>
```

**Comment by birjolaxew** [comment]
@phatbhoy67 I definitely agree that we should use the official SVG.

**Comment by runxel** [comment]
Appreciating the comment @phatbhoy67!
But I think something's wrong on your side. The icon in the PR **_is_** the one you have linked.
Your version is way to round, the one in the PR is 100% true to the original. I've checked it thrice now and I'm pretty sure that I've done everything carefully... 😕 

Maybe you have resized the logo and by accident the Illustrator option "resize corners and effects" was on? Because again, look at the official logo: (sorry for dark mode)
fd

The corners are rounded, but the radius is much much smaller than in your "EXP" version.

**Comment by birjolaxew** [comment]
After checking it out in Photoshop, I can definitely confirm that the version from this PR matches the official SVG exactly. 

<p align="center"></p>

With that in mind, I'll be merging this in. Thanks for your work on this @runxel!

**Comment by birjolaxew** [comment]
Also I'm kinda interested in what went wrong above :P It's obviously an honest mistake, but I'm having a hard time trying to think of how the SVG got more rounded. Would be interested if you figure it out @phatbhoy67.

**Comment by phatbhoy67** [comment]
f-droid-final

Update...................

**Comment by runxel** [comment]
> Also I'm kinda interested in what went wrong above :P It's obviously an honest mistake, but I'm having a hard time trying to think of how the SVG got more rounded. 

My bets are still on the Illustrator option that will resize rounded corners when scaling (or rather not resizes so the radius stays big, but the overall vector sizes down). 🤔

**Comment by phatbhoy67** [comment]
As @runxel pointed out I think it was a scaling issue with the stroke when I copied one into the other to compare and resized down the original icon to 24px. I'd love to tell you it's an easy mistake to make, but it really isn't 😆  Apologies for the spam @runxel

**Comment by runxel** [comment]
Ah don't worry @phatbhoy67! Happens to the best people! 😊

**Pull request merged**
