### PR TITLE
Add ImageJ

### PR DESCRIPTION
**Pull request by adamrusted**
imagej

**Issue:** Contributes to #5466
**Alexa rank:** [177,386](https://www.alexa.com/siteinfo/imagej.net)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Gone with the blue from the Inkscape SVG provided, and simplified the curves of the J, to remove extraneous points.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
@ctrueden, before we proceed with our review, are you happy with this treatment and colour choice?

**Comment by ayushnoori** [comment]
Hi @PeterShaggyNoble - following up on this thread, do you have a rough estimate of when the ImageJ logo might be available via SimpleIcons? Thanks so much!

**Comment by adamrusted** [comment]
Hey @ayushnoori, as per @PeterShaggyNoble's comment above, we're waiting on comment from @ctrueden before the team review the PR for inclusion. Once it's been reviewed and merged, it'll be in the next release (generated every Sunday) - but will then need the likes of shields.io to update their dependency, which we have no control over.

**Comment by ctrueden** [comment]
Ah, sorry, just noticed this deep in my bottomless pit of email. Yes, I am happy with it. Thanks for seeing it through.

**Comment by adamrusted** [comment]
Amazing, thanks @ctrueden!
@simple-icons/maintainers - any chance we can get this reviewed ahead of this weeks' release?

**Comment by PeterShaggyNoble** [comment]
I'm seeing a [small difference](https://user-images.githubusercontent.com/15157491/117309257-2aaa9e80-ae7a-11eb-8a5c-d18d06dee04f.png) in the bottom curve when compared against the top left logo in the source file, @adamrusted.

**Review by PeterShaggyNoble — APPROVED** [review]
Looks perfect now, @adamrusted, nice work 👍🏻

And thanks for your feedback, @ctrueden, much appreciated 🙂

**Pull request merged**
