### PR TITLE
Added pytest icon

### LINKED ISSUE #5474: pytest
**Brand Name:**pytest  
**Website:** https://docs.pytest.org/en/6.2.x/  
**Alexa rank:**  164,047
  

**Official resources for icon and color:**
  
  https://docs.pytest.org/en/6.2.x/_static/pytest1.png

### PR DESCRIPTION
**Pull request by DenverCoder1**
image

**Issue:** Resolves #5474 
**Website:** https://pytest.org, https://github.com/pytest-dev/pytest
**Alexa rank:** 174,236

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The blue color was chosen as the color since it is the color of the largest bar as well as being incorporated as the text color in the text version of the logo.

The SVG from the [design repo](https://github.com/pytest-dev/design/blob/081f06cd2d6cd742e68f593560a2e8c1802feb7c/pytest_logo/pytest_logo.svg) was used for creating this monochrome logo.

### CODE REVIEW

**Review by service-paradis — CHANGES_REQUESTED** [review]
Thank you @DenverCoder1 for your contribution! The icon is looking good overall 💯 

There is a little difference in the horizontal bar that might be due to the optimization process (you can try with a precision of 4 if needed):
image

Can you give this one another try?

**Comment by DenverCoder1** [comment]
@service-paradis I have tried with precision set to 4. It looks accurate to me, hopefully there are no issues.

**Review by service-paradis — APPROVED** [review]
Thank you @DenverCoder1, it is perfect now 💯 
If you can bring your PR up-to-date with `develop`, I will be able to merge this one :)

**Comment by DenverCoder1** [comment]
@service-paradis Thanks, it should be up to date now

**Pull request merged**
