### PR TITLE
Add Wellfound Icon

### LINKED ISSUE #8528: Request: Wellfound
### Brand Name

Wellfound

### Website

https://wellfound.com/

### Popularity Metric

[15,882](https://www.similarweb.com/website/wellfound.com/#overview)

### Official Resources for Icon and Color

https://wellfound.com/logo

color: either `#000000` or `#ea2c00`

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by Katsute**
**Issue:** closes #8528 

**Similarweb rank:** [8017](https://www.similarweb.com/website/wellfound.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Closes #8528, sourced from EPS icon from https://wellfound.com/logo

### Preview

preview

### CODE REVIEW

**Comment by LitoMore** [comment]
@Katsute Would you mind reaching out to their Twitter and asking for their color preference or getting a approval?

I can see they have two colors in their brand guideline but we only support single color.

**Comment by Katsute** [comment]
@LitoMore I do not have a Twitter 😭

I think black rather than the red would make sense as the primary, judging off their site design. Red only appears in the logo site-wide.

**Comment by LitoMore** [comment]
@Katsute No worries. I will follow up this.

**Comment by adamrusted** [comment]
@LitoMore - did you get any feedback? I'd be happy with the black tbf, and the icon is a perfect match.

**Comment by LitoMore** [comment]
@adamrusted No reply yet.

**Comment by service-paradis** [comment]
I think we could merge this one as-is. Color could be updated easily if we have some feedback later.

**Comment by Katsute** [comment]
Can we merge this? #9303 will make it impossible to refer to Wellfound, since people use the AngelList icon as a stand-in for Wellfound.

**Comment by adamrusted** [comment]
Given we've still not heard anything back, and the icon is a perfect match, let's get this one merged for now. Can always change the hex at a later date.

**Review by adamrusted — APPROVED** [review]

**Pull request merged**
