### PR TITLE
Add ADP icon

### PR DESCRIPTION
**Pull request by Jwaegebaert**
**Issue:** No related issue

**Similarweb rank:** 570

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The icon was found using element inspect on the [ADL homepage](https://www.adp.com/). Here I found a direct link to the [SVG](https://www.adp.com/-/media/adp/redesign2018/ui/logo-adp-fy19.svg). 
The HEX value #D0271D was fetched from the SVG icon.

adp

### CODE REVIEW

**Comment by LitoMore** [comment]
CleanShot 2022-11-04 at 21 08 42@2x

@Jwaegebaert I see some differences. Could you check this?

**Review by LitoMore — CHANGES_REQUESTED** [review]

**Comment by Jwaegebaert** [comment]
Hey @LitoMore, how can I tackle this? Currently, I use `svgomg` to simplify the SVG file. Would increasing the precision here help?

**Comment by LitoMore** [comment]
@Jwaegebaert Yes. Increasing the precision might help. And make sure you enabled the aspect ratio lock when resizing the icon.

**Comment by Jwaegebaert** [comment]
I rescaled the image from the starting SVG to make sure it isn't warped and added more precision with ´svgomg´

**Review by LitoMore — APPROVED** [review]
CleanShot 2022-11-14 at 21 15 49@2x

@Jwaegebaert Perfect fit now. Thank you!

**Pull request merged**
