### PR TITLE
Add Font Awesome

### LINKED ISSUE #2437: Font Awesome
**Name:** Font Awesome
**Website:** https://fontawesome.com/
**Alexa Rank:** [~2.7k](https://www.alexa.com/siteinfo/fontawesome.com)
**Colour:** `#339af0`
**Official resources for icon and color:** https://fontawesome.com/icons/font-awesome

[Font Awesome](https://github.com/simple-icons/simple-icons/files/4092505/fontawesome.zip)

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Font Awesome

**Issue:** Closes #2437

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by runxel** [comment]
Well, I've corrected obvious errors in the past as well.
It also makes the icons smaller in file size at most times.

**Comment by PeterShaggyNoble** [comment]
@ericcornelissen & @runxel, before I commit it, does this path look OK to you?

```
M21.31 0H2.69A2.705 2.705 0 000 2.69v18.62A2.705 2.705 0 002.69 24h18.62A2.705 2.705 0 0024 21.31V2.69A2.705 2.705 0 0021.31 0zM18.88 15.23c0 .225-.193.322-.418.418-.895.386-1.854.734-2.882.734-1.442 0-2.111-.895-3.841-.895-1.249 0-2.561.45-3.617.927-.064.032-.128.032-.192.065v2.432c.004.668-.45 1.072-1.056 1.087a1.081 1.081 0 01-1.087-1.087V7.2a1.781 1.781 0 01-.702-1.409c0-.991.798-1.795 1.795-1.795.99 0 1.794.799 1.794 1.795 0 .579-.257 1.088-.702 1.409v.991c.097-.032.193-.064.29-.129.99-.417 2.175-.766 3.294-.766 1.216 0 2.175.322 3.263.734.225.097.45.129.702.129 1.216 0 2.56-.863 2.882-.863.257 0 .482.193.482.418v7.516Z
```

My manual editing skill aren't the best but I did what I could with it after removing the 2 extra points. Still, that bottom right curve of the flagpole doesn't *quite* line up with the original.

**Comment by PeterShaggyNoble** [comment]
Here's another option made by layering their [`font-awesome-flag` icon](https://fontawesome.com/icons/font-awesome-flag) over their  [`square` icon](https://fontawesome.com/icons/square). There are some minor discrepancies with the original `font-awesome` icon but this is what they use for the logo in their header.

```
M2.571 0A2.572 2.572 0 000 2.571V21.43A2.572 2.572 0 002.571 24H21.43A2.572 2.572 0 0024 21.429V2.57A2.572 2.572 0 0021.429 0zm4.324 4c.993 0 1.793.8 1.793 1.791A1.7 1.7 0 017.984 7.2v.993c.128-.043 1.836-.897 3.584-.897 2.04 0 3.053.865 3.968.865 1.217 0 2.56-.865 2.88-.865.257 0 .48.192.48.416v7.521c0 .224-.191.32-.415.416-.896.384-1.857.736-2.88.736-1.44 0-2.113-.896-3.841-.896-1.248 0-2.56.448-3.616.929-.064.032-.129.032-.193.064v2.432c0 .669-.503 1.088-1.056 1.088a1.08 1.08 0 01-1.088-1.088V7.199a1.789 1.789 0 01-.704-1.408C5.103 4.8 5.903 4 6.895 4z
```

**Comment by phatbhoy67** [comment]
I think merging the version that matches the original with the small distortion is fine.

@tagliala looks to be one of the most active maintainers over at [Font-Awesome](https://github.com/FortAwesome/Font-Awesome) maybe they can confirm it is an anomaly in the icon path at (https://fontawesome.com/icons/font-awesome) that needs fixing?

**Comment by tagliala** [comment]
@phatbhoy67 thanks for point this out! I think this is an issue and an opportunity to improve the svg. I will open a new issue on Font Awesome

**Comment by PeterShaggyNoble** [comment]
Thanks, @tagliala and good to "see" you again 😃

I'll keep an eye on your bug report and update here when it's sorted.

**Comment by ericcornelissen** [comment]
Great to see the official icon may get updated 👍 

@PeterShaggyNoble your newer paths both look good w.r.t. [the distortion I pointed out](https://user-images.githubusercontent.com/3742559/72898510-ec44ab00-3d2c-11ea-8cd8-0a0c19efc0bb.png) but both still have [the distortion pointed out by @tagliala](https://user-images.githubusercontent.com/556268/73008536-0c4c9b00-3e0f-11ea-81b2-e37e3db74e0f.png) (I noticed that one as well but actually thought it was intentional 😅).

I'm fine with merging this with either the current path or [this path](https://github.com/simple-icons/simple-icons/pull/2447#issuecomment-577614426) or [this path](https://github.com/simple-icons/simple-icons/pull/2447#issuecomment-577650448) for now and updating whenever the problem is resolved at font-awesome's side 🙂

**Comment by PeterShaggyNoble** [comment]
Let's go with the last option I posted as it's what they use as their logo and we can update when they update when then get the original sorted.

**Pull request merged**
