### PR TITLE
The Revert PR

### PR DESCRIPTION
**Pull request by adamrusted**
This PR goes alongside #10518 to complete #10514. Reverts some icons back to using `#FFFFFF` as their hex.

### CODE REVIEW

**Comment by LitoMore** [comment]
Some colors don't need to revert. Let's create a common PR instead.

**Comment by adamrusted** [comment]
> Some colors don't need to revert. Let's create a common PR instead.

See the linked PR and issue. Can we keep discussion to the issue so as to not muddy the waters?

**Comment by LitoMore** [comment]
np. Go ahead.

**Review by PeterShaggyNoble — APPROVED** [review]

**Comment by service-paradis** [comment]
As mentioned in the issue (https://github.com/simple-icons/simple-icons/issues/10514#issuecomment-1961461766), I think some of those revert was not necessary (Fluxus and Reason Studios for example).

**Pull request merged**
