### PR TITLE
Add XMPP

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
From previously abandonded #1339

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo is as an svg on the website header (quality is very bad tho, I did some tidy up).
Color is very debatable. I chose `#1777A9` for the moment. This is the calculated midpoint from the blue stripes' gradients. However we could as well take that green `#a0ce67`, or orange `#e96d1f`.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Found this SVG in their repo, if it's any help: https://github.com/xsf/xmpp.org/blob/f42b08f5d9edbfe068e2463e486d536a9c5bc96d/content/icons/safari-pinned-tab.svg The [one on Wikimedia](https://upload.wikimedia.org/wikipedia/commons/9/95/XMPP_logo.svg) also seems to be better quality than the one on the website.

The colour's tricky. As you say, any of the 3 would be valid choices but, as blue is the one they use most on their site, I'd agree with your choice. However, from the website's stylesheet that blue is `#008cba`. What do the other @simple-icons/maintainers think?

**Comment by phatbhoy67** [comment]
I would use (https://xmpp.org/icons/safari-pinned-tab.svg) as the source to remove the need to interpret the  [logo .svg](https://xmpp.org/theme/images/xmpp-logo.svg) found in the header.

I'd say the main brand colour is `#002b5c`. Used as a stop on the logo gradient and as font colour in headers on the website.

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @runxel 👍

**Comment by Neustradamus** [comment]
@runxel: Have you taken the last SVG from commons?
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

**Comment by ericcornelissen** [comment]
As per #2272 I agree that we should update it to the wikimedia version, thanks @Neustradamus 🙂

**Comment by Neustradamus** [comment]
@ericcornelissen: Thanks in advance!
Note: Do not add the text.

**Comment by runxel** [comment]
@Neustradamus 
Thanks for your valuable comments here!
This all should be resolved in #2275 :)

**Comment by Neustradamus** [comment]
@runxel: Thanks a lot, if all people was like you!

**Comment by runxel** [comment]
@Neustradamus 
Thanks! You're welcome 😊

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/simple-icons/simple-icons/pull/2085
- https://github.com/simple-icons/simple-icons/issues/2272
- https://github.com/simple-icons/simple-icons/pull/2275

**Pull request merged**
