### PR TITLE
Fixed the Conda-Forge and Viber icons' paths.

### PR DESCRIPTION
**Pull request by metaa**
I'm working on something for `simple-icons` right now (#1307) and noticed that the icons `conda-forge` and `viber` are messed up.

This is what they looked like when opened in InkScape:
`conda-forge` had a box surrounding it far outside the viewbox.
image

`viber` had a speech bubble far outside the viewbox.
image

I removed the oddities, rescaled the icons to 24px and recentered them.

### CODE REVIEW

**Comment by davidklebanoff** [comment]
Interesting! A great catch, thanks!

Would you mind combining the paths for the Viber icon before we merge? Other than that it they look good!

**Comment by metaa** [comment]
Whoops, of course!

**Comment by davidklebanoff** [comment]
Again, great job! The new icons have been merged in.

**Comment by casperdcl** [comment]
lol whoops I contributed the original `conda-forge` icon; don't know how I missed that.

**Pull request merged**
