### PR TITLE
Add transmission

### LINKED ISSUE #6246: Request to add torrent clients
- [ ] BitComet: https://en.wikipedia.org/wiki/BitComet
Alexa rank: 62777

- [ ] BItTorrent: https://en.wikipedia.org/wiki/BitTorrent_(software)
Alexa rank: 4104

- [ ] uTorrent: https://en.wikipedia.org/wiki/%CE%9CTorrent
Alexa rank : 705

- [ ] Transmission: https://en.wikipedia.org/wiki/Transmission_(BitTorrent_client)
Alexa rank: 139777

So, I think we can all agree that like 99% of applications of the bitTorrent protocol is illegal downloads and piracy. Regardless of my personal opinions on the matter, I think that shouldn't matter, using the same criteria used to allow fileshare services and OnlyFans: Even if 99% of the content is illegal / unsavory / not preferable, there are plausible legal applications and they are not illegal nor promoted for illegal uses.

If this is approved, I will take them since I'm personally interested in having them added. Waiting on feedback...

### LINKED ISSUE #7490: Transmission
### Brand Name

Transmission

### Website

https://transmissionbt.com/

### Popularity Metric

143,594 https://www.similarweb.com/website/transmissionbt.com/#ranking

### Official Resources for Icon and Color

None

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
transmission

**Issue:** closes #7490

**Similarweb rank:** 168,243. See https://www.similarweb.com/website/transmissionbt.com

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Vectorized from logo on front page https://transmissionbt.com/assets/images/Transmission_icon.png
Color: `#D70008` Taken from the download button on the front page https://transmissionbt.com

### CODE REVIEW

**Comment by PratyushJayachandran** [comment]
> Looks pretty good to me, @PratyushJayachandran 👍🏻 But I think we should give the handle a bit more definition, either by adding cut-outs between each part or outlining the red part. What do you reckon?

Done
transmission

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
That works much better, @PratyushJayachandran, nice work 👍🏻 Is it possible to get [the handle](https://github.com/simple-icons/simple-icons/assets/15157491/bbaa12c4-b169-45be-8dd3-086a2dec28b2) to line up a bit better with the original, though?

**Comment by PratyushJayachandran** [comment]
> That works much better, @PratyushJayachandran, nice work 👍🏻 Is it possible to get [the handle](https://github.com/simple-icons/simple-icons/assets/15157491/bbaa12c4-b169-45be-8dd3-086a2dec28b2) to line up a bit better with the original, though?

I started with a vectorized png and that seems to have resulted in my shapes being misaligned. Give me some time on this one.

**Comment by adamrusted** [comment]
@PratyushJayachandran / @PeterShaggyNoble - there are SVGs available [here](https://github.com/transmission/transmission/blob/7c9e04d035f3f75a8124e83d612701824487eb4e/gtk/icons/hicolor_apps_scalable_transmission.svg) or a monochrome (albeit tiny) icon [here](https://github.com/transmission/transmission/blob/7c9e04d035f3f75a8124e83d612701824487eb4e/gtk/icons/hicolor_apps_symbolic_transmission-symbolic.svg). Should we be using one of those as the source?

**Comment by PeterShaggyNoble** [comment]
Nice find, @adamrusted! 👍🏻 I think the monochrome one is the one we should run with - what do you reckon, @PratyushJayachandran?

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran / @PeterShaggyNoble - there are SVGs available [here](https://github.com/transmission/transmission/blob/7c9e04d035f3f75a8124e83d612701824487eb4e/gtk/icons/hicolor_apps_scalable_transmission.svg) or a monochrome (albeit tiny) icon [here](https://github.com/transmission/transmission/blob/7c9e04d035f3f75a8124e83d612701824487eb4e/gtk/icons/hicolor_apps_symbolic_transmission-symbolic.svg). Should we be using one of those as the source?

Changed to monochromatic icon which @adamrusted skillfully discovered.
transmission-v3

**Pull request merged**
