### PR TITLE
Updating Nokia

### LINKED ISSUE #8391: Update Nokia
### Brand Name

Nokia Corporation

### Official Resources for Icon and Color

https://commons.wikimedia.org/wiki/File:Nokia_2023.svg

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by zcraber**
nokia

**Issue:** closes #8391

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

**Why did you pick the hex value?**
Brand colour.

### CODE REVIEW

**Comment by zcraber** [comment]
Nokia Mobile still retains the old logo.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @zcraber!

**Comment by zcraber** [comment]
@adamrusted Just a heads up, [Nokia Phones](https://www.nokia.com/phones/) still uses the old logo.

**Comment by adamrusted** [comment]
That URL points to a 3rd party, who are the global reseller for Nokia.
Nokia themselves are using the new logo on their socials etc, so I think we're safe as-is.
If we get a request specifically for the 'Nokia Phones' icon to be re-added, I'll contribute it myself 🙂

**Pull request merged**
