### PR TITLE
Add Fubo Icon (#10047)

### LINKED ISSUE #10047: Fubo
### Brand Name

Fubo

### Website

https://www.fubo.tv/

### Popularity Metric

The Similarweb rank is 1,295. See https://www.similarweb.com/website/fubo.tv

### Official Resources for Icon and Color

Official Fubo iOS app logo from press release https://s21.q4cdn.com/819998841/files/doc_multimedia/Fubo_IOS_Icon_1024x1024_RGB.jpg

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by andyrak**
image

**Issue:** closes #10047

**Similarweb rank: 1,295**

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Hex value extracted from the official logo.
- Vector extracted as AI from official brand assets.

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Looking at the version available [here](https://www.fubo.tv/signin) in red, it would appear your PR is slightly stretched. Would you mind having another look please, @andyrak?

image

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @andyrak?

**Comment by andyrak** [comment]
@PeterShaggyNoble Yes, will have some time today to investigate!

**Comment by andyrak** [comment]
@adamrusted Not sure where the discrepancy is coming from. Every version I've checked matches my original outline, not the red as you highlighted. Unless I'm doing something terribly wrong in my workflow.

I confirmed this with these three files:
- https://drive.google.com/file/d/12Ly4vWvK-KQ6j5qH1iw1vtB8w1jafZns/view?usp=drive_link
- https://drive.google.com/file/d/1vq2cbPZAoNJcQCHscUzdazMJCppoXEQu/view?usp=drive_link
- Page 4 of the PDF https://drive.google.com/file/d/17AGIDjFWvJGsqhcGUAZse62H1m5ANb7i/view?usp=drive_link

My original was lifted from the logo on the right-side margin of page 4 of the PDF listed above.

**Review by PeterShaggyNoble — APPROVED** [review]
> My original was lifted from the logo on the right-side margin of page 4 of the PDF listed above.

Compared against that logo, your version lines up perfectly :+1:

For the colour, though, I'm getting `#e03100` from the stylesheet on [their login page](https://www.fubo.tv/signin) and `#c83d1e` from other pages like [this one](https://www.fubo.tv/stream/tv/). And of those 2, I'd lean towards the latter.

**Comment by andyrak** [comment]
Thanks, @PeterShaggyNoble!

I've updated the json to reflect `#C83D1E`.

image

**Comment by andyrak** [comment]
Thanks for the help! Excited to make other contributions in the future. Have a good one!

**Pull request merged**
