### PR TITLE
Add Consul

### PR DESCRIPTION
**Pull request by mhf-ir**
**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Alexa rank is about [197K](https://www.alexa.com/siteinfo/consul.io)

### CODE REVIEW

**Comment by foo-dogsquared** [comment]
Basing from the monochrome SVG file (`consul-monochrome.svg`) from the given brand kit. 

(Your version is yellow and the official SVG is in black.)



It doesn't matter much since the official SVG is malformed. 
(Isn't that fun...)
 






Here's the malformed sections of the official SVG in highlight.
(The SVG file in picture is `consul-black.svg` but it doesn't matter either since it also has the same problems as all of the other SVGs.)



The AI version, for whatever reason, has less problems (and way more subtle unless closely inspected). 
I recommend to start with that and fix the highlighted sections.

**Comment by mhf-ir** [comment]
Update from official hashicorp https://www.hashicorp.com/brand:
https://s3.amazonaws.com/hashicorp-marketing-web-assets/brand/Consul.zip
Consul_VerticalLogo_MonochromeTonal.svg

**Comment by foo-dogsquared** [comment]
The malformations are still present in the updated version. 

I advise to use the AI version of the logo (for reference, I mainly inspected `Consul_PrimaryLogo_Black.ai`) since it has less malformations than the SVG versions.

**Comment by mhf-ir** [comment]
I think you must ask Consul to fix it.
All version have same issue:
Screenshot from 2020-01-20 20-25-26
Screenshot from 2020-01-20 20-24-18
Screenshot from 2020-01-20 20-23-30

**Comment by mhf-ir** [comment]
Should i fix original icon? or ask for Hashicorp to fix it :smiley: ?

**Comment by mhf-ir** [comment]
CNCF also have same issue:
https://github.com/cncf/landscape/blob/master/hosted_logos/consul.svg

I dont think this is duty of simple icon to fix problem of logo designing.

**Comment by PeterShaggyNoble** [comment]
Closing as abandoned due to [this comment](https://github.com/simple-icons/simple-icons/pull/2402#issuecomment-579852495). If anyone else would like to take this on, please feel free to open a new PR or issue.

**Pull request closed without merging**
