### PR TITLE
Add Ardour

### LINKED ISSUE #2909: Request: Ardour
**Name:** Ardour
**Website:** https://www.ardour.org
**Official resources for icon and color:** SVG file can be found [in source code repository](https://raw.githubusercontent.com/Ardour/ardour/master/tools/misc_resources/ardour_bw.svg). All vector resources are located [in the same directory](https://github.com/Ardour/ardour/tree/master/tools/misc_resources).
**Alexa Rank:** [~300k](https://www.alexa.com/siteinfo/ardour.org)
**Colour:** `#E4214E` or `#DC1C3C`
**Official resources for icon and color**: Colour from [repository icons](https://github.com/Ardour/ardour/tree/master/tools/misc_resources). [This file (app-icon_tango.svg)](https://raw.githubusercontent.com/Ardour/ardour/master/tools/misc_resources/app-icon_tango.svg) has some Ardour icons colorized, but not all with the same colour.

### PR DESCRIPTION
**Pull request by mondeja**
ardour-preview

**Issue:** Closes #2909 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Source SVG file from [here](https://raw.githubusercontent.com/Ardour/ardour/master/tools/misc_resources/ardour_bw.svg).

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the PR, @mondeja.

I think we can go with the icon without the text here.

**Comment by PeterShaggyNoble** [comment]
Also, the source URL should be the URL of the SVG used on GitHub, including the commit hash. See [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#source-guidelines) for more details.

**Comment by mondeja** [comment]
Updated, here is the new preview:
ardour-commit-2-preview

**Comment by PeterShaggyNoble** [comment]
Thanks, @mondeja :+1:

Firstly, one minor issue: your path is coming in at `24.001` wide. This can usually be fixed by increasing the precision.

Secondly, to help us compare like with like, could you let us know which specific version of their icon you based yours on? There are some terrible inconsistencies between files and even within individual files 🙄 The comparison below, for example, shows the top-left icon in [this file](https://github.com/Ardour/ardour/blob/master/tools/misc_resources/app-icon_tango.svg) overlaid in red with the top-right one. I've compared your version with 3 different versions from their repo and all have different inconsistencies so I suspect I'm not using the one you used.

Finally, for the source URL, if you used the `app-icon_tango.svg` file linked above, for example, it should be https://github.com/Ardour/ardour/blob/9fac6139ea40ee2ba5af1415c302c61fee6a13aa/tools/misc_resources/app-icon_tango.svg - to get the file URL with the latest commit hash included hit `y` on your keyboard while viewing the source file in your browser.

Ardour

**Comment by mondeja** [comment]
I've used the file [ardour_bw](https://raw.githubusercontent.com/Ardour/ardour/9fac6139ea40ee2ba5af1415c302c61fee6a13aa/tools/misc_resources/ardour_bw.svg). I'm not sure of what icon to use. Maybe we need to ping Ardour developers.

**Comment by PeterShaggyNoble** [comment]
> I've used the file ardour_bw.svg.

That was one of the ones I tried in my comparisons, too. There are a couple of minor discrepancies that will need to cleaned up before we can merge this (see screenshots below for examples, with your version in red).

> I'm not sure of what icon to use.

As they're all from an official source, it's fine to use any of them. My first preference would be to `ardour_bw.ai`, followed by `ardour_bw.svg`.

> Maybe we need to ping Ardour developers.

Certainly can't hurt :+1: Pinging @pauldavisthefirst as the top contributor to that repo for feedback. If we don't hear back in a few days.

**Comment by thorwil** [comment]
Hi, I’m the creator of Ardour’s logo. There has been an update several years ago. The old version has irregular “teeth” and happens to be in the first image of this thread. The new version has evenly spaced “teeth”. Since I never had commit access, as it would have been silly for one file here, one file there, and since years have passed, I don’t know what is what in there, except that all originals are SVG created with Inkscape.

[ardour_for_simple-icons.zip](https://github.com/simple-icons/simple-icons/files/4494557/ardour_for_simple-icons.zip): current version, including low-resolution versions derived from the original Tango-themed icon set.

**Comment by mondeja** [comment]
Thanks @thorwil. I will update the logo soon.

**Comment by mondeja** [comment]
ardour-preview

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to reply and provide us with that file, @thorwil - we very much appreciate it.

The height of your SVG is a little off, @mondeja (`20.933` vs. the expected `20.787`), leading to the sort of differences seen below, with your version in red. With a vector of the newest logo seemingly not being available anywhere I'm not sure about the source URL but I think what you've used is a good compromise; hopefully by the time they next update their logo, that repo will be up to date.

**Comment by mondeja** [comment]
Resized to `20.787`. Let me know if you catch another inconvenient.

**Comment by PeterShaggyNoble** [comment]
You've gone the other way now, @mondeja - this is now coming in at only `23.832` in width.

**Comment by PeterShaggyNoble** [comment]
Took me a second to realise that you based your latest version on the more simplified second icon in the provided zip! 🤦‍♂️ Yours lines up perfectly with that and, for our purposes, I'm OK with using that second icon.

I'll let @thorwil have the final, official say, though; if they give the :+1: on us using the second icon over the first then this is ready to merge.

**Comment by thorwil** [comment]
That version is really only meant for 48px and maybe below. For anything larger, 
[ardour.zip](https://github.com/simple-icons/simple-icons/files/4540124/ardour.zip) would be better. So it depends on what kind of use you expect.

**Comment by PeterShaggyNoble** [comment]
As our native size is `24*24`, I think that suits us perfectly, so.

Thanks for your efforts on this one, @mondeja and for your valuable inpu & feedback, @thorwil.

**Pull request merged**
