### PR TITLE
Sony icon

### PR DESCRIPTION
**Pull request by adsingh14**
**Issue:** #6340
**Alexa rank:** 1,797
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

sony

### CODE REVIEW

**Comment by dirien** [comment]
hi @adsingh14, i think there is already a PR for the sony icon -> #6745?

**Comment by adsingh14** [comment]
> hi @adsingh14, i think there is already a PR for the sony icon -> #6745?

That's a **ghost** and abandoned PR though. I created this icon from a scratch via issue #6744 resources.

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @adsingh14,

thanks for contributing. can you check the letter S again. There is an sligth issue. 

Maybe export the svg with a precision of 4 please?

image
image

**Comment by adsingh14** [comment]
> Maybe export the svg with a precision of 4 please?

I set precision value to 4 and tried up to 6. Getting same results after 4.

image

**Review by dirien — APPROVED** [review]
Looks much better know

image

**Pull request merged**
