### PR TITLE
Add Dark Reader

### LINKED ISSUE #3339: Request: Dark Reader Icon
**Name:** Dark Reader
**Website:** https://darkreader.org/
**Alexa rank:** 37,964

**Official resources for icon**
https://github.com/darkreader/darkreader-design
https://github.com/darkreader/darkreader.github.io/blob/master/images/darkreader-icon-256x256.png
https://github.com/darkreader/darkreader.github.io/blob/master/images/darkreader-icon.svg

**Colors:**
Colors can be found here: https://github.com/darkreader/darkreader-design/blob/master/mascot/darkreader-mascot.ink
Primary:`rgb(20,30,36)`, Secondary: `rgb(47,116,133)`, Tertiary: `rgb(233,108,76)`.

**I have no affiliation with Dark Reader.**

### PR DESCRIPTION
**Pull request by adamalston**
Dark Reader

**Issue:** Closes #3339
**Alexa rank:** [~38.6k](https://www.alexa.com/siteinfo/darkreader.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon's creator: @NovaGL

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for your efforts on this one @adamalston & @NovaGL :+1:

Personally, I'm not _entirely_ sold on this treatment but, after a few attempts myself, I couldn't come up with anything much better. So let's first of all ping @alexanderby, who is the main contributor to @darkreader's design repo, for their feedback to see if they're OK with this treatment or if they could provide us with an official monochrome version.

If we do run with this version then the source URL will need to be updated to the latest commit: https://github.com/darkreader/darkreader.github.io/blob/48138dccd26eaffc2ffc851d7f728db8f49cd4a8/images/darkreader-icon.svg

**Comment by adamalston** [comment]
I think it may be worth pinging @Gusted, another main contributor to the project.

**Comment by alexanderby** [comment]
Could you please explain what is this?

**Comment by alexanderby** [comment]
Our icon is colored. Do you need b/w?

**Comment by alexanderby** [comment]
Try this one
```svg
<svg xmlns="http://www.w3.org/2000/svg" role="img" viewBox="0 0 24 24">
  <title>Dark Reader icon</title>
  <path d="M18.281 8.572c-.18-1.671-.926-3.132-2.105-4.173A6.315 6.315 0 0012 2.824c-1.538 0-3.026.56-4.176 1.575C6.646 5.44 5.9 6.901 5.72 8.572a4.968 4.968 0 01.987-.101 4.587 4.587 0 014.24 2.827l2.107-.002a4.57 4.57 0 014.241-2.825 4.88 4.88 0 01.987.101zM3.624 16.494l-2.212 6.094H0l2.662-7.324a4.621 4.621 0 01-.401-1.046 4.803 4.803 0 01-.143-1.16 4.7 4.7 0 01.574-2.283 4.43 4.43 0 011.576-1.642c.08-2.207.943-4.178 2.43-5.593A7.7 7.7 0 0112 1.412c1.973 0 3.876.768 5.305 2.13 1.486 1.417 2.348 3.388 2.427 5.596a4.42 4.42 0 011.576 1.64c.383.693.576 1.478.574 2.28 0 .39-.047.78-.142 1.159-.091.362-.225.713-.402 1.045L24 22.588h-1.412l-2.212-6.097c-.41.367-.879.649-1.383.843a4.653 4.653 0 01-1.699.313 4.635 4.635 0 01-3.132-1.227c-.827-.765-1.344-1.814-1.443-3.008H11.28c-.103 1.192-.62 2.241-1.447 3.005a4.637 4.637 0 01-3.128 1.23 4.644 4.644 0 01-1.698-.31 4.514 4.514 0 01-1.384-.843zm11.2-3.445a2.462 2.462 0 002.489 2.48 2.47 2.47 0 00-.019-4.94 2.464 2.464 0 00-2.47 2.46zm-10.589.01a2.463 2.463 0 002.47 2.47 2.469 2.469 0 002.472-2.47 2.469 2.469 0 00-2.471-2.47 2.463 2.463 0 00-2.47 2.47zm5.647 6c.033-.423.327-.703.706-.706a.681.681 0 01.706.706v2.823a.681.681 0 01-.706.706c-.38-.003-.673-.283-.706-.706V19.06zm2.824 0c.033-.423.326-.703.706-.706a.681.681 0 01.706.706v2.823a.681.681 0 01-.706.706c-.38-.003-.673-.283-.706-.706V19.06zm2.823 1.412c.033-.423.327-.703.706-.706a.681.681 0 01.706.706v1.411a.681.681 0 01-.706.706c-.38-.003-.673-.283-.706-.706v-1.411zm-8.47 0c.033-.423.326-.703.706-.706a.681.681 0 01.706.706v1.411a.681.681 0 01-.706.706c-.38-.003-.673-.283-.706-.706v-1.411z"/>
</svg>

```

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to reply, @alexanderby and, especially, to provide us with a monochrome version of your logo, it is much appreciated. While we have you, are you happy with the colour chosen to represent your brand here?

@adamalston, now that we have an official version, could you update the PR, please?

**Comment by PeterShaggyNoble** [comment]
We're good to go now. Thanks for your collaborative efforts on this one, @adamalston, @alexanderby & @NovaGL 👏

If the colour _does_ need to be changed, we can easily do that later.

**Comment by PeterShaggyNoble** [comment]
By the way, @adamalston, for future PRs, can you create a new branch from our `develop` branch instead of working directly on it?

**Comment by adamalston** [comment]
Yes.

**Pull request merged**
