### PR TITLE
Add Neutralinojs icon

### LINKED ISSUE #3336: Neutralinojs
**Name:** Neutralinojs
**Website:** https://neutralino.js.org
**Alexa rank:** https://www.alexa.com/siteinfo/neutralino.js.org
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by elliotwutingfeng**
image

**Issue:** closes #3336

**GitHub stars:** 6k

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Neutralinojs is a lightweight and portable desktop application development framework.

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
HI @elliotwutingfeng,

thanks for you contribution. I can see some differences:

image

**Comment by dirien** [comment]
Hi @elliotwutingfeng,

i still cans see some differences.

**Comment by elliotwutingfeng** [comment]
Is it a requirement for at least 2 edges of the 24x24 canvas to touch the logo? The original logo is not touching the edges of the canvas.

**Comment by dirien** [comment]
Hi, @elliotwutingfeng,

sorry forgot about that. But still there is a difference:

image

I removed the first child path from the group of the original svg. Maybe up the precision?

**Comment by LitoMore** [comment]
CleanShot 2022-09-13 at 20 40 59@2x

@elliotwutingfeng It's a perfect fit.

@dirien You need to convert all borders to outlines before you resize it.

**Pull request merged**
