### PR TITLE
Add Snyk icon

### PR DESCRIPTION
**Pull request by gabrieledarrigo**
**Issue: https://github.com/simple-icons/simple-icons/issues/1127**

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

Snyk SVG icon, grabbed from here:

[https://snyk.io/press-kit](https://snyk.io/press-kit)

For the primary logo's color, I choose #53537A, let me know if it's ok!

### CODE REVIEW

**Comment by davidklebanoff** [comment]
So I looked around a bit.

Their [website logo](https://snyk.io/wp-content/themes/snyk_v2_etyhadar/dist/images/svg/snyk-wordmark-fixed.svg) when you scroll has `#4c4a73` as the logo color.
The [support site logo](https://support.snyk.io/hubfs/logo-1.svg) has `#443EA0` as the logo color.
Their downloadable Brand Assets "Black" logo has `#091C30` as the logo color.

I'm in agreement with @ericcornelissen, I would go with `#4c4a73`. But it's clear that there is no official right answer.

**Comment by gabrieledarrigo** [comment]
Hi @davidklebanoff, @ericcornelissen,
I just updated the JSON with #4c4a73 value!

**Comment by ericcornelissen** [comment]
Thanks again for your work @gabrieledarrigo!

One thing for the future, I notice you force push updates rather then creating new commits and pushing them. Both approaches are acceptable, I just want you to know that we always [Squash and merge](https://blog.github.com/2016-04-01-squash-your-commits/) when a Pull Request adds an icon. So force pushing is not necessary.

**Comment by gabrieledarrigo** [comment]
Ok @ericcornelissen,
so no need to squash on "feature branch"?

**Comment by ericcornelissen** [comment]
Indeed @gabrieledarrigo, that is not necessary.

**Pull request merged**
