### PR TITLE
Add GitHub Sponsors

### PR DESCRIPTION
**Pull request by outsideris**
**Issue:** N/A
**Alexa rank:**
  

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
This is an icon for [GitHub Sponsors](https://github.com/sponsors). I know it is just a heart icon. But because GitHub Sponsors use the heart icon, it is useful if it is included in SimpleIcons, I think.
I made this icon and choose color base on [GitHub official buttons](https://buttons.github.io/).

### CODE REVIEW

**Comment by runxel** [comment]
Well, we're called "simple-icons" arent we 😅

**Comment by NovaGL** [comment]
I reject this icon as it is a mdi icon.
Or if I'm wrong it's very similar. 

I guess I need more convincing.

**Comment by outsideris** [comment]
I also worried about the same thing before I submit this.
I'm fine if you reject this icon. I will follow your project policy. 

Let me know if you want to proceed with this. If so, I will fix the failed build.

**Comment by runxel** [comment]
Let's ask @ericcornelissen this time for chiming in. He will decide the vote (: 
Thanks anyway for your work, dear @outsideris!

**Comment by ericcornelissen** [comment]
GitHub sponsoring feels less like a product to me than GitHub Actions, but I might be biased as I use Actions but not sponsoring.

With regards to "it being just a heart", if we consider it to be a brand that shouldn't be much of a problem, take e.g. the icon of Awesome Lists (sunglasses), Buy me a Coffee (throw-away cup), or, most-notably, DocuSign (in my opinion a download icon). In other words, a generic heart icon of would not be accepted, a brand that uses a heart as it's brand could be fine.

**Comment by llucax** [comment]
It it helps to the discussion, other services are using simpleicons to build on top of it, like https://shields.io, so not having support for a GitHub Sponsors simpleicon, means not having support for badges either. GitHub sponsors is a new funding platform, and I don't see why it shouldn't be supported, as the many other funding platforms, just because it is under the GitHub brand or because they chose to pick an icon that happens to be somehow "standard".

**Comment by llucax** [comment]
Also remember that simple icons includes the color too, which is part of the brand represented by the icon.

**Comment by ericcornelissen** [comment]
> It it helps to the discussion, other services are using simpleicons to build on top of it, like https://shields.io, [...]

Thanks for the input @llucax, we are aware that others build on-top of us, but this project's scope is limited to (popular) brands. One may want to include many different icons in shields, but we won't add them because of that.

> so not having support for a GitHub Sponsors simpleicon, means not having support for badges either.

Actually, you can include an encoded vector image in shields.io URLs if you want a custom image 😉 As an aside, having a badge for GitHub sponsers seems a bit weird to me as the GitHub UI provides a button for it (but that's not an argument against adding this icon).

**Comment by llucax** [comment]
> (popular) brands

So your point is GitHub Sponsors is not a popular brand then? How is popularity determined when comes to decide which brands to include?

**Comment by ericcornelissen** [comment]
> > this project's scope is limited to (popular) brands
> 
> So your point is GitHub Sponsors is not a popular brand then? 

I'm sorry for the confusion @llucax, I wasn't trying to say GitHub Sponsers is not popular. I was talking only about your argument about shields.io.

As a concrete example, some people may want a badge for the project license and have a license icon for that, that does not mean that simple-icons should add a license icon.


> How is popularity determined when comes to decide which brands to include?

As per the [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) we usually look at the Alexa ranking of the brand's website. However, as GitHub sponsers does not have its own domain that won't work. In this case we could use something like statistic about the number of GitHub users that donate.


That said, our main concerns is whether or not GitHub sponsers is a "brand" in its own right.

In the meantime, if you're looking for the GitHub sponsers logo in a shields.io badge: badge based on the URL:

```
https://img.shields.io/badge/foo-bar-green?logo=data:image/svg+xml;base64,PHN2ZyByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+R2l0SHViIFNwb25zb3JzIGljb248L3RpdGxlPjxwYXRoIGZpbGw9InJlZCIgZD0iTTYuMzUzIDMuMzY2Yy0xLjk5NyAwLTQuMTEgMS44MzYtNC4xMSA0LjczMiAwIDMuMzkgMi4zNjEgNi41MzYgNS4wMyA4Ljk2MmEzMC43NDMgMzIuNDM3IDAgMCAwIDQuNjg2IDMuNDg3IDMwLjczNyAzMi40MyAwIDAgMCA0LjY4Ny0zLjQ4N2MyLjY2OC0yLjQyNiA1LjAzLTUuNTcxIDUuMDMtOC45NjIgMC0yLjg5Ni0yLjExNC00LjczMi00LjExLTQuNzMyLTIuMDUzIDAtMy45MDEgMS41NTUtNC41MjkgMy44NzRhMS4xMjEgMS4xODMgMCAwIDEtMi4xNTYgMGMtLjYyNy0yLjMxOS0yLjQ3NS0zLjg3NC00LjUyOC0zLjg3NHptNS42MDYgMTguNTMzbC0uNTE2IDEuMDUtLjAwMy0uMDAxLS4wMDktLjAwNS0uMDI2LS4wMTZhMTEuNDI2IDEyLjA1NSAwIDAgMS0uNDY0LS4yNjggMzMgMzQuODE4IDAgMCAxLTUuMTMzLTMuODA3QzMuMDU4IDE2LjM0OCAwIDEyLjU5MiAwIDguMDk4IDAgMy44OTYgMy4xMTggMSA2LjM1MyAxYzIuMzEzIDAgNC4zNCAxLjI2NSA1LjYwNiAzLjE4NkMxMy4yMjUgMi4yNjUgMTUuMjUyIDEgMTcuNTY1IDFjMy4yMzUgMCA2LjM1MyAyLjg5NiA2LjM1MyA3LjA5OCAwIDQuNDk1LTMuMDU3IDguMjUtNS44MDcgMTAuNzU0YTMzLjAwNyAzNC44MjYgMCAwIDEtNS41OTcgNC4wNzVsLS4wMjcuMDE2LS4wMS4wMDVoLS4wMDJsLS41MTYtMS4wNXptMCAwbC41MTYgMS4wNWExLjEyNCAxLjE4NiAwIDAgMS0xLjAzMiAwbC41MTYtMS4wNXoiLz48L3N2Zz4=
```

Where you can modify the last part (after `image/svg+xml;`) by an [Base64 encoding](https://www.base64encode.org/) of the SVG you want to have on the badge. In the example badge I used the SVG in this PR with `fill="red"` on the `<path>` element:

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>GitHub Sponsors icon</title><path fill="red" d="M6.353 3.366c-1.997 0-4.11 1.836-4.11 4.732 0 3.39 2.361 6.536 5.03 8.962a30.743 32.437 0 0 0 4.686 3.487 30.737 32.43 0 0 0 4.687-3.487c2.668-2.426 5.03-5.571 5.03-8.962 0-2.896-2.114-4.732-4.11-4.732-2.053 0-3.901 1.555-4.529 3.874a1.121 1.183 0 0 1-2.156 0c-.627-2.319-2.475-3.874-4.528-3.874zm5.606 18.533l-.516 1.05-.003-.001-.009-.005-.026-.016a11.426 12.055 0 0 1-.464-.268 33 34.818 0 0 1-5.133-3.807C3.058 16.348 0 12.592 0 8.098 0 3.896 3.118 1 6.353 1c2.313 0 4.34 1.265 5.606 3.186C13.225 2.265 15.252 1 17.565 1c3.235 0 6.353 2.896 6.353 7.098 0 4.495-3.057 8.25-5.807 10.754a33.007 34.826 0 0 1-5.597 4.075l-.027.016-.01.005h-.002l-.516-1.05zm0 0l.516 1.05a1.124 1.186 0 0 1-1.032 0l.516-1.05z"/></svg>
```

**Comment by llucax** [comment]
Hi @ericcornelissen, I see you are touching on quite a few more general topics but I'm rather interested in if this icon will be included or not (thanks for the tip on how to include a custom icon with shields.io). So you can forget about me mentioning shields.io from now on, there is a workaround to use the icon there so all good.

So far I don't get if you think if adding the icon is appropriate or not, as the Alexa ranking seems to be somehow a soft rule, as GitHub Actions icon was already included, it doesn't feel like a strong argument to me. The guidelines you linked even say so "For anything else, popularity will be judged on a case-by-case basis.". So it seems there is no clear criteria here, it seems to be subject to someone making the call.

Again, personally I think GitHub Sponsors is big/popular enough to be worth including.

**Comment by ericcornelissen** [comment]
> So far I don't get if you think if adding the icon is appropriate or not, as the Alexa ranking seems to be somehow a soft rule, as GitHub Actions icon was already included, it doesn't feel like a strong argument to me. The guidelines you linked even say so "For anything else, popularity will be judged on a case-by-case basis.". So it seems there is no clear criteria here, it seems to be subject to someone making the call.
> 
> Again, personally I think GitHub Sponsors is big/popular enough to be worth including.

First off, let me say that we are very happy with your input! It is not often outsiders say things about PRs they did not make themselves.

Indeed, the Alexa rank is a soft rule. But, "popularity will be judged on a case-by-case basis" means that we still need to judge the popularity somehow. I wouldn't be surprised if GitHub has published usage numbers of GitHub Sponsers somewhere (so far I have just been too lazy to search for them). Admittedly, sometimes the maintainers make a judgement call that may not seem fair (such as GitHub Actions vs. GitHub Sponsers), though this PR has not yet been rejected!

In essence, to me, GitHub sponsers _feels_ more like a feature of GitHub and less like a product by GitHub. Whereas Github actions _feels_  more like a product by GitHub and less like a feature of GitHub. But, I can totally see why someone would disagree with that, which is why I think I would be fine with merging this PR.

I think one way to convince both me and @NovaGL more is to find an alternative for the logo we add. Though I think the current SVG makes sense, it feels more like "just the thing that's on the sponsoring button". This would, admittedly, make it somewhat recognizable for the brand. However, based on [GitHub's feature page](https://github.com/features) (scroll down to "community") and the [GitHub sponsers homepage](https://github.com/sponsors) I would maybe expect an Octocat holding a heart instead<sup>1</sup> :thinking: @runxel do you have any further opinion in this regard?

---

1. Suprisingly, that one actually is an SVG. See: https://github.githubassets.com/images/modules/site/sponsors/logo-mona-2.svg

**Comment by runxel** [comment]
@ericcornelissen
I'm not really having a preference here. The octocat with the heart is cute, and might be more "on brand", but also hard to make monochrome.

**Comment by llucax** [comment]
> Indeed, the Alexa rank is a soft rule. But, "popularity will be judged on a case-by-case basis" means that we still need to judge the popularity somehow. I wouldn't be surprised if GitHub has published usage numbers of GitHub Sponsers somewhere (so far I have just been too lazy to search for them). Admittedly, sometimes the maintainers make a judgement call that may not seem fair (such as GitHub Actions vs. GitHub Sponsers), though this PR has not yet been rejected!

On a quick search, I couldn't find any unfortunately. The best I can see as a sample of popularity is which high-profile open source projects are using it and how many supporters they have. Some examples I found:

* https://github.com/sponsors/Homebrew: 378
* https://github.com/sponsors/curl: 1

(not much, I know, but I couldn't even find an easy way to search for projects or organizations with Sponsors enabled, so I just hit refresh a couple of times here: https://github.com/sponsors/community)

There is also some services building up from it, like https://sponsorsyrup.com/.

> I think one way to convince both me and @NovaGL more is to find an alternative for the logo we add. Though I think the current SVG makes sense, it feels more like "just the thing that's on the sponsoring button". This would, admittedly, make it somewhat recognizable for the brand. However, based on [GitHub's feature page](https://github.com/features) (scroll down to "community") and the [GitHub sponsers homepage](https://github.com/sponsors) I would maybe expect an Octocat holding a heart instead1 thinking @runxel do you have any further opinion in this regard?

I don't agree with this to be honest, what you see everywhere where you want to use this "product" is the pink hart, not the cute octocat. I think nobody will identify GitHub Sponsors with that logo. Go to any GitHub repo or organization that has GitHub Sponsors enabled and you'll see the heart.

Examples:

Top of the page:
image

Sponsoring sidebar:
image

Sponsors explore page:
image


And about GitHub actions, for me is the exact opposite. I don't see GitHub Actions as a product (they have a section in the features page: https://github.com/features/actions as opposed to Sponsors that have a full dedicated page https://github.com/sponsors). Also to be honest I never seen the icon hosted in here for GitHub Actions 🤭 (what I have more identified with GitHub Actions is the "Play" button you see in the project's tab).

But anyway, I think I spent enough time with this, so I think I will drop it now, I think

**Comment by ericcornelissen** [comment]
I completely see where you are coming from @llucax, which is why I'm inclined to accept this PR. Thanks again for your input :smiley: @outsideris could you look into fixing the build errors?

And, for what it's worth, I would personally be opposed to using the play button for GitHub Actions. We have actually encountered brands in the past that mandate you use a version of the logo that few people would associate with the brand in the context of Simple Icons (e.g. brands mandating you use a text-based logo while they have an icon available). Though admittedly, GitHub doesn't seem to be mandating anything.


> [...] I couldn't even find an easy way to search for projects or organizations with Sponsors enabled [...]

That seems like an important feature to me, its a shame its missing.

**Comment by NovaGL** [comment]
I still don't see this as a brand the heart is like a star or a thumbs up but it's hard for me to assess further as I don't use the service.

**Comment by ericcornelissen** [comment]
@NovaGL, to be extra clear, do you think this isn't a brand because the icon is generic or because it is not a brand?

**Comment by NovaGL** [comment]
Both

**Comment by outsideris** [comment]
Ok, I will try to fix the build failure.

**Comment by outsideris** [comment]
I fixed lint errors.

**Comment by outsideris** [comment]
@ericcornelissen Could you check this?

**Comment by ericcornelissen** [comment]
Apologies @outsideris I forgot about this one, thanks for the ping 🙂 

The build looks good now, but I'm seeing some difference when I compare yours to an official version, as seen below. Specifically, I compared it to the SVG found in the "Sponsor" button on repositories (e.g. [Homebrew/brew](https://github.com/Homebrew/brew)). This might be due to the SVGO optimization process, you could try a higher precision. 

Could you look into this @outsideris? If you need help, feel free to ask here!

image

For the record, given that the vote is currently 2-to-1, with others also showing interest in this icon I think we should go ahead and merge this once it is ready 🙂

**Comment by outsideris** [comment]
@ericcornelissen Thanks. I will try to fix it ASAP.

**Comment by outsideris** [comment]
Fixed.

**Review by ericcornelissen — APPROVED** [review]

**Comment by ericcornelissen** [comment]
Looking good now, thank you very much for your work @outsideris 🎉

**Pull request merged**
