### PR TITLE
Remove Automatic

### PR DESCRIPTION
**Pull request by fbernhart**
automatic

**Issue:** #3169 
**Alexa rank:** -

### ~Checklist~
~- [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)~
~- [x] I optimized the icon with SVGO or SVGOMG~
~- [x] The SVG `viewbox` is `0 0 24 24`~

### ~Description~
~I took the already used SVG.~
~I used Inkscape to fix size and center~
~I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG~

### Edit

This PR is removing the Automatic icon as the brand no longer exists.

### CODE REVIEW

**Comment by adamrusted** [comment]
[Looks like Automatic no longer exists.](https://www.automatic.com/press)

**Comment by mondeja** [comment]
> Looks like Automatic no longer exists. @simple-icons/maintainers should this therefore be removed? I'm not familiar with the brand to know whether the products will still be in use.

You are right. Could you use this pull to remove the icon and mark this as breaking change for the next v5.0.0 milestone @fbernhart?

**Comment by fbernhart** [comment]
Done ⚰️

**Comment by PeterShaggyNoble** [comment]
@fbernhart, can you update the original post to clarify that this PR will remove the icon?

**Review by PeterShaggyNoble — APPROVED** [review]
Looks good to me 👍🏻 Once the conflicts have been resolved, this can be merged straight in.

**Pull request merged**
