### PR TITLE
Add wasmCloud icon

### LINKED ISSUE #7452: Request: wasmCloud Icon
### Brand Name

wasmCloud

### Website

https://wasmcloud.com

### Popularity Metric

The Similarweb rank is 11,191,630
https://www.similarweb.com/website/wasmcloud.com

While this is not within your metrics, wasmCloud is [CNCF project](https://landscape.cncf.io/card-mode?category=scheduling-orchestration&grouping=category&selected=wasm-cloud) amongst the likes of Kubernetes and Nomad.  The wasmCloud team was integral in putting together the CNCF's first Wasm Day and continues to be active members in the WebAssembly landscape

### Official Resources for Icon and Color

https://github.com/cncf/artwork/blob/master/examples/sandbox.md#wasmcloud-logos

### Additional Comments

wasmCloud has a large and active community that meets weekly via Zoom.  The project will only continue to grow.  Thank you!!!!

### Contributing

Yes

### PR DESCRIPTION
**Pull request by foo-dogsquared**
wasmcloud

**Issue:** closes #7452

**Similarweb rank:** ~6 million
  

GitHub stars is at ~600 stars which doesn't pass the metrics.

Per the comment from the issue:

> While this is not within your metrics, wasmCloud is [CNCF project](https://landscape.cncf.io/card-mode?category=scheduling-orchestration&grouping=category&selected=wasm-cloud) amongst the likes of Kubernetes and Nomad. The wasmCloud team was integral in putting together the CNCF's first Wasm Day and continues to be active members in the WebAssembly landscape

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Hex value was picked from the logo.

### CODE REVIEW

**Comment by brooksmtownsend** [comment]
@foo-dogsquared Just wanted to do a quick correction, the official wasmCloud hex color is `#00C389`

You can see our style guidelines at https://cosmonic.github.io/branding/wasmcloud. Thank you for this!

**Comment by foo-dogsquared** [comment]
Thank you @brooksmtownsend for the correction. Though, that's also my bad for not checking if wasmCloud has a brand guidelines. I quickly found [this repo containing brand guidelines for wasmCloud](https://github.com/wasmCloud/branding). Is the GitHub repo up-to-date? Or the one you linked is the more preferred page?

**Comment by foo-dogsquared** [comment]
Alright then, I chose the GitHub repo since it contains more complete guidelines and updated the PR with it. Thanks again @brooksmtownsend

**Comment by jordan-rash** [comment]
Thanks so much @foo-dogsquared!!!

**Pull request merged**
