### PR TITLE
Use icons from CDN

### PR DESCRIPTION
**Pull request by LitoMore**
Closes: #9085

I created a CDN service for Simple Icons, that supports colors and dark mode.

<h3>
  
  Simple Icons CDN usage
</h3>

```
GET https://si-cdn.vercel.app/:icon_slug/:color?/:dark_mode_color?
```

-  - https://cdn.simpleicons.org/simpleicons
-  - https://cdn.simpleicons.org/simpleicons/blue
-  - https://cdn.simpleicons.org/simpleicons/hotpink
-  - https://cdn.simpleicons.org/simpleicons/ff99cc
-  - https://cdn.simpleicons.org/simpleicons/f9c
-  - https://cdn.simpleicons.org/simpleicons/orange/blue (with dark mode color)

### Notes

According to [**Specifying the theme an image is shown to**](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to), we should use the `<picture>` method instead.~~

BTW, the `#gh-dark-mode-only` or `#gh-light-mode-only` only supports images hosted on GitHub.

```html
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://cdn.simpleicons.org/simpleicons/white">
  <source media="(prefers-color-scheme: light)" srcset="https://cdn.simpleicons.org/simpleicons">
  <img alt="Simple Icons" width=70 src="https://cdn.simpleicons.org/simpleicons">
</picture>
```

With Simple Icons CDN dark mode API, the `<picture>` tag can be changed to:

```
<img alt="Simple Icons" width=70 src="https://cdn.simpleicons.org/simpleicons/000/fff">
```

Simple Icons

@mondeja Current https://github.com/mondeja/strip-gh-theme-links does not support `<picture>`. We need to update that tool. I created an issue there: https://github.com/mondeja/strip-gh-theme-links/issues/22.

**Update:**\
We may need to add some logic to convert Simple Icons CDN dark mode links to single mode links.

For the Vercel usage, we can revert this PR if it increases too many loads at anytime.

### References

- Simple Icons CDN - https://github.com/LitoMore/simple-icons-cdn

### CODE REVIEW

**Comment by mondeja** [comment]
Are you sure that you've the infrastructure needed to process potentially millions of requests every day?

**Comment by LitoMore** [comment]
I just tested it. It will not consume bandwidth when it hits the cache.

FYI:

- https://vercel.com/guides/do-vercel-serverless-functions-increase-bandwidth-usage
- https://vercel.com/guides/lower-usage#serverless-function-usage

**Review by mondeja — COMMENTED** [review]
I'm not convinced about some icons, like the Python one:

image

The Python logo have two colors, blue and yellow, not one. It looks really bad, and probably we would be breaking [their guidelines](https://www.python.org/community/logos/):

> In general, we want the logo to be used as widely as possible to indicate use of Python or suitability for Python. However, please [ask first](mailto:psf-trademarks@python.org) when using a derived version of the logo or when in doubt.

This is the reason why we hadn't used a monocrome color version stored the *assets/* folder at first. Couldn't the server optionally serve each subpath (paths within `Mm-Zz`) in one color? Like passing an array of colors and breaking each subpath in their own `path` tag. That would be the solution.

**Comment by LitoMore** [comment]
For the python.svg, there are four subpaths in it. How can I separate the original path into two?

```shell
# subpath 1
M14.25.18l.9.2.73.26.59.3.45.32.34.34.25.34.16.33.1.3.04.26.02.2-.01.13V8.5l-.05.63-.13.55-.21.46-.26.38-.3.31-.33.25-.35.19-.35.14-.33.1-.3.07-.26.04-.21.02H8.77l-.69.05-.59.14-.5.22-.41.27-.33.32-.27.35-.2.36-.15.37-.1.35-.07.32-.04.27-.02.21v3.06H3.17l-.21-.03-.28-.07-.32-.12-.35-.18-.36-.26-.36-.36-.35-.46-.32-.59-.28-.73-.21-.88-.14-1.05-.05-1.23.06-1.22.16-1.04.24-.87.32-.71.36-.57.4-.44.42-.33.42-.24.4-.16.36-.1.32-.05.24-.01h.16l.06.01h8.16v-.83H6.18l-.01-2.75-.02-.37.05-.34.11-.31.17-.28.25-.26.31-.23.38-.2.44-.18.51-.15.58-.12.64-.1.71-.06.77-.04.84-.02 1.27.05z

# subpath 2
m-6.3 1.98l-.23.33-.08.41.08.41.23.34.33.22.41.09.41-.09.33-.22.23-.34.08-.41-.08-.41-.23-.33-.33-.22-.41-.09-.41.09z

# subpath 3
m13.09 3.95l.28.06.32.12.35.18.36.27.36.35.35.47.32.59.28.73.21.88.14 1.04.05 1.23-.06 1.23-.16 1.04-.24.86-.32.71-.36.57-.4.45-.42.33-.42.24-.4.16-.36.09-.32.05-.24.02-.16-.01h-8.22v.82h5.84l.01 2.76.02.36-.05.34-.11.31-.17.29-.25.25-.31.24-.38.2-.44.17-.51.15-.58.13-.64.09-.71.07-.77.04-.84.01-1.27-.04-1.07-.14-.9-.2-.73-.25-.59-.3-.45-.33-.34-.34-.25-.34-.16-.33-.1-.3-.04-.25-.02-.2.01-.13v-5.34l.05-.64.13-.54.21-.46.26-.38.3-.32.33-.24.35-.2.35-.14.33-.1.3-.06.26-.04.21-.02.13-.01h5.84l.69-.05.59-.14.5-.21.41-.28.33-.32.27-.35.2-.36.15-.36.1-.35.07-.32.04-.28.02-.21V6.07h2.09l.14.01z

# subpath 4
m-6.47 14.25l-.23.33-.08.41.08.41.23.33.33.23.41.08.41-.08.33-.23.23-.33.08-.41-.08-.41-.23-.33-.33-.23-.41-.08-.41.08z
```

**Comment by mondeja** [comment]
Interesting 🤔 Seems that the paths 2 and 4 are the circles and are cutting the geometry internallly, so some analysis about the geometry is needed to know if the paths are adding or substracting parts. So each most outter paths are converted into a `path` tag.

Also, it could be cases where the paths are cutting themselves as in infinite symbols. Maybe that should be linted, but I'm not sure if theses cases are easily solvable in vector graphic editors. If not we can just ignore them adjusting the array of colors as needed.

I know that this is not an easy task. Maybe we even need a SVG path debugger to help implementing it. It would be really great to separate it in a external library called `svg-path-geometry-splitter` or something like that.

**Comment by LitoMore** [comment]
@mondeja I just launched dark mode support for cdn.simpleicons.org.

See https://github.com/LitoMore/simple-icons-cdn/commit/b1527f5c6e4a431797d280db0d61189c81fb1d18.

We could update those links to https://cdn.simpleicons.org/simpleicons/000/fff to make our readme looks clean.

What do you think?

**Comment by adamrusted** [comment]
I would be all for replacing the existing icons in the readme with a simple `https://cdn.simpleicons.org/simpleicons/black/white` call. That way, we're not worrying about displaying brands in the wrong colour (it's still black or white, depending on the user).

**Comment by LitoMore** [comment]
Since we changed image links to Simple Icons CDN's auto-dark mode images, we may need to add some logic to strip the dark mode color from the link.

```diff
-https://cdn.simpleicons.org/simpleicons/000/fff
+https://cdn.simpleicons.org/simpleicons/000
```

For the Vercel usage, we can revert this PR if it increases too many loads at anytime.

**Comment by mondeja** [comment]
> @mondeja I just launched dark mode support for cdn.simpleicons.org.
>
> See https://github.com/LitoMore/simple-icons-cdn/commit/b1527f5c6e4a431797d280db0d61189c81fb1d18.
>
> We could update those links to https://cdn.simpleicons.org/simpleicons/000/fff to make our readme looks clean.
>
> What do you think?

Yes, it would be great because we wouldn't need the extension to strip dark theme image URLs before publising the packages.

**Review by mondeja — CHANGES_REQUESTED** [review]
Would you mind to remove the *assets/* directory? Also, [this test](https://github.com/simple-icons/simple-icons/blob/97962cce6822df5875286ea6213daf4b53fac650/tests/docs.test.js#L10) must be removed.

**Comment by LitoMore** [comment]
@mondeja We can remove that directory in the next major release since those files are still used on npm and other pages.

**Comment by mondeja** [comment]
> since those files are still used on npm and other pages

Not really, the `strip-gh-theme-action` is dropping the ``-white.svg`` links. You can check it with `cat node_modules/simple-icons/README.md | grep 'white.svg'` as doesn't show nothing. Also, are removed before releases so even READMEs of tags are not using them.

**Comment by LitoMore** [comment]
@mondeja Ah, you're right. Thanks!

Updated!

**Review by mondeja — APPROVED** [review]
Fantastic! Great work creating the CDN @LitoMore 🥇

**Pull request merged**
