### PR TITLE
Add Itch.io

### PR DESCRIPTION
**Pull request by schweller**
**Issue:** n/a

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The icon is from Itch.io's [official press kit](https://itch.io/press-kit). The color was extracted from the press kit SVG: `#000000`

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Looking at [the color palette in the press-kit](https://itch.io/press-kit#color-palette) I would expect the color to be `#fa5c5c` (note that the color should reflect the brand rather than the logo itself). 

Would you mind changing it or explain why you went with `#000000`? I'm not too familiar with itch.io so you might be able to convince me that's better 😉 

Also, I went ahead and quickly changed the `<path d="..."></path>` into `<path d="..."/>`. Other than that this is a great Pull Request!

**Comment by schweller** [comment]
@ericcornelissen The reason I did it is that when you download their press kit, SVG has a color `#000000`. That being said, I agree we should expect `#fa5c5c` and will make the change. Appreciate the feedback!

**Comment by ericcornelissen** [comment]
Thanks for working on this @schweller, and thanks for the response on the color. Your contribution is much appreciated! 🎉 

With this PR merged the icon will be available in the next version (which should be coming up rather quickly as there have been quite a few new icons since the [last release](https://github.com/simple-icons/simple-icons/pull/1305)) 😄

**Comment by metaa** [comment]
This introduced some ugly whitespace after the comma in the JSON file 😢

**Comment by ericcornelissen** [comment]
Oops :sweat_smile:

**Comment by davidklebanoff** [comment]
It's not a big deal, but we might as well take the opportunity to prevent it from happening again. I created issue #1324 to track it.

**Pull request merged**
