### PR TITLE
Add Prevention icon

### LINKED ISSUE #7888: Prevention Icon
### Brand Name

Prevention

### Website

https://www.prevention.com/

### Popularity Metric

The Similarweb Global rank is 7,997. See https://www.similarweb.com/website/prevention.com/#overview

### Official Resources for Icon and Color

svg: using svg-grabber from the official website
color: `#44C1C5`, from the official website

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
prevention

**Issue:** closes #7888 

**Similarweb rank:**
Global rank: 7,997 &nbsp; `https://www.similarweb.com/website/prevention.com/#overview` 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG logo is retrieved from: https://www.prevention.com/
The hex value is extracted from the official website

### CODE REVIEW

**Review by LitoMore — CHANGES_REQUESTED** [review]
See https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#icon-guidelines.

The `®` can be removed.

**Comment by Anmol-Baranwal** [comment]
@LitoMore 
As per contributing guidelines- `If there is ambiguity about the conditions under which the symbol is required, it must be included if it is a registered trademark symbol (®) but not if is a trademark symbol (™).`
- Can you please tell me how can I know whether the (®) should be included or excluded since here it is attached with the logo but there is no explicit requirement that a symbol must be included? Thus making it confusing.

**Comment by LitoMore** [comment]
@Anmol-Baranwal In my understanding, the `®` can be removed if it does not participate in the overall design.

**Review by LitoMore — APPROVED** [review]
CleanShot 2022-10-01 at 23 07 28@2x

@Anmol-Baranwal Perfect fit! Thanks!

**Comment by Anmol-Baranwal** [comment]
@LitoMore  please add the label `hacktoberfest-accepted` for this, and other PRs of mine to count as a contribution to Hacktoberfest 2022

**Comment by LitoMore** [comment]
@Anmol-Baranwal I have forwarded your request to our team.

**Pull request merged**
