### PR TITLE
Update: OpsLevel Logo

### LINKED ISSUE #9387: OpsLevel new logo
### Brand Name

OpsLevel

### Official Resources for Icon and Color

svg with primary logo mark: https://app.opslevel.com/OpsLevelLogoMark-Primary.svg
svg with white logo mark: https://app.opslevel.com/OpsLevelLogoMark-White.svg

### Additional Comments

We are changing our logo and this just launched today.

### Contributing

Yes

### PR DESCRIPTION
**Pull request by katerberg**
Preview:

opslevel

**Issue:** closes #9387

**Similarweb rank:** 1,036,735 (but hopefully this can be an exception since we have built tooling around the previous logo and it's been here for a while)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Updated to new branding colors and icon.

### CODE REVIEW

**Comment by adamrusted** [comment]
Thanks for this @katerberg!
Before I look at what is causing our linters to error, is there a popularity metric we can use outside the SimilarWeb rank?
At a glance I can't see any public repositories for the company, and unfortunately it falls outside the 750k 'keep once added' criteria - so in principal it should be removed.

It would also appear that when the icon was added, there were no popularity metric requirements. What do other @simple-icons/maintainers think in this situation?

**Comment by katerberg** [comment]
@adamrusted I think I fixed the linting errors (it's my first time with Inkscape, so I'm still learning :) )

For popularity, OpsLevel is one of the thought-leaders in the DevX space and is the pioneer of the Internal Developer Portal space. 

It is [10,788](https://www.crunchbase.com/search/organization.companies/field/organization.companies/rank_org_company/10788) on Crunchbase, [got quite a bit of noise as the space has gotten more occupied](https://techcrunch.com/2022/03/01/opslevel-raises-15m-to-help-developers-manage-their-microservices/?guccounter=1), and has [quite a few popular logos](https://www.opslevel.com/) that it's serving.

I'm biased since I work there, but it would be a shame to not be able to use simple-icons for some of our tooling (like Github Service Level badging) that we built with the assumption that contributing to this repo back in 2020 would have our logo.

**Comment by service-paradis** [comment]
In fact, the guidelines were more strict before #4735...
I think we can review and merge this PR with the updated logo. A new discussion about popularity might be needed between maintainers. No need to do it here on this PR.
This icon will probably get flagged in #9072 and some icons there are planned to be remove, so we might try to find a solution before V10.

**Comment by adamrusted** [comment]
> This icon will probably get flagged in #9072 

It will if you keep me away from the letter `O` review...

**Review by adamrusted — CHANGES_REQUESTED** [review]
I'm seeing a _slight_ inconsistency between the logo in the website header (blue) and the PR (black)...
image

Would you mind attempting to re-do this @katerberg?
I'm happy to share an SVG path if you'd prefer - but we'd need another maintainer to review it in then!

**Comment by katerberg** [comment]
@adamrusted I'll do it! I think the "simplify" button was my enemy from inkscape. I'll give it another go.

fwiw, I really appreciate the strict linting and review. It's helpful to get it right rather than have a sloppy/suboptimal thing merged.

**Comment by adamrusted** [comment]
> @adamrusted I'll do it! I think the "simplify" button was my enemy from inkscape. I'll give it another go.

Yeah, that'd do it. You should be able to just get away with a 'union' in Inkscape - and SVGO / SVGLint will tell you off if it's not optimal!

**Comment by katerberg** [comment]
Okay, I think I have it all good to go now @adamrusted!

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @katerberg 🚀

**Comment by katerberg** [comment]
Thanks for merging it! Not pressing at all, but just so I can tell stakeholders, how long is the release cycle for y'all?

I'm not sure when `develop` merges to production and it would be nice to tell folks if it'll be days, weeks, or months from now if there's a regular cadence.

**Comment by adamrusted** [comment]
So a release gets generated in the early hours of Sunday morning - and the icon will be available in that - assuming you're using simple-icons@latest

**Pull request merged**
