### PR TITLE
Add alteryx icon

### PR DESCRIPTION
**Pull request by dsmdavid**
**Issue:** 5469 https://github.com/simple-icons/simple-icons/issues/5469
**Alexa rank:** 26,320
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

image

Alteryx icon:
Press release kit: https://www.alteryx.com/company/news/press-kit which links to this google folder: https://drive.google.com/drive/folders/1WIxPiTucm9A97U5qJkZRdKoVOqA6Lv2W

Used the "EPS" "white logo" file in the press release kit to get the outline of the letters.
Hex color taken from the "Alteryx Blue" logo in the press release kit.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @dsmdavid and thanks for the contribution 🙂

Would you mind having another look at this, though, please? I'm seeing [quite a few differences](https://user-images.githubusercontent.com/15157491/115585900-f2289380-a2c3-11eb-8b86-84cc6dc5d687.png) between your version (in red) and the source EPS.

For the colour I'd expect, just from from their website, that it would be `#00263e`. Although if we do decide on the lighter blue, as seen in their favicon then I would suggest `#0082ca` from their website's stylesheet as picking colours from PNGs can occasionally produce inaccurate results.

Finally, I think just using https://www.alteryx.com/company/news/press-kit for the `source` and omitting the `guidelines` would be sufficient here as the press page doesn't provide any information on their branding or the use of their logo.

**Comment by dsmdavid** [comment]
Thank you, @PeterShaggyNoble 
I've changed the color to the  #0082ca you suggested based on their stylesheet. It's the closest to the predominant color in the software (although they may be in a process of rebranding that involves moving to a darker blue, but it has not made it to their software yet). I have been unable to find a "style guide" that specifies "their" color.
I've updated the svg. If this doesn't work, there's an svg available in wikimedia https://commons.wikimedia.org/wiki/File:Alteryx_logo.svg that maybe could be used instead?

Cheers!

**Comment by PeterShaggyNoble** [comment]
Thanks for updating, @dsmdavid.

However, the linter is now failing due to the dimensions being slightly off, the width is `24.003`. The is most likely, but not necessarily, due to the precision being too low during the optimisation process.

**Comment by adamrusted** [comment]
Hi @dsmdavid - just ran the linter on this newer version, and it's still getting similar errors about sizing (see https://github.com/simple-icons/simple-icons/pull/5499/checks?check_run_id=2485977990).
Rather than manually re-sizing the icon after the fact, you may be better to begin from the source file again and try a higher precision from the off. Perhaps a precision of 4 will fix the issues with this one?

**Comment by PeterShaggyNoble** [comment]
Are yo still working on this one, @dsmdavid?

**Comment by ericcornelissen** [comment]
Closing this as abandoned given almost 2 months without activity since the last comment.

Feel free to reopen if you want to continue working on this @dsmdavid. And to anyone else, feel free to use this Pull Request as a jumping off point if you want to work on this one 🙂

**Pull request closed without merging**
