### PR TITLE
Add Audiomack icon

### PR DESCRIPTION
**Pull request by aaya-audiomack**
**Issue:** Closes https://github.com/simple-icons/simple-icons/issues/2229

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Creative assets from Audiomack's CCO @purenine and the official [style guide](https://styleguide.audiomack.com/)

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for your work on this one, @aaya-audiomack. However, could you update the SVG to fill the full width of the canvas?

**Comment by aaya-audiomack** [comment]
Thanks for catching the error @PeterShaggyNoble. Does this look okay now?

**Comment by PeterShaggyNoble** [comment]
Thanks for the quick update, @aaya-audiomack, this looks good to me now but, as I'm on my phone, I'll leave it to one of the other @simple-icons/maintainers to review more thoroughly before merging.

**Comment by runxel** [comment]
Looks fantastic! Thank you for the PR @aaya-audiomack 👍

**Pull request merged**
