### PR TITLE
Add Alchemy Icon

### LINKED ISSUE #8055: Icon Request: Alchemy Web3
### Brand Name

Alchemy

### Website

https://www.alchemy.com/

### Popularity Metric

The Similarweb rank is 46,241
For reference - https://www.similarweb.com/website/alchemy.com/#overview

It is one of the most used and well-funded products in the web3 developer community.

### Official Resources for Icon and Color

Press kit - https://static.alchemyapi.io/assets/Alchemy-brand-assets.zip

svg: https://assets-global.website-files.com/5f973c970bea5548ad4287ef/6088f4c7c34ad61ab10cdf72_horizontal-logo-onecolor-neutral-alchemy.svg
color: `#0C0C0E`

### Additional Comments

Since it is a registered legal entity, the authenticity information should be available with the team. They can be contacted here - support@alchemy.com

### Contributing

Yes

### PR DESCRIPTION
**Pull request by zainabnazar**
**Preview**

alchemy

**Issue:** closes #8055

**Popularity Metric**
Alchemy ranks 41K in [similarweb](https://www.similarweb.com/website/alchemy.com/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- The color is #0C0C0E
- The source is: https://www.alchemy.com/

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @zainabnazar,

Thanks for the contribution! Could you use from the PressKit (https://static.alchemyapi.io/assets/Alchemy-brand-assets.zip) the Mark instead? It will be just the triangle without the word mark.

Thanks.

**Comment by zainabnazar** [comment]
Hi @dirien, 
I've done the required change. 
Thanks.

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @zainabnazar,

thanks for the rework, but can you check the icon again?

I see huge difference from the source you provided, when I remove the word "Alechemy"

image

**Comment by dirien** [comment]
Hi @zainabnazar,

thanks for the contribution!
image

**Pull request merged**
