### PR TITLE
Add The Conversation

### PR DESCRIPTION
**Pull request by davidjb**
theconversation

**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Color determined from the SVG logo at https://theconversation.com/au/republishing-guidelines. Speech bubble part of the logo was extracted, which is the icon used as the site's Favicon and focal point of other media (such as reports).

The Conversation ranks at 2246 on Alexa (https://www.alexa.com/siteinfo/theconversation.com) -- popular in the research and journalism sectors.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @davidjb :+1:

The SVG is coming in at `24.002` wide, which is usually down to the precision used when optimising the path. Could you fix that, please?

Personally, I'm not entirely sold that the orange is the correct choice for the colour. Looking through their website, it seems to be used as an accent colour rather than a primary colour. From their website, I'd expect the primary brand colour to be the grey used in the logo.

**Comment by davidjb** [comment]
@PeterShaggyNoble Updated the SVG and made sure the path is exactly 24.000 wide. Is there a command that could be run perhaps as part of the lint process to ensure width/height are okay?

As for the choice of colour, the grey is used a bit and but it doesn't feel like the primary branding colour with the reddish-orange (eg `#d8352a`) being the eye-catching and prominent colour used in on the site (logo, favicon, active links in navigation, [web app icons](https://cdn.theconversation.com/static/tc/@theconversation/ui/dist/logos/wide-ff7cd271a80cc1d23b31b20c0ac37865.png)) and most social media ([Facebook](https://www.facebook.com/pg/ConversationEDU/photos/?tab=album&album_id=390937124267255)).  That said, the grey turns up as the website footer and plain nav links and on their [YouTube](https://www.youtube.com/user/ConversationEDU/featured) as their icon so they might be moving that way...

The orange does turn up as a primary colour in their reports' diagrams, maps, headings, signage, etc (the 2017/2018 reports use it particularly heavily):

* https://cdn.theconversation.com/static_files/files/807/2019_Stakeholder_Report_The_Conversation.pdf  (the 2019 report _does_ use the grey in headings/text, but the use of the orange is a focal point of on the covering page and full-page map on page 10)
* https://cdn.theconversation.com/static_files/files/395/TCSR_2018singlepagesupdated.pdf
* https://cdn.theconversation.com/static_files/files/14/2017_Stakeholder_Report_The_Conversation.pdf

**Comment by ericcornelissen** [comment]
Regarding the color, I would agree that a reddish-orange is the brand color. The gray feels more like it is just used to contrast the white background of the website.

The icon looks good now 👍 I'll leave the final decision (given the color) to @PeterShaggyNoble or a third @simple-icons/maintainers.

---

> Is there a command that could be run perhaps as part of the lint process to ensure width/height are okay?

That would be awesome, I'm not aware of any tool that can do that for us out of the box, but it would certainly be useful!

**Comment by davidjb** [comment]
> That would be awesome, I'm not aware of any tool that can do that for us out of the box, but it would certainly be useful!

@ericcornelissen See what you think of #3107 😀

**Comment by PeterShaggyNoble** [comment]
At the time of my initial review, the orange was being used very little on their site but, given how prominent it is _now_, I'm happy to run with it. Thanks for your work on this one, @davidjb.

**Pull request merged**
