### PR TITLE
Add protractor icon

### LINKED ISSUE #5574: Protractor icon
**Brand Name: Protractor**
**Website: https://www.protractortest.org**
**Alexa rank:406,878** https://www.alexa.com/siteinfo/protractortest.org
  

**Official resources for icon:** https://github.com/angular/protractor/blob/master/website/img/favicon.ico
**color: e23237**

### PR DESCRIPTION
**Pull request by konradlu**
protractor

**Issue: Closes #5574**
**Alexa rank: 406,878** https://www.alexa.com/siteinfo/protractortest.org
  

### Checklist
  * [x] I updated the JSON data in `_data/simple-icons.json`
  * [x] I optimized the icon with SVGO or SVGOMG
  * [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon for Protractor - end-to-end test framework for Angular and AngularJS applications. https://www.protractortest.org

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @konradlu and thanks for the contribution 👍🏻 However, could you double check the SVG you included as it looks to be a work in progress file?

Also, could you update the source URL to https://github.com/angular/protractor/blob/df3dd6400e3a4792ff9f7a58849d2a5eed6e1483/logo.svg, please?

**Comment by konradlu** [comment]
I don't understand what's going on, the file is "in progress". This was my first time trying to edit .svg files. I edited the original file in IcoMoon and then resized to the correct size in Inkscape and pushed it. If I did something wrong, please direct me to the problem.

**Comment by adamrusted** [comment]
Thanks for the contribution @konradlu - I'm just taking a look at the linter output now, and it would appear that the majority of the issue it's having is with the use of groups and multiple paths within the icon. You should be able to Unify the paths in Inkscape using `Path > Union` (<kbd>Ctrl + +</kbd>) and Excluding the inner white area `Path > Exclude` (<kbd> Ctrl + ^</kbd>).

Any issues, give myself or @PeterShaggyNoble a shout on here, and we can try and help 👍

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @konradlu?

**Comment by wwwescape** [comment]
I hope it's okay that I gave it a try as well - #5999.

**Comment by PeterShaggyNoble** [comment]
Seeing as there has been no activity on this in over 2 months, I'm going to close it out in favour of @wwwescape's #5999.

**Pull request closed without merging**
