### PR TITLE
Add Payback icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** #6373 
**Alexa rank:** 12,600
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
From their website, https://www.payback.de/blueberry/static/ui-core/1.375.0/assets/logos/pb_logo--desktop.svg

I trimmed the logo down ony to the dots. As it is well know like this too.

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
So, this looks good to me, but I can't access the source (access denied).
Also, can you link to the page rather than to the file directly, if possible?

If you want me to check this one, feel free to copy the svg you used as source here so I can compare on inkscape.

**Comment by dirien** [comment]
@jorgeamadosoria here the svg

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="110px" height="40px" viewBox="0 0 110 40" version="1.1">
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="PB-Badge">
            <rect id="Background" fill="#0046AA" x="0" y="0" width="110" height="40" rx="5.01824818"/>
            <g id="Domino-Small" transform="translate(74.671533, 6.969388)" fill="#FFFFFF">
                <path d="M4.01459854,7.85969388 C6.17637005,7.85969388 7.92883212,6.12251302 7.92883212,3.97959184 C7.92883212,1.83667065 6.17637005,0.0994897959 4.01459854,0.0994897959 C1.85282703,0.0994897959 0.100364964,1.83667065 0.100364964,3.97959184 C0.100364964,6.12251302 1.85282703,7.85969388 4.01459854,7.85969388 Z M4.01459854,7.06377551 C5.73292974,7.06377551 7.12591241,5.68293945 7.12591241,3.97959184 C7.12591241,2.27624423 5.73292974,0.895408163 4.01459854,0.895408163 C2.29626734,0.895408163 0.903284672,2.27624423 0.903284672,3.97959184 C0.903284672,5.68293945 2.29626734,7.06377551 4.01459854,7.06377551 Z" id="Circle-1"/>
                <path d="M13.75,7.85969388 C15.9117715,7.85969388 17.6642336,6.12251302 17.6642336,3.97959184 C17.6642336,1.83667065 15.9117715,0.0994897959 13.75,0.0994897959 C11.5882285,0.0994897959 9.83576642,1.83667065 9.83576642,3.97959184 C9.83576642,6.12251302 11.5882285,7.85969388 13.75,7.85969388 Z M13.75,7.06377551 C15.4683312,7.06377551 16.8613139,5.68293945 16.8613139,3.97959184 C16.8613139,2.27624423 15.4683312,0.895408163 13.75,0.895408163 C12.0316688,0.895408163 10.6386861,2.27624423 10.6386861,3.97959184 C10.6386861,5.68293945 12.0316688,7.06377551 13.75,7.06377551 Z" id="Circle-2"/>
                <ellipse id="Circle-3" cx="23.4854015" cy="3.97959184" rx="3.91423358" ry="3.88010204"/>
                <path d="M4.01459854,17.5102041 C6.17637005,17.5102041 7.92883212,15.7730232 7.92883212,13.630102 C7.92883212,11.4871809 6.17637005,9.75 4.01459854,9.75 C1.85282703,9.75 0.100364964,11.4871809 0.100364964,13.630102 C0.100364964,15.7730232 1.85282703,17.5102041 4.01459854,17.5102041 Z M4.01459854,16.7142857 C5.73292974,16.7142857 7.12591241,15.3334496 7.12591241,13.630102 C7.12591241,11.9267544 5.73292974,10.5459184 4.01459854,10.5459184 C2.29626734,10.5459184 0.903284672,11.9267544 0.903284672,13.630102 C0.903284672,15.3334496 2.29626734,16.7142857 4.01459854,16.7142857 Z" id="Circle-4"/>
                <ellipse id="Circle-5" cx="13.75" cy="13.630102" rx="3.91423358" ry="3.88010204"/>
                <ellipse id="Circle-6" cx="23.4854015" cy="13.630102" rx="3.91423358" ry="3.88010204"/>
                <path d="M4.01459854,27.1607143 C6.17637005,27.1607143 7.92883212,25.4235334 7.92883212,23.2806122 C7.92883212,21.1376911 6.17637005,19.4005102 4.01459854,19.4005102 C1.85282703,19.4005102 0.100364964,21.1376911 0.100364964,23.2806122 C0.100364964,25.4235334 1.85282703,27.1607143 4.01459854,27.1607143 Z M4.01459854,26.3647959 C5.73292974,26.3647959 7.12591241,24.9839599 7.12591241,23.2806122 C7.12591241,21.5772646 5.73292974,20.1964286 4.01459854,20.1964286 C2.29626734,20.1964286 0.903284672,21.5772646 0.903284672,23.2806122 C0.903284672,24.9839599 2.29626734,26.3647959 4.01459854,26.3647959 Z" id="Circle-7"/>
                <path d="M13.75,27.1607143 C15.9117715,27.1607143 17.6642336,25.4235334 17.6642336,23.2806122 C17.6642336,21.1376911 15.9117715,19.4005102 13.75,19.4005102 C11.5882285,19.4005102 9.83576642,21.1376911 9.83576642,23.2806122 C9.83576642,25.4235334 11.5882285,27.1607143 13.75,27.1607143 Z M13.75,26.3647959 C15.4683312,26.3647959 16.8613139,24.9839599 16.8613139,23.2806122 C16.8613139,21.5772646 15.4683312,20.1964286 13.75,20.1964286 C12.0316688,20.1964286 10.6386861,21.5772646 10.6386861,23.2806122 C10.6386861,24.9839599 12.0316688,26.3647959 13.75,26.3647959 Z" id="Circle-8"/>
                <ellipse id="Circle-9" cx="23.4854015" cy="23.2806122" rx="3.91423358" ry="3.88010204"/>
            </g>
            <g id="PAYBACK-Small" transform="translate(6.423358, 11.844388)" fill="#FFFFFF">
                <path d="M2.91058394,5.57169372 C4.40719499,5.57169372 5.62043796,4.3689707 5.62043796,2.88533666 C5.62043796,1.40170262 4.40719499,0.198979592 2.91058394,0.198979592 C1.4139729,0.198979592 0.200729927,1.40170262 0.200729927,2.88533666 C0.200729927,4.3689707 1.4139729,5.57169372 2.91058394,5.57169372 Z M2.91058394,4.7755102 C3.96375468,4.7755102 4.81751825,3.92919133 4.81751825,2.88520408 C4.81751825,1.84121684 3.96375468,0.994897959 2.91058394,0.994897959 C1.85741321,0.994897959 1.00364964,1.84121684 1.00364964,2.88520408 C1.00364964,3.92919133 1.85741321,4.7755102 2.91058394,4.7755102 Z" id="Circle-1-Copy"/>
                <path d="M12.1682757,3.2196317 C12.1682757,3.87980757 11.8470231,4.21634196 11.0413539,4.21634196 L9.7342499,4.21634196 L9.7342499,2.26247925 L11.0794205,2.26247925 C11.8726994,2.26247925 12.1682757,2.64853415 12.1682757,3.2196317 L12.1682757,3.2196317 Z M14.4643659,3.18622733 C14.4643659,1.18064644 13.135467,0.43256433 11.1337588,0.43256433 L7.46129823,0.43256433 L7.46129823,8.73779947 L9.79112594,8.73779947 L9.79112594,6.04523131 L10.9764166,6.04523131 C13.0267904,6.04523131 14.4643659,5.2971492 14.4643659,3.18622733 L14.4643659,3.18622733 Z" id="Fill-15"/>
                <path d="M19.6831031,5.58064682 L17.4250795,5.58064682 L17.6785585,4.92721043 C18.165513,3.66136056 18.3783876,3.10637916 18.5533449,2.44092892 C18.7283021,3.10637916 18.9425203,3.64685603 19.4279819,4.92721043 L19.6831031,5.58064682 L19.6831031,5.58064682 Z M22.8603987,8.73779947 L19.7616248,0.43256433 L17.369547,0.43256433 L14.2721166,8.73779947 L16.6128419,8.73779947 L17.0765085,7.08735979 L20.0301813,7.08735979 L20.4939972,8.73779947 L22.8603987,8.73779947 L22.8603987,8.73779947 Z" id="Fill-16"/>
                <path d="M27.9343979,0.43256433 L27.2753225,1.69020962 C26.8252405,2.55667213 26.4589051,3.34870736 26.3017122,3.83438935 C26.2975324,3.82515919 26.2908147,3.81050815 26.2867841,3.80113148 C26.1225751,3.31266581 25.7645994,2.53953042 25.3225785,1.69020962 L24.6663395,0.43256433 L21.9322589,0.43256433 L25.0919394,5.67778322 L25.0919394,8.73779947 L27.4828231,8.73779947 L27.4828231,5.64320676 L30.6426528,0.43256433 L27.9343979,0.43256433" id="Fill-17"/>
                <path d="M36.762148,6.10237036 C36.762148,6.62555901 36.467766,7.00604652 35.8209316,7.00604652 L33.7662287,7.00604652 L33.7662287,5.22799629 L35.8358597,5.22799629 C36.4541814,5.22799629 36.762148,5.56877948 36.762148,6.10237036 L36.762148,6.10237036 Z M36.5544982,2.90155762 C36.5544982,3.33273773 36.3401307,3.61887254 35.7380807,3.61887254 L33.7799625,3.61887254 L33.7799625,2.18277759 L35.7380807,2.18277759 C36.3538646,2.18277759 36.5544982,2.49689589 36.5544982,2.90155762 L36.5544982,2.90155762 Z M38.9426947,6.05578006 C38.9426947,5.11899255 38.4911199,4.53866485 37.7235173,4.21912566 C38.2957111,3.8970958 38.7460917,3.49507126 38.7460917,2.59403229 C38.7460917,1.20320904 37.8808594,0.43256433 35.7585322,0.43256433 L31.6358403,0.43256433 L31.6358403,8.73779947 L35.7355429,8.73779947 C37.8808594,8.73779947 38.9426947,7.75412863 38.9426947,6.05578006 L38.9426947,6.05578006 Z" id="Fill-18"/>
                <path d="M44.9257813,5.58160789 L42.6686799,5.58160789 L42.9208625,4.92804951 C43.4052203,3.66196333 43.622166,3.10687832 43.797156,2.44130385 C43.9706528,3.10687832 44.1878971,3.64745609 44.6721056,4.92804951 L44.9257813,5.58160789 L44.9257813,5.58160789 Z M48.1036701,8.73934992 L45.0043177,0.43256433 L42.6131371,0.43256433 L39.5137847,8.73934992 L41.8576345,8.73934992 L42.3187001,7.08860214 L45.274268,7.08860214 L45.7381705,8.73934992 L48.1036701,8.73934992 L48.1036701,8.73934992 Z" id="Fill-19"/>
                <path d="M56.0073366,6.72049483 L54.0048286,5.68733785 C53.5398513,6.4701924 53.2234458,6.86425752 52.4790939,6.86425752 C51.453277,6.86425752 51.0396652,5.85381535 51.0396652,4.58501065 C51.0396652,3.26579376 51.4670143,2.30591034 52.4572934,2.30591034 C53.237183,2.30591034 53.5299963,2.7931794 53.8355016,3.56255162 L55.9826991,2.74511196 C55.3952808,1.17837704 54.5667134,0.299680695 52.4668498,0.299680695 C50.1715285,0.299680695 48.561429,1.91448306 48.561429,4.58501065 C48.561429,7.03996748 49.9151489,8.86653039 52.4572934,8.86653039 C54.4838417,8.86653039 55.4347008,7.81212409 56.0073366,6.72049483" id="Fill-20"/>
                <path d="M65.1005539,8.73779947 L62.2338638,3.364677 L64.8079431,0.43256433 L62.157576,0.43256433 L61.4078355,1.27499914 C60.823211,1.92990063 60.0419701,2.84837434 59.6393316,3.39925345 C59.6270898,3.41522309 59.6091748,3.43778569 59.5985751,3.45258324 C59.6229096,2.84837434 59.6364951,2.10424801 59.6364951,1.40803058 L59.6364951,0.43256433 L57.2197688,0.43256433 L57.2197688,8.73779947 L59.6364951,8.73779947 L59.6364951,6.23422972 L60.5426928,5.26535644 L60.5994235,5.20411509 L62.5603637,8.73779947 L65.1005539,8.73779947" id="Fill-21"/>
            </g>
        </g>
    </g>
</svg>
```

**Comment by jorgeamadosoria** [comment]
image

The proportions of the circles does not seem to correlate with the blue original.

**Comment by jorgeamadosoria** [comment]
this is my attempt, see if it is useful for you:

`m 6.159375,3.8812499 c -1.2970634,0 -2.3496095,1.0427626 -2.3496095,2.3285155 0,1.2857526 1.0525461,2.3273448 2.3496095,2.3273448 1.2970632,0 2.3484372,-1.0415922 2.3484378,-2.3273448 0,-1.2857529 -1.0513746,-2.3285153 -2.3484378,-2.3285155 z m 5.840625,0 c -1.297063,0 -2.3484372,1.0427626 -2.3484372,2.3285155 0,1.2857526 1.0513742,2.3273448 2.3484372,2.3273448 1.297063,0 2.348437,-1.0415922 2.348437,-2.3273448 0,-1.2857529 -1.051374,-2.3285155 -2.348437,-2.3285155 z m 5.841797,0 A 2.3485402,2.3280613 0 0 0 15.49336,6.2097654 2.3485402,2.3280613 0 0 0 17.841797,8.5371102 2.3485402,2.3280613 0 0 0 20.190235,6.2097654 2.3485402,2.3280613 0 0 0 17.841797,3.8812499 Z M 6.159375,4.359375 c 1.0309992,0 1.8667968,0.8283817 1.8667968,1.8503904 0,1.0220088 -0.8357976,1.850391 -1.8667968,1.850391 -1.0309994,0 -1.866797,-0.8283822 -1.866797,-1.850391 0,-1.0220087 0.8357976,-1.8503904 1.866797,-1.8503904 z m 5.840625,0 c 1.030999,0 1.866797,0.8283817 1.866797,1.8503904 0,1.0220088 -0.835798,1.850391 -1.866797,1.850391 -1.030999,0 -1.866797,-0.8283822 -1.866797,-1.850391 C 10.133203,5.1877567 10.969001,4.359375 12,4.359375 Z M 6.159375,9.6714846 c -1.2970634,0 -2.3496095,1.0427624 -2.3496095,2.3285154 0,1.285753 1.0525461,2.328515 2.3496095,2.328515 1.2970632,0 2.3484372,-1.042762 2.3484378,-2.328515 0,-1.285753 -1.0513746,-2.3285154 -2.3484378,-2.3285154 z m 5.840625,0 A 2.3485402,2.3280613 0 0 0 9.6515628,12 2.3485402,2.3280613 0 0 0 12,14.328515 2.3485402,2.3280613 0 0 0 14.348437,12 2.3485402,2.3280613 0 0 0 12,9.6714846 Z m 5.841797,0 A 2.3485402,2.3280613 0 0 0 15.49336,12 2.3485402,2.3280613 0 0 0 17.841797,14.328515 2.3485402,2.3280613 0 0 0 20.190235,12 2.3485402,2.3280613 0 0 0 17.841797,9.6714846 Z M 6.159375,10.14961 c 1.0309992,0 1.8667968,0.828381 1.8667968,1.85039 0,1.022008 -0.8357976,1.85039 -1.8667968,1.85039 -1.0309994,0 -1.866797,-0.828382 -1.866797,-1.85039 0,-1.022008 0.8357976,-1.85039 1.866797,-1.85039 z m 0,5.312109 c -1.2970634,0 -2.3496095,1.042763 -2.3496095,2.328516 0,1.285752 1.0525461,2.328515 2.3496095,2.328515 1.2970632,0 2.3484372,-1.042763 2.3484378,-2.328515 0,-1.285753 -1.0513746,-2.328516 -2.3484378,-2.328516 z m 5.840625,0 c -1.297063,0 -2.3484372,1.042763 -2.3484372,2.328516 0,1.285752 1.0513742,2.328515 2.3484372,2.328515 1.297063,0 2.348437,-1.042763 2.348437,-2.328515 0,-1.285753 -1.051374,-2.328516 -2.348437,-2.328516 z m 5.841797,0 a 2.3485402,2.3280613 0 0 0 -2.348437,2.328516 2.3485402,2.3280613 0 0 0 2.348437,2.328515 2.3485402,2.3280613 0 0 0 2.348438,-2.328515 2.3485402,2.3280613 0 0 0 -2.348438,-2.328516 z M 6.159375,15.939844 c 1.0309992,0 1.8667968,0.828382 1.8667968,1.850391 0,1.022008 -0.8357976,1.85039 -1.8667968,1.85039 -1.0309994,0 -1.866797,-0.828382 -1.866797,-1.85039 0,-1.022009 0.8357976,-1.850391 1.866797,-1.850391 z m 5.840625,0 c 1.030999,0 1.866797,0.828382 1.866797,1.850391 0,1.022008 -0.835798,1.85039 -1.866797,1.85039 -1.030999,0 -1.866797,-0.828382 -1.866797,-1.85039 0,-1.022009 0.835798,-1.850391 1.866797,-1.850391 z M 0,0 H 24 V 24 H 0 Z`

**Comment by dirien** [comment]
i drop this icon!

**Pull request closed without merging**
