### PR TITLE
Added lumX

### LINKED ISSUE #2511: LumX
**Name:** LumX
**Website:** https://ui.lumapps.com/
**Alexa Rank:** [~54k](https://ui.lumapps.com/)
**Colour:** `#303f9f` from the website header, or one of the colours from the logo?
**Official resources for icon and color:** https://github.com/lumapps/lumX-vscode-snippets/blob/master/images/lumx-logo.svg

Not sure what the best way to convert this to monochrome is. Just merge all 4 parts together? Or try something similar to what we did in MDI?

image

### PR DESCRIPTION
**Pull request by adamrusted**
lumx

**Issue:** Closes #2511
**Alexa rank:** [17,535](https://www.alexa.com/siteinfo/lumapps.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Used SVG found in GitHub repo. Yellow is CTA colour from website, and also seems to be primary colour of `lumapps`, unless @matmkian would like to suggest another?

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one one, @adamrusted. However, when compared with the original (your version in black), the cut-outs don't  seem to be entirely consistent; could you take another look? Also, what was your reasoning for selecting the yellow?

Separately, I was still relatively new to this project when I created the original issue and realise now that the Alexa Rank I quoted was for the parent domain, rather than the subdomain and with just 2k stars on GH & no commits or activity to speak of in over a year, I now question its suitability for inclusion in our library.

**Comment by adamrusted** [comment]
@PeterShaggyNoble think I picked the yellow based on the buttons on the website. Happy to sit on this one for a bit and see what other @simple-icons/maintainers think about it's inclusion, or lack thereof.

**Comment by adamrusted** [comment]
@PeterShaggyNoble I've just rebuilt this. To get the gaps looking okay, I've had to apply them all around the icon (including outside the shape - which is probably why it's not matching up properly. If you make that icon 0.5px smaller, and center it should match spot on.

**Comment by adamrusted** [comment]
Another potential treatment below, if that's preferred I can submit to this PR.

lumx
```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>LumX icon</title><path d="M3.786 12.379l-1.729-1.728 8.587-8.587 6.82 6.82-2.092 2.053-5.076-5.075-6.51 6.517zm6.51-5.809l-.009.009.009-.009zm3.406 11.612l-5.108-5.108-2.055 2.101 6.809 6.767v.001l8.594-8.594-1.704-1.704-6.536 6.537zm-2.057-2.764l2.057 2.057 8.241-8.241L12.709 0l-1.711 1.711 7.177 7.177-6.53 6.53zm.709-6.79l-2.057-2.057-8.24 8.24L11.291 24l1.704-1.704-7.176-7.129 6.535-6.539z"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
A month later and I'm more inclined now to say that this is outside our scope.

**Comment by service-paradis** [comment]
The rank above is for https://www.lumapps.com/
I'm not sure which metrics we can use to evaluate Lumx, but according to their Github ⭐(~2k) alone, it would be out of scope.

**Comment by PeterShaggyNoble** [comment]
> but according to their Github ⭐(~2k) alone, it would be out of scope

I agree and, with nothing else to go on, I think we're going to have to rule it out. Let's let @adamrusted make the final call on it, though, seeing as he's already put the work in on the PR.

**Comment by adamrusted** [comment]
Happy for us to mark this one out of scope :)

**Pull request closed without merging**
