### PR TITLE
Added unilever icon

### PR DESCRIPTION
**Pull request by KarthikNayak024**
**Issue:** #3497 
**Alexa rank:** 85,087
  

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by KarthikNayak024** [comment]
Is the icon I added is fine? Are there any changes that need to be done?

**Review by runxel — APPROVED** [review]
Thanks for your patience.
Nice work, thanks alot @KarthikNayak024! 👍

**Comment by KarthikNayak024** [comment]
When will this icon appear on the website?

**Comment by runxel** [comment]
Hey @KarthikNayak024, we do weekly updates to our `master` branch on the night of saturday/sunday.

**Pull request merged**
