### PR TITLE
Perplexity: New Icon

### LINKED ISSUE #10262: Request: Perplexity
### Brand Name

Perplexity

### Website

https://www.perplexity.ai/

### Popularity Metric

The Similarweb rank is 1,089. See https://www.similarweb.com/website/perplexity.ai/#overview

### Official Resources for Icon and Color

svg: https://commons.wikimedia.org/wiki/File:Perplexity_AI_logo.svg
color: `#20808D`

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by durgeshgowdac**
**Issue:** closes #10262

**Similarweb rank:**

Global Rank: 1,089
Link: https://www.similarweb.com/website/perplexity.ai/

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by durgeshgowdac** [comment]
@PeterShaggyNoble There's no conflict. You can review it and let me know if there's any changes needed. You can merge it.

Thank You,
@durgeshgowdac

**Comment by durgeshgowdac** [comment]
@PeterShaggyNoble Can I know How you compared the above svgs?

**Comment by PeterShaggyNoble** [comment]
Just overlaid all 3 in different colours.

**Comment by durgeshgowdac** [comment]
> Just overlaid all 3 in different colours.

I was asking which software you use. 
@PeterShaggyNoble Things aside, I've finished the requested changes. Please check if it satisfies all your requirements. 

- [x] I've changed the source and color in json.
- [x] I changed the svg to be based on the website instead of wikipedia.

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
I'm seeing [some minor differences](https://github.com/simple-icons/simple-icons/assets/15157491/2f40e15f-5fca-4a4b-ae82-05612cde2c45) now, @durgeshgowdac, with your version in red.

But, as Inkscape often doesn't play nice with `stroke`s, I'll ask one of the other @simple-icons/maintainers to have a look at it, too, before you make any changes.

**Review by PratyushJayachandran — COMMENTED** [review]
Upon fetching SVG from their website, I am only getting a path with no strokes. Am I missing something?
image

**Comment by PeterShaggyNoble** [comment]
@PratyushJayachandran, you'll need to grab the `stroke-width` from the CSS.

**Review by PratyushJayachandran — CHANGES_REQUESTED** [review]
First of all the source SVG is so misaligned. After aligning it, when comparing [I see a lot of differences!](https://github.com/simple-icons/simple-icons/assets/35000807/589bfbfa-fe07-45a6-9eac-7c201cdbccb0)
I found a better aligned SVG on the pop-up window on the website as shown here:
image

**Comment by adamrusted** [comment]
@durgeshgowdac - are you able to create using the SVG source @PratyushJayachandran discovered? I'll be able to review once that's merged in.

**Comment by durgeshgowdac** [comment]
@PeterShaggyNoble I've tried many times. Everytime, there is a marginal error. Can you assign it to someone else. 
Thank You

**Pull request closed without merging**
