### PR TITLE
Add JFrog Pipelines

### LINKED ISSUE #3445: Request: Shippable
**Name:** Shippable
**Website:** https://www.shippable.com/
**Alexa rank:** 558,253 (as of 13/8/2020)

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by adamrusted**
jfrogpipelines

**Issue:** closes #3445

**Similarweb rank:** [89,706](https://www.similarweb.com/website/jfrog.com/#overview) (for JFrog)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG available in the megamenu.

### CODE REVIEW

**Comment by LitoMore** [comment]
CleanShot 2022-09-20 at 16 32 34@2x

@adamrusted Could you provide the resource link? I use the resource from the [JFrog Media Kit](https://jfrog.com/brand-guidelines/) but have some difference.

**Comment by adamrusted** [comment]
@LitoMore - I used the icon from the 'megamenu' at the top of the page. If there's a proper media kit, I'll swap to that!

**Comment by LitoMore** [comment]
@adamrusted The media kit can be found here: https://drive.google.com/open?id=13n59MuOz84GPH1geugCa7xiQVybdvvFs

**Comment by adamrusted** [comment]
@LitoMore @dirien - interestingly, when coming back to this I'm getting the below error using PowerShell on Windows.
image

**Comment by LitoMore** [comment]
@adamrusted Yes. Some configurations have been changed. You can try with `rm -rf node_modules && npm i` to reinstall dependencies if you still encounter running errors.

**Comment by adamrusted** [comment]
@LitoMore as I added above, I hadn't rebased to development before making my changes, hence the issue. It was using old configs 🤦🏻‍♂️

**Comment by LitoMore** [comment]
@adamrusted Oh, I see. 🤦

**Review by LitoMore — APPROVED** [review]
image

Perfect!

**Pull request merged**
