### PR TITLE
Remove LinkedIn

### LINKED ISSUE #11372: Removal: LinkedIn
### Brand Name

LinkedIn

### Reason for Removal

Another Microsoft product. Besides, the brand guidelines say:

**LinkedIn generally does not permit its members, third party developers, partners and the media (“you”) to use its name, trademarks, logos, web pages, screenshots and other brand features.  Narrow and specific exceptions are detailed below.  Any other uses must obtain prior approval from LinkedIn.**

### PR DESCRIPTION
**Pull request by vanshaj-sharma**
Deleted LinkedIn, closes #11372

### CODE REVIEW

**Comment by adamrusted** [comment]
I've converted this to a draft so we don't accidentally merge ahead of our next major release - but all looks good on this one. If you wouldn't mind keeping the branch available - we'll merge this in October.

**Comment by vanshaj-sharma** [comment]
> I've converted this to a draft so we don't accidentally merge ahead of our next major release - but all looks good on this one. If you wouldn't mind keeping the branch available - we'll merge this in October.

sure no problem!

**Comment by adamrusted** [comment]
We tend to just keep the PRs as draft - so as to not have to maintain another development branch. Most of our release pipeline is automated, so only having the two key branches works best for us at the moment.

**Comment by LitoMore** [comment]
Alright, once again. Another earthquake to GitHub.

**Comment by HariSekhon** [comment]
Unless Microsoft / LinkedIn themselves is requesting the removal please leave this icon.

**Comment by markadrake** [comment]
[A troll can open a PR]([ILoveHDDark](https://github.com/ILoveHDDark)),
remove an icon everyone uses,
[quote a sentence from a much larger document](https://brand.linkedin.com/policies),
and now, all of a sudden, our LinkedIn icons don't work across 20 websites.

> image

On the very same page, 
if anyone spent even 5 seconds to research what this troll posted:

> image

This should be reversed.

https://github.com/simple-icons/simple-icons/issues/11372
https://github.com/simple-icons/simple-icons/pull/11395

**Comment by LitoMore** [comment]
@markadrake We can't. See:

**Comment by markadrake** [comment]
@LitoMore, with all due respect, consult a lawyer. As popular as this library is, I sincerely hope the funds for a simple consultation with a lawyer can be raised promptly.

I cannot find a legal precedent or law stating that storing a copy of a brand's logo for personal use is prohibited. The act of storing or possessing the logo, especially for non-commercial, private purposes, generally falls outside the scope of both copyright and trademark infringement unless there's an intent to use it in a way that violates these rights.

This use of this library is exclusively intended to be used _by others_, which means the 55k people and projects that download this each week are accountable for using the logos concerning copyright, trademarks, and brand guidelines. Even if you were granted a license today to add the logo to your library (ref: LinkedIn), that would not grant you a permissive license that can be transferred to everyone who downloads your library. 

The individuals using the logo from your library need to reach out if they intend to use it beyond the scope of said company's guidelines—not you. 

This conversation is ludicrous. 

[Do you think Adobe consulted Microsoft and got a permissive license granted to show the LinkedIn logo down at the bottom of their website?](https://www.adobe.com/about-adobe.html?promoid=XKMMH7MW&xProduct=&mv=other&mv2=ahome&xProductLocation=&cchClientLanguage=en&userLanguage=en&productLanguage=en)

image

I'll donate USD 400 to the cause. It should cover the initial one-hour consultation with any legitimate lawyer you seek out.

**Comment by LitoMore** [comment]
@markadrake Thanks. I just forwarded your comment to our maintainers. Let's see what they think about this.

**Comment by pboling** [comment]
If tech companies want to hire luddite lawyers who trip over their shadow, then we might as well enjoy the absurdity.Until 

So, until LinkedIn begins singing a different song, I'm replacing the blank space that used to be their logo with a better logo that deserves a shoutout:

```
newjapanprowrestling
```

[![Follow Me on LinkedIn][💖🖇linkedin-img]][💖🖇linkedin]

[💖🖇linkedin]: http://www.linkedin.com/in/peterboling
[💖🖇linkedin-img]: https://img.shields.io/badge/PeterBoling-LinkedIn-0B66C2?style=flat&logo=newjapanprowrestling

**Pull request merged**
