### PR TITLE
add Deutsche Bank

### PR DESCRIPTION
**Pull request by cyper85**
deutschebank

**Issue:**  #5025
**Alexa rank:** [#3862](https://www.alexa.com/siteinfo/deutsche-bank.de)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
International Bank, located in Germany

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @cyper85 👍🏻

Note, though, that there is an official SVG available in the header of [their website](https://www.db.com/), which is what we should base our version off.

```
<svg viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
   <path d="M4.5 4.5v23h23v-23h-23zM0 0h32v32H0V0zm7 24.3L19.2 7.7H25L12.8 24.3H7z"/>
</svg>
```

**Comment by adamrusted** [comment]
Given we've not heard from @cyper85 in over 2 weeks - I've updated the source and icon to match the file found by @PeterShaggyNoble.

**Comment by cyper85** [comment]
@adamrusted thanks for the update. I'm a little busy at the moment...

**Comment by adamrusted** [comment]
> @adamrusted thanks for the update. I'm a little busy at the moment...

No worries! Do you want me to leave your other PRs for you to look at at a later date?

**Comment by cyper85** [comment]
You've already successfully corrected the Sparkassen logo. I'll take another look at the Fraunhofer logo.

**Comment by fbernhart** [comment]
LGTM! 👍🏼  Thanks @cyper85  and @adamrusted  for working on this one. 🏆

**Pull request merged**
