### PR TITLE
Update Code Climate

### PR DESCRIPTION
**Pull request by mondeja**
image

**Issue:** #4590
**Alexa rank:** [~97K](https://www.alexa.com/siteinfo/codeclimate.com)

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Rebuilt from scratch using the SVG of the header of [their website](https://codeclimate.com/) (same source) fixing the mountain below because it has imperfect straight lines.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
There are a few icon sized versions without the imperfection available at https://codeclimate.com/github/codeclimate/python-test-reporter/badges/, @mondeja, could you update from one of those?

**Comment by mondeja** [comment]
Where @PeterShaggyNoble? I can't see one with straight lines in that page... :thinking:

**Comment by PeterShaggyNoble** [comment]
It's in [this badge](https://api.codeclimate.com/v1/badges/127e203095fa008649d1/maintainability), @mondeja.

**Review by adamrusted — CHANGES_REQUESTED** [review]
~Thanks @mondeja 💪 - though I'm seeing some [pretty severe differences](https://user-images.githubusercontent.com/1830867/110792155-f3998180-826a-11eb-864c-71d646fe44a0.png) between PR (red) and source (black) after removing the weird points in the left-hand shape of the source. Any chance you could take another look at it? 😅~

**Review by adamrusted — APPROVED** [review]
When I updated my source to the SVG badge you've updated the source to :roll_eyes: it matches up perfectly. Note to self, read the whole thread when reviewing an icon! 😆 

Thanks @mondeja for your work on this one 🚀

**Pull request merged**
