### PR TITLE
Add OBS Studio icon (#2000)

### LINKED ISSUE #2000: Open Broadcaster Software
**Name:** Open Broadcaster Software
**Website:** [obsproject.com](https://obsproject.com/) ([Alexa Rank ~9.9K](https://www.alexa.com/siteinfo/obsproject.com))
**Official resources for icon and color:**
- https://upload.wikimedia.org/wikipedia/commons/7/78/OBS.svg
- `#322F32`/`#000000`

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
Closes #2000

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The linked SVG version of the icon has `#302E31` as base color.
However on the website they use a small png logo which has a gradient instead of a single color fill.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @runxel looking at the .svg I'm not sure it matches the look of the logo or the wiki version as I would expect it to be simplified. The outer circle in the PR version is much thinner (see below).

obs-options

Code for the wiki version simplified as I would expect is below.

```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M12 0C5.38 0 0 5.38 0 12s5.38 12 12 12 12-5.38 12-12S18.62 0 12 0zm0 1.11c6.021 0 10.89 4.869 10.89 10.89 0 6.021-4.869 10.89-10.89 10.89A10.882 10.882 0 011.11 12C1.11 5.979 5.979 1.11 12 1.11zm-2.769.883c-1.547.767-2.698 2.299-3.05 3.996l.02.012c-.307 1.337-.084 2.766.527 3.997.384.035.767.065 1.148.133 1.199.253 2.302.963 3.002 1.97.937 1.278 1.148 3.05.591 4.54a4.912 4.912 0 01-3.024 2.934c-1.03.367-2.155.314-3.19.012 1.157.523 2.464.724 3.708.463 1.618-.307 3.108-1.326 3.932-2.755-.593-1.145-.755-2.523-.377-3.773.444-1.57 1.733-2.845 3.293-3.293a4.89 4.89 0 013.773.425c1.173.649 2.033 1.8 2.375 3.095-.029-.975-.45-1.912-.991-2.711-1.055-1.531-2.852-2.486-4.7-2.548-.863 1.531-2.583 2.547-4.348 2.468-2.276.032-4.377-1.793-4.732-4.028-.281-1.464.18-3.056 1.2-4.156.248-.298.574-.507.843-.78z"/></svg>
```

Can you update please.

**Comment by runxel** [comment]
Oh yes, thanks @phatbhoy67!
I know what happened. My mistake.
It's fixed now!

**Comment by runxel** [comment]
Oh yes, thanks @phatbhoy67!
I know what happened. My mistake.
It's fixed now!

**Comment by phatbhoy67** [comment]
Hey @runxel thanks for your work on this 👍

**Pull request merged**
