### PR TITLE
Added Kuaishou icon

### PR DESCRIPTION
**Pull request by torendo**
kuaishou

**Issue:** #6684
**Alexa rank:** 8589

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
svg is made by usage this svg: https://seeklogo.com/vector-logo/408699/kuaishou then checked over original png, source: https://www.kuaishou.com/official/material-lib
color: `#FF4906` , from official materials too
legal usage is allowed, see official disclaimer here: https://www.kuaishou.com/official/material-lib

### CODE REVIEW

**Comment by torendo** [comment]
Hi guys! Any chances this pr to be merged this weekend? :) Just kindly asking

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @torendo,

thanks for contributing, and the delay :(

I see a sligthly difference with the original logo:

image


I used as a comparison the svg from the  original site `https://s2-10623.kwimgs.com/udata/pkg/cloudcdn/img/footer_logo.30949f8d.svg``

Maybe experting the svg with a precision of 4 will fix it?

**Comment by torendo** [comment]
@dirien thanks! Used their svg. You have got an eagle eye =) I didn't manage to find svg on their website.

**Review by dirien — APPROVED** [review]
@torendo.

perfect fit! Many thanks! 🙏 😊 

image

**Pull request merged**
