### PR TITLE
lemmy icon

### PR DESCRIPTION
**Pull request by ghost**
lemmy

**Issue:** #6735
**Alexa rank:** 876,720 
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by service-paradis** [comment]
User @harjotlucky no longer exists (replaced by Github ghost). Closing this one since some changes would be needed.

**Comment by adsingh14** [comment]
@service-paradis Would you mind if I make some changes or re-create an `svg` ?

**Comment by jorgeamadosoria** [comment]
> @service-paradis Would you mind if I make some changes or re-create an `svg` ?

I wouldn't, @adsingh14. But I think it will be best if you create a separate PR and duplicate this one.
When you do, please assign me to review.

**Comment by adsingh14** [comment]
I wanted to know what changes he'd asked for it ?

**Comment by adsingh14** [comment]
> since some changes would be needed.

@jorgeamadosoria First, I wanted to know the changes ?

**Comment by jorgeamadosoria** [comment]
> > since some changes would be needed.
> 
> @jorgeamadosoria First, I wanted to know the changes ?

no one has reviewed this PR, so there are no requests for changes yet. We would need the PR to be reopened and assigned to you, or for you to duplicate this work in a different PR. If you do either of these things, I can review it and tell you if it need changes.

**Pull request closed without merging**
