### PR TITLE
Replace Colons & Multiple Accented Characters in Filenames

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
As seen in #2624, we don't currently handle colons in brand names when creating the filename. The change in this PR simply strips them out but, alternatively, we could replace them with hyphens instead.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Hadn't seen that issue, Eric. Would the better solution, I wonder, be to remove the line I modified in this PR and instead add a new `replace` to the end of the chain like so: `.replace(/[^\-\w]/g,"")`.

I also now notice that the replacement of accented accented letters isn't using a global RegEx; we should update that, too.

**Comment by ericcornelissen** [comment]
I'd say we merge this in as is* and proceed the discussion in #1531. Using `/[^\-\w]/g` is probably fine, but we might want to use similar solutions to `.Net` -> `dot-net` for other symbols as well...


>  also now notice that the replacement of ~~accented~~ accented letters isn't using a global RegEx; we should update that, too.

That, we should :+1: *Do you want to include that in this Pull Request?

**Comment by PeterShaggyNoble** [comment]
> Do you want to include that in this Pull Request?

Just pushed that update.

**Comment by ericcornelissen** [comment]
> Just pushed that update.

Okay, that is a simple change and can be merged without a problem.

I would like to have an extra pair of :eyes: from the @simple-icons/maintainers look at the change of **removing ":" (colons) from brand names**. Feedback from the community is also welcome! (@paulmelnikow perhaps?)

**Comment by PeterShaggyNoble** [comment]
Added a couple more replacements:

- Stripping out regular `'`s
- Replacing `š` with `s`

**Comment by runxel** [comment]
Added more common diacritics in 0fd4cdb
`č, ć, ň, ń, ś, ž, ź`

**Comment by paulmelnikow** [comment]
Pinging @chris48s, do you have any input on behalf of Shields?

**Comment by chris48s** [comment]
I don't see any issue with this for our usage :+1:

**Comment by PeterShaggyNoble** [comment]
Thanks, @paulmelnikow & @chris48s :+1: Merging this in, so.

**Pull request merged**
