### PR TITLE
Add CodeceptJS

### LINKED ISSUE #3388: Request: CodeceptJS Icon
**Name:** CodeceptJS
**Website:** https://codecept.io/
**Alexa rank:** [685166](https://www.alexa.com/siteinfo/codecept.io)
  

**Official resources for icon and color:**

https://codecept.io/logo.svg

### PR DESCRIPTION
**Pull request by vanessafsoares**
codeceptjs

**Issue:** Closes #3388
**Alexa rank:** [714.286](https://www.alexa.com/siteinfo/codecept.io)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Hex taken directly from the original SVG
- I got logo from Github and resized using Figma

Thanks to @PeterShaggyNoble for support!

### CODE REVIEW

**Comment by vanessafsoares** [comment]
@PeterShaggyNoble I'm having a small problem with the viewbox. When I manipulate the icon in illustrator or any other tool I set the viewbox value to `0 0 24 24` but whenever I export the svg and use the `npm run svglint` to check I see the message `"Size of <path> must be exactly 24 in one dimension; the size is currently 24,034 x 22,724"` realizing that the viewbox value was not as expected. How can I set this value in svg?

**Comment by NovaGL** [comment]
Thanks for this @vanessafsoares 
Can you please look at the svg file. Only one path is allowed.

Also changing the precision might help with the sizing

**Comment by vanessafsoares** [comment]
Hey

inkscape

It's been hours I'm trying to have it 24 wide. It looks goods in my AI file, I export the SVG's path, tried to resize SVG file using Inkscape but I still have the same error.

Captura de Tela 2020-08-05 às 18 34 03

Your script is working but for some reason, I can't make it 24 wide in the code, neither be centered.
I've no idea what more I can do.

**Comment by NovaGL** [comment]
Hi @vanessafsoares 

I opened this in Inkscape and I am still seeing multiple paths, which in turn will cause the centering to be wrong.
In Illustrator I make a compound path. But usually open in Inkscape after to fix the sizing as Illustrator is not very good with SVG sizing.

Hope that helps.

**Comment by vanessafsoares** [comment]
@NovaGL I finally make it 24 wide. Thank's for help  😁

**Comment by vanessafsoares** [comment]
@NovaGL is there anything else missing to aprove PR?

**Comment by NovaGL** [comment]
Hi @vanessafsoares,

We'll wait for one of the other maintainers to review it and get back to you.

**Comment by NovaGL** [comment]
Hi @vanessafsoares 

After an internal review and looking into the Alexa ranking. We're going to have to put this PR on hold. The criteria for adding icons is an Alexa ranking of less than 500K. I checked again and it's at 887,284 which is well beyond the scope of this project.

Don't let this dishearten you. If you find another metric that shows the popularity we can revisit it. Please feel free to re-open this PR at a later date

**Comment by runxel** [comment]
@simple-icons/maintainers 
Maybe we were a little harsh in closing this one off!
While yes, their Github Repo has "only" 3k of stars (which alone is not enough to our metrics sadly), but their [NPM](https://www.npmjs.com/package/codeceptjs) shows a steady weekly download rate of ~60k, which I think _should_ be a sufficient factor!
Cheers 🌴

**Comment by PeterShaggyNoble** [comment]
That seems to have tailed off recently, @runxel but that could easily be a seasonal thing. I suggest we monitor its NPM activity for the next few weeks to see which way it's trending and if there's an uptake again then we use this to set a cut-off for NPM downloads as a metric of popularity.

**Comment by fbernhart** [comment]
@PeterShaggyNoble The Alexa rank has increased up to [348,063](https://www.alexa.com/siteinfo/codecept.io) in the last few months. So this is now definitely within the scope of Simple Icons and can be added in my opinion (if the SVG matches the source). What do you think?

**Comment by PeterShaggyNoble** [comment]
Oh, in that case, @fbernhart, we can definitely reopen this one for further review.

**Comment by fbernhart** [comment]
@vanessafsoares Reviewing this icon, I can see quite some differences between your version (red) and [the source](https://codecept.io/logo.svg):

image

I'm as well not too sure about the best way to make this logo monochrome. In my opinion it would be better to keep the yellow circle, as it better matches [the original logo](https://codecept.io/logo.svg). I just gave it a try myself: I've separated the gray "moon" from the yellow circle with a gap (same width as the other gaps in the original logo).

codeceptjs

Any opinions on which version should be used @simple-icons/maintainers ?

**Comment by PeterShaggyNoble** [comment]
@fbernhart, see the discussion in [the original issue](https://github.com/simple-icons/simple-icons/issues/3388) relating to the treatment used here.

**Comment by fbernhart** [comment]
@PeterShaggyNoble Thanks! I should have looked at the issue.

**Comment by vanessafsoares** [comment]
@PeterShaggyNoble is there anything else missing to aprove?

**Comment by fbernhart** [comment]
@vanessafsoares Comparing your version (red) with the monochrome source (black) it seems like your SVG has been resized wrong. Would you like to give it another try? If not, I can as well quickly push an improved version. 😊 

image

And as we're using this as source: https://github.com/codeceptjs/codeceptjs.github.io/blob/c7917445b9a70a9daacf20986c403c3299f5c960/favicon/safari-pinned-tab.svg

I would be in favour of changing the `source` attribute in the `simple-icons.json` file to this link.

**Comment by vanessafsoares** [comment]
@fbernhart It's ok to push an improved version, go ahead 👍

**Comment by fbernhart** [comment]
@vanessafsoares Done. Should be fine now. 😊 

codeceptjs


Maybe @adamrusted could review and merge it. Quick note: The color is from [this SVG](https://codecept.io/logo.svg), the icon itself has been built from [this simplified monochrome version](https://github.com/codeceptjs/codeceptjs.github.io/blob/c7917445b9a70a9daacf20986c403c3299f5c960/favicon/safari-pinned-tab.svg). I couldn't make if pass the linter with a precision of 3, a precision of 4 was necessary.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @vanessafsoares and @fbernhart for your work on this! 🎉

**Pull request merged**
