### PR TITLE
Add VEGAS Pro icon

### LINKED ISSUE #7250: Request: Vegas Pro
### Brand Name

Vegas Pro

### Website

https://www.vegascreativesoftware.com/de/vegas-pro/

### Popularity Metric

https://www.similarweb.com/de/website/vegascreativesoftware.com/#overview

### Official Resources for Icon and Color

None

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by sh1n-afk**
**Issue:** closes #7250 

**Popularity metric:**
The website for VEGAS Pro ranks within the top 500k globally on SimilarWeb.

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

I selected the hex value #406aff based on its consistent use across the VEGAS Pro website and branding. 
The SVG was carefully adjusted to ensure it fits the required viewbox and adheres to the project's standards. 
The icon was sourced from Wikimedia Commons.

### CODE REVIEW

**Comment by sh1n-afk** [comment]
Thank you for considering my contribution! This is my first time contributing to open source, and I appreciate any feedback or suggestions to improve my submission.

**Review by LitoMore — CHANGES_REQUESTED** [review]
The icon you submitted is definitively different from the resource on https://commons.wikimedia.org/wiki/File:Vegas_Pro_21_logo.svg.

Can you check this?

**Comment by sh1n-afk** [comment]
Thank you for the feedback! I've updated the VEGAS Pro icon to match the official resource from Wikimedia Commons. Please let me know if any further adjustments are needed.

**Comment by uncenter** [comment]
See https://github.com/simple-icons/simple-icons/issues/7250#issuecomment-2351068810. @sh1n-afk would you be willing to [reach out and request permission](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission)?

**Review by uncenter — APPROVED** [review]
Color, source, title, and icon all look good though. I will tentatively approve this, still need that permission though.

**Comment by sh1n-afk** [comment]
I have reached out to the VEGAS Pro team to request permission for including their icon in Simple Icons. I will update once I receive a response.

**Comment by mondeja** [comment]
Have you received a response @sh1n-afk?

**Comment by sh1n-afk** [comment]
No response yet! I can reach out again with a follow up

**Comment by adamrusted** [comment]
@sh1n-afk - we've allowed 2mths for the brand to respond already, if you haven't heard back by now we're going to have to unfortunately close this PR. If you do hear back from them in the future, let us know here and we can re-open.

**Pull request closed without merging**
