### PR TITLE
add Grafana k6 icon

### LINKED ISSUE #7462: Request: k6
### Brand Name

k6 by Grafana Labs

### Website

https://k6.io

### Popularity Metric

https://github.com/grafana/k6
16.5K stars

### Official Resources for Icon and Color

https://commons.wikimedia.org/wiki/File:K6-logo.svg

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by mubeeum**
**Issue:** closes #7462 

**Similarweb rank:** 1,71,690

**Repo:** https://github.com/grafana/k6
16.5K stars

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with [SVGOMG Online Tool](https://jakearchibald.github.io/svgomg/)
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This icon is fetched from [Wikimedia](https://commons.wikimedia.org/wiki/File:K6-logo.svg). The HEX value #7D64FF is the official color used in the logo.

grafanak6

### CODE REVIEW

**Review by sisp — CHANGES_REQUESTED** [review]
Thanks for the update!

I still see the same difference between the original icon and your derived one. I've derived it myself (with Boxy SVG) and optimized the resulting SVG image it with SVGOMG, and now I get the following rather negligible difference:



I've added a code suggestion with the SVG path data, so feel free to review it and commit the change if you agree.

**Comment by mubeeum** [comment]
Thanks, @sisp the feedback.
I need to use a different tool for rendering the SVG within the correct viewBox. I will use Boxy SVG instead of other tools going forward.

**Comment by sisp** [comment]
I didn't mean to recommend Boxy SVG, it's just what I use. :slightly_smiling_face: By the way, at least in my workflow I use a high SVG path precision (6 decimal points) and let SVGOMG reduce the precision. This way, I've had fewer rounding issues which sometimes even lead to `svglint` errors.

**Review by sisp — APPROVED** [review]
LGTM now! :tada: Thanks for making the changes and your patience! :pray:

**Comment by mubeeum** [comment]
> I didn't mean to recommend Boxy SVG, it's just what I use. 🙂 By the way, at least in my workflow I use a high SVG path precision (6 decimal points) and let SVGOMG reduce the precision. This way, I've had fewer rounding issues which sometimes even lead to `svglint` errors.

Got it. Thanks for the information @sisp :)

**Pull request merged**
