### PR TITLE
Add KiCad Icon (#7516)

### LINKED ISSUE #7516: Request: KiCad
### Brand Name

KiCad

### Website

https://www.kicad.org/

### Popularity Metric

KiCad is the industry leading free and open source Printed Circuit Board design software. It is ubiquitous in the computer and electrical engineering space as an alternative to expensive Eagle or Altium proprietary software

### Official Resources for Icon and Color

https://www.kicad.org/about/kicad/
svg: https://www.kicad.org/img/about/kicad-logo.png
color: #314CB0 (Blue)

### Additional Comments

Variations of this icon include the entire word "KiCad" or just the square "Ki" portion. Both icons might be useful to have.
According to the website footer, this icon should be licensed under GNU GPL v3.

There is an existing issue from 2019 including KiCad in a list of icons to add, however no progress has been made since then. 
I recently wanted to use a KiCad icon from simple icons, but turns out it hasn't been added yet.
I am working making this addition, once I figure out how Inkscape works.

### Contributing

Yes

### PR DESCRIPTION
**Pull request by jack-mil**
**Issue:** closes #7516

**Similarweb rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Took the svg image from KiCad website and merged all paths into one. I had to figure out a hacky way to add gaps between the different colored elements when the image is converted to monochrome (black). Let me know if this looks alright. This is my first time editing SVGs. 
I suggested in #7516 that a alternative version of just the "Ki" square portion of the logo be added as well. Let me know if i should work on that. I think that version would look clearer in badges especially. 
The hex value comes from the main logo blue color.
kicad(2)

### CODE REVIEW

**Review by jack-mil — COMMENTED** [review]
Are the gap sizes correct between elements?

**Comment by jack-mil** [comment]
kicad(1)

**Review by sachinraja — CHANGES_REQUESTED** [review]
`kicad.svg` looks good! The gap is fine, we typically do 0.5px but there isn't enough space to work with here.

We don't do variants at the moment so could you remove `kicad_variant.svg` from this PR?

**Review by sachinraja — APPROVED** [review]

**Comment by jack-mil** [comment]
No problem, though personally I think the square icon will look nicer as a badge. 
I have reverted the commit with `kicad_variant.svg` and rebased on the current develop branch

**Comment by sachinraja** [comment]
Yeah it's unfortunate but we just don't have support for them right now. Some discussion in https://github.com/simple-icons/simple-icons/issues/6636

**Pull request merged**
