### PR TITLE
adding Sonatype icon

### PR DESCRIPTION
**Pull request by jorgeamadosoria**
sonatype

In response to:
**Issue:** https://github.com/simple-icons/simple-icons/issues/6170

### CODE REVIEW

**Comment by johannroux** [comment]
Very nice! Thanks for taking care of it. Maybe we don't need the name Sonatype under the logo, so that the hexagram takes all the place?

**Comment by jorgeamadosoria** [comment]
> Very nice! Thanks for taking care of it. Maybe we don't need the name Sonatype under the logo, so that the hexagram takes all the place?

Yes, I think so too, but the guidelines are very clear that the logo always include the text. I'm happy to remove it if the hexagon alone is accepted in the library, but since I'm new here I wanted to do this by the book

**Comment by service-paradis** [comment]
> By downloading our logos you agree not to change, edit, or manipulate them in any way.

According to the above sentence from their press kit, I tend to agree that we should probably keep the wordmark on this one.

**Comment by jorgeamadosoria** [comment]
> I think the icon should be unstacked (the hexagon and the wordmark are on the same line)

I don't understand what you mean.
You want to use the horizontal version of the logo?

**Comment by jorgeamadosoria** [comment]
> > You want to use the horizontal version of the logo?
> 
> yes, though that is just my preference. Not sure if a standard has already been set

no, there is no standard. I'm using this one because I think it would scale better since it's more square.
Tell you what, I'm going to process the horizontal variante and upload the preview so you can compare by yourself.
I don't really care about one over the other, so we'll go with the one you consider better.

**Comment by sachinraja** [comment]
Still not sure. I see your point on the scaling. @simple-icons/maintainers was a previous standard set for this?

**Comment by jorgeamadosoria** [comment]
> I would say for slightly better clarity on the text, we should use the vertically stacked version. Other than that, it'd be worth dropping their press email a line to see if there's _any_ way we can use just the icon - while linking to official guidelines they write. The favicon on their site is just the shape - and so they may allow us to use just the shape if guidelines are present?

that's true, but personally I would prefer to keep the wordmark. The icon alone is just... an hexagon. It would be contextless, I don't know. it lacks identity, in my opinion.

**Comment by adamrusted** [comment]
Apart from a couple of [incredibly minor](https://github.com/simple-icons/simple-icons/assets/1830867/d7ded504-80b8-4c79-b174-73ee5754191d) differences between the PR (black) and source (red) - I'm happy to merge the vertically stacked version currently in this PR. @jorgeamadosoria - would you mind taking another quick look at this, perhaps upping the decimals of the precision? We can close this one off then!

**Pull request closed without merging**
