### PR TITLE
Add Sublime Merge icon

### LINKED ISSUE #9727: Icon Request: Sublime Merge
### Brand Name

Sublime Merge

### Website

https://sublimemerge.com

### Popularity Metric

The Similarweb rank is 1,197,627. See https://www.similarweb.com/zh/website/sublimemerge.com/

Sublime Merge is an awesome Git GUI client, which can easily intergrated to VSCode and IDEA by plugins, and is officially intergrated to Sublime Text.

Moreover, it is a good tutor for git beginners, which shows git subcommand and arguments after each options. This helps beginners know what they are clicking, and can help users know what they are doing.

Other hightlights can be seen at <https://www.sublimemerge.com/>

### Official Resources for Icon and Color

svg: https://www.sublimehq.com/images/sublime_merge_stripe.svg

There are three colors:

background: `#4b4b4b`
arrow image: `#88d9d9` (upper part) and `#00e6e7` (lower part)

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by LitoMore**
CleanShot 2024-02-24 at 15 23 54@2x

**Issue:** closes #9727

**Similarweb rank:** [Compare sublimemerge.com, sublimetext.com, and sublimehq.com](https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=sublimemerge.com,sublimetext.com,sublimehq.com)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Sublime Merge is a popular Git client powered by Sublime HQ. This one may be able to use the popularity rank of Sublime Text as reference.

There are two shapes in the source image. I've combined them into one like our Sublime Text icon. Just make them consistent.

I picked color `#00E6E7` from the shape at the top as brand color.

### CODE REVIEW

**Comment by service-paradis** [comment]
Using Google Trends with Sublime Text that we have is not really convincing:
https://trends.google.com/trends/explore?q=%2Fm%2F0b6h18n,%2Fg%2F11t2v9bn8h

Using Google Trends with other Git client that we have is not really convincing either:
https://trends.google.com/trends/explore?q=%2Fg%2F11t2v9bn8h,%2Fg%2F11f4m3s1j2,%2Fg%2F11fll47g3k

**Comment by PeterShaggyNoble** [comment]
@LitoMore, is the website the only way to download Merge? Or is it available elsewhere that might have stats we can use to gauge its popularity? If it's _only_ available from the website then I think we'll have to say this is out of scope.

**Comment by adamrusted** [comment]
@LitoMore - please see above from @service-paradis and @PeterShaggyNoble. Are there other metrics we can use?

**Comment by LitoMore** [comment]
Closing due to I can't find any other popular metrics for this.

**Pull request closed without merging**
