### PR TITLE
Add StockX

### PR DESCRIPTION
**Pull request by diegobot1977**
stockx

**Issue:** #5946 
**Alexa rank:** 949

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I vectorized the StockX icon (logo), and just wrote in SVG-edit. The official brand color of StockX is `#006341`.

### CODE REVIEW

**Comment by StokicDusan** [comment]
Hi. The SVG no longer requires the word 'icon' in the `<title>` tag, so if you remove that, it should fix some of the issues you're having with the check.

**Comment by diegobot1977** [comment]
Alright. I'm still removing the `icon` because there is no icon word in this title. See the example:

`<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Simple Icons</title><path d="M12 12v-1.5c-2.484 0-4.5-2.016-4.5-4.5S9.516 1.5 12 1.5s4.5 2.016 4.5 4.5H18c0-3.312-2.688-6-6-6S6 2.688 6 6s2.688 6 6 6zM15.037 12.826c2.858 1.678 3.816 5.355 2.138 8.214h1.68c.423-.954.642-1.987.643-3.03.003-4.144-3.352-7.505-7.494-7.51V12c1.066 0 2.113.286 3.033.826zM12.003 10.5H12h.003M6.828 21.04C6.3 20.148 6 19.11 6 18v-.03H4.5V18c-.002 1.047.218 2.084.645 3.04h1.683zM15 22.5v-6h1.5V15h-9v1.5H9v6H4.5V24h15v-1.5H15zm-1.5 0h-3v-6h3v6zM9.078 5.922C9.035 7.58 10.343 8.957 12 9c1.597-.04 2.88-1.326 2.922-2.922C14.965 4.42 13.656 3.043 12 3c-1.597.04-2.88 1.326-2.922 2.922zm4.422.08c0 .828-.672 1.5-1.5 1.5-.83 0-1.5-.673-1.5-1.502 0-.83.67-1.5 1.5-1.5.828 0 1.5.672 1.5 1.5Z"/></svg>`

**Comment by StokicDusan** [comment]
maybe the example should be changed, I don't know.  
The issue #5478 discussed the change.

**Comment by adamrusted** [comment]
So the issue the linter is having is that there are two points in exactly the same spot (see the command l0,0). Without delving into the SVG code and editing it myself - you _may_ be able to just delete that one command and fix the linter errors, but without context I'm not sure.

**Comment by diegobot1977** [comment]
But actually...we tried to figure out what should I leave this `l0,0` command, but I just tried to update...

**Pull request closed without merging**
