### PR TITLE
Codewars logo

### PR DESCRIPTION
**Pull request by mudlabs-monster**
This is the Codewars SVG logo I made for a project the other day. You want it?

### CODE REVIEW

**Comment by davidklebanoff** [comment]
Issue #547.

**Comment by davidklebanoff** [comment]
Looks good to me! It will need to be run through [SVGO](https://github.com/svg/svgo) or [SVGOMG](https://jakearchibald.github.io/svgomg/) before it can be accepted. Lots of room for optimization/compression.

**Comment by birjolaxew** [comment]
As @davidklebanoff said, run this through SVGOMG and it's good to go. I really appreciate you taking the time to implement this, though!

**Comment by mudlabs-monster** [comment]
Actually I have already passed it through **SVGOMG**, got a 74% reduction. But that was my first time using the tool. Will give it another go.

**Comment by birjolaxew** [comment]
@mudlabs-monster Might want to lower the precision a bit then - usually 3-4 digits of precision is quite sufficient (unless you see visual degradation of the icon, of course).

**Comment by mudlabs-monster** [comment]
I've set the precision to 2, 1 was horrible at scale.

**Comment by davidklebanoff** [comment]
Thanks for the contribution!

**Comment by mudlabs-monster** [comment]
Yew!! Thanks for the opportunity. That's my first PR (🍒 picked)

**Pull request merged**
