### PR TITLE
Add Hive Blockchain

### LINKED ISSUE #2998: HIVE Blockchain
**Name:** HIVE
**Website:** https://hive.io/
**Official resources for icon and color:** https://hive.io/brand

### PR DESCRIPTION
**Pull request by selabie68**
Hive

**Issue:** Closes #2998

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Created using the brand assets form official site https://hive.io/brand/
Color located on the same page.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one on, @selabie68 :+1:

One small change, though: your path is coming in at `24.013` wide, rather than `24`.

We'll also need to figure out how best to avoid the name clash with our existing Hive icon, which is under discussion in #2260. Although the name you've chosen makes sense, changing a brand's name in this manner to avoid the clash doesn't sit well with me.

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @selabie68?

**Comment by selabie68** [comment]
@PeterShaggyNoble
Could you please advise on the desired naming convention sue to the conflicted name?

**Comment by PeterShaggyNoble** [comment]
You can leave the name as it currently is, @selabie68. When we get #2260 resolved, we will advise on the changes required to the brand and file names.

**Comment by PeterShaggyNoble** [comment]
With #2260 now resolved by #4918; we can _finally_ get this one merged in. I've made all the necessary changes to the JSON & SVG file but, as this is our first icon to use a custom slug, can one of the other @simple-icons/maintainers throw an eye over it to make sure all is correct.

**Comment by ericcornelissen** [comment]
All looks good to me @PeterShaggyNoble :+1: Could you merge `develop` into this branch just to be sure? (for some reason I wasn't able to push to this branch, even though you seem to be able to...)

**Comment by PeterShaggyNoble** [comment]
> Could you merge develop into this branch just to be sure?

That's done, @ericcornelissen

> perhaps we should hold off a little longer on merging this until #5002 is resolved?

I'm OK with merging it now; we're not going to have a huge amount of icons with `slug`s before that PR is merged so we should be able to field the small handful of questions we may get in the meantime about how to use them.

**Comment by ericcornelissen** [comment]
Fair enough, then with the build succeeding with `develop` merged in I will go ahead and merge this.

**Comment by ericcornelissen** [comment]
Thank you very much for your work on this one @selabie68 :tada: I'm glad we were finally able to merge it :smile:

**Pull request merged**
