### PR TITLE
Updated Read the Docs

### PR DESCRIPTION
**Pull request by fbernhart**
readthedocs

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
After play a bit with the source, I want to point that the treatment of current version in simple-icons is very poor. You can see in next comparison that the current version (black) has too much coordinates, which seems innecessary:

image

Also, it has some inconsistencies in the path. Check it:

image

So, I think that would be worth to rebuild from source. Also, the source must be changed to use https://github.com/readthedocs/readthedocs.org as the repository (currently pointing to old https://github.com/rtfd/readthedocs.org organization). What do you think @fbernhart?

**Comment by fbernhart** [comment]
readthedocs

@mondeja Done. The style is a bit different now, as the logo isn't "filled" anymore. But I think it is closer to the original logo, as the outline of the logo can be seen.

Or would you prefer a filled version?

**Comment by mondeja** [comment]
I'm afraid that this could break a lot of badges, since the ReadtheDocs icon is not well seen at small sizes using a non filled version... Could you try with a filled one?

### Before

image


### After

image

**Comment by fbernhart** [comment]
@mondeja You're right! Thanks for pointing this out.

I've updated it.

**Review by mondeja — APPROVED** [review]
Ouh yeah, really amazing job! :trophy:
Thank you so much @fbernhart!

**Pull request merged**
