### PR TITLE
Add Prisma

### PR DESCRIPTION
**Pull request by aadelgrossi**
prisma

**Issue:** n/a
**Alexa rank:** [#52,881](https://www.alexa.com/siteinfo/prisma.io)
**Github stars:** 8.2k [https://github.com/prisma/prisma](https://github.com/prisma)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon obtained from [prisma/presskit](https://github.com/prisma/presskit)
Hex value extracted from website palette (Charcoal 2F3747)

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~53.2k](https://www.alexa.com/siteinfo/prisma.io)

**Comment by aadelgrossi** [comment]
> **Alexa rank:** [~53.2k](https://www.alexa.com/siteinfo/prisma.io)

Thanks, I have added the rank to the info. :-D

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @aadelgrossi :+1:

Which source file did you base your version on? I'm seeing some hairline differences when comparing it to [this SVG](https://github.com/prisma/presskit/blob/master/Logos/Logo%20Black%20Symbol.svg). Also, for the colour, the closest colour I see in the CSS to the one you've chosen is `#2d3748`. Finally, as the source repo is a branding repo, could you update the source in the JSON to https://github.com/prisma/presskit?

**Comment by aadelgrossi** [comment]
> Thanks for the contribution, @aadelgrossi 
> 
> Which source file did you base your version on? I'm seeing some hairline differences when comparing it to [this SVG](https://github.com/prisma/presskit/blob/master/Logos/Logo%20Black%20Symbol.svg). Also, for the colour, the closest colour I see in the CSS to the one you've chosen is `#2d3748`. Finally, as the source repo is a branding repo, could you update the source in the JSON to https://github.com/prisma/presskit?

I did it based on that one, however I might have wrongly scaled it horizontally by a few pixels because I wasn't managing to get it centered correctly and the lint was failing. I redid it maintaining the original ratio (19.8749px by 24px) and managed to center it properly now. Feel free to check again if there are any differences. 

Color hex corrected to #2d3748 as suggested.

**Review by PeterShaggyNoble — APPROVED** [review]
Thanks for the quick update, @aadelgrossi, everything looks perfect to me now 👍🏻

Tried to get the precision down to 3 but couldn't either. I'm also not entirely convinced of the colour choice but as they don't really seem to have a clear cut preference for their brand colour I'm going to merge this in as-is and we can update it at a later date, if necessary.

**Comment by aadelgrossi** [comment]
> Thanks for the quick update, @aadelgrossi, everything looks perfect to me now 👍🏻
> 
> Tried to get the precision down to 3 but couldn't either. I'm also not entirely convinced of the colour choice but as they don't really seem to have a clear cut preference for their brand colour I'm going to merge this in as-is and we can update it at a later date, if necessary.

Lowering the precision to 3 apparently messes the centering or the icon size itself therefore the linting fails; I struggled immensely yesterday to find that was causing it. Since the precision threshold is 5, I hoped 4 would still be ok  for now. Thx for approving and merging!

**Pull request merged**
