### PR TITLE
Add Conan icon

### PR DESCRIPTION
**Pull request by tapia**
conan

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo of the [Conan project](https://conan.io/).

I'm a member of the Conan team, so I can speak on behalf of the brand in case of doubt.

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
@tapia thanks for the contribution! Do you happen to have an official assets / guideline page?

**Comment by jorgeamadosoria** [comment]
also, in your preview, why not include the vertical line in the box's face? Currently, the monochrome logo does not transmit the idea that it is a cube, since it has no vertices. I think the vertical line in the box face should be enough.

**Comment by tapia** [comment]
Hey, @jorgeamadosoria! I'm afraid we don't have any official guidelines. We're probably going to work on that in 2022, but there's nothing yet.

I updated the PR with the vertical line in the box. I didn't add it before because I think it clutters the logo in small sizes, but let me know what you think.

**Comment by jorgeamadosoria** [comment]
> Hey, @jorgeamadosoria! I'm afraid we don't have any official guidelines. We're probably going to work on that in 2022, but there's nothing yet.
> 
> I updated the PR with the vertical line in the box. I didn't add it before because I think it clutters the logo in small sizes, but let me know what you think.

I think it looks better and it is closer to the original logo, but far from me to dictate what you want to do with your own logo. If you feel the logo represents your brand better without the vertical line, you are the final arbiter of how you want it represented in our library. 
Feel free to keep the vertical line or remove it at your pleasure, we can add the icon either way. Your decision.

**Comment by tapia** [comment]
@jorgeamadosoria You can go ahead and merge the icon with the vertical line, as it's the official design. Thanks for the suggestion! :-)

**Pull request merged**
