### PR TITLE
Add Coinbase icon

### PR DESCRIPTION
**Pull request by el1f**
**Issue:** #1690 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Just followed the amazing issue.

### CODE REVIEW

**Comment by el1f** [comment]
Realized it's a duplicate. Sorry for the spam guys.

**Comment by PeterShaggyNoble** [comment]
@el1f, as #1695 was abandoned, would you like to pick this one up again?

**Comment by el1f** [comment]
Sure thing. It currently shows the C from Coinbase which may be deemed too similar to other logos that only feature the C. Should we make some changes to make them easier to distinguish?

**Comment by ericcornelissen** [comment]
> Sure thing. It currently shows the C from Coinbase which may be deemed too similar to other logos that only feature the C. Should we make some changes to make them easier to distinguish?

Apologies for the delay @el1f, as per the discussion in #1695 I think we would prefer the full wordmark. Could you update it?

**Comment by el1f** [comment]
Done :)

**Comment by phatbhoy67** [comment]
Hey @el1f thanks for taking this one on. 👍 

The .svg is great. 

Can you update the hex value in the .json file to use uppercase letters i.e. `"0667D0"` which should fix the failing check.

**Comment by el1f** [comment]
Done :)

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @el1f 👍

**Pull request merged**
