### PR TITLE
D-Wave Systems

### PR DESCRIPTION
**Pull request by eugena**
image

**Issue:**
**Alexa rank:** [315,504](https://www.alexa.com/siteinfo/dwavesys.com) ~788~

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
-

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for your work on this @eugena!

Just taking a quick look at the site, I'm not able to see a monochrome version of the logo in use. I've therefore converted the icon myself with an (inside) stroke of 0.5px on the blue circle, resulting in the black path below. With yours overlaid in red, there appear to be some differences, including the stroke on that blue circle. Would you mind taking another look at it?
image

If you're able to get the icon working with three decimals of precision as well, that'd be great!

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks @eugena, looking a lot better! 🎉
I am however seeing some differences, where it looks like your PR (red) has been stretched when compared to the original (black). It may just be from the optimization process, but would you mind taking another look?

image

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks again @eugena, though it appears the issues remain (see below, with your icon in red).

image

It's worth always comparing your version against the original before submitting - the version in black is pulled straight from the source SVG and scaled down to 24px tall. You can easily check it by saving your edited (and optimized) version separately, and then overlaying the original and your version in whatever software you're using. I use Figma for my overlays like the one above, and use a mix of Inkscape and Adobe Illustrator for the icons, depending on whether there's any specific things that the icon needs (sometimes Illustrator doesn't show all the paths, or imports strokes weird).

Feel free to give this another shot yourself, though I've included a path that works at 4 decimals of optimization if you're struggling. You're welcome to submit my path if that's easier.

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>D-Wave Systems icon</title><path d="M10.1062 12.0046c0 1.5815-1.2842 2.8636-2.8685 2.8636-1.5842 0-2.8684-1.282-2.8684-2.8636 0-1.5815 1.2842-2.8635 2.8684-2.8635 1.5843 0 2.8685 1.2821 2.8685 2.8635zM7.2377 0C5.6536 0 4.3693 1.2817 4.3693 2.8628s1.2842 2.8629 2.8684 2.8629c1.5842 0 2.8685-1.2817 2.8685-2.8629C10.1062 1.2817 8.822 0 7.2377 0zm9.5246 18.2781c-1.5838 0-2.8677 1.2764-2.8677 2.8636 0 1.5763 1.2835 2.8583 2.8677 2.8583 1.5845 0 2.8684-1.282 2.8684-2.8583 0-1.5872-1.2843-2.8636-2.8684-2.8636zm-2.8685-6.2735c0-1.5815 1.2842-2.8635 2.8685-2.8635 1.5842 0 2.8684 1.282 2.8684 2.8635 0 1.5815-1.2842 2.8636-2.8684 2.8636-1.5843 0-2.8685-1.282-2.8685-2.8636zm.5 0c0 1.3033 1.0625 2.3636 2.3685 2.3636s2.3684-1.0603 2.3684-2.3636c0-1.3032-1.0624-2.3635-2.3684-2.3635s-2.3685 1.0603-2.3685 2.3635z"/></svg>
```

**Comment by adamrusted** [comment]
Thanks for implementing changes @eugena, though now I'll need to ping another @simple-icons/maintainers to review this, being as I've helped with the path.

**Comment by PeterShaggyNoble** [comment]
SVG looks good to me. Although, as it's an original treatment, I'd like one of the other @simple-icons/maintainers to give it the OK, too.

I'm curious about the choice of colour, @eugena; I don't notice it in (prominent) use on their website. My instinct would have been to go with the `#008cd7` from their stylesheet or maybe even the `#5d87a1` from the logo.

**Review by adamrusted — APPROVED** [review]
Thanks for your work on this @eugena! 🥳
Given @PeterShaggyNoble already approved the SVG, and the hex has been updated - I'm merging this one.

**Pull request merged**
