### PR TITLE
Add Kubuntu

### PR DESCRIPTION
**Pull request by noahhendlish**
**Issue:** #5215
**Alexa rank:** 232,399
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Logo Sourced from "Kubuntu Artwork" (https://share.kde.org/s/3s6Mfq9agNdTrf2) in the footer of https://kubuntu.org/.

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for your speedy work on this @noahhendlish! 🚀
The reason the icon is failing the linter would appear to be down to the precision of the icon. Could you try re-building it with a precision of 4 decimals (by editing the `svgo.config.js` file in the root of the project, running the SVGO command, and then discarding the edits to the SVGO config before uploading? (Or, much simpler on SVGOMG where you just need to move the slider to 4 😅)

You can also run the linter test locally by running the command `npm run svglint` in the root directory of the project.

**Comment by noahhendlish** [comment]
No problem! Thanks for the detailed explanation! All fixed now 👍

**Review by adamrusted — CHANGES_REQUESTED** [review]
SVG looks spot on @noahhendlish 🚀
Any chance you could update the hex to `#0079C1`, to match the source SVG? I've opened it in Illustrator and Affinity and am getting that code - so probably best to stick to that. After that's done, we can merge this! 💪

**Review by adamrusted — APPROVED** [review]
I've just updated this hex so it can be included in next week's release. Thanks for your work on this @noahhendlish 🚀

**Pull request merged**
