### PR TITLE
Added Eyeem Icon

### PR DESCRIPTION
**Pull request by ngrosso**
**Issue: #1550**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Got icon from [Svgrepo](https://www.svgrepo.com)
Got hex from [EyeEm press kit](https://www.eyeem.com/press)
Checked the image with inkscape

### CODE REVIEW

**Comment by ngrosso** [comment]
I'll need to change something, because i messed up the "expo.svg" image

**Comment by ngrosso** [comment]
Sure i'll take a look on tuesday, thanks for pointing it out

**Comment by birjolaxew** [comment]
:+1: Looks good! Thanks a lot for the contribution @ngrosso!

**Comment by birjolaxew** [comment]
I agree with @phatbhoy67 that #000000 is the appropriate color here. `#191919` seems to be their website nav color, but `#000000` is used extensively on both their website and for the brand in general.

Thanks a lot for the contribution @ngrosso!

**Pull request merged**
