### PR TITLE
Added ProtonVPN

### LINKED ISSUE #4914: protonVPN
**Brand Name:** ProtonVPN
**Website:** https://protonvpn.com
**Alexa rank:** 7326 
**Official resources for icon and color:** https://protonvpn.com/press

### PR DESCRIPTION
**Pull request by adamrusted**
protonvpn

**Issue:** Fixes #4914 - carries on from #4929
**Alexa rank:** [7,422](https://www.alexa.com/siteinfo/protonvpn.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Hex pulled directly from SVG. Tidied up SVG from original (abandoned) PR.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Could you double check the precision on this, @adamrusted? I was able to get it down to 3. Also there's a duplicate point in the top of the bottom circle that you may be able to clean up.

**Comment by adamrusted** [comment]
@PeterShaggyNoble just rebuilt this in Illustrator, and removed the additional point at the bottom. Should be good to go now.

**Comment by PeterShaggyNoble** [comment]
Odd, I'm seeing some differences around some of the edges in the circles now 🤔 

Example (yours in red):

**Comment by adamrusted** [comment]
Going back to the original PR, I'm unable to remove that duplicate point without changing the rest of the path it's attached to. I'll take another look tomorrow to see if I can rebuild it from scratch, a bit more accurately!

**Comment by adamrusted** [comment]
Well, there's our problem @PeterShaggyNoble - [the circles aren't circular](https://user-images.githubusercontent.com/1830867/109284685-08602900-7818-11eb-872b-e4928654d444.png)! Given I'm not _great_ with the pen tool, I'm not going to be able to remove it. Will roll back the PR to the original adaptation with just the extra point in the bottom circle - if any other @simple-icons/maintainers are able to remove it, feel free!

**Review by PeterShaggyNoble — APPROVED** [review]
Looks good to me now 👍🏻Thanks, @adamrusted

**Pull request merged**
