### PR TITLE
Updated AT&T

### PR DESCRIPTION
**Pull request by fbernhart**
at-and-t

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
There's an embedded SVG [here](https://www.att.com/), might it be worth changing the source to this?
There also appears to be a few differences between the PR and SVG on the website.

image

**Comment by fbernhart** [comment]
@adamrusted Thanks a lot! The official website is indeed a better source than Wikipedia.

I've updated the source and rebuilt the icon. 👍🏼

**Review by adamrusted — APPROVED** [review]
Perfect 💯 - can you resolve the merge conflict for me please? 😇

**Comment by fbernhart** [comment]
@adamrusted As you've already approved it, I'll quickly merge it (before another conflict arises 😄).

**Pull request merged**
