### PR TITLE
Updated Citrix

### LINKED ISSUE #4746: Update Citrix
**Brand Name:** Citrix
**Official resources for icon and color:** https://brand.citrix.com/
- https://brand.citrix.com/brand-system/compact-mark/
- https://brand.citrix.com/brand-system/logo/
- https://brand.citrix.com/brand-system/color/

We'll need to update our Citrix icon following a rebrand in September.

### PR DESCRIPTION
**Pull request by adamrusted**
citrix

**Issue:** Fixes #4746
**Alexa rank:** [7,723](https://www.alexa.com/siteinfo/citrix.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Updated source to new brand hub. Picked most prominent of their colour schemes.

### CODE REVIEW

**Comment by fbernhart** [comment]
I'm approving everything. But was a precision of 4 necessary here? 🤔  I got the same matching results with a precision of 3:
```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Citrix icon</title><path d="M11.983 0a1.78 1.78 0 0 0-1.78 1.78 1.78 1.78 0 0 0 1.78 1.78 1.78 1.78 0 0 0 1.78-1.78A1.78 1.78 0 0 0 11.983 0zM5.17 5.991a1.026 1.026 0 0 0-1.095 1.027c0 .308.136.616.376.822l6.162 7.086-6.401 7.258a1.084 1.084 0 0 0-.309.787c0 .582.48 1.027 1.062 1.027.342 0 .684-.17.89-.444l6.128-7.19 6.162 7.19c.205.274.547.444.89.444.582.035 1.062-.445 1.062-1.027a1.14 1.14 0 0 0-.309-.787l-6.402-7.258 6.162-7.086c.24-.206.377-.514.377-.822v-.034c0-.582-.513-1.027-1.095-.993-.343 0-.65.171-.856.445l-5.957 7.018L6.06 6.436a1.07 1.07 0 0 0-.855-.445z"/></svg>
```

**Comment by adamrusted** [comment]
> I got the same matching results with a precision of 3:

You and your Inkscape magic! 😜
I've just pushed your path to the PR. 🤣

**Comment by fbernhart** [comment]
I haven't done anything special this time. 😄


As I've created the path: could you review it and merge the PR if it matches?

**Comment by adamrusted** [comment]
> As I've created the path: could you review it and merge the PR if it matches?

Yep, looks good to me. Thanks again @fbernhart for your vector wizardry! 🤣

**Pull request merged**
