### PR TITLE
Add justeat icon

### PR DESCRIPTION
**Pull request by el1f**
**Issue:** #1955 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @el1f thanks for your work so far on this PR 👍 

I think this icon should be "Just Eat" and not "JustEat". 

Can you please update the `<title>` within the .svg itself and the .json entry. 

Can you also change the file name to be all lowercase, i.e. `justeat.svg`.

**Comment by runxel** [comment]
> Or the [full wordmark .svg](https://www.just-eat.com/logo.svg) from the header in their website.

Yeah, that's what I would expect for sure.

**Comment by el1f** [comment]
I went ahead and updated the logo to use the full wordmark in a format similar to the app in the latest commit. Let me know which version is preferrable.

**Comment by phatbhoy67** [comment]
Hey @el1f I like this version 😃 

Can you make some small adjustments to closer match the app icon. 

The "T"'s should line up vertically. 

The top of "EAT" should be in line with the bottom of "J" horizontally.

Roughly as below:

je-hv


```xml
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M14.936 3.887c-1.606 0-2.877.839-2.877 2.385 0 1.315 1.102 1.75 2.342 2.13.626.184 1.1.325 1.1.705 0 .32-.343.601-.995.64v-.003c-.653.038-1.282.014-2.248-.103-.5-.061-.516-.012-.64.703-.136.783-.119.793.427.873a13.166 13.166 0 002.448.135c1.713-.067 2.783-.907 2.783-2.346 0-1.223-.935-1.782-2.356-2.195-.765-.2-1.086-.4-1.086-.75 0-.29.235-.57 1.061-.58a17.443 17.443 0 011.762.074c.372.033.527-.036.642-.71.116-.673.033-.832-.416-.874-.5-.045-1.274-.084-1.947-.084zm-13.01.043c-.663 0-.663-.001-.799.765-.136.768-.12.793.467.793h1.203L2.13 9.381c-.15.873-.541 1.461-1.716 1.822-.3.09-.391.212-.391.346 0 .15.06.3.182.617.18.465.3.557.464.557.164 0 .465-.09.57-.12 1.673-.542 2.336-1.823 2.606-3.359l.756-4.38c.165-.92.166-.934-.648-.934zm4.551 0c-.821 0-.842-.007-.95.666L4.919 8.15c-.35 2.012.888 3.258 2.663 3.258 1.988 0 2.99-.887 3.326-3.013l.605-3.52c.164-.945.126-.945-.728-.945h-.002c-.802 0-.821.006-.936.674l-.61 3.543c-.168 1.024-.446 1.627-1.44 1.627-.996 0-1.333-.6-1.18-1.516l.578-3.385c.153-.949.126-.943-.717-.943zm12.332 0c-.658 0-.658-.002-.795.777-.138.78-.122.781.46.781h1.507l-.84 4.866c-.153.948-.14.947.717.947.78 0 .826-.001.933-.674l.885-5.139h1.44c.649 0 .649 0 .785-.78s.136-.778-.461-.778h-.002zM7.577 12.74c-1.162 0-1.141.001-1.34 1.178l-.848 4.924c-.212 1.269-.203 1.27.992 1.27h3.227c.674 0 .659 0 .797-.764.137-.795.136-.795-.475-.795H7.145l.229-1.422h2.31c.627 0 .627-.001.736-.736.122-.75.122-.748-.736-.748H7.62l.228-1.346h2.707l.002-.002c.651 0 .653-.007.785-.78.133-.772.133-.779-.463-.779zm7.87 0c-1.223 0-1.207 0-1.573.748l-2.77 5.737c-.398.827-.335.886.69.886.795 0 .779.001 1.117-.734l.443-.98h2.662l.137.98c.106.735.137.734.933.734.894 0 .982-.064.811-.949l-.98-5.504c-.17-.918-.17-.918-1.47-.918zm3.368 0c-.658 0-.659 0-.797.78-.137.779-.121.779.461.779h1.506l-.84 4.867c-.153.95-.14.947.717.947.78 0 .828.001.935-.672l.883-5.14h1.44c.649 0 .649 0 .785-.78s.134-.779-.461-.779v-.002zm-3.508 1.635c.138 0 .139 0 .17.211l.322 2.328h-1.773l1.07-2.34c.091-.199.091-.199.211-.199z"/></svg>
```

**Comment by el1f** [comment]
Should be done :)

**Comment by phatbhoy67** [comment]
Hey @el1f thanks for all your work on this PR, I think the .svg looks great 👍 

Can you confirm why you chose the hex value `#FA0029`

Since this is an interpretation of the logo can the @simple-icons/maintainers give a view about using this over the full [wordmark.svg](https://www.just-eat.com/logo.svg) please.

**Comment by PeterShaggyNoble** [comment]
Without the rays, I thinks the full wordmark should be used, rather than the stacked version. This would appear to be backed up by [this page](https://www.just-eat.co.uk/info/our-brand).

**Comment by ericcornelissen** [comment]
> Without the rays, I thinks the full wordmark should be used, rather than the stacked version. This would appear to be backed up by this page.

What exactly on the page suggests it would be better to use the full wordmark? I'm not necessarily against it, but given that we are working in a square - rather than a rectangle - I think it might be better to use the stacked version as they do in their app icon (regardless of the rays being there or not) 🤔

**Comment by el1f** [comment]
I agree with @ericcornelissen on this. I think that when we are working on icons for this specific package we should keep the most reasonable use cases in mind, which to the extent of my experience involves using the icons with relatively small sizes and aspect ratios. If the user's working with enough real estate to actually afford to go for the full horizontal wordmark I honestly doubt their use case would generally warrant using something like simple-icons rather than going for the full-fledged official SVG or something like that.

I think that since most icons here sometime have to actually interpret the brand icon, especially when a brand guide is absent, it would be in our and in the user's best interest to go for the designs that we deem most flexible rather than more "brand safe".

**Comment by phatbhoy67** [comment]
Looking at this again what about 👇 
just-eat-alt

**Comment by ericcornelissen** [comment]
Interesting suggestions @phatbhoy67, though it might look a little weird when centered vertically in the viewbox 🤔 We could decide to ignore that rule for this specific icons, but I'm not quite sure about that other.

Any opinions from others or other @simple-icons/maintainers ?

**Comment by el1f** [comment]
Bump!
Which one do you guys think we should go with? I am fairly neutral about it myself. Should we go with @phatbhoy67's proposal or should we go with the plain wordmark? :)

**Comment by PeterShaggyNoble** [comment]
Of the two options on the table at the moment - your current version & @phatbhoy67's alternative - my vote goes to yours, @el1f.

**Comment by runxel** [comment]
Mine too :)
The wordmark as it is now looks good to me.

**Comment by el1f** [comment]
Nice! Is there any work left to be done on the current iteration? It seems ready to land IMO

**Comment by PeterShaggyNoble** [comment]
Agreed, @el1f, merging it in now. Thanks for your work and patience on this one 👍

**Comment by el1f** [comment]
Thank you guys for the great work <3

**Pull request merged**
