### PR TITLE
Add 2K Icon

### PR DESCRIPTION
**Pull request by Mvlprem**
2k

**Similarweb rank:** [22,895](https://www.similarweb.com/website/2k.com/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

The only svg available in their website is on [login page](https://portal.2k.com), Hex taken from stylesheet ` --color-primary-rgb ` ` rgb(221, 7, 0) `

Coming to svg the one available is just the 2K part the outer border is not available so i made one, I don't know something like this is accepted here, if not and we should just use the 2K part let me know and I'll update the svg.

### CODE REVIEW

**Comment by Mvlprem** [comment]
@PeterShaggyNoble The vector is available, at least a part of it

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
Yeah, it was because only the "2k" was available as a vector that I added the label. However, I have since found vector versions of the full logo in the PDFs available [here](https://support.2k.com/hc/en-us/articles/203972113-Digital-Copies-of-2K-Manuals). And, comparing yours with the one on the cover of the [Spanish WWE 2K23 manual](https://cdn.2kgames.com/manuals/wwe2k23/pc/2KSWIN_WWE2K23_PC_Online_Manual_SPA.pdf), the "2k" in yours is considerably larger.

**Comment by Mvlprem** [comment]
@PeterShaggyNoble I've updated the source & svg and sorry for the extra work I'll keep an eye on release docs from next time.

**Review by PeterShaggyNoble — APPROVED** [review]
This is a collaborative project; we're all here to help each other 😀 Plus: I'd much rather be reviewing your PRs than reviewing our existing icons for our Great Icon Review! 😆

All looks good here now 👍🏻

**Pull request merged**
