### PR TITLE
Add FreeCAD icon

### LINKED ISSUE #7295: Request: FreeCAD
### Brand Name

FreeCAD

### Website

https://freecadweb.org

### Popularity Metric

The SimilarWeb rank is 67,253. See https://www.similarweb.com/website/freecadweb.org

### Official Resources for Icon and Color

svg: `https://www.freecadweb.org/svg/logo-freecad.svg`
color: `#343A40`, from their website footer.

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
freecad

**Issue:** closes #7295

**Similarweb rank:** 60,929. See https://www.similarweb.com/website/freecad.org

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from website header https://www.freecad.org
Color: `#729FCF` Taken from one of the colors in the logo.

### CODE REVIEW

**Review by LitoMore — CHANGES_REQUESTED** [review]
See https://www.freecad.org/svg/icon-freecad.svg.

There should be a gap between `F` and the gear. And it loses too many details from the original design.

Better to ask their team for advice.

**Comment by PratyushJayachandran** [comment]
> See https://www.freecad.org/svg/icon-freecad.svg.
> 
> There should be a gap between `F` and the gear. And it loses too many details from the original design.
> 
> Better to ask their team for advice.

Yes. I was split on this one. I tried with a gap between F and gear but the way the teeth are positioned, it makes it look weird. I'll try once more with a different approach or we can ask them.

**Comment by PratyushJayachandran** [comment]
> There should be a gap between `F` and the gear. And it loses too many details from the original design.

freecad
I added a gap.
@LitoMore please review

**Comment by PratyushJayachandran** [comment]
> image
> 
> @PratyushJayachandran Please don't change the style of the corner.

I didn't understand what you meant by corner.

Just to note, the wireframe for original logo in this comparison image doesn't show the stroke that is around F and the gear symbol. I didn't change the corner style for those strokes but I'll re-check.

**Comment by LitoMore** [comment]
image

This is corner.

image

Those corners in your design are angled.

image

**Comment by PratyushJayachandran** [comment]
> image
> 
> This is corner.
> image
> 
> Those corners in your design are angled.
> image

Okay my assumption was close. I'll recheck the source and correct. Thank you for the review and detailed explanation.

**Comment by PratyushJayachandran** [comment]
> image
> 
> @PratyushJayachandran Please don't change the style of the corner.

@LitoMore the corner style was take as is from the logo. It looks different in wire frame mode as it is a stroke. Please look at the following image 
image

**Comment by PeterShaggyNoble** [comment]
What are people's thoughts on this approach? Or should we keep both the "F" and the cog solid and just have a cut-out where they overlap?

**Comment by PeterShaggyNoble** [comment]
Don't forget about this one, @PratyushJayachandran; just need to fix up the corners and it should be good to go.

**Comment by PratyushJayachandran** [comment]
> Don't forget about this one, @PratyushJayachandran; just need to fix up the corners and it should be good to go.

My application is beveling the joints for some reason instead of mitering it like it looks in reality, no matter what I select in the settings. Can you extract the logo mark and attach it here. Maybe saving on a different application might solve the issue. Now I understand why @LitoMore was seeing a different style of corner 😐

**Comment by PeterShaggyNoble** [comment]
This any use, @PratyushJayachandran?

**Comment by PratyushJayachandran** [comment]
> This any use, @PratyushJayachandran?
> 
> 

image
SethMeyersStressedGIF


The issue is that I am not able to miter the corners and outlining the strokes results in beveled shape. How do I fix this now 😞

**Comment by PeterShaggyNoble** [comment]
And I thought Inkscape was a jerk with `stroke`s! 😆 What software are you using?

I'll have a go at doing the icon myself shortly.

**Comment by PeterShaggyNoble** [comment]
What do you reckon to this, @PratyushJayachandran? I took the liberty of redrawing the inner circle of the cog while I was at it.
```
M -218.45535,3.0090742V 73.544161h 16.45818V 45.330126h 14.10702V 28.871939h -14.10702v -9.404678h 23.5117V 3.0090742Zm 45.70889,18.8105048 -4.81599,0.252556a 1.1756577,1.1756062 0 0 0 -1.06767,0.866726l -2.06072,7.570939 -2.1009,1.004484 -3.62778,-1.584214v 16.869591h -13.21385l 0.26979,4.672286a 1.1756577,1.1756062 0 0 0 0.86102,1.067623l 7.57127,2.054887 1.01027,2.100807 -3.16283,7.163406a 1.1756577,1.1756062 0 0 0 0.28701,1.348878l 3.59908,3.23731a 1.1756577,1.1756062 0 0 0 1.3719,0.149237l 6.79635,-3.903138 2.20996,0.786368 2.84138,7.312643a 1.1756577,1.1756062 0 0 0 1.15951,0.751928l 4.85044,-0.269776a 1.1756577,1.1756062 0 0 0 1.07341,-0.872466l 2.03201,-7.576679 2.09516,-1.004484 7.18668,3.174169a 1.1756577,1.1756062 0 0 0 1.35468,-0.292735l 3.23745,-3.598922a 1.1756577,1.1756062 0 0 0 0.14351,-1.371839l -3.90331,-6.801792 0.76918,-2.209865 7.30722,-2.841254a 1.1756577,1.1756062 0 0 0 0.75196,-1.153722l -0.24682,-4.844483a 1.1756577,1.1756062 0 0 0 -0.86677,-1.073363l -7.57701,-2.031928 -1.01027,-2.100806 3.15135,-7.197846a 1.1756577,1.1756062 0 0 0 -0.29275,-1.348879l -3.59908,-3.237308a 1.1756577,1.1756062 0 0 0 -1.3719,-0.143498l -6.80209,3.897399 -2.187,-0.757668 -2.86434,-7.318385a 1.1756577,1.1756062 0 0 0 -1.15951,-0.746187zm 6.60757,25.866124a 7.6398315,7.6427703 0 0 1 -7.63983,7.642771 7.6398315,7.6427703 0 0 1 -7.63983,-7.642771 7.6398315,7.6427703 0 0 1 7.63983,-7.64277 7.6398315,7.6427703 0 0 1 7.63983,7.64277z
```

**Comment by PratyushJayachandran** [comment]
> What do you reckon to this, @PratyushJayachandran? I took the liberty of redrawing the inner circle of the cog while I was at it.
> 
> ```
> M -218.45535,3.0090742V 73.544161h 16.45818V 45.330126h 14.10702V 28.871939h -14.10702v -9.404678h 23.5117V 3.0090742Zm 45.70889,18.8105048 -4.81599,0.252556a 1.1756577,1.1756062 0 0 0 -1.06767,0.866726l -2.06072,7.570939 -2.1009,1.004484 -3.62778,-1.584214v 16.869591h -13.21385l 0.26979,4.672286a 1.1756577,1.1756062 0 0 0 0.86102,1.067623l 7.57127,2.054887 1.01027,2.100807 -3.16283,7.163406a 1.1756577,1.1756062 0 0 0 0.28701,1.348878l 3.59908,3.23731a 1.1756577,1.1756062 0 0 0 1.3719,0.149237l 6.79635,-3.903138 2.20996,0.786368 2.84138,7.312643a 1.1756577,1.1756062 0 0 0 1.15951,0.751928l 4.85044,-0.269776a 1.1756577,1.1756062 0 0 0 1.07341,-0.872466l 2.03201,-7.576679 2.09516,-1.004484 7.18668,3.174169a 1.1756577,1.1756062 0 0 0 1.35468,-0.292735l 3.23745,-3.598922a 1.1756577,1.1756062 0 0 0 0.14351,-1.371839l -3.90331,-6.801792 0.76918,-2.209865 7.30722,-2.841254a 1.1756577,1.1756062 0 0 0 0.75196,-1.153722l -0.24682,-4.844483a 1.1756577,1.1756062 0 0 0 -0.86677,-1.073363l -7.57701,-2.031928 -1.01027,-2.100806 3.15135,-7.197846a 1.1756577,1.1756062 0 0 0 -0.29275,-1.348879l -3.59908,-3.237308a 1.1756577,1.1756062 0 0 0 -1.3719,-0.143498l -6.80209,3.897399 -2.187,-0.757668 -2.86434,-7.318385a 1.1756577,1.1756062 0 0 0 -1.15951,-0.746187zm 6.60757,25.866124a 7.6398315,7.6427703 0 0 1 -7.63983,7.642771 7.6398315,7.6427703 0 0 1 -7.63983,-7.642771 7.6398315,7.6427703 0 0 1 7.63983,-7.64277 7.6398315,7.6427703 0 0 1 7.63983,7.64277z
> ```

Well this looks like the possible contributions itself 😨 
image

**Comment by PeterShaggyNoble** [comment]
Feel free to run with it in that case 🙂

**Comment by service-paradis** [comment]
Not sure why, but the inner circle looks like this in Inkscape on my side 🤔 
image

Might need someone else to review this one...

**Comment by LitoMore** [comment]
@service-paradis I just checked this icon. It looks good on other SVG editors and browsers.

**Comment by uncenter** [comment]
> Not sure why, but the inner circle looks like this in Inkscape on my side 🤔 image
> 
> Might need someone else to review this one...

Huh I'm also seeing that in Inkscape:

Screenshot 2024-04-22 at 08 39 50 (Inkscape)

Though it looks fine on GitHub:

image

**Review by LitoMore — APPROVED** [review]

**Comment by adamrusted** [comment]
@LitoMore - were you happy with this? If so, can you merge it down please?

**Pull request merged**
