### PR TITLE
Add: NASA

### PR DESCRIPTION
**Pull request by adamalston**
nasa

**Alexa rank:** [1,164](https://www.alexa.com/siteinfo/nasa.gov)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The color is NASA Blue as defined in the source

### CODE REVIEW

**Comment by adamalston** [comment]
Fixed @runxel.

**Comment by adamrusted** [comment]
nasa

Just trying to revive this one, I've just been able to generate the following path:
```svg
M12.376 12.76a.175.175 0 00-.302.12v.178c0 .035.011.069.03.097l-.506.338a.82.82 0 00-.04-.056c-.019-.022-.029-.034-.033-.046-.034-.087-.292-.781-.563-1.512.398-.103.761-.2 1.07-.286.123.614.624.862.944.984l-.466.308a.195.195 0 00-.034-.038 1.54 1.54 0 01-.1-.086zM1.533 13.965A9.862 9.862 0 011.336 12c0-5.423 4.397-9.82 9.82-9.82 3.466 0 6.507 1.8 8.254 4.513a48.65 48.65 0 01-.328.195c-1.192.699-3.123 1.593-5.297 2.453a.171.171 0 00-.045.026c-1.203-1.458-2.547-2.64-3.81-3.347-1.395-.78-2.555-.9-3.266-.336-.853.678-.855 2.279-.067 4.277H5.49a.172.172 0 00-.164.134c-.02.077.02.16.09.2.067.036.251.245.251.354v1.186l-1.054-1.788a.176.176 0 00-.15-.086H2.817a.175.175 0 00-.11.311c.122.098.325.262.325.41v.193a128.4 128.4 0 01.002 2.42.179.179 0 00-.133.006c-.49.222-.942.443-1.369.663zm10.269-8.599a.082.082 0 10-.165 0 .082.082 0 00.165 0zm1.497.844a.11.11 0 10-.22 0 .11.11 0 00.22 0zm-.543-2.223l.282.015c.01.047.048.084.096.093l.026.28.014-.28a.123.123 0 00.1-.097l.275-.026-.274-.015a.121.121 0 00-.104-.101l-.026-.273-.016.275a.12.12 0 00-.093.104l-.28.025zm-1.16.227a.11.11 0 10.22 0 .11.11 0 00-.22 0zm-.502-1.226a.082.082 0 10.164 0 .082.082 0 00-.164 0zm-.314 1.914a.082.082 0 10.165 0 .082.082 0 00-.165 0zm-.314-.835a.11.11 0 10.22 0 .11.11 0 00-.22 0zM9.68 5.204a.082.082 0 10.165 0 .082.082 0 00-.165 0zm-.244-.162a.082.082 0 10.165 0 .082.082 0 00-.165 0zm-.04.408a.082.082 0 100 .165.082.082 0 000-.165zm-.18-.57a.082.082 0 10.165 0 .082.082 0 00-.165 0zm3.966 8.481l-.001.02a.166.166 0 00-.022-.006l-.44.284c-.128.083-.288.187-.468.307v.17c.095-.187.304-.355.466-.364.07-.003.312.22 1.31.166.464-.026 1.333-.502 1.393-1.065a14.376 14.376 0 00-.396-.718c-.32.213-.65.431-1.003.661.093.068.166.142.175.233.025.265-.507.393-.987.338-.01-.001-.019-.004-.028-.007l.008-.023-.007.004zm.013-3.79a52.304 52.304 0 01-2.729.97l-.173-.466a.175.175 0 00-.164-.114H8.22c-.072 0-.13.05-.156.118a.187.187 0 00.052.198c.074.068.27.247.247.389-.01.06-.074.309-.16.632a.189.189 0 00-.1.003l-.198.066a.137.137 0 00-.013-.03c-1.357-2.384-1.699-4.532-.83-5.222.196-.156.454-.233.761-.233.526 0 1.195.225 1.945.664 1.122.658 2.324 1.721 3.426 3.025zM7.598 6.853a.082.082 0 10-.165 0 .082.082 0 00.165 0zm.352.426a.082.082 0 10-.165 0 .082.082 0 00.165 0zm.978-.26l-.273-.016a.121.121 0 00-.104-.1l-.026-.273-.016.275a.12.12 0 00-.094.103l-.28.026.282.015c.01.047.049.084.097.093l.025.28.015-.28a.122.122 0 00.1-.097l.274-.026zm4.989 5.939a.16.16 0 01-.043-.046l-.482.313c.287.023.534-.059.614-.137.014-.027.006-.06-.089-.13zm-4.455.66c.117-.117.138-.19.135-.209a1.716 1.716 0 00-.07-.258h-.423l.027.037c.05.07.1.143.157.213l.174.217zm8.128-1.286l-.26-.645-.198.645h.458zm-2.13-.47c.23.412.434.82.608 1.217.128-.456.396-1.43.545-2-.358.247-.74.506-1.145.779l-.008.005zm-8.951-.01c.288-.103.57-.202.843-.296-.24-.438-.448-.865-.624-1.277a.173.173 0 01-.055.026c-.02.02-.164.21-.164.344v1.204zM20.25 8.305A9.783 9.783 0 0120.976 12c0 5.423-4.397 9.82-9.82 9.82a9.774 9.774 0 01-6.369-2.353 45.517 45.517 0 012.525-2.031l.325-.247a74.19 74.19 0 012.438-1.748l.004.005c.398.542.701.85.956.97.331.158.557.06.656-.084.118-.173.076-.428-.098-.593-.073-.07-.19-.16-.332-.27-.16-.124-.356-.277-.562-.457.504-.345.982-.668 1.376-.93v.054c0 .08.055.151.134.17.077.023.16-.019.197-.091.073-.145.232-.263.32-.268l-.005.01c.145.06.481.195 1.315.155.44-.024 1.275-.42 1.502-1 .078.16.15.32.216.476a.235.235 0 00-.07.034 2.583 2.583 0 00-.088.07.175.175 0 00.114.307h.135a.128.128 0 00.065-.02c.152.406.26.787.328 1.142a.11.11 0 00.004.218c.011 0 .019-.008.029-.012.028.185.045.362.048.528a.11.11 0 00-.187.079.11.11 0 00.188.077c-.016.537-.173.964-.48 1.236-.265.23-1.156.317-2.32-.206a.177.177 0 00-.21.053.255.255 0 00-.039.164c.01.055.044.137.145.2.744.299 2.094.717 2.798.158.746-.593.77-1.964.213-3.617h.46a.175.175 0 00.132-.291c-.1-.112-.16-.196-.149-.267a6.14 6.14 0 01.056-.29h.954c.034.1.056.182.068.258.004.024-.025.118-.206.275a.175.175 0 00.114.307h2.188a.175.175 0 00.041-.345c-.049-.011-.148-.101-.208-.255-.073-.19-1.232-3.316-1.232-3.316a.175.175 0 00-.165-.114h-.293a27.452 27.452 0 001.36-1.057l.06-.05c.185-.155.407-.344.643-.55zm-4.84 7.468a.082.082 0 10.164 0 .082.082 0 00-.165 0zm-.016 1.116a.082.082 0 10.165 0 .082.082 0 00-.165 0zM7.257 18.14a.083.083 0 10.165 0 .083.083 0 00-.165 0zm.746 1.15l-.273-.016a.122.122 0 00-.104-.101L7.6 18.9l-.016.275a.12.12 0 00-.093.104l-.28.025.282.015c.01.047.048.085.096.093l.026.281.015-.28a.122.122 0 00.1-.098l.273-.026zm.327-1.794a.11.11 0 100-.22.11.11 0 000 .22zm.208.85a.083.083 0 10-.166 0 .083.083 0 00.166 0zm2.202-.24a.083.083 0 10-.166 0 .083.083 0 00.166 0zm1.937-.7a.082.082 0 10-.165 0 .082.082 0 00.165 0zm3.273 1.659a.082.082 0 10-.165 0 .082.082 0 00.165 0zm1.62-3.895a.11.11 0 10.22 0 .11.11 0 00-.22 0zm.118 1.522a.082.082 0 100 .165.082.082 0 000-.165zm-.253-2.021a.083.083 0 10.165 0 .083.083 0 00-.165 0zm.858 2.563l-.273-.015a.121.121 0 00-.104-.101l-.026-.273-.016.275a.121.121 0 00-.093.103l-.28.026.282.015c.01.047.048.084.096.093l.025.28.016-.28a.121.121 0 00.1-.097l.273-.026zm.226.02a.082.082 0 10-.165 0 .082.082 0 00.165 0zm.123-1.306a.082.082 0 10-.165 0 .082.082 0 00.165 0zm.247-.846l.274-.026-.273-.016a.121.121 0 00-.105-.1l-.026-.273-.015.275a.12.12 0 00-.094.103l-.28.026.282.015c.01.047.049.084.097.093l.025.28.015-.28a.122.122 0 00.1-.097zm.31.67a.11.11 0 10-.22 0 .11.11 0 00.22 0zm-9.096-1.364l.038.043.011.016.705-.477H9.763c.095.117.187.23.267.332.023.03.048.058.073.086zM3.874 12.1v.776l.37-.154-.37-.621zm10.737-.561l.02-.013.009-.005c-.155-.24-.318-.48-.49-.72-.003.073-.06.138-.13.163-.134.047-.264.09-.394.134.093.049.22.092.357.139.149.05.31.105.47.18.022.01.046.023.07.036.034.018.067.05.088.086zm.66-1.046a.174.174 0 01-.065.012v.527a.174.174 0 01-.139.171l.012.019a69.45 69.45 0 002.28-1.654c-.636.317-1.334.625-2.088.925zm-6.04 1.825a.172.172 0 01-.022.008l-.025.007h.054l-.006-.015zM4.318 19.04a9.801 9.801 0 01-2.621-4.437c.371-.173.74-.333 1.117-.476a.174.174 0 00.11-.127h1.143a.175.175 0 00.11-.312l-.021-.016.513-.161a.165.165 0 00.037-.017l.246.413a.176.176 0 00.15.085h1.586a.175.175 0 00.106-.313c-.151-.117-.283-.286-.284-.342V13c.014 0 .03-.001.043-.005.401-.103.833-.212 1.278-.324-.099.354-.174.623-.186.66-.026.075-.208.213-.296.28a2.93 2.93 0 00-.103.08.175.175 0 00.113.308h1.178a.175.175 0 00.131-.291c-.1-.112-.16-.196-.149-.266l.01-.064.05.072c.12.174.24.348.376.519.133.167.26.318.37.45.113.135.209.248.272.333l.043.063v.001c-.909.618-1.7 1.16-2.09 1.43-.224.153-.531.4-.878.692-.016-.017-.02-.045-.045-.045a.083.083 0 00-.083.083c0 .02.025.023.037.037a79.767 79.767 0 00-2.263 2.026zm3.353-3.156a.11.11 0 100 .22.11.11 0 000-.22zm-.114-1.784a.082.082 0 10.165 0 .082.082 0 00-.165 0zm-2.323 3.266a.11.11 0 10.22 0 .11.11 0 00-.22 0zm-.286-.88a.11.11 0 10.22 0 .11.11 0 00-.22 0zm-.112.557a.083.083 0 10.165 0 .083.083 0 00-.165 0zm-.774-.426a.082.082 0 10-.165 0 .082.082 0 00.165 0zm10.97-6.532c-.037.037-.198.222-.345.191a6.359 6.359 0 00-.281-.05c.171.235.334.472.489.708.059.038.109.074.137.098v-.947zm4.14-3.045c-1.301.762-3.33 1.677-5.322 2.465.038.047.077.092.115.14.1.125.187.254.28.38.184.025.349.053.478.08.007 0 .054-.007.172-.129.05-.05.13-.074.197-.047.066.027.115.085.115.156v.245c1.397-.553 2.847-1.24 4.038-2.058-.645.612-2.723 2.168-4.075 3.1.07.114.135.228.2.341 1.958-1.313 3.287-2.287 4.066-2.942 1.1-.924 3.61-2.994 4.565-5.768-1.674 2.128-3.652 3.347-4.83 4.037zM6.772 5.82c-1.029.817-.63 3.174.747 5.677l.22-.075c-1.386-2.435-1.756-4.675-.787-5.446 1.245-.988 4.25.793 6.742 3.93.516.65.97 1.301 1.354 1.937 1.47 2.434 1.922 4.635.906 5.534-.311.275-1.262.383-2.506-.178-.018.022.01.081.032.096 1.075.432 2.104.596 2.623.183 1.249-.992.29-4.496-2.277-7.727-2.567-3.23-5.702-5.005-7.054-3.931zm-.145 4.315H5.49c.092.04.352.308.352.514v1.827l-1.38-2.341H2.819c.173.14.39.323.39.547 0 .102.014 2.47 0 2.653a.664.664 0 01-.353.488h1.211c-.187-.15-.367-.327-.367-.51v-1.85l1.402 2.352h1.585c-.113-.088-.352-.315-.352-.48V10.65c0-.224.224-.496.294-.514zm6.856.774c-.008.01-.014.023-.005.049l.001.002c.16-.054.318-.105.483-.163-.007 0-.014-.003-.02-.003-.276.005-.42.059-.46.115zm-5.326.557c-.512.17-1.067.362-1.65.572v.786c.43-.11.897-.228 1.375-.348.09-.326.189-.689.275-1.01zm5.214-1.499h.037c.039 0 .074.003.113.003l-.212-.257c-.988.381-1.945.721-2.784.99l.375 1.01c.417-.108.796-.209 1.115-.298-.004-.056-.013-.109-.011-.17.02-.7.634-1.274 1.367-1.278zm.75 1.88a8.66 8.66 0 00.355-.222c-.033-.016-.067-.037-.1-.052-.469-.22-.96-.26-1.063-.558-.073-.21.132-.403.63-.396.026 0 .048.009.073.01-.117-.16-.233-.32-.358-.48-.094-.003-.187-.008-.287-.007-.63.004-1.174.491-1.192 1.108-.024.812.583 1.066.979 1.207.43-.281.773-.5.962-.61zm3.999 1.532a2.24 2.24 0 00-.117-.404h-1.219s-.066.294-.088.44.074.276.19.408h-.523c-.058-.16-.12-.323-.187-.488a116 116 0 00.657-2.412c.4-.278.77-.542 1.11-.788h.537s1.16 3.126 1.233 3.317c.073.191.209.334.33.363h-2.187c.135-.117.29-.286.264-.436zm-1.226-.874h.954l-.543-1.343-.41 1.343zm-5.786 3.752c.466.22.592-.176.364-.392-.16-.15-.525-.399-.922-.751-.111.076-.22.15-.331.228.276.376.614.785.89.915zm-8.425-2.399a.176.176 0 01.102-.196c.074-.031.14-.115.188-.203C1.901 13.946.871 14.475 0 15.038l.264.103c.976-.55 1.777-.91 2.487-1.179a.171.171 0 01-.067-.103zm9.94-.347c.85-.545 1.615-1.046 2.313-1.51-.014-.023-.024-.045-.038-.068-.052-.087-.116-.176-.171-.263a11.28 11.28 0 01-.519.329c-.94.543-5.52 3.67-6.561 4.389s-3.934 3.45-4.785 4.242l-.03.323c2.745-2.466 3.606-3.074 4.698-3.905 1.35-1.027 4.144-2.928 5.093-3.537zm-.374-.454l.114-.076a1.598 1.598 0 01-.114-.101v.177zm3.594.766c-.01-.028-.018-.054-.029-.082l-.105.082h.134zm-7.26-.673c.167.237.322.476.507.708.272.343.519.618.646.79l.047.069.224-.152c-.039-.045-.078-.087-.116-.134a67.854 67.854 0 00-.354-.44h-.033a.174.174 0 01-.164-.115.169.169 0 01.006-.123c-.066-.082-.137-.169-.195-.243-.095-.12-.174-.24-.263-.36h-.305zm2.533.665H9.505c.135-.117.29-.286.264-.436a2.235 2.235 0 00-.118-.404H8.433s-.066.294-.088.44c-.022.147.073.276.19.408H7.359c.114-.096.396-.275.451-.437.04-.116.69-2.473.727-2.693.04-.246-.224-.474-.316-.558h1.908s1.16 3.126 1.233 3.317c.022.057.061.09.092.138l-.336.225zm-1.62-1.31l-.543-1.343-.41 1.343h.953zm-.33-.35l-.19-.47-.171.56.36-.09zm-5.293 1.157c0 .056.056.133.138.219l.603-.189-.28-.47c-.154.063-.307.128-.461.193v.247z
```

> @adamalston said:
Also, question. NASA has 2 official logos.

They do - though I would expect to see the one originally linked here over the 'worm' logo. @simple-icons/maintainers correct me if I'm wrong, but I think we may be better with the 'proper' logo.

**Comment by PeterShaggyNoble** [comment]
There's an official monochrome treatment available in [this PDF](designtagebuch.de/cd-manuals/NASA_StyleGuide_Nov06.pdf), although it is dated from 2006.

**Comment by adamrusted** [comment]
> There's an official monochrome treatment available in [this PDF](designtagebuch.de/cd-manuals/NASA_StyleGuide_Nov06.pdf), although it is dated from 2006.

@PeterShaggyNoble unfortunately the monochrome treatment of the logo includes gradients 🙄 (see page 48 of PDF).
Looks like the 'worm' logo was also retired in favour of this one - so we may not be able to add this.

**Comment by PeterShaggyNoble** [comment]
Well, feck my eyesight, anyway! 😆 These 2, from page 9 looked entirely monochrome to me yesterday!

**Comment by adamrusted** [comment]
> Well, feck my eyesight, anyway! 😆

@PeterShaggyNoble Oh dear! 🤣
Does this therefore mean that NASA is unfortunately out of scope for us?

**Comment by PeterShaggyNoble** [comment]
Before we reject it, maybe we could try a treatment based on the second version in my screenshot, with an outlined circle instead of a filled one?

**Comment by adamrusted** [comment]
> maybe we could try a treatment based on the second version in my screenshot

I'll take a quick look now to generate a preview of it.

**Comment by adamrusted** [comment]
@PeterShaggyNoble here's the icon with a 0.5pt border on the inside of the original circle. Unfortunately I think while we can tell it's the NASA logo - without the gradients it's a little too illegible for my liking.

nasa

**Comment by adamrusted** [comment]
Pinging @simple-icons/maintainers for opinions following https://github.com/simple-icons/simple-icons/pull/3447#issuecomment-758619747 - I don't think we can do the logo 'justice' without some pretty major creative liberties.

**Comment by PeterShaggyNoble** [comment]
As a last resort, could we try that last version with a slight cut-out around the letters to see how it looks?

**Comment by adamrusted** [comment]
@PeterShaggyNoble there's a fair bit of overlapping between the text and the two shapes inside the logo - may be quite a difficult one to complete the 'slight cut-out' around. Will take a look this weekend and see if it can be done.

**Comment by PeterShaggyNoble** [comment]
[This (unofficial) treatment](https://www.jing.fm/iclipt/hTJbTo/) might be of help, @adamrusted.

**Comment by PeterShaggyNoble** [comment]
Hold that thought! According to both [Wikipedia](https://en.wikipedia.org/wiki/NASA_insignia) and [Logopedia](https://logos.fandom.com/wiki/NASA), NASA reintroduced [their old "worm" logo](https://commons.wikimedia.org/wiki/File:NASA_Worm_logo.svg) as a secondary logo last year, which would suit us much better than the full insignia.

**Comment by adamrusted** [comment]
Yep! Official article [here](https://www.nasa.gov/feature/the-worm-is-back) on NASA's website. I'll look to make the `Worm` variant, given the `meatball` main logo isn't suitable for our treatment.

**Comment by adamrusted** [comment]
@PeterShaggyNoble see top of [this page](https://www.nasa.gov/multimedia/guidelines/index.html) regarding logo use. Looks like _after all this_ we won't be able to include it.

> The NASA Insignia (the blue "meatball" logo), the NASA Logotype (the "worm" logo) and the NASA Seal may not be used for any purpose without explicit permission. These images may not be used by persons who are not NASA employees or on products, publications or web pages that are not NASA-sponsored. These images may not be used to imply endorsement or support of any external organization, program, effort, or persons.

**Comment by PeterShaggyNoble** [comment]
I'd agree, @adamrusted; that reads to be much more restrictive and explicit than what we're discussing in #4629. Although, I wouldn't necessarily be _opposed_ to adding it on those grounds depending on the outcome of that discussion.

**Comment by adamalston** [comment]
I referenced and actually created the Worm icon when I first opened this PR and no one ever got back to me. Good to see it is finally being discussed even if it will not eventually be incorporated into the project.

> Also, question. NASA has 2 official logos. The one in this PR and another called the [NASA Worm](https://commons.wikimedia.org/wiki/File:NASA_Worm_logo.svg). How do I determine if both are acceptable for placement in this project?

**Comment by adamrusted** [comment]
Hey @adamalston, sorry - I hadn't seen any other reference to the worm returning to general use at the time.
Would definitely be _easier_ for us to include than the full `meatball` version that is their primary logo. Following the outcome of #4629, would you be up for submitting the worm variant @adamalston, or should we close this PR and open a new one with the Worm icon?

**Comment by adamalston** [comment]
@adamrusted PR opened

**Comment by adamrusted** [comment]
Thanks @adamalston, I'll close this PR and we can move there for review 👌

**Pull request closed without merging**
