### PR TITLE
Add BookMyShow icon

### LINKED ISSUE #6002: Add BookMyShow
**Brand Name:** BookMyShow
**Website:** https://in.bookmyshow.com/
**Alexa rank:** 4,042
  

**Official resources for icon and color:** SVG is available in the header of the website. Primary color used from the logo is `#CA2532`.

### PR DESCRIPTION
**Pull request by wwwescape**
bookmyshow

**Issue:** Closes #6002
**Alexa rank:** 4,042
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

 - I used the SVG from the header of the website
 - I used Inkscape to remove the text, scale and adjust
 - I used https://jakearchibald.github.io/svgomg/ to optimize

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @wwwescape 👍🏻

I am, though, seeing [some pretty significant differences](https://user-images.githubusercontent.com/15157491/123414580-f915a000-d5ab-11eb-9654-78011f708cd3.png) between your version (in red) and the logo embedded in the website's header. Would you mind having another look at that, please?

Also, from the same SVG, I'm getting `#c4242b` for the colour.

**Comment by wwwescape** [comment]
Sure @PeterShaggyNoble. I'll take another look at it over the weekend.

**Comment by wwwescape** [comment]
@PeterShaggyNoble Done.

**Review by dirien — APPROVED** [review]
HI @wwwescape,

thanks for the contribution! Perfect fit!

image

**Pull request merged**
