### PR TITLE
Added Google Chrome Icon

### PR DESCRIPTION
**Pull request by William-Owen**

### CODE REVIEW

**Comment by davidklebanoff** [comment]
Hi @William-Owen. Where did you source the icon and color? I'm not seeing it on the source page you indicated.

**Comment by William-Owen** [comment]
Original SVG was taken from https://commons.wikimedia.org/wiki/File:Google_Chrome_icon_(2011).svg

Source was cited in that wikimedia post. Color was taken from the default Google blue. I couldn't find any brand guidelines or information on color use with regards to the chrome browsers.

**Comment by davidklebanoff** [comment]
@William-Owen Got it. Thanks!

**Comment by davidklebanoff** [comment]
Closes issue #695.

**Pull request merged**
