### PR TITLE
Add MediaTek icon

### LINKED ISSUE #5166: Request: MediaTek icon
**Brand Name: MediaTek**
**Website: https://www.mediatek.com/**
**Alexa rank: 50,019**
  

**Official resources for icon and color: https://corp.mediatek.com/news-events/press-library**

### PR DESCRIPTION
**Pull request by LittleJake**
mediatek

**Issue:** Close #5166
**Alexa rank:** 50,019
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

For the first try.
BTW, I wonder why everyone's icon in the preview is white.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @LittleJake, and thanks for the contribution 👍🏻

The SVG looks pretty good to me apart from a [tiny difference](https://user-images.githubusercontent.com/15157491/110117374-a9b72400-7db0-11eb-9345-81264ce88604.png) (your version in red) along the top and bottom edges. Could you see if you could fix that? There's also a duplicate point in the inner vertical line of the second "E" which you may be able to remove.

For the colour, the use a number of different shades of that orange throughout their site but I think we should go with the `#ec9430` one from [their website's logo](https://cdn-www.mediatek.com/icons/mtklogo.svg) as the AI file uses CMYK and converting to RGB can often give inaccurate results.

> BTW, I wonder why everyone's icon in the preview is white

It's dependent on the luminance of the background colour.

**Comment by LittleJake** [comment]
Well, I use [this one](https://cdn-www.mediatek.com/page/PRIMARY-MASTER-LOGO_EN_CMYK_WHITE.ai) as the source file. It might be a little different between them. I guess?

**Comment by LittleJake** [comment]
Got no idea what to do next.

**Comment by PeterShaggyNoble** [comment]
I'm still seeing that same difference when comparing it to the file you used, @LittleJake - could you have another look at it? One possible cause may be that the precision is being set too low when you're optimising the final SVG.

**Comment by LittleJake** [comment]
@PeterShaggyNoble I've tried to increase the precision. I think it is all set now.

**Comment by PeterShaggyNoble** [comment]
Thanks, @LittleJake 👍🏻

Gave it a try myself and managed to get the precision back down to 3, while removing some of the excess points, if you want to give this path a try:
```
M3.863 8.996c-.297 0-.665.21-.816.467L.064 14.537c-.15.257-.03.467.268.467h19.805c.297 0 .665-.21.816-.467l2.983-5.074c.15-.257.03-.467-.268-.467zm3.41 1.975h1.09l-.232.402h-.776c-.238 0-.312.093-.312.338v.807h1.37l-.233.402H6.502v-1.197c0-.589.307-.752.771-.752zm1.444 0h.937c.703 0 1.002.27 1.002.959 0 .73-.301.99-.976.99h-.963zm7.832 0h1.09l-.233.402h-.775c-.239 0-.313.093-.313.338-.004.264-.002.539-.002.807h1.372l-.233.402h-1.678v-1.197c0-.589.308-.752.772-.752zm-11.567.004v.986l.569-.984.65-.002v1.941h-.547v-1.191l-.672 1.191h-.546v-1.191l-.688 1.19h-.535l1.121-1.938zm5.98 0h.546v1.941h-.545zm1.798 0h.781v1.941h-.553v-1.383l-.797 1.383h-.552zm1.256 0h1.714l-.232.404h-.504v1.537h-.533v-1.537h-.68zm3.873 0h.547v1.941h-.547zm1.345 0h.545l-.558.968-.002.004h.002l.558.969h-.545l-.56-.97zm-9.994.398v1.145h.297c.432 0 .567-.104.567-.586 0-.483-.135-.559-.567-.559zm-1.847.416h.87l-.185.318h-.86zm9.255 0h.872l-.186.318h-.86Z
```

**Comment by LittleJake** [comment]
Awesome, @PeterShaggyNoble 

But why it is not the same result as the one I followed the guideline?
Is there any trick to do with it? :thinking:

**Comment by PeterShaggyNoble** [comment]
Could be as simple as the fact that some software just doesn't like to play nice with some icons.

Thanks for the update but as you're now using my path we'll need one of the other @simple-icons/maintainers to review this before it can be merged.

**Review by service-paradis — APPROVED** [review]
LGTM 💯 
Thank you @LittleJake and @PeterShaggyNoble!

**Pull request merged**
