### PR TITLE
Adds Prismic.IO, Hexo, and Netlify icons

### PR DESCRIPTION
**Pull request by xdesro**
RE: #508. Let me know if any issues!

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Good work, I've got two suggestions:
- Maybe change the link of Hexo to just `https://hexo.io/`?
- It seems you picked the color for Prismic from their landing page (`#1DE9B6`), right? I'm not sure if that is the best color to use since that's the only place where I could find that particular color... Instead maybe use `#13C095`, a similar color which they use as an accenting color throughout their website?

**Comment by xdesro** [comment]
@ericcornelissen Noted and fixed! Thanks for the guidance  🙏

**Comment by birjolaxew** [comment]
Prismic seems to user 3 logo color schemes: [white](https://prismic.io/), [blue](https://prismic.io/blog) or [multicolored](https://github.com/prismicio).

<p align="center">
  
  
  
</p>

Since we'll be using single-colored, I'd actually suggest #484A7A (from their blue logo)

**Comment by xdesro** [comment]
That makes sense. New commit reflects that thought.

**Comment by birjolaxew** [comment]
:+1: Merged and published

**Pull request merged**
