### PR TITLE
Update Adobe XD

### PR DESCRIPTION
**Pull request by MetLee**
image

**Issue:** #3369 
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by fbernhart** [comment]
@MetLee Thanks for your work so far. Are you still working on this one?

image


If so, it seems like Adobe has slightly changed their logo in the meantime and changed the rounded edges (see comparison above with your version in red).

Could you update your pull request with the logo provided here as source?
https://www.adobe.com/content/dam/cc/us/en/products/xd/home/XD_lockup.svg

**Comment by adamrusted** [comment]
Just to weigh in on this:

> Can you double check this one, @MetLee? I'm seeing some hairline differences in the letters when compared to adobe.com/content/dam/cc/icons/xd.svg

This is the current icon as used on the [UI/UX](https://www.adobe.com/creativecloud/ui-ux.html) page of Adobe.

Comparing @MetLee's icon and my own generated from source, I can't see any differences between them. I've provided my path below, and providing the source is updated to the correct used SVG [this one](https://www.adobe.com/content/dam/cc/us/en/creativecloud/max2020/mnemonics/xd.svg) in my case, then this is good to merge IMO.

```svg
M19.75.3H4.25C1.9.3 0 2.2 0 4.55v14.9c0 2.35 1.9 4.25 4.25 4.25h15.5c2.35 0 4.25-1.9 4.25-4.25V4.55C24 2.2 22.1.3 19.75.3zm-6.91 16.47c-.01.04-.05.01-.11.02h-2.29c-.16 0-.27-.01-.34-.11-.21-.42-.43-.83-.64-1.25-.21-.41-.44-.83-.68-1.26-.24-.43-.48-.86-.72-1.3h-.02c-.21.43-.44.86-.67 1.29-.23.43-.46.86-.68 1.28-.23.42-.46.85-.69 1.26-.04.1-.12.11-.23.11h-2.2c-.04 0-.07.02-.07-.03-.01-.04 0-.08.02-.11l3.11-5.1L3.6 6.44c-.03-.04-.04-.08-.02-.1.02-.03.06-.04.1-.04h2.27c.05 0 .1.01.14.02.04.02.07.05.1.09.19.43.41.86.64 1.29.24.43.47.85.72 1.27.24.42.46.84.67 1.27h.02c.21-.44.43-.87.65-1.29.22-.42.45-.84.68-1.26.23-.42.45-.85.67-1.26.01-.04.03-.08.06-.1.04-.02.08-.03.13-.02h2.11c.05-.01.1.02.11.07.01.01-.01.05-.03.07l-3 4.95 3.2 5.25c.02.04.03.08.02.12zm7.57-.39c-.52.22-1.07.38-1.63.48-.51.09-1.02.14-1.54.14-.74.01-1.48-.14-2.15-.45-.63-.29-1.15-.77-1.51-1.36-.37-.61-.55-1.37-.55-2.28-.01-.74.18-1.47.55-2.11.38-.65.93-1.19 1.59-1.55.7-.39 1.54-.58 2.53-.58.05 0 .12 0 .21.01s.19.01.31.02V5.54c0-.07.03-.11.1-.11h2.03c.05-.01.09.03.1.07v9.54c0 .18.01.38.02.6.02.21.03.41.04.58 0 .07-.03.13-.1.16zm-2.46-5.83c.09.01.18.03.27.05V15c-.12.04-.23.06-.36.05-.13.01-.27.02-.42.02-.28 0-.56-.04-.83-.13-.26-.08-.49-.22-.68-.4-.2-.2-.35-.44-.45-.71-.12-.33-.18-.68-.17-1.03 0-.52.11-.95.33-1.27.22-.32.51-.57.85-.74.35-.18.74-.26 1.13-.26.11 0 .22.01.33.02z
```

> Could you update your pull request with the logo provided here as source?
[adobe.com/content/dam/cc/us/en/products/xd/home/XD_lockup.svg](adobe.com/content/dam/cc/us/en/products/xd/home/XD_lockup.svg)

**Does** have some differences to the above path, but only appears to be used in the 'lockup' variation of the icon.

**Comment by adamrusted** [comment]
@simple-icons/maintainers - this one is ready for review! 🙏🏻

**Comment by fbernhart** [comment]
@adamrusted We've used "https://www.adobe.com/products/PRODUCTNAME" as source for most of the other Adobe logos (After Effects, Dreamweaver, Illustrator, InDesign, Lightroom, Lightroom Classic, Photoshop, Premiere Pro). For consistency I think we should stick with that and use https://www.adobe.com/products/xd.html instead. Do you agree?

**Comment by adamrusted** [comment]
> @adamrusted We've used "[adobe.com/products/PRODUCTNAME](https://www.adobe.com/products/PRODUCTNAME)" as source for most of the other Adobe logos (After Effects, Dreamweaver, Illustrator, InDesign, Lightroom, Lightroom Classic, Photoshop, Premiere Pro). For consistency I think we should stick with that and use [adobe.com/products/xd.html](https://www.adobe.com/products/xd.html) instead. Do you agree?

Sure, let me push a quick edit - and it'll be good to go!

**Comment by fbernhart** [comment]
@adamrusted Thanks. But now that we've agreed on the source, the differences in https://github.com/simple-icons/simple-icons/pull/3386#issuecomment-745259261 apply.

> @MetLee Thanks for your work so far. Are you still working on this one?
> 
> image
> 
> If so, it seems like Adobe has slightly changed their logo in the meantime and changed the rounded edges (see comparison above with your version in red).
> 
> Could you update your pull request with the logo provided here as source?
> https://www.adobe.com/content/dam/cc/us/en/products/xd/home/XD_lockup.svg

Could you rebuilt it with the SVG found on the https://www.adobe.com/products/xd.html page?

**Comment by fbernhart** [comment]
@adamrusted Thanks! LGTM 👍🏼 

And as well thanks to @MetLee for the initial work on this icon! 🎉

**Pull request merged**
