### PR TITLE
add mural icon

### LINKED ISSUE #9229: Mural
### Brand Name

Mural

### Website

https://www.mural.co/

### Popularity Metric

The Similarweb rank is 23,747. See: https://www.similarweb.com/website/mural.co

### Official Resources for Icon and Color

https://www.mural.co/brand-assets

Mural_Symbol_Multicolor_RGB

Mural_Wordmark_Multicolor_RGB

The small favicon is only using the Mural Red: #ff4b4b

63f8b1b0585b45a64baf52da_Mural_Favicon_32x32

### Additional Comments

[Mural](https://www.mural.co/about-us) is the closest competitor to [Miro](https://miro.com/about/), both established in 2011. 

### Contributing

Yes

### PR DESCRIPTION
**Pull request by josch87**
mural (1)

**Issue:** closes #9229 

**Similarweb rank:** 23,747
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- [Brand assets](https://www.mural.co/brand-assets)
- Mural Red is used for favicon

### CODE REVIEW

**Comment by josch87** [comment]
@adamrusted: I kind of got the permission now. Can I forward you the email conversation?

**Comment by adamrusted** [comment]
Sure, if you want to send it to `adam.rusted@simpleicons.org` just so we've got a reference!

**Comment by adamrusted** [comment]
Just to confirm, I've seen proof (an email exchange with Daniel at Mural) of us being able to use the Mural monochrome icon, the raw file for which is listed below. We should still link to the [official brand guidelines](https://mural.co/brand-assets) as our `guidelines` JSON entry, as that specifically gives details on how to obtain permission to use the icon outside of our project and use-case. @josch87 - would you be happy to double-check your PR matches up with the below version, and give me a nudge when it's ready for me to review?

**Comment by josch87** [comment]
Added guidelines to simple-icons.json and compered svgs: besides the color it is the same icon.
@adamrusted: Please review my PR. Thanks.

**Review by PratyushJayachandran — APPROVED** [review]
It is a perfect match @josch87 🎉 
Can we merge this @adamrusted?

**Comment by josch87** [comment]
@adamrusted: Why is this PR not merged and released?

**Pull request merged**
