### PR TITLE
Add Alipay (#2240)

### LINKED ISSUE #2240: Alipay
**Name:** Alipay
**Website:** https://intl.alipay.com/
**Official resources for icon and color:**
  
[CoreUI](https://coreui.io/icons/brand/alipay/) has a vectorized logo.

### PR DESCRIPTION
**Pull request by runxel**
**Issue:** Closes #2240

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo and color `#00A1E9` is taken from their official `.ai` file. Kudos to @PeterShaggyNoble for that one!

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @runxel the .svg is great 👍 

I get the hex value to be `#0092E5` 🤔

**Comment by runxel** [comment]
From where exactly?
In the .ai it's the color I posted above, on the website I just eyedropped `#00a0e9` (which is close, but not identical to both of the colors 🤣)

**Comment by phatbhoy67** [comment]
> From where exactly?

the .ai file opened in XD

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @runxel 👍

**Comment by runxel** [comment]
> the .ai file opened in XD

Ah! Maybe because the document is orginally in CMYK – so the conversion to HEX could be done differently (?).

**Pull request merged**
