### PR TITLE
switch from jest to uvu

### PR DESCRIPTION
**Pull request by sachinraja**
[`uvu`](https://github.com/lukeed/uvu) is faster and way smaller than `jest` and its dependencies (~1 MB vs ~40 MB).

jest:
```
Benchmark 1: npm t
  Time (mean ± σ):     10.590 s ±  0.856 s    [User: 23.097 s, System: 2.174 s]
  Range (min … max):    9.548 s … 12.687 s    10 runs
```
uvu:
```
Benchmark 1: npm t
  Time (mean ± σ):      4.682 s ±  0.277 s    [User: 4.573 s, System: 0.957 s]
  Range (min … max):    4.348 s …  5.138 s    10 runs
  ```
  uvu is much faster than jest. This also improves GH Actions/CI times.

### CODE REVIEW

**Comment by LitoMore** [comment]
How about [AVA](https://github.com/avajs/ava)?

**Comment by sachinraja** [comment]
ava:
```
Benchmark 1: npm t
  Time (mean ± σ):      8.252 s ±  0.095 s    [User: 17.197 s, System: 1.695 s]
  Range (min … max):    8.098 s …  8.373 s    10 runs
  ```
  While I like ava's output format much better, `uvu` is still considerably faster.

**Review by mondeja — APPROVED** [review]
Really awesome! 🎉 

I have taken the liberty of committing to delete jest-diff dependency. Check it and if you see all ok, feel free to merge.

**Review by LitoMore — APPROVED** [review]

**Comment by sachinraja** [comment]
> I have taken the liberty of committing to delete jest-diff dependency.

I also looked into replacing `jest-diff` but not having the context lines makes the diff useless. It shows the entire diff between both strings, sometimes completely hiding the diff.

**Comment by mondeja** [comment]
Yes, it looks better!

**Review by mondeja — APPROVED** [review]
Great! Thank you @sachinraja

**Pull request merged**
