### PR TITLE
Adding CodeProject Icon #3550

### PR DESCRIPTION
**Pull request by ChrisMaunder**
**Issue:** Adding CodeProject Icon #3550
**Alexa rank:** 2,910

### Checklist
  -  I updated the JSON data in `_data/simple-icons.json`
  -  I optimized the icon 
  - The SVG `viewbox` is `0 0 24 24`

### Description 

The hex value is based on CodeProject's main theme colour, not the main colour of the logo itself.

### CODE REVIEW

**Review by runxel — CHANGES_REQUESTED** [review]
Hey @ChrisMaunder 
Thanks for the PR! Please revert the changes on the .gitignore file.
Also have a close look into our [CONTRIBUTING guidlines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and ahere to our standards. (the svg is not what the linter expects, thus the build is failing currently)

**Comment by adamrusted** [comment]
Hi @ChrisMaunder, I've just tried taking a look at this to try and resolve the merge errors but it looks like access to maintainers is disabled on this PR. Could you let us know if you're still interested in fixing this PR, as we'll have to close it otherwise.

**Comment by ChrisMaunder** [comment]
Easiest to just close the PR instead of leaving it hanging. Sorry - been absolutely slammed and have not had a chance to fix the issue. I'll issue a clean one once I've dug myself out.

**Comment by adamrusted** [comment]
No worries! I'll mark this as abandoned for now - but feel free to reopen this PR or submit another one later down the line.

**Pull request closed without merging**
