### PR TITLE
Add Hestia

### PR DESCRIPTION
**Pull request by zcraber**
hestiacontrolpanel

**Similarweb rank:** [388,526](https://www.similarweb.com/website/hestiacp.com/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo is taken from website header. Brand colour `#ff558f` picked from the website.

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Hey @zcraber - could you please regenerate this ensuring you create the 0.5-1px gap _after_ scaling down to 24px? I'd also remove all the aliases - as they all reference 'Hestia' - which you'll be typing in regardless!

**Comment by zcraber** [comment]
@adamrusted Please check! 
hestia

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
I like this treatment, @zcraber. However, I think the cut-out encroaching on the blue area [here](https://github.com/simple-icons/simple-icons/assets/15157491/b32bd822-f469-4587-9271-95896b7d92db) should be removed, and there are also a few minor differences in yours, mostly along the bottom - [example 1](https://github.com/simple-icons/simple-icons/assets/15157491/5084d7d0-c03f-400b-b616-b88c93b8aaf4), [example 2](https://github.com/simple-icons/simple-icons/assets/15157491/82a7299c-ac8b-4c0e-960c-cbcd69af530c).

And, to offer another possible treatment, what would you and @adamrusted think of the following, in order to try to retain the sense of depth? (Forgive the shoddiness of this one, it was quite rushed!)

image

**Comment by zcraber** [comment]
@PeterShaggyNoble Please check if this looks good.

```xml
m11.98 18.121-.005.079c-.481.989-.962 1.979-1.476 2.952.046-.05.091-.103.137-.159l.007-.013-.005.01.022-.026s-.15.308-.445.719l-.084.121c-.113.14-.221.284-.349.433-.404.471-.824.808-1.243 1.005-1.002.569-2.351.773-4.023-.214-2.225-1.334-2.433-3.457-2.433-6.239l.002-.404S2.784 7.027 2.434 0c0 0 1.23 1.102 1.71 4.571.141 1.016.213 2.234.186 3.691a37.414 37.414 0 0 1-.248 3.695c-.067.674-.12 1.322-.144 1.943a24.965 24.965 0 0 0-.001 1.954c.034.848.11 1.63.22 2.343.221 1.419.574 2.566 1.027 3.409.895 1.668 2.165 2.226 3.591 1.348a2.27 2.27 0 0 1-.883.183l-.362-.025a1.52 1.52 0 0 1-.869-.423c-.379-.277-.706-.724-.973-1.329-.362-.823-.608-1.92-.736-3.262a24.779 24.779 0 0 1-.101-2.263c-.002-.6.014-1.232.043-1.895.027-.607.059-1.24.115-1.897.097-1.414.123-2.672.073-3.79a21.325 21.325 0 0 0-.48-3.766C3.812.999 2.434 0 2.434 0h.017c.343-.001 5.827.132 5.295 9.408a77.024 77.024 0 0 0-.135 4.351c-.001 1.95.096 3.547.276 4.787.64-.967 1.44-2.337 2.407-4.276.666-1.332 1.115-2.198 1.798-2.797h.006c.022-.021.045-.04.068-.06.087-.075.177-.146.269-.214.262-.191.545-.355.848-.469l.015-.005c.523-.191 1.133-.229 1.691.198.054.039.105.082.153.128.255.25.405.586.5.926.035.133.065.268.09.403.038.234.066.469.081.705.011.175.018.35.021.525.012.59-.01 1.18-.034 1.77-.03.745-.066 1.489-.066 2.235 0 .612.024 1.226.102 1.834v.003c.137.343 1.274 2.933 4.414 2.934h.022a6.798 6.798 0 0 0 1.594-.207c.005-.002.011-.002.015-.002h.002c.036.002.045.056.016.085-.424.27-1.314.778-2.081 1.042l-.188.076c-.875.158-1.627.237-2.219.027-1.347-.478-1.721-1.045-2.295-1.945a4.647 4.647 0 0 1-.691-1.786c-.063-.433-.11-.867-.142-1.303-.05-.664-.08-1.329-.089-1.994-.019-1.169.2-2.319.203-3.118-.011-1.001-.26-1.533-.595-1.796-.282-.221-.618-.262-.93-.216-.281.042-.536.15-.692.227a.343.343 0 0 1 .056.008c.334-.104.984-.23 1.379.186.245.259.365.731.259 1.561-.09.801-.26 1.883-.333 3.06a16.64 16.64 0 0 0-.008 2.083c.031.476.092.946.185 1.397.153.744.388 1.437.721 2.029.422.748.989 1.343 1.758 1.669.865.366 1.98.4 3.427-.087l-.073.03c-.037.019-2.296 1.126-4.471.203 0 0-2.489-.92-2.971-4.183a13.719 13.719 0 0 1-.129-1.311Zm.433-5.03-.003-.001-.112.319c-.542 1.399-1.792 3.743-2.628 5.189-.411.71-.832 1.414-1.255 2.116.19.432.257.521.382.678.179-.271.272-.462.436-.742 1.04-1.779 1.733-2.963 2.477-4.697.089-1.182.58-2.081.703-2.862ZM10.314 21.5l.034-.064.094-.103-.128.167Z```

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @zcraber?

**Comment by zcraber** [comment]
> Are you still working on this one, @zcraber?

Sorry, didn't get time to look into it.

**Comment by adamrusted** [comment]
Closing due to inactivity.

**Pull request closed without merging**
