### PR TITLE
Add Max-Planck-Gesellschaft Icon

### LINKED ISSUE #3787: Request: Max Planck Society Icon
**Name:** Max Planck Society
**Website:** http://www.mpg.de/en // https://en.wikipedia.org/wiki/Max_Planck_Society
**Alexa rank:** 29,904

**Official resources for icon and color:**
**SVG**: https://upload.wikimedia.org/wikipedia/en/c/c9/Max-Planck-Gesellschaft.svg
**Color**: Pantone 328 (Deriviations: https://store.pantone.com/de/de/colorfinder/index/acfproduct/code/328+C)

### PR DESCRIPTION
**Pull request by fbernhart**
maxplanckgesellschaft

Close #3787 
**Alexa rank:** 29,904
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I've used the color hex value from the official logo guidelines: https://www.mpikg.mpg.de/6335559/Logo-Guide-Print-_-Max-Planck-Gesellschaft.pdf

### CODE REVIEW

**Comment by Kalaschnik** [comment]
@fbernhart ; Why were you not using the #007367 as suggested by the official Pantone website for hex: https://store.pantone.com/de/de/colorfinder/index/acfproduct/code/328+C?
Your color (#007D7A) is not as close as (#007367) to Pantone 328C.

**Comment by fbernhart** [comment]
@Kalaschnik Thanks for your input! :) I've actually just used the color that was already used in the .svg file from Wikimedia - from the link that you've provided in your issue (#3793). This color has the hex value #007367.

Now I've just checked [their website](https://www.mpg.de/de) and the header and footer are using the color #006C66.

I've googled a bit and found an official style guide for their logo:  https://www.mpikg.mpg.de/6335559/Logo-Guide-Print-_-Max-Planck-Gesellschaft.pdf

On page 6 it mentions as well the color: #006C66

So I think it will be the best to stick to #006C66. I'll add a commit to change it right now.

**Comment by Kalaschnik** [comment]
Thank you so much for investigating! Seems best to go for #006C6 then!

**Comment by adamrusted** [comment]
There's an [SVG embedded in the homepage](https://www.mpg.de/assets/responsive/minerva-e398a023178e28b57ee5b5011fbcd6cbc49783ca3e9dee2bee3ff9d4203bf45c.svg) - would we be better to reference that as a source than Wikipedia?

**Comment by fbernhart** [comment]
@adamrusted Thanks for pointing this out! This has actually been my first PR for simple-icons.

No wonder, that I've missed this 😄

**Comment by fbernhart** [comment]
@adamrusted Should be fine now. Please check again and feel free to merge it, if it's ok. 😊

**Review by adamrusted — APPROVED** [review]
LGTM 🎉

**Comment by Kalaschnik** [comment]
@adamrusted, how long does it take after a merged PR, that the icon appears on simpleicons.org / is usable?

**Comment by adamrusted** [comment]
> @adamrusted, how long does it take after a merged PR, that the icon appears on simpleicons.org / is usable?

So the new icon are added to the 'develop' branch, which is automatically released once a week on a Sunday. Unfortunately we just missed the last release - but does mean it should be included at the end of this week!

**Comment by Kalaschnik** [comment]
Thanks for the info.

**Pull request merged**
