### PR TITLE
Add Qlik icon

### LINKED ISSUE #8751: Qlik Sense
### Brand Name

Qlik Sense

### Website

https://www.qlik.com/

### Popularity Metric

The Similar web rank is 53,745. See https://www.similarweb.com/website/qlik.com/#overview

### Official Resources for Icon and Color

color: #009845
png: https://www.qlik.com/us/-/media/images/qlik/global/qlik-logo-2x.png?rev=1167e952ae934867bc9ee7f3d4952e1f
Guidelines: https://www.qlik.com/us/-/media/files/legal/trademarks/qlik-full-trademark-list.pdf?rev=030ea00e206e4b2ba3c1595525be6708&hash=969CC8940082C9454A1273F2AA423116

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
qlik

**Issue:** closes #8751 

**Similarweb rank:** 53,461. See https://www.similarweb.com/website/qlik.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from website header https://www.qlik.com
Color: `#009848` Taken from logo

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
I can spot a [slight difference](https://github.com/simple-icons/simple-icons/assets/1830867/85b54887-affc-4f91-8713-1c1fa02835d7) between the PR in black, and the source icon in red. Could you take another look please @PratyushJayachandran 🙏

**Comment by PratyushJayachandran** [comment]
> I can spot a [slight difference](https://github.com/simple-icons/simple-icons/assets/1830867/85b54887-affc-4f91-8713-1c1fa02835d7) between the PR in black, and the source icon in red. Could you take another look please @PratyushJayachandran 🙏

I have attempted a fix. I removed the R symbol and then scaled.
This is the source I used
```
<svg role="img" viewBox="0 0 154 47" xmlns="http://www.w3.org/2000/svg"><title>Qlik</title>
<path fill="#009848" d="M152.61 39.571l-6.06-5.097c2.103-3.351 3.35-7.308 3.35-11.55 0-11.943-9.696-21.639-21.638-21.639-11.942 0-21.638 9.696-21.638 21.639 0 11.942 9.696 21.638 21.638 21.638 4.634 0 8.948-1.462 12.477-3.957l6.452 5.419s.963.82 1.783-.143l3.85-4.563c-.036 0 .748-.962-.214-1.747zm-11.051-16.647c0 7.343-5.953 13.296-13.297 13.296-7.343 0-13.297-5.953-13.297-13.296 0-7.344 5.954-13.297 13.297-13.297 7.344 0 13.297 5.953 13.297 13.297z"></path>
<path fill="#54565B" d="M119.706 22.924a8.52 8.52 0 018.52-8.52 8.52 8.52 0 018.52 8.52 8.52 8.52 0 01-8.52 8.52 8.52 8.52 0 01-8.52-8.52zm29.268-15.258a2.35 2.35 0 012.352-2.353 2.35 2.35 0 012.353 2.353 2.374 2.374 0 01-2.353 2.353 2.374 2.374 0 01-2.352-2.353zm2.352-2.067c-1.105 0-1.996.89-1.996 2.032 0 1.14.856 2.031 1.996 2.031 1.141 0 1.997-.89 1.997-2.031-.036-1.106-.856-2.032-1.997-2.032zm-.534 3.493h-.321V6.205h1.034c.499 0 .89.25.89.784 0 .463-.249.748-.676.784l.82 1.283h-.393l-.748-1.283h-.57v1.32h-.036zm0-1.568h.641c.392 0 .642-.072.642-.535 0-.357-.285-.5-.642-.5h-.641v1.035z"></path>
</svg>
```

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for the speedy update @PratyushJayachandran!
I'm still spotting a slight difference (see below, with PR in black) - this might be entirely down to the SVGO precision though, could you try with a precision of 4?
image

**Comment by PratyushJayachandran** [comment]
> Thanks for the speedy update @PratyushJayachandran! I'm still spotting a slight difference (see below, with PR in black) - this might be entirely down to the SVGO precision though, could you try with a precision of 4? 

Had to increase precision. Thanks for reviewing!

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @PratyushJayachandran 🎉

**Pull request merged**
