### PR TITLE
Kingston Technology icon

### PR DESCRIPTION
**Pull request by adsingh14**
**Issue:** #6933
**Alexa rank:** 17,816
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

kingstontechnology

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @adsingh14, i am not sure on this.

The original has different color schemes.
image

**Comment by LitoMore** [comment]
They have some black and white usages on their product.

FYI: https://cmc-kingston.assetbank-server.com/assetbank-kingston/action/viewAsset?id=11361&index=2&total=3&view=viewSearchItem

**Comment by adsingh14** [comment]
> They have some black and white usages on their product.
> 
> FYI: https://cmc-kingston.assetbank-server.com/assetbank-kingston/action/viewAsset?id=11361&index=2&total=3&view=viewSearchItem

Exactly! Still it's not accepted.

**Comment by LitoMore** [comment]
> Still it's not accepted.

That's because the icon you provided is incorrect.

image image

**Review by dirien — APPROVED** [review]
hi @adsingh14,

looks very good for me

image

**Pull request merged**
