### PR TITLE
Add Afterpay

### LINKED ISSUE #9771: Missing Afterpay icon
### Brand Name

Afterpay

### Website

https://www.afterpay.com/en-AU

### Popularity Metric

Buy now pay later brands are very popular . Afterpay Limited is an Australian financial technology company best known for its buy now, pay later service. It operates in Australia, the United Kingdom, Canada, the United States, and New Zealand. Afterpay was founded in 2014 by Nick Molnar and Anthony Eisen.

I want to use this icon to show in our footer that we accept it.

### Official Resources for Icon and Color

https://www.afterpay.com/en-AU/business/resources/marketing/brand-tools/brand-guidelines

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by service-paradis**
image

Sticker version:
image

**Issue:** closes #9771

**Similarweb rank:** [~1,4k](https://www.similarweb.com/website/afterpay.com/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Took the logo `Logos/Logo Black/AP_logo_lockup_flex_blackclear_eps.eps` from the Zip file at https://www.afterpay.com/en-AU/business/resources/marketing/logos
- Took the primary color from https://www.afterpay.com/en-AU/business/resources/marketing/brand-tools/colour-palette

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
We might have to go with the full logo, @service-paradis. [This page](https://www.afterpay.com/en-AU/business/resources/marketing/asset-library) states:
> Our logo is made up of two elements: the Loop and the word Afterpay. **They must always appear together** and only in the colours specified.

Having said that, though, both the "[Dos & Don'ts](https://www.afterpay.com/en-AU/business/resources/marketing/brand-tools)" and the [brand guidelines](https://www.afterpay.com/en-AU/business/resources/marketing/brand-tools/brand-guidelines) confuse the issue by mentioning a "sticker" version with a circle background, so if we _are_ going to run with just the icon then I think that's the version we should use. What do you reckon?

**Comment by service-paradis** [comment]
Their guidelines are not easy to follow!
They have examples with logo only as you said as Sticker or as App Icon:
image

You're right that, without wordmark, we probably need to use the sticker version. I will make the change!

**Comment by PeterShaggyNoble** [comment]
Yeah, I had considered the "app" version as well but, as it appears that it's intended to represent the app _only_ and we can't guarantee that that's what our users would use it for, I though the "sticker" version would be our safer option.

**Comment by service-paradis** [comment]
> Yeah, I had considered the "app" version as well but, as it appears that it's intended to represent the app _only_ and we can't guarantee that that's what our users would use it for, I though the "sticker" version would be our safer option.

Just pushed the sticker version. I extracted directly the logo from the Brand Guidelines PDF.

**Comment by PeterShaggyNoble** [comment]
@service-paradis, looks like you forgot to push the updated SVG.

**Comment by service-paradis** [comment]
> @service-paradis, looks like you forgot to push the updated SVG.

Done!

**Review by PeterShaggyNoble — APPROVED** [review]
All looks good to me 👍🏻 Although there are a few excess points in the cut-out that could likely be removed, if you want to try before merging.

**Comment by service-paradis** [comment]
Just removed some of them!

**Pull request merged**
