### PR TITLE
Add CoinMarketCap

### LINKED ISSUE #5113: CoinMarketCap
**Brand Name: CoinMarketCap**
**Website: https://coinmarketcap.com/**
**Alexa rank:**
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by mondeja**
image

**Issue:** Resolves #5113
**Alexa rank:** [223](https://www.alexa.com/siteinfo/coinmarketcap.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Icon from [website](https://coinmarketcap.com/) header.
- Color from icon.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I'm seeing one [small difference](https://user-images.githubusercontent.com/15157491/110659354-6991e000-81ba-11eb-9c08-9ac059912fe4.png) in the right of the "M", @mondeja - could you take another look at that please?

**Comment by PeterShaggyNoble** [comment]
In the interests of getting this one off @mondeja's plate (and out of our backlog), I've pushed an updated path that should fix the imperfection above. Could one of the other @simple-icons/maintainers throw an eye over it, please?

**Comment by service-paradis** [comment]
> In the interests of getting this one off @mondeja's plate (and out of our backlog), I've pushed an updated path that should fix the imperfection above. Could one of the other @simple-icons/maintainers throw an eye over it, please?

Looking good! I'm seeing some extra points that could be removed though at the far right:
image

**Comment by jorgeamadosoria** [comment]
I've removed two points in the right, possibly the ones that @service-paradis was talking about. This looks done now, so I'm going to proceed to merged it. Good work everyone.

**Pull request merged**
