### PR TITLE
Add Muni

### LINKED ISSUE #2821: Request: SF Muni Icon
**Name:** SF Muni
**Website:** https://www.sfmta.com/
**Official resources for icon and color:** https://en.wikipedia.org/wiki/San_Francisco_Municipal_Railway 
  

In the SFMTA [vehicle decal design standards document](http://mission.sfgov.org/oca_bid_attachments/FA52440.pdf), the Muni logo color is referenced as [Pantone 200 C](https://www.pantone.com/color-finder/200-C) which translates to `#BA0C2F`. However, the color of the Muni logo on the linked Wikipedia page is `#CC3847`.

### PR DESCRIPTION
**Pull request by samuelpolat**
muni

**Issue:** Closes #2821 & #2822 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I selected `#BA0C2F` from the [SFMTA vehicle decal design guidelines](http://mission.sfgov.org/oca_bid_attachments/FA52440.pdf) (p. 25) as discussed.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks, @samuelpolat.

However, you've managed to include the [MTA](https://github.com/simple-icons/simple-icons/pull/2820) icon in this PR too. 🙈

Path looks good when compared to the source - it just needs to be centred horizontally on the canvas. When compared with the version on page 25 of the PDF you linked, though, there are some differences (your version in red below) so I think we should go with that one.

From Wikipedia and to prevent any possible future naming clashes, I'd suggest using the full name here. "SF Muni" might also work, though. Thoughts, @simple-icons/maintainers?

Note that for logos sourced from Wikipedia or Wikimedia, we use the file's page as the source (https://commons.wikimedia.org/wiki/File:Muni_worm_logo.svg, in this case).

**Comment by samuelpolat** [comment]
I am very sorry for the MTA mixup. I have never submitted a pull request prior to simple-icons, still need to figure this whole thing out. 😅 

I have checked the source of the Muni worm logo from Wikimedia and it seems like it is from the [latest train schedule](http://www.actransit.org/wp-content/uploads/HSP_CC-sched.pdf) (`Revised February 20, 2020` in the bottom right corner). The [SFMTA vehicle decal design guidelines](http://mission.sfgov.org/oca_bid_attachments/FA52440.pdf), I linked previously is from 2015. It seems like the SMTA changed the logo in 2017, when you look at the Wikimedia file history. The color is still the same though.

**Comment by PeterShaggyNoble** [comment]
> I am very sorry for the MTA mixup, @PeterShaggyNoble. I have never submitted a pull request prior to simple-icons, still need to figure this whole thing out.

No problem, we all learned once 🙂 Fixing it should be as simple as deleting the MTA icon from your `muni` branch and removing its data from `simple-icons.json`.

> I have checked the source of the Muni worm logo from Wikimedia and it seems like it is from the latest train schedule (Revised February 20, 2020 in the bottom right corner). The SFMTA vehicle decal design guidelines, I linked previously is from 2015. It seems like the SMTA changed the logo in 2017, when you look at the Wikimedia file history. The color is still the same though.

Nice detective work :+1: I'd agree that the newer PDF should definitely supercede the older. Aside from the vertical centring issue, your path lines up perfectly with the logo in the PDF.

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @samuelpolat?

**Comment by samuelpolat** [comment]
@PeterShaggyNoble I have been very busy with work lately. I might get it done in the evening or earlier tomorrow.

**Comment by PeterShaggyNoble** [comment]
No rush; I just wanted to check you hadn't abandoned it before closing it as such 🙂

**Comment by PeterShaggyNoble** [comment]
Closing this out as abandoned due to inactivity; I'll submit a fresh PR for it shortly.

**Pull request closed without merging**
