### PR TITLE
Added SymPy

### LINKED ISSUE #3324: Add SymPy Icon
**Name:** SymPy
**Website:** https://www.sympy.org/
**Alexa rank:**
  

**Official resources for icon and color:**
  
  

[https://www.sympy.org/en/index.html](https://www.sympy.org/en/index.html)
[https://www.sympy.org/static/images/logo.png](https://www.sympy.org/static/images/logo.png)

### PR DESCRIPTION
**Pull request by adamrusted**
sympy

**Issue:** Closes #3324
**Alexa rank:** [225,126](https://www.alexa.com/siteinfo/sympy.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This was a fun one! 🤯
SVG taken from source and shapes simplified as much as possible, with outline of snake being used to differentiate between snake and cube.

### CODE REVIEW

**Review by iamrajiv — APPROVED** [review]

**Comment by PeterShaggyNoble** [comment]
Oh, this one is an absolute jerk! 😮 I remember trying it myself a few months back and tearing my hair out!

Seeing quite a few differences, I'm afraid 🙁 Might give it another try myself later but I seem to remember Inkscape no liking the strokes in the source file _at all_.

image

**Comment by adamrusted** [comment]
@PeterShaggyNoble I think some of the problem is that I've gone with the 'inner paths' of the cube and the snake, instead of the outer strokes - so that'll throw off any comparison by a bit.

**Comment by PeterShaggyNoble** [comment]
Ah, yes, the strokes may have been throwing off my comparison. Removing them from the left panel [gets me a little closer](https://user-images.githubusercontent.com/15157491/109520473-2cd03580-7aa4-11eb-858a-77d7b1574516.png) and from the top panel, too, [slightly closer still](https://user-images.githubusercontent.com/15157491/109520643-5f7a2e00-7aa4-11eb-913f-3367e6f9cdbb.png) but neither quite perfect. And, thanks to Inkscape completely butchering pretty much all the strokes when converting them to paths (it can't even handle the tongue!), I'm unable to recreate it myself so that I'm at least comparing like with like. I think we'll need one of the other @simple-icons/maintainers with better software to throw an eye over this one.

**Review by mondeja — APPROVED** [review]
I'm able to fit this perfectly with the source. Altough the circles may be subject to interpretation, I think the chosen treatment is a good compromise.

Merging this as is. Nice work @adamrusted :ok_hand:

**Pull request merged**
