### PR TITLE
Add JCB

### LINKED ISSUE #2370: JCB (Credit card)
**Name:** JCB
**Website:** https://www.global.jcb/en/index.html
**Official resources for icon and color:**
The official JCB site's brand page is [blurry](https://www.global.jcb/en/about-us/brand-concept/agreement/) so [here I picked up the home logo itself in this link](https://www.global.jcb/en/common/images/svg/jcb_emblem_logo.svg). Colors are straight blue, red, and green.

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
image

**Issue:** Closes #2370

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon from website footer (thanks, @ericcornelissen), colour lifted from brand colour image.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
@ericcornelissen, from the GIF at the end of https://www.global.jcb/en/about-us/brand-concept/

**Comment by ericcornelissen** [comment]
I'm not sure how reliable picking a colour from a `.gif` is 🤔 (I thought gifs have/used to have a limited colour spectrum available)

In the `<navbar>` of that page they use a gradient ending with `#004794`, which comes pretty close...  In [the SVG linked in the issue](https://www.global.jcb/en/common/images/svg/jcb_emblem_logo.svg) (which can also be found [on wikimedia](https://commons.wikimedia.org/wiki/File:JCB_logo.svg)) the darkest blue is `#1F286F` (with intermediates `#004E94` and `#0066B1`  and as lightest blue `#006FBC`)

With all that, I'm not sure what we should use 🤷‍♂ Though given their website design I do agree it should be blue. Any input from others or other @simple-icons/maintainers?

**Comment by runxel** [comment]
I'm okay with `#0b4ea2`.
While, yes, gifs do have a limited color palette it doesn't matter here, since were under 256 total colors. In the end: There so many blues which are really close to each other: We shouldn't worry too much :)

**Comment by phatbhoy67** [comment]
I am happy to merge this one in, thanks for your work on this @PeterShaggyNoble 👍

**Pull request merged**
