### PR TITLE
Add Litecoin

### LINKED ISSUE #2186: Litecoin
**Name:** Litecoin
**Website:** https://litecoin.org/
**Alexa Rank:** [~175k](https://www.alexa.com/siteinfo/litecoin.org)
**Colour:** `#a6a9aa`
**Official resources for icon and color:** https://litecoin-foundation.org/wp-content/uploads/2019/01/LC18-007-Brand-guidelines.pdf

[Litecoin](https://github.com/simple-icons/simple-icons/files/3988009/litecoin.zip)

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Litecoin

**Issue:** Closes #2186

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by phatbhoy67** [comment]
I'm getting some small differences in the path @PeterShaggyNoble see image below for example:
lite-diff

**Comment by PeterShaggyNoble** [comment]
Thanks, @phatboy67. I wonder could this be accounted for by us grabbing icons from 2 different sources? I used the blue icon available in the downloads in the PDF I linked.

**Comment by phatbhoy67** [comment]
I clicked the "CLICK TO DOWNLOAD ICONS" button within the .pdf you linked which opens dropbox.

I used the .svg 👇 

(https://www.dropbox.com/sh/0wtenvse624vm1j/AABWEy6T6_LuWSB1PeuLaF78a/SVG/Coin/Coin%20full%20colour.svg?dl=0)

**Comment by PeterShaggyNoble** [comment]
Same place I sourced it, so (although I think I might have used https://www.dropbox.com/sh/0wtenvse624vm1j/AAAm5l7-pR1RZBwRTT_jRbuca/SVG/Coin?dl=0&preview=Coin+blue.svg&subfolder_nav_tracking=1).

As I mentioned in another PR, I won't be back at a computer for another few days so if you, or someone else, wants to tweak this in the meantime, work away.

**Comment by PeterShaggyNoble** [comment]
Icon updated.

**Comment by phatbhoy67** [comment]
Looks great @PeterShaggyNoble thanks for updating 👍

**Pull request merged**
