### PR TITLE
Add Backstage logo

### LINKED ISSUE #7948: Request: Backstage icon
### Brand Name

Backstage

### Website

https://backstage.io/

### Popularity Metric

https://www.similarweb.com/website/backstage.io/#overview

### Official Resources for Icon and Color

https://backstage.io/docs/overview/logos

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by marcopollivier**
**Issue:** closes #7948

**Similarweb rank:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This PR adds the Backstage logo 

I based this PR with the original documentation https://backstage.io/docs/overview/logos

### CODE REVIEW

**Comment by marcopollivier** [comment]
@LitoMore this thread helped me a lot. https://github.com/simple-icons/simple-icons/pull/7908#issuecomment-1266943734

Is it makes sense to be part of the documentation?

**Comment by LitoMore** [comment]
@marcopollivier The problems you'll run into when processing with icons can vary, and the ones I've mentioned in the comments are just the smoothest. In practice, there may be more problems, and if you want to write a document, it will be complicated and difficult to read.

We already have several related discussions, and I prefer to share the basic principles of SVG and how to use the editor, rather than writing a step-by-step tutorial:

- https://github.com/simple-icons/simple-icons/discussions/5076
- https://github.com/simple-icons/simple-icons/discussions/7603
- https://github.com/simple-icons/simple-icons/discussions/4935
- https://github.com/simple-icons/simple-icons/discussions/6689

**Comment by marcopollivier** [comment]
Hmmm. Makes sense. 🤔

**Review by LitoMore — CHANGES_REQUESTED** [review]
CleanShot 2022-10-15 at 20 48 44@2x

@marcopollivier There are some differences.

According to their [guidelines](https://backstage.io/logo_assets/Backstage_Identity_Assets_Overview.pdf), we'd better use the [teal one](https://github.com/backstage/backstage/blob/master/microsite/static/logo_assets/svg/Icon_Teal.svg) as a reference.

These links can be found at https://backstage.io/docs/overview/logos.

**Comment by marcopollivier** [comment]
@LitoMore I changed, but I'd like to validate as you did 🤔

**Review by dirien — APPROVED** [review]
Hi @marcopollivier ,

Thanks for your contribution to simple-icons!

It's a perfect fit:
image

**Comment by LitoMore** [comment]
@marcopollivier For reviewing the difference, see https://github.com/simple-icons/simple-icons/pull/7752#issuecomment-1238557522.

**Pull request merged**
