### PR TITLE
Manual patching of icons (#2061)

### PR DESCRIPTION
**Pull request by runxel**
**Issue:** 
https://github.com/simple-icons/simple-icons-font/issues/29
and #2061

### Checklist
[x] yes.

### Description

What I am doing here is basically cleaning my own mess:
The icon for ABB robotstudio was one of my first contributions here. It was minimized using SVGOMG, which has problems – see issues linked above for more info.

I will continue to update all icons which has these problems here. This first PR should be merged by one of you @simple-icons/maintainers, so you know whats going on. The next ones I should be able to merge alone.
The correction is actually done quite easily (if you want to help):
1. See what icon has a problem (the Travis build for the font will tell you).
2. Optimize the logo again with svgo (locally!!!).
  It will correct the problems without changing the overall structure.
3. merge back in.
4. profit :)

### CODE REVIEW

**Comment by ericcornelissen** [comment]
I'm not against doing this in theory, though I would prefer one giant PR for all the icons at once 😄

If you're doing it for https://github.com/simple-icons/simple-icons-font/issues/29 then I would like to inform you that was planning to try and include the transformation you describe above in the build process of the simple-icons-font. So, in that regard this is not necessary. (I have been thinking this for a while, but seen as the font isn't particularly popular it just doesn't have high priority)

Lastly, until we can fix this for new contributions I think this will be too time consuming to do... I actually think an automated fix for this can be implemented with GitHub Actions (as opposed to #2420) If you are very concerned about this issue I will move creating it to the top of my priority list for Simple Icons 😃

**Comment by runxel** [comment]
> I'm not against doing this in theory, though I would prefer one giant PR for all the icons at once 😄

Oh yeah, sure, that would be better.
I just wasn't smart enough how to get a list all the shady icons at once. (which then could be automatically put thru svgo.)

> If you're doing it for [simple-icons/simple-icons-font#29](https://github.com/simple-icons/simple-icons-font/issues/29) then I would like to inform you that was planning to try and include the transformation you describe above in the build process of the simple-icons-font. 

You mean there will be no need for people to optimize their icons by hand, but instead our CI will do that and push the optimized svg back?
Well, would be neat! Even easier for people to contribute then.

> Lastly, until we can fix this for new contributions I think this will be too time consuming to do... I actually think an automated fix for this can be implemented with GitHub Actions 

Do you want to run all existing icons thru a GH action?

> If you are very concerned about this issue I will move creating it to the top of my priority list for Simple Icons 😃

Haha 🙈 no no, its okay :D

**Comment by ericcornelissen** [comment]
> > If you're doing it for simple-icons/simple-icons-font#29 then I would like to inform you that was planning to try and include the transformation you describe above in the build process of the simple-icons-font.
>
> You mean there will be no need for people to optimize their icons by hand, but instead our CI will do that and push the optimized svg back?
> Well, would be neat! Even easier for people to contribute then.

Sorry for the confusion, that particular comment was meant to apply solely to **simple-icons/simple-icons-font**. My idea was to update [it's build pipeline](https://github.com/simple-icons/simple-icons-font/blob/36000da53a092b8bf36edee589e1d12ae5940445/scripts/build.js) to re-optimize the icons at build-time only to make the font.


However...

> > Lastly, until we can fix this for new contributions I think this will be too time consuming to do... I actually think an automated fix for this can be implemented with GitHub Actions
>
> Do you want to run all existing icons thru a GH action?

Yes! At some point I want that "there will be no need for people to optimize their icons by hand, but instead our CI will do that and push the optimized svg back" (see #2380). Of course this would still require some work from contributors, e.g. fitting it in the 24x24 viewbox, but the SVGO(MG) step will be eliminated. 😄

**Comment by runxel** [comment]
Okay great!
Fixing the icons at the build pipeline helps with those icons, which are currently "corrupted".
Having our CI doing all the heavy lifting will help in the future. Both's fabulous!

However, what's with the existing icons here? They would still be bad, since the iconfont only does the fixing at build time and doesn't give the fixed icons back to this repo.
Maybe I can find a solution to still find & fix those.... 🤔

**Comment by ericcornelissen** [comment]
> Fixing the icons at the build pipeline helps with those icons, which are currently "corrupted".
Having our CI doing all the heavy lifting will help in the future. Both's fabulous!

👍 


> However, what's with the existing icons here? They would still be bad, since the iconfont only does the fixing at build time and doesn't give the fixed icons back to this repo.

Those do indeed still need to be fixed, however, if you start doing that before we have fixed the source of problem you will need to keep updating. If we do it once after we implemented a fix for the problem we can patch it and send out a patch-release immediately. Especially since, as far as I can tell, there is no gain for doing it now I don't really see a reason to do it.

Then again, as I said before, do feel free to do update them now 🙂 

One thing you could try to investigate is see if you can automate the detection of "corrupted" icons so that fixing them can be automated 🤔

**Comment by ericcornelissen** [comment]
I will close this now due to inactivity (both here and w.r.t. #2061)

**Pull request closed without merging**
