### PR TITLE
Use tabs

### LINKED ISSUE #11741: Change indentation of `simple-icons.json` to tab
As the number of icons increases, our files become larger and larger. We are currently using 4-space indentation. This can be optimized with tabs.

Here are file sizes in different formats:

|4-space|tab|minified|
|:-|:-|:-|
|563 KB|422 KB|347 KB|

We can also change the distribution file to minified JSON.

### TODO

- [x] Optimize distribution file to minified JSON (#11903)
- [ ] Change all space-indent to tab-indent (except YAML)

### PR DESCRIPTION
**Pull request by LitoMore**
Resolves #11741

Markdown keeps spaces due to https://github.com/prettier/prettier/issues/8782

### How do I resolve conflicts on this PR

1. Copy the code from develop to the branch
2. Run `npm run format`
3. Done

### How to resolve conflicts after this PR

1. Press the dot key <kbd>.</kbd> on the PR page to open the VS Code web
2. Open `simple-icons.json` from file explorer
4. Click the indentation button `Spaces: 4` on the bottom status bar
5. Select `Convert Indentation to Tabs` from the popup command palette
6. Save and commit changes (There is a Git icon on the left sidebar)
7. Done

### CODE REVIEW

**Comment by mondeja** [comment]
I'm fine with the change. The main problem is that we're going to receive conflicts in 130 PRs (aprox).

Do you see this as a big problem? Do you think it would be worth reducing the number of PRs before merging?

**Comment by adamrusted** [comment]
@mondeja - from experience ~130 PRs is quite low for us with our current capacity - and those of us reviewing PRs are more than capable of fixing merge conflicts. Might just be worth biting the bullet and getting this change in as part of v14?

**Comment by LitoMore** [comment]
> The main problem is that we're going to receive conflicts in 130 PRs (aprox).

It's not a big problem since GitHub has the VS Code web for editing files. This only requires two simple clicks.

**Review by mondeja — APPROVED** [review]
Let's go! 🤞🏼

**Pull request merged**
