### PR TITLE
Add Mumble

### LINKED ISSUE #4212: Request: Mumble Icon
**Name:** Mumble
**Website:** https://mumble.info
**Alexa rank:** 280,061
  

**Official resources for icon and color:** https://mumble.info

### PR DESCRIPTION
**Pull request by Mstrodl**
Mumble

**Issue:** Closes #4212
**Alexa rank:** 261,082
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The original is kind of messed up (off-center, not a perfect circle, messed up paths) so I wasn't sure how many changes I should make. I fixed the circle and recentered everything, but I left the weird paths for consistency.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @Mstrodl, and thanks for taking this one on 🙂

Off, that source SVG really is a mess! 😮 Great job so far in cleaning it up. However, we do endeavour to stay as faithful as possible to the source material, only correcting minor imperfections and obvious errors so I think for this one we'll need to retain the relative size and positioning of the elements. Could you look into updating that, please?

**Comment by Mstrodl** [comment]
@PeterShaggyNoble Honestly the degree at which I changed things was stuff that can basically be chalked up to either running it through an SVG optimizer or removing some values beyond the decimal point (in the case of the circle). If you still really want me to redo this I guess I can add it to my todo list.

**Comment by PeterShaggyNoble** [comment]
Sorry, @Mstrodl, forgot to get back to you on this one. Not wanting to ask you to make changes unnecessarily because the source SVG is so terrible, I asked one of the other team members to double check in case my comparison was wrong and they're seeing the same differences as I am below, with your version in red overlaid on the original in black.

**Comment by adamrusted** [comment]
Hi @Mstrodl, are you still working on this PR?

**Comment by Mstrodl** [comment]
@adamrusted My bad, I haven't, but I can do it real quick

**Comment by adamrusted** [comment]
> @adamrusted My bad, I haven't, but I can do it real quick

No worries, just wanted to check in before I closed it. Take your time with it 👌

**Comment by Mstrodl** [comment]
So I guess I should keep the imperfect circle and stuff?

**Comment by adamrusted** [comment]
> So I guess I should keep the imperfect circle and stuff?

Looking back at @PeterShaggyNoble's comments, I would say yes? We need to try and maintain the aspect ratio of the original icon, so if that was an imperfect circle - we should definitely try to maintain that.

**Comment by Mstrodl** [comment]
@adamrusted Should be okay now

**Comment by adamrusted** [comment]
Thanks @Mstrodl, that looks good to me apart from [a couple differences](https://user-images.githubusercontent.com/1830867/112170042-a4e4d380-8bea-11eb-885e-8da786e0cfcb.png) but I'm not sure if that's differences between your PR and source, or whether that'd Affinity Designer not wanting to play! Will ask another @simple-icons/maintainers to look at this one before we merge it. Excellent job tackling an awkward icon! 🚀

**Comment by Mstrodl** [comment]
@adamrusted might be some rounding errors or something... I guess I could try again if it's enough of an issue

**Review by PeterShaggyNoble — APPROVED** [review]
Thanks for the update, @Mstrodl. This looks fine to me in Inkscape; I'm not seeing the same difference as Adam.

It could be Inscape that's wrong though so can one of the other @simple-icons/maintainers triple check it in a different editor before we merge it?

**Comment by ericcornelissen** [comment]
> 
> 
> Thanks for the update, @Mstrodl. This looks fine to me in Inkscape; I'm not seeing the same difference as Adam.
> 
> It could be Inscape that's wrong though so can one of the other @simple-icons/maintainers triple check it in a different editor before we merge it?

I'm also not seeing the difference in illustrator, so I'll be merging this in as is 👍 Thanks for the contribution @Mstrodl!

**Pull request merged**
