### PR TITLE
Add NATS.io icon

### PR DESCRIPTION
**Pull request by mrwormhole**
natsdotio

**Issue:**
**Alexa rank:**
305,134

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

This format is the best 24 24 format for the view box. I had it from the community manager of NATS. Why did I pick this hex value? It is because there are 4 colors evenly spread out on the logo so it is hard to decide on which color will be picked out of 4

Used sources
- https://github.com/cncf/artwork/
- https://github.com/cncf/artwork/tree/master/projects/nats
- https://cncf-branding.netlify.app/projects/nats/

This PR can close this issue https://github.com/simple-icons/simple-icons/issues/6076

### CODE REVIEW

**Comment by MrWormHole** [comment]
Special thanks to @hhhapz and @gcolliso, wouldn't be possible without them

**Comment by MrWormHole** [comment]
@service-paradis any way to merge this logo PR anytime soon?

**Comment by jorgeamadosoria** [comment]
> @service-paradis any way to merge this logo PR anytime soon?

I've reviewed your submission vs https://cncf-branding.netlify.app/img/projects/nats/icon/black/nats-icon-black.svg (the black logo in their branding page (https://cncf-branding.netlify.app/projects/nats/). There are discrepancies that need to be addressed:

image

Furthermore, the icon information is:
{
    "title": "NATS.io",
    "hex": "27AAE1",
    "source": "https://nats.io/"
},

However, in this PR you are listing several different pages as used sources. Please choose the one you used for your PR, and use that in the source field for the JSON definition.

I suggest https://cncf-branding.netlify.app/img/projects/nats/icon/black/nats-icon-black.svg, which appears to be the official resource, in SVG and monochrome (so very easy to convert and add to the library).
Can you take another pass at this, @MrWormHole ?

**Comment by MrWormHole** [comment]
@dirien sorry for asking, I saw you were adding some pretty slick logos but could you help with this when you have time? I have no idea how to do this

**Comment by dirien** [comment]
> @dirien sorry for asking, I saw you were adding some pretty slick logos but could you help with this when you have time? I have no idea how to do this

Np, should we chat in slack? I am in the chanel from Openfass too! Let me know!

**Comment by pacoguzman** [comment]
I'm interested in having NATS.io icon, how can I help?

**Comment by mrwormhole** [comment]
hey @pacoguzman , yes you can help, so it needs SVG editing as @jorgeamadosoria mentioned. I don't know how to do but ideally you need to use SVG editing software and adjust the ratio of N like the black area shown above

**Comment by adamrusted** [comment]
Closing as it looks like the fork is now missing.

**Pull request closed without merging**
