### PR TITLE
Add Textpattern icon

### PR DESCRIPTION
**Pull request by philwareham**
Textpattern

Add icon for [Textpattern CMS](https://textpattern.com/).

**Issue:** n/a
**Alexa rank:** [379,874](https://www.alexa.com/siteinfo/textpattern.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @philwareham and thanks for the contribution 👍🏻

The [linter is currently failing](https://github.com/simple-icons/simple-icons/pull/4966/checks?check_run_id=1873001351) due to an ineffective segment - see #4935 for some tips on how to resolve that.

**Comment by philwareham** [comment]
Fixed it now, thanks 🎉

**Comment by PeterShaggyNoble** [comment]
Thanks for the quick update, @philwareham 👍🏻

Is this based off the base-64 encoded SVG found in the website's header or did you use a different source file? When comparing it to that SVG, I'm noticing some subtle differences around the outer edges of both tools as well as in the negative space at the top of the hammer's head. However, as a representative of their brand, if you're happy with those differences then that's good enough approval for us and we can merge this in as-is.

**Comment by philwareham** [comment]
It's a simplified version of the previous icon, more suitable for use at different sizes (i.e. scales better). I'm going to adjust our site logo soon to follow the same subtle improvements to shape. Hope that's OK?

**Comment by PeterShaggyNoble** [comment]
Thanks for the clarification, @philwareham. In that case, we can merge this straight in - nice work 🙂

**Comment by philwareham** [comment]
Thats wonderful - thanks! 👏👏👏

**Comment by philwareham** [comment]
Hmmm, I'm getting an error when I try to download a PDF version of the logo from your site - any idea why? https://simple-icons.github.io/simple-icons-website/?q=Textpattern

**Comment by PeterShaggyNoble** [comment]
That website is a work in progress, @philwareham. Our current website can be found at https://simpleicons.org/

But if you believe you have found an issue or a bug on the new website then please create an issue in [our website's repo](https://github.com/simple-icons/simple-icons-website) and we'll look into it there. In the meantime, PDFs of all released icons are available in [our PDF repo](https://github.com/simple-icons/simple-icons-pdf).

**Comment by philwareham** [comment]
Thanks Peter, seems that the PDF repo lags behind the icon repo so that's why I think (i.e. there is no generated PDF there for our logo at the moment - last revision date on generated PDFs seems to be 28th December).

**Comment by PeterShaggyNoble** [comment]
Didn't spot that but you're right, @philwareham and that's the cause of it not being accessible through the new website. It looks like the problem is related to #4124 which will probably necessitate a reworking of our [SVG to PDF "bot"](https://github.com/simple-icons/svg-to-pdf-bot).

**Comment by fbernhart** [comment]
It's correct that the svg-to-pdf-bot is broken. Therefore there are no new PDFs being created at the moment.

I've already informed @ericcornelissen about that a month ago. He said that he'll look into it once the new website is done and he has some time.

**Comment by ericcornelissen** [comment]
To clarify, indeed the PDF versions of the SVGs are no longer updated or added. This is actually due to changes to 1) the GitHub API and 2) the hosting service we used to use for the SVG to PDF bot (it has nothing to do with the CI service we use). I had attempted to hotfix the problem when the changes to the GitHub API were announced, which seems to have worked for a while but at some point it broke down anyway.

The reason I/we didn't investigate further is because to the best of my knowledge none of our users actually used the PDFs! And we were not particularly interested in keeping them alive for no one. I added them to the website redesign to see if anyone would find it out. Hence, as @fbernhart said, I was planning to look into this maybe after the redesign.

@philwareham, to clarify, are you actually interested in the PDF version of the logo, or were you just checking if the icon you added was available on the website?

**Comment by philwareham** [comment]
@ericcornelissen sorry, no pressure from me, I just spotted the PDF download of our logo didn't work and assumed it was something I'd not set up properly in my original PR. As long as the issue isn't our file, then I'm happy. Have a good afternoon everyone!

**Comment by ericcornelissen** [comment]
No problems @philwareham :smile: Thanks for your input, you did uncover a "bug" in the website and we're glad you reported it! In any case, the SVG you contributed is perfectly fine :+1:

**Pull request merged**
