### PR TITLE
Remove Rome

### LINKED ISSUE #10109: Request for removal of Rome
### Brand Name

Rome

### Reason for Removal

The project has been dropped. However, someone is continuing this project in a different name, called [Biome](https://biomejs.dev/).

---

#### Tasks
- [x] Add Biome #10110
- [x] Remove Rome #10113

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
**Issue:** closes #10109

### Description
Development on Rome has ceased and its GitHub repo has been archived.

### CODE REVIEW

**Comment by CredenceHamby** [comment]
No reason to remove this, its already there just leave it. Some might still need it regardless of the state of the company/brand.

**Comment by PeterShaggyNoble** [comment]
@CredenceHamby, if you can provide data to make a case that Rome is still in widespread enough use to qualify as popular then we can _consider_ temporarily keeping it in our collection as a legacy brand.

**Comment by adamrusted** [comment]
Will continue to merge as no reasons given to keep it.

**Review by uncenter — APPROVED** [review]
100%. From what I've heard Rome has been fully replaced by the community maintained Biome fork, which we already have a logo in our collection for. No need for a legacy hold!

**Pull request merged**
