### PR TITLE
Add Unicode

### LINKED ISSUE #2219: Unicode
**Name:** Unicode
**Website:** https://home.unicode.org/
**Alexa Rank:** [~42k](https://www.alexa.com/siteinfo/unicode.org)
**Colour:** `#5455fe`
**Official resources for icon and color:** Colour lifted from website stylesheet. SVG logo from Wikimedia: https://upload.wikimedia.org/wikipedia/commons/0/09/New_Unicode_logo.svg

3 possibilities for the icon here and, although I'd prefer the first, I think the second might be our best bet as they use it for their favicon.

[UnicodeUnicodeUnicode](https://github.com/simple-icons/simple-icons/files/3994805/unicode.zip)

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Unicode

**Issue:** Closes #2219

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Colour lifted from [website](https://home.unicode.org/) stylesheet.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Apologies for not voicing my opinion in the issue itself earlier, but I would expect the top-right version of the icon to be added. I can't seem to find the logo as you added it anywhere... 🤔

**Comment by PeterShaggyNoble** [comment]
Yup, I agree with that, @ericcornelissen - it's what they use for their favicon. However that leaves us with 2 votes from the team in favour of that version (you & I) and 2 in favour of the version I've used here (@runxel & @birjolaxew). Let's see if any of the other @simple-icons/maintainers weigh in to break the tie.

**Comment by phatbhoy67** [comment]
I think the version below is the better choice (https://home.unicode.org/wp-content/themes/unicode/favicons/apple-touch-icon.png)

icon

There is a version in the website source similar to the PR version of the icon, for safari, available here: (https://home.unicode.org/wp-content/themes/unicode/favicons/safari-pinned-tab.svg) but it seems to be of very poor quality. 👀

**Comment by PeterShaggyNoble** [comment]
Thanks for the feedback, @phatbhoy67 - PR updated to match the (current) majority vote.

It's amazing how bad some of those `safari-pinned-tab.svg`s that Potrace generates can be! Came across [this abomination](https://cdn.imagecomics.com/safari-pinned-tab.svg) for [Image Comics](https://imagecomics.com/) the other day.

**Comment by birjolaxew** [comment]
I can agree with @ericcornelissen and @PeterShaggyNoble. My thumbs up on the comment in the issue wasn't particularly well researched, and was mostly just personal preference under the assumption that all variants were officially used. Since the second version is the only one we can find officially, that would definitely be the one we should add.

**Comment by runxel** [comment]
Yeah, my choice was merely based on personal flavor. So see my vote going to that what's official! :)

**Pull request merged**
