### PR TITLE
Updated Kaspersky

### PR DESCRIPTION
**Pull request by fbernhart**
kaspersky

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by mondeja — COMMENTED** [review]
I'm seeing a very small difference repect to [this localized source (es_ES)](https://www.kaspersky.es/content/es-es/images/homepage/kaspersky-logo.svg). Also, the color is different in this source (`#006D5C`). I don't know what was the exact source used. Can you check this @fbernhart?

**Comment by fbernhart** [comment]
@mondeja Yeah, there is a minimal difference.

If I'm visiting https://www.kaspersky.com it's redirecting me to https://www.kaspersky.de (the German website), which has the following SVG as header:

https://service.maxymiser.net/cm/images-eu/kaspersky-com/A386D9BFC296DBD6F507D510782B63B2D90178927B0784DEE02C9F16DC3DB5DA.svg

The SVGs do look like the same. But the one in the header of the German website uses `#00A88E` as color. 


Acessing kaspersky.com through a webproxy from the US, I'm seeing the same color as on the Spanish kaspersky.es site. This version even seem to be hosted on the German site, as https://www.kaspersky.de/content/de-de/images/homepage/kaspersky-logo.svg returns the same SVG file. But they don't use it (yet?).

I guess the .es and .com version are already using the new color while the .de version is still stuck with the old one. So I'd be in favour of changing it to `#006D5C`.

**Comment by fbernhart** [comment]
Feel free to merge it, if you agree with the color.

kaspersky

**Review by mondeja — APPROVED** [review]
Thanks for the investigation @fbernhart! :+1:

**Pull request merged**
