### PR TITLE
Update Let’s Encrypt icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** #5383

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Let’s Encrypt have official monochrome icon now that will be available soon at https://letsencrypt.org/trademarks/ 🎉 
  - For now, we can find them at https://github.com/letsencrypt/website/pull/1223
- I used `le-logo-lockonly-black.svg`
- I used Inkscape to scale
- I used https://jakearchibald.github.io/svgomg/ to optimize
  - Needed a precision of 4 on this one

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Labelling this as "Pending" until that PR is merged, in case any tweaks are made in the meantime.

**Comment by adamrusted** [comment]
Looks like their PR has now been merged. @service-paradis would you mind updating the source to https://letsencrypt.org/trademarks/ ?

**Comment by service-paradis** [comment]
> Looks like their PR has now been merged. @service-paradis would you mind updating the source to https://letsencrypt.org/trademarks/ ?

The source is already correct:
https://github.com/simple-icons/simple-icons/blob/develop/_data/simple-icons.json#L4792

**Comment by adamrusted** [comment]
So it is! Thought you'd used the PR as your source here - my bad!

**Review by adamrusted — APPROVED** [review]
This looks good to me! Thanks @service-paradis 💪

**Pull request merged**
