### PR TITLE
Add Anytype Icon

### LINKED ISSUE #8877: Add anytype icon
### Brand Name

anytype

### Website

https://anytype.io

### Popularity Metric

Similarweb rank - 420,643
https://www.similarweb.com/website/anytype.io

### Official Resources for Icon and Color

- from [community forum header](https://community.anytype.io) - https://github.com/anytypeio/community/blob/main/assets/anytype-logo.svg
- from GitHub -  https://community.anytype.io/uploads/default/original/2X/4/403be88df2688ebdd1c1e66b9727985419c1ed80.png

I think it's pretty safe to use `#FFFFFF` as their brand color

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by RiteshK-611**
**Issue:** closes #8877

**Similarweb rank:**
Similarweb rank - 420,643
https://www.similarweb.com/website/anytype.io

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This commit resolve issue #8877 by adding Anytype logo in anytype.svg file and by updating simple-icons.json file with icon's data

### Preview
image

### CODE REVIEW

**Comment by adamrusted** [comment]
@RiteshK-611 - the source URL doesn't work anymore. Any chance they've got a similar resource in their new(er) org [here](https://github.com/anyproto)?

**Comment by RiteshK-611** [comment]
> @RiteshK-611 - the source URL doesn't work anymore. Any chance they've got a similar resource in their new(er) org [here](https://github.com/anyproto)?

Hey @adamrusted I'm unable to find the svg logo URL as they updated their repo & resources.
Is it ok if I provide anytype logo png url?

**Comment by RiteshK-611** [comment]
Hey @adamrusted you can close this PR if it looks good

**Review by adamrusted — CHANGES_REQUESTED** [review]
Hey @RiteshK-611 - unfortunately I can see [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/13e874e7-0c0a-4d52-96e8-83eaa7f0c305) when comparing against the source image. Any chance you could review?

**Comment by PeterShaggyNoble** [comment]
Are we _sure_ this is the icon for Anytype itself, and not specific to [their community](https://community.anytype.io)? Their branding is a bit confusing; other than the icon in this PR, there's also the wordmark on [their main website](https://anytype.io), and a pixel wordmark in [their GH org](https://github.com/anyproto).

**Comment by PeterShaggyNoble** [comment]
I'm going to ping @cheggaaa from the @anyproto team here to see if they can help us out in deciding which is the correct icon for our purposes.

**Comment by PeterShaggyNoble** [comment]
Let's proceed with our best guess, which would appear to be the icon in this PR.

@RiteshK-611, could you see if you can fix up the differences [Adam pointed out above](https://github.com/simple-icons/simple-icons/pull/8941#pullrequestreview-1731868556), please?

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
I'm seeing some differences throughout this one, @adamrusted - [here's the "T"](https://github.com/simple-icons/simple-icons/assets/15157491/e4a4e528-228b-4a96-95bd-cc9b0855cb1b) for example, with yours in red.

Also, from their website, I'd still expect black, or maybe pink, for the colour.

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
And, we're back where we started 😆 Their branding really is all over the place!

I'm seeing [some differences](https://github.com/simple-icons/simple-icons/assets/15157491/fbd4e284-044e-481c-88ae-f4c2562ab2e5) (yours in red) in all 4 corners of the new version, @adamrusted.

**Review by service-paradis — APPROVED** [review]
LGTM 🎉, thanks everyone that works on this one!

**Pull request merged**
