### PR TITLE
Add LoopBack icon

### LINKED ISSUE #7421: Add LoopBack icon
### Brand Name

LoopBack

### Website

https://loopback.io/

### Popularity Metric

Similarweb ranking is 245,184

### Official Resources for Icon and Color

svg: https://loopback.io/images/global/loopback-mark-frame-white.svg
color: #3f5dff (from website)

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by Atlinx**
loopback

**Issue:** closes #7421 

**Similarweb rank:** 245,184
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Hex value was picked from the site, and it is also present in the press-kit for the "blue" version of their icon.

### CODE REVIEW

**Review by sisp — CHANGES_REQUESTED** [review]
The original LoopBack icon has some quality issues. For instance, the vertical line at the very left is not perfectly vertical, the path point at the bottom of this almost-vertical line segment has an x-axis coordinate > 0. Also, the y-axis coordinates of this point and the corresponding point at the very right aren't identical.

Any opinions on how to proceed here, @simple-icons/maintainers?

**Comment by mondeja** [comment]
> The original LoopBack icon has some quality issues. For instance, the vertical line at the very left is not perfectly vertical, the path point at the bottom of this almost-vertical line segment has an x-axis coordinate > 0. Also, the y-axis coordinates of this point and the corresponding point at the very right aren't identical.
>
> Any opinions on how to proceed here, https://github.com/orgs/simple-icons/teams/maintainers?

In the past we've only improved the original source if these imperfections were adding much more size to the icon, always fitting with the geometry of the source as much as possible. I have not taken a deep look, but after a first view seems to me that is not necessary for this icon.

Simple Icons is a library that takes brand icons from sources, we don't do the work that graphic designers have to do, but if someone wants to do it optimizing without affecting the original geometry is always welcome 👍🏼

**Review by sisp — APPROVED** [review]
LGTM now! :tada:

**Comment by sisp** [comment]
Thanks for your contribution, @Atlinx! :pray:

**Pull request merged**
