### PR TITLE
Updated AdGuard

### PR DESCRIPTION
**Pull request by adamrusted**
adguard

**Issue:** Contributes to #5251.
**Alexa rank:** [16,968](https://www.alexa.com/siteinfo/adguard.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Outlined version no longer available in footer of website, and AdGuard seem to be using the 'filled' version of the icon on all their socials. Updated the hex to the base colour available in the header SVG.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
There's a media kit page [here](https://adguard.com/en/media-materials.html) (linked from the sitemap in the footer) which includes [this zip](https://cdn.adguard.com/public/Adguard/Mediakits/en/AdGuard_logo.zip) of logos & icons in which all the icons are square so we should probably do the same.

**Comment by adamrusted** [comment]
Good spot @PeterShaggyNoble - I've updated the icon and source to match the link you found.

**Comment by PeterShaggyNoble** [comment]
Looks perfect to me now, @adamrusted :+1: Although there's a duplicate point in the top right of the tick you might be able to remove.

**Comment by adamrusted** [comment]
Well spotted! 👀
Point removed, should be good to go.

**Review by PeterShaggyNoble — APPROVED** [review]
Nice one, @adamrusted :+1:

**Pull request merged**
