### PR TITLE
Add IFTTT

### PR DESCRIPTION
**Pull request by gizmecano**
ifttt

**Issue:** #3298
**Alexa rank:** _circa_ [7'000](https://www.alexa.com/siteinfo/ifttt.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

This pull request is a proposal to include the IFTTT logo (cf. #3298), according to these points:

- the logo seems only a typographical wordmark
- the [_Brand guidelines_](https://ifttt.com/discover/brand-guidelines) does not mention any specific color
- the brand assets only contains full white `#FFFFFF` and black `#000000` examples

### CODE REVIEW

**Comment by gizmecano** [comment]
> This is likely because the SVG is slightly off center, I'm getting 12.001 for the Y position of the SVG

This is particularly strange, because the Y positioning should be at `8.820`px...

ifttt svg

**Comment by PeterShaggyNoble** [comment]
> I think black is the right choice of brand color for this one, based on my limited experience with the brand, but I'm open to some blue (e.g. used on their buttons) as well if someone feels strong about that (if I recall correctly their branding used to be more blue).

Based on their website alone, I'd definitely agree with the black - to me, the blue is a secondary, highlight/accent colour.

**Comment by PeterShaggyNoble** [comment]
@ericcornelissen, after updating the branch to include the new linting step to test the centre of an icon, the build is passing here so looks like what you were seeing might juts have been a rounding issue.

**Comment by gizmecano** [comment]
> (...) the build is passing here so looks like what you were seeing might juts have been a rounding issue.

I'm not sure I understood if I should change something or not... 🤔

**Comment by ericcornelissen** [comment]
Just checked again and it seems everything is correct. My guess is that in my original review I misaligned the two versions of the Logo in my artboard... Apologies for the misunderstanding

**Comment by ericcornelissen** [comment]
Thanks for your work on this @gizmecano, it's much appreciated! :tada:

**Comment by gizmecano** [comment]
I have just edited my first comment to add the word `close` in front of the number of the issue, but this edition seems to do not work retroactively. As this pull request was merged, I suppose mainteners have to close manually the linked issue (#3298)?

**Comment by ericcornelissen** [comment]
Thank you for letting us know it didn't close, I closed it now.

**Pull request merged**
