### PR TITLE
Add Firewalla icon

### LINKED ISSUE #7274: Firewalla
### Brand Name

Firewalla

### Website

https://firewalla.com

### Popularity Metric

The Similarweb rank is 246,296, see https://www.similarweb.com/website/firewalla.com

### Official Resources for Icon and Color

svg: https://github.com/firewalla/firewalla/blob/97f7463fe07b85b979a8f0738fdf14c1af0249a8/extension/diag/static/firewalla.svg
color: `#C8332D`, from button background color taken from their website `.css` file at https://cdn.shopify.com/s/files/1/1766/2665/t/85/assets/theme.css?v=17341612456331214376
website: https://firewalla.com

### Additional Comments

Firewalla is an Intrusion Detection System and Intrusion Prevention System with a modern mobile interface, and a powerful cloud.

### Contributing

Yes

### PR DESCRIPTION
**Pull request by elliotwutingfeng**
image

**Issue:** closes #7274

**Similarweb rank:** 246,296

### Checklist

  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

nil

### CODE REVIEW

**Comment by LitoMore** [comment]
@elliotwutingfeng Those paths need to be combined. Use `Path -> Uniocn` from the menu in Inkscape.

**Comment by LitoMore** [comment]
CleanShot 2022-09-22 at 10 47 59@2x

Perfect fit.

**Comment by elliotwutingfeng** [comment]
Do you think gaps are necessary to preserve the details of the flame?

**Comment by LitoMore** [comment]
@elliotwutingfeng Good point.

I'd prefer to have gaps.

@simple-icons/icon-review Any thoughts?

**Review by dirien — APPROVED** [review]
Hi @elliotwutingfeng,

perfect fit!
image

**Pull request merged**
