### PR TITLE
Land Rover

### LINKED ISSUE #3175: land rover
**Name:roger**
**Website:support27**
**Official resources for icon and color:**
  

https://www.landroverusa.com/index.html

### PR DESCRIPTION
**Pull request by NovaGL**
**Issue:** Closes #3175

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
Extracted and cleaned logo from PDF #3175

simpleicons(2)

### CODE REVIEW

**Comment by NovaGL** [comment]
Done those changes as requested and linked directly to a PDF, although any of these PDFs should do.

https://www.landrover.com.au/download-a-brochure/index.html

After you remove all the paths some of the PDFS actually have a monochrome logo as the base, just needed a little bit of fixing.

**Comment by PeterShaggyNoble** [comment]
Thanks for that, @NovaGL I would suggest, though, https://www.landrover.com.au/download-a-brochure/index.html as the source URL.

Other than that, I'm happy to merge this in pending another review. Seeing as it's still inaccessible, here's the PDF @NovaGL extracted the icon from, so you can compare like with like: 
[landrover.zip](https://github.com/simple-icons/simple-icons/files/4764265/landrover.zip).

**Comment by NovaGL** [comment]
No problem, I just was basing it off this 
> Also, if you've used the PDF as the source, we should go with that for the source URL

**Comment by PeterShaggyNoble** [comment]
Ah, yes, sorry, I should have made that clearer: That suggestion was just for that _particular_ PDF as we couldn't find a page anywhere that linked to it directly. Generally, though, we'd use the page a PDF was found on as the source URL.

**Pull request merged**
