### PR TITLE
Fauna Icon

### LINKED ISSUE #5761: Icon Request:  FaunaDB
**Brand Name:** FaunaDB
**Website:** https://fauna.com
**Alexa rank:** 71,105
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by yuriBaza23**
**Issue:** Fixes #5761 
**Alexa rank:** 17,105
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @yuriBaza23 and thanks for the contribution 🙂

The build is currently failing as the icon is slightly off centre and the `path` element has a `fill` attribute that needs to be removed. Could you look into fixing those up, please?

**Comment by yuriBaza23** [comment]
> Welcome to Simple Icons, @yuriBaza23 and thanks for the contribution 🙂
> 
> The build is currently failing as the icon is slightly off centre and the `path` element has a `fill` attribute that needs to be removed. Could you look into fixing those up, please?

Okay, I can!! 😊

**Comment by adamrusted** [comment]
Hey @yuriBaza23 - are you still working on this one? Given the changes made in v5, you'll have to merge the updated version, and make the relevant changes before pushing any updates.

**Comment by ericcornelissen** [comment]
@yuriBaza23 please let us know if you plan to continue working on this, even if you don't have time for it at the moment. If you don't plan to continue working on this we can close this Pull Request to keep it clear what Pull Request (may) need attention and which ones don't.

**Comment by service-paradis** [comment]
Closing this one for now. Feel free to reopen this PR @yuriBaza23 if you plan to continue your work on this.

**Pull request closed without merging**
