### PR TITLE
Add Misskey icon

### LINKED ISSUE #8410: Request: Misskey Icon
### Brand Name

Misskey

### Website

https://misskey-hub.net/

### Popularity Metric

Misskey is an open source distributed social networking platform.

The repository has [5.7k stars](https://github.com/misskey-dev/misskey) and the Global rank of the official site is [251,465](https://www.similarweb.com/website/misskey-hub.net/#overview).

The largest server "misskey.io"  has a Global Rank of [43,396](https://www.similarweb.com/website/misskey.io/#overview) and [100,000 users](https://misskey.io/about).

Misskey and its forks are hosting by users in a variety of languages and are expected to continue to grow, so it is well worth adding an icon.
> https://join.misskey.page/en-US/instances

### Official Resources for Icon and Color

media kits: https://github.com/misskey-dev/assets

icon png: https://raw.githubusercontent.com/misskey-dev/assets/main/icon.png

color: `#A1CA03` (from [Logo in the repository's README](https://raw.githubusercontent.com/misskey-dev/misskey/develop/assets/title_float.svg))

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by arrow2nd**
misskey

**Issue:** closes #8410

**Similarweb rank:**
repository has [5.7k stars](https://github.com/misskey-dev/misskey) and the largest server "[misskey.io](https://misskey.io/)"  has a Global Rank of [43,396](https://www.similarweb.com/website/misskey.io/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Icons can be found on the following pages.
> https://misskey-hub.net/en/appendix/assets.html#icon

The brand colors were extracted from the SVG image of [the logo in the repository's README]( https://raw.githubusercontent.com/misskey-dev/misskey/develop/assets/title_float.svg).
In addition, `misskey.svg` was created using the portion of this SVG image that had already been split.

screenshot

### CODE REVIEW

**Review by LitoMore — CHANGES_REQUESTED** [review]
CleanShot 2023-04-02 at 16 36 47@2x

@arrow2nd I found some differences. Could you try with higher precision?

**Comment by arrow2nd** [comment]
Thanks for the review.
I changed the Number precision of SVGOMG from 3 to 5.

**Comment by LitoMore** [comment]
CleanShot 2023-04-02 at 21 53 31@2x

@arrow2nd Seems differences are still there. Please make sure you are working on the original one with precision 5.

**Comment by arrow2nd** [comment]
Hmm...

I tried several times with the [original SVG](https://raw.githubusercontent.com/misskey-dev/misskey/develop/assets/title_float.svg) and could not successfully correct the misalignment.
I think this is due to my unfamiliarity with editing SVGs.

I would like to work on this issue, but my personal life has become too busy lately to devote the time, so I would like to close this pull request.

I am so sorry for giving up in the middle of this review, even though you had reviewed it.

**Comment by LitoMore** [comment]
@arrow2nd It's ok. Let me continue on the work.

**Comment by arrow2nd** [comment]
Sorry. Thank you.
Reopened.

**Comment by LitoMore** [comment]
2023-05-24 at 19 18 12@2x

Fixed now.

**Review by LitoMore — APPROVED** [review]

**Pull request merged**
