### PR TITLE
Add Photobucket

### LINKED ISSUE #3213: Photobucket
**Name:**Photobucket
**Website:**https://photobucket.com/
**Official resources for icon and color:**https://photobucket.com/resources/home/svg/pb-logo-inverted.svg (Without text)

https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Photobucket_Logo.svg/1280px-Photobucket_Logo.svg.png (With text)

### PR DESCRIPTION
**Pull request by HanselD**
Photobucket

**Issue:** Closes #3213 
**Alexa rank:** 3896
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I picked the hex value per @PeterShaggyNoble's suggestion on the issue. The blue definitely seems to be their primary color. I was not able to find a brand/style guide so I picked the image from their header.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @HanselD :+1:

It looks like you managed to vertically stretch the path with [this commit](https://github.com/simple-icons/simple-icons/pull/3253/commits/62a6ee5f59e4fba2b124f3278c038b400a8a62c9), the version in [this commit](https://github.com/simple-icons/simple-icons/pull/3253/commits/8cbc6374b79859c751da87e56242100f6acc1dd1) was spot on. Although, it was `24.001` in width, rather than the expected `24`, which should have been caught by the changes in #3107 🤔

**Comment by davidjb** [comment]
@PeterShaggyNoble The linter in #3107 doesn't have a degree of tolerance.  It has a precision of 3 which has the effect of resolving rounding errors in float representations (e.g. if the number was `24.00000000000001` or `23.99999999992` they get resolved to `"24.000"` which becomes `24`).  If the computed size was say `24.00119999999` or any number greater than `24.0005` and less than `24.0015` - including if it happened to actually be `24.001` exactly - then these sizes resolve to be `24.001`.

The other discussion in the PR over in #3250 is talking about allowing a tolerance of 0.001 for centring, so that could be applied to the size linter as well if implemented.

**Comment by HanselD** [comment]
Hi @PeterShaggyNoble , happy to roll it back to [this commit](https://github.com/simple-icons/simple-icons/pull/3253/commits/8cbc6374b79859c751da87e56242100f6acc1dd1). I think the issue was I used IcoMoon first and the lint checks weren't passing. I switched to Inkscape which worked better. Let me know!

**Comment by PeterShaggyNoble** [comment]
@HanselD, if you could roll back to that commit, please, then this should be good to go.

> a tolerance of 0.001 ... could be applied to the size linter as well if implemented.

I don't think we should apply that variance to the size linter, @davidjb as the main reason for it was to catch icons with one or both of its dimensions being `24.001`, as that was the most common issue.

**Comment by HanselD** [comment]
Rolled back! Please let me know if this is good to go

**Comment by PeterShaggyNoble** [comment]
Thanks for that, @HanselD 

You've managed to remove `package-lock.json` and `package.json` from your branch, though - could you restore them, please?

On the SVG, it's still coming in at `24.001` wide, which can usually be rectified by increasing the precision by 1 when optimising it.

**Comment by HanselD** [comment]
@PeterShaggyNoble Re-added pkg-lock and resized the image. I think I've got it right this time, please let me know!

**Comment by PeterShaggyNoble** [comment]
Looks like something's gone awry, @HanselD - it's gone back to the vertically stretched version.

**Comment by HanselD** [comment]
Sorry about that, I really have no idea what I'm doing wrong here. I'll start over and update later this week. 
Just curious, where do you see the vertically stretched version? I'm confused about how the build is passing despite that.

**Comment by ericcornelissen** [comment]
> Sorry about that, I really have no idea what I'm doing wrong here. I'll start over and update later this week.

No problem. If you're having trouble working with git, feel free to ask us for help. Regarding the icon, I'm not sure how you're editing this but the vertical stretching could be a result of manually editing the SVG. Make sure to get the icon looking good in a 24x24 canvas in your editing software and don't touch the SVG yourself after that. I hope that helps 😄 


> Just curious, where do you see the vertically stretched version? I'm confused about how the build is passing despite that.

We are unable to check this in the build as it is a purely visual feature of the icon that is different from icon to icon. You can see it simply by viewing the SVG (e.g. in your browser). If you do that you will see that it looks taller then it's supposed to be.

**Comment by PeterShaggyNoble** [comment]
Are you still working on this, @HanselD?

**Comment by adamrusted** [comment]
Updated source to Photobucket homepage, and rebuilt from source SVG found embedded in header.

photobucket

**Review by mondeja — APPROVED** [review]
LGTM @adamrusted :+1:
Thank you for the previous work @HanselD! :pray:

**Pull request merged**
