### PR TITLE
Add BMC Software icon

### PR DESCRIPTION
**Pull request by foo-dogsquared**
**Issue:** #1673 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The vector and color was extracted from the header logo of the website. 
More specifically, it is from [this link](https://www.bmc.com/etc/clientlibs/bmc/head/bmc_logo_header.svg). 

EDIT: Nevermind, I found the [logo usage guide](https://www.bmc.com/content/dam/bmc/corporate/bmc_logo_usage_guidelines.pdf). 
It seems that they preferred to keep the logo and the wordmark. 
I don't see a rule that allows the symbol to be used exclusively. 
What do you think?

### CODE REVIEW

**Comment by birjolaxew** [comment]
Hmm, there's no obvious choice to make here. It looks like they use the full BMC wordmark fairly consistently, barring a few cases where the full wordmark wouldn't fit (e.g. their favicon). On the other hand, it could be argued that our icons are likely to be used exactly in those cases. Without any explicit guiding by the brand itself, it'll have to be a judgement call. Thoughts @simple-icons/maintainers?

**Comment by birjolaxew** [comment]
Pinging other @simple-icons/maintainers again for opinions.

**Comment by phatbhoy67** [comment]
Hey @birjolaxew sorry about the late reply, looking at the brand guideline the full logo is made up of a symbol and logotext. In most cases we isolate and extract the symbol, so I think that is what we should do again in this case.

**Comment by birjolaxew** [comment]
Aight, let's remove the wordmark then. Could you update the SVG @foo-dogsquared?

**Comment by foo-dogsquared** [comment]
The SVG has been updated (or rather reverted to its original commit), @birjolaxew .

**Pull request merged**
