### PR TITLE
Added Toshiba icon

### PR DESCRIPTION
**Pull request by kaleeaswari**
**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hi @kaleeaswari thanks for your work on this PR, can you let me know what source you used for the .svg?

Looking at the .svg you submitted you will need to make some changes.

Did you follow the [contributing guide](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) instructions?

The .svg should have a single path, without colour or other attributes and be sized at 24 x 24. It should also be optimised.

If you need any help or tips on how to do that let me know.

As far as the logo itself, you have used the full Toshiba wordmark. Perhaps it is a good idea to use just the "T" like the favicon on the Toshiba website, what do the @simple-icons/maintainers think?

**Comment by kaleeaswari** [comment]
Have committed new file created using Inkscape and optimized using  SVGOMG.

**Comment by phatbhoy67** [comment]
> Have committed new file created using Inkscape and optimized using SVGOMG.

Hi @kaleeaswari thanks for making the changes, however there are a few changes you still need to make to your .svg file. 

The easiest thing to do would be to open it up again in Inkscape and edit it. 

Are you quite familiar with Inkscape? If not I can list some steps you need to take to achieve the result in detail, let me know.

In summary the steps are:
- open file in Inkscape
- select your "toshiba" object
-  object->ungroup
- unset fill
- center on page (horizontally and vertically)
- open document properties and set width and height to 24px, ensure "scale" is set to "1"
- set viewbox to 24px by 24px
- select your "toshiba" object, lock the aspect ratio  and set width to 24px
- center again on page both horizontally and vertically

That should fix some of the issues. 

Then you will need to optimise it and annotate it.

You can annotate it easily using a normal text editor. 

Hope that helps, let me know if you need any further guidance 👍

**Comment by kaleeaswari** [comment]
Thanks for the detailed steps phatbhoy67. Am new to inkscape, have followed the steps listed and committed back.

**Comment by phatbhoy67** [comment]
Thanks for updating the file @kaleeaswari  It looks like we are nearly there. The icon is still too big, I think you may have set the height to 24px rather than the width. 

If you open the file back up in Inkscape, select the icon, make sure the aspect ratio is locked (click the padlock in between the W and H) and set the width to 24px. 

Then center the icon both vertically and horizontally on the page.

Next, to ensure you have only one path, with the icon selected, go to the "Path" menu and click "union". Nothing should change visually when you do this.

Save the file and upload it to [svgomg](https://jakearchibald.github.io/svgomg/) check it looks ok , if so, click the "markup" button. There should be only one `<path .... />` which should start with `d="M` and end with a `z"`.

If that is the case press the "download" button. Open that file in a text editor.

The properly annotated final file should look like this (I've removed the path data to shorten it in the example)

`<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Toshiba icon</title><path d="M.....z"/></svg>`

To be clear that means you will have to manually delete the `version="1.0" width="24" height="24"` from the file. It's totally fine to do that.

That should be you good to go.

Good luck and let me know if you get stuck 👍

**Comment by phatbhoy67** [comment]
Hey @kaleeaswari the .svg looks good, well done and thanks for your work making the requested changes 👍. The reason the checks are still failing is because you have used lowercase letters in the hex value in the _data/simple_icons.json file. If you change the `ff0000` to `FF0000` that will fix the issue and pass the check. 🤞 Can you also move the entry to be in alphabetical order, the Toshiba entry should be between the entries for `tor.svg` and trainerroad.svg`. You can simple cut and paste it, be careful to include a comma after your entry though. Good luck!

**Comment by kaleeaswari** [comment]
Thanks much @phatbhoy67 for helping out with detailed explanations.

**Comment by phatbhoy67** [comment]
Hey @kaleeaswari thanks for your patience, persistence and effort on this PR, really appreciated the contribution 👍. I will ask @birjolaxew to review it, hopefully it will be merged in soon. 👏

**Comment by kaleeaswari** [comment]
Thanks @phatbhoy67.. Looking forward for merge.

**Comment by birjolaxew** [comment]
:+1: Looks good! Thanks a lot for all your work on updating this @kaleeaswari and @phatbhoy67!

**Pull request merged**
