### PR TITLE
New icon: Heimdall

### LINKED ISSUE #8320: Icon: Heimdall
### Brand Name

Heimdall

### Website

https://heimdall.site/

### Popularity Metric

> 5500 stars

https://github.com/linuxserver/Heimdall

### Official Resources for Icon and Color

https://github.com/linuxserver/Heimdall/blob/2.x/public/img/heimdall-logo.svg
#3f8483

### Additional Comments

Heimdall,: an Application dashboard and launcher 

### Contributing

Yes

### PR DESCRIPTION
**Pull request by 21st-centuryman**
**Issue:** closes #8320

**Similarweb rank:**
> 5500 stars

https://github.com/linuxserver/Heimdall

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
heimdall(2)

### CODE REVIEW

**Comment by 21st-centuryman** [comment]
I do not understand this error. Anyone able to help me with this?

**Comment by ripzerotwo** [comment]
The error is with the linter when it lints your svg file. I haven't confirmed this persay with your code for you svg but it has an abnormal format with double spaces in the path tag for some reason when u look at the raw.

**Comment by ripzerotwo** [comment]
Also as a rule of thumb make sure that when you use a github file for a source make sure to use a permanent link.

**Comment by ripzerotwo** [comment]
Ope figured it out its not the double space but rather you have a bunch of commas in your path for some reason of your svg. thats no bueno with the linter

**Comment by ripzerotwo** [comment]
Actually i have no fucking clue what happened to your svg but the format is definitely incorrect in the path segment did you use svgo to compress.

**Comment by ripzerotwo** [comment]
The linter problem is def something wrong with your svg path however i don't know the exact things that are messed up my guess is the combination of double spaces and a bunch of commas for some reason.

**Comment by ripzerotwo** [comment]
If you want to continue to figure out your svg feel free to otherwise ill create a pr to close the issue.

**Comment by 21st-centuryman** [comment]
You can close this. I decided to redo it from scratch as something definetly went wrong with SVGO, INscape or the preview website. There is a new PR on the repo with heimdall where this is fixed.

**Pull request closed without merging**
