### PR TITLE
Add Greenhouse icon

### PR DESCRIPTION
**Pull request by ericsalvi**
CleanShot 2022-09-30 at 22 46 03@2x

**Similarweb rank:** [3,762](https://www.similarweb.com/website/greenhouse.io/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Greenhouse creates an applicant tracking system and recruiting software for businesses.

### CODE REVIEW

**Comment by LitoMore** [comment]
Hi @ericsalvi, you could use Inkscape for processing the icon.

Here is the size of your icon:

CleanShot 2022-09-30 at 21 41 02@2x

But its expected size is:

CleanShot 2022-09-30 at 21 43 18@2x

**Review by LitoMore — APPROVED** [review]

**Review by LitoMore — CHANGES_REQUESTED** [review]

**Comment by ericsalvi** [comment]
Thank you @LitoMore, I got the size and placement exact this time. I am used to Affinity Designer but for some odd reason when positioning the SVG it was adding transform attributes to the SVG code. Inkscape is a bit more challenging but I was able to get it to work.

**Review by LitoMore — APPROVED** [review]
CleanShot 2022-09-30 at 22 43 38@2x

@ericsalvi Perfect fit! Thank you!

**Pull request merged**
