### PR TITLE
Add Civo icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** #6064
**Alexa rank:** 455,249
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

https://www.civo.com/brand-assets

### CODE REVIEW

**Comment by dirien** [comment]
Will this be considered for the weekend release?

**Review by ericcornelissen — APPROVED** [review]
The SVG, name, and color all look good to me. Nice work @dirien 👌

In the interest of getting this merged as soon as possible I will be adding the same URL as the `"source"` as `"guidelines"` as well ([read this for more info](https://github.com/simple-icons/simple-icons/blob/235776ec555e096e771ba2762b713ba74752497a/CONTRIBUTING.md#optional-data)).

> Will this be considered for the weekend release?

Apologies for the delay @dirien, this project is run by volunteers who work on this in their free time. Hence, it can sometimes take a bit to get a response to your work. I hope you understand.

**Comment by dirien** [comment]
hi @ericcornelissen, thanks for the feedback!

Sorry, i did not want to listen demanding or something like this. I was simply curious 😅 

Thanks again for the great work! ❤️

**Comment by ericcornelissen** [comment]
> Sorry, i did not want to listen demanding or something like this. I was simply curious :sweat_smile:

Thanks for clarifying and in that case, no problem! :slightly_smiling_face:

**Pull request merged**
