### PR TITLE
Add 3DS and Zulip; Update vk

### PR DESCRIPTION
**Pull request by louistsaitszho**
**Issue:**
- #1573 
- #1602 
- #1599 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I basically just follow what's written in those 3 issues. **However, IDK which color should be use for 3DS, so right now it's blank**

P.S.: there is also 1 extra space added by VSCode auto-format on save 🤷‍♀

### CODE REVIEW

**Comment by louistsaitszho** [comment]
I can use some help here: for the 3DS icon, if I don't use `fill-rule`, the whole icon becomes 1 rectangle.  🙏

**Comment by birjolaxew** [comment]
@louistsaitszho It required some manual cleanup of the SVG, but here's a version with everything in one `<path>`:

<p align="center"></p>

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M17.653 16.63a.712.712 0 1 0 1.424 0 .712.712 0 1 0-1.424 0m-9.45 4.238h7.575c.3 0 .524-.225.544-.524v-5.175c-.02-.282-.263-.525-.544-.507H8.203a.54.54 0 0 0-.544.525v5.156c0 .301.244.525.544.525zm13.051-3.525a.729.729 0 0 0 .73-.729.73.73 0 1 0-.73.729zm-1.443-.019a.714.714 0 1 0 .001 1.427.714.714 0 0 0-.001-1.427zm-.713-2.137a.712.712 0 1 0 1.424 0 .712.712 0 1 0-1.424 0M2.54 16.612a1.65 1.65 0 1 0 3.3 0 1.65 1.65 0 1 0-3.3 0M21.272 0H2.728A2.73 2.73 0 0 0-.01 2.72v18.542C.009 22.781 1.228 24 2.728 24h18.526a2.753 2.753 0 0 0 2.756-2.719V2.737C23.991 1.219 22.772 0 21.272 0zm1.913 21.281a1.92 1.92 0 0 1-1.912 1.912H2.728a1.92 1.92 0 0 1-1.913-1.912v-8.456h22.369v8.456zm0-9.694H.815v-8.85A1.92 1.92 0 0 1 2.728.824h18.544c1.049 0 1.912.863 1.912 1.913v8.85z"/><path d="M17.409 3.112H6.534c-.3 0-.544.263-.544.563V9.15c0 .3.226.563.544.563h10.875a.548.548 0 0 0 .544-.563V3.656a.543.543 0 0 0-.544-.544z"/></svg>
```

**Comment by louistsaitszho** [comment]
I just took the red from the [letter `3` in the logo](https://upload.wikimedia.org/wikipedia/commons/1/19/Nintendo_3ds_logo.svg)

**Comment by louistsaitszho** [comment]
@ericcornelissen oh yeah i missed that, let me fix it up......

**Comment by ericcornelissen** [comment]
Thanks a bunch for your work on these three logos @louistsaitszho :tada: Also thanks @birjolaxew for your work on the 3DS `.svg` :wink:

**Pull request merged**
