### PR TITLE
Added Wattpad, Tapas, Aurelia, Gumroad icons

### PR DESCRIPTION
**Pull request by Josh-Powlison**
Hey guys,

The icons have been added and the json updated! I may keep adding stuff to this until it's merged in. :)

Thanks for all your help figuring this out @birjolaxew, you've been fantastic! :D

### CODE REVIEW

**Comment by birjolaxew** [comment]
Lots of contributions, thank you very much! Two things that need changing before this can be merged:

- The "source" URL is intended to be where people can go if the company updates their logo, or similar. For Aurelia that would be https://aurelia.io/ (as their logo on the site is an SVG), for Tapas it would be https://tapas.io/about#media, and for Wattpad it would be https://www.wattpad.com/press/#assets.
- You have a leftover `fill` on your `<path>` in the Gumroad SVG

Other than that, this looks good!

**Comment by ericcornelissen** [comment]
Great work @Josh-Powlison! I've got a few remarks:
- The Gumroad SVG still has a `fill` attribute on its `<path>` which shouldn't be there
- The Aurelia source should preferably link to a website related to Aurelia, I think @mabouchalkha took the SVG from http://aurelia.io/
- I think we shouldn't use links to a Google Drive folder as you did with Tapas, but I also don't know where @birjolaxew found that link 🤔 
- As for Wattpad, I think it's better to have the source be https://www.wattpad.com/press/ instead of the actual file (that link is less likely to change)
- For Auralia and Gumroad you specified why you choose the color, which is great! For Tapas I got `#FECE00` from the `tapas-appicon.eps` or `#F6B606` from their website, how did you end up with `#FFCE00`? I had some problems opening the Wattpad files, but could you specify where you took the color from?

**Comment by Josh-Powlison** [comment]
- [ ] Leftover fill on Gumroad (dagnabit, how'd it sneak its way into the end of the file? :) )
- [ ] Set links to pages, not specific files
- [ ] Explain Wattpad color
- [ ] Figure out Tapas color

The Wattpad color was in the EPS for the icon that they provide, so it was an easy grab. :) I double-checked that it's the same for inverted and normal versions, and it is. (which it should be, but after the below...)

# Tapas color weirdness

The Tapas color was kinda weird, I had checked the colors of the boxes on the website and it was as you said, `#F6B606`. But I just found more weirdness:

tapas-colors

The color for the large tapas icon in the screenshot is `#FFCF00` but for the small icons it's `#FFCE00`. I guess it's different for the app icon too? Also, the pouch at the bottom is lighter.

It looks like they used a wide variety of colors to create a subtle illusion of depth, even having the smaller icons "poke out" slightly less. But I'm not sure what the specific color for the brand should be then; I was assuming the back of the logo, but maybe not? Should we go with the color used in the background of the website (`#F6B606`) since it's consistent?

What do you guys think? I'd say we should probably go for the color on the back of the large icon `#FFCF00`.

**Comment by birjolaxew** [comment]
:+1: Thanks for the contributions! This is great work :)

Unfortunately it's somewhat common for companies to not be consistent with their color usage. As long as the color is taken from the logo, it's fair enough if it can't be consistent. I think `#FFCE00` is just fine.

**Comment by ericcornelissen** [comment]
>The Wattpad color was in the EPS for the icon that they provide, so it was an easy grab. :) I double-checked that it's the same for inverted and normal versions, and it is. (which it should be, but after the below...)

👍 


> What do you guys think? I'd say we should probably go for the color on the back of the large icon #FFCF00.

I vote for `#F6B606` since, as you pointed out, the icons are using a gradient from which it is quite hard to get the color they intended. If anyone finds a more reliable source for the color we can always change it 😉

**Comment by ericcornelissen** [comment]
@Josh-Powlison, just wanted to give you two tips with regards to Pull Requests:
1. It's okay to open a new Pull Request for each icon you add, that way if one has a problem that needs to be solved the others can be merged.
2. You don't have to/should not close issues before the related Pull Request is merged. You can also use `closes #1` in the description of the Pull Request so the issue is automatically closed when it is merged.

**Comment by Josh-Powlison** [comment]
@birjolaxew  You're welcome! This is my first Github contribution to a project not my own, so that's exciting for me! :D

@ericcornelissen I'd be totally on board with the color shift if there was a shred of consistency. :P Just found this screenshot in their assets folder and thought it might help:

2-tapas-categories

Nope, the color for the header is `#F5B704`. XD I don't know if we can win with Tapas's color no matter what we do, so my vote's going with the prominent color in-between the shades of the logos.

I'm open to further conversation and thoughts on it though. I can see the appeal and logic behind `#F6B606`, I just don't think Tapas even holds that up.

Also, thanks for the tips! :D It automatically added the extra commits to this thread; is there an easy way to split them up? Or not include certain commits in a pull request? I'm still new to collaborating on Github.

**Comment by ericcornelissen** [comment]
> I'm open to further conversation and thoughts on it though. I can see the appeal and logic behind #F6B606, I just don't think Tapas even holds that up.

I think its fine for now 🙂 


> Also, thanks for the tips! :D It automatically added the extra commits to this thread; is there an easy way to split them up? Or not include certain commits in a pull request? I'm still new to collaborating on Github.

Yes there is, but its git thing rather then a GitHub thing. You can create a [branch](https://git-scm.com/docs/git-branch) for an icon and add changes there. Then if you want to work on another icon you can make another branch and work from there ([this video](https://www.youtube.com/watch?v=H5GJfcp3p4Q) might be helpful 😉)

It is actually almost always better to work with branches when you contribute to another project because right now your project is out of sync with this project, which can be solved but is not the nicest solution imo. But that might be a bit beyond your understanding for now, since I'm guessing you're new to git as well(?). Anyway, I found [this tutorial](https://try.github.io/levels/1/challenges/1) to be very helpful to get started with git 👍 and if you have any questions don't hesitate to ask!

**Comment by Josh-Powlison** [comment]
@ericcornelissen Thanks! I'm sort of comfortable with Git but right now use Sourcetree (outside of direct uploads to Github like I've done here). Still new for sure, I've done quite a bit but haven't found my "sea legs" yet or done direct in the command line much. Thanks for the videos, I'll check them out! :D

Okay, I was kind of hoping I wouldn't have to bother with multiple branches for the pull, but I'll do that then! I think I understand how I would do it now!

**Comment by ericcornelissen** [comment]
@Josh-Powlison you can do branches with SourceTree as well, so you don't have to use the command line if you don't want to (I just gave those links because I remember using them) 🙂

Managing multiple branches can be difficult when you're getting started but in the long run its nice to know it works. If you don't feel comfortable yet you can do your next PR the same way you did this one 👍 

Just remember that you have to keep your `develop` branch up to date with the `develop` branch of this repo.

**Comment by Josh-Powlison** [comment]
@ericcornelissen Yeah, I've done branches, but I realized I haven't been using them near as much as I ought to. I guess since I've mostly worked alone, I haven't run into a situation where my bad habits were challenged.

I do need to get a lot better at branches, seeing some videos and looking up stuff, I realize I'm more of a Grasshopper than I'd realized. 😄

Okay! Thanks for your guys' patience and for working with me! I feel like I've learned a lot in the short time I've gotten involved here! :D I'll probably make a few branching mistakes here as I move forward, but I'll keep learning and improving!

**Pull request merged**
