### PR TITLE
Add Render icon

### PR DESCRIPTION
**Pull request by uiuxarghya**
render

**Issue:** #5815 
**Alexa rank:** 40,878
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Website: https://render.com/
Hex Value : `#46E3B7`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @uiuxarghya.

However, when comparing to the logo in the website's header, I'm noticing some small differences [along the bottom of the 2 top right squares](https://user-images.githubusercontent.com/15157491/120678496-0b5e5b80-c490-11eb-8283-65071e417536.png) and [down the right of the bottom left one](https://user-images.githubusercontent.com/15157491/120678557-203aef00-c490-11eb-870d-05e54690f9d1.png) (with your version in red in both cases). This may simply, although not necessarily, be a result of the precision needing to be set 1 higher during the optimisation process. Could you have another look to see if you could fix those up, please?

**Comment by uiuxarghya** [comment]
> Thanks for the contribution, @uiuxarghya.
> 
> However, when comparing to the logo in the website's header, I'm noticing some small differences [along the bottom of the 2 top right squares](https://user-images.githubusercontent.com/15157491/120678496-0b5e5b80-c490-11eb-8283-65071e417536.png) and [down the right of the bottom left one](https://user-images.githubusercontent.com/15157491/120678557-203aef00-c490-11eb-870d-05e54690f9d1.png) (with your version in red in both cases). This may simply, although not necessarily, be a result of the precision needing to be set 1 higher during the optimisation process. Could you have another look to see if you could fix those up, please?

@PeterShaggyNoble 
I have updated the SVG code of Render Icon. Can you check it once?

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for this, @uiuxarghya.
It looks like the source icon has a load of unnecessary points at the top of the squares, see [here](https://user-images.githubusercontent.com/1830867/122021676-cb677480-cdbd-11eb-91b6-d7f2dd3188cc.png). You may also be able to cut down the number of points needed for the curves in the top left.

Also going to highlight that this icon appears to be exported with 2 decimals of precision, while we generally ask for 3-5 decimals for the project, providing the icon matches up properly we could perhaps include this with only 2? What do other @simple-icons/maintainers think?

**Comment by uiuxarghya** [comment]
> Thanks for this, @uiuxarghya.
> It looks like the source icon has a load of unnecessary points at the top of the squares, see [here](https://user-images.githubusercontent.com/1830867/122021676-cb677480-cdbd-11eb-91b6-d7f2dd3188cc.png). You may also be able to cut down the number of points needed for the curves in the top left.
> 
> Also going to highlight that this icon appears to be exported with 2 decimals of precision, while we generally ask for 3-5 decimals for the project, providing the icon matches up properly we could perhaps include this with only 2? What do other @simple-icons/maintainers think?

I have removed the unnecessary points at the top of the squares. 
I have changed the precision to 3 now.

**Comment by ericcornelissen** [comment]
Just for the record: if the SVG works with a precision of 2, that should be fine. No need to force extra precision if it's not necessary, right?

That said, it's also not necessary to bring the precision back down to 2 now that @uiuxarghya already changed it to 3, I would say - unless you want to, of course.

**Comment by PeterShaggyNoble** [comment]
Thanks, @uiuxarghya. However, I'm still seeing the same differences as I did in [my first comment](https://github.com/simple-icons/simple-icons/pull/5816#issuecomment-854002987). To make sure I'm comparing like with like though, can you confirm that you based your version on the base-64 encoded SVG embedded in the website's header?

**Comment by uiuxarghya** [comment]
I have updated the SVG code of Render Icon and fixed all the above errors.
Can anyone from @simple-icons/maintainers check it out ?

**Comment by ericcornelissen** [comment]
I'm also [seeing similar differences to what Peter described](https://user-images.githubusercontent.com/3742559/125172093-e4debf00-e1b7-11eb-9609-2c1b9b555e2c.png) (black is the PR version, green is what I got from the website) 🤔 

@uiuxarghya, first, can you confirm that you used a base64 encoded version of the SVG taken from the header of the website as source material? Second, can you try exporting with a higher precision, I think it's quite likely the differences are due to the precision of 1(?) this time around.

**Pull request closed without merging**
