### PR TITLE
Add Pretzel icon

### LINKED ISSUE #5799: Pretzel.rocks
**Brand Name:** Pretzel.Rocks
**Website:** https://pretzel.rocks
**Alexa rank:** 399,412
  

**Official resources for icon and color:** https://download.pretzel.rocks/public/BrandAssets.zip

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** Close #5799
**Alexa rank:** [~449k](https://www.alexa.com/siteinfo/pretzel.rocks)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I used `Pretzel_icon.svg` found in the Brand Assets zip file from the [website](https://www.pretzel.rocks/) footer
- I used Inkscape to scale and to remove some extra nodes
- I used https://jakearchibald.github.io/svgomg/ to optimize

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
HI @service-paradis,

can you fix the lint issue so I can start to review your PR?

**Review by dirien — COMMENTED** [review]
Hi @service-paradis,

I did not find the linked svg, so I used the logo from the website.

i see some differences

image

I let you decide! 😄

**Comment by service-paradis** [comment]
Thanks for the review @dirien! When I created this PR the first time, there was some SVGs available in the "Brand pack" footer link... Unfortunately, there are no more... I will gave this another look in the next few days!

**Comment by service-paradis** [comment]
@adamrusted Thank you for reminding me about this one! Glad to have you back :)

I just commit a new SVG using the one found in the header.

**Review by adamrusted — APPROVED** [review]

**Pull request merged**
