### PR TITLE
Added Radar

### LINKED ISSUE #4313: Request: radar.io Icon
**Name:** radar.io 
**Website:** https://radar.io/
**Alexa rank:** 192,377
  

**Official resources for icon and color:** https://radar.io/

### PR DESCRIPTION
**Pull request by adamrusted**
radar

**Issue:** #4313 
**Alexa rank:** 192,377

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Fixes #4313
- Icon pulled from [Press Kit](https://www.dropbox.com/sh/ltsbhc0d527uz5d/AADkCT0cX9nsHr-ufpQz2L5ea?dl=0) in footer of site.
- SVG generated using a mix of Adobe Illustrator / Figma, optimised using SVGO CLI.
- While site is radar.io - they refer to the company simply as Radar in information across the site.

### CODE REVIEW

**Comment by hasthamalp** [comment]
ok

**Comment by fbernhart** [comment]
@adamrusted I'm not sure which file you've exactly used as source.

But comparing your version against the `mark_blue.svg` file found in the press kit that you've linked, there are some differences:

image

Could you have another look at it?

**Comment by adamrusted** [comment]
Not sure either - this is one of my earlier contribs, so likely a bit messy! 😅

**Comment by fbernhart** [comment]
@adamrusted LGTM 🚀

**Pull request merged**
