### PR TITLE
Add Kong icon

### LINKED ISSUE #5776: Icon Request: Kong
**Brand Name:** Kong
**Website:**  https://konghq.com/kong/
**Alexa rank:** 23.1 k (the site returned stats of konghq.com)
**Github Stars:** ~ 29.2k (https://github.com/Kong/kong)
  

**Official resources for icon and color:** https://konghq.com/kong/ 
  
  (The site's header has a SVG logo)

### PR DESCRIPTION
**Pull request by sisp**
Kong icon preview

**Issue:** #5776
**Similarweb rank:** 171,768
**GitHub Stars**: 31.4k

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The icon is based on the "Blue Logomark" SVG file from the official [Kong brand assets page](https://konghq.com/brand-assets/). The color hex has been extracted from this file, too.

Closes #5776.

### CODE REVIEW

**Review by dirien — APPROVED** [review]
Hi @sisp,

thanks for your contribution. Can you take a look again into your logo?
image
I see some differences.

**Review by dirien — CHANGES_REQUESTED** [review]
See comments above

**Comment by sisp** [comment]
Thanks for checking! I'm not sure what happened, but indeed there were differences. I've extracted the icon again from the blue logo. Can you please check again?

**Review by dirien — APPROVED** [review]
HI @sisp,

Thanks for the rework! Looks very good now!

image

**Comment by sisp** [comment]
Awesome! Again, thank you very much for your thorough review!

**Pull request merged**
