### PR TITLE
Add QuickTime icon

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
QuickTime
**Issue:** #1935

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Very uncertain about pretty much everything in this (see #1935 for more details) so could do with some input from the @simple-icons/maintainers.

### CODE REVIEW

**Comment by birjolaxew** [comment]
The SVG itself looks pretty on point, except that the corners of the official version seems to be slightly rounded, while they're sharp in this PR.

<p align="center"></p>

I personally think I would prefer a blue for the color. I think that the primary color of the official logo is the blue center, which also matches well with the blue of the old logo. It's obviously a gradient (and a raster image) so it's hard to pick one color, but I think one of `#17D5FB` or `#1C69F0` would work (those are taken from the lightest part and the part just above the center respectively).

**Comment by PeterShaggyNoble** [comment]
That's some eyesight you have, @birjolaxew! 😆 Leave it with me, I'll see if I can tweak that.

Personally, of the 2 blues, I'd lean towards the darker one.

**Comment by PeterShaggyNoble** [comment]
Does this look a bit closer, @birjolaxew?

[QuickTime](https://github.com/simple-icons/simple-icons/files/3921555/quicktime.zip)

**Comment by birjolaxew** [comment]
@PeterShaggyNoble That looks good! Thanks for updating it. I agree that the darker of the two blues is probably the way to go, so once that's been updated we'll get this merged in :)

**Comment by PeterShaggyNoble** [comment]
Thanks for the help, @birjolaxew - those changes have been made.

**Comment by birjolaxew** [comment]
:+1: Looks good! Since the color is pretty subjective, I'll let another @simple-icons/maintainers weigh in on it before merging this in.

**Pull request merged**
