### PR TITLE
Update Zingat logo

### PR DESCRIPTION
**Pull request by service-paradis**
Part of #9072 
image

Update Zingat logo using https://kq9v7r75.rocketcdn.com/static/img/data/about/logos/download/zingat_white_square.svg fund at https://www.zingat.com/kurumsal-logolar

### CODE REVIEW

**Review by adamrusted — COMMENTED** [review]
@service-paradis - how would you feel about changing the JSON to have the logo page for guidelines, and the homepage as the source? Comparing against the website header image I'm seeing [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/4e0321f4-ee62-4caa-9f3d-dea125f6ca69), but I'm happy to continue with the source as-is if you'd prefer.

**Comment by service-paradis** [comment]
> @service-paradis - how would you feel about changing the JSON to have the logo page for guidelines, and the homepage as the source? Comparing against the website header image I'm seeing [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/4e0321f4-ee62-4caa-9f3d-dea125f6ca69), but I'm happy to continue with the source as-is if you'd prefer.

Hum... Maybe the current icon is correct in this case! There are no real guidelines at https://www.zingat.com/kurumsal-logolar. The only change needed might be to use the homepage as source...

**Comment by adamrusted** [comment]
@service-paradis - are you able to double check the source on this one, it may be we don't need to change the icon at all!

**Comment by adamrusted** [comment]
@service-paradis - please review the PR, I've made changes to the JSON and icon.

**Pull request merged**
