### PR TITLE
Add Pixie Logo

### LINKED ISSUE #9122: [REQUEST] Add the Pixie icon
### Brand Name

Pixie

### Website

https://px.dev

### Popularity Metric

Pixie has 4.7k stars on GitHub. See: https://github.com/pixie-io/pixie

Its quite close to the threshold but it's rising popularity should justify for this premature request.

Pixie is the go-to solution for automated metrics and monitoring of Kubernetes-deployed applications.

It also is one of the primary tools used by DataDog, a very popular solution.

### Official Resources for Icon and Color

logo-pixie

HEX Color: #3fe7e7
RGBA Color: rgba(63,231,231,255)

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by CodeWithShipraJain**
**Issue:** closes #9122

**Similarweb rank:** 3,898,361. See https://www.similarweb.com/website/px.dev/
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by weiensong — COMMENTED** [review]
i think it is a good work

**Comment by LitoMore** [comment]
The popular metric needs to meet our requirements.

See https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon.

I will keep this PR open since it will reach 5k stars quickly.

Feel free to ping me once its popular metric meets our requirements.

**Comment by PeterShaggyNoble** [comment]
That's GH rounding up, @adamrusted; they're only at 4991. Given how slow that number is growing _and_ how low it is relative to the age of the project, I'd be inclined to call this out of scope - _especially_ with a rank as low as theirs.

**Comment by adamrusted** [comment]
Let's close this one down for now then. @CodeWithShipraJain - feel free to re-open should it hit 5k or rank highly on SimilarWeb.

**Pull request closed without merging**
