### PR TITLE
Add IBM Cloud icon

### PR DESCRIPTION
**Pull request by Asmit2952**
Signed-off-by: Asmit2952 <asmitbm2952002@gmail.com>

ibmcloud

**Issue:  #6723 **
**Alexa rank: 635**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG and colors sourced from [IBMs Official](https://www.ibm.com/brand/systems/cloud/brand/logo) branding website.

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
hi @Asmit2952,

Unfortunatly there is a login screen. Can you maybe add the original icon as comment?

image

**Comment by Asmit2952** [comment]
> hi @Asmit2952,
> 
> Unfortunatly there is a login screen. Can you maybe add the original icon as comment?
> 
> image

Screenshot (95)

Screenshot (96)

Screenshot (97)

Are these enough? @dirien

**Comment by dirien** [comment]
hmm reading the special use case and misuse guide (no flat logo) i am not sure if we can use it in simple-icons. Asking @service-paradis and @ericcornelissen for help.

**Comment by Asmit2952** [comment]
> hmm reading the special use case and misuse guide (no flat logo) i am not sure if we can use it in simple-icons. Asking @service-paradis and @ericcornelissen for help.

Yup, I read that, and used gradient logo as suggested. Flat logo is not used in my PR.

**Comment by dirien** [comment]
@Asmit2952, can you save the pic of the site, not a screenshot, add attach to this PR? or even if possible to original svg? thanks

**Comment by Asmit2952** [comment]
> @Asmit2952, can you save the pic of the site, not a screenshot, add attach to this PR? or even if possible to original svg? thanks

Save the pic of the site means? Like the whole ss of the site? And original svg isn't available right on the site, you need to be IBM employee for that.

I converted the PNG image on the official site to SVG. Then optimized it with the SVG tool.

**Comment by Asmit2952** [comment]
> > @Asmit2952, can you save the pic of the site, not a screenshot, add attach to this PR? or even if possible to original svg? thanks
> 
> Save the pic of the site means? Like the whole ss of the site? And original svg isn't available right on the site, you need to be IBM employee for that.
> 
> I converted the PNG image on the official site to SVG. Then optimized it with the SVGOMG Online tool.

**Comment by dirien** [comment]
> > @Asmit2952, can you save the pic of the site, not a screenshot, add attach to this PR? or even if possible to original svg? thanks
> 
> Save the pic of the site means? Like the whole ss of the site? And original svg isn't available right on the site, you need to be IBM employee for that.
> 
> I converted the PNG image on the official site to SVG. Then optimized it with the SVGOMG Online tool.

Please add the PNG image to this PR, that will help :)

**Comment by Asmit2952** [comment]
> > > @Asmit2952, can you save the pic of the site, not a screenshot, add attach to this PR? or even if possible to original svg? thanks
> > 
> > Save the pic of the site means? Like the whole ss of the site? And original svg isn't available right on the site, you need to be IBM employee for that.
> > 
> > I converted the PNG image on the official site to SVG. Then optimized it with the SVGOMG Online tool.
> 
> Please add the PNG image to this PR, that will help :)



Official image as seen in the above screenshot.

**Review by dirien — CHANGES_REQUESTED** [review]
hi @Asmit2952, 

thanks for the image.

I can see  some differences between your logo (red) and the reference image (black)

image

@jorgeamadosoria

**Comment by Asmit2952** [comment]
> hi @Asmit2952, 
> 
> thanks for the image.
> 
> I can see  some differences between your logo (red) and the reference image (black)
> 
> image
> 
> @jorgeamadosoria 
> 

I'll fix that. 

I checked that changes, but as per Contribution guidelines, the logo should be in the center in the viewbox, if I place it in the center, I get an error when I `npm run lint`...I get an error saying the SVG is not centered (11.56, 12) it should be (12, 12). 
Actually 11.56 is correct position. So how do I eliminate that error?

**Comment by dirien** [comment]
@Asmit2952, I am not a good designer myself, so maybe one of the @simple-icons/maintainers have a hint for you?

**Comment by Asmit2952** [comment]
> @Asmit2952, I am not a good designer myself, so maybe one of the @simple-icons/maintainers have a hint for you?

Okay, I'll share the screenshot of the error

**Comment by sachinraja** [comment]
I think this is considered misuse, we cannot use a flat color.

**Comment by Asmit2952** [comment]
> I think this is considered misuse, we cannot use a flat color.

Same is done for IBM Watson PR and Issue on this repository. The color is stated on their official website.

**Comment by sachinraja** [comment]
> The color is stated on their official website

What color?

**Comment by Asmit2952** [comment]
> > The color is stated on their official website
> 
> What color?

#08BDBA...the teal background

**Comment by sachinraja** [comment]
Yes, but it still does not have the gradient on the lines at the top.

**Comment by Asmit2952** [comment]
And this is the official IBM Watson logo. @sachinraja

**Comment by Asmit2952** [comment]
> Yes, but it still does not have the gradient on the lines at the top.

Official Website Guidelines

**Comment by sachinraja** [comment]
I'm not sure about the other IBM icons that were added, but the gradient discussion was not brought up in those PRs.  About the limited-use logo, I don't think SVG icons can be used for those purposes.

**Comment by Asmit2952** [comment]
> I'm not sure about the other IBM icons that were added, but the gradient discussion was not brought up in those PRs.  About the limited-use logo, I don't think SVG icons can be used for those purposes.

There are no gradient logos on Simple Icons website as far as I have seen. Adding a gradient wouldn't simplify the SVG needed in single line, according to contribution.md

**Comment by sachinraja** [comment]
That's why I'm saying I don't think we can add this. We can wait to see what the other maintainers here think though.

**Comment by Asmit2952** [comment]
> That's why I'm saying I don't think we can add this. We can wait to see what the other maintainers think though (mentioning @dirien and @jorgeamadosoria).

Okay👍🏻✌🏼

**Comment by jorgeamadosoria** [comment]
Icons in Simple Icons can't have gradients. 
The limited use logo says "best for", not "exclusively for", so we are fine.
In this case converting the gradient into solid is the proper way to do it, unless there is a clause in IBM's guidelines that forbid tampering with the icon in this way. Given that they provide an icon for "limited-use" that is completely solid, this doesn't seem to be the case.

Finally, the icon should be centered in the 24x24 viewbox. If you have your icon centered and still see a discrepancy with the reference icon, it may be because the reference icon is not centered itself. try reducing its viewbox to 24x24 and centering the drawing, and then compare again.

Hope that helps.

**Comment by sachinraja** [comment]
> The limited use logo says "best for", not "exclusively for", so we are fine.

It says "Please review all logo options to make sure this is the only logo appropriate for your needs."  So I think anyone who needs an SVG version of this icon should use the gradient version from the website because it is not necessary that it be monochrome.

**Comment by adamrusted** [comment]
> > The limited use logo says "best for", not "exclusively for", so we are fine.
> 
> It says "Please review all logo options to make sure this is the only logo appropriate for your needs."  So I think anyone who needs an SVG version of this icon should use the gradient version from the website because it is not necessary that it be monochrome.

Given we're a monochrome library, and a monochrome icon is available - we should include that variant, as well as a link to this page for guidelines. That way it is up to our users to decide which to use.

**Comment by sachinraja** [comment]
I disagree that "a monochrome icon is available" because they explicitly say not to use it if you don't have to, so I think it's more than just a variant.

**Comment by Asmit2952** [comment]
Any updates on this PR? @dirien @sachinraja @jorgeamadosoria @adamrusted

**Comment by jorgeamadosoria** [comment]
> IBMs Official

Checking the monochrome icon with gradient and the limited used one, I believe they are the same minus the gradient. And since the gradient needs to go away because the library does not allow for it, then it is functionally the same as taking the monochrome one and removing the gradients.
Given this, I'm fine with this proposal. We just need to correct the slight differences with the source and it should be fine.

**Comment by sachinraja** [comment]
@jorgeamadosoria I'm fine with merging this given your comment. Although I think we should change it to the IBM blue brand color shown in https://github.com/simple-icons/simple-icons/pull/6746#issuecomment-996383705.

**Comment by jorgeamadosoria** [comment]
> @jorgeamadosoria I'm fine with merging this given your comment. Although I think we should change it to the IBM blue brand color shown in [#6746 (comment)](https://github.com/simple-icons/simple-icons/pull/6746#issuecomment-996383705).

I think blue is far more representative for IBM too, yes.

@Asmit2952 can you please change the color to IBM blue, and correct the slight differences? It seems we have reached an agreement now. When you do, please let us know to check and merge!

**Comment by Asmit2952** [comment]
> > @jorgeamadosoria I'm fine with merging this given your comment. Although I think we should change it to the IBM blue brand color shown in [#6746 (comment)](https://github.com/simple-icons/simple-icons/pull/6746#issuecomment-996383705).
> 
> I think blue is far more representative for IBM too, yes.
> 
> @Asmit2952 can you please change the color to IBM blue, and correct the slight differences? It seems we have reached an agreement now. When you do, please let us know to check and merge!

Sure, I'll change the color to IBM's blue, and other slight differences have been solved.

**Comment by Asmit2952** [comment]
@jorgeamadosoria Updated the color

**Comment by jorgeamadosoria** [comment]
it's a perfect match with the limited use logo. LGTM

**Pull request merged**
