### PR TITLE
Add Blackberry icon

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
**Issue:** #1915
Blackberry

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Possible alternative colour: `#1475dc`.
Possible alternative source URLs:
- https://www.blackberry.com/
- https://www.blackberry.com/us/en/company/newsroom/media-gallery
- https://www.blackberry.com/us/en/legal/trademarks (which links to the PDF I used)

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Great work on this icon @PeterShaggyNoble 👍 

I agree with the hex value chosen, `#000000`, however since there is a decision to be made best to get the views of @simple-icons/maintainers .

Also, would it be better to cite the [Blackberry website](https://www.blackberry.com/us/en) as the source, there is an .svg in the header and this is more likely to be remain the best source for the future? 🤔

**Comment by PeterShaggyNoble** [comment]
Added blackberry.com to the list of possible alternative source URLs.

**Comment by birjolaxew** [comment]
I agree with `#000000`, but also would prefer just having blackberry.com as the source, given that an SVG is available in the header.

**Comment by PeterShaggyNoble** [comment]
Source updated, checks still pending.

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble nice work 👍

**Pull request merged**
