### PR TITLE
Update Adobe Photoshop

### PR DESCRIPTION
**Pull request by MetLee**
image

**Issue:** #3369 
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I use the color of the text 'PS'.

### CODE REVIEW

**Comment by MetLee** [comment]
@PeterShaggyNoble  Should I continue to update the other 9 icons?

**Comment by ericcornelissen** [comment]
> [...] SVG looks perfect to me. I agree with you that:
>
>    1. We should update our colours, and,
>    2. We should use the foreground colour of each icon,

I complete agree with that 👍

**Comment by runxel** [comment]
I'll give my support for this as well!
(By "foreground" we mean the text color, which part is now knocked out, right?)

**Comment by PeterShaggyNoble** [comment]
Excellent, looks like we have a consensus, so 🙂

> By "foreground" we mean the text color, which part is now knocked out, right?

That's it, ay, @runxel.

**Pull request merged**
