### PR TITLE
Adding RubyGem

### PR DESCRIPTION
**Pull request by spaquet**
### Description
* Adding RubyGem package that can be used directly in Rails project. Other ruby based framework might be added later but for now only Rails application are supported. Thus the name simple-icons-rails ;-)
* This gem is acting as a passthrough an call your cdn passing the icon slug and color as specified.
* This gem is licensed under MIT, let me know if this is an issue for you and if you need me to align or mention the type of license used in your project.

### CODE REVIEW

**Comment by LitoMore** [comment]
@spaquet See https://raw.githubusercontent.com/simple-icons/simple-icons/develop/assets/readme/rubygems-white.svg

You should copy a `rubygems.svg` to the `assets/readme/rubygems-white.svg` and change its color to white like other files.

BTW, I can't find your package on RubyGems. See https://rubygems.org/search?query=simple-icons-rails.

**Comment by spaquet** [comment]
1. ok will change the icon as requested.
2. here is the link to the package  https://rubygems.org/gems/simple-icons-rails

**Review by spaquet — COMMENTED** [review]
* Adding ruby gems-white.svg to assets/readme

**Comment by spaquet** [comment]
took me some trials to get the logo right, but we should be good now.

**Review by mondeja — APPROVED** [review]

**Pull request merged**
