### PR TITLE
Add hepsiemlak

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
hepsiemlak

**Issue:** contributes to #9072 

**Similarweb rank:** 6,020. See https://www.similarweb.com/website/hepsiemlak.com

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from website footer
Color: Taken from logo `#e1251b`

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Spotting some slight differences on this one @PratyushJayachandran - could you have another look please?

image

**Comment by PratyushJayachandran** [comment]
> Spotting some slight differences on this one @PratyushJayachandran - could you have another look please?
> 

I have redone the icon. Please review again @adamrusted

**Review by adamrusted — CHANGES_REQUESTED** [review]
A very slight difference in the paths now @PratyushJayachandran - looks to be a precision thing more than anything. Could you up it to 4pts?

image

**Comment by PratyushJayachandran** [comment]
> A very slight difference in the paths now @PratyushJayachandran - looks to be a precision thing more than anything. Could you up it to 4pts?


Increased precision to 4. Please review again.

**Review by PeterShaggyNoble — APPROVED** [review]

**Pull request merged**
