### PR TITLE
Adding Sensu icon

### PR DESCRIPTION
**Pull request by asachs01**
**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Adding the Sensu logo here. There are two color variants of the logo: Dark blue (#2C3458) and light green (#89C967). As the dark blue doesn't tend to show up well on darker backgrounds, we decided to go with the light green hex value. We also went with the mark, though we do have text logos as well (https://github.com/sensu/sensu-go/tree/master/dashboard/src/assets/logo/wordmark).

### CODE REVIEW

**Comment by davidklebanoff** [comment]
Hi @asachs01,

Thanks for your contribution! We love getting pull requests from official sources. I think you're spot on with the icon choice and color (it's consistent with your official website and favicon as well).

Congratulations on a flawless first contribution! 🎉

**Comment by asachs01** [comment]
Thanks a ton @davidklebanoff ! Glad to have contributed! :smile:

**Comment by asachs01** [comment]
Howdy @davidklebanoff :wave:!

I was curious about how often y'all merge develop into master to pull in new icons.

**Comment by davidklebanoff** [comment]
Hi @asachs01,

There's currently no standard schedule for when we merge, but we typically do it about twice a month unless there's a pressing need. Since it sounds like you're patiently waiting on this addition, we'll get it merged soon. :)

@ericcornelissen @birjolaxew

**Comment by asachs01** [comment]
<3 y'all are awesome! Thank you!

**Comment by davidklebanoff** [comment]
@asachs01 - Follow progress: #1220.

**Comment by davidklebanoff** [comment]
Released!

**Pull request merged**
