### PR TITLE
Add Unraid

### LINKED ISSUE #3501: UnRAID logo
**Name:** Unraid
**Website:** https://unraid.net/
**Alexa rank:** 39,298 https://www.alexa.com/siteinfo/unraid.net
  

**Official resources for icon and color:**
  
  https://craftassets.unraid.net/uploads/logos/unraid-stacked-dark.svg

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Unraid

**Issue:** Closes #3501
**Alexa rank:** [~35.7k](https://www.alexa.com/siteinfo/unraid.net)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon from [this SVG](https://craftassets.unraid.net/uploads/logos/unraid-stacked-dark.svg) found in the website footer. In the absence of anything to tell us otherwise, I've gone with just the "wave" as that's what they use themselves on social media, etc. The colour is the darker orange used for links on the site but I'm open to suggestions for alternative colours.

### CODE REVIEW

**Comment by fbernhart** [comment]
The icon looks good to me 👍🏼 But is a precision of 4 necessary? I was able to get the same results with a precision of 3.

```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Unraid icon</title><path d="M11.406 8.528h1.17v6.926h-1.17zM1.17 15.454H0V8.528h1.17zm4.534.828h1.17v2.645h-1.17zm-2.86-2.969h1.169v4.282h-1.17zm5.703 0h1.17v4.282h-1.17zM22.83 8.528H24v6.926h-1.17zm-4.534-.81h-1.17V5.073h1.17zm2.86 2.95h-1.169V6.406h1.17zm-5.72 0h-1.17V6.406h1.17z"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
I got some (extremely) hairline differences on the right edges of a couple of the bars with a precision of 3 using SVGO, @fbernhart, which I'm also seeing in your version. See screenshot below with original in black and yours in red.

**Comment by fbernhart** [comment]
@PeterShaggyNoble I barely can zoom in enough to see them. 😄 As the differences seem to be really, really small, I would go for a precision of 3. But I'm ok with a precision of 4 as well, if you prefer that.

**Comment by PeterShaggyNoble** [comment]
Let's get a 3rd opinion from one of the other @simple-icons/maintainers and go with that, @fbernhart 😉 Sometimes I can be too much of a perfectionist!

If the decision is to go with precision 3, feel free to push your version directly to my branch.

**Comment by adamrusted** [comment]
> Let's get a 3rd opinion from one of the other @simple-icons/maintainers and go with that, @fbernhart 😉 Sometimes I can be too much of a perfectionist!
> 
> If the decision is to go with precision 3, feel free to push your version directly to my branch.

Not that it makes a massive difference, but providing the 4 decimal file isn't much bigger I'd say go for that purely on accuracy. I'd only say stick to the 3 decimals if the file was *significantly* smaller.

**Comment by runxel** [comment]
While @adamrusted certainly has a point I also have to say that I also can't make out a difference.
I wouldn't stress the accucary point this much. 
In the end both is fine 🙃

**Comment by adamrusted** [comment]
@simple-icons/maintainers - shall we go for the 3 decimals then, given the difference is so small?
@fbernhart did you want to push your version in and we can merge it?

**Comment by fbernhart** [comment]
@adamrusted Done. Feel free to merge after a last review.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @PeterShaggyNoble and @fbernhart 🥳

**Pull request merged**
