### PR TITLE
Added Crowdsource

### LINKED ISSUE #3988: Request:  Google Crowdsource Icon
**Name:** Google Crowdsource
**Website:** https://crowdsource.google.com/
**Alexa rank:** https://www.alexa.com/siteinfo/google.com
  

**Official resources for icon and color:** https://crowdsource.google.com/

### PR DESCRIPTION
**Pull request by adamrusted**
googlecrowdsource

**Issue:** Fixes #3988
**Alexa rank:** N/A (Google Service)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG found by @PeterShaggyNoble, hex is Google Blue.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for this one, @adamrusted.

However, I'm noticing some small differences, on both sides, [in the "shoulders"](https://user-images.githubusercontent.com/15157491/109649165-6d3abc80-7b53-11eb-867c-6300fddc1252.png) and along the bottom curve.

Took a quick stab at it myself and got a little closer. Still not perfect, but it might help:
```
M 12 1.7714844 C 10.870861 1.7714844 9.9550781 2.6872677 9.9550781 3.8164062 C 9.9550781 4.945545 10.870861 5.8632812 12 5.8632812 C 13.129139 5.8632812 14.044922 4.945545 14.044922 3.8164062 C 14.044922 2.6872678 13.129139 1.7714844 12 1.7714844 z M 7.3632812 5.453125 C 6.2341426 5.453125 5.3183594 6.3708613 5.3183594 7.5 C 5.3183594 8.6291387 6.2341426 9.5449219 7.3632812 9.5449219 C 8.49242 9.5449219 9.4082031 8.6291387 9.4082031 7.5 C 9.4082031 6.3708613 8.4924199 5.453125 7.3632812 5.453125 z M 16.636719 5.453125 C 15.50758 5.453125 14.591797 6.3708613 14.591797 7.5 C 14.591797 8.6291387 15.50758 9.5449219 16.636719 9.5449219 C 17.765858 9.5449219 18.681641 8.6291387 18.681641 7.5 C 18.681641 6.3708613 17.765858 5.453125 16.636719 5.453125 z M 1.3457031 7.6367188 C 1.0127913 7.631264 0.67648122 7.749947 0.41601562 7.9960938 C -0.079005305 8.4611134 -0.14035125 9.2269659 0.27148438 9.765625 L 1.6386719 11.552734 L 2.9238281 13.230469 C 3.6452223 14.172782 4.0351563 15.327258 4.0351562 16.513672 C 4.0351562 18.032826 4.7447771 19.479977 5.984375 20.355469 C 6.7514469 20.897948 7.5988393 21.328385 8.5 21.646484 L 8.5 17.722656 C 8.5 17.130085 8.6745462 16.583598 8.9550781 16.101562 C 8.8522759 15.152404 8.4512241 14.257889 7.7734375 13.574219 L 2.3417969 8.1054688 L 2.2617188 8.0273438 C 2.0087533 7.7730146 1.6786149 7.6421735 1.3457031 7.6367188 z M 22.65625 7.6367188 C 22.323338 7.6421735 21.992518 7.7730146 21.740234 8.0273438 L 17.195312 12.601562 L 16.226562 13.576172 C 15.549264 14.258167 15.14877 15.149555 15.044922 16.095703 C 15.310313 16.550607 15.482261 17.063327 15.5 17.619141 L 15.5 17.626953 L 15.5 21.648438 C 16.401174 21.330254 17.248856 20.898549 18.015625 20.355469 C 19.25386 19.479977 19.964844 18.032826 19.964844 16.513672 C 19.964844 15.325894 20.356142 14.170829 21.076172 13.228516 L 22.048828 11.957031 L 23.728516 9.765625 C 24.140351 9.2269659 24.077641 8.4611134 23.583984 7.9960938 C 23.322837 7.749947 22.989162 7.631264 22.65625 7.6367188 z M 12 9.1347656 C 10.870861 9.1347656 9.9550781 10.052502 9.9550781 11.181641 C 9.9550781 12.310779 10.870861 13.226562 12 13.226562 C 13.129139 13.226562 14.044922 12.310779 14.044922 11.181641 C 14.044922 10.052502 13.129139 9.1347656 12 9.1347656 z M 12.001953 14.863281 C 10.343701 14.863281 9 16.143498 9 17.722656 L 9 21.814453 C 9.9518582 22.081738 10.956774 22.228516 12 22.228516 C 13.043226 22.228516 14.048142 22.083101 15 21.814453 L 15 17.634766 C 14.950907 16.096519 13.62884 14.863281 12.001953 14.863281Z
```

**Comment by adamrusted** [comment]
Thanks @PeterShaggyNoble - using your path and removing one or two excess points, I've been able to get it matching at 4 decimals.

**Comment by PeterShaggyNoble** [comment]
Still seeing some small differences in the same 4 places, @adamrusted. It looks like you should be able to fix that, though, just by dragging the point of each corner out to meet the curve of the original.

**Comment by adamrusted** [comment]
Should be resolved @PeterShaggyNoble 🤞

**Review by PeterShaggyNoble — APPROVED** [review]
SVG looks perfect now, @adamrusted 👍🏻 Nice work.

Looking at [their site](https://crowdsource.google.com/about/) and [app](https://play.google.com/store/apps/details?id=com.google.android.apps.village.boond) the brand name seems to be just "Crowdsource" so I think we should go with that. Once that change is made then this can be merged straight in.

**Comment by adamrusted** [comment]
Sorted, thanks @PeterShaggyNoble!
Will wait for the checks to process and merge it straight in.

**Pull request merged**
