### PR TITLE
Add Piwigo

### PR DESCRIPTION
**Pull request by gitschneider**
piwigo

**Issue:** none, had the logo anyway

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The hex value ist the value of the outer ring.
I took the original svg logo, extracted the image part and merged it into a single path.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @gitschneider and thanks for the contribution.

A couple of minor corrections before we can merge this in, though:
1. Could you try optimising the path with a precision of 3 rather than 2? I'm seeing some small differences around the outer edges of the camera and inner edges of the flash.
2. Can you update the source URL to https://github.com/Piwigo/piwigodotorg/blob/6edb840c16257314caec770a9a51f67ef81836e4/images/piwigo.org.svg, which is the latest commit hash you get after hitting `y` when viewing [this URL](https://github.com/Piwigo/piwigodotorg/blob/master/images/piwigo.org.svg).

**Comment by PeterShaggyNoble** [comment]
Thanks for the speedy update, @gitschneider - the SVG looks spot on to me now

One other quick correction, though, please: the hex value should be uppercase. My apologies for missing it in my initial review, despite it causing the build to fail - this is why I shouldn't be allowed to review contributions without sufficient caffeine! 😆

**Comment by gitschneider** [comment]
Oh damn, I missed that too and somehow thought it should be lower case :D 
It would be great, if this check was included in the `npm run our-lint`.

**Comment by PeterShaggyNoble** [comment]
@gitschneider, it's included in `jsonlint`.

Thanks again for your work on this one, it's good to go now :+1:

**Comment by ericcornelissen** [comment]
> Oh damn, I missed that too and somehow thought it should be lower case :D
> 
> It would be great, if this check was included in the `npm run our-lint`.

> gitschneider, it's included in jsonlint.
> 
> Thanks again for your work on this one, it's good to go now +1

It might be an idea to add new command called `npm run lint` that runs all our linting scripts :thinking:

**Pull request merged**
