### PR TITLE
Qiskit icon

### PR DESCRIPTION
**Pull request by eugena**
image

https://qiskit.org/

**Issue:**
**Alexa rank:** 453,690 (https://www.alexa.com/siteinfo/qiskit.org)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @eugena

Which source file did you base your version on, though, as I'm seeing [some notable differences](https://user-images.githubusercontent.com/15157491/108382533-d5f37200-7200-11eb-94f5-ecdc915a664c.png) when comparing the SVG in their website header (in black) with yours (in red)? I'm also getting `#6929c4` for the colour.

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @eugena. However, I'm still seeing [some less pronounced differences](https://user-images.githubusercontent.com/15157491/109034930-0be09c80-76c0-11eb-8cda-704bd7273f7a.png) between your version and the source.

I think that may be a software issue, though; when I tried to recreate the icon in Inkscape myself by performing a `union` of all the paths, I got some similar distortions. I did get better results using the SVG in the header of [this page](https://qiskit.org/documentation/) but, unfortunately, it still wasn't quite perfect. Could one of the other @simple-icons/maintainers give this a try with different software to see what the results are like?

**Review by adamrusted — CHANGES_REQUESTED** [review]
I'm also seeing some differences to the icon [see here](https://user-images.githubusercontent.com/1830867/109192972-cb505400-778f-11eb-8c89-255c398fe833.png) when rebuilding from scratch. Unfortunately, the original SVG doesn't want to open correctly in Illustrator, so I've had to use InkScape which I'm less familiar with.

I, much like @PeterShaggyNoble used the union path tool, which _should_ just combine all the paths without making any changes.

Could you take another look at this one please @eugena? Happy to export my path now I've got it working in Illustrator if you want to compare against that?

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks @eugena for taking another look at this!
Unfortunately, I can still see some faint differences between your PR (red) and the source URL (header SVG on homepage of website) in black. [See Here.](https://user-images.githubusercontent.com/1830867/109393394-4abd5f00-7919-11eb-8394-e98d3067ffe7.png)

It may just be down to the precision of SVGO - so you may need to take the decimals up to 4 when optimizing. If you're using the CLI version you'll need to edit `svgo.config.js` - there's a line near the top that is set to 3 which you can amend to 4 just to run the script. If you're using SVGO it's either called Precision or Decimals, I'm unsure which it is.

**Review by adamrusted — CHANGES_REQUESTED** [review]
Looks a lot better @eugena, though I'm still seeing a slight difference when comparing to the header image at source. Is that the version you're using? If so, it may be worth re-building the SVG from scratch making sure your editing software is outputting at least 4 decimals.

image

**Review by adamrusted — CHANGES_REQUESTED** [review]
Hi @eugena - thanks again for looking at this, though I'm still seeing [similar issues](https://user-images.githubusercontent.com/1830867/109500168-c5a78680-7a8d-11eb-80da-3dc5d15e6a05.png).

I've been able to get a path at 4 decimals, which passes the linter and matches the source SVG - you're welcome to use it, though we'll need another reviewer of you do.

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Qiskit icon</title><path d="M11.9662 0a11.9915 11.9915 0 0 0-.5925 23.9665 6.17 6.17 0 0 0 .6437.0335c.2382 0 .468-.0138.6886-.0381a11.9915 11.9915 0 0 0 11.279-11.8035 1.349 1.349 0 0 0 .0067-.1157v-.0342a1.403 1.403 0 0 0-.006-.11 11.9915 11.9915 0 0 0-1.4156-5.5601A11.9915 11.9915 0 0 0 11.9702 0h-.004zm0 .8392c1.2334 0 2.0728.274 2.0728.5139 0 .2398-.8566.5484-2.0557.5484-1.1992 0-2.0898-.2912-2.0898-.531 0-.2399.8565-.5313 2.0727-.5313zm2.8805.3673a11.1863 11.1863 0 0 1 4.995 2.8363c-1.967-.754-4.8277-1.1702-7.6014-1.1992-1.3457 0-2.7008.0896-3.9736.2583a1.0278 1.0278 0 0 0-1.7615.2961c-.864.1805-1.6557.4033-2.3391.6649a11.1692 11.1692 0 0 1 4.9154-2.8313 1.0346 1.0346 0 0 0-.0104.1389c0 1.2334 2.0214 1.336 2.9122 1.336s2.878-.1197 2.878-1.336c0-.0572-.006-.1114-.0146-.164zm-2.6064 2.4422c5.4818.0685 9.302 1.4904 9.302 2.7238 0 .8253-1.7305 1.7051-4.4446 2.2303-1.533-.2227-3.1821-.3482-4.806-.363-.5953 0-1.192.0176-1.786.0448L8.2662 4.4025a1.0278 1.0278 0 0 0 .2241-.524c1.1436-.1448 2.4046-.2298 3.75-.2298zm-5.6923.557a1.0278 1.0278 0 0 0 .9472.5735 1.1306 1.1306 0 0 0 .1368 0l2.0634 3.551c-.9549.0639-1.893.1598-2.785.2914-2.741-.5286-4.4346-1.4294-4.4346-2.2491 0-.0946.0253-.19.0696-.2857a11.1692 11.1692 0 0 1 .1515-.236c.5127-.6206 1.8994-1.226 3.851-1.645zm15.5404 2.9775a11.1692 11.1692 0 0 1 .9987 3.3542c-.8726-.6684-2.3127-1.2012-4.0404-1.5846 1.4598-.448 2.565-1.045 3.0417-1.7696zm-20.161.0311c.4877.729 1.5974 1.3211 3.044 1.7623-1.7297.3858-3.1595.9158-4.0293 1.5715a11.1692 11.1692 0 0 1 .9853-3.3338zm10.347 1.8134c.2925.0032.5796.0103.8639.0194-.4442.0189-.8952.0322-1.3604.0322a31.5922 31.5922 0 0 1-.8258-.0208l-.0044-.008a39.693 39.693 0 0 1 1.3266-.0228zm4.9157.3801c3.6457.5523 5.949 1.6142 5.9944 2.5793a11.1692 11.1692 0 0 1 0 .0412c-.043.964-2.3724 2.004-5.9409 2.5585-1.0463-.2007-2.1777-.3418-3.3308-.4189l-1.5354-2.6391-.9438-1.6358c.109.0023.2182.0072.3269.0084 1.8743 0 3.7696-.1718 5.4296-.4935zm-10.369.016c1.1792.2266 2.4655.375 3.7653.4394l1.157 1.9911 1.3096 2.2675a31.7987 31.7987 0 0 0-.8127-.0235c-1.894 0-3.8094.1731-5.4825.4986-3.4656-.5358-5.7045-1.534-5.9108-2.4639a11.1692 11.1692 0 0 1 0-.2566c.2112-.9356 2.5186-1.9212 5.974-2.4525zm16.2633 4.0756a11.1692 11.1692 0 0 1-.978 3.2964c-.4662-.7202-1.5345-1.3021-2.935-1.7385 1.6797-.3874 3.0647-.913 3.913-1.5579zm-22.1353.0201c.8515.6533 2.2325 1.174 3.8892 1.5545-1.3906.4364-2.4462 1.0106-2.922 1.7054a11.1692 11.1692 0 0 1-.9672-3.2599zm11.2912 1.3668c.44.0069.8649.0254 1.2824.0485l.0084.0144a39.6282 39.6282 0 0 1-1.7877.0401 39.3727 39.3727 0 0 1-1.4343-.0421 31.0887 31.0887 0 0 1 1.9312-.0609zm5.0903.5226c2.611.5393 4.2177 1.4099 4.2288 2.2183 0 .1154-.0359.2326-.1034.3496a11.1692 11.1692 0 0 1-.025.0395c-.394.6166-1.6917 1.2328-3.5751 1.6756a1.0278 1.0278 0 0 0-.819-.4199 1.045 1.045 0 0 0-.1543 0l-2.0771-3.57c.8672-.07 1.7161-.1666 2.5251-.293zm-10.6615.012c1.602.2481 3.345.3868 5.0572.4076a38.57 38.57 0 0 0 2.2715-.0673l2.234 3.8875a1.0278 1.0278 0 0 0-.1974.3852c-1.2746.1867-2.709.3-4.2565.3-4.7049-.0587-8.1833-1.1018-9.0863-2.176a11.1692 11.1692 0 0 1-.1713-.268c-.0382-.0881-.0604-.1758-.0616-.2627.0107-.8002 1.6368-1.6663 4.2104-2.2062zm13.2632 4.466a11.1692 11.1692 0 0 1-4.9113 2.8785c.0507-.1198.08-.245.08-.3757 0-.5564-.4854-1.0307-1.2507-1.3216a28.779 28.779 0 0 0 2.2922-.2456 1.0278 1.0278 0 0 0 1.899-.358c.6924-.1646 1.3297-.3577 1.8908-.5775zm-15.7846.049c1.5913.6111 3.765.997 6.001 1.1402-.7443.2871-1.2148.749-1.2148 1.2965v.017c0 .131.0308.2572.0836.3781a11.1692 11.1692 0 0 1-4.8698-2.8319zm7.8697 1.5972c1.3876 0 2.2614.4968 2.2785.8566.0124.2599-.4687.5814-1.2527.7404a11.1692 11.1692 0 0 1-2.1466-.0087c-.7273-.1737-1.1574-.4938-1.1574-.7317 0-.3427.8906-.8566 2.2782-.8566z"/></svg>
```

**Comment by eugena** [comment]
image

**Review by adamrusted — COMMENTED** [review]
Thanks @eugena! Looks like this matches up almost perfectly now. 💪
I'm going to request another @simple-icons/maintainers takes a look at this one, as there is still a _slight_ difference, which I'd be happy to allow providing I get another okay on it.

**Review by PeterShaggyNoble — APPROVED** [review]
That looks great now, @eugena 👍🏻 Thanks for your continued efforts on it

Like Adam, I am still seeing a few minor differences but, given how tricky the source was to work with and that the differences a extremely insignificant, I'm happy to run with this as-is for now and if anyone _can_ improve upon it we can update it later.

So, once the colour is updated (see [this comment](https://github.com/simple-icons/simple-icons/pull/5033#issuecomment-781440017)) then this will be ready to merge.

**Comment by PeterShaggyNoble** [comment]
Thanks for the quick update, @eugena; this one's good to go now.

**Pull request merged**
