### PR TITLE
Updated Kotlin

### PR DESCRIPTION
**Pull request by adamrusted**
kotlin

**Issue:** Contributes to #3169
**Alexa rank:** N/A

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> Not necessary
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Rebuilt from source, with gaps of 0.35px between sections.
Ran through SVGO CLI.

### CODE REVIEW

**Comment by adamrusted** [comment]
kotlin

Found an official monochrome source embedded in the `guidelines.pdf` within the source zip file. Clearer than the one I'd generated.

**Comment by fbernhart** [comment]
In the mentioned `guidelines.pdf` file, there are three monochrome versions:

image


Personally I would prefer the middle one (with the gaps), as it fits pretty good our "gap style" that we've already applied to quite a few other icons. But maybe some of the other @simple-icons/maintainers can give their opinions. 😊 

Here's the link to the ZIP file, that contains the mentioned PDF file: https://resources.jetbrains.com/storage/products/kotlin/docs/kotlin_logos.zip

**Comment by mondeja** [comment]
> Personally I would prefer the middle one (with the gaps), as it fits pretty good our "gap style" that we've already applied to quite a few other icons. But maybe some of the other @simple-icons/maintainers can give their opinions. blush

I agree :+1:

**Comment by adamrusted** [comment]
Consider it done! :smile:

**Comment by fbernhart** [comment]
@adamrusted Great! 👍🏼  Looks perfect!

**Pull request merged**
