### PR TITLE
New Icon: DaVinci Resolve

### LINKED ISSUE #6062: DaVinci Resolve Logo
**Brand Name:** DaVinci Resolve
**Website:** https://www.blackmagicdesign.com/products/davinciresolve/
**Alexa rank:** 5377
  

**Official resources for icon and color:** https://en.wikipedia.org/wiki/DaVinci_Resolve#/media/File:DaVinci_Resolve_Logo.png

### PR DESCRIPTION
**Pull request by CodedFlute**
simpleicons

**Issue:** closes #6062 

**Similarweb rank:** 18,374 (https://www.similarweb.com/website/blackmagicdesign.com/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
Converted from .tif image. Used image trace for inside, manual shape creation for outside circle.
Interpreted colour as foreground, can be changed if desired.
Color code taken from #8288

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for your work on this, @CodedFlute 👍🏻 

However, we will first need determine the popularity of this brand, as the Similarweb ranking is not an accurate reflection of it. Is there a Google Trends comparison that can be done with a similar brand that is either already in our collection or meets our ranking requirements, or is there some other metric we can use to gauge the popularity?

**Comment by CodedFlute** [comment]
@PeterShaggyNoble Yes, it is most comparable to adopt premier pro which is alread in you collection. I have linked a Google trends comparison between DaVinci resolve and Adobe Premier Pro, for context I also included Apple’s Final Cut Pro X which is a very similar and quite popular software in this field although it only runs on Mac.

https://trends.google.ca/trends/explore?date=today%205-y&q=%2Fg%2F1q5y_dyrm,%2Fm%2F043dqq,%2Fm%2F07_s4,%2Fm%2F0gtt1gb&hl=en-CA

**Comment by PeterShaggyNoble** [comment]
I was going to say that it outperforming Shotcut was a good enough indication of its popularity but, after checking its rank, Shotcut is now _way_ outside our scope. And DaVinci sitting in the midpoint between it and Premiere Pro isn't quite convincing enough in itself.

Is there anything, maybe, in #9979 that could help indicate its popularity?

**Comment by runxel** [comment]
No objection here. DaVinci is the (un)sung hero of movie editing. Pretty safe to say it fulfills our metrics.

**Comment by PeterShaggyNoble** [comment]
Right, now that's out of the way (thanks for your patience, @CodedFlute), we can start the review process!

It looks to me like the icon they provide at the `source` might actually be outdated. Scrolling down through [their product page](https://www.blackmagicdesign.com/products/) I see that they consistently use a square version rather than a circle and [their Wikipedia entry](https://en.wikipedia.org/wiki/DaVinci_Resolve) also uses the square version, which is [a good quality PNG](https://en.wikipedia.org/wiki/DaVinci_Resolve#/media/File:DaVinci_Resolve_Studio.png). Being more familiar with the brand (cc: @runxel), and to hopefully avoid having to start from scratch on this one, do they use the 2 versions interchangeably at all, or should we be using the square version?

**Comment by CodedFlute** [comment]
I think you are be right. Looking at their media kit they provide both logos with no indication on which one is more current. Looking at current logo usage it appears that the square one is currently more used and the round one was used for the previous software version. I will get started on updating it to the square logo soon.

**Comment by CodedFlute** [comment]
davinciresolve
Updated the logo to the version with the square boarder. Let me know if there are any more changes that need to be made.

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
Thanks for updating, @CodedFlute. Looking at the TIFF file in the zip file, though, this version should be a perfect square. Also, I don't know where the colour choice in the original PR came from but, lacking anything else more concrete to go on, what do you think of using the `#233a51` from the source file?

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @CodedFlute?

**Comment by CodedFlute** [comment]
davinciresolve
Made it square and updated the colour. Let me know if there are any more changes i should make.

**Review by PeterShaggyNoble — APPROVED** [review]
As far as manual vertorisations go, the SVG looks good to me now - nice work 🙂 

As it _is_ manually vectorised, though, we'll need the approval of one of the other @simple-icons/maintainers before merging. And I'd also like some input from them on the colour.

**Review by service-paradis — APPROVED** [review]
Looks good enough, good job 🎉

**Pull request merged**
