### PR TITLE
Add Microsoft SQL Server

### LINKED ISSUE #2445: Need icon for SQL Server
**Name:** SQL Server
**Website:** https://www.microsoft.com/es-es/sql-server/sql-server-2019
**Official resources for icon and color:** 🤷‍♂
  
microsoft-sql-server

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Microsoft SQL Server
**Issue:** Closes #2445

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Colour chosen is the [calculated midpoint](https://meyerweb.com/eric/tools/color-blend/#EE352C:A91D22:1:hex) of the red gradient.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Wanted to point out two things about the addition in this PR:

- The [source you linked](https://en.wikipedia.org/wiki/Microsoft_SQL_Server) does not actually have the logo on it 😅 [The SVG that was linked in the issue](https://de.wikipedia.org/wiki/Datei:Microsoft_SQL_Server_Logo.svg) is on [the German version of that page](https://de.wikipedia.org/wiki/Microsoft_SQL_Server)
- I can't find an official source for this, but judging by how the logo typically appears I think we **should** include the TradeMark symbol in the SVG 😞

**Comment by PeterShaggyNoble** [comment]
Thanks, @ericcornelissen. My bad on the source link; could've sworn I use the German page there! 🙄 I'm OK just commiting that change straight to `develop`, right?

We do have precedent for removing (registered) trademark symbols (ref: #2177 & #594) when they're not explicitly required but we should probably have a broader discussion on when they should and shouldn't be included.

**Comment by ericcornelissen** [comment]
> Thanks, @ericcornelissen. My bad on the source link; could've sworn I use the German page there! 🙄 I'm OK just commiting that change straight to develop, right?

Go right ahead!


> We do have precedent for removing (registered) trademark symbols (ref: #2177 & #594) when they're not explicitly required but we should probably have a broader discussion on when they should and shouldn't be included.

If it is not explicitly stated I'm fine if it is not there, I mainly pointed it out to see if you had considered it 😄 That said, having a (new, given #594) "formal" discussion about it in a separate issue might be useful.

**Comment by runxel** [comment]
The TradeMark symbol ™ is a misleading symbol and has no legal meaning whatsoever (opposed to the _registered_ trademark).
I would always exclude it.

In the end both are a tautological boilerplate. 😃

**Comment by ericcornelissen** [comment]
> The TradeMark symbol ™ is a misleading symbol and has no legal meaning whatsoever (opposed to the registered trademark).
> I would always exclude it.
> 
> In the end both are a tautological boilerplate. 😃

I agree with that, however, if a brand insist on ~~making their logo ugly~~ including the ™ in the icon then have to include it as well (regardless of it whether it has legal meaning).

**Pull request merged**
