### PR TITLE
Add DLNA

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
From previously abandonded #1339

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Sadly they don't have a svg on the website, I found only pngs. Color `#46AA42` is eyedropped.
(Funny btw how in the wordmark they write it lower case, opposing the running text, where it's upper case).

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
There's an SVG [here](https://upload.wikimedia.org/wikipedia/en/f/f0/Dlna.svg) if it's any use.

The green they use in the website's stylesheet is `#48a842` so should we go with that instead?

**Comment by runxel** [comment]
> The green they use in the website's stylesheet is `#48a842` so should we go with that instead?

Yeah, great choice. Updated it. Thank you! :)

**Comment by PeterShaggyNoble** [comment]
Looks good to me but I'll leave it to one of the other @simple-icons/maintainers to merge in so we can get another opinion on the colour choice.

**Comment by ericcornelissen** [comment]
Thanks for adding this (_finally_, 741 PRs later) @runxel  🎉

**Pull request merged**
