### PR TITLE
Add pkgsrc icon.

### PR DESCRIPTION
**Pull request by fraggerfox**
**Issue:** #7060
**Alexa rank:** 612,704
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- The hex value was chosen from the original logo at https://pkgsrc.org
- ~The logo was manually vectorized.~ The svg was taken from here https://pkgsrc.joyent.com/img/pkgsrc.svg

image

### CODE REVIEW

**Comment by sachinraja** [comment]
Closing this for now as the Alexa rank doesn't meet our requirement for inclusion. Please don't delete the branch so we can reopen once it meets our requirements.

**Comment by fraggerfox** [comment]
> Closing this for now as the Alexa rank doesn't meet our requirement for inclusion. Please don't delete the branch so we can reopen once it meets our requirements.

@sachinraja pkgsrc is a subproject within The NetBSD Foundation 

https://www.alexa.com/siteinfo/netbsd.org

Kindly do not close this PR.

**Comment by sachinraja** [comment]
Will discuss more in #7060

**Review by sachinraja — CHANGES_REQUESTED** [review]
I'm really not good at checking against images, but the angle does seem to be off here:
image
(orange is original, red is the one here)

**Comment by fraggerfox** [comment]
> I'm really not good at checking against images, but the angle does seem to be off here: image (orange is original, red is the one here)

Let me look into this, could be error from my side when the conversion happened.

**Comment by fraggerfox** [comment]
@sachinraja Regenerated the svg from the following source, https://pkgsrc.joyent.com/img/pkgsrc.svg let me know if the orientation looks fine now.

**Comment by fraggerfox** [comment]
@sachinraja Here is the new SVG compared to the picture posted by you (orange - original, red - previous svg, darker red - new svg)

image

Let me know what you think.

**Review by sachinraja — APPROVED** [review]
Awesome, this is a perfect match

**Pull request merged**
