### PR TITLE
Split release workflow into two workflows

### PR DESCRIPTION
**Pull request by ericcornelissen**
Split the release workflow - which so far created and helped merging release PRs - into one workflow for creating the release PR and one for helping to merge it. This follows the discussion in #4276 and #4334.

### CODE REVIEW

**Review by mondeja — APPROVED** [review]

**Comment by mondeja** [comment]
If you've setted the keys, feel free to merge.

**Comment by mondeja** [comment]
I don't do the merge because I can't be sure if the keys are correct. I guess in these cases it's up to you @ericcornelissen :upside_down_face:

**Comment by ericcornelissen** [comment]
Alright, then I'll merge :slightly_smiling_face: 

For your information. The `secrets.GITHUB_TOKEN` is always provided by default by GitHub Actions and is also used in e.g. [our labeler workflow](https://github.com/simple-icons/simple-icons/blob/47a94a6308a4610a048ac020849efaeea138132c/.github/workflows/labeler.yml#L12). The `secrets.RELEASE_TOKEN` is custom and defined by us in this repositories settings as one of the maintainers Personal Access Tokens, [it was already used in the workflow that has now been removed](https://github.com/simple-icons/simple-icons/blob/47a94a6308a4610a048ac020849efaeea138132c/.github/workflows/release.yml#L16).

**Comment by mondeja** [comment]
But, you are using `secrets.NPM_TOKEN` in this pull... Maybe it's a mistake?

**Comment by ericcornelissen** [comment]
Oops :sweat_smile: You're right. Fixed it in f2dc5287805c7ab9521bf7d9ec46ebc54534316b

**Pull request merged**
