### PR TITLE
Add Test-St-Petersburg

### PR DESCRIPTION
**Pull request by sergey-s-betke**
**Issue:** none
**Alexa rank:** 1155803
  

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by adamrusted** [comment]
Thanks for the contribution, @sergey-s-betke! 💪
Unfortunately, it looks as though this project is _very_ out of scope for us (see our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) regarding scope). I'm also not 100% sure, but I don't think we can use the Alexa rank as the source you've linked to is a subdomain, and Alexa only looks at the top-level domain of `spb.ru`. Before I close this one out though, I'll ping the other @simple-icons/maintainers for input on this also.

**Comment by sergey-s-betke** [comment]
> Thanks for the contribution, @sergey-s-betke! 💪
> Unfortunately, it looks as though this project is _very_ out of scope for us (see our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) regarding scope). I'm also not 100% sure, but I don't think we can use the Alexa rank as the source you've linked to is a subdomain, and Alexa only looks at the top-level domain of `spb.ru`. Before I close this one out though, I'll ping the other @simple-icons/maintainers for input on this also.

Thank you! Alexa rank source: https://www.alexa.com/siteinfo/rustest.spb.ru. It is for rustest.spb.ru. Test-St-Petersburg - is the biggest metrology center of Russia. Please, add this logo to your project. Thank You!

**Comment by ericcornelissen** [comment]
Hi @sergey-s-betke, while I appreciate the effort I think I agree with @adamrusted that this is out of scope.

We intentionally put a limit on the icons we accept into the project for various reason (e.g. maintaining them takes effort, icons may need to be removed, package size) and we intentionally have clear and comparable measures for this. Being the biggest in a country is quite something, but 1) it is hard to verify for us if none of is comes from that country, and, more importantly, 2) it does not imply popularity.

That said, we are open to other measures of popularity so I won't close this quite yet. If you can show us another metric of the popularity that implies a need for the icon please share it here 🙂

**Comment by sergey-s-betke** [comment]
Ok, thank You.

**Pull request closed without merging**
