### PR TITLE
Add EmulationStation

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
EmulationStation

**Issue:** Templarian/MaterialDesign#5025

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Does this fall into the same grey area as Popcorn Time?

**Alexa rank:** [~390k](https://www.alexa.com/siteinfo/emulationstation.org)

### CODE REVIEW

**Comment by adamrusted** [comment]
This looks good to me - @simple-icons/maintainers do we have any objections to adding this icon?

**Comment by fbernhart** [comment]
The Alexa rank of [842,121](https://www.alexa.com/siteinfo/emulationstation.org) would clearly state "out of scope".

**Comment by adamrusted** [comment]
> The Alexa rank of [842,121](https://www.alexa.com/siteinfo/emulationstation.org) would clearly state "out of scope".

Yikes! Didn't spot that! I'll close this issue for now @PeterShaggyNoble - unless another @simple-icons/maintainers wants to keep this open.

**Comment by PeterShaggyNoble** [comment]
Wow! That dropped off a cliff since I submitted this PR - I wonder what happened to them?

Going to ping @Asthonishia here, who originally requested it from MDI, to see if they can provide an alternative metric of popularity we can use to determine its suitability for inclusion.

**Comment by PeterShaggyNoble** [comment]
Bumping this for monitoring purposes as there has been significant improvement in their ranking since last we checked and although still south of 500k (~591k) as of now they should break it within a month if they continue on their current trajectory.

**Pull request closed without merging**
