### PR TITLE
Add DTS icon

### LINKED ISSUE #8829: Request: DTS icon
### Brand Name

DTS

### Website

https://dts.com/

### Popularity Metric

The Similarweb global rank is 365,334 currently. See: https://www.similarweb.com/website/dts.com/#overview.

### Official Resources for Icon and Color

From Wikipedia
svg: https://upload.wikimedia.org/wikipedia/commons/1/1c/Dts_D.E._logo.svg

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
dts

**Issue:** closes #8829 

**Similarweb rank:**
The similarweb rank is 365,334. See https://www.similarweb.com/website/dts.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from brand owener page at https://xperi.com/brands/dts/
Color: `#f98b2b` taken from website header by averaging out the colors https://dts.com/about-us/

### CODE REVIEW

**Comment by PratyushJayachandran** [comment]
> The `®` sign can be removed. See https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#icon-guidelines

I have updated the icon
dts

**Review by LitoMore — CHANGES_REQUESTED** [review]
image

I can see some differences.

The expected size is:

image

But yours:

image

By the way, you could review the difference before submitting the code so that we can save some time in merging your icon requests.

**Comment by PratyushJayachandran** [comment]
> By the way, you could review the difference before submitting the code so that we can save some time in merging your icon requests.

How do you check the fit? Do you download the SVG from source and compare it? How do I review the difference?

I must have accidentally scaled it non proportionally. I'll fix and recommit.

**Comment by LitoMore** [comment]
@PratyushJayachandran I'm using Inkscape.

1. Download the image from your PR, open it with Inkscape
1. Drag the source image to the canvas
1. Remove unused shapes
1. Resize it to 24
1. Change its fill to `#ffffff`
1. Move it to the vertical center and horizontal center

Sometimes I also use `View - Display Mode - Outline` to check the difference.

The `Edit paths by nodes` feature is helpful for checking redundant control points.

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran I'm using Inkscape.
> 
>     1. Download the image from your PR, open it with Inkscape
> 
>     2. Drag the source image to the canvas
> 
>     3. Remove unused shapes
> 
>     4. Resize it to 24
> 
>     5. Change its fill to `#ffffff`
> 
>     6. Move it to the vertical center and horizontal center
> 
> 
> Sometimes I also use `View - Display Mode - Outline` to check the difference.
> 
> The `Edit paths by nodes` feature is helpful for checking redundant control points.

Oh I understand! I thought you download from source to check if someone scaled the image non proportionally. I don't use inkscape but I'm trying to learn it nowadays so I'll give it a try. Thanks for explaining in detail 🙂

**Comment by PratyushJayachandran** [comment]
> image
> 
> I can see some differences.

I fixed it.

**Comment by LitoMore** [comment]
image

Hey @PratyushJayachandran, there is no need to update the branch every time. I will update it when I prepare to merge the code.

The `update branch` action will send a notification to my GitHub, which is annoying. I appreciate your understanding.

**Comment by PratyushJayachandran** [comment]
> The `update branch` action will send a notification to my GitHub, which is annoying. I appreciate your understanding.

Understood... Won't do it 🙂

**Review by LitoMore — APPROVED** [review]
image

LGTM.

**Pull request merged**
