### PR TITLE
Add Imou

### LINKED ISSUE #5440: Request: Imou
**Brand Name:** Imou
**Website:** https://www.imoulife.com/
**Alexa rank:** 102,278

**Official resources for icon and color:**
  https://www.imoulife.com/public/asset/images/web/logo.png

### PR DESCRIPTION
**Pull request by jonathanathe**
imou

**Issue:** Closes #5440
**Alexa rank:**102,278
  

### Checklist
  - [- ] I updated the JSON data in `_data/simple-icons.json`
  - [ -] I optimized the icon with SVGO or SVGOMG
  - [ -] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @jonathanathe and thanks for the contribution 🙂

Looks like you forgot to include the SVG file in your PR which is why the build is currently failing. If you drop it into the `icons` directory of the "patch-1" branch on your fork, it will get added to the PR.

In addition, I'd suggest updating the source URL to https://www.imoulife.com/support/download/userManual and using the `#E89313` from their website stylesheet - sourcing colours from PDFs isn't always accurate as they may use a different colour model (e.g., CMYK) which doesn't always translate exactly to RGB equivalents.

**Comment by jonathanathe** [comment]
Hi @PeterShaggyNoble , I think I've made the changes but I'm not entirely sure.

**Comment by PeterShaggyNoble** [comment]
Look like you added it to the `develop` branch on your fork, @jonathanathe, rather then the `patch-1` branch being used for this PR. Here's a direct link to the `icons` directory on that branch: https://github.com/jonathanathe/simple-icons/tree/patch-1/icons

**Comment by jonathanathe** [comment]
@PeterShaggyNoble I have already added it where indicated

**Comment by PeterShaggyNoble** [comment]
Thanks, @jonathanathe. The build is failing this time, however, because the SVG's file name should be `imou.svg`.

The icon itself is almost perfect apart from [some differences](https://user-images.githubusercontent.com/15157491/114893612-c7db5f80-9e05-11eb-9afb-736d956f6f31.png) in the "m" and the "o" (your version in red). After recreating the icon myself, though, I can confirm that it's not down to anything you did wrong but rather to the precision during the optimisation process. If you run it through the optimiser you used again with a precision of 4, that will solve it.

Also, don't forget to update the source URL in the JSON 😉

**Comment by jonathanathe** [comment]
@PeterShaggyNoble What goes wrong now?

**Comment by PeterShaggyNoble** [comment]
A couple of things seem to have gone missing from your SVG file, the `role` attribute on the `svg` tag and the `title` tag - see full markup below. And the precision during optimisation still needs to be increased to 4 on top of that.
```html
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Imou icon</title><path d="M14.642 9.148A2.857 2.857 0 0011.786 12a2.857 2.857 0 005.712 0 2.857 2.857 0 00-2.856-2.852zm-9.817.005a2.504 2.504 0 00-2.503 2.5v2.953c0 .088.072.16.16.16h.973a.16.16 0 00.16-.16v-2.953a1.21 1.21 0 012.419 0v2.953c0 .088.072.16.16.16h.973a.16.16 0 00.16-.16v-2.953a1.21 1.21 0 012.419 0v2.953c0 .088.072.16.16.16h.973a.16.16 0 00.16-.16v-2.953c0-1.379-1.122-2.5-2.502-2.5-.737 0-1.398.321-1.856.828a2.495 2.495 0 00-1.856-.828zM.16 9.284a.161.161 0 00-.16.161v5.16c0 .09.072.161.16.161h.964a.16.16 0 00.16-.16v-5.16a.161.161 0 00-.16-.162zm18.288 0a.161.161 0 00-.161.161v1.45c0 .088.072.16.16.16h.964a.16.16 0 00.16-.16v-1.45a.16.16 0 00-.16-.16zm4.427 0a.16.16 0 00-.161.161v1.45c0 .088.072.16.161.16h.963a.16.16 0 00.16-.16v-1.45a.16.16 0 00-.16-.16zm-8.234 1.147c.867 0 1.571.704 1.571 1.569a1.572 1.572 0 01-3.142 0c0-.865.705-1.57 1.571-1.57zm3.807 1.258a.16.16 0 00-.161.16v.08c0 1.545 1.2 2.862 2.746 2.92A2.858 2.858 0 0024 12v-.15a.161.161 0 00-.161-.16h-.963a.16.16 0 00-.16.16V12a1.572 1.572 0 01-3.144 0v-.15a.16.16 0 00-.16-.16z"/></svg>
```

**Comment by jonathanathe** [comment]
@PeterShaggyNoble I'm sorry but I don't understand what I have to do. And the optimisation I already set it to 4 on the website I use, I don't understand why it says it's not there yet.

**Comment by PeterShaggyNoble** [comment]
Just missing the word "icon" in the `title` tag now.

With regard to re-optimising the file with increased precision; make sure you're optimising your original, pre-optimised SVG rather than the version included in the PR. If you're still having trouble with it, you're more than welcome to use my version below:
```html
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Imou icon</title><path d="M14.6426 9.1484c-1.5747 0-2.8555 1.279-2.8555 2.8516 0 1.5724 1.2808 2.8516 2.8555 2.8516 1.5748 0 2.8554-1.2792 2.8554-2.8516 0-1.5725-1.2806-2.8516-2.8554-2.8516zm-9.8184.0059c-1.3802 0-2.502 1.12-2.502 2.498v2.9532c0 .0886.0714.1601.1602.1601h.9727a.1598.1598 0 0 0 .1601-.1601v-2.9532c0-.6656.5425-1.207 1.209-1.207.6667 0 1.209.5414 1.209 1.207v2.9532c0 .0886.0733.1601.1621.1601h.9707a.1615.1615 0 0 0 .1621-.1601v-2.9532c0-.6656.5423-1.207 1.209-1.207.6665 0 1.209.5414 1.209 1.207v2.9532c0 .0886.0714.1601.1601.1601h.9727a.1598.1598 0 0 0 .1602-.1601v-2.9532c0-1.378-1.122-2.498-2.502-2.498-.7367 0-1.397.3209-1.8555.8281-.4582-.5072-1.1209-.8281-1.8574-.8281zm-4.664.1309A.1596.1596 0 0 0 0 9.4453v5.1602c0 .0888.0714.1601.1602.1601h.9628a.1614.1614 0 0 0 .1622-.1601V9.4453a.1615.1615 0 0 0-.1622-.1601H.1602zm18.289 0a.1612.1612 0 0 0-.162.1601v1.4492c0 .089.073.1602.162.1602h.963a.1596.1596 0 0 0 .16-.1602V9.4453a.1596.1596 0 0 0-.16-.1601h-.963zm4.4278 0a.1612.1612 0 0 0-.1622.1601v1.4492c0 .089.0732.1602.1622.1602h.9628A.1596.1596 0 0 0 24 10.8945V9.4453a.1596.1596 0 0 0-.1602-.1601h-.9628zm-8.2344 1.1464c.8663 0 1.5703.7035 1.5703 1.5684 0 .865-.704 1.5684-1.5703 1.5684-.8664 0-1.5723-.7035-1.5723-1.5684 0-.865.706-1.5684 1.5723-1.5684zm3.8066 1.2579a.1615.1615 0 0 0-.162.1601v.08c0 1.5443 1.2004 2.8615 2.746 2.92C22.6579 14.9108 24 13.6088 24 12v-.1504a.1598.1598 0 0 0-.1602-.1601h-.9628a.1615.1615 0 0 0-.1622.1601V12c0 .8651-.704 1.5684-1.5703 1.5684-.8663 0-1.5722-.7033-1.5722-1.5684v-.1504a.1597.1597 0 0 0-.1602-.1601h-.9629Z"/></svg>
```

**Comment by jonathanathe** [comment]
@PeterShaggyNoble Many thanks to you for your great patience.

**Comment by adamrusted** [comment]
Icon looks spot on! Thanks for your work on this @jonathanathe (welcome to Simple Icons!) and @PeterShaggyNoble 💪 I'll merge this now, and it'll get released on Sunday! 🎉

**Pull request merged**
