### PR TITLE
Updated Coursera

### PR DESCRIPTION
**Pull request by fbernhart**
coursera

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
It seems that Coursera is using the "C" letter of their wordmark as their symbol now as you can see [here](https://blog.coursera.org/evolving-courseras-brand-identity/). Also their color has been changed to `#0056D2`. Could you rebuilt from source using this new version @fbernhart?

**Comment by fbernhart** [comment]
@mondeja Would you go for the full wordmark "coursera" now? Apart from the favicon, I haven't found any other place, where the just use the "C". On their website, their blog as well on all of their social media presence (Facebook, Instagram, Youtube, Twitter, LinkedIn) they are using always the full wordmark.

**Comment by mondeja** [comment]
See in the link that I've posted previously, the section "From infinity to C", their favicon, and other photographies with their proffesionals, all are pointing to the "C" as their symbol.

**Comment by fbernhart** [comment]
@mondeja I've now vectorized the biggest version of the "C and the circle" that I've found. It's this one:
https://about.coursera.org/icons-4e4a40baff9dd2d8374a43b4651f5537/apple-touch-startup-image-2048x2732.png

coursera

**Review by mondeja — APPROVED** [review]
Maybe in the future they will share their logo vectorized, but anyway this version is of very good quality.
Good work @fbernhart! :trophy:

**Pull request merged**
