### PR TITLE
Remove Babylon.js

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
**Issue:** ref: #6317 & #8737

### Description
As permission to include a monochrome version of Bablylon.js' icon was not sought prior to #8737 being merged and we have yet to receive a response to our _request_ for permission to do so, we will need to remove Babylon.js from our collection. If permission _is_ granted prior to the release of v11 then this PR can be closed.

### CODE REVIEW

**Review by adamrusted — APPROVED** [review]

**Comment by jglamp** [comment]
Has this ever mentioned to Babylon.JS? If not, I can send an issue to their branding to see if we can get this sorted.

**Comment by adamrusted** [comment]
Don't think so, no. We've recently started cracking down on requiring permission, and BabylonJS was one that we previously hadn't obtained permission for. Happy for you to reach out if you like, see the new [guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission) if you're unsure.

**Comment by jglamp** [comment]
Alright I reached out. [See here.](https://github.com/BabylonJS/Brand-Toolkit/issues/6)

**Comment by RaananW** [comment]
Answered in the referenced issue. Thanks for reaching out!

**Pull request merged**
