### PR TITLE
Update U Brands

### PR DESCRIPTION
**Pull request by adamrusted**
**Issue:** Contributes to #5251.

### Notes
- Uber's media assets aren't downloading for me at the moment. May be an issue with the ZIP we need to keep an eye on.
- Do we need to include the ® on the [Ubiquiti](https://www.ui.com/marketing/#logos) logo?

### CODE REVIEW

**Comment by service-paradis** [comment]
> * Uber's media assets aren't downloading for me at the moment. May be an issue with the ZIP we need to keep an eye on.

image
Using the URL from the console error message (https://newsroomapi.uber.com/wp-content/uploads/2018/09/PNG-20180910T163831Z-001.zip?_ga=2.198979055.1343858345.1617651557-184396900.1617651557), we're able to download the assets. It contains PNG files only though.

---

> * Do we need to include the ® on the [Ubiquiti](https://www.ui.com/marketing/#logos) logo?

I think so according to https://dl.ubnt.com/compliance/Trademark_Guidelines_v2.pdf
> Use the appropriate trademark symbol and trademark acknowledgment. Use the ® or ™ symbol in connection with
any Ubiquiti trademark or logo and use the following acknowledgement of Ubiquiti’s ownership: “[insert permissible
mark(s)] [is a/are] registered trademark[s] or trademark[s] of Ubiquiti Networks, Inc. in the United States and other
countries.”
• Do not modif

**Review by service-paradis — APPROVED** [review]
We can merge this one once we solve the Ubiquiti note 💯

**Review by service-paradis — CHANGES_REQUESTED** [review]
Using `Ubiquiti Networks U Logo CMYK` .ai file, I got some differences. Mostly in the curve:
image

Can you take another look at it?

In any case you want us to merge the data changes, you could also open a new PR for this icon.

**Comment by adamrusted** [comment]
Cool, let's scrap the SVG for now - and I'll make a new issue. Feel free to revert my changes to the SVG and merge, providing the JSON is okay.

**Review by PeterShaggyNoble — APPROVED** [review]
Nice short one this time 🙂

Thanks, @adamrusted :+1:

**Pull request merged**
