### PR TITLE
Add Roblox icon

### LINKED ISSUE #5097: Request: Roblox Icon
**Brand Name: Roblox**
**Website: web.roblox.com**
**Alexa rank: 93**
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by YolandaHaynes**
roblox

**Issue:** Closes #5097
**Alexa rank:** [94](https://www.alexa.com/siteinfo/roblox.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Created Roblox icon by following their official guidelines.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @YolandaHaynes and thanks for taking this one on 🙂

However, I'm seeing [a difference]https://user-images.githubusercontent.com/15157491/115584461-b5a86800-a2c2-11eb-998f-606eb8681aba.png) in the hole between your version (in red) when compared to `Logo_Roblox\tilt\roblox_tilt_black.ai`. Could you have another look at that and see if you can fix it up, please?

Also, while I too would have expected the colour to be black, from the brand guidelines PDF included in the zip file it looks like it should be either "Roblox Blue" (`#00a2ff`) or "Roblox Silver" (`#828da3`) and, from their website, the latter looks to be more dominant.

**Comment by YolandaHaynes** [comment]
Hi @PeterShaggyNoble.  I am still new to using a vector editor but I definitely do my best to adjust it to the correct position. 

I have a quick question in regards to the color. I was reading the guidelines as well and I read that the blue color is used for accents and their studio icon which is different from their logo. Also it was stated that "The use of a strongly contrasting black & white, accented by hues of grey, give our brand a sophisticated and refined feel."So I was a bit confused and went with black since it was still part of the guidelines colors. Is it best to go with Silver? I did notice they do use a grey hue/tone on their website as you said. Thank you very much for the feedback.

**Comment by PeterShaggyNoble** [comment]
> I am still new to using a vector editor but I definitely do my best to adjust it to the correct position

Did you maybe use a different source file for your version than I did for my comparison? If so then I think we should update to base it off the version I used as that's supplied specifically for use as an icon.

> I was reading the guidelines as well and I read that the blue color is used for accents and their studio icon which is different from their logo.

Missed that line. In that case, I think we're OK to stick with the black.

**Comment by YolandaHaynes** [comment]
@PeterShaggyNoble I used the same file that was in the press kit which was roblox_tilt_black.ai. But I may have done something while I was attempting to resize it that may have caused to change the tilt. I will redo it again and resubmit my new changes. Thank you for being patient with me, appreciate it.

**Review by PeterShaggyNoble — APPROVED** [review]
Thanks for the update, @YolandaHaynes, that looks spot on to me, now :+1:

As the zip file contains a PDF of their brand guidelines, the last thing I'd suggest is adding the `guidelines` entry to the icon's JSON and either duplicate the `source` URL or link directly to the zip. Once that's done then this will be ready to merge; if anyone wants to make a case for using a different colour, we can address that in a separate PR.

**Comment by PeterShaggyNoble** [comment]
Thanks for your work on this one, @YolandaHaynes 👍🏻

**Pull request merged**
