### PR TITLE
Add Vonage

### LINKED ISSUE #3734: Request: Vonage Icon
**Name:** Vonage
**Website:** https://www.vonage.com
**Alexa rank:** 6992

**Official resources for icon and color:**
From our brand guidelines:
White icon over black
or
Black icon over white

[03_Vonage_Symbol.zip](https://github.com/simple-icons/simple-icons/files/5397636/03_Vonage_Symbol.zip)

### PR DESCRIPTION
**Pull request by lukeocodes**
vonage

Close #3734
**Alexa rank:** 6992

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
  - #FFFFFF hex to match that of the homepage, brand guidelines stipulate black over white or white over black.
  - I took the official SVG, simplified the base code, and then optimized it with SVGO.
  - I work for Vonage

### CODE REVIEW

**Comment by service-paradis** [comment]
Hi @lukeocodes, thanks for your contribution! 😃 
I dont know if it is during the optimization process, but the current logo looks a little bit different than the original found on their website:
image

can you take a look at it?

**Comment by lukeocodes** [comment]
Hi @service-paradis certainly looks like an issue with the optimisation! I'll redo it, thanks! :)

**Comment by lukeocodes** [comment]
hey @service-paradis, 

I've taken the icon from our logo suite, resized it to 24x24 using illustrator, then optimized it using the maximum precision in svgomg UI (rather than the CLI).

Attached originals: [Symbol_Black.zip](https://github.com/simple-icons/simple-icons/files/5635652/Symbol_Black.zip)

**Comment by lukeocodes** [comment]
🤪  I've just pulled upstream for the linter changes. Apparently, illustrator strikes again... Despite being specifically set to 12px to centre, in the code it's 11.95px. 

Inkscape downloading 🤣

**Review by service-paradis — APPROVED** [review]
Looks perfect now 💯 
Thank you for your contribution!

**Pull request merged**
