### PR TITLE
Added Bio.Link

### PR DESCRIPTION
**Pull request by markbattistella**
134440335-f40a29ce-701b-4c84-acf3-e587d05a7b15

**Issue:** #6566 

**Alexa rank:** 20583

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by sachinraja** [comment]
The preview path does not seem to be the same as [the one in the file](https://github.com/simple-icons/simple-icons/blob/e83342a5bf05ae5ab4bcb5934abc12ca1ca671a9/icons/biolink.svg), which seems to have an issue on the `I`

**Comment by markbattistella** [comment]
Sorry @sachinraja not sure what happened - I've updated the SVG now

**Comment by sachinraja** [comment]
image
The current svg appears to be stretched in height, make sure to lock the dimensions.

image

**Comment by markbattistella** [comment]
> Sorry @sachinraja not sure what happened - I've updated the SVG now

fixed :)

**Comment by sachinraja** [comment]
image
Slight difference on the `B`, might need to increase the precision

**Comment by markbattistella** [comment]
> image
> Slight difference on the `B`, might need to increase the precision

attempted again, scaling was done at a percentage so hopefully this time its better. I was using Illustrator, but tried using Inkscape. I also think SVGOMG was messing with some number roundings.

z

**Review by sachinraja — APPROVED** [review]

**Comment by sachinraja** [comment]
Thanks for bearing with me, icon looks good now!

**Pull request merged**
