### PR TITLE
Update Medium icon

### PR DESCRIPTION
**Pull request by adamlui**
It changed last month from 

to

### Checklist

- [X] I optimized the icon with SVGO or SVGOMG
- [X] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by LitoMore** [comment]
I can see some differences:



You can follow the guide https://github.com/simple-icons/simple-icons/discussions/9351 with Inkscape to reprocess the icon.

**Review by LitoMore — CHANGES_REQUESTED** [review]

**Comment by adamlui** [comment]
How do you view the difference, when you drag and drop OG icon what import type do you pick

**Comment by adamlui** [comment]
Also the original SVG was two paths against a background, but since repo guideline says no non-path elements, I converted the PNG to SVG instead, using https://www.pngtosvg.com/ set to 1 color (explaining the trivial diff). IDK how I would accomplish the same by editing SVG in Inkscape, sounds very hardcore to clip paths from a background then convert to path w/o a 1-click converter

**Comment by LitoMore** [comment]
> How do you view the difference, when you drag and drop OG icon what import type do you pick

Convert the object to a path, then use difference calculation.

**Comment by adamlui** [comment]
But which import type is picked when executing the drag-and-drop step from your guide

image

Also is this Path > Object to Path > difference calculation an additional step to the diffing section of your linked guide or a new/separate method

**Comment by LitoMore** [comment]
Please use the official SVG resource. It can be downloaded at https://medium.design/logos-and-brand-guidelines-f1a01a733592.

**Comment by adamlui** [comment]
I did use the official Medium-Icon-Black.svg. I figured out how to Inkscape it to convert the rect + paths into single path:

1. Shift-click the 'M' + 'e' > Path menu > Combine
2. Click Fill and Stroke tab > click white swatch on bottom bar
3. Click black rect > Path menu > Object to Path
4. Ctrl+A to select both paths > Path menu > Difference
5. File menu > Document Properties > change Width/Height + Viewbox X/Y to 24
6. Change path X/Y to 0 + W/H to 24
7. Saved/uploaded to https://svgomg.net/ for Precision Level 3 optimization
8. Added `role="img"`, removed extraneous code

The following output is result:

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M4.21 0A4.201 4.201 0 0 0 0 4.21v15.58A4.201 4.201 0 0 0 4.21 24h15.58A4.201 4.201 0 0 0 24 19.79v-1.093c-.137.013-.278.02-.422.02-2.577 0-4.027-2.146-4.09-4.832a7.592 7.592 0 0 1 .022-.708c.093-1.186.475-2.241 1.105-3.022a3.885 3.885 0 0 1 1.395-1.1c.468-.237 1.127-.367 1.664-.367h.023c.101 0 .202.004.303.01V4.211A4.201 4.201 0 0 0 19.79 0Zm.198 5.583h4.165l3.588 8.435 3.59-8.435h3.864v.146l-.019.004c-.705.16-1.063.397-1.063 1.254h-.003l.003 10.274c.06.676.424.885 1.063 1.03l.02.004v.145h-4.923v-.145l.019-.005c.639-.144.994-.353 1.054-1.03V7.267l-4.745 11.15h-.261L6.15 7.569v9.445c0 .857.358 1.094 1.063 1.253l.02.004v.147H4.405v-.147l.019-.004c.705-.16 1.065-.397 1.065-1.253V6.987c0-.857-.358-1.094-1.064-1.254l-.018-.004zm19.25 3.668c-1.086.023-1.733 1.323-1.813 3.124H24V9.298a1.378 1.378 0 0 0-.342-.047Zm-1.862 3.632c-.1 1.756.86 3.239 2.204 3.634v-3.634z"/></svg>
```

For diffing you said "Convert the object to a path, then use difference calculation" but since originally it is 3 objects (1 rect + 2 paths) I repeated the above steps to convert rect to path + merge paths, then naturally difference calculation resulted in no changes, so IDK what method you wanna use but if changes are detected, can you confirm my above steps are optimal anyway?

**Comment by LitoMore** [comment]
@adamlui Here you go: 

https://github.com/user-attachments/assets/952a3a28-bf67-463e-97e9-4d704c28ea87

**Comment by adamlui** [comment]
Thank you for the recording, your steps are equivalent to mine except I didn't use outline for the diffing, but I have to sleep now so I will upload the new SVG produced using the steps I outlined in https://github.com/simple-icons/simple-icons/pull/12124#issuecomment-2466830091, then if it is unsatisfactory still, do you think you could do some final tweaks just so the icon can be updated (I've been waiting years for the old one to be replaced so this is a momentous occasion)

**Review by LitoMore — APPROVED** [review]
Perfect! 多謝！

**Pull request merged**
