### PR TITLE
Add Omada Cloud icon

### LINKED ISSUE #10320: Request: Omada Cloud
### Brand Name

Omada

### Website

www.tp-link.com

### Popularity Metric

I don't have access to SimilarWeb

### Official Resources for Icon and Color

https://static.tp-link.com/upload/menu/omada_20231205034833a.png

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by anhthang**
image

**Issue:** closes #10320 

**Popularity metric:**

Global Rank: 21,740
https://www.similarweb.com/website/tplinkcloud.com/#overview

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

SVG and hex value `#10c1d0` extracted from the website

### CODE REVIEW

**Review by adamrusted — COMMENTED** [review]
Which specific logo did you use? If I compare it to the dual-branding TP-Link Omada SVG in the header I'm getting the below results (PR in blac)
image

**Comment by anhthang** [comment]
I think I used the logo at the top of the login form

https://omada.tplinkcloud.com/theme/img/svg/Omada.svg

**Comment by adamrusted** [comment]
Hm, even with that one I'm seeing some _weird_ differences. @uncenter - are you able to take a look?
image

**Comment by uncenter** [comment]
Screenshot 2024-06-10 at 15 21 45 (Inkscape)

I'm seeing the same, original in the back, your path in red.

**Comment by anhthang** [comment]
hmm, let me look into this again

**Comment by anhthang** [comment]
image

I'm just open the original file, duplicate the group and see the differences. Should I continue?

**Comment by uncenter** [comment]
Huh, weird... thoughts @adamrusted?

**Comment by adamrusted** [comment]
This is a weird logo - so no fault of your own @anhthang!
Looking at your latest comparison, that _feels_ like it might be a stroke/optimization issue, which could be resolved by bumping the precision up when using SVGO. May be worth giving that a try and seeing if we can get closer?

**Review by adamrusted — CHANGES_REQUESTED** [review]
Sorry to dig up this PR @anhthang - I'm trying to work my way through our backlog.
Based on [the logo in the header](https://omada.tplinkcloud.com/theme/img/svg/TP-LinkOmada.svg), I'm still seeing quite significant differences after removing the stroke (your PR in black, source icon in white). If you'd prefer, I can supply a path and get another maintainer to review?

image

**Comment by anhthang** [comment]
Hi @adamrusted 
I have updated again based on the logo you are using. Please review again. If it's still not match, maybe we need someone else to involve to this PR or I can close it to open for another people

**Review by adamrusted — APPROVED** [review]
LGTM, thanks @anhthang!

**Pull request merged**
