### PR TITLE
Add Preact icon

### LINKED ISSUE #5779: Icon Add - Preact
**Brand Name:** Preact
**Website:** https://preactjs.com/
**Alexa rank:** 216,354
  
**Official resources for icon and color:**  -none-

### PR DESCRIPTION
**Pull request by wwwescape**
preact

**Issue:** Closes #5779
**Alexa rank:** 216,354
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I used the SVG from the header of [preactjs.com](https://preactjs.com/)
- I used Inkscape to remove the text, scale and adjust
- I used https://jakearchibald.github.io/svgomg/ to optimize

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @wwwescape 👍🏻

However, I'm seeing [some differences](https://user-images.githubusercontent.com/15157491/123400657-e8f6c400-d59d-11eb-873f-be8249091f9d.png) between your version (in red) and the version available in the header of the website; it looks like you've cut out a bit more than is necessary and, also, the rings don't quote line up. Gave it a quick try myself and there was some visual shift when converting the strokes to paths (Inkscape is a jerk like that!) so that accounts for some of it and the rest may possibly be down to the optimisation. Would you mind taking another look?

Also, I'm getting `#673ab8` for the colour from the website's stylesheet, which has the variable name `--color-brand`.

**Comment by wwwescape** [comment]
Sure @PeterShaggyNoble. I'll take another look at it over the weekend.

**Comment by wwwescape** [comment]
@PeterShaggyNoble I can't believe I didn't see the difference between my SVG and the original. Don't know what I was doing.

I updated the color as well as the SVG but I think there are _very very_ slight edges that don't line up. Could you review?

**Comment by elliotwutingfeng** [comment]
image
preact

Hi all, here's my take on this logo, would this work?

**Review by sachinraja — APPROVED** [review]
Thanks @elliotwutingfeng but I just checked the one in this PR and it matches up with the one in the Preact website header.

**Pull request merged**
