### PR TITLE
Update Disroot

### PR DESCRIPTION
**Pull request by mondeja**
image

**Issue:** #4590 
**Alexa rank:** [~440K](https://www.alexa.com/siteinfo/disroot.org)

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Just removed manually a collinear segment.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Looks like [Disroot](https://disroot.org/en) have updated their branding to use a, thankfully for us, much more simplified "D".

**Comment by mondeja** [comment]
> Looks like Disroot have updated their branding to use a, thankfully for us, much more simplified "D".

I haven't found any vector version, did you?

**Comment by mondeja** [comment]
I haven't found any vectorized version of this "D" and in their repository (source) is the same version that we have, did you found one @PeterShaggyNoble?

**Comment by PeterShaggyNoble** [comment]
The logo in that [PDF ](https://git.disroot.org/Disroot/Website/src/branch/master/pages/annual_reports/AnnualReport2019.pdf) I sent you last night unfortunately is a raster file. Given the size of it, though, it may still be usable. Other than that, I couldn't find anything either but [this repo](https://git.disroot.org/Disroot/Artwork_assets) is probably our best bet for monitoring for updated artwork.

**Comment by fbernhart** [comment]
LGTM 👍🏼  Let's stick with this version for now. If we ever find a vectorized version of the new logo, we can still update it.

**Pull request merged**
