### PR TITLE
Add iTunes icon (previously abandoned)

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
get #1096 (abandoned) going again

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Was going to add this last week but then thought it might be covered by Apple Music. Perhaps not!

**Comment by runxel** [comment]
> Was going to add this last week but then thought it might be covered by Apple Music. Perhaps not!

You're right, they are pretty similar, yet not the same. (I did miss that Apple Music was already on board)
I let the maintainers decide :)

**Comment by birjolaxew** [comment]
I couldn't find any official guidelines on the actual iTunes logo. The [Apple Music guidelines](https://www.apple.com/itunes/marketing-on-music/identity-guidelines.html#apple-music-icon) (which uses a similar logo) specifically forbids using the circle version, but that seems to be for Apple Music app; the [iTunes Store guidelines](https://www.apple.com/itunes/marketing-on-itunes/identity-guidelines.html#itunes-store-icon) uses the app icon, which is significantly different from the logo of iTunes itself.

Thoughts @simple-icons/maintainers?

**Comment by phatbhoy67** [comment]
The icon used on [iTunes](https://www.apple.com/itunes/) homepage is the one below, so I think the PR version is the correct one to use here. As previously mentioned, similar but not the same as Apple Music so I think adding it is a good idea. 

iTunes Logo

**Comment by birjolaxew** [comment]
:+1: In that case this looks good. Thanks for reopening and taking care of this @runxel!

**Pull request merged**
