### PR TITLE
Add Intuit

### PR DESCRIPTION
**Pull request by diegobot1977**
intuit

**Issue:** #5894 
**Alexa rank:** 97

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description
Used on the Intuit's homepage, so the HEX color of the logo is `#0076c9`.

### CODE REVIEW

**Comment by fbernhart** [comment]
@diegobot1977  I've reopened this one for you.

Please DON'T close it.

You can now push the .svg file and the other needed changes to this branch.

After that one of us will review it.

**Comment by diegobot1977** [comment]
Ok but I don't know how can I upload this .svg file?

**Comment by fbernhart** [comment]
@diegobot1977 I'm sure you can find many articles and YouTube tutorials on the internet about this. You can either use pure git, GitHub, or your favourite code editor, like for example VS Code.

**Comment by diegobot1977** [comment]
Ok!

**Comment by diegobot1977** [comment]
@fbernhart! I just wrote the Intuit icon `T` for this third letter on SVG-edit.

**Comment by diegobot1977** [comment]
Ok @fbernhart! So I just did the SVG-edit for Simple Icons.

**Comment by diegobot1977** [comment]
Let's close this out because it did not add an Intuit icon.

**Pull request closed without merging**
