### PR TITLE
Added Palo Alto Networks Icon

### PR DESCRIPTION
**Pull request by uiuxarghya**
paloaltonetworks

**Issue:** #5807
**Alexa rank:** 12,332
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Brand Resources : https://www.paloaltonetworks.com/company/brand
Hex Value : `#F04E23`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @uiuxarghya :+1:

However, when compared with [the black AI file](https://www.paloaltonetworks.com/content/dam/pan/en_US/images/logos/brand/primary-company-logo-black/panw-parent-brand-primary-logo-cmwk.ai), your version (in red) shows a number of differences. Would you mind having another look to see if you can fix that up?

Also, from page 46 of [the brand guidelines](https://www.paloaltonetworks.com/content/dam/pan/en_US/partners/PAN-brand-guidelinesv22-lores.pdf) it looks like the colour should be `#FA582D`.

**Comment by uiuxarghya** [comment]
Okay, @PeterShaggyNoble thanks for finding the hex code. 😀
I am updating the SVG and the hex code.

**Comment by uiuxarghya** [comment]
paloaltonetworks (1)

@PeterShaggyNoble
I have updated the SVG and the hex code. 
I have tried hard and managed to make it as proper as possible.

Is it correct now? What do you think?

**Comment by adamrusted** [comment]
Hey @uiuxarghya - it looks as though this file only has 2 decimals of precision, and therefore still has [some pretty major differences](https://user-images.githubusercontent.com/1830867/121770079-294a5100-cb5f-11eb-911a-64cdc76c79a9.png) when compared to the source file in grey. We always use a minimum of 3 decimals, and go up to a maximum of 5 if the icon needs it. Could you rebuild from source and export with 3 decimals of precision, and we can review it then?

**Comment by uiuxarghya** [comment]
> Hey @uiuxarghya - it looks as though this file only has 2 decimals of precision, and therefore still has [some pretty major differences](https://user-images.githubusercontent.com/1830867/121770079-294a5100-cb5f-11eb-911a-64cdc76c79a9.png) when compared to the source file in grey. We always use a minimum of 3 decimals, and go up to a maximum of 5 if the icon needs it. Could you rebuild from source and export with 3 decimals of precision, and we can review it then?

As it is not passing the linter.


```bash
x icons/paloaltonetworks.svg
  x icon-centered <path> must be centered at (12, 12); the center is currently (12, 11.95)

---------------------------------------------------------------- Summary ----------------------------------------------------------------
✓ 1931 valid files.
x 1 invalid files.
```

I have checked around 19 to 20 different decimal values after the actual value given below  👇 didn't pass the linter. 

<div align="center">

Screenshot 2021-06-12 162642

👆 The actual value after narrowing its width to 24px.

</div>

So I decided to make a very slight change so that it passes the linter. I think that's a very minor change it wouldn't affect the logo, you can merge it in.

**Comment by PeterShaggyNoble** [comment]
Thanks, @uiuxarghya. However, I'm still seeing [some differences](https://user-images.githubusercontent.com/15157491/122545289-96f5f180-d025-11eb-81bc-44d677368f23.png). I suspect, though, that that may simply be due to the precision being set too low when optimising. Could you try optimising your original SVG again with a precision of 2 or 3 and comparing against the source to check if they line up?

**Pull request closed without merging**
