### PR TITLE
added Google Scholar logo

### PR DESCRIPTION
**Pull request by awwsmm**
**Issue:** #1338

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

This is a Google subdomain so the hex value I picked is ["Google blue"](https://www.designpieces.com/palette/google-new-logo-2015-color-palette-hex-and-rgb/).

Logo was vectorised from a very small `png` and could probably be optimised further.

### CODE REVIEW

**Comment by awwsmm** [comment]
This PR is failing on the linter, which says there's a newline at the end of the SVG (there isn't) and on buggy code which I didn't write:

```
SyntaxError: Unterminated string constant
    at JS_Parse_Error.get (eval at <anonymous> (/home/travis/build/simple-icons/simple-icons/node_modules/uglify-js/tools/node.js:20:1), <anonymous>:71:23)
    at formatError (util.js:609:16)
    at formatValue (util.js:513:18)
    at inspect (util.js:293:10)
    at format (util.js:160:12)
    at Console.warn (console.js:145:21)
    at data.icons.forEach.icon (/home/travis/build/simple-icons/simple-icons/scripts/build-package.js:57:15)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/travis/build/simple-icons/simple-icons/scripts/build-package.js:48:12)
    at Module._compile (module.js:653:30)
  message: 'Unterminated string constant',
  filename: '0',
  line: 4,
  col: 7,
  pos: 76 }
```

**Comment by ericcornelissen** [comment]
First off: thanks a lot for the effort you're willing to put into this project. It really means a lot! Thanks a bunch 🎉 

* * *

> This PR is failing on the linter, which says there's a newline at the end of the SVG (there isn't) [...]

There is but GitHub is hiding it from us. If there really wasn't a final newline you would see an extra symbol in the code on GitHub. Removing it through the GitHub IDE will automatically add it (as will many editors). However, as I pointed out in #1324 we are fine with removing this requirement from the linter (though that is going to depend on what I'm explaining below).

> [...] and on buggy code which I didn't write

It's also not code that we wrote per se, it is actually [uglify-js](https://www.npmjs.com/package/uglify-js) doing something weird. Interestingly, it is caused by the newline! I tested it locally and removing the newline resolves the problem. The `\r\n` (that is your newline) at the end of the SVG file seems to be confusing uglify-js (and therefor possibly also JS interpreters!) when we pass the SVG file's content to it.

I guess we can resolve this by checking for newlines on our side and removing them before running uglify-js 🤔 If you want this PR to be merged quickly I recommend you to remove the newline yourself (remove it with `notepad.exe` - or something similar on other OSs - and check the diff. Again don't try to do this in the GitHub IDE, and if you use an editor locally consider enabling displaying whitespace), if not then we will look into updating the build in the near future and your PR will be merge-able after that 🙂

**Comment by awwsmm** [comment]
Thanks for your quick response @ericcornelissen. I manually removed the newline and committed. Let's hope it works this time.

**Comment by awwsmm** [comment]
Fixed the scaling! Sorry about that.

Screenshot 2019-09-29 16 38 58

**Comment by ericcornelissen** [comment]
Thanks a lot for you contribution @awwsmm, it is very much appreciated! :tada:

Also, thanks for [your feedback on the contribution process](https://github.com/simple-icons/simple-icons/pull/1677#issuecomment-536188278) (also [this one](https://github.com/simple-icons/simple-icons/issues/1324#issuecomment-536188025)), we will do our best to improve the experience for future contributors :smile: 

> Fixed the scaling! Sorry about that.

Not a problem at all, thanks for the quick fix :wink:

**Pull request merged**
