### PR TITLE
Update Aerospike

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
aerospike

**Issue:** contributes toward #9072 

**Similarweb rank:** 751,760. See https://www.similarweb.com/website/aerospike.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from [this specific PDF](https://pages.aerospike.com/rs/aerospike/images/Acid_Whitepaper.pdf) as the logo is not available as a square elsewhere
Color: Updated to `#C22127` taken from the same logo inside PDF

### CODE REVIEW

**Comment by adamrusted** [comment]
Looks like on their socials they just use the `A` without the square. Would it be worth us following suit? If so, we may still need to use this source, as the logo isn't available as an SVG on the website...

**Comment by PratyushJayachandran** [comment]
> Looks like on their socials they just use the `A` without the square. Would it be worth us following suit? If so, we may still need to use this source, as the logo isn't available as an SVG on the website...

Their favicon is still the same is the red square. But yeah socials are different. Should we favor favicon more?

**Comment by adamrusted** [comment]
> Their favicon is still the same is the red square. But yeah socials are different. Should we favor favicon more?

@simple-icons/icon-review

**Comment by adamrusted** [comment]
Given we've not heard anything, let's just stick with the square version for now. Will review shortly.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @PratyushJayachandran 🎉

**Pull request merged**
