### PR TITLE
Request: Suckless Icon

### LINKED ISSUE #4883: Add Icon for Suckless (and possibly dwm)
**Brand Name:** Suckless
**Website:** https://suckless.org
**Alexa rank:** 412,962

## Official resources for icon and color:
* Icon: https://suckless.org/logo.svg and/or https://dwm.suckless.org/dwm.svg
* Colors:
  * [](https://suckless.org/pub/style.css)
  * [](https://git.suckless.org/dwm/file/config.def.h.html#l10)
  * [](https://git.suckless.org/dwm/file/config.def.h.html#l11)
  * [#bbbbbb](https://git.suckless.org/dwm/file/config.def.h.html#l12)
  * [#eeeeee](https://git.suckless.org/dwm/file/config.def.h.html#l13)
  * [](https://git.suckless.org/dwm/file/config.def.h.html#l14)

### PR DESCRIPTION
**Pull request by yuri-norwood**
## Details
suckless

**Issue:** Closes #4883 - Add Icon for Suckless (and possibly dwm)
**Alexa rank:** [412,962](https://www.alexa.com/siteinfo/suckless.org)

**Why did you pick the hex value?**
The suckless tools all have a very consistent aesthetic, based on the 6 colours listed in my issue, however, the website and it's logo used `#069` (nice) and since most people customize the colours of the tools, this seems to be the best fitting. Both in terms of recognizability, and brand consistency.

**Did you manually vectorize the logo?**
Yes, I manually wrote the `path="..."` to get it to fit 24x24.

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @yuri-norwood. However, it looks like your version (in red below) is vertically stretched when compared to the original.

Also, from the source SVG and their website, I'd expect the colour to be `#1177aa`. Finally, linking to the homepage rather than the logo for the source is fine.

**Comment by yuri-norwood** [comment]
Edit: Updated preview in PR details, [original](https://user-images.githubusercontent.com/76186754/106087820-a913e800-6189-11eb-97fc-87a0ec1f43f5.png).

**Comment by yuri-norwood** [comment]
* [x] Stylise title in SVG & JSON
* [x] Change colour to be #1177AA
* [x] Change `source` link to the homepage

**Review by PeterShaggyNoble — APPROVED** [review]
Thanks, @yuri-norwood, everything looks perfect now 👍🏻 And congrats on finding an icon that could be optimised down to 0 decimal points of precision; they're incredibly rare!

**Comment by yuri-norwood** [comment]
Thank you very much, I'm glad I could help improve Simple Icons.

**Pull request merged**
