### PR TITLE
Add STACKIT icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** https://github.com/simple-icons/simple-icons/issues/5830
**Alexa rank:** 6,071,066 
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I am working for STACKIT, a German Cloud provider from the Schwarz Group (Lidl, Kaufland).

All the assets are from our internal design department and follow the guideline (shape, color) for the brand STACKIT

### CODE REVIEW

**Comment by dirien** [comment]
Hi @adamrusted, could you review this.

This icon is from my place i work. So more feelings than the Cloud Foundry Icon 😅

**Review by adamrusted — APPROVED** [review]
Thanks for this one @dirien, the icon matches up perfectly to the SVG available in the header of the website, and given you've had approval from your designer - I'm happy for this to be merged. It'll be in the release on Sunday - thanks again for contributing @dirien 💪

**Comment by fbernhart** [comment]
@adamrusted 

Maybe you've missed it, but wouldn't an Alexa rank of over 6 million be **clearly** out of scope?

**Comment by adamrusted** [comment]
> @adamrusted 
> 
> Maybe you've missed it, but wouldn't an Alexa rank of over 6 million be **clearly** out of scope?

You are not wrong. We may need to remove this one before the release gets generated for this week then, my bad!

**Comment by dirien** [comment]
I commented on thos on the PR for removing the PR.  #5847 

I would aks for a dialog on this special case :)

**Pull request merged**
