### PR TITLE
add jenkins x icon

### PR DESCRIPTION
**Pull request by MarckK**
### Checklist
  -  I updated the JSON data in `_data/simple-icons.json`
  -  I optimized the icon with SVGO or SVGOMG
  - The SVG `viewbox` is `0 0 24 24`

### Description

The hex value is from the Jenkins X [brand guidelines](https://github.com/cdfoundation/artwork/blob/master/jenkinsx/jenkins_brand_guide.pdf).

### CODE REVIEW

**Comment by MarckK** [comment]
Thanks @ericcornelissen. Hopefully, this next attempt will be better ;)

**Comment by ericcornelissen** [comment]
@MarckK as you can see below the logo is now fully visible. However, we [want the icon to fit perfectly inside the viewbox and have it centered as well](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#2-extract-the-icon-from-the-logo), can you make that change?

If you need help with that, tell us what software you're using to edit the SVG and we should be able to help 😉 

SVG preview

**Comment by MarckK** [comment]
Thank you for your help, @ericcornelissen. This corrected svg will hopefully be correct. :)

**Comment by ericcornelissen** [comment]
> Thank you for your help. This corrected svg will hopefully be correct. :)

Looking good :+1: The last thing we require is that the logo is centered in viewbox. It is already centered horizontally, can you center it vertically as well @MarckK?

**Comment by birjolaxew** [comment]
@MarckK I will be closing this PR off as abandoned for now. Please don't take this personally - it is simply done to keep our PR list a bit cleaner, especially now with Hacktober going on. If you have plans to come back and update the PR with the [final requested change](https://github.com/simple-icons/simple-icons/pull/1684#issuecomment-539186713), please comment and I'll reopen and get this merged in :)

**Pull request closed without merging**
