### PR TITLE
#1627 Add Keras

### PR DESCRIPTION
**Pull request by louistsaitszho**
**Issue:** #1627 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by birjolaxew** [comment]
@louistsaitszho Can you please elaborate a bit on where you got the SVG from? I can't seem to find an actual vector on https://keras.io/

**Comment by louistsaitszho** [comment]
@birjolaxew In the issue itself (#1627), it included a link to the svg directly.

**Comment by birjolaxew** [comment]
@louistsaitszho In that case the `source` should definitely be  [the `ml-logos` repository](https://github.com/valohai/ml-logos/blob/master/keras-text.svg). That being said, it looks like this vectorization is not particularly accurate when compared to [the official raster logo](https://s3.amazonaws.com/keras.io/img/keras-logo-2018-large-1200.png):

<p align="center"></p>

I have been unable to find a proper vectorization of their logo anywhere, so I think we would want a manual vectorization based on the official raster logo instead. If you want to take on that challenge feel free @louistsaitszho - otherwise we might want to close this PR to signal to others that it's up for grabs. I'll let you make the decision.

**Comment by louistsaitszho** [comment]
@birjolaxew hmmm I should have checked that. Let me try it out this week, and I will provide either an update to this PR, or close this PR, by the end of this week.

**Comment by louistsaitszho** [comment]
ezgif com-video-to-gif

Ok re-created that. Does it look ok now?

**Comment by birjolaxew** [comment]
:+1: That looks great @louistsaitszho, thanks a lot for your work on this PR!

**Pull request merged**
