### PR TITLE
Added Norwegian

### PR DESCRIPTION
**Pull request by adamrusted**
norwegian

**Issue:** Contributes to #2587
**Alexa rank:** [66,237](https://www.alexa.com/siteinfo/norwegian.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG available in header - took red from the stylesheet also.
There were a _lot_ of rogue points in this one - I've smoothed it out as best I can, but there's likely to be a fair difference between this and the source.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Yeah, I remember that SVG, and most everything else I came across being pretty terrible. The versions in [these PDFS](https://www.norwegian.com/ie/travel-info/on-board/in-flight-entertainment/magazine/) seemed to be the best of a bad lot - fewer imperfections and points - so do you want to try using one of those as the source instead, before we review?

**Comment by adamrusted** [comment]
@PeterShaggyNoble give that a go - used pg1 of http://nmagazine.ink-live.com/html5/reader/production/default.aspx?pubname=&edid=1454da02-759b-45f3-a10e-23b6d8ba269e if it makes any difference.

**Comment by PeterShaggyNoble** [comment]
That looks good to me, @adamrusted - only thing I see that needs fixing is [this small difference](https://user-images.githubusercontent.com/15157491/109962268-e4528b00-7ce2-11eb-906c-d6ef895d14ee.png) where the back of the plane meets the "jetstream" (your version in red).

**Comment by adamrusted** [comment]
Try that out @PeterShaggyNoble - just a quick tweak to the SVG.

**Review by PeterShaggyNoble — APPROVED** [review]
Looks good to me now, @adamrusted :+1: Nice one

**Pull request merged**
