### PR TITLE
Add LEGO to list of forbidden brands

### PR DESCRIPTION
**Pull request by HonkingGoose**
**Issue:** I'm not closing any issue with this PR.

**Popularity metric:**

### Checklist

- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

### Description

This project rejected requests for the LEGO logo:

- #5823
- #3674

So it's probably a good idea to add LEGO to the list of forbidden brands, to prevent another duplicate issue down the line.

### CODE REVIEW

**Comment by uncenter** [comment]
Hmm I think we only add them to the forbidden brands list when a company has many many *different* products that are requested. For individual products like LEGO I think just referring to the closed issues is fine.

**Comment by adamrusted** [comment]
The 'forbidden brands' list is for those we've explicitly received cease and desist notifications, or widely known litigious brands.
While we've rejected Lego in the past, should their terms change - or a contributor is particularly interested in asking the question of Lego, we can always revisit it.

**Comment by HonkingGoose** [comment]
> The 'forbidden brands' list is for those we've explicitly received cease and desist notifications, or widely known litigious brands.

The Renovate project _used_ to have the LEGO logo as part of a gallery of big-name companies/projects that use Renovate. The LEGO group asked the Renovate project to stop using the logo:

- https://github.com/renovatebot/renovate/discussions/13164

> While we've rejected Lego in the past, should their terms change - or a contributor is particularly interested in asking the question of Lego, we can always revisit it.

I'll just drop the [LEGO's fair-play guidelines](https://www.lego.com/en-gb/legal/notices-and-policies/fair-play/) here, and let you make your own decision. :smile:

**Comment by adamrusted** [comment]
Closing this for now, as I don't feel Lego's stance is worthy of being on our 'forbidden' list. While we have no intention of adding it at this time, if a contributor feels particularly strongly about adding the logo - they are welcome to reach out to Lego to negotiate.

**Pull request closed without merging**
