### PR TITLE
Add Fluent Bit

### PR DESCRIPTION
**Pull request by mhf-ir**
**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Same as Fluentd but lightweight even more usage then FluentD ruby version:
https://github.com/fluent/fluent-bit#fluent-bit-in-production

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Where did you source this one, @mhf-ir? Or did you manually vectorise it? I can only see a PNG on their website homepage and the SVGs in their website repo look to be outdated (e.g., https://github.com/fluent/fluent-bit-website/blob/master/designs/fluentbit_logo.svg).

**Comment by mhf-ir** [comment]
That logo is outdate. i get it from company behinde fluentbit:
https://www.treasuredata.com/opensource/

**Comment by PeterShaggyNoble** [comment]
Thanks, @mhf-ir.

The current Alexa rank for this brand is [~610k](https://www.alexa.com/siteinfo/fluentbit.io) which would put it outside the scope of SI and the activity in & popularity of [their GH repo](https://github.com/fluent/fluent-bit/) don't, to me, make up for that.

That being said, our requirements and thresholds for measuring popularity outside of Alexa ranks are still up in the air (ref: #1207) so I'd like to hear from the other @simple-icons/maintainers on whether they think this one should be added. It should also be noted that the parent company's Alexa rank is a healthy [29k](https://www.alexa.com/siteinfo/treasuredata.com).

If it's to be added, I'd suggest updating the source URL to the page you linked above.

**Comment by runxel** [comment]
Hm, if their claim
> Fluent Bit is used widely, just on 2019 it was deployed more than 62 Million times. The following is a preview of who uses Fluent Bit heavily in production

holds true, this could be a good indicator to include it!

**Comment by PeterShaggyNoble** [comment]
That certainly sounds popular enough, @runxel! 😆

The original SVG from that page has a few of problems that we should probably fix, chief among them the rip of the wing:

image

**Comment by PeterShaggyNoble** [comment]
Closing as abandoned due to [this comment](https://github.com/simple-icons/simple-icons/pull/2402#issuecomment-579852495). If anyone else would like to take this on, please feel free to open a new PR or issue.

**Pull request closed without merging**
