### PR TITLE
Add Prime Video

### LINKED ISSUE #2989: Prime Video
**Name:** Prime Video
**Website:** https://primevideo.com
**Official resources for icon and color:**
  
* Brand guidelines: https://m.media-amazon.com/images/G/01/cooper/PV_Branding_Guidelines_Logos_Lock_Ups._CB1539191655_.pdf
* Colors: `#00AAE1`, `#1F2E3E`
* Resources: https://m.media-amazon.com/images/G/01/digital/video/PrimeVideoLogos/Prime_Video_Logos_10918._CB483297842_.zip

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Prime Video

**Issue:** Closes #2989

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon & colour from `Prime_Video_Logos_10918\01_Mark\Black\Prime-Video-Black.svg` found in the [zip file](https://m.media-amazon.com/images/G/01/digital/video/PrimeVideoLogos/Prime_Video_Logos_10918._CB483297842_.zip) linked from the last page of the source PDF.
Possible alternative name, for consistency: Amazon Prime Video

I went with the darker blue rather than the lighter as that's what _appears_ to be suggested by the 3rd page of the source PDF and is backed up by the colouring of [their website](https://www.primevideo.com/). However, the colours used in the SVGs in the zip linked above do differ from those in the [Amazon Prime brand guidelines](https://images-na.ssl-images-amazon.com/images/G/01//gift-certificates/corporate/3PStyleGuideQ12019rev7040819002._CB1559605351_.pdf).

If anyone can find a better source URL (e.g., a page on an Amazon site that links to the source PDF) or a source that would allow us to use the stacked logo as seen [here](https://play.google.com/store/apps/details?id=com.amazon.avod.thirdpartyclient), please let me know.

### CODE REVIEW

**Comment by NovaGL** [comment]
I would say the stacked version is better. 
I would also say the lighter blue is more globally used on the logo itself.

https://logos.fandom.com/wiki/Amazon_Prime_Video

**Comment by PeterShaggyNoble** [comment]
Yep, I'd definitely prefer the stacked version too, @NovaGL but, per the discussion in #2989, their brand guidelines don't seem to allow it.

**Comment by NovaGL** [comment]
Sorry for the cross post, but as per their guidelines this should be fine.

**Comment by PeterShaggyNoble** [comment]
Nice find, @NovaGL :+1: Bear in mind, though, that internal brand guidelines can sometimes differ to those for third parties. We would need to find a copy of these guidelines either directly provided by Amazon or out in the wild somewhere in order to use the stacked version.

On the colour, note that "Prime" is the parent brand and "Prime Blue" is the primary colour for that but, from the "Prime Video" website, it would appear that "Squid Ink" is actually the primary colour for that sub-brand. But I'm happy to update if we get a consensus to change it.

**Comment by ericcornelissen** [comment]
Given that some of the pages in the source referenced by @NovaGL are included [in the brand guidelines .PDF found through google](https://m.media-amazon.com/images/G/01/cooper/PV_Branding_Guidelines_Logos_Lock_Ups._CB1539191655_.pdf), but not the one with the stacked version, I would agree that we should keep the version currently found in this PR.

As an outsider I would agree that it seem that "Squid Ink" is the **brand** color, even though from the logo it may seem that "(Prime) Blue" is a better option. Are you a user of Prime Video, @NovaGL? If so (and otherwise as well), could you share some UI/branding that makes you think that "(Prime) Blue" is the way to go?

**Comment by NovaGL** [comment]
@ericcornelissen I'd add some photos to this post but I agree after a look at their UI it seems that squid ink is the primary color but prime blue is the secondary color. Therefor if we can only choose one color then squid ink is the one I would go for.

On a side note, I wanted to provide the logo for Amazon Music as well but the branding and coloring for that is so inconsistent it would be impossible to work out what the correct brand is without access to branding guidelines.

**Comment by ericcornelissen** [comment]
> On a side note, I wanted to provide the logo for Amazon Music as well but the branding and coloring for that is so inconsistent it would be impossible to work out what the correct brand is without access to branding guidelines.

Alright, glad that is resolved :+1: 


> On a side note, I wanted to provide the logo for Amazon Music as well but the branding and coloring for that is so inconsistent it would be impossible to work out what the correct brand is without access to branding guidelines.

Open an issue for it, perhaps others can help you figure it out :wink: (just for your information, Amazon isn't very good with regards to consistent branding in general :upside_down_face:)

**Comment by NovaGL** [comment]
@ericcornelissen You've quoted the same thing twice. I'm assuming you mean the coloring for the first quote?

So you want an issue or pull request for amazon music?

**Comment by ericcornelissen** [comment]
> You've quoted the same thing twice. I'm assuming you mean the coloring for the first quote?

Ah yes, apologies (I edited my comment to fix it)


> So you want an issue or pull request for amazon music?

If you already have a PR ready feel free to open it and the discussion can happen in the PR thread. If not, I would open an issue first and we will assign you to it so others know that someone is already working on it :slightly_smiling_face:

**Comment by NovaGL** [comment]
> If you already have a PR ready feel free to open it and the discussion can happen in the PR thread. If not, I would open an issue first and we will assign you to it so others know that someone is already working on it 🙂

Rather than create an in-progress PR I created issue #3163 

I would think this (Prime Video) PR can be merged unless there are any objections

**Pull request merged**
