### PR TITLE
adding SolidJS icon

### PR DESCRIPTION
**Pull request by jorgeamadosoria**
solidjs

**Issue:** #6594 

EDIT:  Added the gaps
solidjs

### CODE REVIEW

**Comment by sachinraja** [comment]
Not sure about this. It may need extra detail to preserve the shape.

**Review by sachinraja — DISMISSED** [review]
Not sure about this. It may need extra detail to preserve the shape.

**Comment by service-paradis** [comment]
> Not sure about this. It may need extra detail to preserve the shape.

I agree! Maybe we can try adding 0.5 gaps to keep the shape

**Comment by jorgeamadosoria** [comment]
> > Not sure about this. It may need extra detail to preserve the shape.
> 
> I agree! Maybe we can try adding 0.5 gaps to keep the shape

I agree with both of you. I just don't know if we should add the gaps around each of the paths or only in the middle between the top and bottom wedges.

**Comment by jorgeamadosoria** [comment]
I've added gaps as requested (look at the beginning of the PR).

**Review by sachinraja — COMMENTED** [review]
This looks good me, but I haven't reviewed anything with gaps before, so I'll leave that to someone else.

**Review by sachinraja — APPROVED** [review]

**Pull request merged**
