### PR TITLE
Add Bluesky icon

### LINKED ISSUE #8935: Request: Bluesky
### Brand Name

Bluesky

### Website

https://bsky.app

### Popularity Metric

The Similarweb rank is 18,253. See https://www.similarweb.com/website/bsky.app

### Official Resources for Icon and Color

The SVG can be found on the [AT Protocol website](https://atproto.com) header and footer.

The color, `rgb(5, 96, 255)` or `#0560ff`, can be found on the title of the [Bluesky landing page](https://blueskyweb.xyz).

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by patrik-csak**
Bluesky Simple Icons preview

**Issue:** closes #8935

**Similarweb rank:** [2,173](https://www.similarweb.com/website/bsky.app/)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Color was picked from the text and button color on [bsky.app](https://bsky.app)
- Logo is from @bluesky-social’s @pfrazee: https://github.com/FortAwesome/Font-Awesome/issues/19810#issuecomment-1854999604

### CODE REVIEW

**Comment by LitoMore** [comment]
Hi @dholms, could you help to review this icon? Does the icon meet your expectations?

**Comment by dholms** [comment]
@pfrazee is the better person for this

**Comment by pfrazee** [comment]
Hmm! Technically this isn't our icon because we don't have one yet, and what's there is just a placeholder. Let me chat with the team a bit

**Comment by iDiegoNL** [comment]
@pfrazee do you have any updates on the above?

**Comment by PeterShaggyNoble** [comment]
As the icon in this PR is not reflective of Bluesky's branding, which has yet to be finalised, I'm going to close this one out until such a time as it _is_ finalised, at which stage a new PR can be submitted. Thanks for your work here nonetheless, @patrik-csak 👍🏻

**Comment by pfrazee** [comment]
Hey sorry for being difficult! Ironically, there's about to be some movement here. Keep an eye out.

**Comment by PeterShaggyNoble** [comment]
Re-opening this to allow @patrik-csak to continue working on it.

**Pull request merged**
