### PR TITLE
Update Google Scholar

### LINKED ISSUE #3081: Update: Google Scholar Icon
**Name:** Google Scholar
**Official resources for icon and color:**
  
google scholar
https://scholar.google.com/favicon.ico
https://scholar.google.com/apple-touch-icon.png
https://commons.wikimedia.org/wiki/File:Google_Scholar_logo.svg

The shapes probably need some negative spacing (eg like Roundcube in #1619) so thought I'd open this for discussion before embarking on anything ambitious.

### PR DESCRIPTION
**Pull request by davidjb**
**Issue:** Closes #3081

scholar-1 5pt

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Based upon the file at https://commons.wikimedia.org/wiki/File:Google_Scholar_logo.svg with insetting applied to the mortarboard triangles and head circle segments to distinguish the parts. The hex colour has been adjusted to match the left-hand side of the coloured mortarboard, which also happens to be the colour of the Gs in the Google logo (which matches other Google brands as well).

### CODE REVIEW

**Comment by runxel** [comment]
Hey @davidjb, thanks for taking care of this one.
However it looks like the stroke width differs from each other. They all should have a width of `1 pt`. (At least this is, what we once settled on informally, when doing work like this)
Also the crossbar should sit higher; if you compare it to the original.

**Comment by PeterShaggyNoble** [comment]
I was thinking of just a single cutout on the mortarboard, along the lines of the below; what are other people's thoughts?

**Comment by davidjb** [comment]
@PeterShaggyNoble Looks good and far clearer as to what it is at larger sizes than mine 👍

**Comment by ericcornelissen** [comment]
That is also what I was expecting @PeterShaggyNoble

**Comment by davidjb** [comment]
Did you want me to update/finish my PR with your icon, @PeterShaggyNoble? Or let you update it in the repo separately?

**Comment by ericcornelissen** [comment]
> Did you want me to update/finish my PR with your icon, @PeterShaggyNoble? Or let you update it in the repo separately?

I'm guessing the intention was for you to update the PR based on the SVG provided by Peter, could you do that?

**Comment by davidjb** [comment]
Sure, more than happy to do it. The preview is just a PNG though - is there an svg available?

**Comment by PeterShaggyNoble** [comment]
Yeah, that was just a rough mock-up I did, @davidjb.

**Comment by davidjb** [comment]
scholar-1 5pt

Updated the PR.  I had tried a 1pt gouge out of the mortarboard but at the smallest size (eg 24px) the distinction was too slight.  This is 1.5pt and thus more obvious when small.

Screen Shot 2020-05-29 at 14 35 47
Screen Shot 2020-05-29 at 14 35 39

**Comment by PeterShaggyNoble** [comment]
Perfect! 😁 Nice work, @davidjb 

Before we merge this in, can you update the source URL to the logos _page_ on Wikimedia: https://commons.wikimedia.org/wiki/File:Google_Scholar_logo.svg?

Nice catch on the colour, by the way. Everyone else OK with changing it to Google blue?

**Comment by davidjb** [comment]
All done @PeterShaggyNoble, thanks for the feedback.

For the URL, I'd followed the example of others' source URLs - there are several more that need adjustment that use the direct link to `upload.wikimedia.org` in case those need changing too.

**Comment by ericcornelissen** [comment]
> For the URL, I'd followed the example of others' source URLs - there are several others that use the direct link to upload.wikimedia.org.

No problem, at some point we set [guidelines on wikimedia URLs](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#source-guidelines) but we didn't update the existing URLs that didn't meet those guidelines. Perhaps we should...

Anyway, thanks a bunch for updating the Google Scholar icon! :confetti_ball:

**Pull request merged**
