### PR TITLE
Added Apache JMeter

### LINKED ISSUE #3641: Request Apache JMeter
[Apache JMeter](https://apache.org/logos/#jmeter)

_Originally posted by @QAInsights in https://github.com/simple-icons/simple-icons/issues/2887#issuecomment-702306324_

### PR DESCRIPTION
**Pull request by adamrusted**
**Issue:** Closes #3641
**Alexa rank:** N/A (Apache Project)
### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Extracted from https://github.com/simple-icons/simple-icons/pull/3680. Thanks to @reginareynolds for working on this one 🎉

### CODE REVIEW

**Comment by fbernhart** [comment]
Hmm .. I don't think that just the "feather" is a good choice here, as this is the logo of Apache itself, which we already have. --> https://simpleicons.org/icons/apache.svg

@adamrusted Could you update it to the full wordmark? https://svn.apache.org/repos/asf/comdev/project-logos/originals/jmeter.svg

**Comment by adamrusted** [comment]
@fbernhart sorted!

**Comment by fbernhart** [comment]
@adamrusted Your version overlayed in green:

image


- Seems like you've removed the strokes of "JMeter", making the icon thinner. Could you convert them to paths instead and keep them?

-  As well your version has a filled feather in the middle, while the source hasn't.

- I guess that we could remove the two TM signs, as I haven't found any guidelines that tell us to keep them. Note: there is as well a tiny TM sign on top of the feather.

**Comment by adamrusted** [comment]
@fbernhart Let's try that again shall we? Why on earth do they bother with a stroke that's exactly the same colour as the fill? 🤦🏻‍♂️

**Comment by fbernhart** [comment]
@adamrusted Already looks pretty good to me. 👍🏼 How about removing the second TM as well? Any opinion?

**Comment by adamrusted** [comment]
Happy to, give me a few 😅

**Comment by adamrusted** [comment]
@fbernhart sorted!

**Comment by fbernhart** [comment]
@adamrusted Perfect!

**Pull request merged**
