### PR TITLE
Add Hetzner icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** #6145
**Alexa rank:** 3,984
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Main Logo is to large and its just the Name so i use teh favicon as base:

https://www.hetzner.com/themes/hetzner/images/favicons/favicon-32x32.png

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Thank you for the contribution @dirien, before we review this though: what is your motivation for going with just the "H"? Being completely unfamiliar with the brand and based solely on the favicon I would say the square to be part of the (small) logo.

**Comment by dirien** [comment]
hi @ericcornelissen, they don't have "classic" logo... And using the full name  feels not like a icon. (see the minecraft simple icon). So i optend for the favicon H.

**Comment by ericcornelissen** [comment]
I agree with that @dirien, I'm just wondering if we should go with "H in a square" rather than just an "H"?

**Comment by dirien** [comment]
As i am not good in Graphic tools, (i use inkspace 😄 ) i let the decision on for you to make  but i cant do it. My skills are really limit on getting a existing svg to fit the simpleicon requirements.

**Comment by ericcornelissen** [comment]
> As i am not good in Graphic tools, (i use inkspace 😄 ) i let the decision on for you to make but i cant do it. My skills are really limit on getting a existing svg to fit the simpleicon requirements.

That is fine, Inkscape is actually perfectly fine for the purposes of this project but if you don't have the skills to make it happen that's okay 😄 

If you don't disagree that it should be in "the H in a square" variant, I'll close this for now. If anyone thinks we should go ahead with this Pull Request as is, please leave a comment.

**Comment by jorgeamadosoria** [comment]
MR with full name: https://github.com/simple-icons/simple-icons/pull/6213

**Comment by dirien** [comment]
@jorgeamadosoria, sounds cool!

**Comment by dirien** [comment]
@ericcornelissen, i can add the square. How thick should be the line of the square? And should there be a margin with the corners?

**Comment by ericcornelissen** [comment]
As close as possible to the favicon, as that's not a vector file you will need to do some manual work to figure out how big the margin should be.

**Comment by dirien** [comment]
New  Icon with the square, followd the favicon -> https://www.hetzner.com/themes/hetzner/images/favicons/favicon-32x32.png
image

@jorgeamadosoria: FYI

**Comment by jorgeamadosoria** [comment]
> https://www.hetzner.com/themes/hetzner/images/favicons/favicon-32x32.png

I think it's good enough to merge, taking into consideration that there was no SVG source

**Review by ericcornelissen — APPROVED** [review]
> I think it's good enough to merge, taking into consideration that there was no SVG source

Agreed, this looks very good for a "manual" vectorization. For completeness, here is a (mediocre) comparison:

image

**Pull request merged**
