### PR TITLE
Update Topcoder

### PR DESCRIPTION
**Pull request by fbernhart**
topcoder

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by service-paradis** [comment]
Thanks @fbernhart 
Looks like they updated their logo (https://www.topcoder.com/topcoder-evolution-of-a-brand/) and their color. Do we merge this one and create a new issue to update it or do you want to give it a try here?

**Comment by fbernhart** [comment]
@service-paradis Let me change it here.

What would you suggest as color? Currently we are using `#29A8E0`. The light blue in the new logo is `#29A7DF`, the darker blue is `#0A73B8`. The linked article at the end of your link (https://projects.invisionapp.com/boards/39103SGXN7Y82#/1684528) is using quite a lot the light blue (`#29A7DF`).

The elements [on their website](https://www.topcoder.com/) are using all kind of blue and turquoise: `#07D6A0`, `#43D7B0`, `#26B3C5`, `#2C95D7`, `#1E94A3` and so on ....

**Comment by service-paradis** [comment]
> Edit: I've now even found their brand style guide at https://zeroheight.com/1g0pfacwv/p/51dcf6-colors/b/28961e. But the color section isn't of any help at all. It lists all kinds of colors and the section "blue" alone has 7 different kind of shades of blue. `#2C95D7`, `#2984BD`, `#16679A`, `#50ADE8`, `#83C5EE`, `#BAE1F9` and `#EAF6FD`. What a color mess. 😅

The more and more I think about it, the more I am confused 😅 
On their website, they kind of use dark green (`#137D60`) for accent elements (buttons and some links). This color is used in the "Button" section of the brand guideline.

**Comment by fbernhart** [comment]
Maybe the other @simple-icons/maintainers can help out?

**Comment by mondeja** [comment]
I would opt by `#29A7DF` because is used in the logo and in parts of the page. Seems that the brand style guide is used for multiple components, is not the brand style guide itself.

**Comment by service-paradis** [comment]
Or `#29A9E1` mentioned as the primary blue in https://projects.invisionapp.com/boards/39103SGXN7Y82#/1684528...

**Comment by fbernhart** [comment]
Almost forgot about this one 😅 

I've now updated the PR with the new logo and the new color. I agree with @mondeja that `#29A7DF` is a better fit in this case.

@service-paradis Feel free to review it again and then merge it, if everything is o.k.

**Review by service-paradis — CHANGES_REQUESTED** [review]
Which source did you use?
I compared with the icon found at https://zeroheight.com/1g0pfacwv/p/56600f-logos--icons/b/68b761 and it looks different:
image

**Comment by fbernhart** [comment]
@service-paradis Sorry for not mentioning the source.

I've actually used this SVG https://www.topcoder.com/wp-content/themes/tc3-marketing/nav/image/tc-logo.svg which they use in the [header of their website](https://www.topcoder.com/).

**Comment by adamrusted** [comment]
> I've actually used this SVG [topcoder.com/wp-content/themes/tc3-marketing/nav/image/tc-logo.svg](https://www.topcoder.com/wp-content/themes/tc3-marketing/nav/image/tc-logo.svg) which they use in the [header of their website](https://www.topcoder.com/).

Matches up with my path just built from source. Will wait for @service-paradis' approval before merging though.

**Review by adamrusted — APPROVED** [review]
> I've actually used this SVG [topcoder.com/wp-content/themes/tc3-marketing/nav/image/tc-logo.svg](https://www.topcoder.com/wp-content/themes/tc3-marketing/nav/image/tc-logo.svg) which they use in the [header of their website](https://www.topcoder.com/).

Matches up with my path just built from source. Will wait for @service-paradis' approval before merging though.

**Review by service-paradis — APPROVED** [review]
Well, looks like their brand guidelines are outdated!

Thank you @fbernhart for your work and thank you @adamrusted for the review 🎉

**Pull request merged**
