### PR TITLE
Add distrokid

### LINKED ISSUE #9107: Request: distrokid
### Brand Name

distrokid

### Website

https://distrokid.com/

### Popularity Metric

is the leader in music releasing 

### Official Resources for Icon and Color

https://distrokid.com/logo/

### Additional Comments

cn you follow the original color ?

### Contributing

Yes

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
distrokid

**Issue:** closes #9107 

**Similarweb rank:** 9,377. See https://www.similarweb.com/website/distrokid.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from https://distrokid.com/logo/
Color: `#231F20` taken from logo at https://distrokid.com/images/logo/distrokid.svg

### CODE REVIEW

**Review by adamrusted — COMMENTED** [review]
The icon itself is a perfect match to the SVG found at source.
I'd raise however that the company use [the mascot](https://github.com/simple-icons/simple-icons/assets/1830867/a92792bc-28ac-4d20-9280-a38d11212e52) in most places (socials, favicon) so would we instead have to consider that as our icon? What do other @simple-icons/icon-review think?

**Comment by OfficialCRUGG** [comment]
I agree with @adamrusted. From my personal observations, the mascot is what most people associate with Distrokid.

**Comment by PratyushJayachandran** [comment]
The mascot is not available as SVG and they have linked the wordmark as the logo they want people to use. So I'm not sure.

**Comment by adamrusted** [comment]
Hm, okay. Let's merge in the text logo for now, given that's the only one they offer up. Can always swap to the mascot if they ever officially release it as a usable icon!

**Pull request merged**
