### PR TITLE
Added Dodge

### PR DESCRIPTION
**Pull request by adamrusted**
dodge

**Issue:** Contributes to #4578
**Alexa rank:** [26,400](https://www.alexa.com/siteinfo/dodge.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Use of the wordmark on it's own is permitted by Dodge (see [this PDF](http://www.fcaci.com/x/v10_images/guidelines/Dodge_Brand_Mark_Guidelines.pdf)), so figured it's inclusion made sense until we can look at incorporating the full duotone icon (hopefully).

SVG used found on Stellantis website. Think we can get away with just the stripes, as it's used in the `Dodge` favicon. Hex pulled from Dodge stylesheet.

#### Previous Treatment
dodge

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
From page 3 of [this PDF](http://www.fcaci.com/x/v10_images/guidelines/Dodge_Brand_Mark_Guidelines.pdf) it looks to me like we need to include the wordmark. However, doing so would necessitate cutting the letters out of the lines which would also seem not to be permitted by those guidelines and I think the fact that this is the _only_ icon on the Stellantis website to be duotone probably backs that up.

**Comment by adamrusted** [comment]
> From page 3 of [this PDF](http://www.fcaci.com/x/v10_images/guidelines/Dodge_Brand_Mark_Guidelines.pdf) it looks to me like we need to include the wordmark. However, doing so would necessitate cutting the letters out of the lines which would also seem not to be permitted by those guidelines and I think the fact that this is the _only_ icon on the Stellantis website to be duotone probably backs that up.

Yeah I took my lead from the favicon, which is just the stripes. Happy to skip this one for now if it requires a duotone treatment.

**Comment by adamrusted** [comment]
@PeterShaggyNoble - updated to use the FCACI source.

**Comment by PeterShaggyNoble** [comment]
Looking over their guidelines again, I don't think we're going to be able to add this one without violating them. The fact that their parent company can't even make an exception for their own brand is pretty damning too.

**Pull request closed without merging**
