### PR TITLE
Update Synology

### PR DESCRIPTION
**Pull request by fbernhart**
synology

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by adamrusted — COMMENTED** [review]
Should this be updated to the full wordmark, as shown on their logo guide?
What do other @simple-icons/maintainers think?

**Comment by mondeja** [comment]
> Should this be updated to the full wordmark, as shown on their logo guide?

I would say yes, quoting brand guidelines: 'The "Synology" logo consists of the word Synology as illustrated below.'

**Review by adamrusted — CHANGES_REQUESTED** [review]
> > Should this be updated to the full wordmark, as shown on their logo guide?
> 
> I would say yes, quoting brand guidelines: 'The "Synology" logo consists of the word Synology as illustrated below.'

@fbernhart - as mentioned above, could you please regenerate this using the full wordmark for Synology? 🙏🏻

**Comment by fbernhart** [comment]
@adamrusted Done. I've as well changed the color slightly. [Their brand guidelines](https://www.synology.com/en-global/company/branding) mention rgb(181,181,182) which should be `#B5B5B6`.

**Comment by adamrusted** [comment]
> @adamrusted Done. I've as well changed the color slightly. [Their brand guidelines](https://www.synology.com/en-global/company/branding) mention rgb(181,181,182) which should be `#B5B5B6`.

Amazing - do we need to include the &reg; symbol in the logo also? I don't see any explicit mention on the logo guide page about the mark, but it *is* featured in every use of the logo on the page, even the incorrect ones!

**Comment by fbernhart** [comment]
> Amazing - do we need to include the ® symbol in the logo also?

@adamrusted Quoting our contribution guidelines:

> If there is no explicit requirement that a symbol must be included, it must not be included.

That's why I've removed it.

**Comment by ericcornelissen** [comment]
I'm not familiar with the brand, but from the brand guidelines this seems to me to fall into the same category as Intel :thinking: 

> If the symbol is incorporated into the design of the logo (e.g. Intel), it must be included.

**Comment by fbernhart** [comment]
I wouldn't say that the (R) is really integrated into the design of the logo.

But I'm happy to add it, if this is the consensus. 😊

**Comment by ericcornelissen** [comment]
> I wouldn't say that the (R) is really integrated into the design of the logo.

If it isn't can you show me a place where they use the logo without the (R)?

**Comment by fbernhart** [comment]
You're right. Seems like they are using it everywhere.

Let me add it. 👍🏼

**Comment by fbernhart** [comment]
Fixed

synology

**Review by adamrusted — APPROVED** [review]
Perfect! @fbernhart 💯

**Pull request merged**
