### PR TITLE
Add Blockchain.com

### PR DESCRIPTION
**Pull request by loganmarchione**
**Issue:** N/A
**Alexa rank:** 1,582 
  

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

There is a SVG in their [homepage](https://www.blockchain.com/). Wasn't sure on the color though, please check and let me know.
blockchain-dot-com

### CODE REVIEW

**Comment by service-paradis** [comment]
I found a press kit containing their logos at https://www.blockchain.com/fr/press

There is also a monochrome version of their logo at https://exchange.blockchain.com/.

The icon is looking good. 🎉 

I dont know about the color. They use `#0c6cf2` a lot on their website (every CTA, a lot of links, ...). Maybe another @simple-icons/maintainers can help with the color?

**Comment by PeterShaggyNoble** [comment]
I would say `#121d33` for the colour.

**Comment by loganmarchione** [comment]
I updated the color to `121d33`
 blockchain-dot-com

**Review by PeterShaggyNoble — APPROVED** [review]
Thanks, @loganmarchione. Based on @service-paradis' review of the icon, this should be good to go now. But given the lack of clarity on the colour choice we'll need approval from at least one of the other @simple-icons/maintainers before merging.

**Comment by adamrusted** [comment]
So from what I can see, the below three hex codes are in use in the icon:
`#85B5F8` `#3D89F5` `#1656B9`

With `#121d33` and `#0c6cf2` being used heavily throughout the website.

Having a quick glance at the site - I'd have gone with `#0C6CF2` - it looks (by my shoddy eyes at least) to be roughly the midpoint between the two darker blues of the logo (`#2A70D7` is the [calculated midpoint](https://meyerweb.com/eric/tools/color-blend/#1656B9:3D89F5:1:hex) of those two, which is _another_ option!), and is used extensively throughout the website and the app. Unfortunately they seem to pick a vague hex that's near enough to 'their colour' for every social post, so I was unable to glean any info from there.

**Comment by adamrusted** [comment]
Any of the other @simple-icons/maintainers want an input on the colour of this one? Suggestions in https://github.com/simple-icons/simple-icons/pull/4818#issuecomment-763765051, https://github.com/simple-icons/simple-icons/pull/4818#issuecomment-763768270, and https://github.com/simple-icons/simple-icons/pull/4818#issuecomment-764798583. Be good if we can reach a consensus before @loganmarchione makes any more changes 😅

**Comment by ericcornelissen** [comment]
Regarding the color: judging by the website I would also have opted for lighter blue than `#121d33`, such as `#0c6cf2` or `#3D89F5`. Given that the website seems to be a bit inconsistent on the website ("_Unfortunately they seem to pick a vague hex that's near enough to 'their colour' for every social post, so I was unable to glean any info from there._") I would choose the color in the SVG as it is more consistently used **and** provided on the press page.

In any case, I agree that this can be merged as is. The color can be changed later after the discussion has concluded.

Regarding the PR: I would suggest including the press page (https://www.blockchain.com/en/press) as [the "guidelines"](https://github.com/simple-icons/simple-icons/blob/1a0a7a7f98111ae59cdcb298f6e3ba06b528fa31/.jsonlintschema#L29-L34) for this brand.

**Comment by loganmarchione** [comment]
@ericcornelissen  - I left the color as-is but added the brand guidelines.

**Review by adamrusted — APPROVED** [review]
SVG matches up perfectly, thanks @loganmarchione! 🎉

@simple-icons/maintainers, the colour may still need some further discussion, but I'm merging as-is for now to clear our backlog.

**Pull request merged**
