### PR TITLE
Add google display & video 360

### LINKED ISSUE #3718: Request: Google Display & Video 360 Icon
**Name:** Google Display & Video 360
**Website:** https://displayvideo.google.com/
**Alexa rank:** #1 as it is part of the Google marketing platform
  

**Official resources for icon and color:** https://www.gstatic.com/analytics-suite/header/suite/v2/ic_display_video.svg

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
googledisplayandvideo360

**Issue:** closes #3718 

### Checklist
- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from https://marketingplatform.google.com/about
Color: Taken from logo `#34a853`

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Most of the icon looks spot on, but the end of the bottom path is missing. Could you re-work please, @PratyushJayachandran?

image

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
I'm seeing numerous differences here now, @PratyushJayachandran - [some examples](https://github.com/simple-icons/simple-icons/assets/15157491/e115ec9f-797a-4115-94e1-7972c22fe9e1), with yours in red. I'm using [this one](https://github.com/simple-icons/simple-icons/assets/15157491/49ccfc16-459b-4e97-97c9-e6b142511ed6) for comparison.

Gave it a try myself and came up with this:
```
M 4.4215943,0.00976563C 3.2615066,-0.08676971 2.1533072,0.50865788 1.5934693,1.5292969 0.75983728,2.9555962 1.2515455,4.7880872 2.6872193,5.6054688L 13.286828,11.669922 18.077844,8.9980469c 0.478244,-0.2649644 0.989515,-0.4072897 1.498047,-0.4394531 0.104501,-0.00661 0.208456,-0.00647 0.3125,-0.00391L 5.7008912,0.42382812C 5.3120664,0.18906383 4.8742377,0.0473544 4.4215943,0.00976563ZM 1.1637818,4.7675781V 19.251953c 0.6081148,-1.008792 1.7141975,-1.6875 2.9726563,-1.6875 1.2518744,0 2.3514032,0.671816 2.9609374,1.671875L 7.1012818,8.7070312 2.4391724,6.0390625C 1.8885995,5.7256011 1.4603801,5.2802683 1.1637818,4.7675781ZM 19.583703,9.0566406c -0.443645,0.033562 -0.874754,0.162828 -1.263672,0.3789063L 7.5993287,15.414062c 0.00384,1.872324 -0.010437,3.74508 0.00391,5.617188 0,0.399836 -0.071962,0.987709 -0.3964844,1.605516L 19.755582,15.410203 21.241911,14.580125C 22.511187,13.914209 23.125929,12.4385 22.704801,11.068406 22.23094,9.7756717 20.956747,8.9543838 19.583707,9.0566876ZM 4.1364381,18.064453c -1.6398937,-7.21e-4 -2.9694706,1.328856 -2.96875,2.96875 3.585e-4,1.639131 1.3296191,2.967517 2.96875,2.966797 1.6383682,-3.59e-4 2.9664384,-1.328429 2.9667968,-2.966797 7.202e-4,-1.639131 -1.3276659,-2.968391 -2.9667968,-2.96875z
```

**Comment by PratyushJayachandran** [comment]
> I'm seeing numerous differences here now, @PratyushJayachandran - [some examples](https://github.com/simple-icons/simple-icons/assets/15157491/e115ec9f-797a-4115-94e1-7972c22fe9e1), with yours in red. I'm using [this one](https://github.com/simple-icons/simple-icons/assets/15157491/49ccfc16-459b-4e97-97c9-e6b142511ed6) for comparison.
> 
> Gave it a try myself and came up with this:
> 
> ```
> M 4.4215943,0.00976563C 3.2615066,-0.08676971 2.1533072,0.50865788 1.5934693,1.5292969 0.75983728,2.9555962 1.2515455,4.7880872 2.6872193,5.6054688L 13.286828,11.669922 18.077844,8.9980469c 0.478244,-0.2649644 0.989515,-0.4072897 1.498047,-0.4394531 0.104501,-0.00661 0.208456,-0.00647 0.3125,-0.00391L 5.7008912,0.42382812C 5.3120664,0.18906383 4.8742377,0.0473544 4.4215943,0.00976563ZM 1.1637818,4.7675781V 19.251953c 0.6081148,-1.008792 1.7141975,-1.6875 2.9726563,-1.6875 1.2518744,0 2.3514032,0.671816 2.9609374,1.671875L 7.1012818,8.7070312 2.4391724,6.0390625C 1.8885995,5.7256011 1.4603801,5.2802683 1.1637818,4.7675781ZM 19.583703,9.0566406c -0.443645,0.033562 -0.874754,0.162828 -1.263672,0.3789063L 7.5993287,15.414062c 0.00384,1.872324 -0.010437,3.74508 0.00391,5.617188 0,0.399836 -0.071962,0.987709 -0.3964844,1.605516L 19.755582,15.410203 21.241911,14.580125C 22.511187,13.914209 23.125929,12.4385 22.704801,11.068406 22.23094,9.7756717 20.956747,8.9543838 19.583707,9.0566876ZM 4.1364381,18.064453c -1.6398937,-7.21e-4 -2.9694706,1.328856 -2.96875,2.96875 3.585e-4,1.639131 1.3296191,2.967517 2.96875,2.966797 1.6383682,-3.59e-4 2.9664384,-1.328429 2.9667968,-2.966797 7.202e-4,-1.639131 -1.3276659,-2.968391 -2.9667968,-2.96875z
> ```

I redid and placed your svg over mine. [Here is the result!](https://github.com/simple-icons/simple-icons/assets/35000807/9364d8b4-17dd-46a0-9e61-0a7243d377c8)
Your svg had dimensions:
image

Not sure why we are seeing different end results on same SVG 😿

**Comment by PeterShaggyNoble** [comment]
I'm seeing some different differences now, @PratyushJayachandran, plus some imperfections in the cut-outs and quite a few excess points. Not sure why my version was coming in at the incorrect size for you, but give this optimised version a try:

```
M4.421.01a2.947 2.947 0 0 0-2.828 1.52 2.967 2.967 0 0 0 1.094 4.076l10.6 6.064 4.79-2.672a3.546 3.546 0 0 1 1.811-.443L5.701.424A2.947 2.947 0 0 0 4.42.01ZM1.164 4.768v14.484a3.474 3.474 0 0 1 2.972-1.687 3.47 3.47 0 0 1 2.961 1.672l.004-10.53L2.44 6.04a3.433 3.433 0 0 1-1.275-1.271Zm18.42 4.289a3.08 3.08 0 0 0-1.264.379L7.6 15.414c.003 1.873-.011 3.745.003 5.617 0 .4-.072.988-.396 1.606l12.548-7.227 1.487-.83a2.978 2.978 0 0 0 1.463-3.511 3.08 3.08 0 0 0-3.121-2.012ZM4.136 18.065A2.967 2.967 0 1 0 4.134 24a2.967 2.967 0 0 0 .002-5.935z
```

**Review by adamrusted — APPROVED** [review]

**Pull request merged**
