### PR TITLE
Add NSIS icon

### PR DESCRIPTION
**Pull request by zrfisaac**
image

**Issue:** Nullsoft Scriptable Install System

**Similarweb rank:** [- -](https://nsis.sourceforge.io/Download)

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
NSIS (Nullsoft Scriptable Install System) is a professional open source system to create Windows installers. It is designed to be as small and flexible as possible and is therefore very suitable for internet distribution.

### CODE REVIEW

**Review by sisp — COMMENTED** [review]
Since NSIS is not being developed on GitHub and the documentation website has no Similarweb rank, none of the standard popularity metrics can be applied for determining its popularity. I'm no Windows expert, but some research and the [supposed users of NSIS](https://nsis.sourceforge.io/Users) indicate that it's indeed quite popular in the Windows community. Any opinions, @simple-icons?

How did you obtain the SVG icon? The source URL refers to a JPG image. Did you vectorize the icon manually? If not, the source URL of the vector image should be provided instead.

**Comment by sachinraja** [comment]
This does indeed look popular enough based on that page you shared @sisp. I also have the same question about the source image

**Comment by zrfisaac** [comment]
Like in the issue #7334 I didn't know that it must be an official svg file posted, so I will ask them to publish the logo in the svg file too.

**Comment by service-paradis** [comment]
@zrfisaac Can you follow-up with them regarding the logo?

**Comment by sredna** [comment]
> them

I did ask for slightly larger spacing to make the small icon look better but perhaps that is not possible?

**Comment by zrfisaac** [comment]
> > them
> 
> I did ask for slightly larger spacing to make the small icon look better but perhaps that is not possible without affecting the large one too much?

Yep, I don't know if this is posible, anyway I will see this week. I had a time off because of my job but I'm going back to work on this!

**Comment by adamrusted** [comment]
GitHub source for the icons found [here](https://github.com/idleberg/nsis-logo) including an [icon sized one with larger gaps](https://github.com/idleberg/nsis-logo/blob/885ba2fd08a6ff450c6f7cbd675563b5df728d38/src/Logo/below%2024x24/mono-flat.svg)!
Will update this PR now.

**Review by PeterShaggyNoble — APPROVED** [review]

**Pull request merged**
