### PR TITLE
Added ROS

### LINKED ISSUE #3347: Request: ROS Icon
**Name:** ROS
**Website:** https://www.ros.org/
**Alexa rank:** 26.5 k
  

**Official resources for icon and color:**
Brand guidelines : https://www.ros.org/press-kit/
color : the color value for print is 533C and the online hex color is #22314E

### PR DESCRIPTION
**Pull request by ed-muthiah**
image

**Issue:** Closes #3347
**Alexa rank:** [51,653](https://www.alexa.com/siteinfo/ros.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG used from [Wikipedia](https://upload.wikimedia.org/wikipedia/commons/b/bb/Ros_logo.svg)
Had to use precision 4 because precision 3 would not centre at 12,12.

### CODE REVIEW

**Comment by fbernhart** [comment]
@ed-muthiah Thanks for your contribution.

I've been able to get a path with a precision of 3, that exactly centers. Would you mind updating it?

```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>ROS icon</title><path d="M2.807 0C1.353 0 .173 1.22.173 2.722c0 1.504 1.18 2.723 2.634 2.723 1.455 0 2.635-1.22 2.635-2.723S4.262 0 2.807 0zM12 0c-1.455 0-2.634 1.22-2.634 2.722 0 1.504 1.18 2.723 2.634 2.723 1.455 0 2.634-1.22 2.634-2.723S13.454 0 12 0zm9.193 0c-1.455 0-2.635 1.22-2.635 2.722 0 1.504 1.18 2.723 2.635 2.723 1.455 0 2.634-1.22 2.634-2.723S22.647 0 21.193 0zM2.807 9.277C1.353 9.277.173 10.497.173 12s1.18 2.722 2.634 2.722c1.455 0 2.635-1.219 2.635-2.722 0-1.504-1.18-2.723-2.635-2.723zm9.193 0c-1.455 0-2.634 1.22-2.634 2.723s1.18 2.722 2.634 2.722c1.455 0 2.634-1.219 2.634-2.722 0-1.504-1.18-2.723-2.634-2.723zm9.193 0c-1.455 0-2.635 1.22-2.635 2.723s1.18 2.722 2.635 2.722c1.455 0 2.634-1.219 2.634-2.722 0-1.504-1.18-2.723-2.634-2.723zM2.807 18.555c-1.454 0-2.634 1.22-2.634 2.722C.173 22.781 1.353 24 2.807 24c1.455 0 2.635-1.22 2.635-2.723s-1.18-2.722-2.635-2.722zm9.193 0c-1.455 0-2.634 1.22-2.634 2.722C9.366 22.781 10.546 24 12 24c1.455 0 2.634-1.22 2.634-2.723s-1.18-2.722-2.634-2.722zm9.193 0c-1.455 0-2.635 1.22-2.635 2.722 0 1.504 1.18 2.723 2.635 2.723 1.455 0 2.634-1.22 2.634-2.723s-1.18-2.722-2.634-2.722z"/></svg>
```

Just a note for the future: Whenever possible, we prefer using an official source (website, press kit, ...). Only if there is no official vectorized logo available, we're using Wikimedia/Wikipedia. As for ROS, there is a vectorized EPS file in the press kit at https://www.ros.org/press-kit. So I've used this one to create the SVG. 😊

**Comment by ed-muthiah** [comment]
@fbernhart Thanks for that 👍🏽 will get from the press-kit in the future.

**Comment by loganmarchione** [comment]
This icon was requested in two issues, #3646 and #3347. Mentioning them here so they get linked.

**Comment by ed-muthiah** [comment]
@loganmarchione 3rd time lucky haha

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks for your work on this @ed-muthiah, and thanks @fbernhart for the optimization! 🎉

**Pull request merged**
