### PR TITLE
Update Tor Project

### PR DESCRIPTION
**Pull request by fbernhart**
torproject

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by service-paradis** [comment]
Since #3442 have been merged a few days ago, maybe it does not need to be updated but only removed from `.svglint-ignored.json`?

**Comment by fbernhart** [comment]
@service-paradis Thanks. I haven't seen the other PR.

**Comment by fbernhart** [comment]
@service-paradis No, the linter is failing due to too high precision.

> x icons/torproject.svg
>   x icon-precision Maximum precision should not be greater than 5; it is currently 7

**Comment by service-paradis** [comment]
> @service-paradis No, the linter is failing due to too high precision.

Ok, thank you, sorry for this!

**Comment by ericcornelissen** [comment]
Yes, I merged #3442 a little to quick when trying to include it in #4150. After that I manually added it to the list of ignored SVGs (in 404f98e8eb8da1e6a1e4c32b387fc9882fdca0e2) and to #3169 as well.

**Review by mondeja — APPROVED** [review]
Spot on! :onion:
Thank you @fbernhart!

**Pull request merged**
