### PR TITLE
Add cookiecutter icon

### PR DESCRIPTION
**Pull request by browniebroke**
cookiecutter-preview

**Issue:**
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I'm helping maintain a popular cookiecutter template ([Cookiecutter Django](https://github.com/pydanny/cookiecutter-django)) and I was interested in adding the logo to a custom shield.io badge. 

So far, I've managed to add the image base64 encoded:
cookiecutter

But I'm interested to add the image here to make it easier (since shied.io uses simple icons as source).

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Did you mean to close this, @browniebroke, or are you still working on it?

**Comment by browniebroke** [comment]
I'm no longer working on this. I worked from a PNG and tried to generate a SVG, but it didn't work and it seems out of my skill sets.

I can share the Figma file if someone is interested to pick it up...

**Comment by PeterShaggyNoble** [comment]
There's an SVG at https://github.com/cookiecutter/cookiecutter/blob/master/logo/cookiecutter-logo.svg if you'd like to give it another go?

**Comment by browniebroke** [comment]
I think the main problem left is that the SVG makes use of `fill-rule="evenodd"`. If I run it through SVGO, the attribute is stripped and the eye disappear.

**Comment by adamrusted** [comment]
Hey @browniebroke, I can see you're having a few issues getting the linter to pass.
I've been able to generate the below path, which passed the linter - feel free to use it 👌🏻

```svg
<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Cookiecutter icon</title><path d="M12.8182 12l9.2432-7.6496a11.9972 11.9972 0 00-3.1978-2.7141C13.14-1.7025 5.7933.2308 2.4545 5.9545-.8843 11.6782 1.049 19.0248 6.7727 22.3636s13.0703 1.4055 16.4091-4.3182L12.8182 12zm-6.7579 1.406c-.365 0-.7272-.1657-.8049-.3682-.0777-.2025.1177-.9702.4342-1.706.5056-1.1753.6693-1.3378 1.3478-1.3378 1.0326 0 1.7876.4344 1.7876 1.0285.0001.6937-1.9602 2.3835-2.7647 2.3835zm4.7117-9.6078c-.4867.1868-2.4566.177-2.9312-.0145-.5264-.2124-.38-.7816.3188-1.2395.8054-.5277 1.2687-.5325 2.2532-.0234.8464.4376 1.0121 1.0269.3592 1.2774zm1.4304 3.037c.3594-.6161 1.1502-.8242 1.7663-.4648.6004.3502.8159 1.1128.4876 1.7255-.3434.6435-1.1596.8746-1.7891.5056-.6161-.3594-.8242-1.1502-.4648-1.7663zM16.859 21.955c-.201.5239-1.0451.4669-1.563-.1054-.676-.7469-.4044-2.6695.377-2.6695.3721 0 1.362 2.3162 1.186 2.7749z"/></svg>
```

Other @simple-icons/maintainers - the precision of 4 is necessary for the circle to display correctly, unless @fbernhart can work his Inkscape magic again 😅

**Comment by browniebroke** [comment]
Thanks a lot @adamrusted, your trick seems to made it (whatever it was 😄).

I've updated the content and PR description. Do you want me to squash the commits?

**Comment by adamrusted** [comment]
> I've updated the content and PR description. Do you want me to squash the commits?

Fab - I'll wait for another @simple-icons/maintainers to merge it being as I worked on the path. We'll squash and merge when it's added, so no need to worry on your end. Thanks for your work on this! 🎉

**Comment by fbernhart** [comment]
I did some magic and converted it to a precision of 3. 🧙🏼‍♂️ ✨ 🔮  I've as well updated the source to point to the specific SVG file used.

@adamrusted Feel free to review and merge.

**Review by adamrusted — APPROVED** [review]
Looks good to me! Thanks @browniebroke for your work on this, and thanks to @fbernhart for your Inkscape Wizardry! 🧙🏻‍♂️🔮

**Pull request merged**
