### PR TITLE
Add SMRT

### PR DESCRIPTION
**Pull request by mondeja**
smrt(2)

**Issue:** #2822

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Path extracted from wikipedia [website file](https://wikipedia.org/wiki/Mass_Rapid_Transit_(Singapore)#/media/File:Singapore_MRT_logo.svg).
- Hex value from logo.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one one, @mondeja.

I'm confused by this one, though, as the logo on (even the [Malay](https://ms.wikipedia.org/wiki/Sistem_Pengangkutan_Gerak_Cepat_(Singapura)) Wikipedia differs from the one on [their website](http://www.smrttrains.com.sg/). It looks to me that there are actually _two_ things called "Singapore Mass Rapid Transit" - the transport system itself and a company that operates _part_ of that system. So, given that, and assuming I'm right, my own instinct would be to go with the logo you chose too as it represents the whole system but, as there is an ambiguity, I'd like to here the thoughts of the other @simple-icons/maintainers or member of the community that might be native to Singapore or familiar with their transport system.

The SVG itself looks perfect to me but could I ask what led you to include the initials? Not saying it's necessarily wrong, but I would have just gone with the icon myself.

Other than that, the source URL just needs to be updated to https://commons.wikimedia.org/wiki/File:Singapore_MRT_logo.svg

**Comment by NovaGL** [comment]
I looked into this and this icon looks like a subsidiary of a subsidiary 

Its just used to outline there is a train service but the train company has a different logo. I think this will add to confusion.

So further information is needed.

**Comment by mondeja** [comment]
> could I ask what led you to include the initials?

I've used the [file in wikipedia website](https://en.wikipedia.org/wiki/Mass_Rapid_Transit_(Singapore)#/media/File:Singapore_MRT_logo.svg) which includes the initials.

>  would have just gone with the icon myself.

I can include only the icon. What are the thoughts of other @simple-icons/maintainers?

**Comment by ericcornelissen** [comment]
If I understand correctly, @PeterShaggyNoble was pointing out the difference between the parent company(?):

image logo parent company

And the transport company (as seen in this PR?):

image transport company

If that is the right distinction, then, in light of #2822, I would agree that this seems to be the _correct_ version.

That said, based on the images on [the English Wikipedia page for MRP](https://en.wikipedia.org/wiki/Mass_Rapid_Transit_(Singapore)) (the Maley version has mostly the same images), the logo of the parent company is perhaps more appropriate as it is [used on their trains](https://en.wikipedia.org/wiki/File:Kawasaki_c751_eunos.jpg). There are also [some trains](https://en.wikipedia.org/wiki/File:C751A_front.jpg) with what appears to be an old logo of theirs.

Again, in light of #2822 I would expect this PR to add the logo that people in Singapore would associate with the transportation system. But it's not clear which one that is...

**Comment by mondeja** [comment]
I've updated the pull using [this file as source](https://commons.wikimedia.org/wiki/File:SMRT_Corporation.svg) and updated the preview image, using their background color as the logo HEX value.

**Comment by PeterShaggyNoble** [comment]
Thanks, @mondeja. I've been out of the loop for a few days so have only skimmed through the discussion so far. Given the ambiguity, I think we should run with the logo you've chosen and, if it turns out to be the wrong one, I'm sure someone will let us know and we can update.

Again, though, I think we'd be safe enough to go with just the icon, without the initials.

**Comment by mondeja** [comment]
Ok, I've removed the initials two and a half months later :relieved: I'm sorry for the delay, this was a pull quite down in my  TODO list.

**Review by ericcornelissen — APPROVED** [review]
No problem at all @mondeja 😃 This looks perfect now, thanks once  again for you contributions to this project! 🎊

**Pull request merged**
