### PR TITLE
Add BookBub icon

### LINKED ISSUE #5236: Request: BookBub
**Brand Name:** BookBub
**Website:** https://www.bookbub.com/welcome
**Alexa rank:** 8848

https://www.alexa.com/siteinfo/bookbub.com

**Official resources for icon and color:**
https://insights.bookbub.com/bookbub-follow-bookmark-buttons-for-authors-websites/

### PR DESCRIPTION
**Pull request by mikestopcontinues**
BookBub

**Issue:** Closes #5236 
**Brand Name:** BookBub
**Website:** https://www.bookbub.com/welcome
**Alexa rank:** 8848

https://www.alexa.com/siteinfo/bookbub.com

Official resources for icon and color:
https://insights.bookbub.com/bookbub-follow-bookmark-buttons-for-authors-websites/

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

* I took the hex color directly from their website.
* I used the SVG logo on their home page to replicate the icons they distribute (as provided in the link above).

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @mikestopcontinues 🙂

The quality of the [source PNGs](https://github.com/simple-icons/simple-icons/files/6166207/bookbub-full-icon-sets.zip) is pretty terrible making a proper comparison tricky. When compared to the `48*48` icon with no background, though, your version looks good to me and, as the letters come from an official SVG, I'd be happy to merge this as-is. As it _is_ a recreation, though, we will need one of the other @simple-icons/maintainers to review it before we can do that.

For the colour, I think we should go with the `#f44336` used in the source SVG.

Should we go with https://insights.bookbub.com/bookbub-follow-bookmark-buttons-for-authors-websites/ for the source seeing as it shows the treatment you've used even though it doesn't include any SVGs?

**Comment by mikestopcontinues** [comment]
Hey Peter, my pleasure! I think that page is the best source for their intended brand icon.

For the color, the reason I went with `#dc3c31` is that's what they're using on their public-facing [home page](https://www.bookbub.com/launch). It's also the SVG logo I used, though I can't detect any differences in the font face between locations. The `insights` subdomain I think is a bit neglected, as it targets authors (re: advertisers) rather than readers, which are their main users. That said, the `insights` page is all they offer the press, so I think whichever way you go makes sense.

**Comment by adamrusted** [comment]
Thanks for the contribution @mikestopcontinues!
I agree with @PeterShaggyNoble's points above about updating the hex, and maybe using the source link he recommended. While there are no SVGs there - I feel like their press pages are likely to be the best place for us to source one in the future, should they update their branding. Would you mind making those couple of changes, and we can look to get this merged?

**Comment by mikestopcontinues** [comment]
@adamrusted Updates made!

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @mikestopcontinues 🎉

**Pull request merged**
