### PR TITLE
Add Amul

### LINKED ISSUE #3955: Request: Amul Icon
**Name:** Amul
**Website:** https://www.amul.com/
**Alexa rank:**  72,254
  

**Official resources for icon and color:**  https://www.amul.com/

### PR DESCRIPTION
**Pull request by bBSempai**
amul

**Issue:** Closes #3955
**Alexa rank:** 85.5k
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one on, @bBSempai 🙂

The linter is currently failing due to the `fill-rule` attribute on the `path` tag and because the path is slightly off centre.

**Comment by bBSempai** [comment]
This should work now right? @PeterShaggyNoble

**Comment by PeterShaggyNoble** [comment]
I'm seeing some differences between the lettering in your version (in red below) and the source file, @bBSempai; could you have another look at it?

**Comment by bBSempai** [comment]
Ahh I thought you wouldn't notice...lol well jokes aside I think it should work now 👀 
@PeterShaggyNoble tell me if there is anything else.

checknew

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @bBSempai 👍🏻 However, after a good bit more digging this morning I finally unearthed an official and much cleaner vector version of their logo in the PDF available on [this page](https://amul.com/classic/products/horeca.php) which differs quite significantly from the Wikipedia version. Would you mind updating the PR based on the new version? It does still have a good few excess points, if you're able to clean those up in the process. Also, from that PDF, I wonder if we might not be able to get away with just the "Amul" wordmark? It would definitely suit us better but, being more familiar with the brand, I'll defer to you on that choice.

**Comment by bBSempai** [comment]
Yeah the the vector logo on the pdf is much better in terms of quality and a proper svg can be made from it. 
Also, upon really cheking their products' pictures on the pdf plus at my home, it really is true that they are using just the "Amul" wordmark at the maximum number of places as their logo. Their official logo still looks like the previous one though; their [YouTube channel](https://www.youtube.com/channel/UCQEZFAIw6YFJAN63xoCA46w) also uses that as their profile picture. But I feel that using just the wordmark should be alright because it is being used by them everywhere on the display; and infact, better, taking in account its display and usage as a svg for the website. 
What's your take, should we go with just the wordmark @PeterShaggyNoble ?

**Comment by PeterShaggyNoble** [comment]
That sounds like a good enough argument to just go with the wordmark to me, @bBSempai 👍🏻

**Comment by bBSempai** [comment]
Okay thy has been done @PeterShaggyNoble 

amul

**Comment by PeterShaggyNoble** [comment]
Well, this is fun; the wordmark in the full logo on the left page of the spread is different to the one in the circle on the right page! 🙄

Your SVG lines up perfectly with the first one, though, so let's run with it 👍🏻 Just a couple of little things to clean up and then this is ready to merge:
1. There are a few excess points in the middle bar of the "A", could you see if you could remove or join them without distorting the path? No worries if you can't.
2. Same goes for the excess points in the top-left of each of the other letters.
3. Can you update the source to https://amul.com/classic/products/horeca.php?
4. The colour is slightly off compared to the `#ed1d24` found in the PDF.

**Comment by bBSempai** [comment]
Okay so I played with the path and removed significant amount of excess points but could not do it exacly the way you asked. Could not remove exactly the points you asked but still simplified the path. Tell me if it is okay else we can just go with the previous path.

**Comment by bBSempai** [comment]
Okay so I played around with the path and removed significant amount of the extra points. I could not remove exactly the points you asked but I simplified the path nevertheless. There is very veery minor difference and should not bother us. Tell me if it is okay else we can just go with the old path.

image

```XML
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Amul icon</title><path d="M4.009 12.785a5.627 5.627 0 01-1.167-.215l-.334.906.79.5c.113.072.253.024.476-.18l.157.157c-.357.411-.73.8-1.1 1.212a2.712 2.712 0 00-1.594-.877c-.628.014-1.213.62-.605 1.717.016.022-.095.138-.157.09a1.905 1.905 0 01-.282-2.093 1.487 1.487 0 011.513-.693l.313-.85c-.287-.113-.6 0-.988.308a1.484 1.484 0 011.412-1.251l.882-2.114a.88.88 0 00-1.125.439c-.131-.017-.224-.063-.25-.147l.9-1.681a1.79 1.79 0 011.152-.047c1.376.436 2.067 2.76 3.1 5.324.095.249.22.272.516-.045l.209.186-1.856 1.848-.854-2.556a2.668 2.668 0 01-1.108.062m3.89-.863c.292-.172.487-.133.515.157v1.631c0 .449-.334.443-.44.466l1.274 1.1 1.227-1.08a.477.477 0 00-.115-.178c-.2.108-.357.046-.357-.22v-1.651c.108-.512.838-.4.838-.047v1.7c-.018.34-.156.488-.311.535l1.157.956 1.243-1.042c-.02-.086-.02-.162-.13-.2-.123.01-.356.25-.356-.286v-1.624a.461.461 0 01.91.055v1.516c-.01.357-.074.583-.366.683l1.2.941 1.276-1.15c0-.078-.11-.158-.15-.179-.42.364-.4-.094-.4-.164V11.75a1.2 1.2 0 00-1.61-.782l-.91.667a1.39 1.39 0 00-1.376-.8c-.31.045-.963.839-1.04.714a1.19 1.19 0 00-1.208-.706l-1.07.923a.289.289 0 00.2.156m7.805.093c.523-.365.514.352.514.352v1.5c0 .527-.2.427-.348.488a16.644 16.644 0 011.454 1.011l1.446-.916 1.073.938 1.267-1.234s-.017-.18-.171-.172c-.444.436-.575-.288-.575-.288v-1.833c0-.8-1.028-.981-1.244-.973l-1.036 1.014a.41.41 0 00.194.165c.484-.383.567.169.567.169v1.5c-.014.62-1.14.847-1.14.008V11.65c-.095-.575-.912-.894-1.027-.793l-1.182.972c.056.093.06.2.207.186m5.343-1.989c.61-.559.747 0 .747.156v3.536c0 .7-.281.589-.385.613l1.209 1.018L24 14.239a.255.255 0 00-.124-.2c-.475.295-.443-.3-.443-.3V9.53c0-.528-.932-1.1-1.285-.986l-1.3 1.3a.242.242 0 00.2.185m-17.04 1.778a2.192 2.192 0 00.787-.033 7.126 7.126 0 00-.786-1.795.418.418 0 01-.078-.068l-.718 1.748s.375.091.8.148"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
That looks to have introduced quite a few differences, @bBSempai so I think we should stick with the current PR version. Had a go at cleaning up those few points myself and came up with the below, which may need to be run through SVGO again.

```
M 4.794,11.772 C 4.69,11.329 4.248,10.28 4.008,9.976 3.968,9.945 3.946,9.93 3.93,9.908 L 3.212,11.656 C 3.212,11.656 3.587,11.747 4.0085,11.804 4.279,11.834 4.566,11.834 4.794,11.772 Z M 21.794,10.179 V 13.715 C 21.794,14.415 21.512,14.305 21.409,14.328 L 22.618,15.346 24,14.236 C 23.986,14.15 23.937,14.065 23.876,14.041 23.401,14.335 23.433,13.739 23.433,13.739 V 9.527 C 23.433,8.999 22.5,8.43 22.148,8.541 L 20.844,9.838 C 20.859,9.892 20.904,10 21.047,10.0235 21.657,9.464 21.794,10.024 21.794,10.179 Z M 16.218,12.363 V 13.863 C 16.218,14.391 16.018,14.291 15.87,14.351 16.282,14.569 16.842,15.019 17.324,15.362 L 18.77,14.446 19.843,15.386 21.109,14.15 C 21.109,14.15 21.093,13.97 20.939,13.979 20.495,14.415 20.364,13.691 20.364,13.691 V 11.858 C 20.364,11.057 19.336,10.878 19.12,10.886 L 18.085,11.896 C 18.129963,11.970667 18.198084,12.028605 18.279,12.061 18.763,11.679 18.846,12.231 18.846,12.231 V 13.731 C 18.832,14.351 17.706,14.578 17.706,13.739 V 11.649 C 17.611,11.073 16.794,10.754 16.678,10.855 L 15.497,11.827 C 15.552,11.92 15.557,12.031 15.704,12.0135 16.227,11.647 16.218,12.363 16.218,12.363 Z M 8.413,12.076 V 13.708 C 8.413,14.158 8.079,14.15 7.973,14.173 L 9.247,15.277 10.474,14.197 C 10.449197,14.129945 10.409935,14.069173 10.359,14.019 10.156,14.126 10.002,14.065 10.002,13.799 V 12.145 C 10.11,11.633 10.84,11.748 10.84,12.098 V 13.794 C 10.822,14.134 10.684,14.282 10.53,14.329 L 11.686,15.285 12.929,14.242 C 12.909,14.157 12.909,14.082 12.8,14.042 12.676,14.05 12.443,14.292 12.443,13.754 V 12.137 C 12.699,11.484 13.328,11.827 13.353,12.192 V 13.708 C 13.344,14.065 13.279,14.291 12.987,14.391 L 14.191,15.331 15.467,14.181 C 15.467,14.104 15.357,14.024 15.317,14.003 14.898,14.367 14.921,13.908 14.915,13.838 V 11.748 C 14.898,11.383 14.215,10.623 13.305,10.965 L 12.395,11.633 C 11.911,10.809 11.205,10.786 11.017,10.833 10.709,10.877 10.055,11.671 9.979,11.546 9.691,10.833 8.926,10.818 8.77,10.84 L 7.7,11.764 C 7.754,11.881 7.841,11.896 7.8995,11.919 8.189,11.749 8.385,11.787 8.413,12.076 Z M 2.842,12.567 2.508,13.473 3.298,13.979 C 3.41,14.05 3.551,14.003 3.774,13.799 L 3.931,13.956 C 3.574,14.366 3.201,14.756 2.835,15.168 2.353,14.726 1.785,14.291 1.241,14.291 0.613,14.304 0.028,14.911 0.635,16.008 0.652,16.03 0.541,16.146 0.479,16.098 0.014,15.703 -0.173,14.616 0.193,14.003 0.449,13.606 0.913,13.218 1.706,13.31 L 2.019,12.46 C 1.732,12.347 1.421,12.46 1.031,12.768 1.163,12.098 1.582,11.632 2.443,11.516 L 3.325,9.402 C 2.858,9.215 2.422,9.442 2.205,9.838 2.073,9.821 1.98,9.775 1.955,9.691 L 2.858,8.011 C 3.298,7.858 3.675,7.858 4.009,7.963 5.385,8.399 6.076,10.723 7.107,13.288 7.202,13.536 7.328,13.559 7.623,13.242 L 7.833,13.428 5.973,15.278 5.117,12.72 C 5.117,12.742 4.7,12.845 4.0095,12.783 3.6141568,12.752253 3.2226591,12.679853 2.842,12.567 Z
```

**Comment by bBSempai** [comment]
Done

amul

**Review by PeterShaggyNoble — APPROVED** [review]
Thanks for your continued efforts and patience on this one, @bBSempai, it looks perfect to me now :+1:

As I had a hand in the final path, though, we'll need one of the other @simple-icons/maintainers to review it before it can be merged.

The only minor thing left to fix is the removal of the trailing `?` from the source URL.

**Review by adamrusted — APPROVED** [review]
Icon matches perfectly with what would be the back page of that brochure. Happy to merge this, and should we find a different source we can always update it. Thanks for your work on this @bBSempai and @PeterShaggyNoble 🚀

**Pull request merged**
