### PR TITLE
Create npm package

### PR DESCRIPTION
**Pull request by peterpme**
Hey @danleech!

Thanks again for creating this awesome resource!

Here's a basic package.json you can publish to npm. Once you merge this in and clone it, you can run `npm publish` and it'll automatically create an npm package called `simple-icons` 😄 

In this case, the only thing that will be consumed is `_data/simple-icons.json` but we can also build out all the icons or create another key that points to the official resource you're hosting so we're not bundling *all* the icons in the package.

Some fun things you can do with npm too is create a build script that will automatically build all the icons for you and push them to the site so you don't have to. 

Example:
Every time you merge in a new change, let travis or circle automatically take that icon and add it to the site.

Thanks again!

### CODE REVIEW

**Comment by peterpme** [comment]
@danleech just an FYI. No rush 😄

**Comment by birjolaxew** [comment]
Could you add a [`.npmignore`](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) file, keeping out everything but `_data/`, `icons`, `package.json` and `README.md`? If I understand NPM correctly, there's no point including all the webpage stuff in the package :P

I'll merge this afterwards and then let @danleech publish to NPM.

**Comment by birjolaxew** [comment]
Merged this. Going to let @danleech do the actual publishing.

**Comment by peterpme** [comment]
Thanks :) We can move forward with #443 now :)

**Comment by jenil** [comment]
Hey any idea when @danleech will be publishing the npm package?

**Comment by peterpme** [comment]
@jenil if you're interested you can start using this right away:
https://github.com/peterpme/create-simple-icon

**Comment by jenil** [comment]
@peterpme thanks for that, but that looks like a CLI app, does it have a node API?

**Comment by peterpme** [comment]
No, but you can download any icon you need and then require the svg file!

How do you envision the node api to work?

**Comment by jenil** [comment]
give me something like [this](https://unpkg.com/feather-icons@3.2.2/dist/icons.json)

**Comment by birjolaxew** [comment]
Since @danleech seems pretty much dead, I'll probably end up doing the publishing instead. If anyone feels like adding the necesarry files (changing `package.json -> main` to point to a file which exports the content of the files instead of their metadata) I can publish it asap.

**Comment by jenil** [comment]
@birjolaxew I can do that, make a library file which exports all the icon meta along with the SVG content, something like

```js
const SimpleIcons = require('simple-icons');

console.log(SimpleIcons);
/*
[{
    title: '500px',
    hex: '0099E5',
    source: 'https://about.500px.com/press',
    svg: '<svg aria-labelledby="simpleicons-500px-icon" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill=""><title id="simpleicons-500px-icon">500px icon</title><path d="..."/></svg>'
  },
  { ... }]
*/

console.log(SimpleIcons.toSvg('500px'));
// <svg aria-labelledby="simpleicons-500px-icon" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill=""><title id="simpleicons-500px-icon">500px icon</title><path d="..."/></svg>
```

Let me know if this works so I can proceed. 🙃

**Comment by birjolaxew** [comment]
@jenil I'd prefer exporting a simple map of icons, so that you can do:

```javascript
const SimpleIcons = require("simple-icons");

console.log(SimpleIcons);
/*
{
  "500px": {
    "hex": "0099E5",
    "source": "https://about.500px.com/press",
    "svg": 'svg aria-labelledby="simpleicons-500px-icon" role="img" ...'
  },
  ...
}
*/

console.log(SimpleIcons["500px"].svg);
// 'svg aria-labelledby="simpleicons-500px-icon" role="img" ...'
```

**Pull request merged**
