### PR TITLE
Add Pusher icon

### PR DESCRIPTION
**Pull request by adempus**
pusher

**Issue:** #5538
**Alexa rank:** 15,052
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Woot! First pull request! 🎉
- Added just the primary icon and JSON object for Pusher.

### CODE REVIEW

**Comment by adempus** [comment]
@adamrusted I am having issues centering the icon relative to the viewbox using Inkscape. There doesn't seem to be an automatic way to do this. I am having to manually adjust the icon in the viewbox, and tit's proving to be unwieldy. Any tips?

**Review by adempus — COMMENTED** [review]
fixed icon size of path to be exactly 24 in one dimension, previously (15.56 x 24.015). Fixed path to center at (12, 12), previously (11.95, 12.036)

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for the update @adempus!
I'm currently seeing some [differences](https://user-images.githubusercontent.com/1830867/116809453-02e3cf80-ab36-11eb-9c5b-d3841d17e51d.png) around the edges when comparing - which may just be down to a precision thing. Could you rebuild this from the source file, using a precision of 4, and see if that fixes the issue?

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for the update @adempus - though it appears the icon is still in 3 decimals, and having [similar issues](https://user-images.githubusercontent.com/1830867/116851415-3849f500-abea-11eb-92a0-f2dbdbd7dbed.png). In order to get it up to 4 decimals, you'll need to start from scratch on the icon, as trying to add decimals to a path that's already optimized to 3 decimals will keep it at 3. If you're using the NPM scripts, you can edit the `svgo.config.js` file, to set the `floatPrecision` to 4 - though be careful not to include that updated file in your PR!

**Comment by adempus** [comment]
> Thanks for the update @adempus - though it appears the icon is still in 3 decimals, and having [similar issues](https://user-images.githubusercontent.com/1830867/116851415-3849f500-abea-11eb-92a0-f2dbdbd7dbed.png). In order to get it up to 4 decimals, you'll need to start from scratch on the icon, as trying to add decimals to a path that's already optimized to 3 decimals will keep it at 3. If you're using the NPM scripts, you can edit the `svgo.config.js` file, to set the `floatPrecision` to 4 - though be careful not to include that updated file in your PR!

Ah, that explains why the values weren't changing. Started from scratch and set precision to 4. Hopefully that fixes it.

**Comment by adempus** [comment]
> > Thanks for the update @adempus - though it appears the icon is still in 3 decimals, and having [similar issues](https://user-images.githubusercontent.com/1830867/116851415-3849f500-abea-11eb-92a0-f2dbdbd7dbed.png). In order to get it up to 4 decimals, you'll need to start from scratch on the icon, as trying to add decimals to a path that's already optimized to 3 decimals will keep it at 3. If you're using the NPM scripts, you can edit the `svgo.config.js` file, to set the `floatPrecision` to 4 - though be careful not to include that updated file in your PR!
> 
> Ah, that explains why the values weren't changing. Started from scratch and set precision to 4. Hopefully that fixes it.

`

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @adempus 🚀

**Pull request merged**
