### PR TITLE
Updated Beats

### PR DESCRIPTION
**Pull request by fbernhart**
beats

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
image

There seems to be some differences when I use the `Solution Product Logo Glyphs/SVG/white/beats-logo-white-64.svg` file. Are you able to check this again?

My path provided below:
```
M10.875,15h-8.25V0h8.25c4.142,0,7.5,3.358,7.5,7.5C18.375,11.642,15.017,15,10.875,15z M19.64,11.705 c-1.571,3.261-4.91,5.518-8.765,5.518h-8.25V24h11.25c4.143,0,7.5-3.358,7.5-7.5C21.375,14.676,20.723,13.005,19.64,11.705z
```

**Comment by fbernhart** [comment]
@adamrusted Done 😊 Seems like they have slightly changed their logo.

**Review by adamrusted — APPROVED** [review]
Spot on! 🙌

**Comment by fbernhart** [comment]
@adamrusted I've resolved the merge conflict.

**Comment by adamrusted** [comment]
> @adamrusted I've resolved the merge conflict.

Beat me to it! You'll have to talk me through resolving them locally from a pull request some time 👌

**Pull request merged**
