### PR TITLE
Add NFC

### LINKED ISSUE #2491: NFC
**Name:** NFC (or Near-Field Communication?)
**Website:** https://nfc-forum.org/
**Alexa Rank:** [~1.2m](https://www.alexa.com/siteinfo/nfc-forum.org), which shouldn't matter as it *is* an important standard
**Colour:** `#002e5f`
**Official resources for icon and color:** https://nfc-forum.org/wp-content/uploads/2016/10/NFC_NMark_Guidebook_9.16.pdf (found at https://nfc-forum.org/our-work/nfc-branding/n-mark/guidelines-and-brand-assets/)

[image](https://github.com/simple-icons/simple-icons/files/4123044/nfc.zip)

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
NFC

**Issue:** Closes #2491

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by ericcornelissen** [comment]
With #2460 in mind, from the PDF in the source you linked:

> The N-Mark symbol is a trademark. By adhering to the following regulations, guidelines, and recommendations, you will maintain the integrity of the N-Mark. In jurisdictions where the N-Mark is registered, the N-Mark must always be  accompanied by the registered trademark ® symbol. Elsewhere, it must  appear with the trademark ™ symbol. If you employ the N-Mark in both  registered and unregistered jurisdictions, use of the ™ symbol is permitted,  unless otherwise advised by the NFC Forum.

I'm not entirely sure, but, assuming the SVG will be used "in both  registered and unregistered jurisdictions", I think we should include the trademark symbol (™) here...

**Comment by PeterShaggyNoble** [comment]
I went by the following line, found in the paragraph after the one you quoted:

> If the N-Mark is smaller than 5mm in height, or **if the means of display makes it infeasible to render** the ™ or ® symbol legibly, the ™ or ® symbol may be omitted. 

Another reason I opted to omit them is that I wasn't sure:
1. Of the legalities of claiming something is a *registered* trademark in a jurisdiction where it's not.
2. Whether showing the trademark symbol in jurisdictions where it is a registered trademark offers the necessary legal protections for that trademark.

The final reason was purely aesthetic, though; including it with the boxed version, which is their preference, would mean that the icon wouldn't fill the canvas in either direction in order to retain its proportions. A way around that, of course, would be to use the unboxed version, which could fill the entire vertical space and still be centred horizontally even with the inclusion of the symbol.

**Comment by ericcornelissen** [comment]
> > If the N-Mark is smaller than 5mm in height, or if the means of display makes it infeasible to render the ™ or ® symbol legibly, the ™ or ® symbol may be omitted.

Assuming [a 96 dpi screen, a 24x24 icon is actually ~6x6mm](https://www.pixelto.net/px-to-mm-converter). But I do agree that it might still be too small. In all honestly, in this regard, I would like to see it as displayed on our site before making a decision.


> Of the legalities of claiming something is a registered trademark in a jurisdiction where it's not.

That is a good point which I hadn't considered 🤔 


> Whether showing the trademark symbol in jurisdictions where it is a registered trademark offers the necessary legal protections for that trademark.

I don't know if it does and honestly I don't think it matters: if the guidelines say you should include it, you should include it.

**Comment by PeterShaggyNoble** [comment]
Here's what they looked like with the `TM` in place. Their illegibility at native size was why I took them up on the option of

> if the means of display makes it infeasible to render the ™ or ® symbol legibly, the ™ or ® symbol may be omitted

**Comment by PeterShaggyNoble** [comment]
I'll take another pass at the optimisation on Monday, see if it needs to be that high. Can't remember now why I *did* go that high but, usually, I zoom in as far as I can in SVGOMG so the icon fills my largest monitor, start at one end of the precision scale or the other, keep moving up or down until I no longer notice a visual difference and then do a quadrant-by-quadrant overlay comparison with the original in Inkscape in case my eye missed any hairline difference(s). Of course, it's equally likely to just be a mistake/copy-paste error! :laughing:

Also, as there was some uncertainty on the `™` symbol, we should get one of the other @simple-icons/maintainers to weigh in and confirm, *or* dispute, our final decision.

**Comment by PeterShaggyNoble** [comment]
Yeah, doesn't look like the precision _did_ need to be that high - clearly I was just seeing things! 😆

Updated.

**Comment by ericcornelissen** [comment]
Alright then, thanks for the contribution @PeterShaggyNoble 😃

**Pull request merged**
