### PR TITLE
Add CorelDRAW Icon

### LINKED ISSUE #5290: Request: CorelDRAW
**Brand Name:** CorelDRAW
**Website:** [CorelDRAW](https://www.coreldraw.com/en/)
**Alexa rank:** #7209

**Official resources for icon and color:**
&nbsp;&nbsp;&nbsp;[Official Graphic from their website](https://www.coreldraw.com/static/cdgs/images/home/coreldraw-2021-wm.png)

### PR DESCRIPTION
**Pull request by Mvlprem**
coreldraw

**Issue:** closes #5290

**Similarweb rank:** [44,751](https://www.similarweb.com/website/coreldraw.com/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

svg taken from this [pdf](https://github.com/simple-icons/simple-icons/files/14392576/Handout_Embroidery_EN.pdf), as for hex I'm going with black.

### CODE REVIEW

**Review by adamrusted — APPROVED** [review]
Icon is a perfect match for me. I'm not 100% on using black as our colour given their usual logo is so colourful, so I'll wait for another maintainer to review before merging!

**Comment by Mvlprem** [comment]
> Icon is a perfect match for me. I'm not 100% on using black as our colour given their usual logo is so colourful, so I'll wait for another maintainer to review before merging!

I'm not sure about it too, there is an entire color Palette in their logo.

**Comment by service-paradis** [comment]
> I'm not sure about it too, there is an entire color Palette in their logo.

Wow, and looking at their website does not help. I think their brand color is all the colors, so might as well use the sum of all colors and use black 😅

**Comment by PeterShaggyNoble** [comment]
What about `#4911d7`, which is used heavily throughout the site and is also used in \[the logo\](https://www.corel.com/static/corel/images/corel-wordmark-color-on-light.svg) of \[their parent company\](https://www.corel.com/)?

**Comment by Mvlprem** [comment]
@PeterShaggyNoble I think black would do fine, since they have a white logo in footer.

**Comment by service-paradis** [comment]
> What about `#4911d7`, which is used heavily throughout the site and is also used in [the logo](https://www.corel.com/static/corel/images/corel-wordmark-color-on-light.svg) of [their parent company](https://www.corel.com/)? If not then I think we should just run with black.

Purple to me refer to Corel which have many products (CorelDRAW, but also Painter, VideoStudio, WordPerfect, ...). The purpleish value can be seen in all their subproducts website (ex. https://www.paintshoppro.com/en/).

**Review by PeterShaggyNoble — APPROVED** [review]

**Pull request merged**
