### PR TITLE
Add Nutanix

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Nutanix
**Issue:** #1651

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble thanks for taking this one on. 👍 

What source did you use for this? Did you isolate the "X" from the full wordmark in the header by any chance? 

For some reason there seems to be a difference from that "X" (pointy toes) and the other "X" (rounded toes) used in the favicon, the logo in the footer, and as described on page six of the brand guide.

eg. 👇 
apple icon

I think the version of the wordmark in the header is a victim of over optimisation, it does not match the wordmark version found in the .eps download linked from the brand document either.

I've checked the logo from the footer against the .eps in this [Nutanix_X_CMYK_Gray.zip](https://github.com/simple-icons/simple-icons/files/3947302/Nutanix_X_CMYK_Gray.zip) and it matches.

Can you update the .svg using either of those as source please.

**Comment by PeterShaggyNoble** [comment]
Good catch, thanks, @phatbhoy67. I'll get that updated when I have a minute (which might not be a for a few days!).

**Comment by PeterShaggyNoble** [comment]
Updated.

Nutanix

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @PeterShaggyNoble 👍

**Pull request merged**
