### PR TITLE
Added Strapi Icon

### PR DESCRIPTION
**Pull request by ngrosso**
**Issue:#1593**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

~~Got the hex value from their [Github Logo](https://github.com/strapi/strapi/)~~
Edited: Got the hex from the original source SVG (thanks phatbhoy67)
~~Got the icon from [Iconify](https://iconify.design/)~~
Edited: Got the icon from the original press site (thanks phatbhoy67)
Then edited in inkscape for centering and fixing
Done the local testing  with jekyll and it looks nice

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Thanks for your work on this PR @ngrosso, comparing the [source](https://iconify.design/icon-sets/?query=strapi) you used with the official logo there appears to be some differences. See below:

strapi-comp

The official logo has more rounded caps on the strokes and appears to be using a thinner stroke width than your source.

Can you please update this PR using the official logo as the source. You can download the official logo from this [page](https://strapi.io/press) on the Strapi website by clicking the "download all logos" button.

**Comment by ngrosso** [comment]
ohh thank you for noticing that, i usually help open source between tasks at my office, this one was my mistake, I'll check it

**Comment by ngrosso** [comment]
Hi!! quick question guys, why is the test package build failing? it doesn't seems from the code i'm pushing, in the local run with jekyll it worked :thinking:

**Comment by ngrosso** [comment]
ohhh that explains everything :man_facepalming:

**Comment by ngrosso** [comment]
Well... it still fails :thinking:

**Comment by ngrosso** [comment]
> Could you update the icon so that the entire code of the SVG is on a single line @ngrosso? After that [the Travis CI build](https://travis-ci.com/simple-icons/simple-icons/jobs/248411950) should succeed.

Well.. it was a blank new line i left by mistake haha, thank you for the support

**Comment by phatbhoy67** [comment]
Hey @ngrosso well done for getting all those changes done! Just to confirm, you said you got the hex value from the official .svg, I have that value as `#2E7EEA` too. 

There are another few blues (and gradients of blues) used on their site including `#64b8f6`, `#2f80ed` and `#378fee`, so I think it should be the logo blue `#2E7EEA` do any @simple-icons/maintainers have a view?

**Comment by ericcornelissen** [comment]
Thanks a bunch for your work on this @ngrosso, we appreciated it very much 🎉

**Pull request merged**
