### PR TITLE
Add Auth.js icon

### LINKED ISSUE #8360: Add Auth.js Icon
### Brand Name

Auth.js

### Website

https://authjs.dev/

### Popularity Metric

The Similarweb rank is 279,511. See https://www.similarweb.com/website/authjs.dev

### Official Resources for Icon and Color

None

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by sumukhj1219**
FIxes #8360

### CODE REVIEW

**Comment by adamrusted** [comment]
Thanks for the submission @sumukhj1219, though there's a lot wrong with this PR that needs resolving before we can proceed.
- There are a huge number of packages showing as added to the `package.json` file. That needs reverting.
- You've added a number of unnecessary spaces to the JSON that need removing.
- The icon, though sized to 24*24px at a viewport level, does not adhere to our [specification](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon), and needs resolving.

**Comment by sumukhj1219** [comment]
Sorry for the inconvinience

**Comment by Jay-Karia** [comment]
@Sumukh1219 

You have written: "Fixes #11585" which is not an issue.
It should be "Fixes #11545  "

**Comment by Jay-Karia** [comment]
There's another issue about this: #8360

**Comment by sumukhj1219** [comment]
What should I do now?

**Comment by Jay-Karia** [comment]
The goal remains same: add Auth.js icon :)

**Comment by Jay-Karia** [comment]
@Sumukh1219 
Please revert the changes made in `package.json` file

**Comment by sumukhj1219** [comment]
Ok got it

**Comment by uncenter** [comment]
@sumukhj1219 are you still interested in continuing this pull request?

**Comment by sumukhj1219** [comment]
I'll try to resolve it by today if I don't you can assign it to someone else

**Comment by sumukhj1219** [comment]
I don't think I can sorry

**Comment by PeterShaggyNoble** [comment]
@sumukhj1219, can you remember where you found the SVG you based your attempt on? I can't find one anywhere.

**Comment by prem-k-r** [comment]
https://github.com/nextauthjs/next-auth/discussions/4656#discussioncomment-9431967
this I think

**Comment by PeterShaggyNoble** [comment]
Good find, @prem-k-r. Do you want to pick this one up yourself?

**Comment by prem-k-r** [comment]
Probably not, that svg is little off from their original icon

**Pull request closed without merging**
