### PR TITLE
Add Flathub

### LINKED ISSUE #2786: Flathub
**Name:** Flathub
**Website:** https://flathub.org/home
**Official resources for icon and color:** https://flathub.org/badges

### PR DESCRIPTION
**Pull request by creepertron95**
simpleicons

**Issue:** Closes #2786

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
 The icon and color is from the website header. I used the logo found on the header of the website.
I have manually vectorized the logo due to the original svg logo being confusing with the many strokes found on the logo `.svg`.

### CODE REVIEW

**Comment by creepertron95** [comment]
Source Image I created from the source logo.
flathub-icon-png

**Comment by PeterShaggyNoble** [comment]
Thanks for your work on this one, @creepertron95.

However, the path isn't horizontally centred on the canvas and there are some differences between your version (in red below) and the source SVG.

I took another stab at it myself and came up with this (unoptimised) path which _seems_ to line up a bit better:

```
M 12 2.6035156 L 11.570312 2.8867188 L 0 10.458984 L 0 17.210938 L 6.3925781 21.394531 L 12 17.724609 L 17.607422 21.396484 L 24 17.210938 L 24 10.458984 L 12 2.6035156 z M 12 3.4316406 L 17.433594 6.9882812 L 14.716797 8.765625 L 12 10.544922 L 9.2832031 8.765625 L 6.5664062 6.9882812 L 12 3.4316406 z M 6.390625 7.1035156 L 11.824219 10.660156 L 6.4160156 14.199219 L 0.98242188 10.642578 L 6.390625 7.1035156 z M 17.609375 7.1035156 L 23.041016 10.658203 L 17.607422 14.214844 L 12.173828 10.660156 L 17.609375 7.1035156 z M 0.92578125 10.867188 L 6.3046875 14.386719 A 0.12334991 0.0807359 0 0 0 6.3320312 14.400391 L 6.3320312 20.046875 L 0.92578125 16.507812 L 0.92578125 10.867188 z M 12.138672 10.982422 L 17.546875 14.521484 L 17.546875 20.185547 L 12.138672 16.646484 L 12.138672 10.982422Z
```

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @creepertron95?

**Comment by creepertron95** [comment]
@PeterShaggyNoble I apologize for not responding for so long. Could I use that path you posted and improve from there?

**Comment by PeterShaggyNoble** [comment]
> I apologize for not responding for so long

No problem; just checking you hadn't abandoned it before closing it as such.

> Could I use that path you posted and improve from there?

Absolutely! 🙂 Work away.

**Comment by PeterShaggyNoble** [comment]
Thanks for your efforts on this one, @creepertron95, it looks spot on to me now :+1:

**Pull request merged**
