### PR TITLE
Added Blender icon

### PR DESCRIPTION
**Pull request by Josh-Powlison**
The Blender icon and info is in this branch! Let me know if any changes need to be made!

I chose the color by grabbing it from the logo EPS file. I chose the orange because even though blue is in the icon, where Blender is showed and displayed the orange is generally shown more prominently for more important things (for example, their [fundraising rocket](https://www.blender.org/) is orange). Also, the orange is surrounding the blue and pops more.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Thanks for the contribution! 😄

**Comment by Josh-Powlison** [comment]
You're welcome, thanks for the fix! :D

**Comment by birjolaxew** [comment]
Quick tip for future PRs: make sure you branch from `develop` when creating new branches - that way you won't have the "Merge pull request ..." commits when you create a pull request.

<p align="center"></p>

**Comment by Josh-Powlison** [comment]
@birjolaxew Okay, thanks! I'm not quite sure what I did wrong though; is it that I didn't keep my fork up-to-date with the main branch here (like you'd mentioned I'd needed to check before)? I believe I branched from develop on my fork, although I could be wrong.

**Comment by ericcornelissen** [comment]
@Josh-Powlison you did everything correct this PR 😄 I think @birjolaxew was referring to `ecc72ac` and `9e5de63` as seen in the image below, but these where caused by your previous PR (#763)

image

But as you can see here, this PR comes from your `blender` branch and is merged into our `develop` branch.

image

**Comment by Josh-Powlison** [comment]
@ericcornelissen Okay, thanks! :D

**Pull request merged**
