### PR TITLE
Added Atlassian products icon (Confluence, Statuspage, Opsgenie)

### PR DESCRIPTION
**Pull request by hylickipiotr**
**Issue:** #1380

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Color was determined by @davidklebanoff.
> To whomever decides to complete this PR, all Atlassian icons share the same color, `#0052CC`.

### CODE REVIEW

**Comment by davidklebanoff** [comment]
@hylickipiotr - Where did you pull these SVG icons from? For example, the Statuspage icon is not consistent with the icon I pulled from https://atlassian.design/guidelines/marketing/resources/logo-files

**Comment by hylickipiotr** [comment]
I downloaded this icon from the offical URL, which is also in your comment. https://atlassian.design/guidelines/marketing/resources/logo-files
Maybe there was some mistake on my part. As fast as is possible, I will fix the problem with Statuspage.

**Comment by ericcornelissen** [comment]
Icons look good to me now, just need to fix the conflict with `simple-icons.json` to get this merged @hylickipiotr

**Comment by hylickipiotr** [comment]
Conflict with `simple-icons.json` was fixed. @ericcornelissen You can merged this PR.

**Comment by ericcornelissen** [comment]
Thanks for working on this one @hylickipiotr, it is much appreciated! 🎉

**Pull request merged**
