### PR TITLE
Egnyte

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Egnyte

**Issue:** Templarian/MaterialDesign#2687

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I was hoping to get away with just using the icon, as they do in their favicon but then I spotted this line in the text of the source URL:
> Please use without modification.

**Alexa rank:** [12447](https://www.alexa.com/siteinfo/egnyte.com)

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble is the source the [`egnyte-lightbg-vector.ai`](https://egnyte-www-static.egnyte.com/assets/images/presskit/corporate-logo.zip) file available to download from the [presskit page](https://www.egnyte.com/presskit.html#section-logos)?

The .ai version is different to the [logo.svg](https://egnyte-www-static.egnyte.com/assets/images/global-footer/Egnyte_logo_a.svg) used in the header and footer of [https://www.egnyte.com/](https://www.egnyte.com/). 

The "Y" is configured differently.

The .ai file appears to be from 2013. 

Is the .svg version fresher? 🤔

**Comment by PeterShaggyNoble** [comment]
Well spotted, @phatbhoy67. I did indeed use the `.ai` file from the zip, without noticing the difference to the SVG. The SVG is newer - the `lastModified` date is the 16th of February 2019 - but I think, if we're to err on the side of caution, we should go with the version they provide in the press kit. Any thoughts from any of the other @simple-icons/maintainers?

**Comment by ericcornelissen** [comment]
Well... that's a conundrum :sweat_smile: On their social media they also use a logo that looks like the SVG version. For the record. there are also raster versions of the logo in the press kit, from 23 March 2018, that look (at least to the eye) the same as the `.ai` version...

We may consider contacting them (_"If you have requirements beyond what is provided, please contact us."_) and ask about it? Otherwise I think I would be in favour of the SVG version as it is used more often, but it's difficult call given that the current version if from their press kit :confused:

**Comment by PeterShaggyNoble** [comment]
Sent them an email, let's see what they say. Also chanced my arm and asked if we could just use the `Y` icon.

**Comment by PeterShaggyNoble** [comment]
Egnyte have replied to say that, between the AI & the SVG, we should use the SVG so I've updated the PR based on that for now. They're going to get back to me on whether or not we're OK to use just the `Y` - path data is below so I can update from my phone later, if they say we can.

```
M22.544 8.74l-1.857-3.238c-.068-.113-.226-.159-.34-.091l-8.354 4.823L3.75 5.389a.256.256 0 0 0-.34.09l-1.9 3.238a.256.256 0 0 0 .09.34l8.332 4.89v9.804c0 .136.114.249.25.249h3.69c.136 0 .25-.113.25-.249v-9.849l8.331-4.823c.113-.068.159-.226.09-.339zm-16.03 6.566c-.068-.114-.227-.159-.363-.091l-5.57 3.306c-.113.068-.158.226-.09.362l.792 1.359c.068.113.227.158.363.09l5.57-3.306c.113-.068.158-.226.09-.362zM12.876 0l-1.834.023c-.068 0-.113.045-.113.135l.022 6.725c0 .068.046.113.136.113h1.834c.068 0 .113-.045.113-.136L13.012.136A.146.146 0 0 0 12.876 0zm10.596 18.158l-5.864-3.283c-.068-.022-.136-.022-.159.046l-.905 1.607c-.023.068-.023.136.045.159l5.864 3.283c.068.022.136.022.159-.045l.905-1.608c.046-.045.023-.136-.045-.159Z
```

**Comment by PeterShaggyNoble** [comment]
They've confirmed that the `Y` icon is _not_ an option so we're going with the SVG version of their logo.

**Pull request merged**
