### PR TITLE
Update issue labels table in Contributing Guidelines

### PR DESCRIPTION
**Pull request by ericcornelissen**
**Issue:** n/a

### Description
Updated the table of labels and their descriptions in the Contributing Guidelines. Added the `website`, `meta`, and `won't add` labels, and fixed the broken link and outdated name for the `new icon` label.

The labels `abandoned`, `Hacktoberfest`, and `invalid` are still not part of the table as I don't think they're relevant to the reader. But I could be persuaded otherwise.

This might also be a place to start the discussion on using labels for pull requests as well as issues?

### CODE REVIEW

**Comment by davidklebanoff** [comment]
Looks good to me!

I'm of the opinion that simple documentation changes such as this shouldn't even need a pull request from members of the organization. :)

As for labeling pull requests, I assume you're pro? I could go either way. We have so few open pull requests relative to issues, I don't see it helping organization of open requests. However, it may help keep closed requests more organized and would assist in searching through historic requests should you want to for some reason. With that said, I don't think I've ever had a need to do such a thing for pull requests ( but I have plenty of times for issues).

**Comment by ericcornelissen** [comment]
My motivation for labeling pull requests is indeed to keep closed pull requests organized. I've gone through historic PRs a few times but indeed not as often as issues. It would mainly make it easier to view e.g. all icon additions as a sort of changelog.

But to be fair, the effort of labeling PRs does not necessarily outway the benefits.


> I'm of the opinion that simple documentation changes such as this shouldn't even need a pull request from members of the organization.

I can see why you would say that, I'm personally of the opinion that openness towards the community is a good enough reason to use PRs for changes like this and that it is important to properly inform other maintainers of these changes (although, if you have suggestions for a different approach I'm interested in hearing them). Also, I don't think our list of PRs suffers from small PRs such as this (if that is one of your concerns).

**Comment by birjolaxew** [comment]
:+1: Good work!

I personally think that changes like this are fine if done by a single maintainer. PRs are great for transparency/documentation, so the optimal workflow in my opinion would be having changes like this be self-merged through a PR by the maintainer in question.

**Comment by davidklebanoff** [comment]
@birjolaxew @ericcornelissen 

For lack of a better place for discussing this... any opinions on adding a 'duplicate' label? This can remain unlisted like 'abandoned' and 'invalid'.

**Comment by birjolaxew** [comment]
@davidklebanoff Sure, go wild. I personally don't feel that's something we need to discuss; if you feel there's a need for it, add away. We can always remove labels later if they start becoming excessive.

**Comment by ericcornelissen** [comment]
Same @davidklebanoff, I personally feel like it is similar to 'abandoned' and 'invalid' and can therefor remain unlisted. However, if you feel it would be useful to list it you can add it 👍

**Pull request merged**
