### PR TITLE
Update Strapi icon

### LINKED ISSUE #9050: Update: Strapi Icon
### Brand Name

Strapi

### Official Resources for Icon and Color

- Strapi Brand book (logo): https://handbook.strapi.io/strapi-brand-book-2022/strapi-logo
- Link to the logo pack `svg` `png`: [download](https://assets.super.so/e7c0f16c-8bd3-4c76-8075-4c86f986e1b2/files/bda71463-8d27-4ebb-8b88-7a214176bdf5.zip)

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by adamrusted**
strapi

**Issue:** closes #9050

**Similarweb rank:** [69,958](https://www.similarweb.com/website/strapi.io/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Updated to use monogram in official brand kit - converted to monochrome using Simple Icons guidelines.

### CODE REVIEW

**Comment by service-paradis** [comment]
@adamrusted The icon is looking good to me!
I think we could add https://handbook.strapi.io/strapi-brand-book-2022/strapi-logo as guidelines and update the brand color to `#4945FF`.
It would be great if they added the monochrome version on their guidelines. Right now, the source in `simple-icons.json` is not correct... Might we use the comments permalink as source?

**Comment by adamrusted** [comment]
Tell you what, @service-paradis - should I actually use the SVG monogram available at that brand book? 🙃

**Comment by adamrusted** [comment]
Easy way to find out!
@maevalienard - sorry to bother, would you be happy with the revised treatment seen in the image at the top of this PR? I've taken the official SVG monogram and simple-icon-ified it.

**Comment by adamrusted** [comment]
Also pinging @fmerian for input on this, before we look to merge!

**Comment by fmerian** [comment]
> Also pinging @fmerian for input on this, before we look to merge!

LGTM, thanks! also ping @maevalienard for review

**Comment by maevalienard** [comment]
LGTM too :)

**Review by LitoMore — APPROVED** [review]
@fmerian @maevalienard If you still need any adjustments, please feel free to come back and contact us at any time.

**Review by service-paradis — APPROVED** [review]

**Pull request merged**
