### PR TITLE
Correct Toyota icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** #3169
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I took the logo from their brand guidelines (https://www.toyota.com/brandguidelines/logo/) since the original looked different
- I updated the source
- I updated the color according to their brand guideline
- I used Inkscape to resize and center the logo
- I used https://jakearchibald.github.io/svgomg/ to optimize

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
The new color is fine, however I'm seeing differences between the icons in the new source (black) and your version (red), that seems fitted with previous source. Could you rebuild from new source @service-paradis?

image

**Comment by service-paradis** [comment]
> The new color is fine, however I'm seeing differences between the icons in the new source (black) and your version (red), that seems fitted with previous source. Could you rebuild from new source @service-paradis?

Sure, will give it another try. Can you tell me which logo did you use for the comparison? I used [this one](https://www.toyota.com/brandguidelines/imgix/logo/logos/logos_logos_01_desktop.svg) (1st logo of the section "Primary Logo") and the difference is not the same as your comment.

**Comment by mondeja** [comment]
>  Can you tell me which logo did you use for the comparison? I used this one (1st logo of the section "Primary Logo") and the difference is not the same as your comment.

I've used the same source as yours and [this](https://www.toyota.com/brandguidelines/imgix/asset-ids/toyota-logo/assetID_toyota_logo.svg) to make sure, both showing the same difference comparing them with your version. Could you share the difference you are seeing?

**Comment by service-paradis** [comment]
> > Can you tell me which logo did you use for the comparison? I used this one (1st logo of the section "Primary Logo") and the difference is not the same as your comment.
> 
> I've used the same source as yours and [this](https://www.toyota.com/brandguidelines/imgix/asset-ids/toyota-logo/assetID_toyota_logo.svg) to make sure, both showing the same difference comparing them with your version. Could you share the difference you are seeing?

I'm probably doing something wrong... This is the comparison I got with the latest path
```
M12 3.848C5.223 3.848 0 7.298 0 12c0 4.702 5.224 8.152 12 8.152S24 16.702 24 12c0-4.702-5.223-8.152-12-8.152zm7.334 3.839c0 1.08-1.725 1.913-4.488 2.246-.26-2.58-1.005-4.279-1.963-4.913 2.948.184 6.45 1.227 6.45 2.667zM12 16.401c-.96 0-1.746-1.5-1.808-4.389.577.047 1.18.072 1.808.072.628 0 1.23-.025 1.807-.072-.061 2.89-.847 4.389-1.807 4.389zm0-6.308c-.59 0-1.155-.019-1.69-.054.261-1.728.92-3.15 1.69-3.15.77 0 1.428 1.422 1.689 3.15-.535.034-1.099.054-1.689.054zm-.882-5.075c-.956.633-1.706 2.333-1.964 4.915C6.391 9.6 4.665 8.767 4.665 7.687c0-1.44 3.504-2.49 6.453-2.669zM2.037 11.68a5.265 5.265 0 011.048-3.164c.27 1.547 2.522 2.881 5.972 3.37V12c0 3.772.879 6.203 2.087 6.97-5.107-.321-9.107-3.48-9.107-7.29zm10.823 7.29c1.207-.767 2.087-3.198 2.087-6.97v-.115c3.447-.488 5.704-1.826 5.972-3.37a5.26 5.26 0 011.049 3.165c-.004 3.81-4.008 6.969-9.109 7.29z
```
image

**Review by adamrusted — COMMENTED** [review]
Can confirm current PR matches up to [this](https://www.toyota.com/brandguidelines/imgix/logo/logos/logos_logos_01_desktop.svg) file perfectly, see below.

image

It appears that anywhere other than the badge on the cars, Toyota show the box around the 'T', should we include that?

**Review by mondeja — APPROVED** [review]
For me it's perfect now :+1: Thanks @service-paradis!

> It appears that anywhere other than the badge on the cars, Toyota show the box around the 'T', should we include that?

I would not include it because they don't prohibit the usage of their symbol alone, but anyway I'm not against the inclusion.

**Review by adamrusted — APPROVED** [review]
Let's push this icon for now then, and we can always add the square later down the line should we need it. Thanks @service-paradis 🎉

**Comment by PeterShaggyNoble** [comment]
At the time we originally added Toyota, they did require the square but, after a recent rebranding, that's no longer the case.

**Pull request merged**
