### PR TITLE
Add Autodesk

### PR DESCRIPTION
**Pull request by mondeja**
autodesk-preview

**Issue:** n/a
**Website:** https://www.autodesk.com
**Alexa Rank:** [694](https://www.alexa.com/siteinfo/autodesk.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Why did you pick the hex value? It's integrated in Autodesk logo. I've chosen the first colour of the `ac` logo gradient, the light blue at the top. Other possible colours are `#0696d7` (from [website](https://www.autodesk.com/) stylesheet), `#0b86ca` (3th colour at `ac` gradient) and `#007dc4` (last colour of the same gradient).
- The source of the logo is the [official website](https://www.autodesk.com/) header.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the PR, @mondeja :+1:

Note that they do have a monochrome version of their icon which can be seen [here](https://brand.autodesk.com/brand-elements/autodesk-logo) but, to save having to register to access the source files, [this SVG](https://damassets.autodesk.net/content/dam/autodesk/www/homepage/fy18/adsk-white.svg) can be found in the footer of their homepage. Also, from [this section](https://brand.autodesk.com/brand-elements/colors) of their brand guidelines, the colour should be your second choice above, `#0696b7`.

**Comment by mondeja** [comment]
Oh, much better. Here is the new preview:
autodesk-preview

**Comment by PeterShaggyNoble** [comment]
Thanks for updating, @mondeja and your continued efforts & patience on all your contributions.

Just one minor thing to fix here is that the SVG is `24.001` wide.

**Comment by PeterShaggyNoble** [comment]
Thanks for your work on this one, @mondeja :+1:

**Pull request merged**
