### PR TITLE
Add Leader Price icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** #6405 
**Alexa rank:** 443,428
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
svg: https://www.leaderprice.fr/repository/image/logo-lp-vec-03.svg
color: `#e50005`

### CODE REVIEW

**Comment by dirien** [comment]
Hi @simple-icons/maintainers,

just in case you cant access the svg:

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Calque_1" x="0px" y="0px" viewBox="0 0 467 497.5" style="enable-background:new 0 0 467 497.5;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#E50005;}
	.st1{fill:#21409A;}
</style>
<g>
	<path class="st0" d="M153.6,315.9h10l16.6,24.9h26.3l-19.6-28.7c10.2-4.3,16.9-12.7,16.9-25.3v-0.2c0-8.1-2.5-14.5-7.3-19.2   c-5.5-5.6-14.2-8.9-26.8-8.9h-38.9v82.2h22.8V315.9z M153.6,278.3h14.9c7.6,0,12.3,3.3,12.3,9.8v0.2c0,6-4.5,9.8-12.2,9.8h-15   V278.3z M121.7,287.7v-0.2c0-18.2-13.4-28.9-34.2-28.9H52.2v82.2H75v-23.5h11.3C106.7,317.3,121.7,307.1,121.7,287.7z M98.9,288.7   c0,6.5-4.9,10.7-13,10.7H75v-21.7h10.7c8.2,0,13.2,3.8,13.2,10.8V288.7z M239.6,258.5h-22.9v82.2h22.9V258.5z M294.2,343.3   c14.4,0,27.8-7.1,36-19l0.5-0.7l-18.5-12.7l-0.5,0.7c-4,5.8-10.5,9.2-17.4,9.2c-11.7,0-21.2-9.5-21.2-21.1   c0-11.7,9.5-21.1,21.2-21.1c7,0,13.5,3.4,17.4,9.2l0.5,0.7l18.5-12.7l-0.5-0.7c-8.2-11.9-21.6-18.9-36-18.9   c-24,0-43.6,19.6-43.6,43.6C250.6,323.7,270.1,343.3,294.2,343.3z M362.5,321.4v-13.8H402v-16.4h-39.5v-13.2h43.6v-19.4h-66.2v82.2   h66.7v-19.4H362.5z M228,497.5l129.3-129.3H98.7L228,497.5z"/>
	<path class="st1" d="M22.8,157H0v82.3h58.5v-20H22.8V157z M338.8,206.1h37.2v-16.4h-37.2v-13.2H380V157h-63.8v82.3h64.4v-19.4   h-41.9V206.1z M88.5,206.1h37.2v-16.4H88.5v-13.2h41.3V157H66v82.3h64.4v-19.4H88.5V206.1z M447.4,210.6   c10.2-4.3,16.9-12.7,16.9-25.3v-0.2c0-8.1-2.5-14.5-7.3-19.2c-5.5-5.6-14.2-8.9-26.8-8.9h-38.9v82.3h22.8v-24.9h10l16.6,24.9H467   L447.4,210.6z M441.4,186.7c0,6-4.5,9.8-12.2,9.8h-15v-19.7h14.9c7.6,0,12.3,3.3,12.3,9.8V186.7z M260.4,157h-31.7v82.3h31.3   c29.6,0,46.9-17.6,46.9-41.4v-0.2C306.8,173.9,289.8,157,260.4,157z M283.4,198.3c0,13.3-9.1,20.8-22.7,20.8h-9.3v-41.8h9.3   c13.6,0,22.7,7.6,22.7,20.8V198.3z M228,0L98.7,129.3h258.6L228,0z M168.3,157l-34.8,82.3h23.8l5.8-14.6h31.5l6,14.6h24.3   L190.1,157H168.3z M169.8,207.1l9.2-24l9.1,24H169.8z"/>
</g>
</svg>
```

image

**Comment by sachinraja** [comment]
Not sure this can be merged at the moment since the Alexa rank has fallen to 555,447. Hopefully the discussion in #6955 will resolve this.

**Comment by dirien** [comment]
@sachinraja: oh welp 😢! Yes we need to solve this! LeaderPrice is really a well established brand in France.

**Comment by jorgeamadosoria** [comment]
> @sachinraja: oh welp 😢! Yes we need to solve this! LeaderPrice is really a well established brand in France.

And Uruguay, Argentina and Brazil as well. Like, really solid.

**Comment by sachinraja** [comment]
I would say that a confirmation from two maintainers that this brand is indeed popular enough for inclusion validates it.

**Comment by jorgeamadosoria** [comment]
it's odd that SimilarWeb does not have a register for this page at all, even though it is present in so many places.
That doesn't bode well for SimilarWeb as a replacement for Alexa rank :(

I would include / keep this one as an exception due to Dirien and me vouching for its popularity (thanks @sachinraja for your support) but it strikes me as odd that it doesn't show in Similar Web.

**Comment by dirien** [comment]
So its okay to merge this? @jorgeamadosoria and @sachinraja?

**Review by sachinraja — APPROVED** [review]
I'm not able to access the website, so thanks for sharing the svg. Just reviewed and this is a perfect match

**Pull request merged**
