### PR TITLE
Add Wiz icon

### LINKED ISSUE #10612: Request: Wiz
### Brand Name

Wiz

### Website

https://wiz.io

### Popularity Metric

The Similarweb [rank](https://www.similarweb.com/website/wiz.io/) is 141,495

### Official Resources for Icon and Color

WizStar24

wiz-logo-official

color: #0254EC

### Additional Comments

There are two variants of the logo, the recognized one is the simple star, and the full-fledged
one is contains the brand name: Wiz.

### PR DESCRIPTION
**Pull request by MinnThikeTunn**
wiz (3)

**Issue:** closes #10612 

**Popularity metric:**  [~141.3k](https://www.similarweb.com/website/wiz.io/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
-  [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

I found two variants according to issues. I didn't know anything about handling two variants and didn't see anything about how I deal with logo variants in contributing guidelines. So, according to the issue creator, I choose the recognized one. I am sorry if I made some mistakes.

### CODE REVIEW

**Comment by uncenter** [comment]
Can you rebase your changes? There are a lot of extra commits here.

**Comment by MinnThikeTunn** [comment]
> Can you rebase your changes? There are a lot of extra commits here.

Yes,I will.

**Comment by uncenter** [comment]
Still looks like there is an extra commit.. seems to be empty but unrelated nonetheless.

**Comment by MinnThikeTunn** [comment]
> Still looks like there is an extra commit.. seems to be empty but unrelated nonetheless.

My bad. I will fix this.

**Comment by MinnThikeTunn** [comment]
I accidentally deleted my branch. Sorry about that. I will come up with another pull request.

**Pull request closed without merging**
