### PR TITLE
Amazon AWS to Amazon Web Services

### PR DESCRIPTION
**Pull request by readboy8**
### Description
Change Amazon AWS to Amazon Web Services
Change amazonaws.svg to amazonwebservices.svg

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for this @readboy8 - could you also delete `amazonaws.svg` from this branch? That's why it's erroring out :)

**Comment by readboy8** [comment]
I deleted amazonaws.svg, so it should be good now.

**Review by adamrusted — APPROVED** [review]
Amazing, thank you @readboy8!
I won't merge this yet - as it's a breaking change - so please don't delete this branch!

**Comment by PyvesB** [comment]
The [release notes](https://github.com/simple-icons/simple-icons/releases/tag/12.0.0) state that `Amazon Web Services` was renamed to `Amazon Web Services`, the former was probably meant to be `Amazon AWS`. :)

**Pull request merged**
