### PR TITLE
Update Adobe Audition

### PR DESCRIPTION
**Pull request by MetLee**
image

**Issue:** #3369 
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Where did you source this one, @MetLee, as I don't see it on Audition's product page? I did find [this one](https://helpx.adobe.com/content/dam/help/mnemonics/au_cc_app_RGB.svg) in the header of [this page](https://helpx.adobe.com/audition/using/whats-new.html) but it differs in size to all the others.

**Comment by MetLee** [comment]
> Where did you source this one, @MetLee, as I don't see it on Audition's product page? I did find [this one](https://helpx.adobe.com/content/dam/help/mnemonics/au_cc_app_RGB.svg) in the header of [this page](https://helpx.adobe.com/audition/using/whats-new.html) but it differs in size to all the others.

I found this icon on https://www.adobe.com/content/dam/cc/icons/audition.svg .
You can find all the logo on `https://www.adobe.com/content/dam/cc/icons/{BRANDNAME}.svg`

**Comment by PeterShaggyNoble** [comment]
Yup, found that one too, @MetLee, and your SVG lines up perfectly with it. We just need to find a source URL that includes that particular file.

**Comment by PeterShaggyNoble** [comment]
https://www.adobe.com/ie/creativecloud/plans.html features that version of the logo **but** every page of the Audition sub-site that has a vector version on it use the inconsistent version I linked above. Happy to run with what's here for the sake of consistency but would like to hear from the other @simple-icons/maintainers, too.

**Comment by MetLee** [comment]
I got it: https://www.adobe.com/ie/creativecloud/video.html
image

**Comment by PeterShaggyNoble** [comment]
Nice find - 2 sources using the same file definitely makes a better case for it. If you update the source URL in this PR to either of the 2 then this one is ready to go.

**Pull request merged**
