### PR TITLE
updated icon for Teespring

### PR DESCRIPTION
**Pull request by jorgeamadosoria**
teespring

**Issue:** #6533

### CODE REVIEW

**Comment by service-paradis** [comment]
FYI @jorgeamadosoria, you can assign yourself on issue you want to take, but dont assign yourself on your own PR. You can assign yourself on PR you plan to review.

**Comment by jorgeamadosoria** [comment]
> FYI @jorgeamadosoria, you can assign yourself on issue you want to take, but dont assign yourself on your own PR. You can assign yourself on PR you plan to review.

why is this in discussion, and what's left to merge it @service-paradis ?

**Comment by service-paradis** [comment]
> > FYI @jorgeamadosoria, you can assign yourself on issue you want to take, but dont assign yourself on your own PR. You can assign yourself on PR you plan to review.

> why is this in discussion

Because I find it misleading. As you can see [in "Icon Review" section](https://github.com/orgs/simple-icons/teams/maintainers), we were using assignment in PR to know if someone planned to review a PR. When I'm looking at the priority list to review, I often skip PRs that are assigned to someone.

> what's left to merge it @service-paradis ?

Did nt reviewed it yet.

**Review by adamrusted — APPROVED** [review]
LGTM! Bear in mind that the homepage of Teespring now states that they are known as 'Spring', which we currently have in the project. Will merge these changes, but we may need to have a discussion about removing 'Teespring' in the next major release.

**Pull request merged**
