### PR TITLE
Add Metro

### LINKED ISSUE #3057: Add Metro bundler
**Name:** Metro bundler
**Website:** https://facebook.github.io/metro/
**Official resources for icon and color:** https://facebook.github.io/metro/img/metro.svg color: `#ef4242`

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Metro

**Issue:** Closes #3057

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon & colour from [this SVG](https://facebook.github.io/metro/img/metro.svg). There were a number of imperfections in the cut-out which had to be cleaned up.

### CODE REVIEW

**Comment by runxel** [comment]
I think this one is one of the possible name collisions... so I'm a bit hesitant to merge this in right now.

**Comment by PeterShaggyNoble** [comment]
A quick solution would be to call it "Facebook Metro", @runxel, but I don't know that that would be entirely accurate. Plus it would set a precedent going forward. Any of the other @simple-icons/maintainers have a suggestion of how to resolve this? Do we just go on a "first come, first served" basis and leave it as-is, addressing any potential name clash with a future PR in _that_ PR?

**Comment by fbernhart** [comment]
Their Twitter name is "Metro Bundler". https://mobile.twitter.com/MetroBundler And there are two posts back from 2017 where they introduced themselves as well as "Metro Bundler". Just to point out an alternative.

Anyway, I would be in favour of "first come, first serve", as this is the way we've handled requests up to now.

**Comment by adamrusted** [comment]
@PeterShaggyNoble I'd be in favour of calling it `Metro Bundler` if that's how they've referred to themselves?*Should* be specific enough then to prevent a conflict in future.

**Comment by PeterShaggyNoble** [comment]
It looks to me like "Metro Bundler" might have been its original name and that "Bundler" has since been dropped as, other than the Twitter username, I can't find anywhere else that they refer to themselves with that name.

**Comment by adamrusted** [comment]
> All mention of "Bundler" was removed from their GH repo in [this commit](https://github.com/facebook/metro/commit/04820d14e9626efd188a0ee530aec614624a1c43) well over a year ago.

In that case, we'll have to follow suit and just call this one `Metro`. Given that a duplicate hasn't arisen since June last year - shall we merge this one, and hopefully resolve the duplication issue before v5.0.0?

**Comment by PeterShaggyNoble** [comment]
Weird! 🤔 Dunno how that happened, @adamrusted, my local copy was fine. Just pushed an update with the path from that file.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @PeterShaggyNoble 💯

**Pull request merged**
