### PR TITLE
Adding aparat.com icon

### PR DESCRIPTION
**Pull request by farshad-sadri**
Aparat is a popular Iranian Video sharing and streaming service and due to limitations on YouTube in Iran, it became popular. I have prepared the SVG according to your guidelines.
I also updated _data/simple-icons.json

Thanks,

### CODE REVIEW

**Comment by davidklebanoff** [comment]
Hi @farshad-sadri, this pull request is showing 17 commits, but 0 files changed...

**Comment by farshad-sadri** [comment]
Sorry, I'm a designer, I forked simple icons and then made changes and came back for a pull request as GitHub suggested. 
Though changes I made was:
https://github.com/farshad-sadri/simple-icons/blob/develop/_data/simple-icons.json (Lines 103-107)
https://github.com/farshad-sadri/simple-icons/blob/develop/icons/aparat.svg

Sorry, 
:)

**Comment by davidklebanoff** [comment]
No worries @farshad-sadri, it's a learning process. I'm happy to see you contribute!

Looking at the files you linked, the changes look good to me! The only issue is the pull-request you submitted does not have these changes included.  So the way I see it, you have two options.

1. Fix this pull request to include the changes. You may have to read some Git or github documentation to learn the proper process.

2. I can go ahead and close this pull request and commit the files myself on your behalf. In this approach you won't be listed as a contributor and won't be given "credit" through git history or github because I would have committed the work on your behalf. So it's certainly not ideal, but I'm happy to help.

I'll let you decide how you would like to proceed.

**Comment by farshad-sadri** [comment]
Thanks a lot @davidklebanoff . It was very helpful. I think I go with the learning curve as I am interested in your project and would like to contribute.

**Comment by birjolaxew** [comment]
@farshad-sadri I think the main problem here is that you're attempting to merge 'simple-icons/simple-icons@master` into `simple-icons/simple-icons@develop`. What you actually want to do is merge `farshad-sadri/simple-icons@develop` into `simple-icons/simple-icons@develop`.

You can choose this when creating the pull request. Click the "compare across forks." link at the top, and change the head fork to `farshad-sadri/simple-icons`.

**Comment by davidklebanoff** [comment]
I'm going to go ahead and close this pull request. Feel free to open a new one with the aparat icons in the future.

**Pull request closed without merging**
