### PR TITLE
Allow skipping release note with `skip release note` label

### PR DESCRIPTION
**Pull request by LitoMore**
Related to https://github.com/simple-icons/simple-icons/pull/9300#issuecomment-1688461364.

Related commit: https://github.com/LitoMore/simple-icons-release-action/commit/1a0c7bb3a4a694ba3877d92e340c01a7a56cc730

### CODE REVIEW

**Comment by adamrusted** [comment]
This looks good to me. Any reason we're using your version of the release action instead of the one managed by the org?

**Comment by LitoMore** [comment]
@adamrusted See this https://github.com/simple-icons/simple-icons/issues/8734#is.suecomment-1578410818

**Review by adamrusted — APPROVED** [review]
Happy to merge this in, given all we're discussing here is the version number. Would be good to get back to the org-managed release action at some point, but not today!

**Comment by mondeja** [comment]
🤔 This looks strange to me. I though that all icons with data updated should be marked as updated icons after a "Icon data updated" header in release notes (see [9.8.0](https://github.com/simple-icons/simple-icons/releases/tag/9.8.0)). Why is not the case for the icons in this letters review? @LitoMore @adamrusted

**Comment by LitoMore** [comment]
@mondeja They are only guidelines updates.

Here is my comment: https://github.com/simple-icons/simple-icons/pull/9300#issuecomment-1688461364

**Comment by mondeja** [comment]
But are icon data updates, right? What should be considered as icon data updates instead?

**Comment by adamrusted** [comment]
This is potentially where we need to get a bit more granular with the big reviews.

Just removing slashes from URLs? Great, skip the release note. Nobody wants potentially 1000+ icons in that list because you've reformatted the exact same URL.

Make fundamental changes to the source and/or data? That's gotta be in the release note.

**Pull request merged**
