### PR TITLE
Updated Fiverr

### PR DESCRIPTION
**Pull request by adamrusted**
fiverr

**Issue:** #3169
**Alexa rank:** [178](https://www.fiverr.com/)

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> Not Necessary
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Updated to match Fiverr's [new branding](https://twitter.com/fiverr/status/1303722784288387072).

### CODE REVIEW

**Comment by mondeja** [comment]
What exact source have you used for this @adamrusted?

**Comment by adamrusted** [comment]
The updated logos are available in the [press kit](https://www.fiverr.com/press-kit) which I believe is the already linked source.

**Comment by mondeja** [comment]
Sorry, but my version optimized does not coincide with yours. What is the exact source that you've used? The SVG embedded in the front page, EPS green logo in press-kit, SVG green logo in press-kit, EPS white logo or SVG white? Just to make sure...

**Comment by adamrusted** [comment]
No worries! I'd used the SVG on the front page - but I'll compare on my end, and rebuild if need be.

**Comment by adamrusted** [comment]
Rebuilt with precision of 3 using [this version](https://assetsv2.fiverrcdn.com/assets/v2_press_room/downloadables/Fiverr_white-2ef7eafe0ae7a864ea0c70e21e842897.svg) of the logo.

**Review by mondeja — APPROVED** [review]
Now it fits correctly :+1:

It seems that the icon they use for the front page is slightly different to those in press kit. In these cases we use press kits or brand guidelines.

Thank you for this update @adamrusted :100:

**Pull request merged**
