### PR TITLE
Add SUSE

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
SUSE

**Issue:** n/a
**Alexa rank:** [~73.9k](https://www.alexa.com/siteinfo/suse.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
~Should we instead use the hex from the logo, which is `#30BA78`, as it appears on their social channels exactly the same. Also looks like the PR version (red) is [missing one of the rings from the eye path](https://user-images.githubusercontent.com/1830867/108603303-2b658580-739f-11eb-9eee-4c9b87c000c0.png), if you use the SVG from their website header as the source. Any chance you could take another look @PeterShaggyNoble?~

Ignore me - I just went off the SVG on their homepage, as opposed to their brand portal. Let me compare your PR against the icon available there.

**Comment by PeterShaggyNoble** [comment]
We generally tend to favour brand colour over icon/logo colour so I'm going to ping the other @simple-icons/maintainers for their feedback as to the correct choice here.

**Comment by ericcornelissen** [comment]
I agree with @PeterShaggyNoble's choice here.

**Comment by adamrusted** [comment]
Will look to merge this at the end of the day, unless any other @simple-icons/maintainers want to chip in?

**Review by adamrusted — APPROVED** [review]
Merging due to lack of objection! 😅

**Pull request merged**
