### PR TITLE
Add Volkswagen

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Volkswagen
**Issue:** #2059

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon was found in the source of https://www.volkswagen.ie/. Colour `#001e50` was taken from the stylesheet of https://www.volkswagen-newsroom.com/ but other options could be `#151f5d` (used in [this image](https://uploads.volkswagen-newsroom.com/system/production/media/30063/images/9d92292f97a9922c237f6de853e18325de79e6a3/DB2019AL01916_overfull.jpg?1568044218)) and `#1d1f20` (Found in the same location as the icon).

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I should have pointed out that the image I lifted the `#151f5d` colour from was found in [this press release](https://www.volkswagen-newsroom.com/en/press-releases/volkswagen-unveils-new-brand-design-and-logo-5337) about their rebranding.

**Comment by PeterShaggyNoble** [comment]
Thanks, @runxel. I think I agree with you on that colour choice purely based on them using it in a splash image announcing their new branding. Let's see what the other @simple-icons/maintainers think, though, before update it.

**Comment by birjolaxew** [comment]
Ye I think I agree with `#151f5d`. Once you've updated that you can go ahead and merge @PeterShaggyNoble - everything else looks good to me!

**Comment by PeterShaggyNoble** [comment]
Thanks, @birjolaxew. Colour updated; will merge once checks have completed.

**Pull request merged**
