### PR TITLE
Added WhatsApp Business Icon

### LINKED ISSUE #8024: Missing WhatsApp Business icon
### Brand Name

WhatsApp Business

### Website

https://business.whatsapp.com/

### Popularity Metric

The Similarweb rank is 142. See https://www.similarweb.com/app/google-play/com.whatsapp.w4b/statistics/

### Official Resources for Icon and Color

Icon: https://play-lh.googleusercontent.com/ebs6ftYUkOKlDY0M174OpvargwbDyHUVAnO_G5aE0dL5GBQKCtfh3adN5H3ZMThXogDi=w480-h960

### Additional Comments

The official website of WhatsApp Business doesn't show the actual logo, for the actual logo, please refer to https://play.google.com/store/apps/details?id=com.whatsapp.w4b

### Contributing

Yes

### PR DESCRIPTION
**Pull request by umairkhalid-devsinc**
whatsappbusiness

**Issue:** closes #8024
** Similarweb rank: 29,022

**Similarweb rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by LitoMore** [comment]
@umairkhalid-devsinc Can you fix those errors?

**Review by LitoMore — CHANGES_REQUESTED** [review]

**Comment by umairkhalid-devsinc** [comment]
@LitoMore ,.Yes, just one lint error remaining, i m fixing it and will send the commit, possibly today

**Comment by umairkhalid-devsinc** [comment]
@LitoMore all lint error are fixed. please review

**Comment by umairkhalid-devsinc** [comment]
@LitoMore , let me know, if further changes are required

**Comment by LitoMore** [comment]
CleanShot 2022-11-19 at 22 03 50@2x

@umairkhalid-devsinc I see some differences. Looks the icon from Iconfinder is not official.

We should find a resource that can fit the original one.

**Comment by umairkhalid-devsinc** [comment]
@LitoMore how you find the difference?

**Comment by adamrusted** [comment]
Closing in favour of #8875.

**Pull request closed without merging**
