### PR TITLE
Add Lidl icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** https://github.com/simple-icons/simple-icons/issues/5852
**Alexa rank:** 5,447
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
No external ressources available, i work for the Schwarz Group (parent holding of the brand Lidl) and the icon and main color is according internal guidelines.

You can check the svg on the official homepage -> https://www.lidl.de/

### CODE REVIEW

**Comment by dirien** [comment]
hi @adamrusted, 

i created a new PR the old one (#5854) was not rebase-able.

The white line between the I and the D is really intentional. Its not so obvious the yellow background.

Source: https://www.lidl.de/static/assets/c6855ba1-a17c-468f-b8b0-09fdab67dea7.svg

I hope it meets the expectiations...

**Comment by ericcornelissen** [comment]
> i created a new PR the old one (#5854) was not rebase-able.

No problem, this works too :slightly_smiling_face: 


> I hope it meets the expectiations...

Again, as was already said in the other Pull Request, we will follow your treatment if you sign off on it. However, I noticed one [minor difference](https://user-images.githubusercontent.com/3742559/127745483-fa4d99ce-dff4-4777-aacc-8628977e17c1.png) between [the source](https://www.lidl.de/static/assets/c6855ba1-a17c-468f-b8b0-09fdab67dea7.svg) and the SVG in this Pull Request at the bottom of the circle . This is due to a (seemingly) extra point there, if you want I think it would be nice to remove one of the points and make sure the circle still lines up.

**Comment by dirien** [comment]
I have no idea how to do this.... I use inkspace. Could you help me on this maybe?

**Comment by ericcornelissen** [comment]
> I have no idea how to do this.... I use inkspace. Could you help me on this maybe?

I'll give it a try in the next few day 👍

**Comment by ericcornelissen** [comment]
The path below should do the trick :+1: But, now that I created the path we will need another @simple-icons/maintainers to review this.

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Lidl</title><path d="M0 0v24h24V0zm.209.209h23.582v23.582H.209zm11.789.625C5.83.834.83 5.834.83 12.002c0 6.168 5 11.168 11.168 11.168 6.167 0 11.167-5 11.168-11.166C23.165 5.837 18.166.837 12 .834zm.002.709c5.777 0 10.46 4.682 10.46 10.459v.004c-.004 5.773-4.686 10.452-10.46 10.453-5.777 0-10.46-4.68-10.46-10.457C1.54 6.225 6.222 1.543 12 1.543zM9.229 7.85c-.645 0-1.166.521-1.166 1.166v.004c0 1.044 1.261 1.567 1.999.829.738-.738.215-2-.829-1.999zM2.73 10.059v.71h.551v2.465h-.55v.713h4.644v-.65l.537-.54 1.486 1.491-.55.547.357.36 2.973-2.977v-.713l-.826.83-1.848-1.848-2.129 2.133v-.576l-1.904 1.06V10.77h.549v-.711zm8.905 0v.71h.549v2.465h-.555v.713h3.129c2.325 0 2.355-3.888.008-3.888zm4.963 0v.71h.55v2.465h-.55v.713h4.648v-1.943l-1.906 1.06V10.77h.55v-.711zm-2.43 1.21h.133c.687 0 .685 1.461.023 1.461h-.156v-1.46z"/></svg>
```

**Comment by dirien** [comment]
@ericcornelissen thanks, i update the PR with your svg. So asking a fellow maintainer to review the changes of @ericcornelissen. 😄

**Review by service-paradis — APPROVED** [review]
LGTM 💯 Thank you @ericcornelissen and @dirien!

**Pull request merged**
