### PR TITLE
Add Amazon Pay

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Amazon Pay

**Issue:** Templarian/MaterialDesign#5612
**Alexa rank:** n/a

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon from [this SVG](https://m.media-amazon.com/images/G/01/EPSMarketingJRubyWebsite/assets/mindstorms/amazonpay-secondary-logo-rgb_clr._CB1560911315_.svg) in source footer. This treatment does seem to be permissible under [these guidelines](https://developer.amazon.com/docs/amazon-pay-automatic/style-guidelines.html) but, for our purposes, we may need to consider [the full logo](https://m.media-amazon.com/images/G/01/EPSMarketingJRubyWebsite/assets/mindstorms/amazonpay-logo-rgb_clr._CB1560911315_.svg):

### CODE REVIEW

**Comment by adamrusted** [comment]
Given our current line-up of Amazon icons, I would suggest the `pay` variant, and maybe look at updating `amazonprime.svg` to match the rest of them - but what do other @simple-icons/maintainers think?

image

**Comment by fbernhart** [comment]
I prefer as well the `pay` variant. They use it as well on their social media presence: [Twitter](https://twitter.com/amazonpay?ld=NSGoogle), [YouTube](https://www.youtube.com/user/amazonpayments?ld=NSGoogle), [Facebook](https://www.facebook.com/AmazonPay/?ld=NSGoogle), [Instagram](https://www.instagram.com/amazonpay/?ld=NSGoogle), [LinkedIn](https://www.linkedin.com/showcase/amazon-pay/)

@adamrusted We do have both, `Prime` and `Amazon Prime`. --> https://simpleicons.org/?q=prime
See #3245 and #3010 for details.

**Comment by adamrusted** [comment]
There's some style guidelines available [here](https://pay.amazon.com/integration) which seem to suggest we can only use the full wordmark variation.

**Comment by PeterShaggyNoble** [comment]
Do you mean the PDF in [this zip](https://m.media-amazon.com/images/G/01/EPSMarketingJRubyWebsite/2019/marketingguides/Marketing_tools_EN.zip?ld=NSGoogle), @adamrusted? That looks to be specifically for merchants and makes no explicit mention of not using the "pay" version. Anyway, when there's a contradiction between guidelines or lack of clarity - as there so very often is with Amazon - then I think we just go with what best suits our purposes.

**Comment by adamrusted** [comment]
Happy to go with this PR if other @simple-icons/maintainers are happy with it!

**Review by service-paradis — APPROVED** [review]
Merging it 😃 🤑

**Pull request merged**
