### PR TITLE
Add/AutoHotkey

### PR DESCRIPTION
**Pull request by bBSempai**
autohotkey

**Issue:** #3855
**Alexa rank:** [28.5k](https://www.alexa.com/siteinfo/autohotkey.com)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Before reviewing, I'm going to ping @Lexikos for their feedback to see if they're happy with this treatment and colour choice.

**Comment by bBSempai** [comment]
Are we still waiting 😪

**Comment by PeterShaggyNoble** [comment]
@bBSempai, we usually [give people 14 days to reply](https://github.com/simple-icons/simple-icons/issues/4461#issuecomment-759387848) before proceeding.

**Comment by PeterShaggyNoble** [comment]
Guess we can go ahead and review this now. @bBSempai, to allow us to do an accurate comparison, did you base your SVG off any particular image (vector or raster) or is it an entirely original interpretation?

**Comment by bBSempai** [comment]
I made the svg taking into account the interpretations made my @adamrusted providing the icon on the AHK [Facebook page](https://www.facebook.com/AutoHotkey/photos/a.455934534445306/998365490202205/) and @fbernhart who suggested to go with that idea which is all mentioned in the issue #3855 

image

**Comment by fbernhart** [comment]
@bBSempai Reviewing and approving this icon isn't easy as it's more or less an interpretation. So I wouldn't be too strict.

But there are still 1-2 things that I'd be in favour of changing. Here is a comparison between your version (red) and a quick mock-up that I've created of [this SVG](https://www.autohotkey.com/static/ahk_logo_no_text.svg) (black):

image

- It seems like you've scaled the key to make it quadratic (24 x 24px). While the original key has a width to height of 24px to 22.984px. We're always trying to keep the width/height ratio of the original icons.

- It as well seems like your AHK letters don't really fit. For my version I've taken the letters, kept their size, centered the H and tried to match the distance between the A and H as well as H and K according to [this image](https://www.facebook.com/AutoHotkey/photos/a.455934534445306/998365490202205/).


If you want, you can directly use and push my SVG path instead:

```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>AutoHotkey icon</title><path d="M20.514.508V.51H1.803C1.053.51.079 1.135 0 2.27v17.133h.002v2.325c.08 1.136 1.05 1.763 1.8 1.763h1.505l.002-.002h18.869c1.256-.053 1.766-1.066 1.822-1.699v-3.023h-.002V2.209c-.056-.633-.567-1.648-1.824-1.701h-1.66zM3.412 1.623h17.154c.898 0 1.618.72 1.618 1.617v16.64c0 .898-.72 1.62-1.618 1.62H3.412a1.616 1.616 0 0 1-1.619-1.62V3.24c0-.897.722-1.617 1.62-1.617zm3.315 12.412l-1.895 5.037h.703l.526-1.467h2.02l.497 1.467h.744l-1.824-5.037h-.771zm8.43.008v5.037h.679v-1.767l.793-.758 1.76 2.525h.884l-2.154-3.002 2.098-2.035h-.94l-2.441 2.441v-2.441h-.68zm-5.153.027v5.037h.682v-2.351h2.628v2.351h.682V14.07h-.682v2.084h-2.628V14.07h-.682zm-2.926.717h.014l.742 2.217H6.271l.807-2.217z"/></svg>
```

**Comment by bBSempai** [comment]
You're right! Damn I feel so dumb realising that 🤦🏻. And yes my letters were wrong my bad. Thank you. Here is the final preview with your svg.

simpleicons

**Comment by PeterShaggyNoble** [comment]
As an original interpretation and a manual vectorisation, I think this is good enough to merge now. If someone can improve upon it or source an official vector interpretation or can suggest a better choice of colour we can update it in the future.

Thanks for your efforts on this one, @bBSempai and for your assistance @fbernhart 👍🏻

**Pull request merged**
