### PR TITLE
Add Supermicro

### LINKED ISSUE #3474: Request: Supermicro icon
These guys are a major global server and motherboard company.

**Name:** Supermicro
**Website:** supermicro.com
**Alexa rank:** 29,589

**Official resources for icon and color:**

- [Corporate Brand Style Guide](https://www.supermicro.com/manuals/SUPERMICRO_Logo_Guidelines.pdf)

### PR DESCRIPTION
**Pull request by bmreading**
**Issue:** Add Supermicro
**Alexa rank:** 35,568

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
This commit resolves #3474

### CODE REVIEW

**Comment by fbernhart** [comment]
@bmreading Congratulations to your first pull request! 🥳 

Reviewing your PR, I assume that you've extracted the logo from the brand guidelines. It seems like this logo might be a bit outdated and in my opinion we should go for the most recent one, which is probably the one in their website header. [Direct link](https://www.supermicro.com/sites/default/files/Super_Micro_Computer_Logo.svg)

Below you can see your PR (reddish) overlayed on top of the logo that can be found in the header of their website (blue). Especially around the (R) there seem to be quite some differences. 

image



**BUT** before proceeding, I'd like to quickly discuss the following sentence that can be found in [their brand guidelines](https://www.supermicro.com/manuals/SUPERMICRO_Logo_Guidelines.pdf):
> The Supermicro logo is a registered trademark of Super Micro Computer, Inc. Third Party Usage is prohibited without authorized written consent

@simple-icons/maintainers seems like we can't add this one (without getting an OK from Supermicro beforehand). Am I right?

**Comment by bmreading** [comment]
@fbernhart I salute you for your attention to detail. You'll find that Supermicro is pretty inconsistent with their logos, and their stuff has small differences all over the place including their packaging, promotional materials, etc. I did use the brand guidelines for the basis of the file, as I feel like that would be the most authoritative.

In regards to the trademark, this seems to be a standard sort of statement regarding the fact that it is registered with the U.S. Patent & Trademark Office, which I'd imagine would probably apply to a large amount of logos in this project. I'm not an attorney, but I believe this is highly-dependent upon the usage of the trademark. The fact that the project is not attempting to sell or market products under the Supermicro name is a large factor. Anyone please feel free to correct me if I'm wrong.

**Comment by adamrusted** [comment]
Just looking at this one, given the poor quality of the homepage icon (see the issues with the outline of the ®, I would be inclined to stick with the brand guidelines version. As mentioned by @fbernhart though I think we should wait for the addition of the `disclaimer.md` file mentioned in #4629 before we add this one, just to be safe on the trademark issues.

**Comment by adamrusted** [comment]
@bmreading, just returning to this. In readiness for our disclaimer, which should be included by v5 of the package, would you be able to get in touch with SuperMicro and ask about it's inclusion in the package?

**Comment by bmreading** [comment]
Hey @adamrusted, I will put it on my list of things to do for this upcoming week. When is the v5 release scheduled?

**Comment by bmreading** [comment]
@adamrusted Is there any boilerplate language that we can send for them to ask for permission? If not, maybe that's something that we would want to do? Basically, my concern is that we need to get them to agree to the proper language, otherwise there's not much point. I've done this sort of thing to satisfy the requirements of Creative Commons licensing on projects like the Wikimedia Commons, but I'd imagine this is quite different.

**Comment by adamrusted** [comment]
> @adamrusted Is there any boilerplate language that we can send for them to ask for permission? If not, maybe that's something that we would want to do?

No boilerplate as such, I just explain what the project is, and link to the Issue / PR as well as contribution guidelines. I agree it's something we should look at having a template for such communications. 

The README and CONTRIBUTING documents should contain the relevant details for most people, and if they ask something you're not sure on - we can always help here!

**Comment by adamrusted** [comment]
No longer pending, following the inclusion of the `DISCLAIMER.md`. Just awaiting feedback from any discussions @bmreading has been able to have.

**Comment by ericcornelissen** [comment]
Pinging @bmreading again to see if there's been any response from Supermicro yet?

If not, any opinions from other @simple-icons/maintainers on including this regardless given [our disclaimer](https://github.com/simple-icons/simple-icons/blob/develop/DISCLAIMER.md) - I'd personally say this is safe to add given precedence set by other included brands.

**Comment by bmreading** [comment]
> Pinging @bmreading again to see if there's been any response from Supermicro yet?

@ericcornelissen, No response from Supermicro as of right now. Not sure how much time we should give them since I didn't get around to sending them anything until about a week ago.

**Comment by ericcornelissen** [comment]
Thanks for the update @bmreading - in that case I would say we should wait until at least 1 month after you send the email. If there's no response by then I think we can merge this regardless provided there's consensus amongst the (active) @simple-icons/maintainers to do so.

**Comment by jorgeamadosoria** [comment]
Seeing as every contributor associated with this issue has moved on from the project and / or is inactive, I'm taking over this PR.
- The disclaimer referenced by @adamrusted has been added and the rules regarding trademarked icons are clear. I think this is not an obstacle to include the icon.
- I agree with @adamrusted in that the brand guidelines icon is better than the header one, specially since they are the official source for this.
- Since efforts have been made to contact Supermicro with no response, and I agree with @bmreading that their disclaimer is boilerplate, I think we are in the clear.
- I think we can add it. I will check it and fix it if necessary, and add it appropriately.

**Comment by bmreading** [comment]
@jorgeamadosoria Thanks for being proactive, and picking this back up.

**Comment by jorgeamadosoria** [comment]
Checked the icon, removed collinear segments, updated to the current standard, and merged. @bmreading thank you for your patience seeing this through!

**Pull request merged**
