### PR TITLE
Request: Fueler

### LINKED ISSUE #9977: Request: Fueler
### Brand Name

Fueler

### Website

https://fueler.io/

### Popularity Metric

The Similar Web ranking is #343495; 
https://www.similarweb.com/website/fueler.io/#overview

### Official Resources for Icon and Color

None

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by namrata18s**
**Issue:** closes #9977 
**Similarweb rank:**

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Colour from [website](https://fueler.io) stylesheet. 

<details>
<summary>Steps taken to process .svg (expand)</summary>

I took the logo from website-header
I used Inkspace for processing:
resized canvas appropriately, updating the viewport to 0 0 24 24
resized content appropriately
centered content horizontally and vertically
converted to monochromatic
I exported from Inkscape with the option 'optimised .svg'
I used npx svgo to further optimise
I annotated the file
I ran the lint task to check for errors -> 
icon-size and icon-centered
I adjusted the logo accurately to the canvas for icon-size
I used npx svgo -p 2 and re-ran lint task -> lint succeeded

</details>

### CODE REVIEW

**Comment by namrata18s** [comment]
hi @PratyushJayachandran , I have updated the svg file could you please take a look into it .

**Comment by namrata18s** [comment]
@PratyushJayachandran  Did you get a chance to look at fueler svg . Does it have still same issue?

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran Did you get a chance to look at fueler svg . Does it have still same issue?

I'll do by next week

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
Thanks for the contribution & updates, @namrata18s 👍🏻 

However, your SVG has now been horizontally stretched. It should measure 24dp in height while retaining the same proportionate width (~23.040dp in this case) and be aligned centrally on the canvas. When I resize & realign your version to match the original I'm also seeing a few minor differences, which can likely be resolved by increasing the precision by 1 decimal place.

**Comment by namrata18s** [comment]
Hi @PeterShaggyNoble, you mean setting the precision to 1 while running the SVGO? I was wondering wouldn't the lint run fail in this case?

**Comment by PeterShaggyNoble** [comment]
No, our icons can have a maximum precision of 5 decimal places, so you can try increasing by 1 place in your optimisation process until you get to a point where you can't see a difference between your version and the original. Without trying it myself, I'd say this one will need a precision of 3, but we _might_ get away with 2.

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran Did you get a chance to look at fueler svg . Does it have still same issue?

As @PeterShaggyNoble mentioned the contributed icon is not retaining the dimension ratio of the original icon. Please scale proportionally. Only one of the dimensions(vertical in this case) needs to be 24px.

[See comparison here](https://github.com/simple-icons/simple-icons/assets/35000807/003c3bb9-004b-46c8-ae3c-9501bdba721c)

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @namrata18s?

**Review by PratyushJayachandran — APPROVED** [review]
Not perfect but close enough in my opinion
image

**Comment by PeterShaggyNoble** [comment]
I'm _must_ be looking at the wrong source file. When I resize the one in the header to 24dp in height, it's coming in at 23.04dp in width, whereas Adam's is 23.05 wide 🤔

**Review by PratyushJayachandran — APPROVED** [review]
Thank you for starting the contribution @namrata18s!
And special thanks to @adamrusted and @PeterShaggyNoble for finishing it up :tada

**Pull request merged**
