### PR TITLE
Use lychee instead of markdown-link-check on CI

### PR DESCRIPTION
**Pull request by mondeja**
Just use lychee instead of markdown-link-check on CI. See a comparsion between both tools: https://github.com/lycheeverse/lychee?tab=readme-ov-file#features

### CODE REVIEW

**Comment by uncenter** [comment]
Sweet! Love lychee, used it for #11901. Does this just check our docs for broken links?

**Comment by mondeja** [comment]
Yes, only for changed documentation files. In `develop` branch exits always with code 0 but still creates a report. Feel free to open other PRs to create reports of possible positive broken links and run on CI at releases to create reports, that would make the work that you've done in #11901 much more easy.

The configuration could eventually bypass some links that became broken if no editions have been made on files, but I think that's ok for now to not bother us so much.

**Comment by mondeja** [comment]
Yes, only for changed documentation files. In `develop` branch exits always with code 0 but still creates a report. The configuration could eventually bypass some links that became broken if no editions have been made on files, but I think that's ok for now to not bother us so much.

Feel free to open other PRs to create reports of possible positive broken links and run on CI at releases to create reports, that would make the work that you've done in #11901 much more easy.

**Review by LitoMore — APPROVED** [review]
Looks good.

**Comment by uncenter** [comment]
I considered that, but also note that only half of those reports were real - many if not most were false positives. Just seems too unreliable to fully automate :/

**Pull request merged**
