### PR TITLE
Add SiFive

### LINKED ISSUE #8838: Add SiFive
### Brand Name

SiFive

### Website

https://www.sifive.com

### Popularity Metric

~~The Similarweb rank is 700,735.~~ The rank has gone up to 353,417.
See https://www.similarweb.com/website/sifive.com

SiFive, Inc. is a fabless semiconductor company and provider of commercial RISC-V processor IP and silicon chips based on the RISC-V instruction set architecture (ISA). SiFive is the first company to produce a chip that implements the RISC-V ISA.

### Official Resources for Icon and Color

SVG: Taken from website header
Color: `#252323` taken from logo

### Additional Comments

~~I realize that the similarweb rank is beyond the threshold but~~ it is an important company in the embedded systems space.
https://en.wikipedia.org/wiki/SiFive

### Contributing

Yes

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
sifive

**Issue:** closes #8838 

The Similarweb rank is 700,735. See https://www.similarweb.com/website/sifive.com

SiFive, Inc. is a fabless semiconductor company and provider of commercial RISC-V processor IP and silicon chips based on the RISC-V instruction set architecture (ISA). SiFive is the first company to produce a chip that implements the RISC-V ISA.

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
svg: Taken from website header
color: `#252323` taken from logo

### CODE REVIEW

**Comment by LitoMore** [comment]
Please don't merge `master` to our `develop` branch. I just fixed it for you.

**Comment by LitoMore** [comment]
The Similarweb rank does not meet our requirement. Our requirement is at least 500k.

**Comment by PratyushJayachandran** [comment]
> Please don't merge `master` to our `develop` branch. I just fixed it for you.

Sorry I messed up the merge in my fork.

**Comment by LitoMore** [comment]
I'm closing this PR. You could re-submit a PR without merging master.

**Pull request closed without merging**
