### PR TITLE
Update Firefox Browser

### PR DESCRIPTION
**Pull request by mondeja**
image

**Issue:** N/A
**Alexa rank:** N/A

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Path optimized removing a lot of useless coordinates, rebuilding from scratch.
- Fixed some inconsistencies in the geometry.
- Added `guidelines` entry.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I'm seeing a number of minor differences in the ears, the ends of the tail, the bottom right of the outer curve and the left of the inner curve when comparing with `Icon (Full Color)\Fx-Browser-icon-fullColor.svg` in [this zip](https://3u26hb1g25wn1xwo8g186fnd-wpengine.netdna-ssl.com/files/2019/10/Firefox-Browser-Logo-Assets.zip), @mondeja.

**Comment by mondeja** [comment]
I've used `Icon (One Color)\Fx-Browser-icon-oneColor.svg` as reference. Could you check against that?

**Comment by PeterShaggyNoble** [comment]
Thanks, @mondeja. Seeing the same differences when comparing against that file. A few of them are (with yours in red):
- [the ears](https://user-images.githubusercontent.com/15157491/111178443-0f6e9180-85a3-11eb-8fd8-91b976cf8786.png)
- [tip of the tail](https://user-images.githubusercontent.com/15157491/111178500-20b79e00-85a3-11eb-82ea-cfe32eaf7f66.png)
- [outer part of the tail](https://user-images.githubusercontent.com/15157491/111178572-362cc800-85a3-11eb-9a3e-b933b5022c73.png)
- [down the right edge of the circle](https://user-images.githubusercontent.com/15157491/111178738-59577780-85a3-11eb-800f-1e6c04bd2b15.png)

Would you mind having another look? They may just be precision issues.

**Comment by adamrusted** [comment]
Just looking at this - I _think_ I've got a working 4 decimal path. @PeterShaggyNoble, would you mind taking a quick look at it, and if it's suitable I'll push an update to this PR.

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Firefox Browser</title><path d="M8.8245 7.2875c.0076.0004.0038.0001 0 0zm-2.8004-1.4c.0076.0004.0038.0001 0 0zm16.7531 2.1617c-.5054-1.2156-1.529-2.5282-2.3328-2.9429.6581 1.2932 1.0363 2.5743 1.1798 3.5485-1.3852-3.4897-4.0287-4.9536-5.7675-8.1622a2.1157 2.1157 0 0 1-.1735-.4597.0303.0303 0 0 0-.0264-.0312c-.013-.0045-.0252.0008-.0361.0077-2.5569 1.477-3.6613 4.171-3.9282 5.8469a6.1959 6.1959 0 0 0-2.3044.5881.2974.2974 0 0 0-.1471.3692.292.292 0 0 0 .3714.1805c.746-.3518 1.562-.5421 2.3872-.5489 2.0862-.0349 4.1062 1.158 5.1265 2.9707-.621-.4362-1.7328-.867-2.8039-.6807 4.1827 2.091 3.0597 9.2917-2.7361 9.0198-2.3352-.0789-4.5551-1.9219-4.79-4.3304 0 0 .5368-2.0001 3.8436-2.0001.3575 0 1.3794-.9975 1.3984-1.2868-.0044-.0945-2.0283-.8995-2.8173-1.6769-.5919-.572-.6464-.6721-1.1003-.9933a5.3873 5.3873 0 0 1-.0327-2.842c-1.1945.544-2.1237 1.4038-2.7992 2.1629h-.0053c-.461-.5839-.4285-2.51-.4022-2.9122-.5595.237-1.0834.7528-1.5247 1.1795a10.19 10.19 0 0 0-1.086 1.3023C1.0075 8.153.4969 10.079.3878 12.373.3878 18.7944 5.5943 24 12.0165 24c5.7516 0 10.5272-4.1753 11.4622-9.6596.3071-2.1184.0888-4.407-.7015-6.2912z"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
Thanks, @adamrusted 👍🏻 A precision of 5 may be necessary here though as I'm seeing 2 minor differences, one in [the left ear](https://user-images.githubusercontent.com/15157491/120628187-4ba3e680-c45c-11eb-8463-e08407cb645e.png) and the other in [the bottom left of the inner curve](https://user-images.githubusercontent.com/15157491/120628258-62e2d400-c45c-11eb-971b-988cea1a07d0.png), with your version in red in both cases.

**Comment by mondeja** [comment]
Given that this will be opened just to make the geometry small, I'm going to close it because is not urgent at all. Feel free to reopen if you want 👍🏼

**Pull request closed without merging**
