### PR TITLE
Updated Peugeot

### PR DESCRIPTION
**Pull request by adamrusted**
peugeot

**Issue:** Contributes to #4578
**Alexa rank:** [43,472](https://www.alexa.com/siteinfo/peugeot.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Updated source, and rebuilt with new SVG.

#### Previous Treatment
peugeot

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
SVG lines up perfectly with the source but there are a few excess points throughout that may be able to be removed; could you have another look at those, @adamrusted?

**Comment by adamrusted** [comment]
@PeterShaggyNoble Unfortunately, looking at [this PDF](https://peugeot.pcaci.co.uk/downloads/Charte_Bloc_Marque_FRGB_2012.pdf) we're unable to remove the wordmark. Have updated source to PCACI and re-generated using the monochrome SVG on pg7 of the PDF.

**Comment by fbernhart** [comment]
@adamrusted Hmm ... Is there a reason not to use [this SVG](https://www.stellantis.com/content/dam/stellantis-corporate/assets/brand-logo-negative/brand-logos-same-width-white/brand-peugeot-SW-white-14.svg) from https://www.stellantis.com/en/brands/peugeot ?

I would assume that it's the most up-to-date one. Because the [PDF](https://peugeot.pcaci.co.uk/downloads/Charte_Bloc_Marque_FRGB_2012.pdf) you've used instead is back from 2012.

And comparing both versions, there are quite some differences:

image

**Comment by adamrusted** [comment]
@fbernhart went with the PCACI source instead of Stellantis, as the other logos found on Stellantis' site have been somewhat troublesome with extraneous points etc.

**Comment by fbernhart** [comment]
But as this icon doesn't contain any troublesome points, I would still be in favour of using the current logo from their website than one from a 2012 PDF (although the differences are pretty small).

Would you mind updating this icon itself and the source to https://www.stellantis.com/en/brands/peugeot?

To save you some work, here is the optimized SVG with a precision of 3, which passes the linter:
```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Peugeot icon</title><path d="M11.108 3.546a1.023 1.023 0 0 0-.25.03 3.586 3.586 0 0 0-1.119.384.569.569 0 0 0-.257.222.249.249 0 0 1-.132.108 6.306 6.306 0 0 0-.708.29c-.094.054-.144.112-.098.22a3.13 3.13 0 0 0 .45.674.743.743 0 0 0 .274.108c.04.01.068.023.082 0a.256.256 0 0 1 .1-.135 1.122 1.122 0 0 1 .454-.152c.09 0 .145-.01.19.023a.64.64 0 0 1 .19.26c.036.114.013.156-.051.175a2.002 2.002 0 0 1-.475.087c-.219.017-.281-.044-.297-.058-.016-.014-.04-.031-.063 0a.457.457 0 0 1-.174.129c-.049.023-.074.075-.027.157.139.241.323.513.495.565.136.042.209 0 .362-.112.153-.11.226-.099.264-.071.039.028.124.1.103.174a2.48 2.48 0 0 1-.334.468c-.044.057-.085.087-.174.049-.116-.056-1.875-.967-2.11-1.06a1.927 1.927 0 0 0-.676-.133 3.336 3.336 0 0 0-.647.041.588.588 0 0 0-.31.188c-.16.148-.328.336-.347.494a.852.852 0 0 0 .128.358.1.1 0 0 0 .105.042 1.108 1.108 0 0 1 .452-.063c.188.033.207.174.216.294a.077.077 0 0 0 .08.063.718.718 0 0 1 .326.066 3.023 3.023 0 0 1 .548.393c.042.045.039.087-.04.096a7.61 7.61 0 0 0-1.353.259c-.21.068-.457.162-.544.313a2.357 2.357 0 0 0-.26.645c-.036.197.175.44.23.494.056.054.065.06.13.024a1.457 1.457 0 0 1 .589-.226c.144 0 .201.127.236.174.035.047.068.016.197-.019.23-.06 1.506-.038 1.956-.017a1.677 1.677 0 0 1 .696.156 4.278 4.278 0 0 1 .59.473s-.505.847-.776 1.348c-.25.463-.435.81-.522 1.012a1.466 1.466 0 0 0-.136.65c.023.301.03.456.026.594-.003.137-.114.132-.273.173-.219.054-.655.096-1.008.174-.322.08-.442.155-.5.404a6.513 6.513 0 0 0-.118.896c0 .09 0 .134.108.111a4.951 4.951 0 0 1 .496-.06c.297-.022.62-.017.87-.018.459 0 1.813.078 1.912.087.1.008.14 0 .13-.084-.01-.108-.029-.448-.034-.65-.005-.202-.036-.41.148-.609.184-.198 1.565-1.74 1.64-1.817.075-.079.111-.14.214-.046.102.094 1.24.915 1.471 1.082a1.14 1.14 0 0 0 .71.23c.186 0 .24.33.08.362-.16.03-.414.081-.588.121a.511.511 0 0 0-.433.332 6.155 6.155 0 0 0-.148.97c0 .048 0 .116.07.1a6.915 6.915 0 0 1 1.42-.07c.646.021 1.271.075 1.36.08.089.005.105 0 .152-.083a3.237 3.237 0 0 1 .537-.58c.104-.072.108-.114.063-.246-.221-.663-1.118-2.327-1.823-3.265-.153-.203-.095-.309-.014-.375a6.043 6.043 0 0 0 .654-.647c.313-.358.388-.763.174-1.351-.214-.588-.95-1.96-1.103-2.418-.173-.522-.193-.762-.086-1.043.125-.338.305-.348.443-.348a.144.144 0 0 1 .129.115 1.943 1.943 0 0 0 .156.718 2.224 2.224 0 0 0 1.017 1.096c.13.055.154-.046.143-.095-.01-.048-.207-.81-.348-1.38-.153-.6-.23-.729-.365-.856a1.186 1.186 0 0 0-.823-.311c-.619.024-.892.622-.927.678-.034.056-.04.083-.104.04-.174-.123-.695-.555-.74-.826-.028-.158-.056-.174-.216-.244a9.176 9.176 0 0 0-1.755-.56 1.023 1.023 0 0 0-.28-.04zm-.002.163c.254.023 1.49.36 1.84.576a.271.271 0 0 1 .052.038.143.143 0 0 1 .046.075 1.35 1.35 0 0 0 .33.621 4.911 4.911 0 0 0 .58.54.477.477 0 0 1 .2.282 9.089 9.089 0 0 1 .149 1.705c-.02.174-.035.255-.27.318-.235.063-.824.19-1.066.266-.372.118-.303.402-.124.654.18.252 1.503 1.812 2.282 2.956a17.097 17.097 0 0 1 1.588 2.814c.012.032.057.126-.017.178l.006-.004a2.74 2.74 0 0 0-.474.501c-.056.082-.06.085-.146.077-.718-.07-1.649-.07-1.913-.07-.047 0-.03-.028-.035-.05a1.85 1.85 0 0 1 .083-.447c.035-.117.067-.136.301-.212.279-.092 1.204-.268 1.425-.332.153-.046.106-.246.01-.41-2.162-3.632-3.362-4.615-6.162-6.138-.368-.199-1.824-.983-2.114-1.1a3.652 3.652 0 0 0-.893-.173c-.174-.013-.38.04-.386-.033-.005-.073.052-.202.141-.216a2.64 2.64 0 0 1 1.012.022 2.523 2.523 0 0 1 .538.218c.535.268 1.243.626 1.412.711.249.125 1.391.713 1.704.84.313.127.412.038.511-.106a8.146 8.146 0 0 0 .522-1.116.743.743 0 0 0-.035-.713 7.826 7.826 0 0 0-.918-1.247c-.182-.193-.696-.185-1.18-.082a8.198 8.198 0 0 0-1.058.334.483.483 0 0 1-.174.049c-.05 0-.15-.174-.163-.216-.037-.085-.037-.097.116-.174.275-.123.537-.174.652-.249.115-.074.122-.187.286-.288a2.765 2.765 0 0 1 1.342-.399zm-.664.436c-.022-.003-.05.003-.082.008a6.301 6.301 0 0 0-.417.104.104.104 0 0 0-.07.056.209.209 0 0 0-.02.134.056.056 0 0 0 .083.033c.062-.027.428-.16.492-.174a.06.06 0 0 0 .044-.038.174.174 0 0 0 .01-.08c-.004-.03-.019-.04-.04-.043zm4.078 3.339c.014-.003.032.006.045.023.026.035.096.242.238.505.213.396.467.892.555 1.106a.466.466 0 0 1-.085.522c-.174.21-.67.44-.79.48a.317.317 0 0 1-.347-.07c-.08-.076-.733-.87-.941-1.099a.303.303 0 0 1 .132-.522c.261-.095.717-.21.857-.25.199-.052.298-.157.31-.303V7.54c0-.035.011-.052.026-.055zM8.826 8.829c.063.004.247.278.43.477A34.73 34.73 0 0 0 8.15 9.29v.003c-.473 0-.92.014-1.075.028a.26.26 0 0 1-.123 0c-.031-.017 0-.078.036-.126a1.075 1.075 0 0 1 .348-.225 6.297 6.297 0 0 1 .696-.08c.052 0 .73-.064.793-.06zm1.714 1.284c.016 0 .034.003.055.009a1.913 1.913 0 0 1 .295.187l.119.087a21.489 21.489 0 0 0-1.66 2.416v.003a1.033 1.033 0 0 0-.132.627c0 .234.033.521.018.659-.016.137-.103.194-.238.233-.136.038-.943.173-1.12.219a.318.318 0 0 0-.25.28 2.087 2.087 0 0 0-.046.226c0 .045 0 .095-.058.099a5.529 5.529 0 0 0-.292.024c-.057.01-.066 0-.064-.068a3.929 3.929 0 0 1 .099-.492.358.358 0 0 1 .306-.297c.202-.049 1.021-.188 1.176-.216.174-.03.226-.11.215-.283-.01-.174-.034-.437-.038-.593a1.043 1.043 0 0 1 .056-.425c.056-.153.348-.784.591-1.23a15.652 15.652 0 0 1 .832-1.37c.05-.06.086-.092.136-.095zm1.509 8.175c-.934 0-1.696.428-1.696 1.08 0 .696.762 1.074 1.696 1.074a5.414 5.414 0 0 0 1.255-.174v-.792h-.55v.602a1.74 1.74 0 0 1-.664.122c-.636 0-1.102-.317-1.102-.82 0-.561.478-.826 1.06-.826a3.494 3.494 0 0 1 1.196.256v-.348a3.927 3.927 0 0 0-1.195-.174zm7.012.013c-.936 0-1.7.436-1.7 1.09 0 .696.764 1.063 1.7 1.063.935 0 1.695-.376 1.695-1.063 0-.654-.76-1.09-1.695-1.09zM0 18.36v2.037h.558v-.624h.501c1.071 0 1.62-.348 1.62-.725 0-.41-.588-.679-1.566-.679zm3.546 0v1.425c0 .38.158.603.673.603l1.644.009v-.256H4.485c-.296 0-.38-.134-.38-.36v-.306H5.72v-.254H4.104v-.607h1.69v-.254zm3.252 0v1.367c0 .56.558.726 1.174.726a3.687 3.687 0 0 0 1.456-.287l.007-1.806H8.87v1.712a1.934 1.934 0 0 1-.66.1c-.429 0-.853-.107-.853-.485V18.36zm7.524 0v1.425c0 .38.158.603.671.603l1.644.009v-.256H15.26c-.296 0-.38-.134-.38-.36v-.306h1.615v-.254H14.88v-.607h1.689v-.254zm6.894 0v.29h1.113v1.738h.558v-1.737H24v-.29zm-2.155.193c.588 0 1.06.28 1.06.837 0 .508-.429.837-1.06.837-.637 0-1.064-.33-1.064-.837 0-.557.476-.837 1.064-.837zm-18.503.034h.44c.454 0 1.052.076 1.052.452 0 .255-.194.506-1.125.506H.558z"/></svg>
```

**Comment by adamrusted** [comment]
@fbernhart - just updated to original source (Stellantis) and switched out path for your one. Comparing it to source SVG it matches up perfectly, so feel free to merge if the JSON is alright.

**Comment by fbernhart** [comment]
@adamrusted Thanks! 👍🏼

**Comment by gizmecano** [comment]
Sorry for the work done just a few days ago by @adamrusted but Peugeot has just announced a new logo yesterday (I haven't found an official link yet, but you can already check out the [published video on Twitter](https://twitter.com/PeugeotFR/status/1364949147925757954)).

**Comment by adamrusted** [comment]
@gizmecano nice find - I'll put up a PR today to hopefully get that updated by next week.

**Comment by gizmecano** [comment]
You're welcome @adamrusted
It's a bit weird: it seems many automakers intend to make a rebranding right now... 🤨

**Comment by adamrusted** [comment]
It's probably to do with the Stellantis merger, I imagine a lot of the brands are going to take the opportunity for a bit of a face-lift!

**Comment by gizmecano** [comment]
> It's probably to do with the Stellantis merger (...)

This explanation seems fair enough, but recently there have also been [Nissan](https://github.com/simple-icons/simple-icons/issues/3345), [Kia](https://github.com/simple-icons/simple-icons/issues/4728) (and Renault brought up a possible new logo during the presentation of the new [R5 Prototype](https://fr.media.groupe.renault.com/folders/2021-renault-5-prototype-ded7-e3532.html))...

**Comment by PeterShaggyNoble** [comment]
@adamrusted, if the Stallantis files aren't up to scratch, there's an SVG available in the header of https://www.peugeot.co.uk/; I'll let you know if I can dig out any official guidelines on the new branding.

**Pull request merged**
