### PR TITLE
Add Winmate Icon

### LINKED ISSUE #2849: Winmate
**Name:** Winmate
**Website:** [Winmate.com](https://winmate.com) 
**Official resources for icon and color:** https://www.winmate.com/images_new/common/Winmate_redlogo.png

### PR DESCRIPTION
**Pull request by LuckyF**
**Issue:** Closes #2849 
**Alexa rank:** ~74.4k

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

winmate

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
> this is not reported in the build failure, cc @PeterShaggyNoble

Looking into this now ...

**Comment by adamrusted** [comment]
@simple-icons/maintainers I've merged develop into this branch and fixed the SVG. Please feel free to merge.

**Comment by fbernhart** [comment]
I've found an official vectorized version of the logo. 🎉  It's a PDF file (on page 1):

https://dc.winmate.com/main/download/Catalog/MARKET_CATA1

Opening the link, you'll be asked to login. As it's for free and there are no real requirements, I've quickly created an account 😄  username: simpleicons@trash-mail.com, password: simpleicons

As there are some minor differences between the source and the SVG in the pull request, I would be in favour of using the official vector version that I've provided above. @adamrusted could you rebuild the icon using the new source?

And please as well update the `source` attribute. I'd suggest updating it to https://www.winmate.com/NewsAndEvents/Publications. The linked PDF above is linked there as "Mobile Solutions".

image

**Comment by adamrusted** [comment]
@fbernhart Done 😄

**Comment by fbernhart** [comment]
@adamrusted LGTM 👍🏼 

@LuckyF Thanks for your initial work on this icon. 🚀

**Pull request merged**
