### PR TITLE
Add icon for ZCOOL

### LINKED ISSUE #3317: Request: ZCOOL icon
**Name: zcool**
**Website: https://www.zcool.com.cn**
**Alexa rank:** 1.5k
  

**Official resources for icon and color:**
  
  

https://www.crunchbase.com/organization/zcool

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** closes #3317

**Similarweb rank:** [~13k](https://www.similarweb.com/website/zcool.com.cn/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Vectorized app icon from https://www.zcool.com.cn/appdown
- Took color from stylesheet

### CODE REVIEW

**Review by PeterShaggyNoble — APPROVED** [review]
Amazing work, @service-paradis 😁 It'll be good to get this one of our plate after all this time!

Before merging, though, what would you, and the other @simple-icons/maintainers, reckon to using _just_ the head, without the background square?

**Comment by service-paradis** [comment]
> Amazing work, @service-paradis 😁 It'll be good to get this one of our plate after all this time!

haha, thanks! One of the oldest icon request still open 😅 

> Before merging, though, what would you, and the other @simple-icons/maintainers, reckon to using just the head, without the background square?

Good question! Maybe @LitoMore can help us here?

**Comment by LitoMore** [comment]
> Before merging, though, what would you, and the other @simple-icons/maintainers, reckon to using just the head, without the background square?

@service-paradis @PeterShaggyNoble Just the head would be better.

See https://weibo.com/u/1733083617. It's their social media. They don't just use rounded icons. In the meantime, it looks better when it's just the head on the badge.

**Comment by service-paradis** [comment]
zcool, thanks for your feedback! Just pushed a new commit using only the zcoolhead:
image

**Review by LitoMore — APPROVED** [review]

**Pull request merged**
