### PR TITLE
Add SNCF icon

### LINKED ISSUE #8096: SNCF icon
### Brand Name

SNCF

### Website

https://www.sncf.com

### Popularity Metric

The Similarweb rank is 4,854. See https://www.similarweb.com/website/sncf.com.

In 2010 the SNCF was ranked 22nd in France and 214th globally on the [Fortune Global 500](https://en.wikipedia.org/wiki/Fortune_Global_500) list.

### Official Resources for Icon and Color

Brand guidelines for SNCF are available on https://www.sncf.com/fr/groupe/marques/sncf/identite

### Additional Comments

**Wikipedia:** The SNCF [[ɛs‿ɛn se ɛf]](https://en.wikipedia.org/wiki/Help:IPA/French) is France's national railway company. Founded in 1938, it operates the country's national rail traffic along with Monaco, including the TGV, on France's high-speed rail network. Its functions include operation of railway services for passengers and freight (through its subsidiaries [SNCF Voyageurs](https://en.wikipedia.org/wiki/SNCF_Voyageurs) and [Rail Logistics Europe](https://en.wikipedia.org/w/index.php?title=Rail_Logistics_Europe&action=edit&redlink=1)), as well as maintenance and signalling of rail infrastructure ([SNCF Réseau](https://en.wikipedia.org/wiki/SNCF_R%C3%A9seau)).

### Contributing

Yes

### PR DESCRIPTION
**Pull request by jamu3l**
sncf

Closes #8096 

**Similarweb rank:** 4,854
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The SNCF is the national railway company of France. All the details about color and logo are available in their [brand guidelines](https://www.sncf.com/fr/groupe/marques/sncf/identite) on their website.

### CODE REVIEW

**Review by dirien — COMMENTED** [review]
Hi @jamu3l,

thanks for the contribution. Can you please open an issue for this PR too? 

Thanks!

**Comment by jamu3l** [comment]
> Hi @jamu3l,
> 
> thanks for the contribution. Can you please open an issue for this PR too?
> 
> Thanks!

Hey @dirien :) Opened #8096 for this icon.

**Review by dirien — APPROVED** [review]
Hi @jamu3l ,

Thanks for your contribution to simple-icons!

It's a perfect fit:
image

**Comment by jamu3l** [comment]
Thanks :)

**Pull request merged**
