### PR TITLE
Add Caffeine icon

### LINKED ISSUE #5000: Caffeine TV
**Brand Name:** Caffeine.tv
**Website:** https://www.caffeine.tv/
**Alexa rank:** I don't know but this is the link: https://www.alexa.com/siteinfo/caffeine.tv
  

**Official resources for icon and color:** There's no link

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** Close #5000
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I used the icon in the footer at https://www.caffeine.tv/
- I used Inkscape to remove extraneous points (corners were a total mess!) and scale
- I used https://jakearchibald.github.io/svgomg/ to optimize

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Oof! Those corners are hideous! Great job cleaning them up 👍🏻

I am though seeing [one tiny difference](https://user-images.githubusercontent.com/15157491/118791459-a4855380-b88e-11eb-9c2e-fa579cd56c4f.png) running down the edge of the vertical line on the right. If that's a side effect of cleaning up the corners, though, I'm OK to run with it given how insignificant it is and this can be merged straight in.

**Comment by service-paradis** [comment]
> Oof! Those corners are hideous! Great job cleaning them up 👍🏻

Thank you for the review! Tried my best to clean those, it was a fun game 😅 

> I am though seeing [one tiny difference](https://user-images.githubusercontent.com/15157491/118791459-a4855380-b88e-11eb-9c2e-fa579cd56c4f.png) running down the edge of the vertical line on the right. If that's a side effect of cleaning up the corners, though, I'm OK to run with it given how insignificant it is and this can be merged straight in.

You're right! Just gave this a try again and I dont know what I'm doing wrong, but I'm not able to fix it right now without unwanted side effects. Will try again after some coffees!

**Comment by service-paradis** [comment]
It should be a little bit better now! Let me know if there is something else!

**Review by mondeja — APPROVED** [review]
Great work ☕

**Pull request merged**
