### PR TITLE
updating the docs to make it easier to follow. 

### PR DESCRIPTION
**Pull request by charlesomane**
**Issue:** closes #

**Popularity metric:**

### Checklist

- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by LitoMore** [comment]
FYI: https://carpentries-incubator.github.io/markdown-intro/06-lists/index.html.

**Comment by LitoMore** [comment]
I prefer to use `1.` for all lines. You don't need to modify them all when you want to add or delete them.

**Comment by mondeja** [comment]
What is the purpose on the change? Are you reading the docs as plain text, not using a Markdown renderer?

**Comment by charlesomane** [comment]
> I prefer to use `1.` for all lines. You don't need to modify them all when you want to add or delete them.

No problem

**Comment by charlesomane** [comment]
> What is the purpose of the change? Are you reading the docs as plain text, not using a Markdown renderer?

I just thought that my change would make more easier for new comers. 
Sorry for the inconvenience.

**Pull request closed without merging**
