### PR TITLE
Add Hilton

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Hilton

**Issue:** #1874

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon & colour from [SVG](https://www.hilton.com/static_brands_assets/shared-ui-assets/header-logo-HI-c070d0a0198360b49d1dff21a46ee30e.svg) in website header.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Don't know that it is Potraced, @runxel - that usually doesn't group paths (more often than not, it results in a single path) and it adds a comment to the SVG source.

The SVG in the "Our Brands" section of [this page](https://www.hilton.com/en/) looks like it might be a bit better, what do you think?

**Comment by runxel** [comment]
> Don't know that it is Potraced, @runxel - that usually doesn't group paths (more often than not, it results in a single path) and it adds a comment to the SVG source.

My evaluation was based on the "(R)" and the shoddy "O" in "Hotels", but maybe thats rooted in something different.


> The SVG in the "Our Brands" section of [this page](https://www.hilton.com/en/) looks like it might be a bit better, what do you think?

Oh yeah, that looks better!

**Comment by PeterShaggyNoble** [comment]
They might have used a different converter 🤷‍♂ 

Path data for the new version for review:
```
M16.123 14.234c0-1.544-1.06-2.788-2.972-3.386V7.347h3.57v8.59h-1.105a2.993 2.993 0 0 0 .506-1.703M11.194 3.708C4.744 3.708 0 7.808 0 12.184c0 2.257 1.267 4.168 2.88 5.481l.114-.092a6.369 6.369 0 0 1-2.418-4.95C.92 7.83 6.818 5.134 12.092 5.134c3.709 0 10.388.85 10.388 7.072 0 3.247-3.455 7.462-10.733 7.462-3.731 0-6.61-2.004-6.61-4.86 0-2.487 1.935-4.26 4.836-4.26a7.83 7.83 0 0 1 2.12.345c-1.199-.207-3.087.092-4.055.85v4.192h3.57v-4.743a4.064 4.064 0 0 1 1.543.6v4.192h.922a3.83 3.83 0 0 1-3.27 1.126v.184c3.385.276 4.813-1.336 4.813-3.156 0-2.118-2.004-3.362-4.03-3.639V7.347h-3.57v3.179c-2.304.46-4.561 1.842-4.561 4.1 0 3.501 4.883 5.666 9.12 5.666 6.452 0 11.425-3.109 11.425-7.508.023-5.299-7.163-9.076-12.806-9.076
```

Preview:
Hilton

Comparison (first version in red):
Hilton

**Comment by runxel** [comment]
👍 Looks nice!

**Pull request merged**
