### PR TITLE
Updated XMPP

### PR DESCRIPTION
**Pull request by adamrusted**
xmpp

**Issue:** Contributes to #3169
**Alexa rank:** [166,575](https://www.alexa.com/siteinfo/xmpp.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Source updated to [GitHub repo](https://github.com/xsf/xmpp.org/tree/00c49187e353c1a156c95562dafaf129e688fbad/content/icons).
Regenerated from source.
Ran through SVGO CLI.

### CODE REVIEW

**Review by mondeja — APPROVED** [review]
Strange geometry, but it seems that the SVG of the source is even worse 👍🏻

**Comment by Neustradamus** [comment]
Dear @adamrusted, @mondeja,

You have done a mistake badly, you have changed the source and the icon!

Can you use the good place?
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg
- https://commons.wikimedia.org/wiki/File:XMPP_logo_(without_text).svg

Thanks in advance.

cc: @PeterShaggyNoble, @runxel, @ericcornelissen.

Linked to:
- https://github.com/simple-icons/simple-icons/pull/2085
- https://github.com/simple-icons/simple-icons/issues/2272
- https://github.com/simple-icons/simple-icons/pull/2275

**Comment by adamrusted** [comment]
@Neustradamus - please elaborate as to why this is a mistake?

Per our own contribution guidelines, an official source (such as the website source code on GitHub) trumps a WikiMedia link. If the version on WikiMedia is the 'official' version, then it should be shown to be used in other locations (available in the GitHub repo, etc).

**Comment by Neustradamus** [comment]
@adamrusted: Old version, there was a problem: https://i.ibb.co/vcqmc8b/xmpp-logo-xsf-test.png

It is not good here:
- https://github.com/xsf/xmpp.org/tree/00c49187e353c1a156c95562dafaf129e688fbad/content/icons

**Comment by adamrusted** [comment]
But just to confirm, it IS good as of a84359cc9f40752485cbc2a4d8a97e7b9da0a3d8 ?

**Comment by Neustradamus** [comment]
Normally the good is here:
- https://github.com/simple-icons/simple-icons/pull/2275

Note that the version on Commons "without text" has been added after the logo with text (published after the cited PR):
- https://commons.wikimedia.org/wiki/File:XMPP_logo_(without_text).svg

**Comment by adamrusted** [comment]
Yeah, so it was adapted to the Commons version there, but as I said previously we should use an official GitHub repo over WikiMedia Commons where possible. Could you confirm the current repository has the correct versions, and I'll use them?

**Comment by Neustradamus** [comment]
If I look history of https://github.com/xsf/xmpp.org/commits/master/static/images/logos/xmpp-logo.svg
It has been updated (2021-09-29).

**Pull request merged**
