### PR TITLE
Add SRG SSR Logo

### PR DESCRIPTION
**Pull request by Andre601**
**Issue:** N/A
**Alexa rank:** [596,636](https://www.alexa.com/siteinfo/srgssr.ch)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Adds the logo of the "Schweizerische Radio- und Fernsehgesellschaft" (SSR stands for Société suisse de radiodiffusion et télévision; English is it "Swiss radio and television company")

The logo's main color is `#af001e` which I set as the branding color.

Please note that I had some issues creating the SVG and that it might actually be invalid/corrupted as using `viewBox` somehow breaks it.
That's the main reason why this is still a Draft, since I have not the knowledge and experience to fix it myself and would appreciate anyone with the tools and knowledge to help me fix it.

Steps I did:
- Took the SVG from the Wikimedia Commons page
- Put it into IcoMoon App (online), set canvas to 24, resized and centered icon and removed all colors
- Put the new SVG into SVGOMG, set detail to 3 (was default) and saved.
- Opened SVG in Notepat++ and edited the `<svg>` attributes (Added `form="img"`, `viewBox="0 0 24 24"` and removed height and width attributes)

### CODE REVIEW

**Comment by NovaGL** [comment]
Hi @Andre601 

It's good you wanted to have a go anyway. I renamed this pull so it's easier to identify.

Some pointers.

The json you provided is invalid, you're missing a comma. It's good practice to validate the JSON before creating a PR, generally these small things can easily be sorted.

Due to the above, the rest of the checks failed.

**Comment by Andre601** [comment]
Thanks for pointing that out. I corrected it.
The issue with the SVG still persists tho. I would appreciate some help here as I never worked with SVG like that before... So I would be really happy if someone with good knowledge could take a look and help fixing it.

**Comment by NovaGL** [comment]
So looking at the test results I can see the following

- You named the icon SRG-SSR but there is no dash in the json, please rename the svg to srgssr.svg
- You're missing the HEX in the JSON (must be in uppercase)
- The <title> should follow the format "[ICON_NAME] icon" and it's missing from the SVG
- The size of <path> must be exactly 24 in one dimension; the size is currently 768 x 265.958

I suggest you look at the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and see if that helps.

**Comment by Andre601** [comment]
I now renamed the svg to srgssr.svg, added the missing `<title>` attribute (Could've sworn that I added it) and also added the brand color.
I still don't get why the size is different. I did follow the guidelines and - as mentioned in my first comment - did use SVGOMG to set canvas size to 24, rescale and center the svg and remove all colors from it, so I'm just lost on that one here.

**Comment by PeterShaggyNoble** [comment]
@Andre601, is there another metric we can use to assess the popularity of this brand? Our cut-off for Alexa ranks is 500k so this would already have been out of scope and it seems to have dropped quite significantly since you opened this PR - it's down to ~789k now.

**Pull request closed without merging**
