### PR TITLE
Add Hitachi icon

### PR DESCRIPTION
**Pull request by el1f**
**Issue:** #1671 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Got the color hex from the website as the design document I found [here](http://www.multimedialab.be/doc/tech/chartes/hitachi.pdf) seems to be set in CMYK mode and has a slightly different hue than the one used in digital media.

### CODE REVIEW

**Comment by el1f** [comment]
I got the SVG from the Wikimedia commons [here](https://upload.wikimedia.org/wikipedia/commons/b/b1/Hitachi_Logo.svg).
As you can see their website only has the PNGs so I compared that version with the one used in their website, realized it was a perfect match and went on with that

**Comment by birjolaxew** [comment]
@el1f In that case, could you please update the `"source"` to [the Wikimedia page](https://commons.wikimedia.org/wiki/File:Hitachi_inspire_the_next-Logo.svg)? Since this looks good other than that, I'll get this merged in afterwards :)

**Comment by el1f** [comment]
Oh, you're right about that. Still, I think this is a grey area when it comes to how to approach this change:
The source in Readme is referred to as a link to a document that will enable to realize whether or not the current icon is representative of the brand. In this case the Wikimedia isn't helpful because if Hitachi goes through a rebrand that link isn't going to be useful to understand that the logo is outdated, nor is it going to provide an updated resource to the new logo.

What do you think about it?

**Comment by birjolaxew** [comment]
@el1f While the `"source"` URL is mostly used so we can go back later and find updated versions of the logo, should it ever change, it also gives an idea of how official the logo source is (e.g. whether it's an official vector, a vector taken from Wikimedia, or a manual vectorization of an official raster). In this case the Wikimedia link further includes some important information about where the vector comes from (it appears to be an officially published PDF, where the logo has been extracted from).

I see your point that an eventual rebrand would reach Wikimedia with a bit of a delay, but I think that in this case the need to source the vector itself trumps that. Thoughts @simple-icons/maintainers?

**Comment by ericcornelissen** [comment]
I agree with @birjolaxew, though as @el1f said it is (it almost always is) a gray area. But I think the Wikimedia link is more helpful for the project in this case.

Hence, @el1f once you update  the `"source"` to [the Wikimedia page](https://commons.wikimedia.org/wiki/File:Hitachi_inspire_the_next-Logo.svg) we can merge this 😃 

To the argument that the Wikimedia link is not going to tell us whether the brand details are outdated I would say that neither does a link to the website. If a brand is outdated we usually find out through contributions (be it from contributors or maintainers) rather then from someone going through the URLs in the metadata file and checking if everything is still up-to-date.

**Comment by el1f** [comment]
Done! :)

**Comment by birjolaxew** [comment]
Thanks for your work on this @el1f!

**Pull request merged**
