### PR TITLE
Add PlatformIO Icon

### LINKED ISSUE #8825: Icon request: PlatformIO
### Brand Name

PlatformIO

### Website

https://platformio.org/

### Popularity Metric

The SimilarWeb rank is 119,499. See https://www.similarweb.com/website/platformio.org/#overview

### Official Resources for Icon and Color

None

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
platformio

**Issue:** closes #8825 

**Similarweb rank:** 117,499. See https://www.similarweb.com/website/platformio.org

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from the PNG available in https://piolabs.com/legal/trademarks.html. Auto-tracing didn't produce good result, hence I drew it keeping the PNG as reference.
Color: `#f5822a` as mentioned in https://github.com/simple-icons/simple-icons/pull/5235#issuecomment-967505314

### CODE REVIEW

**Comment by PratyushJayachandran** [comment]
Please review
@adamrusted and @ivankravets

**Comment by ivankravets** [comment]
@PratyushJayachandran could you try to remove the "circle" around the ant/alien? See example

Badge

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran could you try to remove the "circle" around the ant/alien? See example
> 

Fixed 😊
Thanks for the review

platformio

**Comment by ivankravets** [comment]
@PratyushJayachandran , looks great to me! 🚀

**Review by adamrusted — APPROVED** [review]
Looks pretty spot on to me, and given we've got @ivankravets blessing I'd be happy to accept.
Given it's an interpretation of a PNG though, I'll request another @simple-icons/icon-review member to okay it too!

**Comment by PratyushJayachandran** [comment]
> Looks pretty spot on to me, and given we've got @ivankravets blessing I'd be happy to accept. 
> Given it's an interpretation of a PNG though, I'll request another @simple-icons/icon-review member to okay it too!

Thank you for comparing and checking. 😊

**Pull request merged**
