### PR TITLE
Add Peloton.

### PR DESCRIPTION
**Pull request by klu17**
**Issue:** #4464
**Alexa rank:** 6333

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
  - `#181A1D` from https://press.onepeloton.com/#logos
  - Manually combined paths with Inkscape. Then, SVGOMG.

### Preview
image

### CODE REVIEW

**Comment by DovOps** [comment]
Thanks @klu17  - Regarding the guidelines at https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon - is it possible to just include the icon, or do the rules require that the text appear in the logo as well?

**Comment by klu17** [comment]
### Updated Preview
image

**Review by adamrusted — CHANGES_REQUESTED** [review]
I can see some ***tiny*** differences between PR (red) and source (black) - you may need to set the precision to 4 on SVGOMG to get these to line up.

image

**Review by adamrusted — APPROVED** [review]
LGTM! 🚴🏻‍♀️🏃🏻‍♀️

**Comment by klu17** [comment]
@adamrusted Just curious. Is that an online diff checker that you are using? For the red and black comparison?

**Comment by adamrusted** [comment]
> @adamrusted Just curious. Is that an online diff checker that you are using? For the red and black comparison?

Nope, I download the SVG from source and PR, and compare them in Figma / Adobe Illustrator. I always put PR at `#ff0000` 50% opacity, and source at `#000000` 100% opacity underneath. That, and checking for any erroneous paths/points inside the icon manually. 😄

**Pull request merged**
