### PR TITLE
Use `<picture>` blocks for GH theme images in README

### PR DESCRIPTION
**Pull request by mondeja**
See [Specifying the theme an image is shown to](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to). The `#gh-dark-mode-only` and `#gh-light-mode-only` link variants are deprecated.

- [x] Needs [mondeja/strip-gh-theme-links@v4](https://github.com/mondeja/strip-gh-theme-links/releases/tag/v4) released.

### CODE REVIEW

**Comment by LitoMore** [comment]
CleanShot 2022-11-24 at 21 30 21@2x

Not sure why this wrapped.

**Comment by LitoMore** [comment]
Seems we can put the `<picture>` behind the plugin name as a workaround.

```markdown
| [Jetpack Compose library](https://github.com/DevSrSouza/compose-icons) <picture><source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/simple-icons/simple-icons/develop/assets/readme/jetpackcompose-white.svg"><source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/jetpackcompose.svg"><img src="https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/jetpackcompose.svg" alt="Jetpack Compose" align=left width=24 height=24></picture> | [@devsrsouza](https://github.com/devsrsouza/) |
```

**Comment by mondeja** [comment]
I don't see it wrapping with the browser window maximized: 

image

But if I reduce the width of the window, it wraps, is the expected behaviour.

**Comment by LitoMore** [comment]
I'm facing this issue with Safari on macOS. What I can see is the issue can be fixed with moving the `<preview>` to the back.

**Comment by mondeja** [comment]
> I'm facing this issue with Safari on macOS. What I can see is the issue can be fixed with moving the `<preview>` to the back.
> 
> BTW, I found our those icons on titles are placed behind the text. So I think we could move the icon to the back of texts in table cells as well.

I'm not sure why we should move them as they would be not vertically aligned, just because of a Github's internal CSS error in Safari.

**Comment by mondeja** [comment]
I'm merging this. Feel free to open another PR to make that change!

**Pull request merged**
