### PR TITLE
add Xcode icon

### PR DESCRIPTION
**Pull request by simonker**
To address JsonLint error, I have fixed hex capitalisation

### CODE REVIEW

**Comment by birjolaxew** [comment]
Looking good! Could you please update the capitalization to match Apple's "Xcode" instead of "xcode" (in JSON and `<title>`)?

**Comment by simonker** [comment]
@birjolaxew Sorry about that, Apple's weird capitalisation always gets me :)

**Comment by birjolaxew** [comment]
@simonker You still have the old capitalization in your SVG: `<title ...>xcode icon</title>`

**Comment by simonker** [comment]
@birjolaxew ok... _Should_ be good now!

**Comment by birjolaxew** [comment]
:+1: There we go! Thanks for the contribution! Much appreciated

**Pull request merged**
