### PR TITLE
Add Amazon S3

### LINKED ISSUE #2687: Request: Amazon S3
**Name:** Amazon S3
**Website:** https://aws.amazon.com/s3/
**Alexa Rank:** n/a
**Colour:** The middle shade of red, I guess?
**Official resources for icon and color:** None that I can find yet, but it is available from [Worldvectorlogo](https://worldvectorlogo.com/logo/aws-s3) and [SVGPORN](https://svgporn.com/). Not sure of the best approach to making it monochrome, though.

Cross-posted from [MDI#4929](https://github.com/Templarian/MaterialDesign/issues/4929).

Amazon S3

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Amazon S3

**Issue:** Closes #2687 (ref: Templarian/MaterialDesign#4929)
**Alexa rank:** n/a

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon & colour from `\Asset-Package_20210131\Resource-Icons_01-31-2021.zip\Res_Storage\Res_48_Light\Res_Amazon-Simple-Storage-Service_S3-Standard_48_Light.svg` found in [this zip](https://d1.awsstatic.com/webteam/architecture-icons/q1-2021/AWS-Architecture_Asset-Package_20210131.a41ffeeec67743738315c2585f5fdb6f3c31238d.zip). Possible alternative colours are `#6cae3e` from the corresponding "Dark" icon, which was also present in the gradient of Amazon's last version of this icon, and `#569a31`, which is [the calculated midpoint](https://meyerweb.com/eric/tools/color-blend/#3F8624:6CAE3E:1:hex) of the two.

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Looks like AWS have updated icons _**AGAIN**_, with the current version of the icon (red) being different to this PR (black) [here](https://user-images.githubusercontent.com/1830867/108602903-ad07e400-739c-11eb-858d-5ad715c1c2e4.png). Do you want to update it, or shall I compare to the ZIP from 2020/09/11?

**Comment by PeterShaggyNoble** [comment]
🤦🏻‍♂️ Damnit, Amazon, why do you always have to make our jobs so difficult! We'll need to double check DynamoDB, too.

Updated icon & colour based on `\Asset-Package_20210131\Resource-Icons_01-31-2021.zip\Res_Storage\Res_48_Light\Res_Amazon-Simple-Storage-Service_S3-Standard_48_Light.svg` found in [this zip](https://d1.awsstatic.com/webteam/architecture-icons/q1-2021/AWS-Architecture_Asset-Package_20210131.a41ffeeec67743738315c2585f5fdb6f3c31238d.zip). The inner curve of the bucket is a mess but, after fighting with it for far too long, I had to accept defeat so just ran with it as-is.

Possible alternative colours are `#6cae3e` from the corresponding "Dark" icon, which was also present in the gradient of Amazon's last version of this icon, and `#569a31`, which is [the calculated midpoint](https://meyerweb.com/eric/tools/color-blend/#3F8624:6CAE3E:1:hex) of the two.

**Comment by adamrusted** [comment]
Icon matches up perfectly, though there are a _LOT_ of excess points in that top ellipse.
I'd be happy to go with the calculated midpoint, bearing in mind that if we set a precedent here, we will need to try and adhere to it for other AWS icons (I'm looking at you, DynamoDB! 👀) but will wait for another @simple-icons/maintainers to take a look at this, primarily to see if we can fix this SVG - but also regarding the colour.

**Review by adamrusted — COMMENTED** [review]
Happy to merge this, as the icon was already perfect. With this, we'll have to keep an eye on any other AWS architecture icons, and give them the similar treatment of calculated midpoint.

**Comment by PeterShaggyNoble** [comment]
Doesn't look like there are corresponding icons for Dynamo DB within `Resource-Icons_01-31-2021.zip` 🙄 Although it's been a _long_ morning so I could easily be missing them. When comparing to `\Asset-Package_20210131\Architecture-Service-Icons_01-31-2021.zip\Arch_Database\32\Arch_Amazon-DynamoDB_32.svg` it doesn't look like we'll need to make any updates.

**Comment by adamrusted** [comment]
There are DynamoDB icons in `Resource-Icons_01-31-2021.zip/Res_Database/Res_48_Light` though they relate to specific areas of a DynamoDB instance (tables, items etc) so not really appropriate. If the hex of DynamoDB matches the midpoint of it's gradient, then we're sorted on that front for now.

**Pull request merged**
