### PR TITLE
Add BandLab icon (#1881)

### LINKED ISSUE #1881: BandLab (online music platform)
BandLab is mainly an online music platform making possible to create music on various platforms (web, mobile, etc.) with the addition of social features. 
The company behind it also took over to the development of [Cakewalk](https://www.bandlab.com/products/cakewalk) which is a very popular DAW (maybe at the time but IDK how popular it is nowadays). 

**Name:** BandLab
**Website:** https://bandlab.com/
**Official resources for icon and color:** https://blog.bandlab.com/press/

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
closes #1881

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Color `#DC3710` and logo is taken from their presskit.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hi @runxel thanks for working on this PR, the svg is great. 🎉 

Can you please update the description above to include the source you used for this icon and why you chose this colour. 

The "see issue" didn't help me here and a full description included with every PR (even if it is repeating information from the issue) makes it a lot easier to review. 😉

**Comment by runxel** [comment]
I am sorry @phatbhoy67, I was lazy here. 😞

**Comment by birjolaxew** [comment]
This PR looks good, except I would prefer having https://blog.bandlab.com/press/ as the `source` URL. Could you update that @runxel?

**Comment by runxel** [comment]
Done so! :)

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @runxel 👍

**Pull request merged**
