### PR TITLE
Add: Data Version Control

### PR DESCRIPTION
**Pull request by casperdcl**
I'm part of @iterative and we have enough users of our open source tools that it seemed time to open this PR.

Logo | Alexa rank | GitHub Stars | Source
---- | ---------- | ------------ | ------
Data Version Control  | 400~650 k (https://dvc.org) | 7.9 k (https://github.com/iterative/dvc) | https://static.iterative.ai/logo/dvc.svg

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Preview

dataversioncontrol

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contributions, @casperdcl. Based on the data you've provided, however, only Data Version Control is currently within our scope with 7.9k stars on GitHub so, before we review, could you remove the others from this PR, please. If you like you can open issues for them for now where we can try to assess their popularity through other metrics.

**Comment by casperdcl** [comment]
@PeterShaggyNoble updated

**Comment by PeterShaggyNoble** [comment]
Thanks, @casperdcl. All looks good to me other than the fact that there are [a few excess points](https://user-images.githubusercontent.com/15157491/118133388-b0899500-b3f8-11eb-9a94-eafb54beccf7.png) _within_ the path. If you're using Inkscape then that can be resolved by using "Union" (<kbd>Ctrl + +</kbd>) in the "Path" menu, rather than "Combine".

**Comment by casperdcl** [comment]
@PeterShaggyNoble good spot - updated again

**Comment by adamrusted** [comment]
Hey @casperdcl, I'm still seeing [similar excess points](https://user-images.githubusercontent.com/1830867/118310890-13595a00-b4e7-11eb-8145-ca6719e346fa.png) within the path when I'm viewing it in Illustrator. Other than that, and a few _tiny_ movements of points when optimizing, this SVG is looking great 💪 - would you mind taking another stab at the excess points again?

**Comment by casperdcl** [comment]
Thanks @PeterShaggyNoble - the problem is inkscape doesn't know what to do with optimised SVGs so I can't check the paths. How about now?

**Review by adamrusted — APPROVED** [review]
Perfect! 😍
No clue what was going on with Inkscape and the optimized SVGs - it's usually Illustrator that has issues with SVGO(MG) vectors!
Thanks for your contribution of this one @casperdcl - and I hope to see the other icons added to the project when they're in scope!

**Comment by casperdcl** [comment]
```bash
$ inkscape --version
Inkscape 0.91 r13725
```

just in case that helps :)

**Comment by adamrusted** [comment]
@casperdcl may just be you need to do an update? Current version of Inkscape is 1.0.2 and shows the optimized SVGs fine as far as I'm aware - though being an Illustrator / Affinity guy I rarely use Inkscape to test it 😅

**Comment by casperdcl** [comment]
Yes needed an update.

**Comment by casperdcl** [comment]
Since this was merged and released, any reason why it doesn't (yet) seem to be working with shields.io?

- Data Version Control (doesn't work): DVC
- Visual Studio Code (similar name format, works): VSC

**Comment by adamrusted** [comment]
> Since this was merged and released, any reason why it doesn't (yet) seem to be working with shields.io?

It's likely because shields.io hasn't updated it's dependency yet. Once they update to the latest version, the icon will be available through their service.

Last I checked, their update process is done mid-week, so should be available by next weekend at the latest. If not, best to ask the question at their repo.

**Pull request merged**
