### PR TITLE
Update Xamarin

### PR DESCRIPTION
**Pull request by jamesmontemagno**
Xamarin hex color is officially #3498DB from branding: https://github.com/dotnet/swag/tree/master/xamarin

**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description
Updated hes from official brnding

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Nice find, @jamesmontemagno. I'd suggest updating the source URL to the Xamarin directory in that repo, too.

And we'll also need to do a comparison with their SVG to make sure it doesn't differ from the version I used and update if it does.

**Comment by jamesmontemagno** [comment]
@PeterShaggyNoble I updated the source URL. The SVG in https://github.com/dotnet/swag/tree/master/xamarin is the official from our original branding site :) 

I am not a SVG master, however they do look a bit different:

current:
https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/xamarin.svg

.net repo: https://raw.githubusercontent.com/dotnet/swag/master/xamarin/Xamagon/svg/Xamagon.svg

**Comment by ericcornelissen** [comment]
It does appear the logo has slightly changed, at least the corners of the 'X' are now rounded where they weren't before. If you'd prefer, one of the @simple-icons/maintainers can push an updated version of the logo to this Pull Requests @jamesmontemagno?

**Comment by PeterShaggyNoble** [comment]
A comparison of the 2 is below, with the one from the .NET repo in grey and our current version in red.

The markup for the updated version, if you want to add it to your PR, is:
```
<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Xamarin icon</title><path d="M6.925 1.323a1.904 1.904 0 00-1.609.93L.241 11.07a1.918 1.918 0 000 1.862l5.075 8.816c.326.56.96.929 1.609.93h10.15a1.904 1.904 0 001.609-.93l5.075-8.816a1.918 1.918 0 000-1.862l-5.075-8.816a1.904 1.904 0 00-1.609-.93zm.092 5.157a.22.22 0 01.043 0h1.75a.23.23 0 01.192.114l2.97 5.292a.228.228 0 01.028.086.228.228 0 01.028-.086l2.963-5.292a.231.231 0 01.198-.114h1.751c.155.002.271.197.199.334L14.239 12l2.9 5.179c.08.138-.04.342-.199.34h-1.75a.232.232 0 01-.2-.12l-2.962-5.292A.228.228 0 0112 12.02a.228.228 0 01-.028.086l-2.97 5.292a.231.231 0 01-.192.12H7.06c-.16.002-.278-.202-.199-.34L9.761 12l-2.9-5.186c-.07-.125.015-.307.156-.334Z"/></svg>
```

Xamarin

**Comment by PeterShaggyNoble** [comment]
@jamesmontemagno, I took the liberty of updating the SVG file in your branch. Hope that's OK.

**Comment by jamesmontemagno** [comment]
Fantastic! Thanks @PeterShaggyNoble  :) looks good to me

**Comment by PeterShaggyNoble** [comment]
:+1: As I contributed the SVG myself, we'll need one of the other @simple-icons/maintainers to review this PR before we can merge it in.

**Comment by phatbhoy67** [comment]
Thanks for your work on this @jamesmontemagno and @PeterShaggyNoble 👏

**Pull request merged**
