### PR TITLE
Add Krutrim icon

### PR DESCRIPTION
**Pull request by k4ustu3h**
**Similarweb rank:** https://www.similarweb.com/website/olakrutrim.com

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Extracted the logo and hex from the splash animation before the chat page on [chat.olakrutrim.com](https://chat.olakrutrim.com/home).

krutrim

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @k4ustu3h 👍🏻 Could you share the source file here, though, as the website is geo-blocked for me?

**Comment by k4ustu3h** [comment]
This is the svg on the splash screen, that I extracted with [archivebox](https://archivebox.io/)

logo

**Review by adamrusted — CHANGES_REQUESTED** [review]
This isn't lining up at all for me (yours in black) - could you take another look for me please @k4ustu3h?
image

**Comment by adamrusted** [comment]
Are you still working on this, @k4ustu3h - if not could you please close down the PR?

**Comment by adamrusted** [comment]
Closing due to inactivity. If you wish to continue working on this @k4ustu3h please ping us here and we can reopen.

**Pull request closed without merging**
