### PR TITLE
Add Vimeo Livestream

### PR DESCRIPTION
**Pull request by fbernhart**
vimeolivestream

**Issue:** N/A
**Alexa rank:** [9,441](https://www.alexa.com/siteinfo/livestream.com)
 
 ### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Relies on the discussion in #4647.
- SVG pulled from the header of https://livestream.com
- Color `#0A0A20`, which is used on the website and was mentioned in https://github.com/simple-icons/simple-icons/pull/4647#issuecomment-756094307

### CODE REVIEW

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @fbernhart 🎉

**Comment by PeterShaggyNoble** [comment]
I still think just the Vimeo `v` is the way to go here, as they do in their favicon and in their website's header on smaller devices.

**Comment by fbernhart** [comment]
@PeterShaggyNoble We already have the "Vimeo v" as the icon of Vimeo itself. https://simpleicons.org/?q=vimeo

So this would mean we're having the same icon twice.

**Comment by PeterShaggyNoble** [comment]
Yes, but first we'd need to resolve #3270

For me, adding a wordmark simply to differentiate from an existing brand isn't ideal; we should always strive to add the icon only whenever possible.

**Pull request merged**
