### PR TITLE
Updated Amazon Lumberyard

### PR DESCRIPTION
**Pull request by fbernhart**
amazonlumberyard

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by adamrusted** [comment]
Looks perfect! 🚀

**Review by adamrusted — CHANGES_REQUESTED** [review]
Looks like in the optimization process, some of the paths may have been smoothed out. See my path generated from [source](https://d1.awsstatic.com/gamedev/lumberyard/lumberyard-branding-book.d543071c4ba02b30df7eae9dbe18916d8c985264.zip) in red, compared to PR path in black. *(May also be worth updating source to the branding pack linked above?)*

Capture

**Comment by fbernhart** [comment]
Visiting https://aws.amazon.com/lumberyard/support they seem to be using a beaver as icon as well. I'd say that it would fit Simple Icons better than the wordmark "lumberyard".

The [assets pack](https://d1.awsstatic.com/gamedev/lumberyard/lumberyard-branding-book.d543071c4ba02b30df7eae9dbe18916d8c985264.zip) as well contains the beaver as vector graphic and displays it in the brand guidelines.

@simple-icons/maintainers would you agree that the beaver is a better fit than the wordmark?

image

**Comment by mondeja** [comment]
> @simple-icons/maintainers would you agree that the beaver is a better fit than the wordmark?

Yes, I would opt by the beaver :+1:

**Comment by fbernhart** [comment]
amazonlumberyard

**Review by adamrusted — APPROVED** [review]
Perfect 💯🎉

**Comment by PeterShaggyNoble** [comment]
Much better 🙂

But, @runxel, wasn't there a reason you went with the wordmark originally?

**Comment by runxel** [comment]
Yes, there was @PeterShaggyNoble!
At that point Amazon didn't use the beaver anywhere – I knew that it existed, because I've saw it at another page (by some game dev, I believe). But it was nowhere to be found on the main website. Amazon used to use the wordmark exclusively.

**Pull request merged**
