### PR TITLE
Add AliExpress

### LINKED ISSUE #3296: AliExpress
**Name:** AliExpress
**Website:** aliexpress.com
**Alexa rank:** 38
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by adamrusted**
aliexpress

**Issue:** Fixes #3296
**Alexa rank:** [39](https://www.alexa.com/siteinfo/aliexpress.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Used PDF suggested by @PeterShaggyNoble, colour is picked from the CSS of the AliExpress homepage.

### CODE REVIEW

**Comment by fbernhart** [comment]
@adamrusted Matches perfectly apart from the "p". Could you have a look at it?

image

**Comment by adamrusted** [comment]
@fbernhart should be fixed - again I was trying to tidy up paths in Illustrator...

**Comment by fbernhart** [comment]
@adamrusted It's great to tidy up paths - if it doesn't change the general shapes. But sometimes if you clear up too many points, the icon will look different - especially after optimization.

Unfortunately I can still see differences - at a different location of the "p" now. 😅 

image

**Comment by adamrusted** [comment]
> Unfortunately I can still see differences - at a different location of the "p" now. 😅 

Looks like it'll have to be a precision of 4 then 👀😅

**Comment by adamrusted** [comment]
@fbernhart Let's try again 😅

**Comment by fbernhart** [comment]
@adamrusted Looks good now! 👍🏼 

I gave it a try myself, simplifying the path with some "Inkscape magic" ✨. I has less points than yours and a precision of 3:
```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>AliExpress icon</title><path d="M5.166 9.096a.022.022 0 0 0-.022.021c0 .396-.32.717-.713.717a.021.021 0 0 0-.021.022c0 .012.01.021.021.021.394 0 .713.322.713.718 0 .012.01.021.022.021.011 0 .021-.01.021-.021A.717.717 0 0 1 5.9 9.88a.021.021 0 0 0 0-.043.716.716 0 0 1-.713-.718v-.002a.021.021 0 0 0-.006-.015.022.022 0 0 0-.015-.006zm-3.693.526L0 13.462h.48l.355-.922h1.782l.354.922h.481L1.98 9.622zm2.264.002v3.838h.491V9.624zm2.375 0v3.838h2.413v-.502H6.613v-1.19H8.19v-.477H6.613v-1.166h1.773v-.502zm-4.386.592l.698 1.82H1.028zm14.689.402a1.466 1.466 0 0 0-.966.366V10.7h-.491v2.763h.49c.002-.477 0-.955.002-1.433a.969.969 0 0 1 .965-.918zm4.18.007c-.053 0-.105.003-.158.01-.315.031-.606.175-.753.377a.689.689 0 0 0-.14.465c.007.2.066.357.233.496.184.147.42.2.657.259.311.067.426.095.546.186.08.07.133.127.136.27 0 .25-.221.372-.42.41a.89.89 0 0 1-.894-.344l-.371.288c.33.382.777.505 1.09.5.54-.01.891-.217 1.029-.534.066-.153.063-.309.063-.38a.677.677 0 0 0-.267-.545c-.228-.177-.583-.228-.636-.242-.437-.078-.658-.196-.697-.341-.043-.192.102-.35.297-.411a.76.76 0 0 1 .857.277l.367-.247a1.166 1.166 0 0 0-.939-.494zm2.387 0c-.052 0-.105.003-.157.01-.316.031-.607.175-.753.377a.689.689 0 0 0-.14.465c.006.2.065.357.233.496.183.147.42.2.657.259.31.067.426.095.545.186.081.07.134.127.136.27.001.25-.221.372-.42.41a.89.89 0 0 1-.894-.344l-.371.288c.33.382.777.505 1.09.5.541-.01.891-.217 1.03-.534.065-.153.062-.309.062-.38a.677.677 0 0 0-.267-.545c-.227-.177-.583-.228-.636-.242-.437-.078-.658-.196-.696-.341-.043-.192.101-.35.297-.411a.76.76 0 0 1 .857.277l.367-.247a1.167 1.167 0 0 0-.94-.494zm-9.84.002a1.461 1.461 0 0 0-1.42 1.117 1.305 1.305 0 0 0-.041.327v2.833h.491v-1.813c.17.18.487.42.96.454a1.447 1.447 0 0 0 1.208-.627 1.457 1.457 0 0 0-1.199-2.292zm4.804 0a1.448 1.448 0 0 0-1.288 2.08c.255.53.811.87 1.412.833a1.452 1.452 0 0 0 1.012-.51l-.363-.291a.968.968 0 0 1-1.106.273 1.01 1.01 0 0 1-.602-.69h2.239l.002-.427a1.295 1.295 0 0 0-1.306-1.268zm-9.2.08l1.062 1.377-1.062 1.378h.581l.779-1.01.778 1.01h.581l-1.062-1.378 1.062-1.378h-.581l-.778 1.01-.779-1.01zm-3.825.015v2.74h.49v-2.74zm8.233.37a.96.96 0 0 1 .95.993.963.963 0 0 1-.863.998.962.962 0 0 1-1.034-.739c-.074-.382 0-.746.307-1.019a.959.959 0 0 1 .64-.233zm4.79.015a.823.823 0 0 1 .819.755h-1.76a.964.964 0 0 1 .94-.755z"/></svg>
```

Maybe you could quickly review it? It matches the source perfectly on my end. If it as well matches on your end, feel free to push and merge it. 😊  Otherwise we'll keep your version and merge it.

**Comment by adamrusted** [comment]
@fbernhart You and your Inkscape Magic! 😂

**Comment by fbernhart** [comment]
@adamrusted 😄 

Did you review my path? Can it be merged?

**Comment by adamrusted** [comment]
> Did you review my path? Can it be merged?

Sorry, yes! I've pushed it to this PR already - so feel free to merge it.

**Pull request merged**
