### PR TITLE
Add VEXXHOST icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** #6724 
**Alexa rank:** 387,17
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by sachinraja — CHANGES_REQUESTED** [review]
image
slight differences, try increasing the precision

**Comment by dirien** [comment]
Hi @sachinraja,

Thanks for thre review. It is already precission of 4 and I cant see the differences:
image

**Comment by sachinraja** [comment]
@dirien Can you share the SVG you used?

**Comment by dirien** [comment]
@sachinraja -> https://vexxhost.com/wp-content/uploads/2020/01/100_circle.svg

**Review by sachinraja — APPROVED** [review]

**Pull request merged**
