### PR TITLE
Updated Google Translate

### PR DESCRIPTION
**Pull request by adamrusted**
googletranslate

**Issue:** Contributes toward #4205
**Alexa rank:** N/A (Google subdomain)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Rebuilt SVG from source ~with gaps of 0.5px between different 'layers'.~

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Note that [the monochrome treatment Google themselves use](https://material.io/resources/icons/?search=g_translate&icon=g_translate&style=baseline) for this one matches our current treatment.

**Comment by adamrusted** [comment]
@PeterShaggyNoble just rebuilt to match existing styling, but with the 0.5px path around the right-hand section for consistency.

**Review by PeterShaggyNoble — APPROVED** [review]
Nice work, @adamrusted - looks good to me :+1: Note, though, that there is a slight gap in both your version and the original which I had "fixed" in my original contribution but I'm OK with or without it, if the other @simple-icons/maintainers are. The only change I'd suggest is using https://commons.wikimedia.org/wiki/File:Google_Translate_logo.svg for the source, in keeping with our current standards.

**Comment by adamrusted** [comment]
> Note, though, that there is a slight gap in both your version and the original which I had "fixed" in my original contribution but I'm OK with or without it, if the other @simple-icons/maintainers are.

Have updated the source, and will fix the gap now, thanks for spotting @PeterShaggyNoble!

**Comment by adamrusted** [comment]
@PeterShaggyNoble should be good to go, would you mind looking over it again before merging? 🙏🏻

**Review by PeterShaggyNoble — COMMENTED** [review]
Looks perfect to me now, @adamrusted 👍🏻 Nice work.

**Pull request merged**
