### PR TITLE
Add PortableApps icon

### LINKED ISSUE #11453: Request: PortableApps.com
### Brand Name

PortableApps.com

### Website

https://portableapps.com/

### Popularity Metric

Similiarweb Global Rank: [38,377](https://www.similarweb.com/website/portableapps.com)

### Official Resources for Icon and Color

- SVG: https://commons.wikimedia.org/wiki/File:PortableApps.com_logo.svg (couldn't find an SVG without the black border)
- Color: `#272727`, from above site 

### Additional Comments

White logo in website header doesn't have a border around the circle

### PR DESCRIPTION
**Pull request by daniel-kargari**
portableapps (1)

**Issue:** closes #11453  

**Popularity metric:**
Similiarweb Global Rank: [38,377](https://www.similarweb.com/website/portableapps.com)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by uncenter** [comment]
Please use the hex color you added (`#829096`) in the preview image.

**Comment by daniel-kargari** [comment]
> Please use the hex color you added (`#829096`) in the preview image.

Sure, I've updated the comment.

**Comment by adamrusted** [comment]
Did you ever hear back from them @DerBraky?

**Comment by JohnTHaller** [comment]
> Did you ever hear back from them @DerBraky?

I just dropped DerBraky a reply with an SVG that I think will work. Apologies on the slow response.

**Comment by adamrusted** [comment]
Thanks @JohnTHaller - are you able to share the SVG here, just so we all have access for comparing when merging?

**Comment by adamrusted** [comment]
Closing in favour of #12366

**Pull request closed without merging**
