### PR TITLE
Updated Nextdoor

### PR DESCRIPTION
**Pull request by fbernhart**
nextdoor

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by mondeja** [comment]
Seems that both the logo and the color have been changed in their brand guidelines. Now the "nextdoor" wordmark is used along with `#8ED500` as color. Could you update this brand @fbernhart?

**Comment by fbernhart** [comment]
@mondeja Done. 

nextdoor

**Review by mondeja — APPROVED** [review]
For the record, their brand guidelines points that: "The ‘n’ does not appear separately from the full wordmark."

I've resolved the conflict appeared after NFC update merge.
The icon looks perfect to me, thank you @fbernhart :1st_place_medal:

**Comment by fbernhart** [comment]
@mondeja Yeah, I've read the same in their guidelines.

Although they themselves use just the "n" in their favicon as logo. 😄

**Pull request merged**
