### PR TITLE
Added Material Design icon.

### PR DESCRIPTION
**Pull request by metaa**
# Added Icon
Material Design (#1282)

## Website
https://material.io/

## Logo
image
image (footer section of the site)

## Color
`#757575` ([Source](https://commons.wikimedia.org/wiki/File:Google_Material_Design_Logo.svg))

## What it will look like
image

### CODE REVIEW

**Comment by davidklebanoff** [comment]
Great job finding a monochromatic version! Can you elaborate on how you chose the color?

**Comment by metaa** [comment]
That icon in the footer area is actually a bit transparent. Using the opacity along with its color gives you `#808080` on a white background.

Actually now that you bring it up, we should maybe consider using `#202124`, which is primarily used as a "theme color" on the website.

**Comment by birjolaxew** [comment]
I think maybe a color from [their normal logo](https://storage.googleapis.com/spec-host/mio-staging/mio-material/1551221848744/static/m2/images/mio-logo-sprite.png) would be appropriate?

I'm getting `#ffffff` / `#bdbdbd` / `#747474`.

**Comment by ericcornelissen** [comment]
It's not easy to choose a color for this one. @birjolaxew suggestion is a more reliable than [the original one](https://github.com/simple-icons/simple-icons/pull/1320#issuecomment-476348264). In that light I would say we should use `#747474` as it is closest to `#808080` and I personally think a dark gray represent the brand quite accurately.

**Comment by PeterShaggyNoble** [comment]
To throw a spanner in the works, Google have another version of this icon in their Material Icons Extended font which has thicker lines.

material-design

**Comment by ericcornelissen** [comment]
@metaa any updates on this? What is your opinion with regards to the color?

@PeterShaggyNoble can you provide a link? I can find it very easily 😅

**Comment by PeterShaggyNoble** [comment]
Yeah, they don't promote that font much at all. You can find the latest `WOFF2` file [here](https://fonts.gstatic.com/s/materialiconsextended/v51/kJEjBvgX7BgnkSrUwT8UnLVc38YydejYY-oE_LvJ.woff2).

**Comment by metaa** [comment]
Hmm, the Material icon on [the i/o website](https://events.google.com/io/) that just recently went live, the icon has a background color of `#757575` (Scroll down on [this page](https://events.google.com/io/codelabs/)).

🤔

**Comment by ericcornelissen** [comment]
@metaa I agree, if you change it `#757575` this PR is good to go.

**Comment by ericcornelissen** [comment]
Thanks for your work on this @metaa 🎊

**Pull request merged**
