### PR TITLE
Add Modin icon

### LINKED ISSUE #7627: Modin
### Brand Name

Modin

### Website

https://github.com/modin-project/modin

### Popularity Metric

GitHub stars is **7.6k**, see https://github.com/modin-project/modin

### Official Resources for Icon and Color

svg: https://modin.org/img/MODIN_hrz.svg
color: `#001729` from logo background

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by elliotwutingfeng**
image

**Issue:** closes #7627

**GitHub Stars:** 7.6k

### Checklist

  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

nil

### CODE REVIEW

**Comment by LitoMore** [comment]
CleanShot 2022-09-21 at 11 42 23@2x

@elliotwutingfeng I see some difference. Could you give a check?

**Comment by elliotwutingfeng** [comment]
Oops I missed those! I can't find a way to extrude those 6 holes using Path -> Exclusion, they are causing the X-coords and the Width of the rest of the svg to shift.

**Comment by LitoMore** [comment]
They are already there. You don't need any calculation on it. Are you using [this resource](https://modin.org/img/MODIN_hrz.svg)? If not please use this one instead.

**Comment by elliotwutingfeng** [comment]
Yes, now svgo keeps increasing the width of the image.

**Comment by LitoMore** [comment]
CleanShot 2022-09-21 at 18 42 56@2x

@elliotwutingfeng I see some difference. Let's increase its precision to 4.

**Review by dirien — CHANGES_REQUESTED** [review]
What @LitoMore wrote, I can confirm.

**Review by dirien — APPROVED** [review]
Hi @elliotwutingfeng,

Thanks for your contribution to simple-icons!

It's a perfect fit:
image

**Pull request merged**
