### PR TITLE
adding Habanos icon

### PR DESCRIPTION
**Pull request by jorgeamadosoria**
habanos

**Issue:** #6265

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
I think this is ready for merging. Can we get someone from @simple-icons/maintainers to sign off / review, please?

**Comment by ericcornelissen** [comment]
Reverted this pro-actively on the bases that the source used here (`https://habanos.com/`) is misleading and should have been `http://www.habanos.com/` (or rather `http://www.habanos.com/en/`) instead - Habanos does not offer a secure HTTP connection it would seem :disappointed:

**Comment by jorgeamadosoria** [comment]
> Habanos does not offer a secure HTTP connection it would seem 😞

it does, but it is self signed - most likely for political reasons related to the embargo

**Comment by ericcornelissen** [comment]
Whether that's secure is debatable, but this is not the place to discuss that :sweat_smile: 

Anyway, if you visit the source used here in any modern browser with default settings you'll be hit with a warning, I think that's a reasonable argument against the source.

Furthermore, if we do want to continue this discussion than it should happen before the change is included in `develop` and included in the next release.

**Pull request merged**
