### PR TITLE
Add Zigbee

### LINKED ISSUE #2373: Zigbee
**Name:** Zigbee
**Website:** https://zigbeealliance.org/solution/zigbee/
**Alexa Rank:** [~579k](https://www.alexa.com/siteinfo/zigbeealliance.org)
**Colour:** `#eb0443`
**Official resources for icon and color:** Colour lifted from [this PNG](https://zigbeealliance.org/wp-content/uploads/2019/11/zb_logo-b_color_rgb_icon-e1573775155251.png) and SVG generated by running it through [Convertio](https://convertio.co/), with surprisingly good results.

While the current rank of zigbeealliance.org would appear to put it outside the scope of SI, it is a newly launched site with Alexa only proving data for it since the 31st of December. The previous website, zigbee.org, which now redirects to the new one, had a rank of [~393k](https://www.alexa.com/siteinfo/zigbee.org) on the same day.

[Zigbee](https://github.com/simple-icons/simple-icons/files/4064945/zigbee.zip)

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Zigbee

**Issue:** Closes #2373

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG created by converting [this PNG](https://zigbeealliance.org/wp-content/uploads/2019/11/zb_logo-b_color_rgb_icon-e1573775155251.png) with [Convertio](https://convertio.co/).

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble found an official .svg version within this [.pdf](https://zigbeealliance.org/wp-content/uploads/2019/11/Zigbee-Alliance-Trademark-and-Logo-Policy.pdf) which can be extracted from first item on page 6 - extracted part attached:

[za-full.zip](https://github.com/simple-icons/simple-icons/files/4078143/za-full.zip)

There are slight differences in the path compared to your PR.

**Comment by PeterShaggyNoble** [comment]
Nice find, @phatbhoy67

It'll have to wait 'til Monday, though; I've just shut down my machine for the weekend.

**Comment by PeterShaggyNoble** [comment]
Icon updated

**Comment by PeterShaggyNoble** [comment]
Good eye, @phatbhoy67 - I did indeed resize it to be a perfect circle. Does this look better, before I push a commit?

```
M11.988 0a11.85 11.85 0 00-8.617 3.696c7.02-.875 11.401-.583 13.289-.34 3.752.583 3.558 3.404 3.558 3.404L8.237 19.112c2.299.22 6.897.366 13.796-.631a11.86 11.86 0 001.912-6.469C23.945 5.374 18.595 0 11.988 0zm.232 4.31c-2.451-.014-5.772.146-9.963.723C.854 7.003.055 9.41.055 12.012.055 18.626 5.38 24 11.988 24c3.63 0 6.85-1.63 9.053-4.182-7.286.948-11.813.631-13.75.388-3.775-.56-3.557-3.404-3.557-3.404L15.691 4.474a38.635 38.635 0 00-3.471-.163Z
```

**Comment by phatbhoy67** [comment]
> Does this look better, before I push a commit?

It looks like a perfect match @PeterShaggyNoble 👍

**Comment by PeterShaggyNoble** [comment]
Thanks, @phatbhoy67 - PR updated

**Comment by phatbhoy67** [comment]
Nice work @PeterShaggyNoble 👍

**Pull request merged**
