### PR TITLE
Adding Reason SVG

### PR DESCRIPTION
**Pull request by weswhite**
**Issue:**
#1288

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
A working PR for reason svg

### CODE REVIEW

**Comment by weswhite** [comment]
very embarrassed by the number of commits :(

**Comment by ericcornelissen** [comment]
That is not a problem @weswhite (also no need to close #1288 really), it's a learning process. We squash merge icon contributions anyway. 😄 In light of #1275 I pushed an extra commit that compounds the 2 `<path>`s in your version to a single path.

I have one last question, where did you get the color `#DB4C3F` from? The color of the SVG linked in #1286 uses `#DD4B39` 🤔

**Comment by weswhite** [comment]
@ericcornelissen i closed it because my new commits were not being picked up in the PR for some reason. That color was from a color picker tool.

**Comment by ericcornelissen** [comment]
> i closed it because my new commits were not being picked up in the PR for some reason.

That is weird :confused: 


> That color was from a color picker tool.

Which color picker tool? And from what did you pick the color? :sweat_smile:

Since there is [an official SVG](https://reasonml.github.io/) that has the color embedded into it I think we're best of using that, unless there are brand guidelines that specify otherwise

**Comment by birjolaxew** [comment]
Interestingly the header on the site uses `#DB4D3F`, while the SVG uses `#DD4B39` - they apparently aren't super consistent themselves. I do agree that we should use the one from the SVG, though

**Comment by weswhite** [comment]
@ericcornelissen I was using the eye dropper chrome pluggin. I may have pulled from the wrong color too. I dont remember. I can update the PR

**Comment by ericcornelissen** [comment]
As @birjolaxew pointed out, you probably pulled the color from the `<header>`, which is different from the color in the `<svg>`... We can go either way but I prefer to use the one from the logo, so can you update the it?

When that's done this PR is ready to be merge @weswhite :smile:

**Comment by weswhite** [comment]
Updated 😌

**Comment by ericcornelissen** [comment]
Thanks for your work on this @weswhite, it is much appreciated! No need [to be embarrassed](https://github.com/simple-icons/simple-icons/pull/1290#issuecomment-473132642), I hope you learned a few things in the process.

There is one thing left, because we use [squash commits](https://help.github.com/en/articles/about-pull-request-merges#squash-and-merge-your-pull-request-commits) to merge PRs that add icons your `develop` branch is now out of sync with our `develop` branch. This is because you've been working on your `develop` branch. For future PRs (also to other repositories) I recommend you work on a separate branch (read more [here](https://www.atlassian.com/git/tutorials/using-branches/git-checkout)).

For now you need to make sure your `develop` is updated. I recommend you take one of these two approaches: 1) remove your fork and fork again, or 2) fetch our pointer to `develop` and force push it to your fork.

If you need any help, feel free to ask it here :smile:

**Comment by weswhite** [comment]
Can i merge your develop branch into mine and then commit? @ericcornelissen

**Comment by ericcornelissen** [comment]
I think so, but I'm not 100% sure :thinking: You can of course test it by trying it out. Merge our `develop` into yours, check out on a new temporary branch, creating a dummy commit, (push the branch,) and try to open a PR for that new branch into our `develop`. If you see only a single commit then it worked.

Please share your findings here :smile:

**Comment by weswhite** [comment]
@ericcornelissen i am seeing that my branch is already merge. Do i still need to update?

**Comment by ericcornelissen** [comment]
>  i am seeing that my branch is already merge.

What do you mean by that? :sweat_smile:

**Comment by weswhite** [comment]
Merged*

This commit is now in develop

**Comment by ericcornelissen** [comment]
Are you talking about this branch/Pull Request? If so, yes. I tried to visualize what happened when this branch got merged :arrow_down: Your `develop` has a bunch of commits that where squashed into a single commit and then added to our `develop`. As a result the two are "out of sync" (i.e. they both think there are different commits on the branch). I hope that clarifies the current situation, yes or no?

```
...o--o--o--o--o--o                [YOUR DEVELOP]
          \___   /
              \ /
   ...o--o--o--o                   [OUR DEVELOP]
```

In the future this will result in all the commits that where squashed in this Pull Request to be included as well. I again tried to visualize this :arrow_down: (where `x` are commits from this PR and R is the commit that will result from your next PR).

```
...o--o--x--x--x--x--o--o--o--o                [YOUR DEVELOP]
         \________________   /
                          \ /
         ...o--o--o--x--o--R                   [OUR DEVELOP]
```

This is kind of ugly and confusing. What we want is for every Pull Request to look like the first one. Therefore we need to keep the two branches "in sync". The easiest way to accomplish this is by just working on a separate branch. So (given your `develop` is in sync with ours) what you do is you checkout a new branch (`git checkout -b my_new_icon`) you add your stuff and then you open a Pull Request from that branch into our `develop`. But for now I recommend you do [what I mentioned earlier](https://github.com/simple-icons/simple-icons/pull/1290#issuecomment-473518257) to get the two in sync.

If you still have questions, feel free to ask (but try to be a bit more specific then you where in your previous to comments :smile:).

**Pull request merged**
