### PR TITLE
Wacom icon

### PR DESCRIPTION
**Pull request by adsingh14**
**Issue:** #6870
**Alexa rank:** 12,456 
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

wacom

### CODE REVIEW

**Review by dirien — COMMENTED** [review]
Hi @adsingh14, thanks for the contribution. Tbh, i am not sure about that icon. I checked most of their social media sites, and they use there only the wacom logo -> https://community.wacom.com/us/wp-content/uploads/2018/12/wacom-logo.svg

I will leave the decision to the other @simple-icons/maintainers.

**Comment by adsingh14** [comment]
@dirien  I was going to use 'wacom' as you refereed but it won't justify it as icon but logo !

**Comment by dirien** [comment]
hi @adsingh14, yepp understand this. But i don't know so I am open for some additonal feedback. And also, someone with more experience to review this.

**Comment by jorgeamadosoria** [comment]
browsing this: https://www.blurb.co.uk/books/2716714-wacom-brand-standards-guidelines

Apparently the Wacom icon is the evolution of the older icon, the one used here.
I don't know how official that booklet is, but it seems legit.
As such, I would use the Wacom logo as Icon rather than this one.

**Comment by adsingh14** [comment]
> I don't know how official that booklet is, but it seems legit.

This is unofficial booklet. I prefer to go with official, wordmark, logo.

**Comment by jorgeamadosoria** [comment]
> > I don't know how official that booklet is, but it seems legit.
> 
> This is unofficial booklet. I prefer to go with official, wordmark, logo.

since there is no public official source, and the Wacom logo is more pervasive (as @dirien  said), and is even present in the main page, I wonder if that's not actually a better choise going forward.
While the "five senses" icon is more representative, my concern is more about time proofing the icon: if Wacom is indeed the way the identity is going to go with in the future, then adding this icon now will require a change in the near future.

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @adsingh14,

can you check the icon again? I see some differences:
image

Thanks

**Comment by adsingh14** [comment]
@dirien Please check icon in #7672

**Pull request closed without merging**
