### PR TITLE
Add Bitrise icon

### PR DESCRIPTION
**Pull request by doomsayer13**
**Issue:**
-

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The SVG created/optimized by Dora Siraly Graphic designer of Bitrise.io

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @doomsayer13 thanks for the contribution. 👍

Looking at the .svg file, the icon is not centered vertically within the viewbox. 

Opening the .svg file in Inkscape, the width of the icon appears to be a fraction wider than 24px at 24.19px.

Can you check the width and make sure it is a maximum of 24px, and then center the icon both horizontally and vertically in the viewbox.  

For reference, the [contribution](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) guidelines detail the steps necessary, including examples and a checklist prior to submission. Hope that helps.

**Comment by doomsayer13** [comment]
@phatbhoy67 Thanks for reviewing it and replying.
We just updated the icon, so please if you have some free time take a look on it. 
Thanks ;)

**Comment by phatbhoy67** [comment]
Thanks for adding the requested changes and for your contribution @doomsayer13, the icon looks great! 👍 .

I've requested a review from @ericcornelissen and hopefully it will be merged soon. 

Note: [Alexa Rank](https://www.alexa.com/siteinfo/bitrise.io): 53,584

**Comment by doomsayer13** [comment]
@ericcornelissen Thanks for replying and for your feedback.
We made the requested changes, pls review it again and if we have to do any other changes let us know ;)

**Comment by ericcornelissen** [comment]
Thanks for the update @doomsayer13 :+1: Can you (again) update the SVG so that it is vertically centred in the viewbox, the same request as [before](https://github.com/simple-icons/simple-icons/pull/1829#issuecomment-546401714).

**Comment by ericcornelissen** [comment]
Thanks for the contribution @doomsayer13, it is much appreciated! The icon will be available with our next release 🙂

**Pull request merged**
