### PR TITLE
Updated Google Assistant

### PR DESCRIPTION
**Pull request by adamrusted**
googleassistant

**Issue:** #4205
**Alexa rank:** N/A

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Updated source to Partner Marketing Hub.
Slight change to logo.
Ran through SVGO CLI and SVGlint.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Couple of suggested changes while I double check the SVG, @adamrusted:

1. That site we using for brand guidelines has been restructured so could you update the source URL to https://thepartnermarketinghub.withgoogle.com/brands/google-assistant/?
2. From https://thepartnermarketinghub.withgoogle.com/brands/google-assistant/overview/color-palette-and-typography/, it looks like `#EA4335` should be the colour by virtue of the fact that it's listed first. Although, I do seem to remember that coming up when this was originally added and us deciding to use the blue anyway.

**Comment by PeterShaggyNoble** [comment]
The downloads for this logo on that new site are now hidden behind a login but comparing yours to the SVG in the header of https://assistant.google.com/, everything looks good to me.

So, ignoring the above, I'd suggest now reverting the source URL to the Assistant website.

**Comment by adamrusted** [comment]
Will push a change to the source in a mo.

> it looks like `#EA4335` should be the colour by virtue of the fact that it's listed first. Although, I do seem to remember that coming up when this was originally added and us deciding to use the blue anyway.

Yeah - bit of an odd one. I'd suggest that because the blue is the largest of the shapes, and fits the rest of Google's branding we should stick to that - but happy to alter if another @simple-icons/maintainers thinks we should go for the red.

**Comment by PeterShaggyNoble** [comment]
I'm also OK with retaining the blue :+1:

This looks good to go to me know but, seeing as I haven't reviewed a PR in _months_, I'll let one of the other @simple-icons/maintainers throw another eye over this to be sure everything's OK.

**Comment by PeterShaggyNoble** [comment]
Given that there has been no further input on this one, I'm going to merge it in.

Thanks, @adamrusted 👍🏻

**Pull request merged**
