### PR TITLE
Added Vectorworks Icon

### PR DESCRIPTION
**Pull request by sjstark**
vectorworks

Issue: #1984 (Fixes Issues with #3586)
Alexa rank: 156,287

Checklist
- [X] I updated the JSON data in _data/simple-icons.json
- [X] I optimized the icon with SVGO or SVGOMG
- [X] The SVG viewbox is 0 0 24 24

Description
---

- Chose the hex value based on company's main brand color. Vectorworks updates actual application icon yearly with release of new software.
- Grabbed the svg from company website's SVG.
- I opened a new request because the branch I had previously started was lost. I checked the vectorworks website to see if they had perhaps updated their SVG, but unfortunately it still had extra nodes as well as unnecessary handles.
- I've gone in with Inkscape and replaced the exterior circle with new circle paths to clean up geometry. I also went and straightened up some of the handles of the 'V' that were pointed out by @runxel and deleted the additional nodes of the upper-left interior corner.

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for your work on this @sjstark!

It looks like there's a fair difference on the right hand side of the circles on your version compared to the source icon. 

<details>
<summary>
Screenshot
</summary>

</details>

And if you compare this PR to the [footer icon](https://www.vectorworks.net/cached/themes/vectorworks_redesign_2018/assets/images/logos/vw-v.svg) there are different inconsistencies there. The circles look more precise on the footer one - so I'd be inclined to use that as the reference as opposed to the header.

Any chance you could take another look at this one? I know the optimizer can sometimes mess up the path for circles, so compare it in [SVGOMG](https://jakearchibald.github.io/svgomg/) against your original exported path, to see if it's kept the shape.

**Comment by adamrusted** [comment]
Hi @sjstark, are you still wanting to look into the issue mentioned in https://github.com/simple-icons/simple-icons/pull/4764#pullrequestreview-569084501? If not, another member of the community may be able to help out 👌🏻

**Comment by sjstark** [comment]
Good find on the footer logo @adamrusted , I've updated it using that as well as used the SVGOMG rather than the CLI to optimize. I believe all should be in order now, but have clearly been mistaken before 😅 

<details>
<summary>SVGOMG</summary>
<br>
chrome_MWiOGuFr2n
</details>

Again, even with the better quality icon, some corners of the 'v' had to be straightened out.

**Review by adamrusted — APPROVED** [review]
So your icon is now a lot cleaner than the official icon @sjstark 😅
While I'm happy with this icon, given the small differences (see image below, your PR in red) I'll ask that another @simple-icons/maintainers takes a look at this before we merge.
image

**Comment by sjstark** [comment]
@adamrusted, I wasn't quite sure the best practice you guys use in this scenario. I think it's clear that their logo isn't intended to have the hard corners (if you look at the inner-right corner of the top left, the original was quite messed up)

I believe when I "corrected" these, I just straightened out the handles (made them inline with the straight edges) and it created the more uniform curves. If desired, I can revert it back, but that's when the corners had odd bumps that aren't noticeable until it's in larger scale.

**Comment by adamrusted** [comment]
> @adamrusted, I wasn't quite sure the best practice you guys use in this scenario. I think it's clear that their logo isn't intended to have the hard corners (if you look at the inner-right corner of the top left, the original was quite messed up)

Yeah - the corners of the `V` are quite messy in the original - I think we just need another @simple-icons/maintainers sign-off on this due to the fact you've done a _much better job than VectorWorks did themselves 😅_

**Review by service-paradis — APPROVED** [review]
LGTM 💯 
Thank you @sjstark for your work on this one!

**Pull request merged**
