### PR TITLE
#932 update Evernote icon for new brand

### PR DESCRIPTION
**Pull request by augbog**
I went and updated the Evernote icon to align with the new brand :) Let me know if there are any issues.

This is a preview of what it looks like locally.

screen shot 2018-08-14 at 1 30 48 pm

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Where did you find the new SVG @augbog ?

**Comment by augbog** [comment]
@ericcornelissen I work at Evernote so I resized and modified it to fit simple-icons straight from the source! I simply took it from one of the brand assets we were given :P 

For reference: 
https://evernote.com/blog/ceo-notebook-evernote-brand/

If you need a confirmed source of where the SVG itself is being used, I can also find one.

**Comment by ericcornelissen** [comment]
@augbog we prefer a link to a page where the icon source (and colour) can be found (if one exists), I found [this](https://brandfolder.com/evernote) linked on your [press page](https://evernote.com/press), I am okay with either 😄

**Comment by augbog** [comment]
Oh nice thanks! (Embarassing you found it easier than I did even though I work here 🤣. I'll update the link in the JSON

**Comment by birjolaxew** [comment]
:+1: Thanks for the contribution! It is much appreciated.

**Pull request merged**
