### PR TITLE
Add Synapse

### LINKED ISSUE #5188: Request: Synapse Icon
**Brand Name:** Synapse
**Website:** https://synapse.org/
**Alexa rank:** [727,373](https://www.alexa.com/siteinfo/synapse.org)
  

**Official resources for icon and color:**
  
https://www.synapse.org/images/logo.svg

### PR DESCRIPTION
**Pull request by tschaffter**
synapse

**Issue:** Fixes #5188
**Alexa rank:** [727,373](https://www.alexa.com/siteinfo/synapse.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Adapted from the [official logo of Synapse](https://www.synapse.org/images/logo.svg), a collaborative platform to organize digital assets and conduct research.
- The logo has been adapted using Adobe Illustrator according to the Contribution Guide of Simple Icons.

### CODE REVIEW

**Comment by adamrusted** [comment]
Hi @tschaffter - welcome to Simple Icons, and thanks for your work on this one!

Unfortunately, on the Alexa Rank alone this brand does not meet our [criteria for inclusion](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon). Is there another metric listed there that we could use when measuring the popularity of Synapse as a product?

**Comment by tschaffter** [comment]
Hey @adamrusted,

Here is a brief introduction to Synapse and its impact on the biomedical research community. I hope that this information will be useful to you when deciding whether or not to add Synapse icon to Simple Icons.

[Synapse](https://www.synapse.org/) is a collaboration platform that has been increasingly popular among the biomedical research community. Since 2006, Synapse is used to organizes the [DREAM Challenges](http://dreamchallenges.org/). First conceived by IBM, DREAM Challenges have addressed objectives that range from predictive models for disease progression to building AI models that predict whether a patient will develop breast cancer in the next 12 months. Designed and run by a community of researchers, DREAM Challenges invite participants to propose solutions, fostering collaboration and building communities in the process. Example of recent highly-visible challenges in the biomedical research community include:

- [The Digital Mammography DREAM Challenge](https://sagebionetworks.org/research-projects/digital-mammography-dream-challenge/) sponsored by IBM, AWS, the White House Cancer Moonshot and the Laura and John Arnold Foundation. The challenge featured a $1M prize money.
- [The COVID-19 EHR DREAM Challenge](https://www.synapse.org/#!Synapse:syn21849255/wiki/601865) supported by the National Center for Data to Health (CD2H), National Center for Advancing Translational Sciences (NCATS), the National COVID Cohort Collaborative (N3C), and the University of Washington.

The DREAM and Synapse community aims at promoting the development of [open-source and FAIR tools](https://docs.google.com/presentation/d/1Lu-xCekLKu85LgBlZaaM0CyZKoH9nD5lRRaR9tlkmXM/edit#slide=id.g5106dd9b14_0_0). This community is particularly active on GitHub where the source code of tools is provided. One of the motivation for registering the Synapse icon with Simple Icons is to enable developers to created shields.io badges that redirect to different projects on Synapse as well as displaying information about a tool queried from the Synapse API (e.g. information on how performant a tool is at solving a given biomedical task).

**Comment by adamrusted** [comment]
Hi @tschaffter, thanks for clarifying!
Unfortunately, Synapse and DREAM Challenges are both outside of our scope at the moment. You're more than welcome to keep an eye on the [Alexa Rank](https://www.alexa.com/siteinfo/synapse.org) of Synapse, and once it's 500,000 or less re-open the issue / PR. In the mean time, you can Base64-encode the SVG and include it in a shields.io badge - to enable people to use them as you mentioned above.

I'll leave this open until Monday - just in case the rank drastically increases, but if it doesn't get near our criteria then I'll have to close them as 'out of scope' for now. Thanks for your work on this, and fingers crossed we can look to add the icon to our package in the near future!

**Comment by tschaffter** [comment]
Thanks @adamrusted for having taken the time to review this submission. I'm looking forward to resubmit the icon when Synapse Alexa rank meets the requested Alexa Rank.

**Comment by adamrusted** [comment]
Closing for now, as the Alexa Rank seems to be stabilized where it was 4 days ago. Thanks for taking the time to work on this one @tschaffter, and as I mentioned above - you're more than welcome to re-open this PR and issue should the rank increase.

**Pull request closed without merging**
