### PR TITLE
Add webhint icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** N/A
**Alexa rank:** [~166k](https://www.alexa.com/siteinfo/webhint.io)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I took the logo from https://github.com/webhintio/webhint.io/blob/5c9f10a33a6d68e1f0d2b1eff0829685b9123433/src/webhint-theme/source/images/webhint-logo.svg
- I used Inkscape to remove unused path and to scale
  - I only kept the narwhal like the favicon
- I optimized it
- I used the main color used in their stylesheet

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I think we'll need to include the circle here, @service-paradis; other than their favicon, they're pretty consistent in using it everywhere, such as their GH org and their social media sites.

Other than that, their are a few imperfections in the original (where the blowhole would be and a couple in the tusk) which I don't know if we should clean up - I can't tell if they're intentional or not!

**Comment by service-paradis** [comment]
> I think we'll need to include the circle here, @service-paradis; other than their favicon, they're pretty consistent in using it everywhere, such as their GH org and their social media sites.

You're right, let me give this another try

> Other than that, their are a few imperfections in the original (where the blowhole would be and a couple in the tusk) which I don't know if we should clean up - I can't tell if they're intentional or not!

I asked myself the same question. Since it could be intentional, I did not fix them. Let me know if you think I should!

**Comment by service-paradis** [comment]
Here is the new version with the circle
image

**Review by PeterShaggyNoble — APPROVED** [review]
Looks good to me, @service-paradis :+1: Let's assume those imperfections are intentional, particularly the blowhole one, and run with them.

The only other thing I spotted was a duplicate point at the top of the inner curve of the circle - can you see if you can remove that? Sometimes it's a result of the optimisation process so, if it can't be removed then this can be merged straight in.

**Comment by service-paradis** [comment]
> The only other thing I spotted was a duplicate point at the top of the inner curve of the circle - can you see if you can remove that? Sometimes it's a result of the optimisation process so, if it can't be removed then this can be merged straight in.

Just gave it another try :)

**Comment by PeterShaggyNoble** [comment]
Perfect 🙂 Nice work, @service-paradis.

**Pull request merged**
