### PR TITLE
Avoid raw asset URLs

### PR DESCRIPTION
**Pull request by LitoMore**
The raw image path file does not make it easy for maintainers to view the relevant history of the source file.

### CODE REVIEW

**Review by uncenter — APPROVED** [review]

**Comment by uncenter** [comment]
Should wait for the second review but this is a nice change!

**Review by mondeja — COMMENTED** [review]
I think that we can use `if then else` JSONSchema constructs for this, just like the github one, see: https://github.com/simple-icons/simple-icons/blob/55b5a43a032ada6e2f0b78dc65c5bb16561517f0/.jsonschema.json#L682-L689

**Comment by mondeja** [comment]
I'm not totally against this approach but I think that the JSONSchema spec would be more reusable and would save us code to maintain.

**Comment by LitoMore** [comment]
The error message from JSONSchema is not human-friendly. It shows a super long regex pattern to our contributors. We've had a few cases where they didn't understand the error message.

**Review by mondeja — APPROVED** [review]
Okay, let's go with this 👍🏼 

> The error message from JSONSchema is not human-friendly. It shows a super long regex pattern to our contributors. We've had a few cases where they didn't understand the error message.

Probably it would be worth to migrate the Github URLs checking of JSONSchema to our linting script. Other solution would be to use [this trick](https://www.npmjs.com/package/jsonschema#localizing-error-messages) to make error messages more human friendly, thus maintaining all the possible validation at JSONSchema side.

**Pull request merged**
