### PR TITLE
Add lint rule to prohibit negative zeros within paths

### LINKED ISSUE #4304: Check '-0' numbers in paths
Reviewing #4262 I've found that, at least one icon (`itch-dot-io.svg`) has some `-0` numbers in their path which must be replaced by `0`. Must be added another linter rule :sweat_smile:?

This is not urgent, but a reminder for the future...

### PR DESCRIPTION
**Pull request by mondeja**
Closes #4304 

I've bumped the minimum NodeJS version required for local testing to 12.4.0 because [`String.prototype.matchAll` was included in that version](https://node.green/#ES2020-features-String-prototype-matchAll). This not affects CI because [current stable version used by `actions/setup-node` is 12.20](https://github.com/actions/node-versions/blob/main/versions-manifest.json#L528).

### CODE REVIEW

**Comment by ericcornelissen** [comment]
@mondeja, did you try and fix the problem in either of the now-ignored SVGs? I tried with Godot Engine but wasn't able to fix it with any of the following paths:

```html
<!-- replace "-0" by " 0" --><svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Godot Engine icon</title><path d="M9.559 0.689c-1.096 0.244-2.181 0.583-3.198 1.095 0.023 0.898 0.081 1.758 0.199 2.632-0.395 0.253-0.81 0.47-1.178 0.766-0.375 0.288-0.758 0.564-1.097 0.901-0.678-0.448-1.396-0.869-2.135-1.241-0.797 0.857-1.542 1.782-2.15 2.818 0.458 0.741 0.936 1.435 1.452 2.094h0.014v6.356c0.012 0 0.023 0 0.035 0.003l3.896 0.376c0.204 0.020 0.364 0.184 0.378 0.389l0.12 1.72 3.399 0.242 0.234-1.587c0.030-0.206 0.207-0.358 0.415-0.358h4.111c0.208 0 0.385 0.152 0.415 0.358l0.234 1.587 3.399-0.242 0.12-1.72c0.014-0.205 0.174-0.369 0.378-0.389l3.895-0.376c0.012 0 0.023-0.003 0.035-0.003v-0.507h0.002v-5.848h0.014c0.516-0.659 0.994-1.353 1.452-2.094-0.608-1.036-1.354-1.961-2.151-2.819-0.739 0.372-1.457 0.793-2.135 1.241-0.339-0.337-0.721-0.613-1.096-0.901-0.369-0.296-0.784-0.513-1.178-0.766 0.117-0.874 0.175-1.734 0.199-2.632-1.017-0.512-2.101-0.851-3.198-1.095-0.438 0.736-0.838 1.533-1.187 2.312-0.414-0.069-0.829-0.094-1.246-0.099h-0.016c-0.417 0.005-0.832 0.030-1.246 0.099-0.349-0.779-0.749-1.576-1.188-2.312l0.001-0.001zM6.476 9.994c1.297 0 2.349 1.051 2.349 2.348s-1.052 2.348-2.349 2.348c-1.296 0-2.348-1.051-2.348-2.348s1.051-2.348 2.348-2.348zM17.524 9.994c1.296 0 2.348 1.051 2.348 2.348s-1.051 2.348-2.348 2.348c-1.297 0-2.349-1.051-2.349-2.348s1.051-2.348 2.349-2.348zM6.701 10.924c-0.861 0-1.559 0.698-1.559 1.559s0.698 1.558 1.559 1.558c0.861 0 1.559-0.698 1.559-1.558s-0.697-1.559-1.559-1.559zM17.298 10.924c-0.861 0-1.558 0.698-1.558 1.559s0.697 1.558 1.558 1.558c0.861 0 1.559-0.698 1.559-1.558s-0.697-1.559-1.559-1.559zM12 11.377c0.417 0 0.757 0.308 0.757 0.687v2.162c0 0.379-0.339 0.687-0.757 0.687s-0.756-0.308-0.756-0.687v-2.162c0-0.379 0.339-0.687 0.756-0.687zM1.46 16.951c0.002 0.377 0.006 0.789 0.006 0.871 0 3.701 4.694 5.479 10.526 5.5h0.014c5.832-0.020 10.525-1.799 10.525-5.5 0-0.084 0.005-0.495 0.007-0.871l-3.502 0.338-0.121 1.729c-0.015 0.208-0.18 0.375-0.389 0.39l-4.181 0.296c-0.206 0-0.384-0.151-0.415-0.358l-0.238-1.614h-3.386l-0.238 1.614c-0.032 0.217-0.226 0.373-0.445 0.357l-4.151-0.296c-0.208-0.015-0.375-0.181-0.389-0.389l-0.12-1.729-3.504-0.337z"/></svg>
<!-- replace "-0" by " " --><svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Godot Engine icon</title><path d="M9.559 0.689c-1.096 0.244-2.181 0.583-3.198 1.095 0.023 0.898 0.081 1.758 0.199 2.632-0.395 0.253-0.81 0.47-1.178 0.766-0.375 0.288-0.758 0.564-1.097 0.901-0.678-0.448-1.396-0.869-2.135-1.241-0.797 0.857-1.542 1.782-2.15 2.818 0.458 0.741 0.936 1.435 1.452 2.094h0.014v6.356c0.012 0 0.023 -0 0.035 0.003l3.896 0.376c0.204 0.020 0.364 0.184 0.378 0.389l0.12 1.72 3.399 0.242 0.234-1.587c0.030-0.206 0.207-0.358 0.415-0.358h4.111c0.208 0 0.385 0.152 0.415 0.358l0.234 1.587 3.399-0.242 0.12-1.72c0.014-0.205 0.174-0.369 0.378-0.389l3.895-0.376c0.012 0 0.023-0.003 0.035-0.003v-0.507h0.002v-5.848h0.014c0.516-0.659 0.994-1.353 1.452-2.094-0.608-1.036-1.354-1.961-2.151-2.819-0.739 0.372-1.457 0.793-2.135 1.241-0.339-0.337-0.721-0.613-1.096-0.901-0.369-0.296-0.784-0.513-1.178-0.766 0.117-0.874 0.175-1.734 0.199-2.632-1.017-0.512-2.101-0.851-3.198-1.095-0.438 0.736-0.838 1.533-1.187 2.312-0.414-0.069-0.829-0.094-1.246-0.099h-0.016c-0.417 0.005-0.832 0.030-1.246 0.099-0.349-0.779-0.749-1.576-1.188-2.312l0.001-0.001zM6.476 9.994c1.297 0 2.349 1.051 2.349 2.348s-1.052 2.348-2.349 2.348c-1.296 0-2.348-1.051-2.348-2.348s1.051-2.348 2.348-2.348zM17.524 9.994c1.296 0 2.348 1.051 2.348 2.348s-1.051 2.348-2.348 2.348c-1.297 0-2.349-1.051-2.349-2.348s1.051-2.348 2.349-2.348zM6.701 10.924c-0.861 0-1.559 0.698-1.559 1.559s0.698 1.558 1.559 1.558c0.861 0 1.559-0.698 1.559-1.558s-0.697-1.559-1.559-1.559zM17.298 10.924c-0.861 0-1.558 0.698-1.558 1.559s0.697 1.558 1.558 1.558c0.861 0 1.559-0.698 1.559-1.558s-0.697-1.559-1.559-1.559zM12 11.377c0.417 0 0.757 0.308 0.757 0.687v2.162c0 0.379-0.339 0.687-0.757 0.687s-0.756-0.308-0.756-0.687v-2.162c0-0.379 0.339-0.687 0.756-0.687zM1.46 16.951c0.002 0.377 0.006 0.789 0.006 0.871 0 3.701 4.694 5.479 10.526 5.5h0.014c5.832-0.020 10.525-1.799 10.525-5.5 0-0.084 0.005-0.495 0.007-0.871l-3.502 0.338-0.121 1.729c-0.015 0.208-0.18 0.375-0.389 0.39l-4.181 0.296c-0.206 0-0.384-0.151-0.415-0.358l-0.238-1.614h-3.386l-0.238 1.614c-0.032 0.217-0.226 0.373-0.445 0.357l-4.151-0.296c-0.208-0.015-0.375-0.181-0.389-0.389l-0.12-1.729-3.504-0.337z"/></svg>
<!-- replace "-0" by "0" --><svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Godot Engine icon</title><path d="M9.559 0.689c-1.096 0.244-2.181 0.583-3.198 1.095 0.023 0.898 0.081 1.758 0.199 2.632-0.395 0.253-0.81 0.47-1.178 0.766-0.375 0.288-0.758 0.564-1.097 0.901-0.678-0.448-1.396-0.869-2.135-1.241-0.797 0.857-1.542 1.782-2.15 2.818 0.458 0.741 0.936 1.435 1.452 2.094h0.014v6.356c0.012 0 0.0230 0.035 0.003l3.896 0.376c0.204 0.020 0.364 0.184 0.378 0.389l0.12 1.72 3.399 0.242 0.234-1.587c0.030-0.206 0.207-0.358 0.415-0.358h4.111c0.208 0 0.385 0.152 0.415 0.358l0.234 1.587 3.399-0.242 0.12-1.72c0.014-0.205 0.174-0.369 0.378-0.389l3.895-0.376c0.012 0 0.023-0.003 0.035-0.003v-0.507h0.002v-5.848h0.014c0.516-0.659 0.994-1.353 1.452-2.094-0.608-1.036-1.354-1.961-2.151-2.819-0.739 0.372-1.457 0.793-2.135 1.241-0.339-0.337-0.721-0.613-1.096-0.901-0.369-0.296-0.784-0.513-1.178-0.766 0.117-0.874 0.175-1.734 0.199-2.632-1.017-0.512-2.101-0.851-3.198-1.095-0.438 0.736-0.838 1.533-1.187 2.312-0.414-0.069-0.829-0.094-1.246-0.099h-0.016c-0.417 0.005-0.832 0.030-1.246 0.099-0.349-0.779-0.749-1.576-1.188-2.312l0.001-0.001zM6.476 9.994c1.297 0 2.349 1.051 2.349 2.348s-1.052 2.348-2.349 2.348c-1.296 0-2.348-1.051-2.348-2.348s1.051-2.348 2.348-2.348zM17.524 9.994c1.296 0 2.348 1.051 2.348 2.348s-1.051 2.348-2.348 2.348c-1.297 0-2.349-1.051-2.349-2.348s1.051-2.348 2.349-2.348zM6.701 10.924c-0.861 0-1.559 0.698-1.559 1.559s0.698 1.558 1.559 1.558c0.861 0 1.559-0.698 1.559-1.558s-0.697-1.559-1.559-1.559zM17.298 10.924c-0.861 0-1.558 0.698-1.558 1.559s0.697 1.558 1.558 1.558c0.861 0 1.559-0.698 1.559-1.558s-0.697-1.559-1.559-1.559zM12 11.377c0.417 0 0.757 0.308 0.757 0.687v2.162c0 0.379-0.339 0.687-0.757 0.687s-0.756-0.308-0.756-0.687v-2.162c0-0.379 0.339-0.687 0.756-0.687zM1.46 16.951c0.002 0.377 0.006 0.789 0.006 0.871 0 3.701 4.694 5.479 10.526 5.5h0.014c5.832-0.020 10.525-1.799 10.525-5.5 0-0.084 0.005-0.495 0.007-0.871l-3.502 0.338-0.121 1.729c-0.015 0.208-0.18 0.375-0.389 0.39l-4.181 0.296c-0.206 0-0.384-0.151-0.415-0.358l-0.238-1.614h-3.386l-0.238 1.614c-0.032 0.217-0.226 0.373-0.445 0.357l-4.151-0.296c-0.208-0.015-0.375-0.181-0.389-0.389l-0.12-1.729-3.504-0.337z"/></svg>
<!-- replace "-0" by "" --><svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Godot Engine icon</title><path d="M9.559 0.689c-1.096 0.244-2.181 0.583-3.198 1.095 0.023 0.898 0.081 1.758 0.199 2.632-0.395 0.253-0.81 0.47-1.178 0.766-0.375 0.288-0.758 0.564-1.097 0.901-0.678-0.448-1.396-0.869-2.135-1.241-0.797 0.857-1.542 1.782-2.15 2.818 0.458 0.741 0.936 1.435 1.452 2.094h0.014v6.356c0.012 0 0.023 0.035 0.003l3.896 0.376c0.204 0.020 0.364 0.184 0.378 0.389l0.12 1.72 3.399 0.242 0.234-1.587c0.030-0.206 0.207-0.358 0.415-0.358h4.111c0.208 0 0.385 0.152 0.415 0.358l0.234 1.587 3.399-0.242 0.12-1.72c0.014-0.205 0.174-0.369 0.378-0.389l3.895-0.376c0.012 0 0.023-0.003 0.035-0.003v-0.507h0.002v-5.848h0.014c0.516-0.659 0.994-1.353 1.452-2.094-0.608-1.036-1.354-1.961-2.151-2.819-0.739 0.372-1.457 0.793-2.135 1.241-0.339-0.337-0.721-0.613-1.096-0.901-0.369-0.296-0.784-0.513-1.178-0.766 0.117-0.874 0.175-1.734 0.199-2.632-1.017-0.512-2.101-0.851-3.198-1.095-0.438 0.736-0.838 1.533-1.187 2.312-0.414-0.069-0.829-0.094-1.246-0.099h-0.016c-0.417 0.005-0.832 0.030-1.246 0.099-0.349-0.779-0.749-1.576-1.188-2.312l0.001-0.001zM6.476 9.994c1.297 0 2.349 1.051 2.349 2.348s-1.052 2.348-2.349 2.348c-1.296 0-2.348-1.051-2.348-2.348s1.051-2.348 2.348-2.348zM17.524 9.994c1.296 0 2.348 1.051 2.348 2.348s-1.051 2.348-2.348 2.348c-1.297 0-2.349-1.051-2.349-2.348s1.051-2.348 2.349-2.348zM6.701 10.924c-0.861 0-1.559 0.698-1.559 1.559s0.698 1.558 1.559 1.558c0.861 0 1.559-0.698 1.559-1.558s-0.697-1.559-1.559-1.559zM17.298 10.924c-0.861 0-1.558 0.698-1.558 1.559s0.697 1.558 1.558 1.558c0.861 0 1.559-0.698 1.559-1.558s-0.697-1.559-1.559-1.559zM12 11.377c0.417 0 0.757 0.308 0.757 0.687v2.162c0 0.379-0.339 0.687-0.757 0.687s-0.756-0.308-0.756-0.687v-2.162c0-0.379 0.339-0.687 0.756-0.687zM1.46 16.951c0.002 0.377 0.006 0.789 0.006 0.871 0 3.701 4.694 5.479 10.526 5.5h0.014c5.832-0.020 10.525-1.799 10.525-5.5 0-0.084 0.005-0.495 0.007-0.871l-3.502 0.338-0.121 1.729c-0.015 0.208-0.18 0.375-0.389 0.39l-4.181 0.296c-0.206 0-0.384-0.151-0.415-0.358l-0.238-1.614h-3.386l-0.238 1.614c-0.032 0.217-0.226 0.373-0.445 0.357l-4.151-0.296c-0.208-0.015-0.375-0.181-0.389-0.389l-0.12-1.729-3.504-0.337z"/></svg>
```

And it seems that whatever I try I get errors from other custom SVG linters and/or the SVG looks like:

image

**Comment by mondeja** [comment]
> I tried with Godot Engine but wasn't able to fix it with any of the following paths.

Have you rebuilt from source? Try this path (rounded to 4 decimals of precision):

```
M6.7002 10.9204c-.86 0-1.558.697-1.558 1.557s.698 1.5579 1.56 1.5579c.86 0 1.5579-.697 1.5579-1.558 0-.8599-.698-1.5579-1.56-1.5579zm10.5974 0c-.86 0-1.5579.697-1.5579 1.557s.698 1.5579 1.558 1.5579c.8619 0 1.5599-.697 1.5599-1.558 0-.8599-.698-1.5579-1.56-1.5579zM9.56.684c-1.097.243-2.1819.584-3.1998 1.095.025.897.083 1.7559.2 2.6299-.395.253-.81.47-1.178.767-.375.2879-.757.5639-1.096.8999-.6779-.448-1.3968-.868-2.1358-1.24-.797.859-1.54 1.785-2.1499 2.8219.458.74.936 1.432 1.452 2.0899h.015v6.3597h.035l3.8957.376c.204.02.363.185.377.39l.12 1.7198 3.3998.24.234-1.5849c.03-.206.207-.36.415-.36h4.1098c.208 0 .386.154.416.36l.235 1.586 3.3998-.242.12-1.72c.014-.204.173-.37.377-.39l3.8938-.374.035-.002v-.5079h.003V9.7505h.015c.516-.658.994-1.353 1.4519-2.094-.608-1.0349-1.353-1.9618-2.1499-2.8198-.74.373-1.458.795-2.1359 1.244-.34-.337-.72-.613-1.096-.9-.368-.298-.7839-.515-1.1779-.768.117-.8739.175-1.7349.2-2.6328-1.018-.512-2.1029-.85-3.1998-1.094-.438.736-.838 1.532-1.187 2.31-.413-.068-.83-.093-1.2449-.098h-.016c-.417.005-.832.03-1.245.1-.35-.78-.7499-1.576-1.1899-2.312zM6.4772 9.9905c1.297 0 2.3469 1.05 2.3469 2.3459 0 1.2969-1.05 2.3498-2.347 2.3498-1.2959 0-2.3498-1.0529-2.3498-2.3498 0-1.297 1.054-2.347 2.3499-2.347zm11.0474 0c1.296 0 2.347 1.05 2.347 2.3459 0 1.2969-1.05 2.3498-2.347 2.3498-1.298 0-2.3499-1.0529-2.3499-2.3498 0-1.297 1.052-2.347 2.35-2.347zM12 11.3705c.417 0 .756.3069.756.6859v2.1629c0 .38-.34.688-.756.688-.417 0-.756-.308-.756-.687v-2.16c0-.38.34-.6859.756-.6859zM1.4604 16.945c.002.376.007.79.007.872 0 3.6998 4.6948 5.4797 10.5265 5.4997h.014c5.8317-.02 10.5225-1.7999 10.5225-5.4997 0-.084.008-.496.01-.872l-3.5028.34-.12 1.727a.4218.4218 0 01-.39.39l-4.1498.2959h-.03a.4213.4213 0 01-.416-.36l-.236-1.612H10.31l-.24 1.613c-.03.216-.225.374-.444.358L5.4762 19.4a.4191.4191 0 01-.39-.388l-.12-1.7299z
```

**Comment by ericcornelissen** [comment]
> EDIT: I've done a naive replacement of -0 by <SPACE>0 at index 401 and it's working, there is no strange paths in the geometry as expected because -0 is the same as 0 for SVG path spec. Could you double check this.

That's what I did as well but I don't know what I did wrong earlier but indeed `<SPACE>0` works now...

However, if the _optimization_ of `-0` is `<SPACE>0` I'm not sure if it's worth linting for and complaining about to contributors :thinking:

**Comment by mondeja** [comment]
> However, if the optimization of -0 is <SPACE>0 I'm not sure if it's worth linting for and complaining about to contributors :thinking:

Think in cases like `m-0, 6` or `C35 -0...`

**Comment by ericcornelissen** [comment]
> Think in cases like m-0 6 or C35 -0.... Just -0 doesn't makes sense. It's not a huge optimization, it's a bit of sanity for the data.

I'm not terribly familiar with the syntax of SVGs, and I'd imagine neither are many contributors. What do those examples map to?

| With -0 | Without `-0` | Gain |
| --- | --- | --- |
| `0.023-0 0.035` | `0.023 0 0.035` | _nothing_ |
| `m-0 6` | ? | ? |
| `C35 -0...` | ? | ? |

In short, I would favor whatever SVGO outputs, and is allowed by the syntax, and what is the least amount of bytes over what is more readable. Depending on what the table above becomes we could still add this lint, but I wouldn't count the Godot Engine SVG as a problem.

**Comment by mondeja** [comment]
| With -0 | Without `-0` | Gain |
| --- | --- | --- |
| `0.023-0 0.035` | `0.023 0 0.035` | _nothing_ |
| `m-0 6` | `m0 6` | 1 character |
| `C35 -0...` | `C35 0...` | 1 character |

As you can see, less bytes and more readable. In fact, this improvement occurred to me when I was reading a path that I found confusing as it had a `-0` instead of `0`, beyond the optimization that could be.

> but I wouldn't count the Godot Engine SVG as a problem.

I can solve it in this pull and we don't have to ignore because the change only would be 1 character.

**Comment by ericcornelissen** [comment]
Okay, given that I'm in favor of adding this linting rule though I would still prefer to exclude cases like Godot Engine (where `-0` should be replaced by `<SPACE>0`) if possible, I'll leave this decision to you @mondeja (if you think you can implement it to begin with). I'm fine with not excluding these cases as they seem to be very rare.

If we don't exclude them, do you think the error message can be made more clear? As replacing `-0` by `0` in the old Godot Engine SVG didn't fix the problem.

**Comment by mondeja** [comment]
I understand you now :sweat_smile: It's specified in the error message since last commit: if the previous character is a number, the replacement should be `<SPACE>0`, but if the previous character is not a number, the replacement should be just `0`.

**Review by ericcornelissen — APPROVED** [review]

**Pull request merged**
