### PR TITLE
Update Twitch logo and color

### PR DESCRIPTION
**Pull request by augbog**
**Issue:**
Update Twitch logo and color

Screen Shot 2019-12-11 at 1 59 29 PM

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
A few weeks ago, Twitch unveiled an update to our Glitch logo and our color. I wanted to update it here as well.

Sources:
https://twitter.com/Twitch/status/1177259718135427072
https://brand.twitch.tv

(For direct link of the SVG source, you need to scroll all the way down on brand.twitch.tv and you'll see a download link to the brand assets)

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @augbog thanks for your contribution and for updating this icon 👍 

Looking at the .svg,  can you please center the icon both horizontally and vertically please.

**Comment by augbog** [comment]
Thanks for the feedback! Will try to get to that this week :)

**Comment by PeterShaggyNoble** [comment]
@augbog, are you still working on this one?

**Comment by ericcornelissen** [comment]
>are you still working on this one?

By now, I guess not. Anyone will to take this over can create a new PR (or continue on this PR if possible) 👍

**Comment by PeterShaggyNoble** [comment]
SVG updated.

Twitch

**Comment by ericcornelissen** [comment]
Thank you for the initial work @augbog and thanks for finishing the job @PeterShaggyNoble 🎉

**Comment by augbog** [comment]
So sorry 🙇 thanks for finishing this up for me @PeterShaggyNoble

**Pull request merged**
