### PR TITLE
Add GDevelop icon

### PR DESCRIPTION
**Pull request by TeerthTejani26**
Add GDevelop icon

gdevelop-preview

### CODE REVIEW

**Comment by TeerthTejani26** [comment]
Closes issue: #11623

**Comment by adamrusted** [comment]
Please ensure you follow our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon), this icon currently does not meet the specification we require.

**Comment by uncenter** [comment]
@TeerthTejani26 are you still interested in continuing this pull request?

**Comment by TeerthTejani26** [comment]
No, I am not interested in continuing this pull request.

I do apologize for not mentioning it earlier.
________________________________

**Pull request closed without merging**
