### PR TITLE
Added CodinGame

### LINKED ISSUE #4531: Request : CodinGame icon
**Name:** CodinGame
**Website:** https://www.codingame.com/
**Alexa rank:** [52.5 K](https://www.alexa.com/siteinfo/codingame.com)

**Official resources for icon and color:** [Media Kit CodinGame](https://www.codingame.com/work/fr/press/press-kit/)

### PR DESCRIPTION
**Pull request by adamrusted**
codingame

**Issue:** Closes #4531
**Alexa rank:** [22,383](https://www.alexa.com/siteinfo/codingame.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon and Hex extracted from AI file within logo resources.

### CODE REVIEW

**Comment by fbernhart** [comment]
@adamrusted The icon looks great! But where did you get the color from? The EPS file in the press kit has `#EDB41C` embedded.

**Comment by adamrusted** [comment]
> @adamrusted The icon looks great! But where did you get the color from? The EPS file in the press kit has `#EDB41C` embedded.

Looks like there's a fair few differences in colour even in the AI file. The small dot on the far right is `#FFD200`, while the main text is `#F2BB13`. I must've just taken the colour from the small dot - thinking it was all the same.

**Comment by fbernhart** [comment]
Somehow I can't open the AI file in Inkscape. Only the EPS file `CodinGame_Logo_Final_Full_transparent.eps`.
Opening the EPS file in Inkscape, I can see `#FBCF17` for the small dot and `#EDB41C` for the rest. 😄 

The website elements at https://www.codingame.com/work/press/press-kit use as well `#F2BB13`, so I would in in favor of using this color.

**Comment by adamrusted** [comment]
@fbernhart - have updated to `#F2BB13`

**Pull request merged**
