### PR TITLE
Microsoft Translator Icon

### PR DESCRIPTION
**Pull request by adsingh14**
**Issue:** #6840 
**Alexa rank:** 21
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

microsofttranslator

### CODE REVIEW

**Comment by adsingh14** [comment]
@service-paradis Please take a look at this icon, if possible.

**Comment by adsingh14** [comment]
@dirien Can you take a look at this icon?

**Comment by service-paradis** [comment]
There is no need to ask people for review. We do this on our free time and have already a lot of PR to review.

**Review by dirien — APPROVED** [review]
LGTM
image

**Pull request merged**
