### PR TITLE
Update Swarm icon

### PR DESCRIPTION
**Pull request by ericcornelissen**
Related to #616

- ~~Reduce the SVG to a single <path> element.~~
- Change the color to a primary web color (`#FFA633`). I couldn't [find](https://github.com/simple-icons/simple-icons/pulls?utf8=%E2%9C%93&q=swarm%20) anything about earlier choices related to this icon nor could I found a reliable source for the color.

### CODE REVIEW

**Comment by davidklebanoff** [comment]
Oh, this one is interesting.

So did you decide to redo this one because it has two paths? Because your outputted icon has two paths! Which of course is very interesting. It seems running the icon through SVGO outputs two paths for this icon, which challenges our assumption that the icons would all be reduced to one path! Perhaps our use of the tools is wrong,  or maybe the guidelines need to be updated to relax the rules a bit? I think a bit more investigation into what's going on here is needed.

It's probably worth looking into how many of our icons have 1 path vs more than one and understanding why that is. It's possible that we wrongly assumed only one was needed?

**Comment by ericcornelissen** [comment]
> So did you decide to redo this one because it has two paths?

Initially I did it because of the color, and then I saw the icon had two paths as well so I, indeed, tried to change that and didn't notice that SVGO changed it back 😅 


> Perhaps our use of the tools is wrong, or maybe the guidelines need to be updated to relax the rules a bit?

Given that SVGO is (more or less) the last step in the process of creating an icon, and it does output icons with multiple paths I think it is a good idea to relax that rule. Perhaps even removing it and trusting that SVGO gives a good enough icon.


> It's probably worth looking into how many of our icons have 1 path vs more than one and understanding why that is. It's possible that we wrongly assumed only one was needed?

After quickly going through the iconbase I found that there are certainly a number of icons with multiple `<path>`s, most of them have white space in them (e.g. Swarm, Event Store, Redis)

**Comment by davidklebanoff** [comment]
So, with some quick playing around with SVGOMG, it seems that it doesn't always optimize icons down to a single path. Even when tweaking various settings like multi-pass.

I'm curious as to why, but that's going to require some investigation that I don't have time for at the moment. It seems rather low priority anyway.

So with that said, this looks good to me!

**Comment by ericcornelissen** [comment]
> I'm curious as to why, but that's going to require some investigation that I don't have time for at the moment. It seems rather low priority anyway.

Same here 😅 I guess for the time being we could remove it from the Contributing Guidelines given the problems in #625, which can be done in #644?

**Comment by davidklebanoff** [comment]
@ericcornelissen Yeah, go for it.

**Pull request merged**
