### PR TITLE
Add SpaceX

### PR DESCRIPTION
**Pull request by birjolaxew**
**Issue:** #1257

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Big thanks to @metaa for finding the official SVG.

The "X" logomark is chosen over the full wordmark for reasons explained in #1257 
Now that I see it, I am starting to doubt that decision though. This is mostly due to the very off-center nature of the logomark, which doesn't mesh well with how Simple Icons is usually used. Two ways to solve this: use a version cropped to a square (like SpaceX use in their favicon) or use the full wordmark (my preferred solution) - or just use the logomark as in this PR.

<p align="center"><br /><br/><br/></p>

### CODE REVIEW

**Comment by davidklebanoff** [comment]
I think you chose the correct icon for the PR. It's consistent with their [Instagram](https://www.instagram.com/spacex/), [Twitter](https://twitter.com/spacex), [LinkedIn](https://www.linkedin.com/company/spacex/), etc. and I think keeps in line with the rest of Simple Icons.

It is a little odd in its positioning, but so are a lot of other icons. It's a known issue and this is where https://github.com/simple-icons/simple-icons/issues/477 comes into play. But even after #477 it may be off, as their brand seems to consider the proper center of the icon to be the middle of the X.

As for the color, I don't think white is correct. If one were to base the decision on their current website and social media, and followed the discussion in #1202, it should be black. However, as someone who has been following the company for a while and watched a bunch of launches, I would argue their brand color may actually be blue (unless it's changed recently). The logo on their rockets, capsule, and launch facility are all blue. So I'm not sure what it should be.

**Comment by metaa** [comment]
> As for the color, I don't think white is correct. [...] it should be black. However, [...] the logo on their rockets, capsule, and launch facility are all blue. So I'm not sure what it should be.

I just dug out this [SVG on Wikipedia](https://upload.wikimedia.org/wikipedia/commons/d/de/SpaceX-Logo.svg) (could've considered checking Wikipedia first 😅) and that one is blue aswell, though the X also has some gray.

**Comment by ericcornelissen** [comment]
Not sure how official this resource is (at least it matches the SVG on Wikipedia) but [SchemeColor.com](https://www.schemecolor.com/spacex-logo-colors.php) also lists `#005288`, at least for the _SpaceX Logo_ (they also have an [entry for the SpaceX website](https://www.schemecolor.com/spacex-website.php)).

Another resource I found is [this pdf](http://stotion.com/spacex/SpaceX-logo-corrections.pdf) which also uses blue (doesn't specify a hex though...), but again I'm not sure how official it is.

**Comment by metaa** [comment]
The PDF uses the same blue by the way.

**Comment by ericcornelissen** [comment]
Since I don't think there is going to be response from Elon anytime soon... Do we stay with the current color or switching to blue (probably `#005288`) @birjolaxew / @davidklebanoff ?

**Comment by metaa** [comment]
I'd use the blue since their logos use blue.

**Comment by birjolaxew** [comment]
I've updated the color to blue. I'll let another maintainer merge this in.

**Comment by ericcornelissen** [comment]
Thanks for your work on this way back @birjolaxew 👍

**Pull request merged**
