### PR TITLE
Rename Delicious as del.icio.us

### LINKED ISSUE #4791: Rename or Remove Delicious
Following on from the discussion in #4499, [the del.icio.us website](http://del.icio.us/) was actually shut down in 2019 but, as of December, there is now a holding page up stating that it should be back online this year without providing a firm date. Therefore, we should check whether it's back online yet prior to the `v5` release and consider it for removal if not.

If we are able to keep it then we should instead rename it as "del.icio.us", consistent with how it's stylised pretty much everywhere.

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
**Issue:** Fixes #4791
**Alexa rank:** [~78.5k](https://www.alexa.com/siteinfo/icio.us) (I'm assuming `del` is the only, or at least primary, subdomain)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description
Updates our existing "Delicious" icon to use the stylised "del.icio.us" name. As the new site is in an archived state, we should check the Alexa rank again before merging this.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
I guess this goes against what I said in #4936, but I think that when #4918 is merged the (custom) slug should be set to "delicious" (as you don't, presumably, call it "del-dot-icio-dot-us").

<sup>or we do go with removing `-` and `_` entirely and instead use custom slugs for e.g. ".Net"</sup>

**Comment by PeterShaggyNoble** [comment]
After reviewing a few other slugs for #5611, I am now of the opinion that would should, in rare cases, make allowances when the `.`s in a brand's name are not pronounced so I've updated this PR accordingly. This is probably no longer a breaking change now as it's just the `title`s in the JSON & SVG that are being changed, with the addition of a `slug` to allow the filename to remain unchanged.

**Review by ericcornelissen — APPROVED** [review]
Can confirm this would not be breaking :+1: 

I would be in favour of this approach. As it concerns a custom slug, I will leave it for at least one more @simple-icons/maintainers to approve this.

**Review by adamrusted — APPROVED** [review]
LGTM!

**Comment by adamrusted** [comment]
> Separately, we may want to once again consider removing this as their website has been down for a few days as their SSL cert expired on the 4th.

If you're willing to visit without the SSL, the site's still there - so I think we're okay to keep it for now. Good to keep an eye on though. Were we waiting for v5 on this one, or is it ready for merge now?

**Comment by ericcornelissen** [comment]
> Added "Delicious" as an alias for people searching for the un-stylised version. I added it as an aka rather than an old as they use it themselves in a few places.

Good call :+1: 


> > Separately, we may want to once again consider removing this as their website has been down for a few days as their SSL cert 
> > expired on the 4th.
> 
> If you're willing to visit without the SSL, the site's still there - so I think we're okay to keep it for now. Good to keep an eye on though. Were we waiting for v5 on this one, or is it ready for merge now?

I agree that an (recently) expired SSL certificate is not a reason for us to remove the icon.

This is good to merge, but I'll leave some time for @PeterShaggyNoble to respond to this discussion on removing it or not.

**Comment by PeterShaggyNoble** [comment]
Yup, agreed. If it's still down come the week of v5, we can discuss it then.

Merging this in, so.

**Pull request merged**
