### PR TITLE
Add building instructions to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ericcornelissen**
Added instructions to CONTRIBUTING.md on how to build and run the site locally. As someone who has virtually no experience with Jekyll, I just wrote down what I did to get it working 😅 If there is something wrong with it, or something that could be made simpler, please feel free to suggest any changes!

### CODE REVIEW

**Comment by birjolaxew** [comment]
Thanks! I've been thinking of writing this, but it must've slipped my mind ^^

Are you sure you cannot simply `jekyll serve`, without step 1-3? IIRC, `bundle exec jekyll serve` fails, but jekyll by itself works fine.

**Comment by ericcornelissen** [comment]
@birjolaxew you're absolutely right that `jekyll serve` is all you really need 👍 That way Jekyll also doesn't generate a ton of files that are not ignored by git 😅

**Comment by birjolaxew** [comment]
:+1: Going to leave this open until tomorrow to allow time for comment.

**Comment by benjaminwil** [comment]
👌

**Pull request merged**
