### PR TITLE
Updated Android

### PR DESCRIPTION
**Pull request by adamrusted**
android (1)

**Issue:** Contributes toward #4205
**Alexa rank:** N/A

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Slight change to SVG shaping from previous commit.
Updated source to Partner Marketing Hub.

### CODE REVIEW

**Comment by mondeja** [comment]
I'm a bit lost with the Google icons review, what is the exact source that you've used to update this @adamrusted?

**Comment by adamrusted** [comment]
> I'm a bit lost with the Google icons review, what is the exact source that you've used to update this @adamrusted?

Not entirely sure on this one. I'll go back to the brands website and see if the SVG source is available now 😅

**Comment by adamrusted** [comment]
@mondeja - I've updated this, with a link to the specific source page used.
I used the `monochrome black SVG`.

android

**Comment by mondeja** [comment]
I'm getting "No such object: pe-portal-consumer-prod-wagtail-static/documents/Android_logo_horizontal_greyscale.svg" in the `Details > Error` inside the SVG :thinking: I need a special permission from Google or this is the expected behaviour when the assets URLs are broken?

**Comment by adamrusted** [comment]
> I'm getting "No such object: pe-portal-consumer-prod-wagtail-static/documents/Android_logo_horizontal_greyscale.svg" in the `Details > Error` inside the SVG 🤔 I need a special permission from Google or this is the expected behaviour when the assets URLs are broken?

I've been getting these kinds of errors throughout the Google review, just seems that you're sometimes unable to download their icons. Full source of `Android logo_horizontal_greyscale.svg` (salvaged from my Recycle Bin!) below...

```svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 23.0.4, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 1045.5824 308.51538" style="enable-background:new 0 0 1045.5824 308.51538;" xml:space="preserve">
<style type="text/css">
	.st0{fill:none;}
</style>
<g>
	<rect class="st0" width="1045.5824" height="308.51538"/>
	<g>
		<path d="M131.08786,130.91409c12.40311,0,22.74167,6.37387,27.56635,13.2662v-11.54312h18.94763v86.1263h-13.56412
			c-2.97429,0-5.38351-2.40921-5.38351-5.38658v-6.15031c-4.82468,6.89233-15.16324,13.26309-27.56635,13.26309
			c-23.59531,0-41.51228-20.15233-41.51228-44.7878C89.57558,151.06953,107.49255,130.91409,131.08786,130.91409
			 M134.53418,148.14183c-15.33398,0-25.66933,12.0585-25.66933,27.56004s10.33534,27.56627,25.66933,27.56627
			c15.3338,0,25.66914-12.06471,25.66914-27.56627S149.86798,148.14183,134.53418,148.14183"/>
		<path d="M199.11728,132.63748h18.95387v11.71388c5.16293-8.61232,14.98607-13.43697,26.18152-13.43697
			c19.9817,0,32.90001,14.12619,32.90001,36.00162v51.84778h-13.56107c-2.97733,0-5.38977-2.40921-5.38977-5.38348v-43.35965
			c0-13.61392-6.88922-21.87851-17.91072-21.87851c-12.57382,0-22.21997,9.81693-22.21997,28.24617v42.37547h-13.56734
			c-2.97429,0-5.38654-2.40921-5.38654-5.38348V132.63748z"/>
		<path d="M333.65994,130.91409c12.40311,0,22.73865,6.37387,27.56314,13.2662V89.57558h18.94476v129.1879h-13.56128
			c-2.97427,0-5.38348-2.40921-5.38348-5.38658v-6.15031c-4.82449,6.89233-15.16003,13.26309-27.56314,13.26309
			c-23.60156,0-41.5155-20.15233-41.5155-44.7878C292.14444,151.06953,310.05838,130.91409,333.65994,130.91409
			 M337.10626,148.14183c-15.32773,0-25.66629,12.0585-25.66629,27.56004s10.33856,27.56627,25.66629,27.56627
			c15.32755,0,25.66611-12.06471,25.66611-27.56627S352.43381,148.14183,337.10626,148.14183"/>
		<path d="M401.68936,132.63748h18.94763v15.33391c3.27234-9.82314,12.91849-16.19701,22.74164-16.19701
			c2.40601,0,4.82471,0.17697,7.40463,0.69235v19.4662c-3.27234-1.03696-6.02625-1.55544-9.47238-1.55544
			c-10.85379,0-20.67389,9.1308-20.67389,26.35854v42.02776h-13.5611c-2.97427,0-5.38654-2.40921-5.38654-5.38348V132.63748z"/>
		<path d="M501.87805,220.4875c-25.49557,0-45.12933-19.81082-45.12933-44.78159c0-24.98007,19.63376-44.79089,45.12933-44.79089
			c25.49536,0,45.12915,19.81082,45.12915,44.79089C547.0072,200.67668,527.37341,220.4875,501.87805,220.4875 M501.87805,202.92134
			c15.1568,0,25.84003-11.89084,25.84003-27.21542c0-15.3308-10.68323-27.21854-25.84003-27.21854
			c-15.33096,0-26.01099,11.88774-26.01099,27.21854C475.86707,191.0305,486.54709,202.92134,501.87805,202.92134"/>
		<path d="M571.83557,113.86269c-6.88922,0-12.74158-5.68152-12.74158-12.74772c0-6.89235,5.85236-12.57386,12.74158-12.57386
			c7.06317,0,12.58008,5.68151,12.58008,12.57386C584.41565,108.18118,578.89874,113.86269,571.83557,113.86269
			 M562.36963,132.63655h18.94135v86.12941h-13.55481c-2.9743,0-5.38654-2.41231-5.38654-5.38658V132.63655z"/>
		<path d="M638.40076,130.91409c12.40308,0,22.74164,6.37387,27.56635,13.2662V89.57558h18.94763v129.1879h-13.56415
			c-2.9743,0-5.38348-2.40921-5.38348-5.38658v-6.15031c-4.82471,6.89233-15.16327,13.26309-27.56635,13.26309
			c-23.59534,0-41.51233-20.15233-41.51233-44.7878C596.88843,151.06953,614.80542,130.91409,638.40076,130.91409
			 M641.84705,148.14183c-15.3277,0-25.66626,12.0585-25.66626,27.56004s10.33856,27.56627,25.66626,27.56627
			c15.33075,0,25.66913-12.06471,25.66913-27.56627S657.1778,148.14183,641.84705,148.14183"/>
		<path d="M894.00989,186.2571c-5.27472,0-9.56543-4.29373-9.56543-9.56856c0-5.27481,4.29071-9.56544,9.56543-9.56544
			c5.27496,0,9.56543,4.29063,9.56543,9.56544C903.57532,181.96336,899.28485,186.2571,894.00989,186.2571 M788.27777,186.2571
			c-5.2749,0-9.56543-4.29373-9.56543-9.56856c0-5.27481,4.29053-9.56544,9.56543-9.56544
			c5.27472,0,9.56543,4.29063,9.56543,9.56544C797.8432,181.96336,793.55249,186.2571,788.27777,186.2571 M897.44067,128.63466
			l19.11835-33.11117c1.09607-1.90317,0.44403-4.33411-1.45605-5.43315c-1.90002-1.09595-4.33411-0.44397-5.43317,1.45608
			l-19.35748,33.5303c-14.80304-6.75573-31.42841-10.51857-49.16858-10.51857c-17.73999,0-34.36536,3.76284-49.1684,10.51857
			l-19.35748-33.5303c-1.09906-1.90005-3.53308-2.55202-5.43317-1.45608c-1.90002,1.09904-2.55511,3.52998-1.45605,5.43315
			l19.11835,33.11117c-32.82855,17.85489-55.28143,51.09024-58.5661,90.35484h229.72589
			C952.71912,179.7249,930.26624,146.48955,897.44067,128.63466"/>
	</g>
</g>
</svg>
```

**Comment by mondeja** [comment]
Thank you @adamrusted :pray: It seems that Google icons review will be hard...

**Review by mondeja — CHANGES_REQUESTED** [review]
I'm seeing differences in the eyes (source black, your version red). Surely it's a problem with optimization, could you use 4 decimals of precision?

image

**Review by mondeja — APPROVED** [review]
Perfect! :+1:

**Pull request merged**
