### PR TITLE
[Updated] Quora icon 2021 edition

### PR DESCRIPTION
**Pull request by adsingh14**
**Issue:** #95
**Alexa rank:** 341
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

> Did you manually vectorize the logo? 

 **Yes !** I used favicon as reference image and generated icon by setting `precision value: 4`.

quora

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @adsingh14,

I am not sure that the favicon is the "offical" logo of Quora? They even use the classic Q in the logo for their Q+ programm

image

**Comment by adsingh14** [comment]
> I am not sure that the favicon is the "offical" logo of Quora? They even use the classic Q in the logo for their Q+ programm

They've updated their official favicon to latest one including official website and app stores. You could check it yourself. I think this issue is related to Quora not it's program ?

**Comment by sachinraja** [comment]
I'm not sure this is the official logo either. It only seems to be used in some places. Is there a source (like a blog post) that their icon has been updated?

**Comment by LitoMore** [comment]
We can find this icon on their [official blog](https://quorablog.quora.com) and [Twitter](https://twitter.com/Quora).

**Comment by sachinraja** [comment]
I think that's good enough then, we can accept this new icon.

**Comment by adsingh14** [comment]
I wonder why did you ignore my reply from day 1 ! Well, that's the popular platform and have using this icon on their website and apps.

**Review by dirien — APPROVED** [review]
image
Looks good enough for me, @sachinraja you can merge it if you think too!

**Review by sachinraja — APPROVED** [review]

**Pull request merged**
