### PR TITLE
Schneider Electric icon 

### PR DESCRIPTION
**Pull request by adsingh14**
**Issue:** #6842
**Alexa rank:** 8,168
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Icon extracted from the official logo.

schneiderelectric

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
hi @adsingh14,

i get some differences, when i compare with the logo from the page:

image

Ask another @simple-icons/maintainers for input. Maybe i do smth. wrong?

**Comment by adsingh14** [comment]
> i get some differences, when i compare with the logo from the page:

I cropped icon from official logo (provided in Issue) instead of using top-bar/drop-down icon. Maybe, that creates the difference?

**Comment by dirien** [comment]
> > i get some differences, when i compare with the logo from the page:
> 
> I cropped icon from official logo (provided in Issue) instead of using top-bar/drop-down icon. Maybe, that creates the difference?

ok, i will check with this again! thx @adsingh14

**Review by dirien — APPROVED** [review]
Ok, looks good to me! Perfect fit!
image

**Pull request merged**
