### PR TITLE
Add Gentoo icon

### PR DESCRIPTION
**Pull request by foo-dogsquared**
**Issue:** #1592 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

They have an [official monochrome version](https://wiki.gentoo.org/wiki/Project:Artwork/Artwork#Variations_of_the_.22g.22_logo) so I picked that as the logo for this entry. 

The brand color (named Gentoo purple) is chosen from the [official color palette](https://wiki.gentoo.org/wiki/Project:Artwork/Colors). 

I manually "vectorized" the logo with Inkscape. 
Making a vector for this particular logo has gone through a weird process. 
With my amateur experience, I can't properly combine the individual nodes of the SVG. 
So I converted the SVG into a high-resolution PNG then vectorized it again to make a single `<path>` node. :|

### CODE REVIEW

**Comment by foo-dogsquared** [comment]
Basically, I tried to combine the logo into one path but there is always an overlap with the combinations I've had (thus, there's always manual editing required). 


So I tried to convert the vector into a high-resolution PNG then create a vector out of it.

**Comment by foo-dogsquared** [comment]
I'm going to update the SVG file. 
I just figured it out how to combine the nodes (without the overlap) now in Inkscape. :sweat_smile:

**Comment by ericcornelissen** [comment]
Thanks for you work on this one @foo-dogsquared your contributions over the past week mean a lot to us as maintainers of this project 😄

**Comment by foo-dogsquared** [comment]
I'm just getting into using Inkscape so I thought I could help out with this project as a starting point. 
I also appreciate your patience while I'm sorting things out. :) 
It means a lot for a new contributor.

**Pull request merged**
