### PR TITLE
Add FareHarbor icon

### LINKED ISSUE #4974: Fareharbor Icon
Hi,

I use the WP plugin Popular Brand SVG Icons - Simple Icons. Thank you for the useful plugin.

I would like to request the icon of Fareharbor to be added to simple icons. See: https://fareharbor.com/

Kindest,
frenkert

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** Close #4974
**Similarweb rank:** [2,794](https://www.similarweb.com/website/fareharbor.com/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Oooh, I though it would be an easy one! I had to do a lot of cleanup!

- I used `FareHarbor_BlackTicket_CutOut.eps` from https://fareharbor.com/about/logo/
- I used Illustrator to scale and convert
- I used Inkscape to to do some more cleanup
- I used https://jakearchibald.github.io/svgomg/ to optimize

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Looks like you has similar problems with the perforations as I did the few times I gave this a try - Inkscape did not want to play nice with them at all 🙁 I'm seeing differences in nearly all of them. Most of them are minor but the most pronounced is [the first one down on the right](https://user-images.githubusercontent.com/15157491/118789586-d5648900-b88c-11eb-9658-f12c4cee9e30.png) (your version in red). I'm also seeing [some hairline thin differences](https://user-images.githubusercontent.com/15157491/118790255-7d7a5200-b88d-11eb-86c9-bb1bf2ab8911.png) in ends of some of the beams. Would you mind having another look to see if you can clean those up?

**Comment by service-paradis** [comment]
Thank you @PeterShaggyNoble for the review and sorry for the mess 😅 
It looks like I broke the file I used for comparison... Will give this another shot today!!

**Comment by service-paradis** [comment]
I gave this one another try with manual improvements for the perforations. I also use a precision of 4 since 3 was messing too much with this icon.
Let me know if there are other improvements needed, every tools I'm trying does not play well with this icon 😅

**Comment by service-paradis** [comment]
Just updated this one with updated source. Took the icon from https://help.fareharbor.com/about/logo/ (`FareHarbor_BlackTicket_CutOut.eps`).
Trying to clean my old PRs, so if a @simple-icons/icon-review member want to check this out, it would be great!

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @service-paradis 🎉

**Pull request merged**
