### PR TITLE
Correct Apache

### PR DESCRIPTION
**Pull request by mondeja**
apache

**Issue:** #2887
**Alexa rank:** n/a

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The Apache icon looks incorrect, so I've corrected. This is the comparison between the Apache press-kit icon and the current one in simple-icons:

apache-main-update

### CODE REVIEW

**Comment by fbernhart** [comment]
LGTM! 👍🏼 

According to [their guidelines](https://www.apache.org/foundation/press/kit/) it seems like we unfortunately need to add the TM symbol.

> The appropriate trademark symbol(s), such as ® or ™, associated with the project's logo must be included in the logo;

**Comment by mondeja** [comment]
Feel free to do the merge if you see it right @fbernhart, but does not forget to select the option **"Squash and merge"** in the "Merge pull request" button :eyes:

**Comment by fbernhart** [comment]
@mondeja Ok, let me try to do my first GitHub merge ever! 😲 

But don't blame me, if the whole internet stops working afterwards. 😂

**Comment by mondeja** [comment]
My house is on fire now :house: :fire: :open_mouth:

Nah, we survived this one. Thanks for the merge @fbernhart!

**Pull request merged**
