### PR TITLE
OpsLevel Icon added #1736

### PR DESCRIPTION
**Pull request by pcsingh**
**Issue:** #1736

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Hi @pcsingh, could you provide some details on the brand you're trying to add? E.g. a link to their website. Also the PR thus far is not in line with our [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), have a look at it and try to update your Pull Request accordingly.

Let us know if you have any questions! :slightly_smiling_face:

**Comment by ericcornelissen** [comment]
Thanks for taking the time to contribute to this project @pcsingh! Unfortunately your work so far is not in line with our [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md). Could you update your Pull Request according to the description there?

Let us know here if you have any questions :slightly_smiling_face:

**Comment by bonez0607** [comment]
@birjolaxew was thinking of picking this one up since it's been stale a while. 

Would you want to include the wordmark? Looking quickly they use the boxes icon on [LinkedIn](https://www.linkedin.com/company/opslevel), but didn't see another reference elsewhere.

**Comment by birjolaxew** [comment]
@bonez0607 Yes, the logomark by itself is definitely the proper choice in this case.

**Pull request closed without merging**
