### PR TITLE
Add Puppeteer

### PR DESCRIPTION
**Pull request by theDavidBarton**
puppeteer

**Issue:** closes: #4789
**Alexa rank:** 103,921

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

  - Manually vectorized the logo with the help of this svg: https://cdn.svgporn.com/logos/puppeteer.svg
  - ... I've re-evaluated my life 😂

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
This looks pretty spot-on to me, @theDavidBarton, nice work 👍🏻 The only thing that stands out to me is that the lettering looks slightly thicker in your version than in [the original image](https://user-images.githubusercontent.com/10379601/29446482-04f7036a-841f-11e7-9872-91d1fc2ea683.png) but, as previously advertised, I'm pretty bad at comparing vector to raster so I'll let one of the other @simple-icons/maintainers throw an eye over it before asking you to make any changes.

Other than that, I'd suggest updating the colour to the `#40b5a4` used in their website's header.

> ... I've re-evaluated my life

Welcome to the dark side 😆

**Review by adamrusted — APPROVED** [review]
From a [quick comparison](https://user-images.githubusercontent.com/1830867/109943897-92ebd100-7ccd-11eb-827f-0797a5fd00eb.png) I'd be happy to go with this SVG. I do agree with @PeterShaggyNoble about the hex code, so if you could change that - that'd be great. Given that it's an original work from a raster image though, I'd ask that another @simple-icons/maintainers approves this too, before we merge it in.

**Review by mondeja — APPROVED** [review]
Wow good work @theDavidBarton! :muscle:
I also agree with @PeterShaggyNoble's suggestion about the hex code, so if you change it we can go ahead with the merge.

**Comment by theDavidBarton** [comment]
Thanks for the triple approval! I just changed the hex.

**Comment by PeterShaggyNoble** [comment]
Thanks, @theDavidBarton and, again, nice work 👍🏻 Looking forward to future contributions from you.

**Pull request merged**
