### PR TITLE
Updated Hexo

### PR DESCRIPTION
**Pull request by fbernhart**
hexo

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
The geometry looks perfect :+1:

Can you decrease the precision @fbernhart?

**Comment by fbernhart** [comment]
@mondeja Done 👍🏼

**Review by mondeja — CHANGES_REQUESTED** [review]
I'm seeing slight differences between your version (red) and [this at website header](https://d33wubrfki0l68.cloudfront.net/6657ba50e702d84afb32fe846bed54fba1a77add/827ae/logo.svg) (blue). Maybe has been updated or something strange have been happened decreasing the precision :thinking: Could you check that @fbernhart?

image

**Comment by fbernhart** [comment]
@mondeja Done

**Review by mondeja — APPROVED** [review]
Perfect :100:

**Pull request merged**
