### PR TITLE
Added #3021 - Apache Cloudstack icon

### LINKED ISSUE #3021: Request: Apache Cloudstack
**Name:** Apache Cloudstack
**Website:** cloudstack.apache.org
**Official resources for icon and color:** http://cloudstack.apache.org/trademark-guidelines.html

### PR DESCRIPTION
**Pull request by kshitishp**
Apache Cloudstack

**Issue:** Closes #3021

### Checklist
  - [ Y ] I updated the JSON data in `_data/simple-icons.json`
  - [ Y ] I optimized the icon with SVGO or SVGOMG
  - [ Y ] The SVG `viewbox` is `0 0 24 24`

### Description
  - Picked the official hex value.
  - Used the .ai file in the source URL for creating the .svg.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @kshitishp and thanks for the contribution:

A couple of things before this can be merged in, though:
1. The name should be "Apache CloudStack" (uppercase `S`).
2. The path needs to be centred vertically on the canvas.
3. Using the _[Apache CloudStack logo with "open source cloud computing" tagline and the Cloud Monkey (.ai file)](http://svn.apache.org/repos/asf/cloudstack/media/ai/apache_cloudstack_with_cloud_monkey.ai)_ from the source URL, I see a difference in the monkey's hand (see image below, with your version in red). Did you perhaps use a different source than that for your version?
4. Where did you source the colour from?

**Comment by kshitishp** [comment]
Thanks, Peter.

I had used a tool to convert the .ai file to .svg (I don't have Adobe
Illustrator). That must have changed a few things.

I'm checking it as I write this mail and I'll update the PR with the
correct version.

Cheers!

---
Kshitish Purohit <https://www.linkedin.com/in/kshitishpurohit/> / (91) 9899
382 887 <+919899382887>
Chief Product Officer @IndiQus <http://www.indiqus.com>

// This email is only intended for its recipients. If your name, or your
email ID, is not present in the recipients' list, or if you feel you got
this email by mistake, please delete this message, including any and all
attachments, immediately. This email is confidential and should be treated
as such.

**Comment by PeterShaggyNoble** [comment]
If it's any help, there are SVGs & PDFs available at https://apache.org/logos/#cloudstack

**Comment by PeterShaggyNoble** [comment]
Thanks for the quick update, @kshitishp.

The path looks spot on to me now but it still needs to be vertically centred. I agree with your choice of colour now but, as there are a couple of possible alternatives, we'll need on of the other @simple-icons/maintainers to weigh in to be sure.

**Comment by kshitishp** [comment]
Thanks, Peter.

Regarding vertical alignment, I've moved the artwork by a partial-pixel
distance to match the exact centre. I hope this does the trick.

Cheers!

---
Kshitish Purohit <https://www.linkedin.com/in/kshitishpurohit/> / (91) 9899
382 887 <+919899382887>
Chief Product Officer @IndiQus <http://www.indiqus.com>

// This email is only intended for its recipients. If your name, or your
email ID, is not present in the recipients' list, or if you feel you got
this email by mistake, please delete this message, including any and all
attachments, immediately. This email is confidential and should be treated
as such.

**Comment by PeterShaggyNoble** [comment]
Looks perfect to me now. Thanks for your efforts, @kshitishp :+1: Once someone else confirms your choice of colour, this can be merged in.

Incidentally, most editing software includes a way to align objects and paths to save you having to do it manually. In Inkscape, for example, "Align and Distribute" can be found at the end of the "Object" menu.

**Comment by kshitishp** [comment]
Sounds good :)

You’re right about the automatic alignment options but most tools align objects to the whole pixel and not to partials. I guess it depends on what tool is/was being used - I use Sketch and, interestingly, it lets you distribute partially but not align partially. So an object of 24 x 19.36 pixels would get aligned on a 24x24 board with some decimals to spare.

Will wait for the colour to get green-lit.
Cheers!


Kshitish Purohit / (91) 9899 382 887
Chief Product Officer @IndiQus

// This email is only intended for the recipients. If your name, or your email ID, is not present in the recipients’ list, or if you think you got this email by mistake, please delete this message immediately (including any and all attachments). This email is confidential and should be treated as such.

**Pull request merged**
