### PR TITLE
Add QuantConnect

### LINKED ISSUE #4287: QuantConnect Icon
**Name:** QuantConnect
**Website:** https://www.quantconnect.com/
**Alexa rank:** 78,816
  

**Official resources for icon and color:**
  
https://avatars0.githubusercontent.com/u/3912814?s=200&v=4

### PR DESCRIPTION
**Pull request by adamrusted**
quantconnect

**Issue:** Fixes #4287
**Alexa rank:** [53,420](https://www.alexa.com/siteinfo/quantconnect.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Based on SVG found by @PeterShaggyNoble - I was able to reduce some of the excess points down using Illustrator's Simplify tool. There's still 1 or 2 points that are a bit stubborn - but short of generating the icon from scratch from the SVG - this is the best I can manage.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Seeing few differences like [this one in the top right curve](https://user-images.githubusercontent.com/15157491/109639553-39599a00-7b47-11eb-85c1-04e39f38e347.png) but seeing as they're obviously as a result of you fixing imperfections in the original that shouldn't have been there, I'm happy to run with this as-is.

However, before we merge it, would you _mind_ taking a stab at recreating it from scratch just to see if that does get us any closer to the original?

**Comment by adamrusted** [comment]
Completely rebuilt using source SVG as reference. Looks like there's a slight imperfection to the inner circle, and the straight lines may not be exactly where they were on the source one, but I've centered them wherever possible.

**Review by PeterShaggyNoble — APPROVED** [review]
Nice work, @adamrusted. I'm happy to run with that as I'm guessing the source version was a bit rushed and it's all _supposed_ to be perfect circles and straight lines. Given the deviation from the source, though, we'll need one of the other @simple-icons/maintainers to sign off before merging.

Shame about the precision; once again it's the simplest of shapes causing us the most trouble when optimising! 😆

**Comment by adamrusted** [comment]
> Shame about the precision; once again it's the simplest of shapes causing us the most trouble when optimising! 😆

Give me a logo that's just straight edges any day of the week! 😅

**Review by mondeja — APPROVED** [review]
LGTM :100: Great work @adamrusted!

**Pull request merged**
