### PR TITLE
Added Ansible icon

### PR DESCRIPTION
**Pull request by rembik**
**Issue:**
#1452

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
  - Why did you pick the hex value?
  Most open source use cases are for Ansible Galaxy and Ansible Docs (both using picked hex value).
  - Did you manually vectorize the logo?
  Yes, because we want the symbol to be inverted into the outer circle.
  - Have you used multiple sources?
  No.

### CODE REVIEW

**Comment by birjolaxew** [comment]
The SVG is looking good! I do have my doubts about the color though, mostly because Ansible itself uses red for its favicon and logo pretty consistently. I'd personally vote for the red from [their header logo](https://www.ansible.com/hubfs/Images/logos/Logo-Red_Hat-Ansible-A-Reverse-SVG.svg), `#EE0000`.

(pinging @ericcornelissen and @davidklebanoff in case they want to weigh in)

**Comment by davidklebanoff** [comment]
Hi @rembik - Can you please clarify what you mean when you say you "manually vectorized" the logo. Typically, when we talk about manually vectorizing on this project it means someone took a rasterized version of the logo (e.g. `jpg` or `png`) and converted it to an `svg`. From the logos page, I see they have some official SVG versions ([example](https://www.ansible.com/hubfs/2017_Images/BrandPage/Brand-Assets/Community/Ansible-Mark-RGB_Black.svg?hsLang=en-us)) that one could convert to a monochrome version (no-fill and transparent) using an editor like Illustrator or Inkskape. Is that what you did? It's not quite clear.

I agree with @birjolaxew with regard to the color. I think `#EE0000` is a better fit.

**Comment by rembik** [comment]
Hi @davidklebanoff, it‘s exactly what I did.

The red color is for Ansible Tower and Rad Hat Ansible. For Ansible Community it‘s `#5BBDBF`, I think.
But hey, do as you want. Will you change it or should I?

**Comment by davidklebanoff** [comment]
@rembik - Thanks for clarifying!

Since red is the main color for the Ansible brand, I think it's the most appropriate for Simple Icons. I can update it myself, will only take a moment.

**Comment by ericcornelissen** [comment]
I definitely agree red is a more recognizable color for Ansible (at least for me). Anyway, thanks for adding the SVG for Ansible @rembik! It is very much appreciated 😃

**Comment by rembik** [comment]
Nice.
When will be the next time you merge the develop branch into master? I am looking forward to use this logo in another project that integrates simple-icons. ^^

**Comment by ericcornelissen** [comment]
I will create a Pull Request for that tomorrow, then it will be merged Monday at the latest 👍

**Comment by ericcornelissen** [comment]
@rembik see #1503 😉

**Pull request merged**
