### PR TITLE
Add Grubhub Icon

### PR DESCRIPTION
**Pull request by TomerPacific**
grubhub

**Issue: #3584**
**Alexa rank: 1,592** 

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
Followed the contribution guidelines, step by step. Hope I have done it correctly.

### CODE REVIEW

**Comment by runxel** [comment]
Hi @TomerPacific,
thanks for the PR! Please center the icon on the canvas, and also please don't distort it while scaling. Always scale uniformly to retain the original proportions. :)

**Comment by TomerPacific** [comment]
@runxel , thanks for responding. I've been trying to do all day, but have not been succeeding in doing so.

I am new to Inkscape and I watched a few videos based on the instructions in your recommendations page.

Even though I have centered the svg relative to the canvas and minimized the canvas size to be 24X24, I still get the errors from TravisCI.

Is there any in depth walkthrough or some guide I can look at so I will understand what I am doing wrong?

**Comment by runxel** [comment]
Hi @TomerPacific, from what you're telling you have been doing great; it's hard to tell where you made an error – the essential steps are correct. I don't know Inkscape well, so I neither can give you hints on any specific pitfalls there may be, sorry!

One thing I can tell for sure: the canvas is still messed up. Maybe try to make a new, empty file with the correct size (24×24) and copy the icon into that.
Also there the SVG is still not formed right: It has `width` and `height` tags. It's always better to use the CLI svgo, because then you can be sure the settings are all right.

I hope you can sort it out! Good luck

**Comment by TomerPacific** [comment]
@runxel ,
I've redone the whole thing again and the TravisCI is still failing on : 

```
x icons/grubhub.svg
  x icon-size Size of <path> must be exactly 24 in one dimension; the size is c
              urrently 23.596 x 4.947
```

I have no idea what I am doing wrong...

**Comment by adamrusted** [comment]
Marking this as abandoned, as the repository doesn't seem to exist any more. I'll try and fix the icon and submit a new PR. @TomerPacific please feel free to re-open this if you'd still like to contribute the icon.

**Pull request closed without merging**
