### PR TITLE
Add OpsLevel icon (#1736)

### PR DESCRIPTION
**Pull request by bonez0607**
**Issue:** #1736  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
1. logomark used as referenced in PR #1761 by @birjolaxew. Removed "OpsLevel" from svg-grabber
2. **Hex color:** `#1890FF` - Color taken from downloaded svg logo

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @bonez0607, thanks for picking up this issue and your work on this PR. 👍 

Can you please confirm the source used for the icon. Looking at the [site header logo .svg](https://www.opslevel.com/images/OpsLevelLogoText.svg) when compared to your PR version the lines are quite a bit thicker in the official version. Image below - official .svg red, PR version black placed on top.

I believe (https://www.opslevel.com/images/OpsLevelLogoText.svg) is the same .svg you would get with svg grabber so not sure why the lines would be different even after scaling down to 24px from 28.291px (height of the official logo). 

stroke-width

**Comment by bonez0607** [comment]
@ericcornelissen @phatbhoy67 - when I grabbed it and imported to Illustrator everything was a strokes line. I outlined the stroke looking to reduce the number of paths and am wondering if that’s why it ended up being a little larger. 

Will take another look when I get a chance, but might be another day or two

**Comment by phatbhoy67** [comment]
> it ended up being a little larger
Hey @bonez0607, thanks for replying. 

When you have the time to have a look at this again, the version you submitted in the PR has **thinner** lines than I would have expected, not thicker.

**Comment by PeterShaggyNoble** [comment]
Here's my attempt at it, @bonez0607, if it's any help - click the image to download. Your version is overlaid in red for reference.

[OpsLevel](https://github.com/simple-icons/simple-icons/files/3928078/opslevel.zip)

**Comment by PeterShaggyNoble** [comment]
@bonez0607, are you still working on this one?

**Comment by ericcornelissen** [comment]
@PeterShaggyNoble I think it is not a problem if you open a new PR for this brand (or, preferably, push changes to this PR if that is possible) 👍

**Comment by PeterShaggyNoble** [comment]
Updated the SVG in @bonez0607's branch.

**Comment by phatbhoy67** [comment]
Thanks for your work on this PR @bonez0607 and thanks to @PeterShaggyNoble for updating the .svg 👏 👍

**Pull request merged**
