### PR TITLE
Add iHeartRadio

### LINKED ISSUE #3102: iHeartRadio
**Name:** iHeart Radio
**Website:**
**Official resources for icon and color:** https://brand.iheart.com/

I've already uploaded a SVG without text here which I think is good

[iHeartRadio SVG ](https://github.com/NovaGL/icons/blob/master/iHeartRadio.svg)

### PR DESCRIPTION
**Pull request by thrash4life**
iheartradio

**Issue**: Closes #3102

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by thrash4life** [comment]
Crap - I need some help here @ericcornelissen and @PeterShaggyNoble 

I can't reduce the SVG down any further.

[iheartradio.svg.zip](https://github.com/simple-icons/simple-icons/files/4685281/iheartradio.svg.zip)

**Comment by thrash4life** [comment]
Sorry to spam but... 😆  
"DON'T use the Logo Mark itself should never be used without the correct usage of the Logo Type."

Does that exclude their mobile app and even the favicon on the brand site itself?

IMG_0737
IMG_0736

**Comment by NovaGL** [comment]
@thrash4life I agree, their branding is inconsistent. I just uploaded the Stitcher logo and and wondering the same thing.

**Comment by ericcornelissen** [comment]
It is not uncommon for brands to specify something in their brand guidelines that they don't adhere to themselves, typically in places such as app icons.

From my/our perspective, it is quite reasonable for them to do this (especially in places such as app icons) while requiring that _outsiders_ adhere to the guidelines. This is simply to ensure that you don't use their logo to mean something else.

Therefore, generally speaking, we prefer to follow explicit guidelines and include text if necessary even if app icons (or similar) do not include text.

**Comment by ericcornelissen** [comment]
> I can't reduce the SVG down any further.

Can you elaborate @thrash4life? I did not do a thorough comparison to the original, but this seems to match the source quite well.

**Comment by PeterShaggyNoble** [comment]
Other than it being a shade over `24` high, your SVG looks fine to me, too, @thrash4life.

**Comment by thrash4life** [comment]
iheartradio

**Comment by PeterShaggyNoble** [comment]
Looks perfect to me know - thanks for your efforts on this one, @thrash4life :+1:

**Comment by thrash4life** [comment]
> Looks perfect to me know - thanks for your efforts on this one, @thrash4life 👍

It was fun and I was happy to contribute again. Thanks for the encouragement and support @PeterShaggyNoble and @ericcornelissen

**Comment by PeterShaggyNoble** [comment]
Looking forward to your future contributions 🙂

**Pull request merged**
