### PR TITLE
Add the FFmpeg icon

### LINKED ISSUE #5384: FFmpeg icon
**Brand Name:** FFMpeg
**Website:** ffmpeg.org
**Alexa rank:**
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by wangwei1237**
ffmpeg

**Issue:** Fixes #5384
**Alexa rank:** [22,811](https://www.alexa.com/siteinfo/ffmpeg.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Add the FFmpeg icon for issue: https://github.com/simple-icons/simple-icons/issues/5384

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for contributing this @wangwei1237!
Before I get to reviewing the SVG itself, it looks like there's an issue with the centering of the icon (see https://github.com/simple-icons/simple-icons/pull/5537/checks?check_run_id=2430819867). Another issue that's appearing is that in the JSON you've labelled the icon as `FFMpeg`, whereas in the icon itself it is (correctly) labelled `FFmpeg`. Any chance you could update the JSON to match when you take a look at centering the icon?

**Comment by adamrusted** [comment]
Thanks for the update @wangwei1237 - though looking at the source SVG, I'm wondering if we should try and maintain the 3D effect (see below, with a 0.35pt gap between the front 'face' and the rest of the shape). Could I get the opinion of some other @simple-icons/maintainers before you put any more work into it though?

ffmpeg (1)

**Comment by PeterShaggyNoble** [comment]
@adamrusted, while I agree that that _does_ look better, their own monochrome version as seen in [their website](http://ffmpeg.org/)'s logo and favicon is just a flattened version of the entire shape.

**Comment by adamrusted** [comment]
> their own monochrome version as seen in their website's logo and favicon is just a flattened version of the entire shape.

Does that still mean the version in the PR needs to be updated to the flattened version of the 3d icon, as opposed to just the front face?

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for the update @wangwei1237 - though it looks like you've stretched the icon to fill the box (see yours in red, and source in black [here](https://user-images.githubusercontent.com/1830867/116808058-b943b680-ab2e-11eb-9972-2e450ba30cf9.png)). You need to keep the aspect ratio the same, so with the width being the higher value. My path is 24px (W) by 22.8468px (H) - should pass the linter once it's optimized. Would you mind taking another look at this?

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks @wangwei1237 - the icon matches up perfectly now!
One problem I'm spotting is that now you've introduced [unnecessary paths](https://user-images.githubusercontent.com/1830867/116820752-80c3cd00-ab6e-11eb-8d8c-ab8c73bde251.png) to the final SVG. I was able to fix this on my end in Illustrator by 'releasing' the compound path and using the 'Unite' tool. Could you take a quick look at that to try and remove the unnecessary points?

**Review by adamrusted — COMMENTED** [review]
Awesome, thanks for the update @wangwei1237!
My only other critique would be that there appear to be some unnecessary points in the middle of straight lines (see [here](https://user-images.githubusercontent.com/1830867/116851083-b22dae80-abe9-11eb-98eb-65ae21327283.png)), though as it's passing the linter - I'd be happy to merge this as-is if you can't remove them.

**Review by adamrusted — CHANGES_REQUESTED** [review]
I'm still seeing some differences around the edge of most of the image (see [here](https://user-images.githubusercontent.com/1830867/116974599-49603800-acb6-11eb-945d-fa9be9a04061.png) with PR in red, source in black) that may be a precision thing, but may also be easily fixed by moving the points to better match the original. Could you take a look at adjusting the image, and comparing against the original on your end @wangwei1237?

**Comment by wangwei1237** [comment]
> I'm still seeing some differences around the edge of most of the image (see [here](https://user-images.githubusercontent.com/1830867/116974599-49603800-acb6-11eb-945d-fa9be9a04061.png) with PR in red, source in black) that may be a precision thing, but may also be easily fixed by moving the points to better match the original. Could you take a look at adjusting the image, and comparing against the original on your end @wangwei1237?

let me try.

**Comment by wangwei1237** [comment]
> > I'm still seeing some differences around the edge of most of the image (see [here](https://user-images.githubusercontent.com/1830867/116974599-49603800-acb6-11eb-945d-fa9be9a04061.png) with PR in red, source in black) that may be a precision thing, but may also be easily fixed by moving the points to better match the original. Could you take a look at adjusting the image, and comparing against the original on your end @wangwei1237?
> 
> let me try.

I double-checked the latest version, and now all the issues raised before have been resolved. As a newcomer to svg, thank you very much for @adamrusted, @PeterShaggyNoble help. I am sorry for the time you consumed by the mistakes I take. Thanks again for your help @adamrusted, @PeterShaggyNoble.

**Review by adamrusted — APPROVED** [review]
> I am sorry for the time you consumed by the mistakes I take. Thanks @adamrusted, @PeterShaggyNoble again.

No worries! That's what we're here for!
The icon looks to match up perfectly now! Thanks for your work (and patience) on this one @wangwei1237! Hope to see some more contributions from you in the future! 💪

**Pull request merged**
