### PR TITLE
Add warning about v6.0.0 npm package deprecation to README

### PR DESCRIPTION
**Pull request by mondeja**
Added deprecation warning introduced in #6900 to README

### CODE REVIEW

**Comment by sachinraja** [comment]
We should probably just remove it from the README

**Comment by mondeja** [comment]
It couldn't be strange for users that have used it, if they come back to the README to see the documentation about simple-icons, to not find any about this type of import?

**Comment by sachinraja** [comment]
I don't think it'll be that confusing, but we can just add a note like this that it's been removed:
> Note: the old way of importing with `require('simple-icons/icons/[ICON SLUG])` is deprecated and will be removed in v7.0.0.

**Comment by mondeja** [comment]
I like it 👍🏼 

Done in https://github.com/simple-icons/simple-icons/pull/6967/commits/c71a9b92b2978643aa58ffd17a57917bbd6f7ace but used `:warning:` (:warning:) instead of `Note:`

**Review by sachinraja — APPROVED** [review]

**Pull request merged**
