### PR TITLE
Add haveibeenpwned icon (#2516)

### PR DESCRIPTION
**Pull request by phatbhoy67**
**Issue: #2516**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO ~or SVGOMG~
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Manual vector based on [favicon](https://haveibeenpwned.com/favicon.ico).

favicon

Hex value chosen is `#191919`from the website.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
@phatbhoy67 may I ask why you went with a manual vectorization instead of using Calibri to type "';--" into a whatever software you use and convert it to a path from that?

**Comment by phatbhoy67** [comment]
Hey @ericcornelissen I did start out with typing the text in Calibri, converting it to path and then used the bottom part of the semicolon (inverted and reversed) to replace the `'` to match the design of the favicon. I also used the favicon as a basis to adjust the character spacing.

That's why I described it as "Manual vector _based on_ favicon."

My thinking is that the favicon is a deliberate design, whereas the icon in the header is dependent on CSS rules (including fallback fonts), which means it might not be rendered exactly the same for everyone.

The `og:image` (https://haveibeenpwned.com/Content/Images/SocialLogo.png) 👇 for the front page also uses a similar version to the favicon.
og-image

**Comment by runxel** [comment]
Yeah I am not too sure about the color either.
Why not some of the blue tones? Would have expected that... 🤔

**Comment by phatbhoy67** [comment]
> Why not some of the blue tones?

I found a lot of blue/shades of blue, but none seem to be favoured over the other and buttons/highlights/CTAs etc all use different colours.

Do you have a favourite from the blue options I found @runxel? 👇 

`#2A6379`is the [calculated midpoint](https://meyerweb.com/eric/tools/color-blend/#0F1932:45ACBF:1:hex) of gradient `#0F1932` to `#45ACBF` front page.

Other blues include `#3a9ac4`, `#2e82a7`, `#2b5766`, `#337ab7`, `#2e6da4`, `#1a8cff`.

I chose `#191919` because it is used consistently across the site as the background colour and is similar to the favicon colour.

**Comment by runxel** [comment]
True, no easy decision overall! :)
But since there _is_ so much blue I'd still tend to use one. I like the gradient midpoint!

**Comment by PeterShaggyNoble** [comment]
I would have suggested going with the boxed version here as they also have one surrounding the full "logo", underneath the main header.

**Comment by ericcornelissen** [comment]
That is a decent argument in favor of the border, I initially didn't think it mattered one way or the other but that is definitely an argument in favor of the border 🤔 Good point @PeterShaggyNoble, any other opinions @simple-icons/maintainers?

**Comment by wolframroesler** [comment]
Great work, and super fast, thanks! (on behalf of KeePassXC where we're going to use it, cf. https://github.com/keepassxreboot/keepassxc/issues/1083)

**Pull request merged**
