### PR TITLE
Add Linktree

### LINKED ISSUE #3846: Linktree
**Name:** linktree
**Website:** https://linktr.ee/
**Alexa rank:** [482](https://www.alexa.com/siteinfo/linktr.ee)
  

**Official resources for icon and color:** 

```
<svg><path d="M7.385.43a.81.81 0 0 0-1.416 0l-5.292 9.6c-.246.493.123 1.047.677 1.047h3.57v3.63c0 .37.307.678.676.678h2.092c.37 0 .677-.308.677-.677v-3.631h-.984a.8.8 0 0 1-.8-.677c0-.123 0-.246.061-.37L9.6 4.676 7.385.43z"></path><path d="M12.062.43a.81.81 0 0 1 1.415 0l5.292 9.6c.246.493-.123 1.047-.677 1.047h-3.507v3.63c0 .37-.308.678-.678.678h-2.215a.683.683 0 0 1-.677-.677v-3.631H12a.8.8 0 0 0 .8-.677c0-.123 0-.246-.062-.37L9.785 4.677 12.062.43z"></path></svg>
```

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Linktree

**Issue:** Closes #3846
**Alexa rank:** [436](https://www.alexa.com/siteinfo/linktr.ee)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon & colour from SVG in website header; I went with the lighter green as they also use if for the buttons on their site. Unfortunately, I had to go with a precision of 4 to prevent SVGO from resizing it.

~This PR also removes an unnecessary JPG file that was inadvertently added in #4561~

### CODE REVIEW

**Comment by fbernhart** [comment]
Oops ... Sorry, I didn't notice that there was a JPG file added while reviewing #4561. Thanks for pointing out! 🏆

**Comment by fbernhart** [comment]
@PeterShaggyNoble Here is a path with a precision of 3. Feel free to use it.

```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Linktree icon</title><path d="M8.033 1.892a1.065 1.065 0 0 0-.971.547L.102 15.065c-.323.648.161 1.38.89 1.38h4.695v4.772c0 .487.404.892.89.892h2.75a.897.897 0 0 0 .892-.89v-4.775H8.924a1.052 1.052 0 0 1-1.05-.891c0-.162-.001-.325.079-.488l3.884-7.041-2.913-5.585a1.065 1.065 0 0 0-.891-.547zm7.937.003a1.065 1.065 0 0 0-.894.544l-2.995 5.587 3.884 7.039c.082.163.082.326.082.488a1.052 1.052 0 0 1-1.053.891H13.7v4.776a.898.898 0 0 0 .89.889h2.915a.899.899 0 0 0 .891-.892v-4.773h4.611c.729 0 1.215-.73.891-1.38L16.937 2.44a1.065 1.065 0 0 0-.967-.544z"/></svg>
```

Sometimes it helps resizing the icon to 23.999 or 24.001 instead before optimizing it. And then after the optimization it will be exactly 24.000. 😊

**Comment by PeterShaggyNoble** [comment]
Thanks, @fbernhart. However, I'm seeing a hairline difference at the bottom of the arrowheads when comparing your version (in red) with the original.

**Comment by PeterShaggyNoble** [comment]
> Makes me wondering if we could add a new rule to the linter, that quickly checks if only SVG files are located in the icons folder?

Yes, no harm in doing that, if it's possible - we've all accidentally pasted the wrong file into the wrong directory at some stage!

**Comment by ericcornelissen** [comment]
> > Makes me wondering if we could add a new rule to the linter, that quickly checks if only SVG files are located in the icons folder?
> 
> Yes, no harm in doing that, if it's possible - we've all accidentally pasted the wrong file into the wrong directory at some stage!

This could be added fairly easily to the [our-lint script](https://github.com/simple-icons/simple-icons/blob/develop/scripts/lint.js) using [`fs.readdir`](https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback)/[`fs.readdirSync`](https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_options) :+1:

**Comment by service-paradis** [comment]
> > > Makes me wondering if we could add a new rule to the linter, that quickly checks if only SVG files are located in the icons folder?
> > 
> > 
> > Yes, no harm in doing that, if it's possible - we've all accidentally pasted the wrong file into the wrong directory at some stage!
> 
> This could be added fairly easily to the [our-lint script](https://github.com/simple-icons/simple-icons/blob/develop/scripts/lint.js) using [`fs.readdir`](https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback)/[`fs.readdirSync`](https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_options) 👍

Maybe we could add a rule in .gitignore too to allow only SVG files.

**Comment by adamrusted** [comment]
> > > > Makes me wondering if we could add a new rule to the linter, that quickly checks if only SVG files are located in the icons folder?
> > > 
> > > 
> > > Yes, no harm in doing that, if it's possible - we've all accidentally pasted the wrong file into the wrong directory at some stage!
> > 
> > 
> > This could be added fairly easily to the [our-lint script](https://github.com/simple-icons/simple-icons/blob/develop/scripts/lint.js?rgh-link-date=2021-01-07T15%3A48%3A04Z) using [`fs.readdir`](https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback)/[`fs.readdirSync`](https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_options) 👍
> 
> Maybe we could add a rule in .gitignore too to allow only SVG files.
> 
> Something like:
> 
> ```
> #ignore all kind of files
> icons/*
> #except SVG files
> !*.svg
> ```

My bad! Sorry guys 😅
Obviously very keen to share the Zotero icon!

**Comment by ericcornelissen** [comment]
> Maybe we could add a rule in .gitignore too to allow only SVG files.
> 
> Something like:
> 
> ```
> #ignore all kind of files
> icons/*
> #except SVG files
> !*.svg
> ```

Perhaps that is a bit easier yes, not a bad idea! (Theoretically this can be circumvented, in contrast to the linter, but that's not something to worry about). Without the intention of hijacking this PR for this disussion, should this go in the root folder's `.gitignore` or a separate `.gitignore` inside the icons directory? :thinking: 


> My bad! Sorry guys sweat_smile
> Obviously very keen to share the Zotero icon!

No problem at all, it happens to the best of us :smile:

**Comment by PeterShaggyNoble** [comment]
I'd stick it in the root `.gitignore`, @ericcornelissen, to keep everything in one place.

**Comment by adamrusted** [comment]
@PeterShaggyNoble able to get it down to a precision of 3 by exporting from illustrator with the path being 24.0001px wide and using SVGO. Feel free to use below path:

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Linktree icon</title><path d="M7.953 15.066c-.08.163-.08.324-.08.486.08.517.528.897 1.052.89h1.294v4.776c0 .486-.404.89-.89.89H6.577a.898.898 0 0 1-.889-.891v-4.774H.992c-.728 0-1.214-.729-.89-1.377l6.96-12.627a1.065 1.065 0 0 1 1.863 0l2.913 5.585-3.885 7.042zm15.945 0l-6.96-12.627a1.065 1.065 0 0 0-1.862 0l-2.995 5.586 3.885 7.04c.081.164.081.326.081.487-.08.517-.529.897-1.052.89h-1.296v4.776c.005.49.4.887.89.89h2.914a.9.9 0 0 0 .892-.89v-4.775h4.612c.73 0 1.214-.729.89-1.377z"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
That works, thanks, @adamrusted. Update.

**Review by adamrusted — APPROVED** [review]
Amazing, thanks @PeterShaggyNoble! 🔗🌲

**Pull request merged**
