### PR TITLE
Added Fantom icon

### PR DESCRIPTION
**Pull request by deepmalamittal**
fantom

**Issue:https://github.com/simple-icons/simple-icons/issues/7013**
**Alexa rank:16138**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
HI @deepmalamittal,

thanks for the contribution. Unfortunatly i see some differences. Maybe up the precision to 4?

image

**Comment by deepmalamittal** [comment]
@dirien Changes have been implemented. Please take a look whenever you get a chance.
Let me know if some issue still prevails.

**Review by sachinraja — CHANGES_REQUESTED** [review]
Still noticing the same issues as @dirien.

**Comment by LitoMore** [comment]
CleanShot 2022-09-21 at 22 50 56@2x

Updated with precision 4.

**Pull request merged**
