### PR TITLE
Added Nextdoor icon

### LINKED ISSUE #515: Request: Nextdoor
Social network for neighborhoods.  Logo example here: https://nextdoor.com/newsroom/.

### PR DESCRIPTION
**Pull request by xdesro**
Closes #515. Let me know if any problems!

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Can I ask where you got the color from? I get `#00b246` both in the CSS and the downloaded logo ([this one](https://d19rpgkrjeba2z.cloudfront.net/0425e70a62d28fb1/static/nextdoorv2/images/newsroom/iTunesArtwork.png)).

Ps. you might want to check [this](https://d19rpgkrjeba2z.cloudfront.net/0425e70a62d28fb1/static/nextdoorv2/images/newsroom/iTunesArtwork.png) out to configure your git so your commits on Github are linked to your account 😉

**Comment by xdesro** [comment]
Hey @ericcornelissen, I just pulled it from the SVG fill code. Swapped to #00B246 though. 

Also, 
>Ps. you might want to check *this* out 

^This just links to the Nextdoor logo! Can you clarify what I'm doing wrong? 😂

**Comment by ericcornelissen** [comment]
Oops 😅 [here](https://help.github.com/articles/setting-your-commit-email-address-in-git/) you go (also updated the one in my original comment)

**Comment by xdesro** [comment]
Thanks for that! I must've had it misconfigured from my work email 🙄  Appreciate it, should be fixed now.

**Comment by birjolaxew** [comment]
:+1: Thanks for the contribution!

**Pull request merged**
