### PR TITLE
Add Yahoo!Japan icon

### LINKED ISSUE #7902: Request: Yahoo!Japan
### Brand Name

Yahoo!Japan

### Website

https://yahoo.co.jp/

### Popularity Metric

This website is one of the top Japanese news website.

https://www.similarweb.com/ja/website/yahoo.co.jp/

### Official Resources for Icon and Color

None

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by Poukame**
yahoojapan

**Issue:** closes #7902 

**Similarweb rank:**
[#17](https://www.similarweb.com/website/yahoo.co.jp/#overview)

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
Pick the hex color on the SVG logo.

### CODE REVIEW

**Comment by LitoMore** [comment]
I'm not sure this icon can be added. Such as Yahoo Japan, Yahoo China, Yahoo Korea, Amazon Canada, Amazon China, etc. We don't want so many duplicated brands in different regions in our repo.

We already have the [Yahoo](https://simpleicons.org/?q=yahoo) icon in our icon set. I think that is enough.

cc @simple-icons/icon-review Thoughts?

**Comment by Poukame** [comment]
@LitoMore No problem, it makes sense not duplicating. I had 5 min yesterday and decided to fulfill an open issue :)

@naohanpen, if you need the SVG for whatever reason, grab it in the commit, or I can send it to you if you wish.

**Comment by naohanpen** [comment]
@LitoMore @Poukame 
Hi !!
If you have a policy of not complicating things, then surely the existing icons are sufficient.
Thank you for your consideration.
If possible, I would appreciate an SVG.
( Please understand that this is a machine translation. )

**Comment by Poukame** [comment]
> If possible, I would appreciate an SVG.

[You can grab it here.](https://github.com/simple-icons/simple-icons/blob/671d7b81f14b3cdfc94a73ecc23885806cd9241a/icons/yahoojapan.svg)

**Comment by naohanpen** [comment]
> > If possible, I would appreciate an SVG.
> 
> [You can grab it here.](https://github.com/simple-icons/simple-icons/blob/671d7b81f14b3cdfc94a73ecc23885806cd9241a/icons/yahoojapan.svg)
> 

Thank you for your kindness 🙇🏻‍♂️

**Comment by adamrusted** [comment]
Closing as discussion resulted in use of standard Yahoo! icon.

**Pull request closed without merging**
