### PR TITLE
Update Write.as

### LINKED ISSUE #10143: Update Write.as
### Brand Name

Write.as

### Official Resources for Icon and Color

Use logomark found [here](https://write.as/brand) with the blue colour used in most examples.
Permission should be sought from Matt Baer before merging.

### Additional Comments

We've been given explicit approval from the founder of `Write.as` to use the single letter version in monochrome, see screenshot below.

image

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Write.as

**Issue:** closes #10143

**Similarweb rank:** [63179](https://www.similarweb.com/website/write.as)

### Checklist
- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
Having received permission to do so, but still pending review & approval by Matt Baer, this PR reverts our Write.as icon to our previous version, which lines up with [this logomark](https://cdn.writeas.net/img/w-sq.svg) found at [source](https://write.as/brand).

### CODE REVIEW

**Comment by adamrusted** [comment]
Have emailed Matt just now.

**Comment by thebaer** [comment]
Thanks for looping me in on this -- looks good to me!

This is totally non-critical, but on the filename, I'd note that the "dot" isn't part of the name as spoken aloud, i.e. it's meant to be said like "write as", so it's conventionally shortened to "writeas" in things like filenames. Totally up to you how you want to handle that here, but I wanted to mention it.

Either way please feel free to merge, and thanks for including us in Simple Icons!

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to review this, @thebaer, and for the approval; it's very much appreciated.

On the filename, that's down to our naming conventions, whereby the filename is constructed from the brand's `title`. The decision was made way back when that, as the number of instances where the `.` in a brand's name is pronounced far outweighed the number of instances where it isn't that it should be included in the filename. However, we do have provision to override the filename using a custom `slug` entry, which we could use here if you'd prefer to remove the `dot` .

@adamrusted, as this is simply reverting to our previous Write.as icon, this can be merged straight in unless you'd like to throw an eye over it first - I've already done a comparison with the currently available source icon.

**Comment by adamrusted** [comment]
@PeterShaggyNoble - awesome, I'll merge this straight in!
@thebaer - feel free to continue discussion here, if you'd prefer we change the slug to `writeas` instead of `writedotas` - that'd constitute a breaking change as far as our API is concerned, thankfully there's a release going out in the new year!

**Pull request merged**
