### PR TITLE
Updated Quasar

### PR DESCRIPTION
**Pull request by fbernhart**
quasar

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by mondeja** [comment]
I'm seeing same differences in the circle against source and current version. Could you check that @fbernhart?

image

**Review by mondeja — CHANGES_REQUESTED** [review]
I'm seeing same differences in the circle against source and current version. Could you check that @fbernhart?

image

**Comment by fbernhart** [comment]
@mondeja Done.

**Review by mondeja — APPROVED** [review]
Perfect :sparkles:

Thank you @fbernhart :+1:

**Pull request merged**
