### PR TITLE
Add React Navigation Icon

### LINKED ISSUE #8857: React Navigation icon missing
### Brand Name

React Navigation

### Website

https://reactnavigation.org/

### Popularity Metric

Similarweb rank: 104,989 https://www.similarweb.com/website/reactnavigation.org/#overview
Github stars: 22.5k https://github.com/react-navigation/react-navigation

### Official Resources for Icon and Color

Logo: 
spiro
Color: #7762BB from the logo
Other brand rules: unknown

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by RiteshK-611**
**Issue:** closes #8857

**Similarweb rank:**
Similarweb rank: 104,989 https://www.similarweb.com/website/reactnavigation.org/#overview
Github stars: 22.5k https://github.com/react-navigation/react-navigation

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This change resolves issue #8857 by adding React Navigation logo in reactnavigation.svg file and by updating simple-icons.json file with icon's data

### CODE REVIEW

**Review by LitoMore — CHANGES_REQUESTED** [review]
image


Personally, I can't accept this icon. This has so many control points and its file size is so big.

They should reprocess the icon with curves rather than one-by-one control points.

**Comment by RiteshK-611** [comment]
> image
> Personally, I can't accept this icon. This has so many control points and its file size is so big.
> 
> They should reprocess the icon with curves rather than one-by-one control points.

Just a question. From where do you get this view of logo? Is it available in Inkscape?

**Comment by LitoMore** [comment]
### Outline view mode

image

### Edit path by nodes mode

image

**Review by PratyushJayachandran — CHANGES_REQUESTED** [review]
Please merge the changes suggested to simplify the number of control points

**Comment by LitoMore** [comment]
As I mentioned before:

> They (the React Navigation team) should reprocess the icon with Bézier curves rather than one-by-one control points.

Personally, I think the current icon is not acceptable.

**Comment by RiteshK-611** [comment]
I improved this logo from my side, so @LitoMore can I suggest this version of the logo to them (React Navigation team)

**Comment by LitoMore** [comment]
@RiteshK-611 Yes, please.

**Comment by PeterShaggyNoble** [comment]
@RiteshK-611, do you have any updates on this?

**Comment by PeterShaggyNoble** [comment]
@RiteshK-611, in the interests of moving this along, can you update this PR with your improved version of the SVG or post the path in a comment and, if it lines up with the original, then we can proceed.

**Comment by PeterShaggyNoble** [comment]
Closing due to inactivity. We can't add their icon in its current state; if they ever provide a better version or someone can faithfully recreate it with a sensible number of points then this can be revisited in a new PR.

@RiteshK-611, if you _are_ still working on this then let us know and we'll reopen this PR for you.

**Pull request closed without merging**
