### PR TITLE
help scout icon

### PR DESCRIPTION
**Pull request by ghost**
helpscout

**Issue:** #6731
**Alexa rank:** 9,560
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
hi @ghost,

thanks for contributing, can you check the logo again. I see a difference. I think setting the precision to 4 while exporting can help 
image

**Comment by service-paradis** [comment]
Since the original user does not exist anymore (ghost is a Github user placeholder), they wont be able to make the requested changes. I'm closing this PR.

**Comment by dirien** [comment]
oh @service-paradis, lol! i did not looked on the avatar! Assumed its named ghost 😄

**Comment by service-paradis** [comment]
haha, no problem 🤣

**Pull request closed without merging**
