### PR TITLE
Add spring boot

### LINKED ISSUE #5683: Add Spring boot icon
Brand Name: Spring boot
Website: https://spring.io/projects/spring-boot
Alexa rank: 113.3 k (I entered the above website in the search bar but it returned stats about https://spring.io/)
Github Stars: 55.1 k

Official resources for icon and color: https://pbs.twimg.com/profile_images/1235868806079057921/fTL08u_H_400x400.png

(Sorry, I could not find any image or logo on their website)

### PR DESCRIPTION
**Pull request by echoaman**
Spring Boot

**Issue:** Closes #5683
**Alexa rank:** n/a ([subdirectory](https://spring.io/projects/spring-boot) of parent brand's site)
**GitHub stars** [~55.1k](https://github.com/spring-projects/spring-boot)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by echoaman** [comment]
Check now

**Comment by adamrusted** [comment]
Thanks for the contribution @echoaman, and welcome to Simple Icons!
Looks like the size of your SVG was impacted by the optimization process, resulting in your path being 23.995px wide instead of 24px wide, which the linter requires. Would you mind taking another look at editing this, making sure to keep the aspect ratio the same, just adjusting the width to suit?

**Comment by echoaman** [comment]
@adamrusted I will retry. Sorry for the troubles.

**Comment by adamrusted** [comment]
No problem! I've assigned myself to review this PR, so whenever you've made changes I'll take a quick look. If you're having difficulty with editing it, let me know here.

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks @echoaman - though it looks like you also stretched the height to fit 24px, which means the icon's aspect ratio has now been impacted (see yours overlaid in black over the original, in green [here](https://user-images.githubusercontent.com/1830867/118311872-67187300-b4e8-11eb-9e40-d8cbb9d94b1f.png)). Could you take another look at this, maintaining the correct aspect ratio so only the longest side is 24px?

**Review by adamrusted — CHANGES_REQUESTED** [review]
That's looking a lot closer to the source icon, thank you @echoaman!
There is still a little [stretching to the PR icon](https://user-images.githubusercontent.com/1830867/118320537-4e15bf00-b4f4-11eb-9c42-0f5cf78c4104.png) when compared to the source in green, though that may be down to the optimizer. It may work better if you optimize the source file to 4 decimals instead of 3, which is just a slider on SVGOMG - or a quick edit to `svgo.config.js` and running `npm run svgo -- icons/springboot.svg` to fix. Let me know if you need some more help with this one - I think we're nearly there though 💪

**Review by adamrusted — APPROVED** [review]
Looks great to me! Thanks for you continued work on this @echoaman! I'll merge this now, and it'll be in our release next Sunday! 🚀

**Pull request merged**
