### PR TITLE
Remove Tencent Weibo

### PR DESCRIPTION
**Pull request by fbernhart**
**Issue:** #3169 
**Alexa rank:** -

### ~Checklist~
  ~- [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)~
  ~- [x] I optimized the icon with SVGO or SVGOMG~
  ~- [x] The SVG `viewbox` is `0 0 24 24`~

### ~Description~
~I took the already used SVG.~
~I used Inkscape to fix size and center~
~I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG~

### Edit
This PR removes the Tencent Weibo icon from Simple Icons as the brand no longer exists. See the discussion below for details.

### CODE REVIEW

**Review by adamrusted — COMMENTED** [review]
According to Wikipedia, Tencent Weibo was scheduled to be shutdown in September 2020. Should this be marked for deletion in v5.0.0 @simple-icons/maintainers?

**Comment by mondeja** [comment]
> Should this be marked for deletion in v5.0.0 @simple-icons/maintainers?

Yes, I'm founding a lot of information in other websites about the closing announcement.

**Comment by ericcornelissen** [comment]
I'd say the relevant question is not whether the announcement is true but whether it has happened yet. As long as it is still active (e.g.. the website is online) when we want to merge this PR I'd say we merge it - it can be removed later if needed. Unfortunately I can't tell if it is still active :sweat_smile:

**Review by adamrusted — APPROVED** [review]
So I've been able to find the archived version of the official announcement [here](https://web.archive.org/web/20200905115413/http://t.qq.com/) which reads the following (in shakily Google Translated):

> Due to business adjustments, Tencent Weibo will be `held (?)` at 23:59 PM on September 28, 2020. ... If necessary, you can back up your relevant information before stopping the service.

Since that announcement visiting the domain presents a login screen, I imagine to forward you back to Tencent's other services. I think the above indicates we're good to set it for removal in v5.0.0, but as @ericcornelissen suggested above, I'm happy for us to merge this fix to the icon until then.

**Comment by ericcornelissen** [comment]
That seems pretty legitimate, let's hope anyone that speaks Chinese corrects us if necessary.

As for updating or removing it. Now, i'm not quite sure what our approach with this has been so far, but considering #3169 and the possibility of removing [the `.svglint-ignored.json` file](https://github.com/simple-icons/simple-icons/blob/61d0ea38b270873a6ecbdb8bd1a3fe5a31f608dd/.svglint-ignored.json) we might be better off updating those icons that should be removed first and then (possibly collectively in one PR) remove them in v5. Thoughts?

**Comment by fbernhart** [comment]
So far we've omitted updating them and instead directly marked them ready to be removed.

See: https://github.com/simple-icons/simple-icons/labels/breaking%20change

**Comment by ericcornelissen** [comment]
> So far we've omitted updating them and instead directly marked them ready to be removed.
> 
> See: https://github.com/simple-icons/simple-icons/labels/breaking%20change

I though so, but wasn't sure. I'm fine with that, just unfortunate that we can't remove `.svglint-ignore.json` until the v5 release.

**Comment by PeterShaggyNoble** [comment]
@fbernhart, could you update the original post to clarify that this PR will remove Weibo, please?

**Review by PeterShaggyNoble — APPROVED** [review]
Looks good to me 👍🏻 Once the conflicts have been resolved, this can be merged straight in.

**Pull request merged**
