### PR TITLE
Add 4D logo

### LINKED ISSUE #3415: Request 4D icon
**Name:** 4D
**Website:** https://www.4d.com
**Alexa rank:** 280,892
  

**Official resources for icon and color:**
  
  
image

### PR DESCRIPTION
**Pull request by midrissi**
**Issue:** Closes #3415 
**Alexa rank:** 280,892

4d

  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

4D is a development platform that lets you focus on your data model and your business rules, and then, takes care of running your application code natively on macOS and Windows.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @midrissi, and thanks for the PR :+1:

Before we can proceed to reviewing it, though, could you revert the changes made to `.svglint-ignored.json` to allow our automated linting and build scripts to run properly, please?

**Comment by midrissi** [comment]
> Before we can proceed to reviewing it, though, could you revert the changes made to `.svglint-ignored.json` to allow our automated linting and build scripts to run properly

Done! I have removed the line previously added to ignore the linting error.

> Could you also let us know where you sourced the file you based your version on - is it from an official vector or manually recreated from a raster file?

I am actually working at 4D. I got the official vector file from our graphic web designer. But, I have optimized it using SVGO.

**Comment by midrissi** [comment]
@PeterShaggyNoble Can someone please review the changes?

**Comment by midrissi** [comment]
I have fixed the conflicts of the merge and waiting for the merge to be done. Thanks

**Review by runxel — APPROVED** [review]
This looks all good to me. Thanks for your patience and your work, @midrissi! 💯

**Pull request merged**
