### PR TITLE
Fix absolute coordinate error in 'collinear-segments' lint

### PR DESCRIPTION
**Pull request by mondeja**
Fixed error with absolute coordinate pointer in `collinear-segments` lint rule. "Aseprite" icon should not be corrected, but "ManageIQ" and "New Japan Pro-Wrestling" instead. Thanks to @adamrusted for [report it](https://github.com/simple-icons/simple-icons/issues/4590#issuecomment-756759175).

### CODE REVIEW

**Comment by mondeja** [comment]
Has found another error in "New Japan Pro-Wrestling" and is not a false positive, so I'm going to merge this to avoid more updates.

**Comment by PeterShaggyNoble** [comment]
Is any action required on that NJPW icon as a result of this, @mondeja?

**Comment by mondeja** [comment]
Yes, there is a problem here:

image
image

The linter is warning for a repeated chained command at `l.31.123.31.123`.

**Comment by PeterShaggyNoble** [comment]
OK, I'll have a look at that later on today, see if I can fix it up. Thanks, @mondeja.

**Comment by PeterShaggyNoble** [comment]
Gave it a go but, unfortunately, everything I tried distorted the "T" in some manner. Could one of the other @simple-icons/maintainers have a look to see if they can figure it out, please?

**Pull request merged**
