### PR TITLE
Add `Windows 11` icon, rename `Windows` to `Windows 10`

### PR DESCRIPTION
**Pull request by halacoglu**
windows11

Windows 11 is the latest major release of [Microsoft](https://en.wikipedia.org/wiki/Microsoft)'s [Windows NT](https://en.wikipedia.org/wiki/Windows_NT) [operating system](https://en.wikipedia.org/wiki/Operating_system), released in October 2021.

**Similarweb rank:** 43

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Microsoft has a different logo for Windows 11. I used the logo on [Wikipedia](https://commons.wikimedia.org/wiki/File:Windows_logo_-_2021_(Black).svg) and edited it according to Simple Icons requirements.
- I used the hex `#0078D4` as provided in the [guidelines.](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE1voQq)

### Rename `Windows` to `Windows 10`
Now that we have seperate icons for Windows 95 and Windows XP, we had better have seperate icons for Windows 10 and Windows 11. For this reason I changed:
- `<title>Windows</title>` to `<title>Windows 10</title>` in `windows.svg` and renamed it to `windows10.svg`.
- `"title": "Windows"` to `"title": "Windows 10"` in `simple-icons/_data/simple-icons.json`.

### CODE REVIEW

**Comment by sachinraja** [comment]
Renaming it is a breaking change, could you split that out into a separate PR? Thanks!

**Comment by LitoMore** [comment]
What about setting the name `Windows` always as the alias of the latest Windows version?

**Comment by service-paradis** [comment]
@LitoMore Good idea. I dont think it would be a good idea to completely remove "Windows". Some people might use this icon without having a version in mind. Using alias would probably be the way to go. Unfortunately, apart from discovering it on our website, people wont be able to use this icon without specifying a version since icons are not yet generated for aliases (https://github.com/simple-icons/simple-icons/issues/4797#issuecomment-834484723).

**Comment by dirien** [comment]
+1 on what @service-paradis wrote!

**Comment by service-paradis** [comment]
> Renaming an icon is a breaking change, could you split that out into a separate PR (the same goes for your other PR)? Thanks!

As mentionned by @sachinraja, it would be good to create a new PR to add Windows 11 right now without waiting a new major release. It would give us time to discuss this!

**Pull request closed without merging**
