### PR TITLE
Matter.js

### PR DESCRIPTION
**Pull request by jorgeamadosoria**
matterdotjs

issue: #6500

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @jorgeamadosoria

I see some differences on the m (appart of the cutouts on the shapes, but guess this is the only way to popout the letters.)

image

**Comment by jorgeamadosoria** [comment]
> Hi @jorgeamadosoria
> 
> I see some differences on the m (appart of the cutouts on the shapes, but guess this is the only way to popout the letters.)
> 
> image

yes, this one you won't get a perfect match. It needs changes to highlight the letters, and that will change the other letters as well.

I will try and see if I can change that, but I'm not optimistic. I was kinda hoping the framework owner would review and accept, since he provided the confirmation for the usage of the long logo in the ticket.

**Comment by dirien** [comment]
@jorgeamadosoria should we wait with the approval? For me its okay.

**Comment by jorgeamadosoria** [comment]
@dirien I gave it another shot, I think it's better now. Please check from your side.

**Comment by liabru** [comment]
Looks reasonable from my side, it's not ideal at smaller sizes but that's more of an issue I can better address myself in a future update of the logo and some variations I think.

**Review by sachinraja — APPROVED** [review]

**Comment by sachinraja** [comment]
Thanks for reviewing @liabru!

**Pull request merged**
