### PR TITLE
Update Douban icon

### PR DESCRIPTION
**Pull request by LitoMore**
CleanShot 2022-09-21 at 23 42 01@2x

**Resource:** I picked the `豆` from their logo of [豆瓣豆品](https://market.douban.com) product.
**Color:** `#2D963D` I picked the color from their logo on https://www.douban.com/about page.

I am a former Douban employee. So I have confidence in the `豆` where I picked from. Although Douban (豆瓣) and Douban Market (豆瓣豆品) are different products, their `豆` word is the same.

```html
<svg width='135' height='100' xmlns='http://www.w3.org/2000/svg'><path d='M70.301 40.46h24.525V38H70.301v2.46zm5.47 10.528h13.588v-5.362H75.77v5.362zm9.728 8.58h-5.87l-.017-.058-1.765-6.09h9.434l-1.782 6.148zM72.44 53.42h2.282l.017.06 1.764 6.088h-6.744V62H95.37v-2.432h-6.744l1.78-6.148h2.282V43.167H72.44V53.42zm-9.871-11.68l-.263 5.485H61.03l-.004-.078-.263-5.494h1.81l-.003.086zm2.81 11.471h-2.331v-3.605h2.692v-2.38h-1.62l.007-.09.478-5.483h.94v-2.381h-2.497v-2.227h-2.594v2.227H57.74L56.083 37l-7.963 1.967-.003 9.623c0 5.422-.097 8.494-2.177 13.555l1.934.795c2.226-5.418 2.335-8.817 2.335-14.35v-7.883l1.345-.216v19.272l-.076.005-2.15.154.535 2.585 5.342-1.093-.458-1.869-1.307.096V40.227l1.474-.233v8.596c0 2.569 0 8.576 1.827 14.177l1.987-.652c-1.722-5.285-1.722-11.056-1.722-13.525v-8.913l.73-.11v2.086h.994l.006.075.48 5.497h-1.48v2.381h2.718v3.605H58.07v2.382h2.385v7.066h2.594v-7.066h2.331v-2.382zM44.815 41.74l-.263 5.486h-1.277l-.004-.078-.263-5.494h1.811l-.004.086zm.406 12.998l1.746-.38.18-2.143-1.818.267v-2.875h2.327v-2.38h-1.29l.007-.09.478-5.483h.555v-2.382h-2.122v-2.227h-2.479v2.227h-2.344v2.38h.515l.007.076.479 5.497h-1.334v2.381h2.589v3.259l-2.553.375.286 2.534 2.095-.456-.013.115c-.22 1.919-.688 4.551-1.663 6.23L43.112 63c1.42-2.427 1.927-6.177 2.104-8.203l.005-.06zm68.243 7.762H125V49.561h-11.536V62.5zm3.116-2.267h5.31v-8.384h-5.31v8.384zM99.388 62.5h11.576V49.561H99.388V62.5zm3.11-2.267h5.358v-8.384h-5.359v8.384zm1.107-13.033h16.951v-9.7h-16.95v9.701zm3.114-2.267h10.725v-5.14H106.72v5.14zM11.544 40.46h24.524V38H11.544v2.46zm5.468 10.528h13.589v-5.362H17.012v5.362zm9.73 8.58h-5.87l-.018-.058-1.764-6.09h9.433l-1.781 6.148zm-13.06-6.148h2.281l.017.06 1.765 6.088H11V62h25.612v-2.432h-6.744l1.781-6.148h2.28V43.167H13.683V53.42z' fill='#44883E' fill-rule='evenodd'/></svg>
```

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Difference preview

CleanShot 2022-09-21 at 23 48 44@2x

### CODE REVIEW

**Comment by dirien** [comment]
Hi @LitoMore,

are you reviewing your own PRs? Is this now the new workflow?

FYI @simple-icons/maintainers

**Comment by LitoMore** [comment]
Sorry about that, is our PRs always require other reviewers' approval?

If yes, I will wait for others' approval for future PRS.

**Comment by LitoMore** [comment]
Feel free to revert my merges if you do mind.

**Comment by LitoMore** [comment]
@dirien Let's chat on Slack.

**Comment by ushuz** [comment]
What do you think about a hollowed `豆` that's more similar to Douban's favicon and app logo? Instead of the `豆` character?

favicon



app logo

**Comment by LitoMore** [comment]
I would say no.

For example:

- https://simpleicons.org/?q=1password
- https://simpleicons.org/?q=bilibili
- https://simpleicons.org/?q=wechat

Their brands/trademarks do not contain a background shape.

**Comment by ushuz** [comment]
@LitoMore 

Thanks for the response. That's a fair point.

Well, I personally prefer the look of the hollowed version, which IMO augments the `豆` glyph in a good way.

I made a [hollowed version SVG](https://user-images.githubusercontent.com/1430856/195025126-3bd83395-f38f-46c2-b719-c9e6ad5d448f.svg) based on your work. Please allow me to attach it here in case anyone else finds it useful.



```svg
<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Douban</title><path fill-rule="evenodd" clip-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v20c0 1.1.9 2 2 2h20a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2Zm19.1 4.8H2.9V3h18.2v1.8Zm-1.6 9.6V6.8h-15v7.6h1.7L7.5 19h-5v1.8h19V19h-5l1.3-4.6h1.7Zm-11 0h7L14.2 19H9.8l-1.3-4.6ZM7 8.7h10v4H7v-4Z"/></svg>
```

**Pull request merged**
