### PR TITLE
feat: add Nextflow logo

### LINKED ISSUE #9740: Nextflow
### Brand Name

Nextflow

### Website

https://www.nextflow.io/

### Popularity Metric

Similarweb rank is 695,933. https://www.similarweb.com/es/website/nextflow.io/#overview

### Official Resources for Icon and Color

White version (svg): https://github.com/seqeralabs/logos/blob/master/nextflow/nextflow_icon_white.svg
Dark version (svg): https://github.com/seqeralabs/logos/blob/master/nextflow/nextflow_icon_dark.svg
Color: `#0dc09d`

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by alvaromartmart**
**Issue:** closes #9740 

**Similarweb rank:**

695,933

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @alvaromartmart 👍🏻 

However, this has now fallen [outside our scope](https://www.similarweb.com/es/website/nextflow.io/) with a rank of 669572. It is currently trending up, though, so we'll leave this open for a few days for monitoring.

For the purposes of reviewing, could you let us know which version of their icon you based yours on, so we can compare like with like?

**Comment by alvaromartmart** [comment]
> Thanks for the contribution, @alvaromartmart 👍🏻
> 
> However, this has now fallen [outside our scope](https://www.similarweb.com/es/website/nextflow.io/) with a rank of 669572. It is currently trending up, though, so we'll leave this open for a few days for monitoring.
> 

I hope you'll reconsider 🙂 : tbh I don't think the website ranking gives a good indicator of the popularity of Nextflow, a popular open source DSL for writing computational workflows. I can give you other stats to reflect that (with links to the source):
- Github stats: [2.2k stars, 568 forks](https://github.com/nextflow-io/nextflow) - over [3.5k repositories in Github using the technology](https://github.com/search?q=nextflow&type=repositories)
- nf-core, an open source community fully dedicated to using Nextflow and standardizing its use / building tooling on top of it. [similarweb rank 786.418](https://www.similarweb.com/es/website/nf-co.re/#overview)
- [Seqera](https://seqera.io/nextflow/) , the "parent" company mainly supporting the development of Nextflow: [Similarweb rank 3,968,939](https://www.similarweb.com/es/website/seqera.io/#overview)
_Full disclosure: I work for this company_

> For the purposes of reviewing, could you let us know which version of their icon you based yours on, so we can compare like with like?

You can find the source here https://github.com/seqeralabs/logos/blob/master/nextflow/nextflow_icon_color.svg

As you can see I had some trouble getting it to pass the Github Action checks in simple-icons, I don't understand why. It's a pretty simple icon. Any help would be appreciated

**Comment by PeterShaggyNoble** [comment]
Thanks for the additional information, @alvaromartmart :+1: However the minimum number of Github stars required for a brand to be considered popular enough for us to add is 5k, and neither of the other 2 brands you mentioned would be within the scope of our minimum rank of 500k.

**Comment by adamrusted** [comment]
Unfortunately I have to agree with @PeterShaggyNoble that this is well out of scope for the time being. Feel free to re-open should it meet our criteria @alvaromartmart!

**Pull request closed without merging**
