### PR TITLE
Updated Google Calendar

### PR DESCRIPTION
**Pull request by adamrusted**
googlecalendar

**Issue:** Contributes toward #4205
**Alexa rank:** N/A

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
New source as discussed on #4205.
Rebuilt from source. 0.~3~5px between colour changes.
Ran through SVGO CLI.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Is this another one that should be updated to use a 0.5dp cut-out, @adamrusted?

**Comment by adamrusted** [comment]
> Is this another one that should be updated to use a 0.5dp cut-out, @adamrusted?

Almost certainly - I'll look at it this afternoon.

**Comment by adamrusted** [comment]
@PeterShaggyNoble updated to 0.5px gaps.

**Review by PeterShaggyNoble — APPROVED** [review]
Nice work, @adamrusted - this looks spot-on to me :+1:

Again, I'd prefer a better source but that's something we can update at a later date.

**Pull request merged**
