### PR TITLE
Added Mattermost

### PR DESCRIPTION
**Pull request by phatbhoy67**
**Issue: [#1552 ](https://github.com/simple-icons/simple-icons/issues/1552)**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The hex value is from site branding (https://mattermost.com/)
Vector created from brand .eps file available here: (https://www.mattermost.org/brand-guidelines/)
Built on GitPod and working as expected

### CODE REVIEW

**Comment by phatbhoy67** [comment]
The hex value (0072C6) is from the site header at (https://www.mattermost.org/brand-guidelines/) and not (https://mattermost.com/) as I had stated. Sorry about that.

I've just checked and the hex value used for branding and the logo on the .com site is a slightly different blue (0058CC) from the one used on the .org site.

The brand guidelines doesn't specify a blue that I can see.

Happy to make any updates to the PR. Let me know.

**Comment by ericcornelissen** [comment]
I'm not seeing any official mention of the colour @phatbhoy67, is that correct? If so, I'm fine with merging this as is.

**Comment by phatbhoy67** [comment]
There is no official mention of a brand colour as far as I can see @ericcornelissen

**Comment by ericcornelissen** [comment]
In that case, thanks for your work on this icon @phatbhoy67 it is very much appreciated!! :tada:

**Pull request merged**
