### PR TITLE
Add Cryengine

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
From previously abandonded #1339 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Color white is mostly used and also the first example on the website (could be black, tho, if you want it to). SVG downloaded directly from their brand page.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Unfortunately, [their styleguide](https://www.cryengine.com/assets/brand-assets/cryengine-logo-styleguide.pdf) forbids the use of the eye on its own so the wordmark will need to be added underneath.

And, personally, I think one of the darker colour would be a better choice.

**Comment by runxel** [comment]
Aw, bummer!
Thanks for letting me know. (Man I hate these style guides haha. I always laugh at how little trust they have in their own brand that they forbid to have the logo stand alone without some stupid text next to it)

Will update soon! (Currently underway)

**Comment by runxel** [comment]
Color is now black and the icon follows the brand rules.
Thanks for checking this, @PeterShaggyNoble! :)

**Comment by phatbhoy67** [comment]
Thanks @runxel for your work on this and @PeterShaggyNoble for your review 👍

**Pull request merged**
