### PR TITLE
Added FMOD Icon

### PR DESCRIPTION
**Pull request by made-indrayana**
**Issue:** #5709
**Alexa rank:** [311,101](https://www.alexa.com/siteinfo/fmod.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I used the official source [here](https://www.fmod.com/attribution), but I think when displayed as a small icon, it is almost not readable. But it is also the case in their [website](https://fmod.com) as favicon. Is this ok or do you have any better suggestion?

preview

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for the contribution @made-indrayana, and welcome to Simple Icons! 🎉
Just taking a look at this, it appears there are [some differences](https://user-images.githubusercontent.com/1830867/118487855-091ba380-b713-11eb-8371-55273f373be0.png) between your PR in red, and the source in black.

They look to be purely from the optimization, so you may be able to fix them by re-optimizing the source icon to a precision of 4 (either using the slider on SVGOMG, or editing `svgo.config.js` within the repo). Would you mind taking another look at it? 🙏

**Review by adamrusted — APPROVED** [review]
This looks good to me now, thanks @made-indrayana!
I'll ping the other @simple-icons/maintainers as there's a _[slight](https://user-images.githubusercontent.com/1830867/118500389-a7156b00-b71f-11eb-8d60-f9d5866b77f1.png)_ difference to the ® symbol, but as it's not the brand icon itself, I think we can let it slide. Once I get the okay from someone else, we can get this merged in for release on Sunday!

**Comment by made-indrayana** [comment]
> 
> 
> This looks good to me now, thanks @made-indrayana!
> I'll ping the other @simple-icons/maintainers as there's a _[slight](https://user-images.githubusercontent.com/1830867/118500389-a7156b00-b71f-11eb-8d60-f9d5866b77f1.png)_ difference to the ® symbol, but as it's not the brand icon itself, I think we can let it slide. Once I get the okay from someone else, we can get this merged in for release on Sunday!

Thank you so much @adamrusted ! 🙇

**Comment by made-indrayana** [comment]
Damn, mistakenly renamed the branch to something else and this broke the pull request. So sorry, @adamrusted , should I make a new one?

**Comment by PeterShaggyNoble** [comment]
> there's a slight difference to the ® symbol, but as it's not the brand icon itself, I think we can let it slide.

Agreed; I think we can stop worrying about trademark symbols lining up perfectly, especially if it can save us a precision point; the important thing is merely that they are present. And that they even include it in their favicon themselves means we should probably also include it. So gonna merge this in based on Adam's approval above.

Thanks for the contribution, @made-indrayana and welcome to Simple Icons 🙂

**Comment by adamrusted** [comment]
> I think we can stop worrying about trademark symbols lining up perfectly, especially if it can save us a precision point;

Perhaps we should look at having a 'stock' ® symbol that is already optimized for our use 'on file' to easily swap in if the brand one isn't up to scratch? 🤔

**Comment by made-indrayana** [comment]
Thank you @PeterShaggyNoble and @adamrusted, I will be very happy to continue to contribute, especially for audio softwares!

**Pull request merged**
