### PR TITLE
Pearson logo

### PR DESCRIPTION
**Pull request by Blargian**
pearson

**Issue:5865**
**Alexa rank:882**

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
Added the Pearson logo. The source image was already a .svg so there wasn't much work to do. Took the hex value straight from the original svg.

### CODE REVIEW

**Comment by Blargian** [comment]
Made a second commit to fix some of the tests which failed on the first commit.

**Review by ericcornelissen — CHANGES_REQUESTED** [review]
Hmm 🤔 I'm noticing some differences when comparing it to what I presume the source is (the SVG in the header of the website), see below. This _could_ be due to SVGO so you could retry this with a higher precision. Though, from my experience with SVGO, the differences here are a bit too significant, so be extra careful when working with the SVG when you try this again. If you need any help, please feel free to reach out for help here 🙂 

I agree with the color and the source, assuming the SVG comes from where I thought it comes from -  did you attempt to find [official brand guidelines or licensing infomation](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#optional-data), @Blargian?

image

**Comment by Blargian** [comment]
Hi @ericcornelissen, the SVG source I used is from [https://www.pearson.com/etc/clientlibs/one-dot-com/one-dot-com/1dc-navigation/assets/logos/pearson_logo_white_bg.svg](here)

It was the source suggested to be used in the original issue.

**Comment by ericcornelissen** [comment]
Thanks for clarifying @Blargian - in that case could you have a look at the differences seen in the comparison of my previous comment?

**Comment by service-paradis** [comment]
Closing this one as abandoned for now since no changes were made in a long time. Please feel free to make the requested changes and reopen this PR if you're still interested to contribute

**Pull request closed without merging**
