### PR TITLE
Add Forgejo icon

### PR DESCRIPTION
**Pull request by Sevichecc**
forgejo

**Similarweb rank:** 2,117,346
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
[Forgejo](https://forgejo.org/) appears to be a promising self-hosted lightweight software forge dedicated to being free and open source software. Forgejo is a “soft” fork of [Gitea](https://gitea.com/) focused on scalability, federation and privacy. [Codeberg](https://codeberg.org/) is built based on Forgejo.

### CODE REVIEW

**Comment by LitoMore** [comment]
2023-05-25 at 14 45 50@2x

@Sevichecc I picked https://codeberg.org/forgejo/meta/raw/branch/readme/branding/logo/forgejo.svg as a reference and found some differences.

Please make sure there is no stretching when resizing.

**Comment by Sevichecc** [comment]
@LitoMore I have refined the icon using this source https://codeberg.org/forgejo/meta/raw/branch/readme/branding/logo/forgejo-monochrome.svg with the help of Forgejo community. Do you have time to review the changes and let me know it look ok?

**Comment by LitoMore** [comment]
2023-06-02 at 23 41 16@2x

It still has some differences. The size should be:

2023-06-02 at 23 45 37@2x

But yours:

2023-06-02 at 23 43 54@2x

Please make sure there is no stretching when resizing.

**Comment by Sevichecc** [comment]
I hope I know how to do it now. Hopefully it will pass the review this time.

**Review by LitoMore — APPROVED** [review]
2023-06-04 at 09 44 12@2x

@Sevichecc Perfect fit now! Thank you for contributing!

**Pull request merged**
