### PR TITLE
Update Android

### LINKED ISSUE #8947: Update Android logo
### Brand Name

Android

### Official Resources for Icon and Color

Google announces a new 3D logo for android: https://www.androidauthority.com/google-reveals-new-android-logo-wordmark-3339530/

Not yet updated on their brand guidelines:
https://source.android.com/docs/setup/about/brands

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Android

**Issue:** closes #8947

**Similarweb rank:** [2043](https://similarweb.com/website/android.com)

### Checklist
- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon extracted from [this SVG](https://storage.googleapis.com/pe-portal-consumer-prod-wagtail-static/documents/horizontallockup_monochrome_black_VLGW7ez.svg), colour from [this one](https://storage.googleapis.com/pe-portal-consumer-prod-wagtail-static/documents/horizontallockup_flat_inverted_pkNLctQ.svg).

### CODE REVIEW

**Comment by adamrusted** [comment]
image

**Review by adamrusted — CHANGES_REQUESTED** [review]
Though the eye 'path' is there - it's filled.
image

I've had this issue before, and it's to do with the organisation of 'layers' prior to merging down.

**Comment by service-paradis** [comment]
> image

I got the same with source in OP 😅 
There is a SVG in the header at https://source.android.com/docs/setup/about/brands?hl=fr that might be used

**Comment by PeterShaggyNoble** [comment]
Unfortunately, the eyes in the 3d version don't line up with the ones in the flat version, @service-paradis. I figured out the problem, though; I missed a `fill-rule` in the source file first time around.

**Review by adamrusted — APPROVED** [review]

**Pull request merged**
