### PR TITLE
Add CKEditor Icon

### LINKED ISSUE #8293: CKEditor5
### Brand Name

CKEditor5

### Website

https://ckeditor.com/

### Popularity Metric

[Similarweb rank](https://www.similarweb.com/website/ckeditor.com)
[GitHub stars](https://github.com/ckeditor/ckeditor5/stargazers)

### Official Resources for Icon and Color

[icon](https://github.com/ckeditor/ckeditor5/blob/master/docs/assets/img/project-logo.svg)
[colorized icon](https://github.com/ckeditor/ckeditor5/blob/master/docs/assets/img/favicons/200x200.png)
[#1ebc61](https://www.colorhexa.com/1ebc61)

### Additional Comments

Now there is an icon of CKEditor 4, but there is already a new version of this editor.

### Contributing

Yes

### PR DESCRIPTION
**Pull request by jrhaberland**
ckeditor

**Issue:** closes #8293 

**Popularity metric:**

The Similarweb rank is 139,593. See https://www.similarweb.com/website/ckeditor.com/

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
Adds main logo for CKEditor the overall company. Color is `#771BFF`

### CODE REVIEW

**Comment by anhthang** [comment]
```
<svg width="131" height="25" viewBox="0 0 131 25" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M79.3085 3.73047C79.3085 4.3401 79.3222 4.93573 79.3497 5.5174C79.3671 5.89029 79.3929 6.26077 79.4216 6.62995C78.8976 6.25809 78.318 5.97157 77.7044 5.78108C76.8121 5.50331 75.8827 5.36313 74.9482 5.36536C73.959 5.33216 72.9776 5.55138 72.0965 6.00234C71.2767 6.49134 70.6665 7.26597 70.383 8.17749C70.0079 9.20255 69.8203 10.6294 69.8203 12.4579C69.8203 14.804 70.1904 16.6049 70.9307 17.8606C71.6709 19.1163 72.9095 19.7442 74.6464 19.7445C75.7767 19.7821 76.8957 19.509 77.8817 18.9551C78.6211 18.5198 79.2747 17.9531 79.8104 17.283L80.1577 19.4124H83.3658V0.0175781H79.3075L79.3085 3.73047ZM77.4988 16.2401C77.0967 16.3488 76.6813 16.4002 76.2648 16.3927C75.8091 16.4119 75.3574 16.3012 74.9621 16.0738C74.5777 15.7928 74.3133 15.3773 74.2216 14.9101C74.0405 14.0965 73.9622 13.2635 73.9887 12.4304C73.9599 11.5463 74.0429 10.6622 74.2356 9.79887C74.3264 9.31691 74.6017 8.88939 75.0029 8.6073C75.4255 8.38631 75.8991 8.28127 76.3754 8.30284C76.959 8.29296 77.541 8.36751 78.1033 8.52419C78.4699 8.63425 78.8719 8.75427 79.3094 8.88428V15.268C79.0333 15.4575 78.7759 15.6261 78.5422 15.7694C78.2168 15.9718 77.8659 16.1301 77.4988 16.2401Z" fill="#1C2331"></path>
<path d="M89.1995 4.74092e-05L87.4445 0.0110368C86.6401 0.0161519 86.2407 0.430033 86.2461 1.25262L86.2552 2.70578C86.2605 3.52871 86.6652 3.9375 87.4692 3.93213L89.2242 3.92114C90.0285 3.91603 90.4282 3.50218 90.4232 2.67959L90.4142 1.2264C90.409 0.403723 90.0041 -0.00506766 89.1995 4.74092e-05Z" fill="#1C2331"></path>
<path d="M90.363 5.7832L86.332 5.80877L86.4182 19.5134L90.4492 19.4879L90.363 5.7832Z" fill="#1C2331"></path>
<path d="M99.0569 1.97266L94.9714 1.99823L95.0024 5.76868L92.6367 5.90705L92.6526 8.4298L95.0237 8.41485L95.0853 15.8735C95.0927 17.0624 95.4414 17.9834 96.1312 18.6365C96.8211 19.2896 97.7785 19.6127 99.0035 19.6057C99.3321 19.6037 99.734 19.5783 100.209 19.5298C100.684 19.4812 101.159 19.4142 101.634 19.3287C102.042 19.2599 102.445 19.1612 102.839 19.0332L102.382 16.2938L100.627 16.3048C100.222 16.3452 99.8164 16.2355 99.4871 15.9966C99.3592 15.8547 99.2621 15.6878 99.2019 15.5065C99.1416 15.3251 99.1198 15.1332 99.138 14.9429L99.0968 8.38966L102.881 8.36574L102.864 5.70524L99.08 5.72903L99.0569 1.97266Z" fill="#1C2331"></path>
<path d="M115.565 5.9697C114.539 5.50935 113.175 5.28455 111.475 5.29529C109.793 5.30595 108.437 5.54782 107.408 6.02096C106.403 6.46721 105.608 7.28197 105.187 8.29718C104.736 9.34218 104.517 10.7421 104.528 12.497C104.538 14.2147 104.776 15.5934 105.239 16.6333C105.671 17.6415 106.478 18.4426 107.489 18.8679C108.524 19.3182 109.883 19.5382 111.564 19.5278C113.265 19.5171 114.626 19.28 115.646 18.8166C116.644 18.3767 117.431 17.565 117.84 16.5541C118.281 15.509 118.497 14.1274 118.485 12.4092C118.474 10.6542 118.242 9.25712 117.787 8.21791C117.364 7.21039 116.568 6.40506 115.565 5.9697V5.9697ZM114.032 14.9881C113.983 15.2428 113.883 15.485 113.738 15.7003C113.593 15.9156 113.407 16.0994 113.189 16.241C112.671 16.4704 112.112 16.5907 111.546 16.5943C110.979 16.5979 110.419 16.4847 109.898 16.2618C109.679 16.1231 109.49 15.9416 109.342 15.7282C109.195 15.5148 109.092 15.2737 109.041 15.0195C108.846 14.1845 108.757 13.3282 108.777 12.471C108.746 11.6053 108.823 10.7391 109.008 9.89282C109.058 9.63691 109.158 9.39345 109.303 9.1767C109.448 8.95948 109.633 8.77292 109.85 8.62773C110.365 8.38953 110.925 8.26441 111.493 8.26074C112.061 8.25718 112.623 8.37526 113.141 8.60703C113.36 8.74955 113.548 8.93376 113.695 9.1491C113.842 9.36461 113.945 9.60679 113.999 9.86201C114.194 10.706 114.282 11.571 114.262 12.4369C114.292 13.2938 114.215 14.1512 114.032 14.9887L114.032 14.9881Z" fill="#1C2331"></path>
<path d="M130.286 5.17584C129.306 5.19746 128.343 5.43461 127.465 5.87045C126.489 6.34841 125.586 6.96352 124.784 7.69706L124.392 5.57967L121.211 5.59962L121.299 19.531L125.357 19.5054L125.298 10.0554C126.174 9.74547 126.913 9.50675 127.515 9.33923C128.166 9.15339 128.838 9.05451 129.515 9.04514L130.639 9.03808L130.999 5.17188L130.286 5.17584Z" fill="#1C2331"></path>
<path d="M55.2066 18.565C53.8937 16.4554 52.5809 14.3458 51.268 12.2362C51.1396 12.0151 50.9956 11.8035 50.8369 11.6031C50.6106 11.3352 50.3561 11.0925 50.0777 10.8791C50.1047 10.8374 50.1405 10.8019 50.1824 10.7752C50.5004 10.5066 50.7771 10.1928 51.0038 9.84374C52.4611 7.58544 53.9186 5.32722 55.3764 3.06909C55.4011 3.03072 55.4397 2.99773 55.4375 2.94773C55.4126 2.92216 55.3849 2.93085 55.3599 2.93059C53.9817 2.92906 52.6035 2.92688 51.2253 2.92407C51.1865 2.92214 51.1481 2.93181 51.1148 2.95182C51.0814 2.97179 51.0547 3.00128 51.0381 3.03649C50.3157 4.19122 49.592 5.34507 48.867 6.49809C48.2928 7.41331 47.717 8.32673 47.1477 9.24451C47.1226 9.29583 47.0821 9.33793 47.0317 9.36483C46.9815 9.39167 46.924 9.40196 46.8676 9.39424C46.6236 9.38145 46.3784 9.39143 46.1335 9.38977C46.0878 9.38977 46.0383 9.40549 45.9952 9.3716C45.9993 9.32378 46.001 9.27546 46.008 9.22827C46.0905 8.64732 46.1284 8.06091 46.1215 7.47418V3.00874C46.1215 2.95695 46.1015 2.92804 46.0463 2.93034H45.9662L42.3253 2.92713C42.1153 2.92713 42.1417 2.90247 42.1417 3.11654V19.2322C42.1417 19.2699 42.1433 19.3072 42.1417 19.3446C42.1391 19.3906 42.1574 19.4139 42.2056 19.4125H45.9414C46.1483 19.4125 46.1212 19.4296 46.1212 19.2345V13.7614C46.1212 13.6231 46.1139 13.4844 46.1095 13.3456C46.0903 12.9955 46.0493 12.6468 45.9868 12.3018H46.1349C46.396 12.3018 46.6568 12.3086 46.9172 12.2987C46.9608 12.2942 47.0047 12.3038 47.0424 12.3262C47.0802 12.3487 47.1096 12.3828 47.1263 12.4234C48.4648 14.7038 49.8043 16.9836 51.145 19.2626C51.1669 19.3119 51.2036 19.3531 51.25 19.3806C51.2962 19.4082 51.3498 19.4207 51.4034 19.4166C52.7867 19.4107 54.1704 19.4129 55.5539 19.4126C55.6051 19.4126 55.6553 19.4084 55.7245 19.4053C55.7029 19.367 55.6911 19.3455 55.6779 19.3241L55.2066 18.565Z" fill="#1C2331"></path>
<path d="M67.7787 16.3864C67.7668 16.1875 67.7708 16.1875 67.5751 16.1875H61.5406C61.4076 16.1883 61.2748 16.1789 61.1432 16.1595C60.999 16.1475 60.8621 16.0908 60.7516 15.9974C60.6412 15.9038 60.5627 15.7781 60.5271 15.6378C60.4912 15.5153 60.4723 15.3884 60.4711 15.2608C60.4711 14.3086 60.4702 13.3564 60.4686 12.4042C60.4686 12.3249 60.4847 12.2832 60.5725 12.2947C60.6098 12.2971 60.6472 12.2971 60.6845 12.2947H66.719C66.7562 12.2947 66.794 12.2916 66.8314 12.2947C66.9045 12.302 66.9245 12.2647 66.9185 12.1997C66.9159 12.1677 66.9185 12.1357 66.9185 12.1043V9.53524C66.9185 9.31363 66.9505 9.33921 66.7267 9.33921H60.6282C60.4505 9.33921 60.4721 9.34843 60.4721 9.18795V7.09752C60.4722 6.98057 60.4827 6.86389 60.5037 6.74883C60.5228 6.59412 60.5923 6.45001 60.7015 6.33872C60.8106 6.22737 60.9532 6.15497 61.1075 6.1327C61.2276 6.111 61.3496 6.10162 61.4716 6.1047H67.5703C67.6075 6.1047 67.6447 6.10189 67.682 6.1047C67.7425 6.10969 67.7705 6.08283 67.7724 6.02375C67.7724 5.99178 67.7785 5.95983 67.7805 5.92837C67.8051 5.51465 67.8294 5.10065 67.8536 4.68641C67.8817 4.22989 67.9142 3.77402 67.9408 3.31814C67.9527 3.10394 67.9475 3.09948 67.7346 3.08183C67.1891 3.03708 66.6421 2.98745 66.0977 2.95586C65.5534 2.92428 65.0027 2.90343 64.4549 2.89192C62.9919 2.86115 61.5287 2.84797 60.0652 2.8524C59.6665 2.85049 59.2695 2.90469 58.8859 3.0134C58.4502 3.12784 58.0435 3.33264 57.692 3.61445C57.3407 3.89636 57.0525 4.249 56.8461 4.64948C56.5978 5.14001 56.4728 5.68373 56.4821 6.23348C56.4799 7.86647 56.4799 9.49923 56.4821 11.1318V15.919C56.4806 16.0997 56.4899 16.2804 56.5101 16.46C56.5593 17.0057 56.749 17.5294 57.0606 17.9801C57.3721 18.4309 57.795 18.7933 58.2882 19.032C58.857 19.3138 59.4868 19.45 60.1212 19.4284C62.0149 19.4156 63.9095 19.4337 65.8016 19.3237C66.4868 19.2835 67.1712 19.2387 67.8546 19.1892C67.9259 19.1839 67.9585 19.1696 67.9518 19.0875C67.9319 18.8279 67.9213 18.5676 67.9053 18.3075C67.8599 17.6703 67.8173 17.0286 67.7787 16.3864Z" fill="#1C2331"></path>
<path d="M40.348 18.5365C40.2423 17.6413 40.1371 16.7462 40.0323 15.8511C40.024 15.7765 39.9988 15.7488 39.9238 15.7581C39.7395 15.7798 39.5548 15.8017 39.3698 15.8185C38.7239 15.876 38.0767 15.9224 37.4289 15.9415C36.5887 15.9655 35.7486 15.9893 34.9084 15.9789C34.6165 15.9774 34.3255 15.9455 34.0401 15.8837C33.5979 15.8078 33.1978 15.575 32.9132 15.228C32.7271 14.9795 32.5864 14.7001 32.4976 14.4026C32.3165 13.7728 32.2106 13.1237 32.182 12.469C32.1366 11.8461 32.1388 11.2221 32.1448 10.5979C32.1455 9.8844 32.2001 9.17197 32.3083 8.46671C32.3655 8.0722 32.4722 7.68649 32.6261 7.31876C32.735 7.04336 32.9096 6.79873 33.1345 6.6061C33.3609 6.41238 33.6306 6.27613 33.9208 6.20892C34.2456 6.129 34.579 6.08908 34.9134 6.0901C36.4817 6.08652 38.0501 6.09855 39.6185 6.21364C39.6722 6.21747 39.6997 6.20086 39.7068 6.15035C39.7103 6.12478 39.712 6.09804 39.7148 6.07208C39.7647 5.61335 39.8145 5.15489 39.8642 4.69675C39.912 4.25481 39.9562 3.81058 40.0073 3.36813C40.017 3.28309 39.9945 3.25303 39.9092 3.22745C38.9205 2.94164 37.9033 2.76583 36.8761 2.70318C36.2878 2.66174 35.6962 2.65625 35.1059 2.65357C34.5052 2.64524 33.9046 2.6794 33.3087 2.75584C32.7782 2.82461 32.2553 2.94221 31.7464 3.10713C30.9801 3.3447 30.2859 3.77125 29.7278 4.34753C29.2643 4.84559 28.9041 5.43044 28.6677 6.06837C28.3483 6.95153 28.1458 7.87269 28.0654 8.80838C27.9899 9.52167 27.9558 10.2387 27.9631 10.9559C27.9469 12.0327 28.023 13.1089 28.1907 14.1727C28.2882 14.7995 28.4498 15.4146 28.6728 16.0085C28.918 16.7039 29.3231 17.332 29.8554 17.8422C30.3908 18.3555 31.0379 18.7376 31.7459 18.9586C32.6057 19.2346 33.5012 19.3835 34.404 19.4005C35.7219 19.4535 37.0419 19.3838 38.3469 19.1922C38.9943 19.0843 39.6341 18.9348 40.2623 18.7446C40.3377 18.7223 40.381 18.6854 40.3559 18.6004C40.3514 18.5794 40.3488 18.558 40.348 18.5365V18.5365Z" fill="#1C2331"></path>
<path d="M15.3398 14.1797C15.3545 14.19 15.3652 14.2051 15.3699 14.2224C15.3651 14.2051 15.3545 14.19 15.3398 14.1797V14.1797Z" fill="#141A25"></path>
<path d="M15.0392 16.726C14.4972 16.7934 13.9748 16.9715 13.5047 17.2495C12.9308 17.58 12.449 18.0491 12.1033 18.6139C11.9947 18.7947 11.3871 19.9614 11.3871 19.9614L9.29688 23.7817L9.31899 23.7972C9.41615 23.8603 9.51945 23.9133 9.62731 23.9556C9.94412 24.0694 10.2774 24.1306 10.614 24.1368C11.8781 24.1943 13.1426 24.1198 14.4069 24.129C15.1315 24.152 15.8568 24.1344 16.5793 24.0762C16.9272 24.0586 17.266 23.9592 17.5683 23.7861C17.8785 23.6081 18.1449 23.3631 18.3484 23.0691C18.4872 22.8637 18.6318 22.6615 18.7576 22.4486C19.3589 21.4281 19.957 20.4064 20.5519 19.3836C20.7393 19.0628 20.9228 18.7398 21.107 18.4181C21.1995 18.2577 21.2954 18.0983 21.3884 17.9368C21.6239 17.545 21.7551 17.0995 21.7695 16.6426L18.5105 16.7003C18.5105 16.7003 15.3644 16.6875 15.0392 16.726ZM17.804 17.6291C17.784 17.6499 17.7719 17.677 17.7697 17.7057C17.772 17.677 17.784 17.65 17.8038 17.6291H17.804Z" fill="#AFE229"></path>
<path d="M18.8281 15.6661C18.8318 15.6221 18.8504 15.5808 18.8808 15.5488V15.5488C18.8504 15.5808 18.8319 15.6222 18.8281 15.6661V15.6661Z" fill="#771BFF"></path>
<path d="M7.11943 22.6092L9.02145 19.1332C9.02145 19.1332 9.23783 18.7175 9.48067 18.2556C9.17018 18.0878 8.86686 17.9061 8.56277 17.7277C7.69679 17.2204 6.79704 16.7708 5.95037 16.2303C5.72043 16.0923 5.5146 15.9176 5.34103 15.7131C5.07045 15.3772 5 14.9768 4.9789 14.5638C4.9266 13.5407 4.97608 12.5177 4.95831 11.4947C4.94987 11.0076 4.95831 10.5204 4.96444 10.0331C4.97467 9.22744 5.34807 8.65073 6.03285 8.25009C6.72739 7.8437 7.42142 7.43665 8.11494 7.02889C8.66549 6.70699 9.21698 6.38664 9.7694 6.06788C9.89613 5.99525 10.0321 5.93847 10.1644 5.87607C10.8446 5.55459 11.4624 5.75741 12.0643 6.08874C12.1026 6.10984 12.1386 6.1344 12.1758 6.15742C12.4824 6.30565 12.7812 6.46953 13.0709 6.64845C13.8653 7.0932 14.6581 7.54077 15.4494 7.99115C15.6878 8.12967 15.9175 8.28265 16.1372 8.44921C16.6222 8.80918 16.7725 9.32438 16.8035 9.89419C16.8419 10.6048 16.8195 11.3164 16.8163 12.0277C16.8138 12.7259 16.8267 13.4236 16.8189 14.1221C18.2966 14.1155 19.9646 14.1221 19.9646 14.1221L21.7724 14.0902C21.7655 13.3603 21.7556 12.6304 21.7554 11.9003C21.7554 10.5909 21.7921 9.2808 21.716 7.97198C21.655 6.92186 21.3763 5.9721 20.4843 5.30599C20.0805 4.99791 19.6583 4.71464 19.2201 4.45769C17.7658 3.6241 16.3094 2.79411 14.8508 1.96777C14.3052 1.65959 13.7826 1.30932 13.2057 1.05728C13.1374 1.01469 13.0709 0.96934 13.0011 0.930337C11.8952 0.316529 10.7613 -0.0617321 9.51634 0.525478C9.27401 0.639927 9.02517 0.742818 8.79333 0.876577C7.78157 1.45731 6.77271 2.04325 5.76675 2.63438C4.49599 3.37752 3.22631 4.12221 1.95769 4.86841C0.704495 5.60166 0.0243105 6.66018 0.0112671 8.14419C0.00333874 9.04138 -0.00894167 9.93848 0.010112 10.8354C0.0500095 12.7193 -0.0336202 14.6045 0.0693205 16.4875C0.11088 17.2483 0.242975 17.9859 0.741438 18.6064C1.06076 18.9839 1.43935 19.307 1.8624 19.563C3.41828 20.5643 5.07096 21.3982 6.66238 22.3379C6.8149 22.4282 6.96725 22.5187 7.11943 22.6092Z" fill="#771BFF"></path>
</svg>
```

I think we should use the icon from website header for CKEditor instead of

**Comment by jrhaberland** [comment]
We already have CKEditor4 and this is what looks like: #5159
ckeditor4

I was just going based off this 🤷‍♂️

**Comment by anhthang** [comment]
In my opinion, we may not need a unique icon for every version, especially when the only difference is a number.

**Comment by uncenter** [comment]
> In my opinion, we may not need a unique icon for every version, especially when the only difference is a number.

It depends on how *major* versions are and how different the logos are for each version. For example:
image
image

**Comment by uncenter** [comment]
> I was just going based off this 🤷‍♂️

How do you mean just going off of that? The number is different so you couldn't base it off that.

**Comment by jrhaberland** [comment]
> > I was just going based off this 🤷‍♂️
> 
> How do you mean just going off of that? The number is different so you couldn't base it off that.

That the logo should be that with a number, I got the actual logo from [HERE](https://github.com/ckeditor/ckeditor5/blob/50c09aab32c0ae7e50ca1d211d5d07021b329b15/docs/assets/img/project-logo.svg)

**Comment by uncenter** [comment]
From https://ckeditor.com/legal/:
> CKSource's trademarks may be used publicly only with permission from CKSource and proper acknowledgement. The names “CKSource”, “CKEditor”, ”CKEditor Ecosystem”, ”Letters”, “CKFinder” and their logos are trademarks of CKSource.

I don't think we can include this without first requesting permission. Would you mind [reaching out](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission) @jrhaberland?

**Comment by jrhaberland** [comment]
Sent an email to CKSource

I'll also need to go back and remove the license I added. Since the license of the GitHub repo only covers the code not the logo

**Comment by uncenter** [comment]
> Sent an email to CKSource

Amazing thank you!

**Comment by adamrusted** [comment]
Now, not knowing the software - please excuse my ignorance.
Does this not go against our guideline for not including 'versioned' software?
Surely we should just have a 'CKEditor' icon?

**Comment by uncenter** [comment]
> Now, not knowing the software - please excuse my ignorance. Does this not go against our guideline for not including 'versioned' software? Surely we should just have a 'CKEditor' icon?

I mean I'm just going with the existing precedent that we already have a versioned CKEditor4 icon, and we have other examples that I've pointed out earlier in this thread that are versioned products/software.

**Comment by adamrusted** [comment]
Most of the others (Playstation, Windows) are kept for archival purposes, hence why we re-added Stadia even though it's a dead brand. CKEditor5 seems like a direct replacement of CKEditor4 though - I can't see anywhere that there is a market of people developing / working with 4 still, and the brand of CKEditor has it's own logo outside of the 'product' icon. I'd argue we should instead change the existing CKEditor4 logo to be the one found in the [website header](https://ckeditor.com/) and not look to include 5.

**Comment by jrhaberland** [comment]
@adamrusted I can go ahead and do that in here, or I can make a new pull request for that change if you think that's more proper

**Comment by adamrusted** [comment]
If you could, @jrhaberland - that'd be great. If you wanted to re-tool this PR to _just_ add CKEditor as it's own thing - and we'll start another PR for the removal of 4 as of October.

**Comment by jrhaberland** [comment]
@adamrusted completed changing it from CKEditor 5 to being just the overall CKEditor logo

**Review by uncenter — APPROVED** [review]
Icon and metadata look good! Last remaining issue is what we should do with the existing `ckeditor4` icon? Remove it in the next major update?

**Comment by jrhaberland** [comment]
Yeah just remove them in the v14 update. We also still need to wait for permission before merging this, I still have yet to hear back from them, but I'll go ahead and send a follow up email.

**Comment by uncenter** [comment]
Raised a draft PR removing it in v14. Only needing that permission and then we are good to merge!

**Comment by uncenter** [comment]
No luck on that follow up email?

**Comment by jrhaberland** [comment]
Unfortunately no, haven't heard anything back from them

**Comment by uncenter** [comment]
Shoot. Welp, closing as no feedback from brand. If you do a response from them feel free to post it here and we can re-open the PR.

**Pull request closed without merging**
