### PR TITLE
Added PaddyPower icon

### LINKED ISSUE #5743: Icon Request: Paddy Power icon
**Brand Name:** Paddy Power
**Website:** https://www.paddypower.com/
**Alexa rank:** 25,784

**Official resources for icon and color:**

Icon source: 
I got the icon from here: https://arspp.cdnppb.net/pp-ssc/ssc-sprite.svg
It looks way better than the PaddyPower text as a logo.

`#004833`

### PR DESCRIPTION
**Pull request by iugabogdan**
paddypower (3)

**Issue:** Closes #5743
**Alexa rank:**  25,784

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
I got the hex value from the header of https://paddypower.com
I got the icon from https://arspp.cdnppb.net/pp-ssc/ssc-sprite.svg

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
You were too quick for me! 😆 Went looking for a vector version of their icon as soon as I saw your issue and, by the time I got back, you had the PR in already.

Found [this sprite](https://arspp.cdnppb.net/pp-ssc/ssc-sprite.svg) in the source of [their main site](https://www.paddypower.com/bet) which includes a couple of versions of the "PP." icon. Would you mind taking another go at it using that SVG instead?

Thanks for the contribution, by the way 🙂

**Comment by iugabogdan** [comment]
> You were too quick for me! 😆 Went looking for a vector version of their icon as soon as I saw your issue and, by the time I got back, you had the PR in already.

I started to work at the icon before I added the issue 😅  

> Found this sprite in the source of their main site which includes a couple of versions of the "PP." icon. Would you mind taking another go at it using that SVG instead?

Yeah I can take a look on those too, maybe we will see some improvements. 

IMO the one I added looks good.

> Thanks for the contribution, by the way 🙂

No worries, I use lots of things from https://shields.io/ for some of our projects, and the icons come from here. It's the least I can do as a thanks for making this awesome opensource project.

**Comment by iugabogdan** [comment]
Okay, changed it a bit, tbh I can't see much difference. Updated the preview as well.

**Comment by iugabogdan** [comment]
Have you managed to look over it @PeterShaggyNoble ?

**Comment by PeterShaggyNoble** [comment]
Sorry for the delay, @iugabogdan, been a hectic week getting everything prepped for the release of v5 and launch of the new website this weekend.

Which version of the icon is your SVG based on? I'm seeing [some differences](https://user-images.githubusercontent.com/15157491/119971129-7d263900-bfa8-11eb-8b3c-5d415941eb66.png) when comparing it against both versions in the sprite I linked above, with yours in red, the Paddy Power Bingo one in black and the Paddy Power Games one in grey - although given that the dot in the Games one is a square, I think we can rule out using it.

Also, if you did base your version on that sprite, could you update the `source` to the main website, please?

**Comment by iugabogdan** [comment]
Hey @PeterShaggyNoble, I used this one from what I remember, the one with the dot.

image

Tbh I've no idea what I've done, I'm like this dog when it comes to svgs. I just click on buttons in inkscape and hope for the best.

image

Not sure how you got that difference, I can try again cuz definitely I've did something wrong.

**Comment by iugabogdan** [comment]
Hey @PeterShaggyNoble 

After few google searches did it again, it should be ok now! 

Not sure however why the Lint fails.

Thanks

**Comment by iugabogdan** [comment]
Ran the linter on my machine and everything is fine..

**Comment by adamrusted** [comment]
Hey @iugabogdan - looks like the main issue with the linter is part of the v5 update. As part of this week's release, we've removed the requirement for you to include 'icon' in the `<title>` of the SVG. If you are able to remove that, and perhaps rebase your PR to our current `develop` branch - this should succeed!

**Comment by iugabogdan** [comment]
Hey @adamrusted, I rebased and deleted the title and now I get this.

image

**Comment by iugabogdan** [comment]
@adamrusted @PeterShaggyNoble hey guys seems that everything is alright now. 

Can you please have a look when you have time ?

Thanks!

**Review by PeterShaggyNoble — APPROVED** [review]
Perfect :+1: Thanks, @iugabogdan.

**Pull request merged**
