### PR TITLE
Add command to run all linting at once

### PR DESCRIPTION
**Pull request by ericcornelissen**
**Issue:** n/a

### Description

Following a comment in #2958, this adds a new command that will run all our linting at once. Also, I added a line to the [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) mentioning that you can run this command to check for issues.

I intentionally put it after the "Once you've completed the previous steps, create a pull request to merge your edits into the *develop* branch." line; and I intentionally worded it as _"You can run [...]"_; to make it clear that people are free to open a Pull Request without running `npm run lint`, in case they don't know how to or simply can't (since npm nor node are not required for contributing).

### CODE REVIEW

**Comment by runxel** [comment]
Great addition! Thanks for this valuable improvement, Eric!

**Comment by davidjb** [comment]
@ericcornelissen @runxel These changes were recently lost.  I've opened a PR to restore what was removed; a later commit removed the changes to `package.json`

**Comment by runxel** [comment]
Wow, great catch! Thanks @davidjb!
The culprit was our dependency updater in https://github.com/simple-icons/simple-icons/commit/e3b3be9532386f53e2d78f11831367f248d8a966#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
I wonder if we have to reconfigure this bot, so it doesn't happen again.
@ericcornelissen can you look into that? You know more about this.

**Comment by ericcornelissen** [comment]
Thanks for pointing this out @davidjb! I was already semi-aware of the problem (see https://github.com/simple-icons/release-action/issues/8) but did not realize it had removed the `lint` command and the related `npm-run-all` dependency.

**Pull request merged**
