### PR TITLE
Add UptimeRobot icon

### LINKED ISSUE #3831: Uptime Robot
Name: Uptime Robot
Website: uptimerobot.com
Alexa rank: 12447

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** Close #3831
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I used the full wordmark SVG from the header of their [website](https://uptimerobot.com/)
- I used Inkscape to keep only the dot, the `U` and the `R`
- I used their [Facebook icon](https://www.facebook.com/491300654233236/photos/3593514437345160/) to position
- I used Inkscape to scale
- I used https://jakearchibald.github.io/svgomg/ to optimize

### CODE REVIEW

**Review by adamrusted — COMMENTED** [review]
I'm seeing a couple small differences when comparing to my version, but given we're both working from a PNG for sizing / spacing, I'd be happy to go with yours if another @simple-icons/maintainers agrees. Obviously the SVG will need updating to remove `icon` from the `<title>` field, but otherwise this'll be good to go assuming others are ok with it.

**Comment by adamrusted** [comment]
In fact, scrap my review above. It appears they now use a duotone circle as their icon on socials (as well as their favicon). Should we instead use that?

**Comment by service-paradis** [comment]
> In fact, scrap my review above. It appears they now use a duotone circle as their icon on socials (as well as their favicon). Should we instead use that?

Oh! It will be a little bit more difficult to keep this recognizable monochromatic... But, I'm not sure the `UR` version from this PR is a valid choice now since it is not used anymore (but LinkedIn)...

**Comment by adamrusted** [comment]
Closing as logo has been re-designed, and wouldn't be recognisable as a simple icon.

**Pull request closed without merging**
