### PR TITLE
Add foobar2000

### PR DESCRIPTION
**Pull request by mfarragher**
foobar2000-preview

**Issue:** #5356 
**Alexa rank:** 99,128 at time of issue

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
👽🐱
Used the hex and source 'alien cat' vector suggested in the issue thread.

This is how the icon rendered when I did a build of the website via Gitpod (I never knew about Gitpod before, it is 👌!):
foobar2000-web-build

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @mfarragher, and thanks for the contribution 🙂

So we can compare like with like, did you base your icon on the PS file mentioned in the original issue or a different file?

**Comment by mfarragher** [comment]
Yes, I based it on the Postscript file in this [topic](https://hydrogenaud.io/index.php?topic=55604.0).

**Comment by PeterShaggyNoble** [comment]
Thanks, @mfarragher.

I'm seeing some [minor differences](https://user-images.githubusercontent.com/15157491/118661529-17d38a80-b7e7-11eb-93bb-791ed1d60a33.png) in [both eyes](https://user-images.githubusercontent.com/15157491/118661611-2f127800-b7e7-11eb-9544-ce7b00008d2f.png) & [the mouth](https://user-images.githubusercontent.com/15157491/118661688-43567500-b7e7-11eb-9f9f-f62ca99c52a2.png) as well as a hairline thin one [down the right edge](https://user-images.githubusercontent.com/15157491/118661837-67b25180-b7e7-11eb-9283-962f607f78dc.png). Would you mind having another look at those? They are all most likely, although not necessarily, due to the precision needing to be set a little higher when optimising.

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @mfarragher?

**Comment by mfarragher** [comment]
I will take a look this weekend

**Comment by ericcornelissen** [comment]
@mfarragher it seems _the weekend_ has passed, will you still be able to work on this?

**Comment by mfarragher** [comment]
> @mfarragher it seems _the weekend_ has passed, will you still be able to work on this?

Hi I will struggle to work on it now

**Comment by jorgeamadosoria** [comment]
given that his PR has not been worked on by more than 6 months I'll be marking this as abandoned and will take over it as soon as possible.

**Pull request closed without merging**
