### PR TITLE
Add Île-de-France Mobilités icon

### LINKED ISSUE #8095: [COLLECT] Public transit networks
- [x] Île-de-France Mobilités (#8062)
- [x] RTM (#8066)
- [x] CTS (#8072)
- [x] BVG (#8073)
- [ ] FGC
- [ ] PANYNJ

Not a duplicate of #2822 since these are public transit authorities/associations managing the cities or regions public transit and not the subway or bus network itself.

### PR DESCRIPTION
**Pull request by jamu3l**
iledefrancemobilites

Closes #8095

**Similarweb rank:** 14,565
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This is the icon for the French public transit network that includes the Paris Metro as well. [Their website](https://www.iledefrance-mobilites.fr) and the [Wikipedia article](https://en.wikipedia.org/wiki/Île-de-France_Mobilités) points to this logo.

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @jamu3l,

can you check the icon again, as I see some differences!

image

**Comment by jamu3l** [comment]
Fixed :)

**Review by dirien — APPROVED** [review]
Hi @jamu3l,

I think this is as good as it can be.
image

So, I will approve it.

Thanks for contributing and happy holidays!

**Comment by jamu3l** [comment]
Thank you, @dirien!! I wish you happy holidays as well :)

**Pull request merged**
