### PR TITLE
Update RabbitMQ icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** #4590
**Alexa rank:** N/A
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I started from scratch with the header logo found at https://www.rabbitmq.com/ (the current one was diffenrent)
- I used Inkscape to scale
- I optimized it
- I added the guideline entry

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Matches perfectly to the source SVG @service-paradis - though there are a lot of excess points [around the curves](https://user-images.githubusercontent.com/1830867/110133543-54850d80-7dc4-11eb-98b1-fe4a95e5497b.png) - would you be able to reduce those down at all?

**Comment by service-paradis** [comment]
> Matches perfectly to the source SVG @service-paradis - though there are a lot of excess points [around the curves](https://user-images.githubusercontent.com/1830867/110133543-54850d80-7dc4-11eb-98b1-fe4a95e5497b.png) - would you be able to reduce those down at all?

Thanks for the review. Weird, I dont see those extra points using Inkscape...
image

I will try to find what is going on!

**Comment by adamrusted** [comment]
> > Matches perfectly to the source SVG @service-paradis - though there are a lot of excess points [around the curves](https://user-images.githubusercontent.com/1830867/110133543-54850d80-7dc4-11eb-98b1-fe4a95e5497b.png) - would you be able to reduce those down at all?
> 
> Thanks for the review. Weird, I dont see those extra points using Inkscape...
> image
> 
> I will try to find what is going on!

Weird! It may just be Figma adding additional points then. I'll have to resort to a _proper_ piece of software for comparing my icons! 😅

**Review by adamrusted — APPROVED** [review]
Looking at this again in Affinity Designer - I can confirm those additional points are there. Note to self, don't review icons in Figma any more! Thanks @service-paradis for your work on this 💪

**Pull request merged**
