### PR TITLE
Add Notion Everything Icon

### PR DESCRIPTION
**Pull request by Mvlprem**
notioneverything

**Similarweb rank:** [305,501](https://www.similarweb.com/website/notioneverything.com/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

[svg](https://assets-global.website-files.com/5eea4f5bf14e8c7d53fadc66/5f9304c586e3e50328d7f35c_LOGO%20NOTION%20EVERYTHING%20v2-09.svg) taken from [website](https://www.notioneverything.com/) header, hex taken from stylesheet ` --primary-color `

### CODE REVIEW

**Comment by service-paradis** [comment]
According to https://www.notioneverything.com/terms-and-conditions, it looks like we need to have permission to use their logo:

> No use of Notion Everything's logo or other artwork will be allowed for linking absent a trademark license agreement.

**Comment by PeterShaggyNoble** [comment]
> According to https://www.notioneverything.com/terms-and-conditions, it looks like we need to have permission to use their logo.

I think we can work around this one, @service-paradis, thanks to them very specifically mentioning using their logo for _linking_. Not everyone who uses our icons does use them to link to brands and including the Ts&Cs as a `guidelines` entry should cover us for for those that do. What do you think?

**Comment by service-paradis** [comment]
> > According to https://www.notioneverything.com/terms-and-conditions, it looks like we need to have permission to use their logo.
> 
> I think we can work around this one, @service-paradis, thanks to them very specifically mentioning using their logo for _linking_. Not everyone who uses our icons does use them to link to brands and including the Ts&Cs as a `guidelines` entry should cover us for for those that do. What do you think?

Hmm... I'm not sure. They begin by stating, "Notion Everything and/or its licensors own the intellectual property rights for all material on Notion Everything," and we cannot reproduce, duplicate, or copy material from Notion Everything. After this, they discuss hyperlinking to their content, which requires approval for most organizations. Then, they mention using their logo for hyperlinking, but it requires a trademark license agreement to overcome the initial restriction on its use.

Overall, it seems to indicate that using their logo is generally prohibited, but they may grant permission to do so under certain circumstances, particularly for linking purposes.

**Comment by PeterShaggyNoble** [comment]
🤔 It's a tricky one. Within the context of the document as a _whole_, though, the line you initially quoted takes on a slightly different meaning and my reading of it would be that we can't include this one at all. May be worth trying to make contact for clarification, though.

**Comment by adamrusted** [comment]
Did you want to reach out to them @Mvlprem to seek permission?

**Comment by adamrusted** [comment]
Closing, as we require permission to include this. If you reach out to the brand @Mvlprem - ping here and we can re-open the PR.

**Pull request closed without merging**
