### PR TITLE
Correct GitLab icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** #3169
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- I took the Knockout SVG from https://about.gitlab.com/press/press-kit/.
- I used Inkscape to fix size and center
- I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by runxel — CHANGES_REQUESTED** [review]
I was wondering why the new svg became so much larger than the old one.
On opening I found a lot of superfluous points – on the straight lines and especially a mess in the most bottom rounding.
How were they introduced? 
I sadly can't accept this PR until the file is cleaned up.

**Comment by service-paradis** [comment]
Oh, you're right, sorry about that!
I started again from scratch, used Inkscape to resize and to clean some lines. Like before, used https://jakearchibald.github.io/svgomg/ to optimize.
Hope it is better this time!

**Review by runxel — APPROVED** [review]
Yeah, that looks clean. Thank you so much for your work! 💯

**Comment by service-paradis** [comment]
Great! Glad you like it :)

**Pull request merged**
