### PR TITLE
Add MusicBrainz

### LINKED ISSUE #2973: Musicbrainz
**Name:** musicbrainz
**Website:** musicbrainz.org
**Official resources for icon and color:** https://wiki.musicbrainz.org/File:MusicBrainz_logo_2016.svg

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
MusicBrainz

**Issue:** Closes #2973 (rel: Templarian/MaterialDesign#907 -ListenBrainz's [Alexa rank](https://www.alexa.com/siteinfo/listenbrainz.org) is _far_ too low)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon & colour from [this SVG](https://metabrainz.org/static/img/projects/musicbrainz.svg). I went with the pink as it seems to be used more than the orange (`eb743b`) on [their site](https://musicbrainz.org/) but a case could probably be made for either.

**Alexa rank:** [46845](https://www.alexa.com/siteinfo/musicbrainz.org)

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the detailed review, @phatbhoy67 :+1: That particular issue should be fixed now, along with a reduction in precision from `4` to `3`.

Unfortunately, I'm only now noticing that this thing is absolutely riddled with excess points and imperfections - particularly the top-right of the musical note. They're present in [all their SVGs](https://github.com/metabrainz/metabrainz-logos/tree/master/final-logos/MusicBrainz/VECTOR/SVG) but less severe in [the AI files](https://github.com/metabrainz/metabrainz-logos/tree/master/final-logos/MusicBrainz/VECTOR) but the AIs, for some reason, are not playing nice with SVGO(MG) and the problems are beyond my capabilities to fix while maintaining the integrity of the icon 🙁

**Comment by PeterShaggyNoble** [comment]
Thanks to @phatbhoy67 for the fixes in the latest version of the SVG.

**Comment by runxel** [comment]
> and the problems are beyond my capabilities to fix while maintaining the integrity of the icon

Do you want some help? What is the status on this one? :)

**Comment by PeterShaggyNoble** [comment]
@runxel, those issues were fixed in the last commit thanks to @phatbhoy67 so, subject to a regular review, this should be good to go now.

**Pull request merged**
