### PR TITLE
add fontbase icon

### PR DESCRIPTION
**Pull request by stefanobartoletti**
fontbase

**Issue:**
**Alexa rank:** ~391k

### Checklist
  - [x] The SVG `viewbox` is `0 0 24 24`
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG

### Description

Icon made from the svg logo and color taken from the website

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Great job @stefanobartoletti!
There are a few [excess](https://user-images.githubusercontent.com/1830867/113474391-a3779e80-9467-11eb-91d9-f5dfbaaae0a5.png) [points](https://user-images.githubusercontent.com/1830867/113474396-ad999d00-9467-11eb-9dab-2e0e930fc3e3.png) throughout your PR which could be removed, but other than those it matches up perfectly! Could you have a look at getting rid of some of those before we merge it?

**Comment by stefanobartoletti** [comment]
Thank you, I tried to find these excess points from Inkscape but they don't seem to be present. Have you used some other app to find them?

I also tried to rerun `svgo` and `lint` scripts, but nothing was reported.

Can you give me some more feedback?

**Comment by adamrusted** [comment]
> Thank you, I tried to find these excess points from Inkscape but they don't seem to be present. Have you used some other app to find them?

Weird! I'm using Affinity Designer - and opening it up in Inkscape gets rid of those points! The other 'excess points' I was talking about were the ones where there were points in the middle of a [straight line](https://user-images.githubusercontent.com/1830867/113475109-8cd34680-946b-11eb-8d3f-44c5b3feda5d.png). You can safely remove those, leaving just the start and end of a straight segment.

> I also tried to rerun `svgo` and `lint` scripts, but nothing was reported.

Yeah, sometimes there are small enough differences between these points that the math in the linter script doesn't pick it up. Always worth re-opening the optimized icon and checking for any unnecessary points along the path 😅

> Can you give me some more feedback?

If there's anything else you need, feel free to give me a shout. 👍

**Comment by stefanobartoletti** [comment]
Done, I removed the intermediate points. It should be fine now, let me know.

**Review by adamrusted — COMMENTED** [review]
Weird - I'm now seeing duplicate points at [these locations](https://user-images.githubusercontent.com/1830867/114307176-65692300-9ad6-11eb-8afe-5c4ea24cc614.png) when viewing in Illustrator. Could another @simple-icons/maintainers take a look at this and make sure I'm not seeing things? 😅

**Comment by stefanobartoletti** [comment]
Strange, I just had a look with Inkscape and these points are not displayed as duplicates.

Again, running `svgo` and `lint` scripts doesn't help, they run correctly and report no errors.

Let me know if I need to do some more checks, but I don't know how to improve further this icon.

**Comment by PeterShaggyNoble** [comment]
I'm noticing more & more that SVGO does occasionally introduce duplicate points during the optimisation process so that may be the cause here.

**Comment by stefanobartoletti** [comment]
I still can't find these duplicates. Feel free to take this as a base for further optimizations, I can't reproduce what you are seeing and I'm stuck.

**Comment by PeterShaggyNoble** [comment]
Just double checked in Inkscape and can see no duplicate points so I'll merge this in based on Adam's approval above.

Thanks for your work on this one, @stefanobartoletti 👍🏻

**Pull request merged**
