### PR TITLE
Added OPNSense

### LINKED ISSUE #3785: Please add the OPNSense Icon
**Name:** OPNSense
**Website:** https://opnsense.org/
**Alexa rank:** 143,461
  

**Official resources for icon and color:** https://forum.opnsense.org/index.php?topic=2561.0 is the best I can find for legal stuff.
The no-text version of the logo is https://github.com/opnsense/core/blob/master/src/opnsense/www/themes/opnsense/build/images/icon-logo.svg and the text version is https://github.com/opnsense/core/blob/master/src/opnsense/www/themes/opnsense/build/images/default-logo.svg
  
  

Thanks!

### PR DESCRIPTION
**Pull request by adamrusted**
opnsense

**Issue:** Closes #3785
**Alexa rank:** [153,026](https://www.alexa.com/siteinfo/opnsense.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Color extracted from SVG. Gap of 0.5px used between paths on different 'layers'.

### CODE REVIEW

**Comment by fbernhart** [comment]
The icon itself matches perfectly the source. 👍🏼 

However I feel like there are "too many gaps" and the logo differs quite a lot from the [original one](https://raw.githubusercontent.com/opnsense/core/06b1804a3d358041607ec3a963ab90b720564cc3/src/opnsense/www/themes/opnsense/build/images/icon-logo.svg). How about just separating the arrows with gaps? Something like this:

simpleicons

What do the other @simple-icons/maintainers think?

**Comment by adamrusted** [comment]
@fbernhart I agree it's quite busy - but I thought it was best to try and show the dimensions of the logo. If we're going to simplify it - can I suggest the two horizontal lines (darker grey [here](https://github.com/opnsense/core/blob/master/src/opnsense/www/themes/opnsense/build/images/icon-logo.svg)) also get outlined, just to give an element of depth?

**Comment by ericcornelissen** [comment]
I would say the current SVG in this PR is already a "simplification" (of sorts) of the original, more accurately it's an artistic impression, and so is @fbernhart's [version](https://github.com/simple-icons/simple-icons/pull/4557#issuecomment-755382828). Arguably @fbernhart's version goes against #4566, but I would expect there to still be quite some freedom with regards to which continuous geometries are actually separate (as per that PR's title, they are recommendations). I do feel like @fbernhart's version looks better at larger sizes, while not making much of a difference at small sizes.

**Comment by adamrusted** [comment]
Happy to go with @fbernhart's version if other @simple-icons/maintainers agree?
If that's the case, @fbernhart would you mind merging your path into this PR?

**Comment by fbernhart** [comment]
@adamrusted My preview was just a quick draft. 😄 I didn't do it properly, so it would need to be rebuilt from scratch anyway.

I wouldn't mind working on it (if we've reached a consensus on this one - have we?). But if you want, you can do it as well. 😊

**Comment by adamrusted** [comment]
> I wouldn't mind working on it (if we've reached a consensus on this one - have we?). But if you want, you can do it as well. 😊

I'll take a look at it later on 👌

**Comment by adamrusted** [comment]
@fbernhart - rebuilt from scratch using your idea. Could you take a look over please? 🙏🏻

**Comment by fbernhart** [comment]
@adamrusted The icon looks good. 👍🏼

My version had angular/sharp/pointed edges/angles (not sure what the correct term in English is 😅 ) while your gaps are rounded. I think both versions are fine and it's just a matter of taste. So unless maybe @ericcornelissen has a preferred version, I think we can merge your version. 😊

**Comment by PeterShaggyNoble** [comment]
Tricky one to monochromise and I don't think either treatment is necessarily wrong but I think, for our purposes, @fbernhart's version works better at native size. I do agree, though, that the arrowheads and their cut-outs shouldn't have rounded corners as the arrows in the original are sharp.

**Comment by adamrusted** [comment]
@PeterShaggyNoble swapped out for the sharp-cornered version.

**Comment by fbernhart** [comment]
@adamrusted Perfect 👍🏼  One last thing: Could you give it a try cleaning up the imperfections and unnecessary points in the top left and bottom right corner? There are some 50+ points on each corner, which aren't really needed.

image

**Comment by adamrusted** [comment]
@fbernhart try that

**Comment by fbernhart** [comment]
@adamrusted Amazing! The file size has decreased by 50% now. 💪🏼 

I'll merge it now.

**Pull request merged**
