### PR TITLE
Add Viaplay Icon

### LINKED ISSUE #8494: Request icon: Viaplay
### Brand Name

Viaplay

### Website

https://viaplay.se

### Popularity Metric

Viaplay is ranked 11,593 in the world, regarding traffic. 

https://www.similarweb.com/website/viaplay.se/#overview

### Official Resources for Icon and Color

none

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by RiteshK-611**
**Issue:** closes #8494

**Similarweb rank:**
Viaplay is ranked 11,593 in the world, regarding traffic.
https://www.similarweb.com/website/viaplay.se/#overview

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This commit resolves issue #8494 by adding Viaplay logo in viaplay.svg file and by updating simepl-icons.json file with icon's data

### Preview
viaplay

### CODE REVIEW

**Comment by LitoMore** [comment]
@RiteshK-611 Please give more details about the brand color. Their logo is in gradient color.

Issue #8494 provides a https://viaplay.se in non-English, and it shows `Något gick snett (Something went wrong)`. So I switched to their English site and found the color `#FE365F` on their primary buttons.

The `#FE365F` matches what you've submitted. But I'd still like to know where you got it from.

**Comment by RiteshK-611** [comment]
@LitoMore I got that color from here https://viaplay.com/gb-en/

**Review by adamrusted — CHANGES_REQUESTED** [review]
Happy with the hex, but I'm spotting a difference between your PR an the source icon, with the white arrow subtracted. Could you take another look please @RiteshK-611?
image

**Comment by RiteshK-611** [comment]
> Happy with the hex, but I'm spotting a difference between your PR an the source icon, with the white arrow subtracted. Could you take another look please @RiteshK-611? 

Sure @adamrusted but I lost the source, can you provide me the link of the svg

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @RiteshK-611 🎉

**Pull request merged**
