### PR TITLE
Update notepadplusplus

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** #4590
**Alexa rank:** N/A
  

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I manually remove the problematic segment
- ~~I also remove an unnecessary coordinate at the end of the path~~

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Seeing some differences between your PR (black) and the source icon (red) [here](https://user-images.githubusercontent.com/1830867/110205956-ef3c2580-7e72-11eb-9f83-502bd658e7b3.png) - any chance you could look to rebuild it?

**Comment by service-paradis** [comment]
> Seeing some differences between your PR (black) and the source icon (red) [here](https://user-images.githubusercontent.com/1830867/110205956-ef3c2580-7e72-11eb-9f83-502bd658e7b3.png) - any chance you could look to rebuild it?

Good catch! I started from scratch this time! :)

**Comment by service-paradis** [comment]
> This does not look like a fun icon to work on so sorry about this! I'm seeing a [small difference in the right eyeball](https://user-images.githubusercontent.com/15157491/110346107-22bfb100-8027-11eb-98ff-52d7bd13b018.png) (your version in red) and [an even smaller one at the top of the intersection](https://user-images.githubusercontent.com/15157491/110346220-3cf98f00-8027-11eb-970b-82abbb9b458b.png) between the tail & the pencil.

haha, surely not a fun one 😃, but thanks for the review. I will check this out!

> Also, could you update the source to https://github.com/notepad-plus-plus/notepad-plus-plus/blob/1f2c63cce173e3e1dc5922637c81a851693e2856/PowerEditor/misc/chameleon/chameleon-pencil.eps?

Sure!

**Comment by service-paradis** [comment]
Just gave it another try. Let me know if there is something else!

**Review by adamrusted — APPROVED** [review]
There are a [couple](https://user-images.githubusercontent.com/1830867/110791485-2f801700-826a-11eb-8bef-8eb12723974d.png) of [tiny](https://user-images.githubusercontent.com/1830867/110791522-39a21580-826a-11eb-9861-8bdc9d4823c0.png) differences between source (black) and PR (red) - though it looks like they'll almost certainly be down to optimization. Other than those, the icon is perfect - and I'd be happy to merge if another @simple-icons/maintainers okays the tiny differences.

**Comment by fbernhart** [comment]
LGTM 👍🏼  Thanks @service-paradis

**Pull request merged**
