### PR TITLE
Added Matomo

### LINKED ISSUE #4453: Matomo
**Name:** Matomo Analytics
**Website:** https://matomo.org/
**Alexa rank:** [~23,311](https://www.alexa.com/siteinfo/matomo.org)
  

**Official resources for icon and color:**
  
- They have a [dedicated media page](https://matomo.org/media/) on their website with [a link to their press kit](https://matomo.org/wp-content/uploads/2020/02/Matomo-Press-Pack-2020-2.zip) that includes their logo, including SVG
- A good color would be `#3152a1` (dark blue) as it's the most prominent in their logo

### PR DESCRIPTION
**Pull request by Jorys-Paulin**
103102295-9acb2d00-461b-11eb-92e7-7f2491834cd7

**Issue:** Fixes #4453
**Alexa rank:** [~23,311](https://www.alexa.com/siteinfo/matomo.org)

  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The color (dark blue `#3152A0`) was chosen because it's the most prominent on the logo
The icon was created from the official logo by @adamrusted since I lack the design skills.

### CODE REVIEW

**Comment by adamrusted** [comment]
Hi @Jorys-Paulin, if the pull request is ready to go, could you please mark it as ready for review?

**Comment by adamrusted** [comment]
Could another @simple-icons/maintainers sign this one off please - being as I worked on the SVG?

**Review by mondeja — CHANGES_REQUESTED** [review]
I'm seeing only one inconsistency with this version (black). The icon hasn't the same height for the three rounded lines of the "M":

image

**Comment by adamrusted** [comment]
> I'm seeing only one inconsistency with this version (black). The icon hasn't the same height for the three rounded lines of the "M":

Should be fixed now @mondeja - see if that's any better :grin:

**Review by mondeja — CHANGES_REQUESTED** [review]
I'm seeing now that you've introduced these corners that didn't exist in the previous version:

image

I feel like the previous version was more adjusted to the original icon than this with these corners. Could you recover the smoothness of both curves?

**Comment by adamrusted** [comment]
> I feel like the previous version was more adjusted to the original icon than this with these corners. Could you recover the smoothness of both curves?

One rebuild from source later. I think the original issue was that I hadn't excluded the 'border' from the bottom right shape. Should be good now.

matomo

**Review by mondeja — APPROVED** [review]
Perfect, thank you @adamrusted! :trophy:

**Comment by adamrusted** [comment]
> Perfect, thank you @adamrusted! 🏆

And thanks @Jorys-Paulin for your work on this! 💯

**Pull request merged**
