### PR TITLE
Correct curl icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** #3169
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- I took the already used SVG.
- I used Inkscape to fix size and center
- I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Hmm, it looks like your update slightly changed the shape of the logo, as you can see in the comparisons below. Specifically, the bottom right circle seems to have a slightly different shape than before. Any ideas why this is the case? Did you compare your version to the source SVG?

| Full | Bottom right |
| --- | --- |
| image | image |

**Comment by service-paradis** [comment]
> Hmm, it looks like your update slightly changed the shape of the logo, as you can see in the comparisons below. Specifically, the bottom right circle seems to have a slightly different shape than before. Any ideas why this is the case? Did you compare your version to the source SVG?

Hum... you're right! Sorry about this. I will take another look!

**Comment by service-paradis** [comment]
I gave it another try. The SVGO tools is messing with circles when I use a precision of 3. Looking fine with a precision of 4. Do I keep it this way?
image

**Review by ericcornelissen — APPROVED** [review]
A precision of 4 is fine (as per #3120), thanks for the quick update @service-paradis :+1:

**Pull request merged**
