### PR TITLE
Add LLVM icon (#1936)

### PR DESCRIPTION
**Pull request by phatbhoy67**
**Issue: #1936**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with ~SVGO or~ SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

~Manual vector silhouette of the wyvern (type of dragon) in the [official logo .png](https://llvm.org/img/DragonFull.png).~

Official source [.ai](https://llvm.org/img/Dragon.ai) converted to .svg.

The logo mainly `#252c38` and many grey silvers including `#c9ced4`.

~Hex value chosen, `#252C38`,  is from the dragon wings in the full logo.~

Hex value the color of the text in this derivative image: (https://llvm.org/img/LLVM-Logo-Derivative-5.png)

Built on Gitpod, working as expected.

### CODE REVIEW

**Comment by h1nk** [comment]
I'm not too sure about the color. Because the wings are a gradient, perhaps `#262D3A` would be better. It's taken from the color of the text in [this](https://miro.medium.com/max/2048/0*zG7y02APSeZ6MzDv.png) and [this](https://llvm.org/img/LLVM-Logo-Derivative-5.png) image, or maybe instead `#556293` which was taken from [this](https://llvm.org/img/LLVM-Logo-Derivative-1.png) and [this](https://llvm.org/img/LLVM-Logo-Derivative-2.png).

I'd say probably the darker one (`#262D3A`) though because it's closer to the average gradient color of the wings in the main logo.

**Comment by h1nk** [comment]
Also, it might be better to make the silhouette paths based off of the official [Illustrator file](https://llvm.org/img/Dragon.ai) rather than doing it manually from the raster image.

**Comment by phatbhoy67** [comment]
> I'm not too sure about the color.

Hey @hink the diff in rgb values between the colour you picked and the one I chose from the gradient are approx ±1 on each channel 👀 Spooky 👻 
`#252C38`
`#262D3A`
I'll be honest, I can't really tell them apart visually. Happy to update the PR all the same 😸

**Comment by h1nk** [comment]
> the diff in rgb values between the colour you picked and the one I chose from the gradient are approx ±1 on each channel

Haha, I only noticed the last channel was different.

> Happy to update the PR all the same

Yeah, I think updating the color to the one pulled from the text and taking the silhouette path from the official vector instead of manual rasterization would be best.

**Comment by phatbhoy67** [comment]
> updating the color to the one pulled from the text

🎉 Done

**Comment by birjolaxew** [comment]
:+1: Thanks for your work on this @phatbhoy67, and your reviewing of it @h1nk!

**Pull request merged**
