### PR TITLE
Add Peerlist icon

### LINKED ISSUE #7328: Peerlist
### Brand Name

Peerlist

### Website

https://peerlist.io 

### Popularity Metric

The Similarweb rank is 418,650
https://www.similarweb.com/website/peerlist.io/#overview

### Official Resources for Icon and Color

https://peerlist.notion.site/Peerlist-logos-usage-25c5f4fd534e4c19ba7913a2819ca26a

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
peerlist

**Issue:** closes #7328 

**Similarweb rank:** 318,349. See https://www.similarweb.com/website/peerlist.io

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Available at the footer of the website https://www.peerlist.io
Color: `#00AA45` taken from the same SVG

### Reason for duplicate PR
There was no closure from the contributor in discussion #7603 and PR #7602 was never updated based on comments by reviewers and the discussion thread

### CODE REVIEW

**Review by adamrusted — COMMENTED** [review]
Thanks for this contribution @PratyushJayachandran 🙏
While creating a version to compare your PR against, I came up with the below.
This version maintains the different colour bands of the wider shape, while also maintaining the outline around the `P`.
peerlist
You're more than welcome to use it, though we'll need another @simple-icons/icon-review member to review if you do!
```html
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Peerlist</title><path d="M12 0c-.584 0-1.14.011-1.673.033-.44.018-.861.046-1.268.08l-.125.01-.366.035-.326.037-.328.043-.322.047-.274.043-.287.053c-.13.024-.26.049-.385.076l-.058.014a13.25 13.25 0 0 0-.473.111 11.136 11.136 0 0 0-.986.307c-.08.028-.154.059-.231.09-.081.032-.164.063-.244.097-.084.036-.166.075-.248.113a6.568 6.568 0 0 0-.457.233l-.133.076a6.922 6.922 0 0 0-.625.41c-.06.045-.117.092-.175.139-.067.053-.136.104-.2.16l-.04.037a6.383 6.383 0 0 0-.532.533l-.037.039c-.056.064-.107.133-.16.2-.047.058-.094.115-.14.175a5.786 5.786 0 0 0-.137.198 6.922 6.922 0 0 0-.272.427l-.076.133a6.568 6.568 0 0 0-.14.264 8.656 8.656 0 0 0-.093.193c-.038.082-.077.164-.113.248-.034.08-.065.163-.097.244-.031.077-.062.152-.09.23l-.008.02a10.356 10.356 0 0 0-.41 1.44l-.014.058C.43 6.772.405 6.9.381 7.03l-.053.287-.043.274-.047.322-.043.328-.037.326-.035.366-.01.125a29.81 29.81 0 0 0-.08 1.268A40.509 40.509 0 0 0 0 12c0 .583.011 1.14.033 1.672.018.441.046.862.08 1.27l.01.124.035.366.037.326a26.403 26.403 0 0 0 .09.65l.041.26c.022.13.046.256.07.381l.049.25c.018.085.038.167.057.25.025.107.049.215.076.318.015.057.032.111.047.166.062.228.13.448.203.66l.06.176c.034.09.069.177.104.264.028.069.053.14.082.207.037.086.078.17.117.254.032.067.063.135.096.201.037.074.076.145.115.217.04.074.08.147.123.218a6.629 6.629 0 0 0 .29.45l.076.103c.059.081.122.159.185.237.045.054.087.11.133.164a5.789 5.789 0 0 0 .545.548c.022.02.042.042.064.06.064.057.133.108.2.16.058.048.115.095.175.14.064.047.13.093.198.138a6.922 6.922 0 0 0 .427.272l.133.076a6.568 6.568 0 0 0 .457.233c.082.038.164.077.248.113.09.038.18.073.274.109.062.025.123.05.187.074a9.918 9.918 0 0 0 1.018.315c.147.038.3.073.455.107l.058.014a17.487 17.487 0 0 0 .688.13l.234.04c.118.018.237.034.358.05l.312.042.336.037.35.035.14.012c.406.034.822.06 1.261.078a40.509 40.509 0 0 0 2.527.025 34.82 34.82 0 0 0 2.08-.103l.14-.012.35-.035.335-.037.312-.041c.121-.017.24-.033.358-.051l.234-.04a17.487 17.487 0 0 0 .688-.13l.058-.014a10.356 10.356 0 0 0 1.473-.422c.064-.023.125-.05.187-.074.093-.036.184-.071.274-.11.084-.035.166-.074.248-.112a8.656 8.656 0 0 0 .457-.233l.133-.076a6.922 6.922 0 0 0 .625-.41c.06-.045.117-.092.175-.14.067-.052.136-.103.2-.16l.004-.003.06-.057a5.58 5.58 0 0 0 .252-.234c.079-.08.154-.162.229-.246.019-.022.04-.042.06-.064l.004-.004c.046-.053.088-.11.133-.164.063-.078.126-.156.185-.237l.075-.103a6.629 6.629 0 0 0 .29-.45c.043-.071.083-.144.124-.218.039-.072.078-.143.115-.217.033-.066.064-.134.096-.201.039-.084.08-.168.117-.254.029-.067.054-.138.082-.207.035-.087.07-.174.103-.264l.008-.017c.019-.052.035-.106.053-.159.073-.212.14-.432.203-.66.014-.05.03-.097.043-.148l.004-.018c.027-.103.05-.21.076-.318.019-.083.039-.165.057-.25l.049-.25c.024-.125.048-.252.07-.38l.04-.26a24.807 24.807 0 0 0 .09-.65l.038-.327.035-.366.01-.125c.034-.407.062-.828.08-1.269a40.509 40.509 0 0 0 .025-2.527 29.753 29.753 0 0 0-.105-2.085l-.01-.125-.035-.366-.037-.326a26.403 26.403 0 0 0-.09-.65l-.041-.26a18.594 18.594 0 0 0-.07-.381l-.05-.25c-.017-.085-.037-.167-.056-.25-.025-.107-.05-.215-.076-.318l-.004-.018c-.013-.051-.03-.098-.043-.148-.062-.228-.13-.448-.203-.66-.018-.053-.034-.107-.053-.16l-.008-.016a9.063 9.063 0 0 0-.103-.264c-.028-.07-.053-.14-.082-.207-.037-.086-.078-.17-.117-.254-.032-.067-.063-.135-.096-.201-.037-.074-.076-.145-.115-.217-.041-.074-.081-.147-.123-.218a6.629 6.629 0 0 0-.291-.45l-.075-.103a6.028 6.028 0 0 0-.185-.237c-.045-.054-.087-.111-.133-.164l-.004-.003a5.684 5.684 0 0 0-.541-.545l-.06-.057-.004-.004c-.064-.056-.133-.107-.2-.16-.058-.047-.115-.094-.175-.14a5.786 5.786 0 0 0-.198-.137 6.922 6.922 0 0 0-.427-.272l-.133-.076a6.568 6.568 0 0 0-.264-.14 8.656 8.656 0 0 0-.193-.093c-.082-.038-.164-.077-.248-.113-.09-.038-.181-.073-.274-.109-.062-.025-.123-.051-.187-.074a9.918 9.918 0 0 0-1.018-.315 13.25 13.25 0 0 0-.455-.107l-.058-.014a17.487 17.487 0 0 0-.688-.131l-.233-.04c-.118-.018-.237-.034-.358-.051a26.362 26.362 0 0 0-.312-.041 31.4 31.4 0 0 0-.336-.037l-.35-.035-.14-.012a29.589 29.589 0 0 0-1.262-.078A40.509 40.509 0 0 0 12 0Zm0 .857c.29 0 .572.003.847.008.55.011 1.07.032 1.562.065a22.546 22.546 0 0 1 2.031.224c.206.034.405.072.598.112.965.198 1.775.47 2.455.826a6.062 6.062 0 0 1 1.09.73h.002a5.53 5.53 0 0 1 .59.59 5.99 5.99 0 0 1 .73 1.092 8.463 8.463 0 0 1 .553 1.369c.312 1.014.513 2.238.61 3.715.034.491.055 1.013.066 1.563a46.705 46.705 0 0 1 0 1.696c-.011.55-.032 1.072-.065 1.564-.098 1.477-.3 2.701-.611 3.715a8.463 8.463 0 0 1-.553 1.369 5.99 5.99 0 0 1-.73 1.092 5.32 5.32 0 0 1-.926.853 6.062 6.062 0 0 1-.756.467c-1.225.64-2.869 1.015-5.084 1.162-.492.033-1.012.054-1.562.065a46.618 46.618 0 0 1-1.696 0c-.55-.011-1.07-.032-1.561-.065-2.215-.147-3.86-.522-5.084-1.162a6.062 6.062 0 0 1-1.092-.73 5.5 5.5 0 0 1-.59-.59v-.002a5.99 5.99 0 0 1-.73-1.09 8.463 8.463 0 0 1-.553-1.369c-.312-1.014-.513-2.238-.611-3.715a33.466 33.466 0 0 1-.065-1.564 46.618 46.618 0 0 1 0-1.698c.011-.55.032-1.07.065-1.561.032-.493.077-.957.133-1.395.055-.437.123-.848.203-1.234.119-.58.264-1.103.439-1.576.058-.158.119-.31.184-.455a6.08 6.08 0 0 1 .933-1.516 5.5 5.5 0 0 1 .59-.59 5.49 5.49 0 0 1 .336-.263 6.696 6.696 0 0 1 1.635-.854c.157-.058.32-.114.49-.166.338-.104.7-.194 1.086-.273.386-.08.797-.148 1.234-.203.438-.056.902-.101 1.395-.133a33.377 33.377 0 0 1 1.561-.065c.276-.005.56-.008.85-.008zm0 .5c-4.457 0-7.035.6-8.54 2.104-1.503 1.504-2.103 4.082-2.103 8.538 0 4.457.6 7.035 2.106 8.539 1.505 1.504 4.083 2.104 8.536 2.104 4.454 0 7.032-.6 8.537-2.104 1.505-1.504 2.106-4.082 2.106-8.539 0-4.456-.601-7.034-2.106-8.538-1.505-1.504-4.083-2.104-8.537-2.104zM7.284 4.715h5.177c3.28 0 5.967 2.564 5.967 5.761 0 1.774-.829 3.354-2.127 4.408a6.046 6.046 0 0 1-4.699 2.211h-.297v2.189h-.856v.858H6.43V5.57h.855zm.43.428v13.713h3.165V15.81h1.582c3.06 0 5.537-2.389 5.537-5.334s-2.478-5.333-5.537-5.333zm3.165 3.046h1.582c1.311 0 2.373 1.025 2.373 2.287s-1.062 2.285-2.373 2.285H10.88zm.426 1.288v2.854h1.156c.328 0 .632-.076.9-.21a1.77 1.77 0 0 0 .186-.79c0-1.01-.855-1.854-1.945-1.854z"/></svg>
```

**Comment by PratyushJayachandran** [comment]
> Thanks for this contribution @PratyushJayachandran 🙏 While creating a version to compare your PR against, I came up with the below. This version maintains the different colour bands of the wider shape, while also maintaining the outline around the `P`. peerlist You're more than welcome to use it, though we'll need another @simple-icons/icon-review member to review if you do!
> 
> ```
> <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Peerlist</title><path d="M12 0c-.584 0-1.14.011-1.673.033-.44.018-.861.046-1.268.08l-.125.01-.366.035-.326.037-.328.043-.322.047-.274.043-.287.053c-.13.024-.26.049-.385.076l-.058.014a13.25 13.25 0 0 0-.473.111 11.136 11.136 0 0 0-.986.307c-.08.028-.154.059-.231.09-.081.032-.164.063-.244.097-.084.036-.166.075-.248.113a6.568 6.568 0 0 0-.457.233l-.133.076a6.922 6.922 0 0 0-.625.41c-.06.045-.117.092-.175.139-.067.053-.136.104-.2.16l-.04.037a6.383 6.383 0 0 0-.532.533l-.037.039c-.056.064-.107.133-.16.2-.047.058-.094.115-.14.175a5.786 5.786 0 0 0-.137.198 6.922 6.922 0 0 0-.272.427l-.076.133a6.568 6.568 0 0 0-.14.264 8.656 8.656 0 0 0-.093.193c-.038.082-.077.164-.113.248-.034.08-.065.163-.097.244-.031.077-.062.152-.09.23l-.008.02a10.356 10.356 0 0 0-.41 1.44l-.014.058C.43 6.772.405 6.9.381 7.03l-.053.287-.043.274-.047.322-.043.328-.037.326-.035.366-.01.125a29.81 29.81 0 0 0-.08 1.268A40.509 40.509 0 0 0 0 12c0 .583.011 1.14.033 1.672.018.441.046.862.08 1.27l.01.124.035.366.037.326a26.403 26.403 0 0 0 .09.65l.041.26c.022.13.046.256.07.381l.049.25c.018.085.038.167.057.25.025.107.049.215.076.318.015.057.032.111.047.166.062.228.13.448.203.66l.06.176c.034.09.069.177.104.264.028.069.053.14.082.207.037.086.078.17.117.254.032.067.063.135.096.201.037.074.076.145.115.217.04.074.08.147.123.218a6.629 6.629 0 0 0 .29.45l.076.103c.059.081.122.159.185.237.045.054.087.11.133.164a5.789 5.789 0 0 0 .545.548c.022.02.042.042.064.06.064.057.133.108.2.16.058.048.115.095.175.14.064.047.13.093.198.138a6.922 6.922 0 0 0 .427.272l.133.076a6.568 6.568 0 0 0 .457.233c.082.038.164.077.248.113.09.038.18.073.274.109.062.025.123.05.187.074a9.918 9.918 0 0 0 1.018.315c.147.038.3.073.455.107l.058.014a17.487 17.487 0 0 0 .688.13l.234.04c.118.018.237.034.358.05l.312.042.336.037.35.035.14.012c.406.034.822.06 1.261.078a40.509 40.509 0 0 0 2.527.025 34.82 34.82 0 0 0 2.08-.103l.14-.012.35-.035.335-.037.312-.041c.121-.017.24-.033.358-.051l.234-.04a17.487 17.487 0 0 0 .688-.13l.058-.014a10.356 10.356 0 0 0 1.473-.422c.064-.023.125-.05.187-.074.093-.036.184-.071.274-.11.084-.035.166-.074.248-.112a8.656 8.656 0 0 0 .457-.233l.133-.076a6.922 6.922 0 0 0 .625-.41c.06-.045.117-.092.175-.14.067-.052.136-.103.2-.16l.004-.003.06-.057a5.58 5.58 0 0 0 .252-.234c.079-.08.154-.162.229-.246.019-.022.04-.042.06-.064l.004-.004c.046-.053.088-.11.133-.164.063-.078.126-.156.185-.237l.075-.103a6.629 6.629 0 0 0 .29-.45c.043-.071.083-.144.124-.218.039-.072.078-.143.115-.217.033-.066.064-.134.096-.201.039-.084.08-.168.117-.254.029-.067.054-.138.082-.207.035-.087.07-.174.103-.264l.008-.017c.019-.052.035-.106.053-.159.073-.212.14-.432.203-.66.014-.05.03-.097.043-.148l.004-.018c.027-.103.05-.21.076-.318.019-.083.039-.165.057-.25l.049-.25c.024-.125.048-.252.07-.38l.04-.26a24.807 24.807 0 0 0 .09-.65l.038-.327.035-.366.01-.125c.034-.407.062-.828.08-1.269a40.509 40.509 0 0 0 .025-2.527 29.753 29.753 0 0 0-.105-2.085l-.01-.125-.035-.366-.037-.326a26.403 26.403 0 0 0-.09-.65l-.041-.26a18.594 18.594 0 0 0-.07-.381l-.05-.25c-.017-.085-.037-.167-.056-.25-.025-.107-.05-.215-.076-.318l-.004-.018c-.013-.051-.03-.098-.043-.148-.062-.228-.13-.448-.203-.66-.018-.053-.034-.107-.053-.16l-.008-.016a9.063 9.063 0 0 0-.103-.264c-.028-.07-.053-.14-.082-.207-.037-.086-.078-.17-.117-.254-.032-.067-.063-.135-.096-.201-.037-.074-.076-.145-.115-.217-.041-.074-.081-.147-.123-.218a6.629 6.629 0 0 0-.291-.45l-.075-.103a6.028 6.028 0 0 0-.185-.237c-.045-.054-.087-.111-.133-.164l-.004-.003a5.684 5.684 0 0 0-.541-.545l-.06-.057-.004-.004c-.064-.056-.133-.107-.2-.16-.058-.047-.115-.094-.175-.14a5.786 5.786 0 0 0-.198-.137 6.922 6.922 0 0 0-.427-.272l-.133-.076a6.568 6.568 0 0 0-.264-.14 8.656 8.656 0 0 0-.193-.093c-.082-.038-.164-.077-.248-.113-.09-.038-.181-.073-.274-.109-.062-.025-.123-.051-.187-.074a9.918 9.918 0 0 0-1.018-.315 13.25 13.25 0 0 0-.455-.107l-.058-.014a17.487 17.487 0 0 0-.688-.131l-.233-.04c-.118-.018-.237-.034-.358-.051a26.362 26.362 0 0 0-.312-.041 31.4 31.4 0 0 0-.336-.037l-.35-.035-.14-.012a29.589 29.589 0 0 0-1.262-.078A40.509 40.509 0 0 0 12 0Zm0 .857c.29 0 .572.003.847.008.55.011 1.07.032 1.562.065a22.546 22.546 0 0 1 2.031.224c.206.034.405.072.598.112.965.198 1.775.47 2.455.826a6.062 6.062 0 0 1 1.09.73h.002a5.53 5.53 0 0 1 .59.59 5.99 5.99 0 0 1 .73 1.092 8.463 8.463 0 0 1 .553 1.369c.312 1.014.513 2.238.61 3.715.034.491.055 1.013.066 1.563a46.705 46.705 0 0 1 0 1.696c-.011.55-.032 1.072-.065 1.564-.098 1.477-.3 2.701-.611 3.715a8.463 8.463 0 0 1-.553 1.369 5.99 5.99 0 0 1-.73 1.092 5.32 5.32 0 0 1-.926.853 6.062 6.062 0 0 1-.756.467c-1.225.64-2.869 1.015-5.084 1.162-.492.033-1.012.054-1.562.065a46.618 46.618 0 0 1-1.696 0c-.55-.011-1.07-.032-1.561-.065-2.215-.147-3.86-.522-5.084-1.162a6.062 6.062 0 0 1-1.092-.73 5.5 5.5 0 0 1-.59-.59v-.002a5.99 5.99 0 0 1-.73-1.09 8.463 8.463 0 0 1-.553-1.369c-.312-1.014-.513-2.238-.611-3.715a33.466 33.466 0 0 1-.065-1.564 46.618 46.618 0 0 1 0-1.698c.011-.55.032-1.07.065-1.561.032-.493.077-.957.133-1.395.055-.437.123-.848.203-1.234.119-.58.264-1.103.439-1.576.058-.158.119-.31.184-.455a6.08 6.08 0 0 1 .933-1.516 5.5 5.5 0 0 1 .59-.59 5.49 5.49 0 0 1 .336-.263 6.696 6.696 0 0 1 1.635-.854c.157-.058.32-.114.49-.166.338-.104.7-.194 1.086-.273.386-.08.797-.148 1.234-.203.438-.056.902-.101 1.395-.133a33.377 33.377 0 0 1 1.561-.065c.276-.005.56-.008.85-.008zm0 .5c-4.457 0-7.035.6-8.54 2.104-1.503 1.504-2.103 4.082-2.103 8.538 0 4.457.6 7.035 2.106 8.539 1.505 1.504 4.083 2.104 8.536 2.104 4.454 0 7.032-.6 8.537-2.104 1.505-1.504 2.106-4.082 2.106-8.539 0-4.456-.601-7.034-2.106-8.538-1.505-1.504-4.083-2.104-8.537-2.104zM7.284 4.715h5.177c3.28 0 5.967 2.564 5.967 5.761 0 1.774-.829 3.354-2.127 4.408a6.046 6.046 0 0 1-4.699 2.211h-.297v2.189h-.856v.858H6.43V5.57h.855zm.43.428v13.713h3.165V15.81h1.582c3.06 0 5.537-2.389 5.537-5.334s-2.478-5.333-5.537-5.333zm3.165 3.046h1.582c1.311 0 2.373 1.025 2.373 2.287s-1.062 2.285-2.373 2.285H10.88zm.426 1.288v2.854h1.156c.328 0 .632-.076.9-.21a1.77 1.77 0 0 0 .186-.79c0-1.01-.855-1.854-1.945-1.854z"/></svg>
> ```

I like this version in the big preview. But in the badge it looks like a blob. I got some idea from your rendition. I'll try to come up with a mix of both. The P might need some negative space so that it looks good in the badge. Is that okay?

**Comment by PratyushJayachandran** [comment]
peerlist1
peerlist2

@adamrusted which one do you fancy?

**Comment by adamrusted** [comment]
I prefer the second one with the shadow still behind the `P`. Let's open this up to other @simple-icons/maintainers too though!

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran - given we've had no response, let's go with the second one please! 🙏😅

Done

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @PratyushJayachandran 🎉

**Pull request merged**
