### PR TITLE
add nano

### LINKED ISSUE #5062: Nano
**Brand Name:** Nano
**Website:** https://nano.org/
**Alexa rank:** 120,005

**Official resources for icon and color:**
https://nano.org/resources

### PR DESCRIPTION
**Pull request by NashJames**
nano

**Issue:**  Closes #5062
**Alexa rank:** 120,005
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The elements of their provided SVG were multiple paths and circles, I used a compound-path to connect them all using Illustrator. (A small update in the contributing guidelines for section 5 would be helpful, to reflect how best to tackle this)

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @NashJames and thanks for the contribution 👍🏻

Which version of their logo did you base your icon on? I'm noticing [some differences](https://user-images.githubusercontent.com/15157491/108486662-3680be80-7296-11eb-9ca2-c9b15e3351f1.png) when comparing it to [this SVG](https://content.nano.org/Nano-Brand-Kit/SVG/nano+mark.svg).

> A small update in the contributing guidelines for section 5 would be helpful, to reflect how best to tackle this

Thanks for the suggestion; would you like to open an issue or PR with your suggested changes for further discussion?

**Comment by NashJames** [comment]
Good spot. Hopefully that's better. It seems like not exporting the entire artboard meant it was losing definition for some unknown reason.

And upon re-reading the guidelines, it seems I missed the compound-paths point in section 2. Easy mistake on my part.

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @NashJames.

However, I'm still seeing a small few hairline differences (such as in [the top of the bottom left circle](https://user-images.githubusercontent.com/15157491/108995905-a4adf280-7695-11eb-9bd2-97e8833c523e.png)) compared to [this SVG](https://content.nano.org/Nano-Brand-Kit/SVG/nano+mark.svg). Before asking you to take a look at it again, though, which file are you basing your version off? It may just be a case of me not comparing like with like - we've often come across instances where companies make multiple versions of their logo or icon available and they all have subtle differences to each other.

**Comment by NashJames** [comment]
That is the SVG I used. It was difficult to tell what was causing it but at one stage of the process, the size was getting warped. I think it's due to the inconvenient sizes they used, so when it is re-sized to 24px total width. Everything becomes long decimal numbers.

I spent much longer trying to get it right on the second attempt. I must have exported it 30-40 times with that being the closest. One thing I did notice was it was kept a lot more of it's accuracy when ticking `Use Artboards` on the Export As. And I am aware of the precision slider on SVGOMG and decimal number on exporting options of Illustrator, neither of those was the culprit for the loss of accuracy. I'm not sure how I could make it more accurate, my Illustrator and SVG knowledge is a work in progress.

**Comment by PeterShaggyNoble** [comment]
No worries, @NashJames. Sometimes software is just determined not to cooperate, regardless of our experience level! 😆 I'm not an Illustrator guy so can't be of much help there, but here's the path I came up with if you want to use it. Unfortunately I did have to go with a precision level of 4 to avoid some distortion in the centre shape.
```
M22.2864 6.8576c-.9453 0-1.7135.7665-1.7135 1.7136 0 1.2843-.4275 1.7136-1.7136 1.7136-.9453 0-1.7135.7664-1.7135 1.7135 0 1.2843-.4276 1.7136-1.7136 1.7136-.9453 0-1.7135.7664-1.7135 1.7135 0 .9454.7665 1.7136 1.7135 1.7136.9454 0 1.7136-.7665 1.7136-1.7136 0-1.2843.4275-1.7135 1.7135-1.7135.9454 0 1.7136-.7665 1.7136-1.7136 0-1.2843.4275-1.7135 1.7135-1.7135.9454 0 1.7136-.7666 1.7136-1.7136 0-.9454-.7682-1.7136-1.7136-1.7136zm-13.717.0017c-.9453 0-1.7135.7665-1.7135 1.7136 0 1.2843-.4275 1.7136-1.7135 1.7136-.9454 0-1.7136.7664-1.7136 1.7135 0 .947.77 1.7135 1.7153 1.7135S6.8576 12.9471 6.8576 12c0-1.2843.4293-1.7135 1.7136-1.7135s1.7136.4275 1.7136 1.7135c0 .947.7698 1.7135 1.7152 1.7135.9453 0 1.7135-.7664 1.7135-1.7135 0-.9454-.7664-1.7135-1.7169-1.7135-1.2843 0-1.7135-.4276-1.7135-1.7136 0-.9453-.7683-1.7136-1.7136-1.7136zm-6.8559 6.856A1.7136 1.7136 0 0 0 0 15.4287a1.7136 1.7136 0 0 0 1.7135 1.7136 1.7136 1.7136 0 0 0 1.7136-1.7136 1.7136 1.7136 0 0 0-1.7135-1.7136Z
```

**Comment by NashJames** [comment]
I appreciate the hand. That looks great.

It's awesome to see how much care you take in getting these right :smile:

**Comment by PeterShaggyNoble** [comment]
> I appreciate the hand. That looks great.

You're welcome 🙂 But, as you're using my path now, we'll need one of the other @simple-icons/maintainers to review this before merging.

> It's awesome to see how much care you take in getting these right

😁 Thanks. We know it can be annoying being asked to make multiple changes to a PR and we often feel like jerks for doing it but we have to try to stay as faithful to the source as we possibly can.

**Comment by fbernhart** [comment]
LGTM! 👍🏼  Thanks @NashJames and @PeterShaggyNoble for your work on this icon.

**Pull request merged**
