### PR TITLE
Add MYOB Logo

### PR DESCRIPTION
**Pull request by NovaGL**
**Website:** [www.myob.com](https://www.myob.com/)
**Alexa rank:** 77.7K

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
Leading accounting and POS system in Australia and New Zealand
image

EDIT: Let me know if I made a problem with the commits, I was trying to have it upto date with this repo.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Just to make sure I'm comparing like-with-like, @NovaGL, which file at the source URL did you base your SVG off?

Also, where di you source you colour from? For some reason [the colour section](https://myob-identikit.frontify.com/d/JK2D4WFOdAwV/for-developers#/visual-identity/colours-and-gradient) of their guidelines is sempty. 🤷‍♂️ [These guidelines](https://developer.myob.com/media/cms_page_media/890/MYOB%20LOGO%20USAGE%20GUIDE.pdf) mention `#5c247b` but they're clearly outdated.

Oh, and I'd suggest updating the source URL to remove the anchor, so just https://myob-identikit.frontify.com/d/JK2D4WFOdAwV/for-developers

**Comment by NovaGL** [comment]
Thanks @PeterShaggyNoble I'm happy to go with your suggested color I just grabbed it from the source of the website but since there are guidelines that mention a particular color I would prefer to use that.

**Comment by mondeja** [comment]
I would go with `#673FA5` because is the leftmost color in their gradients and, as @PeterShaggyNoble has pointed, these guidelines are clearly outdated. What do other @simple-icons/maintainers think about this?

**Comment by service-paradis** [comment]
According to https://developer.myob.com/program/myob-developer-logos/, the new brand guidelines can be found at https://myob-identikit.frontify.com/d/JK2D4WFOdAwV/for-developers
The official source for the logo is https://myob-identikit.frontify.com/d/JK2D4WFOdAwV/for-developers#/visual-identity/logos
In the official logo, it looks like the leftmost color is `#6100A5`

**Comment by fbernhart** [comment]
I've as well checked the leftmost color of the logo and the website banner. And I've come to the same result: `#6100A5`. So I'd go for this color.

@mondeja Where did you find `#673FA5`?

**Comment by mondeja** [comment]
Maybe my web color eyepicker it's trolling me :sweat_smile:
Have you extracted `#6100A5` from some CSS? I can't find where you get the color from :thinking:

**Comment by fbernhart** [comment]
@mondeja I've just used Chrome's color picker and clicked once on the PNG file [here](https://myob-identikit.frontify.com/d/JK2D4WFOdAwV/for-developers#/visual-identity/logos) as well as on the banner [on the website](https://www.myob.com/au).

The color gradient in the SVG file [on the website](https://www.myob.com/au) has as well this color in the source code:



```
<svg id="logo" class="brand__logo brand__logo--site block overflow-i--visible" preserveAspectRatio="xMidYMin slice" data-name="logo" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 283.5 116.4" aria-label="MYOB Home">
    <title>MYOB</title>
    <defs>
        <linearGradient id="logo-gradient" gradientUnits="userSpaceOnUse" x1="0" y1="58.2083" x2="283.4646" y2="58.2083">
            <stop offset="0.36" stop-color="#6100A5"></stop>
            <stop offset="0.4557" stop-color="#7001A0"></stop>
            <stop offset="0.6409" stop-color="#980293"></stop>
            <stop offset="0.8947" stop-color="#D9057E"></stop>
            <stop offset="0.97" stop-color="#ED0677"></stop>
        </linearGradient>
    </defs>
    <g fill="url(#logo-gradient)">
```

**Comment by service-paradis** [comment]
Just opened the EPS ([EPS_High Res Printing.zip](https://github.com/simple-icons/simple-icons/files/5646035/EPS_High.Res.Printing.zip)) version of the logo and the gradient is defined as `#6100A5` to `#ED0677`.
I think I would keep this one (the preview have been generated with `#6100A5`, but the source is still `#5C247B`)

**Comment by NovaGL** [comment]
I'm happy with whatever, I thought my first choice was correct but then the consensus seemed to be a different colour so I changed it. If we're all in agreement, lets change the colour back and merge this.

**Review by mondeja — APPROVED** [review]
Thank you all for the help with choosing the color. Good work with this one @NovaGL! :muscle: :tada:

**Pull request merged**
