### PR TITLE
Add El Jueves

### PR DESCRIPTION
**Pull request by mondeja**
eljueves(1)

**Issue:** N/a
**Alexa Rank:** [~89k](https://www.alexa.com/siteinfo/eljueves.es)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Path extracted from image of [website](https://www.eljueves.es/) header ([this file](https://www.eljueves.es/content/skins/ej2020/img/logo-eljueves.svg?v=20200603152824)).
- Color `#BE312E` from website background.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Before diving into a full review of this, I wonder could we instead use their jester mascot, as seen in the favicon and in use in various places throughout their site? It's a publication I only have a passing knowledge of so, assuming you're more familiar with it, @mondeja, what do you think? If so then we could use [this simplified version](https://www.eljueves.es/content/skins/ej2020/img/ic-menu.svg?v=20200603152824) which can be found in the menu running along the bottom of the viewport on smaller devices.

**Comment by PeterShaggyNoble** [comment]
Sorry, @mondeja, didn't mean for you to update straight off the bat - I was just looking to open it up for discussion, initially. Or, should I take it, from your update that, being more familiar with the brand, that you agree with me? What do the other @simple-icons/maintainers think?

**Comment by mondeja** [comment]
> Or, should I take it, from your update that, being more familiar with the brand, that you agree with me?

Yes, being familiar with the brand, I could say that their jester mascot is enough popular to take it.

**Comment by PeterShaggyNoble** [comment]
Thanks for the clarification, @mondeja :+1: Happy to run with this version, so.

I'm noticing a couple of minor differences in the curves of the hat - see example below, with your version in red - could you have a look at that please? It may simply be a precision issue when optimising.

On an unrelated note, is your email address on GitHub up-to-date? We've been trying to get in touch with you over the past couple of weeks,

**Comment by mondeja** [comment]
Sorry @PeterShaggyNoble, I did this pull just before the holidays and on my return I had to be aware of other more urgent projects. I saw the email too late. If you want to contact me this month I will be ready.

About this icon, I've increased the precission optimizing it. Hopefully now it will fit your version.

**Review by ericcornelissen — APPROVED** [review]
> About this icon, I've increased the precission optimizing it. Hopefully now it will fit your version.

Looking good now, thanks a bunch @mondeja 🎉

**Pull request merged**
