### PR TITLE
Add Redux-Saga

### LINKED ISSUE #3652: Add Redux-Saga Icon
**Name:** Redux Saga
**Website:** https://redux-saga.js.org/
**Alexa rank:**
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by fbernhart**
redux-saga

**Issue:** Closes #3652 
**Alexa rank:** [113,397](https://www.alexa.com/siteinfo/redux-saga.js.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Source: I've manually vectorized [this PNG](https://github.com/redux-saga/redux-saga/blob/9d2164946f402e594a0dfe453c6d20fb6f14858f/logo/3840/Redux-Saga-Logo.png) from their GitHub repo in lack of an official SVG file.
- Color: `#999999`, which is one of the main two colors in their logo. The other would be `#89D96D`.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Looks like the filename is wrong on this one, @fbernhart - it should be hyphenated.

**Comment by fbernhart** [comment]
@PeterShaggyNoble Oops, my bad. I've fixed it now.

**Review by adamrusted — APPROVED** [review]
Looks good to me - thanks @fbernhart 🥳
Will wait for another @simple-icons/maintainers to check it over, being as it's a manual vectorization.

**Review by service-paradis — APPROVED** [review]
LGTM 🎉

**Pull request merged**
