### PR TITLE
Add eightsleep icon

### PR DESCRIPTION
**Pull request by kalpeshT101**
**Issue:**#3599
**Alexa rank:**[76,908](https://www.alexa.com/siteinfo/eightsleep.com)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by runxel — CHANGES_REQUESTED** [review]
Hey @kalpeshT101, thanks for the PR.
However your contribution doesn't match our standards, that's why the build is failing. Please have a careful look at the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and follow them.

Also, please don't distort icons when scaling! Always scale uniformly!

**Comment by IIAIronWolf** [comment]
Any update on this? My issue was mentioned in this.

**Comment by runxel** [comment]
> 
> 
> Any update on this? My issue was mentioned in this.

Hey @IIAIronWolf, no, there weren't any updates by @kalpeshT101.
Let's wait a bit more until I will mark this one as abandoned.

**Comment by adamrusted** [comment]
Assuming this PR has been abandoned, which of these variants do we think is better? Can submit either.
image

**Comment by fbernhart** [comment]
@adamrusted I would go for the second one - just the "8".

They as well use it in their favicon and as logo for their social media presence.

**Comment by adamrusted** [comment]
> @adamrusted I would go for the second one - just the "8".
> 
> They as well use it in their favicon and as logo for their social media presence.

Consider it done! Rebuilt from press kit, and used hex found in SVG there.

eightsleep

**Comment by IIAIronWolf** [comment]
Looks great! Thanks!

**Comment by fbernhart** [comment]
@adamrusted LGTM! 8️⃣  Thanks for rescuing this one.

Thanks as well to @kalpeshT101 for the initial try. 👍🏼

**Pull request merged**
