### PR TITLE
Add Looker icon

### PR DESCRIPTION
**Pull request by dhruvkb**
simpleicons

**Issue:** #4428
**Alexa rank:**  23,481

  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by adamrusted** [comment]
Thanks for your PR @dhruvkb 🎉

Just had a look at why it's failing the Lint check - and it looks like the icon size is *slightly* too big (0.002px to be precise!), and isn't quite centred. Would you mind taking another quick look at it, making sure that the longest side is exactly 24px (I sometimes enter 24.0000px just to be safe!) and centred on the canvas? Otherwise, great job!

**Comment by dhruvkb** [comment]
I found why. I had the "snap to pixel grid" preference turned on 🤦 !

**Comment by adamrusted** [comment]
> I found why. I had the "snap to pixel grid" preference turned on 🤦 !

No worries! If you want to resubmit changes in this PR, I'll take another look over it.

**Comment by dhruvkb** [comment]
Tried as hard as I might, I just can't get the size and centering to line up in Inkscape.
```
x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 14.87 x 23.976
x icon-centered <path> must be centered at (12, 12); the center is currently (12, 12.012)
```

**Comment by adamrusted** [comment]
> Tried as hard as I might, I just can't get the size and centering to line up in Inkscape.

No worries! I had a quick look at this myself, and it was failing on anything less than 4 decimals on the linter.
I've been able to rectify it on #4438, so hopefully one of the other maintainers can review it shortly!

**Pull request closed without merging**
