### PR TITLE
Add Spinrilla

### PR DESCRIPTION
**Pull request by dylancopeland**
### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

---

Thanks for this great project and for checking out this PR. Please let me know if you have any questions.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Thanks for taking the time to contribute @dylancopeland :smile: Could you have a look at [optimizing the SVG](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon) and [annotating the SVG](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#4-annotate-the-icon) in our Contributing Guidelines and update your Pull Request accordingly?

If you need help with that, let us know :smile: 

As an aside, why did you choose to omit the "background" of the icon (as it is seen in their favicon)? I'm unfamiliar with the brand, but looking at the favicon it seems to me the logo is meant to look like an abstract [CD](https://en.wikipedia.org/wiki/Compact_disc), which is lost in your interpretation of the logo :thinking: 

* * *

**Alexa rank**: [~175k](https://www.alexa.com/siteinfo/spinrilla.com)

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @dylancopeland and thanks for the contribution.

The build is currently failing because:
1. You're missing the `role="img"` attribute on the `svg` tag, and,
2. Icons should be a single compound `path`.

More details can be found in our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

Also, to help us review this better, I'm assuming you based your icon [this file](https://dpjsgvx0fhwmn.cloudfront.net/packs/media/images/icon-22b6ef2706c6d7ab077ee7926319202f.svg)?

**Alexa rank:** [174148](https://www.alexa.com/siteinfo/spinrilla.com)

**Comment by PeterShaggyNoble** [comment]
@ericcornelissen, they have both boxed and circled favicons (e.g., https://dpjsgvx0fhwmn.cloudfront.net/packs/media/images/touch-icon-iphone-5a3eab99757fbb7ed967dd4a9fe79315.png & https://dpjsgvx0fhwmn.cloudfront.net/packs/media/images/favicon-220400306d41b11142c3f600454cd542.ico) so I'm guessing the background isn't part of the icon. Although the boxed versions may be out of necessity for Apple devices.

**Comment by ericcornelissen** [comment]
I'm sorry for the confusion (and my laziness), I meant [the second icon you linked](https://dpjsgvx0fhwmn.cloudfront.net/packs/media/images/favicon-220400306d41b11142c3f600454cd542.ico), so the "circled" version.

**Comment by dylancopeland** [comment]
Hi everyone,

Thanks for the feedback. I've addressed the two issues preventing builds from passing. I totally glossed over over those important bits in the contribution guidelines. 

@PeterShaggyNoble is correct in regards to the background. The fav icon does have a round background but it is not part of the mark itself. The background of the icon is independent of the glyph and varies depending on context.

## Contexts

### App Icons

app-icons

### Print

spinrilla-print

### Video

watermark
tile-slide

Source: I'm the founder.

**Comment by PeterShaggyNoble** [comment]
This looks good to me now :+1: Thanks for your efforts on it, @dylancopeland.

**Pull request merged**
