### PR TITLE
add spring icon #1706

### PR DESCRIPTION
**Pull request by bgalek**
**Issue:**
#1706 add spring icon (spring.io)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by birjolaxew** [comment]
Hey @bgalek, thanks a lot for the PR! A few things we'd like changed before we can merge this in:

- We require that each icon has a `<title>` containing the name of the brand followed by "icon" (in this case "Spring icon"). This is for a11y reasons.
- We try to keep the icon files as small as possible. Could you remove the extra whitespace (namely newlines)?
- Could you explain a bit about where you found the SVG? I can't seem to find an official SVG at https://spring.io/trademarks

**Comment by bgalek** [comment]
Hi @birjolaxew!
I've added title (I missed it out when reading CONTRIBUTING.md) - sorry ;)
I've removed the fill-rule and new lines. 
I've seperated and vectorized this file from https://spring.io/img/spring-by-pivotal-9066b55828deb3c10e27e609af322c40.png available at https://spring.io/trademarks :)

**Comment by birjolaxew** [comment]
Thanks a lot for the update!

The checklist in our PR template doesn't quite cover everything our contribution guidelines do; we used to have a lot of new contributors that either submitted SVGs directly from the source, without minifying/resizing it, or didn't update the JSON correctly - the checklist is mostly used as a reminder to contributors that we have some formatting requirements, even if it doesn't cover all of them. Thanks a lot for reading the contribution guidelines regardless! That does mean a lot to us.

One last thing that I apparently missed in my last comment: I'm getting `#6DB33F` when I color pick the logo, while this PR uses `#77BC1F` - although the difference is obviously pretty small, we prefer to use official colors where possible. Did you pick your color from somewhere else?

**Comment by bgalek** [comment]
It's possible that I messed with it during vectorization process, I'll update the color! :)

**Comment by birjolaxew** [comment]
:+1: That is all the nitpicking I could do this time around I think ;) The vectorization looks excellent. Thanks a lot for the updates and all your work on this @bgalek!

**Pull request merged**
