### PR TITLE
Update Gitpod Icon color

### PR DESCRIPTION
**Pull request by uiuxarghya**
gitpod

**Issue:** (none yet)
**Alexa rank:** 44,562

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Hello, simple-icons! 👋

Gitpod has undergone a rebranding, so I would like to update the icon color and the official Gitpod logo here. ✨

There is a previous pull request done before but the **color of the logo** is not correct there #5425.
After examining many times and researching I found the color is actually `#FF8A00` and not the previous one.

The new logo has an orange color (well, "kumquats"  `#FF8A00`) and can already be seen in various official places like:

* [https://gitpod.io](https://gitpod.io)
* [https://gitpod.io/static/media/gitpod.2cdd910d.svg](https://gitpod.io/static/media/gitpod.2cdd910d.svg)
* [https://www.gitpod.io](https://www.gitpod.io)
* [https://github.com/gitpod-io/gitpod/#readme](https://github.com/gitpod-io/gitpod/#readme)
* [https://twitter.com/gitpod](https://twitter.com/gitpod)
* etc.

### CODE REVIEW

**Comment by adamrusted** [comment]
Hi @uiuxarghya, welcome to Simple Icons, and thanks for your contribution!

I would've actually assumed both colours were usable - given the icon appears to always be shown with the gradient between those two. In situations where we can't decide one or the other hex code, we often use the [calculated midpoint](https://meyerweb.com/eric/tools/color-blend/#FF8A00:FFB45B:1:hex), which in this case would be `#FF9F2E`. It also appears you've updated the SVG path in your PR - was there an issue with the one provided in #5425 that we didn't catch?

Assuming other @simple-icons/maintainers agree, could you please apply the midpoint hex code to the JSON and revert the SVG (unless there's an issue with it) and we can merge this minor update in!

**Comment by service-paradis** [comment]
I think I would choose between the 2 following colors for their brand color: `#ff8a00` or `#ffae33`
```CSS
--brand-ripe: #ff8a00;
--brand-almost-ripe: #ffae33;
```

`--brand-ripe` is used through their website in various places such as markers at https://www.gitpod.io/privacy or link color at https://www.gitpod.io/features and a few other places.
`--brand-almost-ripe` is used for button color at https://www.gitpod.io/features

**Comment by adamrusted** [comment]
Yeah. My only worry is they consistently use the gradient when the icon is present - I haven't found a monochrome version while I had a glance at their stuff. Given the update in the previous PR was done by a contributor from Gitpod - I've asked the question on their rebrand issue as to what they think we should go with, citing the example of the calculated midpoint that we've used on other icons with a gradient. Will wait and see what they come back with.

**Comment by uiuxarghya** [comment]
Okay, let us see what Gitpod tells on the color in the question you asked. @adamrusted
https://github.com/gitpod-io/gitpod/issues/3771#issuecomment-821068864

I think the dark orange is good in black as well as a white background.

**Comment by PeterShaggyNoble** [comment]
I'd vote for one of the values from the CSS variables @service-paradis mentioned above, leaning towards `#ffae33` as it looks to be used more extensively on their site.

**Comment by uiuxarghya** [comment]
Okay I am updating the color then to `#ffae33`

**Comment by uiuxarghya** [comment]
gitpod (1)

I have updated the color to `#ffae33`
so you can merge it now...

**Comment by adamrusted** [comment]
Thanks for updating the hex @uiuxarghya - could you please revert the changes to the SVG, and I'll merge in the hex update? I don't think there was anything wrong with the SVG that was submitted in the last PR - so shouldn't need updating. 💪

**Comment by uiuxarghya** [comment]
Okay, sure I will be happy to do that. @adamrusted 😊

**Comment by uiuxarghya** [comment]
> Thanks for updating the hex @uiuxarghya - could you please revert the changes to the SVG, and I'll merge in the hex update? I don't think there was anything wrong with the SVG that was submitted in the last PR - so shouldn't need updating. 💪

Okay, sure I will be happy to do that. @adamrusted 😊

**Comment by uiuxarghya** [comment]
I have reverted the SVG code now you can merge the pull request.😊

**Review by adamrusted — APPROVED** [review]
Perfect, thanks @uiuxarghya! Can always update if we hear back from the Gitpod team.

**Pull request merged**
