### PR TITLE
Add John Deere

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
John Deere

**Issue:** #2059

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Colour from [website](https://www.deere.com/) stylesheet. 

Possible alternative colour from source SVG: `#247218`

Rejected alternative treatment based on their [favicon](https://www.deere.com/assets/images/image-icons/favicon.ico):
John Deere

### CODE REVIEW

**Comment by runxel** [comment]
Looks good, but I'm favor of the "alternative". 😅

**Comment by PeterShaggyNoble** [comment]
The alternative was my first draught until I spotted their favicon, which works better at our native size. Labelling as `in discussion` for now so we can get further feedback from the @simple-icons/maintainers.

**Comment by ericcornelissen** [comment]
I'm not terribly familiar with the brand, but I do feel like the alternative version is more appropriate. I don't think it is less legible at smaller sizes and apart from the favicon they seem to use it everywhere.

**Comment by PeterShaggyNoble** [comment]
Thanks, Eric. PR updated, so :+1:

**Comment by ericcornelissen** [comment]
Thank you for the contribution(s) @PeterShaggyNoble :ok_hand:

**Pull request merged**
