### PR TITLE
Add Monoprix icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** #6410 
**Alexa rank:** 42,409
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

svg: https://www.monoprix.fr/contents/images/logo_monop_rouge.svg
color: #fb1911

### CODE REVIEW

**Review by sachinraja — CHANGES_REQUESTED** [review]
Some differences with source (red):
image

**Comment by dirien** [comment]
hi @sachinraja,

thanks for the feedback. I checked it againg but i cant see difference like with your pic.
image

**Comment by sachinraja** [comment]
Can you send the exact link to your source? @dirien

**Comment by dirien** [comment]
@sachinraja it's in the description and in the issue

**Review by sachinraja — APPROVED** [review]
Perfect match, thanks!

**Pull request merged**
