### PR TITLE
Add AWS CodePipeline Icon

### PR DESCRIPTION
**Pull request by Vboivin**
**Issue:** #3629
**Alexa rank:** N/A
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Why did you pick the hex value? It is Amazon main color and it is using this color here: https://aws.amazon.com/codepipeline/
- Did you manually vectorize the logo? No
- Have you used multiple sources? Yes
- - https://aws.amazon.com/architecture/icons/
- - https://d1.awsstatic.com/webteam/architecture-icons/Q32020/AWS-Architecture-Assets-For-Light-and-Dark-BG_20200911.478ff05b80f909792f7853b1a28de8e28eac67f4.zip
- - https://aws.amazon.com/codepipeline/

simpleicons

### CODE REVIEW

**Comment by fbernhart** [comment]
@Vboivin Thanks for your work. It seems like Amazon might have changed this logo in the meantime. Your version (black) doesn't match with the current version (red) from the source. I've used the 64px version `Arch_AWS-CodePipeline_64.svg` from the [assets pack available here](https://aws.amazon.com/architecture/icons/).

image



### Popularity
**BUT** before you change it, I'd like to discuss quickly, if this icon could even be added to Simple Icons. As AWS CodePipeline doesn't have a own website and only is a [subdomain](https://aws.amazon.com/de/codepipeline/) of AWS, we can't use the Alexa rank to measure popularity. I as well haven't found any GitHub repo that could prove the popularity of AWS CodePipeline.

I'm not familiar with all the different AWS services and products at all, but maybe one of the other @simple-icons/maintainers is and could help here out?

**Comment by ericcornelissen** [comment]
I'm not familiar with AWS Code Pipelines, but I have heard of people/companies using it. Given that it is an AWS product since 2015 ([source](https://en.wikipedia.org/wiki/Timeline_of_Amazon_Web_Services)) I would be include to accept it as being popular enough. Relatedly, we do plan on adding AWS S3 already, see #2687, though admittedly S3 is much more famous (right?).

**Comment by mondeja** [comment]
> though admittedly S3 is much more famous (right?).

Much more, see [this comparison with Google Trends](https://trends.google.com/trends/explore?q=aws%20pipelines,aws%20s3).

**Comment by mondeja** [comment]
I think that this icon should not be added. Comparing it with [HC Cargo](https://www.alexa.com/siteinfo/hc-cargo.co.uk) (Alexa Rank ~3,000,000), brand rejected due is out of scope for simple icons, using Google Trends seems that [both are in the same level of popularity](https://trends.google.com/trends/explore?q=aws%20pipelines,hc%20cargo), and this comparison uses "aws pipelines", if I use "aws code pipelines" is even more far away.

**Comment by ericcornelissen** [comment]
> I think that this icon should not be added. Comparing it with [HC Cargo](https://www.alexa.com/siteinfo/hc-cargo.co.uk) (Alexa Rank ~3,000,000), brand rejected due is out of scope for simple icons, using Google Trends seems that [both are in the same level of popularity](https://trends.google.com/trends/explore?q=aws%20codepipeline,hc%20cargo).

That is a fair comparison :thinking: @Vboivin, do you have anything to say with regards to the popularity of AWS CodePipelines?

**Comment by Vboivin** [comment]
> > I think that this icon should not be added. Comparing it with [HC Cargo](https://www.alexa.com/siteinfo/hc-cargo.co.uk) (Alexa Rank ~3,000,000), brand rejected due is out of scope for simple icons, using Google Trends seems that [both are in the same level of popularity](https://trends.google.com/trends/explore?q=aws%20codepipeline,hc%20cargo).
> 
> That is a fair comparison  @Vboivin, do you have anything to say with regards to the popularity of AWS CodePipelines?

If it doesn't reach the required popularity target, I think it is only fair if we do not add this icon to the library. Thanks for considering it!

**Comment by mondeja** [comment]
Anyway, thanks for the attempt @Vboivin! :+1:
Feel free to reopen this in the future if you feel that fit our popularity requirement then.

**Pull request closed without merging**
