### PR TITLE
Update Vuetify

### PR DESCRIPTION
**Pull request by adamrusted**
vuetify

**Issue:** contributes toward #9072

**Similarweb rank:** [42,785](https://www.similarweb.com/website/vuetifyjs.com/#overview)
[37.8k GitHub ⭐](https://github.com/vuetifyjs/vuetify)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Unfortunately, the monochrome icon isn't available as part of the brand kit ZIP. It _is_ however embedded as an SVG at the source link!

### CODE REVIEW

**Review by s-rigaud — APPROVED** [review]
Nice update 👍

**Comment by s-rigaud** [comment]
@adamrusted Do you have any idea when this PR will be merged ? 😄

**Comment by adamrusted** [comment]
Afraid not @s-rigaud - we're all volunteering our spare time on this project, so it'll be whenever another maintainer has availability to review.

**Review by service-paradis — APPROVED** [review]
Perfect 🎉

**Pull request merged**
