### PR TITLE
Add MLB

### PR DESCRIPTION
**Pull request by huuphongnguyen**
mlb

**Issue:** #5926 
**Alexa rank:** [452](https://www.alexa.com/siteinfo/mlb.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- I got SVG code from View Code of [MLB.com](https://www.mlb.com/)
- I used Sketchapp to adjust and export
- I used https://jakearchibald.github.io/svgomg/ to optimize
- I used Inscape to compare with source icons to make sure it fit.

### CODE REVIEW

**Comment by diegobot1977** [comment]
Sorry, this brand "Target" is already used on #5927. Also, consider previewing this one:

mlb

**Comment by huuphongnguyen** [comment]
> Sorry, this brand "Target" is already used on #5927. Also, consider previewing this one:
> 
> mlb

Sorry, what do you mean?

**Comment by diegobot1977** [comment]
The Target brand name is already used. Try this one:

mlb

**Comment by huuphongnguyen** [comment]
> The Target brand name is already used. Try this one:
> 
> mlb

Opps. Made this preview after doing Target logo, so I forgot to change the name. Don't worry, it's just preview for maintainers. Will fix it soon

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @huuphongnguyen 👍🏻

But, once again, it looks like a precision of 3 should be sufficient here. Also, I'm getting `#041e42` from both the website stylesheet and the source SVG for the colour. And, could you add "Major League Baseball" as an [`aka` alias](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#aliases), please?

**Pull request merged**
