### PR TITLE
Add Dialogflow

### PR DESCRIPTION
**Pull request by ineshbose**
Closes https://github.com/simple-icons/simple-icons/issues/3444
**Alexa rank:** 51,437
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The lighter of the two tones of the logo was used for an easy, appealing look.

### CODE REVIEW

**Comment by ineshbose** [comment]
Pushing a commit with a fix ASAP.

**Review by runxel — CHANGES_REQUESTED** [review]
The logo appears to have rounded corners, yours doesn't. 🤔

**Comment by ineshbose** [comment]
Replaced with a new, fresh made logo with some space in between to differentiate the top and the lower.

**Review by fbernhart — CHANGES_REQUESTED** [review]
@ineshbose Thanks for your work.

I've overlayed your version (blue) with the one provided as [source](https://en.wikipedia.org/wiki/File:Dialogflow_logo.svg). And there seem to be quite some dfferences.

image

Could you give it another try?

**Comment by ineshbose** [comment]
Thank you for that! Just a learner here, so that visualisation helps a lot. I've made the requested changes and I'm sorry about the previous commits; I wasn't using the tests from my command line and also I switched from IcoMoon to Illustrator but Illustrator was being a bitch while exporting the SVG. Hopefully the logo will be much better. Cheers!

**Comment by fbernhart** [comment]
@ineshbose It looks better, but unfortunately it still differs quite a bit from the original. (your version is the black one in the background)

image

Don't worry about too many commits. 😊 It hasn't been too long since I've started learning and working with SVG files myself.
I haven't used IcoMoon or Illustrator myself, so unfortunately I can't help you out there. I only have experience with Inkscape.

**Comment by ineshbose** [comment]
Thank you for getting back this quick, and apologies for that (again). I wouldn't be the best person to add the "division" flair, so for now I've put the simple logo turned into SVG. :)

**Comment by fbernhart** [comment]
@ineshbose Looks great now. They perfectly match! 👍🏼 

Would you mind, if I quickly add the gaps to your logo?

**Comment by ineshbose** [comment]
@fbernhart absolutely! :D Thank you so much, I appreciate all your help with this. :)

**Comment by fbernhart** [comment]
@ineshbose Done. Thanks for your great work! 🏅 


dialogflow

**Pull request merged**
