### PR TITLE
Drop `contributing` option from issue template

### PR DESCRIPTION
**Pull request by LitoMore**
Here is the related discussion in our private channel on Discord:

https://discord.com/channels/1142044630909726760/1142045966078316574/1155431402251235388

I think some of the issue authors just submit the issue with the default value `Contributing?: Yes`.

I think we can keep the "assignee" field empty. Our contributors can give up their work anytime; it's OK. Also, new contributors are welcome.

### CODE REVIEW

**Comment by adamrusted** [comment]
I'm happy with this, but before we merge - let's ping the @simple-icons/maintainers group for additional feedback.

**Comment by PratyushJayachandran** [comment]
I agree with this. In fact I had asked for defaulting the contributing to NO even before I had joined the team.
Most people leave it at YES.

**Review by mondeja — APPROVED** [review]
I agree too.

**Review by adamrusted — APPROVED** [review]
Well, with 1/3 of our maintainers happy with this, and a known number of the others currently inactive, I'm happy to merge this one in.

**Pull request merged**
