### PR TITLE
Add Nette Framework

### PR DESCRIPTION
**Pull request by matronator**
Nette Framework

**Issue:** #5755
**Alexa rank:** 437k
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I just combined the paths from the official resource into one and scaled it to the viewbox.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @matronator and thanks for the contribution 🙂

The SVG looks spot-on to me 👍🏻 However, I'm not sure on the name 🤔 Other than on the page you sourced the logo from, they seem to refer to themselves as simply "Nette". I'm not _entirely_ sure if that's correct though as the English version of the site is very badly translated and I, sadly, do not speak Czech. What do you think? Other than that, could you add the `guidelines` entry to the JSON, duplicating the source URL?

**Comment by matronator** [comment]
Oops, sorry, I hit the update button before I noticed the comment above. Thank you @PeterShaggyNoble! :)

I agree, the naming is kinda ambiguous (or at the very least outdated), even in the Czech version. I can ask on the forums for a clarification, I already made a post linking this PR and issue there. I'll try tagging someone from the core team, they usually respond pretty quick to these things.

As for the other thing, no problem, I'll update it as soon as I can.

Sorry again for hitting the button, hope I didn't mess up something with that.

**Comment by matronator** [comment]
@PeterShaggyNoble lol, so I asked on the official forums and the inventor (main author/lead dev) replied:

> I don't even know myself :)
> (Translated from Czech)

Snímek obrazovky 2021-06-07 v 1 02 46

So I don't know what to make of it 😅 I guess it's fine how it is?

I'll do the JSON stuff in a moment, just finishing something else first.

**Comment by adamrusted** [comment]
I think if we're calling it `Nette Framework`, we would need to include the 'framework' wordmark underneath the logo found at source. Otherwise, I'd suggest renaming the icon in the JSON and SVG code to just `Nette`. What do you think @matronator?

**Comment by PeterShaggyNoble** [comment]
I agree with @adamrusted on changing the name to just "Nette" as it looks to be used much more extensively. @matronator, if you can make those changes, along with the addition of the `guidelines` entry to the JSON, then this can be merged straight in.

**Comment by matronator** [comment]
Sorry for the delay, this past couple of weeks have been kinda, IDK... Weird, I guess o_O Name changed to just Nette everywhere and added `guidelines` to the JSON.

**Comment by PeterShaggyNoble** [comment]
Thanks, @matronator 👍🏻 You forget to change it in the SVG title, though, but, in the interest of getting this merged, I went ahead and updated it for you. Once the checks complete (they're running very slow right now), this can be merged straight in.

**Review by PeterShaggyNoble — APPROVED** [review]

**Pull request merged**
