### PR TITLE
Added Carlsberg Group icon

### LINKED ISSUE #8813: Add Carlsberg Group logo
### Brand Name

Carlsberg Group

### Website

https://carlsberggroup.com

### Popularity Metric

https://www.similarweb.com/website/carlsberggroup.com/

### Official Resources for Icon and Color

svg: https://cx-media-fe.live.cx-apps.io/ottilia/age-gateway/logos/ca873d93-747d-48b1-9a97-3e55bc6de560/logo.svg
color: rgb(0, 50, 30), from [Carlsberg's Design Guide](https://www.carlsberggroup.com/who-we-are/about-the-carlsberg-group/design-guide/)

### Additional Comments

There are two variants for the color, one white and the other with the official green (specified above).

### Contributing

Yes

### PR DESCRIPTION
**Pull request by blakmagjick**
carlsberggroup

**Issue:** closes #8813

**Similarweb rank:** #495,776 Globally
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Found SVG on https://www.carlsberggroup.com/who-we-are/about-the-carlsberg-group/design-guide/
- Hex code converted from RBG code in the design guide

### CODE REVIEW

**Comment by blakmagjick** [comment]
This isn't passing all the checks, need to fiddle with the icon a bit more tonight.

**Comment by blakmagjick** [comment]
Finally got the linter to work locally...so hopefully I can get this sorted without having to push so many updates🥲

**Comment by LitoMore** [comment]
In their brand guideline, I didn't see a use case for the clover shape part. We may need to keep the complete trademark.

Or you can reach out to them through mail or their social media for approval.

**Comment by blakmagjick** [comment]
I've sent an email to contact@carlsberg.com this afternoon asking for approval/feedback. Will keep the thread posted when I hear something back.

**Comment by wtfiscrq** [comment]
@blakmagjick If you don’t get a reply soon, ping me and I’ll try reaching out internally.

**Comment by blakmagjick** [comment]
> @blakmagjick If you don’t get a reply soon, ping me and I’ll try reaching out internally.

Thanks! If you could ping internally, that would likely be faster! 😸 
I only got an auto reply to my email, and even that said there is no guarantee that there will be a reply.

**Comment by wtfiscrq** [comment]
Will do that! No worries and thanks! ☺️

**Comment by service-paradis** [comment]
@wtfiscrq Any news?

**Comment by adamrusted** [comment]
Given we've had no response, and although they include the logomark on their website, do not use it apart from the full wordmark elsewhere - I'm going to close this one down for now. If you want to re-work this to include the full wordmark @blakmagjick - be my guest and we can re-open this PR!

**Review by adamrusted — CHANGES_REQUESTED** [review]
See https://github.com/simple-icons/simple-icons/pull/8819#issuecomment-1836385255

**Comment by blakmagjick** [comment]
I can definitely take a stab at it, but due to my current work schedule and moving at the end of the month, I won't be able to tackle it until after the new year....but since this has been open since July, I'm gonna guess that won't be a problem...lol

**Comment by PeterShaggyNoble** [comment]
@blakmagjick, I hope you don't mind but, in the interest of moving it along, I've pushed a few updates to this PR - I'm on a bit of a rampage at the moment, trying to clear out as many issues and PRs as I can!

My icon is based on `\Carlsberg_Group\ai_Professional_use\RGB\Carlsberg_Group_Carlsberg_green_RGB.ai` from the [zip file](https://www.carlsberggroup.com/media/13433/carlsberg_group.zip) available at [the source URL](https://www.carlsberggroup.com/who-we-are/about-the-carlsberg-group/design-guide).

**Review by adamrusted — APPROVED** [review]
LGTM

**Comment by blakmagjick** [comment]
Didn't mind at all...I started a new job and this kept being pushed to the back burner for me. (Like, three weeks later I'm finally commenting...heh) Thanks for getting it over the finish line!

**Pull request merged**
