### PR TITLE
Page search find .NET Google+ etc

### LINKED ISSUE #902: Page search does not find .NET
The search on our website appears to be based on [file names](https://github.com/simple-icons/simple-icons/blob/924632bc6f737d35f584a7ceb04e269036f54bb1/index.html#L182) - it should be based on titles. This clashes with our recent changes to filenames, leading to e.g. ".NET" not finding .NET, while "dot-net" does ([as correctly pointed out by @ericcornelissen](https://github.com/simple-icons/simple-icons/pull/875#pullrequestreview-139680729))

### PR DESCRIPTION
**Pull request by RedSparr0w**
closes #902
Allow search to find `.NET`, `Google+` etc.

### CODE REVIEW

**Comment by birjolaxew** [comment]
:+1: Thanks for the contribution! It is much appreciated.

**Comment by adsingh14** [comment]
Why not we add dotnet as alias ?

**Comment by adsingh14** [comment]
@LitoMore What about .env?

**Comment by LitoMore** [comment]
See https://github.com/microsfot/dotnet. They only use `dotnet` for the repository name and URL path name.

But Dotenv is different. They call themself `Dotenv`.

**Pull request merged**
