### PR TITLE
Add Microsoft Exchange

### LINKED ISSUE #2617: Microsoft Exchange Server
**Name:** Microsoft Exchange Server
**Website:** https://products.office.com/en-ie/exchange/email
**Alexa Rank:** n/a
**Colour:** `#0078d4`
**Official resources for icon and color:** Icon from [Farbric Icons](https://uifabricicons.azurewebsites.net/), colour from [this page](https://developer.microsoft.com/en-us/fabric#/styles/web/colors/products)

[Microsoft Exchange Server](https://github.com/simple-icons/simple-icons/files/4220353/microsoftexchangeserver.zip)

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Microsoft Exchange

**Issue:** Closes #2617

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The source URL isn't ideal as you need to dig around to find the icon in particular, but I couldn't find a single page source that featured both the colour and the new icon in monochrome. To get at the colour from the source URL is straightforward enough - it's the first page when you click through to the colours - but, to get at the icon, you need to go to iconography, scroll down to the end of the page and hit the "Fabric Core" tab ("Fabric React" still uses the old logo)

### CODE REVIEW

**Comment by ericcornelissen** [comment]
I'm not against using this version of the logo, but why don't you use the version of the logo found on [the product colors page](https://developer.microsoft.com/en-us/fabric#/styles/web/colors/products)? That is also the version of the logo you will find on [this page](https://developer.microsoft.com/en-us/fabric#/styles/web/icons) and (but this shouldn't be the reason to switch) it simplifies the source URL.

**Comment by PeterShaggyNoble** [comment]
That's their old log, @ericcornelissen - there are a few on the product colours page that have not (yet) been updated. If you switch from "Fabric React" to "Fabric Core" on the second page you linked, you'll find the new logo there.

**Comment by ericcornelissen** [comment]
That finishes the updates and additions of Microsoft Office icons, thanks a bunch for **all** the work @PeterShaggyNoble :confetti_ball:

**Comment by PeterShaggyNoble** [comment]
There are [a few others](https://en.wikipedia.org/wiki/Microsoft_Office#Components) but I don't think we need add them yet or even until they're requested.

**Comment by ericcornelissen** [comment]
I guess that's what I meant : laughing:

**Pull request merged**
