### PR TITLE
Add Bluesound Icon

### LINKED ISSUE #8915: BlueSound
### Brand Name

BlueSound

### Website

https://www.bluesound.com/

### Popularity Metric

The Similarweb rank is 313,090. See https://www.similarweb.com/website/bluesound.com/#overview

### Official Resources for Icon and Color

None (can't find anything)

### Additional Comments

From the website, it looks like there are two colours, white on black, or black on white
The stylised "B" should be enough, rather than the full "BlueSound" word/logo 

### Contributing

Yes

### PR DESCRIPTION
**Pull request by Mvlprem**
bluesound

**Issue:** closes #8915

**Similarweb rank:** [193,790](https://www.similarweb.com/website/bluesound.com/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

svg taken from product manual [pdf](https://content-bluesound-com.s3.amazonaws.com/uploads/2023/05/NODE-X-Owners-Manual-N131.pdf) the one inside product img, Hex taken from stylesheet

### CODE REVIEW

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
@Mvlprem, we may need to up the precision here; I'm seeing some hairline differences throughout when compared with both the logo and the product icon of the first page of that PDF.

Also, for the colour, I would have expected `#0f131e`. What do you think?

**Comment by Mvlprem** [comment]
I've redone the svg as requested, taken from header ` BLUESOUND ` in the page 1

**Comment by PeterShaggyNoble** [comment]
Looks good to me now, @Mvlprem 🙂 However, there are a couple of unnecessary points along the left edge, in bother corners, that we should be able to remove, as well as [2 groups of overlapping points in the middle](https://github.com/simple-icons/simple-icons/assets/15157491/6822f391-b5ad-44ed-9490-337cb340803f) which it _might_ be possible to clean up.

**Comment by Mvlprem** [comment]
> Looks good to me now, @Mvlprem 🙂 However, there are a couple of unnecessary points along the left edge, in both corners, that we should be able to remove, as well as [2 groups of overlapping points in the middle](https://github.com/simple-icons/simple-icons/assets/15157491/6822f391-b5ad-44ed-9490-337cb340803f) which it _might_ be possible to clean up.

I've already tried cleaning the nodes along the left edge and it didn't work removing any of those nodes left with considerable difference, same for the points in the middle too.

**Review by PeterShaggyNoble — APPROVED** [review]
In that case, this is good to go - thanks for your work on it 👍🏻

**Pull request merged**
