### PR TITLE
Add pre-push GIT hook and workflow to check release tag

### PR DESCRIPTION
**Pull request by mondeja**
Add a pre-push GIT hook to disallow push tags following other format than `X.Y.Z`. Prevents https://github.com/simple-icons/simple-icons/issues/10610 to happen again. EDIT: also adds a workflow to check if a release is created with the wrong tag and deletes it if so.

This is not the first time that happened. I'm not sure if I pushed two years ago a tag with a `v` prefix, but fixed the mistake 10 minutes later. The tag format of simple-icons is not really common so these things can happen and with a lot of third party extensions now a mistake like that can be a real pain.

### CODE REVIEW

**Comment by mondeja** [comment]
I'm not sure if this is cross platform, perhaps could break pushes on Windows 🤔

**Comment by mondeja** [comment]
OK, so if an user is capable of running `.husky/pre-push` before push it means that it has been installed dev dependencies. In that case, has node installed so we can write this as a node script. Rewriting...

**Comment by LitoMore** [comment]
I used `create new release` to create a tag. I'm afraid this hook cannot detect that action.

**Comment by LitoMore** [comment]
Here https://github.com/simple-icons/simple-icons/releases.

It will create a tag when creating new release.

**Comment by mondeja** [comment]
Ahm... 🤔 I'll check if could be some workflow that can be configured at that level.

**Comment by mondeja** [comment]
Hi @LitoMore. I've added a workflow to handle the case that you've faced, tested [here](https://github.com/mondeja/test-tag-release-create-ci-delete/actions/runs/8486806539/job/23253758959#step:5:12) and seems to work fine. Note that to remove releases and tags the app needs the following permission, which is currently granted:

image

Would you mind to review again?

**Comment by LitoMore** [comment]
The Packagist is using the GitHub Webhook event to publish new versions. But this code still cannot intercept the webhook action.

**Comment by mondeja** [comment]
Closing for now...

**Pull request closed without merging**
