### PR TITLE
New Icon: Cloudbees

### PR DESCRIPTION
**Pull request by oleg-nenashev**
**Issue:** #1517

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I would like to add a logo for CloudBees (https://www.cloudbees.com/) so that it can be later used in shields and other artwork. This is an official SVG logo, it was just resized and optimized according to the repository requirements. The hex value has been taken from the corporate color scheme.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Thanks for adding the icon @oleg-nenashev, in order for the SVG to be accepted a couple of changes are still required:

- Remove the `<g>`, since there's only one group it is redundant (the `fill` should also be removed).
- Add `role="img"` to the `<svg>` for accessibility.
- Add `<title>CloudBees icon</title>` right after the opening `<svg>` for accessibility.
- Merge the two `<path>`s into a single one to reduce the file size. If you have editing software for SVG search online for "compound SVG paths in [SOFTWARE]", or if you want I can help you out on this one (since we don't have an automated solution yet... :disappointed:).

**Comment by oleg-nenashev** [comment]
@ericcornelissen thanks for the feedback. I have fixed first two bullets, but I will indeed appreciate help with the third one. Gimp does not seem to support compounding paths, and I do not have any professional graphics design software

**Comment by ericcornelissen** [comment]
> [...] but I will indeed appreciate help with the third one. Gimp does not seem to support compounding paths, and I do not have any professional graphics design software

No problem, actually with #1476 just merged would you mind updating your branch with our latest `develop` and follow [the instructions for using the SVGO Command Line Tool](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon). This should automatically combine the `<path>`s in the SVG for you, beware that you have to run `npm install` again if you did that before. Let me know if you run into any problems (also tell me if our documentation is unclear!), if it doesn't work out I will merge the `<path>`s for you manually 😄

**Comment by oleg-nenashev** [comment]
NPM is restricted on my work laptop due to security reasons :(

**Comment by oleg-nenashev** [comment]
FTR I used the https://jakearchibald.github.io/svgomg/ service to generate the original image .
I can try running svgo in a Docker image, but I am not sure it is going to provide much difference to the current image

**Comment by ericcornelissen** [comment]
> NPM is restricted on my work laptop due to security reasons :(

That is unfortunate in this instance 😅 


> FTR I used the https://jakearchibald.github.io/svgomg/ service to generate the original image .
I can try running svgo in a Docker image, but I am not sure it is going to provide much difference to the current image

We usually recommend using the website you linked. However, the svgo CLI utility has received an update over the weekend that allows you to (force) compounding of paths (you'll need [our configuration file](https://github.com/simple-icons/simple-icons/blob/develop/.svgo.yml) to enable it). So yes, the website will not (yet) compound paths for you.

**Pull request merged**
