### PR TITLE
Add Rocket.Chat

### LINKED ISSUE #5055: Rocket.Chat (communication platform)
A free and open source alternative to Discord.

**Brand Name:** Rocket.Chat
**Website:** https://rocket.chat/
**Alexa rank:** 131,077 (as of 2021-02-18)
  

**Official resources for icon and color:**
- I guess https://rocket.chat/press/ would be the preferred URL to refer to.
- As for the colors, https://docs.rocket.chat/guides/brand-and-visual-guidelines/colors. `#F5455C` would be the color since it is the accent color of the website and the featured on several logo samples.

### PR DESCRIPTION
**Pull request by foo-dogsquared**
simpleicons

**Issue:** Fixes #5055
**Alexa rank:** 161,041

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Original source is `red-logo-icon.svg` for future comparisons.

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for the contribution @foo-dogsquared 💪

I'm seeing a couple small differences, especially around the [circles](https://user-images.githubusercontent.com/1830867/110206474-c79a8c80-7e75-11eb-8708-e659a3272db0.png) - a common cause for this is the optimization process. SVGO(MG) likes to shrink simple shapes to try and get them to match the precision. In that regard, it may be worth rebuilding this one, and optimizing to 4 decimals. That usually fixes the issue.

There's also a couple of points on the path that _could_ be removed if you're feeling up to it. For example, the left-hand-side of the inner speech bubble, seen [here](https://user-images.githubusercontent.com/1830867/110206510-016b9300-7e76-11eb-8405-edcfb6a6b2e1.png) could be reduced - but unfortunately I don't know how to advise on doing that in Inkscape.

If you're having any issues - feel free to ping me here and I'll help where I can!

**Comment by foo-dogsquared** [comment]
(I forgot to create the screenshots, apologies for that.)

Hello, @adamrusted! I've rebuilt the icon with your requested changes. Though, I optimized with 5 decimals instead of 4 since it's still noticeably malformed with the circles.

> There's also a couple of points on the path that could be removed if you're feeling up to it. For example, the left-hand-side of the inner speech bubble, seen here could be reduced - but unfortunately I don't know how to advise on doing that in Inkscape.

I did able to [remove one point](https://user-images.githubusercontent.com/34962634/110237856-3f9dab00-7f79-11eb-9985-f1b43da10beb.png) (original is in green, my version is in red, resulting in a brown color). Although I did not include it in this commit since I want to stick with the original version as much as possible.

**Comment by adamrusted** [comment]
> Hello, @adamrusted! I've rebuilt the icon with your requested changes. Though, I optimized with 5 decimals instead of 4 since it's still noticeably malformed with the circles. (I forgot to create the screenshot for this, apologies for that. I immediately deleted it.)

Weird - I've just tried this in Illustrator, and I _think_ I've got it down to 3 decimals without any malformed circles.

> I did able to [remove one point](https://user-images.githubusercontent.com/34962634/110237856-3f9dab00-7f79-11eb-9985-f1b43da10beb.png) (original is in green, my version is in red, resulting in a brown color). Although I did not include it in this commit since I want to stick with the original version as much as possible.

On attempting this on my end, there are differences introduced by removing these points, so I've also left them in. Will push an update to this branch now, so another @simple-icons/maintainers can review it.

**Review by mondeja — CHANGES_REQUESTED** [review]
Good work with this :+1: Just a minor suggestion: I'm able to remove this coordinate without problems. Could you check that @adamrusted?

image
image

**Comment by PeterShaggyNoble** [comment]
I think we should go with https://docs.rocket.chat/guides/brand-and-visual-guidelines/logo for the `guidelines` here.

Note this line, though:

> Whenever placing the Rocket.Chat symbol in circular or square formats, use the circle in the center of our symbol as a reference for centering

The centre of the canvas isn't quite the centre of the circle though, as seen below. The bottom right corner of the black square is the canvas centre and, of the green square, the circle's centre. It's minor enough that I think we can get away with it, personally.

**Comment by adamrusted** [comment]
> I think we should go with [docs.rocket.chat/guides/brand-and-visual-guidelines/logo](https://docs.rocket.chat/guides/brand-and-visual-guidelines/logo) for the `guidelines` here.

Agree - and it'll help mitigate the below.

> Whenever placing the Rocket.Chat symbol in circular or square formats, use the circle in the center of our symbol as a reference for centering

I think providing we give our users the guidelines, this is a minor enough request that it can be upheld by our end users.

**Comment by adamrusted** [comment]
Could another @simple-icons/maintainers chip in on the discussed points, so we can look at getting this updated and merged? 🙏

**Comment by ericcornelissen** [comment]
> I think providing we give our users the guidelines, this is a minor enough request that it can be upheld by our end users.

I'd disagree, as opposed to some other requests brands put in guidelines this is something we can do - even if it causes some trouble with our linters. Moreover, I wouldn't know how to uphold this as an end user if I was using simple icons through, say, a CDN.

**Comment by adamrusted** [comment]
> I'd disagree, as opposed to some other requests brands put in guidelines this is something we can do - even if it causes some trouble with our linters. Moreover, I wouldn't know how to uphold this as an end user if I was using simple icons through, say, a CDN.

Fair enough. I wouldn't even know where to start with the linters, and working out the correct size of the SVG to make that circle perfectly centered will be a nightmare. I'll have a play with it and see what I can come up with.

**Comment by adamrusted** [comment]
[This](https://user-images.githubusercontent.com/1830867/112973311-15d73e80-9149-11eb-8a39-2a3249ceca56.png) is the closest I'm able to get to their specification using our icon size - see SVG below.

```svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 24.1.2, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 24 24" style="enable-background:new 0 0 24 24;" xml:space="preserve">
<path d="M22.92133,8.30249c-0.64136-0.99915-1.54156-1.88367-2.67236-2.6297
	c-2.18475-1.43921-5.05591-2.23199-8.08429-2.23199c-1.01154,0-2.00806,0.08813-2.97589,0.26282
	C8.58844,3.12427,7.8866,2.60303,7.14319,2.19116c-2.75812-1.3783-5.1886-0.86505-6.41663-0.42236
	c-0.4035,0.14551-0.52795,0.65704-0.22955,0.96558c0.86615,0.896,2.29895,2.66687,1.94672,4.2771
	c-1.36926,1.40125-2.11182,3.09094-2.11182,4.85016c0,1.79285,0.74255,3.48248,2.11182,4.88379
	c0.35223,1.61023-1.08057,3.3819-1.94672,4.27783c-0.29755,0.3078-0.17395,0.81934,0.22955,0.96484
	c1.22803,0.44263,3.65851,0.95673,6.41748-0.42163c0.74341-0.41174,1.44531-0.93298,2.04559-1.51233
	c0.9679,0.17456,1.96442,0.26276,2.97589,0.26276c3.0293,0,5.90045-0.79193,8.08429-2.23114
	c1.1308-0.74597,2.03101-1.62964,2.67236-2.62958C23.63776,14.3432,24,13.14471,24,11.89606
	C23.99915,10.61383,23.6369,9.41632,22.92133,8.30249z M12.04102,18.24011c-1.30927,0-2.55756-0.16925-3.69543-0.47528
	l-0.83167,0.80164c-0.45197,0.43561-0.98163,0.82977-1.5343,1.1402c-0.73193,0.35889-1.45502,0.5556-2.1701,0.61462
	c0.04059-0.07312,0.0777-0.14728,0.11743-0.22131c0.83344-1.53442,1.05853-2.91364,0.6745-4.13684
	c-1.3631-1.07318-2.18066-2.44708-2.18066-3.9436c0-3.43488,4.30743-6.21973,9.62024-6.21973
	c5.31378,0,9.6214,2.78485,9.6214,6.21973C21.66241,15.45526,17.3548,18.24011,12.04102,18.24011z M8.85675,11.99921
	c0,0.77875-0.63477,1.4101-1.41779,1.4101c-0.78308,0-1.41791-0.63135-1.41791-1.4101c0-0.77863,0.63483-1.41003,1.41791-1.41003
	C8.22113,10.58917,8.8559,11.22058,8.85675,11.99921z M13.42004,11.99921c0,0.77875-0.63434,1.4101-1.41791,1.4101
	c-0.78271,0-1.41791-0.63135-1.41791-1.4101c0-0.77863,0.63519-1.41003,1.41791-1.41003
	C12.78571,10.58917,13.42004,11.22058,13.42004,11.99921z M17.98468,11.99921c0,0.77875-0.63513,1.4101-1.41785,1.4101
	c-0.78278,0-1.41797-0.63135-1.41797-1.4101c0-0.77863,0.63519-1.41003,1.41797-1.41003
	C17.34955,10.58917,17.98468,11.22058,17.98468,11.99921z"/>
</svg>

```

**Comment by ericcornelissen** [comment]
> Fair enough. I wouldn't even know where to start with the linters, and working out the correct size of the SVG to make that circle perfectly centered will be a nightmare. I'll have a play with it and see what I can come up wit

I'd say we can just ignore this icon in [the `icon-centered` linter](https://github.com/simple-icons/simple-icons/blob/4e16c14bdca52c56890756887f8a51adc420b33f/.svglintrc.js#L523-L547) - either with a descriptive commit message or with an updated [`.svglint-ignored.json`](https://github.com/simple-icons/simple-icons/blob/develop/.svglint-ignored.json) schema where we can give a reason for ignoring it.

**Comment by PeterShaggyNoble** [comment]
That looks close enough to me, @adamrusted ; getting an `x` position of `12.002` and a `y` position of `11.999` for the centre of the middle circle, which I don't think is a significant enough difference from dead centre for us to worry about.

**Comment by adamrusted** [comment]
@PeterShaggyNoble shall I merge in the path above then, and we can deal with any linter issues that arise from it?

**Comment by PeterShaggyNoble** [comment]
Yep, let's go for it, assuming @foo-dogsquared doesn't mind.

**Comment by adamrusted** [comment]
@ericcornelissen and @PeterShaggyNoble - I've added this to both the 'icon centered' and 'icon size' ignores on the linter, and with that this passes no problem. For comparison, the path is `23.668px` W x `21.165px` H at X `0.332px` and Y `1.2967px`.

**Review by ericcornelissen — APPROVED** [review]
Looks good to me 👍 Maybe we should update the description of https://github.com/simple-icons/simple-icons/issues/4590 that this one does not need to be fixed - after this is merged.

**Comment by adamrusted** [comment]
> Looks good to me 👍 Maybe we should update the description of https://github.com/simple-icons/simple-icons/issues/4590 that this one does not need to be fixed - after this is merged.

Agree, I've added a "Notes" section to the post, detailing the updates made here.

**Comment by PeterShaggyNoble** [comment]
> Looks good to me 👍

@ericcornelissen, was that just in relation to the changes to the list of the ignored icons or did you review the icon itself, too?

**Comment by ericcornelissen** [comment]
> 
> 
> > Looks good to me 👍
> 
> @ericcornelissen, was that just in relation to the changes to the list of the ignored icons or did you review the icon itself, too?

Apologies, I did not look at the SVG - which is also why I didn't merge it.

**Comment by PeterShaggyNoble** [comment]
@adamrusted, when I resize `red-logo-icon.svg` to `23.668` wide, I get a relative height of `21.116` so the comparison with your version is slightly off.

**Comment by adamrusted** [comment]
@PeterShaggyNoble give this a go:

```
X: 0.3246
Y: 1.3312
W: 23.668
H: 21.1164
```

**Review by PeterShaggyNoble — APPROVED** [review]
Looks good to me now, @adamrusted. Thanks for your work on this and for you initial work, too, @foo-dogsquared.

Should we go with just https://docs.rocket.chat/guides/brand-and-visual-guidelines/ for the `guidelines` entry? Once that's decided an, if necessary, updated then this can be merged straight in.

**Comment by adamrusted** [comment]
> Should we go with just [docs.rocket.chat/guides/brand-and-visual-guidelines](https://docs.rocket.chat/guides/brand-and-visual-guidelines/) for the `guidelines` entry? Once that's decided an, if necessary, updated then this can be merged straight in.

Yep. I was going to suggest we go even more specific and use https://docs.rocket.chat/guides/brand-and-visual-guidelines/logo as our guidelines link. If we're okay with that link, I'll push it and merge this PR straight away.

**Comment by PeterShaggyNoble** [comment]
Either works for me, @adamrusted 👍🏻

**Review by adamrusted — APPROVED** [review]
Just updated the `guidelines` entry. Merging on @PeterShaggyNoble's previous approval.

**Pull request merged**
