### PR TITLE
Add Apache Superset icon

### LINKED ISSUE #3508: Superset
**Name:*Superset*
**Website:*https://superset.incubator.apache.org*
**Alexa rank:*2,167*
  

**Official resources for icon and color:*https://superset.incubator.apache.org/_images/s.png*

### PR DESCRIPTION
**Pull request by 10xLaCroixDrinker**
Apache Superset simpleicons preview

**Issue:** closes #3508

**Popularity metric:** [58.9k stars](https://github.com/apache/superset) [upward trend](https://star-history.com/#apache/superset&Date)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Seems the inconsistency between the logo site and the project repo that was present when #3508 was opened has been resolved.

I also tried two other treatments for this. I'm happy to update the PR to either if desired.

<details>
<summary>Expand to see alternative treatments</summary>

image

IMG_5549

</details>

### CODE REVIEW

**Comment by PratyushJayachandran** [comment]
I vote for this treatment:
326268486-a887e28b-a59a-4824-b7a1-962778dfdc9f

**Comment by adamrusted** [comment]
I agree with @PratyushJayachandran - would you mind submitting that version please @10xLaCroixDrinker?

**Comment by 10xLaCroixDrinker** [comment]
Updated!

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @10xLaCroixDrinker!

**Pull request merged**
