### PR TITLE
add conda-forge

### LINKED ISSUE #1218: Add conda-forge
**Name:** conda-forge
**Website:** https://conda-forge.org/
**Official resources for icon and color:** https://github.com/conda-forge/conda-forge.github.io/tree/master/img

### PR DESCRIPTION
**Pull request by casperdcl**
closes #1218

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- chose CD5C5C for hex value. could be black or white instead (original icon and site theme is bw). the only non-bw colours in https://github.com/conda-forge/conda-forge.github.io/blob/master/css/theme.css is CD5C5C or purple.

### CODE REVIEW

**Comment by casperdcl** [comment]
thought this would fail the lint because of `<g>` however that's what `svgomg` produced.

**Comment by casperdcl** [comment]
- yes, can change to #000000
- can't remove those keys as the logo is a black mass with white lines drawn on top

**Comment by ericcornelissen** [comment]
> can't remove those keys as the logo is a black mass with white lines drawn on top

Do you have any SVG editing software? If so you should try to edit it such that this is not the case. Otherwise, you can try using [any of these](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#2-extract-the-icon-from-the-logo) to do so. If you tell me which editor you use I can try to guide you in the progress.

Otherwise, your best bet is to wait for someone to pick this one up 😅

**Comment by casperdcl** [comment]
oh I can edit things but that would alter the logo. The logo is meant to be black *and* have a white outline (so it would stand out on both black or white backgrounds).

Is your general ethos to reject such logos? If so it should be in the guide.

**Comment by ericcornelissen** [comment]
> oh I can edit things but that would alter the logo. The logo is meant to be black _and_ have a white outline (so it would stand out on both black or white backgrounds).
Is your general ethos to reject such logos? If so it should be in the guide.

We do not necessarily reject such logos, but we do provide **monochrome** (i.e. one colour) versions of logos. In this case the inner (black) part of the logo can either be omitted/made transparent, or combined with the outline into a single shape.

**Comment by casperdcl** [comment]
done what i can now; can't find a way to remove fill=none or stroke=#000

**Comment by ericcornelissen** [comment]
What editor do you use to modify the SVG? I might be able to help you if you tell me 🙂  Good job on the changes so far, visually the logo looks ready for use now

**Comment by casperdcl** [comment]
inkscape & vim

**Comment by ericcornelissen** [comment]
In that case [this guide](https://graphicdesign.stackexchange.com/a/84571) should help you convert the stroke into a path. When you did that, I expect you have a single `<path>` without the attributes `stroke` and `stroke-width`. There might still be a `fill` which you can remove safely.

**Comment by casperdcl** [comment]
The link didn't help but I managed something. Don't even know how to replicate it but seems to have worked.

**Comment by ericcornelissen** [comment]
Thanks for the effort @casperdcl 🎉

**Pull request merged**
