### PR TITLE
adding Google docs icons

### PR DESCRIPTION
**Pull request by jorgeamadosoria**
googleslides

Issue: #5155

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
googledocs

**Comment by jorgeamadosoria** [comment]
googleforms

**Review by dirien — APPROVED** [review]
LGTM

**Comment by sachinraja** [comment]
For Google Docs, should the bars in the middle be completely cut out, like they are for the Google Forms icon?

**Comment by adamrusted** [comment]
> For Google Docs, should the bars in the middle be completely cut out like they are for the Google Forms icon?

I would say yes, just to keep the Google icons consistent.

**Comment by service-paradis** [comment]
Looks like we increased the corner cutout for Google Sheet. Maybe we should do the same too.

**Comment by jorgeamadosoria** [comment]
> Looks like we increased the corner cutout for Google Sheet. Maybe we should do the same too.

I've widened the cut to better show, at the same width than the one on google sheets

**Comment by mzs21** [comment]
Where are the icons? I can't find on the website.

**Comment by adamrusted** [comment]
Closing as head of this PR has been deleted. If you can (and want to) @jorgeamadosoria - feel free to recover the branch and re-open this PR.

**Pull request closed without merging**
