### PR TITLE
Add guidelines in Microsoft

### PR DESCRIPTION
**Pull request by chetannada**
Added guidelines in all Microsoft Icons

**Issue:** closes #

**Similarweb rank:**
  

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by LitoMore** [comment]
This will increase our package bundle size quickly.

I prefer to move these duplicated data to another place. For example:

```json
{
	"icons": [
		{
			"title": "Microsoft Stuff",
			"source": "#microsoft",
			"guidelines": "#microsoft"
		}
	],
	"sources": {
		"microsoft": "https://source.example.com"
	},
    "guidelines": {
		"microsoft": "https://guideline.example.com"
	}
}
```

Or:

```json
{
	"icons": [
		{
			"title": "Microsoft Icon",
			"source": "#microsoft",
			"guidelines": "#microsoft"
		},
		{
			"title": "Amazon Icon",
			"source": "#amazon-source",
			"guidelines": "#amazon-guidelines",
			"license": {
				type: "custom",
				url: "#amazon-custom-license"
			}
		}
	],
	"links": {
		"microsoft": "https://microsoft-source-and-guideline.example.com",
		"amazon-source": "https://amazon-source.exmaple.com",
		"amazon-guidelines": "https://amazon-guidelines.example.com",
		"amazon-custom-license": "https://amazon-license.example.com"
	}
}
```

**Comment by adamrusted** [comment]
This would likely need to be part of a major release though, correct?
I'm not aware of other projects accessing our source, guidelines, and license data - but we need to ensure if anything is likely to break with us reformatting - we cover ourselves!

**Comment by service-paradis** [comment]
I dont think there is enough duplicated data to justify a completely new structure.
This would require many changes for the website and how people fetch the icon from the package.

**Comment by adamrusted** [comment]
`<sarcasm, but only slightly>`
If we're talking JSON changes, can we split into different files by lettter?
Make my reviews so much easier!
`</sarcasm>`

**Comment by chetannada** [comment]
> This will increase our package bundle size quickly.
> 
> I prefer to move these duplicated data to another place. For example:
> 
> ```json
> {
> 	"icons": [
> 		{
> 			"title": "Microsoft Stuff",
> 			"source": "#microsoft",
> 			"guidelines": "#microsoft"
> 		}
> 	],
> 	"sources": {
> 		"microsoft": "https://source.example.com"
> 	},
>     "guidelines": {
> 		"microsoft": "https://guideline.example.com"
> 	}
> }
> ```
> 
> Or:
> 
> ```json
> {
> 	"icons": [
> 		{
> 			"title": "Microsoft Icon",
> 			"source": "#microsoft",
> 			"guidelines": "#microsoft"
> 		},
> 		{
> 			"title": "Amazon Icon",
> 			"source": "#amazon-source",
> 			"guidelines": "#amazon-guidelines",
> 			"license": {
> 				"type": "custom",
> 				"url": "#amazon-custom-license"
> 			}
> 		}
> 	],
> 	"links": {
> 		"microsoft": "https://microsoft-source-and-guideline.example.com",
> 		"amazon-source": "https://amazon-source.exmaple.com",
> 		"amazon-guidelines": "https://amazon-guidelines.example.com",
> 		"amazon-custom-license": "https://amazon-license.example.com"
> 	}
> }
> ```

Yeah, Currently [simple-icons.json](https://github.com/simple-icons/simple-icons/blob/31044e2a538b22589411f487a0be4948f5f4ec44/_data/simple-icons.json) file is very huge, I will make changes according  to your suggestion. Thanks.

@adamrusted I'm also thinking the same because [simple-icons.json](https://github.com/simple-icons/simple-icons/blob/31044e2a538b22589411f487a0be4948f5f4ec44/_data/simple-icons.json) contains 14k+ lines of code so we can split into different files by lettter. It's good Idea.

**Comment by adamrusted** [comment]
> Yeah, Currently [simple-icons.json](https://github.com/simple-icons/simple-icons/blob/31044e2a538b22589411f487a0be4948f5f4ec44/_data/simple-icons.json) file is very huge, I will make changes according to your suggestion. Thanks.

It's worked for us up until now - but I think a deeper discussion is required further down the line as to how we manage the JSON.
This, however, is not the place for it. I'm happy to merge this as-is. Thanks @chetannada 🎉

**Comment by chetannada** [comment]
> > Yeah, Currently [simple-icons.json](https://github.com/simple-icons/simple-icons/blob/31044e2a538b22589411f487a0be4948f5f4ec44/_data/simple-icons.json) file is very huge, I will make changes according to your suggestion. Thanks.
> 
> It's worked for us up until now - but I think a deeper discussion is required further down the line as to how we manage the JSON. This, however, is not the place for it. I'm happy to merge this as-is. Thanks @chetannada 🎉

I'm also glad that my PR is getting merged. Thanks @adamrusted 😍

**Pull request merged**
