### PR TITLE
Updated Common Workflow Language

### PR DESCRIPTION
**Pull request by fbernhart**
commonworkflowlanguage

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by adamrusted** [comment]
Embedded in the [source file](https://github.com/common-workflow-language/logo/blob/main/CWL-Logo-nofonts.svg) for this one, there is a black and white variation which doesn't include the gaps. @simple-icons/maintainers should we use this one instead?

**Comment by mondeja** [comment]
> Embedded in the source file for this one, there is a black and white variation which doesn't include the gaps. @simple-icons/maintainers should we use this one instead?

I've found it in the `.ai` file, but not in the SVG file that you've linked :thinking:
I would say yes because seems to be the monochrome official version. Maybe these gaps are a subjective interpretation of the colored logo.

**Comment by adamrusted** [comment]
> I've found it in the `.ai` file, but not in the SVG file that you've linked 🤔

Weird - it's just showing up as another set of layers in Illustrator...
Path of monochrome logo provided at 3 decimals for reference.

```svg
M15.482,8.861l-0.017,0.017l0.017,0.015l-3.889,3.889L13.811,15l0.011-0.011l1.543,1.575l-3.761,3.814l1.993,2.046 L12.054,24l-3.429-3.482v-0.011l-0.107-0.118l3.76-3.828l-3.76-3.79l1.532-1.543h0.011l2.309-2.322L8.721,5.454L8.625,5.357 L13.918,0l1.564,1.596l-3.664,3.718L15.482,8.861z
```

**Review by adamrusted — CHANGES_REQUESTED** [review]
Path of monochrome logo provided at 3 decimals for reference.

```svg
M15.482,8.861l-0.017,0.017l0.017,0.015l-3.889,3.889L13.811,15l0.011-0.011l1.543,1.575l-3.761,3.814l1.993,2.046 L12.054,24l-3.429-3.482v-0.011l-0.107-0.118l3.76-3.828l-3.76-3.79l1.532-1.543h0.011l2.309-2.322L8.721,5.454L8.625,5.357 L13.918,0l1.564,1.596l-3.664,3.718L15.482,8.861z
```

**Comment by fbernhart** [comment]
@adamrusted Fixed

**Review by adamrusted — APPROVED** [review]
LGTM 🎉

**Pull request merged**
