### PR TITLE
Added Polywork

### PR DESCRIPTION
**Pull request by medoix**
Polywork

**Issue:** #5756
**Alexa rank:** 104,926

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
First time doing anything like this so please have mercy! :)

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for your work on this @medoix! 💪
Having a quick look, there appears to have been some [issues](https://user-images.githubusercontent.com/1830867/120101233-05d5de00-c13d-11eb-8e0a-dbd0a814887c.png) with the optimization (see your path in red, source in black) and also [unnecessary paths](https://user-images.githubusercontent.com/1830867/120101247-15edbd80-c13d-11eb-825e-669d92eb896b.png) showing, which may just be a result of the coloured squares being included when not needed.

I've included my comparison icon below, which passes the linter at 3 decimals - and you're welcome to use if you'd prefer.
I'd also recommend updating the source to the page on which you found that SVG, as the page is likely to persist longer than that specific file, so we can track any updates!

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Polywork</title><path d="M19.125 0H4.875A4.865 4.865 0 0 0 0 4.875v14.25C0 21.825 2.175 24 4.875 24h6.6c2.7 0 4.875-2.175 4.875-4.875V16.65h2.775c2.7 0 4.875-2.175 4.875-4.875v-6.9C24 2.175 21.825 0 19.125 0zM16.5 1.275h2.625a3.6 3.6 0 0 1 3.6 3.6v2.7H16.5v-6.3zM15.075 9v6.45H8.85V9h6.225zM8.85 1.2h6.225v6.375H8.85V1.2zM1.275 4.8a3.6 3.6 0 0 1 3.6-3.6H7.5v6.375H1.275V4.8zM7.5 9v6.45H1.2V9h6.3zm0 13.725H4.8a3.6 3.6 0 0 1-3.6-3.6V16.8h6.3v5.925zm7.575-3.525a3.6 3.6 0 0 1-3.6 3.6H8.85v-5.925h6.225V19.2zm7.65-7.35a3.6 3.6 0 0 1-3.6 3.6H16.5V9h6.225v2.85z"/></svg>
```

**Comment by adamrusted** [comment]
Thanks for the updates @medoix, though we'll now need to ask another @simple-icons/maintainers to review this as you've used my path. Great work on this regardless! 🎉

**Comment by medoix** [comment]
> Thanks for your work on this @medoix! muscle
> Having a quick look, there appears to have been some [issues](https://user-images.githubusercontent.com/1830867/120101233-05d5de00-c13d-11eb-8e0a-dbd0a814887c.png) with the optimization (see your path in red, source in black) and also [unnecessary paths](https://user-images.githubusercontent.com/1830867/120101247-15edbd80-c13d-11eb-825e-669d92eb896b.png) showing, which may just be a result of the coloured squares being included when not needed.
> 
> I've included my comparison icon below, which passes the linter at 3 decimals - and you're welcome to use if you'd prefer.
> I'd also recommend updating the source to the page on which you found that SVG, as the page is likely to persist longer than that specific file, so we can track any updates!
> 
> ```
> <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Polywork</title><path d="M19.125 0H4.875A4.865 4.865 0 0 0 0 4.875v14.25C0 21.825 2.175 24 4.875 24h6.6c2.7 0 4.875-2.175 4.875-4.875V16.65h2.775c2.7 0 4.875-2.175 4.875-4.875v-6.9C24 2.175 21.825 0 19.125 0zM16.5 1.275h2.625a3.6 3.6 0 0 1 3.6 3.6v2.7H16.5v-6.3zM15.075 9v6.45H8.85V9h6.225zM8.85 1.2h6.225v6.375H8.85V1.2zM1.275 4.8a3.6 3.6 0 0 1 3.6-3.6H7.5v6.375H1.275V4.8zM7.5 9v6.45H1.2V9h6.3zm0 13.725H4.8a3.6 3.6 0 0 1-3.6-3.6V16.8h6.3v5.925zm7.575-3.525a3.6 3.6 0 0 1-3.6 3.6H8.85v-5.925h6.225V19.2zm7.65-7.35a3.6 3.6 0 0 1-3.6 3.6H16.5V9h6.225v2.85z"/></svg>
> ```

Thanks for the help @adamrusted. I really have no idea what is happening inside the `<path d=` section and i have been testing this with a few files today so no doubt i possibly mucked up and used one with the squares still in it (or partially removed some of the squares manually in the SVG but not the other items). Either way was a good learning, will continue to try and learn more about Inkscape and SVG files.

**Comment by PeterShaggyNoble** [comment]
SVG looks good to me and I agree with Adam that it probably _is_ intended to be square 👍🏻

On the colour, though, @medoix: from their website, I would have expected it to be purple rather than blue, or am I missing something?

**Comment by medoix** [comment]
@PeterShaggyNoble thank you for the feedback. The blue came from the product if you are logged in but i just opened the site without a session (it auto directs you to the profile page) and i see what you mean now so have changed the default color to the website purple to match better.

**Comment by medoix** [comment]
I am not sure where the preview image comes from so am unable to update it to reflect the change in color.

**Comment by PeterShaggyNoble** [comment]
For future reference, the preview generator can be found at https://petershaggynoble.github.io/SI-Sandbox/preview/

**Pull request merged**
