### PR TITLE
Add pnpm icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** N/A
**Alexa rank:** [10.9k Github ⭐](https://github.com/pnpm/pnpm)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I took the Standard Logo with no text SVG from https://pnpm.io/logos#standard-logo-with-no-text
- I used Inkscape to scale
- I used https://jakearchibald.github.io/svgomg/ to optimize
- I took the primary color define in the website stylesheet
  - `#f9ad00` from the logo might be another color option

### CODE REVIEW

**Review by PeterShaggyNoble — APPROVED** [review]
Looks spot on to me, @service-paradis and I agree with the colour choice. Nice one 👍🏻

**Comment by zkochan** [comment]
Thanks but the logo look different. These are the 2 versions of the pnpm logo:

image
image

**Comment by PeterShaggyNoble** [comment]
Thanks for the feedback, @zkochan. Are you saying that the use of your icon in monochrome isn't permitted? If so, we will, unfortunately, have to remove it as we are a monochrome icon library. Note that this icon will be added in our release this coming Sunday so if it is to be removed it will need to be done before then or we'll have to wait until our next major release next month.

**Comment by zkochan** [comment]
OK, if this should be monochrome then the submitted version is fine.

**Comment by PeterShaggyNoble** [comment]
Thanks for the seal of approval, @zkochan, much appreciated 🙂

**Pull request merged**
