### PR TITLE
Add Nx

### PR DESCRIPTION
**Pull request by brunano21**
nx

**Issue:** Contributes to #4767
**Alexa Rank:** [163,745](https://www.alexa.com/siteinfo/nx.dev)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
As with #4859, if you could update the source to the homepage, I'll look at reviewing the path 👍🏻

**Comment by brunano21** [comment]
> As with #4859, if you could update the source to the homepage, I'll look at reviewing the path 👍🏻

Do you changing the source to point at https://nrwl.io/?

**Comment by brunano21** [comment]
Done - please let me know if it looks fine now.

**Comment by brunano21** [comment]
@adamrusted - can you please _resolve the conversations?

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks @brunano21, and sorry I wasn't able to look at this yesterday.
I've pushed an update to the source URL to change it to nx.dev - as that's where the SVG for this icon is found. There's also a small error in the right-hand side of the wave, which may have been caused by optimization. Could you take another look at it for me please?

image

**Comment by brunano21** [comment]
@adamrusted how can I fix that? Also, I'm able to see that in InkScape...any suggestion?

**Comment by adamrusted** [comment]
> @adamrusted how can I fix that? Also, I'm not able to see that in InkScape...any suggestion?

I've overlaid your Pull Request icon in red against the source SVG in black - so as I mentioned it looks like the path has been edited by the optimization process. You may need to rebuild it from the source SVG, and run through [SVGOMG](https://jakearchibald.github.io/svgomg/), making sure the optimization process doesn't alter the shape of the wave.

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @brunano21?

**Comment by adamrusted** [comment]
@PeterShaggyNoble I've just pushed an update to the path, as suggested in my review. Should be okay for merging now 🤞

**Comment by brunano21** [comment]
@PeterShaggyNoble I was meant to work on this but got very very busy in the last weeks. 🙄

@adamrusted thanks a lot for helping with this! 💪

**Comment by PeterShaggyNoble** [comment]
@adamrusted, there are some tint, not even hairline differences in some of the curves of the wave but nowhere near significant enough, I don't think, to warrant increasing the precision further. However, there are a couple of points that you may be able to remove; one in the dip where the wave joins the top of the "X" and one at the very right edge of the wave.

**Comment by adamrusted** [comment]
@PeterShaggyNoble - give that a try. Can't believe I didn't spot those points on the wave! 🤦‍♂️

**Review by PeterShaggyNoble — COMMENTED** [review]
> Can't believe I didn't spot those points on the wave!

When you consider how many points we look at every day across all the icons we work on, it's amazing we don't all miss more! 😆

Anyway, this looks perfect to me now; thanks for your work on it, @brunano21 and @adamrusted :+1:

**Pull request merged**
