### PR TITLE
adding Funimation icon

### PR DESCRIPTION
**Pull request by jorgeamadosoria**
funimation

**Issue:** #6652 

Used the svg present in their header since the official assets are JPG, PNG and AI. They all draw the same thing.
Could have used only the smiling face as depicted in their favicon in some social media, but apparently they only have the full wordmark as official logo and the smiling face is a space saving measure on their socials. 

Happy to change to only the smiling face if necessary, but I would stick to the officially approved logo if no one minds.

Smiling face version is:
funimation (1)

### CODE REVIEW

**Comment by service-paradis** [comment]
Since they use the smiley only for their favicon and on social media, I think we're ok with the icon only. There are no explicit sentence preventing the use of the icon only (or did I missed it?).

Me may ask other maintainers to weight in if you want!

**Comment by jorgeamadosoria** [comment]
> Since they use the smiley only for their favicon and on social media, I think we're ok with the icon only. There are no explicit sentence preventing the use of the icon only (or did I missed it?).
> 
> Me may ask other maintainers to weight in if you want!

I didn't find an express prohibition, no. I didn't read the PDF, but no, I don't think it's expressly prohibited.

**Comment by dirien** [comment]
@jorgeamadosoria,

This time its me, who cant access the header for the original svg. 

image

**Comment by jorgeamadosoria** [comment]
@dirien here you go:
`

<svg xmlns="http://www.w3.org/2000/svg" width="132.263" height="17.61" viewBox="0 0 132.263 17.61">
--
  | <g id="logo" transform="translate(-291.013 -297.657)">
  | <path id="Path_2" data-name="Path 2" d="M329.5,299.464a4.744,4.744,0,0,0-1.923-1.3,8.236,8.236,0,0,0-2.92-.453,6.135,6.135,0,0,0-3.286.927,5.092,5.092,0,0,0-1.756,1.763V298.18h-2.4v16.643h2.4v-9.668A6.985,6.985,0,0,1,320,303a5.2,5.2,0,0,1,.966-1.693,4.416,4.416,0,0,1,1.5-1.111,4.874,4.874,0,0,1,2.035-.406,4.507,4.507,0,0,1,1.908.357,3.02,3.02,0,0,1,1.192.97,3.9,3.9,0,0,1,.626,1.478,9.241,9.241,0,0,1,.184,1.891v10.334h2.4V304.18a11.335,11.335,0,0,0-.289-2.659A4.857,4.857,0,0,0,329.5,299.464Z" fill="#410099"/>
  | <rect id="Rectangle_2" data-name="Rectangle 2" width="2.4" height="16.643" transform="translate(332.559 298.181)" fill="#410099"/>
  | <path id="Path_3" data-name="Path 3" d="M354.193,297.709a6.371,6.371,0,0,0-3.12.812,5.109,5.109,0,0,0-2,2.026,3.975,3.975,0,0,0-1.677-2.021,5.759,5.759,0,0,0-3.016-.816,5.973,5.973,0,0,0-3.37.884,6.259,6.259,0,0,0-1.828,1.909V298.18H336.94v16.643h2.4v-9.265a9.219,9.219,0,0,1,.276-2.321,5.407,5.407,0,0,1,.832-1.817,3.842,3.842,0,0,1,1.432-1.193,4.735,4.735,0,0,1,2.093-.435,3.541,3.541,0,0,1,1.513.294,2.514,2.514,0,0,1,.973.8,3.424,3.424,0,0,1,.532,1.215,6.665,6.665,0,0,1,.167,1.509v11.214h2.4v-9.391a11.273,11.273,0,0,1,.2-2.145,5.394,5.394,0,0,1,.68-1.8,3.57,3.57,0,0,1,1.278-1.233,4.075,4.075,0,0,1,2.034-.46,3.473,3.473,0,0,1,2.824.975,4.613,4.613,0,0,1,.8,2.935v11.12h2.4V303.611C359.779,299.7,357.9,297.709,354.193,297.709Z" fill="#410099"/>
  | <path id="Path_4" data-name="Path 4" d="M375.864,312.739c-.66,0-.954-.3-.954-.984V303.14a5.964,5.964,0,0,0-.558-2.755,4.433,4.433,0,0,0-1.453-1.664,5.391,5.391,0,0,0-1.995-.8,11.519,11.519,0,0,0-2.177-.208,10.081,10.081,0,0,0-2.633.322,6,6,0,0,0-2.1,1.01,4.856,4.856,0,0,0-1.43,1.77,6.832,6.832,0,0,0-.618,2.53l-.015.223h2.407l.006-.2a3.332,3.332,0,0,1,1.174-2.716,4.82,4.82,0,0,1,2.956-.854,8.9,8.9,0,0,1,1.613.138,3.459,3.459,0,0,1,1.276.488,2.412,2.412,0,0,1,.839.942,3.425,3.425,0,0,1,.307,1.555,2.613,2.613,0,0,1-.156.987,1.325,1.325,0,0,1-.42.559,1.74,1.74,0,0,1-.7.292c-.307.061-.671.113-1.084.155-1.052.124-2.116.256-3.163.393a11.634,11.634,0,0,0-2.85.721,4.963,4.963,0,0,0-2.083,1.527,4.414,4.414,0,0,0-.8,2.786,5.153,5.153,0,0,0,.445,2.212,4.288,4.288,0,0,0,1.223,1.552,5,5,0,0,0,1.8.887,8.421,8.421,0,0,0,2.177.274,8.77,8.77,0,0,0,2.111-.227,5.92,5.92,0,0,0,1.6-.652,5.643,5.643,0,0,0,1.274-1.061q.4-.45.8-.99c.013.222.035.433.065.63a2.4,2.4,0,0,0,.363.981,1.839,1.839,0,0,0,.8.657,3.226,3.226,0,0,0,1.3.223,6.285,6.285,0,0,0,.7-.033c.181-.021.392-.053.627-.1l.172-.031V312.5l-.294.131A1.325,1.325,0,0,1,375.864,312.739Zm-3.354-6.526v2.115a4.669,4.669,0,0,1-.435,2.047,4.717,4.717,0,0,1-1.174,1.536,5.136,5.136,0,0,1-1.737.969,6.654,6.654,0,0,1-2.1.336,4.075,4.075,0,0,1-1.286-.209,3.328,3.328,0,0,1-1.094-.606,3.056,3.056,0,0,1-.751-.943,2.691,2.691,0,0,1-.276-1.241,2.148,2.148,0,0,1,.639-1.684,4.586,4.586,0,0,1,1.73-.946,14.259,14.259,0,0,1,2.4-.511c.886-.114,1.762-.247,2.6-.394a7.5,7.5,0,0,0,.97-.226,1.717,1.717,0,0,0,.517-.245Z" fill="#410099"/>
  | <path id="Path_5" data-name="Path 5" d="M375.994,300.266h2.83V311.15a3.123,3.123,0,0,0,3.731,3.83c.292,0,.593-.011.9-.032.286-.021.577-.031.865-.031h.209v-2.11l-.232.026a14.9,14.9,0,0,1-1.662.093c-.628-.037-1.019-.2-1.16-.5a3.38,3.38,0,0,1-.246-1.434V300.259h3.3v-2.085H376Z" fill="#410099"/>
  | <rect id="Rectangle_3" data-name="Rectangle 3" width="2.4" height="16.643" transform="translate(386.406 298.181)" fill="#410099"/>
  | <path id="Path_6" data-name="Path 6" d="M422.988,301.516a4.872,4.872,0,0,0-1.019-2.053,4.732,4.732,0,0,0-1.923-1.3,8.237,8.237,0,0,0-2.92-.454,6.135,6.135,0,0,0-3.286.927,5.092,5.092,0,0,0-1.756,1.763v-2.22h-2.4v16.643h2.4v-9.668a7.015,7.015,0,0,1,.381-2.152,5.2,5.2,0,0,1,.966-1.693,4.416,4.416,0,0,1,1.5-1.111,4.874,4.874,0,0,1,2.035-.406,4.5,4.5,0,0,1,1.907.357,3.012,3.012,0,0,1,1.192.97,3.9,3.9,0,0,1,.626,1.478,9.243,9.243,0,0,1,.184,1.891v10.334h2.4V304.18A11.321,11.321,0,0,0,422.988,301.516Z" fill="#410099"/>
  | <path id="Path_7" data-name="Path 7" d="M399.238,297.657a8.589,8.589,0,1,0,8.589,8.589A8.59,8.59,0,0,0,399.238,297.657Zm.02,13.839c-2.971,0-3.284-2.346-3.284-2.346h6.568s-.312,2.346-3.284,2.346Z" fill="#410099"/>
  | <path id="Path_8" data-name="Path 8" d="M297.8,297.666c-2.533,0-6.783.8-6.783,6.193v10.966h2.455v-6.838h5.549v-2.268h-5.573v-1.9a3.675,3.675,0,0,1,.918-2.536,4.911,4.911,0,0,1,3.755-1.3,12.612,12.612,0,0,1,1.8.143l.24.035V297.9l-.166-.035A11.886,11.886,0,0,0,297.8,297.666Z" fill="#410099"/>
  | <path id="Path_9" data-name="Path 9" d="M315.377,298.137h-2.466v10.639a4.2,4.2,0,0,1-3.992,4.4c-.119.006-.238.007-.357,0-.045,0-4.488-.228-4.488-4.4V298.137h-2.331v9.889a7.672,7.672,0,0,0,1.722,5.263,6.494,6.494,0,0,0,4.776,1.967v.008h.637v-.006a6.542,6.542,0,0,0,4.814-1.972,7.446,7.446,0,0,0,1.685-5.123Z" fill="#410099"/>
  | </g>
  | </svg>

`

**Review by dirien — APPROVED** [review]
hi @jorgeamadosoria,

perfect fit!
image

**Pull request merged**
