### PR TITLE
Change Mozilla icon to social icon instead of wordmark

### PR DESCRIPTION
**Pull request by rosslh**

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Oops 😅 that is unfortunate... I did a [squash commit](https://github.com/blog/2141-squash-your-commits) for your last PR, which resulted in different histories on our and your `develop` branch.

Would you mind branching of 7bb8191 with your `474c459` commit and change the base of this PR to that branch?

Ps. I do like the change 👍 but you should have a look at some of the attributes & tags 😉

**Comment by rosslh** [comment]
Thaks for the heads-up, Eric, those problems should now be resolved.

**Comment by birjolaxew** [comment]
You seem to have a stray `id="a"` on your path - other than that this looks good :)

**Comment by rosslh** [comment]
Oh, whoops! Should be good now @birjolaxew

**Comment by birjolaxew** [comment]
:+1: Looking good! Thanks for the contribution!

**Pull request merged**
