### PR TITLE
Add Cloud Foundry icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** https://github.com/simple-icons/simple-icons/issues/5840
**Alexa rank:** 179,978
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
For the SVGs
https://github.com/cloudfoundry/logos

For the guidlines, styleguides
https://www.cloudfoundry.org/logo/

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for your work on this, @dirien - and welcome to Simple Icons!
This icon _really_ doesn't look to be fun to work with - so kudos for tackling it.
Overlaying the white EPS file found at the guidelines page you mentioned produces the following difference - which may primarily be down to the linter (it's a bit troublesome!), but there are also _way too many_ excess points in the source file.

Could I suggest that you take another look at this, by using the monochrome EPS available and creating two copies, one which is just converted to 24px tall, but no further optimizations (apart from locking it, so you don't edit it!) - and then another on top of that (ideally in a bright colour for easy comparison) which you can optimize. I don't know what it's referred to as in other programs but in Illustrator I use the Object -> Path -> Simplify tool with specifically selected regions (mainly straight lines) to remove any excess points. You can then compare your path (bright colour) to the one underneath it to make sure you're matching the original path.

You may also find you need to set SVGO to use 4 decimals, instead of 3. That's fine by our guidelines, as we allow anywhere between 3-5 decimals of precision should the icon need it.

Any questions, feel free to ping me - and if you're not using Illustrator I might need to ask one of the other maintainers to chip in 😅

**Comment by dirien** [comment]
Hi @adamrusted, thanks for the feedback. Unfortunatly I am not a Illustrator nor i have access to the same tool. I used some free online tools to crop the SVG. I use boxy-svg.com

And simplifying here, makes a nice piece of art out of it.
image

So maybe someone of the community chip in to help otherwhise i would close the PR.

**Comment by adamrusted** [comment]
> So maybe someone of the community chip in to help otherwhise i would close the PR.

No worries! If you're able to, I'd recommend using something like [Inkscape](https://inkscape.org/) for editing, as you'll be able to have much more control than with something like boxy-svg.

I'll also take a look tomorrow at generating a path myself, which you'd be welcome to use if you want.

**Comment by dirien** [comment]
hi @adamrusted ,

tried inkspace and removed some points! Hope its better this time :)


Looking forward for your feedback 😄 

image

**Comment by adamrusted** [comment]
Hey @dirien - thanks for your continued work on this one.
Unfortunately, I can see some [differences](https://user-images.githubusercontent.com/1830867/121049099-52f62780-c7af-11eb-909d-f2e8c5bb37e6.png) between this PR in red, and the source in black. Some of this could be due to the removal of points (I get a bit trigger-happy in Illustrator!) or the optimization process. Let me have a quick look at generating a path on my end, because I can see this would be an awkward one to work with.

**Comment by dirien** [comment]
@adamrusted, yes this is a job for a expert. If i continue like this the guild of designers will come to slap me 😄

**Comment by adamrusted** [comment]
@dirien - the below path has _minimal_ differences, I've taken some liberties when rounding curves, etc.
Before you merge it in, I'll ask for another of the @simple-icons/maintainers to sign off on the below, just to make sure they're happy with the minor differences.

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Cloud Foundry</title><path d="M12.8535 13.537c-.0479 1.7904.0743 3.8624.1495 4.9168.9592.1363 1.6328.4566 1.6328.8301 0 .4972-1.1932 1.0704-2.665 1.0704s-2.665-.5732-2.665-1.0704c0-.3735.6736-.6939 1.6328-.8301.0752-1.0544.1974-3.1264.1495-4.9169-.0432-1.6134-.7781-3.0909-1.6753-3.8214-.7251-.5903-1.1735-1.427-1.1654-2.3532.0154-1.7655 1.6824-3.186 3.7235-3.186s3.7081 1.4205 3.7235 3.186c.0081.9262-.4403 1.7629-1.1654 2.3532-.8974.7305-1.6323 2.208-1.6755 3.8215zm6.2144 6.5962c.287-.1149.6121-.1773.9515-.1903-.0079-.2405-.1669-.6717-.3035-.8774-.5606-.0987-1.2763-.3129-1.6581-.682-.1615-.1409-.1913-.2818-.1861-.4094.0266-.1464.1332-.2533.2787-.3291-.2709-.1638-.7918-.4085-1.08-.5153-.5471.0666-1.1754.0204-1.6972-.1234-.303-.0907-.7644-.2406-.8208-.5493-.1601-.0297-.539-.083-.7653-.1121-.0188.0544-.058.2445-.0709.3106-.0885.4156.1522.8373.5606.9556.9998.2911 1.7558.7704 1.9739 1.3588.4412 1.1901-1.4123 2.3535-4.2307 2.3535-2.8194 0-4.673-1.1634-4.2327-2.3535.213-.574.9392-1.044 1.903-1.3372.4269-.1296.6799-.5688.5883-1.0049l-.0596-.2829c-.2911.0309-.779.1015-1.031.1481-.0185.3129-.476.466-.7602.5637-.5314.1527-1.1652.2066-1.7075.1471-.3249.1305-.7536.351-1.0523.5349.5439.2311.3158.7363-.0905.97-.4066.2535-.8419.409-1.3794.5112-.0513.0874-.1115.2973-.1635.4371-.016.1359-.0628.3666-.0524.4588.6451.0196 1.2678.1523 1.6201.6048.281.5082-.0246.9766-.5102 1.3639.3917.3167.9855.6735 1.4504.8682.8501-.346 1.8198-.4459 2.7145-.2685.7179.1594 1.5059.5809 1.7424 1.2888.6346.0419 1.8949.0398 2.5273-.0411.1825-.7311.9069-1.1465 1.6067-1.3259.8949-.2041 1.8444-.1254 2.7114.1934.3565-.1798 1.0307-.6025 1.3064-.9-.4738-.3585-.8735-.7949-.6295-1.3259.0843-.1893.3003-.3292.5462-.4403zm-9.5402-5.8487s.4187-1.5855-1.3996-3.6311c-.8105-.906-1.2457-2.0981-1.2485-3.307 0-2.7796 2.2639-5.0412 5.0469-5.0412 2.8228-.0647 5.1681 2.219 5.1643 5.0412-.0035 1.2096-.4365 2.3997-1.2478 3.3056-1.6143 1.6164-1.4006 3.6325-1.4006 3.6325 2.9478-1.0164 4.9394-3.788 4.9563-6.8974.035-4.0212-3.3897-7.4699-7.4138-7.3855C7.9575-.081 4.5377 3.3664 4.5717 7.3871c.0166 3.1093 2.0083 5.881 4.956 6.8974z"/></svg>
```

**Comment by dirien** [comment]
Looks really much better on the cog. Much smoother...


image

**Comment by dirien** [comment]
Hi @adamrusted, i update the Icon with your suggestions! 💪🏻

**Comment by adamrusted** [comment]
Hey @dirien, don't worry about merging develop into this branch, one of the team will worry about that when they review the PR. Unfortunately, because I had a hand in the creation of this path, we'll have to wait on another @simple-icons/maintainers to take a look at it.

**Comment by ericcornelissen** [comment]
I'm seeing [a hairline difference on the inner-left shape](https://user-images.githubusercontent.com/3742559/122130398-d65eeb00-ce37-11eb-9e5c-649ce19801a4.png) when comparing to [the SVG in the logos repository](https://github.com/cloudfoundry/logos/blob/1b658f73b4db8202c0732a07f4d944ac91259636/CF_Icon_4-colour.svg) (not sure if that's the source you used, @adamrusted) that I would say is unnecessary. Can you have a look at that?

**Comment by adamrusted** [comment]
Thanks for looking at this, @ericcornelissen. That hairline difference is due to the excessive amount of points found in the SVGs in the logo repo. When I worked on the path used, I tried to smooth as much out as possible, assuming the shapes were meant to be a bit simpler without those excess points. Happy to take another look to try and remove that hairline difference though, if you'd like?

**Comment by ericcornelissen** [comment]
Happy to run with it as is, it can be improved later if need be.

**Comment by ericcornelissen** [comment]
Thanks for working on this @dirien, it's much appreciated! And of course thanks @adamrusted for helping out as well.

**Comment by dirien** [comment]
Yes many thanks for @adamrusted to jump in 💯

**Pull request merged**
