### PR TITLE
Added Angular Universal icon

### PR DESCRIPTION
**Pull request by nexus0212**
**Issue:** #1345

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I picked color from official [Angular Universal logo](https://angular.io/generated/images/marketing/concept-icons/universal.svg) (brighter color on the left side) 

### **Trouble**
@SanderElias I have problem with icon URL.
I used offcial Angular website URL (it was used in issue description) https://angular.io/
I think it would be better to use GitHub repo/documentation URL https://github.com/angular/universal

### CODE REVIEW

**Comment by davidklebanoff** [comment]
@nexus0212 
Everything looks great and I agree with your color choice, it's consistent with the color we chose for the Angular icon (the left, bright side).

As for the source URL, I would use https://angular.io/presskit which is the official brand page and links to the official Universal icon. Once the source is updated I'll merge it in!

**Comment by nexus0212** [comment]
> As for the source URL, I would use https://angular.io/presskit which is the official brand page and links to the official Universal icon. Once the source is updated I'll merge it in!

@davidklebanoff 
I've updated the URL. I hope everything is okay.

**Comment by davidklebanoff** [comment]
Great job @nexus0212! Thanks for your contribution. 🎉

**Comment by ericcornelissen** [comment]
Just noticed the `<title>` is missing the word "icon", fixed in 265bdeacafbd99491eb9cbc5de8256e36b7310f0

**Pull request merged**
