### PR TITLE
Add Gutenberg icon (#1896)

### LINKED ISSUE #1896: Gutenberg
**Name:** Gutenberg
**Website:** https://github.com/WordPress/gutenberg
**Official resources for icon and color:**
https://github.com/WordPress/gutenberg/blob/9e523ceb3221d6eb89a9aa69e3f5db956a483f9d/docs/contributors/reference.md

gutenberg

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
Closes  #1896

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Sourced directly from their Github repo. Only color there is pure black.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @runxel thanks for working on this PR, the .svg is great 👍 

Can you please update the description to state the source you used and why you chose the hex value you did. ("see issue" doesn't help here)  [see comment](https://github.com/simple-icons/simple-icons/pull/2013#issuecomment-560008464)😄 

I think the json `"source"` should be (https://github.com/WordPress/gutenberg/blob/master/docs/final-g-wapuu-black.svg) rather than the .md file, can you update that please. Thanks 😸

**Comment by runxel** [comment]
Updated source and PR. :)

**Comment by phatbhoy67** [comment]
Thanks for taking care of this one @runxel 👍

**Comment by birjolaxew** [comment]
:+1: Looks good to me! Thanks for taking care of this one @runxel!

**Pull request merged**
