### PR TITLE
Added Digi-Key Electronics

### LINKED ISSUE #4328: Request: Digi-Key Electronics Icon
**Name:** Digi-Key Electronics
**Website:** https://www.digikey.com/
**Alexa rank:** 5,978
  

**Official resources for icon and color:** https://www.digikey.com/

### PR DESCRIPTION
**Pull request by adamrusted**
digi-keyelectronics

Fixes #4328
**Alexa rank:** [6,083](https://www.alexa.com/siteinfo/digikey.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG created from favicon and social media icon.
Colour used is `#CC0000` from the website.
Created in Adobe Illustrator.
Optimized with SVGO CLI.
Ran through SVGlint.

### CODE REVIEW

**Comment by fbernhart** [comment]
@adamrusted Great work! 💪🏼 But could you maybe remove these two col-linear points? After that we can merge it.

image

**Comment by adamrusted** [comment]
@fbernhart sorted 👌🏻

**Comment by fbernhart** [comment]
@adamrusted Perfect 👍🏼  Thanks

**Comment by hasthamalp** [comment]
great work perfect

**Pull request merged**
