### PR TITLE
Add Carto

### LINKED ISSUE #3075: Carto
**Name:** Carto
**Website:** https://carto.com
**Official resources for icon and color:** [Icon (printed positive version)](https://carto.com/downloads/CARTO-logo-solid-negative.zip) and color `#EB1510` from [brand guidelines](https://carto.com/brand/).
**Alexa Rank**: [~44k](https://www.alexa.com/siteinfo/carto.com)

### PR DESCRIPTION
**Pull request by mondeja**
carto

**Issue:** Closes #3075

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @mondeja.

Your path, however, is coming in at `23.989` wide - could you look into that, please?

**Comment by mondeja** [comment]
I've increased the precission of SVGO optimization, that I think it's was failing.

**Comment by PeterShaggyNoble** [comment]
Thanks for the quick update, @mondeja. But I'm seeing some differences between your version (in red below) and [the source file I'm using](https://carto.com/downloads/CARTO-logo-solid-positive.zip). Which version did you base your icon off, as I may not be comparing like with like?

**Comment by mondeja** [comment]
Seems that the file has been updated this morning. I was found that `Printed positive version` Carto website logo was downloading the negative version, and I was report this error to their developers team and this morning was changed:

>  May 25, 2020, 12:43:20 PM EDT
> Hello Álvaro,
> Our team informs us that the error in the main portal of CARTO (the switched logos) is now fixed, please check it out!

So I will update it again.

**Comment by PeterShaggyNoble** [comment]
Hang on, let me do a comparison with the negative version first; if it lines up then we can merge this in.

**Pull request merged**
