### PR TITLE
Adding Joplin icon

### PR DESCRIPTION
**Pull request by forsgren**
joplin

**Issue:**
**Alexa rank:** 93,178 
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Hex value picked from the center of the app icon gradient
- Source: https://github.com/laurent22/joplin/blob/45e35576bd8b1bb0ffe958309cc1ab3736cc266b/Assets/JoplinLetter.svg

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
Thanks for the contribution @forsgren.

Can you please link the issue and / or source for this logo so we can compare it to the contribution, please?

**Comment by forsgren** [comment]
> Thanks for the contribution @forsgren.
> 
> Can you please link the issue and / or source for this logo so we can compare it to the contribution, please?

Source: https://github.com/laurent22/joplin/blob/45e35576bd8b1bb0ffe958309cc1ab3736cc266b/Assets/JoplinLetter.svg (added it in the PR as well)

**Comment by jorgeamadosoria** [comment]
> > Thanks for the contribution @forsgren.
> > Can you please link the issue and / or source for this logo so we can compare it to the contribution, please?
> 
> @jorgeamadosoria: No issue exists. As I've understood that's not a requirement, have I misunderstood in some way?
> 
> The source is: https://github.com/laurent22/joplin/blob/45e35576bd8b1bb0ffe958309cc1ab3736cc266b/Assets/JoplinLetter.svg (added it in the PR as well)
> 
> Are source files supposed to be referenced in some additional ways apart from in `simple-icons.json`? Asking to make sure future PRs contain sufficient information :)

The issue is not mandatory, you didn't misunderstood. The source is enough. 
Source file should be in simple-icons, but it also should be specified in the ticket itself (the issue and / or pull request) for convenience more than anything. 
See, not every brand can have an specific github asset you can link as you did. Sometimes the source is taken from a website header, or a raster file inside a PDF, or something like that. In those cases the source link in simple-icons and the source link in the PR can be different. You just happened to be one of the cases where there is no difference :)

**Comment by jorgeamadosoria** [comment]
omparing with the source, I think this is very similar. LGTM.

**Pull request merged**
