### PR TITLE
Updated Google Chrome

### PR DESCRIPTION
**Pull request by adamrusted**
googlechrome

**Issue:** Contributes toward #4205
**Alexa rank:** N/A

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Source updated.
SVG rebuilt from source, with 0.35px gaps between colours.
Ran through SVGO CLI.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Managed to grab the white, monochrome AI from [this page](https://thepartnermarketinghub.withgoogle.com/brands/chromebook/visual-identity/visual-identity/logos-and-badges/) if you want to update based on that @adamrusted. I know it's for Chromebook rather than Chrome but the branding of the 2 seems to be identical.

[chromebook.zip](https://github.com/simple-icons/simple-icons/files/5830704/chromebook.zip)

**Comment by adamrusted** [comment]
@PeterShaggyNoble should be good to go now. Just pushed newer path.

**Review by PeterShaggyNoble — APPROVED** [review]
All looks perfect to me, @adamrusted :+1: ~The are a few excess points in the top left corner but everything I tried to do to get rid of them destroyed the circle so we may just have to run with them - I even tried drawing a new circle and intersecting the 2 shapes but that made things so much worse!~ **Update:** started from scratch and managed to get rid of them, see unoptimised path below.

Separately, as the source isn't _technically_ for Chrome, I'd like one of the other @simple-icons/maintainers to give the OK on it too.

```
M 12,0 C 8.2100345,0 4.8310909,1.7574532 2.6319245,4.5013323 L 6.585405,11.349076 C 6.9073595,8.6437582 9.2079545,6.5454545 12,6.5454545 H 22.691495 C 20.705264,2.6599882 16.66329,0 12,0 Z M 1.9314627,5.4699927 C 0.71009045,7.3493482 0,9.5916191 0,12 0,18.011806 4.4208041,22.991015 10.18892,23.86417 L 14.142134,17.017223 C 13.484452,17.298541 12.760636,17.454545 12,17.454545 9.9814091,17.454545 8.2203041,16.357227 7.2770768,14.727273 H 7.2762791 Z M 15.272727,7.6363636 C 16.597364,8.6315455 17.454545,10.215545 17.454545,12 17.454545,12.993273 17.18763,13.923447 16.723721,14.725675 L 16.724787,14.727273 16.72452,14.727806 H 16.723455 L 11.379173,23.98402 C 11.584759,23.994496 11.79181,24 12,24 18.627409,24 24,18.627409 24,12 24,10.460486 23.709757,8.98884 23.181552,7.6363636 Z M 16.363636,12 C 16.363636,14.409955 14.409955,16.363636 12,16.363636 9.5900455,16.363636 7.6363636,14.409955 7.6363636,12 7.6363636,9.5900455 9.5900455,7.6363636 12,7.6363636 14.409955,7.6363636 16.363636,9.5900455 16.363636,12
```

**Comment by adamrusted** [comment]
Rebuilt using your path @PeterShaggyNoble, and seems to work. Did need a precision of 4 for the circle in the centre to keep it's shape though.

**Comment by PeterShaggyNoble** [comment]
Why is always the simplest shapes and icons that cause us the most issues with precision?! 😆

Think I managed to get it down to 3:
```
M12 0C8.21 0 4.831 1.757 2.632 4.501l3.953 6.848A5.454 5.454 0 0 1 12 6.545h10.691A12 12 0 0 0 12 0zM1.931 5.47A11.943 11.943 0 0 0 0 12c0 6.012 4.42 10.991 10.189 11.864l3.953-6.847a5.45 5.45 0 0 1-6.865-2.29zm13.342 2.166a5.446 5.446 0 0 1 1.45 7.09l.002.001h-.002l-5.344 9.257c.206.01.413.016.621.016 6.627 0 12-5.373 12-12 0-1.54-.29-3.011-.818-4.364zM12 16.364a4.364 4.364 0 1 1 0-8.728 4.364 4.364 0 0 1 0 8.728Z
```

**Comment by adamrusted** [comment]
Your path matches up perfectly @PeterShaggyNoble, though I'll wait for another @simple-icons/maintainers to merge this.

**Review by service-paradis — APPROVED** [review]
LGTM 💯 
Good job @PeterShaggyNoble and @adamrusted

**Pull request merged**
