### PR TITLE
Update AlliedModders

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
AlliedModders

**Issue:** #1893
**Alexa rank:** [~63.4k](https://www.alexa.com/siteinfo/alliedmods.net)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon from [this SVG](https://forums.alliedmods.net/images/misc/am-banner.svg).

Possible alternative treatment:

### CODE REVIEW

**Comment by adamrusted** [comment]
Much though I like the alternative path you've provided - it does seem to look a bit confusing at the smaller shields.io sizes...

Will look to compare this one later today, hopefully get it merged.

**Comment by fbernhart** [comment]
Another alternative: Removing the stroke and just keeping the blue fill.

am-banner

**Comment by adamrusted** [comment]
I think if we were to do a 'filled' logo, we'd have to keep the stroke on there to maintain the rounded edges - otherwise I think it's a solid option @fbernhart. I think of the 3, that'd be my preferred option - purely for readability on a smaller scale.

**Comment by PeterShaggyNoble** [comment]
Including the stroke in the filled version doesn't work quite as well. Seeing as we have a few seemingly equally viable options, let's take it to a quick straw poll by giving a to 👍🏻
- [my first comment](https://github.com/simple-icons/simple-icons/pull/5107#issue-578587723) for the outlined version,
- [Adam's first comment](https://github.com/simple-icons/simple-icons/pull/5107#issuecomment-785821327) for the cut-out version
- [fbernhart's comment](https://github.com/simple-icons/simple-icons/pull/5107#issuecomment-787049057) for the filled version w/o the stroke
- this comment for the filled version w/ the stroke.

**Comment by mondeja** [comment]
Given that most of us have voted for the alternate version in the comment https://github.com/simple-icons/simple-icons/pull/5107#issuecomment-785821327, could you go with that @PeterShaggyNoble?

**Comment by PeterShaggyNoble** [comment]
Thanks, @mondeja - updated.

**Review by mondeja — APPROVED** [review]
It looks perfect :100: Thank you @PeterShaggyNoble :pray:

**Pull request merged**
