### PR TITLE
Add Vapor

### LINKED ISSUE #4444: Add Vapor icon
**Name:** vapor
**Website:** https://vapor.codes/
**Alexa rank:** 1.1 kTotal
  

**Official resources for icon and color:**
  
https://github.com/vapor

The vapor symbol
vapor

### PR DESCRIPTION
**Pull request by adamrusted**
vapor

**Issue:** Fixes #4444
**Alexa rank:** [588,008](https://www.alexa.com/siteinfo/vapor.codes)
**GitHub stars:** [20.1k](https://github.com/vapor/vapor)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Traced from PNG from scratch. Picked the grey / black as the most prominent colour on the website. Would prefer to go with `#E040FB` or `#3DC4FF`, but they're both used in equal measure so it makes it a difficult choice!

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
That looks pretty good to me, @adamrusted. Although, and this just might be down to my poor comparison skills, the top corner looks slightly off:
image

Of the 2 colours from the logo, I'd lean towards the pink but I don't think either are used with enough frequency to be considered the brand colour so one of the blacks is probably the best choice here.

**Comment by adamrusted** [comment]
> That looks pretty good to me, @adamrusted. Although, and this just might be down to my poor comparison skills, the top corner looks slightly off

Possibly? I thought I had it matched up pretty well, though happy to take another look if other @simple-icons/maintainers can also see an issue.

**Comment by service-paradis** [comment]
At first, I tried to compare with https://github.com/vapor/docs/blob/master/4.0/docs/assets/logo.png, but there was major differences.

Then, I compared with https://github.com/vapor/website/blob/master/src/assets/logo.png, and it is surely closer. I see the same difference as stated by @PeterShaggyNoble 
image

I wonder if we should get rid of the gap? When they use simplified versions of their logo, they use a solid color for the bottom part. Ass seen in their [doc](https://github.com/vapor/docs/blob/master/4.0/docs/assets/logo.png) and for the [favicon](https://github.com/vapor/website/blob/master/public/favicon.ico).

**Comment by adamrusted** [comment]
I did go with the block version in https://github.com/simple-icons/simple-icons/issues/4444#issuecomment-751512964 - though @PeterShaggyNoble wanted us to try and retain the layers.

**Comment by service-paradis** [comment]
> I did go with the block version in [#4444 (comment)](https://github.com/simple-icons/simple-icons/issues/4444#issuecomment-751512964) - though @PeterShaggyNoble wanted us to try and retain the layers.

Sorry, my bad, missed this comment. Tried to compare with https://docs.vapor.codes/4.0/assets/logo.png and I got this:
image

**Comment by adamrusted** [comment]
> > I did go with the block version in [#4444 (comment)](https://github.com/simple-icons/simple-icons/issues/4444#issuecomment-751512964) - though @PeterShaggyNoble wanted us to try and retain the layers.
> 
> Sorry, my bad, missed this comment. Tried to compare with [docs.vapor.codes/4.0/assets/logo.png](https://docs.vapor.codes/4.0/assets/logo.png) and I got this:
> image

Yeah, I didn't compare _this version_ of the icon against the docs version. Looks like yet another brand with differences across their icon suite 🙄

**Comment by PeterShaggyNoble** [comment]
> Looks like yet another brand with differences across their icon suite

In that case, given that it's such a small difference, let's run with this as-is and update if we can ever source a vector version.

For the record, my comparison was against [this file](https://vapor.codes/img/logo.7c12f228.png).

**Pull request merged**
