### PR TITLE
Add ESRI and ArcGIS icons

### LINKED ISSUE #8476: Request: ESRI and ArcGIS
### Brand Name

ESRI / ArcGIS

### Website

https://www.esri.com/en-us/arcgis/products/arcgis-pro/overview

### Popularity Metric

The ESRI / ArcGIS rank is 2,257. See [https://www.similarweb.com/website/arcgis.com/#overview](https://www.similarweb.com/website/arcgis.com/#overview)

### Official Resources for Icon and Color

svg: [https://www.esri.com/en-us/arcgis/products/arcgis-pro/overview](https://www.esri.com/en-us/arcgis/products/arcgis-pro/overview)
color: `#000000` and `#2C7AC3`, from the icons

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by geoyee**
esri

arcgis

**Issue:** closes #8476 

**Similarweb rank:**
  
Global Rank is [2,257](https://www.similarweb.com/website/arcgis.com/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Edited from the official SVG icons.

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @geoyee,

can you check the Arcgis:
image


and  ESRI

image

**Comment by geoyee** [comment]
> Hi @geoyee,
> 
> can you check the Arcgis: image
> 
> and ESRI
> 
> image

NP, i will update them

**Comment by geoyee** [comment]
@dirien i believe that these icons should be correctly. please review again, thank you 😄

**Review by dirien — APPROVED** [review]
Hi @geoyee,

Thanks for your contribution to simple-icons!

It's a perfect fit:
image

image

**Pull request merged**
