### PR TITLE
Add Hungry Jack's

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Hungry Jack's

**Issue:** Follow-up to #3443 & #4801
**Alexa rank:** [~120k](https://www.alexa.com/siteinfo/hungryjacks.com.au)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon from [SVG](https://www.hungryjacks.com.au/App_Themes/HJ/assets/images/HJLogo.svg) in website header - it looks like they use the boxed version consistently across their website & packaging. I went with the more vibrant red from their website stylesheet for the colour rather than the one used in the source SVG.

### CODE REVIEW

**Comment by adamrusted** [comment]
Do we need to keep the ® being as it's in both shown versions of the logo?

**Comment by NovaGL** [comment]
I wouldn't remove the registered sign I think that's a requirement for logos with registered trademarks.

**Comment by PeterShaggyNoble** [comment]
Our stance on symbols is:
1. If there is a explicit requirement to include it then we include it, regardless of the symbol.
2. If there is a requirement to include except under specific circumstances then we base our decision on whether our usage falls within those circumstances.
3. If there is a requirement to include except under specific circumstances but it's unclear or ambiguous whether our usage falls within those circumstances then we include it if it's a registered trademark symbol but omit it otherwise.
4. If there is nothing stated anywhere regarding its inclusion then we omit it, regardless of the symbol.

So, unless we can find some guidelines covering its inclusion, I think we're safe to omit it here under point 4 above.

**Comment by adamrusted** [comment]
As @PeterShaggyNoble mentioned above, given there isn't an official trademark document readily available for Hungry Jack's - I'm _happier_ to look at merging this one without the ® for now - though I would note that even the tiny icons on their [voucher books](https://www.hungryjacks.com.au/Upload/HJ/Media/HJ00428_National_Voucher_December_WEB.pdf), they include the ® symbol. If the other @simple-icons/maintainers could weigh in on this, that'd be great.

**Comment by PeterShaggyNoble** [comment]
Just realised: We did decide a while back that it the symbol is integrated into the logo/icon, as it was in the old Intel icon and in the Chupa Chups icon, then we should _include_ it if we're not explicitly allowed to omit it. The fact that they themselves include it when displaying the logo a small sizes would also lead me to believe we need to keep it. Will get this PR updated later today.

**Comment by PeterShaggyNoble** [comment]
Updated.

**Review by adamrusted — APPROVED** [review]
Looks good to me! Thanks @PeterShaggyNoble 🍔

**Pull request merged**
