### PR TITLE
Added Crunchbase icon

### PR DESCRIPTION
**Pull request by hylickipiotr**
**Issue:** #1430 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

Accoring to @birjolaxew  comment in issue #1430, I've got 'c' and 'b' letter from logo and I've possitioned using logo from [Crunchbase Linkedin avatar](https://www.linkedin.com/company/crunchbase/). The color was picked maually from [Crunchbase Linkedin avatar](https://www.linkedin.com/company/crunchbase/) `#0087D2`.

It is not official site with the Crunchbase logo, so I set the value to Crunchbase homepage.

### CODE REVIEW

**Comment by davidklebanoff** [comment]
I would change the color to `#0288d1`, which I extracted from the css on the official website. It's listed as the "primary" color and used in their header and links among other elements. In the absence of an official brand guide, I think it's the most accurate.

Extracting colors from rasterized files like PNGs or JPGs is not ideal as the colors often change when the images are generated.

Other than the small color change, everything looks great!

**Comment by hylickipiotr** [comment]
In the first commit I've extracted the color from the header, but I thought I better option is to pick the color from the PNG file. I will revert the commit.

**Comment by ericcornelissen** [comment]
I'd like to propose to change the icon to be in the same stile as [LinkedIn](https://simpleicons.org/?q=linkedin). This, I believe, more accurately reflects their favicon, as well as the icon in their footer.

> I thought I better option is to pick the color from the PNG file.

It is generally a bad idea to pick a color from a rasterized image (such as PNG or JPG) because they usually have inaccurate colors due to compression.

**Comment by davidklebanoff** [comment]
@ericcornelissen That works too.

In fact, upon further inspection, the favicon is also shown in the footer of the [Crunchbase website](https://www.crunchbase.com/). Rounded corners and all. Perhaps that should have been used all along? It also shares the same color as the header, `#0288D1`.

**Comment by hylickipiotr** [comment]
@ericcornelissen your consideration is better. I agree to use logo icon from the [Crunchbase website](https://www.crunchbase.com/) footer, but I think we need to know @birjolaxew opinion, because, he suggested to take letters from the logo.

**Comment by birjolaxew** [comment]
@hylickipiotr I somehow missed the favicon SVG in their footer - that one would be much preferred to cobbling something together ourselves :P

**Comment by hylickipiotr** [comment]
I updated Crunchbase icon. Now the SVG is the same as in the [Crunchbase website](https://www.crunchbase.com/) footer.

**Comment by ericcornelissen** [comment]
Thanks once again @hylickipiotr :tada:

**Pull request merged**
