### PR TITLE
update Google Drive icon

### PR DESCRIPTION
**Pull request by jorgeamadosoria**
googledrive

**Issue:** #4205

### CODE REVIEW

**Comment by service-paradis** [comment]
Which source did you use for this?
The new Google Drive icon looks like this:
image

**Comment by jorgeamadosoria** [comment]
> Which source did you use for this? The new Google Drive icon looks like this: image

they have a dedicated monochrome icon: 
https://developers.google.com/drive/api/v3/branding

**Review by dirien — CHANGES_REQUESTED** [review]
hi @jorgeamadosoria,

can you have a look again? I cant get a perfect fit on the left icon part
image

**Comment by jorgeamadosoria** [comment]
@dirien 
image

I get 100% match. 
I took the PNG and convert it to PNG to use as base and comparison, so that comparison is SVG without optimization vs SVG optimized.

What are you comparing against?

**Pull request merged**
