### PR TITLE
Add ReactiveX icon

### PR DESCRIPTION
**Pull request by thmsgbrt**
reactivex

**Issue:**
**Alexa rank:** ~130k

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Issue: #3354 

I'm getting this error: 
> x icons/reactivex.svg
>   x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 23.919 x 23.581
>   x icon-centered <path> must be centered at (12, 12); the center is currently (11.959, 11.913)

I can't manage to get it right, for some reason...

### CODE REVIEW

**Comment by NovaGL** [comment]
Thanks for this @thmsgbrt 

Can you please check the SVG as it's not centred and it is not 24 in one dimension.

**Comment by thmsgbrt** [comment]
Hey!

Screenshot 2020-08-04 at 14 54 58

Honestly, it's been hours I'm trying to have it 24 wide. It looks goods in my AI file, I export the SVG's path and then I still have the error mentioned above.

Your script is working but for some reason, I can't make it 24 wide in the code, neither be centered.

Screenshot 2020-08-04 at 14 57 16

I've no idea what more I can do.

**Comment by vanessafsoares** [comment]
@thmsgbrt I have the same problem as yours.

@NovaGL Could you help us?

**Comment by sharmavins23** [comment]
I would love to say that I found some extremely useful solution, but I didn't. What ended up working for me was recreating the icon in Inkscape.

**Steps**
1. I took your SVG, rasterized it to a PNG using https://webkul.github.io/myscale/
2. In Inkscape, I created an SVG automatically out of it https://logosbynick.com/inkscape-convert-png-to-svg/
3. I then resized the content SVG to the proper size http://inkscape.13.x6.nabble.com/Resize-Content-to-Page-td2863938.html

Here's the resulting code, already linted and optimized with SVGOMG:
https://gist.github.com/sharmavins23/6b1add95a083e406e8a4b06c11466e3c

Sorry this didn't help much with the original problem @thmsgbrt @vanessafsoares but that's how I solved it.

**Comment by thmsgbrt** [comment]
Hi @sharmavins23,

I don't know what was wrong with the original SVG...
Thanks for your solution and your help, awesome!

Here is the updated preview:
simpleicons

**Comment by NovaGL** [comment]
Sorry but this logo does not match the original SVG. Generally I would advise against converting a SVG to PNG and back again.
image

**Comment by thmsgbrt** [comment]
So, I can update my PR with the path you are suggesting @NovaGL ?

**Comment by NovaGL** [comment]
My path is unoptimised you will need to run it through SVGOMG

**Comment by thmsgbrt** [comment]
Ok. I'll give it a try as soon as I have the time, thanks!

**Comment by thmsgbrt** [comment]
Hi guys, I'm sorry. I believe this should be simple but I can't manage to make it valid. I spent numerous hours on this and I'm running out of ideas...

I tried to run your path through SVGO and I have the same error, in the end.

**Comment by vanessafsoares** [comment]
@thmsgbrt In Illustrator I make a compound path. But usually open in Inkscape after to fix the sizing as Illustrator is not very good with SVG sizing.

**Comment by thmsgbrt** [comment]
reactivex


Thanks @vanessafsoares, it seems correct now

**Comment by thmsgbrt** [comment]
Hey @NovaGL, does it look correct to you now?

**Review by NovaGL — APPROVED** [review]
Looks good to me.

**Comment by runxel** [comment]
Merging this in, thanks for all the effort it took! 💯 

---

FWIW: I also encountered this many times... Illustrator just doesn't seem to be very precise in general. (Or in other words: Illustrator is not _that_ imprecise, the developers just decided to _fake_ precision to you in a way, where they aggressively apply rounding to the numbers they display for you. So having a `12px` somewhere _could_ mean, it is precisely 12 px, but most times it is in fact more like `12.0284px`. I assume more people were freaked out by that and the other way around...)
However it also depends on your initial export of the SVG. I think I mostly use `SVG Tiny 1.2` (seemed to work best in a quick test) as base format and always use 7 decimal places (the maximum). SVGO takes care of this, so there is no point in reducing it already there.
The next thing I encountered is the circumstance how you _make_ your paths. As you know, we want to be everything living in one single `<path>` element. This goes by the term "compound path" in Illustrator.
SVGO is able to make a compound path on its own. So sometimes it yields better results to let SVGO do its magic, then already make the compound path in Illustrator.
I always run the linter after I ran SVGO, and having a copy of the originial pre-svgo'ed svg surely helps as well.

**Pull request merged**
