### PR TITLE
Add Habr icon

### PR DESCRIPTION
**Pull request by phatbhoy67**
**Issue: #1280 **

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Resized the [favicon .svg](https://habr.com/images/safari-pinned-tab.svg) from the [habr website](https://habr.com/).

Hex value `#77A2B6` is the specified colour for the background of the favicon.

Built on GitPod, working as expected.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Hmm :thinking: I'm actually not sure if we should go with the "h" given that their logo [in the App Store](https://apps.apple.com/us/app/habr/id778613673) is something different. I would like to know the opinion of a user before we continue :sweat_smile: @sh7dm do you have any insight?

That said, if we decide to use the "h" as it appears in the favicon I would say it should be inside a square.

**Comment by phatbhoy67** [comment]
habr-options

Hey @ericcornelissen @sh7dm visual of options mentioned above. 

A: [favicon](https://habr.com/images/apple-touch-icon.png) in box
B: bitmap trace of the [icon](https://habr.com/images/habr.png)

**Comment by sh7dm** [comment]
I pick :a:, since it's an official logo used everywhere. I've seen :b: only in Play Market & AppStore

**Comment by ericcornelissen** [comment]
> I pick 🅰️, since it's an official logo used everywhere. I've seen 🅱️ only in Play Market & AppStore

In that case my vote goes to 🅰️ as well, can you update that @phatbhoy67?

**Comment by phatbhoy67** [comment]
Updated now @ericcornelissen ✔️

**Comment by ericcornelissen** [comment]
Thanks for the contribution @phatbhoy67 and thanks for the feedback @sh7dm 😄

**Pull request merged**
