### PR TITLE
Add Sequelize

### LINKED ISSUE #3334: Sequelize
**Name:** Sequelize
**Website:** [sequelize.org](https://sequelize.org/)
**Alexa rank:** 31,280
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by adamrusted**
sequelize

**Issue:** Closes #3334
**Alexa rank:** [31,369](https://www.alexa.com/siteinfo/sequelize.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Generated from SVG in https://github.com/sequelize/sequelize/pull/12871, using gap of 0.35px between blocks.
Main color picked from top of blocks.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
There are a few minor differences between your version (in red) and the source, @adamrusted but I wonder if we shouldn't hold off on this one until sequelize/sequelize#12871 is merged making it official, giving us a commit URL to use as the source and in case there are any further changes to it in that PR?

**Comment by adamrusted** [comment]
Given this another go, tracing round each shape individually and removing any inconsistencies (see outside of the larger shapes), so the current version is just a lot _cleaner_ than the source file. Still no sign of it being merged into the main project on their end yet, so for the time being shall we continue with the source as-is, and I'm happy to update it at a later date once it's merged / edited.

**Comment by PeterShaggyNoble** [comment]
Yeah, let's go for it; we can update the source, at least, when the PR over there _does_ get merged.

I'm still seeing a few small differences in the cubes (e.g., [the centre cube](https://user-images.githubusercontent.com/15157491/114748570-f72c9680-9d49-11eb-94ed-ac8606c937c1.png)), unforunately.

Took a stab at it myself 'cause it looked like a fun challenge and ended up with the path below. Like you, I tried to fix up the imperfections in the outer cube which I did by deleting the 2 bottom parts, flipping a copy of the top part to the bottom and the filling in the blanks giving better symmetry. Dunno if that was the right option, though, and I shouldn't have just dragged the node in the bottom parts to meet the nodes on the top part.

```
M 12.027344 0 L 1.5957031 5.9921875 L 1.5957031 18.007812 L 12.027344 24 L 22.40625 18.007812 L 22.40625 5.9921875 L 12.027344 0 z M 12 3.484375 L 19.429688 7.7109375 L 19.429688 16.289062 L 12 20.515625 L 4.6523438 16.333984 L 4.5722656 7.7109375 L 12 3.484375 z M 12.048828 4.0742188 C 11.072292 4.6369101 10.096888 5.201628 9.1210938 5.765625 L 9.1210938 6.0195312 L 11.728516 7.5429688 L 11.728516 8.0253906 C 11.864015 7.9473345 11.990138 7.874259 12.130859 7.7929688 L 12.386719 7.9433594 L 12.386719 7.6074219 C 13.271142 7.1006022 14.194004 6.5661803 14.955078 6.1269531 C 14.958623 6.0037762 14.957732 5.8735062 14.958984 5.7539062 C 13.98879 5.1942558 13.018816 4.6342252 12.048828 4.0742188 z M 8.3359375 6.1386719 C 7.3654251 6.6916932 6.4047549 7.2614557 5.4433594 7.8300781 L 5.4433594 11.232422 C 6.4083375 11.787702 7.3720837 12.345116 8.3359375 12.902344 L 8.7382812 12.669922 L 8.7382812 9.7539062 C 9.5943572 9.2593562 10.490502 8.7412817 11.228516 8.3144531 L 11.228516 7.8300781 L 8.3359375 6.1386719 z M 15.779297 6.2265625 C 14.815085 6.7831691 13.850903 7.3398286 12.886719 7.8964844 L 12.886719 8.234375 L 15.523438 9.7753906 L 15.523438 12.841797 C 15.608795 12.891148 15.693936 12.940885 15.779297 12.990234 L 18.671875 11.320312 L 18.671875 7.9179688 L 15.779297 6.2265625 z M 12.130859 8.3710938 C 11.167278 8.9294439 10.202747 9.4861496 9.2382812 10.042969 L 9.2382812 13.466797 C 10.203259 14.022078 11.167005 14.579491 12.130859 15.136719 L 15.023438 13.464844 L 15.023438 10.0625 L 12.130859 8.3710938 z M 5.9335938 12.09375 C 5.7708626 12.189969 5.6060802 12.282664 5.4433594 12.378906 L 5.4433594 15.78125 C 6.4076844 16.338313 7.3718019 16.895734 8.3359375 17.453125 L 8.7382812 17.220703 L 8.7382812 14.302734 C 8.9007942 14.208829 9.0468567 14.124051 9.2109375 14.029297 C 9.047991 13.934839 8.9062358 13.853023 8.7382812 13.755859 L 8.7382812 13.248047 L 8.3359375 13.480469 C 7.5109061 13.003361 6.6457305 12.504478 5.9335938 12.09375 z M 18.181641 12.179688 L 15.779297 13.568359 C 15.69131 13.517477 15.612091 13.47117 15.523438 13.419922 L 15.523438 13.753906 L 15.03125 14.039062 L 15.523438 14.326172 L 15.523438 17.392578 C 15.608795 17.441928 15.693936 17.491666 15.779297 17.541016 L 18.671875 15.869141 L 18.671875 12.466797 L 18.181641 12.179688 z M 9.7128906 14.318359 C 9.5547698 14.409648 9.3964021 14.500509 9.2382812 14.591797 L 9.2382812 18.015625 C 10.202001 18.573085 11.166462 19.12926 12.130859 19.685547 L 15.023438 18.015625 L 15.023438 14.613281 L 14.533203 14.326172 L 12.130859 15.714844 C 11.300292 15.234531 10.429656 14.732019 9.7128906 14.318359Z
```

**Comment by adamrusted** [comment]
I'm in the process of manually rebuilding this, using the hexagonal shape created by the inner elements combined as a guide for the outline. There's a fair bit of a difference, but given how the original SVG in that PR is, I think we can get away with it. Will upload it here once it's done, and may be worth pinging their contributors for input.

**Comment by adamrusted** [comment]
sequelize

@PeterShaggyNoble this one was created by manually tracing the inner cubes with hexagons, and then using the 'outer hexagon' of those shapes combined to generate the outline. I think the majority of our issue has been that the outline shape doesn't really match up nicely - so I've tried to use the shapes already in the icon to tidy the outer ring into something more uniform. As mentioned above, it may be worth talking to the Sequelize maintainers and seeing if this version is okay. I'll ping their PR shortly.

**Comment by PeterShaggyNoble** [comment]
OK, let's see what they see before we proceed further.

**Comment by adamrusted** [comment]
Given the lack of activity on their end, should we proceed with reviewing this one?

**Comment by PeterShaggyNoble** [comment]
Not sure what's going on here, @adamrusted 🤔 Are the differences below intentional? ([vs. my version, for comparison](https://user-images.githubusercontent.com/15157491/118691374-ee275d00-b800-11eb-9618-92b18e77ccd8.png))

**Comment by adamrusted** [comment]
I've updated this using @PeterShaggyNoble's path. Could another @simple-icons/maintainers take a look at this?

**Review by ericcornelissen — APPROVED** [review]
Provided everyone is okay with fixing up [the inconsistencies](https://user-images.githubusercontent.com/3742559/119271045-07187f80-bc00-11eb-8541-28c4059d59f6.png) in the upstream version of [4b0ce1031badb15943445ee458691dfe0b672a09](https://github.com/sequelize/sequelize/pull/12871/commits/4b0ce1031badb15943445ee458691dfe0b672a09) this looks good to me 👍

**Comment by PeterShaggyNoble** [comment]
Gonna go ahead and merge this in based on Eric's approval above to get it off our plate; we can always review it once their PR gets merged or if there are any further changes to it.

**Comment by WikiRik** [comment]
Hi @PeterShaggyNoble @adamrusted 
Just came across this repository and was happy to see the inclusion of Sequelize. Since this PR has been merged we have brought new life to Sequelize and merged a PR for the official logo, it's https://github.com/sequelize/sequelize/pull/13628
Not sure if this aligns with the merged PR and I'm not knowledgeable on this matter so it would be nice if one of you two could check if out and make another PR here if it does not match.
Thanks again for the work on this repository!

**Pull request merged**
