### PR TITLE
Add Pastebin icon (#1557)

### PR DESCRIPTION
**Pull request by phatbhoy67**
**Issue: #1557**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with ~SVGO or~ SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Manually converted [official .png](https://pastebin.com/i/facebook.png) available in source of their [website](https://pastebin.com/) to vector.

Main website header colour is a linear gradient: `#023859` to `#02456C` with a [calculated midpoint](https://meyerweb.com/eric/tools/color-blend/#023859:02456C:1:hex) of `#023F63` which was my initial suggestion for the hex value to use.

However, on smaller screens, the menu dropdown background colour is `#02456C` and on hover is `#023859`, which suggests that the dominant colour might be `#02456C`, which is the hex value I've used.

### CODE REVIEW

**Comment by foo-dogsquared** [comment]
This PR looks pretty neat to me. 
Nice job on looking through this issue, @phatbhoy67 ! 

I agree on the color of your choosing. 
Choosing the midpoint seems to be safest bet. 
Judging from their social media accounts (i.e., [Twitter](https://twitter.com/Pastebin)) and their [Open Graph image](https://pastebin.com/i/facebook.png), they seem to be using the (similar) color a lot. 

I approve of this PR. 
Though, I'll have to know the opinion from other @simple-icons/maintainers.

**Comment by ericcornelissen** [comment]
The corners of the SVG look a little bit awkward as illustrated in the image below. This might be due to compression, if you still have a version with higher precision that would be great @phatbhoy67. But to be fair, to some extend it might just be remnant of the PNG version being not very high resolution. 

@birjolaxew what do you think?

svg preview

**Comment by phatbhoy67** [comment]
Hey @ericcornelissen I've now drawn the surrounding rounded square manually (original was done with potrace) and cut the "bent back corner" piece back in. Attached the .svg in .zip to make it easier for you to compare.
pastebin-corner-fix
[pastebin-corner-fix.zip](https://github.com/simple-icons/simple-icons/files/3827203/pastebin-corner-fix.zip)

**Comment by ericcornelissen** [comment]
That looks good @phatbhoy67 👍 Could you update the PR to use that version?

**Comment by ericcornelissen** [comment]
Thanks for your work on this @phatbhoy67, good job on the final vectorization! Work on issues like this (where there is no vector version available) is very valuable 😄

**Pull request merged**
