### PR TITLE
Add easyJet

### PR DESCRIPTION
**Pull request by runxel**
**Issue:** #2587

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
There was sadly no svg to be found, neither on their website nor Wikipedia.
However it was easy to recreate, since the wordmark is set in [Cooper Black](https://fontsinuse.com/uses/16586/easyjet). The kerning was adjusted to fit to a higher resolution picture of the logo.
The color `#FF751A` was lifted from the website's css.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I extracted the wordmark from page 14 of [this PDF](https://easy.com/wp/wp-content/uploads/2018/10/easyGroup_Brand_Manual-1.pdf) and converted it to a path and your version (in read) doesn't _quite_ line up. From page 18 ofhat PDF, as well, there are a couple more choices for the colour:
- `#fe5000` from converting the Pantone
- `#ff5700` from converting the CMYK
- `#ff6600`

easyJet

**Comment by runxel** [comment]
Hey @PeterShaggyNoble. thanks for joining in here!
The link to the brand guide is great, I saw it referenced mutliple times but the links were all dead; nice to see you've found it!

However, please do your comparison with the _actual_ logo from the website – you will see that indeed the kerning in the PDF is wrong (it was just set in Cooper Black with no additional kerning done on it).

I'm fine with either of those colors, we just need to agree on one. :D

**Comment by PeterShaggyNoble** [comment]
Ah, I _completely_ misread your initial comment, don't know what I think you meant now! Sorry 'bout that.

From past experience, you're much better at comparisons between vector and raster than I so I'll defer to you there, pending a review from one of the other @simple-icons/maintainers, of course.

On the colour: I'd vote `#ff6600` as it's provided twice in the brand guidelines. But I also think that your initial choice is an acceptable alternative given that it's also sources from easyJet, if that's the consensus.

**Comment by runxel** [comment]
`#ff6600` it is, then!

We could link to `https://easy.com/` ? 
I mean, that's the parent page. I am not sure if we should link against the document itself. Pretty sure @PeterShaggyNoble would be concerned of link rot, and actually I am as well in this case.
(Given that this just a basic wordpress link it doesn't really look persistent enough)

**Comment by ericcornelissen** [comment]
@runxel I think the easyJet website is better than the easy website. I agree that link rot is a potential problem, and linking the PDF itself is not ideal in any case. The main reason I asked for suggestions is because you said earlier:

> The link to the brand guide is great, I saw it referenced multiple times but the links were all dead; nice to see you've found it!

So I was wondering if any of the pages where you saw it referenced could be used as a source. If not, then I think this is fine as is.

<sup>at least we have a reference to the brand guidelines in this discussion...</sup>

**Comment by runxel** [comment]
> > The link to the brand guide is great, I saw it referenced multiple times but the links were all dead; nice to see you've found it!
> 
> So I was wondering if any of the pages where you saw it referenced could be used as a source. If not, then I think this is fine as is.

Ah, got it, sorry!
Funnily enough, the links were all on _unrelated_ websites (like from `fontsinuse.com` and therelike).
So yes, best is to stay on easyjet.com, like it was already.

**Comment by PeterShaggyNoble** [comment]
All looks good to me 😃

**Pull request merged**
