### PR TITLE
Add Southwest Airlines

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Southwest Airlines

**Issue:** #2587

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Colour from [main website's](https://www.southwest.com/) stylesheet - the SVG logo there is just a wrapper for a PNG! :man_facepalming:

Possible alternative:
Southwest Airlines

### CODE REVIEW

**Comment by adamrusted** [comment]
There is an [SVG on the homepage](https://www.southwest.com/swa-resources/images/globalnav/logos/swa_logo_dark.svg), buried underneath the image logo.
Might it be worth updating the source to the homepage on this one? Also think I'd prefer the block-colour logo to the line-art one - but will leave it for other @simple-icons/maintainers to chip in too.

**Comment by fbernhart** [comment]
>  Also think I'd prefer the block-colour logo to the line-art one

Agree 👍🏼

**Comment by PeterShaggyNoble** [comment]
Source updated.

**Comment by runxel** [comment]
We now ending the embargo on airline logos?

**Comment by PeterShaggyNoble** [comment]
This one pre-dated the embargo, @runxel 😉

**Comment by runxel** [comment]
Oh, I'm sorry 🙈😂
Reading would help....

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @PeterShaggyNoble ✈

**Pull request merged**
