### PR TITLE
Add Kamailio

### PR DESCRIPTION
**Pull request by ishvaram**
Added kamailio icon

### CODE REVIEW

**Comment by fbernhart** [comment]
@ishvaram Thanks for your contribution so far. Unfortunately there are some issues with your pull request that need to be fixed:

1.  Could you please provide the needed information from the pull request template and include it into your initial post?


    > Before opening your pull request, have a quick look at our contribution guidelines:
    > https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md
    > 
    > Consider adding a preview image of your submission using:
    > https://petershaggynoble.github.io/MDI-Sandbox/simpleicons/preview/
    > 
    > **Issue:**
    > **Alexa rank:**
    >        The Alexa rank can be retrieved at https://www.alexa.com/siteinfo/
    >        Please see our contributing guidelines for more details on how we
    >        assess a brand's popularity. 
    > 
    > ### Checklist
    >   - [ ] I updated the JSON data in `_data/simple-icons.json`
    >   - [ ] I optimized the icon with SVGO or SVGOMG
    >   - [ ] The SVG `viewbox` is `0 0 24 24`
    > 
    > ### Description
    > Anything relevant, for example:
    >   - Why did you pick the hex value?
    >   - Did you manually vectorize the logo?
    >   - Have you used multiple sources?
    >   - etc.
    > 
    > 


2. It would be nice if you could as well include a preview image of your pull request, using https://petershaggynoble.github.io/MDI-Sandbox/simpleicons/preview/

3. It looks like the SVG you've provided hasn't been optimized with either SVGOMG or SVGO. If you haven't already, please have a look at our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon).

4. I assume you've used the SVG from Wikipedia. At Simple Icons we prefer to use official SVGs (from the brand's website) and only use Wikipedia, if there is no other option. I've found a vectorized version of the Kamailio logo here:

https://www.kamailio.org/pub/kamailio-logos/current

You can either use the `kamailio-logo.eps` file or the `kamailio-logo.ai` file to produce the SVG. Please as well use the provided link above as `source` attribute instead of Wikipedia.

5. Looking at their website https://www.kamailio.org I would assume that their primary brand color is green and not white. So I would be in favor of changing the color to the green from the logo, but if someone else has a better idea, let me know.

**Comment by adamrusted** [comment]
To throw an additional spanner in the works - the `o` at the end of the icon is a mess of points. Unfortunately though, it's not a perfect circle shape - so we may need to stick with it.

[See circle (matched to edges) in yellow](https://user-images.githubusercontent.com/1830867/108504763-515f2d00-72ae-11eb-92ff-ac929cfbac56.png)

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @ishvaram?

**Comment by adamrusted** [comment]
Closing as abandoned, as no response from @ishvaram in over 20 days. Feel free to reopen if you'd like to continue your contribution.

**Pull request closed without merging**
