### PR TITLE
Add Kitsu icon

### LINKED ISSUE #3355: Add Kitsu icon
**Name:** Kitsu
**Website:** https://kitsu.io
**Alexa rank:** ~160000 (https://www.alexa.com/siteinfo/kitsu.io)

**Official resources for icon and color:**
https://www.behance.net/gallery/51546457/Kitsu-Brand-Identity-Design

### PR DESCRIPTION
**Pull request by crse**
kitsu

**Issue:** Closes #3355
**Alexa rank:** ~160.000

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I use the vector logo provided by the dev via Slack, more info of branding https://www.behance.net/gallery/51546457/Kitsu-Brand-Identity-Design

### CODE REVIEW

**Comment by NovaGL** [comment]
Hi @crse 

Thanks for contributing this. Can you please look into the following as it has failed our checks

The icon size isn't correct it's currently 20.681 x 23.143 it needs to be 24 x 24
The icon isn't centered on the canvas

**Comment by crse** [comment]
It should be fixed right now :)

**Comment by PeterShaggyNoble** [comment]
@crse, could you provide us with the original vector file their devs supplied you with, please, so we can do a direct comparison? Thanks for reaching out to them, by the way, much appreciated.

**Comment by crse** [comment]
@PeterShaggyNoble Here's the logo
https://www.dropbox.com/s/dv8abnb3yru9ihp/kitsu.svg?dl=0

**Comment by PeterShaggyNoble** [comment]
Thanks, @crse - your SVG looks perfect when compared to the original. However there are a number of imperfections in the original (see top-left of left ear below, for example) - could you look into cleaning those up? Not the end of the world, if you can't.

And, from the source URL you provided, the colour should be `#fd8320` - although, from the SVG they supplied you with and from their website, there's also `#f75239`, which makes me wonder if those brand guidelines aren't outdated.

I also think we should use https://kitsu.io/ as the source URL as has an SVG of the logo in the header and would be a better place for future reviewers to start looking for an updated logo.

**Comment by adamrusted** [comment]
Marking this as abandoned, being as the last comment was at the end of July. I've opened #4520 as a replacement to this.

**Pull request closed without merging**
