### PR TITLE
Update r

### LINKED ISSUE #5282: Update R icon?
I wanted to take a look at the letters `R` for #5251. The first one is [`R`](https://www.r-project.org/logo/). I though it would look a little bit better with gaps. What do other @simple-icons/maintainers think?

**Brand Name:** R
**Official resources for icon and color:**
  

#### Current treatment
image

#### Proposal
image

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** Close #5282
**Alexa rank:** [~9k](https://www.alexa.com/siteinfo/r-project.org)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I took the SVG logo from https://www.r-project.org/logo/
- I used Inkscape to scale and add gaps
- I optimized it

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Looks like the cut-outs have introduced some distortion in the ellipse, @service-paradis, such as [this one in the middle](https://user-images.githubusercontent.com/15157491/111310629-35ed0500-8655-11eb-89bf-10df271c5ee6.png). You might be able to fix them easily enough by dragging the points in yours to meet the curve of the original.

**Comment by service-paradis** [comment]
Sorry, I miss this one. It should be better now!

**Review by adamrusted — CHANGES_REQUESTED** [review]
I'm seeing a difference still on the inside of the `R` (see [here](https://user-images.githubusercontent.com/1830867/112755879-91ff4400-8fda-11eb-9e84-40d71a8dc946.png)). Would you mind taking a quick look on your end @service-paradis?

**Comment by service-paradis** [comment]
> I'm seeing a difference still on the inside of the `R` (see [here](https://user-images.githubusercontent.com/1830867/112755879-91ff4400-8fda-11eb-9e84-40d71a8dc946.png)). Would you mind taking a quick look on your end @service-paradis?

Using Inkscape with [this logo](https://www.r-project.org/logo/Rlogo.svg) as reference, I do not see the same differences:
image

**Comment by adamrusted** [comment]
Weird. I've pulled both your PR version and the SVG from their site fresh, and they're still showing those differences in 
[Affinity](https://user-images.githubusercontent.com/1830867/114306215-1cfc3600-9ad3-11eb-86ad-9876f761199c.png) and also [Inkscape](https://user-images.githubusercontent.com/1830867/114306276-5339b580-9ad3-11eb-872e-610cb2f61e67.png). Could another @simple-icons/maintainers verify this one?

**Comment by ericcornelissen** [comment]
I can confirm that I'm also still seeing some differences in the ellipse in Illustrator, though I must add that I have to run `npm run svgo -- ./icons/r.svg` before I'm able to view the SVG in Illustrator (see #2061). @adamrusted do you do the same? @service-paradis are you able to do a comparison after local optimization of the SVG? @PeterShaggyNoble perhaps you can look at the new SVG again?

**Comment by service-paradis** [comment]
This is what I get comparing the SVG from https://www.r-project.org/logo/ and the latest SVG from this PR:
image

I think I will just try this on from scratch again since we're not seeing the same 😅

**Comment by service-paradis** [comment]
Started this one from scratch again 😅 
Looking good in Inkscape for me, hop it is for you 😄 
image

**Review by PeterShaggyNoble — APPROVED** [review]
Looks perfect now, @service-paradis, nice work 👍🏻

**Pull request merged**
