### PR TITLE
Remove Stitcher icon

### LINKED ISSUE #11662: Removal: Stitcher
### Brand Name

Stitcher

### Reason for Removal

The Stitcher app and website was shut down on August 29, 2023. It is recommended that we remove this icon from our collection.

More information can be found here: https://www.cbsnews.com/news/podcasting-app-stitcher-shuts-down-sirius-xm/

### PR DESCRIPTION
**Pull request by oyezaheer**
Fixes #11662

This PR Removes the Stitcher icon.

### CODE REVIEW

**Comment by CodeShakingSheep** [comment]
Hi @oyezaheer ,
you also need to remove the icon itself. See https://github.com/simple-icons/simple-icons/blob/develop/icons/stitcher.svg
And please also mark this PR as draft as icon removals are only planned for major releases (next one will be in October as far as I know).

**Comment by uncenter** [comment]
Why open a new pull request? You can add the changes here and mark it as a draft without creating a new one.

**Comment by oyezaheer** [comment]
I initially decided to delete and create a new PR to keep the changes organized and ensure a clean commit history. However, I'll keep in mind the option to use draft pull requests in the future to streamline the process. I appreciate the feedback!

**Comment by uncenter** [comment]
> to keep the changes organized and ensure a clean commit history

We use squash merge commits so the commit history of individual PRs isn't seen on the primary branches.

> However, I'll keep in mind the option to use draft pull requests in the future to streamline the process.

I'm not asking you to "keep in mind" the "option" to mark this PR (or the other) a draft, that's how icon removals work. Removal PRs remain drafts until time for a major release, as @CodeShakingSheep mentioned yesterday.

**Pull request closed without merging**
