### PR TITLE
Add Stata icon

### LINKED ISSUE #9429: STATA
### Brand Name

STATA

### Website

https://www.stata.com/

### Popularity Metric

The Similarweb rank is 85,157. See https://www.similarweb.com/website/stata.com/#overview

### Official Resources for Icon and Color

favicon: https://www.stata.com/favicon.ico
This is the design installed by the software for script file (of course, scaled up, it's not the same file).

### Additional Comments

It's a very popular software for statistical analysis

### Contributing

No

### PR DESCRIPTION
**Pull request by thiagogquinto**
stata

**Issue:** closes #9429 

**Similarweb rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PratyushJayachandran** [comment]
Should we go with this instead? @simple-icons/icon-review 
https://www.stata.com/includes/images/stata-logo-blue.svg
The favicon is also their software icon AFAIK

**Comment by LitoMore** [comment]
@PratyushJayachandran Ah, that's hard to choose. But I prefer the favicon one.

@simple-icons/maintainers I think we can add two icons for this brand. One is for their trademark `Stata®` and one is for the software icon· What do you think?

This solution is also good for the Next.js.

**Comment by service-paradis** [comment]
Looks like they use their favicon for their social media too. They also called the favicon `Stata icon` in their [shop](https://www.stata.com/giftshop/).

Personally, I would go for this:
image
image

**Comment by service-paradis** [comment]
Also, I'm not sure we can add this icon without express permission as stated in https://www.stata.com/terms-of-use/

> However, the pictures, icons, and logos may not be individually extracted and used in other websites without the written permission of StataCorp or the respective copyright or trademark holder.

**Comment by PratyushJayachandran** [comment]
@service-paradis Looking through the shop it now seems more ambiguous. They use the wordmark and logomark interchangeably when talking about Stata. Like Stata-saur T-shirt.

When it comes to Stata I always saw the logomark though. We could do what @LitoMore said maybe.

But more importantly we need to ask them as you rightly pointed out the terms. It gives the impression that editorial use is fine? I'm not sure. Better to ask.

**Comment by PeterShaggyNoble** [comment]
> However, the pictures, icons, and logos may not be individually extracted and used in other websites without the written permission of StataCorp or the respective copyright or trademark holder.

Based on this, we're unfortunately going to have to reject this one at this time. If someone reaches out to them to request permission then we can revisit it.

Thanks for your efforts nonetheless, @thiagogquinto 👍🏻

**Pull request closed without merging**
