### PR TITLE
Update Harbor

### PR DESCRIPTION
**Pull request by mondeja**
image

**Issue:** #4590
**Alexa rank:** [~444k](https://www.alexa.com/siteinfo/goharbor.io) ([13.7k Github stars](https://github.com/goharbor/harbor/stargazers))

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Rebuilt from source and optimized using 3 decimals precision.

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
There seem to be some *tiny* differences between PR (red) and source (black). Any chance you could take another look?

image

**Comment by mondeja** [comment]
I've tried a lot of things, but even with a precision of 4 I'm always obtaining a slight difference with the source. Could you take a look @adamrusted?

**Comment by adamrusted** [comment]
> Could you take a look @adamrusted?

Sure - I'll take a look now and see what I can do :+1:

**Comment by adamrusted** [comment]
@mondeja try that. If that matches up ok to source then we can look to merge :smile:

**Comment by mondeja** [comment]
Wow, it's perfect now! :100:
I should consider trying AI :sweat_smile:

**Comment by adamrusted** [comment]
> Wow, it's perfect now! 💯
> I should consider trying AI 😅

One of the main reasons I enjoy working in marketing for my day-job! 😅👀

**Pull request merged**
