### PR TITLE
Rails .svg

### PR DESCRIPTION
**Pull request by whoisjorge**
From original sources.

### CODE REVIEW

**Comment by davidklebanoff** [comment]
Thanks for the contribution @whoisjorge! Did you run it through SVGO or [SVGOMG](https://jakearchibald.github.io/svgomg/)?

**Comment by whoisjorge** [comment]
Yes! I did through [SVGOMG](https://jakearchibald.github.io/svgomg/)... watching the code again it shouldn't have preserved the `id="Shape"` on paths.

**Comment by whoisjorge** [comment]
Great! Thank you @davidklebanoff.

**Comment by davidklebanoff** [comment]
Issue #487.

**Pull request merged**
