### PR TITLE
Add Gridsome icon

### LINKED ISSUE #3117: Gridsome
**Name:** Gridsome
**Website:** https://gridsome.org
**Official resources for icon and color:** https://gridsome.org/logo

### PR DESCRIPTION
**Pull request by chumaumenze**
gridsome

**Issue:** Closes #3117

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon and colours defined at https://gridsome.org/logo

### CODE REVIEW

**Comment by chumaumenze** [comment]
@PeterShaggyNoble how are you measuring the path? I'm not experienced working with svg, in fact I used Adobe Illustrator for the first time yesterday. I would like to do the extra checks to correct that before pushing any changes.

Regarding the colour, I used `#00835C` because the colour seem to be used more than `#00A672`. 

The former was used more in:

+ [Logo with text](https://gridsome.org/logos/logo-dark.svg)
+ [Logo with square background](https://gridsome.org/logos/only-logo-light.svg)
+ [Logo with circle background](https://gridsome.org/logos/logo-circle-light.svg)

The latter was used fewer times, mainly in the lower part of the *G* symbol.

**Comment by PeterShaggyNoble** [comment]
> how are you measuring the path?

Illustrator should have a toolbar that allows you to view and manually set the dimensions. I don't know Illustrator myself so can't tell you exactly where to find it but see the screenshot below for what it looks like in Inkscape.

> I used `#00835C` because the colour seem to be used more

I see your point. However, the variables in their [website stylesheet](https://gridsome.org/assets/css/0.styles.163c28ee.css) refers to that as `primary-color-dark`, while `#00a672` is simply referred to as `primary-color`, so I still think that's what we should go with.

```
:root{
	--body-color:rgba(0,0,0,0.8);
	--primary-color:#00a672;
	--primary-color-dark:#00835c;
	...
}
```

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @chumaumenze?

**Comment by PeterShaggyNoble** [comment]
Closing this out due to inactivity. I'll open a fresh PR for it shortly.

**Pull request closed without merging**
