### PR TITLE
Adds Postwoman icon

### PR DESCRIPTION
**Pull request by liyasthomas**
**Issue:** #1860 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Solves #1860 
- Postwoman logo features an alien head 👽
- Brand color is alien green `#50FA7B`

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Thanks for your work on this @liyasthomas, the icon looks great. 👍 

To keep things tidy, can you please update the PR so that the entry for Postwoman in `_data/simple-icons.json` is not at the end of the file but in alphabetical order.

**Comment by liyasthomas** [comment]
Yeah! Sure. I didn't knew it should be given that way.

**Comment by liyasthomas** [comment]
Done!

**Comment by phatbhoy67** [comment]
Thanks for your work on this @liyasthomas 👍

**Pull request merged**
