### PR TITLE
Add NameMC icon

### LINKED ISSUE #10410: Request: NameMC
### Brand Name

NameMC

### Website

namemc.com

### Popularity Metric

https://s.namemc.com/img/favicon-30.png
https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimage.winudf.com%2Fv2%2Fimage1%2FY29tLm5hbWVtY19pY29uXzE1NjAxNTY1NTBfMDQx%2Ficon.png%3Fw%3D340%26fakeurl%3D1&f=1&nofb=1&ipt=1cd604eb56c851be2eadcec2af37c5f4d1541e25781e6296c49ce63158b94b16&ipo=images

### Official Resources for Icon and Color

#000000

### Additional Comments

Tanks

### PR DESCRIPTION
**Pull request by Garbg**
namemc

**Issue:** closes #10410

**Similarweb rank:**
Global: 5931
Country (US): 8275
Category: 73

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

I manually vectorized the icon because it was simple pixel art and an automatic vectorization would probably have been less accurate. The logo is updated now.

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
I think we'd be better including the square to be honest. I've also generated the below preview using the background colour of the website. What do you think @Garbg?
image

As far as manual recreation goes, I've generated the below path on a 30x30px grid (same size as the favicon) and then shrunk down to meet our canvas size. You're welcome to use it - we'll need another maintainer to review if you do!
```
M24,0L24,24L0,24L0,0L24,0ZM16,8L16,4.8L4.8,4.8L4.8,19.2L8,19.2L8,8L16,8ZM16,8L16,19.2L19.2,19.2L19.2,8L16,8Z
```

**Comment by Garbg** [comment]
I'll update the icon when I can

**Comment by Garbg** [comment]
I'll only have 1 square of outline (which means each square is 4 pixels)

**Comment by Garbg** [comment]
The favicon has 2 squares of outline, but the logo on the navbar only has 1 so I'll go with one square of outline

**Comment by adamrusted** [comment]
The one I used was [the favicon from the navbar](https://s.namemc.com/img/favicon-30.png) and that's got 2 pixels around the shape. Worth basing off of this one if possible - given that's the main one they show.

**Comment by Garbg** [comment]
The requested changes have been done.

**Review by adamrusted — CHANGES_REQUESTED** [review]
I'm still seeing [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/41d666dc-ce3d-4a38-9638-496df60cfb71) when comparing to the path I created by doing a 1:1 trace at 30x30px - and then shrinking down.

**Comment by Garbg** [comment]
As I said earlier, the favicon has slightly bigger borders than the navbar icon, mine is based off the navbar icon

**Comment by Garbg** [comment]
Nvm you're right

**Comment by Garbg** [comment]
I opened the image in a pixel art editor to see the sizes of everything, so I'll recreate it in vector then scale it down from 30x30 to 24x24

**Comment by Garbg** [comment]
I updated the icon again

**Review by adamrusted — APPROVED** [review]

**Pull request merged**
