### PR TITLE
add Verdaccio

### LINKED ISSUE #5422: Icon Request: Verdaccio
**Brand Name:** Verdaccio
**Website:** https://verdaccio.org/
**Alexa rank:** 733270
  

**Official resources for icon and color:** https://verdaccio.org/docs/en/logo

### PR DESCRIPTION
**Pull request by raeffs**
verdaccio

**Issue:** Closes #5422
**Alexa rank:** 733270
**GitHub stars:** [~11k](https://github.com/verdaccio/verdaccio/)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I used the black and white SVG from their [website](https://verdaccio.org/docs/en/logo), removed unnecessary elements and combined all the paths to one. The hex value is the one from their websites header. It's almost the same value used in the icon itself, just slightly different (I wasn't able to see any difference).

### CODE REVIEW

**Comment by raeffs** [comment]
I saw that the icon is not displayed correctly in the [preview generator](https://petershaggynoble.github.io/MDI-Sandbox/simpleicons/preview/), I will check that again.

**Comment by raeffs** [comment]
looks better now:

verdaccio

**Review by PeterShaggyNoble — APPROVED** [review]
Welcome to Simple Icons, @raeffs, and thanks for the contribution 🙂

Everything looks good to me 👍🏻 There are a couple of minor differences arising from the removal of the left path of the "v" but I think that's OK as it looks to be an imperfection in the original rather than intentional.

I also think that's the correct choice for the colour; it's also used for text & links throughout the site. The other option, though, would be the darker `#405236` from the full colour SVGs.

I don't think we need the `guidelines` entry here as the source page doesn't include any additional information about the branding or usage of the icon. Once that change is made, this can be merged straight in.

**Comment by raeffs** [comment]
@PeterShaggyNoble I removed the `guidelines` entry

**Comment by PeterShaggyNoble** [comment]
Thanks for the quick update and for your work on this, @raeffs 👍🏻

If anyone feels that the imperfection in the original was intentional or that there's a better choice of colour, we can address that  in a separate PR.

**Comment by raeffs** [comment]
sounds good 👍🏻

**Comment by juanpicado** [comment]
This so cool 😎:) looking forward seeing online, thanks @raeffs

**Comment by PeterShaggyNoble** [comment]
It will be available from this coming Sunday, @juanpicado.

**Pull request merged**
