### PR TITLE
Add Obtainium icon

### PR DESCRIPTION
**Pull request by CodeShakingSheep**
image

**Issue:** closes https://github.com/simple-icons/simple-icons/issues/11418

**Popularity metric:**

Obtainium has ~6k GitHub stars. See https://github.com/ImranR98/Obtainium

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

I used the website's text color as brand color.

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
The [source](https://github.com/ImranR98/Obtainium/blob/main/assets/graphics/icon.svg) in issue #11418 (violet) has so many less points than your version (black):

image


Please, optimize the path.

**Comment by CodeShakingSheep** [comment]
> The [source](https://github.com/ImranR98/Obtainium/blob/main/assets/graphics/icon.svg) in issue #11418 (violet) has so many less points than your version (black):
> 
> Please, optimize the path.

I didn't use the icon from the GitHub repo as source but the SVG icon from the official website which is a completely different SVG. If you think that the icon from the GitHub repo should be used as source instead, I could rework the icon. What do you think @mondeja?

**Comment by adamrusted** [comment]
I would prefer us to use the Github version of the icon, specifically [this link](https://github.com/ImranR98/Obtainium/blob/e5afe7521347c73382534a013c070b9c1da716c5/assets/graphics/icon.svg) so we maintain a view of the versioning of the file.

**Review by adamrusted — APPROVED** [review]
LGTM, thanks @CodeShakingSheep!

**Pull request merged**
