### PR TITLE
Add Cloudways icon

### LINKED ISSUE #3295: Cloudways
**Name:** Cloudways
**Website:** cloudways.com
**Alexa rank:** 9793
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by avats-dev**
**Issue:** closes #3295 
**Alexa rank:** 8709
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- [Resource](https://www.cloudways.com/en/media-kit.php)

### CODE REVIEW

**Comment by NovaGL** [comment]
Hi @avats-dev 

Thanks for doing this. Can you please look at the size of the icon as it's not correct. It should be 24 x 24 however it's currently 1749.023 x 944.316

Have a look to make sure the icon is centred as well.

**Comment by avats-dev** [comment]
> Hi @avats-dev
> 
> Thanks for doing this. Can you please look at the size of the icon as it's not correct. It should be 24 x 24 however it's currently 1749.023 x 944.316
> 
> Have a look to make sure the icon is centred as well.

Hi @NovaGL , I changed the `viewBox = "0 0 24 24"`, but it still is same. I really want to do this, but I don't know what should I do now. 

I checked again and there are 2 path elements and I will compound them into one, but what should I do about size? I tried [icomoon](https://icomoon.io/app), but it remained same. Thanks for helping me out!

**Comment by NovaGL** [comment]
Try loading the image in inkscape and fix it there

**Comment by runxel** [comment]
Hey @avats-dev, you still with us? 😊
Lets us know if you're working on this PR. Thanks!

**Comment by avats-dev** [comment]
@runxel sorry for not being active here, I was having problems in dealing with `svg`. I'm thinking of trying again. Can you spare me some more time for this? I'll update soon, thanks. :pleading_face:

**Comment by runxel** [comment]
Sure, no problem! Take your time :)

**Comment by adamrusted** [comment]
Hi @avats-dev, are you still interested in contributing this icon? Don't worry if not, I can continue working from your PR here. 🙂

**Comment by adamrusted** [comment]
@simple-icons/maintainers there's now an SVG source including embedded colour. I've rebuilt the icon using the SVGs in the logo kit, and changed the colour. Needed 4 decimals though. If any of you can get it to 3 then feel free to merge into this branch.

**Comment by fbernhart** [comment]
@adamrusted Done. 😉 It helped resizing it to 24.001 px in Inkscape before optimization. So it became 24.000 px after optimizing it with a precision of 3.

**Comment by adamrusted** [comment]
Beautiful - thanks @fbernhart 🙏🏻

**Review by adamrusted — APPROVED** [review]
Perfect, thanks @fbernhart for reducing this one down, and thanks @avats-dev for your initial work on this 🎉

**Pull request merged**
