### PR TITLE
Updated Apache Flink

### PR DESCRIPTION
**Pull request by adamrusted**
apacheflink (2)

**Issue:** #2887

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> Not Necessary
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Swapped for the 'filled' variation of the Flink logo.
- Extracted from [file](https://flink.apache.org/img/logo/svg/white_filled.svg) with Adobe Illustrator.
- SVGLINT returned valid.

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
Thanks for the update @adamrusted :+1:

I'm seeing significant differences between your version and the source. I think that is because you're using 2 decimals optimizing it and maybe this value is too low. Could you use 3 decimals of precision?

**Comment by adamrusted** [comment]
> I'm seeing significant differences between your version and the source. I think that is because you're using 2 decimals optimizing it and maybe this value is too low. Could you use 3 decimals of precision?

Sure thing - will update later tonight or tomorrow morning 👍

**Comment by mondeja** [comment]
Ups, the eye seems to have disappeared now... :sweat_smile: 

image

**Comment by adamrusted** [comment]
> Ups, the eye seems to have disappeared now... 😅
> 
> image

GOING WELL! 😆
Serves me right for rushing to get it done.

**Review by mondeja — APPROVED** [review]
Looks good! :+1:
Thank you @adamrusted

**Pull request merged**
