### PR TITLE
Add revolt.chat

### LINKED ISSUE #7314: Request: Revolt
### Brand Name

Revolt

### Website

https://revolt.chat

### Popularity Metric

The Similarweb rank is [#296,031](https://www.similarweb.com/website/revolt.chat).

### Official Resources for Icon and Color

[revoltchat/revite](https://github.com/revoltchat/revite/tree/master/public/assets_default)

### Additional Comments

Earlier issue: #6088

### Contributing

Yes

### PR DESCRIPTION
**Pull request by Andre601**
revoltdotchat

**Issue:** closes #7314 

**Similarweb rank:** [#344,582](https://www.similarweb.com/de/website/revolt.chat/#overview) (8th of may, 2022)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG icon of Revolt.chat, an open-source Text and VOIP site.
The SVG is based off a version someone else was providing through a (now discontinued) instance of Simple icons.

Note that this is my first time working with SVG stuff, so please don't hesitate if I messed something up or forgot to improve something.

### CODE REVIEW

**Comment by Andre601** [comment]
Looks like I need to fix the size and centering, but I'm not sure how, so if you have some steps, lmk.

**Comment by Andre601** [comment]
Guess I got this stuff to be right now...

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @Andre601,

thanks for the contribution but the provided link is not a valid SVG anymore.

https://github.com/revoltchat/revite/blob/master/public/assets_default/badges/revolt_r.svg

**Comment by Andre601** [comment]
> Hi @Andre601,
> 
> thanks for the contribution but the provided link is not a valid SVG anymore.
> 
> https://github.com/revoltchat/revite/blob/master/public/assets_default/badges/revolt_r.svg

In what way? Clicking it brings me to the SVG itself, so it seems to be fine?

**Comment by Andre601** [comment]
Talking with the devs, it seems like they made the svgs empty...

So, remove the source? Otherwise Idk what else I could point as the source here, unless a specific commit URL is acceptable.

**Comment by Andre601** [comment]
Received a new source URL that can be used and seems to be valid: https://app.revolt.chat/assets/badges/revolt_r.svg

**Review by dirien — CHANGES_REQUESTED** [review]
Hi,

I sees some differences. Could you rework the icon in the PR with the new logo?

image

**Comment by Andre601** [comment]
> Hi,
> 
> I sees some differences. Could you rework the icon in the PR with the new logo?
> 
> image

I honestly can't.... I do not have the experience with SVG to achieve this changes here, so if you (or someone else experienced) could try doing this, I would really appreciate it.

And it's weird that it is different as I literally used that exact SVG and tried my best to resize it to the 24x24 viewbox in the end (As you may have guessed from all the commits and failed runs).

One thing I am curious now and want to take the opportunity to ask: Would a small difference like this be acceptable, if the owner(s) gave their permission/agreement for it?

**Comment by Andre601** [comment]
This should hopefully fix the wrong dimensions... If not, then please give me the steps to make it work as I tried the following within Inkscape:

- Selected all paths using `Edit -> Select all in all layers`
- Opened `Object -> Transform`
- Set height to `24.000` pixels while preserving scale proportions
- Set canvas size to 24x24 pixels
- Aligned SVG vertically and horizontally in the center.

Afterwards I did all the SVGOMG shenanigans.

**Review by dirien — APPROVED** [review]
Perfect fit!

image

**Pull request merged**
