### PR TITLE
Updated Google Tag Manager

### PR DESCRIPTION
**Pull request by adamrusted**
googletagmanager

**Issue:** Contributes to #4205
**Alexa rank:** N/A (Google subdomain)

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> Not Necessary
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Rebuilt from source with 0.5px gaps between sections.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Comparing with [this SVG](https://www.gstatic.com/analytics-suite/header/suite/v2/ic_tag_manager.svg), @adamrusted, I'm seeing considerable difference to your version in red below.

**Comment by adamrusted** [comment]
Looks like I did a _real_ rough job on this one. Bear with while I fix it 👌

**Comment by adamrusted** [comment]
Should be updated - if @PeterShaggyNoble could take another look?

**Comment by PeterShaggyNoble** [comment]
Unfortunately, I'm still seeing a few slight differences between your version (in red) and the source.

 - [Comparison 1](https://user-images.githubusercontent.com/15157491/106602953-97e62500-6555-11eb-9eb7-ed129ded8151.png)
 - [Comparison 2](https://user-images.githubusercontent.com/15157491/106603091-c6640000-6555-11eb-86b5-0aa2b62d948a.png)

**Comment by adamrusted** [comment]
Should be fixed 🤞🏻

**Comment by PeterShaggyNoble** [comment]
Still seeing a few differences, @adamrusted 🙈 See [this comparison](https://user-images.githubusercontent.com/15157491/107365658-05093580-6ad5-11eb-87c2-862d5a4226c5.png). Gave it a stab myself and came up with the following, unoptimised path, if it helps:
```
M 45.391459,19.003031 A 2.9730305,2.9730305 0 1 1 41.186459,23.207031 2.9730305,2.9730305 0 0 1 45.391459,19.003031 Z M 40.832459,18.649031 A 3.45,3.45 0 0 1 43.288459,17.632031 C 43.573459,17.632031 43.850459,17.677031 44.119459,17.743031 L 38.564459,12.079031 42.969459,7.6740315 40.847459,5.5540315 A 3.49,3.49 0 0 1 39.946459,2.2110315 L 32.204459,9.9530315 A 2.999,2.999 0 0 0 32.202459,14.193031 L 32.204459,14.196031 39.924459,21.915031 A 3.464,3.464 0 0 1 40.833459,18.649031 Z M 54.444459,9.9530315 H 54.439459 L 45.444459,0.95703148 A 3.0002541,3.0002541 0 0 0 41.201459,5.2000315 L 48.089459,12.083031 43.658459,16.559031 45.535459,18.474031 45.585459,18.513031 C 45.640459,18.555031 45.695459,18.598031 45.745459,18.649031 L 45.746459,18.650031 C 45.949459,18.853031 46.112459,19.080031 46.254459,19.316031 46.291459,19.378031 46.320459,19.441031 46.354459,19.505031 46.455459,19.701031 46.537459,19.902031 46.600459,20.111031 46.614459,20.161031 46.632459,20.211031 46.644459,20.261031 46.782459,20.814031 46.784459,21.388031 46.647459,21.941031 L 54.417459,14.219031 C 54.425459,14.210031 54.437459,14.205031 54.445459,14.196031 A 3,3 0 0 0 54.445459,9.9530315 Z
```

**Comment by adamrusted** [comment]
What the heck @PeterShaggyNoble 😅
No clue where I'm going wrong with this path. I'll try optimizing yours and comparing against source, see if that does the job.

**Comment by adamrusted** [comment]
@PeterShaggyNoble try that one out - took a bit of faffing to get it to pass the linter, but seems fine now.

**Comment by PeterShaggyNoble** [comment]
Crap! Sorry, @adamrusted; looks like I copied and pasted the wrong path into my last comment 🙁 And Inkscape crashed on me before I could save the correct one. Here's a rough recreation:

```
M 12.002609,0 C 11.234893,0 10.467189,0.29323275 9.8815157,0.87890625 8.7101689,2.0502533 8.7101689,3.9497468 9.8815157,5.1210938 L 16.74675,11.986328 12.301437,16.527344 14.045578,18.363281 A 3.4319999,3.4319999 0 0 1 14.74675,19.101562 L 14.758468,19.113281 14.756515,19.115234 A 3.4319999,3.4319999 0 0 1 15.36589,21.068359 3.4319999,3.4319999 0 0 1 15.276047,21.847656 L 23.026047,14.201172 C 23.057418,14.172336 23.093287,14.151509 23.123703,14.121094 23.147135,14.097661 23.161755,14.068925 23.18425,14.044922 24.286237,12.869028 24.271617,11.02682 23.123703,9.8789062 L 14.123703,0.87890625 C 13.538029,0.29323275 12.770325,0 12.002609,0 Z M 8.6295626,2.1328125 0.87956263,9.8085938 C -0.29042076,10.978577 -0.29042075,12.875528 0.87956263,14.046875 L 8.5807345,21.796875 A 3.4319999,3.4319999 0 0 1 8.5026095,21.068359 3.4319999,3.4319999 0 0 1 11.93425,17.636719 3.4319999,3.4319999 0 0 1 12.760421,17.738281 L 7.2369845,11.927734 11.608078,7.5546875 9.5280001,5.4746094 C 8.6246258,4.571235 8.3349791,3.2915234 8.6295626,2.1328125 Z M 11.93425,18.136719 A 2.9317765,2.9317765 0 0 0 9.0026095,21.068359 2.9317765,2.9317765 0 0 0 11.93425,24 2.9317765,2.9317765 0 0 0 14.86589,21.068359 2.9317765,2.9317765 0 0 0 11.93425,18.136719 Z
```

**Comment by adamrusted** [comment]
No worries @PeterShaggyNoble - that new path _seems_ to be okay, if you wanted to review the optimized version?

**Comment by PeterShaggyNoble** [comment]
> if you wanted to review the optimized version

Did you push the update for that, yet?

**Comment by adamrusted** [comment]
> Did you push the update for that, yet?

I thought I had, obviously closes GitHub pre-emptively on my desktop. Let me just go and check it 👌

**Comment by PeterShaggyNoble** [comment]
Other than the minor imperfection on the right corner (which I missed in my attempt! 🤦🏻‍♂️), this looks pretty good to me now. Although, as I had a hand in it, we'll need one of the other @simple-icons/maintainers to take up the review now.

**Review by service-paradis — APPROVED** [review]
LGTM,
Good job @PeterShaggyNoble and @adamrusted 💯

**Pull request merged**
