### PR TITLE
Add Homebridge.

### LINKED ISSUE #3464: Homebridge
**Name:** Homebridge
**Website:** https://homebridge.io
**Alexa rank:** 622,544
  

**Official resources for icon and color:**  https://github.com/homebridge/branding
  
  

Homebridge is a popular smart home platform that provides HomeKit support for non-HomeKit-native devices.

### PR DESCRIPTION
**Pull request by hjdhjd**
**Issue:** Closes #3464.

  

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

Icon from [this file](https://github.com/homebridge/branding/blob/master/logos/homebridge-outline-black.svg), color from the SVG and branding site.

### CODE REVIEW

**Comment by runxel** [comment]
@hjdhjd thanks for the PR! 👍 
As you can see, the linting fails currently:
`icon-centered <path> must be centered at (12, 12); the center is (11.988, 12)`.
If you use Illustrator you might want to try Inkscape for better results.
Also using a bigger precision on SVGO can help.

**Comment by hjdhjd** [comment]
Inkscape doesn't work on the Mac I'm afraid. Trying to figure out an alternate option.

**Comment by hjdhjd** [comment]
Updated and ready to go!

**Comment by hjdhjd** [comment]
Tagging @runxel - anything else needed?

**Comment by hjdhjd** [comment]
@runxel?

**Comment by runxel** [comment]
Hi @hjdhjd, I understand you're eager to get this PR in! :) 
We all are! Sadly the maintainers are pretty busy right now, and reviewing takes _a lot of time_ since we do one on one comparisons with the OG. We will do review the PR as fast as possible 😉

**Comment by hjdhjd** [comment]
Works for me. Suggest you update the docs to let people know it can take a while for future reference. :)

**Review by runxel — CHANGES_REQUESTED** [review]
Hi @hjdhjd 
Sorry for the long time waiting. I had a look at your PR and it doesn't seem to match the original file, as you can see:
hb

**Comment by hjdhjd** [comment]
Not sure what the issue is, I've looked at the file in several environments and it is correct. The above is not.

Please provide a mechanism to recreate the error you're seeing, because I don't see it. The file is correct as far as I can tell.

**Comment by hjdhjd** [comment]
image

**Comment by hjdhjd** [comment]
Zoomed in further:

image

**Comment by hjdhjd** [comment]
Tagging @runxel 

See above. Thanks.

**Comment by runxel** [comment]
> Please provide a mechanism to recreate the error you're seeing, because I don't see it. The file is correct as far as I can tell.

I've taken several of the files from the repo linked. Please also include a direct link to the icon you've used ion the future. (And not only that, we'd like to have the link to the precise commit; you get this link by pressing `y` on your keyboard.)
Anyway: None of those files matched with your version. Your's perfectly square, while the original icons _are not_.

**Comment by hjdhjd** [comment]
They do, and they are.

Here's the direct link:

https://github.com/homebridge/branding/blob/6ef3a1685e79f79a2ecdcc83824e53775ec0475d/logos/homebridge-outline-black.svg

The icon above remains correct.

**Comment by runxel** [comment]
I beg to differ ;)
The OG is, I repeat, _not square_.

false

**Comment by hjdhjd** [comment]
Alrighty then - we're at the limits of what I can do. If someone wants to take this and run with it, I encourage them to do so. I gave it my best shot. :smile:

Would you like me to close this PR, or leave it open?

**Comment by runxel** [comment]
Okay, @hjdhjd, I didn't wanted to stifle your efforts!
Big thanks nonetheless! ❤️ 
Maybe someone else from the community will pick this one up :)

**Comment by hjdhjd** [comment]
No worries. Hope someone else picks this up!

**Pull request closed without merging**
