### PR TITLE
Updated Android Studio

### PR DESCRIPTION
**Pull request by adamrusted**
androidstudio (1)

**Issue:** Contributes to #4205
**Alexa rank:** N/A

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Updated source to [developer.android.com/studio](https://developer.android.com/studio).
Rebuilt icon from new source.
Gap of 0.35px to differentiate between android, compass, and background.

### CODE REVIEW

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
I'm noticing some minor differences around the edges of the head and the eyes as well the hole of the compass. Could you have a look at those, @adamrusted? I also wonder if that hole shouldn't either be completely empty or have the circle be off-centre as it is in the original.

(PR version in red)

**Comment by adamrusted** [comment]
> I also wonder if that hole shouldn't either be completely empty or have the circle be off-centre as it is in the original.

Looks like it's been updated again since I looked at it - could've sworn the compass had the gap as I put it.
Will rebuild from source now, hopefully fixing any issues.

**Comment by PeterShaggyNoble** [comment]
[This SVG](https://developer.android.com/studio/images/studio-icon.svg) (found [here](https://developer.android.com/index.html)) could be taken as confirmation that the hole is supposed to be empty.

**Comment by adamrusted** [comment]
> [This SVG](https://developer.android.com/studio/images/studio-icon.svg) (found [here](https://developer.android.com/index.html)) could be taken as confirmation that the hole is supposed to be empty.

@PeterShaggyNoble I've realised what it is - if I were to colour it, the inner circle of the compass is supposed to be the 'background' in the simplified version. If you just do the compass shape, ignoring the dark circle and shadow behind it, there should be a 0.5px margin around the outside of the compass shape.

**Comment by PeterShaggyNoble** [comment]
Yep, that looks good to me.

**Comment by adamrusted** [comment]
@PeterShaggyNoble path updated. Should be good to go if you're happy with it.

**Comment by PeterShaggyNoble** [comment]
I'm still seeing some minor - although not as pronounced - differences around the edges of the head and the compass, @adamrusted. They're small enough that it could simply be a precision issue, though.

**Comment by adamrusted** [comment]
@PeterShaggyNoble give that a try - re-exported with 4 decimals of precision.

**Comment by PeterShaggyNoble** [comment]
Still seeing those issues, I'm afraid, @adamrusted. Perhaps it was an issue converting strokes to paths, if that's what you're doing - Inkscape has fierce issues with that some times. I gave it a try myself and managed to come up with something that lines up a bit better, if it's any help as a starting point. Although it did, somehow through the process, end up with far too many points! Gonna have a quick try with the alternative source I found to see if that produces better results.

I also wonder if we shouldn't add a cut-out around the curves where the pages overlaps itself?

```
M 8.0996094,0 C 8.0231652,0.00421132 7.9534032,0.04490583 7.9121094,0.109375 7.8730666,0.17706536 7.8730666,0.26043464 7.9121094,0.328125 L 8.9492188,2.1191406 C 7.2903117,3.0273741 6.1435658,4.6505493 5.8417969,6.5175781 H 18.146484 C 17.844715,4.6505493 16.697969,3.0273741 15.039062,2.1191406 L 16.070312,0.328125 C 16.169697,0.09192447 15.851997,-0.09340061 15.695312,0.109375 L 14.652344,1.9257812 C 12.96095,1.1660667 11.025378,1.1660667 9.3339844,1.9257812 L 8.2851562,0.109375 C 8.2467608,0.04290752 8.1763568,0.00140621 8.0996094,0 Z M 4.0996094,3.0332031 C 3.000217,3.0374283 2.1112419,3.9298964 2.1113281,5.0292969 2.1101429,5.0683504 2.1101429,5.1074309 2.1113281,5.1464844 V 18.78125 C 2.1144395,19.876091 2.9989297,20.764067 4.09375,20.771484 H 7.0351562 L 10.287109,13.771484 C 9.7667771,13.185552 9.5224686,12.442368 9.6914062,11.75 9.8595274,11.060979 10.414654,10.518719 11.140625,10.236328 V 9.4140625 C 11.128117,9.1069874 11.283627,8.8160892 11.544922,8.6542969 L 11.548828,8.6503906 11.552734,8.6484375 C 11.68547,8.5698924 11.834922,8.53125 11.984375,8.53125 12.133828,8.53125 12.28328,8.5698925 12.416016,8.6484375 L 12.419922,8.6503906 12.425781,8.6542969 C 12.687076,8.8160892 12.840633,9.1069874 12.828125,9.4140625 L 12.830078,9.3945312 V 10.292969 C 13.465355,10.603271 13.974844,11.130291 14.119141,11.837891 14.268937,12.539034 14.01104,13.218186 13.556641,13.751953 L 16.929688,20.771484 H 19.166016 V 23.847656 C 19.165675,23.902714 19.208688,23.948308 19.263672,23.951172 H 20.107422 C 21.093009,23.947474 21.890161,23.147703 21.890625,22.162109 V 9.046875 C 21.889876,9.1299102 21.88335,9.2127927 21.871094,9.2949219 V 8.9492188 C 21.871094,6.7665483 18.972656,7.0175781 18.972656,7.0175781 H 5.2851562 C 5.4170284,5.523884 6.0519095,4.1191581 7.0859375,3.0332031 Z M 9.1289062,4.1679688 C 9.1490715,4.1667963 9.1692878,4.1667963 9.1894531,4.1679688 9.6689607,4.1884559 9.8685604,4.7910689 9.4960938,5.09375 9.3984559,5.1900905 9.2660466,5.2429134 9.1289062,5.2402344 8.6667554,5.244317 8.4335025,4.684758 8.7617188,4.359375 8.8524557,4.2476346 8.9853408,4.1783648 9.1289062,4.1679688 Z M 14.863281,4.2070312 C 15.143637,4.216505 15.366277,4.4460475 15.367188,4.7265625 15.366412,5.0099336 15.136887,5.2394584 14.853516,5.2402344 14.387535,5.2515418 14.147376,4.6874184 14.478516,4.359375 14.565502,4.2726225 14.680321,4.2193629 14.802734,4.2089844 14.822861,4.2071607 14.843078,4.2065086 14.863281,4.2070312 Z M 11.972656,9.0292969 C 11.914087,9.0313214 11.85698,9.0481176 11.806641,9.078125 11.75481,9.1109857 11.712408,9.1567524 11.683594,9.2109375 L 11.681641,9.2128906 V 9.2148438 C 11.652348,9.2700694 11.638197,9.332065 11.640625,9.3945312 V 10.521484 C 11.457892,10.550092 11.280673,10.606749 11.115234,10.689453 11.105447,10.694267 11.095592,10.698151 11.085938,10.703125 10.948492,10.776173 10.821123,10.866776 10.707031,10.972656 10.68923,10.989104 10.671326,11.004382 10.654297,11.021484 L 10.652344,11.023438 C 10.54234,11.133688 10.447141,11.257775 10.369141,11.392578 10.365778,11.398457 10.36267,11.404242 10.359375,11.410156 10.194637,11.699377 10.113495,12.02868 10.125,12.361328 10.125237,12.369156 10.126615,12.376938 10.126953,12.384766 10.135377,12.538787 10.163604,12.691082 10.210938,12.837891 10.217755,12.859725 10.224718,12.88071 10.232422,12.902344 10.284968,13.049694 10.356537,13.189549 10.445312,13.318359 10.453692,13.330275 10.461979,13.341747 10.470703,13.353516 10.57793,13.501113 10.707015,13.631515 10.853516,13.740234 L 6.7402344,22.59375 C 6.5844052,22.910539 6.6112739,23.286701 6.8105469,23.578125 7.013223,23.866558 7.3538014,24.025693 7.7050781,23.996094 8.0565775,23.962736 8.3623626,23.741435 8.5039062,23.417969 L 11.248047,17.525391 C 11.28072,17.458523 11.322924,17.39547 11.371094,17.341797 11.371745,17.341796 11.372396,17.341796 11.373047,17.341797 11.373046,17.341146 11.373046,17.340495 11.373047,17.339844 11.470664,17.232575 11.597064,17.15396 11.736328,17.113281 11.73763,17.113278 11.738932,17.113278 11.740234,17.113281 11.809203,17.093499 11.881051,17.08234 11.955078,17.082031 12.177534,17.081333 12.386154,17.176509 12.53125,17.335938 12.535209,17.340449 12.539116,17.345007 12.542969,17.349609 12.584985,17.398005 12.619144,17.45278 12.648438,17.511719 12.651088,17.51625 12.653693,17.520807 12.65625,17.525391 L 15.470703,23.384766 C 16.037109,24.552734 17.789062,23.703124 17.222656,22.535156 L 12.986328,13.720703 C 13.118788,13.616635 13.235836,13.494326 13.333984,13.357422 13.334843,13.356228 13.335082,13.354711 13.335938,13.353516 13.431543,13.220795 13.508435,13.075554 13.564453,12.921875 13.564885,12.920675 13.564024,12.919169 13.564453,12.917969 13.620125,12.763886 13.654301,12.602866 13.666016,12.439453 V 12.4375 C 13.677251,12.269917 13.664758,12.101588 13.628906,11.9375 13.59566,11.77366 13.539787,11.615242 13.462891,11.466797 13.46138,11.463883 13.458557,11.461888 13.457031,11.458984 13.307279,11.17265 13.083322,10.931828 12.808594,10.761719 12.80213,10.757731 12.795582,10.753908 12.789062,10.75 12.649307,10.666282 12.498849,10.601894 12.341797,10.558594 L 12.34375,10.552734 H 12.330078 V 9.3945312 C 12.330191,9.3917716 12.328078,9.3894722 12.328125,9.3867188 12.329428,9.3291871 12.316691,9.2722044 12.291016,9.2207031 12.288983,9.2166573 12.287341,9.21295 12.285156,9.2089844 12.256069,9.1555143 12.21369,9.1104446 12.162109,9.078125 12.108336,9.0461555 12.046934,9.0292866 11.984375,9.0292969 11.983724,9.0292951 11.983073,9.0292951 11.982422,9.0292969 11.979167,9.0292512 11.975911,9.0292512 11.972656,9.0292969 Z M 11.890625,11.197266 C 11.97888,11.197804 12.06675,11.208951 12.152344,11.230469 12.180665,11.237813 12.208682,11.246283 12.236328,11.255859 H 12.238281 C 12.266029,11.265181 12.293395,11.275606 12.320312,11.287109 12.400861,11.322182 12.476923,11.36677 12.546875,11.419922 H 12.548828 C 12.737956,11.56337 12.875659,11.7641 12.941406,11.992188 12.949667,12.01989 12.956835,12.047906 12.962891,12.076172 V 12.078125 C 13.040286,12.46129 12.908709,12.856763 12.617188,13.117188 12.462899,13.255631 12.27266,13.347703 12.068359,13.382812 12.010921,13.392612 11.952796,13.397837 11.894531,13.398438 11.864569,13.39901 11.834597,13.398358 11.804688,13.396484 11.746764,13.391919 11.689293,13.382776 11.632812,13.369141 H 11.630859 C 11.574215,13.355975 11.518703,13.338341 11.464844,13.316406 11.464192,13.315756 11.463541,13.315105 11.462891,13.314453 11.436403,13.303752 11.410342,13.292025 11.384766,13.279297 H 11.382812 C 11.330982,13.252674 11.281347,13.221979 11.234375,13.1875 11.233723,13.18685 11.233072,13.186199 11.232422,13.185547 11.13771,13.116492 11.054633,13.032755 10.986328,12.9375 V 12.935547 C 10.969766,12.912079 10.954129,12.887972 10.939453,12.863281 10.938801,12.862631 10.93815,12.86198 10.9375,12.861328 10.908031,12.811334 10.882561,12.759087 10.861328,12.705078 10.860676,12.704428 10.860025,12.703777 10.859375,12.703125 10.838006,12.648576 10.821025,12.592408 10.808594,12.535156 10.75137,12.274263 10.790936,12.001463 10.919922,11.767578 V 11.765625 C 10.947975,11.715008 10.979975,11.666681 11.015625,11.621094 V 11.619141 C 11.034258,11.596228 11.053805,11.574075 11.074219,11.552734 11.084405,11.541452 11.094824,11.530382 11.105469,11.519531 11.147899,11.477538 11.193618,11.439004 11.242188,11.404297 11.412619,11.283141 11.613557,11.212103 11.822266,11.199219 11.845027,11.197873 11.867824,11.197221 11.890625,11.197266 Z M 11.957031,17.582031 C 11.84485,17.582499 11.746515,17.6453 11.697266,17.746094 L 10.289062,20.771484 H 13.662109 L 12.205078,17.740234 V 17.738281 C 12.15952,17.641248 12.064227,17.581695 11.957031,17.582031 Z
```

**Comment by adamrusted** [comment]
@PeterShaggyNoble odd - I'll rebuild it from source again, adding in the lines around the curves if possible. What's the exact source SVG you're comparing to, just so I can run it by there again before uploading.

**Comment by PeterShaggyNoble** [comment]
The one embedded in the HTML of the source URL (see below), @adamrusted. I've since tried as well with [the alternative source](https://developer.android.com/studio/images/studio-icon.svg) I mentioned above and, while the results weren't better, the file is a bit "cleaner" so you may fare better.

[Source Screenshot](https://user-images.githubusercontent.com/15157491/105607506-0af1dd80-5d97-11eb-94dd-787788e5557b.png)

**Comment by adamrusted** [comment]
Give that a try @PeterShaggyNoble - it's still showing a few slight differences on my end when compared to source, but that's as good as I can get it even with Illustrator!

**Review by PeterShaggyNoble — APPROVED** [review]
This looks good to me, @adamrusted 👍🏻 Still seeing some minor differences in the outer curve of the head but as this is already an original interpretation with the addition of the cut-outs, I don't think they're significant enough at this stage to warrant spending more time on.

If anyone can improve on it then please open a new PR.

Thanks for your patience on this one.

**Pull request merged**
