### PR TITLE
Add Argo icon

### LINKED ISSUE #6644: Request: Argo
### Brand Name

Argo

### Website

https://www.cncf.io/projects/argo/

### Popularity Metric

9,367 for [argo-workflows](https://github.com/argoproj/argo-workflows) & 7,026  for [argo-cd](https://github.com/argoproj/argo-cd)

### Official Resources for Icon and Color

SVG: https://cncf-branding.netlify.app/img/projects/argo/icon/black/argo-icon-black.svg
More SVGs: https://cncf-branding.netlify.app/projects/argo/

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by outsideris**
**Issue:** closes #6644

argo

**Similarweb rank:** [290,319](https://www.similarweb.com/website/argoproj.github.io/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This is an icon for Argo family like [Argo CD](https://argoproj.github.io/cd/), [Argo Workflows](https://argoproj.github.io/workflows/), [Argo Rollouts](https://argoproj.github.io/rollouts/) or [Argo Events](https://argoproj.github.io/events/) which are popular in Kubernetes.

### CODE REVIEW

**Review by sisp — CHANGES_REQUESTED** [review]
Thanks for your contribution, @outsideris! :pray:

The aspect ratio of your icon differs from the original icon's aspect ratio. Please retain the original aspect ratio.

**Comment by outsideris** [comment]
Thank you. I fix the aspect ratio.

**Review by sisp — APPROVED** [review]
LGTM now! :tada:

There is no notable difference between the derived and the original SVG image:

**Comment by outsideris** [comment]
Thank you.

**Comment by sisp** [comment]
You're welcome, and again, thanks for your contribution! :pray:

Just a minor question: Was there any particular reason why you force-pushed the second commit? Typically, there's no need for force-pushing (or amending commits and force-pushing). With regular commits, it's easier to track the progress of the PR and review it if you just add commits, i.e. I can better check only the changes since the last review.

**Pull request merged**
