### PR TITLE
Add Alamy

### PR DESCRIPTION
**Pull request by zcraber**
alamy

**Similarweb rank:** [3,734](https://www.similarweb.com/website/alamy.com)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo taken from the website header. Brand colour `#00ff7b` picked from the website.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I think we can get away with using the [encircled "a"](https://s.alamy.com/logos/1.68.0/safari-pinned-tab.svg) here, as they use it themselves all over social media and it's better suited to our purposes as an icon library. What do you think, @zcraber?

**Comment by zcraber** [comment]
> What do you think?

@PeterShaggyNoble Sounds great, I'll work on it! Actually, I did search for that 'a' icon before, but couldn't find the vector version.

**Comment by zcraber** [comment]
@PeterShaggyNoble Done!

**Review by adamrusted — APPROVED** [review]

**Comment by PeterShaggyNoble** [comment]
> Actually, I did search for that 'a' icon before, but couldn't find the vector version.

Spend enough time here and you'll get to the point where you're able to find vector artwork even when you're not looking for it! 😆

**Pull request merged**
