### PR TITLE
Adding files for SaltStack Icon

### PR DESCRIPTION
**Pull request by kaleeaswari**
**Issue: #1809**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Source for the icon: https://www.saltstack.com/resources/brand/

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @kaleeaswari thanks for working on this PR. 👍.

A few changes are required.

Please include in the "description" the source you used for the .svg and the reason you chose the hex value `#00EACE`.

Is there a reason you included the &#174; symbol? 

Some changes are required for the .svg file. 

- The icon is not centered in the view box.

- The icon is larger than 24px tall.

In the image below, the grey square represents the 24 x 24px viewbox if I center your icon.

saltstack

**Comment by kaleeaswari** [comment]
Hi @phatbhoy67,

Source for the icon: https://www.saltstack.com/resources/brand/
And list of colors are also mentioned in the same web page.
And the R symbol is also mentioned in the same web page as part of icon.

**Comment by phatbhoy67** [comment]
Hey @kaleeaswari thanks for updating the icon and the information 👍.

Looking at the .svg, it requires a further adjustment. Some of the icon is outside the viewbox.

If you open the file in Inkscape, select the icon, lock the aspect ratio and then set the height to 24px. Then center it again horizontally and vertically on the page. See below for how it looks now.

scrnli_27_10_2019_15-04-16

I've added the source to the description, I also added the issue reference number this PR looks to address. You can reference an issue by typing its number e.g. #1835 with a `#` at the start which will auto link back to the issue. 🎉

**Comment by phatbhoy67** [comment]
Hey @kaleeaswari thanks for making the changes requested 👍, I've requested a review, hopefully this will be merged soon! 👏

**Comment by birjolaxew** [comment]
:+1: Looks good! Thanks a lot for your work on this @kaleeaswari, and for your thorough review @phatbhoy67!

<sup>On a sidenote, you're free to merge it yourself if you're confident the PR is good @phatbhoy67  - you're a maintainer on par with all the rest of us ;)</sup>

**Pull request merged**
