### PR TITLE
Add smash.gg Icon

### PR DESCRIPTION
**Pull request by adempus**
smashgg_icon_preview

**Issue:** #5710
**Alexa rank:** 21,562 https://www.alexa.com/siteinfo/smash.gg

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @adempus. Could you let us know which file you based your version off, please? The first EPS I tried on Google Drive was just an image embedded within the file 🙄 I'll _never_ understand why people do that!

Also, could you remove the custom `slug` from the JSON and change the filename to `smashdotgg.svg`, please?

**Comment by adempus** [comment]
> Thanks for the contribution, @adempus. Could you let us know which file you based your version off, please? The first EPS I tried on Google Drive was just an image embedded within the file  I'll _never_ understand why people do that!
> 
> Also, could you remove the custom `slug` from the JSON and change the filename to `smashdotgg.svg`, please?

Done. Any reason why the file shouldn't follow the same convention observed for similar 'dot' formatting in other files?

I used the red logomark PNG file from Google Drive. Ran into issues converting the EPS files because it would generate xlink:hrefs instead of paths in the SVG result oddly. 🤔

**Review by PeterShaggyNoble — APPROVED** [review]
> I used the red logomark PNG file from Google Drive.

Nice work :+1: Everything looks good to me; the only differences I can see are down to the poor anti-aliasing in source file. Seeing as it is a manual vectorisation, though, we'll need one of the other @simple-icons/maintainers to throw an eye over it as well before merging.

> Any reason why the file shouldn't follow the same convention observed for similar 'dot' formatting in other files?

We [recently made a change](https://github.com/simple-icons/simple-icons/pull/5121) to disallow hyphens in file names but, in order to avoid that being an immediate breaking change we made exceptions for all existing files with hyphens in their file names by using the custom `slug` entry in the JSON. Those files are all [scheduled for renaming](https://github.com/simple-icons/simple-icons/pull/5611) in v5, at which stage the related `slugs` will be removed from the JSON.

**Review by ericcornelissen — APPROVED** [review]
Looks awesome, especially for a manual vectorisation, @adempus! Thank you for the contribution 🎉 

With @PeterShaggyNoble having already approved this I will merge this in.

**Pull request merged**
