### PR TITLE
Update New Japan Pro-Wrestling

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
New Japan Pro-Wrestling

**Issue:** #2784, #2791 & #4590
**Alexa rank:**  [~43.3k](https://www.alexa.com/siteinfo/njpw.co.jp) - [~363k](https://www.alexa.com/siteinfo/njpw1972.com) - [~38.6k](https://www.alexa.com/siteinfo/njpwworld.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Found a better quality source which, in turn, claims to be from an official source. Hopefully this one isn't as riddled with imperfections and passes the linter! 🤞🏻

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
Could you remove this icon from `.svglint-ignored.json` @PeterShaggyNoble?

**Comment by PeterShaggyNoble** [comment]
Done, @mondeja.

**Review by mondeja — CHANGES_REQUESTED** [review]
I'm seeing some deformations comparing against the source. It seems that have appeared trying to solve the linting issue. Could you check that @PeterShaggyNoble?

image

**Comment by PeterShaggyNoble** [comment]
Gonna have to admit defeat here and ask for help; can't figure it out at all 🤔

**Comment by PeterShaggyNoble** [comment]
Managed a workaround but had to increase the precision to 4 as a result.

**Review by mondeja — APPROVED** [review]
Now looks spot on! Nice work @PeterShaggyNoble :clap:

**Pull request merged**
