### PR TITLE
Update Meetup icon

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
image
**Issue:** #2023

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Colour lifted from SVG on media page.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble thanks for your work on this one 👍 

Can you check the level of optimisation applied to the .svg, the detail in the external corners of the big "splash" are rounded rather than "V" shaped, crudely outlined in blue below (original yellow, PR black).

Inkedrect843_LI

**Comment by PeterShaggyNoble** [comment]
Thanks, @phatboy67, will get that updated Monday.

**Comment by PeterShaggyNoble** [comment]
Upped the precision from `4` to `5`.

Possible alternative, and smaller, path which I still need to inspect for differences:

```
M7 .566C6.69 .566 6.45 .8 6.45 1.11C6.45 1.41 6.69 1.65 7 1.64C7.29 1.64 7.53 1.41 7.53 1.1C7.53 .799 7.3 .568 7 .566M13.44 1.2C12.88 1.2 12.43 1.64 12.43 2.2C12.42 2.75 12.88 3.2 13.43 3.21C14 3.21 14.43 2.76 14.43 2.21C14.43 1.65 14 1.2 13.44 1.2M10.5 3.42C10.22 3.42 9.91 3.45 9.61 3.5C7.85 3.83 6.59 4.81 5.84 6.43C5.76 6.6 5.67 6.67 5.5 6.71C3.97 7.03 2.87 8.33 2.81 9.9C2.79 10.53 2.94 11.13 3.25 11.68C3.3 11.76 3.29 11.81 3.23 11.88C2.4 12.71 2.05 13.72 2.17 14.89C2.29 15.9 2.77 16.72 3.58 17.35C4 17.7 4.5 17.92 5.05 18C5.15 18.05 5.19 18.09 5.19 18.19C5.19 18.31 5.22 18.44 5.23 18.56C5.5 20.34 7.03 21.71 8.84 21.82C9.76 21.88 10.61 21.64 11.36 21.1C11.46 21.03 11.5 21.03 11.6 21.1C12.25 21.61 13 21.83 13.79 21.71C15 21.54 15.83 20.84 16.24 19.67C16.27 19.59 16.3 19.56 16.39 19.56C16.65 19.56 16.91 19.54 17.17 19.5C19.2 19.14 20.7 17.35 20.7 15.27C20.7 14.5 20.5 13.78 20.11 13.11C20.08 13.05 20.06 13 20.13 12.95C20.86 12.24 21.1 11.38 20.81 10.4C20.58 9.61 20.05 9.08 19.27 8.79C19.19 8.76 19.17 8.73 19.17 8.64C19.19 8.41 19.18 8.18 19.15 7.95C19.03 6.91 18.61 6 17.85 5.27C16.56 4.04 15.05 3.68 13.34 4.18C13.24 4.21 13.16 4.2 13.07 4.15C12.27 3.68 11.41 3.42 10.5 3.42M4.82 4.25C4.38 4.25 4.05 4.58 4.05 5C4.05 5.45 4.39 5.79 4.81 5.79C5.25 5.79 5.58 5.44 5.58 5C5.58 4.58 5.25 4.25 4.82 4.25M20.81 6.61C20.34 6.61 19.94 7 19.94 7.5C19.95 7.95 20.33 8.32 20.8 8.32C21.28 8.32 21.67 7.94 21.66 7.47C21.66 7 21.27 6.62 20.81 6.61M12.65 7.66C12.93 7.67 13.2 7.78 13.44 8C13.54 8.09 13.63 8.19 13.73 8.28C13.87 8.4 14 8.42 14.17 8.32C14.63 8 15.14 8 15.65 8.12C16.21 8.22 16.54 8.59 16.68 9.13C16.77 9.5 16.72 9.83 16.62 10.17C16.43 10.8 16.16 11.39 15.89 12C15.62 12.61 15.34 13.22 15.12 13.86C15 14.21 14.91 14.57 14.91 14.94C14.92 15.37 15.09 15.59 15.5 15.67C15.77 15.72 16 15.76 16.28 15.81C16.36 15.82 16.45 15.85 16.53 15.88C16.76 16 16.87 16.16 16.88 16.4C16.89 16.64 16.79 16.82 16.57 16.93C16.29 17.07 16 17.09 15.68 17.08C15.26 17.06 14.85 17 14.44 16.86C13.64 16.6 13.07 15.82 13.07 14.93C13.05 14.55 13.22 14.18 13.4 13.82C13.8 12.96 14.22 12.1 14.63 11.24C14.7 11.09 14.76 10.93 14.82 10.78C14.85 10.71 14.87 10.63 14.88 10.55C14.88 10.4 14.87 10.25 14.73 10.17C14.58 10.09 14.42 10.1 14.27 10.19C14.11 10.29 14 10.45 13.93 10.61C13.69 11.05 13.46 11.5 13.23 11.95L11.76 14.85C11.62 15.13 11.43 15.38 11.12 15.5C10.85 15.59 10.58 15.57 10.33 15.46C10.07 15.35 9.95 15.07 10 14.76C10.03 14.58 10.1 14.42 10.17 14.25C10.5 13.42 10.83 12.59 11.16 11.76C11.24 11.56 11.32 11.37 11.34 11.15C11.36 10.95 11.31 10.77 11.16 10.63C10.9 10.4 10.5 10.5 10.33 10.86C10.18 11.21 10.05 11.55 9.91 11.9C9.4 13.16 8.93 14.43 8.4 15.68C8.24 16.06 8 16.39 7.59 16.5C7.08 16.67 6.58 16.6 6.13 16.31C5.55 15.94 5.3 15.27 5.5 14.58C5.97 13.04 6.41 11.5 6.96 10C7.08 9.67 7.2 9.35 7.36 9.04C7.7 8.33 8.5 7.87 9.3 7.94C9.54 7.96 9.75 8.08 9.97 8.18C10.19 8.28 10.41 8.37 10.62 8.5C10.84 8.6 11.03 8.57 11.23 8.44C11.46 8.3 11.63 8.1 11.83 7.94C12.09 7.74 12.37 7.65 12.65 7.66M23.5 9.69C23.27 9.69 23.05 9.91 23.04 10.17C23.04 10.43 23.26 10.65 23.53 10.65C23.79 10.65 24 10.44 24 10.18C24 9.91 23.79 9.7 23.5 9.69M1 10.5C.447 10.5 0 10.95 0 11.5C0 12.07 .447 12.5 1 12.53C1.56 12.53 2.03 12.06 2 11.5C2 10.96 1.56 10.5 1 10.5M22.31 12.59C21.96 12.59 21.66 12.89 21.66 13.24C21.66 13.58 21.95 13.87 22.3 13.87C22.66 13.87 22.94 13.6 22.94 13.24C22.94 12.88 22.66 12.59 22.31 12.59M4.07 18.68C3.81 18.68 3.6 18.9 3.6 19.16C3.6 19.43 3.81 19.63 4.08 19.63C4.34 19.63 4.55 19.42 4.55 19.15C4.55 18.9 4.33 18.68 4.07 18.68M17.75 20.23C17.16 20.23 16.69 20.7 16.68 21.29C16.68 21.86 17.17 22.35 17.74 22.35C18.33 22.35 18.81 21.87 18.81 21.28C18.81 20.71 18.33 20.23 17.75 20.23M11.41 22.13C11.04 22.13 10.75 22.42 10.75 22.79C10.75 23.15 11.04 23.43 11.41 23.43C11.77 23.43 12.07 23.15 12.07 22.79C12.07 22.43 11.78 22.13 11.41 22.13Z
```

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble thanks for looking at the .svg again 👍 

I think I may have twigged what the issue might be. What source are you using? The [icon](https://www.meetup.com/mu_static/en-US/logo--mSwarm--2color.4ff7188b.svg) from this [page](https://www.meetup.com/media/) i.e. the icon above the link to download the logo pack?

If so, confusingly 😖 that version does not match the .ai or .pdf version available in the [M Swarm](https://s3.amazonaws.com/com.meetup.prod.brand/Meetup_logo_package.zip) download pack (which I've been trying to match the PR against  😭 ).

I think the downloadable version has to win on this occasion, can you use either it as source and update the PR please.

**Comment by PeterShaggyNoble** [comment]
Ah-ha, that explains it, so. Sadly, I don't have the first clue (nor, I imagine, the necessary tools) how to convert an `.ai` or `.pdf` to SVG! 😆

**Comment by PeterShaggyNoble** [comment]
Managed to get the AI converted to SVG and have updated the PR with that path data. Also, from that AI, it looks like the colour should be `#ed1c40`, as it originally was so I've also updated that.

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @PeterShaggyNoble 👍 

The .svg is great and I agree with your updated colour choice.

Ps. You can usually extract embedded svg from .pdf files by opening them in [Inkscape](https://inkscape.org/release/inkscape-0.92.4/).

[Adobe XD](https://www.adobe.com/uk/products/xd.html) will let you [open/import](https://helpx.adobe.com/uk/xd/help/working-with-external-assets.html) .ai files which you can then export as .svg. Both are free.

**Comment by PeterShaggyNoble** [comment]
> Ps. You can usually extract embedded svg from .pdf files by opening them in Inkscape.

Thanks for the tip, @phatbhoy67.

**Pull request merged**
