### PR TITLE
Add Shenzhen Metro

### PR DESCRIPTION
**Pull request by mondeja**
shenzhenmetro

**Issue:** #2822

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Logo from [Wikipedia](https://en.wikipedia.org/wiki/Shenzhen_Metro#/media/File:Shenzhen_Metro_Corporation_logo_full.svg) English page.
- Hex value from logo file.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Nice work, @mondeja :+1: The SVG looks good to me. However, I wonder if we shouldn't fix the issue of the two outermost "feet" not touching the bottom of the canvas in order to match the "arms"?

I think we should use `#009943` for the colour, as that's what they use on [their website](https://www.szmc.net/).

Other than that, can you update the source URL to https://en.wikipedia.org/wiki/File:Shenzhen_Metro_Corporation_logo_full.svg?

**Comment by ericcornelissen** [comment]
> I wonder if we shouldn't fix the issue of the two outermost "feet" not touching the bottom of the canvas in order to match the "arms"?

From [the logo on the homepage](https://www.szmc.net/home/a/C1585217473517S.png) I would say yes :thinking: 

> I think we should use #009943 for the colour, as that's what they use on their website.

Without proper guidelines, I think either the current and the suggested value would work as a color for this brand. I would personally lean to the slightly lighter `#13A034` that is currently in the metadata.

**Comment by PeterShaggyNoble** [comment]
Where are you seeing the `#13a034` colour, @ericcornelissen? I can't find it in the HTML of either the Chinese or English homepages.

**Comment by ericcornelissen** [comment]
> Where are you seeing the #13a034 colour? I can't find it in the HTML of either the Chinese or English homepages.

From the SVG itself.

**Comment by PeterShaggyNoble** [comment]
Ah, sorry, thought you meant their site's metadata! 🤦‍♂️

**Comment by mondeja** [comment]
I've opted for `#009943` in the new commit and updated the preview. Let me know if you prefer `#13a034`.

**Pull request merged**
