### PR TITLE
Add Sabanci icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
image

**Issue:** #6332 
**Alexa rank:** 476,880
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
From the website https://www.sabanci.com/en and Wiki https://en.m.wikipedia.org/wiki/File:Sabanc%C4%B1_Holding_logo.svg

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
@dirien  did you use the PNG on the web site or the SVG in the wikipedia page?

**Comment by dirien** [comment]
hi @jorgeamadosoria, in this case wikipedia

**Comment by jorgeamadosoria** [comment]
I see slight differences:
image

also, your version has a height of 12.322 vs a wiki height of 12.313. What transformations did you apply to the circles?

**Comment by adamrusted** [comment]
@jorgeamadosoria @dirien these _slight_ differences could be caused by SVGO - especially on the circular shapes. Worth re-exporting from source, and optimizing with a higher precision (4 instead of 3) to see if that fixes it.

**Comment by dirien** [comment]
@jorgeamadosoria update icon with precision 4

**Review by jorgeamadosoria — APPROVED** [review]
Excellent. LGTM

**Pull request merged**
