### PR TITLE
Added Cognizant

### LINKED ISSUE #4312: Request: Cognizant Icon
**Name:** Cognizant 
**Website:** https://www.cognizant.com/
**Alexa rank:** 4,417
  

**Official resources for icon and color:** https://www.cognizant.com/

### PR DESCRIPTION
**Pull request by adamrusted**
cognizant

Fixes #4312
**Alexa rank:** [4,355](https://www.alexa.com/siteinfo/cognizant.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Used SVG and Hex from website.
Adapted in Adobe Illustrator.
Optimized using SVGOMG.
Ran through SVGlint.

### CODE REVIEW

**Comment by fbernhart** [comment]
@adamrusted All the letters match perfectly, BUT the "o". 😄  Can you have a look at it?


image

**Comment by adamrusted** [comment]
@fbernhart done - needed a precision of 4 to keep the 'O' in correct shape.

**Comment by fbernhart** [comment]
@adamrusted Hmm ... You're using Illustrator, right? Might be that Inkscape is sometimes behaving a bit differently. 😄 I had no problem to create a union and optimise it with a precision of 3, while still keeping the "o" in place.

I've pushed my version - I hope you don't mind. Maybe double check and feel free to merge it. 😊

**Comment by adamrusted** [comment]
> @adamrusted Hmm ... You're using Illustrator, right? Might be that Inkscape is sometimes behaving a bit differently. 😄 I had no problem to create a union and optimise it with a precision of 3, while still keeping the "o" in place.

Strange. I was outputting with 7 points of precision from Illustrator, and comparing that to the SVGOMG result as 'basically source', and only 4 would work. Ah well, I'll try and use Inkscape for a few more I guess 😅

**Pull request merged**
