### PR TITLE
Added LOT Polish Airlines

### LINKED ISSUE #2587: [COLLECT] Airlines
- [x] Aer Lingus (#2607)
- [x] Aeroflot (#4881)
- [x] Aeroméxico (#4760)
- [x] Air Asia (#4892)
- [x] Air Canada (#2833)
- [x] Air China (#4799)
- [x] Air France (#2891)
- [x] Alitalia (#4808)
- [x] All Nippon Airways (ANA) (#4821)
- [x] American Airlines (#2827)
- [x] British Airways (#4908)
- [x] China Eastern (#4827)
- [x] China Southern (#4837)
- [x] Delta (#4844)
- [x] easyJet (#2598)
- [x] Emirates (#4862)
- [x] Ethiopian Airlines (#4909)
- [x] Etihad (#4957)
- [x] KLM (#2588)
- [x] Lion Air (#4959)
- [x] LOT (#5221)
- [x] Lufthansa (#2113)
- [x] Norwegian Air (#5145)
- [x] Pegasus (#5144)
- [x] Qantas (#2839)
- [x] Qatar Airways (#4869)
- [x] Ryanair (#2606)
- [x] S7 (#4888)
- [x] Southwest (#2896)
- [x] TUI (#2851)
- [x] Turkish Airlines (#1527)
- [x] United (#2803)
- [x] Wizz Air (#2847)

others:
- [ ] PanAm ? :D – just for the chuckles, and as a "retro" brand

---

See [wikipedia](https://en.wikipedia.org/wiki/Largest_airlines_in_the_world).

### PR DESCRIPTION
**Pull request by adamrusted**
lotpolishairlines

**Issue:** Fixes #2587
**Alexa rank:** [60,692](https://www.alexa.com/siteinfo/lot.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG pulled from page 3 of [this PDF](https://d6u0ytoepgi6w.cloudfront.net/Kaleidoscope/Kaleidoscope-202102.pdf), and some imperfections cleared up. Hex pulled from button on source page.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I'm seeing some hairline thin differences in quite a few places, @adamrusted, dunno if it's an optimisation issue or a result of cleaning up the imperfections. If the latter, I'm happy to run with it as-is but could you try with a precision of 3 first?

And, for the colour, both the Polish and English logos in the header use `#1a3171` so I think we should go with that.

**Comment by adamrusted** [comment]
Almost certainly down to optimization. Let me rebuild and export to 4 decimals, see how that looks.

**Comment by adamrusted** [comment]
Try that @PeterShaggyNoble - got rid of all the weird joins between the circle and the icon, and (hopefully) lined them up again pretty okay.

**Comment by PeterShaggyNoble** [comment]
I'm still seeing some differences, @adamrusted (some examples below, with yours in red). Given that you've already increased the precision, it's looking more likely that it's as a result of fixing the problems in the original.

- [inner left of the circle](https://user-images.githubusercontent.com/15157491/111335493-57a5b680-866c-11eb-80b9-54abc15f0efe.png)
- [inner top of the circle](https://user-images.githubusercontent.com/15157491/111335612-6ee4a400-866c-11eb-862e-2444e6a1b80f.png)
- [tail of the plane](https://user-images.githubusercontent.com/15157491/111335754-8c197280-866c-11eb-85ad-bdf45e8d0d04.png)
- [curve of bottom wing](https://user-images.githubusercontent.com/15157491/111335866-a3f0f680-866c-11eb-879d-fa4804e8dab8.png)

**Comment by adamrusted** [comment]
Would we be happy to run with those differences, as a 'fix of the source icon', @PeterShaggyNoble?
Or shall I try and get this version a bit closer to the original?

**Comment by PeterShaggyNoble** [comment]
Other than [the one in the tail of the plane](https://user-images.githubusercontent.com/15157491/111335754-8c197280-866c-11eb-85ad-bdf45e8d0d04.png) which is just a bit too significant in my opinion, I'd be happy to run with the other minor differences if they've arisen as a result of fixing issues in the source icon 👍🏻

**Comment by adamrusted** [comment]
@PeterShaggyNoble - give that another shot. I've compared against the original, and it looks okay on my end.

**Pull request merged**
