### PR TITLE
Added Vaadin icon

### LINKED ISSUE #4968: Request: Vaadin
**Brand Name:** Vaadin
**Website:** https://vaadin.com/
**Alexa rank:** [57,498](https://www.alexa.com/siteinfo/vaadin.com)
**Official resources for icon and color:** https://vaadin.com/trademark

### PR DESCRIPTION
**Pull request by litetex**
Fixes #4968

grafik

**Issue:** Contributes to #4968 
**Alexa rank:** [56,117](https://www.alexa.com/siteinfo/vaadin.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
* Icon is based on https://cdn2.hubspot.net/hubfs/1840687/Pages/trademark/vaadin-logo-1.svg
* Alternative would be https://github.com/vaadin/vaadin-icons/blob/master/assets/svg/vaadin-h.svg, but the svg is currently damaged → see [vaadin/vaadin-icons#97](https://git.io/Jtig0)
* Resized, centered and removed the color

### CODE REVIEW

**Comment by service-paradis** [comment]
Thank you @litetex for your contribution 🎉!

The PDF logo listed at https://vaadin.com/trademark is pretty good and should be used as the official source.
I found some differences comparing your version with the symbol found in this PDF (example below with your version overlayed).
image

**Comment by litetex** [comment]
@service-paradis 
Thank you for the feedback.

It took me some time to extract the svg and convert it, because the contribution process isn't that easy too understand und implementable.
I'm not animated to do it all once again.

Apparently you are more familiar with these processes.
So if the (in my opinion minimal; see [vaadin/vaadin-icons#97](https://git.io/Jtig0) for bigger problems) deviation does not correspond to the required quality, you are welcome to take over the further development of this icon.

**Comment by PeterShaggyNoble** [comment]
Give this path a try, @litetex. Also, could you update the `source` to match the `guidelines` while you're at it, please?

```
M1.166.521C.506.521 0 1.055 0 1.715v1.97c0 2.316 1.054 3.473 3.502 3.473h5.43c1.623 0 1.783.685 1.783 1.35 0 .068.004.13.012.193a1.268 1.268 0 0 0 2.531-.004c.007-.062.012-.121.012-.19 0-.664.16-1.349 1.783-1.349h5.43C22.93 7.158 24 6.001 24 3.686V1.715c0-.66-.524-1.194-1.184-1.194-.66 0-1.189.534-1.189 1.194l-.004.685c0 .746-.476 1.27-1.594 1.27h-5.322c-2.422 0-2.608 1.796-2.687 2.748h-.055c-.08-.952-.266-2.748-2.688-2.748H3.955c-1.118 0-1.629-.544-1.629-1.29v-.665c0-.66-.5-1.194-1.16-1.194zm5.875 10.553a1.586 1.586 0 0 0-1.375 2.371c1.657 3.06 3.308 6.13 4.967 9.184a1.415 1.415 0 0 0 2.586.02l.033-.06 4.945-9.142a1.587 1.587 0 0 0-1.377-2.373c-.702 0-1.179.345-1.502 1.082l-3.386 6.313-3.383-6.305c-.326-.745-.805-1.09-1.508-1.09Z
```

**Comment by litetex** [comment]
@PeterShaggyNoble 
Thank you for the path 🎉 

Updated the PR as requested.

**Comment by PeterShaggyNoble** [comment]
Thanks, @litetex. As you're now using the path I provided, though, we'll need one of the other @simple-icons/maintainers to review this before merging it.

**Comment by service-paradis** [comment]
Thanks @litetex for your work!
There is one extra point that could be removed, but if @PeterShaggyNoble is OK with it, we can merge this one :)
image

**Comment by PeterShaggyNoble** [comment]
Tried a few things to clean that up, @service-paradis but they all distorted the bottom curve of the "v".

**Pull request merged**
