### PR TITLE
Add Lidl icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** https://github.com/simple-icons/simple-icons/issues/5852
**Alexa rank:** 5,447
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
No external ressources available, i work for the Schwarz Group (parent holding of the brand Lidl) and the icon and main color is according internal guidelines.

You can check the svg on the official homepage -> https://www.lidl.de/

### CODE REVIEW

**Comment by dirien** [comment]
@adamrusted : Even more fancy to merge? 😄

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for your work on this, @dirien - though there is a _tiny_ segment of the `i` which could be joined up to the `D` to make the path a lot simpler. (See [here](https://user-images.githubusercontent.com/1830867/121770740-0e79db80-cb63-11eb-8ffe-c25ac6c557a0.png) for the segment in question). You should be able to just drag those two points of the `i` under the `D` before you unite the paths. Also, it may be worth looking at an alternative treatment (such as the below) to make the icon clearer at smaller sizes.

lidl

**Comment by dirien** [comment]
Update like you said @adamrusted, Hope you like it. There rest i would like to let it like it is, to not mess with corporate identiy 😄 



image

**Comment by adamrusted** [comment]
Any other @simple-icons/maintainers got an opinion on this before I do a full review of the icon as is?

**Comment by service-paradis** [comment]
Since @dirien is working for the parent company of the brand, I would review the given icon if it is in line with their internal guidelines.

**Comment by dirien** [comment]
Thanks for the Feedback @adamrusted  and @service-paradis! The way the icon is designed is quite fix. As you can see on https://www.lidl.de/. From FavIcon to normal Pictures. 

I can see, that is tricky when its get extremly scaled down. But it is as it is 😓

**Comment by PeterShaggyNoble** [comment]
Yep, I agree with @service-paradis; as this is coming from an official source, we should follow @dirien's treatment. (Although I do agree that a treatment like @adamrusted's would look better).

I'm noticing some differences in [the "D"](https://user-images.githubusercontent.com/15157491/122556565-949a9400-d033-11eb-87a0-32baba76a3a8.png) and [the left edge of the circle](https://user-images.githubusercontent.com/15157491/122556654-aed47200-d033-11eb-991b-05a0509845f4.png) when comparing you version (in red in both cases) with [the logo](https://www.lidl.de/imgs/lidl-logo-svg.svg) found in the website header. However, as you _are_ an official source and you based your version off one from the official, internal guidelines then if you say we can run with those differences then this can be merged straight in.

**Comment by dirien** [comment]
Sounds good! 😀

**Comment by dirien** [comment]
hi @adamrusted , would you mind to merge it for any release? :)

**Comment by adamrusted** [comment]
Hey @dirien, sorry - work has been a bit mad recently. I should have some time ahead of this next release to get it reviewed and merged, but am back in the office today. It's on my to-do list though.

**Comment by dirien** [comment]
@adamrusted oh sorry, did not want to sound pushy or demanding. I was just crurious about the state of the PR, as there where some discussions and if you need some feedback from me. So i could prepare myselft for this.

**Comment by adamrusted** [comment]
No worries! 😂
As I say, should be good to review ahead of this weekends release.

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for this, @dirien - finally able to take a look at this PR!
It appears there are some small issues, both in the [D shape](https://user-images.githubusercontent.com/1830867/124350361-3bfaf780-dbec-11eb-8d4e-f6c56c2e1e33.png), and the [circle around the logo](https://user-images.githubusercontent.com/1830867/124350368-461cf600-dbec-11eb-9d24-b32d48b1fd1e.png) which may just be down to an optimization. Could you try exporting this again and, if necessary, upping the precision to 4 decimals?

**Pull request closed without merging**
