### PR TITLE
Updated Delicious

### PR DESCRIPTION
**Pull request by adamrusted**
delicious (1)

**Issue:** Contributes to #3169
**Alexa rank:** [74,351](https://www.alexa.com/siteinfo/icio.us)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Changed source to official website.
Built from scratch, added border to define edges of shape.
Color updated to blue used on website.

### CODE REVIEW

**Comment by fbernhart** [comment]
Just wondering, how about such an approach with a gap of 0.5px between color changes? Would this better represent [Delicous](http://del.icio.us/) or is this already Microsoft? 😂  @simple-icons/maintainers opinions?

delicious

**Comment by PeterShaggyNoble** [comment]
Yeah, that's definitely too close to Microsoft to me, @fbernhart. I also don't think that outlining the lighter regions is the way to go either; our current treatment works better for me.

We should also probably flag this one for monitoring for potential removal if it doesn't come back online.

**Comment by adamrusted** [comment]
> I also don't think that outlining the lighter regions is the way to go either; our current treatment works better for me.

Fine by me - I'll remove the edit to the SVG, and just update the source.

> We should also probably flag this one for monitoring for potential removal if it doesn't come back online.

Happy to hold fire on the merging on this until we get a better idea of what's going on. Given it's been down since mid-December, I'd say we give it until mid-February / early March for them to update in some way.

**Comment by fbernhart** [comment]
I would still merge it now and just recheck before releasing v5.0 at the end of May.

If by then the website is still not up and the Alexa rank has dropped out of scope, we can still create a new PR to remove it.

**Comment by adamrusted** [comment]
Should be good to go. Just removed the icon - left the website as source and updated colour though.

**Comment by PeterShaggyNoble** [comment]
If, come v5, we _are_ able to keep this one then it should be renamed as "del.icio.us".

**Pull request merged**
