### PR TITLE
Add Org

### LINKED ISSUE #4845: Request: Org mode
**Project:** Org (`.org` files)
**Website:** https://orgmode.org/
**Alexa rank:** 247,154 
  

**Official resources for icon and color:**
Theme colors (`#77aa99` / `#587e71`) be seen on the home page and in the icon. As for the icon:
- color: https://orgmode.org/resources/img/org-mode-unicorn.svg
- color, borderless: https://orgmode.org/resources/img/org-mode-unicorn-borderless.svg
- colour, reduced detail: https://orgmode.org/resources/img/org-mode-unicorn-borderless-icon.svg
- monochrome: https://orgmode.org/resources/img/favicons/safari-pinned-tab.svg
  

**Additional information**

Org is a 17 year old project / markup format with first-class support in Emacs (as this is where the 'reference implementation' is), and alternative parsers found in various applications (Github uses `org-ruby` for rendering `.org` files, Hugo uses `go-org`, etc.).

I am involved with the Org project, and oversaw an overhaul of the main site (see the footer).

### PR DESCRIPTION
**Pull request by tecosaur**
org

**Issue:** Closes #4845
**Alexa rank:** ~250k

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Project Homepage: https://orgmode.org
Source image: ~~https://orgmode.org/resources/img/org-mode-unicorn-borderless-icon.svg~~ https://orgmode.org/resources/img/org-mode-unicorn-borderless.svg

Spatial separation between body and mane used in place of chromatic separation.

A little bit more background info can be found in the issue.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Hmm ... Looks like the next thing we have to decide on here is the name. Other than the name used in the PR, they seem to use the following 3 variants with fairly equal consistency on their homepage:
1. Org Mode
2. Org mode
3. Org-mode

**Comment by tecosaur** [comment]
What's that saying...
> There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors
:stuck_out_tongue: 

`-mode` is a suffix that relates to the format's origin as an Emacs mode. Most references to it simply call it "Org" though, for example it's "Org" [to GitHub](https://github.com/github/linguist/blob/299318747a903a90581f46e637f7d3be387ff844/lib/linguist/languages.yml#L3868), [Pandoc](https://pandoc.org/org.html), [Hugo](https://gohugo.io/content-management/formats/), etc. and the de facto mime type is `text/org` (see homepage).

I should probably make the homepage more consistent with those 3 variants, but I think the use of "Org" is rather well-established at this point. If you'd like to insist on using an "org mode" variant, then `Org mode` would be the most correct form.

**Comment by PeterShaggyNoble** [comment]
> If you'd like to insist on using an "org mode" variant

Seeing as you're more familiar with the brand and, more importantly, involved with their project, I'm happy to run with just "Org".

There are quite a few differences between the original and your version (in red below) but as it's an original interpretation and given your association with them, I'm happy to run with it as-is. We will need approval from one of the other @simple-icons/maintainers or, preferably, a member of the Org team before we can merge it, though.

**Comment by tecosaur** [comment]
> Seeing as you're more familiar with the brand and, more importantly, involved with their project, I'm happy to run with just "Org".

Easy. Really, I don't think you could go wrong with either "Org" or "Org mode", but I figure why not go with the shorter and simpler version — particularly when it seems to have been used as the label by a number of other entities.

> There are quite a few differences between the original and your version (in red below)

Since this icon collection seems to want small icon files, I reduced the number of points in the icon then tried to adjust the splines to be as close to the original as possible. As you've picked up, there are a number of small differences, but I feel they keep close enough to the original that you can't really tell by eye without overlaying the two.

I suppose at this point we just wait for someone else to chime in?

**Comment by tecosaur** [comment]
I've actually just had another look at the difference between this and the published icon (borderless variant), and managed to reduce the difference to something I'd consider completely negligible:
##### Overlay: Borderless icon (7.3kb, solid monochrome green) on bottom, Spline-reduced PR'd version (1.4kb, transparent grey) on top
image

I'll be pushing this shortly. Should help make this easier to merge :slightly_smiling_face:

**Comment by adamrusted** [comment]
> I've actually just had another look at the difference between this and the published icon (borderless variant), and managed to reduce the difference to something I'd consider completely negligible.

Any chance you could link to the borderless variant used so I can compare? 🙏🏻

**Comment by tecosaur** [comment]
Sure, it's the same as linked in the original issue: https://orgmode.org/resources/img/org-mode-unicorn-borderless.svg

**Comment by adamrusted** [comment]
Looks good to me against that version. I'll update your post above to link to this version - as the 'borderless-icon' variant has a fair few differences to this shape! Will wait for another @simple-icons/maintainers to sign off on it though before we merge it.

**Comment by PeterShaggyNoble** [comment]
The only major difference I'm noticing now is where the ear meets the mane. Also it would be nice if we could match the outline of the horn. Couple of minor differences around the eye and mouth, too, but as this is an original interpretation, I think we can let them slide.

Then again, with Adam already approving it, if one of the other @simple-icons/maintainers is OK with those differences, we can merge this in.

**Comment by tecosaur** [comment]
So ... at this point, we're just waiting for a third person to approve this?

**Comment by PeterShaggyNoble** [comment]
Yep, just to confirm whether we should run with it as-is or fix the 2 minor issues I mentioned above. Alternatively, if you'd to ping a member of the Org team for their feedback, we can merge it straight in if it meets with their approval.

**Comment by tecosaur** [comment]
Eh, I don't think it's worth contacting the whole mailing list over the small difference. If it makes it possible to merge immediately I could probably have a look at removing that small difference. Otherwise, I'll just sit and wait for a third simple-icons person to say it looks good to them :slightly_smiling_face:.

**Comment by adamrusted** [comment]
@tecosaur - I've just had a quick play with this in Affinity following @PeterShaggyNoble's comments, and come out with the below path, which _should_ work for the horn. Not sure on the mane, though I guess that's entirely up to interpretation.

org
```svg
M9.77 6.313a18.7 18.7 0 0 1 .281-.698c.046-.154.099-.268.155-.35.347-.5.851.223.927.723.007.085.023.164.043.238a.079.079 0 0 1 .028-.05c.51-.12.915-.19 1.238-.228l.021-.236c0-.736.515-1.23.78-1.23.093 0 .155.06.155.19-.003.592.193 1.03.395 1.27.104-.188.284-.36.46-.473-.13-.377-.167-.476.451-.888-.283-.45.373-.926.466-1.13-.183-.414.331-.762.55-1.032-.309-.605.669-.888.554-1.081-.003-.34.322-.541.575-1.001.103-.232.225-.336.309-.337.108-.001.153.166.015.446-.063.403.028.75-.372 1.008l.003.124c.004.283-.013.858-.402.88.039.373.026.9-.424 1.003.154.353.103.798-.271.94.066.253.141.979-.323.978h-.011c.147.286.09.772-.283.875 0 0 .104.26.021.435.16.066.327.14.493.207.088.035.175.068.262.096.631.02.86.22.895.405a.286.286 0 0 1-.051.223h-.001s.978.623 2.152.787c.536.045 1.622-.048 2.729.15.483-.343.887-.157.919.326.095.17.371.31.374.774.001.102-.012.219-.042.355-.315.626-.382.494-1.011.904l-.026-.028a2.151 2.151 0 0 1-.455.26c-.124.054-.241.096-.308.095-.123-.001-.232-.084-.358-.164-.138-.088-.294-.174-.496-.174-.699 0-1.131.22-1.285.322l-.092.06.109.01c.101.01.215-.03.342-.06.176-.043.382-.066.628.114.308.327.595.458.844.49.25.032.464-.037.627-.113.289-.087.379-.27.424-.327.082-.108.063-.202.043-.286-.014-.058-.031-.111.018-.161l.005-.004c.705 1.104-.608 1.475-1.58 1.475-.327 0-.616-.042-.776-.112a2.488 2.488 0 0 0-.873-.144c-.448.002-.887.09-1.378.09-.266 0-.547-.025-.854-.104-.589.869-1.275 1.115-1.863 1.114-.768-.001-1.369-.422-1.369-.422-.168.777-1.636 2.974.702 4.25 3.763 2.18 5.636 6.9 5.362 6.903-.014 0-.034-.012-.06-.038-.291-.213-2.426-2.76-6.279-2.766a9.82 9.82 0 0 0-2.699.39l-.035.01c-2.169.67-3.725.243-4.817-.528l-.217-.163a5.994 5.994 0 0 1-1.381-1.597 1.357 1.357 0 0 1-.054-.027.8.8 0 0 0 .081-.221c.19-.96 1.238-1.824 2.079-2.411.373-.26.75-.746 1.164-1.32.579-.8 1.243-1.776 2.133-2.461.681-.524.873-1.245.833-1.99-.037-.688-.279-1.396-.482-1.952-.105-.287-.09-.71-.03-1.16.065-.493.191-1.018.313-1.453zm-.722.869a8.143 8.143 0 0 0-.087.519c-.072.542-.07 1.05.056 1.397.188.515.419 1.169.453 1.808.032.583-.105 1.155-.639 1.566-.929.715-1.629 1.729-2.233 2.565-.375.519-.708.967-1.046 1.203-.938.654-2.07 1.652-2.283 2.723a.342.342 0 0 1-.018.06 5.19 5.19 0 0 1-.188-.138c-.532-.351-.927-.897-1.216-1.515l-.168-.396-.001-.003c-.504-1.314-.595-2.812-.551-3.42.188-2.42 2.996-4.955 4.463-5.073.852-.07 1.494-.202 1.986-.367.798-.27 1.203-.623 1.472-.93zm5.894 1.293c.007-.005.025-.017.045-.04a.768.768 0 0 0 .164-.07.06.06 0 0 0 .021-.028.057.057 0 0 0 .011-.06.059.059 0 0 0-.065-.035c-.447.087-1.456.093-2.163-.171a.057.057 0 0 0-.072.029.058.058 0 0 0 .023.075c.054.03.334.127.417.163.01.04.019.08.046.126.047.08.149.176.428.3l.006.004c.244.076.53.087.753.05.158-.026.286-.08.353-.145a.052.052 0 0 0 .016-.037 1.99 1.99 0 0 1 .017-.161z
```

Will wait for another @simple-icons/maintainers to take a look at this too - but should this path be preferred, you're more than welcome to use it.

**Comment by tecosaur** [comment]
Thanks @adamalston :slightly_smiling_face:. I have mixed feelings on that, on one hand, it's more accurate to the outline, on the other, I'm not sure whether it fits well with the overall "simplified" look.

**Comment by adamrusted** [comment]
Completely get your concern @tecosaur - though with icons such as [Elsevier](https://simpleicons.org/?q=elsevier) included in the library I don't think we need to worry about the level of detail included in the above. 😅

Will wait and see what the other @simple-icons/maintainers think though, before any changes are requested 👍🏻

**Comment by tecosaur** [comment]
Hehe. I'd like to see the person who can make a simplified version of Elsevier's logo :laughing:. Thanks for your work and I'll wait for other people to chime in.

I personally still hold a preference for the simpler version, but I expect the main use to be small icons, and from what I can tell they both look identical at that sort of size.

**Comment by PeterShaggyNoble** [comment]
That looks good to me, @adamrusted :+1: @tecosaur, if you can update the PR version to match (or use Adam's path if you prefer) then we can get this merged in.

**Comment by tecosaur** [comment]
So to confirm @PeterShaggyNoble, you're not happy with the simple horn, but if that has the detail added as in adam's mock-up you're happy to merge?

I still think that given the simplification applied to the rest of the design that the simplified horn style fits best, but after waiting three weeks I'll compromise to get this merged at last.

**Comment by PeterShaggyNoble** [comment]
Any of the other @simple-icons/maintainers have a preference on how we should treat the horn before asking @tecosaur to update?

**Comment by mondeja** [comment]
Seeing both versions, I like the horn of the @adamrusted version but not the mane, that line is too much subjective. So I suggest either use, if it looks good, the original complex mane adding the corresponding gap, using @adamrusted's version (if he want to do that additional job), otherwise check @tecosaur's version against the simplified one. What is the reason for having simplified the mane instead of using the line of the simplified version or the line of the mane without simplifying @adamrusted?

**Comment by adamrusted** [comment]
> Seeing both versions, I like the horn of the @adamrusted version but not the mane, that line is too much subjective. So I suggest either use, if it looks good, the original complex mane adding the corresponding gap, using @adamrusted's version (if he want to do that additional job), otherwise check @tecosaur's version against the simplified one. What is the reason for having simplified the mane instead of using the line of the simplified version or the line of the mane without simplifying @adamrusted?

I drew a _very rough_ line where the path of the mane went, building from the source SVG again. Thought that the mane was indeed far too busy for us to do it justice in the monochrome fashion. Happy for the two to be spliced together if that's the preferred route.

**Comment by adamrusted** [comment]
Returning to this - if I were to use the outlined version, and try to keep as much fidelity to the logo as possible, the below is the result. Happy to optimize this path if @simple-icons/maintainers would prefer the full-res version?

**Comment by tecosaur** [comment]
I feel the need to make a comment here, there is a fundamental issue when translating this multi-colour design into a monochrome form, in that simply copying the edges erases much of the difference between different components of the logo (particularly at small image sizes, as seems to be the primary use).

This is why in this PR I have used a mane that doesn't match the edges of the full-colour version — I feel that it is actually more faithful to the logo than the strict edge-copy that @adamrusted has kindly produced.

You (simple icons maintainers) may insist on matching the lines as closely as possible, but I think this effect deserves some consideration.

**Comment by mondeja** [comment]
Given the opinion of @tecosaur, that is Org contributor, plus the fact that the gap of the mane in @adamrusted's version can't be increased without loss a lot of precision of the geometry, I vote for the simplified version of @tecosaur.

**Comment by fbernhart** [comment]
Agreeing with @mondeja here.

**Review by adamrusted — APPROVED** [review]
As previously stated I'm also okay with @tecosaur's treatment of the icon, so am happy to merge as-is based on @mondeja and @fbernhart's comments. Could another @simple-icons/maintainers take a quick look over it too, just to make sure we're all good without @tecosaur having to do any additional work on it?

**Comment by PeterShaggyNoble** [comment]
OK, let's run with it as-is so. Thanks for your continued efforts and patience on this one, @tecosaur 👍🏻

**Pull request merged**
