### PR TITLE
Added Composer icon

### PR DESCRIPTION
**Pull request by JoaoPedroMoraes**
**Issue:** #1480 

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
From the official SVG I was able to create a monocolor version. https://getcomposer.org/

the svg logo was removed from that issue [composer/composer#4403](https://github.com/composer/composer/issues/4403)

### CODE REVIEW

**Comment by birjolaxew** [comment]
Not sure I'm a fan of the checkering on the shirt. Pinging for opinion from @ericcornelissen @davidklebanoff

**Comment by davidklebanoff** [comment]
The [PNG icon](https://getcomposer.org/img/logo-composer-transparent3.png) on the official website's homepage has the checkered pattern inverted such that the lines are filled in rather than the squares in between. Perhaps that would be more true to the source?

**Comment by birjolaxew** [comment]
@davidklebanoff The logo on the homepage actually cycles between 5 different versions, which can be found [in their website repo](https://github.com/composer/getcomposer.org/tree/master/web/img)

<p align="center"></p>

**Comment by JoaoPedroMoraes** [comment]
vote for which one you like best! @davidklebanoff @birjolaxew 

Captura de Tela_selecionar área_20190630184112

**Comment by JoaoPedroMoraes** [comment]
> vote no que você mais gosta! @davidklebanoff @birjolaxew
> 
> Captura de Tela_selecionar área_20190630184112

What color do I use? because I did not find reference to this

**Comment by birjolaxew** [comment]
@JoaoPedroMoraes I think the current color `#885630` (from the hair of the official SVG) is just fine.

I think I prefer version 1. It's a lot less busy and, in my opinion, recognizable, and should work decently at small sizes.

**Comment by ericcornelissen** [comment]
Both 1 and 3 are fine by me @JoaoPedroMoraes :)

**Comment by ericcornelissen** [comment]
Thanks a bunch for working on this @JoaoPedroMoraes 😄

**Pull request merged**
