### PR TITLE
Add nf-core icon

### LINKED ISSUE #12463: Request: nf-core
### Brand Name

nf-core

### Website

https://nf-co.re

### Popularity Metric

- The Similarweb global rank is # 408,177 https://www.similarweb.com/website/nf-co.re/

### Official Resources for Icon and Color

- SVG: https://github.com/nf-core/logos/blob/master/nf-core-logos/nf-core-logo-square.svg
- Primary Colour: #24B064

### Additional Comments

More information on the:
- Logo: https://nf-co.re/docs/guidelines/graphic_design/logo
- Colours: https://nf-co.re/docs/guidelines/graphic_design/colours

I am a core-team member of nf-core (see [here](https://nf-co.re/governance#core-team) ), and this brand is very closely associated to the recently added Nextflow icon (nf-core is an open-source community working out of Nextflow)

### PR DESCRIPTION
**Pull request by jfy133**
image

**Issue:** closes #12463

**Popularity metric:**  Similarweb global rank is # 408,177 https://www.similarweb.com/website/nf-co.re/

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Adds logo for the nf-core community organisation (associated to the recently added Nextflow icon).

I am ['core team' member](https://nf-co.re/governance) of the community, and adds this on behalf of the community.

Linting results:

```
> svglint --ci --config svglint.config.mjs icons/*.svg

------------------------------------------- Files -------------------------------------------
x icons/nfcore.svg
  x attr-3 0:93 Found extra attributes ["style"] with whitelisting enabled
                  At node <path> (0:93)

------------------------------------------ Summary ------------------------------------------
✓ 3247 valid files.
x 1 invalid files.
```

I tried to fix this, but I have a feeling there is something I don't know about the behaviour between Inkscape and SVG (i.e. if I remove the style attribute manually from the SVG file XML, then the icon doesn't get displayed, I guess because the fill is not set correctly).

### CODE REVIEW

**Comment by LitoMore** [comment]
Hi @jfy133, thank you for contributing to Simple Icons.

> I tried to fix this, but I have a feeling there is something I don't know about the behaviour between Inkscape and SVG (i.e. if I remove the style attribute manually from the SVG file XML, then the icon doesn't get displayed, I guess because the fill is not set correctly).

Just simply remove all the style attribute:

```diff
-style="fill:#ffffff;stroke:none;stroke-width:0.00104378;stroke-linecap:round;stroke-dasharray:none;paint-order:stroke markers fill"
```

**Comment by jfy133** [comment]
Aha! Thank you very much @LitoMore not sure what I had been doing before when I tried exactly that - but indeed works now!

Local lint now passes :)

```

------------------------------------------------------------------------------------------ Summary ------------------------------------------------------------------------------------------
✓ 3248 valid files.

> simple-icons@14.0.1 wslint
> editorconfig-checker

Downloading v3.0.3

> simple-icons@14.0.1 markdownlint
> markdownlint-cli2 '**/*.md' '#node_modules'

markdownlint-cli2 v0.15.0 (markdownlint v0.36.1)
Finding: **/*.md !node_modules
Linting: 8 file(s)
Summary: 0 error(s)
```

**Comment by LitoMore** [comment]
I can see some differences:



It looks like the icon has been stretched. Can you check it?

Here is [how do I review differences](https://github.com/simple-icons/simple-icons/discussions/9351) in case you want to review it on your local.

**Comment by jfy133** [comment]
You were correct! I guess I made a mistake when trying to satisfying linting, and had to re-scale multiple times because Inkscape kept adding +0.001 pxs half the time :roll_eyes: 

Following your difference reviewing docs (very nice and concise btw!), and in outline mode with new icon on top and then below:

image
image

Hopefully this should now be good to go :crossed_fingers:

**Comment by jfy133** [comment]
And for completeness, linting still satisfied:

```
------------------------------------------------------------------------------------------ Summary ------------------------------------------------------------------------------------------
✓ 3248 valid files.

> simple-icons@14.0.1 wslint
> editorconfig-checker


> simple-icons@14.0.1 markdownlint
> markdownlint-cli2 '**/*.md' '#node_modules'

markdownlint-cli2 v0.15.0 (markdownlint v0.36.1)
Finding: **/*.md !node_modules
Linting: 8 file(s)
Summary: 0 error(s)
```

Thanks again @LitoMore !

**Review by LitoMore — APPROVED** [review]
@jfy133 Perfect fit! Congrats on your first contribution to Simple Icons!

**Comment by jfy133** [comment]
Thank you!!

**Comment by jfy133** [comment]
Hi @LitoMore out of curiosity, do you know approximately how long it takes for the icon to be displayed on the website?

I want to test a live example of one of the uses to the rest of the community :grimacing:

**Comment by LitoMore** [comment]
We usually create a release PR on Sunday, like #12460, and below is the code of our scheduled script:

https://github.com/simple-icons/simple-icons/blob/86ee3f263aa0884c6f3e901172c5efe4e3f32326/.github/workflows/create-release.yml#L6-L8

At that time, I review the PR and merge it. After that our release bot will automatically publish updates to npm and other platforms.

For our icons on [shields.io](https://shields.io). Their updates are usually a week behind ours, which means you will see updates on shields.io a week after our release. You can refer to their [how are Icon updates scheduled](https://github.com/badges/shields/discussions/5369) for more details.

Today is Monday, so it should be about two weeks before your icons are available on shields.io.

**Comment by jfy133** [comment]
Ok perfect, thank you very much!

**Pull request merged**
