### PR TITLE
Updated Sentry

### PR DESCRIPTION
**Pull request by fbernhart**
sentry

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Looks like they've updated their primary colour. Could you look to change to `#323366` please?

**Comment by fbernhart** [comment]
@adamrusted Why `#323366`? 🤔  The logo itself has the color `#362D59`.

**Comment by adamrusted** [comment]
> @adamrusted Why `#323366`? 🤔 The logo itself has the color `#362D59`. --> [sentry.io/branding](https://sentry.io/branding) as well as the SVG in the header.

Don't mind me! 🙃
Let's go with `#362D59`

**Comment by fbernhart** [comment]
@adamrusted Done

sentry

**Review by adamrusted — APPROVED** [review]
LGTM! ⚠

**Pull request merged**
