### PR TITLE
Updated Steem

### PR DESCRIPTION
**Pull request by fbernhart**
steem

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by service-paradis** [comment]
According to https://steem.com/brand/, I think we can update the source and the color. I would probably choose `#171fc9`.
Logos can also be downloaded here. I'm asking if we should keep the circle.
Maybe, we can merge this one and open a new issue about the update? What do you think?

**Comment by fbernhart** [comment]
@service-paradis I would keep the circle as well.

Color and source have indeed to be updated.

I prefer pushing the new icon to this PR. Is that ok?

**Comment by service-paradis** [comment]
> I prefer pushing the new icon to this PR. Is that ok?

Sure 😄

**Comment by fbernhart** [comment]
steem

**Review by service-paradis — APPROVED** [review]
Perfect, thank you! 💯

**Pull request merged**
