### PR TITLE
Cinema4d icon

### PR DESCRIPTION
**Pull request by massamino**
**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Manually vectorized

### CODE REVIEW

**Comment by foo-dogsquared** [comment]
Alexa ranking: [~20k](https://www.alexa.com/siteinfo/maxon.net) for the parent company (Maxon). 

I am a bit familiar with the tool and it is considered as one of the common choices for 3D modelling. 
Also, it's not likely to be rejected since it is one of their popular products, after all. 

For clarification, where you did get the icon? 
I found [a press kit page](https://www.maxon.net/de/header-meta-navigation/ueber-maxon/pressematerial/) that contains the EPS of the logo (although no monochrome version of the logomark so far).

**Comment by PeterShaggyNoble** [comment]
@foo-dogsquared, should the name not be just "Cinema 4D"?

**Comment by foo-dogsquared** [comment]
I don't think there would be any naming conflicts with this so we'll go with "Cinema 4D". 

Please update the name in the JSON file instead @massamino as @PeterShaggyNoble suggested.

**Comment by PeterShaggyNoble** [comment]
You'll also need to update the `title` tag in the SVG to match.

And the source URL in the JSON should be where you sourced the original artwork.

**Comment by runxel** [comment]
Hey @massamino!
Welcome to simple-icons and thank you very much for your PR! 🎉 

The others already gave some good advice to improve it so we can merge this bad boy in! 😎 
Thanks! 👋

**Comment by massamino** [comment]
Tnx, I'll fix it. I couldn't open the kit on my mac to check for logo files, so I made it from scratch.

**Comment by massamino** [comment]
@PeterShaggyNoble should the source point to the presskit page then?

**Comment by massamino** [comment]
What am I doing wrong. The build failed. I can't see a typo and all is renamed to "Cinema 4D" ...

**Comment by PeterShaggyNoble** [comment]
Thanks for updating, @massamino. I'd agree with that choice for the source URL.

The build is failing because Cinema 4D is not in the correct spot in the JSON, which needs to be sorted alphabetically by title.

**Comment by massamino** [comment]
OK, sorry, didn't know that. I'll fix that as well :)

**Comment by PeterShaggyNoble** [comment]
It's a brand spanking new addition to our linting :wink: We have plans in place to automate the sorting so the build won't fail in future.

**Comment by massamino** [comment]
Fixed. Thanks for your help.

**Comment by PeterShaggyNoble** [comment]
Thanks for sorting all that out, @massamino :+1:

Now we just have to decide if we're happy with this monochrome treatment of the icon. I'll defer to @foo-dogsquared on the final call as he's familiar with the software. I really like [this version](https://www.deviantart.com/physxpsp/art/Cinema-4D-Metro-logo-344402024) of it, though, so maybe we could do something similar?

Cinema 4D by PhysXPSP

**Comment by massamino** [comment]
I saw that version as well when I was searching for a svg icon for the software. For me this version has to little contrast. That's why I choose to make the dark side of the 'c' transparent to reflect that. But if the final decision is to use the full white one, I'll fix the errors in the screenshot and use your version.

**Comment by runxel** [comment]
I would follow your argumentation. The monochromization is well done and I like the look more then the too dense version Peter found.

> I saw that version as well when I was searching for a svg icon for the software. For me this version has to little contrast. That's why I choose to make the dark side of the 'c' transparent to reflect that. But if the final decision is to use the full white one, I'll fix the errors in the screenshot and use your version.


However I can't agree on the color being black.
_I_ would have suspected it to be `#011a6a` matching the blue orb.

**Comment by massamino** [comment]
@runxel I would agree if I could find that color as a main color on their website. I was looking for a different match than black to, but couldn't find it. I can see a blue color on the website, but it doesn't match the blue orb. I'll check again :)

**Comment by runxel** [comment]
I wouldn't give so much attention to the website in this case.
The page is rather bland, nothing to gain there.

But yes, I understand that the decision is not so easy, since there is also no flat icon version.

**Comment by massamino** [comment]
I'll change the color to the suggested orb color.

**Comment by PeterShaggyNoble** [comment]
If we're all agreed that the current version is better then that works for me too 👍 Nice work, @massamino

**Pull request merged**
