### PR TITLE
Added Taobao

### LINKED ISSUE #3297: Taobao
**Name:** Taobao
**Website:** taobao.com
**Alexa rank:** 9
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by adamrusted**
taobao

**Issue:** Closes #3297
**Alexa rank:** [8](https://www.alexa.com/siteinfo/taobao.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Converted PNG found at source to SVG.

### CODE REVIEW

**Comment by fbernhart** [comment]
How about using this PDF (page 19) as official source for a vectorized version?
https://doc.irasia.com/listco/hk/alibabagroup/annual/2020/ar2020.pdf

As you've manually converted the PNG, I assume there might be quite some differences to the PDF linked above.

**Comment by adamrusted** [comment]
taobao

@fbernhart rebuilt from new source, which also included a new HEX.

**Comment by fbernhart** [comment]
@adamrusted Looks good, but there is one small difference: The circle in the right glyph. Could you have a look at it?

image

**Comment by adamrusted** [comment]
@fbernhart should be fixed, though had to use a precision of 4 to get the circle to optimize properly.

**Comment by fbernhart** [comment]
@adamrusted Thanks 👍🏼  LGTM!

**Pull request merged**
