### PR TITLE
BHIM UPI icon

### PR DESCRIPTION
**Pull request by adsingh14**
**Issue:** #6936
**Alexa rank:** 126,928
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

bhimupi

### CODE REVIEW

**Comment by adsingh14** [comment]
@service-paradis I hope you've checked this icon ?

**Review by sachinraja — CHANGES_REQUESTED** [review]
Guidelines available at https://www.bhimupi.org.in/sites/default/files/BHIM%20UPI%20Guidelines.pdf. Source at https://www.npci.org.in/npci-in-news/knowledge-centre ("BHIM UPI all logo formats").
Comparison with source above shows a difference:
image

**Comment by adsingh14** [comment]
> Guidelines available at https://www.bhimupi.org.in/sites/default/files/BHIM%20UPI%20Guidelines.pdf. Source at https://www.npci.org.in/npci-in-news/knowledge-centre ("BHIM UPI all logo formats").
> Comparison with source above shows a difference:
> image
> 

Please check 'Additional Comments' from #6936.

Refer. to 
page3logo

**Comment by adsingh14** [comment]
@sachinraja Several changes will be made after getting permission from official. Until then, I'll keep it close.

**Pull request closed without merging**
