### PR TITLE
New Icon: DaisyUI

### LINKED ISSUE #7865: Request: daisyUI
### Brand Name

daisyUI

### Website

https://daisyui.com

### Popularity Metric

The Similarweb rank is 79,046 https://www.similarweb.com/website/daisyui.com
14.5k stars on GitHub https://github.com/saadeghi/daisyui

### Official Resources for Icon and Color

svg: https://raw.githubusercontent.com/saadeghi/files/main/daisyui/logo-4.svg
color: `#5A0EF8`, from the GitHub page's logo

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by TheInfamousGrim**
Added the DaisyUI svg:
    - Made the icon monochromatic
    - Compounded paths
    - Centered the icon
    - Made the viewbox 24 by 24
    - Icon width is 24px
    - Icon was optimized using the SVGOMG Online tool
    - Annotated the icon to the correct paramenters

Added the JSON data for DaisyUI icon.

**Issue**: closes #7865 

**Similarweb rank:** : 91,490

### Preview

Preview of Icon

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Hex values were picked from the original logo, it was the primary color of the daisy word
- Edited in Adobe Illustrator
- Only used the single source

### CODE REVIEW

**Comment by TheInfamousGrim** [comment]
How do I link the issue to  Request: daisyUI #7865? I'm new to this and need a little help

**Comment by ripzerotwo** [comment]
So technically, you already have linked the PR to the issue request. Whenever a PR mentions an issue via "#...." that issue will get linked.

**Comment by TheInfamousGrim** [comment]
@ripzerotwo Thanks for the help! realized I didn't put it as closing the issue haha

**Review by dirien — APPROVED** [review]
Hi @TheInfamousGrim ,

Thanks for your contribution to simple-icons!

It's a perfect fit:

**Pull request merged**
