### PR TITLE
Update Xcode

### PR DESCRIPTION
**Pull request by adamrusted**
xcode

**Issue:** Contributes to #5251.
**Alexa rank:** N/A (Apple Subdomain)

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
New monochrome icon found at source.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for this one, @adamrusted; SVG looks perfect to me 👍🏻

Before merging though, do we also want to take the opportunity to review the colour? Not sure where we sourced it originally. The blue they use on [their site](https://developer.apple.com/xcode/) is `#0066cc` but it doesn't look to be the primary colour to me. The blue from their full colour icon is probably what we should go for but that may be tricky to get right as it's a gradient and all versions seem to be raster files. Apple's black could be another option but that doesn't really feel right to me.

**Comment by service-paradis** [comment]
Good job @adamrusted! Glad to see an official monochrome treatment for this one!
For the color, I dont find any official resources. There is color that comes often when searching for "ios palette" or "xcode palette": `#147EFB`.

**Comment by adamrusted** [comment]
Good to go @service-paradis

**Comment by service-paradis** [comment]
Thank you @adamrusted, 
since I dont find any official source supporting this color (or this palette), I will wait to see what @PeterShaggyNoble thinks about it.

**Comment by PeterShaggyNoble** [comment]
In the absence of anything official stating otherwise, I think that's as good a choice as any so happy to merge this as-is. Nice work, @adamrusted 👍🏻

**Pull request merged**
