### PR TITLE
Add Google Ads logo

### PR DESCRIPTION
**Pull request by el1f**
**Issue:** #1676 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
ads
Here it is. Opinions?

### CODE REVIEW

**Comment by birjolaxew** [comment]
This looks good to me! I like the monochromization you've done here a lot (and thanks for the work!), but given that that's a subjective thing, I'll let another @simple-icons/maintainers merge this in.

**Comment by el1f** [comment]
TBF that's for the better. I realized that there actually happens to be a monochromatic version of the Ads logo on the Google MyBusiness dashboard. You can see it in the attached screenshot.
Which one should we use?

image

**Comment by birjolaxew** [comment]
@el1f If there is an official monochrome version, we'd definitely prefer using that one. Good find! If you update the PR, I'll get this merged in.

**Comment by el1f** [comment]
I will go ahead and try to either extract it directly from there or trace it if it's not an SVG. Will update you tomorrow morning

**Comment by el1f** [comment]
Done @birjolaxew

**Comment by birjolaxew** [comment]
:+1: Thansk a lot @el1f!

**Pull request merged**
