### PR TITLE
add Trusted Shops Icon

### LINKED ISSUE #3275: Request: Trusted Shops
**Name:** Trusted Shops
**Website:** https://trustedshops.de
**Alexa rank:** 76,212
  

**Official resources for icon and color:**
https://brand.trustedshops.com/d/dorIFVeUmcN9/corporate-design#/basic-elements/logo-1573044308/symbol

### PR DESCRIPTION
**Pull request by oliverpitsch**
Trusted Shops

**Issue:** Closes #3275
**Name:** Trusted Shops
**Website:** https://trustedshops.de
**Alexa rank:** 76,212

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG _⟶ Optimised via SVGOMG, but the shape gets distorted every time. Had to keep it as the original <path>_
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Hex Value: `#FFDC0F` ⟶ See https://brand.trustedshops.com/d/dorIFVeUmcN9/corporate-design#/basic-elements/colours

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one on, @oliverpitsch.

Before we start into reviewing it though, you say:
> Optimised via SVGOMG, but the shape gets distorted every time. Had to keep it as the original

What precision were you using? Those issues can usually be solved by increasing it by 1 until it lines up with the original again.

**Comment by oliverpitsch** [comment]
@PeterShaggyNoble Thank you for that tip. Worked after increasing the precision. The path is now optimized with SVGOMG.

**Comment by PeterShaggyNoble** [comment]
Thanks for the quick update 🙂

The build is currently failing on the following two points, though:
1. Both paths should be merged into one, single path.
2. The `<title>` tag in the SVG should be "[BRAND] icon" so, in this case "Trusted Shops icon".

I'd also suggest updating the source URL to just https://brand.trustedshops.com/d/dorIFVeUmcN9/corporate-design

**Comment by PeterShaggyNoble** [comment]
Which file did you base your SVG on, @oliverpitsch, so we can make sure we're comparing it to the same version?

**Comment by oliverpitsch** [comment]
I hope I understand your question right, @PeterShaggyNoble. It's basically the same mark as in `Trusted-Shops_Symbol_e_square.svg`. The one I used is coming straight from our design system, but comparing them should lead to the same result. :)

**Comment by PeterShaggyNoble** [comment]
Your SVG looks perfect when compared to that version, @oliverpitsch :+1:

However, it would seem that a precision of 3 is sufficient here:
```
M15.187 14.332c-1.1 1.626-2.63 3.108-4.687 3.108-2.175 0-3.442-1.362-3.442-3.562 0-3.561 2.63-7.052 6.335-7.052 1.242 0 2.916.502 2.916 2.009 0 2.7-4.231 3.609-6.311 4.135-.072.457-.143.908-.143 1.362 0 .933.501 1.793 1.53 1.793 1.338 0 2.412-1.29 3.203-2.247zm-1.148-5.808c0-.55-.31-.978-.884-.978-1.722 0-2.608 3.346-2.94 4.66 1.601-.48 3.824-1.794 3.824-3.682zM12 0a12 12 0 1 0 12 11.997A11.997 11.997 0 0 0 12 0zm-.1 19.523a7.563 7.563 0 1 1 7.564-7.563 7.563 7.563 0 0 1-7.563 7.56Z
```

**Comment by oliverpitsch** [comment]
@PeterShaggyNoble Sorry for the delayed response here. Is there anything I can do at the moment or is the ball now in your playing field?

**Comment by PeterShaggyNoble** [comment]
Could you update to a lower precision, please, @oliverpitsch? You can grab the path data I posted above, if you like.

**Comment by PeterShaggyNoble** [comment]
Thanks for the quick update, @oliverpitsch :+1: As you're using the path I provided now, we'll need one of the other @simple-icons/maintainers to throw another eye over this before it can be merged in.

**Comment by ericcornelissen** [comment]
Thanks for the contribution @oliverpitsch! It is very much appreciated 🎉

**Pull request merged**
