### PR TITLE
Add iFood

### LINKED ISSUE #2167: Icon request: iFood
**Name:** iFood
**Website:** https://ifood.com.br
**Official resources for icon and color:** #ea1d2c

This site has a svg logo inside html. I got it and saved in .svg file.

[ifood.zip](https://github.com/simple-icons/simple-icons/files/3981297/ifood.zip)

About: Ifood is the largest food delivery service in Latin America, with 2 millions orders per month.

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
iFood

**Issue:** Closes #2167

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon & colour found in website footer.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble can you check the optimisation for this one, I'm getting a few small path differences, see example below:

ifood-diff

**Comment by PeterShaggyNoble** [comment]
Nice catch, @phatboy67. I won't be back at a computer for a few days yet so, in the interests of getting this off the board, if you want to update the path data in the PR - either directly or by review - feel free to do so.

**Comment by PeterShaggyNoble** [comment]
Icon updated

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @PeterShaggyNoble 👍

**Pull request merged**
