### PR TITLE
Css hover

### PR DESCRIPTION
**Pull request by ezzzin**
**Issue:**#1124

### Checklist
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by ericcornelissen** [comment]
For anyone interested in what this looks like here is a preview (tip for you @ezzzin, when you change something visually, include a screenshot or video of the change 😉):

preview

**Comment by RedSparr0w** [comment]
👍 

It looks pretty good, but maybe a slightly more subtle effect will look nicer?
`scale(1.1)`:



`scale(1.05)`:

shields

Or just scale the icons & name:

**Comment by ericcornelissen** [comment]
Thanks for mocking up different styles @RedSparr0w, I like your last idea, but I would limit it to just the icon (or scale up the hex-value as well)

**Comment by ericcornelissen** [comment]
If anyone wants to add hover effects, I suggest reviewing the discussion here and perhaps first discussing your idea in #1124, I'm closing this pull request for now.

**Pull request closed without merging**
