### PR TITLE
Add Buildkite

### PR DESCRIPTION
**Pull request by JuanitoFatas**
Buildkite is the fastest, most secure way to test and deploy code at any scale.
https://buildkite.com/

simpleicons

**Issue:** 

#3437

**Alexa rank:**

69,719 (as of UTC 12:02 PM Tuesday, August 11, 2020)

### Checklist

  - [x] Add SVG
  - [x] Add preview from [here](https://petershaggynoble.github.io/MDI-Sandbox/simpleicons/preview/)
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Icon and colour choice from our design team at Buildkite.

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
@PeterShaggyNoble @runxel This is ready for review. Thank you 😊

**Comment by runxel** [comment]
Hi @JuanitoFatas! Thank you for this PR!
However, as you can see, the build is currently failing.
First it misses the `role` attribute and a `title` tag.
Also it seems that the path is not centered on the canvas right now.

Please have a look at our [Contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#5-check-the-icon) and fix those issues, then we are good to go. 😊

**Comment by JuanitoFatas** [comment]
@runxel Thanks for the tips, great catch! Added the role, title, and centered in e2e9a1d...3f0967e.  Thank you! ☺️

**Comment by runxel** [comment]
Very good! 💯
The build is passing – and since you're representing the brand there are no questions left :)
I will happily merge this one in. Thanks again for this PR! Have a great day 👋

**Comment by HariSekhon** [comment]
Great, do you know how long before it appears on https://simpleicons.org/ and is usable?

**Comment by runxel** [comment]
@HariSekhon We do our releases every ~2 weeks.
Please note that [shields.io](https://shields.io) is not as fast, tho. It can take up to one month until it is available there.

**Pull request merged**
