### PR TITLE
Request: read.cv

### LINKED ISSUE #8362: Request: read.cv
### Brand Name

read.cv

### Website

https://read.cv

### Popularity Metric

The Similarweb rank is 140,798. See https://www.similarweb.com/website/read.cv

### Official Resources for Icon and Color

- svg: `https://www.dropbox.com/s/6hu732q4v56zte3/icon.svg`

- color: `#111111`

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by 5ouma**
readdotcv

**Issue:** closes #8362

**Similarweb rank:** 140,798

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo link is [here](https://read.cv/support/vcY96F2GqbvLOdKkWl0I).
The actual SVG file is in [Dropbox](https://www.dropbox.com/s/6hu732q4v56zte3/icon.svg).

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @5ouma,

thanks for the contribution. I see a difference in the icon:

image

**Comment by 5ouma** [comment]
When I run `npm run svglint`, it says like this.
```
x icons/readdotcv.svg
  x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 21.438 x 23.041
  x icon-centered <path> must be centered at (12, 12); the center is currently (10.829, 12.043)
```
Could you tell me how to solve this, please?

**Comment by LitoMore** [comment]
@5ouma You could try to increase the precision when running `svgo`.

**Comment by LitoMore** [comment]
Hi @5ouma, it seems you still need to fix the stretched issue. There is no need to keep your branch updated with develop branch right now.

**Comment by 5ouma** [comment]
Thank you @LitoMore!!
I finally solved the problem.

**Comment by 5ouma** [comment]
@dirien
Could you review this PR again?
I fix the issue and it must be resolved.

**Comment by LitoMore** [comment]
Hey @5ouma, we maintain this project at free time. We will review your PR when we have time. Thank you for your patience.

**Comment by 5ouma** [comment]
I'm sorry to hurry you up.😅
I'll be waiting patiently.

**Review by dirien — APPROVED** [review]
Hi @5ouma,

Thanks for your contribution to simple-icons!

It's a perfect fit:
image

**Comment by 5ouma** [comment]
Thank you very much!!

**Pull request merged**
