### PR TITLE
Add Directus icon (#2136)

### PR DESCRIPTION
**Pull request by phatbhoy67**
**Issue: #2136**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO ~or SVGOMG~
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Source is [official .svg](https://directus.io/img/assets/directus-flat.svg) available to download from [website](https://directus.io/resources.html).

Hex value `#263238` used on the [directus website](https://directus.io/).

### CODE REVIEW

**Comment by runxel** [comment]
Yeah, I'd vote for `#37474F` ...

**Comment by PeterShaggyNoble** [comment]
As per my comment in #2136, my vote goes to `#263238`.

**Comment by phatbhoy67** [comment]
In the brand [style guide](https://docs.directus.io/guides/style-guide.html#example-color-aliases) it mentions they use the [material design color palette](https://www.materialui.co/colors) and provide examples of aliases used in their styling including:
`--brand: var(--blue-grey-900);` 

which is [`#263238`](https://www.materialui.co/colors/blue-grey/900).

Its also used as the background colour for these:

apple touch apple touch
favicon favicon
ico .ico

And in source of their website: 

`<meta name="msapplication-TileColor" content="#263238">`
`<meta name="theme-color" content="#263238">`

I do like `#37474F` though.

**Comment by ericcornelissen** [comment]
Given your explanations (@PeterShaggyNoble and @phatbhoy67) I agree it should be `#263238` 👍

**Pull request merged**
