### PR TITLE
Updated MailChimp

### PR DESCRIPTION
**Pull request by fbernhart**
mailchimp

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
I'm seeing slight differences with the original souce. Have you rebuilted from source @fbernhart? If not, could you rebuilt it using the source?

**Comment by fbernhart** [comment]
@mondeja No, I haven't. I've used the one that was already part of Simple Icons.

I'll rebuild it from source. 👍🏼

**Comment by fbernhart** [comment]
@mondeja Done 👍🏼

**Review by mondeja — APPROVED** [review]
Perfect :monkey_face:

**Pull request merged**
