### PR TITLE
Added Chef Icon

### PR DESCRIPTION
**Pull request by sohammondal**
**Issue:** #1500

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

1. Extracted the logo from using svg-grabber from [https://www.chef.io/](https://www.chef.io/)
2. Optimized the icon
    1. Got the brand hex color code from IcoMoon - ico
    2. Performed remaining tasks like isolating the icon, changing icon's viewBox to 24x24, etc using InkScape
3. Optimized the icon using SVGO CLI Tool
4. Annotated the icon properly
5. Updated src code and tested in Gitpod.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Thanks for your work on this @sohammondal! And congratulations on your first open source contribution 🎉

**Comment by sohammondal** [comment]
> PR looks good @sohammondal! Very good job on everything , and the description is really helpful 🙂 Also, nice to see that people are actually using [our Gitpod](https://gitpod.io/#https://github.com/simple-icons/simple-icons) 🎉
> 
> I just want to give you some general tips regarding git and GitHub
> 
> * You can configure your local git setup so that commits include metadata about you so that GitHub can link the commit to your account. Right now, if you look at your commits, it has a generic GitHub icon rather than your avatar. [Read more here](https://help.github.com/en/articles/setting-your-commit-email-address#setting-your-commit-email-address-in-git).
> * You can link to issues (and pull requests) on GitHub using `#`, so to reference the issue with number 1500 you just put `#1500`, so #1500 (I changed it for you in the pull request description).

Noted.  Thanks. 🙂

**Comment by sohammondal** [comment]
> Thanks for your work on this @sohammondal! And congratulations on your first open source contribution 🎉

@ericcornelissen Thank you so much for the opportunity. :smiley:

**Comment by ericcornelissen** [comment]
> When can I expect to see the update live?

I'm expecting next weekend 😉

**Pull request merged**
