### PR TITLE
Add Byju's

### LINKED ISSUE #3954: Request: BYJU'S Icon
**Name:**  BYJU'S
**Website:** https://byjus.com/
**Alexa rank:** 961
  

**Official resources for icon and color:** https://byjus.com/

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Byju's

**Issue:** Closes #3954
**Alexa rank:** [~953](https://www.alexa.com/siteinfo/byjus.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon & colour from first SVG provided by @service-paradis in the original issue, using the treatment seen in the PNGs.

### CODE REVIEW

**Review by mondeja — CHANGES_REQUESTED** [review]
In general, the geometry fits almost perfectly, I'm just looking at a double coordinate that should be joined. Could you fix it  @PeterShaggyNoble?

image

**Comment by PeterShaggyNoble** [comment]
Removing or joining those 2 points introduces [a difference](https://user-images.githubusercontent.com/15157491/110322421-03b32600-800b-11eb-9ef4-ec35131b4863.png) in the lower half of the inner "B" shape, @mondeja.

**Comment by mondeja** [comment]
I'm able to remove the left coordinate and then adjust the curve of the right according to the original path:

image

**Comment by PeterShaggyNoble** [comment]
Yep, was able to fix that too, @mondeja but [these differences](https://user-images.githubusercontent.com/15157491/110324620-209d2880-800e-11eb-9b06-6b3a7af8329e.png) I wasn't able to fix properly.

**Comment by mondeja** [comment]
But those zones are unrelated, or am I missing something?

**Comment by PeterShaggyNoble** [comment]
Dunno how it happens, @mondeja but, yeah, when you delete either of those points or join them together it distorts that inner part of the "B" 🤷🏻‍♂️

**Comment by ericcornelissen** [comment]
@mondeja, where you able to confirm Peter's findings? Or else, are you okay merging this with the current version of the SVG?

**Comment by jorgeamadosoria** [comment]
@mondeja can you please revisit this?
I think it's fine merging with the double coordinate. It's better than dealing with differences without a clear cause.

**Review by mondeja — APPROVED** [review]
Revisiting this just now. Let's go ahead 👍🏼

**Pull request merged**
