### PR TITLE
Update TrainerRoad Icon

### LINKED ISSUE #5932: Update TrainerRoad
**Brand Name:** TrainerRoad
**Official resources for icon and color:** The official logo of TrainerRoad, is `#d9291c`. Also See below in the TrainerRoad homepage.

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** Close #5932
**Alexa rank:** [~61k](https://www.alexa.com/siteinfo/trainerroad.com)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I took `Logos/Print/TrainerRoad-Logo-Primary.eps` from the Zip files found at https://www.trainerroad.com/press/
- I used Inkscape to scale and adjust
- I used https://jakearchibald.github.io/svgomg/ to optimize
- I took the red color mentioned in the guidelines found in the Zip file

### CODE REVIEW

**Comment by ericcornelissen** [comment]
I'm seeing some minor differences at [the top](https://user-images.githubusercontent.com/3742559/127570421-c6518491-a76a-41a2-9d25-e2fa43a1c4bb.png) and [the bottom](https://user-images.githubusercontent.com/3742559/127570446-fac53a6a-e6e4-477a-af4c-aa9cb4d8936e.png) (black is your version). However, I'm comparing to the top logo on page 10 of the brand guidelines because my Inkscape didn't want to open the `.eps`... Did you compare your SVG to the original @service-paradis? Did you encounter any difficulty trying to open the `.eps`?

**Comment by service-paradis** [comment]
> I'm seeing some minor differences at [the top](https://user-images.githubusercontent.com/3742559/127570421-c6518491-a76a-41a2-9d25-e2fa43a1c4bb.png) and [the bottom](https://user-images.githubusercontent.com/3742559/127570446-fac53a6a-e6e4-477a-af4c-aa9cb4d8936e.png) (black is your version). However, I'm comparing to the top logo on page 10 of the brand guidelines because my Inkscape didn't want to open the `.eps`... Did you compare your SVG to the original @service-paradis? Did you encounter any difficulty trying to open the `.eps`?

Thank you @ericcornelissen for the review!
I used Illustrator to open and convert the `.eps` to SVG. I will try to take another look at it this week to be sure nothing went wrong during the conversion!

**Comment by service-paradis** [comment]
I started again from scratch. I think it should be better now! If not, I really need to verify the conversion process!

**Review by ericcornelissen — APPROVED** [review]
Not entirely sure what's going on here. I firstly compared to the same logo from the PDF and it again didn't line up (same as before). Then I used some online tool to convert the EPS to an SVG and that does line up!

I'm happy to run with this and assume that both our approaches correctly converts the EPS to SVG, but I'll leave merging this up to you @service-paradis (in case you disagree and want to investigate further).

**Comment by service-paradis** [comment]
> Not entirely sure what's going on here. I firstly compared to the same logo from the PDF and it again didn't line up (same as before). Then I used some online tool to convert the EPS to an SVG and that does line up!
> 
> I'm happy to run with this and assume that both our approaches correctly converts the EPS to SVG, but I'll leave merging this up to you @service-paradis (in case you disagree and want to investigate further).

Thank you @ericcornelissen for your time! I gave this a few more tries to be sure and I think we are good to go.

**Pull request merged**
