### PR TITLE
Add Ruff icon

### LINKED ISSUE #8366: Ruff
### Brand Name

ruff

### Website

https://beta.ruff.rs

### Popularity Metric

8.8k GH stars as of 2023-02-20

### Official Resources for Icon and Color

https://github.com/charliermarsh/ruff/tree/4ddcdd02d668a9f095b803ba0a4f0f4f404b7be6/assets/badge

68747470733a2f2f696d672e736869656c64732e696f2f656e64706f696e743f75726c3d68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f636861726c6965726d617273682f727566662f6d61696e2f6173736574732f62616467652f76312e6a736f6e

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by MicaelJarniac**
ruff

**Issue:** closes #8366

[Repo](https://github.com/charliermarsh/ruff): GitHub Repo stars

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by MicaelJarniac** [comment]
I believe `transform` isn't supported, will fix it.

**Comment by MicaelJarniac** [comment]
I saw the linting errors and will try to fix them.

One of them seems to be because the GitHub web editor added a new line at the end of the file, which should be easy to fix.

The other one seems to be about the icon not being exactly centered I guess, will see if I can figure it out.

**Comment by MicaelJarniac** [comment]
Well, I've removed the newline for now. Am not quite sure how to fix the other issue, though.

**Comment by MicaelJarniac** [comment]
I think I've fixed it.

**Comment by dushmanta05** [comment]
Hi, I'm facing linting errors. How can I fix them? Can you please help? Thanks.

**Comment by dushmanta05** [comment]
Sorry sir.

**Comment by MicaelJarniac** [comment]
@dushmanta05 I think you can open a discussion to ask for help:
https://github.com/simple-icons/simple-icons/discussions/categories/help-with-svgs
Link to your PR and include the original SVG file, your attempt, and the linting errors you're getting.

**Comment by dushmanta05** [comment]
Okay, thank you for the information; I appreciate it.

**Pull request merged**
