### PR TITLE
Add Tauri icon

### PR DESCRIPTION
**Pull request by JonasKruckenberg**
tauri

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo for [Tauri](https://github.com/tauri-apps/tauri). I am a member of the Tauri team.

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
thank you for the contribution, @JonasKruckenberg !
Regarding the source, can you please point to the PNG, SVG or other source image you got this from in your repo? If the source is in Github we can have it linked directly to the file and not to the general repo.

**Comment by JonasKruckenberg** [comment]
> Regarding the source, can you please point to the PNG, SVG or other source image you got this from in your repo? If the source is in Github we can have it linked directly to the file and not to the general repo.

Sure!

**Comment by jorgeamadosoria** [comment]
> > Regarding the source, can you please point to the PNG, SVG or other source image you got this from in your repo? If the source is in Github we can have it linked directly to the file and not to the general repo.
> 
> Sure!
> 
> Should it point to a permalink or is normal fine?

permalink, please, thank you!

**Comment by JonasKruckenberg** [comment]
> permalink, please, thank you!

Done!

**Comment by jorgeamadosoria** [comment]
LGTM!

**Pull request merged**
