### PR TITLE
Added Dynatrace icon

### PR DESCRIPTION
**Pull request by JoaoPedroMoraes**
**Issue:** #1416 

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
From the official SVG I was able to create a monocolor version. https://www.dynatrace.com/

### CODE REVIEW

**Comment by birjolaxew** [comment]
Although the logo looks good, I don't agree with the brand color chosen for this PR. As [discussed in the issue](https://github.com/simple-icons/simple-icons/issues/1416#issuecomment-493795391), they seem to use 4 colors for their brand. I agree with @ericcornelissen that we would probably want either `#1496FF` or `#6F2DA8` - my personal preference is the blue one. Thoughts @ericcornelissen @davidklebanoff ?

**Comment by davidklebanoff** [comment]
I vote `#1496FF` because out of the four brand colors, it appears to be used the most.

It may be worth noting that the monochrome version of their logo in their presskit uses `#1A1A1A`.

**Comment by ericcornelissen** [comment]
> I vote #1496FF because out of the four brand colors, it appears to be used the most.

I personally agree.

I would like to get back to @DeadManPoe comment in the original issue where they prefer green (I missed the comment at the time...), may I ask why @DeadManPoe? I looked around a bit more and it seems they used to have a logo that only has green as color, is this why you associate green with the brand, or something else?


> It may be worth noting that the monochrome version of their logo in their presskit uses #1A1A1A.

I don't think that is anything to go by, it is just that: "a monochrome version" and doesn't really tell us anything about the brand color.

**Comment by DeadManPoe** [comment]
@ericcornelissen In the original issue I did not mention my preference for green, I just underlined that the original logo is the multicoloured one. For what concerns me, I agree with your colour choice.

**Comment by ericcornelissen** [comment]
Okay, sorry for the confusion @DeadManPoe and many thanks once again @JoaoPedroMoraes!

**Pull request merged**
