### PR TITLE
Update LinkedIn Colour

### LINKED ISSUE #4938: Update LinkedIn icon color?
Looks like LinkedIn updated their logo color in 2019.

**Brand Name:** LinkedIn
**Official resources for icon and color:**
  
- https://brand.linkedin.com/downloads
- Color found in the logo: `#0a66c2`
- Colors found on their website: `#0073b1`

### PR DESCRIPTION
**Pull request by xtlmnz**
**Issue:** Closes #4938
**Alexa rank:** [~53](http://alexa.com/siteinfo/linkedin.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description
LinkedIn icon colour is updated.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one on, @xtlmnz. I agree with the chosen colour but we should also take this opportunity to double check that our icon still lines up with the source, in case they tweaked it during the rebrand. And we should add a `guidelines` entry to the JSON pointing to https://brand.linkedin.com/policies

**Comment by adamrusted** [comment]
@PeterShaggyNoble @xtlmnz - looks like the icon is exactly the same. Would it be worth as well linking to the specific 'logos' page as the source, as that has info about requiring the use or the ® on larger scales.

**Comment by PeterShaggyNoble** [comment]
Either works for me, @adamrusted but brand.linkedin.com offers better future proofing.

**Comment by adamrusted** [comment]
Cool, so pending the addition of the `guidelines` entry, this PR is ready to merge!

**Comment by PeterShaggyNoble** [comment]
In the interests of getting the colour updated for this weekend's relaese, I'm going to merge this in and add the guidelines separately. Thanks for taking this on, @xtlmnz 👍🏻

**Pull request merged**
