### PR TITLE
Update Apache Pulsar

### PR DESCRIPTION
**Pull request by mondeja**
apachepulsar

**Issue:** #2887

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Path extracted from [this file](https://svn.apache.org/repos/asf/comdev/project-logos/originals/pulsar.svg).

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks, @mondeja.

Am I missing something, though, or is the source URL the only thing that's been changed here. Not the I'm averse to doing this for all Apache brands that don't have their own design guidelines, I also don't think it's strictly necessary if there's no update needed to the SVG. Also, if we _are_ going to update the source URLs for those icons that don't need to be updated and don't have their own guidelines,I'd rather we do them all in a single PR. Any thoughts from the other @simple-icons/maintainers?

**Comment by mondeja** [comment]
Seems that the path has, at least, one minor change, note the `v1.574` new command instead of `v1.573`.

**Comment by ericcornelissen** [comment]
> Seems that the path has, at least, one minor change: note the v1.574 new command instead of v1.573.

That seems correct, but it doesn't seem like a notable difference :thinking: Though I'm not against updating it, I'm also not sure if it's really necessary.

>  I also don't think it's strictly necessary if there's no update needed to the SVG. Also, if we are going to update the source URLs for those icons that don't need to be updated and don't have their own guidelines,I'd rather we do them all in a single PR.

I agree with both of these points.

**Comment by PeterShaggyNoble** [comment]
> Seems that the path has, at least, one minor change: note the v1.574 new command instead of v1.573.

And that's why I shouldn't try to "eyeball" the differences between two paths! :laughing:

**Comment by PeterShaggyNoble** [comment]
> Seems that the path has, at least, one minor change: note the `v1.574` new command instead of `v1.573`.

And that's why I shouldn't try to "eyeball" the differences between two paths! :laughing:

It looks like the difference between the 2 is simply one of rounding during the optimisation process as, looking at the path data for the [SVG](https://pulsar.apache.org/img/pulsar.svg) I used vs. the one you used, there are only a very few minor differences with a couple of absolute commands being replaced by relative commands:

```
## https://pulsar.apache.org/img/pulsar.svg
M61,13.73H46.09C42.06,6,37.8,0,32,0c-7.55,0-11.1,6.59-14.53,13l-.3.56H0v3.81H10c3.53,0,4.25,1.19,4.25,1.19-2.77,4.3-6.1,8.55-11.65,8.55H0v4H2.62c10.76,0,15.46-8.73,19.23-15.74C25.31,8.91,27.72,5,32,5c4.44,0,9.11,9.66,13.22,18.19.6,1.24,1.21,2.51,1.83,3.77-15.76.5-23.27,4.19-29.38,7.2-4.47,2.2-8,4.93-13.81,4.93H0v4H3.83c7,0,11.36-2.16,16-4.45,6.43-3.16,13.72-6.74,30.9-6.74h9.93v-4H55.05a3,3,0,0,1-2.47-1C51.6,25,50.64,23,49.7,21L48.4,18.34s.93-1,3.51-1H61Z

## https://svn.apache.org/repos/asf/comdev/project-logos/originals/pulsar.svg
M61 13.73H46.09C42.06 6 37.8 0 32 0c-7.55 0-11.1 6.59-14.53 13l-.3.56H0v3.81h10c3.53 0 4.25 1.19 4.25 1.19-2.77 4.3-6.1 8.55-11.65 8.55H0v4h2.62c10.76 0 15.46-8.73 19.23-15.74C25.31 8.91 27.72 5 32 5c4.44 0 9.11 9.66 13.22 18.19.6 1.24 1.21 2.51 1.83 3.77-15.76.5-23.27 4.19-29.38 7.2-4.47 2.2-8 4.93-13.81 4.93H0v4h3.83c7 0 11.36-2.16 16-4.45 6.43-3.16 13.72-6.74 30.9-6.74h9.93v-4h-5.61a3 3 0 0 1-2.47-1C51.6 25 50.64 23 49.7 21l-1.3-2.66s.93-1 3.51-1H61z
```

So I'd agree with Eric that, while not strictly necessary, updating does no harm and, at the very least, updates to the more correct source URL so I'm going to merge it in. Going forward, though, we should focus initially on those icons where there is a significant visual difference.

**Pull request merged**
