### PR TITLE
Added Windows Terminal

### LINKED ISSUE #4775: Request Windows Terminal icon
**Brand Name:** Windows Terminal
**Website:** 
- https://github.com/microsoft/terminal
- https://docs.microsoft.com/en-us/windows/terminal/
**Alexa rank:** N/A but have 70.8k stars on Github
  
image

**Official resources for icon and color:**
  
SVGs
- https://github.com/microsoft/terminal/tree/main/res/terminal
- [Terminal.svg](https://github.com/microsoft/terminal/blob/main/res/terminal/Terminal.svg)
- [Terminal_HC.svg](https://github.com/microsoft/terminal/blob/main/res/terminal/Terminal_HC.svg)

Colors
- A lot of colors are available in the official SVG.
  - `#CCCCCC`
  - `#999999`
  - `#666666`
  - Gradient from `#4D4D4D` to `#333333`
  - Gradient from `#B3B3B3` to `#999999`
  - Gradient from `#E6E6E6` to `#666666`

### PR DESCRIPTION
**Pull request by adamrusted**
windowsterminal

**Issue:** Fixes #4775
**Alexa rank:** N/A (Microsoft Product)
**GitHub stars:** 71.8k

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Used HC icon linked as source. `#4D4D4D` was chosen as colour following brief discussion with @service-paradis.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Looks good to me, @adamrusted; the only minor issue is an unneeded point at the top of the window, below the rightmost tab:

**Comment by adamrusted** [comment]
@PeterShaggyNoble - should be good to go now.

**Comment by PeterShaggyNoble** [comment]
Looks like the precision might be too low now, @adamrusted. See comparison below, with your version in red.

**Comment by adamrusted** [comment]
> Looks like the precision might be too low now, @adamrusted. See comparison below, with your version in red.

Odd - I literally made the one edit and re-optimized. Have been having issues with npm this morning though - so will rebuild and see if that fixes the issue.

**Comment by adamrusted** [comment]
That should do it @PeterShaggyNoble - was able to remove another extraneous point in the process.

**Comment by PeterShaggyNoble** [comment]
Looks good to me now, @adamrusted - nice one 👍🏻 Not sure on the colour choice but, as there was no clear-cut choice, we can merge this in as-is and update the colour later, if necessary.

**Pull request merged**
