### PR TITLE
Added Metabase

### LINKED ISSUE #5377: Request: Metabase Icon
**Brand Name: Metabase**
**Website: https://www.metabase.com/**
**Alexa rank: 47,161**
  

**Official resources for icon and color: https://freeicons.io/vector-and-svg-logos-icons-13/metabase-icon-8804**

### PR DESCRIPTION
**Pull request by adamrusted**
metabase

**Issue:** Closes #5377
**Alexa rank:** [47,161](https://www.alexa.com/siteinfo/metabase.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon pulled from header. Hex from stylesheet. Used `0.5px` stroke round lighter circles, though can update to `0.35px` if preferred (just now realising it doesn't look great at smaller sizes).

### CODE REVIEW

**Comment by adamrusted** [comment]
@service-paradis, see https://github.com/simple-icons/simple-icons/pull/5380/checks?check_run_id=2226444032. Appears there's an issue when trying to allocate to the project still.

**Comment by ericcornelissen** [comment]
> 
> 
> @service-paradis, see https://github.com/simple-icons/simple-icons/pull/5380/checks?check_run_id=2226444032. Appears there's an issue when trying to allocate to the project still.
> @simple-icons/maintainers, what's the best step from here? Should I revert the change to the checks?

Thanks for testing this @adamrusted, I removed the workflow in e35244300b4333ca754ceea6e5430dcaa9b8d963 to prevent this issue from appearing in outside contributions

**Comment by PeterShaggyNoble** [comment]
It works for me with the `0.5` strokes; the "M" is still legible at native size. For the sake of comparison, though, would you be able to knock together a rough version using `0.35` strokes?

**Comment by adamrusted** [comment]
Here's the icon at 0.35pt in the previewer. Possible looses too much fidelity at our smallest sizes, but otherwise I like it.

metabase

**Comment by PeterShaggyNoble** [comment]
> Possible looses too much fidelity at our smallest sizes

Yeah, at native size in particular, the outlines circles go missing a bit but the contrast difference between the white and the blue isn't helping there. The "M" stands out a lot more, though, which, to me, seems to be the intent of the full colour logo. If you're in agreement, let's run with the `0.35` version.

**Comment by adamrusted** [comment]
Give that a try @PeterShaggyNoble - needed 4 decimals to get the size working, but otherwise shouldn't be a problem there.

**Comment by PeterShaggyNoble** [comment]
Looks like a precision of 5 might be needed 👀 Quite a few of the circles have shifted compared to the original (e.g., [first one on second row](https://user-images.githubusercontent.com/15157491/114894866-e8f08000-9e06-11eb-836e-57a4e668ae97.png), with yours in red).

**Comment by adamrusted** [comment]
Weird - didn't see those differences on my end. Will re-export with 5 decimals now and see if that fixes it.

**Comment by adamrusted** [comment]
Realized what the issue was - I recreated the icon assuming there were imperfections in the original path. Just rebuilt from source, and it looks to match up 👌

**Review by PeterShaggyNoble — APPROVED** [review]
Looks perfect now, @adamrusted, nice work 👍🏻

**Pull request merged**
