### PR TITLE
Add additional Roots icons

### PR DESCRIPTION
**Pull request by MWDelaney**
rootsbedrock
rootssage

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
* Adds the Roots product logos in addition to the Roots logo already in simple-icons.
* Hex value is the Roots brand color (see here: https://roots.io/about/brand/)
* Logos were already in SVG format. I resized and re-colored them to match the simple-icons guidelines.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @MWDelaney and thanks for the comprehensive PR, much appreaciated

The first thing I'd like to suggest, though, is that you remove Acorn, Bud & Clover for now. As they're only currently in alpha, I wouldn't say they are yet ready for this project; I'd personally prefer to hold off on adding them until they are production ready (or have graduated to beta, at least) and have gained a bit of traction.

**Comment by MWDelaney** [comment]
Good notes, @PeterShaggyNoble ! I've removed the alpha products.

**Comment by PeterShaggyNoble** [comment]
Thanks, @MWDelaney - please do resubmit those for consideration once they're a bit further along in development and have gained some popularity.

Moving on to the remaining icons, the next thing we need to decide is whether or not we should include "Roots" in the names. Looking around the site, all products are referred to without it which would make me of the inclination that we should do the same. However, that would create a potential future naming clash were we ever to add, for example, [this Sage](https://www.sage.com/). Any thoughts from the other @simple-icons/maintainers?

To review the icons individually, then:

## Bedrock
Is there another metric we can use to assess the popularity of this one? Obviously there's no Alexa rank to go on, other than for the parent brand, and ~4.8k stars on GitHub isn't quite at the threshold I'd like to see for inclusion. @simple-icons/maintainers, do we have any precedent for including a brand if its _parent_ brand meets our popularity requirements?

There are a few minor differences in the SVG, compared to the one available at the source URL - see screenshots in [this zip](https://github.com/simple-icons/simple-icons/files/4579974/roots.zip), with your version in red.

## Sage
I'd say this one meets our popularity requirements. Although we've yet to set an _definitive_ cut-off for GitHub stars as a measurement, we have generally accepted brands with 10k+

As above, though, there are a few little discrepancies between the path in the PR and the source which, again, can be seen in [these screenshots](https://github.com/simple-icons/simple-icons/files/4579974/roots.zip).

## Trellis
The SVG looks spot on to me 👍 However, with only ~2.1k GitHub stars, see the questions on assessing popularity above.

**Comment by ericcornelissen** [comment]
First, I'd be in favour of adding "Roots" to the names of these icons to avoid any problems in the future. 

Second, i think Bedrock is safe to add, Trellis is less clear to me and I would like to see another metric of popularity on it before we decide to include it.

Lastly, @MWDelaney are you able to update the Bedrock and Sage SVGs based on @PeterShaggyNoble feedback?

**Comment by PeterShaggyNoble** [comment]
Given that @MWDelaney is a member of the @Roots organisation on GitHub (which I've only just spotted), I'm happy now to go with the inclusion of "Roots" in the names of all these.

**Comment by PeterShaggyNoble** [comment]
Are you still working on these, @MWDelaney? While we try to assess its suitability for inclusion, I'd suggest removing Trellis from this PR and opening an issue for it instead, where we continue the discussion. This way, it won't be blocking Bedrock & Sage from being added.

**Comment by MWDelaney** [comment]
I am still working on these. I'll try to get the SVG adjustments made and Trellis removed this week. Thanks and sorry for the delay.

**Comment by PeterShaggyNoble** [comment]
Thanks for the updates, @MWDelaney :+1: Don't forget to open that issue for Trellis for further discussion on its popularity.

Note that the build is currently failing on the following two points, which need to be remedied:
1. The `role="img"` attribute is missing from both SVGs,
2. The indentation of your JSON entries is slightly off.

As for the SVGs themsleves, I'm noticing some minor differences in both, compared to those available at https://roots.io/about/brand/ (in black below, with the PR versions in red). However, on this occasion, as it is _your_ brand, if you're happy to run with them as-is then that's OK by me.

Other than that, the only change I'd suggest is using https://roots.io/about/brand/ as the source URL for both.

## Bedrock




## Sage

**Comment by MWDelaney** [comment]
I swear I'm getting better at SVG because of this silly attempt to get these icons added :)

See the latest versions. Should be everything.

**Comment by PeterShaggyNoble** [comment]
> I swear I'm getting better at SVG because of this silly attempt to get these icons added

I think contributing to this library (or others) are how a lot of us developed our SVG skills! 😆 I exclude myself from that "us" 'cause I still suck.

> See the latest versions. Should be everything.

I almost hate to point it out at this stage 🙊 but there are still a few differences in both. Although, as I said earlier, as it is _your_ brand, if you're happy to run with them as-is then that's OK by me.

Or, if you prefer and want to use them, here's the optimised data from my own attempts at them:
```
# Bedrock
M.4 0L0 .4v5.2l.343.343 11.314-1.886L12 4.4V8l11.52-1.92.48-.48V.4l-.4-.4zm.08 9.92L0 10.4v3.2l.343.343L12 12V8zM12 12v4l11.52-1.92.48-.48v-3.2l-.343-.343zM.48 17.92L0 18.4v5.2l.4.4h23.2l.4-.4v-5.2l-.343-.343-11.314 1.886L12 19.6V16L.48 17.92z
# Sage
M7.384 4.232l1.71 5.075-4.478-3.136L0 9.403l1.753 5.2.01.03H7.3L2.82 17.77l1.754 5.2.01.03h5.705L12 17.925l1.7 5.045.01.03h5.707l1.763-5.23-4.48-3.137h5.537L24 9.403l-4.616-3.232-4.479 3.136 1.711-5.075L12 1zm.105 10.342l1.723-5.111h5.576l1.723 5.111-4.51 3.16z
```

Other than that, the build is currently failing due to the presence of the `fill` attribute on the `<path>` tags of both SVGs and you also have an errant file named "test" in your branch.

**Comment by PeterShaggyNoble** [comment]
Hope you don't mind, @MWDelaney but, in the interests of getting this merged in, I went ahead and committed those last changes directly to your branch?

**Comment by ericcornelissen** [comment]
Thanks a bunch for putting in the initial effort @MWDelaney! It is much appreciated 🎉 Also, many thanks to @PeterShaggyNoble for finalizing the work 👌

**Pull request merged**
