### PR TITLE
Add Canonical

### PR DESCRIPTION
**Pull request by gizmecano**
canonical

**Issue**: Request: Canonical #3148

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

~~Note I do not check _I optimized the icon with SVGO or SVGOMG_ because I usually operate with [svgcleaner](https://github.com/RazrFalcon/svgcleaner) that generally does the optimization job well. Let me know if you think there seems to be a significant difference in code optimization.~~

I used vector files from [Canonical symbol set for web](https://design.ubuntu.com/downloads/) and added color `#77216F` as suggested by @ericcornelissen in [his comment](https://github.com/simple-icons/simple-icons/issues/3148#issuecomment-636741231).

### CODE REVIEW

**Comment by gizmecano** [comment]
As there are indeed significant difference in code optimization, I have finally updated the icon with svgomg online tool.

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one on, @gizmecano :+1:

The path looks spot on to me, it just needs to be centred on the canvas. Also, using `canonical-symbol-set-web\SVG\canonical_aubergine_hex.svg` from the "Canonical symbol set for web" ZIP, I get `#772953` for the colour - which file did you source the colour from, @ericcornelissen?

**Comment by ericcornelissen** [comment]
`#77216F` (Light aubergine) comes from [the colour pallete](https://design.ubuntu.com/brand/colour-palette/) and is the closest to what's in the SVG, that's why I suggested it :slightly_smiling_face:

**Comment by PeterShaggyNoble** [comment]
Ah, hadn't seen that. In that case, I agree with the choice of colour.

**Comment by gizmecano** [comment]
> (...) it just needs to be centred on the canvas.

I don't quite understand what @PeterShaggyNoble means...

The path seems absolutely centered in my editor (Inkscape) and I don't really see what I can change here... 🤔

fit-canvas

Can you explain me what seems erroneous on your own side?

**Comment by PeterShaggyNoble** [comment]
Weird, lemme restart my Inkscape and try again - it does sometime play sill beggars like that on me when I'm pasting a path in.

**Comment by PeterShaggyNoble** [comment]
D'oh! I hadn't spotted that the x & y coordinates of the `viewBox` in the original weren't set to `0`, accounting for the offset I thought I was seeing. Sorry 'bout that.

Looks perfect to me know - thanks again for your efforts on this one, @gizmecano :+1:

**Comment by gizmecano** [comment]
Do not hesitate to tell me if you see such an error: I have to say I'm not necessarily experienced enough for checking all required elements.

**Pull request merged**
