### PR TITLE
Update Yammer

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Yammer

**Issue:** #1585

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
See #2541 for notes on source URL

### CODE REVIEW

**Comment by ericcornelissen** [comment]
The "Y" has some weird angles to it but it seems the source material does too :thinking: I'm fine with adding it this way but I'll request a second pair of :eyes: from another @simple-icons/maintainers just in case :+1:

**Comment by runxel** [comment]
It looks weird, yes, but not _toooo_ shoddy.
I think we can add this.

**Comment by PeterShaggyNoble** [comment]
No that it's been pointed out, it's annoying me! 😆 But beyond my limited skills to try to fix! 🙁

**Comment by runxel** [comment]
Hey @PeterShaggyNoble!
I can totally understand the pain :D 

What do you think of this?

[yammer](https://github.com/simple-icons/simple-icons/files/4207392/yammer.zip)

----

It's totally redrawn, has much less control points, and straight lines are actually straight. (And of course you would see differences if you do an overlay – but that's clearly expected and a mudged origin can never yield a totally equal looking _constructed_ svg)

**Comment by PeterShaggyNoble** [comment]
Appreciate that, thanks @runxel 😀

Your version was just a hair over 24px wide and scaling down to size required increasing the precision to 4 when running it through SVGOMG.

**Comment by runxel** [comment]
> Your version was just a hair over 24px wide and scaling down to size required increasing the precision to 4 when running it through SVGOMG.

Ach, that reminds me to check my svgs more careful after I svgo them. Precision 3 is indeed not always sufficient...

**Pull request merged**
