### PR TITLE
Add Ren'Py Icon

### PR DESCRIPTION
**Pull request by creepertron95**
renpy(2)

**Issue:** #3515
**Alexa rank:** 104,196
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I have attempted to manually vectorize the logo from the source image the best as I could due to the logo being .png only. I picked the hex value from the mascot's hair color.

### CODE REVIEW

**Comment by creepertron95** [comment]
cc @renpytom

**Comment by runxel** [comment]
@creepertron95 Thank you so much for this PR!
Manual vectorizing is always difficult. We appreciate your effort!

As you can see, the build is currently failing, because it seems the path is not perfectly centered. Would be nice to check that again. You _might_ need to bump up the precision of svgo to get a pass in the linter.

**Comment by creepertron95** [comment]
@runxel Should I go ahead and invert the snake as well as the founder suggested?

**Comment by runxel** [comment]
@creepertron95 We try to respect the wishes from the brand owners, so normally we look at things like brand manuals. But the founder replying in a thread has even more importance. So yes, that would be great.

Also have a look at the svg again in general. The build fails because the structure isn't right. But thats easy to fix. :)

**Comment by creepertron95** [comment]
@runxel How can I go about fixing the structure?

**Comment by runxel** [comment]
Thanks for your work!
The lint is still failing however 🙈 
`<path> must be centered at (12, 12); the center is currently (12.012, 12)`

I don't know what tool you are using – sometimes with Illustrator there are problems to align it correctly. Inkscape seems to do a better job at this. 

Otherwise it looks great! 💯  I think @renpytom will agree :)
If not: now's the best time to demand changes!

**Comment by creepertron95** [comment]
@runxel I am using Inkscape 1.0, How can I center the path correctly to fix the lint?

**Comment by runxel** [comment]
I don't know Inkscape well, tbh, but I do think you can position it correctly with the numerical position input (there should be some boxes).

**Comment by creepertron95** [comment]
@runxel I have tried to recenter the logo by adding and subtracting '0.012' to the X position input and the build still fails.

**Comment by runxel** [comment]
No! @creepertron95 it looks all good now! 💯  You can click on the Travis link btw, to see why the build failed.
The report now says, that the location of the new item inside the JSON is wrong... Pretty sure the `'` is problematic. I'm not sure tho what we actually expect (luckily most brands use only alphanumeric values 😅). Gonna tag @PeterShaggyNoble here who will probably have a clue! :)

**Comment by creepertron95** [comment]
@runxel Done! I found the problem and fixed it.

**Comment by runxel** [comment]
Great! We're good to go!
Big thanks to anyone involved! 💯

**Pull request merged**
