### PR TITLE
Audit dependencies

### PR DESCRIPTION
**Pull request by ericcornelissen**
**Issue:** n/a

### Description
Audited the package dependencies using `$ npm audit fix`, going down from 1110 vulnerabilities to 0.

### CODE REVIEW

**Comment by birjolaxew** [comment]
> 1110 high severity vulnerabilities

Yikes. Nice job catching this!

**Comment by ericcornelissen** [comment]
> Yikes. Nice job catching this!

It's honestly not such a big deal because it's all devDependencies and the way were using them barely effects our package. But it's still nice to stay up-to-date :smile:

**Comment by davidklebanoff** [comment]
Hmm, I see bot potential here.

**Comment by ericcornelissen** [comment]
> Hmm, I see bot potential here.

Sure, didn't think it was necessary since dependencies are not super relevant (everything is a `devDependency`). Anyhow, Ihave experience with [Greenkeeper](https://github.com/marketplace/greenkeeper) and [Renovate Bot](https://github.com/marketplace/renovate/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW45NTk=#pricing-and-setup) (both are free for open source), I would definitely recommend the latter over the former. What do you think @davidklebanoff ?

**Comment by davidklebanoff** [comment]
I don't have experience with either of those tools, so I can't say one way versus another. The task is definitely low priority since as you mentioned they are devDependencies. We could trial the Renovate Bot to see how it goes. I like that they allow you to throttle how often it runs - given that these are only devDependencies we don't have to rush to get things updated ASAP. Perhaps a cadence of biweekly or monthly would be appropriate for a project such as Simple Icons.

**Comment by ericcornelissen** [comment]
> We could trial the Renovate Bot to see how it goes. I like that they allow you to throttle how often it runs - given that these are only devDependencies we don't have to rush to get things updated ASAP. Perhaps a cadence of biweekly or monthly would be appropriate for a project such as Simple Icons.

I like that idea, I didn't know you can throttle how often it runs but that seems like a great feature for our case indeed! I will try to look into this as soon as possible as it isn't that hard to set up (though I never configured a Renovate Bot before) and I'll open an issue as well just to be sure :wink:

**Pull request merged**
