### PR TITLE
Add Iceland icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** #6570 
**Alexa rank:** 54,649
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

see issue

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
@dirien when I tried to access https://www.iceland.co.uk/ it keeps saying access denied.

**Comment by adamrusted** [comment]
> @dirien when I tried to access https://www.iceland.co.uk/ it keeps saying access denied.

Even when using a VPN? Cause that'd be weird.

**Comment by dirien** [comment]
@jorgeamadosoria and @adamrusted, it works for me fine.  Maybe some DNS issue again...

image

**Comment by jorgeamadosoria** [comment]
Is this a geo locked market website or something? Why would I need a VPN to access a shopping website?

**Comment by jorgeamadosoria** [comment]
well, I can't access this one. Someone else will have to check it, sorry.

**Comment by dirien** [comment]
lol, thats so strange! Maybe an issue with the brandname? I mean Iceland is quite generic! But its one of the biggest store for frozen stuff in the UK. I love their American Style Pizza 😄

**Comment by jorgeamadosoria** [comment]
> lol, thats so strange! Maybe an issue with the brandname? I mean Iceland is quite generic! But its one of the biggest store for frozen stuff in the UK. I love their American Style Pizza 😄

I don't understand it either, but it is what it is. Maybe they have blocked Latin American access or something. I'm not going to install a VPN just to find out 🤷 
No worries, @adamrusted or @service-paradis may take a look at this at a later time

**Comment by dirien** [comment]
@jorgeamadosoria added the source from the website:

```svg
<svg version="1.1" id="dual-logo" x="0" y="0" viewBox="0 0 120 16" xml:space="preserve" xmlns="http://www.w3.org/2000/svg"><path class="cast0" d="M91.8 5.5v.1c0 .6-.2.9-.6.9-.4 0-.6-.3-.6-.9v-.8h2.3v-1c0-1.2-.4-2-1.7-2s-1.7.8-1.7 2v1.6c0 1.2.4 2 1.7 2 1.2 0 1.7-.8 1.7-1.9h-1.1zm-1.2-1.9c0-.6.2-.9.6-.9.4 0 .6.3.6.9v.3h-1.2v-.3zM22.2 13.3c-2.7 0-3.6-1.2-3.8-2.2l7.4-1.6c0-5.4-3.3-6.4-5.4-6.4-2.7 0-5.7 2-5.7 6.3 0 3.8 2.6 6.2 6.9 6.2 1.3 0 2.7-.3 3.5-.6l-.4-2c-.7.2-1.7.3-2.5.3zm-1.8-7.9c1.1 0 1.9.8 2 2.4l-4.3.9c.1-2.1.9-3.3 2.3-3.3zM91.3 8.4h-1.4l-1.2 6.9h1.1l.2-1.5h1.3l.2 1.5h1.1l-1.3-6.9zm-1.1 4.4l.5-3 .5 3h-1zM100.4 3.8c0-1.2-.4-2-1.7-2-1.2 0-1.7.8-1.7 2v1.6c0 1.2.4 2 1.7 2 1.2 0 1.7-.8 1.7-2V3.8zm-1.7 2.7c-.4 0-.6-.3-.6-.9v-2c0-.6.2-.9.6-.9.4 0 .6.3.6.9v2c0 .6-.2.9-.6.9zM37.8 3.1c-1.9 0-3.6.5-4.6.8 0 .1.4 2 .5 2.2 1.1-.4 2.6-.7 3.6-.7 1.6 0 2.3.5 2.3 1.6v.5c-5 0-7.1 1.8-7.1 4.1 0 2.6 2.3 4 5.6 4 2.2 0 4-.4 4.8-.6V7.2c.1-2.8-1.6-4.1-5.1-4.1zm1.8 10.1c-.3.1-.9.1-1.2.1-1.1 0-2.4-.5-2.4-1.8s1.1-2 3.5-1.9v3.6zM104.1 3.8c0-1.2-.4-2-1.7-2-1.2 0-1.7.8-1.7 2v1.6c0 1.2.4 2 1.7 2 1.2 0 1.7-.8 1.7-2V3.8zm-1.7 2.7c-.4 0-.6-.3-.6-.9v-2c0-.6.2-.9.6-.9.4 0 .6.3.6.9v2c0 .6-.2.8-.6.9zM65.4 0v3.4c-.4-.1-.9-.2-1.7-.2-2.9 0-6 2-6 6.3 0 3.8 2.5 6.1 6.6 6.1 1.7 0 3.7-.3 4.5-.5V0h-3.4zm0 13.3c-.3.1-.7.1-.9.1-2.1 0-3.3-1.5-3.3-4 0-1.9.8-3.9 3.1-3.9.3 0 .9.1 1.1.1v7.7zM95.7 12.2c.4-.2.8-.6.8-1.8 0-1.5-.7-2-2-2h-1.6v6.9h1.2v-2.8h.6l.8 2.9h1.2l-1-3.2zm-1.2-.7h-.4V9.4h.4c.6 0 .9.2.9 1.1 0 .8-.2 1-.9 1zM108.3 10.1c0-1-.6-1.8-1.8-1.8s-1.8.8-1.8 1.8v3.6c0 1 .6 1.8 1.8 1.8 1.2 0 1.8-.8 1.8-1.8v-3.6zm-1.8 4.3c-.5 0-.6-.2-.6-.8v-3.5c0-.5.1-.8.6-.8s.6.2.6.8v3.5c0 .5-.1.8-.6.8zM107.9.1h-1.1v2.3c-.4-.4-.6-.6-1.1-.6-.7 0-1.1.5-1.1 1.5v2.6c0 1 .4 1.5 1.1 1.5.5 0 .8-.2 1.2-.7v.6h1V.1zm-1.7 6.3c-.3 0-.5-.2-.5-.9v-2c0-.7.2-.9.5-.9.2 0 .4.1.6.3v3.2c-.2.2-.4.3-.6.3zM87 .1v2.3c.4-.4.6-.6 1.3-.6.6 0 .9.4.9 1.1v4.3h-1.1V3.1c0-.3-.2-.4-.4-.4s-.4.1-.7.3v4.2h-1.1V0l1.1.1zM0 0h3.1v15H0zM11.4 15.6c-3.5 0-5.8-2.4-5.8-5.9 0-3.8 2.5-6.5 5.9-6.5.8 0 1.8.2 2.4.5l-.6 2.1c-.4-.1-.9-.3-1.3-.3-1.9 0-3.2 1.6-3.2 4s1.2 3.8 3 3.8c.5 0 1.2-.1 1.8-.3l.5 2.1c-.6.2-1.8.5-2.7.5zM27.6 0h3.1v15h-3.1zM55.9 15h-3.3V7.3c0-1.6-.8-2-2-2-.6 0-1.3.1-1.8.2V15h-3.3V3.7c.8-.2 3.2-.6 5.2-.6 3.6 0 5.2 1.3 5.2 4V15zM75.9.4h.7v15.3h-.7zM83.1 1.9h.6V.5h1.1v1.4h.7v.9h-.7v3.1c0 .3.1.4.4.4h.4v.9c-.1 0-.3.1-.5.1-.8 0-1.3-.3-1.3-1.1V2.9h-.6l-.1-1zM87.1 15.3l-.8-4.5-.8 4.5h-1l-1.3-6.9h1.1l.7 4.4.8-4.4h.9l.8 4.4.7-4.4h1.1l-1.2 6.9zM96.2 1.9h.6v.9h-.6v4.4h-1.1V2.8h-.6v-.9h.6v-.7c0-.9.4-1.3 1.2-1.3h.5v.9h-.3c-.3 0-.4.1-.4.4l.1.7zM97 15.3V8.4h3.1v1h-1.9v1.8h1.5v1.1h-1.5v2h2.1v1zM103.1 15.3v-3.1l-1.3.1v3h-1.1V8.4h1.1v2.8h1.3V8.4h1.1v6.9zM110.6 15.4c-1.1 0-1.8-.7-1.8-1.8V8.4h1.2v5.2c0 .5.2.8.6.8.4 0 .6-.3.6-.8V8.4h1.2v5.2c-.1 1.2-.7 1.8-1.8 1.8zM114.5 15.4c-1.1 0-1.7-.9-1.7-1.9l1.1-.2c0 .7.3 1 .7 1 .4 0 .7-.2.7-.6 0-1.4-2.4-1.7-2.4-3.7 0-1.1.7-1.7 1.8-1.7.9 0 1.5.7 1.6 1.7l-1.1.1c0-.6-.4-.8-.6-.8-.4 0-.6.3-.6.7 0 1.2 2.4 1.7 2.4 3.6-.1 1.2-.9 1.8-1.9 1.8zM116.8 15.3V8.4h3.1v1h-2v1.8h1.5v1h-1.5v2.1h2.1v1z"></path></svg>
```

**Comment by jorgeamadosoria** [comment]
image

Small discrepancies all over. Probably a precision issue, as usual

**Comment by dirien** [comment]
@jorgeamadosoria, done 

image

**Comment by jorgeamadosoria** [comment]
great, LGTM!

**Pull request merged**
