### PR TITLE
Adding penpot icon griger

### PR DESCRIPTION
**Pull request by grivasgervilla**
**Issue:** #6664
**Alexa rank:** 297,05. See https://www.alexa.com/siteinfo/penpot.app

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I have take the branding colour, `#000000`, from the logo itself. In the JSON file I have add the URL to the SVG logo in the Penpot's repository.

### CODE REVIEW

**Comment by sachinraja** [comment]
I believe checks are failing on this because the icon has not been optimized. Please read [this section](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon) of the contributing guidelines.

**Comment by Griger** [comment]
> I believe checks are failing on this because the icon has not been optimized. Please read [this section](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon) of the contributing guidelines.

Hi, @sachinraja. I think that I have optimized this icon using the SVGOMG tool. Did I do it wrong?

**Comment by Griger** [comment]
@sachinraja, sorry for bothering you. But, I have added the `title` tag because in the contributing guidelines it is said that the SVG file should be annotated. Am I wrong?

**Comment by sachinraja** [comment]
No worries, I'm happy to help. The `title` tag is correct. The problem is the precision of the icon. You may want to reset to defaults on SVGOMG or just try again. Also, note the order of the steps in the contributing guidelines. You should optimize the icon first and then annotate it because the configuration on SVGOMG will remove the annotations.

**Comment by adamrusted** [comment]
Closing as Penpot was merged in #7911

**Pull request closed without merging**
