### PR TITLE
Update Grubhub

### PR DESCRIPTION
**Pull request by mondeja**
image

**Issue:** #4590
**Alexa rank:** [1,3K](https://www.alexa.com/siteinfo/grubhub.com)

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- ~~Just manually removed four useless segments from the path.~~
- Rebuilt from source.
- Cleaned up path.

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks @mondeja - though it looks like there are still some excess points in this version of the icon - see [screenshot](https://user-images.githubusercontent.com/1830867/110133060-be50e780-7dc3-11eb-83aa-2324bb6e7c89.png). Mostly around the curves of the shapes. Would you mind taking another look?

**Comment by mondeja** [comment]
If you take a closer look, there are a lot of duplicated points which create some teeth in letters, the original path is a complete mess. I've rebuilt from the source and manually cleaned up all these imperfections, but if this is too much difference from the original, I can do it again by correcting only the curves you mention.

**Review by adamrusted — COMMENTED** [review]
I'm seeing [minor differences throughout](https://user-images.githubusercontent.com/1830867/110205618-e77b8180-7e70-11eb-9701-c1decb828765.png) - though I assume that's almost all down to optimization. Happy to run with this if another @simple-icons/maintainers approves it, but will await input from at least one other person before merging.

**Comment by mondeja** [comment]
> I'm seeing minor differences throughout - though I assume that's almost all down to optimization

No, it's because there are imperfections in the original path, I have assumed that the letters should look rounded without those teeth in the middle of the paths.

**Comment by PeterShaggyNoble** [comment]
Can someone share the source file, please? Grubhub is geo-blocked here.

**Comment by adamrusted** [comment]
Weird - SVG available [here](https://media-cdn.grubhub.com/image/upload/v1532110052/Onboarding/logo-gh.svg) or source code below.

```svg
<svg width="211" height="44" xmlns="http://www.w3.org/2000/svg"><path d="M146.678.71h-7.303a.725.725 0 0 0-.728.728v15.954h-7.41V1.438a.725.725 0 0 0-.728-.728h-7.277a.725.725 0 0 0-.727.728v41.097c0 .405.323.728.727.728h7.304a.725.725 0 0 0 .727-.728v-16.52h7.411v16.52c0 .405.324.728.728.728h7.303a.725.725 0 0 0 .728-.728V1.438a.725.725 0 0 0-.728-.728h-.027zm-62.01 0h-7.465c-.377 0-.7.27-.728.647v29.32c.054 1.213-.296 2.4-1.024 3.342l.027-.027a3.314 3.314 0 0 1-4.662.243 1.03 1.03 0 0 1-.243-.243 5.064 5.064 0 0 1-.97-3.26V1.357a.652.652 0 0 0-.7-.647H61.41a.67.67 0 0 0-.728.62V30.759v-.081c-.242 3.53.89 7.006 3.153 9.701l-.027-.027a12.283 12.283 0 0 0 9.163 3.612h.108a12.283 12.283 0 0 0 9.163-3.612l-.027.027a13.626 13.626 0 0 0 3.153-9.701V1.357a.705.705 0 0 0-.701-.647zM12.471.01h-.054a12.283 12.283 0 0 0-9.163 3.61l.081-.107A13.65 13.65 0 0 0 .02 13.188v17.597-.08c-.242 3.53.89 7.006 3.153 9.701l-.027-.027a12.283 12.283 0 0 0 9.163 3.612h.135a12.283 12.283 0 0 0 9.163-3.612 13.626 13.626 0 0 0 3.153-9.701V21.11a.766.766 0 0 0-.755-.728h-10.78a.791.791 0 0 0-.781.728v7.168c.027.431.35.755.781.755h2.965v1.644a5.428 5.428 0 0 1-1.024 3.45l.027-.028c-.647.809-1.644 1.267-2.668 1.186h-.054c-1.024.08-2.021-.323-2.668-1.132a5.197 5.197 0 0 1-1.078-3.422V13.295v.027A5.312 5.312 0 0 1 9.857 9.82c.647-.809 1.644-1.267 2.668-1.186h.054c1.024-.08 2.02.324 2.668 1.132l.054.054a5.447 5.447 0 0 1 .889 3.476v1.617c.027.378.35.647.727.647h7.304c.377 0 .7-.27.727-.647v-1.697.053c.189-3.53-.997-6.98-3.341-9.647h.027A12.387 12.387 0 0 0 12.47.009zM112.803 21.3l.054-.055a11.316 11.316 0 0 0 3.476-8.165v.108a12.704 12.704 0 0 0-3.126-8.57v.027a11.826 11.826 0 0 0-9-3.935H92.563a.725.725 0 0 0-.728.728v41.097c0 .405.324.728.728.728H104.8c3.692.054 7.222-1.536 9.594-4.366l-.027.027a13.431 13.431 0 0 0 2.695-8.812v.108c0-3.477-1.563-6.738-4.258-8.92zM100.541 9.36h3.692-.027a3.112 3.112 0 0 1 2.453.944l.053.054a4.47 4.47 0 0 1 .863 3.018v-.054c.108 1.132-.243 2.291-.916 3.234v-.027a2.968 2.968 0 0 1-2.426 1.024h-3.692V9.361zm6.845 24.255l.027-.027a3.21 3.21 0 0 1-2.722 1.132h-4.15v-8.893h4.204-.027a3.21 3.21 0 0 1 2.722 1.132l-.027-.027a4.84 4.84 0 0 1 1.024 3.234v.027c.054 1.212-.35 2.398-1.078 3.368l.027.054zm-57.213-8.678l.027-.026c.754-.513 1.428-1.132 2.048-1.806l-.027.054a13.558 13.558 0 0 0 3.288-9.325v-.08a13.293 13.293 0 0 0-3.423-9.136l.135.161A12.243 12.243 0 0 0 43.409.656H31.147a.725.725 0 0 0-.728.728v41.151c0 .405.323.728.728.728h7.303a.725.725 0 0 0 .728-.728V27.31h2.695l4.608 15.523c.08.296.377.512.7.512h7.762a.753.753 0 0 0 .593-.297.687.687 0 0 0 0-.646l-5.363-17.464zm-4.5-7.572a3.749 3.749 0 0 1-2.911 1.185h-3.584V9.36h3.557a3.749 3.749 0 0 1 2.91 1.187v-.027a4.796 4.796 0 0 1 1.105 3.26v.054c.081 1.294-.296 2.534-1.105 3.53h.027zm160.348 3.934l.053-.054a11.316 11.316 0 0 0 3.477-8.165v.161a12.678 12.678 0 0 0-3.126-8.785l.054.08a11.826 11.826 0 0 0-9.001-3.934h-11.696a.725.725 0 0 0-.728.728v41.205c0 .405.323.728.728.728h12.18c3.693.054 7.223-1.536 9.595-4.366l-.027.027a13.431 13.431 0 0 0 2.695-8.812v.054c0-3.45-1.563-6.738-4.258-8.894l.054.027zM193.759 9.361h3.692-.027a3.112 3.112 0 0 1 2.452.943l.054.054a4.47 4.47 0 0 1 .862 3.018v-.054c.108 1.132-.242 2.291-.916 3.234v-.027a2.968 2.968 0 0 1-2.425 1.024h-3.692V9.361zm6.845 24.254l.027-.027a3.21 3.21 0 0 1-2.722 1.132h-4.15v-8.893h4.204-.027a3.21 3.21 0 0 1 2.722 1.132l-.027-.027a4.84 4.84 0 0 1 1.024 3.234v.027c.054 1.212-.35 2.398-1.078 3.368l.027.054zM177.886.71h-7.52a.67.67 0 0 0-.727.62v29.348c.054 1.185-.27 2.344-.97 3.287a3.314 3.314 0 0 1-4.662.243 1.03 1.03 0 0 1-.243-.243 5.064 5.064 0 0 1-.97-3.26V1.357c-.027-.377-.35-.647-.728-.647h-7.492c-.377 0-.7.27-.727.647v29.402c-.243 3.449.89 6.925 3.153 9.62l.08.081c5.256 4.716 13.26 4.662 18.434-.161l-.108.08a13.626 13.626 0 0 0 3.153-9.701V1.357c-.027-.35-.323-.647-.673-.647z" fill="#FFF" fill-rule="nonzero"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
I'm seeing the same differences as well as ones such as [this one](https://user-images.githubusercontent.com/15157491/110654576-2a619000-81b6-11eb-83e5-ecabcc0ed809.png) in the top left of the "H" which may be a result of the precision being too low. For me, I think, the differences @adamrusted pointed out are a bit too big of a deviation from the original. Would you mind having another looks at this, @mondeja?

**Comment by adamrusted** [comment]
Returning to this, there is [this SVG](https://assets.grubhub.com/assets/img/grubhub/logo-full-primary.svg) which only ever shows on the loader, but is much cleaner for us to use as a source. I've generated the below, which I'm happy to push to this PR to get it closed for @mondeja.

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Grubhub</title><path d="M16.708 9.556h-.84c-.048 0-.072.048-.072.072v1.828h-.84V9.628c0-.048-.048-.072-.072-.072h-.84c-.048 0-.072.048-.072.072v4.692c0 .048.048.072.072.072h.84c.048 0 .072-.048.072-.072v-1.876h.84v1.876c0 .048.048.072.072.072h.84c.048 0 .072-.048.072-.072V9.628c0-.024-.024-.072-.072-.072m-7.08 0h-.84c-.048 0-.072.024-.072.072v3.324a.61.61 0 0 1-.12.384c-.072.096-.168.12-.288.12a.404.404 0 0 1-.288-.12.61.61 0 0 1-.12-.384V9.628c0-.048-.048-.072-.072-.072h-.84c-.048 0-.072.024-.072.072v3.348c0 .432.096.84.36 1.108.264.264.624.408 1.036.408.432 0 .796-.144 1.036-.408.264-.264.36-.648.36-1.108V9.628c-.004-.024-.028-.072-.08-.072m-8.232-.072c-.432 0-.796.144-1.036.408C.096 10.156 0 10.54 0 11v2c0 .432.096.84.36 1.108.264.264.624.408 1.036.408.432 0 .796-.144 1.036-.408.264-.264.36-.648.36-1.108v-1.104a.103.103 0 0 0-.096-.096H1.468a.103.103 0 0 0-.096.096v.82c0 .048.048.096.096.096h.316v.192a.678.678 0 0 1-.12.408c-.072.096-.168.12-.288.12a.404.404 0 0 1-.288-.12.686.686 0 0 1-.12-.408v-1.976c0-.168.048-.316.12-.408.072-.096.168-.12.288-.12.116 0 .216.048.288.12.072.096.12.24.12.408v.192c0 .048.048.072.072.072h.84c.048 0 .072-.024.072-.072v-.192c0-.432-.096-.84-.36-1.108-.216-.292-.604-.436-1.012-.436m10.832 3.828c-.072.096-.168.12-.316.12h-.48v-1.016h.48c.12 0 .216.048.288.12a.59.59 0 0 1 .12.36c.008.2-.016.316-.092.416zm-.796-2.768h.432c.12 0 .216.024.288.12.072.072.096.192.096.34 0 .148-.024.264-.096.36a.385.385 0 0 1-.264.12h-.432v-.94h-.024zm1.396 1.372c.144-.144.408-.48.408-.916 0-.508-.192-.82-.34-.988-.264-.288-.624-.432-1.036-.432h-1.316c-.048 0-.072.048-.072.072v4.696c0 .048.048.072.072.072h1.396c.432 0 .84-.168 1.108-.508.144-.192.316-.508.316-.988-.028-.576-.388-.916-.536-1.008zm-7.652-.46c-.072.096-.192.144-.34.144h-.408v-1.056h.408c.144 0 .264.048.34.144.096.096.12.216.12.384s-.02.288-.12.384zm.532.868c.096-.072.168-.12.24-.216.168-.192.384-.532.384-1.06 0-.508-.192-.84-.384-1.036-.24-.288-.6-.432-1.012-.456H3.54c-.048 0-.072.048-.072.072v4.692c0 .048.048.072.072.072h.84c.048 0 .072-.048.072-.072v-1.736h.288l.532 1.78c0 .024.048.048.072.048h.888c.024 0 .048-.024.072-.024s.024-.048.024-.072l-.62-1.992zm17.136.988c-.072.096-.168.12-.316.12h-.48v-1.016h.48c.12 0 .216.048.288.12a.59.59 0 0 1 .12.36c.028.2-.016.316-.092.416zm-.772-2.768h.432c.12 0 .216.024.288.12.072.072.096.192.096.34 0 .148-.024.264-.096.36a.385.385 0 0 1-.264.12h-.432v-.94h-.024zm1.396 1.372c.144-.144.408-.48.408-.916 0-.508-.192-.82-.34-.988-.264-.288-.624-.432-1.036-.432h-1.328c-.048 0-.072.048-.072.072v4.696c0 .048.048.072.072.072h1.404c.432 0 .84-.168 1.108-.508.144-.192.316-.508.316-.988a1.441 1.441 0 0 0-.532-1.008zm-3.224-2.36h-.84c-.048 0-.072.024-.072.072v3.324a.61.61 0 0 1-.12.384c-.072.096-.168.12-.288.12a.404.404 0 0 1-.288-.12.61.61 0 0 1-.12-.384V9.628c0-.048-.048-.072-.072-.072H17.6c-.048 0-.072.024-.072.072v3.348c0 .432.096.84.36 1.108.264.264.624.408 1.036.408.432 0 .796-.144 1.036-.408.264-.264.36-.648.36-1.108V9.628c.024-.024-.024-.072-.076-.072"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
That lines up perfectly for me, @adamrusted. Although there are [a couple of excess points](https://user-images.githubusercontent.com/15157491/120624185-578da980-c458-11eb-907b-9a9a96b18a84.png) in the top left corner of the upper cut-out of both "B"s which can be removed.

**Comment by adamrusted** [comment]
Good spot, @PeterShaggyNoble. Try this:

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Grubhub</title><path d="M16.708 9.556h-.84c-.048 0-.072.048-.072.072v1.828h-.84V9.628c0-.048-.048-.072-.072-.072h-.84c-.048 0-.072.048-.072.072v4.692c0 .048.048.072.072.072h.84c.048 0 .072-.048.072-.072v-1.876h.84v1.876c0 .048.048.072.072.072h.84c.048 0 .072-.048.072-.072V9.628c0-.024-.024-.072-.072-.072m-7.08 0h-.84c-.048 0-.072.024-.072.072v3.324a.61.61 0 0 1-.12.384c-.072.096-.168.12-.288.12a.405.405 0 0 1-.288-.12.61.61 0 0 1-.12-.384V9.628c0-.048-.048-.072-.072-.072h-.84c-.048 0-.072.024-.072.072v3.348c0 .432.096.84.36 1.108.264.264.624.408 1.036.408.432 0 .796-.144 1.036-.408.264-.264.36-.648.36-1.108V9.628c-.004-.024-.028-.072-.08-.072m-8.232-.072c-.432 0-.796.144-1.036.408C.096 10.156 0 10.54 0 11v2c0 .432.096.84.36 1.108.264.264.624.408 1.036.408.432 0 .796-.144 1.036-.408.264-.264.36-.648.36-1.108v-1.104a.102.102 0 0 0-.096-.096H1.468a.102.102 0 0 0-.096.096v.82c0 .048.048.096.096.096h.316v.192a.676.676 0 0 1-.12.408c-.072.096-.168.12-.288.12a.405.405 0 0 1-.288-.12.69.69 0 0 1-.12-.408v-1.976c0-.168.048-.316.12-.408.072-.096.168-.12.288-.12.116 0 .216.048.288.12.072.096.12.24.12.408v.192c0 .048.048.072.072.072h.84c.048 0 .072-.024.072-.072v-.192c0-.432-.096-.84-.36-1.108-.216-.292-.604-.436-1.012-.436m10.832 3.828c-.072.096-.168.12-.316.12h-.48v-1.016h.48c.12 0 .216.048.288.12.079.104.121.23.12.36.008.2-.016.316-.092.416zm-.364-2.768c.12 0 .216.024.288.12.072.072.096.192.096.34s-.024.264-.096.36a.385.385 0 0 1-.264.12h-.432v-.94h.408zm.964 1.372c.144-.144.408-.48.408-.916 0-.508-.192-.82-.34-.988-.264-.288-.624-.432-1.036-.432h-1.316c-.048 0-.072.048-.072.072v4.696c0 .048.048.072.072.072h1.396c.432 0 .84-.168 1.108-.508.144-.192.316-.508.316-.988-.028-.576-.388-.916-.536-1.008zm-7.652-.46c-.072.096-.192.144-.34.144h-.408v-1.056h.408c.144 0 .264.048.34.144.096.096.12.216.12.384s-.02.288-.12.384zm.532.868c.096-.072.168-.12.24-.216.168-.192.384-.532.384-1.06 0-.508-.192-.84-.384-1.036-.24-.288-.6-.432-1.012-.456H3.54c-.048 0-.072.048-.072.072v4.692c0 .048.048.072.072.072h.84c.048 0 .072-.048.072-.072v-1.736h.288l.532 1.78c0 .024.048.048.072.048h.888c.024 0 .048-.024.072-.024s.024-.048.024-.072l-.62-1.992zm17.136.988c-.072.096-.168.12-.316.12h-.48v-1.016h.48c.12 0 .216.048.288.12.079.104.121.23.12.36.028.2-.016.316-.092.416zm-.34-2.768c.12 0 .216.024.288.12.072.072.096.192.096.34s-.024.264-.096.36a.385.385 0 0 1-.264.12h-.432v-.94h.408zm.964 1.372c.144-.144.408-.48.408-.916 0-.508-.192-.82-.34-.988-.264-.288-.624-.432-1.036-.432h-1.328c-.048 0-.072.048-.072.072v4.696c0 .048.048.072.072.072h1.404c.432 0 .84-.168 1.108-.508.144-.192.316-.508.316-.988a1.442 1.442 0 0 0-.532-1.008zm-3.224-2.36h-.84c-.048 0-.072.024-.072.072v3.324a.61.61 0 0 1-.12.384c-.072.096-.168.12-.288.12a.405.405 0 0 1-.288-.12.61.61 0 0 1-.12-.384V9.628c0-.048-.048-.072-.072-.072H17.6c-.048 0-.072.024-.072.072v3.348c0 .432.096.84.36 1.108.264.264.624.408 1.036.408.432 0 .796-.144 1.036-.408.264-.264.36-.648.36-1.108V9.628c.024-.024-.024-.072-.076-.072"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
Thanks, @adamrusted, that looks good to me now 👍🏻 I've pushed it to @mondeja's branch and will merge once the checks have passed.

**Pull request merged**
