### PR TITLE
Request : Popcorn Time icon

### PR DESCRIPTION
**Pull request by team-pct**
**Issue:** Request : Popcorn Time icon

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Popcorn Time Icon

### CODE REVIEW

**Comment by birjolaxew** [comment]
This brings up the discussion about whether we should allow sites that provide illegal content. As I mentioned [last time this was brought up](https://github.com/simple-icons/simple-icons/issues/806#issuecomment-377825693), I'm not particularly fond of allowing it but playing cops isn't something I'm interested in either. As the previous time this was brought up ended up being a misunderstanding all together, we never really reached a decision. Opinions @ericcornelissen @davidklebanoff ?

**Comment by ericcornelissen** [comment]
Although I don't like playing cops either, the Contributing Guidelines are pretty clear ⬇️ And I think it is hard to make a case for Popcorn time not promoting piracy... :neutral_face:

> We welcome icon requests. Before you submit a new issue please make sure the icon isn't related to anything that provides an illegal service (e.g. piracy, malware, threatening material, spam, etc.).

**Comment by birjolaxew** [comment]
@ericcornelissen True that, forgot we had that in :P Closing this as off topic.

**Comment by team-pct** [comment]
wow guys ! you are an open source project , we are talking about Popcorn Time Icon which is ours ! we are not promoting piracy ! we are torrent client showing the industry of Cinema how things can be done right for the customers ! now as you said earlier you are not here to play cop we are not also here to play cop about piracy ( popcorntime.sh/tos ) and also on our main page "Popcorn Time streams movies and TV shows from torrents" now Torrenting is illegal maybe where you live but where we live it is not 

But again Thank you for taking time to read all that , and good luck on your project !

**Comment by ericcornelissen** [comment]
@team-pct the fact that we're open source does not mean we can not have an opinion on things. Where I live torrenting is not illegal, and I would happily add the BitTorrent or uTorrent icon. However, piracy is illegal and as I said I think it is difficult to make the case that Popcorn Time is not promoting that. As you pointed out the website says "Popcorn Time streams movies and TV shows from torrents", and to my understanding the original creators of that content are not being compensated. That makes it piracy.

I hope you understand our decision and I get your frustration. I'm not saying our approach is perfect nor that the current system of intellectual property is.

I wish you good luck with Popcorn Time, and Merry Christmas to you guys as well 😄 


> One fun fact also Adobe is responsible for a big % of malware because of their vulnerability ...

That is a bit of a misrepresentation in my opinion. First of all I don't believe Adobe is promoting malware. Second, saying that Adobe is responsible for malware is the same as saying that Windows is responsible for malware. All software products (especially of that size) are bound to have vulnerabilities, Adobe and Windows are responsible or a large percentage of malware because so many people are using their product not because their programmers are evil.

**Comment by team-pct** [comment]
Just for clarification We would love to compensate Original creators for their work , as long as they allow users to pay them directly , we have nothing against creators of movies / Shows

Most of our users have no Access to legal alternative and the remaining others that are living in countries like yours if they use popcorn time probably they have no budget for that ... anyway guys i just found out about your project and wanted to add Popcorn Time Icon , 
Wikipedia is talking about Popcorn Time https://en.wikipedia.org/wiki/Popcorn_Time 
It does not promote it 
as i was thinking a simple icon should just deal with icon and as long as the icon itself is not copyright infringement it should no be an issue 

Same for Twitter https://twitter.com/popcorntimetv 


Take care guys i hope i made you think about that at least 0.01% differently ❤️

**Comment by ericcornelissen** [comment]
> Just for clarification We would love to compensate Original creators for their work , as long as they allow users to pay them directly

I did not know that! Why don't you state that on you website, or am I just unable to find it?


> I'm not saying our approach is perfect

And this thread is perfect to discuss if it is! Personally I find your "Wikipedia is talking about Popcorn Time, It does not promote it" argument very compelling, and the idea that we can provide icons as long as they're not copyrighted themselves is not a bad one to me.

**Comment by team-pct** [comment]
> I did not know that! Why don't you state that on you website, or am I just unable to find it?
We have sent various emails to MPAA , we just got ignored , We are doing 0 income from Popcorn Time and we pledged that we won't do any despite hundreds of emails received from AD companies .
Popcorn Time got DMCA in Github itself and we open the topic if movie producers own the right of our CODE ( as main goal of github is hosting codes ) 

Popcorn Time never and will never create a torrent for copyright infringement purpose we just scrape the web and present it as any Video Platform should do ( https://github.com/popcorn-official/popcorn-api ) 
The simple solution for piracy is global movies/tvshow availability at a price that everyone can afford to pay for , again you guys can take a look at Alexa ranking you will see that we are most popular on countries that have very limited access to legal alternative , others i am sure they really cant afford paying 3 or 4 Subscriptions just to use them rarely 

Popcorn Time will continue to exist as long as they play it this way , we are open source and not the first team

**Comment by ericcornelissen** [comment]
@team-pct, you don't have to promote Popcorn Time, it is popular where I live as well, or put what you're doing in a way that makes it look like its not piracy, turning a blind eye to the fact that the web contains illegal content doesn't change a thing in my opinion.

I get that you believe you're doing the right thing, but our current guidelines simply state that services that **provide** illegal content will not be allowed. I'm open to discussing whether we should change that, but I don't think you will be able to compel us that Popcorn Time is not providing illegal content.

**Pull request closed without merging**
