### PR TITLE
Replace Riot by Element

### LINKED ISSUE #3606: Update: Riot has become Element
**Name:** Element
**Official resources for icon and color:** https://element.io/
  

[Riot](https://simpleicons.org/icons/riot.svg) has been rebranded to [Element](https://element.io/blog/welcome-to-element/). The old Riot.im is basically depreciated at this point.

### PR DESCRIPTION
**Pull request by ericcornelissen**
### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Closes #3606, removes [Riot](https://simpleicons.org/?q=riot) and replaces it by [Element](https://element.io/) in preparation for the upcoming [v4 release](https://github.com/simple-icons/simple-icons/milestone/3).

The new SVG is based on the SVG found in the header of the Element homepage. The color is taken from that SVG. Optimized using the SVGO CLI at a precision of ~~3~~ 4.

### CODE REVIEW

**Comment by mondeja** [comment]
I'm seeing some differences between your optimization and the original, also comparing it with my version:

## My optimization

```svg
M5.593 14.218c-.485 0-.88-.392-.88-.877 0-3.282 2.668-5.943 5.958-5.943.486 0 .88.393.88.877s-.394.877-.88.877c-2.318 0-4.198 1.877-4.198 4.19 0 .486-.393.878-.88.878zm8.615 4.19c0 .485-.394.878-.88.878-3.29 0-5.956-2.662-5.956-5.945 0-.483.394-.876.88-.876.484 0 .878.393.878.877 0 2.316 1.88 4.192 4.2 4.192.484 0 .878.392.878.877zm4.2-8.626c.484 0 .878.392.878.877 0 3.282-2.667 5.943-5.957 5.943-.486 0-.88-.393-.88-.877s.394-.877.88-.877c2.318 0 4.198-1.877 4.198-4.19 0-.486.393-.878.88-.878zm-8.602-4.19c0-.485.394-.878.88-.878 3.29 0 5.956 2.662 5.956 5.945 0 .483-.394.876-.88.876-.485 0-.878-.393-.878-.877 0-2.316-1.88-4.192-4.2-4.192-.484 0-.878-.392-.878-.877zM12 24c6.627 0 12-5.373 12-12S18.627 0 12 0 0 5.373 0 12s5.373 12 12 12z
```

## Differences between your version (red) and original unoptimized (original color)

orig-eric-fix-1
orig-eric-fix-2

## Differences between your version (red) and mine (black)

mondeja-eric-fix-1
mondeja-eric-fix-2

**Comment by service-paradis** [comment]
@mondeja Was about to post exactly this, but with a different overlay color 😛 
I used the icon in the footer website and got the similar differences:
image

**Comment by ericcornelissen** [comment]
Thanks for the review guys, guess I was a little too quick with submitting this one. I re-added the icon, now with an optimized precision of 4

**Review by mondeja — APPROVED** [review]
Looks good now :+1:

**Review by service-paradis — APPROVED** [review]

**Pull request merged**
