### PR TITLE
Add akamai icon

### PR DESCRIPTION
**Pull request by ericksarabia**
**Issue:** #5307 
**Alexa rank:** 4,554
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I got hex value and SVG from [Akamai Media Resources](https://www.akamai.com/newsroom/media-resources) and use figma to update SVG sizes and colors.

### CODE REVIEW

**Comment by adsingh14** [comment]
I recommend  [this](https://github.com/simple-icons/simple-icons/pull/6692#issuecomment-939401557) link for adding missing things.

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @ericksarabia,

thanks for contributing the icon. I see a slightly difference from the origianal svg

image


i used as comparison the offical svg under `https://www.akamai.com/content/dam/site/en/images/logo/akamai-logo1.svg`

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @ericksarabia

thanks for the rework, but I still see some differences.

image

**Comment by ericksarabia** [comment]
> Hi @ericksarabia
> 
> thanks for the rework, but I still see some differences.
> 
> image

Hi @dirien 
What is the tool you use to see the differences?

**Comment by dirien** [comment]
Hi @ericksarabia,

I just use inkscape.

**Review by dirien — APPROVED** [review]
Hi @ericksarabia ,

Thanks for your contribution to simple-icons!

It's a perfect fit:
image

**Pull request merged**
