### PR TITLE
Update NPM icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** #5340

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I took the squared `n` in the footer at https://www.npmjs.com/about
- I used Inkscape to scale
- I optimized it

**_I also think we should rename this brand in a future breaking release. They always use `npm`, not `NPM`._**

### CODE REVIEW

**Review by adamrusted — COMMENTED** [review]
Icon looks spot on to me, and I may be wrong but I don't think a change in casing constitutes a breaking change, so we may get away with it here. Will ask another @simple-icons/maintainers to advise on that though.

I think we will need to keep the guidelines entry in, as there's a specific section about the logo, which states: 
`Our npm Logos are very recognizable and deserves special treatment. The npm Logos signify us, or a special relationship with us, and you may use them only with our permission. Since the goal is to avoid confusion about you being us, or your relationship with us, context counts. We will consider requests on a case-by-case basis.`

**Comment by ericcornelissen** [comment]
In our npm package, searching by title is case insensitive, [see the `index.js` template](https://github.com/simple-icons/simple-icons/blob/develop/scripts/templates/index.js), and filenames are normalized to lowercase anyway so changing "NPM" to "npm" would not be a breaking change.

As for whether we should change it, it seems it was added way back in https://github.com/simple-icons/simple-icons/pull/462 (closing issue https://github.com/simple-icons/simple-icons/issues/444) without much thought or discussion regarding the name. I agree that the name is pretty much always stylized as "npm" so I'd be in favor of changing it :+1:

**Comment by service-paradis** [comment]
Thank you @adamrusted and @ericcornelissen!

> I think we will need to keep the guidelines entry in, as there's a specific section about the logo, which states:

You're right, good catch! My mistake, dont know why I removed it 🤔 

> I don't think a change in casing constitutes a breaking change

I'm not sure why I was thinking it was breaking yesterday, but thank you both for the input 😄 

Just pushed the changes!!

**Review by adamrusted — APPROVED** [review]
Spot on, thanks @service-paradis!
Just a reminder for @simple-icons/maintainers to make sure this doesn't bump us to v5.0.0 next week!

**Pull request merged**
