### PR TITLE
Add KAYAK icon

### LINKED ISSUE #11174: Request: Kayak
### Brand Name

Kayak

### Website

https://www.kayak.com

### Popularity Metric

The Similarweb rank is 1,046.
https://www.similarweb.com/website/kayak.com

### Official Resources for Icon and Color

SVG: https://upload.wikimedia.org/wikipedia/commons/c/cb/Kayak_Logo.svg
Color: `#ff690f`

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by anhthang**
image

**Issue:** closes #11174 

**Popularity metric:**

The Similarweb rank is 1,046.
https://www.similarweb.com/website/kayak.com

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

SVG and hex value `#FF690F` extracted from the website

### CODE REVIEW

**Comment by uncenter** [comment]
From https://www.kayak.com/terms-of-use:

> Your use of and access to Our Website does not grant you any license or right to use any of the marks included on Our Website.

I think we will need to request permission here. Would you be willing to [reach out](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission) @anhthang?

**Comment by adamrusted** [comment]
Were you able to reach out @anhthang? We'll have to close this PR if not.

**Comment by anhthang** [comment]
@adamrusted yes, I sent email but haven't heard back yet

**Comment by adamrusted** [comment]
> @adamrusted yes, I sent email but haven't heard back yet

Awesome, when did you reach out to them? Just so I can update when we'll next need to review this PR.

**Comment by anhthang** [comment]
> > @adamrusted yes, I sent email but haven't heard back yet
> 
> Awesome, when did you reach out to them? Just so I can update when we'll next need to review this PR.

It's a week ago

**Comment by anhthang** [comment]
Closing as no feedback from the brand

**Pull request closed without merging**
