### PR TITLE
Add Foundry Virtual Tabletop icon

### LINKED ISSUE #5828: Request: Foundry Virtual Tabletop Logo
**Brand Name:** Foundry Virtual Tabletop
**Website:** https://foundryvtt.com/
**Alexa rank:** 136,559
  

**Official resources for icon and color:**
  
https://foundryvtt.s3-us-west-2.amazonaws.com/website-media-dev/FVTT-community-content-kit.zip
This can be found at https://foundryvtt.com/article/branding/

### PR DESCRIPTION
**Pull request by adamrusted**
image

**Issue:** closes #5828 

**Similarweb rank:** [107,491](https://www.similarweb.com/website/foundryvtt.com/)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Hex code picked is [midpoint](https://meyerweb.com/eric/tools/color-blend/#FD9C21:FF381D:1:hex) of gradient on the main logo.

### CODE REVIEW

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
@adamrusted, as it's provided by an official source, I think we should run with the simplified version that just includes the anvil. What do you reckon?

**Comment by adamrusted** [comment]
Both versions came from Andrew, and I'd associate this version moreso - if we're happy it displays okay at smaller sizes?

**Comment by PeterShaggyNoble** [comment]
For me, the numbers go missing at 24*24. And I think the anvil would stand out more if they weren't there, too.

**Review by PeterShaggyNoble — APPROVED** [review]
Looks good to me, @adamrusted 👍🏻

Before merging, though, I'm going to ping @aaclayton to make sure that they're happy with the colour choice.

**Comment by aaclayton** [comment]
Thank you @adamrusted and @PeterShaggyNoble for spending time in optimizing this SVG. I appreciate you improving it!

I think if the geometry of the logo will be in white, it would be better to choose a darker orange for the displayed background. Normally we would present our logo (see foundryvtt.com) as black outline on an orange background. If we switch the foreground to light I'd prefer seeing a darker hue of orange in the background. Maybe something like `#cb2f17` or in that neighborhood.

**Comment by PeterShaggyNoble** [comment]
Thanks for the feedback, @aaclayton 👍🏻 To clarify, the colour we provide in our data is the _brand's_ primary colour; our icon files don't have a `fill` colour, so that our users may choose which colour to use, be that black, white, the brand colour, or something else.

Given that, would you still like us to run with the `#cb2f17` you mentioned above?

**Comment by aaclayton** [comment]
Sorry, I misinterpreted the use case for the color. I thought it was for a display asset like the one in the initial issue. If it's a suggested default color for the brand I suppose `#FE6A1F` is fine. 

My expectation is that most users will use black or white in practice. Thanks for clarifying!

**Pull request merged**
