### PR TITLE
Optimize Simple Icons icon

### PR DESCRIPTION
**Pull request by LitoMore**
### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

I simply executed the `npx svgo icons/simpleicons.svg`.

### CODE REVIEW

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
We could also probably remove these 2 excess points in the bottom left while we're at it:

**Comment by LitoMore** [comment]
@PeterShaggyNoble Could you help on this? Those two control points are special, it seems we cannot just move them directly.

**Comment by PeterShaggyNoble** [comment]
Give this a try:
```
M12 0C8.688 0 6 2.688 6 6s2.688 6 6 6c4.64-.001 7.526 5.039 5.176 9.04h1.68A7.507 7.507 0 0 0 12 10.5 4.502 4.502 0 0 1 7.5 6c0-2.484 2.016-4.5 4.5-4.5s4.5 2.016 4.5 4.5H18c0-3.312-2.688-6-6-6Zm0 3a3 3 0 0 0 0 6c4 0 4-6 0-6Zm0 1.5A1.5 1.5 0 0 1 13.5 6v.002c-.002 1.336-1.617 2.003-2.561 1.058C9.995 6.115 10.664 4.5 12 4.5ZM7.5 15v1.5H9v6H4.5V24h15v-1.5H15v-6h1.5V15Zm3 1.5h3v6h-3zm-6 1.47c0 1.09.216 2.109.644 3.069h1.684A5.957 5.957 0 0 1 6 17.97Z
```

**Comment by LitoMore** [comment]
Those excess points look good now. There are some new differences:



But this difference look good to me. Because the new shape you provided the the actual 6x6 circle. Our previous one is 5.846x6.

**Review by PeterShaggyNoble — APPROVED** [review]
Ha! I never even looked at that circle! Recreating the steps I see now that the right edge shifted when I removed the 2 points and the left edge shifted during optimisation, so the resulting perfect circle is entirely accidental!

Anyway, as it's our own logo, we don't need to subject it to the same exacting standards as we do all others; I'm happy to run with this version if you are.

**Pull request merged**
