### PR TITLE
Add Tidal

### PR DESCRIPTION
**Pull request by davidklebanoff**
**Issue:** #1193 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

Icon pulled from the official website. Specifically from the bottom of the [login page](https://listen.tidal.com/login).

### CODE REVIEW

**Comment by davidklebanoff** [comment]
I could be persuaded either way. 🤷‍♂️

Thinking out loud here... In all official uses I have seen the icon is always white and the background is always black. So does this mean the brand is white or black?

Typically when we see white icons, it's because they are using the "light version" on top of a brand color (e.g. facebook). So one could make that argument using the same logic that the brand color is black.

But, if the logo was all black and sitting atop a white page, we would also assume the brand is black. 🤔

**Comment by ericcornelissen** [comment]
> In all official uses I have seen the icon is always white and the background is always black. [...] Typically when we see white icons, it's because they are using the "light version" on top of a brand color (e.g. facebook). So one could make that argument using the same logic that the brand color is black.

That I agree with. The main reason I think the brand color in this case should be black (or dark gray) is because the entire website is black(/dark).


> And, if the logo was all black and sitting atop a white page, we would also assume the brand is black.

That is a fair point and a "bias" I hadn't noticed myself yet 🤔 Although, personally, I feel like having white as a brand color is quite rare and shouldn't be selected unless it is abundantly clear it is. Mainly because white is the default background color for both the web and paper.

**Comment by davidklebanoff** [comment]
Updated. I chose black instead of a dark gray because it was consistently used across their homepage, social media profiles, and favicon.

**Comment by ericcornelissen** [comment]
Thanks for the work on this @davidklebanoff 👌

**Pull request merged**
