### PR TITLE
Add Best Buy Icon

### LINKED ISSUE #11249: Request: Best Buy
### Brand Name

Best Buy

### Website

https://www.bestbuy.com/

### Popularity Metric

The similarweb ranking is 521: https://www.similarweb.com/website/bestbuy.com/#overview

### Official Resources for Icon and Color

SVG: Located in header
Color: `#0046BE`

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by jrhaberland**
bestbuy

**Issue:** closes #11249 

**Popularity metric:**

The similarweb ranking is 521: https://www.similarweb.com/website/bestbuy.com/

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PratyushJayachandran** [comment]
The [Terms and Conditions page](https://www.bestbuy.com/site/help-topics/terms-and-conditions) states that:

> The Best Buy and Geek Squad logos and other trademarks on the Best Buy Properties are the property of their respective owners and are owned by, licensed to, or, where required, used with permission by Best Buy and may not be reproduced, copied, or manipulated in any manner without the express, written approval of the trademark owner.

Hence, we would require permission to use the logo. Would you be able to contact them @jrhaberland?

**Comment by jrhaberland** [comment]
Sent them an email

**Comment by PratyushJayachandran** [comment]
> Sent them an email

Awesome! We will wait for reply.

**Comment by uncenter** [comment]
Closing as no feedback from brand. If you do a response from them @jrhaberland - feel free to post it here and we can re-open the PR.

**Pull request closed without merging**
