### PR TITLE
Add canvas

### LINKED ISSUE #5477: Canvas
**Brand Name:** Canvas
**Website:** https://www.instructure.com/
**Alexa rank:** 66
  

**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
canvas

**Issue:** closes #5477 

**Similarweb rank:** 176. See https://www.similarweb.com/website/instructure.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from Brand Guidelines PDF https://www.instructure.com/resources/ebooks/instructure-brand-guide-2022
Color: Taken from logo in that PDF `#e72429`

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Annoyingly, I'm seeing [a tiny difference](https://github.com/simple-icons/simple-icons/assets/1830867/42bfaacc-ccd6-48b4-a9fe-88e88ab2b61e) between the PR in black, and the source icon in red. This is pulled from Page 6 of their [2023 Brand Book](https://www.instructure.com/resources/ebooks/instructure-brand-guide-2023)

**Comment by PratyushJayachandran** [comment]
> Annoyingly, I'm seeing [a tiny difference](https://github.com/simple-icons/simple-icons/assets/1830867/42bfaacc-ccd6-48b4-a9fe-88e88ab2b61e) between the PR in black, and the source icon in red. This is pulled from Page 6 of their [2023 Brand Book](https://www.instructure.com/resources/ebooks/instructure-brand-guide-2023)

Missed this comment somehow. I don't see any difference on my end but re-did with the source you mentioned. Can you please review again @adamrusted?

**Review by LitoMore — CHANGES_REQUESTED** [review]
CleanShot 2023-10-04 at 03 13 36@2x

I can see some differences as well.

**Comment by PratyushJayachandran** [comment]
> I can see some differences as well.

Not sure why it is happening but I re-did again from `Single Mar`k logo on page 26
image

**Review by PeterShaggyNoble — APPROVED** [review]

**Pull request merged**
