### PR TITLE
Add Power Platform

### PR DESCRIPTION
**Pull request by adamrusted**
powerplatform (2)

**Issue:** https://github.com/simple-icons/simple-icons/issues/7780

**Similarweb rank:** N/A (Microsoft Product, Citizen Developer Platform)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
In the process of updating all of the Dynamics / Power Platform icons (I use them for work!)
This is a new icon for the over-arching 'Power Platform' ecosystem, which encompasses Power BI, Power Apps, Power Virtual Agents, etc.

Hex code is picked randomly from the middle of the icon, given the entire thing is a gradient.

### CODE REVIEW

**Comment by LitoMore** [comment]
CleanShot 2022-09-17 at 12 27 18@2x

This part looks a little weird.

**Comment by LitoMore** [comment]
CleanShot 2022-09-17 at 14 39 58@2x

@adamrusted We could apply an inside 0.5px stroke to each shape.

**Comment by adamrusted** [comment]
> CleanShot 2022-09-17 at 14 39 58@2x
> 
> @adamrusted We could apply an inside 0.5px stroke to each shape.

Would an inside stroke not impact the overall size of the icon? Or do you mean just the central shape?

**Comment by LitoMore** [comment]
> Would an inside stroke not impact the overall size of the icon? Or do you mean just the central shape?

I mean all those three shapes. I think the change of overall size is acceptable.

**Comment by adamrusted** [comment]
> > Would an inside stroke not impact the overall size of the icon? Or do you mean just the central shape?
> 
> I mean all those three shapes. I think the change of overall size is acceptable.

Let me see if I can tidy up the edges of that original image - perhaps just extend it so the rounded edge doesn't show inside the icon

**Comment by LitoMore** [comment]
CleanShot 2022-09-17 at 16 43 58@2x

After we've modified the first shape we should make sure the edges on the right side are always on the edge of the new circle.

**Comment by adamrusted** [comment]
Apologies @LitoMore - I was just getting my branch up to date. Just pushed a new update - though manually dragged the points, so be kind 🙏

**Comment by LitoMore** [comment]
@adamrusted 😂 Sorry I clicked the close button by accident.

**Comment by adamrusted** [comment]
> @adamrusted 😂 Sorry I clicked the close button by accident.

Rude! 🤣

**Comment by LitoMore** [comment]
> Apologies @LitoMore - I was just getting my branch up to date. Just pushed a new update - though manually dragged the points, so be kind 🙏

LOL. Of course. My native language is not English so sometimes I wrote a wrong tone 🙏

**Comment by adamrusted** [comment]
> LOL. Of course. My native language is not English so sometimes I wrote a wrong tone 🙏

No worries! It's all good :smile:

**Comment by LitoMore** [comment]
I think the inside stroke didn't break their design concept for the logo. Just like fonts have thin and bold. The inside stroke ensures that its own curve is not modified by strokes from other shapes.

**Comment by adamrusted** [comment]
@LitoMore - not sure how I'd be able to apply the inner stroke effectively in Affinity. All I've done here is an outer stroke of the centre piece, which to my eye is the 'raised' bit of the logo - and then extended it out so we don't get those weird rounded corners any more. Might need some further guidance if we need to change that :)

**Comment by LitoMore** [comment]
<p align="right">
CleanShot 2022-09-17 at 19 05 59@2x
CleanShot 2022-09-17 at 18 50 55@2x
</p>

1. Duplicate the shape
2. Select the `Align Stroke to Inside`
3. Change its color to none
4. Select `Layer -> Expand Stroke` to convert its stroke to fill
5. Now you can use `Layer -> Geometry` on the processed shape and the backup one to get a new shape.

**Comment by adamrusted** [comment]
@LitoMore - Give that a try. I'm trying to avoid using that inner stroke, as it'll warp the image too much. I've given the edges on this another go - let me know what you think.

**Comment by LitoMore** [comment]
@simple-icons/icon-review Any suggestions?

**Pull request closed without merging**
