### PR TITLE
Add `statsmodels` icon

### LINKED ISSUE #6903: statsmodels
### Brand Name

statsmodels

### Website

www.statsmodels.org

### Popularity Metric

97,672

### Official Resources for Icon and Color

https://www.statsmodels.org/stable/_images/statsmodels-logo-v2-no-text.svg
https://www.statsmodels.org/stable/_images/statsmodels-logo-v2-no-text-dark.svg
https://www.statsmodels.org/stable/_images/statsmodels-logo-v2-no-text-light.svg

### Additional Comments

https://www.statsmodels.org/stable/about.html

### Contributing

No

### PR DESCRIPTION
**Pull request by adamrusted**
image

**Issue:** closes #6903

**GitHub stars:** [9,072](https://github.com/statsmodels/statsmodels)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

SVG from website header. Hex listed as primary colour on homepage.

### CODE REVIEW

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
There's [a small shift](https://github.com/simple-icons/simple-icons/assets/15157491/e900a13f-ca3e-431c-bf9b-a8846efadb0d) in all the circles, @adamrusted, which is likely just a precision issue.

There are also some differences throughout the curve ([example](https://github.com/simple-icons/simple-icons/assets/15157491/0182bd65-cdfe-4994-82cc-44f9f9c64905)) but that could be our different software being differently weird about `stroke`s again, so I've asked for another pair of eyes on this.

**Comment by service-paradis** [comment]
Comparing with the white SVG from their website header, I'm seeing the same differences as @PeterShaggyNoble. Can you take another look @adamrusted?

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
I'm still seeing similar differences in your new version, @adamrusted. I think the problem might be that the source icon isn't a perfect square while yours is.

**Comment by adamrusted** [comment]
@simple-icons/maintainers feel free to pick this one up. I'm not in a place at the moment where I can make appropriate changes.

**Comment by PeterShaggyNoble** [comment]
I'm still seeing those same differences, @adamrusted, although the shift in the circles seems to be less pronounced. Also, when resized to fir our canvas, the source icon is coming in at 24*23.982.

**Comment by adamrusted** [comment]
You know what it might be? I think Affinity Designer is rounding numbers!

**Comment by PeterShaggyNoble** [comment]
[I hate this icon!](https://github.com/simple-icons/simple-icons/assets/15157491/faddb793-646a-4b95-9a2b-0961a902b543) We're both obviously doing different things to get different results; for one the source icon resizes to 23.982 for me.

**Comment by PeterShaggyNoble** [comment]
I'm still seeing differences 😢 Dunno what the problem is. Let's see if @PratyushJayachandran & @service-paradis are seeing the same.

**Comment by LitoMore** [comment]
CleanShot 2024-03-14 at 21 21 48@2x

I can see some differences as well. I'm using Inkscape.

**Review by PratyushJayachandran — CHANGES_REQUESTED** [review]
I see the same issues @adamrusted 
image

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
😢 This icon hates us! Still differences throughout (with yours in red).

**Comment by adamrusted** [comment]
_I'm going to close this down, but leave it linked to the original Issue - so someone else can attempt this if they want to._

**Pull request closed without merging**
