### PR TITLE
Add Imgur (#1986)

### LINKED ISSUE #1986: Imgur (image hosting service)
Imgur is an online image platform usually used from Reddit. 

**Name:** Imgur
**Website:** https://imgur.com/
**Official resources for icon and color:** 
- They have offered their logos on [their company site](https://imgurinc.com/press) (though I can't see a download link). 
- Suggested brand color is `#1bb76e` . 
It is just the primary color used in the website. 
- Anyways, just use the SVG from their app site at https://s.imgur.com/images/imgur-logo.svg?1
  

Alexa ranking is at [~87](https://www.alexa.com/siteinfo/imgur.com).

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
Closes #1986

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
see issue

### CODE REVIEW

**Comment by birjolaxew** [comment]
After some further discussion in #1986, it looks like the favicon is preferred over the wordmark. Could you update the PR to use a vectorization of that? (one is available [here](https://github.com/simple-icons/simple-icons/issues/1986#issuecomment-558405181), or you're free to make one yourself :) )

**Comment by runxel** [comment]
Took your version! ✨

**Comment by ericcornelissen** [comment]
Thanks for updating the SVG @runxel 👍 Looks like you still have the old source in that. Could you update it? I think `https://s.imgur.com/images/favicon-152.png` works 🤔

**Comment by runxel** [comment]
Ah thanks, totally forget. Sorry! It's fixed :)

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @runxel 👍

**Pull request merged**
