### PR TITLE
Add Google Tag Manager icon (#1675)

### PR DESCRIPTION
**Pull request by phatbhoy67**
**Issue: #1675**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO ~or SVGOMG~
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Source is [official .svg](https://www.gstatic.com/analytics-suite/header/suite/v2/ic_tag_manager.svg) found in their [website](https://tagmanager.google.com/#/home) header, manually adjusted to represent colour and shape differences with negative space.

Blues present in logo: `#246fdb`,`#4285f4`,`#8ab4f8`.

Hex value chosen `#246fdb` is the darkest blue.

Built on GitPod, working as expected.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
> Looking at the [original](https://www.gstatic.com/analytics-suite/header/suite/v2/ic_tag_manager.svg) it seems if youre version is mirrored (at least in the bottom, where the left part is over the right one) 🤔

Yeah @runxel no idea what I was doing there tbh 🤣 

Have updated the path and made the cut outs visually even (he says..... 👀) and wider, thanks for the suggestion 👍

**Comment by phatbhoy67** [comment]
Hey @runxel thanks for the review.

Please add your .svg code as a suggested change that I will happily accept, no point in me redoing your work 👍

**Comment by runxel** [comment]
Great, I did so! :)

Now someone else should merge it in, just to be sure _I didn't_ made some other error/regression here.

**Comment by ericcornelissen** [comment]
Thanks for your work on this @phatbhoy67 and @runxel, this is now _finally_ merged 😄

**Pull request merged**
