### PR TITLE
Add anime.js

### LINKED ISSUE #7691: Request: anime.js
### Brand Name

anime.js

### Official Resources for Icon and Color

https://animejs.com/

https://github.com/juliangarnier/anime/blob/master/documentation/assets/img/anime-mini-logo.svg

### Contributing

No

### PR DESCRIPTION
**Pull request by adamrusted**
animedotjs

**Issue:** closes #7691

**Similarweb rank:** [238,254](https://www.similarweb.com/website/animejs.com/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
For some reason, @PeterShaggyNoble's preview generator didn't like this one. It also shows that the filename should still contain 'dot' but I don't think that's the case any more?

### CODE REVIEW

**Comment by LitoMore** [comment]
Looks the `a` and `e` in your processed one not correct.

It should be:

CleanShot 2022-09-18 at 07 36 02@2x

**Comment by adamrusted** [comment]
> Looks the `a` and `e` in your processed one not correct.

Very weird! Definitely didn't display like that in my editor... I'll take another look now.

**Comment by adamrusted** [comment]
@LitoMore - The issue I'm having is that the path is _requiring_ the use of a `fill-rule:evenodd;` either on the path or the SVG itself - and I can't for the life of me remember how to get around that (at least, not in Affinity Designer).

**Comment by LitoMore** [comment]
@adamrusted Just delete that path . `fill-rule: evenodd;` means no-color.

**Pull request closed without merging**
