### PR TITLE
Rename WEBTOON

### PR DESCRIPTION
**Pull request by service-paradis**
**Issue:** #5251 (following review from #5355)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description

Looks like they've removed `LINE` from their branding across the board.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
@service-paradis, could you add "LINE WEBTOON" as an `old` alias to this?

**Comment by service-paradis** [comment]
> @service-paradis, could you add "LINE WEBTOON" as an `old` alias to this?

Done :)

**Review by adamrusted — APPROVED** [review]
Thanks for this one, @service-paradis.
Happy for this to be merged straight in!

**Comment by PeterShaggyNoble** [comment]
Following on from Eric's comment [here](https://github.com/simple-icons/simple-icons/pull/4717#issuecomment-846994050), can you remove the alias and we'll revisit it when we've decided _exactly_ how we want to use them and have added them to the package?

**Comment by service-paradis** [comment]
> Following on from Eric's comment [here](https://github.com/simple-icons/simple-icons/pull/4717#issuecomment-846994050), can you remove the alias and we'll revisit it when we've decided _exactly_ how we want to use them and have added them to the package?

Alias is gone!

**Pull request merged**
