### PR TITLE
Add HashiCorp Icon

### PR DESCRIPTION
**Pull request by uiuxarghya**
hashicorp

**Issue:** #5809 
**Alexa rank:**  30,283
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Brand Resources : https://www.hashicorp.com/brand
Hex Value : `#FFFFFF`

### CODE REVIEW

**Comment by adamrusted** [comment]
Thanks for this PR @uiuxarghya - though it looks like you've based this off your Palo Alto branch, instead of Develop. On this branch, could you please remove the Palo Alto references?

**Comment by uiuxarghya** [comment]
> Thanks for this PR @uiuxarghya - though it looks like you've based this off your Palo Alto branch, instead of Develop. On this branch, could you please remove the Palo Alto references?

By mistake, I pushed that commit of Palo Alto Networks Icon in my develop branch.
Actually, I don't know how to do remove the Palo Alto references. 
Could you please merge this PR?

**Comment by adamrusted** [comment]
Hey @uiuxarghya - I've removed the references to Palo Alto on this PR. Will be working through some PRs later today, so hopefully can get this looked at. If not, another maintainer will be able to pick it up during the week.

**Comment by uiuxarghya** [comment]
> Hey @uiuxarghya - I've removed the references to Palo Alto on this PR. Will be working through some PRs later today, so hopefully can get this looked at. If not, another maintainer will be able to pick it up during the week.

Thanks, @adamrusted for removing it.

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @uiuxarghya 👍🏻

Could you let us know which file you based your version off so we can make sure we're comparing like with like? When compared to `Corporate\Logomark\RGB\SVG\HashiCorp_Icon_Black_RGB.svg` from the zip file, I'm seeing the differences below, with your version in red.

**Comment by uiuxarghya** [comment]
Well @PeterShaggyNoble 
I have used the White Logomark in  `Corporate\Logomark\RGB\SVG\HashiCorp_Icon_White_RGB.svg`
But both white and black logomarks have some minor differences.

Asset 2

Asset 3

**Comment by adamrusted** [comment]
Hey @uiuxarghya - those tiny differences look to be related to the precision of the SVG. Could you try rebuilding from source, and exporting with a precision of 4 please? That may help get rid of those tiny inconsistencies.

**Comment by uiuxarghya** [comment]
> Hey @uiuxarghya - those tiny differences look to be related to the precision of the SVG. Could you try rebuilding from source, and exporting with a precision of 4, please? That may help get rid of those tiny inconsistencies.

Okay, I will do it.

**Comment by uiuxarghya** [comment]
> Hey @uiuxarghya - those tiny differences look to be related to the precision of the SVG. Could you try rebuilding from source, and exporting with a precision of 4 please? That may help get rid of those tiny inconsistencies.

I have used this file `\Corporate\Logomark\RGB\AI\HashiCorp_Icon_Black_RGB.ai`
I have updated the SVG code with precision 4 as you said. Can you please check it?

**Comment by ericcornelissen** [comment]
I'm still seeing some differences when comparing the SVG in the Pull Request to the `.ai` file you specified in Illustrator @uiuxarghya 🙁 You _could_ try rebuilding from the source - if you're not using Illustrator you may be better of starting from one of the SVGs - but I don't have much advice beyond that as I'm convinced an icon this simple doesn't need a precision of 5.

(red is the `.ai` file, black is your SVG)

image

**Review by dirien — CHANGES_REQUESTED** [review]
hi @uiuxarghya 

can you use this svg:

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>HashiCorp</title><path d="M23.3332 18.5493 13.8852 24v-4.0951l5.8979-3.4051V3.4096l3.55 2.0489zM13.8852.0006V10.426h-3.771V6.535L6.5646 8.584v13.3575l3.5494 2.054V13.5998h3.7711v3.8658l3.55-2.0502V2.0501L13.8847.0006ZM.6668 5.4507 10.1141 0v4.0951L4.2163 7.4996v13.0908L.6668 18.5415V5.4501Z"/></svg>
```
image

i took it from the official svg of hasicorp :`https://www.hashicorp.com/favicon.svg`

**Pull request closed without merging**
