### PR TITLE
Add Müller icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** #6460 
**Alexa rank:** 65,838
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

icon -> https://www.mueller.de/7aaea20bf455fcb4119f987a33c3860fb6bd5dc6/assets/base/images/logotype.svg

### CODE REVIEW

**Comment by dirien** [comment]
Add a comparison 

image

**Review by sachinraja — CHANGES_REQUESTED** [review]
differences along the edges
image

**Comment by dirien** [comment]
Hi @sachinraja,

i checked the Icon, but I could not see this strong difference like you have on your screenshot

image

**Comment by sachinraja** [comment]
Can you send the exact link to your source?

**Comment by sachinraja** [comment]
> Can you send the exact link to your source?

bumping this @dirien

**Comment by dirien** [comment]
@sachinraja it's in the issue and in the description of the PR

**Review by sachinraja — APPROVED** [review]
Great job, another perfect match!

**Pull request merged**
