### PR TITLE
Check icon titles and slugs with svglint

### PR DESCRIPTION
**Pull request by LitoMore**
Fix the problem mentioned in https://github.com/simple-icons/simple-icons/pull/12010#discussion_r1804243708.

[Screencast from 17-10-24 12:51:00 PM IST.webm](https://github.com/user-attachments/assets/8373580f-7e1c-4c03-b5fe-e7acfdc4cef4)

### CODE REVIEW

**Comment by mondeja** [comment]
But this is covered by the tests:

https://github.com/simple-icons/simple-icons/blob/afd656872537b6c47241c70191ae0e4824ef0c88/tests/test-icon.js#L44-L46

Which have been failed in the linked PR as expected: https://github.com/simple-icons/simple-icons/actions/runs/11368626959/job/31624298504#step:5:31

**Review by mondeja — COMMENTED** [review]
But this is covered by the tests:

https://github.com/simple-icons/simple-icons/blob/afd656872537b6c47241c70191ae0e4824ef0c88/tests/test-icon.js#L44-L46

Which have been failed in the linked PR as expected: https://github.com/simple-icons/simple-icons/actions/runs/11368626959/job/31624298504#step:5:31

IMO, lints are just for stylistic changes. The SVGLint ones are used to improve the SVG.

**Comment by LitoMore** [comment]
I see. I think we can polish those error message. It's hard to understand. The actual and expected are written in reverse.

**Comment by mondeja** [comment]
You're right! Would you mind to rewrite this PR to check `<title>`s on tests instead?

**Comment by mondeja** [comment]
Double checked and it seems to be fine. Closing...

**Pull request closed without merging**
