### PR TITLE
Add PyCQA

### LINKED ISSUE #3623: PyCQA:  Python Code Quality Authority icon request
**Name:** PyCQA
**Website:** https://PyCQA.org
**Alexa rank:** 598,088
  

**Official resources for icon and color:** https://github.com/PyCQA/meta/issues/1#issuecomment-201368468

### PR DESCRIPTION
**Pull request by adamrusted**
image

**Issue:** closes #3623 

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Going to ping @glynnis again for their feedback on this before starting the review process. Are you happy with this monochrome treatment and the choice of colour, Glynnis?

**Comment by glynnis** [comment]
@PeterShaggyNoble Looks great!

**Comment by adamrusted** [comment]
@simple-icons/maintainers feel free to pick this one up. I'm not in a place at the moment where I can make appropriate changes.

**Review by PeterShaggyNoble — APPROVED** [review]
Looks good to me now, @adamrusted; nice work.

**Pull request merged**
