### PR TITLE
Archicad icon update

### LINKED ISSUE #3308: Archicad has a new logo
**Name:** Archicad
**Official resources for icon and color:**  https://graphisoft.com/
  

No brand page, but on the homepage is the new logo ~~featured as svg~~.  Scratch that! It's just another dumb "lets put raster inside a vector format" bullshit ....

### PR DESCRIPTION
**Pull request by runxel**
**Issue:** closes #3308

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The color `#4971D0` is the midpoint of the gradient.
A vector logo was found by @PeterShaggyNoble.
Also they changed the case back from all caps to normal case.

simpleicons

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
SVG looks good to me, @runxel :+1: Although, it is coming into Inkscape at 24.001 wide - given that the build isn't failing, I'd say it's probably just a rounding issue but you might want to double check.

Would the `#2d50a5` blue, used for the fill of the dot be a better choice for the colour?

**Comment by runxel** [comment]
I changed the color; it's maybe something easier to agree on. (Especially in the light of a "no-gradient-color" rule :D)

Regarding the size: It shows 24px for me at least in Illustrator (and it's not Illustrator doesn't show sufficient enough decimal places. It does for the height... but maybe it's overcorrecting)
Weirdly enough, in Inkscape it shows `23.994` – I don't understand what is going on here. 🤣 

And _now_ the build failed. So I fixed it by throwing more precision on it.
Sorry for the inconvenience. 🙃

**Comment by PeterShaggyNoble** [comment]
Illustrator can be weird sometimes! 😕

Managed to get the precision back down to 3, if you want to double check it and run with it:
```
M.15 19.827a1.41 1.41 0 1 0 2.52 1.267s7.85-16.01 14.255-16.148c4.23-.09 4.231 5.642 4.231 5.642a1.41 1.41 0 1 0 2.82 0c.001 0 .058-8.381-7.018-8.457a5.806 5.806 0 0 0-.177-.003c-8.14 0-16.63 17.7-16.63 17.7M24 14.911a1.41 1.41 0 1 0-2.821 0 1.41 1.41 0 0 0 2.821 0Z
```

**Comment by runxel** [comment]
> Illustrator can be weird sometimes! 😕
True, but why did you had something different in Inkscape than I did?....

> Managed to get the precision back down to 3, if you want to double check it and run with it:
Sorry, for me svglint is failing on that one. (?)

**Comment by ericcornelissen** [comment]
> Sorry, for me svglint is failing on that one. (?)

I have the same issue.

I managed to get it down to a precision of 3 that doesn't fail on `npm run svglint` but it looks slightly distorted. So I guess the current version is the best we can do 👍 Thanks @runxel

**Pull request merged**
