### PR TITLE
Updated Anaconda

### PR DESCRIPTION
**Pull request by fbernhart**
anaconda

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by mondeja** [comment]
I've rebuilt from source using the logo in their main page https://www.anaconda.com/ and its quite different to the logo in simple-icons. Also, the source of `_data/simple-icons.json` seems outdated. Can you rebuilt using the icon in their header and update the source of  `_data/simple-icons.json` @fbernhart?

**Comment by fbernhart** [comment]
@mondeja It's always failing 😞 And I have no idea what else could I try. Can you give it a try?

The combined path I get from the original SVG (before optimization) is:
```
M 12.045274,0.03322204 A 12.181753,12.181753 0 0 0 10.683894,0.11138735 17.513061,17.513061 0 0 1 12.49733,1.5444181 L 12.976744,1.9821439 12.51166,2.4328972 A 15.048047,15.048047 0 0 0 11.386079,3.6366429 L 11.207602,3.8515976 A 8.5272269,8.5272269 0 0 1 12.067421,3.8020929 8.1546086,8.1546086 0 1 1 7.7813565,18.950531 15.764621,15.764621 0 0 1 5.9405628,19.057356 H 5.0807444 A 21.848332,21.848332 0 0 0 5.3452037,21.923418 11.966781,11.966781 0 1 0 12.045274,0.03322204 Z M 8.1695768,0.67808589 A 12.181753,12.181753 0 0 0 5.545828,1.9534833 15.506655,15.506655 0 0 1 7.3592631,2.3833925 18.552093,18.552093 0 0 1 8.1695768,0.67808589 Z m 1.2532508,0.0716515 A 16.23756,16.23756 0 0 0 8.4275226,2.748164 16.151571,16.151571 0 0 1 10.032517,3.4073581 6.9794276,6.9794276 0 0 1 10.462426,2.8992835 C 10.696507,2.6126541 10.935307,2.3404225 11.178942,2.082456 A 15.048047,15.048047 0 0 0 9.4228276,0.74973739 Z M 4.6794958,2.9487882 a 14.969224,14.969224 0 0 0 0,2.3358402 c 0.5875904,-0.064492 1.1958791,-0.09966 1.8121325,-0.106826 A 16.617344,16.617344 0 0 1 6.972345,3.4295049 16.481195,16.481195 0 0 0 4.6794958,2.9487882 Z M 3.619053,3.5011564 A 11.938118,11.938118 0 0 0 1.7626268,5.8799875 17.004294,17.004294 0 0 1 3.639897,5.4357479 17.391243,17.391243 0 0 1 3.619053,3.5011564 Z M 8.0262735,3.7877626 C 7.8829595,4.2248725 7.7605214,4.6762043 7.6458696,5.1348115 A 8.2549289,8.2549289 0 0 1 9.3160016,4.3323142 C 8.8932231,4.1316737 8.4705499,3.9525745 8.0262735,3.7877626 Z M 6.2988205,6.2160983 A 14.05201,14.05201 0 0 0 4.7433307,6.324227 c 0.064492,0.523099 0.1576241,1.0382541 0.2722759,1.5541872 A 8.3910779,8.3910779 0 0 1 6.2988205,6.2160983 Z M 3.7480258,6.3528877 A 15.31318,15.31318 0 0 0 1.1464236,7.0694032 h -0.078165 v 0.078165 a 17.104613,17.104613 0 0 0 1.2675808,2.5442811 l 0.042991,0.07165 0.071652,-0.049508 A 16.309217,16.309217 0 0 1 4.1844488,8.631402 L 4.2417698,8.596233 V 8.5389066 A 16.868145,16.868145 0 0 1 3.8340076,6.4453833 V 6.3528877 Z M 0.64486285,8.0946711 0.58102784,8.2952952 A 11.844963,11.844963 0 0 0 -9.9468728e-7,11.655101 v 0.208442 L 0.14330208,11.712422 a 17.706536,17.706536 0 0 1 1.58415032,-1.44736 l 0.057321,-0.04299 -0.042991,-0.06383 A 16.180233,16.180233 0 0 1 0.71651441,8.2874796 Z M 4.4137337,9.3479219 4.2352563,9.4482343 C 3.7694834,9.7205316 3.3038224,10.02142 2.8595467,10.336713 l -0.065137,0.0508 0.050807,0.06383 c 0.3081267,0.43711 0.6441839,0.86695 0.995305,1.275398 L 3.977311,11.892198 V 11.683757 A 8.1761058,8.1761058 0 0 1 4.3420824,9.534211 Z m -2.2133812,1.5046821 -0.071652,0.05081 a 16.574349,16.574349 0 0 0 -1.81343487,1.733963 l -0.0573212,0.05732 0.0651378,0.05733 a 15.449329,15.449329 0 0 0 1.99191267,1.48253 l 0.071652,0.05081 0.042991,-0.07947 a 16.739161,16.739161 0 0 1 1.0526262,-1.640169 v -0.05081 l -0.042991,-0.04951 A 16.989961,16.989961 0 0 1 2.2498573,10.924255 Z m 1.8551235,2.071381 -0.1211562,0.171963 a 15.36334,15.36334 0 0 0 -0.9171397,1.433031 l -0.042991,0.07165 0.071652,0.04299 a 16.610178,16.610178 0 0 0 1.5620035,0.766021 l 0.1928078,0.08598 -0.085982,-0.192808 A 8.0399568,8.0399568 0 0 1 4.055476,13.131121 Z m -3.97600892,0.479414 v 0.200624 a 11.758974,11.758974 0 0 0 0.94580032,3.325934 l 0.078165,0.186294 0.071652,-0.19411 a 16.216063,16.216063 0 0 1 0.8454881,-1.999729 l 0.057321,-0.06383 -0.063835,-0.04299 a 17.197769,17.197769 0 0 1 -1.77695764,-1.28322 z m 2.54297812,1.805619 -0.035174,0.07947 a 15.764621,15.764621 0 0 0 -0.9822774,2.479144 v 0.07947 h 0.085982 a 16.151571,16.151571 0 0 0 2.687584,0.501561 l 0.071652,0.0065 v -0.08601 A 17.563221,17.563221 0 0 1 4.614359,16.213405 v -0.06514 H 4.5505228 A 16.266223,16.266223 0 0 1 2.7019131,15.252006 Z m 2.5442811,1.168571 v 0.114643 a 17.255094,17.255094 0 0 0 -0.1511197,1.827765 v 0.07816 h 0.93147 c 0.2866295,0 0.6233421,0.01433 0.9458,0 H 7.1013175 L 6.9358682,18.26919 A 8.0112938,8.0112938 0 0 1 5.295699,16.43491 Z m -3.289457,2.100041 0.1146424,0.171964 a 11.988278,11.988278 0 0 0 2.50129,2.737088 l 0.1576334,0.128973 v -0.200624 a 22.579237,22.579237 0 0 1 -0.2006243,-2.33584 v -0.07165 h -0.071651 a 16.230394,16.230394 0 0 1 -2.3006657,-0.38692 z
```

But it doesn't matter how many times I optimize it with SVGOMG with a different precision (3, 4, 5) and try to resize/recenter it. It always fails with:

>  x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 24.001 x 23.934

**Comment by mondeja** [comment]
I can see that all other implementations are returning the same BBOX of the linter:

<details>
  <summary>Comparison</summary>

### anaconda.svg

```svg
M12.0453.0332a12.1818 12.1818 0 00-1.3614.0782 17.513 17.513 0 011.8134 1.433l.4794.4377-.465.4508a15.048 15.048 0 00-1.1256 1.2037l-.1785.215a8.5272 8.5272 0 01.8598-.0495 8.1546 8.1546 0 11-4.286 15.1484 15.7646 15.7646 0 01-1.8408.1069h-.8599a21.8483 21.8483 0 00.2645 2.866 11.9668 11.9668 0 106.7-21.8902zM8.1696.6781a12.1818 12.1818 0 00-2.6238 1.2754 15.5067 15.5067 0 011.8135.4299A18.552 18.552 0 018.1696.678zm1.2532.0716a16.2376 16.2376 0 00-.9953 1.9985 16.1516 16.1516 0 011.605.6592 6.9794 6.9794 0 01.43-.5081c.234-.2866.4728-.5589.7164-.8168A15.048 15.048 0 009.423.7497zm-4.7433 2.199a14.9692 14.9692 0 000 2.336c.5876-.0646 1.1959-.0997 1.8121-.1069a16.6173 16.6173 0 01.4807-1.7483 16.4812 16.4812 0 00-2.2928-.4807zm-1.0604.5525A11.9381 11.9381 0 001.7626 5.88 17.0043 17.0043 0 013.64 5.4357a17.3912 17.3912 0 01-.0208-1.9345zm4.4072.2866c-.1433.437-.2658.8884-.3804 1.347a8.255 8.255 0 011.6701-.8025 15.7998 15.7998 0 00-1.2897-.5445zM6.2988 6.216a14.052 14.052 0 00-1.5555.1081c.0645.5231.1577 1.0383.2723 1.5542a8.391 8.391 0 011.2832-1.6623zm-2.5508.1368a15.3132 15.3132 0 00-2.6016.7165h-.0781v.0782a17.1046 17.1046 0 001.2675 2.5442l.043.0717.0717-.0495a16.3092 16.3092 0 011.734-1.0826l.0573-.0352V8.539a16.8681 16.8681 0 01-.4078-2.0935v-.0925zM.645 8.0947l-.0639.2006A11.845 11.845 0 000 11.6551v.2084l.1433-.151a17.7065 17.7065 0 011.5842-1.4474l.0573-.043-.043-.0639A16.1802 16.1802 0 01.7165 8.2875zm3.7688 1.2532l-.1784.1003a18.719 18.719 0 00-1.3758.8885l-.065.0508.0507.0638c.3081.4372.6442.867.9953 1.2754l.1368.1655v-.2084a8.1761 8.1761 0 01.3648-2.1496zm-2.2133 1.5047l-.0717.0508a16.5743 16.5743 0 00-1.8134 1.734l-.0574.0573.0652.0573a15.4493 15.4493 0 001.9919 1.4826l.0716.0508.043-.0795a16.7392 16.7392 0 011.0527-1.6402v-.0508l-.043-.0495a16.99 16.99 0 01-1.1894-1.5411zm1.855 2.0714l-.121.172a15.3633 15.3633 0 00-.9172 1.433l-.043.0716.0716.043a16.6102 16.6102 0 001.562.766l.1929.086-.086-.1928a8.04 8.04 0 01-.6592-2.1717zm-3.976.4794v.2006a11.759 11.759 0 00.9459 3.326l.0781.1863.0717-.1942a16.216 16.216 0 01.8455-1.9997l.0573-.0638-.0638-.043a17.1978 17.1978 0 01-1.777-1.2832zm2.543 1.8056l-.0351.0795a15.7646 15.7646 0 00-.9823 2.4791v.0795h.086a16.1516 16.1516 0 002.6876.5016l.0716.0065v-.086a17.5632 17.5632 0 01.1642-2.0558v-.0651h-.0639a16.2662 16.2662 0 01-1.8486-.8963zm2.5443 1.1686v.1146a17.255 17.255 0 00-.151 1.8278v.0782h.9314c.2866 0 .6233.0143.9458 0h.2084l-.1654-.129a8.0113 8.0113 0 01-1.6402-1.8343zm-3.2894 2.1l.1146.172a11.9883 11.9883 0 002.5013 2.737l.1576.129v-.2006a22.5792 22.5792 0 01-.2006-2.3358v-.0717h-.0716a16.2304 16.2304 0 01-2.3007-.3869z
```

- Commands in path:
  - q: NO
  - Q: NO
  - t: NO
  - T: NO
  - c: YES
  - C: NO
- `svg-path-bounding-box`:
  - minX: 0
  - maxX: 24.000818214566845
  - minY: 0.0332
  - maxY: 23.96680638699361
  - centerX: 12
  - centerY: 12
- `svg-path-bbox`:
  - minX: 0
  - maxX: 24.000818214566845
  - minY: 0.0332
  - maxY: 23.96680638699361
  - centerX: 12
  - centerY: 12

+ `svgpathtools`

```
Traceback (most recent call last):
  File "svgpathtools-bbox.py", line 6, in <module>
    path = parse_path(sys.argv[1])
  File "/usr/local/lib/python3.8/dist-packages/svgpathtools/parser.py", line 15, in parse_path
    return Path(pathdef, current_pos=current_pos, tree_element=tree_element)
  File "/usr/local/lib/python3.8/dist-packages/svgpathtools/path.py", line 2274, in __init__
    self._parse_path(segments[0], current_pos)
  File "/usr/local/lib/python3.8/dist-packages/svgpathtools/path.py", line 3075, in _parse_path
    sweep = float(elements.pop())
ValueError: could not convert string to float: 'l'
```

+ `github.com/kpym/SVGPathy`
  + minX: 0
  + maxX: 24.0008182
  + minY: 0.0332
  + maxY: 23.9668064
  + centerX: 12
  + centerY: 12

</details>

The 24.001 is because the rounding to 3 decimals. This differs with `icon-centered` linter, that it's giving 0.001 of tolerance... :thinking:

You are using Inkscape right?

**Comment by service-paradis** [comment]
Decided to give it a try using Inkscape. Dont know why, but it works for me 😄 
```svg
<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Anaconda icon</title><path d="M12.045.033a12.181 12.182 0 00-1.361.078 17.512 17.513 0 011.813 1.433l.48.438-.465.45a15.047 15.048 0 00-1.126 1.205l-.178.215a8.527 8.527 0 01.86-.05 8.154 8.155 0 11-4.286 15.149 15.764 15.765 0 01-1.841.106h-.86a21.847 21.848 0 00.264 2.866 11.966 11.967 0 106.7-21.89zM8.17.678a12.181 12.182 0 00-2.624 1.275 15.506 15.507 0 011.813.43A18.551 18.552 0 018.17.678zM9.423.75a16.237 16.238 0 00-.995 1.998 16.15 16.152 0 011.605.66 6.98 6.98 0 01.43-.509c.234-.286.472-.559.716-.817A15.047 15.048 0 009.423.75zM4.68 2.949a14.969 14.97 0 000 2.336c.587-.065 1.196-.1 1.812-.107a16.617 16.617 0 01.48-1.748 16.48 16.481 0 00-2.292-.481zM3.62 3.5A11.938 11.938 0 001.762 5.88a17.004 17.004 0 011.877-.444A17.39 17.391 0 013.62 3.5zm4.406.287c-.143.437-.265.888-.38 1.347a8.255 8.255 0 011.67-.803c-.423-.2-.845-.38-1.29-.544zM6.3 6.216a14.051 14.052 0 00-1.555.108c.064.523.157 1.038.272 1.554a8.39 8.391 0 011.283-1.662zm-2.55.137a15.313 15.313 0 00-2.602.716h-.078v.079a17.104 17.105 0 001.267 2.544l.043.071.072-.049a16.309 16.31 0 011.734-1.083l.057-.035V8.54a16.867 16.868 0 01-.408-2.094v-.092zM.644 8.095l-.063.2A11.844 11.845 0 000 11.655v.209l.143-.152a17.706 17.707 0 011.584-1.447l.057-.043-.043-.064a16.18 16.18 0 01-1.025-1.87zm3.77 1.253l-.18.1c-.465.273-.93.573-1.375.889l-.065.05.05.064c.309.437.645.867.996 1.276l.137.165v-.208a8.176 8.176 0 01.364-2.15zM2.2 10.853l-.072.05a16.574 16.574 0 00-1.813 1.734l-.058.058.066.057a15.449 15.45 0 001.991 1.483l.072.05.043-.08a16.738 16.74 0 011.053-1.64v-.05l-.043-.05a16.99 16.99 0 01-1.19-1.54zm1.855 2.071l-.121.172a15.363 15.363 0 00-.917 1.433l-.043.072.071.043a16.61 16.61 0 001.562.766l.193.086-.086-.193a8.04 8.04 0 01-.66-2.172zm-3.976.48v.2a11.758 11.759 0 00.946 3.326l.078.186.072-.194a16.215 16.216 0 01.845-2l.057-.063-.064-.043a17.197 17.198 0 01-1.776-1.284zm2.543 1.805l-.035.08a15.764 15.765 0 00-.983 2.479v.08h.086a16.15 16.152 0 002.688.5l.072.007v-.086a17.562 17.563 0 01.164-2.056v-.065H4.55a16.266 16.266 0 01-1.849-.896zm2.544 1.169v.114a17.254 17.255 0 00-.151 1.828v.078h.931c.287 0 .624.014.946 0h.209l-.166-.129a8.011 8.011 0 01-1.64-1.834zm-3.29 2.1l.115.172a11.988 11.988 0 002.502 2.737l.157.129v-.201a22.578 22.58 0 01-.2-2.336v-.071h-.072a16.23 16.23 0 01-2.3-.387z"/></svg>
```

**Comment by mondeja** [comment]
With @service-paradis path Inkscape measures (at least for me) 23.999px of width and Javascript implementations `24.000211229581375`.

**Comment by fbernhart** [comment]
Yeah, I'm using Inkscape (version 1.0.1).

@service-paradis How did you do it? 😄  Did you resize it with Inkscape manually to a width of 23.999 instead of 24.000? Or are you using a different version of Inkscape?

And why is there a difference at all between Inkscape and our linter? 🤔

**Comment by service-paradis** [comment]
> Yeah, I'm using Inkscape (version 1.0.1).
> 
> @service-paradis How did you do it? 😄 Did you resize it with Inkscape manually to a width of 23.999 instead of 24.000? Or are you using a different version of Inkscape?
> 
> And why is there a difference at all between Inkscape and our linter? 🤔

Inkscape 1.0.1 too
Resized to 24. But as @mondeja said, after the optimization, I'm now seeing it as 23,999...

**Comment by fbernhart** [comment]
I'm seeing your path as well as 23.999 in Inkscape. So I guess our Inkscape versions are working the same way.

Using the Inkscape path I provided above:

```
M 12.045274,0.03322204 A 12.181753,12.181753 0 0 0 10.683894,0.11138735 17.513061,17.513061 0 0 1 12.49733,1.5444181 L 12.976744,1.9821439 12.51166,2.4328972 A 15.048047,15.048047 0 0 0 11.386079,3.6366429 L 11.207602,3.8515976 A 8.5272269,8.5272269 0 0 1 12.067421,3.8020929 8.1546086,8.1546086 0 1 1 7.7813565,18.950531 15.764621,15.764621 0 0 1 5.9405628,19.057356 H 5.0807444 A 21.848332,21.848332 0 0 0 5.3452037,21.923418 11.966781,11.966781 0 1 0 12.045274,0.03322204 Z M 8.1695768,0.67808589 A 12.181753,12.181753 0 0 0 5.545828,1.9534833 15.506655,15.506655 0 0 1 7.3592631,2.3833925 18.552093,18.552093 0 0 1 8.1695768,0.67808589 Z m 1.2532508,0.0716515 A 16.23756,16.23756 0 0 0 8.4275226,2.748164 16.151571,16.151571 0 0 1 10.032517,3.4073581 6.9794276,6.9794276 0 0 1 10.462426,2.8992835 C 10.696507,2.6126541 10.935307,2.3404225 11.178942,2.082456 A 15.048047,15.048047 0 0 0 9.4228276,0.74973739 Z M 4.6794958,2.9487882 a 14.969224,14.969224 0 0 0 0,2.3358402 c 0.5875904,-0.064492 1.1958791,-0.09966 1.8121325,-0.106826 A 16.617344,16.617344 0 0 1 6.972345,3.4295049 16.481195,16.481195 0 0 0 4.6794958,2.9487882 Z M 3.619053,3.5011564 A 11.938118,11.938118 0 0 0 1.7626268,5.8799875 17.004294,17.004294 0 0 1 3.639897,5.4357479 17.391243,17.391243 0 0 1 3.619053,3.5011564 Z M 8.0262735,3.7877626 C 7.8829595,4.2248725 7.7605214,4.6762043 7.6458696,5.1348115 A 8.2549289,8.2549289 0 0 1 9.3160016,4.3323142 C 8.8932231,4.1316737 8.4705499,3.9525745 8.0262735,3.7877626 Z M 6.2988205,6.2160983 A 14.05201,14.05201 0 0 0 4.7433307,6.324227 c 0.064492,0.523099 0.1576241,1.0382541 0.2722759,1.5541872 A 8.3910779,8.3910779 0 0 1 6.2988205,6.2160983 Z M 3.7480258,6.3528877 A 15.31318,15.31318 0 0 0 1.1464236,7.0694032 h -0.078165 v 0.078165 a 17.104613,17.104613 0 0 0 1.2675808,2.5442811 l 0.042991,0.07165 0.071652,-0.049508 A 16.309217,16.309217 0 0 1 4.1844488,8.631402 L 4.2417698,8.596233 V 8.5389066 A 16.868145,16.868145 0 0 1 3.8340076,6.4453833 V 6.3528877 Z M 0.64486285,8.0946711 0.58102784,8.2952952 A 11.844963,11.844963 0 0 0 -9.9468728e-7,11.655101 v 0.208442 L 0.14330208,11.712422 a 17.706536,17.706536 0 0 1 1.58415032,-1.44736 l 0.057321,-0.04299 -0.042991,-0.06383 A 16.180233,16.180233 0 0 1 0.71651441,8.2874796 Z M 4.4137337,9.3479219 4.2352563,9.4482343 C 3.7694834,9.7205316 3.3038224,10.02142 2.8595467,10.336713 l -0.065137,0.0508 0.050807,0.06383 c 0.3081267,0.43711 0.6441839,0.86695 0.995305,1.275398 L 3.977311,11.892198 V 11.683757 A 8.1761058,8.1761058 0 0 1 4.3420824,9.534211 Z m -2.2133812,1.5046821 -0.071652,0.05081 a 16.574349,16.574349 0 0 0 -1.81343487,1.733963 l -0.0573212,0.05732 0.0651378,0.05733 a 15.449329,15.449329 0 0 0 1.99191267,1.48253 l 0.071652,0.05081 0.042991,-0.07947 a 16.739161,16.739161 0 0 1 1.0526262,-1.640169 v -0.05081 l -0.042991,-0.04951 A 16.989961,16.989961 0 0 1 2.2498573,10.924255 Z m 1.8551235,2.071381 -0.1211562,0.171963 a 15.36334,15.36334 0 0 0 -0.9171397,1.433031 l -0.042991,0.07165 0.071652,0.04299 a 16.610178,16.610178 0 0 0 1.5620035,0.766021 l 0.1928078,0.08598 -0.085982,-0.192808 A 8.0399568,8.0399568 0 0 1 4.055476,13.131121 Z m -3.97600892,0.479414 v 0.200624 a 11.758974,11.758974 0 0 0 0.94580032,3.325934 l 0.078165,0.186294 0.071652,-0.19411 a 16.216063,16.216063 0 0 1 0.8454881,-1.999729 l 0.057321,-0.06383 -0.063835,-0.04299 a 17.197769,17.197769 0 0 1 -1.77695764,-1.28322 z m 2.54297812,1.805619 -0.035174,0.07947 a 15.764621,15.764621 0 0 0 -0.9822774,2.479144 v 0.07947 h 0.085982 a 16.151571,16.151571 0 0 0 2.687584,0.501561 l 0.071652,0.0065 v -0.08601 A 17.563221,17.563221 0 0 1 4.614359,16.213405 v -0.06514 H 4.5505228 A 16.266223,16.266223 0 0 1 2.7019131,15.252006 Z m 2.5442811,1.168571 v 0.114643 a 17.255094,17.255094 0 0 0 -0.1511197,1.827765 v 0.07816 h 0.93147 c 0.2866295,0 0.6233421,0.01433 0.9458,0 H 7.1013175 L 6.9358682,18.26919 A 8.0112938,8.0112938 0 0 1 5.295699,16.43491 Z m -3.289457,2.100041 0.1146424,0.171964 a 11.988278,11.988278 0 0 0 2.50129,2.737088 l 0.1576334,0.128973 v -0.200624 a 22.579237,22.579237 0 0 1 -0.2006243,-2.33584 v -0.07165 h -0.071651 a 16.230394,16.230394 0 0 1 -2.3006657,-0.38692 z
```

If I optimize it to a precision of 3, using [SVGOMG](https://jakearchibald.github.io/svgomg/), I'm getting this path:
```
M12.045.033a12.182 12.182 0 00-1.361.078 17.513 17.513 0 011.813 1.433l.48.438-.465.45a15.048 15.048 0 00-1.126 1.205l-.178.215a8.527 8.527 0 01.86-.05A8.155 8.155 0 117.78 18.951a15.765 15.765 0 01-1.84.106h-.86a21.848 21.848 0 00.264 2.866 11.967 11.967 0 106.7-21.89zM8.17.678a12.182 12.182 0 00-2.624 1.275 15.507 15.507 0 011.813.43A18.552 18.552 0 018.17.678zM9.423.75a16.238 16.238 0 00-.995 1.998 16.152 16.152 0 011.605.66 6.98 6.98 0 01.43-.509c.234-.286.472-.559.716-.817A15.048 15.048 0 009.423.75zM4.679 2.949a14.97 14.97 0 000 2.336c.588-.065 1.196-.1 1.813-.107a16.617 16.617 0 01.48-1.748 16.481 16.481 0 00-2.293-.481zM3.62 3.5A11.938 11.938 0 001.763 5.88a17.004 17.004 0 011.877-.444A17.391 17.391 0 013.62 3.5zm4.407.287c-.143.437-.265.888-.38 1.347a8.255 8.255 0 011.67-.803 15.8 15.8 0 00-1.29-.544zM6.3 6.216a14.052 14.052 0 00-1.556.108c.065.523.158 1.038.273 1.554a8.391 8.391 0 011.283-1.662zm-2.551.137a15.313 15.313 0 00-2.602.716h-.078v.079a17.105 17.105 0 001.268 2.544l.043.071.071-.049a16.31 16.31 0 011.734-1.083l.058-.035V8.54a16.868 16.868 0 01-.408-2.094v-.092zM.645 8.095l-.064.2A11.845 11.845 0 000 11.655v.209l.143-.152a17.707 17.707 0 011.584-1.447l.058-.043-.043-.064a16.18 16.18 0 01-1.025-1.87zm3.769 1.253l-.179.1a18.72 18.72 0 00-1.375.889l-.066.05.051.064c.308.437.644.867.996 1.276l.136.165v-.208a8.176 8.176 0 01.365-2.15zM2.2 10.853l-.071.05a16.574 16.574 0 00-1.814 1.734l-.057.058.065.057a15.45 15.45 0 001.992 1.483l.072.05.043-.08a16.74 16.74 0 011.052-1.64v-.05l-.043-.05a16.99 16.99 0 01-1.19-1.54zm1.855 2.071l-.12.172a15.363 15.363 0 00-.918 1.433l-.043.072.072.043a16.61 16.61 0 001.562.766l.193.086-.086-.193a8.04 8.04 0 01-.66-2.172zm-3.976.48v.2a11.759 11.759 0 00.946 3.326l.078.186.072-.194a16.216 16.216 0 01.846-2l.057-.063-.064-.043a17.198 17.198 0 01-1.777-1.284zm2.543 1.805l-.035.08a15.765 15.765 0 00-.982 2.479v.08h.086a16.152 16.152 0 002.688.5l.071.007v-.086a17.563 17.563 0 01.164-2.056v-.065h-.063a16.266 16.266 0 01-1.85-.896zm2.545 1.169v.114a17.255 17.255 0 00-.151 1.828v.078h.931c.287 0 .623.014.946 0H7.1l-.165-.129a8.011 8.011 0 01-1.64-1.834zm-3.29 2.1l.115.172a11.988 11.988 0 002.501 2.737l.158.129v-.201a22.58 22.58 0 01-.2-2.336v-.071h-.072a16.23 16.23 0 01-2.301-.387z
```

Which is still showing as 24.000 in Inkscape and which is the same as in my commit https://github.com/simple-icons/simple-icons/pull/3965/commits/16f7200c4b7959dbb8db20cea31ae4a9d354392a. And this one failed the linter.


Do you use SVGOMG (as I do) or the SVGO command line tool to optimize it?

**Review by mondeja — APPROVED** [review]
Thanks for the help @service-paradis :+1: Looks good now so I'm merging it. Maybe some day we could find the algorithm of size computation of Inkscape...

**Comment by service-paradis** [comment]
> Thanks for the help @service-paradis 👍
> Looks good now so I'm merging it. Maybe some day we could find the algorithm of size computation used by Inkscape...

NP!
Might be difficult to adapt, but we could get some inspiration from https://gitlab.com/inkscape/inkscape 😅

**Comment by mondeja** [comment]
> Might be difficult to adapt, but we could get some inspiration from https://gitlab.com/inkscape/inkscape 😅 

Do you know where is the part of the code that computes sizes? I've searched it many times, but it's difficult to find.

**Comment by service-paradis** [comment]
> Do you know where is the part of the code that computes sizes? I've searched it many times, but it's difficult to find.

It is quite a use repo! I think something is going on on those file, but I did not check for too long:
- https://gitlab.com/inkscape/inkscape/-/blob/master/src/object/object-set.cpp
- https://gitlab.com/inkscape/inkscape/-/blob/master/src/helper/geom.cpp

**Pull request merged**
