### PR TITLE
Add Hedera icon

### LINKED ISSUE #6112: Hedera Hashgraph Icon
**Brand Name: Hedera Hashgraph **
**Website: https://hedera.com/**
**Alexa rank: 41,265**

**Official resources for icon and color: 
hedera
**

### PR DESCRIPTION
**Pull request by adsingh14**
hedera

**Issue:** closes #6112

**Similarweb rank:** 179,123
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by sisp — CHANGES_REQUESTED** [review]
Thanks for your contribution, @adsingh14! :pray:

I see some notable differences between the original icon (`black-cutout.svg` in the ["STANDARD" .zip file](https://hederabrandcentral.frontify.com/api/attachment/download/hoJFXTIUSjZr6qBObBdXQQZrtXztfxybZyEesVnz6fNCTCg1RgRO7dTUsBiZ1g5aWuUG9naD0RokRrwByaHRw-drAGp43v1A-f_IL_ukrX4)) and yours:


Could you please give it another try? It might help to perform the conversion with the highest possible precision your SVG editor supports and let SVGO/SVGOMG perform the precision reduction afterwards.

**Comment by adsingh14** [comment]
@sisp Can you please check the attached image?
On the right side, I overlapped my version over the original icon and on the other side, I overlapped the original-on-original icon.
test-1

**Comment by sisp** [comment]
I don't know how you created the diffs, but mine show some non-negligible differences. I used Boxy SVG, imported the original icon, converted it with maximum precision, imported yours, and computed the diff using the `Exclude` operation.

**Comment by LitoMore** [comment]
https://user-images.githubusercontent.com/8186898/194116185-967de9dd-2be9-4c49-8542-5a60bcddec29.mp4

I think the small difference can be accepted. I tried to scale it a lot. But the difference is still very thin.

**Comment by sisp** [comment]
@LitoMore I think the difference is more visible at the edge of the circle. :thinking: Curves and arcs are sometimes difficult to convert accurately with reduced precision. I'm not opposed to accepting the current icon if you think it's sufficiently accurate.

**Comment by LitoMore** [comment]
https://user-images.githubusercontent.com/8186898/194120956-23758384-f138-4490-8f98-fbb50838cf8b.mp4

@sisp Ah, you are right. Let me try to process one and see what happened.

**Comment by adsingh14** [comment]
Don't worry, I'm pushing the same again.

**Comment by LitoMore** [comment]
@sisp I tried with precision 5 but still have problems. I think we can consider it good enough.

**Comment by adsingh14** [comment]
> @sisp I tried with precision 5 but still have problems. I think we can consider it good enough.

Should I halt my local commit?

**Review by LitoMore — APPROVED** [review]

**Review by sisp — APPROVED** [review]
@LitoMore @adsingh14  Alright then, let's keep it as it is now.

**Pull request merged**
