### PR TITLE
Updated Google Ads

### PR DESCRIPTION
**Pull request by adamrusted**
googleads

**Issue:** Contributes to #4205
**Alexa rank:** N/A

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Source updated as per [comment](https://github.com/simple-icons/simple-icons/issues/4205#issuecomment-748528744).
Rebuilt from source, with 0.35px line between colour changes.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
The SVG looks perfect to me, @adamrusted. However, it should be noted that the monochrome treatment mentioned [here](https://github.com/simple-icons/simple-icons/pull/1848#issuecomment-547581526) is still in use on Google My Business so I think we should stick with that. What do the other @simple-icons/maintainers think?

**Comment by PeterShaggyNoble** [comment]
Conversely, adding the cut-out makes it consistent with other Google icons such as AdSense & Optimize. Also, per [this comment](https://github.com/simple-icons/simple-icons/pull/4472#issuecomment-756866656), should the cut-out here also be 0.5dp?

**Comment by adamrusted** [comment]
Yep - I think a lot of these Google ones were prior to the 0.5px discussion. I'll have a look over these today.

**Comment by adamrusted** [comment]
@PeterShaggyNoble should be sorted.

**Comment by PeterShaggyNoble** [comment]
Before reviewing, do any of the other @simple-icons/maintainers have any opinions on whether or not we should stick with our current treatment (per [this comment](https://github.com/simple-icons/simple-icons/pull/4471#issuecomment-762232535)) or add the cut-out to make it consistent with other, similar Google icons (per [this comment](https://github.com/simple-icons/simple-icons/pull/4471#issuecomment-762272566))?

**Comment by service-paradis** [comment]
That is a good question!
I agree with consistencies when there are no other options (but it becomes a little bit opinionated). I think I would use official logos without any transformation when it is available.

**Comment by ericcornelissen** [comment]
Though I agree that an official is preferred, I'm not sure if an icon from a different Google service that is arguably very much different from the actual logo can be considered official. I don't recall any specific incidents, but I definitely remember Google forgetting to update logos of product A in product B :thinking:

**Comment by PeterShaggyNoble** [comment]
Well, this is odd, the SVG is passing the linter but, when I pull it into Inkspace, it's showing as `23.999` wide 🤔 I wonder if it's related to some of the points [breaking the bounds of the canvas](https://user-images.githubusercontent.com/15157491/107880603-cc53cc80-6ed7-11eb-8a19-78180b72900e.png) and causing some imperfections in the shapes. There's also an excess point in the bottom right curve.


Here's my own attempt at it:
```
M 3.9997845,22.929104 C 1.7907643,22.929104 -2.0340928e-7,21.138339 2.3841858e-7,18.929319 3.4887553e-7,16.720299 1.7907647,14.929535 3.9997845,14.929535 6.2088042,14.929535 7.9995686,16.720299 7.9995687,18.929319 7.9995691,21.138339 6.2088046,22.929104 3.9997845,22.929104 Z M 23.464129,16.928744 15.463196,3.0720075 C 14.358585,1.1587114 11.912075,0.50276316 9.998779,1.6073746 8.0854829,2.711986 7.4295346,5.1584957 8.5341461,7.0717918 L 16.535078,20.928528 C 17.63969,22.841824 20.0862,23.496409 21.999496,22.393161 23.912792,21.28855 24.567376,18.84204 23.464129,16.928744 Z M 7.5136719,4.84375 1.5644531,15.148438 C 2.2904657,14.680006 3.1359849,14.430486 4,14.429688 6.4852814,14.429688 8.5,16.444407 8.5,18.929688 8.4997576,19.001339 8.4978039,19.072974 8.4941406,19.144531 L 11.710938,13.572266 8.1015625,7.3222656 C 7.6515991,6.5428842 7.4692655,5.6827909 7.5136719,4.84375 Z
```

**Comment by adamrusted** [comment]
Yeah - I'm not able to pass the linter at all with the path above, and seem to remember I had some trouble with this one. Figured if the linter passed we were good to go! 😅
Let me adjust SVGO to 4 points of precision and try again, may just be we can't get it down to 3.

**Comment by adamrusted** [comment]
Got it passing with 4 decimals of precision. Not ideal, but if it gets it through the linter 🤷🏻‍♂️

**Comment by PeterShaggyNoble** [comment]
Sorry, @adamrusted; forgot about this one 🤦🏻‍♂️

Looks good to me now; thanks for your continued work on it 👍🏻

**Pull request merged**
