### PR TITLE
Add Nuke (#2495)

### LINKED ISSUE #2495: Nuke
**Name:** Nuke
**Website:** https://www.foundry.com/products/nuke
**Official resources for icon and color:** @ header

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
Closes #2495

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG was taken from the websites header.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
There's a minor issue in the top left of the inner circle, that's also present in the original. Don't know if you want to fix it but we could probably do with having a broader discussion on whether or not we *should* be fixing imperfections in officially sourced graphics.

image

**Comment by runxel** [comment]
Oh good catch.
Well yeah, let's fix that. At least I always did so. Think of Neovim e.g.
I'm always in favor of fixing. It helps to reduce visual complexity, bandwidth, and processing power.

**Comment by PeterShaggyNoble** [comment]
Looks like something went wrong there, @runxel (yours in red, original in green).

image

**Comment by runxel** [comment]
Baffling!

**Comment by PeterShaggyNoble** [comment]
Looks good to me now, @runxel. Nice work :+1:

**Pull request merged**
