### PR TITLE
Remove Twitter

### PR DESCRIPTION
**Pull request by adamrusted**
Removes the Twitter brand. Already exists as an alias of `X`.

### CODE REVIEW

**Comment by LitoMore** [comment]
Converting to draft since it's still the most famous icon.

**Comment by adamrusted** [comment]
> Converting to draft since it's still the most popular icon.

Will be removed as of May 2024 though, as the brand will have been changed for over 6 months at that point, so users best get updating their apps!

**Comment by XFox111** [comment]
I'd like to ask you to reconsider this, as there're a lot of people who refuse to accept the new branding and would prefer to keep using the old one

**Comment by adamrusted** [comment]
Unfortunately, @XFox111 - we (myself included) may not be a fan of the re-brand, but that is what the company have done.
We need to ensure we keep our brands up to date, and therefore - Twitter will need to be removed. We already postponed the removal from 26/11/23 to 28/04/24 - which will have been _plenty_ of time since the rebrand happened. We wouldn't give _this_ much leway to any other brand.

**Comment by XFox111** [comment]
@adamrusted that's a fair point. Though I thought it would be better to keep it as a legacy logo as an exclusion (maybe rename it to `legacytwitter` or something). Because it kind of became a big part of the IT history and just wiping it off doesn't feel right.

**Comment by teauxfu** [comment]
In case anyone goes looking for it later, here's the SVG itself copied from the diff. 

```
<svg role="img" viewBox="0 0 24 24"><title>Twitter</title><path d="M21.543 7.104c.015.211.015.423.015.636 0 6.507-4.954 14.01-14.01 14.01v-.003A13.94 13.94 0 0 1 0 19.539a9.88 9.88 0 0 0 7.287-2.041 4.93 4.93 0 0 1-4.6-3.42 4.916 4.916 0 0 0 2.223-.084A4.926 4.926 0 0 1 .96 9.167v-.062a4.887 4.887 0 0 0 2.235.616A4.928 4.928 0 0 1 1.67 3.148 13.98 13.98 0 0 0 11.82 8.292a4.929 4.929 0 0 1 8.39-4.49 9.868 9.868 0 0 0 3.128-1.196 4.941 4.941 0 0 1-2.165 2.724A9.828 9.828 0 0 0 24 4.555a10.019 10.019 0 0 1-2.457 2.549z"/></svg>
```

**Pull request merged**
