### PR TITLE
add Snapcraft

### PR DESCRIPTION
**Pull request by casperdcl**
### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- edited svg from https://github.com/snapcore/snap-store-badges
- hex value from logo's primary body colour

### CODE REVIEW

**Comment by casperdcl** [comment]
@igorljubuncic fyi

**Comment by davidklebanoff** [comment]
Hi @casperdcl, this is great work! I created an issue to help track this pull request, if you end up adding more icons in the future, please create an issue as well.

As for this icon, everything looks great to me. My only concern is - is the Snapcore repos an official source? We prefer to use icons from official sources and I don't know if Snapcore is related/part-of Snapcraft. Otherwise, using the logo from say the [Snapcraft homepage](https://snapcraft.io/) may be preferred.

**Comment by casperdcl** [comment]
er, snapcore owns snapcraft: https://github.com/snapcore/snapcraft

**Comment by davidklebanoff** [comment]
Got it, thanks!

**Comment by davidklebanoff** [comment]
Closes #1215.

**Comment by davidklebanoff** [comment]
Closes #1216.

**Pull request merged**
