### PR TITLE
Add Apollo GraphQL

### LINKED ISSUE #2586: Request: Apollo GraphQL
**Name:** Apollo GraphQL
**Website:** https://www.apollographql.com/
**Official resources for icon and color:**
- [Logo SVG](https://github.com/apollographql/space-kit/tree/master/logos)
- [Primary brand color _(base)_](https://space-kit.netlify.com/?path=/story/color--brand-colors): `#3F20BA` (Dark Indigo)
- [Space-kit Design System](https://space-kit.netlify.com/)

### PR DESCRIPTION
**Pull request by YoussefRaafatNasry**
**Issue: closes #2586**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to SImple Icons, @YoussefRaafatNasry and thanks for the PR. It's failing, though, because all icons need to be a single `path`.

I'd also suggest updating the source URL to https://github.com/apollographql/space-kit/blob/9a42083746a49c9a734563f427c13233e42adcc9/logos/mark.svg

And see my comment in #2586 on the colour.

**Comment by PeterShaggyNoble** [comment]
Sorry, @YoussefRaafatNasry, I missed that you had a dash in the SVG file name, which is what's causing the build to fail this time.

**Comment by PeterShaggyNoble** [comment]
Also, your SVG (in red below) doesn't quite line up with the one I linked above. Did you use a different source?

I wasn't saying your choice of colour was necessarily wrong, by the way, just wondering what led you to choose i.

**Comment by YoussefRaafatNasry** [comment]
@PeterShaggyNoble Yes, I've used the mentioned source, maybe something have gone wrong with the resizing/alignment. Anyway, I've done the whole process from scratch again just to make sure.

**Comment by YoussefRaafatNasry** [comment]
@PeterShaggyNoble Concerning the color, for me, I prefer working with official brand primary colors mentioned in the style guide. I think it just makes more sense, tho I have no problem with the color you mentioned.

**Comment by YoussefRaafatNasry** [comment]
Another thing you may consider, is adding the svg files naming conventions to [CONTRIBUTING.md](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#5-check-the-icon), just to make things more clear for upcoming PRs.

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @YoussefRaafatNasry 😀 Unfortunately, there are still a couple of issues with the SVG (see below).

Good point about documenting how files should be named - would have sworn we already had that in `CONTRIBUTING.md`. As you can see above, @ericcornelissen is working on [a tool to generate expected file names](https://github.com/ericcornelissen/simple-icons/commit/a30ca32befb000503ca86acbb7c9721668b30968) but we should still document it for reference. Eric, do you want to add that while you're at it?

image

**Comment by YoussefRaafatNasry** [comment]
Tried to fix it, it's still a tiny bit off due to precision, can do nothing about it.

- Yellow: optimized
- Black: source

image

**Comment by ericcornelissen** [comment]
> Good point about documenting how files should be named - would have sworn we already had that in CONTRIBUTING.md. As you can see above, @ericcornelissen is working on a tool to generate expected file names but we should still document it for reference. Eric, do you want to add that while you're at it?

I intended to do both and I will open a PR for that (which should be there soon). However, describing the filename is a bit difficult as it is based on [this transformation](https://github.com/simple-icons/simple-icons/blob/36abec3c39887814155c59ff9c7f7d04ba41b044/scripts/utils.js#L6) :sweat_smile:

**Comment by PeterShaggyNoble** [comment]
Thanks for your continued efforts and patience with this one, @YoussefRaafatNasry.

I took a stab at it myself and ended up with the following path, which lines up a bit better with the original:

```
M12,0C5.372,0 0,5.373 0,12 0,18.628 5.372,24 12,24 18.627,24 24,18.628 24,12A12.014,12.014 0 0 0 23.527,8.657 0.6,0.6 0 0 0 22.4,9.066H22.398C22.663,10.009 22.8,10.994 22.8,12A10.73,10.73 0 0 1 19.637,19.637 10.729,10.729 0 0 1 12,22.8 10.73,10.73 0 0 1 4.363,19.637 10.728,10.728 0 0 1 1.2,12 10.73,10.73 0 0 1 4.363,4.363 10.728,10.728 0 0 1 12,1.2C14.576,1.2 17.013,2.096 18.958,3.74A1.466,1.466 0 1 0 19.82,2.9 11.953,11.953 0 0 0 12,0ZM10.56,5.88 6.36,16.782H8.99L9.677,14.934H13.646L12.927,12.892H10.314L12.014,8.201 15.038,16.781H17.669L13.47,5.88Z
```

**Comment by ericcornelissen** [comment]
Looking good 👍 Thanks a lot for the contribution @YoussefRaafatNasry and thanks for the help @PeterShaggyNoble!

**Pull request merged**
