### PR TITLE
Add Wikimedia Foundation

### LINKED ISSUE #9684: Wikimedia Foundation
### Brand Name

Wikimedia Foundation

### Website

https://wikimediafoundation.org

### Popularity Metric

https://www.similarweb.com/website/wikimediafoundation.org/ - `#73,216`

### Official Resources for Icon and Color

- SVG: https://commons.wikimedia.org/wiki/File:Wikimedia-logo_black.svg
- Color: `#000000`
- Visual guideline: https://foundation.wikimedia.org/wiki/Legal:Visual_identity_guidelines
- TM Policy: https://foundation.wikimedia.org/wiki/Policy:Trademark_policy

Bonus: _Wikimedia Community_ logo also are available free to use.
- SVG: https://commons.wikimedia.org/wiki/File:Wikimedia_Community_Logo.svg
- Other infos are the same with this logo.

### Additional Comments

In the SVG link for WMF logo, it mention that the version used for this request are released in **PD** (Public domain), but the styled wordmark are CC-BY-SA 3.0 instead.

### PR DESCRIPTION
**Pull request by songnguxyz**
image

**Issue:** closes #9684

**Similarweb rank:** see issue

### Checklist

- [X] I updated the JSON data in `_data/simple-icons.json`
- [X] I optimized the icon with SVGO or SVGOMG
- [X] The SVG `viewbox` is `0 0 24 24`

### Description

Everything has already been mentioned in the issue, thanks Peter for helps.

### CODE REVIEW

**Comment by pisceskaze** [comment]
hold up-
I have just noticed that the icon was not on their "diet" isn't it-

**Comment by pisceskaze** [comment]
Sneak peak on what is coming:

wikimediafoundation(1)

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
Thanks for the contribution, @pisceskaze 👍🏻 However, I'm seeing [some differences](https://github.com/simple-icons/simple-icons/assets/15157491/d206e501-ac9e-4b68-bdfb-1f10c5ff4a85) in the outer circle between your version (in red) and the source (in black). This could either be as a result of converting the `stroke` to a `path`, or gettinng the intersection with the `clip-path`. When I tried it myself, both created differences for me, too - although, different differences to yours.

**Comment by pisceskaze** [comment]
> Thanks for the contribution, @pisceskaze 👍🏻 However, I'm seeing [some differences](https://github.com/simple-icons/simple-icons/assets/15157491/d206e501-ac9e-4b68-bdfb-1f10c5ff4a85) in the outer circle between your version (in red) and the source (in black). This could either be as a result of converting the `stroke` to a `path`, or gettinng the intersection with the `clip-path`. When I tried it myself, both created differences for me, too - although, different differences to yours.

Seems like it to me, it's hard to be noticed without a direct check.

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @songnguxyz?

**Review by PeterShaggyNoble — APPROVED** [review]

**Pull request merged**
