### PR TITLE
Add egghead

### LINKED ISSUE #3789: Request: Egghead Icon
**Name:** Egghead
**Website:** https://egghead.io/
**Alexa rank:** 34,089
**Official resources for icon and color:** https://egghead.io/

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
egghead

**Issue:** Closes #3789
**Alexa rank:** [~39.5k](https://www.alexa.com/siteinfo/egghead.io)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon from SVG in website header. I went for white as the colour in the end because, well, it's an egg! But other possible options from the website's stylesheet are `#232c3b` and `#141618`.

### CODE REVIEW

**Comment by fbernhart** [comment]
Just to add some more shades of white: 😁

The wordmark "egghead.io" in their website header has `#FFFFFB` as color. And the egg in the logo itself has `#FCFBFA` as color.

I would prefer `#FCFBFA` to represent the egg. 🥚

**Comment by PeterShaggyNoble** [comment]
I grabbed the pure white colour from the bottom "border" `path` in the SVG; never thought to check anything else 🤦🏻‍♂️ I'm happy to go with the consensus of the @simple-icons/maintainers, though 🙂

Shutting down my machine for the evening so, if a decision is reached, feel free to commit directly to my branch in the interests of getting this merged quicker.

**Comment by adamrusted** [comment]
I would probably agree with @fbernhart on `#FCFBFA` extracted from the egg. @PeterShaggyNoble I'm happy to commit the change if you'd like?

**Comment by PeterShaggyNoble** [comment]
As that's the colour used for the "body" of the egg, @adamrusted; it is probably the best option. Updated.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @PeterShaggyNoble! 🥚

**Pull request merged**
