### PR TITLE
Removed STACKIT

### PR DESCRIPTION
**Pull request by adamrusted**
Removes STACKIT, accidentally merged by myself in #5829 without looking at Alexa rank.
Note to self, don't review PRs after a stressful day at work 🙃

@dirien - I'd completely missed the Alexa rank, which as pointed out by @fbernhart puts this out of scope for the time being. Please feel free to re-open an issue when the rank improves to match our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon).

### CODE REVIEW

**Comment by fbernhart** [comment]
@adamrusted  thanks for fixing it. :)

**Comment by dirien** [comment]
oh.. thats a bummer. We recently started this brand, an part of increasing the popularity was to work with badges... 

So thats a hen and egg problem :)

is there a way to discuss this maybe in more detail? For the Schwarz IT  (Lidl, Kaufland) it would mean lot to get the this into the library. Parallel we are silver members in the CNCF and our hosted k8s is also certified by the CNCF. So the badges would really help, especiall in Github.

**Comment by dirien** [comment]
Are ther any points i could deliver to you folks? 

As mentioned, badges are the way we want to spread the brand with the Developer Community.

**Comment by dirien** [comment]
In your guidelines you mention
image
 that we can discuss on a case-by-case basis. 
 
 So i am open for this.
 
 Btw here the link to the CNCF landscape -> https://landscape.cncf.io/card-mode?organization=stackit-schwarz-it-kg,

**Comment by adamrusted** [comment]
The way I've always read that in the guidelines, is it's only judged on a case-by-case basis when the Alexa Rank or GitHub stars cannot be used. For example, we've discussed the possibility of using a different metric for Fandom pages, as they all use the same TLD. With `stackit.de` being a TLD, that is the main metric we would use for its inclusion.

I'm happy for other @simple-icons/maintainers to chip in, and if they think we should include it then I have your SVG saved so we can re-merge it back in 🙏

**Comment by dirien** [comment]
wow @adamrusted, that would be great. 👍🏻  Thanks for helping to find a solution. 

I know i ask much atm, but from a developer advocat point of view, using shield.io for badges would tremedous help us to build a brand reputation.  

People know our flagships Lidl and Kaufland, but that we are going to be a German cloud provider is still very unknown.  So we try to do everything possible to build the community:

- meetups: https://www.meetup.com/de-DE/SIT-Meetups-Die-IT-Meetups-der-Schwarzgruppe/
- youtube: https://www.youtube.com/channel/UCrlj8jX00GYQYJO5Wnal6Bw
- CNCF: https://landscape.cncf.io/card-mode?organization=stackit-schwarz-it-kg

And hopefully simple-icons too :)

Looking forward for the community voice...

**Comment by service-paradis** [comment]
Thank you for the information @dirien! Unfortunately, I'm in favor of removing it for now. As stated on the repository and on the website, Simple Icons provides "Free SVG icons for _**popular** brands_". So we have some requirements before adding a brand.  

We'll be happy to add your icon once once it is popular enough! So feel free to open a new Issue or a new PR once the requirements are met or  when you have popularity metrics that can be used to evaluate the inclusion.

**Comment by ericcornelissen** [comment]
@dirien I get that you want the icon in the collection here so it's easy to include in shields, but simple-icons is not an icon provider for shields. While we are aware we are their primary provider for brand icons of shields, that does not mean we will add any icon so it can appear on a shield. From our perspective, even though you did a lot of work providing us with the SVG, every icon adds maintenance, considerations, and package size, which are some of the reasons we don't just add every icon being contributed.

That said, did you know that you can include any SVG you like a shields.io badge using `?logo=data:image/svg;base64,…`? For example: example using the URL:

```
https://img.shields.io/badge/stack-it-blue.svg?logo=data:image/svg%2bxml;base64,PHN2ZyBmaWxsPSJ3aGl0ZSIgcm9sZT0iaW1nIiB2aWV3Qm94PSIwIDAgMjQgMjQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHRpdGxlPlNUQUNLSVQ8L3RpdGxlPjxwYXRoIGQ9Ik02LjE2NiAzLjE2OCA0LjAxNSAxMy4yNDFoNS4zNzdsMS4xNTctNS40MTloMTIuNDU4TDI0IDMuMTY4em04LjQ5MSA3LjU2LTEuMTY1IDUuNDVILjk5M0wwIDIwLjgzMmgxNy44NzZsMi4xNTgtMTAuMTA0eiIvPjwvc3ZnPg==
```

So, if you have the ability to give a URL for the badge to your users, you can use that until StackIt is popular enough for inclusion here.

**Comment by dirien** [comment]
Hi @service-paradis and @ericcornelissen,

thanks both of you for valuable feedback! While unhappy (😭 ), I fully understand your point of view and the requirements fpr simple-icons (btw awsome project 👍🏻 )

I will take this to an internal discussion and I guess we need to continue to build up our popularity!

Thanks again !

**Pull request merged**
