### PR TITLE
Added Revue

### LINKED ISSUE #4389: Revue (getrevue.co)
**Name:** Revue
**Website:** https://www.getrevue.co/
**Alexa rank:** #36,988

**Official resources for icon and color:**
  https://avatars2.githubusercontent.com/u/10776509

### PR DESCRIPTION
**Pull request by adamrusted**
revue

Fixes #4389
**Alexa rank:** [36,988](https://www.alexa.com/siteinfo/getrevue.co)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo pulled from [SVG](https://d3jbm9h03wxzi9.cloudfront.net/assets/logo-54de083d6a27559767ca9354c50c44f47b1d52cb0b5d2fbdbd203a9fbf689764.svg) in header.
Adjusted to Simple Icons format in Adobe Illustrator.
Ran through SVGO CLI and SVGLint.

### CODE REVIEW

**Comment by fbernhart** [comment]
@adamrusted Seems like you've somehow resized it. 🤔 

image


Could you give it another try?

**Comment by adamrusted** [comment]
Rebuilt in `Inkscape` - though needed a precision of 4 again - odd.

**Comment by fbernhart** [comment]
@adamrusted Resizing it to 23.999 before optimising it with a precision of 3 did the trick for me. 😉  Feel free to review my path & merge it.

**Comment by adamrusted** [comment]
LGTM! Thanks @fbernhart 🎉

**Pull request merged**
