### PR TITLE
Add Material-UI

### LINKED ISSUE #2187: Material-UI
**Name:** Material-UI
**Website:** https://material-ui.com/
**Alexa Rank:** [~12k](https://www.alexa.com/siteinfo/material-ui.com)
**Colour:** Either `#00b0ff`,  `#0081cb` or `#1976d2`
**Official resources for icon and color:** Icon & first two colour choices from [logo on homepage](https://material-ui.com/static/images/material-ui-logo.svg), third colour choice from website stylesheet.

[Material-UI](https://github.com/simple-icons/simple-icons/files/3988094/material-ui.zip)

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Material-UI

**Issue:** Closes #2187

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Colour from website stylesheet.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble the .svg is great 👍 

I think the colour should be one chosen from the logo, either `#00b0ff` or `#0081cb`.

My preference is `#0081cb` but will ask @simple-icons/maintainers to give a view.

**Comment by runxel** [comment]
> My preference is `#0081cb` 

Mine too :)

**Comment by PeterShaggyNoble** [comment]
Thanks, guys. Colour updated.

**Comment by runxel** [comment]
Looks good, I will merge this in :)
Thanks for your work on this one!

**Pull request merged**
