### PR TITLE
Add: Farcaster

### LINKED ISSUE #10402: Request: Farcaster
### Brand Name

Farcaster

### Website

https://www.farcaster.xyz/

### Popularity Metric

Farcaster is a protocol for building sufficiently decentralized social networks. Warpcast, a Farcaster client, just had its 10th straight DAU day with 50k+ users (https://warpcast.com/dwr.eth/0x05ba005d). tldr; crypto twitter

### Official Resources for Icon and Color

farcaster-logo

svg: https://github.com/rgboop/farcaster-assets/blob/main/farcaster-logo.svg
color: #855DCD

### PR DESCRIPTION
**Pull request by tytwitchell**
**Issue:** closes #10402

**Similarweb rank:** [347470](https://similarweb.com/website/farcaster.xyz)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

  - the hex and svg were provided in the issue description

### CODE REVIEW

**Review by PeterShaggyNoble — COMMENTED** [review]
Thanks for the contribution, @tytwitchell 👍🏻 However, your icon currently exceeds the bounds of our 24*24 canvas; could you fix that, please?

**Comment by tytwitchell** [comment]
@PeterShaggyNoble this has been corrected

**Comment by adamrusted** [comment]
Thanks for this one, @tytwitchell - though I would think we'd want it _with_ the rounded rectangle around the outside, see the preview below. I've included my path below based on their CSS on the site, which you're welcome to use - but we'll need another maintainer to review if you do!
image
```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Farcaster</title><path d="M18.24.24H5.76C2.5789.24 0 2.8188 0 6v12c0 3.1811 2.5789 5.76 5.76 5.76h12.48c3.1812 0 5.76-2.5789 5.76-5.76V6C24 2.8188 21.4212.24 18.24.24m.8155 17.1662v.504c.2868-.0256.5458.1905.5439.479v.5688h-5.1437v-.5688c-.0019-.2885.2576-.5047.5443-.479v-.504c0-.22.1525-.402.358-.458l-.0095-4.3645c-.1589-1.7366-1.6402-3.0979-3.4435-3.0979-1.8038 0-3.2846 1.3613-3.4435 3.0979l-.0096 4.3578c.2276.0424.5318.2083.5395.4648v.504c.2863-.0256.5457.1905.5438.479v.5688H4.3915v-.5688c-.0019-.2885.2575-.5047.5438-.479v-.504c0-.2529.2011-.4548.4536-.4724v-7.895h-.4905L4.2898 7.008l2.6405-.0005V5.0419h9.9495v1.9656h2.8219l-.6091 2.0314h-.4901v7.8949c.2519.0177.453.2195.453.4724"/></svg>
```

**Comment by tytwitchell** [comment]
thanks @adamrusted! I just added the styles and re-tested locally.  thank you and your team for your patience with this one.

If you need anything else feel free to let me know.

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
I'm seeing [some small differences](https://github.com/simple-icons/simple-icons/assets/15157491/9ebaadab-2a3e-482c-a5ce-3547e651b372) (PR in red) throughout both the left & right side of the cut-out. As we're manually recreating this from CSS, though, I'd be happy to let them slide if someone else decides they're insignificant enough.

**Review by service-paradis — APPROVED** [review]
On my side, I got much smaller differences than yours @PeterShaggyNoble . LGTM, thank you @tytwitchell!

**Pull request merged**
