### PR TITLE
Updated Opel

### PR DESCRIPTION
**Pull request by adamrusted**
opel

**Issue:** Contributes to #4578
**Alexa rank:** [128,956](https://www.alexa.com/siteinfo/opel.com) 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Update to source, and a slight change to the SVG based on new source.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Could you take another look at this one, @adamrusted? I'm noticing some hairline differences, mainly in the "bolt", which may simply be a precision issue. There are also a couple of excess points top & bottom of the inside of the circle and on the very right of the "bolt".

**Comment by adamrusted** [comment]
@PeterShaggyNoble had to bump it to 4 decimals, but should be good now.

**Comment by fbernhart** [comment]
The icon looks good to me 👍🏼  But how about the color?

I haven't found any brand guidelines, but given that our current color (`#F7D900`) was based on #2361, where we've just used the yellow found on their website, we should change it.

The two websites linked below are now using `#F7FF14` instead.

https://de-media.opel.com
https://www.opel.de

**Comment by adamrusted** [comment]
@fbernhart happy to update colour. Give me a minute and should be ready for review 👌

**Comment by fbernhart** [comment]
@adamrusted Great work! 🚗

**Pull request merged**
