### PR TITLE
Add babbel icon

### LINKED ISSUE #10654: Request: Babbel
### Brand Name

Babbel

### Website

https://babbel.com

### Popularity Metric

The similar web rank is 5595 https://www.similarweb.com/website/babbel.com

### Official Resources for Icon and Color

babbel

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by imskr**
**Issue:** closes #10654 

**Popularity metric:**

The similar web rank is 5595 https://www.similarweb.com/website/babbel.com

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

N/A

### CODE REVIEW

**Comment by imskr** [comment]
I don't understand why the lint is failing even though the dimensions are correct

**Comment by adamrusted** [comment]
Are you still working on this one, @imskr?

**Comment by imskr** [comment]
Thanks @adamrusted for the review. I am not very comfortable with SVG paths. Is it something you can help me with it?

**Comment by adamrusted** [comment]
Which editing software are you using @imskr? There are different steps to correct this based on which one you're using.

**Comment by imskr** [comment]
> Which editing software are you using @imskr? There are different steps to correct this based on which one you're using.

I haven't had the chance to look at it tbh as I have never used it before for these works @adamrusted

**Comment by adamrusted** [comment]
Fair enough! Worth a read of [this file](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) to go through how we recommend editing files and adding them to a PR. There are various software options there - and once you settle on one we can advise better on how to get the linter to pass.

**Comment by adamrusted** [comment]
Did you still want to work on this @imskr?

**Comment by imskr** [comment]
Sorry I do not have any bandwidth to work on this @adamrusted

**Pull request closed without merging**
