### PR TITLE
chore: update nuxt icon

### PR DESCRIPTION
**Pull request by Atinux**
**Similarweb rank:** 58,168
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

New version of Nuxt brought the new logo

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @Atinux,

thanks for the contribution.

I see a difference to the original icon in the design kit.
image

**Comment by Atinux** [comment]
I tried to optimise it but not sure what is the best way to do so

**Comment by Atinux** [comment]
Tried multiple things but don't know how to fix the lint @dirien

**Review by dirien — APPROVED** [review]
Hi @Atinux ,

Thanks for your contribution to simple-icons!

It's a perfect fit:
image

**Pull request merged**
