### PR TITLE
Letter R review

### PR DESCRIPTION
**Pull request by service-paradis**
**Issue:** #5251

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`

### Question

- According to https://static.raspberrypi.org/files/Raspberry_Pi_Visual_Guidelines_2020.pdf, should we keep the R symbol?
- I'm not sure is I'm looking at the correct RTL. They might have changed their logo?

### Description

- Update Rakuten data
  - Add guidelines
- Update Ram data
  - Add guidelines
- Update Rancher data
  - Add guidelines
- Update Raspberry Pi data
  - Add guidelines
  - Update color
- Update Razer data
  - Update source
- Update React Router data
  - Update source
- Update Realm data
  - Update source
- Update Reason Studios data
  - Add guidelines
- Update Reddit data
  - Add guidelines
- Update Redis data
  - Add guidelines
- Update RedwoodJS data
  - Add guidelines
- Update Ripple data
  - Add guidelines
- Update Roam Research data
  - Update source
- Update Roku data
  - Add guidelines
- Update Roots data
  - Add guidelines
- Update ROS data 
  - Add guidelines
- Update RStudio data 
  - Add guidelines
- Update Ruby data 
  - Add license
- Update Runkeeper data
  - Add guidelines
- Update Rust data
  - Add guidelines
  - Add license

### CODE REVIEW

**Comment by adamrusted** [comment]
> * According to [static.raspberrypi.org/files/Raspberry_Pi_Visual_Guidelines_2020.pdf](https://static.raspberrypi.org/files/Raspberry_Pi_Visual_Guidelines_2020.pdf), should we keep the R symbol?

Yep. Guidelines explicitly state no removal of ® mark. Did you want to look at submitting an update?

> * I'm not sure is I'm looking at the correct RTL. They might have changed their logo?

Looks like we're including [this RTL](https://www.rtl.de/), with the logo matching [their Wikipedia page](https://de.wikipedia.org/wiki/RTL_Television).

**Comment by service-paradis** [comment]
> > * According to [static.raspberrypi.org/files/Raspberry_Pi_Visual_Guidelines_2020.pdf](https://static.raspberrypi.org/files/Raspberry_Pi_Visual_Guidelines_2020.pdf), should we keep the R symbol?
> 
> Yep. Guidelines explicitly state no removal of ® mark. Did you want to look at submitting an update?

I dont know if I will find enough time soon for it. I will open a new issue if someone want to take a look at it!

> > * I'm not sure is I'm looking at the correct RTL. They might have changed their logo?
> 
> Looks like we're including [this RTL](https://www.rtl.de/), with the logo matching [their Wikipedia page](https://de.wikipedia.org/wiki/RTL_Television).

Thank you for your help and thanks Google Translate 😅 
Other than in their Wikidata page, I dont find any use of this icon. Is it outdated?

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @service-paradis 🚀

**Comment by adamrusted** [comment]
> Other than in their Wikidata page, I dont find any use of this icon. Is it outdated?

Quite possibly. They are a subsidiary of the [RTL Group](https://www.rtlgroup.com/en/about_us/businesses/tv-broadcast.cfm) who have one logo, with [RTL.de](https://www.rtl.de/) having it's own. I'll merge this PR for now, as the rest of the data is good - but could a German-speaking @simple-icons/maintainers clarify which one we should be using?

**Comment by PeterShaggyNoble** [comment]
Our RTL icon is for their flagship television channel in Germany. The full colour logo is the one seen on Wikipedia and the brands page linked above. The monochrome treatment which can be seen in the corner of the screen during programmes as well as on subsites such as [their gaming site](https://spiele.rtl.de/).

Having said all that, our version was recreated from the full colour Wikipedia version as we couldn't find a vector of the monochrome version at the time but, after a little bit more digging this morning, I unearthed [this SVG](https://www.mediengruppe-rtl.de/export/system/modules/com.netrtl.cms.mediengruppe/resources/refresh/dist/images/logos/senderlogo_RTL_324x136_s.svg) in the footer of [this site](https://www.mediengruppe-rtl.de/) so we should double check ours lines up with it and update if not. And, while we're at it, we should also check [VOX](https://www.mediengruppe-rtl.de/export/system/modules/com.netrtl.cms.mediengruppe/resources/refresh/dist/images/logos/senderlogo_VOX_324x136_s.svg); our version was based on a particularly messy SVG found on Wikipedia.

**Pull request merged**
