### PR TITLE
Add VMware

### LINKED ISSUE #1653: VMWare Icon
**Name: VMWare Inc
**Website: www.vmware.com
**Official resources for icon and color: www.vmware.com

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
VMware

**Issue:** Closes #1653

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
~Colour was converted from a Pantone found in [their brand guidelines](https://www.vmware.com/content/dam/brand/photography-only/guidelines/logo/VMWare_Logo_Guidelines_January2019.pdf), which now, unfortunately, require registration to access.~

Credit to @phatbhoy67 for sourcing an official SVG.

Possible alternative treatment (see conversation below), which may not adhere to their brand guidelines:

[VMware](https://github.com/simple-icons/simple-icons/files/4026437/vmware.zip)

Markup, so I can update from my phone, if necessary:
```
<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>VMware icon</title><path d="M1.281 7.129a1.296 1.296 0 00-.504.125 1.277 1.277 0 00-.642 1.744l2.924 6.354c.458.974.974 1.521 1.851 1.521s1.394-.566 1.852-1.521l2.572-5.614a.37.37 0 01.371-.234.41.41 0 01.399.41v5.438a1.374 1.374 0 102.74 0v-4.444a1.364 1.364 0 011.45-1.414 1.335 1.335 0 011.395 1.414v4.444a1.364 1.364 0 001.354 1.521 1.384 1.384 0 001.375-1.521v-4.444a1.364 1.364 0 011.451-1.414 1.335 1.335 0 011.395 1.414v4.444a1.364 1.364 0 001.353 1.521 1.374 1.374 0 001.375-1.521v-5.059a3.167 3.167 0 00-3.295-3.156 4.23 4.23 0 00-2.924 1.246 3.236 3.236 0 00-2.816-1.237 4.64 4.64 0 00-2.758 1.237 3.304 3.304 0 00-2.465-1.237 3.021 3.021 0 00-2.972 2.018L4.89 13.568 2.492 7.916l.03-.01a1.296 1.296 0 00-1.24-.777Z"/></svg>
```

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble I'm not convinced about needing to use the full wordmark (although I haven't read the guidelines 😆 ) simply because they use just "vm" all across their social media accounts. I think the icon should be the "vm" in a box to match the website favicon, so best ask the other @simple-icons/maintainers for a view.

**Comment by PeterShaggyNoble** [comment]
Found another copy of the brand guidelines that doesn't require registration at https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/company/vmware-it-academy-logo.pdf

The lines I quoted in the issue can be found on the second page of that PDF. Although, if we can get away with it, I'd also definitely prefer if we could just use the `vm`.

**Comment by PeterShaggyNoble** [comment]
I've updated the PR according to the SVG you found, @phatbhoy67, thanks for that.

**Comment by runxel** [comment]
Maybe use `https://myvmware.workspaceair.com/SAAS/horizon/images/vmware_logo.svg` as link and not the generic one? 🤔

**Comment by PeterShaggyNoble** [comment]
We'd run the risk of "link-rot" there, @runxel, if they were ever to update their logo.

**Comment by runxel** [comment]
> We'd run the risk of "link-rot" there, @runxel, if they were ever to update their logo.

Yeah, I know, I know 😞, but at least you could always just go back to the root in this case.
One reason more for https://github.com/simple-icons/simple-icons/issues/2068

**Comment by birjolaxew** [comment]
Given the guidelines, I would personally lean towards the full wordmark. Although the official social media avatars do break with their own guidelines, they also differ enough from their logo that I wouldn't use them as an official source for that.

**Comment by PeterShaggyNoble** [comment]
Any thoughts from the other @simple-icons/maintainers on @runxel's suggestion for the source URL? That's the last thing to clear up before we can merge this in.

**Comment by birjolaxew** [comment]
As long as the logo can be easily extracted from the source URL (as in this case), the convention so far has been to use the generic URL.

**Pull request merged**
