### PR TITLE
Add Ecovacs

### PR DESCRIPTION
**Pull request by ronschaeffer**
image

**Issue:** closes #

**Similarweb rank:** 63,922

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Vector created from rasterized image https://mma.prnewswire.com/media/1232042/ECOVACS_Logo.jpg distributed as part of an official press release.

Color 19374F picked from the color of the E here https://mma.prnewswire.com/media/1232042/ECOVACS_Logo.jpg, which is also the color of the remainder of the wordmark https://mma.prnewswire.com/media/2216491/Ecovacs_Logo_Logo.jpg.

### CODE REVIEW

**Comment by Mvlprem** [comment]
Thanks for the contribution, @ronschaeffer You can find the vector version in their product manual [DEEBOT OZMO T8](https://www.ecovacs.com/in/support/deebot-ozmo-t8#download)

**Comment by ronschaeffer** [comment]
> Thanks for the contribution, @ronschaeffer You can find the vector version in their product manual [DEEBOT OZMO T8](https://www.ecovacs.com/in/support/deebot-ozmo-t8#download)

Thanks. I didn't use user manuals as a source, because the logo is incorrectly applied in all user manuals that I checked--about half a dozen of them.

The lower curve is clipped at the bottom in the user manuals:

image

The logo is also stretched horizontally when compared to official PNGs on the website and in press releases. The PNGs I've checked are consistent with each other. The user manual version is shown in yellow below overlayed on the official PNG.

image

**Comment by Mvlprem** [comment]
@ronschaeffer I believe that the image you used to make the svg is from this news website [PR Newswire](https://www.prnewswire.com/news/ecovacs/) if that's the case i don't think we take that as an official source, as far as i know the image must be from the website, or from a document found on website, git hub project or Wikipedia.

In that case i suggest to use the vector in one of their product manual, now i know it's not perfect as you pointed out, but as long as they are using it in their official document we are good with it. Just to be sure I'll ask another maintainer to take a look and let's see what he has to say about this if they are good with your decision then you can go ahead.

@adamrusted, @PeterShaggyNoble What are your thoughts on this ?

**Review by adamrusted — APPROVED** [review]
Great work, thanks for this @ronschaeffer!
Always pays for us to be detail oriented! 🔎

**Pull request merged**
