### PR TITLE
Update Peugeot

### PR DESCRIPTION
**Pull request by adamrusted**
peugeot

**Issue:** #4578
**Alexa rank:** [46,068](https://www.alexa.com/siteinfo/peugeot.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
As pointed out by @gizmecano in https://github.com/simple-icons/simple-icons/pull/5013#issuecomment-786513237, Peugeot are in the process of updating their branding. Thankfully, they've included SVGs on both the Stellantis and Peugeot websites. I've gone with the Stellantis source, as it seems to be a bit higher-fidelity than the header of Peugeot's own website. As pointed out by other @simple-icons/maintainers though, some of the Stellantis SVGs haven't been optimized effectively. Happy to switch source back to Peugeot.com if we think that's a better icon.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Oof! Both versions are a little rough, each with their own many and differing issues. If we have to choose between the 2, though, I'd opt for the one from Peugeot simply because the lettering is cleaner.

**Comment by adamrusted** [comment]
> If we have to choose between the 2, though, I'd opt for the one from Peugeot simply because the lettering is cleaner.

Thought as much 😅
Give me a few minutes and I'll have it updated.

**Comment by adamrusted** [comment]
@PeterShaggyNoble give that a go. I've removed as many of the excess points as possible from the Peugeot.co.uk website version.

**Comment by fbernhart** [comment]
LGTM 👍🏼

**Pull request merged**
