### PR TITLE
Replace Postwoman by Hoppscotch

### LINKED ISSUE #3589: Rename Postwoman
**Name:**

The brand 'Postwoman' has been renamed to Hoppscotch. Logo and color have been kept same.

**Official resources:**

- Old domain: https://postwoman.io/
- New domain: https://hoppscotch.io/

### PR DESCRIPTION
**Pull request by ericcornelissen**
### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Closes #3589, removes [Postwoman](https://simpleicons.org/?q=Postwoman) and replaces it by [Hoppscotch](https://hoppscotch.io/) in preparation for the upcoming [v4 release](https://github.com/simple-icons/simple-icons/milestone/3).

The new SVG is based on [the SVG version of the logo](https://github.com/hoppscotch/hoppscotch/blob/main/static/images/ufo_logo.svg) I found in the repository of the website of Hoppscotch. that version has tiny lines between the three components of the logo (UFO top part, UFO body, UFO "beam") that I removed - I'd be open to reintroducing them, but I feel like they don't work at small sizes... The color I took from the "alien" SVG in the sidebar of [the Webapp](https://hoppscotch.io/), given that the green in the logo SVG is a gradient. Suggestions for a better color source are welcome (@ChristianOellers any ideas?).

### CODE REVIEW

**Review by mondeja — APPROVED** [review]
I see it well, I have tried a version with the halo without filling but it looks very bad in small sizes and breaks the original logo.

**Review by service-paradis — APPROVED** [review]
I always thought their logo was the alien head 😛 They use it everywhere!
LGTM, not an easy one to do monochrome!

The accent color used in the website is `#31c48d`, but I'm not sure if it should be used.
```css
:root[data-accent=green] {
    --ac-color: #31c48d;
}
```

**Comment by ericcornelissen** [comment]
> I always thought their logo was the alien head

I'm not familiar with the product so I don't know. If you think it should be the alien we might have to consider that? What would you say @ChristianOellers?

> The accent color used in the website is `#31c48d`, but I'm not sure if it should be used.

Ow oops, that is actually the color I intended! 😅 Will update this momentarily.

**Comment by ericcornelissen** [comment]
Without further feedback I will be merging this as is so that the name change is included in the [upcoming v4 release](https://github.com/simple-icons/simple-icons/milestone/3), if it turns out the color or SVG need to change this can be done at a later time without requiring a name change.

**Pull request merged**
