### PR TITLE
Add Voron Design

### LINKED ISSUE #8694: Voron Design
### Brand Name

VoronDesign

### Website

https://vorondesign.com/

### Popularity Metric

Global Rank is 150,862.

### Official Resources for Icon and Color

https://avatars.githubusercontent.com/u/44981431?s=200&v=4

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
vorondesign

**Issue:** closes #8694 

**Similarweb rank:** 160,586. See https://www.similarweb.com/website/vorondesign.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Traced out PNG available at https://vorondesign.com/
Color: `#FE2100` Taken from logo on website

### CODE REVIEW

**Comment by raymondh2** [comment]
I see you used a traced out PNG from the main website. We have our logo available in multiple formats here https://github.com/VoronDesign/Voron-Extras/tree/main/Images/Logo

**Comment by PratyushJayachandran** [comment]
> I see you used a traced out PNG from the main website. We have our logo available in multiple formats here https://github.com/VoronDesign/Voron-Extras/tree/main/Images/Logo

This is awesome, will use these SVGs instead. I was checking in the wrong repositories 😅

**Comment by PratyushJayachandran** [comment]
@raymondh2 I have updated the PR with the icon you provided. Excited to see such products 😊

@adamrusted you may remove the from raster icon now. Please review the updated PR
vorondesign

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @PratyushJayachandran 🎉

**Pull request merged**
