### PR TITLE
Run Renovate through GitHub action

### PR DESCRIPTION
**Pull request by mondeja**
Renovate is not opening PRs because of scheduling, see https://github.com/simple-icons/simple-icons/pull/9634#issuecomment-1736893958

So this PR configures it to run self hosted through a GitHub action. See https://github.com/renovatebot/github-action for information. Chosen first day of May and November to run, a few weeks before major releases.

I've added a personal token of my own as `RENOVATE_TOKEN`.  Means that it will open PRs with my user, which is not ideal, but if `GITHUB_TOKEN` is used it will not trigger CI. 

TODO:
- If this PR is merged, disable the Renovate GitHub App integration for the repo.
- If this PR is rejected, remove `RENOVATE_TOKEN` from repository secrets.

### CODE REVIEW

**Comment by LitoMore** [comment]
Can we use this? https://github.com/organizations/simple-icons/settings/personal-access-tokens-onboarding

I'm not sure if it's the correct thing.

**Comment by mondeja** [comment]
> Can we use this? https://github.com/organizations/simple-icons/settings/personal-access-tokens-onboarding
> 
> I'm not sure if it's the correct thing.

Use that for what? Organizations don't have accounts. That's only access for personal tokens with more customized access to the organization's repositories. Nothing relevant in this context.

**Comment by uncenter** [comment]
Is it worth creating a specific `simple-icons-bot` account for these kind of things? As you said, having it from your user is not ideal so that is a potential alternative... :eyes:

**Comment by mondeja** [comment]
> Is it worth creating a specific `simple-icons-bot` account for these kind of things? As you said, having it from your user is not ideal so that is a potential alternative... 👀

Not sure. Personally I don't want to deal with more accounts, seems to me that it would increase the maintenance burden and currently is huge.

**Comment by LitoMore** [comment]
@mondeja We can count how many bot committers are currently automatically executed using your personal account and then consider whether you need a new bot account.

This new bot account is not used to generate tokens. It displays a better avatar and name more suitable for the scene.

**Comment by LitoMore** [comment]
Merging. This looks good to me for now. We can have more discussions in the future.

**Comment by mondeja** [comment]
> @mondeja We can count how many bot committers are currently automatically executed using your personal account and then consider whether you need a new bot account.
> 
> This new bot account is not used to generate tokens. It displays a better avatar and name more suitable for the scene.

I do not know what you mean. Is there a way to set something like this up without creating a new account?

**Comment by LitoMore** [comment]
I mean, create a new bot account, but use your tokens. Tokens are still easy to maintain.

We can use `git config user.name` and `git config user.email` to change the display user.

Sometimes, I see your account merging a PR or deleting and adding a label in seconds, which may confuse others. It might look a little friendlier if it showed a bot.

At the same time, your account can also get a more accurate contributions graph on GitHub profile.

**Comment by uncenter** [comment]
My thoughts exactly regarding the reasoning for a bot :)

**Comment by mondeja** [comment]
> We can use `git config user.name` and `git config user.email` to change the display user.

I'm all ears. What should be the values? We haven't done it until now because I have no idea how to do it.

> At the same time, your account can also get a more accurate contributions graph on GitHub profile.

Yes, I agree. But to make this clear, only this PR opened for dependencies will be added to my profile because other contributions are not appearing: adding or removing labels nor pushing to `master` (contributions to non default branches are not displayed). And anyways I'm opening PRs for dependency updates.

**Comment by LitoMore** [comment]
We already have similar usage here:

https://github.com/simple-icons/simple-icons/blob/883152bfb802fd1294022a43e42bb73ac6a1e635/.github/workflows/publish.yml#L71-L72

**Comment by mondeja** [comment]
Ah, if that works it would be great. Please, would you mind to open a PR for that @LitoMore? We can revert it if something bad happens.

**Pull request merged**
