### PR TITLE
Add LibreOffice Calc

### LINKED ISSUE #9496: LibreOffice apps
### Brand Name

LibreOffice

- [x] LibreOffice Base #9595
- [ ] LibreOffice Calc #9923
- [x] LibreOffice Impress #9925 
- [x] LibreOffice Math #9926 
- [x] LibreOffice Writer #9927 

### Website

https://www.libreoffice.org/

### Popularity Metric

[GlobalRank](https://www.similarweb.com/website/libreoffice.org/#overview) equals 17,519

### Official Resources for Icon and Color

https://wiki.documentfoundation.org/Marketing/Branding

### Additional Comments

Since Microsoft Office has separate icons for Word, Excel, PowerPoint, Access, I think LIbreOffice could have separate icons for Writer, Calc, Impress, Base, Math

### Contributing

No

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
libreofficecalc

**Issue:** closes #9496 

**Similarweb rank:** 14,010. See https://www.similarweb.com/website/libreoffice.org

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from [GitHub Repo](https://github.com/LibreOffice/help/tree/master/source/media/navigation)
Color: `#007C3C` Taken from Base column in branding page https://wiki.documentfoundation.org/Design/Branding

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
@PratyushJayachandran - what gap did you use on this?
If we were to go with our smallest recommended gap of 0.5px, you can see your PR (in red) doesn't line up with the source in black below. Could you take another look please?
image

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran - what gap did you use on this? If we were to go with our smallest recommended gap of 0.5px, you can see your PR (in red) doesn't line up with the source in black below. Could you take another look please?

So, this happened because I inverted the treatment we usually give. I made an inside stroke and subtracted from the small green colored shape. I did that to keep the impression of it being in the front like in the colored image.
libreofficecalc-comparison

See original overlaid on contribution. I can re-do the usual way if you want :)

**Comment by adamrusted** [comment]
If you could, @PratyushJayachandran - that'd be great. I think it's more important to maintain the size of the front element, and have the cutout taken from the table in the background than the other way around!

**Comment by PratyushJayachandran** [comment]
> If you could, @PratyushJayachandran - that'd be great. I think it's more important to maintain the size of the front element, and have the cutout taken from the table in the background than the other way around!

Please check again @adamrusted 
libreofficecalc

**Comment by PratyushJayachandran** [comment]
@adamrusted please check again. I fixed it 😄 
libreofficecalc

**Review by PeterShaggyNoble — APPROVED** [review]

**Pull request merged**
