### PR TITLE
Add Netlify CMS alias

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** N/A
**Alexa rank:** [~120k](https://www.alexa.com/siteinfo/netlifycms.org)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description

- We have aliases now, so wanted to give it a try :)

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Looks good to me, @service-paradis 👍🏻

**Comment by service-paradis** [comment]
Thanks @PeterShaggyNoble!
I'm thinking about it, with the current release action, those icons wont be listed as new icons in release notes?

**Comment by PeterShaggyNoble** [comment]
See the note at the end of #5615 😉

**Comment by ericcornelissen** [comment]
Actually, currently these "aliases" are not being released as icons yet, so it does not (yet) make sense to include them in the release notes - see [this comment](https://github.com/simple-icons/simple-icons/issues/4797#issuecomment-834484723) for more. But you're right, we should include them once we do release them.

**Pull request merged**
