### PR TITLE
Add bose

### LINKED ISSUE #3017: Bose logo request
**Name: Bose**
**Website: https://www.bose.com/**
**Official resources for icon and color: https://de.wikipedia.org/wiki/Datei:Bose_logo.svg**

### PR DESCRIPTION
**Pull request by Orchomenos**
bose

**Issue:** Closes #3017

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for this one, @Orchomenos :+1:

Two little things before we can merge it in, though:
1. The name should be capitalised as "Bose"
2. The SVG path is coming in at `24.001` wide, rather than `24`.

You'll also need to remove the Audio-Technica JSON entry and SVG from your branch. Rather than working directly on the `develop` branch of your fork, we generally recommend creating a new branch for each icon/PR in order to help keep thing separated.

**Comment by PeterShaggyNoble** [comment]
Thanks for updating, @Orchomenos - everything looks good to me now. Just need to remove the Audio-Technica SVG and this one is ready to merge.

**Comment by ericcornelissen** [comment]
> Thanks for updating, @Orchomenos - everything looks good to me now. Just need to remove the Audio-Technica SVG and this one is ready to merge.

A tip for the future @Orchomenos, as the [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) suggest you should ideally checkout to a different _branch_ when contributing anything. If you're unfamiliar with git branches, I recommend looking into it if you like contributing.

In short, it's a way to make multiple contributions in parallel completely separate from each other. So if you want to contribute two icons, you create two branches and you can open two Pull Requests!

Feel free to ask for more info or pointers with more information if you're interested :slightly_smiling_face:

**Comment by Orchomenos** [comment]
Thank you for the help, definitly going to use it in the future (or at least try it).

**Comment by PeterShaggyNoble** [comment]
Thanks for your work on this one, @Orchomenos :+1:

**Pull request merged**
