### PR TITLE
feat: add playwright icon

### LINKED ISSUE #7470: Request: Playwright
### Brand Name

Playwright

### Website

https://playwright.dev/

### Popularity Metric

The Similarweb rank is 108,804. See https://www.similarweb.com/website/playwright.dev

### Official Resources for Icon and Color

svg: https://playwright.dev/img/playwright-logo.svg
color: `#242526`

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by SimonGolms**
**Issue:** closes #7470 

**GitHub Stars:** [39k](https://github.com/microsoft/playwright)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I used the svg [icon](https://github.com/microsoft/playwright.dev/blob/768c59464e5b3270db26fa6a839d022a7e0dd064/static/img/playwright-logo.svg) from the website repository and have removed the shadow elements for simplicity.
I could not find the color mentioned in the request (`#242526`). Since there is no color guideline, you have to distinguish between the the light (`#1A7E1F`) and dark (`#45BA4B`) theme as [primary color](https://github.com/microsoft/playwright.dev/blob/768c59464e5b3270db26fa6a839d022a7e0dd064/src/css/custom.css) on the website. Therefore I selected the the most prominent color in the icon: `#2EAD33`

playwright

### CODE REVIEW

**Comment by SimonGolms** [comment]
I just stumbled across the discussion #5975 and adapted the icon a bit as another solution:

playwright (1)

```html
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Playwright</title><path d="M16.579 6.655c2.601.697 4.705.506 5.582.352.171-.03.331-.061.479-.09.932-.181 1.41-.274 1.356.545-.056.837-.257 2.136-.716 3.85-.996 3.715-4.27 10.875-10.42 9.227-1.681-.451-2.848-1.364-3.634-2.53l-.001.001c-.561-.832-.93-1.793-1.154-2.805h.001a12.169 12.169 0 0 1-.249-1.722c-.172-2.266.204-4.574.625-6.145a24.034 24.034 0 0 1 .219-.778c.388-1.313.773-2.282 1.086-2.915.362-.737.729-.418 1.445.205.114.099.237.206.37.317.684.573 2.41 1.792 5.011 2.488Zm-4.163 2.384c-1.644-.467-2.613 1.041-2.613 1.041l4.386 1.246s-.128-1.819-1.773-2.287Zm-1.938 4.653s.446 2.306 3.338 3.153c2.836.829 4.402-.948 4.43-.98l.001-.001-7.769-2.172Zm8.697-2.624c-1.644-.469-2.612 1.038-2.612 1.038l4.385 1.249s-.13-1.819-1.773-2.287Zm-10.87 7.226c-.502-.866-.819-1.849-1-2.871l-2.238.634s.27-1.567 2.054-2.337c-.097-2.122.257-4.237.651-5.707.142-.529.285-1.012.426-1.449-.648.355-1.477.722-2.473.99-2.007.541-3.63.398-4.307.281-.132-.023-.255-.047-.369-.069-.719-.137-1.087-.208-1.046.422.041.644.194 1.643.545 2.961.746 2.803 3.18 8.154 7.757 7.145ZM2.37 11.189l3.375-.889s-.099 1.298-1.364 1.631c-1.265.334-2.011-.742-2.011-.742Z"/></svg>
```

**Comment by sisp** [comment]
I think the variant with the gap looks better. But the gap does not have a constant width. It looks like its width is 0.5px at the top but >0.5px at the bottom. Could you make it 0.5px everywhere?

**Comment by SimonGolms** [comment]
Hi @sisp, you are right about the gap which comes from the shadow by the [original icon](https://github.com/microsoft/playwright.dev/blob/768c59464e5b3270db26fa6a839d022a7e0dd064/static/img/playwright-logo.svg). This change makes it look more authentic to me than a continuous gap of `0.5px`. However, I have an adjusted version with a continuous gap of `0.5px`. Please let me know what is the preferred variant now? 
Personally, I would choose variant 2 with the shadow as the gap.

playwright

```html
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Playwright</title><path d="M16.58 6.655c2.6.697 4.705.506 5.582.352.171-.03.33-.061.479-.09.932-.181 1.409-.274 1.355.545-.056.837-.257 2.135-.716 3.85-.995 3.715-4.269 10.874-10.419 9.227-6.152-1.65-5.408-9.487-4.413-13.201.459-1.716.934-2.941 1.305-3.694.362-.736.729-.417 1.446.206.114.099.236.206.369.317.684.573 2.41 1.791 5.012 2.488Zm-4.164 2.384c-1.644-.467-2.613 1.041-2.613 1.041l4.386 1.245s-.127-1.819-1.773-2.286Zm-1.938 4.653s.446 2.306 3.338 3.153c2.837.829 4.402-.948 4.431-.981l-7.769-2.172Zm8.697-2.624c-1.644-.469-2.612 1.038-2.612 1.038l4.385 1.249s-.129-1.819-1.773-2.287ZM8.704 18.191c-.544-.853-.904-1.825-1.127-2.846l-2.51.712s.291-1.688 2.262-2.421c-.196-2.418.205-4.89.654-6.567.042-.156.084-.308.126-.456-.634.339-1.434.685-2.383.941-2.008.541-3.631.398-4.308.28-.131-.022-.253-.046-.367-.068h-.002c-.718-.137-1.087-.208-1.046.422.041.644.194 1.643.546 2.961.76 2.856 3.272 8.359 8.021 7.08l.134-.038Zm-6.333-7.002 3.374-.889s-.098 1.298-1.363 1.631c-1.266.333-2.011-.742-2.011-.742Z"/></svg>
```

**Comment by sisp** [comment]
Ah, I see. There are arguments for both variants I guess. I slightly tend to prefer the continuous 0.5px gap variant to be honest. What do you think, @simple-icons/icon-review?

**Comment by sachinraja** [comment]
I also prefer the gap because of the shadow in the original icon

**Comment by SimonGolms** [comment]
I interpreted the feedback that the icon with the continuous gap of `0.5px` is preferred and just made the change.

**Review by sisp — COMMENTED** [review]
I see a difference between your icon and the one I've derived for comparison:


Now, the question is which one is correct. :thinking: My steps were:

1. Remove unnecessary paths, so that only 2 paths, one for each face, remain.
2. Subtract the right face from the left one to remove the part of the left face that is hidden behind the right one.
3. Add a stroke of width 1px to the right face.
4. Convert the stroke to a path.
5. Subtract the path-stroke from the left face.
6. Unite the paths of the two faces.
7. Resize and center the path.

This is what my derived SVG looks like:

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Playwright</title><path d="M23.996 7.462c-.056.837-.257 2.135-.716 3.85-.995 3.715-4.27 10.874-10.42 9.227-6.15-1.65-5.407-9.487-4.412-13.201.46-1.716.934-2.94 1.305-3.694.42-.853.846-.289 1.815.523.684.573 2.41 1.791 5.011 2.488 2.601.697 4.706.506 5.583.352 1.245-.219 1.897-.494 1.834.455Zm-9.807 3.863s-.127-1.819-1.773-2.286c-1.644-.467-2.613 1.04-2.613 1.04Zm4.058 4.539-7.769-2.172s.446 2.306 3.338 3.153c2.862.836 4.43-.98 4.43-.981Zm2.701-2.51s-.13-1.818-1.773-2.286c-1.644-.469-2.612 1.038-2.612 1.038ZM8.57 18.23c-4.749 1.279-7.261-4.224-8.021-7.08C.197 9.831.044 8.832.003 8.188c-.047-.73.455-.52 1.415-.354.677.118 2.3.261 4.308-.28a11.28 11.28 0 0 0 2.41-.956c-.058.197-.114.4-.17.61-.433 1.618-.827 4.055-.632 6.426-1.976.732-2.267 2.423-2.267 2.423l2.524-.715c.227 1.002.6 1.987 1.15 2.838a5.914 5.914 0 0 1-.171.049Zm-4.188-6.298c1.265-.333 1.363-1.631 1.363-1.631l-3.374.888s.745 1.076 2.01.743Z"/></svg>
```

What do you think?

**Comment by SimonGolms** [comment]
@sisp I edited the icon in the same steps with Figma and optimized it online with SVGOMG. Using `npm run lint`  I noticed that the icon is not centered, so I aligned it correctly with the help of Boxy SVG, which I did not manage with Figma and assume that there are rounding errors which have occurred.
To keep it short I have taken over your suggestion.

**Review by sisp — APPROVED** [review]
Thank you very much for your patience with the review iterations and pushing updates! :pray:

LGTM now! :tada:

There's no notable difference between the original icon and your icon anymore:


The SVG path length has also decreased. :slightly_smiling_face:

**Pull request merged**
