### PR TITLE
Add Devfolio icon

### LINKED ISSUE #10936: Request: Devfolio
### Brand Name

Devfolio

### Website

https://devfolio.co

### Popularity Metric

The similar web rank is 94,727. See https://www.similarweb.com/website/devfolio.co/

### Official Resources for Icon and Color

SVG: https://github.com/devfolioco/brand-assets/blob/main/Logo/Logo.svg

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by anhthang**
image

**Issue:** closes #10936 

**Popularity metric:**
The similar web rank is 94,727. See https://www.similarweb.com/website/devfolio.co/

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Hex value is from original svg

### CODE REVIEW

**Comment by anhthang** [comment]
> You may not modify the assets in the manner of color, font, or appearance.

Oops, I have just saw this from the brand guidelines. Do you guys think we won't add this?

**Comment by adamrusted** [comment]
Ooh, good spot. Definitely worth asking the question, as we don't stipulate a colour that users _must_ display the icon in. We can, however, link to a 'brand guidelines' page if that makes the decision easier for the team.

**Comment by anhthang** [comment]
Okay, just sent them email to request for permission

**Comment by anhthang** [comment]
Closing as no reply from brand

**Pull request closed without merging**
