### PR TITLE
Add Migadu icon

### LINKED ISSUE #10498: Request: Migadu
### Brand Name

Migadu

### Website

https://migadu.com/

### Popularity Metric

The Similarweb rank is 304,278. See https://www.similarweb.com/website/migadu.com/.

### Official Resources for Icon and Color

SVG: https://migadu.com/svg/logo_bg.svg

Color: `#0043CE` (from above SVG & homepage colors)

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by uncenter**
preview image

**Issue:** closes #10498.

**Similarweb rank:** https://www.similarweb.com/website/migadu.com/

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for this @uncenter!
Looking at both the source icon, and your PR there appear to be a lot of excess points, that we can probably clean up as part of this PR, mainly in the circular shapes.
image

Would you be up for having a go at that?

**Comment by uncenter** [comment]
Hmm I don't think I know my way around Inkscape for that yet ahah.

**Comment by uncenter** [comment]
Hmm but that removes the eye?

Screenshot 2024-03-15 at 10 04 24 (Arc)

**Comment by PeterShaggyNoble** [comment]
😮 The feck did that happen?!

**Comment by uncenter** [comment]
Not sure how to do that fancy overlay where you can see if it doesn't match up but from the naked eye the new SVG looks great!

**Comment by PeterShaggyNoble** [comment]
Nothing fancy about it 😉 You just layer the PR version over the source (or vice versa) in contrasting colours.

**Comment by service-paradis** [comment]
> Nothing fancy about it 😉 You just layer the PR version over the source (or vice versa) in contrasting colours.

@PeterShaggyNoble Which source did you use?
I get some differences comparing with https://migadu.com/svg/logo_bg.svg. Ex. 
image

**Review by service-paradis — APPROVED** [review]
@PeterShaggyNoble Nevermind, comparing to https://migadu.com/svg/logo.svg is a perfect match! Thank you @uncenter for your initial work on this!

**Pull request merged**
