### PR TITLE
Add CLion icon.

### LINKED ISSUE #5389: Request JetBarins CLion Icon
**Brand Name:**
CLion
**Website:**
https://www.jetbrains.com/clion/  
**Alexa rank:**
1,779
  

**Official resources for icon and color:**
https://www.jetbrains.com/company/brand/logos/  
color: black (000000)

### PR DESCRIPTION
**Pull request by nidbCN**
CLion

**Issue: Closes #5389**
**Alexa rank:1,779**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The Alexa rank just a reflection of JetBrains. So I use [CLion, IDEA and PhpStorm on Google Trends](https://trends.google.com/trends/explore?geo=US&q=CLion,intellij%20IDEA,phpstorm) and it works and I am here to create a pull request.

The svg file has something wrong first time. So I fix it and create this pr.

### CODE REVIEW

**Comment by nidbCN** [comment]
I had used SVGOMG Online Tool and SVGO Command Line Tool, which were written in contributing guidelines to optimize the Icon. But I still cannot fix the wrong that failing in GitHub Action.

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @nidbCN, and thanks for the contribution :+1:

The linter is currently failing as the 2 paths in the SVG need to be merged into one by knocking the lettering out of the background square. If you're using Inkspace, that can be done by selecting both paths and selecting "Exclude" from the "Path" menu, or by hitting <kbd>Ctrl + -</kbd>. There's also an unneeded `fill` attribute on one of the paths that should be removed, if it's still present after merging the paths.

**Comment by nidbCN** [comment]
I fix the error in my CLion svg file. Thanks for your help.
p.s. I put a wrong data in #5390 . I have corrected the link to data, is it necessary to have another look?

**Comment by PeterShaggyNoble** [comment]
Thanks, @nidbCN. I'm seeing some small differences throughout the icon, however, most noticeably at [the bottom of the "C"](https://user-images.githubusercontent.com/15157491/114848598-c0e92880-9dd6-11eb-8e52-48159018e3f9.png) (your version in red) when compared to the `icon_CLion.svg` source file. This is most likely down to the precision being set too low during the optimisation process rather than that you did wrong in the creation of the icon - you'll probably need to increase it to 3 but you _might_ get away with 2.

**Comment by nidbCN** [comment]
Ok, I'll work on it. Maybe there something wrong when I exclude the path.

**Comment by PeterShaggyNoble** [comment]
:thinking: That still looks the same to me, @nidbCN. Could you try increasing the precision level to 3 when optimising the SVG to see if that helps?

**Comment by nidbCN** [comment]
In the last and this commit, the precision level is three. So, I think there are something wrong when I expand paths.

I use Adobe Illustrator to expand paths first. This time I want to use Inkspace, but it not works when I press `Ctrl` + `-`. so, I used Adobe Illustrator to process the icon again. (But it also doesn't work).

Do you have any solution?

**Comment by PeterShaggyNoble** [comment]
You'll need to run SVGOMG on your original SVG, pre-optimisation rather than the version included in the PR. If you're still having trouble with it, you're more than welcome to use my version below:

```html
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>CLion icon</title><path d="M0 0v24h24V0H0zm7.041 3a5.049 5.049 0 0 1 .219 0c1.86 0 3 .6 3.9 1.56L9.78 6.18C9 5.46 8.22 5.04 7.26 5.04c-1.68 0-2.88 1.38-2.88 3.12 0 1.68 1.2 3.12 2.88 3.12 1.14 0 1.86-.48 2.64-1.14l1.38 1.38c-1.02 1.08-2.16 1.8-4.08 1.8a5.1 5.1 0 0 1-5.1-5.16A5.049 5.049 0 0 1 7.04 3zm5.738.12H15v8.1h4.32v1.86h-6.54V3.12zM2.28 19.5h9V21h-9v-1.5Z"/></svg>
```

**Comment by nidbCN** [comment]
I first optimize the icon, then use Inkspace to edit the Adobe Illustrator to expand paths. But the result is same as the last version that has a difference.

So, I add your version to the icons folder. Thanks for your help.

p.s. What should I do with the ReSharper icon?

**Comment by PeterShaggyNoble** [comment]
Everything looks good to me now, @nidbCN, thanks for your continued efforts on this one 👍🏻

As you're using the path I provided, though, we'll need one of the other @simple-icons/maintainers to review it before merging.

**Comment by nidbCN** [comment]
Sure, it is necessary to review the changes.

En... What should I do with the ReSharper icon in another issue. I give you a wrong data by mistake. So, I don't know it is a clever idea to add the ReShaper icon.

**Review by adamrusted — APPROVED** [review]
Spot on! Thanks @nidbCN for your work on this, and @PeterShaggyNoble for the assist! 💪

**Pull request merged**
