### PR TITLE
Add Air India

### LINKED ISSUE #6005: Add Air India
**Brand Name:** Air India
**Website:** https://www.airindia.in/
**Similarweb rank:** [12,698](https://www.similarweb.com/website/airindia.in/#overview)

**Official resources for icon and color:** 
Wikipedia. Primary color used from the logo is `#C5022E`.

### PR DESCRIPTION
**Pull request by wwwescape**
airindia

**Issue:** Closes #6005
**Similarweb rank:** [12,698](https://www.similarweb.com/website/airindia.in/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
 - I used the SVG from Wikipedia
 - I used Inkscape to remove the text, scale and adjust
 - I used https://jakearchibald.github.io/svgomg/ to optimize

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @wwwescape 👍🏻

After a bit of digging I found some official vector versions in the PDFs available [here](https://www.airindia.in/annualreport-2019-2020.htm) so I think we should run with that for the source and base our version off one of those. Also, what do you think of using the treatment below, with the flower cut out of the fin? I think it retains the integrity of the brand a bit better. And, for the colour, from the page I linked above, I'm getting `#C32026`.

**Comment by wwwescape** [comment]
Sure @PeterShaggyNoble. I'll take another look at it over the weekend.

**Comment by wwwescape** [comment]
@PeterShaggyNoble I tried my best with the vectors from the PDF. Could you check if the updated SVG is good enough?

**Comment by adamrusted** [comment]
@simple-icons/icon-review - I've resurrected this PR using the website as source - as they've now updated to include the icon there!

airindia

**Review by LitoMore — APPROVED** [review]
image

LGTM!

**Pull request merged**
