### PR TITLE
[New icon] .NET

### PR DESCRIPTION
**Pull request by DoronBrayer**
.NET icon - according to the guidelines.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Thanks @DoronBrayer, the icon looks good but you forgot to add the icon to `_data/simple-icons.json`. Can you add an entry to that file with the correct details for .NET

**Comment by DoronBrayer** [comment]
@ericcornelissen No problem.
See [pull request](https://github.com/simple-icons/simple-icons/pull/876).

**Comment by ericcornelissen** [comment]
I notice this is your first PR @DoronBrayer, so I'll give you a little tip. You can (and should) continue your contributions on this pull request 😉 

You can do that by making sure you're on the [branch](https://git-scm.com/book/en/v1/Git-Branching-What-a-Branch-Is) belonging to this pull request. For this PR the branch name is "patch-2". When you're on that branch you can make the same changes as you did in the other pull request and push the changes to Github.

If you need any more help, feel free to ask me in this thread, I'm happy to help you out 😃 In the mean time I closed your other pull request

**Comment by DoronBrayer** [comment]
@ericcornelissen Done. Anything else?
By the way, I'm new at this.

**Comment by ericcornelissen** [comment]
You're pretty much done. However, due to how we generate the website the current filename for the icon doesn't work. This is because we [remove](https://github.com/simple-icons/simple-icons/blob/4084e82ec9ce9abd4faf4bdb5bfdd04412acc82b/index.html#L8) any `"."` from the icon title and look for a file with that name, so in this case we would be looking for a file named `"net.svg"`.

But I don't think this is very nice, as from this name it is not clear that it is the icon for .NET 🤔 Personally I'm thinking we should change our current approach for matching the icon title in `./_data/simple-icons.json` to a file in `./icons`. But maybe there are other approaches we can take... @birjolaxew, @davidklebanoff, thoughts?

so @DoronBrayer, for now there is nothing you can do, but I won't merge your PR yet either 😅 


> By the way, I'm new at this.

I figured 🙂 But again, I'm happy to help!

**Comment by DoronBrayer** [comment]
@ericcornelissen 
Suggestion: Any brand that contains a "." prefix, should become "dotexample.svg".
In this case, it would be "dotnet.svg".
There are very few brands with this prefix, so don't think about it too much.

**Comment by DoronBrayer** [comment]
@ericcornelissen Here's another formula:
(dot)example.svg
(dot)net.svg
Using "()" this time.
Anyway, the .NET brand certainly deserves to be in Simple Icons.

**Comment by ericcornelissen** [comment]
> Anyway, the .NET brand certainly deserves to be in Simple Icons.

I'm not saying it doesn't, just give us some time to work things out. And again, thanks for you suggestions.

**Comment by birjolaxew** [comment]
Sorry about the late response, I was on a holiday that unexpectedly ended up being without an internet connection.

The issue is [how we map `icon.title` to a filename when generating our website](https://github.com/simple-icons/simple-icons/blob/ba5e411b83459553878109369af1cf539e8c9c83/index.html#L8). This replaces `"."` with `""`, so that e.g. `"About.me"` maps to `aboutme.svg`. This specific rule currently affects:

- About.me
- Brand.ai
- dev.to
- Draugiem.lv
- GOV.UK
- Last.fm
- Mail.Ru
- Micro.blog
- Node.js
- Picarto.TV
- Player.me
- Proto.io
- Vue.js

I'm personally a fan of simply changing the mapping from `"." → ""` to `"." → "dot"`, so that e.g. `"About.me"` maps to `aboutdotme.svg`. This stops the issue we run into when we *remove* information during the mapping, and it seems reasonable that any brand with a literal dot in their name could be represented with it replaced with "dot".

This would obviously involve renaming a couple of existing SVGs (a breaking change), but would be the easiest fix.

**Comment by davidklebanoff** [comment]
@ericcornelissen - If that is indeed the case, we could simply change the search to search across brand names versus file names?

**Comment by birjolaxew** [comment]
@ericcornelissen [I ran it through SVGO for him](https://github.com/simple-icons/simple-icons/pull/875/commits/6fec1f577bffb0a0f04633b719ce7a4b6628e264); a lower precision than 4 lead to artifacts, so it was left at that. Said commit is included in this PR.

**Comment by birjolaxew** [comment]
@DoronBrayer I think the PR is good to go, but since I was the one who made the latest changes (bd7e809 and 6fec1f5) it wouldn't be right of me to merge it. There seems to be some confusion internally about whether the icon is adequately optimized (6fec1f5), but we should clear up any confusion before optimizing further.

As of right now, we're waiting for @ericcornelissen to either approve or clarify his review.

**Comment by ericcornelissen** [comment]
> @ericcornelissen I ran it through SVGO for him; a lower precision than 4 lead to artifacts, so it was left at that. Said commit is included in this PR.

I guess I somehow just missed 6fec1f5 😅 it seems fine now, so I merged the PR 👍

**Comment by birjolaxew** [comment]
:+1: Thanks for the contribution @DoronBrayer, and thanks for all the work and discussion on this and #888 @ericcornelissen / @davidklebanoff!

**Pull request merged**
