### PR TITLE
adding underscorejs icon

### PR DESCRIPTION
**Pull request by jorgeamadosoria**
underscoredotjs

**Issue:**

Adding underscorejs icon.
Taken from https://github.com/jashkenas/underscore/blob/master/docs/images/underscore.png
Selected the only available color for the icon even though it betrays the idea behind the logo being dual colored.
No guidelines available.
Justified by having 5k+ stars on Github: https://github.com/jashkenas/underscore
Need for my personal set of used technology icons

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
what are you comparing against? the source you linked?
Because this icon has no work done at all. if you are comparing against the source you link, the only thing I can think of is precision

**Comment by sachinraja** [comment]
Yes, I compared against https://github.com/jashkenas/underscore/blob/f098f61ff84931dea69c276b3674a62b6ae4def7/docs/images/underscore.png

**Comment by sachinraja** [comment]
How did you compare them? I copied your svg into inkscape, centered it, and changed the color to red. Then I copied the original image, resized it, and centered it on the page.

**Comment by jorgeamadosoria** [comment]
> I'm still seeing a difference. How did you compare them? I copied your svg into inkscape, centered it, and changed the color to red. Then I copied the original image, resized it, and centered it on the page.

well, the order of transformations here is:
1 - convert PNG to SVG with Convertio
2 - Union all paths in Inkspace
3 - remove `transform(.75)` and resize the path to 24 in the horizontal.
4 - resize view to 24x24
5 - center the path
6 - remove stroke

That's it. There is no particular work being done here, so I don't know why there is a discrepancy or how big it is.

**Comment by sachinraja** [comment]
It's not that big of a difference and considering the source is a PNG, I'm ok with merging this as is. I'm not sure if the other @simple-icons/maintainers agree though.

**Comment by jorgeamadosoria** [comment]
> It's not that big of a difference and considering the source is a PNG, I'm ok with merging this as is. I'm not sure if the other @simple-icons/maintainers agree though.

before we do that, can you share the svg code you used to compare my changes against? I want to make the same comparison you did on my side, see what is the problem.

**Comment by sachinraja** [comment]
@jorgeamadosoria I think the merge needs to be done again. This shows 4294 changed files

**Comment by jorgeamadosoria** [comment]
closed in favor of #6815 @sachinraja

**Pull request closed without merging**
