### PR TITLE
Update 500px

### PR DESCRIPTION
**Pull request by mondeja**
500px

**Issue:** #3169
**Alexa rank:** [~51k](https://www.alexa.com/siteinfo/500px.com)

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Updated to fit the canvas width, optimized to 3 decimals with SVGO.

### CODE REVIEW

**Comment by runxel** [comment]
> Also, @simple-icons/maintainers, do we remove the 500px icon from [.svglint-ignored.json](https://github.com/simple-icons/simple-icons/blob/995f2c94deda4234737ccde317d76179eb78dd16/.svglint-ignored.json) in this PR or do we delegate that to our future selves?

I would already do it here. Otherwise it's just too easy to lose overview.


Also good work, @mondeja! 👍

**Comment by mondeja** [comment]
Sorry for the inconvenience. It's fixed now.

**Comment by PeterShaggyNoble** [comment]
> I would already do it here.

I'd say the opposite, to save the work: leave them until we get through them all and then just remove them all at once.

**Comment by ericcornelissen** [comment]
> https://docs.google.com/document/d/1ZTVW7mf7E_YZHkWzVRfxaMfQcrNvodAafpx7ZTD6Qds/edit

Yes I think I agree. Initially I asked because I thought that 500px would be ignored until removed, but when I removed it from the list I remembered we designed it such that that's not the case. Luckily it doesn't hurt that we removed it here :smile:

**Pull request merged**
