### PR TITLE
CD Projekt (#2181)

### LINKED ISSUE #2181: CD Projekt (game developer company)
**Name:** CD Projekt 
**Website:** https://www.cdprojekt.com/
**Official resources for icon and color:** 

* https://www.cdprojekt.com/en/media/logotypes/ 
* [There is another convenient SVG found in the header](https://www.cdprojekt.com/en/wp-content/themes/cdprojekt/assets/images/CDProjekt-Black.svg) but I think it is more appropriate to get the source in the given media link. 
* Suggested brand color is `#DB0D15` extracted from the SVG. 
  

Alexa ranking: [~292k](https://www.alexa.com/siteinfo/cdprojekt.com)

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
closes #2181

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG made out of Illustrator file which can be downloaded on their site.
Color `#DC0D15` is from the brand guide.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Nice work, @runxel.

However, following [my comments](https://github.com/simple-icons/simple-icons/pull/2261#issuecomment-570806095) about Potrace, which was used to generate the icon I linked to in #2181, I'm no longer fully convinced that the completely filled bird is the way to go here. What do the other @simple-icons/maintainers think?

**Comment by ericcornelissen** [comment]
> Color `#DC0D15` is from the brand guide.

Where in the brand guidelines did you find this @runxel? Asking as it doesn't match with, but is close to, the color from the SVG linked in #2181 `#DB0D15`.


> However, following my comments about Potrace, which was used to generate the icon I linked to in #2181, I'm no longer fully convinced that the completely filled bird is the way to go here.

I think that has mostly to do with the quality of the SVG. As for which parts of the logo should be solid or not, I think it is still a valid source. Agreed @PeterShaggyNoble?

**Comment by runxel** [comment]
> Where in the brand guidelines did you find this @runxel? Asking as it doesn't match with, but is close to, the color from the SVG linked in #2181 `#DB0D15`.

If you download the logo set on the [page](https://www.cdprojekt.com/en/media/logotypes/) there is a PDF included with the brand guide.

**Comment by ericcornelissen** [comment]
> If you download the logo set on the page there is a PDF included with the brand guide.

Okay thanks, didn't expect there to be a PDF in there 😅 Then I'll wait for @PeterShaggyNoble response before merging this in 🙂

**Comment by PeterShaggyNoble** [comment]
Looks good, @runxel, nice work 👍

As there was a bit of back & forth, I'll leave it to one of the other @simple-icons/maintainers to double check everything before we merge this in.

**Pull request merged**
