### PR TITLE
Update Open Source Initiative icon

### LINKED ISSUE #5277: Update Open Source Initiative icon
**Brand Name:**  Open Source Initiative
**Official resources for icon and color:**

- https://opensource.org/logo-usage-guidelines

According to their [guidelines](https://opensource.org/logo-usage-guidelines#Trademark_Symbol), we should add the Trademark symbol (`®`) for this icon.

> The 'TM' or ® trademark symbol as determined by OSI must always be visible and readable for both the OSI Logo in the placements shown in these guidelines. You may not remove or obfuscate either of the TM or ® symbols in the OSI Logo.

image

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** Close #5277
**Alexa rank:**
  

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I took the SVG logo found at https://opensource.org/logo-usage-guidelines
- I used Inkscape to scale
  - I created a new `R` symbol to fit the one found in the picture 1.1.3.
- I optimized it

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Which file did you base your version off, @service-paradis? I'm seeing some small differences when comparing it to [this one](https://opensource.org/files/OSI_Keyhole.svg) (from [this page](https://opensource.org/node/442)).

I think the positioning of the trademark symbol works a bit better in that source version as it allows for the icon itself to be vertically centred on the canvas.

**Comment by service-paradis** [comment]
I used https://opensource.org/files/OSI_Standard_Logo.svg as the source and I positioned the `R` symbol according to https://opensource.org/files/osi_symbol_0.png.

Totally missed the source you linked 🤦‍♂️ 
I will start this one again soon. Thank you for the review!

**Comment by service-paradis** [comment]
I gave this another try
image

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @service-paradis 🎉

**Pull request merged**
