### PR TITLE
updating sourcegraph icon

### PR DESCRIPTION
**Pull request by jorgeamadosoria**
sourcegraph
**Issue:** https://github.com/simple-icons/simple-icons/issues/6141

hex and sources remain the same.

### CODE REVIEW

**Review by service-paradis — CHANGES_REQUESTED** [review]
Thank you @jorgeamadosoria for your contribution!

Which file did you use as source? I used `Sourcegraph Brand Kit 2.2 - May 2021/Logos/Star Logomark/SVG/Sourcegraph_Logomark_BLK.svg` from the ZIP file to compare.
There are some differences. For example, the top left bar:
image

There are also some extra segments that could be removed. Ex.
image

By using `Union` instead of `Combine`, it will probably produce less of those.

Can you gave this another try?

**Comment by jorgeamadosoria** [comment]
> Thank you @jorgeamadosoria for your contribution!
> 
> Which file did you use as source? I used `Sourcegraph Brand Kit 2.2 - May 2021/Logos/Star Logomark/SVG/Sourcegraph_Logomark_BLK.svg` from the ZIP file to compare.
> There are some differences. For example, the top left bar:
> image
> 
> There are also some extra segments that could be removed. Ex.
> image
> 
> By using `Union` instead of `Combine`, it will probably produce less of those.
> 
> Can you gave this another try?

source remained the same.

**Comment by service-paradis** [comment]
> source remained the same.

Just wanted to know which file from the Zip file did you use. To be sure I compare your icon with the same version you used. As mentioned above, I used `Sourcegraph Brand Kit 2.2 - May 2021/Logos/Star Logomark/SVG/Sourcegraph_Logomark_BLK.svg` to compare and I got some differences.

**Comment by service-paradis** [comment]
@jorgeamadosoria Do you still want to work on this?

**Pull request closed without merging**
