### PR TITLE
Add Apache Freemarker

### LINKED ISSUE #9470: Add Apache Freemarker
### Brand Name

Freemarker

### Website

https://freemarker.apache.org

### Popularity Metric

Not sure about the  similarweb ranking as it is part of apache.org

### Official Resources for Icon and Color

https://apache.org/logos/#freemarker

### Additional Comments

Apache FreeMarker™ is a template engine: a Java library to generate text output (HTML web pages, e-mails, configuration files, source code, etc.) based on templates and changing data. 
Very useful tool for dynamic file generation.

### Contributing

Yes

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
apachefreemarker

**Issue:** closes #9470 

**Similarweb rank:** Not sure

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from https://www.apache.org/logos but modified to look like the favicon on https://freemarker.apache.org
I overlaid the SVG on top and tried to match it the best I can.
Color: Taken from logo `#326CAC`

### CODE REVIEW

**Comment by adamrusted** [comment]
@service-paradis - why did you mark this one as pending? Is there an ongoing discussion?

**Comment by PratyushJayachandran** [comment]
> @service-paradis - why did you mark this one as pending? Is there an ongoing discussion?

Discussion on #9470

**Comment by PeterShaggyNoble** [comment]
@PratyushJayachandran, do they use this icon anywhere else other than for their website's favicon?

**Comment by adamrusted** [comment]
To answer your question @PeterShaggyNoble - they use `<F>` as their Twitter icon, but otherwise it's the full wordmark. I'd say given how we've handled other Apache projects we should probably use the apache.org/logos variant as our 'source of truth'.

**Comment by PeterShaggyNoble** [comment]
@PratyushJayachandran, could you update to use the full logo, please?

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
@PratyushJayachandran, could you update to use the full logo, please?

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran, could you update to use the full logo, please?

I am awaiting some response on this one from freemarker. I will update as soon as I get that.

**Comment by PratyushJayachandran** [comment]
apachefreemarker2
Updated

**Review by adamrusted — APPROVED** [review]

**Pull request merged**
