### PR TITLE
Added zustand Icon

### LINKED ISSUE #7847: Request: Zustand
### Brand Name

Zustand

### Website

https://github.com/pmndrs/zustand

### Popularity Metric

21.9k stars in Github

### Official Resources for Icon and Color

the symbol is a bear but it seems don't have main color 

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by Sarveshk76**
**Issue:** closes #7847 #10007

**Similarweb rank:**

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by adamrusted** [comment]
Thanks for the contribution @Sarveshk76 - though it looks like (from the code submitted) the SVG just includes an embedded Base64 encoded PNG, which we cannot accept. Please ensure that the SVG you submit contains a single `<path>` element, as per our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#2-extract-the-icon-from-the-logo).

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
@Sarveshk76, as above, the structure of the SVG file is still not correct. It should contain a `title` element and a single `path` element _only_ and the `path` element should only have the `d` attribute. The required structure is as follows:

```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>[BRAND]</title><path d="[PATH]"/></svg>
```

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
@Sarveshk76, the linting is now failing due to the precision being too high when optimising; the _maximum_ we allow is 5 decimal places.

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @Sarveshk76? And are you attempting to manually vectorise the image at the source URL or did you find a vector file to work from?

**Comment by service-paradis** [comment]
No answer for a month, closing this one. Feel free to reopen this PR @Sarveshk76 if you still want to work on this!

**Pull request closed without merging**
