### PR TITLE
Add Segment

### PR DESCRIPTION
**Pull request by axe312ger**
segment

**Issue:** none
**Alexa rank:** 6,405

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Was segment.io before and is now part of Twilio

Got all information from https://brand.segment.com/

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks for your work on this @axe312ger, looks like it's failing the linter stage. Could you look at re-exporting / optimizing the icon to a precision of 4, see if that fixes it?

**Comment by axe312ger** [comment]
Damn, a precision of 2 was enough :(

**Comment by adamrusted** [comment]
Hi @axe312ger - not sure why the linter's failing, but it looks like you've optimized to 2 decimals again. It may need you to start the icon from scratch, and export to 3 decimals initially, and we can review from there :+1:

**Comment by axe312ger** [comment]
Alright ok :D

**Comment by axe312ger** [comment]
Lets try again

**Comment by axe312ger** [comment]
Hmm, how to center it properly? Its more higher as wide 🤔

**Comment by PeterShaggyNoble** [comment]
Your software should have a tool to do that for you, @axe312ger; in Inkscape it's called "Align & Distribute" and can be found in the "Object menu" - "Center on vertical axis" and "Center on horizontal axis" will do the job for you.

**Comment by axe312ger** [comment]
I use Figma and it aligns it always to the left, damn :D

**Comment by PeterShaggyNoble** [comment]
Pinging @adamrusted for assistance here as I think he's familiar with Figma.

**Comment by adamrusted** [comment]
Hey @axe312ger - so I use a frame in Figma that's fixed to 24x24px and make sure the icon is centered within that frame. If you then export the frame as an SVG instead of the icon, that should fix alignment. 🤞

**Comment by axe312ger** [comment]
@adamrusted will try to manually center. Figma always moves it to the left

**Comment by axe312ger** [comment]
Pixel grid snapping was the issue. Lets see if the linter likes this icon :)

**Comment by axe312ger** [comment]
I think centering is now fine, but, as soon I put the icon into svgomg it changes the dimension, very slightly:

icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 22.964 x 24.004

Figma says `24` px width :/

**Comment by adamrusted** [comment]
Yeah, SVGO can sometimes alter the image size if the optimized path would have gone out of bounds. I'll take a look at this one this morning though, as 4 decimals should be passing it.

**Review by adamrusted — CHANGES_REQUESTED** [review]
I'm spotting a [slight difference](https://user-images.githubusercontent.com/1830867/116809124-84d2f900-ab34-11eb-80e6-700ec17c5a55.png) between the top-right circle on your PR (red) and source (black). Generally, this is just a precision issue when the icon's been fixed in SVGO - so you may be able to fix that by dragging the point to match in your vector software. Could you take another look at this one please @axe312ger?

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @axe312ger?

**Comment by axe312ger** [comment]
To be honest, I got the SVG directly implemented in my project, and my customer won't pay me to do another adjustment to this PR. 

I tried it multiple times, I code, I don't design. Probably this super precise SVG task is out of my skillset.

 I would close this now, no more need on my side, if others want to continue, or Segment.io itself, feel free to.

**Comment by adamrusted** [comment]
If you don't mind, @axe312ger - rather than closing this out as abandoned, I'll look to continue your work on this PR. May need to rebuild from source, but means you get the attribution then 👌

**Comment by axe312ger** [comment]
@adamalston Thanks a lot!

The original logo and brand infos are still online at the link in the opening issue.

**Comment by adamrusted** [comment]
I've just pushed my version to this branch, if another @simple-icons/maintainers could take a look at it?

**Comment by PeterShaggyNoble** [comment]
I'm seeing a hairline thin difference around some of the edges, @adamrusted ([example](https://user-images.githubusercontent.com/15157491/122432448-3adf8e80-cf8d-11eb-87d3-91f3ddf1c44e.png), with yours in red), which may just be a precision issue. We should probably also duplicate the `source` as the `guidelines` in the JSON. And should we not go with "Dark Acai" (`#1C0732`) for the colour, as it's [listed first](https://brand.segment.com/#link-color) and used pretty extensively on [their website](https://segment.com/)?

**Comment by ericcornelissen** [comment]
@adamrusted, did you have a change to work on an updated based on Peter's feedback?

**Comment by adamrusted** [comment]
> @adamrusted, did you have a change to work on an updated based on Peter's feedback?

Yeah, sorry @ericcornelissen. Started a new job this week and thought I'd have more time to contribute. Apparently not. Feel free to close this, unless anyone else wants to continue this one.

**Comment by ericcornelissen** [comment]
No problem @adamrusted - given that I'll close this Pull Request as abandoned. Feel free to reopen if you decide to continue working on this.

If anyone else wants to see this icon in the collection, please feel free to use this Pull Request as a starting point! If you don't think you'll be able to create a Pull Request, but would like to see it included, do consider opening [a new issue](https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=new+icon&template=icon_request.md) for Segment to increase visibility.

**Pull request closed without merging**
