### PR TITLE
Update Roblox icon

### LINKED ISSUE #8313: Update Roblox logo
### Brand Name

Roblox

### Official Resources for Icon and Color

SVG Icon: (stored on website as vector data, not direct link)
data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTYiIGhlaWdodD0iNTYiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTExLjY3NiAwTDAgNDQuMTY2IDQzLjU3NyA1NmwxMS42NzYtNDQuMTY2TDExLjY3NiAwem0yMC40MDkgMzUuODI3bC0xMi4xNzctMy4zMDggMy4yNjQtMTIuMzQyIDEyLjE4MiAzLjMwOC0zLjI3IDEyLjM0MnoiIGZpbGw9IiMzOTNCM0QiLz48L3N2Zz4=

Color:
#FFFFFF (for dark backgrounds, primary branding color)

### Additional Comments

The color of the logo can sometimes vary between sites and company documents. For example, if their light theme is turned on (default to light theme when not logged into an account), the logo appears as #393b3d. And on some documents their logo appears as #000000 on white documents. However, across their brand on parts like their corporate website (corp.roblox.com), the color seems to consistently be #FFFFFF.

Roblox does not have a press kit that I can find which contains this new logo, so the vector data that I sent above will go to a direct link for the logo. This is the way that it's stored on their website, compared to their wordmark which is stored on their CDN 

### Contributing

Yes

### PR DESCRIPTION
**Pull request by RyanLua**
roblox

**Issue:** closes #8313

**Similarweb rank:** [35](roblox.com)
  

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

Update the icon to use the new Roblox logo as mentioned in this blog post from Roblox on "[Our Refreshed Logo](https://blog.roblox.com/2022/08/our-refreshed-logo/)", with the current logo, used in Simple Icons, being the 2018-2022 logo. This pull request updates it to the present one. I kept the same `000000` hex color as it still remains the same brand color from [The Roblox Brand Guidelines](https://d5m0vnpvja3z4.cloudfront.net/assets/blt17b54e1557ae1c23/Roblox_Brand_Guidelines_-_Logo.pdf). I took the SVG from [roblox.com/home](https://www.roblox.com/home)'s HTML as a path, unfortunately I could not find the direct URL to just the SVG to use as source so it has been updated to the full logo's link.

The present logo has a larger hole in the "O", which the current one lacks so this pull request will correct it to the present logo.

image

### CODE REVIEW

**Comment by LitoMore** [comment]
CleanShot 2023-05-22 at 13 34 54@2x

@RyanLua I can see some differences. The expected size should be:

CleanShot 2023-05-22 at 13 36 01@2x

But yours:

CleanShot 2023-05-22 at 13 36 13@2x

Please make sure the picture is not stretched.

**Comment by RyanLua** [comment]
> CleanShot 2023-05-22 at 13 34 54@2x
> 
> @RyanLua I can see some differences. The expected size should be:
> 
> CleanShot 2023-05-22 at 13 36 01@2x
> 
> But yours:
> 
> CleanShot 2023-05-22 at 13 36 13@2x
> 
> Please make sure the picture is not stretched.

For clarification it should be 23.997 pixels for the height? Just want to make sure.

**Comment by LitoMore** [comment]
@RyanLua Yes. The original icon is not an actual square.

Please make sure to enable the proportion lock when resizing.

**Comment by RyanLua** [comment]
Should be fixed. For some reason I got the below result with proportion lock.

image

**Comment by LitoMore** [comment]
@RyanLua It should be `24 x 23.997`.

https://github.com/simple-icons/simple-icons/assets/8186898/ea46bf41-b438-4350-a610-aeeb8e5722c1

**Comment by RyanLua** [comment]
> @RyanLua It should be `24 x 23.997`.
> 
>  Kapture.2023-05-24.at.06.06.36.mp4 
> I took the SVG from [roblox.com/home](https://www.roblox.com/home) as you mentioned in the description.

@LitoMore That's quite odd.

I just zoomed in around 250% on [the support page](https://www.roblox.com/support) which until it showed the truncated "O" variation of the logo. Saved the svg from the website and then scaled it down from there. 

I maybe should have mentioned that step before. I showed it on the support page as you don't need to be logged into Roblox to get the different variant of the Roblox logo. They could just be using a different "O" for the full and single variant of the logos.

---

The shortened logo between the home and support are the exact same except for maybe color for dark and light themes.

image

How I scaled the logo and sourced it:

https://github.com/simple-icons/simple-icons/assets/80087248/f2ecdf20-44ca-4190-b072-982ade2b1d0c

https://github.com/simple-icons/simple-icons/assets/80087248/cdcd1df0-f16a-4f74-85bf-a8081be1dd88

**Comment by LitoMore** [comment]
@RyanLua OK, please share the SVG file that you're using. I will use yours as a reference.

**Comment by RyanLua** [comment]
> @RyanLua OK, please share the SVG file that you're using. I will use yours as a reference.

Here are the files from the Roblox site, unedited. Both light and dark theme variants.

robloxref
robloxref2

**Pull request merged**
