### PR TITLE
Add React Hook Form icon

### PR DESCRIPTION
**Pull request by jsun969**
reacthookform

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
React Hook Form is a popular form lib for react to improve UX.
Github: https://github.com/react-hook-form/react-hook-form (over 29k stars)
Website: https://react-hook-form.com/

I am the author of react hook form devtools browser extension

### CODE REVIEW

**Comment by bluebill1049** [comment]
thanks for adding this icon. 👍

**Review by sisp — COMMENTED** [review]
Thanks for your contribution, @jsun969! :pray:

There's a small but notable difference at the ring at the top of the icon:


With a precision of 3 decimal places, there were significantly more differences because of the several arcs which are often difficult to draw accurately with reduced precision. Now with a precision of 4 decimal places, only the ring at the top is a bit off though not by much. @sachinraja Do you think this is sufficiently close to the original icon?

**Comment by sachinraja** [comment]
Yes I think it's fine if it's difficult to fix.

**Comment by jsun969** [comment]
> Thanks for your contribution, @jsun969! 🙏
> 
> There's a small but notable difference at the ring at the top of the icon: 
> 
> With a precision of 3 decimal places, there were significantly more differences because of the several arcs which are often difficult to draw accurately with reduced precision. Now with a precision of 4 decimal places, only the ring at the top is a bit off though not by much. @sachinraja Do you think this is sufficiently close to the original icon?

I think it's quite difficult to fix. That's why I update the icon twice to pass lint🤔

**Comment by jsun969** [comment]
thx a lot 🎉 @sisp

**Pull request merged**
