### PR TITLE
Add BMW logo

### PR DESCRIPTION
**Pull request by el1f**
**Issue:** #2059 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Toke the logo from the Wikipedia page for BMW (which is the same used by Wikimedia and by BMW itself, even if in form of a PNG on their website).
I went for the traditional BMW blue for the color and I've taken it from their logo.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
After a bit of digging, I found an official EPS [here](https://www.bmwgroup-classic.com/en/bmw-clubs/downloadbereich.html#other.), if you want to compare it to your file.

I also found [this file](https://www.bmwgroup-classic.com/content/dam/grpw/websites/bmwgroup-classic_com/bmw_clubs/downloads/sonstiges/bmw_clubs_guideline_apparel_english_20171212.pdf), which includes details on 2 options for the monochrome logo as well as some Pantone refs. for their colours.

**Comment by birjolaxew** [comment]
Based on the files linked by @PeterShaggyNoble, I think I would expect either the black-on-light version, which has an extra ring outside of the "BMW" ring, or (preferably) the white-on-dark version which doesn't require much interpretation.

Unfortunately I couldn't find a vector version (the ones linked by @PeterShaggyNoble are for the BMW Clubs), but a reference logo can be seen in the photos attached to [this press release](https://www.press.bmwgroup.com/global/article/detail/T0274134EN/beyond-driving-pleasure:-innovative-luxury-bmw-style?language=en) (and related articles from other news outlets)

image

**Comment by el1f** [comment]
Is it just me or is the "BMW" lettering different in every single incarnation of the logo?
Here is the latest update. Lettering ripped from the PDF linked by @PeterShaggyNoble, shapes traced based on the bitmap by @birjolaxew

simple-icons

**Comment by ericcornelissen** [comment]
Closing this as work seems to have stopped. If you want to continue working on this @el1f feel free to re-open! :smile: 

And to anyone else, feel free to use this PR as a resource when adding the BMW logo.

**Comment by el1f** [comment]
Sorry for the disappearance guys. Been busy working on some other projects and had little time to open any design tools :)
Seems like @runxel already took up the task so I'll leave the rest to him.

**Pull request closed without merging**
