### PR TITLE
Updated Behance

### PR DESCRIPTION
**Pull request by fbernhart**
behance

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Compared to [source](https://www.behance.net/dev/api/brand) there are a couple of issues with your path. See the misalignment and sharp edge in the middle of the 'e'.

image

**Comment by fbernhart** [comment]
I've now rebuilt it using the upper left [EPS file](https://a5.behance.net/2acd763b00852cc6bd4375598dba21e22bfa71e3/img/dev/brand/poweredbybehance-logo-white-vertical.eps).

@adamrusted Please have another look at it. 👀

**Comment by adamrusted** [comment]
> I've now rebuilt it using the upper left [EPS file](https://a5.behance.net/2acd763b00852cc6bd4375598dba21e22bfa71e3/img/dev/brand/poweredbybehance-logo-white-vertical.eps).
> 
> @adamrusted Please have another look at it. 👀
> 
> Note: I couldn't get it through the linter with a precision of 3. I had to use 4 instead.

Looks spot on to me - just tried with precision of 3 on my end, and it's not passing the linter, so I'm happy to merge this if you can resolve the conflict for me please? 😅

**Comment by adamrusted** [comment]
I ***think*** I'm finally getting the hang of merging *(3 commits later)* - could another @simple-icons/maintainers look over this, just to make sure I've not broken anything before I merge?

**Comment by fbernhart** [comment]
LGTM! 🎉  Congratulations on solving the merge conflict yourself! 😊

**Pull request merged**
