### PR TITLE
Remove Koding

### PR DESCRIPTION
**Pull request by fbernhart**
koding

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
~~I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG~~

This PR is removing the Koding icon as per the discussion in #4129

### CODE REVIEW

**Comment by service-paradis** [comment]
I think the icon is outdated. I opened #4129 to discuss about it.

**Review by mondeja — COMMENTED** [review]
@fbenhart, can you remove the icon in this pull as has been discussed in #4129, so in v5 release we need only to merge this pull?

**Comment by fbernhart** [comment]
@mondeja Done.

**Comment by PeterShaggyNoble** [comment]
OK, looks like we have a consensus on a secondary cut-off of 750k for brands that have already been added, allowing us to keep this one based on its current rank of ~630k.

However, as there has been no activity in the blog, on their social media or in their GitHub repos for years and their primary repo has been archived, I think we're safe enough to make a judgement call that this is no longer a going concern and can be removed. This is aided by the precedent being set by the removal of Vine earlier today, which had a much healthier rank.

If we _do_ decide to keep it then the icon and colour will need to be updated.

**Comment by ericcornelissen** [comment]
I'd be inclined to say we should remove this as the hosted service has been discontinued ([ref 1](https://github.com/koding/koding/issues/11518), [ref 2](https://user-images.githubusercontent.com/3742559/119560957-df165100-bda4-11eb-8c62-6d55bb67d0d1.png)) and [the open source project](https://github.com/koding/koding) has been archived. On the other hand, as the Alexa rank is still okay-ish, at least in the context of #4735, we should maybe just keep it for one more release - there's no real harm in that either.

**Review by adamrusted — COMMENTED** [review]
While I agree that this _should_ be removed due to the repo being archived, and their services being shut down, the fact that the Alexa rank is still relatively high would suggest it's still popular. Think waiting until v6 is our best bet.

**Comment by ericcornelissen** [comment]
@fbernhart can you look into updating this Pull Request?

**Review by ericcornelissen — COMMENTED** [review]
Following https://github.com/simple-icons/simple-icons/pull/5775, I'm actually not sure if we should merge this given that the Alexa rank of [`koding.com` is still at ~540k](https://www.alexa.com/siteinfo/koding.com).

It does seem the icon needs to be updated if we decide to keep it.

**Comment by sachinraja** [comment]
Considering the repo is archived and our icon is outdated, I think it should just be removed.

**Comment by jorgeamadosoria** [comment]
This raiaes a good question: is Simple Icons a library of only currently extant icons? Just because a brand doesn't exist anymore, does that means that the brand is no longer relevant in any way for users?

For example, my personal case: if the applications I've made that use certain technologies' icons are updated to the latest version, am I in danger of errors because a popular technology I used a while back is no longer actively developed?

I think this should be removed, but the SVG file should be frozen elsewhere for direct download, at least. 
The icon should remain accesible to users in some form to reduce backward compatibility issues, specially in cases like this where the brand may be out, but its popularity is still strong

**Comment by sachinraja** [comment]
I think you have a very valid point @jorgeamadosoria. But I don't think we should keep such icons in the main package. I think it'd be great if we could publish these "deprecated, but still used" icons in separate packages (`@simple-icons/deprecated-icon`) instead of in the main package.

**Comment by service-paradis** [comment]
I think we should only keep existing icon as part of the active release. If someone really want to use a deprecated icon, they can still use an old version of Simple Icons. 

For example, HipChat have been removed in the latest release ([v5](https://github.com/simple-icons/simple-icons/releases/tag/5.0.0)). So, we're not able to get it using the current package (https://cdn.jsdelivr.net/npm/simple-icons@v5/icons/hipchat.svg), but we still can use it using the v4 (https://cdn.jsdelivr.net/npm/simple-icons@v4/icons/hipchat.svg).

**Comment by jorgeamadosoria** [comment]
> .

I agree, that's my point. A separate repoaitory without all the bells and whistles of the main repo

**Comment by jorgeamadosoria** [comment]
> I think we should only keep existing icon as part of the active release. If someone really want to use a deprecated icon, they can still use an old version of Simple Icons. 
> 
> For example, HipChat have been removed in the latest release ([v5](https://github.com/simple-icons/simple-icons/releases/tag/5.0.0)). So, we're not able to get it using the current package (https://cdn.jsdelivr.net/npm/simple-icons@v5/icons/hipchat.svg), but we still can use it using the v4 (https://cdn.jsdelivr.net/npm/simple-icons@v4/icons/hipchat.svg).

That's not a sufficient solution, however. 
It would mean that I need to eother use two versions of the library or be stuck with an old version. 

Old icons shouldn't be in the main repo, but they should be somewhere. Even if only as a svg file to be downloaded

**Comment by mondeja** [comment]
I'm inclined to move this removal to v7. Do you agree @simple-icons/maintainers?

> Old icons shouldn't be in the main repo, but they should be somewhere. Even if only as a svg file to be downloaded

You can download old icons using the CDN link format that @service-paradis has shared https://cdn.jsdelivr.net/npm/simple-icons@v4/icons/hipchat.svg

**Comment by ericcornelissen** [comment]
> Considering the repo is archived and our icon is outdated, I think it should just be removed.

I'm unfamiliar with the brand, but it could just be that they moved to closed source.


> This raiaes a good question: is Simple Icons a library of only currently extant icons? Just because a brand doesn't exist anymore, does that means that the brand is no longer relevant in any way for users?

While it's fine to have that discussion, as of this Pull Request this is an established process. Approximately every 6 months there's a major release that removes SVGs of [brands that no longer exist](https://github.com/simple-icons/simple-icons/blob/4c7b870af642100233547ea56f7c6b1feaf550cc/VERSIONING.md) as well as SVGs for [brands that are not popular enough anymore](https://github.com/simple-icons/simple-icons/blob/4c7b870af642100233547ea56f7c6b1feaf550cc/CONTRIBUTING.md?plain=1#L46). If anyone wants to change that, it's best to have a discussion about that separate from this Pull Request. If there's consensus amongst @simple-icons/maintainers that we should discuss it prior to releasing [v6](https://github.com/simple-icons/simple-icons/milestone/5) than that consensus should be reached soon as that release is currently planned for November 28, 2021.

**Comment by sachinraja** [comment]
Looks like they just took down the hosted version. If you go to the [login page](https://www.koding.com/login/), it tells you that the hosted version has been discontinued and you can only self-host now. But the self-hosted version is just the https://github.com/koding/koding repo, which is archived. None of the repos in the koding org show any activity, so I think it's safe to say the brand no longer exists.

**Comment by jorgeamadosoria** [comment]
> > Considering the repo is archived and our icon is outdated, I think it should just be removed.
> 
> I'm unfamiliar with the brand, but it could just be that they moved to closed source.
> 
> > This raiaes a good question: is Simple Icons a library of only currently extant icons? Just because a brand doesn't exist anymore, does that means that the brand is no longer relevant in any way for users?
> 
> While it's fine to have that discussion, as of this Pull Request this is an established process. Approximately every 6 months there's a major release that removes SVGs of [brands that no longer exist](https://github.com/simple-icons/simple-icons/blob/4c7b870af642100233547ea56f7c6b1feaf550cc/VERSIONING.md) as well as SVGs for [brands that are not popular enough anymore](https://github.com/simple-icons/simple-icons/blob/4c7b870af642100233547ea56f7c6b1feaf550cc/CONTRIBUTING.md?plain=1#L46). If anyone wants to change that, it's best to have a discussion about that separate from this Pull Request. If there's consensus amongst @simple-icons/maintainers that we should discuss it prior to releasing [v6](https://github.com/simple-icons/simple-icons/milestone/5) than that consensus should be reached soon as that release is currently planned for November 28, 2021.

this has nothing to do with the v6 release. Like I said, the icon can be removed regardless. The problem is to keep it accesible in some way.

**Comment by jorgeamadosoria** [comment]
> I'm inclined to move this removal to v7 because the Alexa Rank has not been fallen enough.
> 
> > Old icons shouldn't be in the main repo, but they should be somewhere. Even if only as a svg file to be downloaded
> 
> You can download old icons using the CDN link format that @service-paradis has shared https://cdn.jsdelivr.net/npm/simple-icons@v4/icons/hipchat.svg

this is good enough as hosting, but where is the discovery part? How is any end user suppose to know that exists?
It needs a note somewhere, or a page to host discontinued icons, or at least the links to the CDN.
I think this warrants a website ticket. I'll follow it up there.

**Comment by mondeja** [comment]
> this is good enough as hosting, but where is the discovery part? How is any end user suppose to know that exists?
It needs a note somewhere, or a page to host discontinued icons, or at least the links to the CDN.
I think this warrants a website ticket. I'll follow it up there.

I agree. A note could be added in [CDN usage section of README](https://github.com/simple-icons/simple-icons#cdn-usage), [deprecated section of VERSIONING.md](https://github.com/simple-icons/simple-icons/blob/develop/VERSIONING.md#deprecation) or even in both sides. Do you want to open an PR for that @jorgeamadosoria?

**Comment by mondeja** [comment]
> If you go to the [login page](https://www.koding.com/login/), it tells you that the hosted version has been discontinued and you can only self-host now. But the self-hosted version is just the https://github.com/koding/koding repo, which is archived. None of the repos in the koding org show any activity, so I think it's safe to say the brand no longer exists.

Given that, I'm not against to include this removal in v6 👍🏼

**Review by sachinraja — APPROVED** [review]

**Review by mondeja — APPROVED** [review]

**Comment by jorgeamadosoria** [comment]
> > this is good enough as hosting, but where is the discovery part? How is any end user suppose to know that exists?
> > It needs a note somewhere, or a page to host discontinued icons, or at least the links to the CDN.
> > I think this warrants a website ticket. I'll follow it up there.
> 
> I agree. A note could be added in [CDN usage section of README](https://github.com/simple-icons/simple-icons#cdn-usage), [deprecated section of VERSIONING.md](https://github.com/simple-icons/simple-icons/blob/develop/VERSIONING.md#deprecation) or even in both sides. Do you want to open an PR for that @jorgeamadosoria?

I opened a ticket on the website to add a page with the links to the website. I don't know if you think I should add a page there, or just an .md document with a list of discontinued icons in the documentation for the main repo.
I'm good with either approach. As long as the user can go somewhere visible and see the icons we removed in each release, that should be enough for them.

**Pull request merged**
