### PR TITLE
Updated Cinema 4D

### PR DESCRIPTION
**Pull request by fbernhart**
cinema4d

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by adamrusted** [comment]
Looks like the source URL has now changed - could you update to [this](https://www.maxon.net/en/about-maxon/branding) please?

**Comment by fbernhart** [comment]
@adamrusted Done

**Comment by adamrusted** [comment]
> @adamrusted Done

Looks like the only official logo is a PNG - I've imported the SVG in above it, and there seems to be some differences. Not sure if it's C4D changing their logo or whether our SVG wasn't quite accurate in the first place.

image

**Comment by mondeja** [comment]
It seems that [has been updated](https://aixsponza.com/work/cinema-4d-logo-redesign/).

**Comment by fbernhart** [comment]
Ufff ... that was quite some work. But I think it was worth it! Comparing it with the source (`CINEMA_4D_byMAXON_DS_RGB.eps`) now:

image


I've made the separation gaps slightly thinner (0.35px). What do you think?

**Review by adamrusted — APPROVED** [review]
LGTM! 💪🏻

**Pull request merged**
