### PR TITLE
Add StackBlitz icon

### LINKED ISSUE #7681: StackBlitz
### Brand Name

StackBlitz

### Website

https://stackblitz.com

### Popularity Metric

At time of writing:

Global Rank: `#22,275`\
Country Rank: `#7,327`

https://similarweb.com/website/stackblitz.com

### Official Resources for Icon and Color

~~https://developer.stackblitz.com/docs/guide/open-from-github/#the-open-in-stackblitz-button~~

The logo on the homepage https://stackblitz.com

`#1269D3`

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by LitoMore**
CleanShot 2022-09-02 at 17 12 54@2x

**Issue:** closes #7681  
**Similarweb rank:** [23,511](https://www.similarweb.com/website/stackblitz.com/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Difference preview

CleanShot 2022-09-02 at 17 19 33@2x

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @LitoMore,

I see a differences to the original svg.

image

btw: I use the svg from the link in the issue -> https://developer.stackblitz.com/img/open_in_stackblitz.svg

**Comment by LitoMore** [comment]
@dirien I used the icon from the logo on the homepage https://stackblitz.com. I think we should use the one on homepage as standard.

**Comment by dirien** [comment]
@LitoMore ok cool! I just checked the description of the issue with the location of the svg! 

Will re-review the PR later!

**Review by dirien — APPROVED** [review]
Hi @LitoMore ,


It's a perfect fit:
image

**Comment by janosh** [comment]
@LitoMore Thanks! How long do new icons usually take to go live on the website?

**Comment by LitoMore** [comment]
@janosh We will create a release on Sunday: https://github.com/simple-icons/simple-icons/blob/develop/.github/workflows/create-release.yml#L7.

https://github.com/badges/shields.io will create a PR to update the simple-icons to latest on Friday: https://github.com/badges/shields/blob/master/.github/dependabot.yml#L8. But it will [take a few days for them to merge](https://github.com/badges/shields/pull/8365).

You could refer to this topic: https://github.com/badges/shields/discussions/5369.

**Pull request merged**
