### PR TITLE
(feat) Icon: React Query

### PR DESCRIPTION
**Pull request by Progyan1997**
Signed-off-by: Progyan Bhattacharya <bprogyan@gmail.com>

**Issue:** https://github.com/simple-icons/simple-icons/issues/6159
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by adamrusted** [comment]
Hey @Progyan1997 - thanks for the submission! When submitting a PR, could you please create a preview image using the icon details at [this page](https://petershaggynoble.github.io/SI-Sandbox/preview/) and include that when opening a PR? It helps us maintainers identify any glaring issues before we dive into the SVG content!

**Review by sachinraja — CHANGES_REQUESTED** [review]
image
Noticing some differences along the edges, you may want to try optimizing with a higher precision.

**Comment by Progyan1997** [comment]
@sachinraja I believe I am having highest precision allowed by the linter and sharing same with `react-table`.
@adamrusted Here is the screenshot:
image

**Review by sachinraja — APPROVED** [review]
I may have been checking against the wrong file for the logo, this is actually a perfect match :+1:

**Pull request merged**
