### PR TITLE
Add BP & Mattel to Our "Won't Add" List

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
**Issue:** ref #5849 & #6656

### Description
Adds BP & Mattel to the list of companies in [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) that we cannot add icons for.

### CODE REVIEW

**Comment by service-paradis** [comment]
If doing so, we'll need to remove Uno in the next breaking release:
https://simpleicons.org/fr/?q=uno

**Comment by adamrusted** [comment]
We could also do with updating the auto-closer logic to include some of these, as well as 'Java'.

**Comment by adamrusted** [comment]
> It will be kind of difficult for Mattel products

Good luck RegEx-ing [this lot](https://corporate.mattel.com/brand-portfolio)

**Comment by PeterShaggyNoble** [comment]
Added BP to this PR in light of https://github.com/simple-icons/simple-icons/issues/5849#issuecomment-1836439819

**Pull request merged**
