### PR TITLE
add vite icon

### PR DESCRIPTION
**Pull request by stefanobartoletti**
vite

**Issue:**
**GitHub Stars:** 23K +
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I adapted the original SVG logo, the color comes from their website. 
Not sure if you like how I adapted it with an outlined part, let me know if you need something different

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Nice job @stefanobartoletti!
I think given that both shapes are filled in the original icon, we should try and maintain that where possible. We do allow for a 0.5pt line between shapes to differentiate between colours, so something like the below would also work (and might make the triangle a bit more readable?). I've included my un-optimized 4 decimal path, if you'd prefer to use that.

vite
```svg
M8.2857,10.5778l0.5126-8.6569C8.8066,1.7816,8.908,1.6655,9.0449,1.6387l8.3326-1.6328C17.3979,0.0019,17.4181,0,17.4378,0 	c0.1971,0,0.3502,0.191,0.2926,0.391l-1.5586,5.403c-0.0577,0.1999,0.0954,0.391,0.2926,0.391c0.0194,0,0.0392-0.0018,0.0594-0.0057 	l2.3879-0.4609c0.0205-0.004,0.0406-0.0058,0.0602-0.0058c0.2191,0,0.3757,0.235,0.2714,0.4433l-6.7899,13.5504l-0.1229,0.1899 	c-0.0637,0.0984-0.1581,0.1411-0.2516,0.1411c-0.1766,0-0.3497-0.1523-0.3049-0.3692l1.0953-5.3015 	c0.0406-0.1963-0.1129-0.3683-0.2986-0.3683c-0.0294,0-0.0596,0.0043-0.09,0.0135l-1.4329,0.4354 	c-0.0304,0.0092-0.0606,0.0135-0.09,0.0135c-0.1854,0-0.3387-0.1715-0.2987-0.3676l0.6893-3.3751 	c0.0397-0.1945-0.1116-0.3674-0.2986-0.3674c-0.0229,0-0.0463,0.0026-0.0699,0.0081L8.6599,10.894 	c-0.0234,0.0054-0.0467,0.0079-0.0695,0.0079C8.4196,10.902,8.2751,10.7576,8.2857,10.5778z M23.2617,2.6515L17.2844,3.741 	L16.74,5.6283l2.077-0.4008c0.0527-0.0102,0.1045-0.0149,0.155-0.0149c0.2801,0,0.5358,0.1434,0.6841,0.3835 	c0.1476,0.2391,0.1605,0.5322,0.0344,0.7838l-6.7899,13.5504l-0.0123,0.0245l-0.0149,0.0231l-0.1229,0.1899 	c-0.1497,0.2314-0.4007,0.3694-0.6714,0.3694c-0.244,0-0.4812-0.1124-0.6346-0.3008c-0.1512-0.1856-0.2095-0.4297-0.16-0.6696 	l1.0293-4.9818l-1.1205,0.3405c-0.0767,0.0233-0.1559,0.0351-0.2353,0.0351c-0.2422,0-0.4696-0.1083-0.6238-0.2972 	c-0.1534-0.1879-0.2134-0.4323-0.1648-0.6704l0.6288-3.0794l-2.026,0.4676C8.7125,11.395,8.6513,11.402,8.5905,11.402 	c-0.2205,0-0.4341-0.0924-0.5861-0.2535c-0.1514-0.1607-0.2308-0.3795-0.2178-0.6002l0.389-6.5699L0.7362,2.6486 	C0.2253,2.5573-0.1601,3.1033,0.0969,3.5541l11.4832,20.1371c0.236,0.4137,0.8332,0.4112,1.0657-0.0045L23.9056,3.5522 	C24.1581,3.1005,23.7709,2.5587,23.2617,2.6515z
```

**Comment by stefanobartoletti** [comment]
Updated, I used your path as a base.

**Comment by adamrusted** [comment]
Could another @simple-icons/maintainers please review this one, as I contributed the path to it? 🙏

**Comment by PeterShaggyNoble** [comment]
SVG looks good to me. For the colour, though, I would expect `#646cff` which is the value of the `--c-brand` variable in their website's stylesheet.

**Comment by stefanobartoletti** [comment]
Thank you, I have updated the color

**Comment by PeterShaggyNoble** [comment]
Thanks for you work on this one, @stefanobartoletti, and for your assistance, @adamrusted 👍🏻

**Pull request merged**
