### PR TITLE
Add Fuga Cloud icon

### PR DESCRIPTION
**Pull request by dirien**
image

**Issue:** #7134 
**Alexa rank:** 452,303
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

svg: from their website (embedded in the website in the header)
color: `#242F4B`

### CODE REVIEW

**Comment by LitoMore** [comment]
> There are some very thin lines that maybe we should preserve? (@sachinraja)

Yes, I think it's by design.

**Comment by dirien** [comment]
I have no clue how to create single object out of this. Everytime i combine the gap gets removed. Would need some help from my fellow @simple-icons/maintainers 😅

**Comment by LitoMore** [comment]
Refer to the Standing Logo Flat (Blue) in https://fuga.cloud/media/. Maybe we could ignore those thin lines.

**Comment by runxel** [comment]
I'd second that. Those thin lines don't seem to be intentional for sure.

**Comment by dirien** [comment]
Than would be nice to accept this PR? It has not the lines in! Thanks in advance!

**Comment by LitoMore** [comment]
CleanShot 2022-08-25 at 20 48 32@2x

Seems the Standing version has a little difference. Could you help to recreate the SVG file base on the Standing one? Thank you!

**Comment by dirien** [comment]
Hi @LitoMore,

created the icon with the Standing Logo Flat (Blue) eps.

Hope it fits, as I needed to use an online eps to svg converter. 😅

**Review by LitoMore — APPROVED** [review]
image

Looks good.

**Comment by LitoMore** [comment]
> Hope it fits, as I needed to use an online eps to svg converter.

Inkscape supports EPS files, you could drag EPS file to Inkscape directly.

**Pull request merged**
