### PR TITLE
Updated Disroot

### PR DESCRIPTION
**Pull request by fbernhart**
disroot

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by fbernhart** [comment]
@service-paradis @mondeja Can anyone of you have a look at this icon?

I've now even rebuilt it from the source https://git.fosscommunity.in/disroot/assests/blob/master/d.svg, but it's still failing. I've used Inkscape to set one dimension to exactly 24, centered it and then optimized it with https://jakearchibald.github.io/svgomg with a (high) precision of 5.

Still the linter is telling me that:

> x icons/disroot.svg
>   x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 24.022 x 15.747
>   x icon-centered <path> must be centered at (12, 12); the center is currently (12.042, 11.979)

I really don't want to say it out loud, but ... **Maybe it's another bug in the linter?** 😨  (Similiar to #3960).

Because Inkscape is telling me that the size is 24 in one dimension and that it's centered.
And as well using Python and https://pypi.org/project/svgpathtools, I get the following:

```
x_min: 0.0
x_max: 24.000008980539683

y_min: 4.147857771966527
y_max: 19.820199999999996

width: 24.000008980539683
height: 15.672342228033468
```

Which is quite different from what the linter calculated (24.022 x 15.747).

**Comment by mondeja** [comment]
I will take a look :eyes:

**Review by mondeja — CHANGES_REQUESTED** [review]
As you can see in the next image, there are a lot of points inside and outside the letter "D" of the original icon that are left over, they do nothing by drawing the path and generate commads like `m0 0zm0 0zm0 0zm0 0zm0 0zm0 0zm0 0z`. This is affecting the calculation of the central coordinate:

failed-points

I have corrected it and I get the following path, which does not generate errors in the linter:

```
M18.824 6.67c.062.086.062.17 0 .256-.062.02-.113.02-.154 0l-.154-.223-.37-.095c-.06-.064-.06-.15 0-.255.063-.086.145-.118.247-.096.185.106.328.245.43.415zm4.49 4.337c.02.063.032.116.032.16l-.154.222v-.35c.04-.022.082-.033.123-.033zm-5.382-4.75l.153.255c-.082.148-.164.244-.246.287l-.093.126c-.04-.106-.07-.212-.092-.318-.02 0-.04-.01-.062-.032l-.123.127-.553-.127c-.082-.107-.06-.224.06-.35.125-.128.268-.16.43-.096zm-1.138.67l-.154-.096.123-.063.03.16zM14.334 5.3l-.185.224-.186-.223-.154-.03.492-.097zm9.596 4.782c.082.064.092.223.03.478l-.183.542-.154.19-.03-.38c0-.086-.01-.16-.03-.224 0-.064-.012-.128-.033-.19l-.4.19c.02.042.03.096.03.16.02.063.042.106.063.127l-.43.032.03.127.092.096-.153.35c-.02.19-.072.298-.154.32l-.123-.192-.37.095c-.082-.085-.122-.16-.122-.223l-.093-.127.154-.19c-.04-.086-.082-.13-.123-.13l-.153.065-.153.382c-.144 0-.237.02-.277.064l.184.255.647.35.03.223c.083.02.144.053.186.095.06.043.102.075.123.096-.02.043-.042.096-.062.16-.02.042-.06.084-.123.127l-.276.192.03.255c-.163.064-.307.17-.43.32l-.092.35c-.226 0-.37.02-.43.063l.03.48-.092-.033c-.082-.128-.164-.16-.246-.096l.123.415c-.062 0-.113.01-.154.032l-.06.064.122.224c.02.085.03.15.03.192-.123.106-.246.17-.37.19-.1.022-.183.097-.245.224l.03.382c-.06.15-.112.245-.153.287-.205 0-.36.02-.46.063l-.186.35-.152-.063c-.083-.02-.145-.02-.185 0l-.123.255c-.185 0-.32.042-.4.127l-.247.224.062-.287c.062-.17.03-.267-.093-.288l-.123.095-.03.16-.31.19-.03.35h-.584l-.123.225c-.04.127-.144.223-.308.287-.164.062-.45.094-.86.094s-.667.02-.77.064c-.102 0-.195.053-.277.16-.06.106-.133.18-.215.223l-.492.16-.153.287-.215.16c-.102.063-.266.095-.492.095l-.308.16-.46.19-.34-.03c-.122-.065-.266-.097-.43-.097h-.554l-.185-.128-.37.064-.183.256-.277-.19-.215-.224-.492-.032-.185-.16.278-.35.37-.51v-.35l.43-.48V17c0-.17.03-.32.092-.447l.338.096c.082-.086.123-.15.123-.193-.12-.106-.234-.244-.337-.414l-.308-.446-.37-.478-.245-.448-.277-.446-.215-.542-.46-.51-1.693-2.486-.308-.542-.307-.606-.246-.16c-.185-.232-.34-.487-.462-.764l-.092-.383-.277-.127-.953.19c-.226 0-.472.044-.738.13l-.646.254-.77.095-.43.16c-.185.043-.328.02-.43-.064l-.216-.254-.338.128-.277-.096c0-.213-.02-.34-.06-.383l-.278-.382C.154 7.798.06 7.743 0 7.723l.03-.16h.308c-.02-.062-.03-.137-.03-.222v-.16l.307.13C.718 7.244.78 7.19.8 7.15l.123-.255.246.032.183-.542-.03-.287.154.095.153.16c.103-.043.164-.086.185-.128l.277-.35.276.032-.092-.223-.184-.224-.277-.095c.123-.192.39-.33.8-.415l.984-.095.337-.223.8-.16 1.23-.064.43-.095c.165-.064.33-.075.493-.032l.492-.03c.328-.086.564-.107.707-.065l.4.032.553.032.83.16.738.062.524-.223c.124 0 .257.084.4.254l.308.223h.646l.215.255-.03.16.184.51.123-.064.277-.32.307.48-.37-.128c-.142 0-.224.106-.245.318l.307.064.123.16.184-.064c.103-.043.206-.022.308.064.123.063.205.137.246.223l.184.255h.4c0-.064.01-.107.03-.128.022-.043.042-.075.062-.095l.062.318h.123l.09-.095.094.16.092-.256c.267 0 .42-.022.46-.064 0-.064-.02-.117-.06-.16l-.123-.16c0-.105.082-.148.246-.126l.43.128.307-.032.184.16.063.127c-.184-.043-.308-.032-.37.032-.04.04-.05.115-.03.222l.215.19c0 .15.072.31.216.48l.123-.128.03-.255.124.158h.523c.103 0 .185.116.246.35l.092.32.123.095.154-.16.49.16.093-.16.154-.063c.082-.064.134-.117.154-.16v-.16l-.06-.16.43.13c.082-.086.134-.15.154-.192-.04-.107-.082-.16-.123-.16l-.306-.063v-.16l.092-.223.092-.19c.102.062.164.115.185.16l.154.22.215-.03.215-.032.77.67.215-.033.215.287.185.096c-.062.085-.062.18 0 .286l.215-.095h.215l.185.32.184.318c.165 0 .288.02.37.064l.123.574.34.19.275.097c0 .107-.02.192-.06.255l.06.32.093.19-.03.223.123-.063c.082-.107.143-.17.185-.19l.123-.065zm-7.75-4.716c.062.063.062.158 0 .286-.02.042-.082.074-.185.096-.06-.064-.06-.16 0-.287.02-.042.082-.074.185-.094zM9.566 18.72l.153-.158.153-.096zM19.01 6.96l.06.096-.154-.064.092-.032zm-.495-.063l-.06.095zm4.492 3.283c0-.17-.03-.308-.093-.415-.04-.106-.113-.2-.215-.286l-.03.414.214.097c.02.063.02.116 0 .16zm-1.17.67l-.153-.033-.184-.287.06-.255-.276.192.154.19.03.097-.368.16.246.03c.04.044.08.075.123.096.06.02.1.032.122.032l.246-.223zm-.614-.575l-.123-.095-.216-.064-.092-.16-.123.128-.093.223.246.096c.122 0 .215.033.277.096zM15.84 6.8l-.123-.065-.184-.095c-.082 0-.123.02-.123.063l.03.192.216.127zm3.692 6.79l.062-.384c0-.34-.124-.7-.37-1.084-.205-.383-.472-.69-.8-.924-.267-.255-.636-.48-1.107-.67l-1.23-.54-.462-.288-.677-.255-.707-.223-1.137-.255-.37-.064c-.184 0-.327.02-.43.064-.082.02-.112.095-.092.223l.37.733c.185.34.36.574.523.7l.277.192v.192l.307.382.03.254c.083.064.145.096.185.096.103.063.236.223.4.478l.34.414.52.765.463.83.215.636-.06.415.122.19-.123.192c-.063.064-.063.128 0 .192l.214-.064.37-.16c.102 0 .276-.063.522-.19l.677-.32.953-.382c.39-.17.667-.34.83-.51l.124-.32c0-.148.02-.254.062-.318z
```

**Comment by fbernhart** [comment]
@mondeja Thanks a lot for your work! It passed now. ☺️

**Comment by mondeja** [comment]
Thanks for the update :+1: Do you think that 4 decimals of precision are needed in this case? I can't see differences in the rendering between 3 and 4 decimals of precission. :thinking:

**Comment by fbernhart** [comment]
@mondeja While working on the about 250 icons in #3169, I made the experience that if I set the precision to 3, about 30% or above of the icons are failing the linter. Meaning I have to reoptimize it and push it again with a precision of 4 or 5 in order to pass.

While with a precision of 4, just about 10% or less are failing. So I've decided to simply always use 4 instead of 3, because the probability of passing the linter is higher. According to #3750 a precision of up to 5 is still ok.

But if you prefer a precision of 3, I can change it.

**Comment by mondeja** [comment]
> So I've decided to simply always use 4 instead of 3, because the probability of passing the linter is higher.

I think that this strategy is not the correct one, since the difference in size between the icons optimized to 3 decimal places and 4 is from 20% to 25%, so every 5 icons one more icon in size is added to the package. I would only use 4 or more decimal places if necessary.

**Comment by fbernhart** [comment]
@mondeja Ok, I understand your concerns. Thanks

**Review by mondeja — APPROVED** [review]
It looks good now. Thank you @fbernhart! :+1:

**Pull request merged**
