### PR TITLE
Add Proton Calendar

### LINKED ISSUE #8652: Proton Calendar
### Brand Name

Proton Calendar

### Website

https://calendar.proton.me/

### Popularity Metric

I cant find the similar web rick, but its a new product from Proton.

### Official Resources for Icon and Color

https://proton.me/media/kit

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
protoncalendar

**Issue:** closes #8652 

**Similarweb rank:** 614. See https://www.similarweb.com/website/proton.me

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from Official Icons in Brand website https://proton.me/media/kit
Color: `#7789ff` Taken from averaging logo colors by square root method.

### CODE REVIEW

**Comment by LitoMore** [comment]
Let’s use 2px gap. ✌️

**Comment by PratyushJayachandran** [comment]
> Let’s use 2px gap. ✌️

2px is thinning out the top left portion of the icon. Previous was 0.65. I increased to 1px all around.
Please review
protoncalendar

**Comment by PratyushJayachandran** [comment]
protoncalendar

Updating to this color `#50B0E9` as it is mentioned in blog post that 

> In addition to the new brand color and palette, we have introduced colors specific to each service: green for Proton VPN, blue for Proton Calendar, and red for Proton Drive.

**Comment by adamrusted** [comment]
@PratyushJayachandran - just to confirm - is this in line with the other Proton icons you submitted in terms of gap and JSON data? Will review later today if so 😄

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran - just to confirm - is this in line with the other Proton icons you submitted in terms of gap and JSON data? Will review later today if so 😄

Yes, all of them have 1px gap and in another PR I had updated the color of proton VPN to match that blog post #8973.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @PratyushJayachandran 🎉

**Pull request merged**
