### PR TITLE
Add Puma

### PR DESCRIPTION
**Pull request by huuphongnguyen**
puma

**Issue:**
**Alexa rank:** [3,529](https://www.alexa.com/siteinfo/puma.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- I got SVG code from View Code of [puma.com](puma.com)
- I used Sketchapp to adjust and export
- I used https://jakearchibald.github.io/svgomg/ to optimize
- I used Inscape to compare with source icons to make sure it fit.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @huuphongnguyen 👍🏻

The SVG looks good to me but, again, it looks like you should be able to reduce the precision down to 3 when optimising without creating any issues.

On the colour: from the (PNG) logos available at the end of [this page](https://about.puma.com/en/newsroom/images-and-footage) as well as the colours used on the website, I'd expect a black or grey but I'm not _entirely_ sure on the correct choice.

**Comment by PeterShaggyNoble** [comment]
SVG looks perfect to me now, @huuphongnguyen, thanks. We just need to decide on the colour before merging this. Any of the other @simple-icons/maintainers have any thoughts on that?

**Comment by service-paradis** [comment]
I would expect a darker color for this brand. Maybe something like `#242b2f` which is the color used in the header and footer of their website?
It is also used in the background for multiple pages section (ex. https://about.puma.com/en/this-is-puma/reform).

**Comment by PeterShaggyNoble** [comment]
Yep, I'd agree with that, @service-paradis 👍🏻 What do you think, @huuphongnguyen?

**Comment by huuphongnguyen** [comment]
Yes. I agreed 👍👍.

**Comment by PeterShaggyNoble** [comment]
OK, so, if you can update the PR with that colour then we can merge it straight in.

**Comment by PeterShaggyNoble** [comment]
Hope you don't mind but, in the interests of getting some of our backlog cleared out, I went ahead and made that change for you.

**Pull request merged**
