### PR TITLE
Add Pug

### LINKED ISSUE #3401: Request: Pugjs icon (HTML templating engine)
**Name:** Pug / Pugjs (formerly, Jade)
**Website:** https://pugjs.org/
**Alexa rank:** Rank - 93,333
  

**Official resources for icon and color:** I couldn't find any branding guidelines. Their media kit is in their repo at [pugjs/pug-log](https://github.com/pugjs/pug-logo).

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Pug

**Issue:** Closes #3401
**Alexa rank:** [~157k](https://www.alexa.com/siteinfo/pugjs.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Colour from [website](https://pugjs.org/) stylesheet.

Original treatment:

### CODE REVIEW

**Comment by adamrusted** [comment]
Is it worth trying to complete the head shape using a line? I've had a quick go at recreating it with a 0.5pt line around the inside of the entire icon. I've included my path (to 3 decimals) below, though no idea if it passes the linter.

pug

```svg
<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Pug icon</title><path d="M17.222 8.942c-.91 0-1.647.737-1.647 1.647 0 .248.059.48.157.691.309.262.603.54.883.837.188.075.392.12.607.12a1.647 1.647 0 000-3.295zm-.411 1.31a.412.412 0 110-.824.412.412 0 010 .824zm-9.884-1.31a1.647 1.647 0 100 3.294c.158 0 .307-.029.45-.07.344-.368.708-.71 1.095-1.023.063-.174.103-.359.103-.554 0-.91-.738-1.647-1.648-1.647zm.412 1.31a.412.412 0 110-.824.412.412 0 010 .824zm16.42-.942a14.95 14.95 0 00-.683-.788 26.708 26.708 0 00-.612-.643c-.87-.884-1.91-1.82-2.546-2.12a5.801 5.801 0 00-.663-.276 7.11 7.11 0 00-.422-.137l-.103-.03a7.935 7.935 0 00-.501-.12l-.1-.019a7.783 7.783 0 00-.374-.062l-.114-.016a6.405 6.405 0 00-.38-.037l-.024-.001a4.019 4.019 0 00-.224-.008l-.034.002c-.05.001-.086.004-.124.008-.031.002-.062.005-.084.01a.118.118 0 00-.05.02c-.006.004-.025.006-.027.01-1.17-.303-2.678-.467-4.6-.467-2.056 0-3.676.197-4.914.56l.084-.073c.017-.017.002-.03-.03-.042l-.013-.005a.858.858 0 00-.211-.021l-.057-.002c-.072 0-.155.003-.247.008-.114.007-.245.021-.383.038-.038.005-.077.01-.117.017a7.826 7.826 0 00-.365.06l-.11.02c-.16.034-.326.073-.495.119-.038.01-.074.022-.112.033a7.139 7.139 0 00-1.08.412C2.773 6.359-.072 9.503.002 9.69c.014.035.085.112.175.204.12.122.288.28.482.457l.462.42c.308.28.599.548.753.716a.952.952 0 01.105.18l.011.021c.04.083.085.185.135.3l.03.072.02.045.1.234.045.102c.056.13.115.262.177.395l.03.063c.064.134.13.266.198.39l.025.045c.072.126.144.245.219.346l.011.014c.075.1.15.182.227.242l.015.014c.075.056.15.084.225.089.007 0 .014.008.02.008.005 0 .01-.004.014-.004a.305.305 0 00.152-.047.473.473 0 00.14-.205c.012-.03.023-.067.034-.102.024-.075.047-.158.066-.254.01-.048.02-.098.028-.151.018-.111.034-.233.048-.363.006-.049.012-.093.017-.144l.002-.012c.057.485.114.961.19 1.418.112.749 1.086 1.348 1.198 2.059.14 1.02.756 1.737 1.989 2.188l.01.01c.053.07.109.126.168.175.018.015.038.027.057.04a.977.977 0 00.206.115c.052.021.105.038.158.052.018.004.034.01.052.013.161.035.328.047.494.061l.145.015.085.012c.049.007.097.018.145.029.023.006.047.01.07.017.07.02.137.046.202.08.115.063.232.113.35.154.04.014.081.021.121.033.08.023.158.047.238.062.051.01.103.015.155.022.07.01.141.022.213.028.057.004.115.005.172.008.068.002.135.006.203.007h.025l.064-.002c.218-.002.438-.012.66-.024.238-.012.479-.025.72-.025.22 0 .433.009.65.018.192.007.382.013.571.015l.075.002.072-.002a5.707 5.707 0 00.398-.019c.079-.006.157-.017.236-.029.051-.007.103-.014.154-.024.085-.017.17-.04.254-.064.043-.013.087-.022.13-.037.127-.043.254-.094.38-.16.066-.034.135-.059.205-.079.025-.007.051-.012.077-.018a1.807 1.807 0 01.239-.039l.114-.01c.179-.014.359-.022.532-.055l.006-.002c.07-.013.137-.033.203-.057l.044-.02a.975.975 0 00.357-.26c.008-.01.018-.016.026-.026 1.24-.449 1.836-1.172 1.977-2.204.113-.711 1.049-1.31 1.16-2.06.062-.365.11-.746.156-1.132.01.087.022.163.034.24.004.03.008.064.013.092a2.211 2.211 0 00.113.414c.038.088.08.162.134.2a.28.28 0 00.147.047c.004 0 .008.004.012.004.007 0 .014-.008.02-.008a.405.405 0 00.22-.09l.014-.013c.075-.06.15-.142.224-.241l.012-.015c.074-.1.147-.22.218-.345l.026-.046a7.73 7.73 0 00.2-.389c.011-.022.022-.043.032-.066.063-.131.123-.263.18-.391l.049-.111.089-.203.031-.072.031-.07c.05-.114.097-.216.137-.299l.012-.022a.982.982 0 01.106-.179c.154-.168.445-.436.753-.716.205-.187.418-.378.602-.548.092-.085.177-.165.25-.236.147-.142.248-.25.267-.297.014-.035-.076-.174-.24-.38zm-11.706 4.652c-.07-.552-.072-1.138-.072-1.688v-.375a5.117 5.117 0 00-.657-.235c.185.033.371.048.545.048.15-.075.187-.3.187-.3s.038.225.187.3c.15.075.861-.15.861-.15-.337.262-.973.262-.973.337v.375c0 .402.025 1.442-.03 1.685.825.007 2.089 1.127 2.089 2.508v.074c-.037-1.347-1.61-2.433-2.096-2.433-.487 0-2.06 1.048-2.097 2.433v-.074c0-1.363 1.232-2.47 2.056-2.505zM9.997 12.91a.15.15 0 11.3 0 .15.15 0 01-.3 0zm1.502-1.75c.05-.158.153-.267.232-.242s.103.172.054.33c-.049.158-.153.267-.232.242-.079-.024-.103-.172-.054-.33zm.858-.222c.08-.02.179.092.22.253s.01.306-.07.327c-.08.02-.179-.092-.22-.253s-.01-.306.07-.327zm1.309 1.972a.15.15 0 11.3 0 .15.15 0 01-.3 0zm1.273.15a.15.15 0 110-.3.15.15 0 010 .3zm-.113.749a.15.15 0 11-.299 0 .15.15 0 01.3 0zm-5.54.15a.15.15 0 110-.3.15.15 0 010 .3zm-.262-.9a.15.15 0 110-.299.15.15 0 010 .3zm10.553-.068c-.046.378-.092.75-.154 1.118-.037.249-.267.541-.49.824-.292.37-.594.752-.671 1.241-.098.716-.474 1.21-1.16 1.572.121-.444.195-1.062.195-1.953.038-1.123.075-1.573-.86-2.696A5.527 5.527 0 0013.65 11.2c-.11-.39-.726-.836-1.556-.836-.829 0-1.415.42-1.536.819a5.528 5.528 0 00-2.845 1.914c-.935 1.123-.86 1.61-.86 2.696 0 .884.072 1.5.191 1.947-.709-.366-1.097-.859-1.195-1.576-.077-.484-.39-.867-.693-1.238-.23-.282-.468-.573-.506-.825a29.354 29.354 0 01-.186-1.394.496.496 0 00-.453-.434c.082-.96.171-2.165.483-3.256.424-1.485 1.626-2.806 2.298-3.458.012 0 .029-.003.04-.004a.5.5 0 00.488.12c1.222-.357 2.828-.539 4.774-.539 1.815 0 3.32.152 4.475.451a.502.502 0 00.339-.031c.03-.002.064-.003.105-.003.047 0 .104.003.159.006.674.652 1.883 1.973 2.334 3.458.366 1.204.435 2.545.52 3.542a.496.496 0 00-.45.432z"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
I had assumed that the white part of the original was supposed to be a void, @adamrusted, probably because of the "mono" in the filename. But I think you may be right and that we need to retain the overall shape of the head somehow so I've just pushed an update with my attempt at your suggested treatment. I did initially try something with a filled face with the eyes knocked out and cutouts around the muzzle & ears but I couldn't quite get it to work - someone with better skills than I, though, may be able to figure it out.

**Comment by adamrusted** [comment]
> I had assumed that the white part of the original was supposed to be a void, @adamrusted, probably because of the "mono" in the filename. But I think you may be right and that we need to retain the overall shape of the head somehow so I've just pushed an update with my attempt at your suggested treatment. I did initially try something with a filled face with the eyes knocked out and cutouts around the muzzle & ears but I couldn't quite get it to work - someone with better skills than I, though, may be able to figure it out.

I think this is as good a treatment as we can give it. Funny that their `mono` logo is actually two colours though. Will leave this for another @simple-icons/maintainers to pitch in, being as I suggested this edit.

**Comment by adamrusted** [comment]
Can another @simple-icons/maintainers look over this, to make sure they're happy with the treatment before merging?

**Review by ericcornelissen — APPROVED** [review]
I agree that the outline makes sense, though I think the version without also looks good enough for use if we want to switch in the future. The SVG looks perfect as well, thanks @PeterShaggyNoble 👍

**Pull request merged**
