### PR TITLE
Add Charles icon

### LINKED ISSUE #9320: Icon Request: Charles Proxy
### Brand Name

Charles

### Website

https://www.charlesproxy.com/

### Popularity Metric

The Similarweb rank is 254,115. See: https://www.similarweb.com/website/charlesproxy.com/#overview

### Official Resources for Icon and Color

png: https://user-images.githubusercontent.com/15472/41327135-e4bf090c-6eca-11e8-9b76-032e8e2b0707.png
color: #B5DDF1, from the website header

### Additional Comments

Charles is an HTTP proxy / HTTP monitor / Reverse Proxy that enables a developer to view all of the HTTP and SSL / HTTPS traffic between their machine and the Internet. This includes requests, responses and the HTTP headers (which contain the cookies and caching information).

### Contributing

Yes

### PR DESCRIPTION
**Pull request by lananolana**
**Issue:** closes #9320

**Similarweb rank:** 237,990. See [here](https://www.similarweb.com/website/charlesproxy.com/#overview).

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Charles

Charles is an HTTP proxy / HTTP monitor / Reverse Proxy that enables a developer to view all of the HTTP and SSL / HTTPS traffic between their machine and the Internet. This includes requests, responses and the HTTP headers (which contain the cookies and caching information).

### CODE REVIEW

**Comment by adamrusted** [comment]
Hey @lananolana - where did you find the SVG for this? I can only see a PNG header.

**Comment by lananolana** [comment]
> Hey @lananolana - where did you find the SVG for this? I can only see a PNG header.

I made it myself, using the official png image as a base.

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
Nicely done, @lananolana :+1: However, for me, it wasn't lining up well with the original at all. But, after playing around with it a bit, I think I found the problem: somewhere along the way your version became vertically stretched. If I reduce the height to around `22.6`dp while retaining a width of `24`dp and recentre it then it lines up about as perfectly as we can expect of a manual vectorisation.

Could you give that a try, please, and then this should be ready to merge straight in?

**Review by PeterShaggyNoble — APPROVED** [review]
Nice work, @lananolana; that looks about as perfect as any manual vectorisation of an icon with complex shapes can get 👍🏻

As it _is_ a manual recreation, though, we'll need the approval of at least one more member of the @simple-icons/icon-review team before merging.

**Review by adamrusted — APPROVED** [review]

**Pull request merged**
