### PR TITLE
Add Paradox Interactive icon

### LINKED ISSUE #11510: Request: Paradox Interactive
### Brand Name

Paradox Interactive

### Website

https://www.paradoxinteractive.com/

### Popularity Metric

Similiarweb Global Rank: [43,574](https://www.similarweb.com/website/paradoxinteractive.com)

### Official Resources for Icon and Color

- SVG: https://www.paradoxinteractive.com/favicons/safari-pinned-tab.svg
- Color: `#000000`, from icon

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by plvzfq-rit**
paradoxinteractive (1)

**Issue:** closes #11510 

**Popularity metric:** [68,142](https://www.similarweb.com/website/paradoxinteractive.com/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

A .svg of the logo used by Paradox Interactive. 

#### Why did you pick the hex value?
A hex value of # 101010 was used since this was the value used when displaying the logo in tab of the company's home page.

#### Did you manually vectorize the logo?
The logo was not manually vectorized.

#### Have you used multiple sources?
The only source used was the company's home page itself, specifically from the home page header (https://www.paradoxinteractive.com/images/logo/logotype_white.svg)

### CODE REVIEW

**Comment by plvzfq-rit** [comment]
Ah apologies, I did not see that someone was already working on this issue; I will retract this pull request.

**Comment by uncenter** [comment]
Are you referring to https://github.com/simple-icons/simple-icons/pull/11534? It is closed and you are open to contribute!

**Comment by plvzfq-rit** [comment]
Ah, I see! In that case, I've more or less finished the work for this issue and it is now for review. Please do let me know if there is something I should change or improve upon.

**Comment by plvzfq-rit** [comment]
By the by, if I may ask, would it be fine for me to work on another issue while I have this pull request active? Sorry to ask, it's my first time contributing to an open source project;;;

**Comment by uncenter** [comment]
Yes that is fine!

**Comment by plvzfq-rit** [comment]
I see, thanks!

**Comment by LitoMore** [comment]
@plvzfq-rit Thanks for contributing. Could you optimize this icon to precison 3 with our script?

You can use this script to optimize:

```shell
npx svgo icons/paradoxinteractive.svg
```

**Comment by plvzfq-rit** [comment]
Sure+ I'll try to have it done within a few hours

**Comment by plvzfq-rit** [comment]
Ran it+

**Review by LitoMore — CHANGES_REQUESTED** [review]
I can see some differences:



I was picked the resource from their homepage header (https://www.paradoxinteractive.com/images/logo/logotype_white.svg) as the reference.

This needs to be fixed.

**Comment by plvzfq-rit** [comment]
Hmm, I'll redo it then, much thanks for letting me know+

**Comment by plvzfq-rit** [comment]
Redid it, should be all correct now, hopefully+

**Comment by plvzfq-rit** [comment]
Had forgotten to update the initial comment, everything should be there now+

**Review by LitoMore — APPROVED** [review]

**Comment by LitoMore** [comment]
@plvzfq-rit Thanks for contributing to Simple Icons!

**Pull request merged**
