### PR TITLE
Add stylelint icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** N/A
**Alexa rank:** [~251k](https://www.alexa.com/siteinfo/stylelint.io) and [8.4k ⭐ on Github](https://github.com/stylelint/stylelint)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- I took the logo `stylelint-icon-black.svg` from https://github.com/stylelint/stylelint/tree/master/identity
- I used Inkscape to scale and adjust
- I used https://jakearchibald.github.io/svgomg/ to optimize
- I used the color from the header background at https://stylelint.io/

### CODE REVIEW

**Review by adamrusted — COMMENTED** [review]
LGTM! Is it worth linking to https://github.com/stylelint/stylelint/tree/1f7bbb2d189b3e27b42de25f2948e3e5eec1b759/identity as the source, just so we've got the specific version on file?

**Comment by service-paradis** [comment]
I never know if I should use a source where we can potentially look in the future if the logo have been updated or if I should link to the specific file in used 😅

**Comment by PeterShaggyNoble** [comment]
1. For GitHub sources link to the specific commit of the file. Unless the repo also contains their brand guidelines, in which case link to the repo.
2. For Wikipedia & Wikimedia, link to the source file's page.
3. For all other sources, try to link to a page that _includes_ the source file. Sometimes, though, linking directly to the file is unavoidable.

So, in this case, assuming you based your version on the black icon, the source URL should be https://github.com/stylelint/stylelint/blob/1f7bbb2d189b3e27b42de25f2948e3e5eec1b759/identity/stylelint-icon-black.svg

**Comment by service-paradis** [comment]
Done 😃

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @service-paradis 💯

**Pull request merged**
