### PR TITLE
Wyze

### PR DESCRIPTION
**Pull request by celomary**
wyze

**Issue:** closes [#8213]

Similarweb rank is 13,833
https://www.similarweb.com/website/wyze.com/#overview

### Checklist
  - [ x ] I updated the JSON data in `_data/simple-icons.json`
  - [ x ] I optimized the icon with SVGO or SVGOMG
  - [ x ] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @celomary,

thanks for the contribution! Can you check the lint error so I can start to review the PR? Thanks!

**Comment by celomary** [comment]
> Hi @dirien , okay i will

**Comment by celomary** [comment]
@dirien  done

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @celomary,

Can you check your icon please? It does not look right.

image

**Pull request closed without merging**
