### PR TITLE
Add Google Maps icon (#1515)

### PR DESCRIPTION
**Pull request by phatbhoy67**
**Issue: #1515**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO ~or SVGOMG~
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

google maps
Source is [wikimedia .svg](https://upload.wikimedia.org/wikipedia/commons/a/a9/Google_Maps_icon.svg) manually adjusted to represent colour and shape differences with negative space.

Colours present in logo: `#4285f4`,`#fbbc05`,`#ea4335`,`#34AB53` from [google design website](https://design.google/library/evolving-google-identity/).

Hex value chosen `#34AB53`. 

Built on GitPod, working as expected.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one up, @phatbhoy67. The SVG looks good to the naked eye but I think a blue (maybe Google blue `#4285f4`) might be a better choice for the colour as that seems to be the primary colour used on the Maps website & app.

**Comment by phatbhoy67** [comment]
Hex value updated to `#4285f4` @PeterShaggyNoble

**Comment by PeterShaggyNoble** [comment]
Thanks, @phatboy67

I'll leave it to someone else to double check that and merge this is.

**Comment by runxel** [comment]
Not sure what's going on here, but Github fails to show a rich diff consistantly and when I'm opening the svg in Illustrator it looks really weird:
(Green is the actual path...)

wtf

**Comment by runxel** [comment]
There are still some problems:
- Down below are weird paths that don't belong there.
- In the marker is a bump, if you zoom in.
- The top is not round, but has a jagged line/extra points.

chr

(Also github still can't display the svg in the rich diff, but I don't know if thats related)

**Comment by runxel** [comment]
Looks neat now! 💯 
Thank you for the patience and the work! 🌮

**Comment by PeterShaggyNoble** [comment]
Excellent! Been needing this one for a while. Thanks again, @phatboy67.

**Pull request merged**
