### PR TITLE
feat: add DX Scanner icon

### PR DESCRIPTION
**Pull request by prokopsimek**
### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
We develop a CLI application called [DX Scanner](https://github.com/DXHeroes/dx-scanner) to measure the quality of an app (Developer Experience) from the source code. We'd like to have a shields.io badge and because of that, I have created this PR.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Hi @prokopsimek 👋 thanks for your contribution! Unfortunately your brand does not yet meet our [required popularity threshold](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon)<sup>1</sup> (if you think you do, feel free to leave a comment here explaining why it does). For now I would advice you to use the custom logo option in shields.io badges as [explained on their website](https://shields.io/#styles).

Once DX scanner gains more traction you're free to reopen this PR and we will be happy to merge it in 🙂 

* * *

<sup>1. we have this threshold so that not everyone's project is just added at random, I get you're a company but that still does not guarantee longevity.</sup>

**Comment by prokopsimek** [comment]
@ericcornelissen Hi, you’re true but I the section about “Requesting an icon” is written for the case of “before submitting an issue” and not a PR directly. It’s the reason why I have created this PR. I guessed if we’re authors of the brand so it’s ok to add an iconand the problem is if someone wants to add “foreign” icon.

I am ok with that, I wasn’t sure. I recommend you to update the Contributing guide.

**Comment by ericcornelissen** [comment]
> you’re true but I the section about “Requesting an icon” is written for the case of “before submitting an issue” and not a PR directly. It’s the reason why I have created this PR. I guessed if we’re authors of the brand so it’s ok to add an iconand the problem is if someone wants to add “foreign” icon.
>
> I am ok with that, I wasn’t sure. I recommend you to update the Contributing guide.

That is a fair interpretation of what is written there. We have never had anyone interpret it that way so I guess that is why it is like this.

Again, be sure to reopen this Pull Request once DX Scanner is more popular! Note that even though we only explicitly mention the Alexa rank, stats about social media or even GitHub repositories are usually considered good indicators of popularity as well for the purposes of this repository 😉

**Comment by prokopsimek** [comment]
Hi, thank you! I understand it’s absolutely ok :)

-- 
Prokop Simek

**Pull request closed without merging**
