### PR TITLE
Add Racket icon

### PR DESCRIPTION
**Pull request by spdegabrielle**
image

**Issue:**
Name: Racket
Alexa rank: 384,283

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Hex value from original image on https://racket-lang.org/

Optimised and set role, viewBox, and title as per https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by spdegabrielle** [comment]
Sorry I currently only have access to the online tools listed in the contribution guidance. 
Is this something you can help with?

**Comment by spdegabrielle** [comment]
I’m a bit confused @NovaGL
The view box is correct ? How can the image be the wrong size?
> <svg role="img" viewBox="0 0 24 24

**Review by NovaGL — CHANGES_REQUESTED** [review]
The icons dimensions are outside the viewbox. If you don't want to use Inkscape you'll have to use another program to fix the svg.

The width is 23.995 and the height is 24.009.

**Comment by spdegabrielle** [comment]
@NovaGL 
 * I’m expecting a clipping by less than 1% wont be visible on an icon that when rendered will be less than an inch onscreen even with ‘retina’ displays.
 * I don’t have access to any svg editors.just text editors and the recommended web tools.

**Comment by adamrusted** [comment]
@spdegabrielle I've been able to rebuild this in Adobe Illustrator and pass the linter. Thanks for your work on this one! 🎉

**Comment by spdegabrielle** [comment]
Thank you @adamrusted 😀
You are a star! Happy new year!

**Comment by fbernhart** [comment]
LGTM! 👍🏼 

Thanks @adamrusted and @spdegabrielle for your work!

**Pull request merged**
