### PR TITLE
Add Warp icon

### LINKED ISSUE #7308: Warp
### Brand Name

Warp

### Website

https://warp.dev

### Popularity Metric

The Similarweb rank is 460,377. See https://www.similarweb.com/website/warp.dev
The Alexa rank is 192,590. See https://www.alexa.com/siteinfo/warp.dev

### Official Resources for Icon and Color

svg: `https://assets-global.website-files.com/62176f9ffac2c484f913de2a/6218d8248b78cfc8aa32a902_logo.svg` from their website
color: `#01A4FF` from the darkest shade of blue on their website buttons

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by elliotwutingfeng**
Latest version by [LitoMore](https://github.com/LitoMore)

image

~Without logo text~

image

~With logo text~

image

**Issue:** closes #7308

**Similarweb rank:** 260,680

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Warp is a blazingly fast, rust-based terminal reimagined from the ground up to work like a modern app.

### CODE REVIEW

**Comment by dirien** [comment]
I am not sure that the logo without the wordmark will go well here...

image

**Comment by elliotwutingfeng** [comment]
Let me try a version which includes the text.

**Comment by sachinraja** [comment]
I would prefer it without the wordmark. I think we just need a gap between the two shapes.

> Some icons can't be easily converted to a monochromatic version due to colour changes, shadows, or other effects. For such cases, the addition of gaps is the recommended approach, with a preferred width of 0.5px. In some situations, a different gap may be required, but that will be determined on a per-case basis.

(from the contributing docs)

**Comment by LitoMore** [comment]
@elliotwutingfeng I've created the icon with a gap for you, could you update your pull request with this one and resolve conflicts?

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Warp</title><path d="M12.035 2.723h9.253A2.712 2.712 0 0 1 24 5.435v10.529a2.712 2.712 0 0 1-2.712 2.713H8.047Zm-1.038 2.6-3.433 13.73h4.956l-.555 2.224H2.712A2.712 2.712 0 0 1 0 18.565V8.036a2.712 2.712 0 0 1 2.712-2.712Z"/></svg>
```

**Comment by elliotwutingfeng** [comment]
> @elliotwutingfeng I've created the icon with a gap for you, could you update your pull request with this one and resolve conflicts?
> 
> ```
> <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Warp</title><path d="M12.035 2.723h9.253A2.712 2.712 0 0 1 24 5.435v10.529a2.712 2.712 0 0 1-2.712 2.713H8.047Zm-1.038 2.6-3.433 13.73h4.956l-.555 2.224H2.712A2.712 2.712 0 0 1 0 18.565V8.036a2.712 2.712 0 0 1 2.712-2.712Z"/></svg>
> ```

Thanks for helping out! I've updated my pull request.

**Review by LitoMore — APPROVED** [review]

**Comment by LitoMore** [comment]
Waiting for the Warp team to approve https://discord.com/channels/851854972600451112/852249738002956311/1014216091209310238

**Pull request merged**
