### PR TITLE
feat: add Exoscale icon

### PR DESCRIPTION
**Pull request by dirien**
image

**Issue:** #7043 
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

svg: `https://www.exoscale.com/static/img/exoscale-logo-full-201711.svg`
Color: `#da291c`

### CODE REVIEW

**Review by sachinraja — CHANGES_REQUESTED** [review]
Seeing a slight difference along the bottom
image

**Comment by dirien** [comment]
hi @sachinraja, I checked again and I can't see any difference like in your screenshot?

Could you verify your settings maybe?
image

**Comment by sachinraja** [comment]
Can you send the exact link to your source?

**Comment by sachinraja** [comment]
> Can you send the exact link to your source?

bumping this @dirien

**Comment by dirien** [comment]
@sachinraja It was in the issue but let me post it here too

svg: `https://www.exoscale.com/static/img/exoscale-logo-full-201711.svg`
Color: `#da291c`

**Review by sachinraja — APPROVED** [review]
Thanks, I may have been looking at the wrong image, this is perfect. Updated the source to `https://www.exoscale.com/press/`.

**Pull request merged**
