### PR TITLE
Add Microsoft Store

### LINKED ISSUE #8760: Icon request: Microsoft Store
### Brand Name

Microsoft Store

### Website

https://apps.microsoft.com/

### Popularity Metric

There is no rank on similarweb.com, but it does say it got 25 million visits. I assume that's because people use the Windows App, not the website.

But for popularity ranking: Every Windows PC has it installed.

### Official Resources for Icon and Color

https://apps.microsoft.com/store/images/logo-40x40.png 
image

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
microsoftstore

**Issue:** closes #8760 

**Similarweb rank:** 39. See https://www.similarweb.com/website/microsoft.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG was not available. Created using reference taken from https://upload.wikimedia.org/wikipedia/en/0/08/Microsoft_Store_app_icon.png
Color taken by averaging out the colors and taking the highest among them: `#13528F`

### CODE REVIEW

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
Microsoft provide [a monochrome version](https://github.com/microsoft/fluentui-system-icons/tree/main/assets/Store%20Microsoft/SVG) of this icon in their own [Fluent UI System Icons](https://github.com/microsoft/fluentui-system-icons/), which we've used as a source for MS icons in the past, so we should probably base our version off that. From the naming of the SVGs in that directory, it looks like the preferred treatment is for the bag to be outlined and the Microsoft logo to be solid. Doing so would necessitate the inclusion of [this license](https://aka.ms/fluentui-assets-license) in the metadata.

For the colour I would suggest `#005FB8` (`--theme-primary-element-color`) from the [website](https://apps.microsoft.com/)'s stylesheet.

**Comment by PratyushJayachandran** [comment]
> `005FB8`

Thanks for finding the SVG out. I struggled unnecessarily :P 
Here is the new preview
microsoftstore
Please review again @PeterShaggyNoble

**Comment by PeterShaggyNoble** [comment]
That looks perfect, @PratyushJayachandran 👍🏻

**Comment by bogdan-patraucean** [comment]
Was this icon removed? Can't find it.

**Comment by PratyushJayachandran** [comment]
> Was this icon removed? Can't find it.

Yes. Reason:
https://github.com/simple-icons/simple-icons/pull/9896#issue-2005813373

**Comment by bogdan-patraucean** [comment]
@PratyushJayachandran, but Microsoft Store is not the same as Office 365.

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran, but Microsoft Store is not the same as Office 365.

Oops, I linked the wrong issue by mistake. Regardless all Microsoft icons are removed from this project as per their legal request.
See: https://github.com/simple-icons/simple-icons/issues/11236

**Comment by bogdan-patraucean** [comment]
> Oops, I linked the wrong issue by mistake. Regardless all Microsoft icons are removed from this project as per their legal request.
See: https://github.com/simple-icons/simple-icons/issues/11236

So sad.

**Pull request merged**
