### PR TITLE
Add Donorbox icon

### LINKED ISSUE #6830: Request: Donorbox.org brand Icon
### Brand Name

Donorbox

### Website

https://donorbox.org

### Popularity Metric

The alexa rank is 13,915. See https://www.alexa.com/siteinfo/donorbox.org

### Official Resources for Icon and Color

Icon : https://donorbox.org/images/red_logo.png
Button : https://donorbox.org/images/png-donate/button-medium-blue.png

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by filips123**
**Issue:** closes #6830

**Similarweb rank:** 43972

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Full logo is available from [their brand assets](https://donorbox.org/media-assets). I've removed the text and kept only the icon. Color has been picked up from the shade of blue that is normally used in their logo.

### CODE REVIEW

**Comment by adamrusted** [comment]
As mentioned in their [brand guidelines](https://donorbox.org/[donorbox-brand-guide.pdf](https://donorbox.org/donorbox-brand-guide.pdf) we probably shouldn't use the icon without the full wordmark. What do other @simple-icons/icon-review folk think?

**Comment by dirien** [comment]
Agree with you @adamrusted

**Comment by adamrusted** [comment]
If you could, @filips123 - that'd be great.
I'd rather err on the side of caution with something like this - and demonstrably have permission to use the icon before we include it!

**Comment by filips123** [comment]
Unfortunately, they said it's not allowed to modify the icon and convert it to monochrome (they only allowed using unmodified SVG file), so I'll close this PR... I may create another one in the future if they change their guidelines to allow this.

**Pull request closed without merging**
