### PR TITLE
Update Adobe Premiere Pro

### PR DESCRIPTION
**Pull request by MetLee**
image

**Issue:** #3369 
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Just to double check, @MetLee, did you use https://www.adobe.com/content/dam/shared/images/product-icons/svg/premiere.svg as the source for this one? Because the current source URL uses one of the other, inconsistent icons and there a few minor differences between it and your version.

**Comment by MetLee** [comment]
I used this one: https://www.adobe.com/content/dam/cc/icons/premiere.svg
Therefore I shoud alter the source to https://www.adobe.com/creativecloud/video.html , shouldn't I?

**Comment by fbernhart** [comment]
Looks good to me. @service-paradis What do you think? Can this be merged?

**Comment by fbernhart** [comment]
### Minor change:

After looking at the other Adobe icons that we are having, I think the source should instead link to the product page of the specific product. So I'm in favor of changing it back to https://www.adobe.com/ie/products/premiere.html

**Comment by service-paradis** [comment]
> Looks good to me. @service-paradis What do you think? Can this be merged?

The icon looks good to me. Since the logo for Adobe Premiere is not found in their [official brand guideline](https://partners.adobe.com/content/dam/tep_assets/public/public_1/documents/Adobe-Creative-Cloud-Developer-Brand-Guide-062218.pdf), I would opt for https://www.adobe.com/ie/products/premiere.html as the source

**Comment by mondeja** [comment]
I've taken the liberty of reverting the source, so we can go ahead with the merge.
Thank you @MetLee for this update, @fbernhart and @service-paradis for the reviews! :tada:

**Pull request merged**
