### PR TITLE
Change hexes for TUI and TailwindCSS

### PR DESCRIPTION
**Pull request by jorgeamadosoria**
tui

tailwindcss

issues: #6541 #6530

### CODE REVIEW

**Review by sachinraja — APPROVED** [review]

**Comment by sachinraja** [comment]
I think we can also add the brand url as guidelines

**Comment by jorgeamadosoria** [comment]
> I think we can also add the brand url as guidelines

done.

**Review by sachinraja — APPROVED** [review]

**Comment by sachinraja** [comment]
I would remove the trailing slash on the TUI url just to match the other ones.

**Comment by jorgeamadosoria** [comment]
> I would remove the trailing slash on the TUI url just to match the other ones.

the TUI urls without the trailing slash redirect to the ones with the slash. 
Besides, there is no format for them: TailwindCSS does not use a trailing slash, but TinyLetter does not work without it 🤷

**Comment by sachinraja** [comment]
> Besides, there is no format for them

Ok, I think this can be merged now then.

**Pull request merged**
