### PR TITLE
Add Feeds Pub

### LINKED ISSUE #3427: Request: Feeds Pub
**Name:** Feeds Pub
**Website:** [feeds.pub](https://feeds.pub)
**Alexa rank:** 320K
  

**Official resources for icon and color:** https://feeds.pub/favicon.ico

### PR DESCRIPTION
**Pull request by timqian**
feedspub

**Issue:** Close #3427 
**Alexa rank:** ~320K

  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I am the founder of [feeds.pub](https://feeds.pub)

### CODE REVIEW

**Comment by NovaGL** [comment]
Hi @timqian 

Can you please look at the SVG, it failed for the following reasons.

icon-title <title> should follow the format "[ICON_NAME] icon"
icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 14.95 x 20.521
icon-centered <path> must be centered at (12, 12); the center is currently (12.026, 11.966)

**Comment by timqian** [comment]
Thanks @NovaGL I have fixed the issues.
As the icon is not in a regular shape, it's center is not accurate, I ignored the size and center lint

**Comment by ericcornelissen** [comment]
@timqian, am I correct that your concern regarding centering is related to the issue described in #477? If so, though unfortunate, I would like to ask you to "center" it according to the projects definition for now. There are other icons that have the same problem, but until #477 is properly resolved I think we want stick with the current definition of "centered".

Else, could you elaborate a bit more? In addition, I think we would need a different way to ignore this SVG then simply including it in [.svglint-ignored.json](https://github.com/simple-icons/simple-icons/blob/9d600293682c4a3a560364939ab07ab951e2d7fb/.svglint-ignored.json) since that list contains icons that _should_ be fixed.

**Comment by fbernhart** [comment]
After resizing the icon to a height of 24.000, I was able to pass the linter without problems locally.

But anyway: Seems like the Alexa rank has dropped massively to [2,908,258](https://www.alexa.com/siteinfo/feeds.pub) within the last few months.

I'm closing this now, as it's out of scope. @timqian feel free to reopen this PR whenever Feeds Pub gets more popular. (We're requiring an Alexa rank of below 500k).

**Pull request closed without merging**
