### PR TITLE
Team Fortress TV logo

### LINKED ISSUE #3187: Team Fortress tv
**Name:** Team Fortress TV (usually referred to as tftv)
**Website:**https://www.teamfortress.tv/
**Official resources for icon and color:**
I couldn't find .svg
https://www.teamfortress.tv/img/tf/logo.png
https://static-cdn.jtvnw.net/jtv_user_pictures/team-teamfortresstv-team_logo_image-e480add9335ceee1-300x300.png
**Alexa rank:** [~103.4k](https://www.alexa.com/siteinfo/teamfortress.tv)

### PR DESCRIPTION
**Pull request by micwoj92**
Team Fortress TV

**Issue:**  Closes #3187 
**Alexa rank:** [108,187](https://www.alexa.com/siteinfo/teamfortress.tv)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I picked the hex value from the image, source next to official was this image https://cdn.discordapp.com/attachments/429191025198628864/647200198572900365/tftv_icon_800x800_color_light.png

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @micwoj92 :+1:

However, when comparing your SVG (in red below) to the 2 provided [here](https://www.teamfortress.tv/56207/svg-version-of-tftv-logo), there are a few differences. As they are original works, though, I'd like to get one of the other @simple-icons/maintainers to do a comparison with the original raster version before asking you to make any changes.

But I would suggest using https://www.teamfortress.tv/56207/svg-version-of-tftv-logo as the source URL.

**Comment by micwoj92** [comment]
Thanks for feedback @PeterShaggyNoble , I didn't really edit the file that I got from roblan11 on forum so I am not sure where that's coming from. I might have done something wrong by accident. Inkscape is still a strange tool for me. We'll see how it goes.

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @micwoj92?

**Comment by micwoj92** [comment]
Oh, I thought you guys will review and tell if it's good enough.

**Comment by ericcornelissen** [comment]
@micwoj92 we generally prefer either an official source (which roblan11 doesn't seem to be) or a vector that matches a bitmap as closely as possible. Unfortunately, as you can see from [the comparison by @PeterShaggyNoble](https://github.com/simple-icons/simple-icons/pull/3271#issuecomment-651900369), the version by roblan11 you added isn't a particularly close match to the original (or perhaps roblan11 used a different source image?).

Do you plan to improve upon the version you added or is that beyond your capabilities?

**Comment by PeterShaggyNoble** [comment]
> Unfortunately, as you can see from the comparison by @PeterShaggyNoble, the version by roblan11 you added isn't a particularly close match to the original (or perhaps roblan11 used a different source image?).

I actually used roblan11's SVGs for my comparison above, @ericcornelissen.

**Comment by NovaGL** [comment]
We're going to have to use artist interpretation as from the link @PeterShaggyNoble posted there is no vector source.

I think roblan11's version is going to be the best unless someone wants to convert the bitmap to a vector themselves.

**Comment by ericcornelissen** [comment]
Apologies for the confusion at my end 😅 Based on the vector to raster comparison below I would say that robin11's version is close enough to the original that we can use it. But, following @PeterShaggyNoble's [earlier comment](https://github.com/simple-icons/simple-icons/pull/3271#issuecomment-651900369) the SVG in this Pull Request still needs to be updated.

image

Hence, the question to @micwoj92 remains: Do you plan to improve upon the version you added or is that beyond your capabilities?

**Comment by micwoj92** [comment]
I do not have that much desire for this icon. If I ever want it I will just create new request with 100% ready svg. Thanks for your time.

**Pull request closed without merging**
