### PR TITLE
Updated Vauxhall

### PR DESCRIPTION
**Pull request by fbernhart**
vauxhall

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by service-paradis — COMMENTED** [review]
Looks like they updated their logo:
https://www.itsnicethat.com/news/vauxhall-rebrand-logo-graphic-design-240920
image


Do you want to update it in this PR or do you prefer we open another one?

**Comment by fbernhart** [comment]
@service-paradis I would update it in this PR. Where have you found the SVG to compare against? Or is this just a PNG file of the new logo?

Because I can't find any SVG version of the new logo.

**Comment by service-paradis** [comment]
> @service-paradis I would update it in this PR. Where have you found the SVG to compare against? Or is this just a PNG file of the new logo?

I took the PNG for a quick comparison. I will take a look if I can find a vector somewhere.

**Comment by fbernhart** [comment]
Found one. This PDF (page 1) looks promising:

https://www.vauxhall.co.uk/content/dam/vauxhall/Home/brochure-library/commercial-vehicles/price-guide.pdf

**Comment by fbernhart** [comment]
Haven't seen your update. 😅 

Would you prefer Wikipedia or the vectorized version for the PDF?

**Comment by service-paradis** [comment]
> Haven't seen your update. 😅

:D

> Would you prefer Wikipedia or the vectorized version for the PDF?

Good find! I would use the one from the PDF!

**Comment by fbernhart** [comment]
vauxhall

**Source:** Vectorized version of the logo from [a PDF file](https://www.vauxhall.co.uk/content/dam/vauxhall/Home/brochure-library/commercial-vehicles/price-guide.pdf)
**Color:** `#EB001E` as used in the [PNG version of the new logo](https://www.vauxhall.co.uk/content/dam/vauxhall/vauxhall-logo-125x75.png). 


@service-paradis Done. 😊  I've now as well changed the "source" in the JSON file to point to the PDF I've used. Is this ok? Or should it point to their main website https://www.vauxhall.co.uk instead?

**Comment by service-paradis** [comment]
> **Source:** Vectorized version of the logo from [a PDF file](https://www.vauxhall.co.uk/content/dam/vauxhall/Home/brochure-library/commercial-vehicles/price-guide.pdf)
> **Color:** `#EB001E` as used in the [PNG version of the new logo](https://www.vauxhall.co.uk/content/dam/vauxhall/vauxhall-logo-125x75.png).
> 
> @service-paradis Done. 😊 I've now as well changed the "source" in the JSON file to point to the PDF I've used. Is this ok? Or should it point to their main website https://www.vauxhall.co.uk instead?

Wow, good job 😄 
The logo is looking good, I agree with the chosen color and source!

**Comment by runxel** [comment]
Well done! 🥇 
(Man, I spent so much time on cleaning the old logo; those car brands are the worst of all)

**Pull request merged**
