### PR TITLE
Add Capital One icon

### LINKED ISSUE #8510: Request: Capital One
### Brand Name

Capital One

### Website

https://www.capitalone.com/

### Popularity Metric

www.similarweb.com rank is 210

### Official Resources for Icon and Color

https://www.kindpng.com/imgv/hJmmJiT_capital-one-logo-white-hd-png-download/
https://companieslogo.com/capital-one/logo/

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by uncenter**
capitalone

**Issue:** closes #8510.

**Popularity metric:** Ranked 198 globally on Similarweb. See https://www.similarweb.com/website/capitalone.com/.

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Logo picked from the red swoosh through the logo. I went with the large, recognizable but detailed version of the logo. However, this isn't very readable at smaller sizes. See https://github.com/simple-icons/simple-icons/issues/8510#issuecomment-2032058381.

### CODE REVIEW

**Comment by adamrusted** [comment]
Unfortunately, section two of their [terms and conditions](https://www.capitalone.com/digital/terms-conditions/) states:

> You are authorized by Capital One to copy, transmit or display information registered or owned by Capital One on any page of the Site only for your personal, non-commercial use. If you do so, it must include any copyright, trademark or service mark attribution as it appears on such page. The information and materials contained at the Site may not otherwise be copied, transmitted, displayed, distributed, downloaded, licensed, modified, published, posted, reproduced, used, sold, transmitted, used to create a derivative work or otherwise used for commercial or public purposes without Capital One's prior written consent.

Given we cannot guarantee how our users will use these icons, we need to seek consent before including it.

**Comment by adamrusted** [comment]
Would you be willing to reach out to Capital One, @uncenter?

**Comment by uncenter** [comment]
> Would you be willing to reach out to Capital One, @uncenter?

Definitely. I'm struggling to find a suitable contact email for them though.

**Comment by adamrusted** [comment]
Were you able to find any details to reach out to them @uncenter?

**Comment by uncenter** [comment]
The closest email I could find was `subpoena@capitalone.com`, under https://www.capitalone.com/digital/subpoena-policy/, for subpoena updates and *legal inquires*. Should I reach out to it orr?

**Comment by adamrusted** [comment]
I guess this _is_ a legal enquiry? Might be worth a shot - just preface the email with "Very aware you're not the right department, but could you please forward it?"

**Comment by uncenter** [comment]
Reached out to them!

**Comment by uncenter** [comment]
Closing as no feedback from brand.

**Pull request closed without merging**
