### PR TITLE
Add Liquibase icon

### PR DESCRIPTION
**Pull request by mcred**
liquibase

**Issue:**
**Similarweb rank: 279,053**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo and Hex values taken from [Liquibase branding guidelines](https://www.liquibase.com/brand)

### CODE REVIEW

**Review by sachinraja — CHANGES_REQUESTED** [review]
Seeing some differences
image

You can try increasing the precision:
https://github.com/simple-icons/simple-icons/blob/83ef249e5568bf1ec7d81f810009b8057c7c2b38/svgo.config.js#L23
(make sure to change it back when you commit though)

**Comment by mcred** [comment]
Thanks for the feedback. I started from scratch with an official SVG from liquibase. Opened it in illustrator to center and fit the logo to a 24x24 art board. Then in a text editor, I fix the formatting (clean up the metadata, put all the paths into one path, convert an ellipse to paths, remove styles and extra tags), then ran `npm run svgo` with a precision of 5. Output below:
```
> svgo --config svgo.config.js "icons/liquibase.svg"


liquibase.svg:
Done in 44 ms!
0.506 KiB - 8.1% = 0.465 KiB
```

**Comment by jorgeamadosoria** [comment]
ok, I used the header logo in the brand page, and remade this submission. I found the same issues @sachinraja reported, but after using precision 5, those went away. 
I think it's fine now. @sachinraja @mcred please check.

**Review by sachinraja — APPROVED** [review]
Great, good work to both of you

**Pull request merged**
