### PR TITLE
Updated Alfa Romeo

### PR DESCRIPTION
**Pull request by adamrusted**
**Issue:** Contributes to #4578
**Alexa rank:** [181,640](https://www.alexa.com/siteinfo/alfaromeo.com)

### Description
Updated HEX to match Pantone found in Style Guide. Removed Stellantis version, as existing icon in package matches perfectly to EPS available at source.

~Updated source to Stellantis website, as they use monochrome SVGs on the brand pages. Updated colour to a hex found on the Alfa Romeo homepage.~

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Looks like you forgot to push the changes to `simple-icons.json` plus there's a change to `.svgo.yml` that needs to be reverted.

**Comment by adamrusted** [comment]
Must've reverted the wrong file. Bear with.

**Comment by PeterShaggyNoble** [comment]
SVG looks spot-on to me, @adamrusted 👍🏻 Although, there is an imperfection at the bottom of the first circle in the snake's crown that's present in the original if you want to try cleaning that up before merging.

On the colour, although my original choice came from [official brand guidelines](http://www.fcaci.com/v15-images/guidelines/Alfa-Romeo-Guidelines-Rev201510.PDF), they are slightly dated now and, as they use your choice throughout their site, I think we're OK to change it here.

**Comment by adamrusted** [comment]
@PeterShaggyNoble copied the middle circle to replace the first on the crown. Otherwise, SVG should be exactly the same 🤞🏻

**Comment by adamrusted** [comment]
@PeterShaggyNoble - just re-doing this one from the FCACI portal, and only thing that's different is the Pantone reference for the hex. Have amended this PR accordingly.

**Comment by PeterShaggyNoble** [comment]
If we're going with the colours from [the PDF](http://www.fcaci.com/v15-images/guidelines/Alfa-Romeo-Guidelines-Rev201510.PDF) rather than from their website then we should probably use the hex reference provided on page 28, which is actually the original colour we had.

**Comment by adamrusted** [comment]
> If we're going with the colours from [the PDF](http://www.fcaci.com/v15-images/guidelines/Alfa-Romeo-Guidelines-Rev201510.PDF) rather than from their website then we should probably use the hex reference provided on page 28, which is actually the original colour we had.

Missed that one - always confuses me when people define a Pantone, and have a hex that is different to the one calculated [by Pantone](https://www.pantone.com/uk/en/color-finder/201-C)! Will revert now.

**Comment by fbernhart** [comment]
I'm a bit confused.

So if the hex is still the same and the SVG is still the same. What is this PR still about? 😅 

Seems like we can just close it. Or am I missing something?

**Comment by adamrusted** [comment]
> So if the hex is still the same and the SVG is still the same. What is this PR still about?

The SVG is different to the one already in Simple Icons - the comment above was talking about differences between my PR versions 🤣

**Comment by fbernhart** [comment]
@adamrusted How is it different? 😄

Have you maybe pushed the wrong file?

**Comment by adamrusted** [comment]
> @adamrusted How is it different? 😄
> 
> Have you maybe pushed the wrong file?

Never mind, I'm obviously confusing this and other PRs. Let's close this one for now, shall we? 🤣

**Pull request closed without merging**
