### PR TITLE
Add Cilium icon

### PR DESCRIPTION
**Pull request by sisp**
cilium

**Issue:** n/a
**GitHub Stars:** [11.2k](https://github.com/cilium/cilium)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The icon is derived from the official SVG logo. I think outlined polygons represent the brand better than filled ones, but I'm open to other opinions. There seems to be no single brand color, the logo is colorful and I couldn't identify a clear brand color on the website either. The hex value is simply the yellow shade of the polygon in the top middle. This choice is mostly arbitrary, perhaps motivated to some extent by the fact that Cilium at its core leverages [ePBF](https://ebpf.io/) whose brand color is a similar shade of yellow.

### CODE REVIEW

**Comment by sisp** [comment]
I just noticed the polygons are not 100% equidistant. It seems the one in the middle is shifted upwards. Should we fix it here or stick with the original layout?

**Comment by sisp** [comment]
I've submitted a PR at Cilium to fix the logo: https://github.com/cilium/cilium/pull/19216

**Comment by sisp** [comment]
My PR at Cilium has been merged, so this icon and the new original logo are in sync.

**Review by dirien — APPROVED** [review]
hi @sisp,

great work! Love the PR at the folks from cilium to fix it there too!

**Pull request merged**
