### PR TITLE
Add Minds icon (#802)

### PR DESCRIPTION
**Pull request by phatbhoy67**
**Issue: #802**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with ~SVGO or~ SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

An interpretation of the [official logo .svg](https://cdn-assets.minds.com/front/dist/en/assets/logos/bulb.svg) available in the header of the [Minds website](https://www.minds.com/) using a combination of lines, fill and negative space to remove/represent colour.

Hex value `#FED12F` is from the logo.

Built on GitPod, working as expected.

### CODE REVIEW

**Comment by birjolaxew** [comment]
This monochromization looks good to me. Only minor thing I'd like is if the lines could be updated to have the same width - it looks like the negative lines are currently significantly thicker than the non-negative ones.

Other than that, I'm happy with merging this. I'll let another @simple-icons/maintainers merge, since this is a custom interpretation.

**Comment by phatbhoy67** [comment]
Hey @birjolaxew see below for new version with line thickness match (TL).

Happy to update PR if this version is preferred.

minds-option-thinner

**Comment by birjolaxew** [comment]
That looks great! I definitely think the TL version is more in line with the original logo.

I'll let another maintainer merge this in, but this gets the green light from me.

**Comment by phatbhoy67** [comment]
> I'll let another maintainer merge this in, but this gets the green light from me.

I'll update the PR now. 👍

**Comment by foo-dogsquared** [comment]
I'll merge this in. 
The TL version looks good to me.

**Pull request merged**
