### PR TITLE
Angular joins the family

### PR DESCRIPTION
**Pull request by whoisjorge**
🚶

### CODE REVIEW

**Comment by birjolaxew** [comment]
Thanks for the contribution! Can I ask where the `#B52E31` color comes from? It seems like [their press kit](https://angular.io/presskit) uses either `#DD0031` (for the base color) or `#C3002F` (for the shadow color).

**Comment by whoisjorge** [comment]
Yeah! I _googled_ it and ended up [this](https://brandcolors.net/b/angularjs) :relaxed:

**Comment by birjolaxew** [comment]
I can't find `#B52E31` mentioned anywhere official (even in the source link from brandcolors.net); could you change the color to the officially used `#DD0031` instead?

**Comment by whoisjorge** [comment]
Of course, thank you! Sorry for the mess about the commits, I'm pretty beginner using Git 🥇

**Comment by birjolaxew** [comment]
Great! One last thing, could you make sure you follow [our contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) (namely add a `<title>`, `aria-labelledby="title"` and `role="img"`)?

**Comment by whoisjorge** [comment]
Sure! I saw that not every icon has those specs, so I _accidentally_ forgotten 😸

**Comment by birjolaxew** [comment]
:+1:

**Pull request merged**
