### PR TITLE
Add Apostrophe icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** N/A
**Alexa rank:** [~380k](https://www.alexa.com/siteinfo/apostrophecms.com)
**Website:** https://apostrophecms.com/
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I took the logo at https://github.com/apostrophecms/apostrophe/blob/a7fcc6b13831302e27f79a6fcaaf58e3a40517df/logo.svg (can also be found inthe website header)
- I took Inkscape to scale and adjust
- I took https://jakearchibald.github.io/svgomg/ to optimize
- I took the darker shade of the gradient found on the website for the color
  - It is also the button color while we click on them
  - It is the color used for slideshow elements
  - Might as well take `#ab92b5` (used for website titles)?

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Could you take another look at this one, please, @service-paradis; there seem to be [some pretty major differences](https://user-images.githubusercontent.com/15157491/108541570-82555700-72da-11eb-9d49-56da27ec06da.png) (your version in red)?

I agree with the choice of colour, which can also be seen in the menu on their website.

**Comment by service-paradis** [comment]
Wow! Not sure what happens for this one! Will start this again from scratch to be sure!

**Comment by service-paradis** [comment]
Should be better now!
Still dont understand what happened the first time 😅

**Comment by service-paradis** [comment]
Thanks @PeterShaggyNoble, I should have mentioned that I also tried to remove it without luck!

**Pull request merged**
