### PR TITLE
Add ICON

### LINKED ISSUE #2158: ICON
**Name:**   icon
**Website:** https://icon.foundation
**Official resources for icon and color

icon_logo

**color** : ** #63B7BF **

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
ICON

**Issue:** Closes #2158

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Colour lifted from [favicon](https://icon.foundation/resources/image/favicon.ico). Possible alternatives from website stylesheet: `#1aaaba` or `#0e9cbc`

### CODE REVIEW

**Comment by birjolaxew** [comment]
Worth noting that they actually provide an [official logo download](https://icon.foundation/contents/resrce/media?lang=en). Confusingly the color used in that download is `#31b8bb`.

They don't seem super consistent with their color usage, but I think I would prefer the color from the official vector.

**Comment by PeterShaggyNoble** [comment]
Nice find, @birjolaxew, thanks. I'll compare the icon in the `.ai` file with what I have later on and update it, if necessary, along with the colour.

**Comment by PeterShaggyNoble** [comment]
There were indeed some differences (see original version in grey below, overlaid with path data from the `.ai` file in red) so I've updated the PR.

On the colour, though, I got `#3ebabd` after converting the `.ai` to `.svg`.

**Comment by birjolaxew** [comment]
@PeterShaggyNoble It gets worse. The black .ai file uses `#31b8bb` as far as I can see, while the white one uses `#43b0b7`. Those are both extracted by opening the file in Illustrator (although admittedly an older version).

In the light of that, I think that any color taken from the official vector is fine with me, whether from a SVG conversion or the AI file.

**Comment by PeterShaggyNoble** [comment]
As `#31b8bb` is the only colour that has come up twice, let's go with that.

**Comment by birjolaxew** [comment]
:+1: It actually didn't come up twice (that's the same icon I was talking about both times), but that color is as good as any other ¯\\\_(ツ)_/¯ Thanks for taking care of this one @PeterShaggyNoble!

**Pull request merged**
