### PR TITLE
Added Google Photos

### LINKED ISSUE #1919: Request Google Photos
**Name: Google Photos**
**Website: https://photos.google.com/**
**Official resources for icon and color:**

### PR DESCRIPTION
**Pull request by adamrusted**
googlephotos (1)

Closes #1919
Contributes to #4205

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon extracted from PNG found [here](https://thepartnermarketinghub.withgoogle.com/brands/google-photos/visual-identity/visual-identity/icon/). Colour of `#4285F4` used from [here](https://thepartnermarketinghub.withgoogle.com/brands/google-photos/visual-identity/color-palette/).
Edited in Adobe Illustrator
Optimized using SVGO CLI

### CODE REVIEW

**Comment by fbernhart** [comment]
@adamrusted Thanks for your work. Already looks pretty good so far.

But there are some few edges, that don't appear that clean:

image

I've cleaned up your SVG a little bit, deleted some unnecessary points and therefore reduced file size to about half.

```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Google Photos icon</title><path d="M12.678 16.672c0 2.175.002 4.565-.001 6.494-.001.576-.244.814-.817.833-7.045.078-8.927-7.871-4.468-11.334-1.95.016-4.019.007-5.986.007-1.351 0-1.414-.01-1.405-1.351.258-6.583 7.946-8.275 11.323-3.936L11.308.928c-.001-.695.212-.906.906-.925 6.409-.187 9.16 7.308 4.426 11.326l6.131.002c1.097 0 1.241.105 1.228 1.217-.223 6.723-7.802 8.376-11.321 4.124zm.002-15.284l-.003 9.972c6.56-.465 6.598-9.532.003-9.972zm-1.36 21.224l-.001-9.97c-6.927.598-6.29 9.726.002 9.97zM1.4 11.315l9.95.008c-.527-6.829-9.762-6.367-9.95-.008zm11.238 1.365c.682 6.875 9.67 6.284 9.977.01z"/></svg>
```

Feel free to use this SVG path, compare it against the [source](https://storage.googleapis.com/pe-portal-consumer-prod-wagtail-static/images/Photos_White_Icon.max-1920x1070.png?Expires=1612320292&GoogleAccessId=pe-portal-consumer-prod%40appspot.gserviceaccount.com&Signature=A2qpqvqO9ztD0RqF2nnXlumZ0NVDPNh04hxNthwnIHylKjATufbrmBIAXtlEmOXUWBjuQX5Iz1eqS6hYBe20FEdUYZJxSpADpeHKkv6m63gT0MsNvrRuLfAmJwOKtZ5vrbOdgur9fcnTFTDD3%2FsDpj1X3mRTggn885cXITicieqfVR%2BMr0h1MLcZFFzH%2FrZWS2%2Bd9Mpi2mynTuEYQFRgFCGp5BrENC5eaxgvSF2j1Fvs4tg6jEF90WRnG%2BVBmPJKnwwfpEzvn4bRolgf1zW%2FDXUGAWQNkx1SfEeCR6n2rKsFy6z71INbkfWK%2Fr98B4wJJM6LafRqtf9jP7QU2tKm8A%3D%3D) and merge it, if you're satisfied. 😊

**Comment by adamrusted** [comment]
@mondeja, I'm getting the warning about collinear paths on this icon (as well as Aseprite) - when there doesn't appear to be any unnecessary paths that could cause the issue. Any chance you could investigate?

**Comment by mondeja** [comment]
> @mondeja, I'm getting the warning about collinear paths on this icon (as well as Aseprite) - when there doesn't appear to be any unnecessary paths that could cause the issue. Any chance you could investigate?

I've found an error in the linter concerning a few icons, I will open a pull soon, but Aseprite has two collinear coordinates (see the chained V commands at the end of the path).

**Comment by adamrusted** [comment]
@fbernhart - just merged develop back in to update Linter, seems to be working fine now.
@mondeja looks like that fix did it, thanks! 🎉

**Pull request merged**
