### PR TITLE
jQuery .svg icon!

### PR DESCRIPTION
**Pull request by whoisjorge**
**Edited:** can't replicate Grunt's logo from official sources. 

### Renamed to jQuery issue!

### CODE REVIEW

**Comment by birjolaxew** [comment]
We'd prefer [an official source](https://github.com/gruntjs/gruntjs.com/blob/master/src/media/grunt-logo.svg) for the logo.

**Comment by whoisjorge** [comment]
Okay, I'll see if I can replicate it from the official source. Meanwhile I'm going to open a new pull request for jQuery. The last one! 🔥

**Comment by whoisjorge** [comment]
Well, I think I am not going to be able to replicate the Grunt's logo from the original source ( ~grunt ) :smile: Anyways I'll be using this one on my project (meanwhile). Sorry for the inconveniences!

**Comment by birjolaxew** [comment]
Same deal with jQuery - we'd prefer [an official source](https://brand.jquery.org/logos/) for the logo ;)

**Comment by whoisjorge** [comment]
Ok. Sorry for the inconveniences!

**Pull request closed without merging**
