### PR TITLE
Add FTX icon

### LINKED ISSUE #6008: Add FTX
**Brand Name: FTX**
**Website: https://ftx.com**
**Alexa rank: 2,967**
  

**Official resources for icon and color:**
[AI File](https://help.ftx.com/hc/en-us/article_attachments/360042714852/ftx_final.ai)
[EPS File](https://help.ftx.com/hc/en-us/article_attachments/360042714872/ftx_final.eps)

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** Close #6008
**Alexa rank:** [~2.7k](https://www.alexa.com/siteinfo/ftx.com)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I used the `.ai` file found at https://help.ftx.com/hc/en-us/articles/360036096791-Media-Kit
- I used Inkscape to scale and adjust
- I used https://jakearchibald.github.io/svgomg/ to optimize
- I took the color from their stylesheet

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
HI @service-paradis,

can you fix the lint issue so I can start to review your PR?

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @service-paradis,

I used the svg from their site (https://help.ftx.com/hc/en-us/article_attachments/4409987735700/FTX_Logo_white.svg) and see a difference:

image

I don't have an option to work with .ai files.

**Comment by adamrusted** [comment]
@service-paradis - FTX have filed for bankruptcy since this PR was submitted, and are no longer trading. Are you happy for us to close this one out?

**Comment by service-paradis** [comment]
> @service-paradis - FTX have filed for bankruptcy since this PR was submitted, and are no longer trading. Are you happy for us to close this one out?

Oh, sure!!

**Pull request closed without merging**
