### PR TITLE
Added De'Longhi

### LINKED ISSUE #4425: Delonghi
Name: De'Longhi
Website: [delonghi.com](https://www.delonghi.com)
Alexa rank: [38,222](https://www.alexa.com/siteinfo/delonghi.com)

Official resources for icon and color:
- image
- image

### PR DESCRIPTION
**Pull request by adamrusted**
delonghi

**Issue:** Fixes #4425
**Alexa rank:** [38,222](https://www.alexa.com/siteinfo/delonghi.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG found [here](https://www.delonghi.com/Global/InstructionManuals/GB/GB-5713213801.pdf) in instruction manual.
Converted in Adobe Illustrator.
Ran through SVGOMG and SVGlint.

### CODE REVIEW

**Comment by fbernhart** [comment]
The logo is perfect. 👍🏼 But I'm not sure about the color choice:

- A lot of the elements on [their website](https://www.delonghi.com/de-de) use `#052644`.
- [The banner](http://www.delonghi-presse.de/wp-content/uploads/2018/03/presse-banner2.png) on their [German press site](http://www.delonghi-presse.de) uses `#033065` as background for the logo.
- On their [Facebook page](https://www.facebook.com/DeLonghiDeutschland) they are using `#0B233F` as background for the [profile picture](https://scontent-muc2-1.xx.fbcdn.net/v/t1.0-9/p960x960/130342873_3058487770918962_4456100735303688687_o.jpg?_nc_cat=105&ccb=2&_nc_sid=85a577&_nc_ohc=g5M5VPEgJ2oAX8ta2Y_&_nc_ht=scontent-muc2-1.xx&tp=6&oh=1a0030d0f716b831d9955118ed702f41&oe=601B1297).

I haven't found any place where they use the color you're proposing in your PR.

**Comment by adamrusted** [comment]
@fbernhart Before I push the update with the PDF link, I've been able to find a [media pack](https://www.delonghigroup.com/en/media/press-kit) which uses `#072240` as the colour of the logo, but it's a PNG, so could be wrong.

**Comment by fbernhart** [comment]
@adamrusted Which file are you talking about? Visiting your link, clicking on the "PDF symbol" of "Images" I'm getting this ZIP file: https://www.delonghigroup.com/sites/default/files/Press_kit_DeLonghi2020_2%20%283%29.zip

Which contains the `Logo_DL_P289.png` file, which has `#062240` as color. 🤔 Was your `#072240` just a typo?

**Comment by adamrusted** [comment]
> @adamrusted Which file are you talking about? Visiting your link, clicking on the "PDF symbol" of "Images" I'm getting this ZIP file: https://www.delonghigroup.com/sites/default/files/Press_kit_DeLonghi2020_2%20%283%29.zip

Thats the one!

> 
> Which contains the `Logo_DL_P289.png` file, which has `#062240` as color. 🤔 Was your `#072240` just a typo?

I literally copy pasted it from Illustrator, guess there's some *slight* variance across the PNG

**Comment by fbernhart** [comment]
Strange. 🤔  The color picker in Chrome as well as in GIMP is showing me `#062240`. And I've picked at different places all over the logo now.

On the other hand I can't imagine that such a professional tool as Illustrator is wrong. 😄 


@simple-icons/maintainers any opinions on which color to choose? `#052644`, `#0B233F`, `#062240`, `#072240`?

**Comment by service-paradis** [comment]
Just to add a little more confusion, the main blue color used in their [canadian website](https://www.delonghi.com/en-ca) is `#0c2645` 😅 
Their [italian website](https://www.delonghi.com/it-it) (which looks like the german one) uses mostly `#052644`.

> Which contains the `Logo_DL_P289.png` file, which has `#062240` as color. 🤔 Was your `#072240` just a typo?

Just opened the same logo in Illustrator and Photoshop. Both gave me `#072240`. Maybe we should go for this one?

**Comment by adamrusted** [comment]
> Just opened the same logo in Illustrator and Photoshop. Both gave me `#072240`. Maybe we should go for this one?

Happy to push `#072240` unless another @simple-icons/maintainers has an objection? 😅

**Comment by fbernhart** [comment]
As all these colors look more or less the same and in absence of an official style guide, I think we should just go for one color.

I'm supporting `#072240`. 👍🏼  @adamrusted Feel free to directly merge it after pushing the new color.

**Comment by adamrusted** [comment]
> I'm supporting `#072240`. 👍🏼 @adamrusted Feel free to directly merge it after pushing the new color.

Consider it merged! 🤣

**Pull request merged**
