### PR TITLE
Add Filament icon

### LINKED ISSUE #10344: Request: FilamentPHP
### Brand Name

FilamentPHP

### Website

https://filamentphp.com/

### Popularity Metric

The filamentphp rank is 127,898 .

image

### Official Resources for Icon and Color

none

### Additional Comments

_No response_

### LINKED ISSUE #10935: Request: Filament
### Brand Name

Filament

### Website

https://filamentphp.com/

### Popularity Metric

The similar web rank is 80,339. See https://www.similarweb.com/website/filamentphp.com/#overview

### Official Resources for Icon and Color

PNG Icon: https://filamentphp.com/favicon/apple-touch-icon.png
GitHub profile image: https://avatars.githubusercontent.com/u/64450473

### Additional Comments

Currently, I'm searching to see if there's an SVG, and I believe we can keep the SVG in the same style as PNG image above instead of the full name (like in GitHub image)

### PR DESCRIPTION
**Pull request by anhthang**
image

**Issue:** closes #10344

**Popularity metric:**

[GitHub Repo stars](https://github.com/filamentphp/filament)

The similar web rank is 80,339. See https://www.similarweb.com/website/filamentphp.com/#overview

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

SVG and hex value `#fdae4b` extracted from the website

### CODE REVIEW

**Review by uncenter — CHANGES_REQUESTED** [review]
Seeing slight differences all over. Try increasing the precision when optimizing?

Screenshot 2024-05-27 at 12 02 22 (Inkscape)

**Comment by anhthang** [comment]
Just checked #10344, what do you guys think about using `fi` only as the favicon

**Comment by adamrusted** [comment]
I'd be happy just using the `fi` as the icon - but would suggest we use the full title as the source as it's a tidier SVG!

**Comment by adamrusted** [comment]
Just a reminder @anhthang - did you want to go with just the `fi` icon here?

**Comment by anhthang** [comment]
@adamrusted `fi` looks better, but Filament seems to be their standard across social media. I think maintaining that consistency is more important.

**Review by uncenter — CHANGES_REQUESTED** [review]
Seeing as this is a large SVG and I'm seeing quite a lot of unnecessary/duplicate nodes (not your fault ahah, just the way the original SVG is), I think it is worth trying to remove some of the ones that aren't affecting the shape. Could you give that a try @anhthang? I usually duplicate the path in my editor, and put one on the bottom with a red fill so I can easily see if deleting a node caused the red to become visible.

**Comment by anhthang** [comment]
@uncenter I have tried to remove a lot of nodes. Would you like to review again?

**Review by mondeja — APPROVED** [review]
Really nice work removing these nodes. Thank you! 👌🏼

**Pull request merged**
