### PR TITLE
Add EditorConfig

### LINKED ISSUE #3567: Request EditorConfig logo
**Name:** EditorConfig
**Website:** https://editorconfig.org/
**Alexa rank:** [290,598](https://www.alexa.com/siteinfo/editorconfig.org)
  

**Rationale:** Similar in character to https://simpleicons.org/?q=pre-commit

**Official resources for icon and color:** https://github.com/editorconfig/editorconfig.github.com/blob/master/logo.png

### PR DESCRIPTION
**Pull request by fbernhart**
EditorConfig

**Issue:** Closes #3567
**Alexa rank:** [350,107](https://www.alexa.com/siteinfo/editorconfig.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
**Source:** PNG from this comment https://github.com/simple-icons/simple-icons/issues/3567#issuecomment-754870261
**Color:** I took `#E0EFEF` from the website's background. But I'm open to use another color. How about white or black?

**Note:** This has been a manual vectorization.

### CODE REVIEW

**Review by PeterShaggyNoble — APPROVED** [review]
That looks good to me, @fbernhart 👍🏻 Nice work. No major differences that I can see and the minor ones we can put down to me not being able to _quite_ line it up exactly with the original.

As it's a manual vectorisation, though, we'll need one of the other @simple-icons/maintainers to approve it too.

I'd also like, if we can, to get @treyhunner's approval as well and feedback on the choice of colour as it looks to me, from their website, like `#fefefe` would be an equally valid choice.

**Review by service-paradis — APPROVED** [review]
Good job @fbernhart, I'm OK with the minor differences for this one 💯

**Comment by treyhunner** [comment]
Exciting that EditorConfig will have a vectorized version of the logo!

Which color is an interesting question since I don't believe we have an official color palette. It does look like the website colors have become the unofficial color palette though (the [VS Code extension uses the background color](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)).

I suspect `#FEFEFE` might be more suitable if just one color was used since the logo is always shown in white when on its own ([example](https://miro.medium.com/max/1384/1*jVvYGygmWHpLQJGIkVO7EA.png)).

Both look pretty good though.

image

What is that color usually used for?

**Comment by fbernhart** [comment]
@treyhunner Thanks for your feedback.

The color is provided as HEX value alongside the SVG icon on our website. --> https://simpleicons.org So that the users of the icons have an official brand color as orientation.

**Comment by adamrusted** [comment]
I would also probably agree on `#FEFEFE` as the 'brand colour', given the inner of the icon always appears in that white. Would you mind changing the hex @fbernhart?

**Comment by fbernhart** [comment]
@adamrusted Done 👍🏼 

editorconfig

**Comment by treyhunner** [comment]
> @treyhunner Thanks for your feedback.
> 
> The color is provided as HEX value alongside the SVG icon on our website. --> https://simpleicons.org So that the users of the icons have an official brand color as orientation.

Thanks for clarifying @fbernhart!

This looks great to me. Thanks so much! 🎉

**Comment by PeterShaggyNoble** [comment]
Based on the approval of multiple maintainers and, more importantly, an official representative, this one can now be merged in.

Nice work, @fbernhart 👍🏻 And thanks for taking the time to assist us, @treyhunner; it's much appreciated 🙂

**Pull request merged**
