### PR TITLE
Add Komoot

### LINKED ISSUE #2862: Komoot
Name: Komoot
Website: komoot.com
Official resources for icon and color: Don't have.

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Komoot

**Issue:** Closes #2862, following on from #2878 & #2949

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon is based on the black version on `SVG\Komoot_Logo_Monochromatic_Black_RGB (v2.1).svg` in [this zip](https://d21buns5ku92am.cloudfront.net/67683/documents/42573-1594397815-Komoot%20Logo%20Vector%20v2.1%20RGB-67ec60.zip), colour from page 12 of [this PDF](https://d21buns5ku92am.cloudfront.net/67683/documents/42569-1594397095-Komoot%20Identity%20Guide%20v2.1-885de4.pdf).

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Hmm 🤔 your links to the SVG and PDF don't work anymore and I also wasn't able to find a file with the exact name you specified. Based on that I'm going to assume that they slightly altered their logo (the files are now suffixed with `v2.1`). And as a result, your version seems to be outdated already, at least based on my comparison. The discrepancies are with the circle in the center and the pointy thing at the bottom.

Could you update the PR with one of the new files? I suspect everything will be fine then.

image

**Comment by PeterShaggyNoble** [comment]
Yep, from the cover date on [their updated identity guide](https://d21buns5ku92am.cloudfront.net/67683/documents/42569-1594397095-Komoot%20Identity%20Guide%20v2.1-885de4.pdf), it looks like they tweaked their branding, including the colours, in the past couple of weeks. I'll get this fixed momentarily.

**Comment by PeterShaggyNoble** [comment]
PR updated with the new icon and colour.

**Comment by ericcornelissen** [comment]
Looking good now, thanks for the addition @PeterShaggyNoble :smile:

**Pull request merged**
