### PR TITLE
Update MDN logo

### PR DESCRIPTION
**Pull request by eritbh**
**Issue:** #7188
**Similarweb rank:** unknown, couldn't get the similarweb site to work
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

There doesn't seem to be a singular brand color in the new site design; the header icon, etc. all just use the same color as links in the website, which change color depending on the page color scheme. So I left the brand color as `#000000`; there were no edits to the JSON necessary.

Preview of updated icon:

mdnwebdocs

### CODE REVIEW

**Comment by sachinraja** [comment]
image
There are some very slight differences down the center. Can you try increasing the precision:
https://github.com/simple-icons/simple-icons/blob/83ef249e5568bf1ec7d81f810009b8057c7c2b38/svgo.config.js#L23
(make sure to change it back when you commit though)

**Comment by eritbh** [comment]
Excuse the force-push. I've updated the branch with a re-optimized icon with `floatPrecision` 8 instead of 3, which might be overkill; I'm not sure.

It's also possible that the misalignment comes from the way I resized the image to 24x24. The original source I used, and which you may be comparing against, has a sub-pixel, barely noticeable gap between the right edge of the "M" and the right edge of the SVG vdocument/viewbox. When resizing the image for this PR, I scaled the icon in such a way that in my version there is no gap along the right edge; if this is an undesirable change, I can maintain it instead.

**Comment by sachinraja** [comment]
> barely noticeable gap between the right edge of the "M" and the right edge of the SVG vdocument/viewbox

Can you take a screenshot of this? I don't see it.

**Comment by sachinraja** [comment]
Still not seeing that, here's a video of what I did:

https://user-images.githubusercontent.com/58836760/158916520-2d1041dc-b796-42ae-aff6-5f4082537d57.mp4

**Comment by eritbh** [comment]
Yeah, the video you sent is functionally identical to what I did to resize it as well, I just opened the document itself rather than importing into a pre-sized document. If there's still inconsistencies with the latest commit on my branch, it's probably something else; let me know what you see so I can investigate.

Also going to look into the lint errors about collinear points soon.

**Comment by sachinraja** [comment]
Awesome, it's a perfect match with [the GitHub source](https://github.com/mdn/yari/blob/809e4dad63027b83b5f03008afaf97752f8dce44/client/src/assets/m-logo.svg).

**Comment by sachinraja** [comment]
> Also going to look into the lint errors about collinear points soon.

Maybe @jorgeamadosoria can help with that as he has experience with it. I tried just removing them but that breaks the icon.

**Comment by jorgeamadosoria** [comment]
I reworked it from the SVG in the header in the source page. I don't see collinear issues, and precision is 3.
Can someone check if I didn't introduce a different error, please? @eritbh @sachinraja

**Comment by sachinraja** [comment]
Still seeing the same differences from https://github.com/simple-icons/simple-icons/pull/7189#issuecomment-1069151750 @jorgeamadosoria

**Comment by jorgeamadosoria** [comment]
> Still seeing the same difference from [#7189 (comment)](https://github.com/simple-icons/simple-icons/pull/7189#issuecomment-1069151750) @jorgeamadosoria

image

What are you using for comparison? My source is the header SVG logo at https://developer.mozilla.org/. I removed the MDN letters and the little horizontal line, and optimized with precision 3, and I don't see a difference with the source SVG afterwards.
So, what are you using to compare against?

**Comment by sachinraja** [comment]
Thanks, that matches perfectly @jorgeamadosoria. I was comparing against the icon from https://github.com/simple-icons/simple-icons/pull/7189#issuecomment-1070959395

**Review by sachinraja — APPROVED** [review]

**Comment by sachinraja** [comment]
Thanks both of you!

**Comment by eritbh** [comment]
Thanks for all the help bot of you, happy to see this merged! 🎉

**Pull request merged**
