### PR TITLE
Add Nunjucks Icon

### LINKED ISSUE #7172: Request: Nunjucks
### Brand Name

Nunjucks

### Website

https://mozilla.github.io/nunjucks/

### Popularity Metric

7.7k GitHub Stars

### Official Resources for Icon and Color

https://github.com/mozilla/nunjucks/blob/master/docs/img/favicon.png
Color: #1C4913

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by simonfarah**
nunjucks

**Issue:** closes #7172 

**GitHub Stars:** [7.8k](https://github.com/mozilla/nunjucks)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The hex value (1C4913) is the one used in the original logo. The logo was provided as PNG and I vectorized it manually on Adobe Illustrator.

### CODE REVIEW

**Review by sachinraja — CHANGES_REQUESTED** [review]
Seeing a difference:
image

green is original, white is the one from this PR

**Review by sachinraja — APPROVED** [review]
Still seeing a slight difference, but I think it's close enough considering the source is a PNG.

**Comment by sachinraja** [comment]
I can't push to your branch so please run `git merge upstream/develop` to update your branch.

**Comment by simonfarah** [comment]
> I can't push to your branch so please run `git merge upstream/develop` to update your branch.

Done!! And as you said, for the future I'll be making changes on a new branch.

**Pull request merged**
