### PR TITLE
Added BookStack

### LINKED ISSUE #3722: Icon Request: Bookstack
**Name:** Bookstack
**Website:** bookstackapp.com
**Alexa rank:** 418,990
  

**Official resources for icon and color:** Unsure sorry

### PR DESCRIPTION
**Pull request by adamrusted**
bookstack

**Issue:** Fixes #3722
**Alexa rank:** [259,548](https://www.alexa.com/siteinfo/bookstackapp.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG pulled from website header. Inverted for better clarity at smaller screen sizes. Hex from SVG.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
This looks good to me, @adamrusted other than some minor differences top & bottom. However, with Inkscape not wanting to play nice with the strokes _at all_, I found it difficult to do an _exact_ comparison so I'd like one of the other @simple-icons/maintainers to double check it before merging it or asking you to make changes.

**Comment by mondeja** [comment]
I think that this icon shouldn't be inverted because the color of the stroke `#0288D1` is different than the background (`#0078B9`) and it loses the round corners.

**Comment by adamrusted** [comment]
Think I need to get my eyes checked - didn't spot that the stroke was a different colour to the background! 😅
Let me re-build this with just the outline, see how that is for us.

**Review by mondeja — COMMENTED** [review]
Thank you @adamrusted. I'm seeing a minor difference in height between your version (red, 22,784 px) and the source (blue, 22,771 px), possibly due to optimization process. Could you check that?

image

**Comment by adamrusted** [comment]
@mondeja weird - there's no difference on my end, when rebuilding from source (blue) against pr (black). This is comparing against the optimized path too... 🤔
image

**Comment by mondeja** [comment]
I've checked another time and still seeing the difference :thinking:  Let's wait for a new review from @PeterShaggyNoble to clarify this doubt.

**Comment by PeterShaggyNoble** [comment]
Yep, I'm seeing the same difference. I had an issue converting the strokes to paths in Inkscape when I gave this one a try that resulted in a similar difference so that may be the issue here.

I'm of the opposite opinion to @mondeja, though, and think that your initial filled version is the way to go as it matches the logo in [their GH org](https://github.com/BookStackApp) and [their Discord](https://discord.gg/ztkBqR2) - I'm guessing the difference in the 2 blues in their website's header is an error.

**Comment by adamrusted** [comment]
Do any other @simple-icons/maintainers want to chip in on this one? Keen to decide on whether the outline or the block version of this is better so we can look at getting it merged in 🚀

**Comment by ericcornelissen** [comment]
I'm not at al familiar with the brand but based on the logo in [their GH org](https://github.com/BookStackApp) and [their Discord](https://discord.gg/ztkBqR2) I agree that the filled version makes more sense, regardless of colors.

**Comment by adamrusted** [comment]
Cool, assuming we're all happy with the filled version of the icon - this should be good for review.

**Comment by PeterShaggyNoble** [comment]
Inkscape's inability to convert curved strokes to paths without distorting them is really starting to annoy me! Gonna need someone with better software to throw an eye over this one.

**Review by service-paradis — APPROVED** [review]
Oh wow, as simple as this icon looks it is REALLY hard to work with!
Took me way too long before being able to compare it 😅, but it looks good to me!

**Pull request merged**
