### PR TITLE
Updated CSS Wizardry

### PR DESCRIPTION
**Pull request by fbernhart**
csswizardry

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Seeing some slight differences between PR and source. Any chance you could take another look?

image

**Comment by mondeja** [comment]
I'm seeing the same differences also comparing with SVG embedded in website header :+1:

**Comment by fbernhart** [comment]
I've rebuilt it from source now; precision = 3

**Review by adamrusted — APPROVED** [review]
Perfect! 🌟

**Pull request merged**
