### PR TITLE
Add MAAS

### PR DESCRIPTION
**Pull request by mhf-ir**
**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Alexa rank about [430K](https://www.alexa.com/siteinfo/maas.io)

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for your work on this one, @mhf-ir :+1:

Which version of their icon/logo did you base your on SVG, though? Using the logo in the header I get a different result - original in grey below, yours in red.

Also, the orange they use in that SVG is `#e95420` so we should go with that too.
MAAS

**Comment by mhf-ir** [comment]
I found svg version on internet:
https://www.2600index.info/Links/33/3/assets.ubuntu.com/v1/33b96a7f-maas-logo.svg
also get colour from it. Seems the same.

Yeah i breakdown and union with inkscape, it's wrong?

**Comment by PeterShaggyNoble** [comment]
Can you update to use the icon & colour from the official SVG, which can be found in their website header, please?

**Comment by mhf-ir** [comment]
Sure i will try

**Comment by mhf-ir** [comment]
Recreated via : https://design.ubuntu.com/downloads/

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @mhf-ir and nice find with those brand assets 😀 This looks good to go now.

**Pull request merged**
