### PR TITLE
Add Picrew icon

### LINKED ISSUE #11058: Request: Picrew
### Brand Name

Picrew

### Website

https://picrew.me/en/

### Popularity Metric

Ranked 3,796 globally on Similarweb. See https://www.similarweb.com/website/picrew.me/#overview.

### Official Resources for Icon and Color

SVG encoded in header:
```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 62"><g id="レイヤー_2" data-name="レイヤー 2"><path fill="#fff" d="M199.4,42.69a11.65,11.65,0,0,1-10.56,8.2,13.57,13.57,0,0,1-10.78-4.53c-5.24,6-15.42,6.21-19.82-.56-4.33,3.08-11,5.09-17.52,5.09-8.79-.29-13.1-3.22-19.06-7.93-6.34-5.9-15.36-1.2-19.53,6.12v10a2.4,2.4,0,0,1-4.79,0V46.38a17.3,17.3,0,0,1-11.73,4.51,17,17,0,0,1-14.94-8.58,11.34,11.34,0,0,1-12.86.08c-4.86,9.09-15.06,14.3-28,14.3-10.19,0-18.66-3.2-24.18-9V59.07a2.4,2.4,0,0,1-4.8,0V40a2.44,2.44,0,0,1,1-2,2.4,2.4,0,0,1,3.45.8c3.8,8.5,12.67,13.08,24.49,13.13s22.42-5.22,24.85-14.77a2.37,2.37,0,0,1,1.23-1.37,2.41,2.41,0,0,1,3.12,1c2.06,3.73,8.37,3.72,10.43,0a2.41,2.41,0,0,1,4.08-.17,2.29,2.29,0,0,1,.33.75,12.33,12.33,0,0,0,23.61,0,2.4,2.4,0,0,1,4.66.05c.11.29.05,3.57.06,3.94,3.64-3.49,8.31-5.8,12.44-5.8,7.63-.26,10.24,4.68,15.57,7.65a21.18,21.18,0,0,0,10.58,2.93c7.11,0,13.7-2.58,17.07-6.21a2.42,2.42,0,0,1,3.49,1.34c2,6.51,11.46,6.55,14.55-.14a2.39,2.39,0,0,1,4.34-.26,8.62,8.62,0,0,0,8.38,5.27,6.9,6.9,0,0,0,6.29-4.87,2.39,2.39,0,0,1,4.56,1.46ZM64.17,46.1a2.39,2.39,0,0,0-2.39,2.4V59.07a2.4,2.4,0,1,0,4.79,0V48.5A2.39,2.39,0,0,0,64.17,46.1Z"/><path fill="#fff" d="M18.91,21.4a.31.31,0,0,1,.32-.33,5,5,0,0,1,3.65,1.79A8.6,8.6,0,0,1,24.62,28a.29.29,0,0,1-.34.31C20.36,27.79,19.37,26.48,18.91,21.4Zm-1.22,0a.31.31,0,0,0-.32-.33,5,5,0,0,0-3.65,1.79A8.6,8.6,0,0,0,12,28a.29.29,0,0,0,.34.31C16.24,27.79,17.23,26.48,17.69,21.4Zm-5.37,8.31A.3.3,0,0,0,12,30a8.62,8.62,0,0,0,1.74,5.18A5,5,0,0,0,17.37,37a.31.31,0,0,0,.32-.33C17.23,31.59,16.24,30.27,12.32,29.71Zm6.59,7a.31.31,0,0,0,.32.33,5,5,0,0,0,3.65-1.79A8.62,8.62,0,0,0,24.62,30a.3.3,0,0,0-.34-.32C20.36,30.27,19.37,31.59,18.91,36.67ZM40.61,21.4a.31.31,0,0,0-.32-.33,5,5,0,0,0-3.65,1.79A8.6,8.6,0,0,0,34.9,28a.29.29,0,0,0,.34.31C39.16,27.79,40.15,26.48,40.61,21.4Zm6.59,7a.29.29,0,0,0,.34-.31,8.6,8.6,0,0,0-1.74-5.18,5,5,0,0,0-3.65-1.79.31.31,0,0,0-.32.33C42.29,26.48,43.28,27.79,47.2,28.35Zm-5.37,8.32a.31.31,0,0,0,.32.33,5,5,0,0,0,3.65-1.79A8.62,8.62,0,0,0,47.54,30a.3.3,0,0,0-.34-.32C43.28,30.27,42.29,31.59,41.83,36.67Zm-6.59-7a.3.3,0,0,0-.34.32,8.62,8.62,0,0,0,1.74,5.18A5,5,0,0,0,40.29,37a.31.31,0,0,0,.32-.33C40.15,31.59,39.16,30.27,35.24,29.71Zm142.82-8a2.4,2.4,0,0,0-2.4,2.4v7.3a2.4,2.4,0,1,0,4.79,0v-7.3A2.39,2.39,0,0,0,178.06,21.68Zm-17.84-3.27a2.39,2.39,0,0,0-2.39,2.39V31.38a2.4,2.4,0,1,0,4.79,0V20.8A2.39,2.39,0,0,0,160.22,18.41Zm35.67,0a2.39,2.39,0,0,0-2.39,2.39V31.38a2.4,2.4,0,1,0,4.79,0V20.8A2.39,2.39,0,0,0,195.89,18.41Zm-42.72,13a2.41,2.41,0,0,1-2.4,2.4H128c0,.3,0,.59,0,.88a2.4,2.4,0,0,1-4.79,0,20,20,0,0,1,.41-3.77c2.18-12,16.69-16.37,25.39-8.54A12.41,12.41,0,0,1,153.17,31.38ZM129.25,29h18.66a8.22,8.22,0,0,0-2.16-3.12,10.87,10.87,0,0,0-7.39-2.67A10.11,10.11,0,0,0,129.25,29ZM85.61,18.41A17,17,0,0,0,70.67,27a11.17,11.17,0,0,0-6.49-2,11.29,11.29,0,0,0-5.51,1.41,35.63,35.63,0,0,0-6.58-15.85,5.68,5.68,0,0,1-.81-1.25c.11-7.95-9.56-11.65-15.19-6-.17.17-.32.34-.43.47a6.21,6.21,0,0,1-1.1-.06,42.44,42.44,0,0,0-4.8-.24,56.86,56.86,0,0,0-5.88.33C18.52-2.52,8.13,1,8.24,9.26a5.68,5.68,0,0,1-.81,1.25A36.36,36.36,0,0,0,.49,29.15a2.4,2.4,0,0,0,4.78.42,31.38,31.38,0,0,1,6-16.15A6.72,6.72,0,0,0,13,9.26a3.59,3.59,0,0,1,2.23-3.58A4.22,4.22,0,0,1,20.2,6.81c1.26,1.54,2.57,2,5.23,1.6a39.31,39.31,0,0,1,4.33-.21,39.31,39.31,0,0,1,4.33.21c2.8.41,4.08-.15,5.33-1.72a4.22,4.22,0,0,1,4.84-1,3.59,3.59,0,0,1,2.23,3.58,6.72,6.72,0,0,0,1.79,4.16,31.38,31.38,0,0,1,6,16.15c.17,1.64,0,3.07,1.45,3.9a2.4,2.4,0,0,0,3.31-1,6.25,6.25,0,0,1,10.38.09A2.4,2.4,0,0,0,73.8,32,12,12,0,0,1,85.61,23.2,12.26,12.26,0,0,1,96,28.65,2.4,2.4,0,1,0,100,26,17,17,0,0,0,85.61,18.41Z"/></g></svg>
```
Color: `#ffbd16` (from footer)

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by anhthang**
image

**Issue:** closes #11058 

**Popularity metric:**
Ranked 3,796 globally on Similarweb. See https://www.similarweb.com/website/picrew.me/#overview.

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

SVG and hex value `#ffbd16` extracted from the website

### CODE REVIEW

**Review by uncenter — CHANGES_REQUESTED** [review]
Screenshot 2024-05-30 at 13 49 03 (Inkscape)
Seeing some differences, try raising the precision?

**Review by uncenter — CHANGES_REQUESTED** [review]
Screenshot 2024-06-01 at 17 00 35 (Inkscape)

Still seeing differences.

**Comment by anhthang** [comment]
it seems still having differences when I increased the precision to 5

image

without that, the icon size keeping down from 24 -> 23.995 -> 23.998 when I try to optimize. is there any ideas to fix it?

**Comment by uncenter** [comment]
Hmm I think you are right, upon closer inspection by hand there aren't really any perceptible differences. I'm good with as is, though I won't merge this yet - I want another @simple-icons/maintainers to make sure I'm not missing anything!

**Review by uncenter — APPROVED** [review]

**Review by adamrusted — APPROVED** [review]
LGTM, thanks @anhthang and @uncenter!

**Pull request merged**
