### PR TITLE
Add Trustpilot icon (#2004)

### LINKED ISSUE #2004: TrustPilot icon request
Please add a TrustPilot icon: https://www.trustpilot.com/

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
Closes #2004

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I stenciled the dark part of star out. This gives imho a good monochrome representation of the brand. The color `#00b67a` is eyedropped from the lighter green part of the star.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @runxel thanks for taking on this issue 👍 

Hex value chosen is confirmed as the light green in the [logo](https://cdn.trustpilot.net/brand-assets/1.1.0/logo-white.svg). 🎨 

Your manual stencil version is a very good effort but just a little bit off. 

Can you please update the PR to use the mono version of the "star" available on (https://www.trustpilot.com/) - you can isolate the "star" from the 5 star bar which you can either grab with svg grabber or download from (https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg).

**Comment by runxel** [comment]
Aw maaaan, @phatbhoy67 😄
That's so close. You're a nice detective, I can say that 👍

**Comment by PeterShaggyNoble** [comment]
The source URL should probably be either [the brand guidelines](https://support.trustpilot.com/hc/en-us/articles/206289947-Trustpilot-Brand-Assets-Style-Guide) or the homepage.

**Comment by runxel** [comment]
Thanks for the link, @PeterShaggyNoble! :)
I've incorporated it.

**Comment by phatbhoy67** [comment]
Thanks for updating the the .svg @runxel and thanks @PeterShaggyNoble for review, merging this one in 👍

**Pull request merged**
