### PR TITLE
Update Visa icon

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** NA
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Visa slightly updated their logo and primary color in 2019 (https://webdesignledger.com/visa-logo-redesign/)

- I took the logo in their brand guidelines (https://merchantsignageeu.visa.com/product.asp?dptID=696)
- I updated the source
- I took the color from the blue logo (without gradient)
- I used Illustrator and Inkscape to scale and adjust the icon
- I used https://jakearchibald.github.io/svgomg/ to opitmize

### CODE REVIEW

**Comment by fbernhart** [comment]
LGTM! 👍🏼 

Strange that opening the EPS file in Inkscape I get `#1D337A` as color, while opening the AI file I get `#1A1F71`. Just wondering: Is this an Inkscape thing, which happens while converting EPS to SVG? Or do you get the same result in Illustrator? 🤔 

But anyway, a quick Google search led me to [this official site](https://usa.visa.com/run-your-business/accept-visa-payments/posguidelines.html), where the "Visa blue" is mentioned as `#1A1F71`.

So this can be merged. 💯

**Comment by service-paradis** [comment]
> Strange that opening the EPS file in Inkscape I get `#1D337A` as color, while opening the AI file I get `#1A1F71`. Just wondering: Is this an Inkscape thing, which happens while converting EPS to SVG? Or do you get the same result in Illustrator? 🤔

I dont know why the color is not the same depending on tools. Kind of weird 😕 
I got `#1A1F71` by opening the AI file in Illustrator. Good catch for the POS website to confirm it! 💯

**Comment by PeterShaggyNoble** [comment]
@fbernhart & @service-paradis, the EPS may use a different colour system, such as CMYK, where there are some colours that don't directly translate to hex equivalents, as such you may see different results when using different tools to convert from EPS to SVG.

**Comment by fbernhart** [comment]
@PeterShaggyNoble Good to know. Thanks 👍🏼

**Comment by service-paradis** [comment]
> @fbernhart & @service-paradis, the EPS may use a different colour system, such as CMYK, where there are some colours that don't directly translate to hex equivalents, as such you may see different results when using different tools to convert from EPS to SVG.

Make sense, thank you for the explanation 🙇

**Pull request merged**
