### PR TITLE
Add Uploaded

### PR DESCRIPTION
**Pull request by mondeja**
uploaded-preview

- **Issue:** #805
- **Alexa Rank**: [~1400](https://www.alexa.com/siteinfo/uploaded.net)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Logo downloaded from [official website](http://uploaded.net).
- HEX value from [inline website source stylesheet](http://uploaded.net/).
- Manually vectorized with Inkscape based on raster image.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I'm not the best at comparing vector with raster so I'll leave that to one of the other @simple-icons/maintainers.

The choice of colour seems reasonable to me, as it's the fallback colour used when the gradient background image doesn't load.

**Comment by runxel** [comment]
Ahoi @mondeja!
Thanks for this PR! It looks pretty good to me (it doesn't open in Illustrator, but that's a known problem with SVGOMG).
If I would be a nitpicker here there is some inconsistency visible when you rotate the logo.
Maybe you can fix that? Thanks again 🙏  :)

up

**Comment by mondeja** [comment]
I've updated the symmetry of those handlers.

**Comment by mondeja** [comment]
The last test if failed because of they had no support for exponential notation numbers inside paths. It's solved by pull #2946.

**Comment by ericcornelissen** [comment]
> The last test has failed because of tests had not support for exponential notation numbers inside paths. It's solved by pull #2946.

Could you merge our `develop` back in to this branch @mondeja, just to be sure :wink:

**Pull request merged**
