### PR TITLE
Added MEGA icon.

### PR DESCRIPTION
**Pull request by metaa**
# Added Icon
MEGA (#1281)

## Website
https://mega.nz/

## Logo
[logo (click)](https://en.wikipedia.org/wiki/File:01_mega_logo.svg)

## Color
`#D9272E`

## What it will look like
image

### CODE REVIEW

**Comment by davidklebanoff** [comment]
Thanks for the contribution @metaa! The icon looks good.

It looks like their website uses multiple red colors for their brand, but in the absence of an official brand guide I think we have to choose one. Can you clarify where your color choice came from?

**Comment by metaa** [comment]
> Can you clarify where your color choice came from?

This is the very color they use in their on-site logo up here: 
image

and also in the center of this thing:
image

But you're right, even the ring in the cloud got another color already 😞 
I guess the color used in the `M` logo would be more "official", but I'll see if I can dig out any official kind of statement or brand definition!

**Comment by metaa** [comment]
😒 We really should consult Wikipedia more often.

https://en.wikipedia.org/wiki/File:01_mega_logo.svg

**Comment by ericcornelissen** [comment]
Thanks again @metaa :tada: 

> We really should consult Wikipedia more often.

Haha, [it's in the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#1-identify-official-logos-and-colors) actually :wink:

**Comment by metaa** [comment]
> Thanks again @metaa 🎉
> 
> > We really should consult Wikipedia more often.
> 
> Haha, [it's in the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#1-identify-official-logos-and-colors) actually 😉

🤦🏻‍♂️

**Comment by hylickipiotr** [comment]
This PR is also related with issue #805

**Pull request merged**
