### PR TITLE
Update AlloCiné

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
AlloCiné

**Issue:** n/a
**Alexa rank:** [~2.9k](https://www.alexa.com/siteinfo/allocine.fr)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon from [this SVG](https://assets.allocine.fr/skin/img/logo-allocine-287bbe0668.svg) found in [website](https://www.allocine.fr/) stylesheet, fixing an imperfection in the bottom right of the handset in our current version as well as a slight difference in the upper curve of the ticket.

The reason I used that SVG instead of [the main logo](https://assets.allocine.fr/skin/img/allocine/logo-main-12195cd9d9.svg) as the logo has the exact same imperfection in the handset despite, judging from [the original PR](https://github.com/simple-icons/simple-icons/pull/1398), the SVG logo not existing at the time, which makes me wonder if they didn't base it off our icon! 😆 Anyway, an attempt has been made to fix that imperfection in the source I used so I went with that instead.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
@mondeja, could you check the linting on this one, please? Inkscape is giving me a height of `24` for the path in the PR.

**Comment by mondeja** [comment]
I've done something very weird, but has worked with 3 decimals of precision, this is the path:

```
M16.434.001a.826.826 0 00-.164.008l-3.423.543a2.635 2.635 0 01-2.189 3.01 2.629 2.629 0 01-3.01-2.185l-3.417.538a.818.818 0 00-.677.931l3.24 20.467a.818.818 0 00.931.677l3.423-.543a2.635 2.635 0 012.189-3.01 2.629 2.629 0 013.01 2.185l3.422-.543a.818.818 0 00.677-.93L17.2.685a.816.816 0 00-.767-.685zm-3.22 6.534c.066 0 .128.005.185.017.423.09.975.6 1.315.955.178.187.192.519.048.73l-1.228 1.795a.89.89 0 01-.437.283c-.504.125-1.248-.95-1.771 1.507-.524 2.458.59 1.776 1.003 2.098a.828.828 0 01.283.437l.394 2.14a.613.613 0 01-.341.649c-.456.182-1.167.427-1.589.336-.907-.192-2.342-2.4-1.57-6.044.725-3.415 2.71-4.89 3.708-4.903z
```

I've setted the height on Inkscape to `23,9995`. Although Inkscape only shows 3 decimals, is possible that internally it is defining the size using more decimals :thinking:

**Comment by PeterShaggyNoble** [comment]
Thanks, @mondeja 👍🏻 Just pushed your path. If it works then we'll need one of the other @simple-icons/maintainers to review this before merging.

**Review by service-paradis — APPROVED** [review]
LGTM 💯 🎥 🎦 📽️ 🎞️ 🎬 
Good job @PeterShaggyNoble and @mondeja

**Pull request merged**
