### PR TITLE
Add Flat icon

### LINKED ISSUE #6821: Add Flat icon
### Brand Name

Flat

### Website

https://flat.whiteboard.agora.io

### Popularity Metric

The Alexa rank is: `#17378`

It's main open-source project is https://github.com/netless-io/flat

### Official Resources for Icon and Color

`#3481FE`

The official color comes from the logo. The the value I have already confirmed the design team of Flat.

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by LitoMore**
CleanShot 2021-11-19 at 02 27 56@2x

**Issue:** Resolves #6821 
**Alexa rank:** 17378
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The official color comes from the logo. The the value I have already confirmed the design team of Flat.

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
HI @LitoMore,

can you check the arch on the first part of the icon with the original?

image

there is a difference with the original

**Comment by LitoMore** [comment]
@dirien Thanks for pointing it out. I tried to reproject this icon. But still have this issue. I guess the difference comes from the compressing process. I tried [SVGO: The Missing GUI](https://jakearchibald.github.io/svgomg/) and our `npm run svgo` script, both of them have the same issue.

BTW, I think this difference is acceptable.

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @LitoMore,

i still see a difference
image

with the original. Asking @jorgeamadosoria, if there is a trick expect upping the precision

**Comment by jorgeamadosoria** [comment]
> Hi @LitoMore,
> 
> i still see a difference image
> 
> with the original. Asking @jorgeamadosoria, if there is a trick expect upping the precision

Precision 4 does the trick. I tried and I only get the slightest discrepancy in the top horizontal line, which I think is acceptable.
So, I suggest trying to set precision to 4 and optimize it with the provided svgo command. That should be more than enough.

Alternatively, you can simply copy this path:
`<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Flat</title><path d="M6.5455 17.4545v3.2728C6.5455 22.5348 5.0802 24 3.2727 24S0 22.5348 0 20.7273c0-1.8075 1.4652-3.2728 3.2727-3.2728Zm8.7272-8.7272V12c0 1.8075-1.4652 3.2727-3.2727 3.2727H5.4545c-1.8074 0-3.2727-1.4652-3.2727-3.2727 0-1.8075 1.4653-3.2727 3.2727-3.2727zM24 0v3.2727c0 1.8075-1.4652 3.2728-3.2727 3.2728H7.6363c-1.8074 0-3.2727-1.4653-3.2727-3.2728S5.829 0 7.6364 0Z"/></svg>`

**Review by jorgeamadosoria — CHANGES_REQUESTED** [review]
Changes requested to set precision 4

**Comment by LitoMore** [comment]
@jorgeamadosoria Thank you so much. Updated now. Please review.
cc @dirien

**Review by jorgeamadosoria — APPROVED** [review]

**Comment by jorgeamadosoria** [comment]
good work @dirien and @LitoMore

**Pull request merged**
