### PR TITLE
Add .ENV (dotenv)

### PR DESCRIPTION
**Pull request by motdotla**
dotenv-preview

**GitHub ⭐️**: 15.9k: https://github.com/motdotla/dotenv

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Logo taken from https://github.com/motdotla/dotenv

Thanks for creating a great community logo service!

### CODE REVIEW

**Comment by LitoMore** [comment]
@motdotla I just created the SVG icon for your project, please review https://github.com/motdotla/dotenv/pull/670.

**Comment by motdotla** [comment]
Looks great. Thanks! Merge away.

**Comment by motdotla** [comment]
Need my morning coffee ☕️. Merging there soon and then I will update this PR.

**Comment by motdotla** [comment]
@LitoMore I left some comments there. Once those are ready, I'll update the PR here. Thanks again.

**Comment by motdotla** [comment]
Thanks @LitoMore. All set.

This is ready @dirien for merge.

**Review by LitoMore — APPROVED** [review]
image

Looks good.

**Pull request merged**
