### PR TITLE
Add Monkeytype icon

### LINKED ISSUE #8844: Icon request: Monkeytype
### Brand Name

Monkeytype

### Website

https://monkeytype.com

### Popularity Metric

The Similarweb rank is 8643 (see https://www.similarweb.com/website/monkeytype.com)

### Official Resources for Icon and Color

* PNG logo: https://github.com/monkeytypegame/monkeytype/blob/f5bb1a239550cd75d461f586aa05a289bde7793b/frontend/static/images/icons/maskable_icon_x512.png (preferred by needs an SVG version)
* SVG favicon: https://github.com/monkeytypegame/monkeytype/blob/f5bb1a239550cd75d461f586aa05a289bde7793b/frontend/static/images/favicon/safari-pinned-tab.svg
* Brand colour: `#e2b714` (default website theme is `Serika Dark`, see https://github.com/monkeytypegame/monkeytype/blob/f5bb1a239550cd75d461f586aa05a289bde7793b/frontend/static/themes/serika_dark.css)

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by ddnomad**
**Issue:** closes #8844 

**Similarweb rank:**
* Global Rank: 8643
* Category Rank: 178

See https://www.similarweb.com/website/monkeytype.com

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
* The brand colour was picked following the website's default colour schema (main colour from https://github.com/monkeytypegame/monkeytype/blob/f5bb1a239550cd75d461f586aa05a289bde7793b/frontend/static/themes/serika_dark.css)
* The logo was inverted to improve its legibility (see [original logo PNG](https://github.com/monkeytypegame/monkeytype/blob/f5bb1a239550cd75d461f586aa05a289bde7793b/frontend/static/images/icons/maskable_icon_x512.png))

### Preview
monkeytype

### CODE REVIEW

**Comment by LitoMore** [comment]
@ddnomad Please don't invert their brand/trademark without their permission. Let's keep the style as the original is.

**Comment by ddnomad** [comment]
> @ddnomad Please don't invert their brand/trademark without their permission. Let's keep the style as the original is.

Done, please see the updated brand preview below.

monkeytype

**Review by LitoMore — CHANGES_REQUESTED** [review]
image

@ddnomad I can see some differences. Please make sure that the aspect ratio does not change when resizing.

**Comment by ddnomad** [comment]
@LitoMore the sizing issue should be fixed now, my apologies. Do let me know if you spot anything else!

**Review by LitoMore — APPROVED** [review]
image

@ddnomad Perfect fit now! Thank you for contributing!

**Pull request merged**
