### PR TITLE
Add Altium Designer

### PR DESCRIPTION
**Pull request by TSprech**
Altium Designer Preview

**New Icon**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The hex values was pulled from the CSS for the [main site](https://www.altium.com/). The logo came as an SVG but had two easily visible, non tangent lines which I worked to correct without altering the logo too much.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Welcome to Simple Icons, @TSprech and thanks for the contribution.

From [this page](https://www.altium.com/products/downloads), I wonder if we shouldn't also go with an outlined version for our monochrome treatment of this icon. What do the other @simple-icons/maintainers think?

**Alexa rank:** [~50k](https://www.alexa.com/siteinfo/altium.com)

**Comment by runxel** [comment]
Good catch, @PeterShaggyNoble! I agree this might be a good option, since they use it themself. It also reflects a bit better on the icon, which has some extensive shading going on.

**Comment by TSprech** [comment]
Shaded and Outlined

@PeterShaggyNoble and @runxel Thanks for the welcome and feedback. I agree with switching from the left shaded logo to the right outlined logo in the above image. I'll start working on the new SVG.

**Comment by PeterShaggyNoble** [comment]
Haven't been able to find a vector version of the outlined logo as yet 😕

**Comment by TSprech** [comment]
Outlined No Overlay Black Outlined Black
I spent yesterday looking and could not find one either. I recreated it as closely as possible, with the first photo being the outlined logo and second photo being the PNG overlaid on the SVG (apologies for the quality, I could only find a logo of that resolution). Let me know any thoughts on it.

**Comment by PeterShaggyNoble** [comment]
That looks close enough to me, @Tsprech, nice work :+1: Given the low quality of the PNG, I don't know that we're going to get much better than that. What do you think, @runxel?

**Comment by runxel** [comment]
@TSprech did an amazing job, given the poor quality/size of the base material!
Thank you so much!

**Comment by PeterShaggyNoble** [comment]
Can you update the PR with the new path, so, @TSprech?

**Comment by TSprech** [comment]
altiumdesigner

@PeterShaggyNoble Yes, I was just working on the optimization earlier this morning. I'll be making the commit in the next few minutes. Thank you and @runxel for the comments.

**Comment by PeterShaggyNoble** [comment]
Thanks for the quick update, @TSprech, and for your efforts on this one :+1:

If anyone comes across a vector version of this in the future, we can come back and review it then.

**Comment by TSprech** [comment]
@PeterShaggyNoble My pleasure, I look forward to helping more in the future.

**Pull request merged**
