### PR TITLE
Add Grammarly icon

### LINKED ISSUE #4940: Request: Grammarly
**Brand Name:** Grammarly
**Website:** https://grammarly.com/
**Alexa rank:** 138
  

**Official resources for icon and color:**
https://www.grammarly.com/media-assets

### PR DESCRIPTION
**Pull request by Karthik-Nayak98**
Grammarly

**Issue:** Closes #4940 
**Alexa rank:** 138
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by service-paradis** [comment]
Thank you @Karthik-Nayak98 for your contribution 🎉 !
FYI, they have an official media kit that can be found at https://www.grammarly.com/media-assets. Can you update the source for this?

Also, your version looks different when compared to te EPS version found on that page:
image

Can you take another look at it?

**Comment by Karthik-Nayak98** [comment]
But their website is https://www.grammarly.com, right?
Are you talking about the colour of the logo which I need to update?

**Comment by service-paradis** [comment]
> But their website is https://www.grammarly.com, right?

Yes, their website is https://www.grammarly.com/, but according to [our contribution guideline](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#source-guidelines), the `source` field is not used to link to the brand website.
It is used to identify where we took the logo. In this case, we should use the logo listed at https://www.grammarly.com/media-assets as a starting point. So both the logo and the source should be updated.

**Comment by Karthik-Nayak98** [comment]
grammarly

This is the logo which I found in their website

**Comment by service-paradis** [comment]
Yes, you should base your work on the EPS version found at https://www.grammarly.com/media-assets

**Comment by Karthik-Nayak98** [comment]
No no, I can't find your version of the logo in that website. The below logo I downloaded from that website.

> grammarly
> 
> This is the logo which I found on their website which looks totally different from yours. In this link https://www.grammarly.com/media-assets

**Comment by PeterShaggyNoble** [comment]
@Karthik-Nayak98, the image @service-paradis [posted above](https://github.com/simple-icons/simple-icons/pull/5045#issuecomment-780594479) was a comparison between your SVG (in black) and [the EPS](https://www.grammarly.com/press/media-resources/docs/icon-grammarly.eps) found at [source](https://www.grammarly.com/media-assets) (in green) to illustrate the subtle differences.

> Are you talking about the colour of the logo which I need to update?

The colour as you have it looks spot on to me.

**Comment by Karthik-Nayak98** [comment]
I can't find any differences @PeterShaggyNoble

**Comment by PeterShaggyNoble** [comment]
Just double-checked, @Karthik-Nayak98, and am seeing [the same differences](https://user-images.githubusercontent.com/15157491/108247814-0c6eb580-714b-11eb-94d2-1ff913d7499e.png) as @service-paradis between your version (in red) and the EPS I linked above (in green).

**Review by service-paradis — APPROVED** [review]
Well done 💯 
Thank you @Karthik-Nayak98!

**Pull request merged**
