### PR TITLE
Add AEW icon

### LINKED ISSUE #5970: AEW aka All Elite Wrestling
**Brand Name:** AEW aka All Elite Wrestling
**Website:** https://www.allelitewrestling.com/
**Alexa rank:** 133,609
  

**Official resources for icon and color:** [Wikimedia](https://commons.wikimedia.org/wiki/File:AEW_Logo_(simplified).svg). Primary color used from the logo is `#C5AB57`.

### PR DESCRIPTION
**Pull request by wwwescape**
aew (2)

**Issue:** Closes #5970
**Alexa rank:** 133,609
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I used the SVG from https://commons.wikimedia.org/wiki/File:AEW_Logo_(simplified).svg
- I used Inkscape to remove the scale and adjust
- I used https://jakearchibald.github.io/svgomg/ to optimize

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for this one, @wwwescape :+1: Been meaning to add it myself for a while but I never got around to it.

I am seeing [a minor difference in the "S"](https://user-images.githubusercontent.com/15157491/122580168-95402400-d04d-11eb-90ab-8e743d4325b9.png), though, between your version (in red) and the original. That may simply, but not necessarily, be down to the precision needing to be set a little higher when optimising. Would you mind taking another look at that, please?

for the colour, I always associate the brand with black, probably mainly due to the fact that the logo pretty much always appears on a black background - what do you think? If we do go with yellow/gold, though, I'd suggest using the `#B19534` from their [website](https://www.allelitewrestling.com/)'s stylesheet.

Amusing side anecdote: When your username first started popping up in my notifications, I read it as "wwescape" and figured you were a wrestling fan. Then I realised I was reading it wrong. And now I realise that that misreading was my latent psychic skills kicking in! 😆

**Comment by wwwescape** [comment]
Sure @PeterShaggyNoble. I'll take another crack at it over the weekend.

For the color, I thought the gold color would make the brand stand out instead of the generic black. But I'll try both the black or the gold from their stylesheet as you suggested.

_As for my username, I'll make the story short. I am from Goa, India and back in the day, I was one of the first few people in my city to get an internet connection. Remember dial-up modems? :grin: Anyways, the internet at the time was my escape, hence **www**escape! :stuck_out_tongue_closed_eyes:_

**Comment by wwwescape** [comment]
@PeterShaggyNoble Can you check this one?

```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>AEW</title><path d="M6.266 6.031l-.748 1.453h.537l.123-.277h.697l.137.277h.535l-.752-1.453h-.53zm1.363 0v1.453h1.389v-.427H8.12V6.03H7.63zm1.549 0v1.453h1.39v-.427h-.896V6.03h-.494zm2.039 0V7.484h1.537v-.382h-1.045v-.194h.861v-.336h-.861v-.158h1.045v-.383h-1.537zm1.765 0v1.453h1.39v-.427h-.897V6.03h-.493zm1.551 0v1.453h.492V6.031h-.492zm.649 0v.428h.556v1.025h.492V6.46h.56v-.428h-1.608zm1.763 0V7.484h1.537v-.382H17.44v-.194h.86v-.336h-.86v-.158h1.043v-.383h-1.537zm-10.418.446l.188.39h-.377l.19-.39zM0 6.924V17.01h3.674v-.512H.53V7.434h4.526v-.51H0zm18.943 0v.51h4.526v9.064h-3.143v.512H24V6.924h-5.057zm3.873 1.281l-2.146.004-1.367 3.469-.94-3.465-2.14.002-.92 3.443-1.356-3.44-2.177.005 2.966 7.482h1.633l.938-3.46.935 3.46h1.653l2.921-7.5zm-11.367.018l-3.783.007.014 3.467 1.57 4.01h5.145l-.707-1.771H9.84V10h2.32l-.71-1.777zm-5.474.01l-1.846.001-2.945 7.473H3.37l.34-.9h2.334l-.686-1.746h-.955l.635-1.674 1.705 4.32h2.172L5.975 8.232zm4.187 2.851v1.771h3.108l-.713-1.771h-2.395zm8.902 5.342v.002c-.398.001-.662.14-.804.316a.757.757 0 00.006.908c.602.625 1.572.135 1.63.008v-.62h-.89v.343h.404v.086c-.114.15-.599.143-.723-.053-.123-.225-.038-.375.008-.445.278-.3.755-.061.785.004l.364-.293a1.33 1.33 0 00-.78-.256zm-7.877.012c-.09 0-.18.008-.267.023-.293.059-.476.206-.518.346-.127.49.57.566.57.566.623.03.573.098.573.123-.064.136-.42.089-.53.07-.22-.041-.43-.185-.43-.185l-.27.299c.759.482 1.38.226 1.48.17.3-.171.289-.484.191-.621-.075-.094-.305-.206-.533-.231-.204-.048-.604-.013-.558-.143.059-.12.682-.038.845.096l.239-.295c-.234-.168-.517-.22-.791-.215v-.003zm-7.083.046l.503 1.399h.504l.28-.854.265.854h.506l.502-1.399h-.496l-.26.868-.295-.868h-.445l-.293.875-.266-.875h-.505zm2.69 0v1.399h.503v-.393h.312l.323.393h.591l-.384-.447c.6-.235.335-.93-.233-.952H6.795zm1.892 0v1.399h1.537v-.328H9.18v-.196h.86v-.336h-.86v-.156h1.043v-.38l-1.537-.003zm3.427 0v.414h.557v.985h.494v-.984h.557v-.415h-1.608zm1.758 0v1.399h1.39V17.5h-.898v-1.016h-.492zm1.563 0v1.399h.492v-1.399h-.492zm.765.002v1.397h.492v-.805l.772.805h.467v-1.397h-.492v.762l-.717-.762h-.522zm-8.904.371h.531c.19-.003.189.286 0 .291h-.531v-.29z"/></svg>
```

Preview with `#000000`:
aew

Preview with `#B19534`:
aew (1)

Would love to create the exact logo from their site but I can't find a good SVG source of it. Also I think it would a bit too difficult for me.

**Comment by PeterShaggyNoble** [comment]
I'm still seeing the same minor difference in the "S" in that version, @wwwescape.

> Would love to create the exact logo from their site

Yeah, when I was reviewing this on Friday, I was thinking there was something not quite right about it and then, when I turned on Dynamite on Sunday, I realised it was the distressing. But then Hager vs. Wardlow was first up using the printed canvas with the monochrome logo and that reminded me that when the logo is monochrome they don't use the distressing, which I double checked against some of their merch that uses the monochrome logo so we're good to go with this treatment.

**Comment by wwwescape** [comment]
I'll give it one more go @PeterShaggyNoble. If I can't get it right, I'll hand it over to you.

**Comment by wwwescape** [comment]
My last attempt at this. @PeterShaggyNoble Could you review? Not sure if I got it right even this time. If not, you could take over.

```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>AEW</title><path d="M0 6.925v10.086h3.674v-.51H.53V7.435h4.526v-.51zm18.944 0v.511h4.526V16.5h-3.144v.511H24V6.925zm-7.727-.891v1.453h1.537v-.383H11.71V6.91h.86v-.336h-.86v-.157h1.044v-.383H11.71zm1.765 0v1.453h1.39V7.06h-.897V6.034zm1.551 0v1.453h.493V6.034zm.648 0v.427h.557v1.026h.493V6.461h.558v-.427h-1.051zm1.765 0v1.453h1.537v-.383H17.44V6.91h.86v-.336h-.86v-.157h1.044v-.383H17.44zM11.45 8.225l-3.785.006.015 3.466 1.57 4.01h5.144l-.707-1.77H9.84V10h2.32zm-1.288 2.862v1.77h3.107l-.712-1.77zM6.265 6.034l-.748 1.453h.538l.122-.278h.699l.135.278h.536l-.753-1.453zm1.363 0v1.453h1.39V7.06h-.897V6.034zm1.55 0v1.453h1.39V7.06h-.896V6.034zm-2.65.444l.187.391h-.377zm16.29 1.73l-2.148.003-1.368 3.47-.938-3.467-2.142.003-.92 3.443-1.355-3.44-2.177.004 2.966 7.483h1.633l.938-3.462.934 3.462h1.653zm-16.844.025l-1.845.003-2.946 7.472H3.37l.342-.9h2.333l-.686-1.747h-.955l.635-1.673 1.706 4.32h2.17zm13.091 8.195c-.398.002-.663.14-.805.316a.76.76 0 00.005.91c.603.625 1.574.134 1.632.008v-.622h-.892v.344h.405v.086c-.114.152-.598.143-.722-.053-.124-.225-.038-.374.008-.444.277-.3.753-.062.784.004l.365-.293a1.332 1.332 0 00-.78-.256zm-7.877.01a2.177 2.177 0 00-.269.02c-.293.06-.476.207-.517.346-.128.491.571.567.571.567.623.03.571.098.572.123-.065.136-.42.087-.529.07-.221-.042-.43-.186-.43-.186l-.271.3c.76.482 1.38.226 1.48.17.3-.171.29-.484.192-.621-.076-.093-.307-.207-.535-.232-.204-.048-.604-.011-.558-.141.06-.12.682-.04.845.095l.24-.295c-.233-.168-.517-.22-.791-.216zm-7.085.047l.504 1.397h.505l.278-.854.266.854h.506l.502-1.397h-.497l-.258.866-.297-.866h-.444l-.294.874-.265-.874zm2.693 0v1.397h.502v-.392h.31l.324.392h.591l-.384-.448c.6-.234.334-.927-.234-.95h-.06zm1.89 0v1.397h1.537v-.328H9.18v-.195h.86v-.335h-.86v-.158h1.044v-.381zm3.427 0v.413h.557v.984h.494v-.984h.557v-.413zm1.758 0v1.397h1.39V17.5h-.897v-1.016zm1.562 0v1.397h.493V16.485zm.766 0v1.397h.493v-.804l.772.804h.466v-1.396h-.493v.761l-.716-.761zm-8.904.372h.531c.19-.003.189.286 0 .292h-.53z"/></svg>
```

Preview with `#000000`:
aew (black)

Preview with `#B19534`:
aew (gold)

**Comment by PeterShaggyNoble** [comment]
That looks perfect to me now, @wwwescape, nice work 👍🏻 If you want to push that path then I'll merge this straight in. And looking at both colours side-by-side, I think black is definitely the correct choice.

**Comment by wwwescape** [comment]
@PeterShaggyNoble Done!

**Review by PeterShaggyNoble — APPROVED** [review]
Excellent 👍🏻 Thanks for your continued work on this one, @wwwescape - a great addition to our existing wrestling icons 🙂

**Pull request merged**
