### PR TITLE
Updated CodeChef

### PR DESCRIPTION
**Pull request by fbernhart**
codechef

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by adamrusted** [comment]
Do you know if there's an SVG available at source?
I can only see the PNGs while browsing - and obviously we'd be better to compare to an SVG if available.

**Comment by mondeja** [comment]
It seems that was created in #1921 vectorizing manually a PNG, so I would only compare against the previous vector if there is not a vector version now in the source, and I can't find it either.

**Comment by fbernhart** [comment]
@adamrusted  How come you can't see the SVG file in the header of https://www.codechef.com? 🤔 

It's this one:
https://s3.amazonaws.com/codechef_shared/sites/all/themes/abessive/logo.svg


I'll rebuild the icon from it.

**Comment by fbernhart** [comment]
codechef

**Comment by adamrusted** [comment]
> @adamrusted How come you can't see the SVG file in the header of [codechef.com](https://www.codechef.com)? 🤔

My bad 😅 must have thought it was a PNG/JPG due to it's complexity.

> Note: I had to keep a precision of 4. I couldn't make the SVG pass the linter with a precision of 3.

I'll compare it against source now, but I imagine it's absolutely fine! 🎉

**Review by mondeja — APPROVED** [review]
> My bad 😅 must have thought it was a PNG/JPG due to it's complexity.

Wow, I must have thought the same :sweat_smile: 

It seems that these gaps are reasonable, so looks perfect for me :100: Thanks for this update @fbernhart!

**Comment by fbernhart** [comment]
@adamrusted Yes, I've slightly cleaned up the bottom of the hat a bit. So that there were no very thin lines hanging around without any reason.

**Pull request merged**
