### PR TITLE
Add write.as icon (#2003)

### LINKED ISSUE #2003: Add write.as
**Name:** write.as
**Website:** [write.as](https://write.as/)
**Official resources for icon and color:** https://write.as/img/w-sq.svg
`#00b3e3` taken from the blue dot.
  <!-- for example media kits, brand guidelines, SVG files, ...) --
[Alex rank](https://www.alexa.com/siteinfo/write.as) is ~60k

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
Closes #2003

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
see issue :)

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @runxel thanks for working on this PR 👍 

The hex value you chose in the PR is `#00B3E3`, referenced in #2003 as the blue colour in the [logo dot](https://write.as/img/w-sq.svg).  

I get the colour of the dot to be `#5bc4ee` 🤔

**Comment by runxel** [comment]
@phatbhoy67 
Yeah, you're right. [The culprit.](https://www.timeanddate.com/moon/phases/)

Anyway. It's fixed! Thanks for the catch!

**Comment by PeterShaggyNoble** [comment]
They use `#5bc4ee` in https://write.as/img/w-sq.svg and `#00b3e3` in https://write.as/img/writeas-logo.svg

**Comment by phatbhoy67** [comment]
Hey @runxel the .svg is good 👍  , however, as @PeterShaggyNoble points out, there seems to be a bit of a choice of blue to use as the hex value so I will ask the opinion of the @simple-icons/maintainers on this point.

Can you please change the source to be (https://write.as/brand). 

All logo options, including (https://write.as/img/w-sq.svg), can be found on that page (and another shade of blue `#5ac4ee`).

**Comment by runxel** [comment]
Updated the link. Thanks for the valuable comments here!
At the brand page they only use `#5ac4ee` – sadly they don't explicitly say mention it.
However I would go with that one.

**Comment by birjolaxew** [comment]
I think the blue `#5bc4ee` (the current on in the PR) is good enough for me. Based on https://write.as/brand, it seems to be what's used in [their official logomark](https://write.as/img/w-sq.svg), with `#00b3e3` being from their [full wordmark](https://write.as/img/writeas-logo.svg). Given that they aren't consistent themselves, I don't think we have to fuss too much, but I would probably use the one from the logomark.

If other @simple-icons/maintainers agree, I think this is ready to merge.

**Pull request merged**
