### PR TITLE
Update .NET

### LINKED ISSUE #4898: Update .NET
~~**Brand Name: .NET Core**~~
~~**Website: https://dotnet.microsoft.com/download/dotnet-core**~~
~~**Alexa rank: 21**~~

~~**Official resources for icon and color:~~
~~https://dotnet.microsoft.com/static/images/redesign/downloads-dot-net-core.svg**~~

~~**Color:#512bd4**~~

Update the existing .NET icon to the official primary color mentioned on page 16 of [.NET brand guidelines](https://github.com/dotnet/brand/blob/master/dotnet-brand-guidelines.pdf).

#512BD4

### PR DESCRIPTION
**Pull request by MoDev32**
.NET

**Issue: Closes #4898**
**Alexa rank: n/a**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG (Not Necessary)
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Updated the current used color to the official primary color as mentioned at page 16 of [.NET brand guidelines](https://github.com/dotnet/brand/blob/master/dotnet-brand-guidelines.pdf).

> Icon updated from [this SVG](https://github.com/dotnet/brand/blob/defe0408e765b48223a434a0d9a94213edc062f8/logo/dotnet-logo.svg) with the circle redrawn.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the PR, @MoDev32. While we're at it, I checked our current icon against [the logo](https://github.com/dotnet/brand/blob/master/logo/dotnet-logo.svg) in their branding repo and we're going to need to update that as well (see comparison below with our version in red) - do you think you'd be up to taking that on? No problem if not, we can address it separately but I would suggest at least updating this PR to change the source URL to https://github.com/dotnet/brand/

**Comment by MoDev32** [comment]
I updated the icon source link, but I have never edited an SVG before. So I'll just download it as a black text from [this source](https://github.com/dotnet/brand/blob/master/logo/text-only/Black/dotnet-logo-text_Black.svg) and optimize it with SVGO if there's a guideline of editing SVGs to be qualified to simple-icons terms, as there are a lot of options regarding the optimization and couldn't find a source related to your preferred options of optimizations.

**Comment by PeterShaggyNoble** [comment]
Sorry, @MoDev32, I should have linked you to our contributing guidelines, which can be found at https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md

For the source, contrary to what those guidelines say, I think we should just go with the repo itself as it contains additional branding information on top of the logo.

**Comment by MoDev32** [comment]
I think I will leave it to you guys. You seem like you could handle this better than me as I've never worked with victors before. I will just change the icon source as you kindly suggested.

**Comment by PeterShaggyNoble** [comment]
Just pushed an SVG to your branch so we can keep this all together. We will need one of the other @simple-icons/maintainers to review it now, though.

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @MoDev32 and @PeterShaggyNoble 🥳

**Pull request merged**
