### PR TITLE
Add /e/

### LINKED ISSUE #4916: e.foundation
**Brand Name:** /e/ foundation
**Website:** https://e.foundation/
**Alexa rank:** 234135
**Official resources for icon and color:** https://e.foundation/wp-content/uploads/2019/12/e-logo.jpg https://en.wikipedia.org/wiki/File:E_Foundation_logo.png

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
/e/

**Issue:** Resolves #4916
**Alexa rank:** [~213k](https://www.alexa.com/siteinfo/e.foundation)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Colour from [website](https://e.foundation/) logo but I'm not sure it's the correct choice. Took some digging to unearth the source icon; thought it was gonna be easy when I found the PDF on [this page](https://e.foundation/about-e/) but ... well, have a look for yourself! 🙈 Unfortunately, I had to go with a precision of 5; 3 was affecting the position & dimensions and with 4 there was a distortion in the bottom of the icon.

This PR also updates `index.html` to remove `/`s from file names.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Just chiming in to say that the website change looks fine to me :+1:

**Comment by adamrusted** [comment]
This'll need an update to remove the index.html file after v5 is released. Have any relevant changes been made to the new site, and preview generator?

**Comment by ericcornelissen** [comment]
> This'll need an update to remove the index.html file after v5 is released. Have any relevant changes been made to the new site, and preview generator?

With #5553 merged the changes to the side are irrelevant - the new website _should_ handle this brand just fine - `index.html` now just needs to be removed here.

**Comment by PeterShaggyNoble** [comment]
Done.

The preview generator can also already handle the "/"s through the `getslug` function.

**Review by ericcornelissen — APPROVED** [review]
The SVG looks spot on, the `source` is still the most up-to-date version of the logo in the repository. I wasn't able to find any `guidelines` or explicit `license` on the SVG. So, all in all this looks great @PeterShaggyNoble, thanks for the contribution! 🎉

**Pull request merged**
