### PR TITLE
Add Autodesk Revit icon

### LINKED ISSUE #1984: [COLLECT] Add icons of CAD brands
Some I have in mind: (Please comment, if you have more suggestions)

- [x] ANSYS (#3211)
- [x] Archicad (#2633)
- [x] Autodesk Autocad (#9920)
- ~CATIA~ _(invalid, see comment below)_
- [ ] fritzing
- [ ] Autodesk Inventor
- [x] KiCad #7517
- [x] Bentley Microstation (#8934)
- [ ] Nemetschek Allplan
- [ ] PTC
- [x] Autodesk Revit (#8956)
- [x] Rhino & Grasshopper (#2197)
- [x] Sketchup (#3587 & #4311)
- [ ] SolidEdge
- ~SolidWorks~ _(invalid, see comment below)_
- [x] Vectorworks (~#3586~ #4764)

### PR DESCRIPTION
**Pull request by PratyushJayachandran**
autodeskrevit

**Issue:** contributes toward #1984 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Icon only available as an image here https://www.autodesk.com/products/revit. Traced manually using reference and imagination.
Color: `#186bff` Taken from the logo available on webpage.

### CODE REVIEW

**Review by adamrusted — APPROVED** [review]
I'm happy with this interpretation, thank you @PratyushJayachandran!
Given it's from a raster image - I'll ask another @simple-icons/icon-review member to review before we add.

image

**Comment by runxel** [comment]
Mh, this doesn't look right 🤔
It should extend much more in the height.
grafik

**Comment by PratyushJayachandran** [comment]
> Mh, this doesn't look right 🤔 It should extend much more in the height.

I think the comparison is slightly off. 
I have attached the [SVG with source embedded](https://github.com/simple-icons/simple-icons/assets/35000807/0f514a7e-205c-462f-a8f2-3a12c2f25ec7).

**Comment by runxel** [comment]
In the absence of any better source, and since Adam is happy, I'm happy too.
Thanks for contribution and the comparison!

**Pull request merged**
