### PR TITLE
Add Hugo

### LINKED ISSUE #2439: Hugo (static site generator)
**Name:** Hugo
**Website:** https://gohugo.io
**Official resources for icon and color:** 

* An SVG can be found on the [hero banner from the index page of the website](https://gohugo.io/). 
* https://d33wubrfki0l68.cloudfront.net/c38c7334cc3f23585738e40334284fddcaf03d5e/2e17c/images/hugo-logo-wide.svg (The lone H with the bounding hexagon.)
* We can consider the pink color as the brand color. 
It is also featured from the [community forums](https://discourse.gohugo.io/).  

  
Alexa ranking: [~29k](https://www.alexa.com/siteinfo/gohugo.io)

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Hugo

**Issue:** Closes #2439

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Rejected alternative:

Hugo

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble I think the "possible alternative" version you included above is more like the [favicon](https://gohugo.io/favicon-32x32.png) and we should include that version instead of the current PR version.

hugo-favicon

Any @simple-icons/maintainers have a view?

**Comment by runxel** [comment]
I'm also slighty more in favour of the outlined logo.

**Comment by PeterShaggyNoble** [comment]
Thanks for the feedback, guys - will update momentarily.

**Comment by phatbhoy67** [comment]
Thanks for the fast update @PeterShaggyNoble , nice work 👏

**Pull request merged**
