### PR TITLE
Add SecurityScorecard icon

### LINKED ISSUE #7743: SecurityScorecard
### Brand Name

SecurityScorecard

### Website

https://securityscorecard.com/

### Popularity Metric

```Global Rank: 269,180```
```Country Rank: 105,859```
```Category Rank: 239```
https://www.similarweb.com/website/securityscorecard.com/#overview

### Official Resources for Icon and Color

svg: https://securityscorecard.com/security-rating/_next/static/media/ssc-logo-badge-1.8891ced8.svg
color: #7033fd

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by NoDataFound**
CleanShot 2022-09-06 at 05 02 38@2x

**Issue:** closes #7743

**Similarweb rank:**
Global Rank: 269,180
Country Rank: 105,859
Category Rank: 239

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by dirien** [comment]
Hi @NoDataFound,

can you create in issue (aka Icon request) and link it to the is PR. Also fill the infos in the PR template.

**Comment by NoDataFound** [comment]
Requested Changes complete.
***Issue*** #7743

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @NoDataFound,

Thanks for your contribution.

I did find some differences with the original SVG linked in the issue:
image

**Comment by NoDataFound** [comment]
Odd and good catch.  I am fixing this now, and think the viewbox area was incorrectly scaled.

**Review by NoDataFound — COMMENTED** [review]
Updated with correct Aspect ratio from source

**Comment by NoDataFound** [comment]
@dirien I updated the svg file and PR with an updated preview.

**Comment by LitoMore** [comment]
@NoDataFound There is still some difference. Please make sure you enable the aspect ratio lock when you resizing.

CleanShot 2022-09-05 at 14 59 43@2x

**Comment by LitoMore** [comment]
CleanShot 2022-09-06 at 04 36 27@2x

Still not fit. But no worries, let me help you out.

**Comment by LitoMore** [comment]
CleanShot 2022-09-06 at 05 00 20@2x

Perfect fit now. :v:

**Comment by NoDataFound** [comment]
@LitoMore thank you SOOOO much.  What was I doing wrong?  I really appreciate you correcting the issue and I look forward to adding more.  

Any advice or help you could offer would be appreciated.  

Thank you again!

**Comment by LitoMore** [comment]
@NoDataFound I guess it's a clip-path related issue. I ungrouped all groups then removed the clip-path attribute in text mode.

Here are my steps (with Inkscape):

1. Remove unused shapes
2. Resize main shape to 24
3. Align center
4. Ungroup all groups
5. Save file
6. `npm run svgo -- icons/securtityscorecard.svg`
7. Open in text mode (any text editor), remove all `clip-path` related attributes
8. Remove fills related attributes
9. Save file
10. `npm run svgo -- icons/securtityscorecard.svg`
11. Done

I'm not a pro at SVG, so I can't tell what you are doing wrong. I only know using those steps may cleans up the clip-path.

**Pull request merged**
