### PR TITLE
Add Komoot icon

### LINKED ISSUE #2862: Komoot
Name: Komoot
Website: komoot.com
Official resources for icon and color: Don't have.

### PR DESCRIPTION
**Pull request by LuckyF**
komoot

**Issue:** Closes #2862

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Unfortunately I have messed up my git repo and had to create a new pull request.
The old one (#2878) can be rejected.

 The icon should now be centered and I increased the precision while optimizing.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @LuckyF :+1:

Again, to ensure we're comparing like with like, can you let us know which version of their logo you based your icon on? I've done a comparison with a couple of different ones and there are a few discrepancies, different for each file as there are inconsistencies between each.

**Comment by LuckyF** [comment]
You're welcome.
I used the _Monochromatic logo_ inside the _Komoot-Logo-RGB.ai_ file and removed the text.

**Comment by PeterShaggyNoble** [comment]
OK, so, using the black version of the icon on the second page of that AI file, I'm seeing some differences around the inner edges of the arc (your version in red below). It doesn't seem to be a precision issue as when I run the path through an SVGO plugin for Inkscape with the same precision, I get the following, which lines up better so I'm not too sure what's causing the difference in your version. 🤔

```
M24 12c0 2.809-.967 5.39-2.584 7.435l-6.141-6.141A3.519 3.519 0 0 0 12 8.477a3.523 3.523 0 0 0-3.274 4.817l-6.142 6.14A11.946 11.946 0 0 1 0 12C0 5.373 5.373 0 12 0c6.628 0 12 5.373 12 12m-9.713 2.673C14.224 14.727 12 11.09 12 11.09s-2.224 3.636-2.287 3.582l-6 6A11.955 11.955 0 0 0 12 24c3.216 0 6.133-1.268 8.287-3.327z
```

**Comment by PeterShaggyNoble** [comment]
Closing this out as abandoned due to inactivity. I'll submit a fresh PR for it shortly.

**Pull request closed without merging**
