### PR TITLE
Corona game engine

### PR DESCRIPTION
**Pull request by runxel**
**Issue:** _none_

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo is as svg in the [website's](https://coronalabs.com/) header, color `#F96F29` included.

### CODE REVIEW

**Comment by phatbhoy67** [comment]
Hey @runxel the .svg and colour are great 👍 

Should this be added as "Corona Game Engine" or "Corona Labs"?

**Comment by PeterShaggyNoble** [comment]
Their [brand guidelines](https://coronalabs.com/presskit.pdf) allow for just "Corona" *but* it doesn't look like those guidelines allow for the icon by itself.

**Comment by runxel** [comment]
So, _Corona Labs_ is the company behind the engine. I could see that we add it as `Corona engine`.

You, @PeterShaggyNoble, found the presskit regarding the company. They share the logo (and part of the name) with the engine. I'd argue while it's true that the name should be added for the company the same doesn't hold true for the _engine_. It should be okay to add the logo without the name since I want to add the _engine_ rather than the company.

**Comment by phatbhoy67** [comment]
I think "Corona Engine" is a good choice @runxel, and I also think the graphic element without the wordmark is acceptable for use here @PeterShaggyNoble

engine

**Comment by runxel** [comment]
Great! Thanks for reviewing :)
Updated the name to be `Corona Engine`.

**Comment by phatbhoy67** [comment]
Nice work @runxel 👍

**Pull request merged**
