### PR TITLE
Add Spark AR icon

### LINKED ISSUE #4434: Request: Spark AR Studio İcon
**Name:** Spark AR Studio 
**Website:** [https://sparkar.facebook.com/ar-studio/](https://sparkar.facebook.com/ar-studio/)
**Alexa rank:** [6](https://www.alexa.com/siteinfo/facebook.com) - for Facebook.com

**Official resources for icon and color:**
[SVG Logo](https://scontent.fada2-2.fna.fbcdn.net/v/t39.2365-6/76870833_509761306273232_5468210970943815680_n.svg?_nc_cat=108&ccb=2&_nc_sid=ad8a9d&_nc_ohc=T66EhE5SvUoAX9z8H11&_nc_ht=scontent.fada2-2.fna&oh=2be59c087ad47de624d92f1790d87003&oe=60082295)

### PR DESCRIPTION
**Pull request by edizbaha**
sparkar

Close #4434
**Alexa rank:** [6](https://www.alexa.com/siteinfo/facebook.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The color (pink #FF5C83) was chosen because it's the most prominent on the logo and website.
The icon was created from the official logo by me.

### CODE REVIEW

**Review by fbernhart — CHANGES_REQUESTED** [review]
@edizbaha Thanks for your contribution so far.

However, it seems like you've forgotten to add the SVG file itself to your pull request. Can you change that?

I'm as well wondering if the word "Studio" is really necessary in this case. Wouldn't it be better to just name it "Spark AR"? Seems like Facebook is as well marketing "Spark AR Hub" and "Spark AR Player" with the same icon/logo. So "Spark AR" would represent all of this. What's your opinion?

**Comment by edizbaha** [comment]
> @edizbaha Thanks for your contribution so far.
> 
> However, it seems like you've forgotten to add the SVG file itself to your pull request. Can you change that?
> 
> I'm as well wondering if the word "Studio" is really necessary in this case. Wouldn't it be better to just name it "Spark AR"? Seems like Facebook is as well marketing "Spark AR Hub" and "Spark AR Player" with the same icon/logo. So "Spark AR" would represent all of this. What's your opinion?



> @edizbaha Thanks for your contribution so far.
> 
> However, it seems like you've forgotten to add the SVG file itself to your pull request. Can you change that?
> 
> I'm as well wondering if the word "Studio" is really necessary in this case. Wouldn't it be better to just name it "Spark AR"? Seems like Facebook is as well marketing "Spark AR Hub" and "Spark AR Player" with the same icon/logo. So "Spark AR" would represent all of this. What's your opinion?

You are right, it would be right to use it as Spark AR. I updated the json file to Spark AR. But I did not fully understand where to add the svg file. 

I uploaded the svg file here. Can you download and add it from here? @fbernhart 

Svg file link: [https://www.mediafire.com/file/857zkpfxcz5ol3r/sparkar.svg/file](url)

**Comment by adamrusted** [comment]
@edizbaha - thanks for your contribution!
The icon required a little work to get it to pass the linter (for reference, run `npm install` then `npm run svglint` locally to see the results before pushing here) but otherwise is great! I'll wait for another @simple-icons/maintainers to approve this one, being as I've altered the icon somewhat.

**Comment by edizbaha** [comment]
When will you review and add this icon on simpleicons.org?
I did as much as I could. I can't do any more.
@fbernhart @adamrusted

**Comment by adamrusted** [comment]
> When will you review and add this icon on simpleicons.org?
> I did as much as I could. I can't do any more.
> @fbernhart @adamrusted 

I've asked for another reviewer to look at this one, being as I had to make tweaks to the icon, so it's whenever one of the other maintainers can take a look.

The icon looks great, so thanks for your work in this @edizbaha 😁

**Comment by edizbaha** [comment]
> I've asked for another reviewer to look at this one, being as I had to make tweaks to the icon, so it's whenever one of the other maintainers can take a look.
> 
> The icon looks great, so thanks for your work in this @edizbaha 😁

Thanks, I hope another reviewer to look at this icon. :)

**Comment by mondeja** [comment]
:thinking: Shouldn't this icon include spaces between colors @adamrusted?

**Comment by adamrusted** [comment]
> 🤔 Shouldn't this icon include spaces between colors @adamrusted?

Yep - just committed 😅

**Review by mondeja — CHANGES_REQUESTED** [review]
Just for consistency, could you remove these two coordinates that are almost collinear?

image

**Comment by adamrusted** [comment]
@mondeja done! 😁

**Review by mondeja — APPROVED** [review]
Perfect :100:
Thank you @edizbaha and @adamrusted for your work :pray:

**Comment by edizbaha** [comment]
Thank you for your work. @adamrusted 😊

**Pull request merged**
