### PR TITLE
Spond

### PR DESCRIPTION
**Pull request by fanatiicx**
**Issue:** 5988
**Alexa rank:** ~240k
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Hi, I read the contributing guidelines and followed the steps. I had to resize the image a few times to get it better aligned. I picked the color from the center of the logo.

This is my first PR in this project for Spond, [Issue #5988](https://github.com/simple-icons/simple-icons/issues/5988). 

Please let me know if I need to make any changes. 

Thanks!

spond_preview

### CODE REVIEW

**Review by fanatiicx — COMMENTED** [review]
Updated midpoint of gradient color to try and pass "Verify Source / Lint" stage.

**Comment by ericcornelissen** [comment]
Just chiming in here to help with the linter @fanatiicx, the letters in the hex value should be uppercase 😉

**Review by fanatiicx — COMMENTED** [review]
@ericcornelissen D'oh! Thanks--I've changed the letters from lowercase to uppercase.

**Comment by fanatiicx** [comment]
failed_centered

Re-centered the image based on error message above.

Hope it works this time. Otherwise, I will continue to troubleshoot and try installing NodeJS in future to test locally.

**Review by PeterShaggyNoble — APPROVED** [review]
Thanks for taking this one on, @fanatiicx and welcome to Simple Icons 🙂

The SVG looks perfect to me, nice work 👍🏻 Just 2 minor changes I'd suggest:
1. I'm getting [`#EE4353`](https://meyerweb.com/eric/tools/color-blend/#EC326A:EF543C:1:hex) for the calculated mid-point of the gradient, and,
2. Can you just go with https://spond.com/ for the source? We generally prefer links to pages over files to reduce the possibility of future "link rot".

Once that's done then this can be merged straight in.

**Review by PeterShaggyNoble — APPROVED** [review]
Thanks again, @fanatiicx - great first PR 👍🏻

**Pull request merged**
