### PR TITLE
C Programming Language

### PR DESCRIPTION
**Pull request by PokiDokika**
**Issue:**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

I picked the hex value because the C++ logo (which is really similar to the C logo) uses it. I found the vectorized logo from dropbox (I found the link from issue #1693) and I decided to make it usable for this project. This is my first attempt to do anything in inkscape so I hope that it'll be good enough.

### CODE REVIEW

**Comment by birjolaxew** [comment]
This is a tough issue to start off with, because it requires a bit of judgement on which logo to pick ;) 

The good news is that the SVG looks pretty good! There are some minor problems (e.g. the logo looks to be a bit more than 24pt high - did you [resize using the toolbar](https://www.tutorviacomputer.com/inkscape/change-the-objects-size/) which lets you input the size directly?) and a misspelling in the `name` of the JSON which is causing the build to fail, but we'll let that rest for now.

The more pressing problem that we'll have to figure out is what the "official" logo of the C programming language is. This is a bit harder than e.g. C++ which has [Standard C++](https://isocpp.org/) as an authority, or C# which has [Microsoft](https://docs.microsoft.com/en-us/dotnet/) as an authority - I don't think that C really has a an authority that uses a logo. As far as I can tell, two logos have become popular: the logo of [the K&R book](https://en.wikipedia.org/wiki/The_C_Programming_Language), and then the one used in this PR (which apparently is based on the C++ one?).

I think it's difficult to really decide on one to pick. For my money, I'm fine with the version used in this PR. It does not, however, have an official resource, which is kind of unique in Simple Icons. Any thoughts on this @simple-icons/maintainers?

**Comment by ericcornelissen** [comment]
Although I'm personally fine with the version in the Pull Request (and the SVG looks great, good job @PokiDokika!), I do think that the "K&R" version can be consider "official" as [the book it comes from](https://en.wikipedia.org/wiki/The_C_Programming_Language) is (co)written by (according to [the Wikipedia page for C](https://en.wikipedia.org/wiki/C_(programming_language))) the "creator" of the language.

One other thing is that I think the name should be just "C" rather then "C Programming Language" (also, there is a type in "language" in the JSON data file) since we don't use the "Programming Language" suffix for any other programming language.

**Comment by PokiDokika** [comment]
Sorry about misnaming it and all!
I hope that it works now.
Thank you for your feedback!

**Comment by birjolaxew** [comment]
@phatbhoy67 I think that quote refers to the style. It is also written on e.g. [their touchpad icon](https://icons8.com/icon/M9xNyIu2wL3e/touchpad).

That being said, it looks like the consensus is to use the [logo of the K&R book](https://commons.wikimedia.org/wiki/File:The_C_Programming_Language_logo.svg) for C instead of the version in this PR. Could you please update the SVG @PokiDokika?

**Comment by PokiDokika** [comment]
I updated the SVG to match the one on the K&R book.
I hope that it's what you're looking for.

**Comment by ericcornelissen** [comment]
Thanks for your contribution and cooperation on this icon @PokiDokika :tada:

**Comment by PokiDokika** [comment]
No problem! I'm happy to help.

**Pull request merged**
