### PR TITLE
Add satellite

### LINKED ISSUE #9462: Add Satellite icon
### Brand Name

Satellite

### Website

https://www.satellite.me

### Popularity Metric

The Similarweb rank is #373.824, see https://www.similarweb.com/website/satellite.me

### Official Resources for Icon and Color

The only SVG icon I was able to find, was the one used in the nav bar on their website.
https://global-uploads.webflow.com/649c3f9ab4db379f08fd7c85/64ae902430fc94b79ab1e03f_satellite_WortBild.svg

### Additional Comments

_No response_

### Contributing

No

### PR DESCRIPTION
**Pull request by iagocarmona**
satellite-preview

**Issue:** closes #9462 

**Similarweb rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Hey @iagocarmona - thanks for the submission!
Comparing your SVG (black) to the source (red) I'm seeing that yours doesn't fill the 24x24 viewport. Could you resize the icon, ensuring that the longest side is exactly 24px?
I'd also suggest we change the source to https://www.satellite.me as that's where the logo is easiest to find.

**Comment by LitoMore** [comment]
This is weird. This one should fail when the lining stage.

**Comment by adamrusted** [comment]
@LitoMore - I've spotted a couple of PRs recently where the linter hasn't caught them. Potentially one to investigate...

**Comment by LitoMore** [comment]
@adamrusted OK, I'm checking right now.

**Comment by adamrusted** [comment]
There we go, thanks for the fast turn-around on the fix @LitoMore 🎉

**Comment by iagocarmona** [comment]
I'm trying to solve the lint error: 
```
 x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 19.727 x 22.191
 x icon-centered <path> must be centered at (12, 12); the center is currently (11.59, 12.819)
```
but I have no Idea how to solve this... someone can help me? 
@adamrusted

**Comment by adamrusted** [comment]
So that lint error is saying that although the icon _canvas_ is the correct size, the icon itself is not 24px in it's longest dimension. At a glance, I would say the height should be 24px, and if you lock the aspect ratio (in software like Inkscape) the width should auto-adjust to suit. Then you'll just need to center the path on the canvas - and it should be good to go!

**Comment by iagocarmona** [comment]
@adamrusted I think that now it's everthing OK. It's ready to merge! Please review it.

**Review by LitoMore — CHANGES_REQUESTED** [review]
CleanShot 2023-09-12 at 14 41 31@2x

Please don't stretch the shape. You should keep its aspect ratio.

**Comment by iagocarmona** [comment]
@LitoMore, Where did you used the icon to stay like this? I pated the path on simple icons preview and its looks ok. 
simpleicons

**Comment by LitoMore** [comment]
@iagocarmona See the `How do I review icons` section in https://github.com/simple-icons/simple-icons/discussions/9351.

**Comment by iagocarmona** [comment]
@LitoMore I resized, but the icon dont fit exactly on viewbox, this is the preview: 

simpleicons

Should I resize to fit in ?

**Comment by iagocarmona** [comment]
@LitoMore Please, can you review it ? Should I resize the icon to fit on viewbox ?

**Comment by LitoMore** [comment]
@iagocarmona Yes. Please resize it to fit the viewbox.

**Comment by iagocarmona** [comment]
This is the preview now! 

simpleicons

**Comment by iagocarmona** [comment]
@LitoMore Now i think it's ready to merge! Please take a look.

**Review by adamrusted — APPROVED** [review]

**Pull request merged**
