### PR TITLE
Add Simple Analytics

### PR DESCRIPTION
**Pull request by bbenno**
simpleanalytics

**Issue:** None
**Alexa rank:**  [110,341](https://www.alexa.com/siteinfo/simpleanalytics.com)

### Checklist

  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

1. Download embedded logo (format: SVG) from https://simpleanalytics.com/ and take color from website's CSS
2. Resize viewbox with Inkscape
3. Optimize with [`svgo`](https://github.com/svg/svgo) v2.2.2
4. Verify changes via `npm run our-lint`

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
Thanks @bbenno, though there looks to be [some differences](https://user-images.githubusercontent.com/1830867/112755674-9ecf6800-8fd9-11eb-9cf5-65d20f604cdd.png) between your PR in red, and the source file `Black on transparent svg` from [here](https://simpleanalytics.com/press). Given they're giving out logos there - may be worth updating the source to that, and using the black logo. The red variants on that page also list the hex as `#FF4F64` so we should probably update to that.

**Comment by adamrusted** [comment]
Thanks for updating the hex @bbenno - though before I review it could you take another shot at the icon using the ones on that logos page, to try and get it to match them?

**Comment by bbenno** [comment]
Changes of forced push:

* different initial SVG version of the logo
* Adjust color and add guidelines link in simple-icons.json

simpleanalytics

### Description

1. Download logo from https://simpleanalytics.com/press
2. Resize viewbox with Inkscape
3. Optimize with [`svgo`](https://github.com/svg/svgo) v2.3.0
4. Verify changes via `npm run our-lint`

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @bbenno 🚀

**Pull request merged**
