### PR TITLE
Updated Arlo

### PR DESCRIPTION
**Pull request by adamrusted**
arlo

**Issue:** Contributes to #5251.
**Alexa rank:** [10,930](https://www.alexa.com/siteinfo/arlo.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Arlo appear to be in the middle of a re-brand. Their old icon is used in the favicon (and appears in their social posts) though the logo in the header has updated.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I'm seeing [a couple](https://user-images.githubusercontent.com/15157491/111171722-15fa0a80-859d-11eb-8b93-b20eaa65ad4b.png) of [small differences](https://user-images.githubusercontent.com/15157491/111171769-21e5cc80-859d-11eb-8408-26458d2740d8.png) in the head, @adamrusted, which look to be the result of cleaning up the points. There's alsoa  duplicated point where the beak joins the head that you might be able to remove.

As tis looks to be a rebrand in progress, we should monitor [this page](https://www.arlo.com/en-us/trademarks.html) and [this PDF](https://partners.arlo.com/us/images/collateral/branding/brandguidelines/Arlo_logo_guidelines.pdf) for changes or updated versions and update again, if necessary.

**Comment by adamrusted** [comment]
@PeterShaggyNoble should've resolved those small differences. Think I just got a bit too ruthless with the points - as you suggested.

**Comment by PeterShaggyNoble** [comment]
There are still a couple of duplicated points that look like they could be removed or joined (the smaller looking 2 in [this screenshot](https://user-images.githubusercontent.com/15157491/111195189-eacee580-85b3-11eb-9db7-4e6eea58fbb6.png)). I was able to remove the top one in the beak and the bottom one in the neck with no noticeable distortion.

**Comment by adamrusted** [comment]
Try that out @PeterShaggyNoble - should be better.

**Review by PeterShaggyNoble — APPROVED** [review]
That's perfect now, @adamrusted 👍🏻 Nice one

**Pull request merged**
