### PR TITLE
feat: Add Piapro

### PR DESCRIPTION
**Pull request by FinnRG**
piapro

**Similarweb rank:** 54,012

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Icon extracted from the linked image to match the favicon. Color extracted from the linked image.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @FinnRG 👍🏻 

Before we start reviewing, though, could you provide us with a bit of information on what this brand is?

**Comment by FinnRG** [comment]
@PeterShaggyNoble Piapro is a song sharing platform created by the japanese media company Crypton Future Media (ref: https://en.wikipedia.org/wiki/Crypton_Future_Media#Piapro). It's quite popular in Asia. 

I've taken the "P" from piapro from the [svg file linked in wikipedia](https://ja.wikipedia.org/wiki/%E3%83%94%E3%82%A2%E3%83%97%E3%83%AD#/media/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:CFM_Piapro_Logo.svg), as it is also used in the favicon and other icons.

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
Thanks for the information, @FinnRG 👍🏻

Would you mind having another look at this, though, please, as I'm seeing [some differences around the edges](https://github.com/simple-icons/simple-icons/assets/15157491/9977f291-f358-4774-8610-446005f9fcc4) between your version (in red) and the source (in black)?

**Review by PeterShaggyNoble — APPROVED** [review]
This looks perfect now, @FinnRG 👍🏻 Thanks for your work on it and welcome to the Simple Icons contributor team 🙂

**Pull request merged**
