### PR TITLE
Add Vala icon

### PR DESCRIPTION
**Pull request by glerroo**
image

**Issue:** closes https://github.com/simple-icons/simple-icons/issues/7877

**Similarweb rank:** [1,910,584](https://www.similarweb.com/website/vala.dev/#overview)

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by LitoMore** [comment]
CleanShot 2022-10-06 at 19 37 58@2x

@glerroo In this case, we could use their full brand instead of the single `V`

**Comment by glerroo** [comment]
@litomore I created this version with the full branding without the rectangular background or is better with it.
image

**Comment by dirien** [comment]
Hi @glerroo, I like the `V` version more! Like the favicon of the website.

**Comment by glerroo** [comment]
Hi @LitoMore and @dirien i made this other version as suggested, the `V` without the square background.

vala

The base color is that used in the [website vala.dev](https://github.com/simple-icons/simple-icons/pull/vala.dev), `#7239B3`.

**Comment by dirien** [comment]
@glerroo cool! I will check this tomorrow! 👍

**Comment by glerroo** [comment]
@dirien I don't have updated the vala.svg file in the repo, i wait your check or upload now the new version.

**Comment by dirien** [comment]
@glerroo go and upload it! I like the V!

**Comment by glerroo** [comment]
@dirien Uploaded! 👍

**Review by dirien — APPROVED** [review]
Hi @glerroo ,

Thanks for your contribution to simple-icons!

It's a perfect fit:
image

**Pull request merged**
