### PR TITLE
Update Apache JMeter

### PR DESCRIPTION
**Pull request by mondeja**
image

**Issue:** #4590 
**Alexa rank:** Not representative

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Rebuilt from source.
- Cleaned up path manually removing imperfections and simplifying.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Looks like there are a few minor imperfections in our original version when compared to [the source](https://svn.apache.org/repos/asf/comdev/project-logos/originals/jmeter.svg). There are also _a lot_ of points in the feather and the "JMeter" that we might be able to clean up. Happy to merge this as-is, though, as it lines up with our original and we can revisit the additional changes later if you don't feel like taking them on right now, @mondeja.

**Comment by mondeja** [comment]
I'm going to give a try to the cleanup :+1:

**Comment by mondeja** [comment]
I've rebuilt from scratch using the reference SVG that you've posted. I wonder if we should add https://apache.org/foundation/marks/ as `guidelines` entry for all the Apache logos :thinking: what do you think @PeterShaggyNoble?

**Review by adamrusted — APPROVED** [review]
There's a couple _tiny_ differences like [this](https://user-images.githubusercontent.com/1830867/110206044-712c4e80-7e73-11eb-94b7-c22da9124018.png) between PR in black, and source in red - though I'm fine to let them through if another @simple-icons/maintainers is ok with it too. Will await feedback from someone else before merging though.

**Comment by PeterShaggyNoble** [comment]
I think those differences are a bit too significant for us to let through, @fbernhart. Would you mind taking a look at this again, @mondeja? I think some of them may be down to converting the strokes to paths; I know Inskscape, at least, struggles with that on occasion.

**Comment by mondeja** [comment]
> I think those differences are a bit too significant for us to let through, @fbernhart. Would you mind taking a look at this again, @mondeja? I think some of them may be down to converting the strokes to paths; I know Inskscape, at least, struggles with that on occasion.

I've converted strokes into paths before all the cleanup. Could you show a specific difference and an example of how to treat it? I'm not quite sure what you mean.

**Comment by adamrusted** [comment]
Returning to this one, I'm still seeing the differences between PR and source after converting the strokes. Some like ([this](https://user-images.githubusercontent.com/1830867/118474141-a6221080-b702-11eb-9061-eb70301b9863.png) and [this](https://user-images.githubusercontent.com/1830867/118474354-e2ee0780-b702-11eb-8126-d3b2f4b06fc1.png)) appear to just be optimization, but others (like [this](https://user-images.githubusercontent.com/1830867/118474200-b5a15980-b702-11eb-983a-1dd072559699.png)) I don't think can be put down to SVGO.

I've expanded the strokes in Illustrator, before copy-pasting the path into Affinity Designer to compare (I'm assuming you've used SVGOMG for optimization, meaning I can't directly compare in Illustrator 😅)

Provided my unoptimized comparison path below, just in case someone wants to compare against that:
```svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 24.1.2, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1"
	 id="svg2" inkscape:version="0.48.4 r9939" sodipodi:docname="logo.svg" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:svg="http://www.w3.org/2000/svg"
	 xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 260.4789429 88.297905" style="enable-background:new 0 0 260.4789429 88.297905;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#D22128;}
</style>
<g>
	<path class="st0" d="M42.6835327,14.4219284c0.3132324-0.8078613,0.5605469-1.5497437,0.7418823-2.2092285
		c0.1483765-0.5770264,0.2637939-1.1210327,0.3627319-1.6486206c-3.2313843,0.5440674-7.2045898,1.0715942-9.7929688,1.2034912
		c-0.7419434,1.1375732-1.5497437,2.4400024-2.4235229,3.8908081c-0.0494995,0.0824585-0.098938,0.1483765-0.131897,0.230835
		c-0.7583618,1.2694702-1.5497437,2.6543579-2.390564,4.187561c-0.7254028,1.3189087-1.4837646,2.7202759-2.2751465,4.25354
		c-0.6862183,1.3071289-1.3729858,2.6963501-2.1073608,4.1654053l-0.0523682,0.0056763
		c0.0164795,0.065918,0,0.098938-0.0164795,0.1154175c-0.098877,0.1978149-0.1813354,0.3791504-0.2802734,0.5770264
		c-0.2802734,0.5935059-0.5770264,1.1870117-0.8572998,1.7969971c-0.3132324,0.6594849-0.6264648,1.3353882-0.9561768,2.027832
		c-0.164917,0.3462524-0.3297729,0.6924438-0.4946289,1.0551758c-0.4945679,1.0715942-0.9891968,2.1762085-1.5002441,3.3137817
		c-0.6265259,1.4013062-1.2529907,2.8521729-1.8959351,4.3688965c-0.6100464,1.4343262-1.2365112,2.9345703-1.8629761,4.4678345
		c-0.5935669,1.4672852-1.2035522,2.9675903-1.8135376,4.5338135c-0.5440674,1.3848267-1.0881348,2.8191528-1.6486816,4.286499
		c-0.032959,0.065918-0.0494385,0.1483765-0.0823975,0.2142944c-0.5440674,1.4508057-1.1046143,2.9511108-1.6651611,4.484314
		c-0.0164795,0.03302-0.032959,0.065979-0.032959,0.098938c-0.0823975,0.230835-0.164856,0.4451294-0.2473145,0.6759644
		c-0.4286499,1.1870117-0.8737793,2.4069824-1.3024292,3.6599731c0,0.0164795-0.0164795,0.032959-0.0164795,0.0494995
		c-0.065918,0.1813354-0.131897,0.3461914-0.1813354,0.5275269c-0.2967529,0.8408203-0.5440674,1.5991821-1.1375732,3.3137817
		c0.9727173,0.4451294,1.7475586,1.5992432,2.4729614,2.9181519c-0.0823975-1.3684082-0.6429443-2.6543579-1.7145996-3.6435547
		c4.7645874,0.2143555,8.8862305-0.9891968,10.996521-4.484314c0.1813354-0.3132324,0.3626709-0.6429443,0.5275269-0.9891968
		c-0.9726563,1.2200317-2.159729,1.7475586-4.418335,1.6156616c3.3137817-1.4837646,4.9788818-2.9180908,6.446228-5.2756348
		c0.3461914-0.5605469,0.6923828-1.1705933,1.0386353-1.8464966c-2.9016113,2.9840698-6.2648926,3.8248291-9.8094482,3.1818848
		c-0.0494995-0.0164795-0.098938-0.0164795-0.164917-0.032959c3.1819458-0.3956909,7.4024658-2.7697754,10.1227417-5.7043457
		c1.2529907-1.3518677,2.390564-2.9345703,3.4456787-4.7975464c0.7913208-1.3848877,1.5167236-2.9181519,2.225647-4.6327515
		c0.6100464-1.4837646,1.2035522-3.0994263,1.7640991-4.8469849c-0.7254028,0.3791504-1.5662231,0.6594238-2.489502,0.8572998
		c-0.164856,0.032959-0.3297119,0.065918-0.4945679,0.098877c-0.164856,0.03302-0.3297119,0.0494995-0.5111084,0.0824585
		c2.9675903-1.1375732,4.8305664-3.3302612,6.1824341-6.0340576c-0.7748413,0.5275269-2.0443115,1.2199707-3.5610352,1.5662231
		c-0.197876,0.0494385-0.4121704,0.0823975-0.6265259,0.1154175c-0.0494385,0-0.098938,0.0164795-0.164856,0.0164795
		c1.0221558-0.4286499,1.8959351-0.9067993,2.6542969-1.4838257c0.164917-0.1153564,0.3132935-0.2472534,0.4616699-0.3791504
		c0.2307739-0.197876,0.4451294-0.4121704,0.6594238-0.6265259c0.131897-0.1483765,0.2637939-0.2802734,0.3956909-0.4286499
		c0.2967529-0.3461914,0.5770264-0.7254028,0.8243408-1.1375732c0.0823975-0.131897,0.164856-0.2472534,0.2307739-0.3791504
		c0.098938-0.197876,0.197876-0.3792114,0.2802734-0.5605469c0.4121704-0.8243408,0.7418823-1.5662231,1.0056763-2.225708
		c0.131897-0.3297119,0.2473145-0.6264648,0.3462524-0.9067383c0.032959-0.1154175,0.0823975-0.2142944,0.1154175-0.3297119
		c0.098877-0.3132324,0.1978149-0.5935059,0.2637329-0.8408203c0.098938-0.3627319,0.164917-0.6594849,0.197876-0.8737793
		c-0.098938,0.0823975-0.2143555,0.164856-0.3462524,0.2307739c-0.8902588,0.5275879-2.4234619,1.0222168-3.6599731,1.2529907
		c-0.0164795,0-0.032959,0-0.0494385,0.0164795c-0.0687256,0.0098267-0.1488647,0.026001-0.2258301,0.0393066
		c2.3829346-1.1103516,3.4656372-2.1118774,4.5122681-3.5673828c0.2802734-0.3956909,0.5605469-0.8243408,0.8408203-1.2694702
		c0.8572998-1.3353882,1.6981201-2.8027344,2.4400024-4.2700195C41.562439,17.0762253,42.2054443,15.6749191,42.6835327,14.4219284z
		"/>
	<path class="st0" d="M9.0675659,63.7659836c0.4451294-1.2199707,0.9067383-2.4729614,1.3848877-3.7589111
		c0.1154175-0.2967529,0.2142944-0.5770264,0.3297119-0.8737793v-0.0164795l-0.0094604-0.0186768
		c0.4267578-1.1643677,0.8855591-2.3287354,1.3283691-3.5259399c0.131897-0.3297119,0.2637939-0.6594238,0.3956909-1.0056763
		c0.5770264-1.4837646,1.1705322-2.9840698,1.7640381-4.5007935c0.5770264-1.4508057,1.1705322-2.9016113,1.7805786-4.3688965
		c0.6099854-1.4673462,1.2364502-2.9346313,1.8629761-4.4019165c0.6429443-1.5003052,1.3024292-2.9840698,1.9783325-4.4678345
		c0.6594849-1.4672852,1.3519287-2.9346313,2.0278931-4.385437c0.2472534-0.5275269,0.4945679-1.0386353,0.7583618-1.5662231
		c0.4286499-0.8902588,0.8737793-1.7805176,1.3189087-2.6707764c0.0164795-0.0494995,0.0494385-0.098938,0.065918-0.1483765
		l-2.177063-4.3320923l2.1936035,4.3320923c0.7254028-1.3684082,1.4343262-2.7367554,2.1431885-4.0886841
		c0.7749023-1.4343262,1.5497437-2.8356323,2.324646-4.2040405c0.8078003-1.4178467,1.6321411-2.7861938,2.4729614-4.1216431
		c0.0494385-0.0823975,0.098938-0.164856,0.1483765-0.2307739c0.8243408-1.3024292,1.6486206-2.5554199,2.4894409-3.7589111
		l-2.5223999-4.7481689c-0.1813965,0.230835-0.3792114,0.4616699-0.5770264,0.7089233
		c-0.7254028,0.9067993-1.4838257,1.8794556-2.258667,2.9181519c-0.8737793,1.1705322-1.7640381,2.4069824-2.6873169,3.7094727
		c-0.8408203,1.2034912-1.6981201,2.4729614-2.5554199,3.7753906c-0.7254028,1.1210938-1.4508057,2.258667-2.1762085,3.4291992
		c-0.032959,0.0494385-0.0494385,0.0823975-0.0823975,0.131897l0.0119629,0.0236816
		c-0.0481567,0.0809937-0.0961914,0.1763916-0.1603394,0.2565918c-0.7584229,1.2529297-1.5332642,2.5223999-2.2751465,3.8248291
		c-0.7583618,1.3189087-1.5003052,2.6543579-2.225708,4.0227051c-0.6099854,1.1540527-1.2034912,2.3081055-1.7969971,3.4786377
		c-0.1154175,0.230835-0.230835,0.4781494-0.3462524,0.7089233c-0.7089233,1.4673462-1.3683472,2.9016724-1.9453735,4.2700195
		c-0.6594849,1.5497437-1.2365112,3.0335083-1.7475586,4.4348755c-0.3297729,0.9232178-0.6430054,1.8135376-0.9232788,2.6708374
		c-0.2307739,0.7254028-0.4451294,1.4672852-0.6594238,2.192688c-0.4946289,1.7145996-0.9067993,3.4291992-1.2529907,5.1437988
		l0.010498,0.020813c-0.0273438,0.0725708-0.0449219,0.1349487-0.0599365,0.2099609
		c-0.4121704,2.0773315-0.7089233,4.1546021-0.8572998,6.2319336c0,0.065918-0.0164795,0.1483765-0.0164795,0.2142944
		c-1.0222168-1.6486206-3.7919312-3.2643433-3.7754517-3.2478638c1.9783936,2.8686523,3.4786377,5.7043457,3.6929932,8.4905396
		c-1.0551147,0.2143555-2.5059204-0.098877-4.1710815-0.7088623c1.7475586,1.5991821,3.0499878,2.0443115,3.5610962,2.159729
		c-1.5991821,0.098877-3.2643433,1.2034912-4.9459839,2.4729614c2.4564819-1.0056763,4.451355-1.4013672,5.8692017-1.0716553
		C4.5172729,73.7568283,2.258667,80.8130417,0,88.297905c0.6924438-0.1978149,1.1046143-0.6759644,1.3353882-1.3024292
		C1.7310791,85.6435471,4.418396,76.7408371,8.605957,65.0519333c0.1154175-0.3297119,0.2473145-0.6594238,0.3626709-1.0056763
		C9.0016479,63.947319,9.0346069,63.8649216,9.0675659,63.7659836z"/>
	<path class="st0" d="M42.8648682,2.6670456c0,0-2.4400024-3.9402466-5.2921143-2.2421875
		c-1.3848877,0.8243408-3.6929932,3.1324463-6.4297485,6.479187l2.5223999,4.7646484
		c1.6687012-2.4016724,3.3817749-4.5570679,5.097168-6.4307861c-0.7810669,0.8935547-2.4302368,2.9307251-4.767395,6.5296631
		c2.5883789-0.131897,6.5615845-0.6594238,9.8094482-1.2199707C44.7773438,5.140007,42.8648682,2.6670456,42.8648682,2.6670456z
		 M39.0565186,4.9092331c0.131897-0.1483765,0.2142944-0.230835,0.2142944-0.230835
		C39.204895,4.7608566,39.1224365,4.8267746,39.0565186,4.9092331z"/>
	<path class="st0" d="M63.3989258,24.5146408H53.434082c-0.3393555,0-0.6142578,0.2749023-0.6142578,0.6142578v45.6123047
		c0,1.2412109-0.1679688,2.2753906-0.5043945,3.0869141c-0.3022461,0.7734375-0.7358398,1.3896484-1.3076172,1.8476563
		c-0.5449219,0.4697266-1.206543,0.8046875-1.9692383,0.9951172c-1.6132813,0.4150391-3.7304688,0.3544922-5.3188477,0.1162109
		c-0.8706055-0.1279297-1.7001953-0.2773438-2.4663086-0.4433594c-0.1821289-0.0371094-0.3710938,0.0048828-0.5161133,0.1220703
		c-0.1445313,0.1171875-0.2285156,0.2929688-0.2285156,0.4785156v8.2929688c0,0.2783203,0.1875,0.5224609,0.456543,0.59375
		c0.7475586,0.1982422,1.6728516,0.3662109,2.7387695,0.4970703c1.0693359,0.1533203,2.331543,0.2304688,3.7514648,0.2304688
		c2.4072266,0,4.6420898-0.3115234,6.6416016-0.9267578c2.03125-0.625,3.7973633-1.6230469,5.2426758-2.9580078
		c1.4794922-1.3212891,2.637207-3.0214844,3.4389648-5.0478516c0.8188477-2.0146484,1.234375-4.4394531,1.234375-7.2070313
		V25.1288986C64.0131836,24.7895432,63.7382813,24.5146408,63.3989258,24.5146408z"/>
	<path class="st0" d="M117.0185547,24.5195236h-13.5673828c-0.2709961,0-0.5102539,0.1777344-0.5883789,0.4375
		L92.5673828,59.1962814l-9.6699219-34.2294922c-0.074707-0.2646484-0.3164063-0.4472656-0.5913086-0.4472656H68.7382813
		c-0.3393555,0-0.6142578,0.2749023-0.6142578,0.6142578v46.9873047c0,0.3388672,0.2749023,0.6142578,0.6142578,0.6142578h8.9086914
		c0.3393555,0,0.6142578-0.2753906,0.6142578-0.6142578V50.259758c0-0.6054688-0.0170898-1.2832031-0.0385742-2.0224609
		c0-0.7607422-0.0209961-1.5498047-0.0639648-2.359375c-0.0214844-0.8183594-0.046875-1.6435547-0.0893555-2.46875
		c-0.0214844-0.8422852-0.0600586-1.6635742-0.1030273-2.4575195c-0.0209961-0.4521484-0.0429688-0.9082031-0.0668945-1.3681641
		l9.1523438,32.7036133c0.0742188,0.2646484,0.3164063,0.4482422,0.5917969,0.4482422h9.1518555
		c0.2709961,0,0.5097656-0.1767578,0.5878906-0.4365234l10.0400391-33.2163086
		c-0.0253906,0.6210938-0.0522461,1.2348633-0.0810547,1.8417969c-0.0209961,0.7666016-0.059082,1.5561523-0.1025391,2.3818359
		l-0.1279297,4.675293v24.1396484c0,0.3388672,0.2749023,0.6142578,0.6142578,0.6142578h9.2924805
		c0.3393555,0,0.6142578-0.2753906,0.6142578-0.6142578V25.1337814
		C117.6328125,24.794426,117.3579102,24.5195236,117.0185547,24.5195236z"/>
	<path class="st0" d="M177.2255859,63.2490158c-0.9101563,0.3242188-1.7607422,0.5830078-2.6035156,0.7890625
		c-0.8017578,0.1992188-1.6679688,0.3007813-2.578125,0.3007813c-0.0048828,0-0.0087891,0-0.0126953,0
		c-0.9560547,0-1.6992188-0.2695313-2.2734375-0.8251953c-0.5546875-0.5371094-0.8369141-1.4267578-0.8369141-2.6435547v-16.703125
		h8.1279297c0.3388672,0,0.6142578-0.2749023,0.6142578-0.6142578v-7.3598633c0-0.3393555-0.2753906-0.6142578-0.6142578-0.6142578
		h-8.1279297v-7.0400391c0-0.3393555-0.2753906-0.6142578-0.6142578-0.6142578h-6.2714844
		c-0.2568359,0-0.4863281,0.1591797-0.5751953,0.3994141l-2.7548828,7.3789063l-5.2080078,3.1787109
		c-0.1826172,0.1118164-0.2939453,0.3100586-0.2939453,0.5244141v4.1469727c0,0.3393555,0.2753906,0.6142578,0.6142578,0.6142578
		h4.0703125v16.703125c0,2.3798828,0.2919922,4.3974609,0.8720703,6.0048828
		c0.6054688,1.5908203,1.4501953,2.8994141,2.515625,3.8945313c1.0625,0.9716797,2.328125,1.6601563,3.7607422,2.046875
		c1.3955078,0.3769531,2.8759766,0.5595703,4.5253906,0.5595703c1.6738281,0,3.2158203-0.1650391,4.5722656-0.4873047
		c1.3896484-0.3037109,2.59375-0.7138672,3.5791016-1.21875c0.2050781-0.1054688,0.3339844-0.3164063,0.3339844-0.546875v-7.2958984
		c0-0.2001953-0.0966797-0.3867188-0.2607422-0.5019531C177.6240234,63.2099533,177.4140625,63.1806564,177.2255859,63.2490158z"/>
	<path class="st0" d="M236.0556641,35.2123947c-0.1679688-0.0556641-0.3759766-0.0898438-0.6582031-0.1103516
		c-0.2548828-0.0463867-0.5478516-0.0874023-0.8222656-0.1054688c-0.3115234-0.0478516-0.6289063-0.0551758-0.9462891-0.0693359
		c-0.3164063-0.0224609-0.6181641-0.0263672-0.8896484-0.0268555c-1.2597656,0-2.4033203,0.1601563-3.3896484,0.4741211
		c-0.9931641,0.300293-1.8974609,0.7392578-2.6855469,1.3017578c-0.7568359,0.534668-1.4462891,1.1972656-2.1083984,2.0249023
		c-0.4746094,0.5927734-0.9160156,1.2202148-1.3183594,1.8720703l-1.2177734-4.5395508
		c-0.0722656-0.2685547-0.3154297-0.4550781-0.59375-0.4550781h-7.4238281c-0.3388672,0-0.6142578,0.2749023-0.6142578,0.6142578
		v35.9282227c0,0.3388672,0.2753906,0.6142578,0.6142578,0.6142578h9.8046875c0.3388672,0,0.6142578-0.2753906,0.6142578-0.6142578
		V53.8310471c0-1.609375,0.1953125-2.9785156,0.5771484-4.0654297c0.3945313-1.0849609,0.9365234-1.9570313,1.6103516-2.5927734
		c0.6953125-0.65625,1.5361328-1.1386719,2.4941406-1.4316406c1.0185547-0.3056641,2.1347656-0.4609375,3.3173828-0.4609375
		c0.1992188,0,0.4501953,0.0166016,0.8046875,0.0380859c0.2949219,0.0009766,0.5859375,0.0195313,0.9238281,0.0634766
		c0.3251953,0.0205078,0.6386719,0.0566406,0.9238281,0.0976563c0.2724609,0.0390625,0.4853516,0.0761719,0.6416016,0.1152344
		c0.1826172,0.0478516,0.3779297,0.0048828,0.5273438-0.1113281s0.2363281-0.2949219,0.2363281-0.484375v-9.203125
		C236.4775391,35.5307541,236.3076172,35.2954025,236.0556641,35.2123947z"/>
	<path class="st0" d="M207.6494141,39.3271408c-1.3847656-1.4521484-3.1083984-2.5629883-5.1152344-3.2983398
		c-1.9599609-0.7490234-4.1953125-1.128418-6.6435547-1.128418c-2.5048828,0-4.8291016,0.4145508-6.9082031,1.2338867
		c-2.0839844,0.828125-3.8916016,2.0786133-5.375,3.7167969c-1.4677734,1.6240234-2.625,3.6777344-3.4414063,6.1040039
		c-0.8115234,2.4111328-1.2226563,5.2539063-1.2226563,8.4511719c0,3.1601563,0.4482422,5.9707031,1.3339844,8.3603516
		c0.9082031,2.3701172,2.1884766,4.3691406,3.8085938,5.9453125c1.6113281,1.5449219,3.5683594,2.7236328,5.8173828,3.5029297
		c2.2236328,0.7705078,4.6816406,1.1611328,7.3056641,1.1611328c1.40625,0,2.6220703-0.0517578,3.7070313-0.15625
		c1.1484375-0.0869141,2.2275391-0.2421875,3.2099609-0.4599609c0.9355469-0.2080078,1.8496094-0.4707031,2.8037109-0.8037109
		c0.9335938-0.3417969,1.8369141-0.7402344,2.6855469-1.1845703c0.2021484-0.1054688,0.3291016-0.3154297,0.3291016-0.5439453
		v-7.5908203c0-0.2128906-0.1103516-0.4111328-0.2910156-0.5224609c-0.1806641-0.1123047-0.4082031-0.1210938-0.5976563-0.0273438
		c-0.9306641,0.4648438-1.8457031,0.8808594-2.7089844,1.2304688c-0.8798828,0.3349609-1.7792969,0.6210938-2.6728516,0.8486328
		c-0.9345703,0.2392578-1.8447266,0.4150391-2.7695313,0.5361328c-0.9121094,0.1005859-1.8984375,0.1494141-3.0175781,0.1494141
		c-1.2412109,0-2.3447266-0.1884766-3.2763672-0.5566406c-0.9121094-0.3691406-1.7158203-0.9072266-2.3759766-1.5869141
		c-0.6533203-0.7128906-1.1767578-1.5888672-1.5488281-2.5888672c-0.3027344-0.8720703-0.4941406-1.8486328-0.5732422-2.9091797
		h21.265625c0.3388672,0,0.6142578-0.2753906,0.6142578-0.6142578v-4.7617188c0-2.6787109-0.3779297-5.0830078-1.1220703-7.1386719
		C210.1357422,42.5810471,209.0517578,40.7739182,207.6494141,39.3271408z M200.1015625,45.0419846
		c0.4570313,0.5908203,0.8085938,1.3203125,1.0458984,2.1699219c0.1953125,0.6972656,0.3203125,1.4482422,0.3730469,2.2412109
		h-11.1962891c0.2197266-2.1230469,0.8046875-3.7070313,1.7373047-4.7099609
		c1.0439453-1.1025391,2.3173828-1.6386719,3.8925781-1.6386719c0.9316406,0,1.7480469,0.1723633,2.4267578,0.5112305
		C199.0820313,43.966301,199.6425781,44.4306564,200.1015625,45.0419846z"/>
	<path class="st0" d="M148.6298828,39.3271408c-1.3847656-1.4521484-3.1074219-2.5629883-5.1132813-3.2983398
		c-1.9609375-0.7490234-4.1962891-1.128418-6.6455078-1.128418c-2.5039063,0-4.828125,0.4145508-6.9086914,1.2338867
		c-2.0830078,0.828125-3.890625,2.0786133-5.3740234,3.7167969c-1.4672852,1.6230469-2.625,3.6772461-3.4418945,6.1040039
		c-0.8110352,2.4111328-1.222168,5.2539063-1.222168,8.4511719c0,3.1601563,0.4477539,5.9707031,1.3334961,8.3603516
		c0.9077148,2.3701172,2.1884766,4.3691406,3.809082,5.9453125c1.6118164,1.5458984,3.5693359,2.7246094,5.8178711,3.5029297
		c2.2226563,0.7705078,4.6806641,1.1611328,7.3046875,1.1611328c1.40625,0,2.6220703-0.0517578,3.7070313-0.15625
		c1.1474609-0.0869141,2.2275391-0.2421875,3.2109375-0.4599609c0.9384766-0.2089844,1.8525391-0.4707031,2.8027344-0.8037109
		c0.9335938-0.3417969,1.8369141-0.7402344,2.6855469-1.1845703c0.2021484-0.1054688,0.3291016-0.3154297,0.3291016-0.5439453
		v-7.5908203c0-0.2128906-0.1103516-0.4111328-0.2910156-0.5224609c-0.1806641-0.1123047-0.40625-0.1210938-0.5986328-0.0273438
		c-0.9287109,0.4648438-1.84375,0.8808594-2.7080078,1.2304688c-0.8818359,0.3359375-1.78125,0.6210938-2.6728516,0.8486328
		c-0.9335938,0.2392578-1.84375,0.4150391-2.7695313,0.5361328c-0.9121094,0.1005859-1.8984375,0.1494141-3.0166016,0.1494141
		c-1.2412109,0-2.3447266-0.1884766-3.2773438-0.5566406c-0.9248047-0.3740234-1.7324219-0.9121094-2.3876953-1.5869141
		c-0.6386719-0.6962891-1.1572266-1.5712891-1.5361328-2.5888672c-0.3027344-0.8740234-0.4951172-1.8496094-0.5742188-2.9091797
		h21.265625c0.3388672,0,0.6142578-0.2753906,0.6142578-0.6142578v-4.7617188c0-2.6787109-0.3779297-5.0830078-1.1220703-7.1386719
		C151.1162109,42.5795822,150.03125,40.771965,148.6298828,39.3271408z M131.3056641,49.4531174
		c0.21875-2.1230469,0.8027344-3.7070313,1.7363281-4.7099609c1.0439453-1.1025391,2.3173828-1.6386719,3.8925781-1.6386719
		c0.9316406,0,1.7480469,0.1723633,2.4267578,0.5112305c0.7021484,0.3515625,1.2636719,0.815918,1.7216797,1.4262695
		c0.4550781,0.5888672,0.8076172,1.3183594,1.0458984,2.1699219c0.1943359,0.6972656,0.3193359,1.4492188,0.3720703,2.2412109
		H131.3056641z"/>
	<path class="st0" d="M61.6942139,1.0836716h-1.3562622l-7.0383911,16.8179321h1.7559814l2.1558228-5.2537842h7.5666504
		l2.1843262,5.2537842h1.7702637L61.6942139,1.0836716z M57.5682373,11.334343l3.4550171-8.309021
		c-0.000061,0,3.3692627,8.309021,3.3692627,8.309021H57.5682373z"/>
	<path class="st0" d="M72.1732788,11.6912766h5.4680176c2.8838501,0,4.8255005-2.5841064,4.8255005-5.3251953
		c0-2.6126709-2.0844116-5.2824097-4.9682617-5.2824097h-6.967041v16.8179321h1.6417847V11.6912766z M72.1732788,2.5541916h5.239563
		c1.855957,0,3.4121094,1.6989136,3.4121094,3.8118896c0,2.0272827-1.2848511,3.8546753-3.2693481,3.8546753h-5.3823242V2.5541916z"
		/>
	<path class="st0" d="M83.2948608,17.9016037l2.1557617-5.2537842h7.5523682l2.1843262,5.2537842h1.7988892L89.9477539,1.0836716
		h-1.3562622l-7.0383911,16.8179321H83.2948608z M89.2767944,3.025322l3.3692627,8.309021h-6.8242188L89.2767944,3.025322z"/>
	<path class="st0" d="M104.8098145,18.0300827c2.5840454,0,5.5678711-1.3991089,6.6528931-3.9118042l-1.3705444-0.7138062
		c-1.0564575,2.1843262-3.2836304,3.1265869-5.1824341,3.1265869c-3.5691528,0-6.2960205-3.3693237-6.2960205-7.0812378
		c0-3.383606,2.1986084-6.9813232,6.2246704-6.9813232c1.8131104,0,3.897522,0.7567139,4.9682617,2.9838257l1.3277588-0.7994995
		c-1.0422363-2.1557617-3.2265625-3.6690674-6.2103882-3.6690674c-5.0682373,0-7.9806519,4.3400879-7.9806519,8.3804321
		C96.9433594,13.6185837,100.1984253,18.0300827,104.8098145,18.0300827z"/>
	<polygon class="st0" points="115.4173584,10.0351486 125.3825073,10.0351486 125.3825073,17.9016037 127.0385742,17.9016037 
		127.0385742,1.0836716 125.3825073,1.0836716 125.3825073,8.5646896 115.4173584,8.5646896 115.4173584,1.0836716 
		113.789856,1.0836716 113.789856,17.9016037 115.4173584,17.9016037 	"/>
	<polygon class="st0" points="142.1290283,16.4311447 132.4637451,16.4311447 132.4637451,10.0208664 140.701355,10.0208664 
		140.701355,8.6217575 132.4637451,8.6217575 132.4637451,2.5541916 141.914917,2.5541916 141.914917,1.0836716 
		130.8361816,1.0836716 130.8361816,17.9016037 142.1290283,17.9016037 	"/>
</g>
</svg>
```

**Comment by mondeja** [comment]
I'm going to close this as it is a mess, feel free to open another PR for this update.

**Pull request closed without merging**
