### PR TITLE
Remove X-Pack

### PR DESCRIPTION
**Pull request by fbernhart**
**Issue:** #3169 
**Alexa rank:** -

### ~Checklist~
  ~- [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)~
  ~- [x] I optimized the icon with SVGO or SVGOMG~
  ~- [x] The SVG `viewbox` is `0 0 24 24`~

### ~Description~
~I took the already used SVG.~
~I used Inkscape to fix size and center~
~I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG~

### Edit
This PR will remove the X-Pack icon from Simple Icons as X-Pack no longer exists as a separate brand. See discussion below for details.

### CODE REVIEW

**Review by adamrusted — COMMENTED** [review]
Looks like X-Pack has now become part of the 'Elastic Stack', and I can't find any reference to it past 2018 on their site. Should we remove this one @simple-icons/maintainers?

**Comment by ericcornelissen** [comment]
> Looks like X-Pack has now become part of the 'Elastic Stack', and I can't find any reference to it past 2018 on their site. Should we remove this one?

I would be inclined to agree, the logo is also missing from [its source](https://www.elastic.co/brand).

**Review by adamrusted — CHANGES_REQUESTED** [review]
@fbernhart - following brief discussion above, could you please mark this icon for removal in v5.0.0? 🙏🏻

**Comment by mondeja** [comment]
Hi @fbernhart! Could you rebase with develop and remove this icon from `collinear-segments` property of `.svglint-ignored.json`, introduced by #4589?

**Comment by fbernhart** [comment]
@mondeja Done 👍🏼

**Comment by PeterShaggyNoble** [comment]
@fbernhart, could you update the original post to clarify that this PR will remove the icon, please?

**Review by PeterShaggyNoble — APPROVED** [review]
Looks good to me 👍🏻 Once the conflicts have been resolved, this can be merged straight in.

**Pull request merged**
