### PR TITLE
Updated Adobe Fonts

### PR DESCRIPTION
**Pull request by adamrusted**
adobefonts

**Issue:** Contributes to #5251.
**Alexa rank:** N/A (Adobe Product)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Adobe Fonts icon has been brought in line with other Adobe products. Hex from the SVG found at source.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I'm seeing [a very small difference](https://user-images.githubusercontent.com/15157491/111158014-77b37800-858f-11eb-9e15-68cd1cef3eef.png) (yours in red) in the top-right corner, @adamrusted. May just be a precision issue.

**Comment by adamrusted** [comment]
> May just be a precision issue.

Almost certainly - let me re-export.

**Comment by adamrusted** [comment]
@PeterShaggyNoble updated with 4 decimals of precision. Hopefully that fixes it! 🤞

**Comment by PeterShaggyNoble** [comment]
Oddly, that doesn't seem to have fixed it, or even improved it 🤔 Given how minor it is, I'd be happy to go with the original precision 3 version rather than having to increase to 5 or more.

**Comment by adamrusted** [comment]
Huh - strange! Let me revert to the 3 decimal variant and it'll be good to go.

**Comment by PeterShaggyNoble** [comment]
Thanks, @adamrusted. Merging this in. If anyone can improve on that corner without increasing the precision too much, we can address it in a separate PR.

**Pull request merged**
