### PR TITLE
Added Spyder IDE

### LINKED ISSUE #3822: Spyder logo
**Name**: Spyder IDE
**Website**: https://www.spyder-ide.org

**Official resources for icon and color**:
https://www.spyder-ide.org/static/images/spyder-logo.svg

**Thanks!**

### PR DESCRIPTION
**Pull request by fbernhart**
spyderide

Close #3822
**Alexa rank:** 96,651 https://www.alexa.com/siteinfo/spyder-ide.org

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Hex value: most prominent color in the official SVG icon.
- Source for icon: https://www.spyder-ide.org/static/images/spyder-logo.svg

### CODE REVIEW

**Comment by blaze-github** [comment]
**Why is my icon not available?**
**When I search it on your website I can't find anything.**

**Thanks!**

**Comment by fbernhart** [comment]
@blaze-github  Because the pull request hasn't been reviewed and merged yet.

**Comment by blaze-github** [comment]
@fbernhart I understand. Thank you!

**Comment by adamrusted** [comment]
Looks like the thicker inner path hasn't been retained in this PR.
I've been able to preserve it in this path - might be worth swapping them out?
`M19.304,16.038L20.71,9.95c2.005-0.777,3.268-1.225,3.29-1.232l-0.306-0.866c-0.021,0.007-1.253,0.444-3.213,1.202 l-4.144-5.293c1.089-1.806,1.81-2.953,1.822-2.972L17.383,0.3c-0.012,0.019-0.738,1.172-1.832,2.987L9.317,3.252 c-0.093-0.85-0.21-1.784-0.359-2.796L8.05,0.59c0.141,0.955,0.253,1.844,0.343,2.657l-0.025,0c-0.001,0-0.002,0-0.003,0 c-0.144,0-0.28,0.066-0.37,0.178l-4.345,5.44C1.437,8.922,0.11,8.801,0.088,8.799L0,9.713c0.074,0.007,0.967,0.09,2.488,0.09 c0.259,0,0.539-0.003,0.834-0.008l1.425,6.429c-1.816,1.543-3.191,2.388-3.213,2.402l0.477,0.784 c0.088-0.054,1.358-0.834,3.071-2.262c0.019,0.014,0.038,0.028,0.06,0.038l6.58,3.239c-0.011,2.021,0.056,3.254,0.057,3.275 l0.917-0.052c-0.001-0.022-0.071-1.312-0.054-3.418l6.196-2.968c0.082-0.039,0.147-0.102,0.194-0.177 c1.283,1.298,2.151,1.839,2.216,1.879l0.478-0.784C21.71,18.171,20.732,17.56,19.304,16.038z M14.173,11.601l-0.496,0.518 l-1.063-1.063l-1.418-1.418c-0.083-0.083-0.172-0.158-0.264-0.229l1.905-0.338L14.173,11.601z M9.888,10.777 c0.031,0.025,0.061,0.051,0.09,0.08l1.313,1.313l0,0l1.194,1.194l-0.279,0.291l-2.544-1.252L9.888,10.777z M16.42,11.677 c0.001,0.009,0.001,0.018,0.002,0.027l-0.096,0.096c0.001-0.028,0.001-0.055,0-0.083C16.357,11.703,16.389,11.69,16.42,11.677z M17.674,12.889c0.027,0.001,0.053,0.003,0.08,0.003c0.457,0,0.964-0.197,1.436-0.571l-0.658,2.85 c-0.435-0.512-0.897-1.097-1.376-1.764L17.674,12.889z M19.224,8.986c-0.241-0.035-0.503-0.015-0.774,0.068 c-0.413,0.127-0.837,0.394-1.194,0.752c-0.245,0.245-0.437,0.505-0.576,0.768c-0.23,0.095-0.463,0.192-0.699,0.291l-1.756-3.327 c-0.018-0.035-0.041-0.067-0.063-0.099c0.59-1.017,1.149-1.965,1.653-2.808L19.224,8.986z M14.984,4.232 c-0.501,0.84-1.057,1.781-1.641,2.79c-0.049,0.001-0.098,0.005-0.146,0.014l-3.556,0.63C9.616,6.866,9.556,5.693,9.414,4.2 L14.984,4.232z M8.501,4.309c0.148,1.575,0.205,2.792,0.226,3.57C8.481,8.014,8.304,8.251,8.244,8.532 C7.02,8.676,5.897,8.764,4.902,8.815L8.501,4.309z M6.986,9.587c-0.017,0.016-0.036,0.03-0.052,0.047l-2.19,2.19L4.287,9.766 C5.093,9.734,5.998,9.678,6.986,9.587z M5.072,13.304l0.315,0.315l2.493-2.493l-0.237,1.705c-0.026,0.187,0.006,0.37,0.08,0.533 c-0.733,0.8-1.467,1.517-2.162,2.146L5.072,13.304z M5.858,16.481c0.811-0.718,1.687-1.56,2.566-2.523l3.456,1.702 c-0.082,1.373-0.125,2.627-0.145,3.715L5.858,16.481z M18.223,16.506l-5.565,2.666c0.021-1.019,0.063-2.177,0.138-3.438 c0.118-0.05,0.228-0.125,0.321-0.222l1.088-1.137c0.21,0.043,0.424,0.066,0.638,0.066c0.562,0,1.123-0.149,1.604-0.443 c0.647,0.897,1.264,1.652,1.827,2.281L18.223,16.506z`

Capture

**Review by adamrusted — DISMISSED** [review]
Looks like the thicker inner path hasn't been retained in this PR.
I've been able to preserve it in this path - might be worth swapping them out?
```
M19.304,16.038L20.71,9.95c2.005-0.777,3.268-1.225,3.29-1.232l-0.306-0.866c-0.021,0.007-1.253,0.444-3.213,1.202 l-4.144-5.293c1.089-1.806,1.81-2.953,1.822-2.972L17.383,0.3c-0.012,0.019-0.738,1.172-1.832,2.987L9.317,3.252 c-0.093-0.85-0.21-1.784-0.359-2.796L8.05,0.59c0.141,0.955,0.253,1.844,0.343,2.657l-0.025,0c-0.001,0-0.002,0-0.003,0 c-0.144,0-0.28,0.066-0.37,0.178l-4.345,5.44C1.437,8.922,0.11,8.801,0.088,8.799L0,9.713c0.074,0.007,0.967,0.09,2.488,0.09 c0.259,0,0.539-0.003,0.834-0.008l1.425,6.429c-1.816,1.543-3.191,2.388-3.213,2.402l0.477,0.784 c0.088-0.054,1.358-0.834,3.071-2.262c0.019,0.014,0.038,0.028,0.06,0.038l6.58,3.239c-0.011,2.021,0.056,3.254,0.057,3.275 l0.917-0.052c-0.001-0.022-0.071-1.312-0.054-3.418l6.196-2.968c0.082-0.039,0.147-0.102,0.194-0.177 c1.283,1.298,2.151,1.839,2.216,1.879l0.478-0.784C21.71,18.171,20.732,17.56,19.304,16.038z M14.173,11.601l-0.496,0.518 l-1.063-1.063l-1.418-1.418c-0.083-0.083-0.172-0.158-0.264-0.229l1.905-0.338L14.173,11.601z M9.888,10.777 c0.031,0.025,0.061,0.051,0.09,0.08l1.313,1.313l0,0l1.194,1.194l-0.279,0.291l-2.544-1.252L9.888,10.777z M16.42,11.677 c0.001,0.009,0.001,0.018,0.002,0.027l-0.096,0.096c0.001-0.028,0.001-0.055,0-0.083C16.357,11.703,16.389,11.69,16.42,11.677z M17.674,12.889c0.027,0.001,0.053,0.003,0.08,0.003c0.457,0,0.964-0.197,1.436-0.571l-0.658,2.85 c-0.435-0.512-0.897-1.097-1.376-1.764L17.674,12.889z M19.224,8.986c-0.241-0.035-0.503-0.015-0.774,0.068 c-0.413,0.127-0.837,0.394-1.194,0.752c-0.245,0.245-0.437,0.505-0.576,0.768c-0.23,0.095-0.463,0.192-0.699,0.291l-1.756-3.327 c-0.018-0.035-0.041-0.067-0.063-0.099c0.59-1.017,1.149-1.965,1.653-2.808L19.224,8.986z M14.984,4.232 c-0.501,0.84-1.057,1.781-1.641,2.79c-0.049,0.001-0.098,0.005-0.146,0.014l-3.556,0.63C9.616,6.866,9.556,5.693,9.414,4.2 L14.984,4.232z M8.501,4.309c0.148,1.575,0.205,2.792,0.226,3.57C8.481,8.014,8.304,8.251,8.244,8.532 C7.02,8.676,5.897,8.764,4.902,8.815L8.501,4.309z M6.986,9.587c-0.017,0.016-0.036,0.03-0.052,0.047l-2.19,2.19L4.287,9.766 C5.093,9.734,5.998,9.678,6.986,9.587z M5.072,13.304l0.315,0.315l2.493-2.493l-0.237,1.705c-0.026,0.187,0.006,0.37,0.08,0.533 c-0.733,0.8-1.467,1.517-2.162,2.146L5.072,13.304z M5.858,16.481c0.811-0.718,1.687-1.56,2.566-2.523l3.456,1.702 c-0.082,1.373-0.125,2.627-0.145,3.715L5.858,16.481z M18.223,16.506l-5.565,2.666c0.021-1.019,0.063-2.177,0.138-3.438 c0.118-0.05,0.228-0.125,0.321-0.222l1.088-1.137c0.21,0.043,0.424,0.066,0.638,0.066c0.562,0,1.123-0.149,1.604-0.443 c0.647,0.897,1.264,1.652,1.827,2.281L18.223,16.506z
```

Capture

**Comment by fbernhart** [comment]
@adamrusted I'm not sure which thicker inner path your referring to? Did you use a different source than I did? Or a different one?

I've used this one and I can't see any thicker inner path: https://www.spyder-ide.org/static/images/spyder-logo.svg

**Comment by adamrusted** [comment]
> @adamrusted I'm not sure which thicker inner path your referring to? Did you use a different source than I did? Or a different one?
> 
> I've used this one and I can't see any thicker inner path: [spyder-ide.org/static/images/spyder-logo.svg](https://www.spyder-ide.org/static/images/spyder-logo.svg)

Weird - looks like Illustrator is adding the thicker path on my end. Could another @simple-icons/maintainers review this one, as apparently my software doesn't like the original file! 😅

**Comment by fbernhart** [comment]
@adamrusted Strange that Illustrator is doing this 😅 . Opening the file in Chrome, Firefox as well as in Inkscape isn't displaying me any thicker inner path.

**Comment by adamrusted** [comment]
> @adamrusted Strange that Illustrator is doing this 😅 . Opening the file in Chrome, Firefox as well as in Inkscape isn't displaying me any thicker inner path.

No clue, must just be reading a value wrong somewhere along the line.

**Review by mondeja — CHANGES_REQUESTED** [review]
What I'm seeing is a lot of useless coordinates. It seems that unions are not properly done and maybe this is related with @adamrusted has pointed out.

@fbernhart Check next comparison between your version (blue) and mine (black). Note all the coordinates inside the geometry in your version:

image
image

**Comment by fbernhart** [comment]
@adamrusted @mondeja Thanks a lot for reviewing. I've now rebuilt it from source and cleaned it up.

If I remember correctly this was one of the first SVGs I've worked with, so probably I messed some things up in Inkscape back then. 😅 


Please have another look now. At least on my machine the SVG should be without unnecessary points and should match perfectly the source. 🕸️ 🕷️

**Review by mondeja — APPROVED** [review]
It's perfect now :spider: 
Thank you @fbernhart! :+1:

**Pull request merged**
