### PR TITLE
Payoneer

### LINKED ISSUE #3238: Request: Payoneer Icon
**Name:** Payoneer
**Website:** https://www.payoneer.com
**Official resources for icon and color:** https://www.payoneer.com/wp-content/uploads/payoneer-light-logo.svg #D8421f

### PR DESCRIPTION
**Pull request by furknyavuz**
Payoneer

**Issue:** Closes #3238
**Alexa rank:** 1209

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Found high quality SVG from their link: https://www.payoneer.com/wp-content/uploads/payoneer-light-logo.svg

### CODE REVIEW

**Comment by furknyavuz** [comment]
How can I add something like below to this PR?

**Comment by PeterShaggyNoble** [comment]
@furknyavuz, at https://petershaggynoble.github.io/MDI-Sandbox/simpleicons/preview/

For future reference, that URL is referenced in the PR template.

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @furknyavuz :+1:

The SVG looks good to me but are you sure the precision needs to be that high? I gave it a quick try myself with a precision of 3 and it seemed to work out OK.

Also, could you update the source URL to be just https://www.payoneer.com/, please?

**Comment by furknyavuz** [comment]
Updated the source url.
You mean we need to reduce the precision? I thought that 3 was acceptable level.

**Comment by PeterShaggyNoble** [comment]
Yep, 3 is our recommended starting precision (lower is better, of course, if it's possible but it rarely is) but if that introduces issues in the size or shape of the path then that should be increased by a factor of 1 until they are resolved. The SVG you included in your PR, however, has a precision of 8.

By the way, the build is failing on your last commit as you have an errant space at the beginning of the source URL. There's also an extraneous space before the closing `/` in the `<path>` tag.

**Comment by furknyavuz** [comment]
How can I check what is my current precision level. I thought I converted to 3 via using https://jakearchibald.github.io/svgomg/

**Comment by furknyavuz** [comment]
Updated the path with new one generated by svgomg precision level 2:

simpleicons

**Comment by PeterShaggyNoble** [comment]
Thanks for updating, @furknyavuz 

The build is failing this time because the precision is to low (apologies, I didn't mean to suggest that `2` would work here, if that's how you interpreted it) causing the dimensions of the path to exceed `24`. Upping the precision to `3` should resolve that.

**Comment by furknyavuz** [comment]
No problem @PeterShaggyNoble,
I thought I reduced to 3 so I decided to try with 2.

**Comment by furknyavuz** [comment]
> Could you maybe have accidentally added the unoptimised version to the PR initially?
That is possible. Thanks for the support during this process.

**Pull request merged**
