### PR TITLE
Add Ember.js

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Ember.js
**Issue:** #2075

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by phatbhoy67** [comment]
@PeterShaggyNoble should there be a container as per the "icon" section of the [logos page](https://emberjs.com/logos/)?
>"In situations where the primary logos aren’t legible (e.g., avatars, favicons) you can use the simple “E” icon. Choose the container shape that best suits the context."

They give 3 different examples. I like the circle.

**Comment by PeterShaggyNoble** [comment]
Good point, @phatbhoy67 - I had read that as the container also being optional.

I like the circle, too, but they use the square one as their favicon so maybe that would be the better option?

**Comment by PeterShaggyNoble** [comment]
I've updated with the square version for now but here are previews of the other 2 versions:
Ember.jsEmber.js

**Comment by ericcornelissen** [comment]
Looking god @PeterShaggyNoble, thanks for the contribution 👍 Also thanks for the nice review @phatbhoy67

**Pull request merged**
