### PR TITLE
Added Frontend Mentor icon

### PR DESCRIPTION
**Pull request by aemann2**
frontendmentor

**Issue:** #5689
**Alexa rank:** 42,697
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

They had no media kit, so I got the icon by contacting them on their website. They sent me an SVG file, which was this image minus the text: https://www.frontendmentor.io/static/images/logo-desktop.svg

I got the hex value by using Digital Color Meter on the SVG file they sent.

### CODE REVIEW

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
Welcome to Simple Icons, @aemann2 and thanks for the contribution 🙂

Could you take another look at the SVG, though, please? Rather than both dimensions being `24`, the height should be relative to the width. Also, could you update the `source` entry in the JSON to point to [the website](https://www.frontendmentor.io/)?

**Comment by aemann2** [comment]
> Welcome to Simple Icons, @aemann2 and thanks for the contribution 🙂
> 
> Could you take another look at the SVG, though, please? Rather than both dimensions being `24`, the height should be relative to the width. Also, could you update the `source` entry in the JSON to point to [the website](https://www.frontendmentor.io/)?

Hi @PeterShaggyNoble, 

I'm a little confused about the dimensions being relative. Steps 2 and 4 in the [Contributing.md](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) file says to change the viewbox dimensions to 24 x 24, and 0 0 24 24 is in the checklist. Are these incorrect? This is my first submission, and I'm actually not sure how to make the height relative to the width in the SVG. Any guidance on that?

**Comment by PeterShaggyNoble** [comment]
The canvas (`viewBox`) should be 24*24, yes but the path should be resized so that it's _largest_ dimension is 24, with the other dimension scaled relatively, and then centred on the canvas.

**Comment by PeterShaggyNoble** [comment]
Did you mean to close this, @aemann2?

**Comment by aemann2** [comment]
> Did you mean to close this, @aemann2?

I did. I can't figure out how to get this to meet the requirements and I'm getting frustrated because I don't know what I'm looking for.

**Comment by PeterShaggyNoble** [comment]
If you let us know what software you're using, one of us may be able to write you up a step-by-step tutorial if that would help?

**Comment by aemann2** [comment]
I'm using Inkscape. I don't know how to make the dimensions relative, I tried to center it when I submitted it before but I guess it didn't work, and I don't know how to resize so the largest dimension is 24. Every thread I look up on working with SVG files is about modifying them with CSS.

**Comment by PeterShaggyNoble** [comment]
An understandable frustration; I still get hacked off at myself every time I try to create something from scratch and fail miserably so don't beat yourself over it 🙂

Here's a quick tutorial for Inkscape, starting from scratch with [the website logo](https://www.frontendmentor.io/static/images/logo-desktop.svg). Let me know if it's any help or not and, if not, I'll put together a PR for it myself for you.

1. After opening the file, select the logo and ungroup it (`Object > Ungroup` or <kbd>Ctrl + Shift + G</kbd>)
2. Select everything bar the 3 shapes of the face and delete it
3. Select the remaining 3 shapes and unify them (`Path > Union` or <kbd>Ctrl + +</kbd>)
4. Open the document's properties (`File > Document Properties...` or <kbd>Ctrl + Shift + D</kbd>)
5. Set the width and height to `24` and close the dialogue
6. Select your unified path with the select and transform tool (<kbd>S</kbd>)
7. Click the lock icon between the "W" & "H" fields in the toolbar and then set the value of "W" to 24
8. Open the alignment tools (`Object > Align and Distribute...` or <kbd>Ctrl + Shift +</kbd>)
9. Ensure "Page" is selected in the "Relative to" field and then click "Center on vertical axis" & "Center on horizontal axis"
10. The SVG is now ready to be optimised

**Comment by aemann2** [comment]
Thanks for your patience, Peter. Later on today, I'll reopen this and go through your directions and see if I can get it to come out right. If I run into trouble I'll let you know.

**Comment by PeterShaggyNoble** [comment]
OK, I'll reopen this PR for now so nobody else thinks it's abandoned and submits a new PR in the meantime.

**Comment by aemann2** [comment]
Just pushed the changes, @PeterShaggyNoble . The tutorial definitely helped, I see where I was going wrong before. Let me know if there's anything that's still off.

**Comment by PeterShaggyNoble** [comment]
Thanks, @aemann2 👍🏻 I'm seeing [a small difference](https://user-images.githubusercontent.com/15157491/122438175-58fbbd80-cf92-11eb-8111-792323c86fb9.png) in the bottom right of the curve, though, with your version in red. Would you mind having another look at it?

In addition to that, you're missing the `d` attribute in the `path` tag, which is what the linter is currently failing on, and you can probably reduce the precision much further when optimising the file.

For the colour, I'm getting `#67bece` from the source file for the lighter blue. But, from their website, it looks like the darker blue `#3f54a3` might actually be their primary brand colour.

**Comment by aemann2** [comment]
@PeterShaggyNoble, I think I figured out where the difference was coming from and I've updated the .svg. I added the `d` attribute and reduced the precision. In the .json file, I changed the old hex code to `#3f54a3`.

**Comment by fanatiicx** [comment]
@PeterShaggyNoble I found the quick tutorial helpful, too. 

I was thinking of adding a few screenshots to your tutorial and adding the quoted text and screenshots to [Help with SVGs](https://github.com/simple-icons/simple-icons/discussions/categories/help-with-svgs) as a discussion. Would that be a good idea?

I thought I'd ask first in case it's something you or someone else is working on. Thanks!

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @aemann2. Unfortunately, though, as you can see, the linter is now failing due to the icon being slightly too wide and slightly off horizontal centre. Could you have a look at that, please? It may simply, but not necessarily, require the precision to be set a little higher when optimising.

-----
Glad you found it useful, @fanatiicx 🙂 The problem with posting tutorials "in the wild" is that different icons require different approaches & techniques so there's no real way to provide an all-encompassing tutorial that would apply to them all. Having said that, we have in the past discussed internally the feasibility of allowing people to request tutorials for specific icons already in our collection in "Help with SVGs" to help newcomers get to grips with some of the basics, at least. It's something we've shied away from a bit as, invariably, it would lead to more work for the maintainers either in fulfilling those requests ourselves or in reviewing others' tutorials to make sure they cover everything and that the final result is as expected.

**Comment by aemann2** [comment]
@PeterShaggyNoble, I bumped the precision up and made sure the file passed the linter locally.

**Review by PeterShaggyNoble — APPROVED** [review]
Everything looks perfect to me now, @aemann2 :+1: Thanks for your continued work on this one.

**Comment by aemann2** [comment]
Hallelujah 🙌. @PeterShaggyNoble thanks for all your patience.

**Comment by fanatiicx** [comment]
@PeterShaggyNoble Makes sense—thanks for taking the time to explain!

**Pull request merged**
