### PR TITLE
Remove Vine

### PR DESCRIPTION
**Pull request by adamrusted**
Given Vine was shut down in 2019, I think we're safe to look at the removal of it's icon in v5.0.0.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Been toying with this one for a good while myself, too, but each time by hand was stayed by the fact that it still somehow maintains  [a healthy Alexa rank](https://www.alexa.com/siteinfo/vine.co) which makes me wonder if people aren't actually still using it in its archived state.

**Comment by adamrusted** [comment]
> Been toying with this one for a good while myself, too, but each time by hand was stayed by the fact that it still somehow maintains [a healthy Alexa rank](https://www.alexa.com/siteinfo/vine.co) which makes me wonder if people aren't actually still using it in its archived state.

Videos previously posted on Vine are still accessible through links directly to the content - though the 'platform' itself has been inactive since the 2017 shutdown. Given no 'new' Vine content is being generated, I can't foresee a situation whereby a user of the package will need the icon in future.

**Comment by PeterShaggyNoble** [comment]
👍🏻 Easy to add it back in if people do start clamouring for it.

**Comment by ericcornelissen** [comment]
> Easy to add it back in if people do start clamouring for it

I agree with this point and agree that we can remove it.

However, this potentially brings up a difficult question. In the context of #4735, if we get a request to re-add it, should we use the threshold for a new icon or for removing an icon? I would expect the latter...

**Comment by adamrusted** [comment]
Yeah, I guess for 're-additions' we could look at removals from major releases, and treat them differently to an entirely new icon.

**Review by PeterShaggyNoble — APPROVED** [review]

**Pull request merged**
