### PR TITLE
Add Apache CouchDB icon

### LINKED ISSUE #5392: Please add CouchDB
Brand Name: CouchDB (Apache)
Website: https://couchdb.apache.org
Alexa rank: 2,096
  

Official resources for icon and color: 

https://couchdb.apache.org/image/couch@2x.png

### PR DESCRIPTION
**Pull request by service-paradis**
image

**Issue:** Close #5392
**Github stars:** [~5k](https://github.com/apache/couchdb/)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I took the SVG from https://apache.org/logos/#couchdb
- I used Inkscape to scale and adjust
- I used https://jakearchibald.github.io/svgomg/ to optimize

### CODE REVIEW

**Comment by fawazsiddiqi** [comment]
Thanks @service-paradis have been really caught up with work, really appreciate it!

**Comment by fawazsiddiqi** [comment]
@service-paradis any idea when this will be merged?

**Comment by service-paradis** [comment]
@fawazsiddiqi Maintainers have been quite busy in th past few weeks. Once it gets reviewed, it will be merged. I cannot tell when exactly it will be, sorry.

**Comment by fawazsiddiqi** [comment]
@service-paradis thanks mate! Just wanted to make sure this isn't forgotten 😂

**Review by mondeja — APPROVED** [review]
Looks perfect :art:

**Pull request merged**
