### PR TITLE
Add platform.sh icon

### PR DESCRIPTION
**Pull request by uiuxarghya**
platformdotsh

**Issue:** #5819
**Alexa rank:** 55,868
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Brand Resources: https://platform.sh/logos/
Hex Value: `#0A0A0A`

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @uiuxarghya; the SVG lines up perfectly 👍🏻

However, it looks like you should be able to get the precision down to 3 when optimising (path below). Also, where did you source the colour from? The closest I could find was `#1A182A`, which is used in the logos on their website.

```
M24 0H0v9.541h24V0zm0 20.755H0V24h24v-3.245zM0 12.618h24v4.892H0v-4.892
```

**Comment by uiuxarghya** [comment]
> Thanks for the contribution, @uiuxarghya; the SVG lines up perfectly 👍🏻
> 
> However, it looks like you should be able to get the precision down to 3 when optimising (path below). Also, where did you source the colour from? The closest I could find was `#1A182A`, which is used in the logos on their website.
> 
> ```
> M24 0H0v9.541h24V0zm0 20.755H0V24h24v-3.245zM0 12.618h24v4.892H0v-4.892
> ```

I have sourced the colour from here :
https://platform.sh/logos/redesign/Platformsh_icon_black.svg
https://platform.sh/logos/redesign/Platformsh_logo_black.svg

Okay, I am again optimizing it with precision 3.

**Comment by adamrusted** [comment]
I would also agree on the colour being `#1A182A` based on the website. Otherwise, the SVG matches up perfectly. If you could make the change to the hex - I'd be happy to merge this in today. 💪

**Comment by uiuxarghya** [comment]
Okay, I am changing the hex value to `#1A182A` ☺

**Comment by uiuxarghya** [comment]
> I would also agree on the colour being `#1A182A` based on the website. Otherwise, the SVG matches up perfectly. If you could make the change to the hex - I'd be happy to merge this in today. 💪

I have updated the icon color to `#1A182A`. 😀

**Review by adamrusted — APPROVED** [review]
Perfect, thanks @uiuxarghya 🚀

**Pull request merged**
