### PR TITLE
Add CocoaPods

### LINKED ISSUE #2901: Cocoapods
**Name:**  cocoapods
**Website:** https://cocoapods.org/
**Official resources for icon and color:**  https://github.com/CocoaPods/Design

### PR DESCRIPTION
**Pull request by mondeja**
Cocoapods

**Issue:** Closes #2901 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The HEX value was retrieved from [original image](https://raw.githubusercontent.com/CocoaPods/Design/master/assets/logo.png) color. Was converted from PNG to SVG and edited with Inkscape.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @mondeja and welcome to Simple Icons 🙂

When you say
> Was converted from PNG to SVG and edited with Inkscape.

do you mean that your SVG is based on that PNG file and not one of the Sketch files in the repo?

**Comment by mondeja** [comment]
In the main README of the repo says:

> To use you will need to have our fonts ( GT Walsheim ) installed. They're probably not gonna work perfectly as we pay for our fonts, and you'd have to grab the trial version, but it should be enough!

So I've vectorized the PNG converting to SVG, edited and simplified the vectors in Inkscape, then I've used SVGOMG.

**Comment by PeterShaggyNoble** [comment]
Thanks, @mondeja :+1:

Looking at your path, there are a couple of imperfections & discrepancies in it, though, likely as a result of the conversion process. Running the PNG through [Convertio](https://convertio.co/) does give better results, but it's still not quite perfect. The other minor issue that's more easily fixed is that your path doesn't fill the full width of the canvas. It might be worth reaching out to them to see if they can provide a vector file that doesn't require the font.

For the colour, I'd suggest either one of the reds from [their website](https://cocoapods.org/) or the orange used in their favicon and footer logo, as the design repo hasn't been updated in a few years.

**Comment by PeterShaggyNoble** [comment]
> It might be worth reaching out to them to see if they can provide a vector file that doesn't require the font.

Pinging @orta, as the top contributor to their design repo. Could you assist with this or put us in touch with someone who can?

**Comment by mondeja** [comment]
I see, I'll take a look for the requested changes. Thank you.

**Comment by orta** [comment]
Hi folks, I've updated that repo with some blank SVGs. The CocoaPods `C>` mark can be grabbed here: https://github.com/CocoaPods/shared_resources/blob/master/media/cocoapods-mark.svg

I assume you'll want to resize it down and remove the margins for consistency? This seems reasonable to me

Two notes:

 - Capital P for Pods please
 - The red is: `#EE3322`

**Comment by PeterShaggyNoble** [comment]
Many thanks for taking the time to reply, @orta, and for the additional files and details - it's very much appreciated.

@mondeja, can you update based on the feedback above, using https://github.com/CocoaPods/shared_resources/blob/3125baf19976bd240c86459645f45b68d2facd10/media/cocoapods-mark.svg as the source URL?

**Comment by mondeja** [comment]
cocoapodsicon

Thanks. This is the icon improved.

**Comment by mondeja** [comment]
The `source` parameter of `simple-icons.json` file needs to be defined for the source file used or the brand company website?

**Comment by PeterShaggyNoble** [comment]
Thanks for the quick update, @mondeja. However, you'll need to scale the path up to fill the full width of the canvas before we can merge this.

For the source, seeing as the original file is from GitHub, you would use the URL I provided in my last comment - see [the "Source" section of our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#source-guidelines) for more details.

**Comment by mondeja** [comment]
Sorry for the inconveniences. I'm understand now. Will be update the both icons In a few hours.

**Comment by PeterShaggyNoble** [comment]
> Sorry for the inconvenience

No inconvenience, we're here to help 🙂

**Comment by mondeja** [comment]
cocoapods-preview-new

**Comment by PeterShaggyNoble** [comment]
Thanks for you efforts and patience on this one, @mondeja - the path looks spot on to me now. It was _ever_ so slightly off vertical centre, which I took the liberty of fixing for you (hope you don't mind) so, once the build completes, this one will be ready to merge.

Thanks to you, too, @orta for your input.

**Pull request merged**
