### PR TITLE
Add LITIENGINE icon.

### PR DESCRIPTION
**Pull request by nightm4re94**
litiengine-icon-preview

**Issue:**
This PR adds the icon for [LITIENGINE](https://github.com/gurkenlabs/litiengine), an open-source Java 2D game engine. 

**Alexa rank:**
1,754,025

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I am one of the developers of LITIENGINE and would love to see its icon included in your collection.
Even though the market for Java 2D game engines may be relatively small, LITIENGINE has already gained quite a following in recent years and is expected to grow further in the years to come. As the very designer of the icon, I have verified that the uploaded version meets our standards.

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
While I personally find your product attractive, the metrics are not up to the minimum threshold for inclusion.
I understand that that's most likely due to the product being directed to a somewhat niche audience, so popularity is relative, but that's the rules.

Maybe you can provide an alternative metric of popularity? for instance, a comparison with other competitors in your niche? Or a graph of how the product has evolved popularity wise? Or maybe a game made with this engine that has achieved renown? Anything that would back an addition to the library.

**Comment by nightm4re94** [comment]
Thank you for your feedback!
I can totally understand your concerns, so I've collected some insights for you.
### Popularity
The following graph shows the GitHub star popularity of LITIENGINE compared to other competitors:
star-history-2022718
The green line denotes LITIENGINE. As you can see, we're relatively new to the market but our growth has been stable and among the top 5 growing java game engines / libraries / frameworks. 
The engine is also [published on itch.io](https://gurkenlabs.itch.io/litiengine), where it reaches around 100 weekly downloads steadily at the moment.
According to google analytics, our website [LITIENGINE.com](https://litiengine.com/) steadily has around 1,500 monthly visitors.
We also provide our artifacts through the [maven central repository](https://search.maven.org/artifact/de.gurkenlabs/litiengine), where we have had over 500 monthly downloads over the past year:
image

### Sponsorships
LITIENGINE currently has several active financial contributors [on OpenCollective](https://opencollective.com/litiengine):
image

Furthermore, we have a partnership with [JPROFILER](https://www.ej-technologies.com/products/jprofiler/overview.html), who are kindly providing their software for free to us.

### Games made with LITIENGINE
So far, we have only published one commercial game with LITIENGINE:
**"Naughty Elves"** is available on [Steam](https://store.steampowered.com/app/750620/Naughty_Elves/) and [itch.io](https://gurkenlabs.itch.io/naughty-elves). On Steam, the game has 1,837 activated copies and it has been downloaded 2,671 times on itch.io.

Other than that, we've been participating in the LDJAM game jam using the engine, and some of our [jam games](https://ldjam.com/users/gurkenlabs/games) have been published as open source:
- [DR. LEPUS](https://gurkenlabs.itch.io/drlepus-the-last-rabbit-on-earth) (closed source)
- [Naughty Gnomes](https://gurkenlabs.itch.io/naughty-gnomes) (closed source)
- [GOIN](https://github.com/gurkenlabs/litiengine-ldjam42) (MIT license)
- [Servus Bonus](https://github.com/gurkenlabs/litiengine-ldjam44) (MIT license)
- [Pumpkin Keeper](https://github.com/gurkenlabs/litiengine-ldjam46) (MIT license)

**Comment by dirien** [comment]
Hi @nightm4re94,

do you have by any chance the link to the original SVG? For me its easier to review from an SVG rather an Image.

If you can provide this, I start to review the PR.

**Comment by nightm4re94** [comment]
You mean the original icon?
litiengine-icon

**Review by dirien — APPROVED** [review]
Perfect fit!

image

**Pull request merged**
