### PR TITLE
Updated Beats by Dre

### PR DESCRIPTION
**Pull request by fbernhart**
beatsbydre

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by fbernhart** [comment]
I have no idea how to get this one through the linter.

I've now even rebuilt it [from source](https://www.beatsbydre.com/content/dam/beats/global/logo.svg), optimized it with a precision of 3, 4 and 5 with SVGOMG and as well have tried to use Inkscape --> File --> Save as --> Optimized SVG, with a precision of 5.

The linter is still telling me that:
```
  x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 24.003 x 24.002
```

**Comment by service-paradis** [comment]
Gave it a few tries... Not able to make it works. Would need to check what is going on with this one.

**Comment by fbernhart** [comment]
I've now slightly changed the size in Inkscape to 23.997 (before optimization) and now it passed with a precision of 4. 🥳

**Review by adamrusted — APPROVED** [review]
Matches up perfectly!

**Comment by mondeja** [comment]
> Matches up perfectly!

Feel free to merge it but doesn't forget to select the **Squash and merge** option in "Merge pull request" button dropdown :wink:

**Pull request merged**
