### PR TITLE
AWS lambda icon

### PR DESCRIPTION
**Pull request by adsingh14**
**Issue:** #6889
**Alexa rank:** 11
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Color used from official brand guidelines
Icon used '32-bit svg icon' as reference from [this link](https://aws.amazon.com/architecture/icons/)
awslambda

### CODE REVIEW

**Review by dirien — COMMENTED** [review]
Hi @adsingh14, I am not sure if we can make the stroke bigger.


Asking one ohter @simple-icons/maintainers for advice?

**Comment by adamrusted** [comment]
> I am not sure if we can make the stroke bigger.

I would say no, given the entire icon is the outline. We would be altering the core logo too much to just make it bolder.

**Comment by adsingh14** [comment]
> > I am not sure if we can make the stroke bigger.
> 
> I would say no, given the entire icon is the outline. We would be altering the core logo too much to just make it bolder.

No worries, I will match the stroke-width and update this commit.

**Comment by LitoMore** [comment]
> No worries, I will match the stroke-width and update this commit.

No. You should find out the AWS Lambda logo from here: https://aws.amazon.com/architecture/icons/

**Comment by adsingh14** [comment]
> No. We should always respect their artwork. The generated SVG from PNG/JPG definitely has some differences. You should find out the AWS Lambda logo from here: https://aws.amazon.com/architecture/icons/
> 
> Next time please spend some time on search logos with simple words: https://www.google.com.hk/search?q=aws+lambda+logo

I'm designer too and respect the official work. I kept this on hold for some reasons with keeping in mind that they'd ask to curate it. I was unable to find  https://aws.amazon.com/architecture/icons back then.

**Comment by adamrusted** [comment]
> Edit: Even their provided .ppt file contains the png image. I've found another icon library and found the exact icon. Will update shortly.

The 'Asset Pack' below contains SVG versions of all the icons. Please use those.

**Comment by LitoMore** [comment]
I think we should drop its background and make the `λ` filled.

@simple-icons/maintainers What do you think?

**Comment by sachinraja** [comment]
I agree, so I think we can move forward with that @adsingh14

**Comment by adsingh14** [comment]
> I agree, so I think we can move forward with that @adsingh14 

What about official icon then if we invert the fill? There are other icons, eg. MSFT translator, Adobe's, etc. , which we used as it is.

**Comment by sachinraja** [comment]
That's actually a fair point and on second thought, after reading through the presentation a bit more, I think it makes sense to keep the current icon (even though I think it looks better filled).

**Comment by LitoMore** [comment]
> I think we should drop its background and make the `λ` filled.

What I mean is to fill the stroke. Not to fill them all. Like this below:

CleanShot 2022-01-10 at 14 24 47@2x

**Comment by jorgeamadosoria** [comment]
I think the icon as presented by @LitoMore will work just fine: no background and stroke filled only.

Background could work too, but just to move this along, I would go with Lito's version.

**Comment by dirien** [comment]
Hi @adsingh14 did you updated the logo with the feedback of @LitoMore?

**Comment by adsingh14** [comment]
> Hi @adsingh14 did you updated the logo with the feedback of @LitoMore?

I updated this logo on the basis of sachinraja jorgeamadosoria and LitoMore, suggestion. 

I've decided to keep it original like I mentioned (https://github.com/simple-icons/simple-icons/pull/6907#issuecomment-1008553035) but other members were not okay with the original icon.

**Comment by sachinraja** [comment]
Are you sure you pushed your changes @adsingh14? I see the updated icon in the icon preview but I don't see any new commits.

**Comment by adsingh14** [comment]
> Are you sure you pushed your changes @adsingh14? I see the updated icon in the icon preview but I don't see any new commits.

..

**Comment by sachinraja** [comment]
@adsingh14 did you see my comment above?

**Comment by adsingh14** [comment]
> @adsingh14 did you see my comment above?

Yes, I did. I checked that too.

**Review by sachinraja — CHANGES_REQUESTED** [review]
image
Some differences here (I believe in stroke size)
I used this icon from the asset pack:
Res_AWS-Lambda_Lambda-Function_48_Dark
and removed the circle around it.

**Review by sachinraja — APPROVED** [review]
Nevermind this icon matches with this (also from the asset pack):
Arch_AWS-Lambda_48
 
 Good work on this, thanks for sticking with it!

**Pull request merged**
