### PR TITLE
Add Kaspersky Icon

### PR DESCRIPTION
**Pull request by ngrosso**
**Issue:#1670**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Got the logo from the [Wikimedia Commons Kaspersky](https://commons.wikimedia.org/wiki/File:Kaspersky_logo.svg)
Checked in the [Official Press Center](https://press.kaspersky.com/gallery/corporate-logo/)
Checked the hex value with photoshop

### CODE REVIEW

**Comment by birjolaxew** [comment]
Thanks for the PR @ngrosso!

Unfortunately it looks like something went wrong with the PR; only the top bit of the "k" is showing. Usually this means that the actual path wasn't updated to fit into the 24x24 viewbox.

<p align="center"></p>

Could you have a look at fixing this? If you need any help, you can always ask here and we'll see if we can help you out.

**Comment by ngrosso** [comment]
Got it, sorry the inconveniences, I'll take a look,

**Comment by birjolaxew** [comment]
@ngrosso That's better! There is one small issue left: the logo isn't vertically centered.  In the below image the vertical center is marked by the red line - the logo seems to be a bit too low.

<p align="center"></p>

**Comment by birjolaxew** [comment]
:+1: Thanks for all your work on this @ngrosso! It is much appreciated.

This icon will be out in the next release (scheduled for this weekend)

**Pull request merged**
