### PR TITLE
New: Barclays logo.

### PR DESCRIPTION
**Pull request by EM-Creations**
barclays (1)

**Issue:** https://github.com/simple-icons/simple-icons/issues/4992
**Alexa rank:** 92,389
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Logo taken directly from SVG embedded in the company's home page. Hex value matches the colour used on their website. No official brand guidelines are publicly available.

### Test / Lint evidence:
Screenshot from 2021-02-14 17 46 09
Screenshot from 2021-02-14 17 46 29

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one one, @EM-Creations :+1:

Your SVG lines up perfectly with the source but, unfortunately, there are quite a number of imperfections in the source file. So I went looking for a better one and while, surprisingly, I couldn't find any brand guidelines, I did find [this PDF](https://www.barclays.co.uk/content/dam/documents/business/barclaysbusinesswelcome.pdf) which includes a better quality logo on the first page, albeit with a number of excess points that would need to be cleaned up. Would you mind giving this a try again using that new source instead?

**Comment by EM-Creations** [comment]
> Thanks for taking this one one, @EM-Creations :+1:
> 
> Your SVG lines up perfectly with the source but, unfortunately, there are quite a number of imperfections in the source file. So I went looking for a better one and while, surprisingly, I couldn't find any brand guidelines, I did find [this PDF](https://www.barclays.co.uk/content/dam/documents/business/barclaysbusinesswelcome.pdf) which includes a better quality logo on the first page, albeit with a number of excess points that would need to be cleaned up. Would you mind giving this a try again using that new source instead?

Hi Peter, I'm not an SVG artist or artist of any kind for that matter - just a programmer. I don't even understand the terms "excess point". I used the company's own logo so even though its not perfectly surely its questionable to change it?

**Comment by adamrusted** [comment]
Hey @EM-Creations - I've had a quick look at this, and @PeterShaggyNoble's suggestions, and been able to come up with the below path. Should reduce the excess points down somewhat, while maintaining the shape of the icon pretty well. You're more than welcome to use it, subject to another @simple-icons/maintainers giving the path the sign-off.

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Barclays icon</title><path d="M11 0c-.39.01-.614.114-.761.293-.027.032-.033.05-.07.046a3.674 3.674 0 0 0-1.053.084 2.254 2.254 0 0 0-1.023.502c-.119.096-.349.366-.401.653-.045.294.002.407.097.578.142-.148.376-.263.82-.265.496-.002 1.175.225 1.413.608.339.548.27.99.199 1.516-.183 1.348-.682 2.048-1.79 2.203-.192.026-.382.04-.563.04-.847.002-1.472-.298-1.725-.883.331-.088.681-.361.76-.718a1.128 1.128 0 0 0-.232-1.006c-.417-.47-.996-.708-1.72-.708-.403 0-.758.075-.987.14-.912.255-1.64.946-2.224 2.112-.414.824-.702 1.913-.814 3.067-.047.482-.064.916-.062 1.354.001.572.037 1.098.08 1.594.125 1.437.365 2.298.712 3.22a15.64 15.64 0 0 0 1.617 3.19c.328-.305.921-1.04 1.189-1.428.193-.269.51-.78.668-1.147l.15.119c.422.438.236.813.067 1.514-.159.552-.462 1.243-.788 1.819-.19.34-.273.507-.2.583.014.015.037.03.059.026.117 0 .343-.116.588-.305.222-.17.817-.671 1.534-1.674a15.436 15.436 0 0 0 1.459-2.52c.119.044.256.101.318.225.081.147.11.342.081.564-.067.537-.38 1.352-.633 1.94-.428.997-1.213 2.114-1.797 2.876-.023.03-.164.197-.186.226.073.078.396.333.531.446.8.657 1.545 1.163 2.489 1.69.73.41 2.214 1.162 3.198 1.426.984-.264 2.469-1.017 3.2-1.425a17.216 17.216 0 0 0 3.017-2.134c-.686-.859-1.495-1.995-1.983-3.105-.252-.59-.566-1.405-.632-1.94-.029-.221-.001-.418.08-.565.035-.1.276-.216.32-.225.434.929.89 1.727 1.458 2.52.72 1.005 1.313 1.507 1.534 1.675.25.192.47.305.589.305a.07.07 0 0 0 .044-.013c.095-.069.018-.233-.183-.594a8.92 8.92 0 0 1-.79-1.822c-.13-.456-.18-.705-.184-.92-.004-.245.09-.466.25-.593l.15-.12c.458.982 1.145 1.845 1.858 2.577a15.644 15.644 0 0 0 1.616-3.19c.346-.922.586-1.783.711-3.222.074-.858.128-1.81.019-2.946-.1-1.117-.404-2.264-.814-3.068-.248-.49-.606-1.112-1.175-1.566a3.284 3.284 0 0 0-1.053-.541 3.09 3.09 0 0 0-.942-.143h-.047c-.414.006-1.188.105-1.708.71a1.135 1.135 0 0 0-.226 1.023c.126.404.35.607.786.687-.04.078-.137.214-.137.214-.15.268-.688.643-1.739.613-.58-.038-1.06-.19-1.623-.915-.349-.451-.526-1.208-.552-2.452-.021-.625-.107-1.166-.256-1.6-.242-.61-.624-.858-1.256-1.078C11.905.014 11.41.003 11 0z"/></svg>
```

barclays

**Comment by EM-Creations** [comment]
> Hey @EM-Creations - I've had a quick look at this, and @PeterShaggyNoble's suggestions, and been able to come up with the below path. Should reduce the excess points down somewhat, while maintaining the shape of the icon pretty well. You're more than welcome to use it, subject to another @simple-icons/maintainers giving the path the sign-off.
> 
> ```svg
> <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Barclays icon</title><path d="M11 0c-.39.01-.614.114-.761.293-.027.032-.033.05-.07.046a3.674 3.674 0 0 0-1.053.084 2.254 2.254 0 0 0-1.023.502c-.119.096-.349.366-.401.653-.045.294.002.407.097.578.142-.148.376-.263.82-.265.496-.002 1.175.225 1.413.608.339.548.27.99.199 1.516-.183 1.348-.682 2.048-1.79 2.203-.192.026-.382.04-.563.04-.847.002-1.472-.298-1.725-.883.331-.088.681-.361.76-.718a1.128 1.128 0 0 0-.232-1.006c-.417-.47-.996-.708-1.72-.708-.403 0-.758.075-.987.14-.912.255-1.64.946-2.224 2.112-.414.824-.702 1.913-.814 3.067-.047.482-.064.916-.062 1.354.001.572.037 1.098.08 1.594.125 1.437.365 2.298.712 3.22a15.64 15.64 0 0 0 1.617 3.19c.328-.305.921-1.04 1.189-1.428.193-.269.51-.78.668-1.147l.15.119c.422.438.236.813.067 1.514-.159.552-.462 1.243-.788 1.819-.19.34-.273.507-.2.583.014.015.037.03.059.026.117 0 .343-.116.588-.305.222-.17.817-.671 1.534-1.674a15.436 15.436 0 0 0 1.459-2.52c.119.044.256.101.318.225.081.147.11.342.081.564-.067.537-.38 1.352-.633 1.94-.428.997-1.213 2.114-1.797 2.876-.023.03-.164.197-.186.226.073.078.396.333.531.446.8.657 1.545 1.163 2.489 1.69.73.41 2.214 1.162 3.198 1.426.984-.264 2.469-1.017 3.2-1.425a17.216 17.216 0 0 0 3.017-2.134c-.686-.859-1.495-1.995-1.983-3.105-.252-.59-.566-1.405-.632-1.94-.029-.221-.001-.418.08-.565.035-.1.276-.216.32-.225.434.929.89 1.727 1.458 2.52.72 1.005 1.313 1.507 1.534 1.675.25.192.47.305.589.305a.07.07 0 0 0 .044-.013c.095-.069.018-.233-.183-.594a8.92 8.92 0 0 1-.79-1.822c-.13-.456-.18-.705-.184-.92-.004-.245.09-.466.25-.593l.15-.12c.458.982 1.145 1.845 1.858 2.577a15.644 15.644 0 0 0 1.616-3.19c.346-.922.586-1.783.711-3.222.074-.858.128-1.81.019-2.946-.1-1.117-.404-2.264-.814-3.068-.248-.49-.606-1.112-1.175-1.566a3.284 3.284 0 0 0-1.053-.541 3.09 3.09 0 0 0-.942-.143h-.047c-.414.006-1.188.105-1.708.71a1.135 1.135 0 0 0-.226 1.023c.126.404.35.607.786.687-.04.078-.137.214-.137.214-.15.268-.688.643-1.739.613-.58-.038-1.06-.19-1.623-.915-.349-.451-.526-1.208-.552-2.452-.021-.625-.107-1.166-.256-1.6-.242-.61-.624-.858-1.256-1.078C11.905.014 11.41.003 11 0z"/></svg>
> ```
> 
> barclays

Cheers, much appreciated! Let's see what @PeterShaggyNoble says.

**Comment by PeterShaggyNoble** [comment]
Did you base your version off the SVG or PDF, @fbernhart? I'm noticing some (very) minor differences at the bottom of both outer wing feathers (see below, with your version in red) and much less pronounced one in the top curve of the right wing and the tip of the beak.

**Comment by fbernhart** [comment]
@PeterShaggyNoble Did you want to mention @adamrusted instead of me? 😄

**Comment by PeterShaggyNoble** [comment]
... Maybe! 🙈

**Comment by adamrusted** [comment]
@PeterShaggyNoble I used the embedded SVG found [here](https://home.barclays/) in the header. Will try regenerating, see if I get the same issue.

**Comment by PeterShaggyNoble** [comment]
I think given that your first attempt lined up better with the cleaner version in the PDF we should run with that, @adamrusted and try to fix it up to line up exactly. I also found [another potential source](https://www.investmentbank.barclays.com/content/dam/barclaysmicrosites/ibpublic/Images/New_Home_Page/barclays_eagle.svg) in the header of [this site](https://www.investmentbank.barclays.com/) (after scrolling down) which, at first glance, looks to be much better than the one sourced from their main site.

They do have a [brand site](https://brand.barclays/) but, sadly, it requires an account to access.

**Comment by adamrusted** [comment]
@PeterShaggyNoble - the below passes the linter at 3 decimals, and _looks_ to match the new source perfectly.
Would you mind taking a look before @EM-Creations puts the work into editing the PR?

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Barclays icon</title><path d="M21.043 3.629a3.235 3.235 0 0 0-1.048-.54c-.318-.1-.65-.15-.983-.143-.413.005-1.184.104-1.701.708a1.138 1.138 0 0 0-.226 1.024c.128.405.348.606.783.688-.308.521-.61.806-1.867.826-.578-.038-1.056-.189-1.616-.915-.347-.45-.523-1.207-.549-2.452-.022-.624-.107-1.165-.256-1.6-.1-.29-.333-.596-.557-.742a2.55 2.55 0 0 0-.694-.336c-.373-.12-.848-.14-1.204-.146-.462-.01-.717.096-.878.292-.027.033-.032.05-.068.046a3.666 3.666 0 0 0-1.05.084c-.47.1-.76.295-1.018.503-.12.095-.347.365-.399.653a.76.76 0 0 0 .097.578c.14-.148.374-.264.816-.266.493-.002 1.169.224 1.406.608.336.547.27.99.199 1.517-.183 1.347-.68 2.048-1.783 2.203-.894.147-1.986-.072-2.278-.844.333-.086.68-.362.757-.717.09-.353.004-.728-.23-1.007-.415-.47-.991-.708-1.713-.708-.4 0-.755.076-.982.14-.908.256-1.633.947-2.214 2.112-.412.824-.7 1.912-.81 3.067-.11 1.13-.056 2.085.019 2.949.124 1.437.363 2.298.708 3.22a15.68 15.68 0 0 0 1.609 3.19c.7-.715 1.413-1.628 1.848-2.575.238.16.41.38.399.711-.003.215-.053.464-.184.922a8.703 8.703 0 0 1-.784 1.818c-.189.341-.27.508-.198.584.014.015.037.03.059.026.116 0 .34-.117.585-.304.222-.17.813-.672 1.527-1.675a15.456 15.456 0 0 0 1.452-2.521c.12.045.255.101.318.226.08.146.108.34.08.563-.066.539-.38 1.352-.63 1.94-.49 1.113-1.288 2.25-1.975 3.104C7.607 22.003 9.645 23.226 12 24c2.354-.773 4.39-1.994 6.187-3.558-.68-.86-1.488-1.994-1.972-3.105-.252-.59-.564-1.405-.63-1.94-.027-.221 0-.417.08-.565.034-.099.275-.217.318-.226.405.884.887 1.73 1.452 2.522.715 1.003 1.306 1.506 1.527 1.674.277.198.47.335.63.292.094-.068.017-.234-.183-.594a9.005 9.005 0 0 1-.786-1.822c-.13-.456-.18-.705-.182-.92-.011-.332.159-.553.399-.712.453.981 1.139 1.844 1.848 2.576a15.658 15.658 0 0 0 1.609-3.19c.344-.922.583-1.783.707-3.221.075-.86.128-1.81.02-2.947-.101-1.117-.404-2.264-.81-3.068-.249-.49-.605-1.113-1.171-1.567z"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
That looks much better, @adamrusted 🙂 The only real difference I'm seeing when comparing to the new source is at the very bottom. All the other ones are very minor and result from cleaning up imperfections in the original so I'm happy for us to run with them.

(Your version in red)

**Comment by adamrusted** [comment]
Again, I'm just _too_ severe with the `Simplify Path` button!
This should match up pretty well now. Gone back round the source SVG comparing as I went.

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Barclays icon</title><path d="M21.043 3.629a3.235 3.235 0 0 0-1.048-.54 3.076 3.076 0 0 0-.937-.144h-.046c-.413.006-1.184.105-1.701.71a1.138 1.138 0 0 0-.226 1.023.9.9 0 0 0 .555.63s.088.032.228.058c-.04.078-.136.214-.136.214-.179.265-.576.612-1.668.612h-.063c-.578-.038-1.056-.189-1.616-.915-.347-.45-.523-1.207-.549-2.452-.022-.624-.107-1.165-.256-1.6-.1-.29-.333-.596-.557-.742a2.55 2.55 0 0 0-.694-.336c-.373-.12-.848-.14-1.204-.146-.462-.01-.717.096-.878.292-.027.033-.032.05-.068.046-.084-.006-.272-.006-.328-.006-.264 0-.498.043-.721.09-.47.1-.761.295-1.019.503-.12.095-.347.365-.399.653a.76.76 0 0 0 .097.578c.14-.148.374-.264.816-.266.493-.002 1.169.224 1.406.608.336.547.27.99.199 1.517-.183 1.347-.68 2.048-1.783 2.203-.191.026-.38.04-.56.04-.776 0-1.34-.248-1.63-.716a.71.71 0 0 1-.088-.168s.087-.021.163-.056c.294-.14.514-.344.594-.661.09-.353.004-.728-.23-1.007-.415-.47-.991-.708-1.713-.708-.4 0-.755.076-.982.14-.908.256-1.633.947-2.214 2.112-.412.824-.7 1.912-.81 3.067-.11 1.13-.056 2.085.019 2.949.124 1.437.363 2.298.708 3.22a15.68 15.68 0 0 0 1.609 3.19c.09-.094.15-.161.308-.318.188-.19.724-.893.876-1.11.19-.27.51-.779.664-1.147l.15.119c.16.127.252.348.249.592-.003.215-.053.464-.184.922a8.703 8.703 0 0 1-.784 1.818c-.189.341-.27.508-.199.584.015.015.038.03.06.026.116 0 .34-.117.585-.304.222-.17.813-.672 1.527-1.675a15.449 15.449 0 0 0 1.452-2.521c.12.046.255.101.317.226a.92.92 0 0 1 .08.563c-.065.539-.379 1.353-.63 1.94-.425.998-1.208 2.115-1.788 2.877-.022.03-.163.197-.186.227.9.792 1.944 1.555 3.007 2.136.725.408 2.203 1.162 3.183 1.424.98-.262 2.458-1.016 3.184-1.424a17.063 17.063 0 0 0 3.003-2.134c-.05-.076-.13-.158-.183-.23-.582-.763-1.365-1.881-1.79-2.875-.25-.59-.563-1.405-.628-1.94-.028-.221-.002-.417.08-.565.033-.098.274-.218.317-.226.405.884.887 1.73 1.452 2.522.715 1.003 1.306 1.506 1.527 1.674.248.191.467.304.586.304a.07.07 0 0 0 .044-.012c.094-.069.017-.234-.183-.594a9.003 9.003 0 0 1-.786-1.822c-.13-.456-.18-.706-.182-.92-.004-.246.088-.466.248-.594l.15-.118c.155.373.5.919.665 1.147.15.216.685.919.876 1.11.156.158.22.222.308.32a15.672 15.672 0 0 0 1.609-3.19c.343-.923.583-1.784.707-3.222.075-.86.128-1.81.02-2.948-.101-1.116-.404-2.264-.81-3.068-.249-.49-.605-1.112-1.171-1.566z"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
That looks good to me now so let's run with it.

**Comment by adamrusted** [comment]
@EM-Creations would you mind updating the SVG to the one at https://github.com/simple-icons/simple-icons/pull/5031#issuecomment-786692094, and the source to the webpage @PeterShaggyNoble found at https://github.com/simple-icons/simple-icons/pull/5031#issuecomment-785774593? 🙏

**Comment by EM-Creations** [comment]
> @EM-Creations would you mind updating the SVG to the one at https://github.com/simple-icons/simple-icons/pull/5031#issuecomment-786692094, and the source to the webpage @PeterShaggyNoble found at https://github.com/simple-icons/simple-icons/pull/5031#issuecomment-785774593? 🙏

Yep will probably get it done tomorrow. Thanks for all the help.

**Comment by EM-Creations** [comment]
New version commited, preview image on the PR updated.

**Review by mondeja — APPROVED** [review]
Looks spot on to me, I think that we can go with the merge :tada:
Thank you everybody for the good work!

**Pull request merged**
