### PR TITLE
Add Crehana (#1865)

### LINKED ISSUE #1865: Crehana
**Name: Crehana**
**Website: https://www.crehana.com/mx/**

### PR DESCRIPTION
**Pull request by runxel**
**Issue:**
Closes  #1865

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This one is quite discussable...
On their website they are not really using their logo (except as a loading icon and favicon of course).
However, they do appear in their [apps](https://apps.apple.com/us/app/crehana/id1353031284).
The logo is super easy, so it was not hard to recreate. Still: this leaves no real trace of a source. At the moment I just put there the website. My spanish is bad, but usable. Still didn't found any kind of press kit.
The color is also debatable. In the app they have the small mint rectangle and the blue/purple background. This `#4B22F4` is also used to big extents on their website, so I used that.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
`#4b22f4` is also the colour used in their [iPhone app](https://apps.apple.com/us/app/crehana/id1353031284) so I'd agree with that choice, although they use `#4c21f5` for their [Android app](https://play.google.com/store/apps/details?id=com.crehana.android)

**Comment by phatbhoy67** [comment]
I would expect the icon to be:
crehana

This is used as the favicon, Instagram and Twitter logo.

I think the hex value is correct, and is mentioned in their (https://www.crehana.com/manifest.json)

I had a look at this a while back and managed to find an .svg, but can't remember where from 🤣 👇 
[Comunidad en línea para creadores _ Crehana-41.zip](https://github.com/simple-icons/simple-icons/files/3958369/Comunidad.en.linea.para.creadores._.Crehana-41.zip)

**Comment by runxel** [comment]
> I would expect the icon to be:

Sooo... with the circle? Meaning the stylized "H" would be stenciled out (both white and mint part).
Will do tomorrow :)
Thanks for the suggestion, @phatbhoy67!

**Comment by runxel** [comment]
@phatbhoy67 updated the logo with the source you provided :)

**Comment by PeterShaggyNoble** [comment]
I think, in the absence of a definitive source, defaulting to their website is the right way to go. Unless @phatbhoy67 can remember where he found that zip!

**Comment by birjolaxew** [comment]
:+1: Thanks a lot for your work on this @runxel!

**Pull request merged**
