### PR TITLE
Publish 14 new icons, 1 updated icon, and 1 package update

### PR DESCRIPTION
**Pull request by ericcornelissen**
:warning: The release will not be fully backwards compatible due to the remove of the "Adobe Lightroom" icon from the NPM package, the icon has been renamed to "Adobe Lightroom Classic" :warning:

---

## New icons
- OCaml (#1469)
- Crunchyroll (#1468)
- Prettier (#1454)
- Elsevier (#1448)
- SpaceX (#1314)
- Cirrus CI (#1478)
- Pantheon (#1484)
- Ansible (#1483)
- Canva (#1487)
- Google Cloud (#1491, #1501)
- Babel (#1493)
- Epic Games (#1492)
- IntelliJ IDEA (#1497)
- Kodi (#1494, 7704018878db9359c1fc7b72a8b090b7c913c4b2)

## Updated icons
- Visual Studio Code (#1470)

## Others
- `<path>` data as separate property in NPM package (#1472)

### CODE REVIEW

**Comment by rembik** [comment]
Would you release a build on npmjs and deliver the icons by CDNs? :)

**Comment by ericcornelissen** [comment]
> Would you release a build on npmjs and deliver the icons by CDNs? :)

Once this gets merged into master, the CI build will automatically publish a new release to NPM. The CDNs should automatically have the updated NPM version available as soon as possible.

Does that answer your question @rembik ?

**Comment by rembik** [comment]
Of course I only wondered, because it looks already merged for me. But it's assumed that it's not so. Sorry then.

**Comment by birjolaxew** [comment]
@rembik The update is now published, and should be out on both NPM and CDNs that track it.

**Pull request merged**
