### PR TITLE
Add Lamborghini

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Lamborghini

**Issue:** #2059

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Colour from [their media centre](https://media.lamborghini.com/)'s stylesheet. Still not fully convinced it's the right choice, though.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks, @runxel - PR updated.

**Comment by runxel** [comment]
Am I... slowly descend to being insane?
Illustrator still says its height would be 24.001 px.... 😨

**Comment by PeterShaggyNoble** [comment]
Weird 😕 It's `24px` when I open it in Inkscape. Anyone else experiencing the same issue as, @runxel?

**Comment by runxel** [comment]
Okay, _maybe_ (I didn't tested that), but maybe SVGO changed it. Otherwise: since I run it on a higher precision than the base svg this shouldn't be case.
(SVGO'd because... you know. Illustrator is some dumb software... :P)

**Comment by runxel** [comment]
Okay, then go ahead 😅

**Comment by ericcornelissen** [comment]
Thanks for adding this one @PeterShaggyNoble :smile:

**Pull request merged**
