### PR TITLE
Update Dacia

### LINKED ISSUE #5987: Update Dacia
**Brand Name:** Dacia
**Official resources for icon and color:** SVG embedded in [website](https://www.dacia.ro/) header. Colour: `#646b52`, from stylesheet

Dacia have just [announced](https://en.media.dacia.com/news/dacia-new-visual-identity-503e-989c5.html) and rolled out a rebrand and, from that press release, it looks like we should just be able to use the "DC" emblem. What do others think?

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
Dacia

**Issue:** Resolves #5987
**Alexa rank:** [~285k](https://www.alexa.com/siteinfo/dacia.ro)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Colour from [website](https://www.dacia.ro/) stylesheet.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thinking about this some more, seeing as Dacia don't plan to start using the emblem on vehicles until next year, should we run with the full wordmark for now for the sake of recognisability and then update to the emblem in January, or whenever they release their first new model next year?

**Comment by PeterShaggyNoble** [comment]
If it is decided that we should run with the full wordmark for now then the path for that is below and the source will need to be updated to https://www.dacia.ro/ as it's the logo from the header. As usual, I'm not online over the weekend so if someone is reviewing this for Sunday's release, feel free to push the changes directly to my branch.

```
M16.948 13.308h1.024v-2.616h-1.024zm-5.153-2.475l-1.046 1.06c-.037.04-.057.072-.057.107 0 .034.02.066.057.106l1.045 1.06c.11.11.185.142.346.142h3.443v-.885h-3.178l-.45-.423.45-.424h3.178v-.884H12.14c-.161 0-.236.032-.345.141zm-8.007 2.334l1.045-1.06c.038-.04.058-.072.058-.107s-.02-.066-.058-.107l-1.045-1.06c-.109-.11-.184-.141-.345-.141H0v.884h3.178l.45.424-.45.424H0v.884h3.443c.161 0 .236-.032.345-.141zm18.881.141H24l-2.51-2.556c-.04-.04-.072-.06-.106-.06s-.066.02-.106.06l-2.51 2.556h1.32l1.287-1.325 1.294 1.325zm-13.65 0h1.332l-2.51-2.556c-.04-.04-.072-.06-.106-.06-.035 0-.066.02-.106.06l-2.51 2.556h1.32l1.287-1.325 1.294 1.325Z
```

**Comment by fbernhart** [comment]
I don't have any strong opinion on whether to use the full wordmark or just the emblem. But if I would have to choose, I'd probably go with the emblem. As we've as well chosen the logo of other brands over their full wordmarks, where possible.

Concerning reviewing the icon:
LGTM 👍🏼  So if nobody else has an objection, I'd merge it.

**Comment by ericcornelissen** [comment]
I'd personally say we wait with the update until they start putting it on vehicles, but if a majority thinks we can already upgrade now I'm fine with that as well. I don't think it makes sense to update to the _new_ wordmark before that though, and I do think using the new logo is better than using the new wordmark.

**Comment by PeterShaggyNoble** [comment]
Coming back to this a couple of weeks later, I can see the point that updating it now before it has started to be used on vehicles might make it less recognisable but, as they've rolled it out everywhere else, I think that that should increase the recognisability of it somewhat so would be OK with updating to the "DC" version now. What do the other @simple-icons/maintainers think?

**Comment by adamrusted** [comment]
Hey @simple-icons/icon-review - the DC emblem is now being used on vehicles, see Dacia's website for a few examples. I'll get this PR up to spec with `develop`, and if we're happy with it - can we merge it down?

**Comment by service-paradis** [comment]
> Hey @simple-icons/icon-review - the DC emblem is now being used on vehicles, see Dacia's website for a few examples. I'll get this PR up to spec with `develop`, and if we're happy with it - can we merge it down?

Did not review the icon myself, but if it is fine, I'm ok to merge this one now!

**Review by adamrusted — APPROVED** [review]
Fab, will merge as logo matches perfectly to the Wikimedia source.

**Pull request merged**
