### PR TITLE
Add BigBlueButton

### LINKED ISSUE #3990: Request: BigBlueButton Icon
**Name:** BigBlueButton
**Website:** https://bigbluebutton.org/
**Alexa rank:** 14,391
  

**Official resources for icon and color:** https://bigbluebutton.org/

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
BigBlueButton

**Issue:** Closes #3990
**Alexa rank:** [~19.9k](https://www.alexa.com/siteinfo/bigbluebutton.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
For the colour, I went with the most dominant one in the gradient but I'm open to suggestions on alternatives.

### CODE REVIEW

**Comment by service-paradis** [comment]
Labeling as `pending` waiting for #4629

**Comment by adamrusted** [comment]
No longer pending, following the inclusion of the `DISCLAIMER.md`.

**Review by adamrusted — APPROVED** [review]
The icon matches up perfectly, and given we now have a `DISCLAIMER` I'd be happy for this to be merged. Will ping other @simple-icons/maintainers for a second opinion though.

**Review by ericcornelissen — APPROVED** [review]
SVG looks perfect, metadata looks good, and I agree DISCLAIMER.md covers this one. Nice work @PeterShaggyNoble 👌

**Pull request merged**
