### PR TITLE
Updated GoldenLine

### PR DESCRIPTION
**Pull request by fbernhart**
goldenline

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by adamrusted** [comment]
Looks like GoldenLine has [updated their icon](https://www.goldenline.pl/). Any chance you could take another look at this one?

**Review by adamrusted — CHANGES_REQUESTED** [review]
Looks like GoldenLine has [updated their icon](https://www.goldenline.pl/). Any chance you could take another look at this one?

**Comment by fbernhart** [comment]
@adamrusted Done. I've as well changed the color to `#FFE005`, which they use in their new logo.

**Review by adamrusted — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
