### PR TITLE
Update Render icon

### LINKED ISSUE #11085: Update: Render
### Brand Name

Render

### Official Resources for Icon and Color

https://dka575ofm4ao0.cloudfront.net/pages-favicon_logos/original/89884/favicon-dark-633ba9a9-4b6f-413d-a316-b1dc3ed9c7bb.png

Above icon downloaded from [Render website](https://render.com/) header. Couldn't find an SVG from header.

### Additional Comments

_No response_

### PR DESCRIPTION
**Pull request by adamrusted**
image

**Issue:** closes #11085

**Popularity metric:** [25,237](https://www.similarweb.com/website/render.com/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

SVG from site header, picked black as the hex as site is black and white, with a preference on socials for the icon to be in black.

### CODE REVIEW

**Comment by adamrusted** [comment]
@uncenter has found [this page](https://render.com/terms) which states:

> Except for your User Content, the Service and all materials therein or transferred thereby, including, without limitation, software, images, text, graphics, illustrations, logos, patents, trademarks, service marks, copyrights, photographs, audio, videos, music, and User Content belonging to other Users (the “Render Content”), and all Intellectual Property Rights related thereto, are the exclusive property of Render and its licensors (including other Users who post User Content to the Service). Except as explicitly provided herein, nothing in this Agreement shall be deemed to create a license in or under any such Intellectual Property Rights, and you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works from any Render Content. Use of the Render Content for any purpose not expressly permitted by this Agreement is strictly prohibited.

I'm interpreting this, then, as meaning we cannot include Render without permission. I'll reach out to them and see what they have to say.

**Comment by adamrusted** [comment]
Hey @anurag - just wanted to check in regarding the ToS for Render. Is our interpretation in https://github.com/simple-icons/simple-icons/pull/11130#issuecomment-2157645604 correct? We can look to remove as of our next major release (November) if so - but wanted to check in before we take any action.

**Comment by anurag** [comment]
Adding @joshklekamp (who leads Design at Render). The new logo looks good, and you have Render's explicit permission to use it in the icon pack.

**Comment by adamrusted** [comment]
Thanks @anurag! We'll await confirmation from @joshklekamp prior to merging, but great to know you're happy with us including Render!

**Pull request merged**
