### PR TITLE
Add backendless logo

### LINKED ISSUE #5605: Backendless Logo
**Brand Name:** Backendless
**Website:** https://www.backendless.com
**Alexa rank:** #101,075

**Official resources for icon and color:**
image
image
image

### PR DESCRIPTION
**Pull request by anmol5varma**
backendless

**Issue:** Fixes #5605
**Alexa rank:** [115,466](https://www.alexa.com/siteinfo/backendless.com)

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Comment by adamrusted** [comment]
Thanks for resubmitting this one @anmol5varma - though it looks like the icon is aligned to the top of the canvas. Could you please re-align the icon in the center of the canvas, and push the changes to this PR, as opposed to creating a new one? 🙏

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @anmol5varma. However the linting is now failing on the following points:
```
x icons/backendless.svg
  x attr-1 0:0 Expected attribute 'role', didn't find it
                 At node <svg> (0:0)
  x icon-size Size of <path> must be exactly 24 in one dimension; the size is c
              urrently 22.992 x 12.001
  x ineffective-segments Innefective segment "m0 0" found at index 854 (should 
                         be removed)
  x extraneous Unexpected character(s), most likely extraneous whitespace, dete
               cted in SVG markup
  x icon-centered <path> must be centered at (12, 12); the center is currently 
                  (12, 11.375)
```

**Comment by service-paradis** [comment]
Just a note... I'm wondering if we could get away with the icon only without wordmark. Or we could use the vertical layout as they use for their social network:
image

**Comment by PeterShaggyNoble** [comment]
OK, I've definitely gone cross-eyed from too much reviewing today, @service-paradis - I _completely_ missed that! 😆

@anmol5varma, as was discussed in #5708, could you update this PR to use just the symbol, without the wordmark, please?

**Comment by service-paradis** [comment]
Closing this one as abandoned for now since no changes were made in a long time. Please feel free to make the requested changes and reopen this PR if you're still interested to contribute

**Pull request closed without merging**
