### PR TITLE
Add OSGeo icon

### LINKED ISSUE #8463: Request: OSGeo
### Brand Name

OSGeo

### Website

https://www.osgeo.org/

### Popularity Metric

The OSGeo rank is 355,173. See [https://www.similarweb.com/website/osgeo.org/](https://www.similarweb.com/website/osgeo.org/)

### Official Resources for Icon and Color

svg: [https://www.osgeo.org/wp-content/themes/roots/assets/img/logo-osgeo.svg](https://www.osgeo.org/wp-content/themes/roots/assets/img/logo-osgeo.svg)
color: `#5CAE58`, from the website header

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by geoyee**
osgeo

**Issue:** closes #8463 

**Similarweb rank:**
  
Global Rank is [355,173](https://www.similarweb.com/website/osgeo.org/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- This color is the primary color for their website. See [https://www.osgeo.org/resources/](https://www.osgeo.org/resources/)
- I simplified the official SVG using Illustrator.

### CODE REVIEW

**Comment by LitoMore** [comment]
CleanShot 2023-04-05 at 12 42 18@2x

Hi @geoyee, could you point out which one you used as reference?

I used their logo on homepage header as reference but found some differences.

**Comment by geoyee** [comment]
> CleanShot 2023-04-05 at 12 42 18@2x
> 
> Hi @geoyee, could you point out which one you used as reference?
> 
> I used their logo on homepage header as reference but found some differences.

i am sorry, i will commit a new logo about original this. because i fix it.

**Comment by geoyee** [comment]
@LitoMore done~ thank you

**Review by LitoMore — APPROVED** [review]
CleanShot 2023-04-05 at 22 04 30@2x

@geoyee Looks good now. Thank you for your contributions!

**Pull request merged**
