### PR TITLE
Update ManageIQ

### PR DESCRIPTION
**Pull request by mondeja**
image

**Issue:** #4590
**Alexa rank:** [~360k](https://www.alexa.com/siteinfo/manageiq.org)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Rebuilt from source and removed next collinear coordinate:

image

- Defined license following [legal page of ManageIQ](https://www.manageiq.org/legal/).

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks, @mondeja. However, that seems to have added [a distortion to the inner circle](https://user-images.githubusercontent.com/15157491/110006235-4fb35180-7d11-11eb-90e8-13dd9707004f.png) that isn't present in our original.

Also, my reading of the their legal page is that that license applies to their content only, which may not necessarily include their logos and icons. I think, in the interests of not adding this under an incorrect license we should remove it from the JSON for now and reach out to them for clarification.

**Comment by mondeja** [comment]
I've given it another try, it should be fine now :crossed_fingers:

**Comment by PeterShaggyNoble** [comment]
The cut-out has gone missing on that latest version, @mondeja.

**Comment by mondeja** [comment]
Ups, sorry for the mess :sweat_smile: I've restored the gap and removed some useless coordinates.

**Comment by PeterShaggyNoble** [comment]
Thanks, @mondeja. Looks like that's introduced [some differences](https://user-images.githubusercontent.com/15157491/110311226-643a6700-7ffb-11eb-8a05-9adfb1e83a75.png) (your version in red) in the upper part of the cut-out as well as along the inner circle of the "Q", though, when comparing to [this file](https://www.manageiq.org/assets/images/logo/manageiq-logo-bw.svg).

**Comment by adamrusted** [comment]
Coming back to this one, I've got the below path optimized to 3 decimals that _appears_ to match up to the source path. @PeterShaggyNoble would you mind having a quick look, and if it _does_ match up, we can merge that path in and get this off @mondeja's list!

**Comment by PeterShaggyNoble** [comment]
Looks good to me, @adamrusted 👍🏻 Although there are a couple of points at the top of the "Q" and the top corner of the rectangle that you may be able to remove.

**Comment by adamrusted** [comment]
@PeterShaggyNoble - I've just pushed my updated SVG with the changes you requested. Going to try and work through a few of these to get them off @mondeja's list.

**Review by PeterShaggyNoble — APPROVED** [review]
Looks good to me, @adamrusted 👍🏻 There's a duplicate point on the our left curve but I couldn't do anything to resolve it either so let's run with it. Thanks to you & @mondeja for your work on this one.

**Comment by mondeja** [comment]
Sorry for not being able to apply the suggestions, I'm a little busy lately. Thanks for finishing the icon update :+1:

**Pull request merged**
