### PR TITLE
Add Premier League

### LINKED ISSUE #3364: icon request premier league
**Name:**
Premier League
**Website:**
https://fantasy.premierleague.com/#/
**Alexa rank:**
1,502
https://www.alexa.com/siteinfo/premierleague.com

**Official resources for icon and color:**
SVG file attached below. I'm sorry this is the best I could I find, as I dont work for them.
[epl-icon.zip](https://github.com/simple-icons/simple-icons/files/4988970/epl-icon.zip)

### PR DESCRIPTION
**Pull request by fbernhart**
premierleague

**Issue:** Closes #3364
**Alexa rank:** [555](https://www.alexa.com/siteinfo/premierleague.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Embedded in the header of https://www.premierleague.com.
Color: `#360D3A`, embedded in the SVG.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Sorry, @fbernhart, didn't realise you'd already started work on this before I posted [this comment](https://github.com/simple-icons/simple-icons/issues/3364#issuecomment-759366118).

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @fbernhart! 💯
Will hold fire on this until tomorrow, just in case another @simple-icons/maintainers still objects to this one being added.

**Comment by adamrusted** [comment]
Any objections from @simple-icons/maintainers about this one being merged?

**Review by adamrusted — APPROVED** [review]
Merging as no objections 👍🏻

**Pull request merged**
