### PR TITLE
Add Argos icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** #6476 
**Alexa rank:** 5,229
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

see issue

### CODE REVIEW

**Review by sachinraja — CHANGES_REQUESTED** [review]
I think this should be based off the smaller icon (from the footer):
image

**Comment by dirien** [comment]
@sachinraja, tbh I only now the Argos logo with the swoosh/smile! I would never think the A with swoosh/smile is Argos?

**Comment by sachinraja** [comment]
Do you mean you only see the icon currently implemented in this PR used everywhere? If so then we can move forward with that

**Comment by dirien** [comment]
@sachinraja: Yes.

**Review by sachinraja — APPROVED** [review]

**Pull request merged**
