### PR TITLE
adding Hetzner logo as full name

### PR DESCRIPTION
**Pull request by jorgeamadosoria**
hetzner

**Issue:** https://github.com/simple-icons/simple-icons/issues/6145

Following the official logo information in https://www.hetzner.com/newsroom, I believe the logo is supposed to contain the full name of the company.
Smaller size does not read very easily however.

### CODE REVIEW

**Comment by dirien** [comment]
Hi @jorgeamadosoria cool you pick it up again. 

Just sharing my opnion: For me a logo != icon. I wish Hetzner had some great icon on their own. Simple H did not cut it for @ericcornelissen and me.

**Comment by jorgeamadosoria** [comment]
> Hi @jorgeamadosoria cool you pick it up again.
> 
> Just sharing my opnion: For me a logo != icon. I wish Hetzner had some great icon on their own. Simple H did not cut it for @ericcornelissen and me.

 I agree that a logo is not an icon. And regarding the discussion in your previous PR, I would have accepted the H in Hetzner's font as good enough, but that's just my opinion.
I'm providing another option to add Hetzner since the H was not accepted, that's all. If it were to be accepted, I would be happy closing this one. I'm not a fan of logos that are just the name of the company. It strikes me as lazy.

**Comment by ericcornelissen** [comment]
To clarify a few things:

- "_For me a logo != icon_", "_I'm not a fan of logos that are just the name of the company. It strikes me as lazy._":

  I agree! But it's not about what we think, it's about what the company wants. If they want you to use a "logo" (full wordmark in this case) rather than an icon than this project will include the "logo". If you don't like it, than you should ask the company to change.


- "_since the H was not accepted_":

  I did not outright reject #6146, I simply asked whether it makes sense to include the square around the H. Please understand that the maintainers of this project cannot be familiar with all brands being asked for/contributed - we need your input on what makes sense if there are no clear guidelines from the company in question. I would be more than happy to accept #6146 provided there is an example of them using just the H. So, before I review this Pull Request, what do you (@jorgeamadosoria & @dirien) think is best?

**Comment by jorgeamadosoria** [comment]
> The favicon is a white "H" inside of a red square, not just an "H" by itself. Other than that, I wasn't able to find any use of the favicon as a logo (website and social media all seem to use the full wordmark). If you can provide an example of just a "H" anywhere I'd be happy to go with that, else I would indeed prefer the "H" inside a square (provided you agree), and as a last resort we can just add the full wordmark (now and possibly change it later).

I' ok with the H in a red square.
Like you said, you can always come back to this PR and add the whole wordmark.
@dirien I think if you can find an example of the H only other than the favicon, we can all agree to go with your PR as soon as you add the square!

**Comment by dirien** [comment]
Hi @jorgeamadosoria and @ericcornelissen 

On thwitter they use the red background and white H 

https://twitter.com/hetznercloud

image

Not even the cool H with their own font.

**Comment by ericcornelissen** [comment]
Not sure which Twitter account you found @dirien but [the Twitter account linked from their website](https://twitter.com/Hetzner_Online) uses the wordmark as their profile picture

image

**Comment by dirien** [comment]
Ya, it looks like its an account only for their cloud product, and on their pinned tweet they redirect the account you showed.

**Comment by dirien** [comment]
I asked for help, from Hetzner.
image

Curious if they reacted. With Equnix Metal it was very good, as they provided me with the final right icon svg.

**Comment by dirien** [comment]
So the good folks of hetzner replied, and will have look into it :)

**Comment by dirien** [comment]
update time @jorgeamadosoria and @ericcornelissen 
98F2A3E0-EF1C-438F-8144-1CADBB6A9F6D

i think that’s good feedback!

**Comment by jorgeamadosoria** [comment]
> update time @jorgeamadosoria and @ericcornelissen
> 98F2A3E0-EF1C-438F-8144-1CADBB6A9F6D
> 
> i think that’s good feedback!

excellent! H in a square like the fav icon, that's all we need it. 
I think I can close this PR in favor of the original one by @dirien then.
Good news!

**Comment by ericcornelissen** [comment]
#6146 still needs some work though as it does not include the square yet.

**Comment by dirien** [comment]
@ericcornelissen, i can add the square. How thick should be the line of the square? And should there be a margin with the corners?

**Pull request closed without merging**
