### PR TITLE
Added Exercism icon

### PR DESCRIPTION
**Pull request by JoaoPedroMoraes**
**Issue:** #1465 

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
From the official SVG I was able to create a monocolor version. https://exercism.io/

### CODE REVIEW

**Comment by davidklebanoff** [comment]
@JoaoPedroMoraes - Can you elaborate on where you got the official SVG from?

**Comment by JoaoPedroMoraes** [comment]
> @JoaoPedroMoraes - Você pode explicar de onde você tirou o SVG oficial?

I've vectored the official logo that's in PNG
https://assets.exercism.io/social/general.png

**Comment by birjolaxew** [comment]
Hmm. This one is a bit weird, mostly because Exercism themselves are inconsistent in which logo they use.

There seem to be two variants: the symmetric one (e.g. [social/general.png](https://assets.exercism.io/social/general.png) or [logo-white.png](https://github.com/exercism/website/blob/master/app/assets/images/logo-white.png)) and the asymmetric one (e.g. [icon.png](https://github.com/exercism/website/blob/master/app/assets/images/icon.png) and [logo.png](https://github.com/exercism/website/blob/master/app/assets/images/logo.png)). On the asymmetric one the ends of the curly brackets are only rounded on one side, with the two curly brackets being rounded differently, and the sizing is slightly different.

<p align="center"></p>

I can only find the symmetric version on exercism.io, so I think that's the one we want. Thoughts @davidklebanoff @ericcornelissen ?

As for the manual vectorization, that fits pretty well. Good work on it @JoaoPedroMoraes!

<p align="center"></p>

**Comment by ericcornelissen** [comment]
I agree the symmetric version is a better option. Perhaps @kytrinyx (creator of Exercism) can way in to give an opinion?

And indeed, great job at the vectorization @JoaoPedroMoraes!

**Comment by kytrinyx** [comment]
Oh, very cool! Let me ask Let me ask our design folks.

**Comment by nicolechalmers** [comment]
Nice work @JoaoPedroMoraes :) The symmetric logo is the one we should using. 

Thanks for pointing out the two variants @birjolaxew I'll standardise it everywhere when I get the chance.

**Comment by JoaoPedroMoraes** [comment]
> Nice work @JoaoPedroMoraes :) The symmetric logo is the one we should using.
> I've uploaded the SVG files [here](https://github.com/exercism/website-icons/tree/master/exercism).
> 
> Thanks for pointing out the two variants @birjolaxew I'll standardise it everywhere when I get the chance.

@davidklebanoff @birjolaxew  I update the pr with that logo?

**Comment by ericcornelissen** [comment]
> I update the pull request with that logo?

That would be ideal @JoaoPedroMoraes, it's unfortunate the manual vectorization turned out to be unnecessary but an official SVG is better 😅

**Comment by JoaoPedroMoraes** [comment]
> > I update the pull request with that logo?
> 
> That would be ideal @JoaoPedroMoraes, it's unfortunate the manual vectorization turned out to be unnecessary but an official SVG is better

No problem, update made :+1:

**Comment by ericcornelissen** [comment]
Thanks for the work @JoaoPedroMoraes and thanks for the input @nicolechalmers 👍

**Comment by ravanscafi** [comment]
Thanks everyone, awesome work!

**Pull request merged**
