### PR TITLE
Add Yubico icon

### LINKED ISSUE #5990: Icon Request - Yubico
**Brand Name:** Yubico
**Website:** https://www.yubico.com/
**Alexa rank:** 30,520 https://www.alexa.com/siteinfo/yubico.com

Yubico is a company that manufactures security keys, (namely YubiKeys); NFC enabled USB hardware for 2-factor/multi-factor passwordless authentication via FIDO Alliance standards. 
  
**Official resources for icon and color:**

`#84BD00`

Here is their main logo: 

yubico_logo

Had trouble finding a good quality image for their icon, but managed to snag a link of the SVG used for their site:

yubico_icon

The icon is widely used on the actual products, and may be more recognized.

### PR DESCRIPTION
**Pull request by zyw271828**
image

**Issue:** closes #5990

**Pull request:** closes #6082

**Similarweb rank:** [41,463](https://www.similarweb.com/website/yubico.com/)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

* I took the SVG from [here](https://www.yubico.com/wp-content/themes/coronado/img/icon.svg)
* I used Inkscape to resize viewbox, resize icon and align
* I used the SVGO command line tool to optimize
* I compared with the original SVG
* I picked the color #84BD00 from the original SVG

### CODE REVIEW

**Comment by sachinraja** [comment]
Where did you find that SVG on their website? I think we should use the full wordmark here based on https://brandguide.brandfolder.com/yubico/logo

**Comment by zyw271828** [comment]
> Where did you find that SVG on their website? I think we should use the full wordmark here based on https://brandguide.brandfolder.com/yubico/logo

I found this SVG by searching `icon.svg` in the source of Yubico official website (view-source:https://www.yubico.com). The original issue requesting this icon also used the same SVG.

This circular logo is widely used in Yubico's products and is still recognizable enough on small screens compared to the full wordmark version.

Should I open a new pull request for the full wordmark version?

**Comment by dirien** [comment]
I would like the y only too! It's on the devices too
image

**Comment by sachinraja** [comment]
> Should I open a new pull request for the full wordmark version?

No just the Y is fine, based on both your comments.

**Pull request merged**
