### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by weswhite**
**Issue:**
#1292

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
  - Why did you pick the hex value?
Hex value came off the original svg file

source: https://github.com/remojansen/logo.ts/blob/master/ts.svg

### CODE REVIEW

**Comment by weswhite** [comment]
I think the other commits came when i created a branch off my develop. But the files are correct

**Comment by ericcornelissen** [comment]
> I think the other commits came when i created a branch off my develop. But the files are correct

That is what I tried to explain over in #1290 :sweat_smile: I appreciate that you want to contribute but I urge to you to take it slow and make sure you understand the contribution process before you continue. That will make contributing in the future (not just to simple icons but other projects as well) a lot more smooth :slightly_smiling_face:

**Comment by weswhite** [comment]
I get it from here on out. You can close this one if you dont want it

**Comment by ericcornelissen** [comment]
Pull Requests like this get a little messy to work with so if you don't mind I would like to ask you to open a new one :slightly_smiling_face:

**Comment by weswhite** [comment]
I am out of time on this stuff. Feel free to take the file if you want it. I will not be able to make another commit though.

**Comment by metaa** [comment]
I see no issues with the files themselves. If the long PR really is the only problem here, then just squash-commit? 🤔

Otherwise I'll just revive this in a new PR and adopt the files.

**Comment by ericcornelissen** [comment]
I think the SVG in this PR is optimized a bit too much and you can notice a difference quite easily (don't have the tools to give a preview on this machine unfortunately). But feel free to fix it in a new PR @metaa, contributions are always welcome :smiley: 

If that was not the case you where right in this scenario (where the author isn't planning to contribute in the future, otherwise I like to encourage contributors to learn a bit about git/GitHub), I just didn't review the PR :sweat_smile:

**Comment by weswhite** [comment]
¯\_(ツ)_/¯ file looked good to me

**Pull request closed without merging**
