### PR TITLE
Add Airbrake.io Icon

### LINKED ISSUE #8765: Icon request: Airbrake
### Brand Name

Airbrake

### Official Resources for Icon and Color

https://d2taz10zyxzbmo.cloudfront.net/assets/images/favicon-safari-pinned-tab.svg
https://d2taz10zyxzbmo.cloudfront.net/assets/images/favicon-192x192.png

color: probably `#DA8A1E`

### Additional Comments

I found http://itolmach.github.io/logo-guidelines/index.html but it doesn't match the logo and colors from https://www.airbrake.io/ so it's probably an old one.

### Contributing

Yes

### PR DESCRIPTION
**Pull request by RiteshK-611**
**Issue:** closes #8765

**Similarweb rank:**
Similarweb Rank [310,669](https://www.similarweb.com/website/airbrake.io/#overview) 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This commit resolves issue #8765 by adding Airbrake.io logo in airbrakedotio.svg file and by updating simepl-icons.json file with icon's data

### Preview
airbrakedotio

### CODE REVIEW

**Review by adamrusted — CHANGES_REQUESTED** [review]
The source used is not an official one, if we can't find one owned by Airbrake.io, we should vectorise our own version of the icon based on the rasters available.

**Comment by RiteshK-611** [comment]
> The source used is not an official one, if we can't find one owned by Airbrake.io, we should vectorise our own version of the icon based on the rasters available.

Hey @adamrusted I found one in their github

**Review by adamrusted — CHANGES_REQUESTED** [review]
Based on the SVG you found, I'm spotting [some minor differences](https://github.com/simple-icons/simple-icons/assets/1830867/6cebf20e-0356-4756-b329-29aa1ecea147) here, would you mind taking another look?

**Review by adamrusted — APPROVED** [review]
LGTM! Thanks @RiteshK-611 🎉

**Pull request merged**
