### PR TITLE
Updated Haskell

### PR DESCRIPTION
**Pull request by fbernhart**
haskell

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Review by service-paradis — APPROVED** [review]
LGTM 💯 
Is the precision of 4 is necessary?
Since they use a SVG file in the header of their [official website](https://www.haskell.org/), should we change the source for it? What do you think?

**Comment by fbernhart** [comment]
@service-paradis I've fixed the precision. 😊

I think we should keep the source as it is. What if they upload a new logo to their website `haskell-logo-new.svg` and we're still having `haskell-logo.svg` as source? 🤔 Maybe we won't even realise the logo change. What do you think?

**Review by service-paradis — APPROVED** [review]
Perfect, thank you 💯 
Though it might be better to use the official website as source instead of Wikimedia, but I'm ok with it 😄

**Comment by PeterShaggyNoble** [comment]
@service-paradis, the SVG on Wikimedia is lifted directly from [this page](https://wiki.haskell.org/Thompson-Wheeler_logo) but there's also an SVG in the header of their [website homepage](https://www.haskell.org/).

**Pull request merged**
