### PR TITLE
Add Hono icon

### PR DESCRIPTION
**Pull request by ryuapp**
image

**Similarweb rank:** [454,247](https://www.similarweb.com/website/hono.dev/#overview)
**GitHub Stars**: [9,273](https://github.com/honojs/hono)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Hono is a web framework for the Edges. It works on any JavaScript runtime.

`#FF612B` is defined by @yusukebe(creator of Hono) on Discord community.
This icon is made manually based on https://github.com/honojs/hono.

### CODE REVIEW

**Comment by adamrusted** [comment]
We do have an SVG available at https://github.com/honojs/hono/blob/76dbc74407329c46870af6aa4fab0c04036d8ae2/docs/images/hono-logo.svg. Should probably use this URL as our source.

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
Thanks for the contribution, @ryuapp, but I'm noticing some differences when comparing with the source SVG Adam linked above - here's [an example](https://github.com/simple-icons/simple-icons/assets/15157491/c51d53cc-8fab-42fb-b6f9-caf7e80f9206), with your version in black. Would you mind having another look at this, please?

Also, the website's stylesheet variables refer to `#E36002` as `--vp-c-brand-1`, so I think that's the colour we should run with here.

**Comment by ryuapp** [comment]
@PeterShaggyNoble
Thanks for reviewing. I fixed it.
I learned to convert multiple paths into one single path.

I confirmed the color(`#FF612B`) with author of Hono by Discord.
`#E36002` was one of the candidates, but he selected `#FF612B`.
If there are any rules in this repo, I'll follow them.

**Comment by PeterShaggyNoble** [comment]
> I confirmed the color(`#FF612B`) with author of Hono by Discord.
> If there are any rules in this repo, I'll follow them.

One of our most important rules is that feedback from official sources overrules all other rules! 😆 So, `#FF612B` is therefore the correct choice here.

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
I'm still seeing [a small difference](https://github.com/simple-icons/simple-icons/assets/15157491/e867a71f-44df-477c-82ec-21a4b3aab031) down the right edge, @ryuapp - it looks like an additional point was introduced in the top corner somewhere along the way that might be causing the issue.

**Comment by ryuapp** [comment]
@PeterShaggyNoble 
Thank you to update source URL.
I fixed the icon.
I focused to centering and resizing and double check for any difference.

**Review by PeterShaggyNoble — APPROVED** [review]
Looks perfect to me now, @ryuapp 👍🏻 Nice work.

**Pull request merged**
