### PR TITLE
Added Adobe Xd icon #1245

### PR DESCRIPTION
**Pull request by nexus0212**
**Issue: #1245**

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Color was choosen from the offical Adobe Xd logo [1].

---
1. https://cdn.worldvectorlogo.com/logos/adobe-xd.svg

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Hi @nexus0212 it looks like you're having some trouble with the `_data/simple-icons.json` file? It seems that the editor you've used to update it automatically changed the indentation 🤔 may I ask what editor you're using so that I can help you fix it? (1)

That said the SVG you added is perfect, good job 👍 

---

<sup>1. Alternatively I can push a commit that fixes it for you</sup>

**Comment by nexus0212** [comment]
Hi @ericcornelissen I understand the problem with the file. As fast as I can I will fix it.

**Comment by ericcornelissen** [comment]
> Hi @ericcornelissen I understand the problem with the file. As fast as I can I will fix it.

Great 👌 The same goes for #1355 and #1356 but I think you already realized that. If you need any help don't hesitate to ask 😄

**Comment by ericcornelissen** [comment]
Great, thanks for fixing that.

Not sure why Travis CI is not running 🤔 But can you _compound the paths_ so that the resulting SVG has only a single `<path>`? If you need help let me know, or I could do it for you (we are currently in the process of making it easy to do this).

If you want to get more details you can also run `npm run svglint` (after running `npm install`) from the project directory 😉

**Comment by ericcornelissen** [comment]
Any updates @nexus0212, why did you close the Pull Request?

**Comment by nexus0212** [comment]
Seriously? I closed the Pull Request? Sorry @ericcornelissen , I didn't know. I'm still learning git. I recieved the notification that Pull Request was successful. I thought that you merged the branches and closed the pull request. 

I want to reopen this pull request, but my button `Reopen and comment` is disabled. @ericcornelissen Is it possible to reopen this pull request, or I will have to prepare second pull request?

**Comment by nexus0212** [comment]
@ericcornelissen I was able to open the pull request, and now I will be fixing SVG problems 😉

**Comment by ericcornelissen** [comment]
> Seriously? I closed the Pull Request? Sorry @ericcornelissen , I didn't know.

Not a problem @nexus0212 😉 


> I'm still learning git.

Okay, good to know. If you have any questions regarding git or GitHub also don't hesitate to ask. Protip, when the PR is merged it will turn purple and say "Merged" as you can see [in this merged Pull Request](https://github.com/simple-icons/simple-icons/pull/1347).


> I was able to open the pull request, and now I will be fixing SVG problems 😉

Great, looking forward to it!

**Comment by nexus0212** [comment]
I fixed all bugs 💃. @ericcornelissen, I will be grateful to check that everything is okey.

**Comment by nexus0212** [comment]
image

Of course I use Adobe Xd. I just wanted to adatp to other Adobe icons in project. On screenshot is the official icon (rounded borders). There is no problem for me to replace this icon. 😁

---

image

If we are talking about Lightroom icon, there are two version of this aplication. One version is the Lightroom Classic with no rounded corners. The newer Lightroom CC version has rounded corners. But there are two separated application. So if I change the Adobe Xd icon, it would be better to add a new Adobe Lightroom CC icon.

**Comment by ericcornelissen** [comment]
> Of course I use Adobe Xd. I just wanted to adatp to other Adobe icons in project. On screenshot is the official icon (rounded borders). There is no problem for me to replace this icon. 😁

Since that seems to be the official logo I think we should go what that. It's not our probably that Adobe is using seemingly inconsistent icons.


> If we are talking about Lightroom icon, there are two version of this aplication. One version is the Lightroom Classic with no rounded corners. The newer Lightroom CC version has rounded corners. But there are two separated application. So if I change the Adobe Xd icon, it would be better to add a new Adobe Lightroom CC icon.

Damn that is confusing 😅 I guess we can leave it for now. If you feel like improving it you can rename the current one and add the new one as well.

**Comment by nexus0212** [comment]
> Since that seems to be the official logo I think we should go what that. It's not our problem that Adobe is using seemingly inconsistent icons.

Okey, so I will change the icon.

> Damn that is confusing 😅 I guess we can leave it for now. If you feel like improving it you can rename the current one and add the new one as well.

As fast as I can, I will rename Adobe Lightroom into Adobe Lightroom Classic. I will also add new issue about adding Adobe Lightroom CC icon 😀

**Comment by ericcornelissen** [comment]
Sounds good, thanks @nexus0212  👍

**Comment by nexus0212** [comment]
> Looking at [Adobe's product page](https://www.adobe.com/products/catalog.html) (and [this one](https://www.adobe.com/products/xd.html) as well) it actually seems the logo should have rounded corners 🤔 The same goes for [Adobe Lightroom](https://simpleicons.org/?q=adobe%20lightroom).

Now the Adobe XD icon is the same like as the official icon 😁✨

**Comment by ericcornelissen** [comment]
Nice 🙂 Can you update the source as well? I would suggest `https://www.adobe.com/products/xd.html` where you can find an SVG of the logo in the header 🤔

**Comment by nexus0212** [comment]
> Nice 🙂 Can you update the source as well? I would suggest `https://www.adobe.com/products/xd.html`

- [x] Change URL

---
>where you can find an SVG of the logo in the header 🤔

I found this icon in `.adobe-icon-color-xd-experience-design-mobile:before` css class. It is encoded in base64, but if you paste it to the chrome search bar, you will get the preview of this icon.

**Comment by ericcornelissen** [comment]
Thanks for your work on this @nexus0212 😃 It took some back and forth but it's all good now.

**Pull request merged**
