### PR TITLE
Asahi Linux

### LINKED ISSUE #10158: Request: Asahi Linux
### Brand Name

Asahi Linux

### Website

https://asahilinux.org/

### Popularity Metric

Similarweb: 473,633
GitHub: https://github.com/AsahiLinux (m1n1 - 3.2k, linux - 2k, other repos)

### Official Resources for Icon and Color

Brand guide: https://github.com/AsahiLinux/artwork/tree/main/logos

### Additional Comments

This is a Linux distro so the popularity metrics are not very indicative of its value.

- Available in many variants (with/without text; color/monochrome)
- ©️ 2021 soundflora* and Hector Martin
- Licensed under CC BY-SA 4.0

### PR DESCRIPTION
**Pull request by durgeshgowdac**
image

**Issue:** closes #10158

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### CODE REVIEW

**Review by PeterShaggyNoble — CHANGES_REQUESTED** [review]
Thanks for the contribution, @durgeshgowdac 👍🏻 However, I'm seeing some significant differences between your version (in red below) and the source file (in black) - would you mind having another go at this, please?

Also, for GitHub `source`s, we use the latest commit URL which, in this case, would be https://github.com/AsahiLinux/artwork/blob/292637c9658c1491ddc1128fb6134aec01d904dd/logos/svg/AsahiLinux_logomark_mono.svg

**Comment by durgeshgowdac** [comment]
I've changed the source to https://github.com/AsahiLinux/artwork/blob/292637c9658c1491ddc1128fb6134aec01d904dd/logos/svg/AsahiLinux_logomark_mono.svg

**Comment by PeterShaggyNoble** [comment]
Thanks, @durgeshgowdac. When you've updated the SVG then please re-request a review from me and I'll have a look over it.

**Review by PeterShaggyNoble — APPROVED** [review]
SVG looks perfect now, @durgeshgowdac - nice work.

**Pull request merged**
