### PR TITLE
Add E.Leclerc icon

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

image

**Issue:** # #6386 
**Alexa rank:** 21,639
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
From their website and https://www.e.leclerc/assets/images/sue-logo.svg as base.

Color: #0066CC

### CODE REVIEW

**Comment by dirien** [comment]
Hi @service-paradis and @ericcornelissen, 

any idea how to handle a dot in the brand name?

**Comment by jorgeamadosoria** [comment]
> Hi @service-paradis and @ericcornelissen,
> 
> any idea how to handle a dot in the brand name?



> Hi @service-paradis and @ericcornelissen,
> 
> any idea how to handle a dot in the brand name?

I think the idea is to substitute the . for "dot".
In this case, the title (or slug) would be "edotleclerc".

**Comment by jorgeamadosoria** [comment]
> @jorgeamadosoria, thanks a lot for the help.

that's what we are here for. One for me, one for you :)

**Comment by jorgeamadosoria** [comment]
Reviewing the icon against your source (after taking out the letters and uniting the paths) I see slight divergences:
image

In my previous experience, this is due to precision issues in svgo.

**Comment by jorgeamadosoria** [comment]
This path is precision 4, and I find it coincides with your source rather well.
Can you please try it on your side, see if it works?

`M12.0006 0C5.4304 0 .104 5.373.104 12.0006.1041 18.628 5.4304 24 12.0006 24c6.57 0 11.8953-5.372 11.8953-11.9994C23.8959 5.373 18.5705 0 12.0006 0zm0 2.491c5.2064 0 9.4266 4.2576 9.4266 9.5096 0 5.2518-4.2202 9.5085-9.4266 9.5085-5.2065 0-9.4278-4.2567-9.4278-9.5085 0-5.252 4.2213-9.5097 9.4278-9.5097zm1.1477 1.9912c-1.4425 0-2.7735.4696-3.8562 1.266h3.1929V8.982c-.556.0284-1.0156.4782-1.0156 1.0436v5.4499h.9442c1.2058 0 1.5093-1.4532 1.5093-1.4532h2.836l.001 2.5939c1.7738-1.1835 2.9437-3.215 2.9437-5.5212 0-3.6525-2.9346-6.6128-6.5554-6.6128zM6.49 6.7322v1.6204c.5462.1418 1.018.6113 1.018 1.3817v5.4592c0 .6162-.4365 1.1693-1.018 1.315v2.0943h9.3003V15.004l-1.2344.007c-.348.8466-1.1771 1.4415-2.1422 1.4415h-1.913V9.691c0-.6981.4543-1.1824 1.0156-1.335V6.7322z`

**Comment by service-paradis** [comment]
> > Hi @service-paradis and @ericcornelissen,
> > any idea how to handle a dot in the brand name?
> 
> I think the idea is to substitute the . for "dot".
> In this case, the name of the SVG (or slug) would be "edotleclerc".
> I think the relevant guideline is this one: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#6-name-the-icon

Good answer by @jorgeamadosoria! There is also another thing we can take into account. Do we pronounce the "dot" when we talk about the brand? For example, we say "dot net" when talking about ".Net", but not "del dot icio dot us" when talking about "del.icio.us". For the latter, we use a "slug" so we name the file `delicious.svg` instead of `deldoticiodotus.svg`.

**Comment by jorgeamadosoria** [comment]
> > @jorgeamadosoria, thanks for the new svg.
> > image
> 
I've checked the second SVG @dirien, and it's a 100% match from my side.

**Pull request merged**
