### PR TITLE
Add Fly.io icon

### LINKED ISSUE #8180: Request: Fly.io
### Brand Name

Fly.io

### Website

https://fly.io/

### Popularity Metric

The fly.io rank is 62,338. See https://www.similarweb.com/pt/website/fly.io/

### Official Resources for Icon and Color

svg: https://fly.io/static/images/brand/brandmark.svg
color: `#7c3aed`, from the website header icons

### Additional Comments

_No response_

### Contributing

Yes

### PR DESCRIPTION
**Pull request by LitoMore**
image

**Issue:** closes #8180

**Popularity metric:** Similar web global rank - 65,383

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

The color was picked from the brand guideline page.

### CODE REVIEW

**Comment by adamrusted** [comment]
Given this is a custom interpretation of their logo, and the fact that [this page](https://fly.io/docs/about/brand/#trademark-usage-agreement) requires permission from the brand, we'll need you to reach out to Fly for permission please @LitoMore 🙏

**Comment by enstyled** [comment]
FYI the Fly.io team is aware of this PR and we are having a conversation about it. Thank you for this contribution 🙏🏼

**Review by adamrusted — COMMENTED** [review]
Icon is a perfect match to the source, but I'm _hoping_ there is opportunity to remove some of these excess points... Paging @PeterShaggyNoble!

**Comment by LitoMore** [comment]
I used the Inkscape built-in feature to simplify the path. It should be fine now.

**Comment by adamrusted** [comment]
@LitoMore - I don't think you committed changes? I'm still seeing the previous version.

**Comment by LitoMore** [comment]
@adamrusted Haha, my bad. Committed this time.

**Review by adamrusted — CHANGES_REQUESTED** [review]
This auto-optimisation seems to have introduced some discrepancies - see below with your PR in black.

image
image

Might need to be a bit more selective on what exactly gets optimised in order to get closer to the source icon.

**Comment by uncenter** [comment]
I've found that the Inkscape simplify tool is pretty terrible at losslessly (or near losslessly) simplifying nodes. I'd avoid it and remove them by hand.

**Comment by LitoMore** [comment]
Can you guys help on this? Feel free to commit some on my PR. Thanks.

**Comment by adamrusted** [comment]
If @uncenter doesn't beat me to it - I'll have a look in Illustrator this evening.

**Comment by uncenter** [comment]
Feel free to do it @adamrusted - pretty busy this weekend and I'm not the greatest at removing nodes either 😅

**Comment by adamrusted** [comment]
> I will research to see if we can implement the paper.js simplify function in our workflow.

Important to note this should always be an optional script for people struggling. Most vector tooling allows for _some_ level of simplification - and the moment we add a tool to the package, people will become reliant on it.

**Comment by LitoMore** [comment]
I found the threshold of the Inkscape simplication can be adjusted.

image

Let me try some new values.

**Comment by LitoMore** [comment]
I think these differences should be fine. We can just ask the them for an approval on the asset.

The original control points looks not on a perfect bezier curve. So these differences are bound to occur.

**Comment by LitoMore** [comment]
I am merging according the approval from the Fly.io team: https://github.com/superfly/docs/issues/1540#issuecomment-2312493984.

**Pull request merged**
