### PR TITLE
Lemmy

### PR DESCRIPTION
**Pull request by adsingh14**
**Issue:** #6735
**Alexa rank:** 1,190,206
  
**GitHub Stars**: Approx. 5.5k (Over 5000)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

lemmy

### CODE REVIEW

**Review by adsingh14 — COMMENTED** [review]
@joaopedromoraez Please have a look at this PR.

**Comment by jorgeamadosoria** [comment]
This is what I get:
image

This may be either precision issues or maybe Because this SVG has to be transformed before comparison and it may affect the result.

Either way, can you give it a shot?

**Comment by adsingh14** [comment]
@jorgeamadosoria Can you please share the reference logo link ?

**Comment by jorgeamadosoria** [comment]
in the home page, the navbar logo:
https://join-lemmy.org/static/assets/images/lemmy.svg

This is the source as defined in simple-icons.json, I assume.

**Comment by adsingh14** [comment]
> in the home page, the navbar logo:
> https://join-lemmy.org/static/assets/images/lemmy.svg
> 
> This is the source as defined in simple-icons.json, I assume.

I've updated the logo.

**Comment by jorgeamadosoria** [comment]
> > in the home page, the navbar logo:
> > https://join-lemmy.org/static/assets/images/lemmy.svg
> > This is the source as defined in simple-icons.json, I assume.
> 
> I've updated the logo.

I see slight discrepancies in a few places.
Can you tell me what transformations you used on the source?
Depending on the actions, it may be acceptable the way it is or not

**Review by adsingh14 — COMMENTED** [review]
Icon precision value : 4

**Pull request merged**
