### PR TITLE
Update Eventbrite

### PR DESCRIPTION
**Pull request by atomicjeep**
#1055

### Checklist
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Taken from inline SVG at  https://www.eventbrite.com/signin/

### CODE REVIEW

**Comment by birjolaxew** [comment]
I'm getting `#F05537` from the SVG on the signin page - is the color in this PR taken from somewhere else?

**Comment by atomicjeep** [comment]
that's the colour in the SVG

`<svg width="100" height="98" viewBox="0 0 100 98" xmlns="http://www.w3.org/2000/svg" data-reactid="96"> <g id="Artboard-Copy" fill="none" fill-rule="evenodd"> <g id="mike-logo/white" transform="translate(0 -3)" fill="#F25439"> <g id="logo/new" transform="translate(.406)"> <path d="M43.647 26.401c10.985-2.481 21.946 2.016 28.049 10.52L23.149 47.89c1.676-10.263 9.513-19.008 20.498-21.489zm28.32 40.35c-3.67 5.322-9.33 9.35-16.227 10.908-11.057 2.498-22.09-2.076-28.17-10.69l48.7-11.002 7.931-1.792 15.165-3.426a47.9 47.9 0 0 0-1.263-9.656C91.93 14.931 65.252-1.382 38.517 4.658 11.782 10.698-4.888 36.804 1.284 62.967c6.173 26.162 32.85 42.475 59.585 36.435 15.754-3.559 28.008-14.085 34.157-27.484l-23.059-5.167z" id="Fill-13"></path> </g> </g> </g> </svg>`

**Comment by birjolaxew** [comment]
It's actually being overwritten in CSS on their site:

```css
.eds-vector-image--ui-orange svg circle,.eds-vector-image--ui-orange svg path {
    fill: #F05537 !important
}
```

I have no idea why they do it that way, but the actual color being shown is `#F05537`

**Comment by birjolaxew** [comment]
:+1: Looks good! Thanks for grabbing this one so quickly @atomicjeep !

**Pull request merged**
