### PR TITLE
Add Apache Lucene icon

### PR DESCRIPTION
**Pull request by MateuxLucax**
Screenshot 2024-10-14 at 21 43 19

**Issue:** N/A

**Popularity metric:**

Although its popularity is not huge, due to its nature of being an Apache-backed project and the foundation for large databases like Solr, Elasticsearch (and its forks), it is certainly a relevant package.

We can still reference the number of stars on its GitHub page: https://github.com/apache/lucene

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

N/A

### CODE REVIEW

**Comment by LitoMore** [comment]
@MateuxLucax Thank you for your first-time contribution to Simple Icons. Can you fix those linting errors? Those errors are reported here: https://github.com/simple-icons/simple-icons/actions/runs/11337281002/job/31563727598?pr=12012

**Comment by uncenter** [comment]
You'll need to both horizontally and vertically align the path. In Inkscape this can be done through Object > Align and Distribute; set the "Relative to:" to Page, click the icons for "Center on vertical axis"  and "Center on horizontal axis".

**Comment by MateuxLucax** [comment]
Finally I've managed to align this using Figma. I've tried with Inkscape but I guess I am still a bit rough from not using that tool for I guess +5 years.

Here are the screenshots of the (now working) tests:

| `npm run test` | `npm run lint` |
|-|--|
|Screenshot 2024-10-15 at 22 25 32 | Screenshot 2024-10-15 at 22 25 50 |

**Comment by uncenter** [comment]
No need to take screenshots of the test results. As long as they pass for you, they should pass in our workflows :)

**Comment by LitoMore** [comment]
As far as I remember, the Figma is snap to pixels (integer) by default. You need to turn those settings off.

If you choose to use Inkscape, you can refer to this tutorial: https://github.com/simple-icons/simple-icons/discussions/9351

**Comment by MateuxLucax** [comment]
Wow, that was a long journey, but I think I’ve finally managed to edit the SVG properly with Inkscape 📦.

**Review by LitoMore — CHANGES_REQUESTED** [review]
CleanShot 2024-10-17 at 12 41 07@2x

It looks like your shape has been stretched a bit. 

Here is the size difference:

Your shape:



The original:

**Comment by MateuxLucax** [comment]
> CleanShot 2024-10-17 at 12 41 07@2x
> 
> It looks like your shape has been stretched a bit.
> 
> Here is the size difference:
> 
> Your shape:
> 
> 
> 
> The original:
> 
> 

Now it's 5.171 🦺

**Comment by MateuxLucax** [comment]
@LitoMore Could you please review once again? I think i've managed to solve all issues.

**Review by LitoMore — APPROVED** [review]

**Pull request merged**
