### PR TITLE
Added streamlit icon

### LINKED ISSUE #3575: Request: Streamlit Icon
**Name:** Streamlit
**Website:** https://www.streamlit.io
**Alexa rank:** 140 000

**Official resources for icon and color:** https://www.streamlit.io/brand

### LINKED ISSUE #4368: Streamlit icon missing
**Name:**
Streamlit
**Website:**
https://www.streamlit.io/
**Alexa rank:**
130,572 globally
95,588 US
48,401 India

**Official resources for icon and color:**
  https://www.streamlit.io/brand

### PR DESCRIPTION
**Pull request by rlew631**
Close #3575
Close #4368

**Name:** Streamlit
**Website:** https://www.streamlit.io/
**Official resources for icon and color:** https://www.streamlit.io/brand
**Alexa rank:**
- 130,572 globally
- 95,588 US
- 48,401 India

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Preview:
Preview

### CODE REVIEW

**Comment by fbernhart** [comment]
image

@rlew631 Thanks for your work. Unfortunately your version (blue in the image) doesn't exactly match with the original logo, when I'm overlaying them. It as well has some sharp edges where it should be round.

Can you have another look at it?

**Comment by adamrusted** [comment]
@Amey-D @domoritz @kantuni @mesmith027 - you wouldn't happen to have an SVG/AI file for the logo that could be used, would you?

**Comment by rlew631** [comment]
This one should looks a little better than the last one you looked at @fbernhart 

I never intended to learn how to work with SVGs and they're now the bane of my existence. I'll hopefully be adding some other icons soon. Working with these graphics design tools is pretty weird coming from CAD. It feels wrong not being able to force lines to be parallel, curves to have constant radii instead of splines, define midpoints, perpendicularity etc.

Also happy belated new year!

**Review by adamrusted — APPROVED** [review]
Thanks for your work on this @rlew631 - the icon looks great now! 🎉
SVGs can be a tricky beast, so I'm glad you stuck with this! 😅

**Pull request merged**
