### PR TITLE
Add XAMPP

### PR DESCRIPTION
**Pull request by runxel**
**Issue:** ––

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo is from the website header. Color `#FB7A24` is embedded there.

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
I wonder should this just be the symbol, without the box? What do the @simple-icons/maintainers think?

XAMPP

**Comment by runxel** [comment]
Hm, I never saw this one alone. Just always in a box. But maybe I missed it somewhere. 🤔

**Comment by phatbhoy67** [comment]
I think the PR box version is most appropriate here. 

Can you have a look at the box dimensions @runxel, the original .svg box isn't perfectly square but the PR version is, meaning it doesn't quite match.

**Comment by phatbhoy67** [comment]
[Alexa Rank 8,148](https://www.alexa.com/siteinfo/apachefriends.org)

**Comment by ericcornelissen** [comment]
> I wonder should this just be the symbol, without the box? 

I agree that the version in the PR is more appropriate than [the version by @PeterShaggyNoble](https://github.com/simple-icons/simple-icons/pull/2086#issuecomment-562084165), I have also never seen the logo without the square. Unless, perhaps, you an provide an example of where it is used without the border.


> Can you have a look at the box dimensions @runxel, the original .svg box isn't perfectly square but the PR version is, meaning it doesn't quite match.

Nicely spotted @phatbhoy67 :+1:

**Comment by runxel** [comment]
Updated the icon :)

**Comment by phatbhoy67** [comment]
Hey @runxel thanks for updating, still a little issue with the corners I think, orange v PR black 👇 
xampp-comp

This is what I get when I resize the original .svg 👇 

```xml
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M21.25 0h-9.256C8.917 0 5.84 0 2.764.004c-.22 0-.442.015-.662.039C1.158.14.522.638.23 1.546c-.11.34-.113.702-.113 1.058C.114 8.739.113 14.874.112 21.008c0 .277.01.551.041.827.087.766.49 1.332 1.085 1.786.081.062.175.095.268.135.467.2.967.236 1.458.237 6.043.01 12.086.006 18.129.007.267 0 .527-.066.795-.067.116 0 .235-.04.348-.075.627-.194 1.04-.635 1.342-1.193.272-.502.3-1.06.302-1.612.009-3.942.008-7.885.008-11.827 0-2.165-.004-4.33-.01-6.494 0-.323-.02-.645-.085-.961-.167-.798-.594-1.377-1.4-1.623A3.882 3.882 0 0021.252 0zm-4.844 4.51c2.292-.022 3.99 1.776 4.31 3.446.135.705.112 1.41 0 2.114a7.53 7.53 0 01-.62 2.025c-.067.143-.06.245.026.377.493.765.71 1.605.683 2.517-.058 1.903-1.404 3.61-3.256 4.056-2.585.623-4.567-.923-5.234-2.794-.108-.304-.16-.622-.224-.985-.068.414-.115.79-.264 1.134-.697 1.617-1.884 2.602-3.664 2.8a4.312 4.312 0 01-4.633-3.085c-.212-.73-.19-1.477-.114-2.22a6.333 6.333 0 01.682-2.26c.053-.102.052-.179-.014-.277-.56-.845-.779-1.778-.7-2.784a4.066 4.066 0 01.417-1.535c.715-1.413 2.285-2.612 4.39-2.413 1.848.175 3.561 1.77 3.829 3.565.013.09.038.178.068.31.044-.24.076-.44.117-.635.345-1.63 1.94-3.335 4.2-3.356zm-.027 2.937a1.423 1.423 0 00-1.392 1.426c-.001.064.002.129-.002.193-.054.84-.517 1.3-1.22 1.35-.128.01-.257.021-.385.022-.912.002-1.823.002-2.735 0-.398 0-.793.043-1.172.16-1.77.546-2.802 1.757-3.144 3.56-.068.358-.128.728-.01 1.095.166.526.48.917 1.033 1.048.575.135 1.075-.015 1.472-.466.257-.292.338-.638.357-1.018.05-.978.583-1.468 1.47-1.46 1.364.011 2.726.002 4.09.003.24 0 .243.003.245.243.002.442-.011.884.006 1.325.027.721.66 1.32 1.396 1.341.758.022 1.434-.539 1.483-1.27.043-.634.04-1.272-.001-1.905-.032-.49-.298-.84-.748-1.044-.108-.049-.221-.085-.334-.127.027-.108.11-.173.17-.252.649-.86.99-1.823.914-2.906-.055-.79-.706-1.348-1.493-1.318zm-8.76.077c-.334.02-.645.17-.924.437-.449.428-.509.952-.352 1.524.144.527.485.826 1.02.916.312.053.624.027.883.035.293 0 .532-.003.771 0 .118.003.162-.048.161-.165-.003-.46.02-.92-.01-1.378-.038-.604-.36-1.041-.922-1.261a1.47 1.47 0 00-.627-.108z"/></svg>
```

**Comment by runxel** [comment]
I will have a look at it again.
What I have done here is that I've re-rounded the edges, because if you zoom in you will notice that they are all wonky – to which _I_ always presume that this was _**not**_ intended.

wonky

**Comment by runxel** [comment]
Soooo, I've updated the icon: the radii are now matching to the original (minus the deformed anchors and wonkiness).

**Comment by phatbhoy67** [comment]
I still see none of the corners matching? 🤔 

There is an equally large "wonk" on the bottom left corner of the original un-un-wonked? 😕 

Attached red is original path, black pr.
[xampp-now.zip](https://github.com/simple-icons/simple-icons/files/3947547/xampp-now.zip)

**Comment by runxel** [comment]
What did you expect?
If the red is the orginal from the website than everything looks like I'd expect 🤔 
The black version from the PR is supposed to look different. Sorry if my wording here was clear.
The website version is _already_ the wonked one 😅

**Comment by phatbhoy67** [comment]
> What did you expect?

> The radii are now matching the original

I expected the corners to remain unchanged and to match the original and the small "extra" pieces to be gone? 

They don't match.

The top corner radii have changed and they don't appear to be visually wonky in the original. 

I don't think they should have changed 🤔

**Comment by runxel** [comment]
True, the two on the top have no visual bumps but are still slightly off – and both are _differently_ off.
Heck, the outer rectangle doesn't even have straight edges! :D  
Which must be an error; I think that's safe to assume.

**Comment by ericcornelissen** [comment]
@phatbhoy67 what do you think about the latest version?

**Comment by phatbhoy67** [comment]
Happy to merge it in @ericcornelissen, which I'll do now, thanks for your work on this one @runxel 👍

**Pull request merged**
