### PR TITLE
Add Elixir

### PR DESCRIPTION
**Pull request by runxel**
**Issue:** _none_

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Elixir programming language has only a png logo. So I took that from their github repo and traced it (it's basicely a drop of liquid). Color `#4B275F` is taken from the solid parts of the logo (they have a lot of transparency).

### CODE REVIEW

**Comment by foo-dogsquared** [comment]
The vector lines up quite nicely with the original source so I approve of this PR. 



You know the drill: since this is a manually vectorized, we'll need one more agreeing maintainer to merge this in.

**Comment by PeterShaggyNoble** [comment]
Should the white bit at the bottom of the full colour version be cut out of this?

**Comment by runxel** [comment]
Nah, I think that would look weird 🤔 

> Should the white bit at the bottom of the full colour version be cut out of this?

**Comment by PeterShaggyNoble** [comment]
In that case, this looks good to go to me. Nice work, @runxel 👍

**Pull request merged**
