### PR TITLE
Add SQLite

### LINKED ISSUE #2922: Request: Sqlite icon
**Name:**  SQLite
**Website:**  [SQLite Home Page](https://www.sqlite.org/index.html)
**Official resources for icon and color:**  I couldn't find any official branding guidelines but I think the authors of SQLite will provide all the necessary details. The logo can be found here: [SQLite logo](https://www.sqlite.org/images/sqlite370_banner.gif)

As there are icons for other popular RDBMS-s I think it will be nice to have SQLite logo too

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
SQLite

**Issue:** Closes #2922

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Original treatment:
SQLite

### CODE REVIEW

**Comment by Giorgi** [comment]
Looks nice to me

**Comment by Giorgi** [comment]
In my opinion the filled version looks more beautiful

**Comment by Giorgi** [comment]
@PeterShaggyNoble @ericcornelissen
Can we get this PR merged ? Thanks

**Comment by ericcornelissen** [comment]
Since the filled version seems to be preferred, the Pull Request should be updated by @PeterShaggyNoble first. Either way, the icon won't be released until the next scheduled release next week.

I hope you understand. If you need the SVG urgently, you can grab the source from this PR :wink:

**Comment by Giorgi** [comment]
No, it's not urgent but would be nice to have it merged in time for the next scheduled release

**Comment by ericcornelissen** [comment]
We'll do our best :+1:

**Comment by runxel** [comment]
By the way: if you want to use it in shields.io, please bear in mind that they don't release as fast. It can take up to one month until it's available there.

**Comment by Giorgi** [comment]
Thanks, I didn't know that

**Comment by PeterShaggyNoble** [comment]
Thanks, guys; I've updated with the alternative version.

But I'm also going to ping the @sqlite team for feedback to see if they have:
1. an existing monochrome version we could use, or,
2. a preference between the 2 treatments presented here, or,
3. an alternative suggestion.

**Comment by PeterShaggyNoble** [comment]
Given the lack of reply, and assuming everyone is happy with the treatment, I think we should just merge this one in and update at a later date if we do hear back from the @sqlite team.

**Comment by ericcornelissen** [comment]
Alright, thanks for adding this one @PeterShaggyNoble :ok_hand:

**Pull request merged**
