### PR TITLE
Rename TikTok

### PR DESCRIPTION
**Pull request by PeterShaggyNoble**
**Issue:** n/a

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description
There shouldn't be a space in the name of this one. ~I don't _think_ this constitutes a breaking change - the filename remains `tiktok.svg` - but didn't want to commit directly, just in case.~

It was indeed a breaking change (see comments below) so **do not** merge this until `v3`.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
I'm confident this **is** a breaking change for our NPM and Packagist(?) packages. In Node TikTok can currently be accessed as:

```javascript
simpleIcons.get("Tik Tok");
```

And after the change, I'm fairly certain, this would no longer work. However I'm currently on my phone so I am not 100% confident and can't test...

**Comment by PeterShaggyNoble** [comment]
Ah. Feck! Good thing I *didn't* commit directly, so!

Adding this to the `v3` miletsone.

**Comment by ericcornelissen** [comment]
Tested it now, it does indeed break backwards compatibility so we can make this change in `v3` 👍

**Comment by PeterShaggyNoble** [comment]
In the interests of keeping all these together, this will be addressed in #2942.

**Pull request closed without merging**
