### PR TITLE
Update Stylus

### PR DESCRIPTION
**Pull request by fbernhart**
stylus

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

### CODE REVIEW

**Comment by service-paradis** [comment]
Looks perfect 💯 , but was it necessary to use a precision of 4?

**Comment by fbernhart** [comment]
@service-paradis Probably not.

When I started working on the list in #3169 I saw that about 1/3 of the icons will fail the linter with a precision of 3.

And as a precision of 3-5 is accepted by the linter, I started using 4 as default precision. Because with a higher precision it is less likely that the linter will fail with something like "size is 24.001".

But @mondeja already told me, that that was probably a wrong decision. And that a precision of 4 shouldn't be used as default, but only if a precision of 3 isn't working.

Sorry for that. If you find any other icon with a precision of 4, just let me know and I'll optimize it again with a precision of 3. 😊

**Comment by service-paradis** [comment]
Ok, I understand, no problem at all!

**Comment by mondeja** [comment]
I would like to point out the same, the linter must be used to detect errors, it must not condition the precision of the icons. Since this icon it was optimized to 3 decimal numbers, I would leave it with 3.

**Comment by fbernhart** [comment]
Thanks for the feedback. I guess this can be merged now. 😊

**Review by mondeja — APPROVED** [review]
Looks perfect. Thank you for the fix @fbernhart! :tada:

**Pull request merged**
