### PR TITLE
Add Pokémon icon

### PR DESCRIPTION
**Pull request by KovuTheHusky**
### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
As a companion PR to #2340.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Not a full review but just wanted to say I'm okay (and I think I prefer) the full Pokémon wordmark. That said, the Pokéball is a good alternative (as per [this comment](https://github.com/simple-icons/simple-icons/pull/2340#issuecomment-575706794)) 👍

**Comment by PeterShaggyNoble** [comment]
I'd vote for the Pokeball over the full wordmark as it suits our purposes as an icon library better and is iconic enough on its own.

**Comment by ericcornelissen** [comment]
> I'd vote for the Pokeball over the full wordmark as it suits our purposes as an icon library better and is iconic enough on its own.

Although the Pokéball is a fictional brand, I personally feel like it is separate :thinking: Any input from other @simple-icons/maintainers?

**Comment by runxel** [comment]
I'd prefer the wordmark actually...

**Comment by ericcornelissen** [comment]
> One thing, why did you choose red for the hex value, I would expect it to be blue or yellow?

Good point, I guess red **is** based on the Pokéball :laughing: but indeed yellow or blue are better options if we go with the wordmark. I'm personally in favour of yellow.

**Comment by PeterShaggyNoble** [comment]
As a Pokémon "outsider" (far too old for it!), I'd associate yellow with it, as a brand. That, however, may well be influenced by Pikachu being the most well known character.

**Comment by ericcornelissen** [comment]
It seems there is consensus on yellow so I updated it 👍 

> That, however, may well be influenced by Pikachu being the most well known character.

I don't even think that is a bad reason to choose yellow 🙃

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @KovuTheHusky and thanks to @ericcornelissen for updating the colour 👍

**Pull request merged**
